### ISSUE TITLE
error: invalid logic expression, use '|' instead of 'or'

### ISSUE THREAD

**Issue by ilya-lavrenov** [microsoft/vcpkg#31683] opened 2023-05-28 20:34 UTC
### Operating system

macOS 13

### Compiler

clang

### Steps to reproduce the behavior

I have the following platform syntax, which is mentioned in [documentation](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json#platform-expression):

```Shell
      "platform": "not (arm or uwp)"
```

### Failure logs

```
$.dependencies[7].platform (a platform expression): CONTROL:1:12: error: invalid logic expression, use '|' instead of 'or'
    on expression: not (arm or uwp)
                              ^
$.features.gpu.supports (a platform expression): CONTROL:1:8: error: invalid logic expression, use '|' instead of 'or'
    on expression: (x64 or arm64) and not (osx or uwp) and not static
                          ^internal error: /Users/runner/work/1/s/src/vcpkg/commands.add-version.cpp(412): vcpkg has crashed; no additional details are available.
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.
```

**Comment by LilyWangLL** [comment] 2023-05-29 06:41
Thanks for posting this issue. This is by design, we will update the documentation later.

**Comment by LilyWangLL** [comment] 2023-05-31 02:45
Since this is a documentation issue, now all of documentation issues and PRs have been moved to [vcpkg-docs](https://github.com/microsoft/vcpkg-docs), so I am closing this issue for now. Please pay attention to the progress of PR https://github.com/microsoft/vcpkg-docs/pull/90.

**Closed by LilyWangLL** 2023-05-31 02:45 UTC
Labels: category:documentation

**Comment by dg0yt** [comment] 2023-05-31 05:08
> Since this is a documentation issue, now all of documentation issues and PRs have been moved to [vcpkg-docs](https://github.com/microsoft/vcpkg-docs), so I am closing this issue for now. Please pay attention to the progress of PR [microsoft/vcpkg-docs#90](https://github.com/microsoft/vcpkg-docs/pull/90).

It is not confirmed that this is a documentation issue. The documentation describes a consistent pattern. The implementation lacks `or`. microsoft/vcpkg-docs#90](https://github.com/microsoft/vcpkg-docs/pull/90 proposed to transfer the inconsistent pattern to the documentation.

**Comment by LilyWangLL** [comment] 2023-05-31 06:34
The following codes from https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/platform-expression.cpp.
```
                        // { "and", optional-whitespace, platform-expression-not }
                        // { "or", platform-expression-binary-keyword-second-operand } }
                        // "and" is a synonym of "&", "or" is reserved (but not yet supported) as a synonym of "|"
                        std::string name = match_while(is_identifier_char).to_string();
                        Checks::check_exit(VCPKG_LINE_INFO, !name.empty());

                        if (name == "and")
                        {
                            return ExprKind::op_and;
                        }
                        else if (name == "or")
                        {
                            add_error(msg::format(msgInvalidLogicExpressionUsePipe));
                            return ExprKind::op_invalid;
                        }
```
The error message from this, here has comment **"or" is reserved (but not yet supported) as a synonym of "|"**. So `or` can not be used in `supports` now, the documentation is incorrect.

**Comment by dg0yt** [comment] 2023-05-31 06:48
Please give a good reason why `or` should remain reserved but not (yet) supported.

**Comment by LilyWangLL** [comment] 2023-05-31 08:06
This change from PR https://github.com/microsoft/vcpkg-tool/pull/267. cc author @markle11m.
cc @dan-shaw
