### ISSUE TITLE
[GRPC] x64-windows-static does not build grpc++_reflection.lib

### ISSUE THREAD

**Issue by Sand2Silicon** [microsoft/vcpkg#21514] opened 2021-11-18 15:13 UTC
**Problem Description** 
When GRPC **x64-windows-static** is installed from VCPkg, it does not build several libraries that are built under the default `x64-windows` configuration including: `grpc++_reflection.lib`, `grpcpp_channelz.lib`

Release and debug copies of these exist on my system in the non-static build:
`C:\local\vcpkg\installed\x64-windows\lib\`
but **not** in the static build:
`C:\local\vcpkg\installed\x64-windows-static\lib\`

Subsequently, when CMake is invoked with the flag `-DVCPKG_TARGET_TRIPLET=x64-windows-static` on a project that uses GRPC++_Reflection, including on the included RouteGuide example project, CMake fails with error (below). 

- Comparing the two folders I see several missing libraries but not sure what other GRPC functionality might be impacted. 
- Also `x86-windows` - someone reported this in April in an unanswered Stackoverflow. [Does grpc++_reflection library come with vcpkg install grpc for x86-windows?](https://stackoverflow.com/questions/67054872/does-grpc-reflection-library-come-with-vcpkg-install-grpc-for-x86-windows)
- [edit] Looks like the similar x86 issue was addressed here: https://github.com/microsoft/vcpkg/issues/17247 but they don't mention 'static' configurations.

**Host Environment**
- OS: Windows 10 Pro
- Compiler: MSVC 19.28.29337.0

**To Reproduce**
First:
```
vcpkg install grpc:x64-windows-static
vcpkg install protobuf protobuf:x64-windows-static
vcpkg install --recurse protobuf[zlib] protobuf[zlib]:x64-windows-static
vcpkg integrate install
```
Next: Build example project and watch failure
```
cd vcpkg\buildtrees\grpc\src\2180080eb4-87c05d756b.clean\examples\cpp\route_guide
cmake -DCMAKE_TOOLCHAIN_FILE=C:/local/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static .
```

Optional Step:
I tried before and after adding this to the top of the RouteGuide project's CMakeLists.txt, replacing the exising `cmake_minimum_required` line. 
```
# CMAKE_MSVC_RUNTIME_LIBRARY flag requires CMAKE >= v3.15
cmake_minimum_required(VERSION 3.15)
cmake_policy(SET CMP0091 NEW)
set(CMAKE_MSVC_RUNTIME_LIBRARY "MultiThreaded$<$<CONFIG:Debug>:Debug>")
```

**Failure logs** 
Repeated many times: 
```
CMake Error at C:/local/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)
```
(full console output attached)
[grpc++_reflection_not_found.txt](https://github.com/microsoft/vcpkg/files/7563634/grpc%2B%2B_reflection_not_found.txt)

**Additional context**
We're building a new GRPC client app to consume the libraries we develop and want to build everything fully statically-linked and `/MT`. 

```
> vcpkg list
abseil:x64-windows                                 20210324.2#1     an open-source collection designed to augment th...
abseil:x64-windows-static                          20210324.2#1     an open-source collection designed to augment th...
c-ares:x64-windows                                 1.17.2#1         A C library for asynchronous DNS requests
c-ares:x64-windows-static                          1.17.2#1         A C library for asynchronous DNS requests
grpc:x64-windows                                   1.41.0           An RPC library and framework
grpc:x64-windows-static                            1.41.0           An RPC library and framework
grpc[codegen]:x64-windows                                           Build code generator machinery
openssl:x64-windows                                1.1.1l#3         OpenSSL is an open source project that provides ...
openssl:x64-windows-static                         1.1.1l#3         OpenSSL is an open source project that provides ...
protobuf:x64-windows                               3.18.0           Protocol Buffers - Google's data interchange format
protobuf:x64-windows-static                        3.18.0           Protocol Buffers - Google's data interchange format
protobuf:x86-windows                               3.18.0           Protocol Buffers - Google's data interchange format
protobuf[zlib]:x64-windows-static                                   ZLib based features like Gzip streams
protobuf[zlib]:x86-windows                                          ZLib based features like Gzip streams
re2:x64-windows                                    2021-11-01       RE2 is a fast, safe, thread-friendly alternative...
re2:x64-windows-static                             2021-11-01       RE2 is a fast, safe, thread-friendly alternative...
upb:x64-windows                                    2021-10-19       μpb (often written 'upb') is a small protobuf i...
upb:x64-windows-static                             2021-10-19       μpb (often written 'upb') is a small protobuf i...
vcpkg-cmake-config:x64-windows                     2021-11-01
vcpkg-cmake:x64-windows                            2021-09-13
zlib:x64-windows                                   1.2.11#13        A compression library
zlib:x64-windows-static                            1.2.11#13        A compression library
zlib:x86-windows                                   1.2.11#13        A compression library
```

**Comment by JackBoosY** [comment] 2021-11-19 09:08
Marked as port bug temporary.

**Comment by yusuke-kadowaki** [comment] 2021-11-24 07:58
A workaround that might work is to add ```codegen``` option. (see https://github.com/microsoft/vcpkg/pull/17276#issuecomment-824171269)

This behavior could originates in the condition in the ports/grpc/portfile.cmake
```
if(NOT TARGET_TRIPLET STREQUAL HOST_TRIPLET)
```
If this condition is true, codegen feature turns off. And when TARGET_TRIPLET = x64-windows-static, this seems to be true (I have not checked).

**Comment by Sand2Silicon** [comment] 2021-12-15 18:05
> A workaround that might work is to add codegen option. (see #17276 (comment))

This is correct. The final syntax I believe I used is: 
vcpkg install --recurse grpc[codegen]:x64-windows-static

However this requires:
1) Knowing the bracket-syntax "[FOO]" denotes a "feature", which can be listed as a parameter to 'vcpkg install'. 
2) Knowing that GRPC Reflection is related to "CODEGEN" 

Neither of these are obvious if you are using GRPC and by extension VCPKG both for the first time.

> This behavior could originates in the condition in the ports/grpc/portfile.cmake
> 
> if(NOT TARGET_TRIPLET STREQUAL HOST_TRIPLET)
> If this condition is true, codegen feature turns off. And when TARGET_TRIPLET = x64-windows-static, this seems to be true (I have not checked).

I came to the same conclusion during my investigation, but this was my first look at VCPKG so I'm not 100% certain. 

As a new user, in changing the triplet once I determined I needed the 'static' version of the library instead, 
I was expecting the static equivalent of the exact same package, not a subset or different variation.

**Comment by yusuke-kadowaki** [comment] 2021-12-16 02:13
@Sand2Silicon
Yeah totally agree that current requirement for users is confusing. I think I can figure this out and make a PR in a moment.

**Comment by JackBoosY** [comment] 2021-12-20 07:11
I tried to reproduce this issue but failed.
1. This issue seems not related to the `codegen` feature.
2. According to the _examples/cpp/route_guide/CMakeLists.txt_ line 70:
```cmake
foreach(_target
  route_guide_client route_guide_server)
  add_executable(${_target}
    "${_target}.cc")
  target_link_libraries(${_target}
    rg_grpc_proto
    route_guide_helper
    ${_REFLECTION}
    ${_GRPC_GRPCPP}
    ${_PROTOBUF_LIBPROTOBUF})
endforeach()
```
`route_guide_client` does link to `${_REFLECTION}` which was found in _examples/cpp/cmake/common.cmake_ line 105:
```cmake
  set(_REFLECTION gRPC::grpc++_reflection)
```
And grpc is found in line 114 which using _VCPKG_ROOT/installed/x64-windows-static/share/grpc/gRPCConfig.cmake_:
```cmake
  find_package(gRPC CONFIG REQUIRED)
```

So it seems that there is no issue here.
Can you please clean the cmake cache then try again?

Thanks.

**Comment by yusuke-kadowaki** [comment] 2021-12-20 15:58
@JackBoosY
I can confirm and reproduce this with the steps below. Did you forget to put the `DVCPKG_TARGET_TRIPLET=x64-windows-static` by any chance?

```
git clone https://github.com/microsoft/vcpkg.git
cd ./vcpkg
./bootstrap-vcpkg.bat
./vcpkg.exe install grpc:x64-windows-static

### move to the example directory

cmake -DCMAKE_TOOLCHAIN_FILE=<path-to-vcpkg>/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static ..
```

This should cause a whole bunch of errors like below.
```
CMake Error at G:/dev/tmp/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)
```

BTW, I'm having the same error with host:x64-windows, target:x86-windows, which is my usecase.

**Comment by JackBoosY** [comment] 2021-12-21 09:12
Can you please provide the full configure log?

**Comment by habanr** [comment] 2021-12-21 14:00
I've exactly the same problem. Library grpc++_reflection.lib an grpcpp_channelz.lib are missing x86-windows grpc package.

**Comment by yusuke-kadowaki** [comment] 2021-12-21 17:14
> Can you please provide the full configure log?

@Sand2Silicon Can you do this please? I can't take time for this for a few weeks because of holidays.

**Comment by JonLiu1993** [comment] 2022-01-11 13:42
@Sand2Silicon , Could you please provide the full configure log?

**Comment by Sand2Silicon** [comment] 2022-01-12 15:40
I can look into this today.

**Comment by yusuke-kadowaki** [comment] 2022-01-21 16:33
@JackBoosY @JonLiu1993 
This is the configure log after clean installing ``grpc:x64-windows-static``.
If you cannot reproduce this, can you also provide your install and configure procedure?

```
PS G:\dev\vcpkg\buildtrees\grpc\src\2180080eb4-87c05d756b.clean\examples\cpp\route_guide> cmake -DCMAKE_TOOLCHAIN_FILE=G:\dev\vcpkg\scripts\buildsystems\vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows-static .
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
-- The C compiler identification is MSVC 19.29.30133.0
-- The CXX compiler identification is MSVC 19.29.30133.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
CMake Warning (dev) at G:/dev/vcpkg/installed/x64-windows-static/share/protobuf/protobuf-options.cmake:6 (option):
  Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
  --help-policy CMP0077" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  For compatibility with older versions of CMake, option is clearing the
  normal variable 'protobuf_MODULE_COMPATIBLE'.
Call Stack (most recent call first):
  G:/dev/vcpkg/installed/x64-windows-static/share/protobuf/protobuf-config.cmake:2 (include)
  G:/dev/vcpkg/installed/x64-windows-static/share/protobuf/vcpkg-cmake-wrapper.cmake:16 (_find_package)
  G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:742 (include)
  G:/dev/vcpkg/buildtrees/grpc/src/2180080eb4-87c05d756b.clean/examples/cpp/cmake/common.cmake:101 (find_package)
  CMakeLists.txt:24 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Protobuf: G:/dev/vcpkg/installed/x64-windows-static/tools/protobuf/protoc.exe (found version "3.18.0.0")
-- Using protobuf 3.18.0.0
-- Found ZLIB: optimized;G:/dev/vcpkg/installed/x64-windows-static/lib/zlib.lib;debug;G:/dev/vcpkg/installed/x64-windows-static/debug/lib/zlibd.lib (found version "1.2.11")
-- Found OpenSSL: G:/dev/vcpkg/installed/x64-windows-static/debug/lib/libcrypto.lib (found version "1.1.1m")
-- Found c-ares: G:/dev/vcpkg/installed/x64-windows-static/share/c-ares/c-ares-config.cmake (found version "1.17.2")
-- Found RE2 via CMake.
-- Using gRPC 1.41.0
-- Configuring done
CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_client" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:540 (_add_executable):
  Target "route_guide_server" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:72 (add_executable)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "route_guide_helper" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:60 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "route_guide_helper" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:60 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "route_guide_helper" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:60 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "route_guide_helper" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:60 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "route_guide_helper" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:60 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "route_guide_helper" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:60 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "route_guide_helper" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:60 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "route_guide_helper" links to target "gRPC::grpc++_reflection" but
  the target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:60 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "rg_grpc_proto" links to target "gRPC::grpc++_reflection" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:49 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "rg_grpc_proto" links to target "gRPC::grpc++_reflection" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:49 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "rg_grpc_proto" links to target "gRPC::grpc++_reflection" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:49 (add_library)


CMake Error at G:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:578 (_add_library):
  Target "rg_grpc_proto" links to target "gRPC::grpc++_reflection" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  CMakeLists.txt:49 (add_library)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

**Comment by seven-mile** [comment] 2022-03-12 16:29
any progress? `x64-windows-static` doesn't include `proto_server_reflection_plugin.h` etc...
although I can copy the header from `x64-windows` triplet, I cannot do the same with `.lib`, which is not generated on my disk.

**Comment by JackBoosY** [comment] 2022-03-14 02:31
I will take a look at this issue today.

**Comment by Sand2Silicon** [comment] 2022-03-14 20:06
> "If most users need to use codegen when using grpc, I can add it as a default feature. "

1. A new GRPC user needs codegen by default, but may not know there is a "CodeGen" component or what it does, and likely wouldn't realize an error message about 'Reflection' is related to a missing codegen feature.

2. If a user specifically wants to use a separate CodeGen available on the host they mostly likely have a use-case and a clearer understanding of how these pieces fit together.

3. Can GRPC be used _without_ any codegen? I don't know, but I believe it's required.

Based on that, I think it should _work by default_ out of the box, and therefore include codegen by default. I can't speak for _most_ users, but 6-months into our enterprise GRPC project I'm not sure how or why you would use a separate codegen, it's not something we've encountered.

**Comment by yusuke-kadowaki** [comment] 2022-03-22 06:56
> If most users need to use codegen when using grpc

I have exactly same opinion as @Sand2Silicon so I don't repeat it.  
@JackBoosY How would you decide if it should be default or not specifically?

> If most users need to use codegen when using grpc, I can add it as a default feature. 

That would be ideal if it is acceptable to make it default. We just need to make sure that it doesn't compile on Windows ARM environments.

**Comment by Neumann-A** [comment] 2022-03-22 10:13
Usage error:
If you only request `x64-windows-static` vcpkg thinks you are crosscompiling and you cannot run codegens. The codegen will still be build but within the `x64-windows` triplet so you probably need extra code for the cross case.
So if you want a native build explicitly request it with `--host-triplet=x64-windows-static`

**Comment by JackBoosY** [comment] 2022-04-21 07:23
We haven't been able to repro this; if more information comes up, or this issue appears again, please reopen.

**Closed by JackBoosY** 2022-04-21 07:23 UTC
Labels: requires:repro
