### ISSUE TITLE
[protobuf] Build error

### ISSUE THREAD

**Issue by shijunz** [microsoft/vcpkg#32851] opened 2023-07-31 07:16 UTC
Copy issue body from C:/tools/vcpkg/installed/vcpkg/issue_body.md

C:\repo\alpaca\WoS_NSP\opencv\build_arm64>vcpkg install protobuf:arm64-windows
Computing installation plan...
The following packages will be built and installed:
    protobuf[core]:arm64-windows -> 3.21.12
Detecting compiler hash for triplet arm64-windows...
Restored 0 package(s) from C:\Users\shijunz\AppData\Local\vcpkg\archives in 628 us. Use --debug to see more details.
Installing 1/1 protobuf:arm64-windows...
Building protobuf[core]:arm64-windows...
-- Using cached protocolbuffers-protobuf-v3.21.12.tar.gz.
-- Cleaning sources at C:/tools/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch compile_options.patch
-- Using source at C:/tools/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean
-- Found external ninja('1.11.0').
-- Configuring arm64-windows
-- Building arm64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/tools/vcpkg/buildtrees/protobuf/arm64-windows-dbg
    See logs for more information:
      C:\tools\vcpkg\buildtrees\protobuf\install-arm64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/arm64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/arm64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/protobuf/portfile.cmake:48 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building protobuf:arm64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[protobuf]+Build+error&body=Copy+issue+body+from+C%3A%2Ftools%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by LilyWangLL** [comment] 2023-07-31 09:47
Closed as duplicate of #32849.

**Closed by LilyWangLL** 2023-07-31 09:47 UTC
Labels: requires:repro
