### ISSUE TITLE
sdl2-mixer[opusfile,libflac,libmodplug,libvorbis,mpg123] build failure

### ISSUE THREAD

**Issue by zulc22** [microsoft/vcpkg#15335] opened 2020-12-28 03:22 UTC
**Host Environment**
- OS: Windows 10 20H2 (en-US)
- Visual Studio 2019, 2017 build tools, 2005, .NET 2003
Other packages work fine -- don't know what the "Compiler: revision" means in the context of this template.

```
PS C:\Users\zulc22> vcpkg install sdl2-mixer[opusfile]
Computing installation plan...
The following packages will be built and installed:
    sdl2-mixer[core,nativemidi,opusfile]:x86-windows -> 2.0.4#10
Detecting compiler hash for triplet x86-windows...
Could not locate cached archive: C:\Users\zulc22\AppData\Local\vcpkg\archives\51\51e353a357690aed46faee8c51751dfaa18e9414.zip
Starting package 1/1: sdl2-mixer:x86-windows
Building package sdl2-mixer[core,nativemidi,opusfile]:x86-windows...
-- Using cached C:/vcpkg/downloads/SDL2_mixer-2.0.4.zip
-- Cleaning sources at C:/vcpkg/buildtrees/sdl2-mixer/src/2.0.4-a895b09396.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/SDL2_mixer-2.0.4.zip
-- Using source at C:/vcpkg/buildtrees/sdl2-mixer/src/2.0.4-a895b09396.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/vcpkg/buildtrees/sdl2-mixer/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\sdl2-mixer\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/sdl2-mixer/portfile.cmake:50 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)


Error: Building package sdl2-mixer:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2-mixer:x86-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.
```
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5745765/install-x86-windows-dbg-out.log)

**Comment by zulc22** [comment] 2020-12-28 03:23
the other sdl2-mixer features i've tried work fine on my system as well, right now opusfile is the only exception i can find.

**Comment by JackBoosY** [comment] 2020-12-28 07:36
```
music_opus.c.obj : error LNK2019: unresolved external symbol _op_open_callbacks referenced in function _OPUS_Load
music_opus.c.obj : error LNK2019: unresolved external symbol _op_free referenced in function _OPUS_Load
music_opus.c.obj : error LNK2019: unresolved external symbol _op_seekable referenced in function _OPUS_Load
music_opus.c.obj : error LNK2019: unresolved external symbol _op_head referenced in function _OPUS_Load
music_opus.c.obj : error LNK2019: unresolved external symbol _op_pcm_seek referenced in function _OPUS_Load
music_opus.c.obj : error LNK2019: unresolved external symbol _op_read referenced in function _OPUS_Load
SDL2_mixer.dll : fatal error LNK1120: 6 unresolved externals
```
```
music_flac.c.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_new referenced in function _FLAC_Load
music_flac.c.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_delete referenced in function _FLAC_Load
music_flac.c.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_get_state referenced in function _FLAC_Load
music_flac.c.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_init_stream referenced in function _FLAC_Load
music_flac.c.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_finish referenced in function _FLAC_Load
music_flac.c.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_flush referenced in function _FLAC_Load
music_flac.c.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_process_single referenced in function _FLAC_Load
music_flac.c.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_process_until_end_of_metadata referenced in function _FLAC_Load
music_flac.c.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_process_until_end_of_stream referenced in function _FLAC_Load
music_flac.c.obj : error LNK2019: unresolved external symbol __imp__FLAC__stream_decoder_seek_absolute referenced in function _FLAC_Load
music_modplug.c.obj : error LNK2019: unresolved external symbol __imp__ModPlug_Load referenced in function _MODPLUG_Load
music_modplug.c.obj : error LNK2019: unresolved external symbol __imp__ModPlug_Unload referenced in function _MODPLUG_Load
music_modplug.c.obj : error LNK2019: unresolved external symbol __imp__ModPlug_Read referenced in function _MODPLUG_Load
music_modplug.c.obj : error LNK2019: unresolved external symbol __imp__ModPlug_Seek referenced in function _MODPLUG_Load
music_modplug.c.obj : error LNK2019: unresolved external symbol __imp__ModPlug_GetSettings referenced in function _MODPLUG_Load
music_modplug.c.obj : error LNK2019: unresolved external symbol __imp__ModPlug_SetSettings referenced in function _MODPLUG_Load
music_modplug.c.obj : error LNK2019: unresolved external symbol __imp__ModPlug_SetMasterVolume referenced in function _MODPLUG_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_init referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_exit referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_new referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_delete referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_plain_strerror referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_strerror referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_rates referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_format_none referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_format referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_getformat referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_open_handle referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_close referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_read referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_seek referenced in function _MPG123_Load
music_mpg123.c.obj : error LNK2019: unresolved external symbol _mpg123_replace_reader_handle referenced in function _MPG123_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol _ov_clear referenced in function _OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol _ov_open_callbacks referenced in function _OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol _ov_pcm_total referenced in function _OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol _ov_pcm_seek referenced in function _OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol _ov_time_seek referenced in function _OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol _ov_pcm_tell referenced in function _OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol _ov_info referenced in function _OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol _ov_comment referenced in function _OGG_Load
music_ogg.c.obj : error LNK2019: unresolved external symbol _ov_read referenced in function _OGG_Load
SDL2_mixer.dll : fatal error LNK1120: 41 unresolved externals
```

**Comment by JackBoosY** [comment] 2020-12-28 07:45
Confirmed.

**Comment by JackBoosY** [comment] 2020-12-28 09:50
Since mixer's dependency `opus` have been updated to 1.3.1, and the current mixer's requires opus version is 0.10, some opus functions used by some mixers have been deprecated, so we should upgrade the mixer.

**Comment by JackBoosY** [comment] 2020-12-28 09:52
But for now, the latest mixer doesn't support the latest opus.

**Comment by noam-c** [comment] 2020-12-31 06:41
@JackBoosY Is the cause the same for the other libraries? I'm unable to install even without opus (i.e. just `sdl2-mixer[mpg123]`). I get some of the same linker errors shown in your log.

```
Package: sdl2-mixer:x64-windows
Vcpkg version: 2020.11.12-nohash
```

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5756609/install-x64-windows-dbg-out.log)

I'm reproing this issue on Windows 8.1, on commit 5c262f63ec509a733dd67db71c0959e8842e0091.

**Comment by JackBoosY** [comment] 2020-12-31 07:15
@noam-c Same issue, but only related to sdl2-mixer, not sdl2.

**Comment by zulc22** [comment] 2021-01-11 01:06
is there any possible workaround for now? vcpkg is the only way i can stand to install libraries when using visual studio. i'd really prefer not to compile the libs myself and spend 3 hours debugging include and library directory configurations in the terribly sorted properties window

**Comment by JackBoosY** [comment] 2021-01-12 09:26
@zulc22 Currently no, we should wait for #11758 merge then set the minimum version of opus that sdl2-mixer depends on to 0.1.0 or wait for upstream fix this issue.

**Comment by thomak-dev** [comment] 2021-02-13 14:54
It looks like versioning is now ready? Is there any ETA for this issue? I don't want to switch over to old school library management of all SDL libraries just because of mpg123

**Comment by JackBoosY** [comment] 2021-04-19 07:11
@thomak-dev Versioning is ready, but we do not support selecting a version in vcpkg by default (by adding a fixed version number in CONTROL or manifest), you can add an overlay port to do it.
See [documentation](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md).

**Comment by vividos** [comment] 2022-05-26 09:06
I get this error also in one of my projects that I'm converting to vcpkg. Is this a simple matter of adjusting the `vcpkg.json` file of the sdl2-mixer port now? In this line?

https://github.com/microsoft/vcpkg/blob/master/ports/sdl2-mixer/vcpkg.json#L61

There also seems to be a new SDL2_Mixer version being prepared, which would make the issue go away anyway, but it would be nice to use SDL2_mixer right away.

Thanks!

**Comment by JackBoosY** [comment] 2022-07-29 07:30
Close this PR until upstream fixes this.

**Closed by JackBoosY** 2022-07-29 07:30 UTC
Labels: category:port-bug, category:port-update, depends:upstream-changes
