### ISSUE TITLE
[eigen3] Build error: Mismatched hash for downloaded file

### ISSUE THREAD

**Issue by davidgidali** [microsoft/vcpkg#30536] opened 2023-03-30 05:17 UTC
**Host Environment**

- OS: Windows 10
- Command Prompt

**To Reproduce**

`vcpkg install colmap[cuda]:x64-windows`

I encountered a build error when trying to install eigen3:x64-windows using vcpkg. The downloaded file's hash does not match the expected hash. I have tried deleting the downloaded file and downloading it again, but the issue persists.

- vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
- vcpkg-scripts version: d10d511f2 2023-03-29

**Downloaded File Details:**
- URL: https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
- File: libeigen-eigen-3.4.0.tar.gz
- Actual SHA256 Hash (from 7-Zip): 0c8c490764f9c2a793133491adca0cd073b73e0bde965c68cbe58d91b5ed4261

**Expected Hash (from vcpkg log):**
- Expected hash: ba75ecb760e32acf4ceaf27115468e65d4f77c44f8d519b5a13e7940af2c03a304ad433368cb6d55431f307c5c39e2666ab41d34442db3cf441638e51f5c3b6a

Any assistance with resolving this issue would be greatly appreciated. Thank you.

**Comment by MonicaLiu0311** [comment] 2023-03-30 05:47
Duplicate of #https://github.com/microsoft/vcpkg/issues/30481

**Comment by MonicaLiu0311** [comment] 2023-03-30 05:52
Duplicate of https://github.com/microsoft/vcpkg/issues/30481

**Closed by MonicaLiu0311** 2023-03-30 05:52 UTC
Labels: category:port-bug
