### ISSUE TITLE
[gmp] Build error

### ISSUE THREAD

**Issue by Beherr** [microsoft/vcpkg#34432] opened 2023-10-12 03:08 UTC
Package: gmp:x64-linux -> 6.2.1#21

**Host Environment**

- Host: x64-linux
- Compiler: GNU 9.4.0
-    vcpkg-tool version: 2023-09-15-ac02a9f660977426b8ec6392919fbb1d51b10998
    vcpkg-scripts version: b40de4489 2023-10-11 (9 hours ago)

**To Reproduce**

`vcpkg install --x-feature=cuda`
**Failure logs**

```
-- Using cached gmp-6.2.1.tar.xz.
-- Cleaning sources at /home/bhw/3D_reconstruct/openMVS/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/bhw/3D_reconstruct/openMVS/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Applying patch gmp-arm64-asm-fix-5f32dbc41afc.patch
-- Using source at /home/bhw/3D_reconstruct/openMVS/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean
-- Getting CMake variables for x64-linux
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/bhw/3D_reconstruct/openMVS/vcpkg/buildtrees/gmp/src/v6.2.1-0c723d4b6f.clean/
    Error code: 1
    See logs for more information:
      /home/bhw/3D_reconstruct/openMVS/vcpkg/buildtrees/gmp/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:635 (vcpkg_execute_required_process)
  ports/gmp/portfile.cmake:85 (vcpkg_configure_make)
  scripts/ports.cmake:168 (include)



```
<details><summary>/home/bhw/3D_reconstruct/openMVS/vcpkg/buildtrees/gmp/autoconf-x64-linux-err.log</summary>

```
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
configure.ac:3791: warning: AC_LIBTOOL_PROG_COMPILER_PIC is m4_require'd but not m4_defun'd
acinclude.m4:2363: GMP_ASM_X86_GOT_UNDERSCORE is expanded from...
configure.ac:3791: the top level
configure.ac:3794: warning: AC_ENABLE_SHARED is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
configure.ac:3794: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
autoreconf: configure.ac: tracing
configure.ac:3791: warning: AC_LIBTOOL_PROG_COMPILER_PIC is m4_require'd but not m4_defun'd
acinclude.m4:2363: GMP_ASM_X86_GOT_UNDERSCORE is expanded from...
configure.ac:3791: the top level
configure.ac:3794: warning: AC_ENABLE_SHARED is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
configure.ac:3794: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:3791: warning: AC_LIBTOOL_PROG_COMPILER_PIC is m4_require'd but not m4_defun'd
acinclude.m4:2363: GMP_ASM_X86_GOT_UNDERSCORE is expanded from...
configure.ac:3791: the top level
configure.ac:3794: warning: AC_ENABLE_SHARED is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
configure.ac:3794: warning: AC_PROG_LIBTOOL is m4_require'd but not m4_defun'd
acinclude.m4:2717: GMP_ASM_X86_MCOUNT is expanded from...
configure.ac:3794: the top level
configure.ac:2664: error: possibly undefined macro: AC_LIBTOOL_WIN32_DLL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:2752: error: possibly undefined macro: AC_PROG_LIBTOOL
configure.ac:2875: error: possibly undefined macro: AC_CHECK_LIBM
configure:11256: error: possibly undefined macro: AC_PROG_NM
configure:15233: error: possibly undefined macro: AC_LIBTOOL_PROG_COMPILER_PIC
configure:15328: error: possibly undefined macro: AC_ENABLE_SHARED
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
</details>**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "openmvs",
  "version": "2.1.0",
  "description": "OpenMVS: open Multi-View Stereo reconstruction library",
  "homepage": "https://cdcseacave.github.io/openMVS",
  "dependencies": [
    "boost-iostreams",
    "boost-program-options",
    "boost-serialization",
    "boost-system",
    "boost-throw-exception",
    {
      "name": "cgal",
      "default-features": false
    },
    "eigen3",
    "glew",
    "glfw3",
    "libpng",
    "opencv",
    "opengl",
    "tiff",
    "vcglib",
    "zlib"
  ],
  "features": {
    "python": {
      "description": "Python bindings for OpenMVS",
      "dependencies": [
        "boost-python"
      ]
    },
    "cuda": {
      "description": "CUDA support for OpenMVS",
      "dependencies": [
        "cuda"
      ]
    },
    "openmp": {
      "description": "OpenMP support for OpenMVS"
    }
  }
}

```
</details>

**Comment by Adela0814** [comment] 2023-10-12 08:34
Please run `sudo apt-get install autoconf automake libtool` and reinstall `gmp` again.

**Comment by Adela0814** [comment] 2023-10-12 08:34
Duplicate of https://github.com/microsoft/vcpkg/issues/33014.

**Closed by Adela0814** 2023-10-12 08:34 UTC

**Comment by Beherr** [comment] 2023-10-12 08:52
Thank you so much！！
