### ISSUE TITLE
[ceres] update to 2.2.0

### ISSUE THREAD

**Issue by moolawooda** [microsoft/vcpkg#38771] opened 2024-05-16 15:48 UTC
### Library name

ceres

### New version number

2.2.0

### Other information that may be useful (release notes, etc...)

project homepage: 
http://ceres-solver.org/

github homepage:
https://github.com/ceres-solver/ceres-solver

latest version(2.2.0) release page:
https://github.com/ceres-solver/ceres-solver/releases/tag/2.2.0

**Comment by patrikhuber** [comment] 2024-06-09 13:42
This is a duplicate of https://github.com/microsoft/vcpkg/issues/34483, but it does need attention.

**Comment by WangWeiLin-MV** [comment] 2024-07-26 07:02
Duplicate of #34483

**Closed by WangWeiLin-MV** 2024-07-26 07:02 UTC
Labels: category:port-update
