### ISSUE TITLE
[aom] Build error

### ISSUE THREAD

**Issue by Sam960312** [microsoft/vcpkg#33061] opened 2023-08-09 03:46 UTC
Package: aom[core]:x64-windows-static -> 3.5.0#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.0.24215.1
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: 501db0f17 2023-04-15 (4 months ago)

**To Reproduce**

`vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static aom:x64-windows-static`

**Failure logs**

```
-- Fetching https://aomedia.googlesource.com/aom 9a83c6a5a55c176adbce740e47d3512edfc9ae71...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Git/cmd/git.exe" fetch https://aomedia.googlesource.com/aom 9a83c6a5a55c176adbce740e47d3512edfc9ae71 --depth 1 -n
    Working Directory: D:/runoob-greeting/rustdesk/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      D:\runoob-greeting\rustdesk\vcpkg\buildtrees\aom\git-fetch-x64-windows-static-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:86 (vcpkg_execute_required_process)
  ports/aom/portfile.cmake:11 (vcpkg_from_git)
  scripts/ports.cmake:147 (include)



```
<details><summary>D:\runoob-greeting\rustdesk\vcpkg\buildtrees\aom\git-fetch-x64-windows-static-err.log</summary>

```
fatal: unable to access 'https://aomedia.googlesource.com/aom/': Failed to connect to aomedia.googlesource.com port 443: Timed out
```
</details>

**Additional context**

**Comment by jimwang118** [comment] 2023-08-09 06:05
duplicate of https://github.com/microsoft/vcpkg/issues/33059

**Comment by dg0yt** [comment] 2023-08-09 06:35
Duplicate of #33059.

**Comment by jimwang118** [comment] 2023-08-09 06:37
Try to see if you can access this address: https://aomedia.googlesource.com/aom/, if you cannot access it directly, please check whether the network or proxy settings are correct.

**Comment by PhoebeHui** [comment] 2023-08-14 09:51
Duplicated of https://github.com/microsoft/vcpkg/issues/33059, please use it to track the problem.

**Closed by PhoebeHui** 2023-08-14 09:51 UTC
Labels: category:question
