### ISSUE TITLE
pcl build failure

### ISSUE THREAD

**Issue by arrlee** [microsoft/vcpkg#21488] opened 2021-11-17 08:34 UTC
**Host Environment**
- OS: Windows 11
- Compiler: Visual Studio 2022, Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30133 for x64
- executed in "x64 Native Tools Command Prompt for VS 2019" as administrator

**To Reproduce**
`./vcpkg install pcl`

**Failure logs** 
```
...
Starting package 95/95: pcl:x64-windows
Building package pcl[core]:x64-windows...
-- Using cached PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz.
-- Extracting source C:/data/vcpkg/downloads/PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz
-- Applying patch add-gcc-version-check.patch
-- Applying patch fix-check-sse.patch
-- Applying patch fix-find-qhull.patch
-- Applying patch fix-numeric-literals-flag.patch
-- Applying patch pcl_config.patch
-- Applying patch pcl_utils.patch
-- Applying patch remove-broken-targets.patch
-- Applying patch fix-cmake_find_library_suffixes.patch
-- Using source at C:/data/vcpkg/buildtrees/pcl/src/89d532cf08-fd49a85837.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:485 (message):
  The following variables are not used in CMakeLists.txt:

      PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):

  ports/pcl/portfile.cmake:42 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)


-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/data/cmake/bin/cmake.exe --build . --config Release --target install -- -v -j9
    Working Directory: C:/data/vcpkg/buildtrees/pcl/x64-windows-rel
    See logs for more information:
      C:\data\vcpkg\buildtrees\pcl\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/pcl/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:142 (include)


Error: Building package pcl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcl[core]:x64-windows -> 1.12.0
  vcpkg version: a4b5cde7f 2021-11-16 (4 hours ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

```
Please also see attached log file.
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7552943/install-x64-windows-rel-out.log)

**Comment by JonLiu1993** [comment] 2021-11-17 09:28
Duplicate of #21327 ,we track in pr #21327 ,Temporarily close this pr

**Closed by JonLiu1993** 2021-11-17 09:28 UTC
Labels: requires:repro
