### ISSUE TITLE
[openssl:x64-windows] build failure

### ISSUE THREAD

**Issue by Alteration** [microsoft/vcpkg#19796] opened 2021-08-30 06:50 UTC
**Host Environment**
-  OS: Windows 11 (22000.120)
-  Compiler: Visual Studio 2019 or 2022

**To Reproduce**

`./vcpkg.exe install openssl:x64-windows`

**Failure Logs**

```
Starting package 1/5: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Downloading https://www.openssl.org/source/openssl-1.1.1l.tar.gz;https://www.openssl.org/source/old/1.1.1/openssl-1.1.1l.tar.gz -> openssl-1.1.1l.tar.gz...
-- Cleaning sources at E:/vcpkg/buildtrees/openssl/src/openssl-1-5a7d592597.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/openssl-1.1.1l.tar.gz
-- Using source at E:/vcpkg/buildtrees/openssl/src/openssl-1-5a7d592597.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip;https://fossies.org/windows/misc/nasm-2.15.05-win32.zip -> nasm-2.15.05-win32.zip...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip
[DEBUG] Downloading https://fossies.org/windows/misc/nasm-2.15.05-win32.zip
Error: Failed to download from mirror set:
https://www.nasm.us/pub/nasm/releasebuilds/2.15.05/win32/nasm-2.15.05-win32.zip: WinHttpSendRequest() failed: 12002
https://fossies.org/windows/misc/nasm-2.15.05-win32.zip: failed: status code 410

[DEBUG] C:\a\1\s\src\vcpkg\base\downloads.cpp(626)
[DEBUG] Exiting after 22583335 us (22583203 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:83 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:274 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_find_acquire_program.cmake:552 (vcpkg_download_distfile)
  ports/openssl/windows/portfile.cmake:8 (vcpkg_find_acquire_program)
  ports/openssl/portfile.cmake:19 (include)
  scripts/ports.cmake:140 (include)


Error: Building package openssl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x64-windows
  Vcpkg version: 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

```
**Additional context**
There appear to be two issues at play here, the first is that nasm.us appears to currently be down, while the alternative fossies url instead heads to a file gone page, this page instead states that the file we might actually be looking for is nasm-2.15.05-win64.zip, there does not appear to be a win32 version.

https://github.com/microsoft/vcpkg/blob/21935b744dc411e0fb1926618fdfb18c67d4b188/scripts/cmake/vcpkg_find_acquire_program.cmake#L87

**Comment by JackBoosY** [comment] 2021-08-30 08:19
The nasm https server is down.

**Comment by JackBoosY** [comment] 2021-08-30 08:21
Please download [this](https://github.com/microsoft/vcpkg/files/7075269/nasm-2.15.05-win32.zip) and put it into _VCPKG_ROOT/downloads_ then try again.

Please note that's a only a workaround, we need to wait for the official webset recovery,

**Comment by emabrey** [comment] 2021-08-30 10:30
I can confirm that on x64-windows replacing the NASM section of `scripts/cmake/vcpkg_find_acquire_program.cmake` with the following snippet fixes my usage of another package which is trying to pull NASM (ffmpeg):

```
[...]
elseif(VAR MATCHES "NASM")
    set(PROGNAME nasm)
    set(NASM_VERSION 2.15.05)
    set(PATHS ${DOWNLOADS}/tools/nasm/nasm-${NASM_VERSION})
    set(BREW_PACKAGE_NAME "nasm")
    set(APT_PACKAGE_NAME "nasm")
    set(URL
      "https://fossies.org/windows/misc/nasm-${NASM_VERSION}-win64.zip"
    )
    set(ARCHIVE "nasm-${NASM_VERSION}-win64.zip")
    set(HASH 0d0469f3d475f3d192b9b5b7ee74662cbcb9e02efa0d51839c12cbf6f5de5cd58b32e1d12c9ee4381a63e99a4956e03df7decaf1369e598e0edff19a12629073)
[...]
```

Unfortunately that is a win64 build so it won't serve to help x86-windows attempts to find NASM (as other people have already pointed out).

**Comment by twose** [comment] 2021-08-30 10:43
It works for me :)
```
New-Item -ItemType container "${env:VCPKG_INSTALLATION_ROOT}\downloads"
          Invoke-WebRequest -Uri "https://github.com/microsoft/vcpkg/files/7075269/nasm-2.15.05-win32.zip" -OutFile "${env:VCPKG_INSTALLATION_ROOT}\downloads\nasm-2.15.05-win32.zip"
```

**Comment by robertobernabe** [comment] 2021-08-30 11:58
We fixed this issue temporarily with a patch. 
`diff --git a/scripts/cmake/vcpkg_find_acquire_program.cmake b/scripts/cmake/vcpkg_find_acquire_program.cmake
index aea148e45..1714aaec8 100644
--- a/scripts/cmake/vcpkg_find_acquire_program.cmake
+++ b/scripts/cmake/vcpkg_find_acquire_program.cmake
@@ -85,6 +85,7 @@ function(vcpkg_find_acquire_program VAR)
     set(URL
       "https://www.nasm.us/pub/nasm/releasebuilds/${NASM_VERSION}/win32/nasm-${NASM_VERSION}-win32.zip"
       "https://fossies.org/windows/misc/nasm-${NASM_VERSION}-win32.zip"
+      "https://github.com/microsoft/vcpkg/files/7075269/nasm-2.15.05-win32.zip"
     )
     set(ARCHIVE "nasm-${NASM_VERSION}-win32.zip")
     set(HASH 9412b8caa07e15eac8f500f6f8fab9f038d95dc25e0124b08a80645607cf5761225f98546b52eac7b894420d64f26c3cbf22c19cd286bbe583f7c964256c97ed)
`

**Comment by JackBoosY** [comment] 2021-08-31 00:30
Hi guys, since the nasm official website has been restored, I think I can close this issue now.

**Closed by JackBoosY** 2021-08-31 00:30 UTC
Labels: depends:upstream-changes

**Comment by DavraYoung** [comment] 2022-04-09 16:57
and its down again(
