### ISSUE TITLE
vcpkg install pcl:x64-windows, but visualization include not installed #include <pcl/visualization/pcl_visualizer.h> missing from pcl installed include

### ISSUE THREAD

**Issue by HuQingsheng520** [microsoft/vcpkg#11601] opened 2020-05-26 22:45 UTC
###  My Environment

- Operating System and version: Win10

- Compiler: VS 2017

- PCL Version: Version: 1.9.1-13

- VTK Version: Version: 9.0
### Context
standard installation of pcl with vcpkg does not generate visualization include directory.
How can the include directory get generated by pcl installation using vcpkg ?

**Comment by Neumann-A** [comment] 2020-05-27 06:53
duplicate of #11462. Requires upstream update to support VTK 9.0.

**Comment by dentx22** [comment] 2020-05-30 12:44
news ?

**Comment by HuQingsheng520** [comment] 2020-05-30 13:31
> news ?
Yes

**Comment by davidbun** [comment] 2020-06-02 11:37
Same issue for me - cannot continue
Any time estimations for fixing that?

**Comment by Neumann-A** [comment] 2020-06-02 11:39
Ask upstream? (https://github.com/PointCloudLibrary/pcl)
Maybe here in specific https://github.com/PointCloudLibrary/pcl/pull/4096 ?

**Comment by vikasmalik22** [comment] 2020-06-14 06:18
I am also facing the same issue. Any updates?

**Comment by HuQingsheng520** [comment] 2020-06-14 07:07
> I am also facing the same issue. Any updates?
My solution is to download and use the 2020.04 release.

**Comment by vikasmalik22** [comment] 2020-06-18 03:33
> > I am also facing the same issue. Any updates?
> > My solution is to download and use the 2020.04 release.

I tried fresh installation still it didn't work. 

I did >> vcpkg install pcl:x64-windows-static

Vcpkg package management program version 2020.02.04-nohash
visualization folder is completely missing from pcl folder.

**Comment by davidbun** [comment] 2020-08-12 12:59
Any update on this issue? Still no visualization folder in include files

**Comment by Neumann-A** [comment] 2020-08-12 19:13
Upstream progress is tracked in https://github.com/PointCloudLibrary/pcl/pull/4262
If you want updates subscribe to that PR or ask question there.

**Comment by TaylorDale** [comment] 2020-08-24 06:50
Any way to use an older version in the meantime?

**Comment by raahilsha-z** [comment] 2020-08-25 21:42
I'm currently using VCPKG commit ecfc714b9adbdf8bf6b394dd6b46d9c56ca993ea (git checkout on VCPKG folder after clone). If you're using QT, you might need to grab the download files for QT from the [archive here](https://download.qt.io/new_archive/qt/5.11/5.11.2/submodules/) and manually place them inside the vcpkg/downloads folder. This commit lets me install pcl[openni2,qt,tools,cuda,opengl]:x64-windows without any issues.

**Comment by JanKovis** [comment] 2020-11-24 13:37
I had to download VTK8, compile it separately, bend PCL to use that VTK version 8.0, 
Struggled with convex hull calculation as well, it used qhull, needed to compile qhull separately and point PCL to it. 
Quite some tinkering in source/CMake files to achieve PCL build with visualization and convex hulls!

**Comment by Andyjk1406** [comment] 2020-12-05 12:09
I think (think...) this might be solved upstream now.

[https://github.com/PointCloudLibrary/pcl/pull/4262](url)

**Comment by JackBoosY** [comment] 2021-03-18 08:41
Duplicated to #15130

**Closed by JackBoosY** 2021-03-18 08:41 UTC
Labels: depends:upstream-changes

**Comment by Chris45215** [comment] 2021-07-18 13:58
Is there some solution that doesn't involve going down a rabbit hole of compiling components (and their sub-components and dependencies) myself? And/or, can actual instructions on how to install the visualizer components after installing PCL via vcpkg be added to the official instructions (which are the top google result) at https://pointclouds.org/downloads/?

For the official instructions to consist of a single line with the implication of "it just works", while the reality is that the visualizer - _which is kind of the point of all the pointcloud stuff for many people_ - isn't even included... that's the type of thing that is usually done by developers who want to spite everyone who tries to use the project.

**Comment by abdullahazab** [comment] 2021-10-21 04:45
having the same problem here in Poth the x86 and the x64 versions, I've noticed that the missing files are in the **buildtrees** folder , but you wouldn't just copy a file and it works the folder structure is not the same .

**Comment by Ilmu011** [comment] 2021-11-17 17:17
This problem seems to be fixed in the newest version. If you still come across this problem, try updating vcpkg via `git pull` and run `vcpkg upgrade --no-dry-run` to update your packages to the newest version. I was also missing the visualization module and after updating vcpkg and its packages it was there.

**Comment by yoavmil** [comment] 2022-01-16 09:03
Same problem here. Updating vcpkg didn't work for me.

**Comment by JackBoosY** [comment] 2022-01-17 00:47
@yoavmil Can you please provide the repro step?

**Comment by yoavmil** [comment] 2022-01-17 08:07
@JackBoosY Not much to it.
```powershell
cd vcpkg
git pull
vcpkg install pcl:x64-windows
vcpkg list pcl # pcl:x64-windows  1.12.0#2  Point Cloud Library (PCL) is open source library...
vcpkg --version # Vcpkg package management program version 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761
```

**Comment by JackBoosY** [comment] 2022-01-18 03:35
@yoavmil  Also please provide the failure logs?

**Comment by yoavmil** [comment] 2022-01-18 08:00
@JackBoosY, no failure logs. Just that the visualation header and dll doesn't exist.

**Comment by JackBoosY** [comment] 2022-01-18 09:04
@yoavmil  Please git pull vcpkg, remove pcl and install pcl with feature `visualization`.
I can confirm the headers and dlls are exist.

**Comment by yoavmil** [comment] 2022-01-18 13:08
Yep, my fault. needed to 
`vcpkg install pcl[visualization]:x64-windows`
Wasn't aware of the options.
