### ISSUE TITLE
vcpkg install [openssl] Build error

### ISSUE THREAD

**Issue by 747728775** [microsoft/vcpkg#32682] opened 2023-07-21 08:37 UTC
win11,visual studio 2022.

vcpkg
error: building openssl:x86-windows failed with: BUILD_FAILED

Copy issue body from E:/vcpkgnew/installed/vcpkg/issue_body.md
PS E:\vcpkgnew> .\vcpkg install openssl:x86-windows
Computing installation plan...
The following packages will be built and installed:
    openssl:x86-windows -> 3.1.1
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\74772\AppData\Local\vcpkg\archives in 101 us. Use --debug to see more details.
Installing 1/1 openssl:x86-windows...
Building openssl:x86-windows...
-- Using cached openssl-openssl-openssl-3.1.1.tar.gz.
-- Cleaning sources at E:/vcpkgnew/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkgnew/downloads/openssl-openssl-openssl-3.1.1.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at E:/vcpkgnew/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x86-windows
-- Getting CMake variables for x86-windows
-- Prerunning x86-windows-dbg
-- Building x86-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/VisualStudio/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x86/nmake.exe /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: E:/vcpkgnew/buildtrees/openssl/x86-windows-dbg
    See logs for more information:
      E:\vcpkgnew\buildtrees\openssl\install-x86-windows-dbg-nmake-out.log
      E:\vcpkgnew\buildtrees\openssl\install-x86-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:50 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:68 (include)
  scripts/ports.cmake:147 (include)

error: building openssl:x86-windows failed with: BUILD_FAILED
Elapsed time to handle openssl:x86-windows: 1.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error&body=Copy+issue+body+from+E%3A%2Fvcpkgnew%2Finstalled%2Fvcpkg%2Fissue_body.md
    
    err.log：
    cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
aes-586.S
crypto\aes\libcrypto-shlib-aes-586.obj.asm:1: error: parser: instruction expected
crypto\aes\libcrypto-shlib-aes-586.obj.asm:2: error: parser: instruction expected
crypto\aes\libcrypto-shlib-aes-586.obj.asm:5: error: label or instruction expected at start of line
crypto\aes\libcrypto-shlib-aes-586.obj.asm:21: warning: label alone on a line without a colon might be in error [-w+label-orphan]
NMAKE : fatal error U1077: '"E:\vcpkgnew\downloads\tools\nasm\nasm-2.16.01\nasm.exe"  -f win32  -o crypto\aes\libcrypto-shlib-aes-586.obj crypto\aes\libcrypto-shlib-aes-586.obj.asm' : return code '0x1'
Stop.
NMAKE : fatal error U1077: 'D:\VisualStudio\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x86\nmake.exe /LU                 _build_libs' : return code '0x2'
Stop.

**Comment by FrankXie05** [comment] 2023-07-21 09:16
Duplicate of https://github.com/microsoft/vcpkg/issues/30645.

**Closed by FrankXie05** 2023-07-21 09:16 UTC
Labels: requires:repro

**Comment by 747728775** [comment] 2023-07-24 06:34
Package: libiconv:x86-windows -> 1.17#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32535.0
-    vcpkg-tool version: 2023-06-15-8c254a5fb6c503615834fc66bd0717664a339a2e
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install libiconv:x86-windows`

**Failure logs**

```
-- Using cached libiconv-1.17.tar.gz.
-- Cleaning sources at E:/vcpkgnew/buildtrees/libiconv/src/v1.17-84a471678e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkgnew/downloads/libiconv-1.17.tar.gz
-- Applying patch 0002-Config-for-MSVC.patch
-- Applying patch 0003-Add-export.patch
-- Applying patch 0004-ModuleFileName.patch
-- Applying patch clang-fortify.patch
-- Using source at E:/vcpkgnew/buildtrees/libiconv/src/v1.17-84a471678e.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x86-windows
-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.40-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.34-3-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.36.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libcrypt-2.1-4-x86_64.pkg.tar.zst.
-- Using msys root at E:/vcpkgnew/downloads/tools/msys2/d7266db249278763
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at E:/vcpkgnew/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Configuring x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: E:/vcpkgnew/downloads/tools/msys2/d7266db249278763/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='compile cl.exe -E' CC='compile cl.exe' CC_FOR_BUILD='touch a.out | touch conftest.exe | true' CPP_FOR_BUILD='touch a.out | touch conftest.exe | true' CXX_FOR_BUILD='touch a.out | touch conftest.exe | true' CXX='compile cl.exe' RC='windres-rc rc.exe' WINDRES='windres-rc rc.exe' AR='ar-lib lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/v1.17-84a471678e.clean/configure --build=x86_64-pc-mingw32 --host=i686-pc-mingw32 \"--enable-extra-encodings\" \"--without-libiconv-prefix\" \"--without-libintl-prefix\" \"--enable-relocatable\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--prefix=/E/vcpkgnew/installed/x86-windows/debug\" \"--bindir=\\${prefix}/../tools/libiconv/debug/bin\" \"--sbindir=\\${prefix}/../tools/libiconv/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libiconv\""
    Working Directory: E:/vcpkgnew/buildtrees/libiconv/x86-windows-dbg
    Error code: 77
    See logs for more information:
      E:\vcpkgnew\buildtrees\libiconv\config-x86-windows-dbg-config.log
      E:\vcpkgnew\buildtrees\libiconv\config-x86-windows-dbg-out.log
      E:\vcpkgnew\buildtrees\libiconv\config-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:833 (vcpkg_execute_required_process)
  ports/libiconv/portfile.cmake:29 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)



```
<details><summary>E:\vcpkgnew\buildtrees\libiconv\config-x86-windows-dbg-config.log</summary>

```
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by libiconv configure 1.17, which was
generated by GNU Autoconf 2.71.  Invocation command line was

  $ ./../src/v1.17-84a471678e.clean/configure --build=x86_64-pc-mingw32 --host=i686-pc-mingw32 --enable-extra-encodings --without-libiconv-prefix --without-libintl-prefix --enable-relocatable ac_cv_prog_ac_ct_STRIP=: gl_cv_double_slash_root=yes ac_cv_func_memmove=yes --disable-silent-rules --verbose --enable-shared --disable-static --prefix=/E/vcpkgnew/installed/x86-windows/debug '--bindir=${prefix}/../tools/libiconv/debug/bin' '--sbindir=${prefix}/../tools/libiconv/debug/sbin' '--libdir=${prefix}/lib' '--includedir=${prefix}/../include' '--datarootdir=${prefix}/share/libiconv'

## --------- ##
## Platform. ##
## --------- ##

hostname = Simple
uname -m = x86_64
uname -r = 3.4.6.x86_64
uname -s = MSYS_NT-10.0-22621
uname -v = 2023-02-15 18:03 UTC

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = x86_64
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /d/VisualStudio/Community/VC/Tools/MSVC/14.36.32532/bin/HostX64/x86/
PATH: /d/VisualStudio/Community/VC/Tools/MSVC/14.36.32532/bin/HostX64/x64/
PATH: /d/VisualStudio/Community/Common7/IDE/VC/VCPackages/
PATH: /d/VisualStudio/Community/Common7/IDE/CommonExtensions/Microsoft/TestWindow/
PATH: /d/VisualStudio/Community/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team Explorer/
PATH: /d/VisualStudio/Community/MSBuild/Current/bin/Roslyn/
PATH: /d/VisualStudio/Community/Team Tools/Performance Tools/
PATH: /c/Program Files (x86)/Microsoft SDKs/Windows/v10.0A/bin/NETFX 4.7.2 Tools/x64/
PATH: /c/Program Files (x86)/HTML Help Workshop/
PATH: /d/Windows Kits/10/bin/10.0.22000.0/x64/
PATH: /d/Windows Kits/10/bin/x64/
PATH: /d/VisualStudio/Community/MSBuild/Current/Bin/amd64/
PATH: /c/Windows/Microsoft.NET/Framework64/v4.0.30319/
PATH: /d/VisualStudio/Community/Common7/IDE/
PATH: /d/VisualStudio/Community/Common7/Tools/
PATH: /e/vcpkgnew/downloads/tools/powershell-core-7.2.11-windows/
PATH: /e/vcpkgnew/scripts/buildsystems/make_wrapper/
PATH: /usr/share/automake-1.16/
PATH: /usr/bin/
PATH: /c/Windows/system32/
PATH: /c/Windows/
PATH: /c/Windows/system32/Wbem/
PATH: /c/Windows/system32/WindowsPowerShell/v1.0/
PATH: /d/VisualStudio/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/
PATH: /d/VisualStudio/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/
PATH: /d/VisualStudio/Community/Common7/IDE/VC/Linux/bin/ConnectionManagerExe/
PATH: /d/VisualStudio/Community/VC/vcpkg/
PATH: /d/VisualStudio/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/
PATH: /e/vcpkgnew/downloads/tools/msys2/6f3fa1a12ef85a6f/mingw32/bin/


## ----------- ##
## Core tests. ##
## ----------- ##

configure:3775: looking for aux files: config.rpath ltmain.sh config.guess config.sub compile missing install-sh
configure:3788:  trying ./../src/v1.17-84a471678e.clean/build-aux/
configure:3817:   ./../src/v1.17-84a471678e.clean/build-aux/config.rpath found
configure:3817:   ./../src/v1.17-84a471678e.clean/build-aux/ltmain.sh found
configure:3817:   ./../src/v1.17-84a471678e.clean/build-aux/config.guess found
configure:3817:   ./../src/v1.17-84a471678e.clean/build-aux/config.sub found
configure:3817:   ./../src/v1.17-84a471678e.clean/build-aux/compile found
configure:3817:   ./../src/v1.17-84a471678e.clean/build-aux/missing found
configure:3799:   ./../src/v1.17-84a471678e.clean/build-aux/install-sh found
configure:3948: checking for a BSD-compatible install
configure:4021: result: /usr/bin/install -c
configure:4032: checking whether build environment is sane
configure:4087: result: yes
configure:4143: checking for i686-pc-mingw32-strip
configure:4175: result: :
configure:4246: checking for a race-free mkdir -p
configure:4290: result: /usr/bin/mkdir -p
configure:4297: checking for gawk
configure:4318: found /usr/bin/gawk
configure:4329: result: gawk
configure:4340: checking whether make sets $(MAKE)
configure:4363: result: yes
configure:4393: checking whether make supports nested variables
configure:4411: result: yes
configure:4549: checking whether make sets $(MAKE)
configure:4572: result: yes
configure:4600: checking for i686-pc-mingw32-gcc
configure:4632: result: compile cl.exe
configure:5030: checking for C compiler version
configure:5039: compile cl.exe --version >&5
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '--version'
cl : Command line error D8003 : missing source filename
configure:5050: $? = 2
configure:5039: compile cl.exe -v >&5
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-v'
cl : Command line error D8003 : missing source filename
configure:5050: $? = 2
configure:5039: compile cl.exe -V >&5
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line error D8004 : '/V' requires an argument
configure:5050: $? = 2
configure:5039: compile cl.exe -qversion >&5
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-qversion'
cl : Command line error D8003 : missing source filename
configure:5050: $? = 2
configure:5039: compile cl.exe -version >&5
Microsoft (R) C/C++ Optimizing Compiler Version 19.36.32535 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9002 : ignoring unknown option '-version'
cl : Command line error D8003 : missing source filename
configure:5050: $? = 2
configure:5070: checking whether the C compiler works
configure:5092: compile cl.exe -Xcompiler -nologo -Xcompiler -W3 -Xcompiler -utf-8 -Xcompiler -MP -Xcompiler -MDd -Xcompiler -Z7 -Xcompiler -Ob0 -Xcompiler -Od -Xcompiler -RTC1 -DWIN32 -D_WINDOWS -D_DEBUG -Xlinker -Xlinker -Xlinker -LE:/vcpkgnew/installed/x86-windows/debug/lib -Xlinker -Xlinker -Xlinker -machine:X86 -Xlinker -Xlinker -Xlinker -nologo -Xlinker -Xlinker -Xlinker -debug -Xlinker -Xlinker -Xlinker -INCREMENTAL conftest.c -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -lcomdlg32 -ladvapi32 >&5
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
conftest.c
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
cl : Command line warning D9002 : ignoring unknown option '-Xcompiler'
conftest.c(1): warning C4828: The file contains a character starting at offset 0x29 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x30 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x36 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x5b that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x5e that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x65 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x69 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x6c that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x6d that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x71 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x76 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x7b that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x7d that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x84 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x86 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x87 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x8b that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x8e that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x91 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x94 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x98 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x9b that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x9c that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0x9e that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xa3 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xa5 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xa6 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xab that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xaf that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xb3 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xb4 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xb5 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xb6 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xba that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xbf that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xc0 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xc7 that is illegal in the current source character set (codepage 65001).
conftest.c(1): warning C4828: The file contains a character starting at offset 0xcb that is illegal in the current source character set (codepage 65001).
conftest.c(1): error C2018: unknown character '0x14'
conftest.c(1): error C2014: preprocessor command must start as first nonwhite space
conftest.c(1): error C2018: unknown character '0x1'
conftest.c(1): error C2061: syntax error: identifier 'E'
conftest.c(1): error C2059: syntax error: ';'
conftest.c(1): error C2059: syntax error: '-'
conftest.c(1): error C2018: unknown character '0xa6'
conftest.c(1): error C2018: unknown character '0x40'
configure:5096: $? = 2
configure:5136: result: no
configure: failed program was:
| b#eZ
