### ISSUE TITLE
tiff :  Problem downloading (libtiff-v4.5.0.tar.gz)

### ISSUE THREAD

**Issue by SKNo** [microsoft/vcpkg#30489] opened 2023-03-28 16:55 UTC
**Describe the bug**
Hello
I am trying to install tiff library for x64-windows (as a prerequist for gdal)
It seems that expected and actual hash for the file libtiff-v4.5.0.tar.gz are not correct (because of partial download). So after partial downloding the anti-virus kicks in. I was wondering if anyone else has the same issue or there is a workaround.

**Environment**
- OS: Windows
- Compiler: cl 19.35.32216.1

**To Reproduce**
1. ./vcpkg install tiff:x64-windows 
2. 

**Expected behavior**

**Failure logs**
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/11092233/stdout-x64-windows.log)
[libtiff-libtiff-v4.5.0.tar.gz.25824.txt](https://github.com/microsoft/vcpkg/files/11092255/libtiff-libtiff-v4.5.0.tar.gz.25824.txt)

**Additional context**
This happens since libtiff version 4.5.0.

**Comment by sbrajchuk** [comment] 2023-03-28 19:49
I think we must compare old version of https://gitlab.com/libtiff/libtiff/-/archive/v4.5.0/libtiff-v4.5.0.tar.gz with new one.

**Comment by StarGate-One** [comment] 2023-03-28 20:22
Here is the file with the SHA512 hash `5227CB7B496AC6829601D8D689233BD8F318C1D04E5CE3457CDD6EAC9E4F8C80CD7211D90CD092C61AD38BC8A4949169A13EABD788C46C15BCEE1F72519FA022` from the portfile.cmake downloaded on 20230220:
[libtiff-libtiff-v4.5.0.tar.gz](https://github.com/microsoft/vcpkg/files/11093852/libtiff-libtiff-v4.5.0.tar.gz)

**Comment by sbrajchuk** [comment] 2023-03-28 20:33
So the content of the tar file in both files is the same, but the gzip compression is different.

**Comment by StarGate-One** [comment] 2023-03-28 21:13
Since this file is downloaded from GitLab I assume this is related to [build failure of projects hosted on gitlab and referenced by tag #30481](https://github.com/microsoft/vcpkg/issues/30481).

**Comment by debangsha-versatile** [comment] 2023-03-28 21:42
One (very bad) way to solve the error is to change the expected hash value to the actual hash value. 
`vcpkg_from_gitlab(
    GITLAB_URL https://gitlab.com
    OUT_SOURCE_PATH SOURCE_PATH
    REPO libtiff/libtiff
    REF "v${VERSION}"
    SHA512 5227cb7b496ac6829601d8d689233bd8f318c1d04e5ce3457cdd6eac9e4f8c80cd7211d90cd092c61ad38bc8a4949169a13eabd788c46c15bcee1f72519fa022
    HEAD_REF master
    PATCHES
        FindCMath.patch
)`

**Comment by sbrajchuk** [comment] 2023-03-28 21:43
As I understand it, the hash `c4b211019892f4cdb5a21b3b9746ef3ca9995ece802a48a5c0eb35e69a3f7ba0df415f2eb9714ab943a2a56d2cebbeaa9c39ce00cdaf43a1515a9714ea2819da` is the hash of the [libtiff-libtiff-v4.5.0.tar.gz.25824.txt](https://github.com/microsoft/vcpkg/files/11092255/libtiff-libtiff-v4.5.0.tar.gz.25824.txt)  that was already uploaded by @SKNo, and in his case, the issue is related to antivirus software.

**Comment by SKNo** [comment] 2023-03-28 21:58
Hi @sbrajchuk 
I cannot dowload it because as soon as hash are different, the anti-virus kicks-in so I have no file to upload (I am using company's computer)
I will look at it again tomorrow
Cheers

**Comment by Cheney-W** [comment] 2023-03-29 02:53
Duplicate of https://github.com/microsoft/vcpkg/issues/30481

Please track this issue with https://gitlab.com/gitlab-org/gitlab/-/issues/402616

**Closed by Cheney-W** 2023-03-29 02:53 UTC
Labels: category:question
