### ISSUE TITLE
vcpkg install --head does not work if there are multiple vcpkg_from_github in the port file

### ISSUE THREAD

**Issue by jasjuang** [microsoft/vcpkg#1771] opened 2017-09-03 21:04 UTC
This is related to #1619.

For OpenCV there is a vcpkg_from_github call for opencv and a vcpkg_from_github call for opencv_contrib. If I attempt to install opencv with `vcpkg install opencv --head`

Only the `opencv_contrib-master` folder is present in `C:\dev\vcpkg\buildtrees\opencv\src\head`, which means the `opencv-master` folder is missing, causing a configuration error as shown in `C:\dev\vcpkg\buildtrees\opencv\config-x64-windows-rel-err.log`

``````
CMake Error: The source directory "C:/dev/vcpkg/buildtrees/opencv/src/head/opencv-master" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
``````

Below is the verbose message when I did `vcpkg install opencv --head`

``````
The following packages will be built and installed:
    opencv:x64-windows
Building package opencv:x64-windows from HEAD...
-- CURRENT_INSTALLED_DIR=C:/dev/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/dev/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/dev/vcpkg/packages/opencv_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/dev/vcpkg/buildtrees/opencv
-- CURRENT_PORT_DIR=C:/dev/vcpkg/ports/opencv/.
-- Downloading https://github.com/opencv/opencv/archive/master.tar.gz...
-- Downloading https://github.com/opencv/opencv/archive/master.tar.gz... OK
-- Extracting source C:/dev/vcpkg/downloads/opencv-opencv-master.tar.gz
-- Extracting done
-- Applying patch C:/dev/vcpkg/ports/opencv/opencv-installation-options.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/dev/vcpkg/ports/opencv/opencv-installation-options.patch done
-- Applying patch C:/dev/vcpkg/ports/opencv/001-fix-uwp.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/dev/vcpkg/ports/opencv/001-fix-uwp.patch done
-- Applying patch C:/dev/vcpkg/ports/opencv/002-fix-uwp.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/dev/vcpkg/ports/opencv/002-fix-uwp.patch done
-- Downloading https://github.com/opencv/opencv_contrib/archive/master.tar.gz...
-- Downloading https://github.com/opencv/opencv_contrib/archive/master.tar.gz... OK
-- Extracting source C:/dev/vcpkg/downloads/opencv-opencv_contrib-master.tar.gz
-- Extracting done
-- Applying patch C:/dev/vcpkg/ports/opencv/open_contrib-remove-waldboost.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/dev/vcpkg/ports/opencv/open_contrib-remove-waldboost.patch done
-- Configuring x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;C:/dev/vcpkg/buildtrees/opencv/src/head/opencv-master;-DBUILD_ZLIB=OFF;-DBUILD_TIFF=OFF;-DBUILD_JPEG=OFF;-DBUILD_PNG=OFF;-DBUILD_opencv_python2=OFF;-DBUILD_opencv_python3=OFF;-DBUILD_opencv_flann=ON;-DBUILD_opencv_apps=OFF;-DBUILD_DOCS=OFF;-DBUILD_EXAMPLES=OFF;-DBUILD_PACKAGE=OFF;-DBUILD_PERF_TESTS=OFF;-DBUILD_TESTS=OFF;-DBUILD_WITH_DEBUG_INFO=ON;-DOpenCV_DISABLE_ARCH_PATH=ON;-DWITH_FFMPEG=ON;-DINSTALL_FORCE_UNIX_PATHS=ON;-DOPENCV_CONFIG_INSTALL_PATH=share/opencv;-DOPENCV_OTHER_INSTALL_PATH=share/opencv;-DINSTALL_LICENSE=OFF;-DWITH_CUDA=OFF;-DWITH_CUBLAS=OFF;-DWITH_OPENCLAMDBLAS=OFF;-DWITH_LAPACK=OFF;-DBUILD_opencv_dnn=ON;-DOPENCV_EXTRA_MODULES_PATH=C:/dev/vcpkg/buildtrees/opencv/src/head/opencv_contrib-master/modules;-DBUILD_PROTOBUF=OFF;-DUPDATE_PROTO_FILES=ON;-DPROTOBUF_UPDATE_FILES=ON;-DBUILD_SHARED_LIBS=ON;-DVCPKG_TARGET_TRIPLET=x64-windows;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Zi ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Visual Studio 14 2015 Win64;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/dev/vcpkg/packages/opencv_x64-windows
    Working Directory: C:/dev/vcpkg/buildtrees/opencv/x64-windows-rel
    See logs for more information:
      C:\dev\vcpkg\buildtrees\opencv\config-x64-windows-rel-out.log
      C:\dev\vcpkg\buildtrees\opencv\config-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:170 (vcpkg_execute_required_process)
  ports/opencv/portfile.cmake:36 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)


Error: Building package opencv:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencv:x64-windows
  Vcpkg version: 0.0.85-2017-08-29-526b1436a16b5c60760cbfc16a7f64e49cf13a01

Additionally, attach any relevant sections from the log files above.
``````

**Comment by jasjuang** [comment] 2017-09-29 16:33
@ras0219-msft @alexkaratarakis Can you let me know which file defines the command `vcpkg install --head`? I will try and see if I can fix this.

**Comment by KindDragon** [comment] 2017-09-29 16:49
It's probably related to that script:

https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_from_github.cmake#L92-L95

**Comment by KindDragon** [comment] 2017-09-29 16:52
Check `VCPKG_USE_HEAD_VERSION` value inside vcpkg_from_github.cmake for each call `vcpkg_from_github`

**Comment by NancyLi1013** [comment] 2020-05-27 02:44
@KindDragon 
Could you please try to update vcpkg and rebuild this?

I cannot reproduce this issue on my local machine with the command `vcpkg install opencv --head` now.

**Comment by NancyLi1013** [comment] 2020-05-27 09:54
I'm closing this issue for now. Since it should be fixed. Please reopen this issue if it is still a problem for you.

**Closed by NancyLi1013** 2020-05-27 09:54 UTC
Labels: category:vcpkg-bug, requires:repro
