### ISSUE TITLE
[New Port Request] <ZeroC-ICE>

### ISSUE THREAD

**Issue by zlinwei** [microsoft/vcpkg#8117] opened 2019-09-10 10:13 UTC
Library name: ZeroC-ICE

Library description: RPC Framework

Source repository URL: https://github.com/zeroc-ice/ice.git

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by davidebeatrici** [comment] 2019-11-15 03:07
Duplicate of #6106.

**Comment by LilyWangL** [comment] 2019-12-03 02:50
Closed as duplicate of #6106.

**Closed by LilyWangL** 2019-12-03 02:50 UTC
Labels: new port request - consider making a PR!
