### ISSUE TITLE
vcpkg silently fails to install any package with visual studio 2022 

### ISSUE THREAD

**Issue by ZeeWanderer** [microsoft/vcpkg#18804] opened 2021-07-04 17:43 UTC
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 19.29.30130.2
- vcpkg: 2021-06-29
- cmake: 3.21.0-rc2

**To Reproduce**
Steps to reproduce the behaviour:
Install Visual Studio 2022 Preview 1.1 and ensure it is the only visual studio installed.
Try to install any package, for example:
`./vcpkg install blend2d:x64-windows`

**Failure logs** 
No failure logs, vcpkg output:
```
Computing installation plan...
```
`errorlevel` on exit is `-1073741819`
and there is some sort of intermediate cmake file directly in `./buildtrees`
[0.vcpkg_tags.cmake.txt](https://github.com/microsoft/vcpkg/files/6760352/0.vcpkg_tags.cmake.txt)

**Comment by autoantwort** [comment] 2021-07-04 18:10
Maybe a duplicate of #18636

**Comment by ZeeWanderer** [comment] 2021-07-04 18:39
@autoantwort hhhm maybe, i am using 3.21.0-rc2 since that is the only version that supports vs2022. 3.21.0 is planned in 10 days according to their gitlab so i guess i would need to wait and see if the issue persists with release cmake version too.

**Comment by JonLiu1993** [comment] 2021-07-05 07:53
@ZeeWanderer ,Thanks for posting this issue,Could you please run "./vcpkg install blend2d:x64-windows --debug" then provide the complete log?

**Comment by JonLiu1993** [comment] 2021-07-05 08:26
@ZeeWanderer ,Could you please run the command "./vcpkg install blend2d:x64-windows --debug " and provide the log?

**Comment by ZeeWanderer** [comment] 2021-07-05 13:35
@JonLiu1993 
[vcpkg_log.txt](https://github.com/microsoft/vcpkg/files/6764543/vcpkg_log.txt)

**Comment by JonLiu1993** [comment] 2021-07-06 02:13
@ZeeWanderer , thanks for your response!

Could you try to download vcpkg.exe from https://github.com/microsoft/vcpkg-tool/releases/tag/2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9 and replace the one in your local machine, and see if the issue persist?

I can't repro this issue locally

**Comment by ZeeWanderer** [comment] 2021-07-06 02:32
@JonLiu1993 tried with the specified vcpkg version, the issue persists.
Error log is the same:
```
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: E:\Tools\vcpkg
[DEBUG] Using installed-root: E:\Tools\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: E:\Tools\vcpkg\buildtrees
[DEBUG] Using downloads-root: E:\Tools\vcpkg\downloads
[DEBUG] Using packages-root: E:\Tools\vcpkg\packages
[DEBUG] Using scripts-root: E:\Tools\vcpkg\scripts
[DEBUG] Using ports-root: E:\Tools\vcpkg\ports
[DEBUG] Using versions-root: E:\Tools\vcpkg\versions
[DEBUG] Default binary cache path is: C:\Users\Max\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: C:\PROGRA~1\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("C:\PROGRA~1\CMake\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    72446 us
[DEBUG] CreateProcessW("C:\PROGRA~1\CMake\bin\cmake.exe" -DVCPKG_ROOT_DIR=E:/Tools/vcpkg -DPACKAGES_DIR=E:/Tools/vcpkg/packages -DBUILDTREES_DIR=E:/Tools/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=E:/Tools/vcpkg/installed -DDOWNLOADS=E:/Tools/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "E:\Tools\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    48131 us
```

**Comment by JonLiu1993** [comment] 2021-07-06 02:38
@ZeeWanderer ,Thanks for your information, please wait for the 3.21.0 version to be released and try again.

**Comment by PhoebeHui** [comment] 2021-07-06 06:17
See https://github.com/microsoft/vcpkg/issues/18774#issuecomment-873847591

**Closed** 2021-07-08 06:08 UTC
Labels: requires:repro
