### ISSUE TITLE
Error: Building package zlib:x64-windows-v140 failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by rianneogi** [Microsoft/vcpkg#1828] opened 2017-09-16 13:32 UTC
Trying to build for v140 platform toolset.
I'm using the following command: vcpkg install boost:x64-windows-v140

Heres is my triplet 'x64-windows-v140.cmake':
`set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v140)`

Here is the error log:
`CMake Error at CMakeLists.txt:4 (project):
  Failed to run MSBuild command:
    MSBuild.exe
  to get the value of VCTargetsPath:
`

Here is the out log:
`-- Configuring incomplete, errors occurred!
See also "C:/Documents/Code/Clones/vcpkg/buildtrees/zlib/x64-windows-v140-rel/CMakeFiles/CMakeOutput.log".
`

I did git pull, so my vcpkg is up to date.
I can build boost for the other triplets, but I get an error when I set toolset to v140. (I have the toolset v140 installed on the computer)

**Comment by alexkaratarakis** [comment] 2017-09-26 03:09
I can reproduce this. Investigating.

**Comment by alexkaratarakis** [comment] 2017-09-28 01:59
The issue should be fixed with f160164219ab0c8422fdcefde3a3def89e5a59de.
Please test with latest master to see if the issue is resolved for you.
(You will need to rerun `.\bootstrap-vcpkg.bat` after `git pull`).

**Closed** 2017-11-03 19:40 UTC
