### ISSUE TITLE
[liblzma] build failure

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#29866] opened 2023-02-26 04:12 UTC
**Host Environment**

- OS:  7.9.2009
- Compiler:  8.3.0 20190222

**To Reproduce**

./vcpkg install liblzma

This is the same issue as noted here - https://github.com/microsoft/vcpkg/issues/21680
The compiler needs to be set to C11 and the default on this system is C99

Updating the fix_config_include.patch to force C11 fixes the issues. I've included the patch

[fix_config_include.patch](https://github.com/microsoft/vcpkg/files/10832937/fix_config_include.patch)

**Comment by autoantwort** [comment] 2023-02-26 11:06
On the other issue C99 also was enough. Can you test it with C99

**Comment by diehard2** [comment] 2023-02-26 14:39
Good call, I verified the patch also works with C99

**Comment by LilyWangLL** [comment] 2023-02-28 07:54
> Hi, XZ Utils co-maintainer here. The problem is our CMakeLists.txt does not currently enforce the requirement for a compiler that supports C99 or add the flags needed to ensure C99. The API header files from liblzma do not require C99, just the source code and internal headers. Our Autotools build system enforces the need for a C99 compiler.
> 
> We are planning a new 5.4.2 release soon, so we will make sure to include a fix for this.

This [comment](https://github.com/microsoft/vcpkg/issues/21680#issuecomment-1446344841) comes from maintainer of `liblzma`.

Thanks for posting this issue. This issue will be fixed in the new version of `liblzma`, closed this issue as duplicate of #21680, let us look forward to the new version together.

**Closed by LilyWangLL** 2023-02-28 07:54 UTC
Labels: category:port-bug
