### ISSUE TITLE
[boost-regex]Error build on visual studio 2019

### ISSUE THREAD

**Issue by viacheslav1988** [microsoft/vcpkg#6021] opened 2019-04-09 19:07 UTC
I am trying to install on Visual Studio 2019 boost, but the installation stops at "regex" with this error.

log [http://sendfile.su/1487689](url)

Starting package 34/144: boost-regex:x86-windows
Building package boost-regex[core]:x86-windows...
-- Downloading https://github.com/boostorg/regex/archive/boost-1.69.0.tar.gz...
-- Extracting source C:/vcpkg-master/downloads/boostorg-regex-boost-1.69.0.tar.gz
-- Using source at C:/vcpkg-master/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/vcpkg-master/installed/x86-windows/tools/boost-build/b2.exe;--stagedir=C:/vcpkg-master/buildtrees/boost-regex/x86-windows-rel/stage;--build-dir=C:/vcpkg-master/buildtrees/boost-regex/x86-windows-rel;--user-config=C:/vcpkg-master/buildtrees/boost-regex/x86-windows-rel/user-config.jam;-j2;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="C:/vcpkg-master/installed/x86-windows/include";-sBZIP2_INCLUDE="C:/vcpkg-master/installed/x86-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=32;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="C:/vcpkg-master/installed/x86-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="C:/vcpkg-master/installed/x86-windows/lib";variant=release;debug-symbols=on
    Working Directory: C:/vcpkg-master/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997/build
    Error code: 1
    See logs for more information:
      C:\vcpkg-master\buildtrees\boost-regex\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  installed/x86-windows/share/boost-build/boost-modular-build.cmake:270 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:71 (include)

Error: Building package boost-regex:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x86-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by ShinduHub** [comment] 2019-04-11 15:28
I have the same problem.

**Comment by viacheslav1988** [comment] 2019-04-11 15:34
I installed MSVC ver 140, and I managed to set the boost

**Comment by pratikpc** [comment] 2019-04-16 07:18
VS 2019 is not supported at this moment.
https://github.com/Microsoft/vcpkg/issues/6078

**Comment by bitsrules** [comment] 2019-04-17 23:37
What are the steps needed to get this working?

1. Update to boost 1.70
2. Update to cmake 3.14
3. Fix "something" in vcpkg

**Comment by bitsrules** [comment] 2019-04-25 00:05
VS 2019 is supported now with https://github.com/Microsoft/vcpkg/pull/6090 merged into master.

**Comment by xoration** [comment] 2019-05-02 15:35
I've switched to VS 2019 today and I have the same problem even though VS2019 seems to be supported now? 

Anyone has a working fix yet?

**Comment by pratikpc** [comment] 2019-05-02 15:38
> VS 2019 is supported now with #6090 merged into master.

Not really. I was unable to install Boost.System which is a dependency of Microsoft C++Rest SDK

**Comment by fwosar** [comment] 2019-05-02 17:17
Boost 1.70 support Visual Studio 2019. The problem is that the boost ports in vcpkg haven't been updated. There is a pull request, but that one hasn't been updated for a week either with one issue still being open. 

You can technically take the ports files from that pull request and overwrite the existing ones on your local installation and use them to compile boost 1.70, which is what I did. Keep in mind, that it may break other builds depending on boost that haven't been updated yet.

**Comment by polortiz4** [comment] 2019-05-07 21:22
I tried upgrading vcpkg through git pull and .\vcpkg upgrade --no-dry-run.. It looks like it downloaded new ports for boost. But then as soon as I tried .\vcpkg install boost, it gave me the same error as before. 
I don't think VS2019 is supported, like some have suggested

**Comment by bitsrules** [comment] 2019-05-07 22:54
vcpkg needs update to Boost 1.70 before it will work with VC2019.

**Comment by polortiz4** [comment] 2019-05-30 02:52
After vcpkg updated to Boost 1.70, I'm still getting the same error... Was this issue solved for someone else after the update? @fwosar, could you please point out which pull request you are referring to? 
Thank you

**Comment by PhoebeHui** [comment] 2020-05-21 05:58
@viacheslav1988, boost currently upgrade to 1_73, could you get latest source and try again? 

I tired and it built successfully with VS2019 16.6.0.

**Comment by PhoebeHui** [comment] 2020-06-11 10:13
@viacheslav1988, feel free to reopen this issue if it still be a problem for you.

**Closed by PhoebeHui** 2020-06-11 10:13 UTC
Labels: requires:repro
