### ISSUE TITLE
[tensorflow-cc] Build error undefined reference to mlir

### ISSUE THREAD

**Issue by aluchko** [microsoft/vcpkg#22867] opened 2022-01-31 02:07 UTC
**Host Environment**
- OS: [Ubuntu 21.10
- Compiler: gcc version 11.2.0 (Ubuntu 11.2.0-7ubuntu2) 

**To Reproduce**
`./vcpkg install tensorflow-cc`

**Failure logs** 
```
Execution platform: @local_execution_config_platform//:platform
tensorflow/compiler/mlir/tensorflow/analysis/resource_alias_analysis.cc:271: error: undefined reference to 'mlir::TF::detail::ResourceAliasAnalysisInfo::kMaxResourceTypeId'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 2359.499s, Critical Path: 397.92s
INFO: 5830 processes: 382 internal, 5448 local.
```

**Comment by JonLiu1993** [comment] 2022-03-04 07:09
Duplicate of #23300

**Closed by JonLiu1993** 2022-03-04 07:09 UTC
Labels: category:port-feature

**Comment by nxt007** [comment] 2022-05-26 12:04
Fix reported in https://github.com/microsoft/vcpkg/issues/23300 do not work. Also error reported in https://github.com/microsoft/vcpkg/issues/23300 do not match current error.
Seems to be false reported as duplicate. 

Facing same error on:
```
Ubuntu 22.04
gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
```
Reproduce step:
```
vcpkg install tensorflow-cc
```

Full log:
```
vcpkg install tensorflow-cc
Computing installation plan...
A suitable version of cmake was not found (required v3.22.2). Downloading portable cmake v3.22.2...
Downloading cmake...
  https://github.com/Kitware/CMake/releases/download/v3.22.2/cmake-3.22.2-linux-x86_64.tar.gz -> /home/dmbarinov/Projects/vcpkg/downloads/cmake-3.22.2linux-x86_64.tar.gz
Extracting cmake...
The following packages will be built and installed:
    tensorflow-cc[core]:x64-linux -> 2.7.0#2
  * tensorflow-common[core]:x64-linux -> 2.7.0#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/dmbarinov/.cache/vcpkg/archives in 15.95 us. Use --debug to see more details.
Installing 1/2 tensorflow-common:x64-linux...
Building tensorflow-common[core]:x64-linux...
-- Installing: /home/dmbarinov/Projects/vcpkg/packages/tensorflow-common_x64-linux/share/tensorflow-common/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /home/dmbarinov/.cache/vcpkg/archives/55/550beca591710f0febf0b32bb4abd106ca6910acd3cc011a8354ce32ddc9d1da.zip
Elapsed time to handle tensorflow-common:x64-linux: 13.41 ms
Installing 2/2 tensorflow-cc:x64-linux...
Building tensorflow-cc[core]:x64-linux...
-- Downloading https://github.com/tensorflow/tensorflow/archive/v2.7.0.tar.gz -> tensorflow-tensorflow-v2.7.0.tar.gz...
-- Extracting source /home/dmbarinov/Projects/vcpkg/downloads/tensorflow-tensorflow-v2.7.0.tar.gz
-- Applying patch /home/dmbarinov/Projects/vcpkg/installed/x64-linux/share/tensorflow-common/fix-build-error.patch
-- Applying patch /home/dmbarinov/Projects/vcpkg/installed/x64-linux/share/tensorflow-common/change-macros-for-static-lib.patch
-- Using source at /home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/src/v2.7.0-8c27530f06.clean
-- Configuring TensorFlow (dbg)
-- Warning: Building TensorFlow can take an hour or more.
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: /usr/local/bin/bazel --output_user_root=/home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/.bzl --max_idle_secs=1 build -s --verbose_failures --compilation_mode=dbg --python_path=/home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/x64-linux-venv/bin/python3 --define=no_tensorflow_py_deps=true //tensorflow:libtensorflow_cc.so //tensorflow:install_headers
    Working Directory: /home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/x64-linux-dbg
    See logs for more information:
      /home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/build-x64-linux-dbg-err.log

Call Stack (most recent call first):
  installed/x64-linux/share/tensorflow-common/tensorflow-common.cmake:280 (vcpkg_execute_build_process)
  ports/tensorflow-cc/portfile.cmake:9 (include)
  scripts/ports.cmake:146 (include)


error: building tensorflow-cc:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tensorflow-cc
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[tensorflow-cc]+Build+error
Include '[tensorflow-cc] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: 20907dc 2022-05-25 (14 hours ago)
```

Last lines of build-x64-linux-dbg-err.log:
```
SUBCOMMAND: # //tensorflow:libtensorflow_cc.so.2.7.0 [action 'Linking tensorflow/libtensorflow_cc.so.2.7.0', configuration: 1e132fcfb5c939ae24166d4360df798f188c556537577d9a5559082915280261, execution platform: @local_execution_config_platform//:platform]
(cd /home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/.bzl/06db2fa6195445efe3f1a1b8f5d73a73/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/dmbarinov/.cache/bazelisk/downloads/bazelbuild/bazel-3.7.2-linux-x86_64/bin:/home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/x64-linux-venv/bin:/usr/bin:/usr/local/bin:/home/dmbarinov/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/x64-linux-venv/bin/python3 \
    PYTHON_LIB_PATH=/home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/x64-linux-venv/lib/python3.10/site-packages \
    TF2_BEHAVIOR=1 \
  /usr/bin/gcc @bazel-out/k8-dbg/bin/tensorflow/libtensorflow_cc.so.2.7.0-2.params)
[5,829 / 5,832] Linking tensorflow/libtensorflow_cc.so.2.7.0; 45s local
ERROR: /home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/x64-linux-dbg/tensorflow/BUILD:1039:20: Linking of rule '//tensorflow:libtensorflow_cc.so.2.7.0' failed (Exit 1): gcc failed: error executing command 
  (cd /home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/.bzl/06db2fa6195445efe3f1a1b8f5d73a73/execroot/org_tensorflow && \
  exec env - \
    PATH=/home/dmbarinov/.cache/bazelisk/downloads/bazelbuild/bazel-3.7.2-linux-x86_64/bin:/home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/x64-linux-venv/bin:/usr/bin:/usr/local/bin:/home/dmbarinov/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin \
    PWD=/proc/self/cwd \
    PYTHON_BIN_PATH=/home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/x64-linux-venv/bin/python3 \
    PYTHON_LIB_PATH=/home/dmbarinov/Projects/vcpkg/buildtrees/tensorflow-cc/x64-linux-venv/lib/python3.10/site-packages \
    TF2_BEHAVIOR=1 \
  /usr/bin/gcc @bazel-out/k8-dbg/bin/tensorflow/libtensorflow_cc.so.2.7.0-2.params)
Execution platform: @local_execution_config_platform//:platform
tensorflow/compiler/mlir/tensorflow/analysis/resource_alias_analysis.cc:271: error: undefined reference to 'mlir::TF::detail::ResourceAliasAnalysisInfo::kMaxResourceTypeId'
collect2: error: ld returned 1 exit status
INFO: Elapsed time: 2019.626s, Critical Path: 284.95s
INFO: 5830 processes: 382 internal, 5448 local.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```
