### ISSUE TITLE
[openssl] Build error building openssl:x64-windows failed with: BUILD_FAILED nasm-2.16.01

### ISSUE THREAD

**Issue by deadcodes** [microsoft/vcpkg#32745] opened 2023-07-25 08:59 UTC
Package: openssl:x64-windows -> 3.1.1#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32535.0
-    vcpkg-tool version: 2023-07-19-814b7ec837b59f1c8778f72351c1dd7605983cd2
    vcpkg-scripts version: b7dba7f9a 2023-07-24 (14 hours ago)

**To Reproduce**

`vcpkg install grpc`

**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.1.1.tar.gz.
-- Cleaning sources at F:/Runescape/MECMake/vcpkg/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Runescape/MECMake/vcpkg/downloads/openssl-openssl-openssl-3.1.1.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at F:/Runescape/MECMake/vcpkg/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip -> nasm-2.16.01-win64.zip...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from F:\Runescape\MECMake\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: F:\Runescape\MECMake\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1045): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 3147us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.5 min (91432902us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_find_acquire_program.cmake:172 (vcpkg_download_distfile)
  ports/openssl/windows/portfile.cmake:1 (vcpkg_find_acquire_program)
  ports/openssl/portfile.cmake:68 (include)
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by jimwang118** [comment] 2023-07-25 09:21
duplicate of https://github.com/microsoft/vcpkg/issues/32741

**Closed by jimwang118** 2023-07-25 09:21 UTC
