### ISSUE TITLE
[abseil] error: building abseil:x64-windows failed

### ISSUE THREAD

**Issue by rgutt** [microsoft/vcpkg#39661] opened 2024-07-03 05:35 UTC
I'm trying to build the latest version of abseil using the most recent version of vcpkg. 

I get the following error message:
```
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:287 (vcpkg_execute_required_process)
  ports/abseil/portfile.cmake:29 (vcpkg_cmake_configure)
  scripts/ports.cmake:192 (include)
```

In the error log "config.x64-windows-dbg-err.log" it says:

```
CMake Error at CMake/AbseilHelpers.cmake:317 (target_link_libraries):
  The link interface of target "test_allocator" contains:

    GTest::gmock

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.
```

I tried installing gtest manually using:

`.\vcpkg.exe install gtest`

The installation succeeded but it did not resolve the issue.

I still could not build abseil.

[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/user-attachments/files/16077503/config-x64-windows-dbg-CMakeCache.txt.log)
[config-x64-windows-dbg-CMakeConfigureLog.yaml.log](https://github.com/user-attachments/files/16077504/config-x64-windows-dbg-CMakeConfigureLog.yaml.log)
[config-x64-windows-dbg-err.log](https://github.com/user-attachments/files/16077506/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/user-attachments/files/16077507/config-x64-windows-dbg-out.log)

**Comment by MonicaLiu0311** [comment] 2024-07-03 06:35
Duplicate of #39452.

**Closed by MonicaLiu0311** 2024-07-03 06:35 UTC
Labels: category:port-bug
