### ISSUE TITLE
[aws-c-common:x64-windows] build failure

### ISSUE THREAD

**Issue by Shortz79** [microsoft/vcpkg#15264] opened 2020-12-23 08:18 UTC
**Host Environment**
- OS : Windows
- Compiler: MSVC2019

**To Reproduce**
`.\vcpkg install aws-c-common:x64-windows

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    aws-c-common[core]:x64-windows -> 0.4.56
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\...l\vcpkg\archives\f8\f8ec6de18c2e13209083d3daf486d49ce414a645.zip
Starting package 1/1: aws-c-common:x64-windows
Building package aws-c-common[core]:x64-windows...
-- Using cached C:/Users/.../vcpkg/downloads/awslabs-aws-c-common-4a21a1c0757083a16497fea27886f5f20ccdf334.tar.gz
-- Cleaning sources at C:/Users/...p/vcpkg/buildtrees/aws-c-common/src/f20ccdf334-c310c32102.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/.../vcpkg/downloads/awslabs-aws-c-common-4a21a1c0757083a16497fea27886f5f20ccdf334.tar.gz
-- Applying patch disable-error-4068.patch
-- Applying patch disable-internal-crt-option.patch
-- Applying patch fix-cmake-target-path.patch
-- Using source at C:/Users/.../vcpkg/buildtrees/aws-c-common/src/f20ccdf334-c310c32102.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/.../vcpkg/buildtrees/aws-c-common/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\...\vcpkg\buildtrees\aws-c-common\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
  ports/aws-c-common/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)

Error: Building package aws-c-common:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: aws-c-common:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Already using git pull to update the vcpkg to newest version.
But still same failure.

**Comment by NancyLi1013** [comment] 2020-12-23 10:38
Hi @Shortz79 

Thanks for posting this issue.

I cannot reproduce this on my machine.

Could you please attach the log `C:\Users...\vcpkg\buildtrees\aws-c-common\config-x64-windows-out.log`?

**Comment by Shortz79** [comment] 2020-12-23 12:27
Here is the log
[1/2] cmd /c "cd ../../x64-windows-dbg && "C:/Users/Aemass/Documents/cmake-3.19.1-win32-x86/bin/cmake.exe" "C:/Users/Aemass/Kevin/temp/vcpkg/buildtrees/aws-c-common/src/f20ccdf334-c310c32102.clean" "-DCMAKE_MAKE_PROGRAM=C:/Users/Aemass/Kevin/temp/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Aemass/Kevin/temp/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Aemass/Kevin/temp/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/Aemass/Kevin/temp/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/Aemass/Kevin/temp/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/Aemass/Kevin/temp/vcpkg/packages/aws-c-common_x64-windows/debug""
FAILED: ../../x64-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x64-windows-dbg && "C:/Users/Aemass/Documents/cmake-3.19.1-win32-x86/bin/cmake.exe" "C:/Users/Aemass/Kevin/temp/vcpkg/buildtrees/aws-c-common/src/f20ccdf334-c310c32102.clean" "-DCMAKE_MAKE_PROGRAM=C:/Users/Aemass/Kevin/temp/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Aemass/Kevin/temp/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Aemass/Kevin/temp/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/Aemass/Kevin/temp/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/Aemass/Kevin/temp/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=C:/Users/Aemass/Kevin/temp/vcpkg/packages/aws-c-common_x64-windows/debug""
-- The C compiler identification is MSVC 19.28.29335.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Success
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Failed
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Failed
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Failed
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Failed
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Building SIMD base64 decoder
-- Packaging is only supported on Linux
-- Configuring done
CMake Error: install(EXPORT "aws-c-common-targets" ...) includes target "aws-c-common" more than once in the export set.
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_LIBDIR


CMake Generate step failed.  Build files cannot be regenerated correctly.
[2/2] cmd /c "cd .. && "C:/Users/Aemass/Documents/cmake-3.19.1-win32-x86/bin/cmake.exe" "C:/Users/Aemass/Kevin/temp/vcpkg/buildtrees/aws-c-common/src/f20ccdf334-c310c32102.clean" "-DCMAKE_MAKE_PROGRAM=C:/Users/Aemass/Kevin/temp/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Aemass/Kevin/temp/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Aemass/Kevin/temp/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/Aemass/Kevin/temp/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/Aemass/Kevin/temp/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/Aemass/Kevin/temp/vcpkg/packages/aws-c-common_x64-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "C:/Users/Aemass/Documents/cmake-3.19.1-win32-x86/bin/cmake.exe" "C:/Users/Aemass/Kevin/temp/vcpkg/buildtrees/aws-c-common/src/f20ccdf334-c310c32102.clean" "-DCMAKE_MAKE_PROGRAM=C:/Users/Aemass/Kevin/temp/vcpkg/downloads/tools/ninja/1.10.1-windows/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/Users/Aemass/Kevin/temp/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/Users/Aemass/Kevin/temp/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/Users/Aemass/Kevin/temp/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/Users/Aemass/Kevin/temp/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/Users/Aemass/Kevin/temp/vcpkg/packages/aws-c-common_x64-windows""
-- The C compiler identification is MSVC 19.28.29335.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS
-- Performing Test AWS_HAVE_GCC_OVERFLOW_MATH_EXTENSIONS - Failed
-- Performing Test AWS_HAVE_MSVC_MULX
-- Performing Test AWS_HAVE_MSVC_MULX - Failed
-- Performing Test AWS_ARCH_INTEL
-- Performing Test AWS_ARCH_INTEL - Success
-- Performing Test AWS_ARCH_ARM64
-- Performing Test AWS_ARCH_ARM64 - Failed
-- Performing Test AWS_ARCH_ARM32
-- Performing Test AWS_ARCH_ARM32 - Failed
-- Performing Test AWS_HAVE_GCC_INLINE_ASM
-- Performing Test AWS_HAVE_GCC_INLINE_ASM - Failed
-- Performing Test AWS_HAVE_AUXV
-- Performing Test AWS_HAVE_AUXV - Failed
-- Performing Test AWS_HAVE_EXECINFO
-- Performing Test AWS_HAVE_EXECINFO - Failed
-- Performing Test HAVE_M_AVX2_FLAG
-- Performing Test HAVE_M_AVX2_FLAG - Success
-- Performing Test HAVE_AVX2_INTRINSICS
-- Performing Test HAVE_AVX2_INTRINSICS - Success
-- Performing Test HAVE_MM256_EXTRACT_EPI64
-- Performing Test HAVE_MM256_EXTRACT_EPI64 - Success
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Performing Test HAS_WGNU
-- Performing Test HAS_WGNU - Failed
-- Performing Test HAVE_SYSCONF
-- Performing Test HAVE_SYSCONF - Failed
-- Performing Test HAS_SANITIZERS
-- Performing Test HAS_SANITIZERS - Failed
-- Building SIMD base64 decoder
-- Packaging is only supported on Linux
-- Configuring done
CMake Error: install(EXPORT "aws-c-common-targets" ...) includes target "aws-c-common" more than once in the export set.
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_BINDIR
    CMAKE_INSTALL_LIBDIR


CMake Generate step failed.  Build files cannot be regenerated correctly.
ninja: build stopped: subcommand failed.

**Comment by Shortz79** [comment] 2020-12-23 12:36
At first I wants to install aws-sdk-cpp
so I use .\vcpkg\vcpkg install aws-sdk-cpp[s3]:x64
But I got the error like this so I went for focusing on aws-c-common:x64-windows
Here is the error code after I " .\vcpkg\vcpkg install aws-sdk-cpp[s3]:x64"
----------------------------------------------------------------------------------------------------------------------------------------
Computing installation plan...
The following packages will be built and installed:
  * aws-c-common[core]:x64-windows -> 0.4.56
  * aws-c-event-stream[core]:x64-windows -> 0.1.6
  * aws-checksums[core]:x64-windows -> 0.1.9
    aws-sdk-cpp[core,dynamodb,kinesis,s3]:x64-windows -> 1.8.83#4
  * zlib[core]:x64-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Aemass\AppData\Local\vcpkg\archives\f8\f8ec6de18c2e13209083d3daf486d49ce414a645.zip
Could not locate cached archive: C:\Users\Aemass\AppData\Local\vcpkg\archives\79\79f1c82d14f18ba8804b27a0f54557f31a55b59d.zip
Could not locate cached archive: C:\Users\Aemass\AppData\Local\vcpkg\archives\e9\e96be804e6af2bdcda556a6ba426e2254d5cb903.zip
Using cached binary package: C:\Users\Aemass\AppData\Local\vcpkg\archives\c3\c3e4e9c1d9363bf418d3562ccc1394e06d19fc51.zip
Could not locate cached archive: C:\Users\Aemass\AppData\Local\vcpkg\archives\3f\3ff0398953e368cf939e9349f359d7e13e574494.zip
Starting package 1/5: aws-c-common:x64-windows
Building package aws-c-common[core]:x64-windows...
-- Using cached C:/Users/Aemass/Kevin/temp/vcpkg/downloads/awslabs-aws-c-common-4a21a1c0757083a16497fea27886f5f20ccdf334.tar.gz
-- Cleaning sources at C:/Users/Aemass/Kevin/temp/vcpkg/buildtrees/aws-c-common/src/f20ccdf334-c310c32102.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Aemass/Kevin/temp/vcpkg/downloads/awslabs-aws-c-common-4a21a1c0757083a16497fea27886f5f20ccdf334.tar.gz
-- Applying patch disable-error-4068.patch
-- Applying patch disable-internal-crt-option.patch
-- Applying patch fix-cmake-target-path.patch
-- Using source at C:/Users/Aemass/Kevin/temp/vcpkg/buildtrees/aws-c-common/src/f20ccdf334-c310c32102.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: ninja -v
    Working Directory: C:/Users/Aemass/Kevin/temp/vcpkg/buildtrees/aws-c-common/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\Aemass\Kevin\temp\vcpkg\buildtrees\aws-c-common\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
  ports/aws-c-common/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:136 (include)


Error: Building package aws-c-common:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: aws-c-common:x64-windows
  Vcpkg version: 2020.11.12-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment] 2020-12-24 07:08
Hi @Shortz79 

Thanks for posting this issue.

```
-- Configuring done
CMake Error: install(EXPORT "aws-c-common-targets" ...) includes target "aws-c-common" more than once in the export set.
```
This is a cmake issue, which has been fixed in 3.19.2. Please see
https://github.com/awslabs/aws-c-common/issues/734 and https://github.com/lukka/get-cmake/pull/22.

**Comment by Shortz79** [comment] 2020-12-24 07:29
@NancyLi1013 Thanks for telling that, I had successfully build that.

**Comment by NancyLi1013** [comment] 2020-12-24 08:06
Closing this issue for it has been solved.

**Closed by NancyLi1013** 2020-12-24 08:06 UTC
Labels: requires:repro

**Comment by hmoffatt** [comment] 2021-04-22 02:06
@NancyLi1013 I have this problem too. cmake is provided by Visual Studio 2019, but the version included is not new enough. But vcpkg thinks it is. If I remove the Visual Studio cmake from my PATH then vcpkg will install 3.19.2 and then aws-c-common builds OK.

It seems like there must be a bug somewhere then, as the version of cmake provided by VS apparently satisfies the dependencies and yet it doesn't work.
