### ISSUE TITLE
Build fails because `python` is not on macOS (only python3)

### ISSUE THREAD

**Issue by rnikander** [microsoft/vcpkg#26907] opened 2022-09-21 17:28 UTC
**Describe the bug**

I had a working CMake build. I installed and used vcpkg according to the Getting started guide, and now I get this:

```
[1/1] Linking CXX executable MyApp/MyApp.app/Contents/MacOS/MyApp
FAILED: MyApp/MyApp.app/Contents/MacOS/MyApp 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -Wall -Wimplicit-fallthrough -Werror=return-type [...] cd /Users/rob/Workspace/MyApp/cmake-build-debug/MyApp && python /Users/rob/Dev/vcpkg/scripts/buildsystems/osx/applocal.py [...]
/bin/sh: python: command not found
```

**Environment**
- OS: macOS Ventura 13.0 
- Compiler: Apple clang version 14.0.0 (clang-1400.0.29.102)

I think the issue is this line:

https://github.com/microsoft/vcpkg/blob/82b7b4fbf53bd134e67b123a00cb15535cfaa6a5/scripts/buildsystems/vcpkg.cmake#L603

It's refers to python, but on my stock (+ Xcode) macOS system, there is no `python`, only `python3`. There was nothing in the Getting Started guide about installing python. Even with sudo, macOS seems to be preventing me from doing something like `ln -s /usr/bin/python3 /usr/bin/python`. Changing that line in vcpkg.cmake to `python3` seems to have fixed it for me. 

Maybe you need to add some kind of detection to see where python is exactly.

**Comment by autoantwort** [comment] 2022-09-22 00:09
Duplicate of #24696

**Comment by Adela0814** [comment] 2022-09-22 05:49
Closing this due to duplication.

**Closed by Adela0814** 2022-09-22 05:49 UTC
Labels: category:vcpkg-bug
