### ISSUE TITLE
[osg] Build error

### ISSUE THREAD

**Issue by newpeople123** [microsoft/vcpkg#32798] opened 2023-07-28 06:23 UTC
```
[82/1670] C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\cl.exe   /TP -DOSG_LIBRARY -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -Dosg_EXPORTS -IE:\SDK\vcpkg\buildtrees\osg\x64-windows-dbg\include -IE:\SDK\vcpkg\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /W4 /wd4589 /wd4706 /wd4127 /wd4100 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osg\CMakeFiles\osg.dir\Matrixd.cpp.obj /Fdsrc\osg\CMakeFiles\osg.dir\ /FS -c E:\SDK\vcpkg\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\src\osg\Matrixd.cpp
FAILED: src/osg/CMakeFiles/osg.dir/Matrixd.cpp.obj 
C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\cl.exe   /TP -DOSG_LIBRARY -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -Dosg_EXPORTS -IE:\SDK\vcpkg\buildtrees\osg\x64-windows-dbg\include -IE:\SDK\vcpkg\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /W4 /wd4589 /wd4706 /wd4127 /wd4100 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Fosrc\osg\CMakeFiles\osg.dir\Matrixd.cpp.obj /Fdsrc\osg\CMakeFiles\osg.dir\ /FS -c E:\SDK\vcpkg\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\src\osg\Matrixd.cpp
cl : Command line warning D9025 : overriding '/W3' with '/W4'
E:\SDK\vcpkg\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\src\osg\Matrix_implementation.cpp(70): warning C4003: not enough arguments for function-like macro invocation 'min'
E:\SDK\vcpkg\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\src\osg\Matrix_implementation.cpp(70): error C2589: '(': illegal token on right side of '::'
E:\SDK\vcpkg\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\src\osg\Matrix_implementation.cpp(70): error C2062: type 'unknown-type' unexpected
E:\SDK\vcpkg\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\src\osg\Matrix_implementation.cpp(70): error C2059: syntax error: ')'
E:\SDK\vcpkg\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\src\osg\Matrix_implementation.cpp(71): error C2143: syntax error: missing ';' before '{'
E:\SDK\vcpkg\buildtrees\osg\src\raph-3.6.5-41fa3cfd98.clean\src\osg\Matrix_implementation.cpp(76): error C2181: illegal else without matching if
```

**Comment by FrankXie05** [comment] 2023-07-28 08:56
@newpeople123 Could you please provide your compilation environment?
```
warning C4003: not enough arguments for function-like macro invocation 'min'
```

**Comment by FrankXie05** [comment] 2023-08-07 08:53
Duplicate of https://github.com/microsoft/vcpkg/issues/33008

**Closed by FrankXie05** 2023-08-07 08:53 UTC
Labels: requires:more-information
