### ISSUE TITLE
[libigl] update to v2.4.0

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#28584] opened 2022-12-27 20:00 UTC
Library name: libigl

New version number: 2.4.0

Other information that may be useful (release notes, etc...)
https://github.com/libigl/libigl/releases/tag/v2.4.0
This version perfectly work on Mac ARM too so please enable the port on Mac ARM

**Comment by FrankXie05** [comment] 2022-12-30 09:14
Will be fixed by PR https://github.com/microsoft/vcpkg/pull/27963

**Comment by FrankXie05** [comment] 2022-12-30 09:15
Duplicate of issue: https://github.com/microsoft/vcpkg/issues/23354

**Closed by FrankXie05** 2022-12-30 09:15 UTC
Labels: category:port-update
