### ISSUE TITLE
[zlib] build failure

### ISSUE THREAD

**Issue by sumitkang** [microsoft/vcpkg#12852] opened 2020-08-11 03:33 UTC
**Host Environment**
- OS: Windows
- Compiler: visual studio 2017

**To Reproduce**

.\vcpkg install ffmpeg

Error: Building package zlib:x86-windows failed with: BUILD_FAILED

log file
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/5054610/config-x86-windows-out.log)

**Comment by LilyWangL** [comment] 2020-08-11 07:05
Thanks for posting this issue. I cann't find error message in your config log, could you please provide the `stdout-x86-windows.log` and `install-x86-windows-dbg-out.log`?

**Comment by sumitkang** [comment] 2020-08-11 07:23
[stdout-x86-windows.log](https://github.com/microsoft/vcpkg/files/5055367/stdout-x86-windows.log)
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5055369/install-x86-windows-dbg-out.log)

@LilyWangL  Thanks , i have uploaded the logs

**Comment by LilyWangL** [comment] 2020-08-11 08:36
Closed as duplicate of #12709.

**Closed by LilyWangL** 2020-08-11 08:36 UTC
Labels: category:tool-update

**Comment by sumitkang** [comment] 2020-08-11 08:41
@LilyWangL  i am new to this forum so basically it ,means it would be fixed  soon ?

**Comment by LilyWangL** [comment] 2020-08-11 09:14
> @LilyWangL i am new to this forum so basically it means that it would be fixed soon ?

The issue #12709 will confirm a workaround to fix this error, so please pay attention to the progress of issue #12709.
