### ISSUE TITLE
Versioning fails to recognise baseline, and doesn't cope with specification of versioning for dependency

### ISSUE THREAD

**Issue by tonygould** [microsoft/vcpkg#18533] opened 2021-06-18 11:07 UTC
**Describe the bug**
Following the steps at https://github.com/microsoft/vcpkg/blob/master/docs/examples/versioning.getting-started.md, configuration fails with errors on the baseline, and, if you delete the baseline, errors on the version specification  of `fmt`.

Either the "Getting started" example should work and there are bug(s) in the underlying vcpkg, or the example should be modified so that new users can easily get started. If the latter, it would be good to have an explanation why the baseline in the example is not working (despite being present in my cloned git repo), and why the version specification doesn't work -- because both of these look reasonable and intuitive to me.

**Environment**
- OS: Windows and Linux

**To Reproduce**

vcpkg.json

    {
        "name": "versions-test",
        "version": "1.0.0",
        "dependencies": [
            {
                "name": "fmt",
                "version>=": "7.1.3"
            },
            "zlib"
        ],
        "builtin-baseline": "b60f003ccf5fe8613d029f49f835c8929a66eb61"
    }

main.cpp

    #include <fmt/core.h>
    #include <zlib.h>

    int main() {
      fmt::print("fmt version is {}\n"
                "zlib version is {}\n",
                FMT_VERSION, ZLIB_VERSION);
      return 0;
    }

CMakeLists.txt

    cmake_minimum_required(VERSION 3.18)

    project(versionstest CXX)

    add_executable(main main.cpp)

    find_package(ZLIB REQUIRED)
    find_package(fmt CONFIG REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB fmt::fmt)

**Expected behavior**
It's the "Getting started" example. It should just work, per instructions.

**Failure logs** 
Initially

    [cmake] Error: Couldn't find explicitly specified baseline `"b60f003ccf5fe8613d029f49f835c8929a66eb61"` in the baseline file, and there was no baseline at that commit or the commit didn't exist.
    [cmake] Error: while checking out baseline 'b60f003ccf5fe8613d029f49f835c8929a66eb61:versions/baseline.json':
    [cmake] fatal: path 'versions/baseline.json' exists on disk, but not in 'b60f003ccf5fe8613d029f49f835c8929a66eb61'
    [cmake] This may be fixed by updating vcpkg to the latest master via `git pull`.
    [cmake] The current commit is "6e024e744e7717c06ddacd5089401109c6298553"

This is despite vcpkg being up-to-date and in particular the baseline commit existing

	$ git log -1 b60f003ccf5fe8613d029f49f835c8929a66eb61
	commit b60f003ccf5fe8613d029f49f835c8929a66eb61
	Author: nicole mazzuca <mazzucan@outlook.com>
	Date:   Fri Jan 15 18:32:04 2021 -0800

I can workaround this by setting the baseline to a more recent commit, e.g. `HEAD^` (`a94c58dcdc7ded8d8a1291324876c433769cb348`), or deleting the baseline altogether. In which case I get

	[cmake] Error: Version conflict on fmt:x64-windows: baseline required 7.1.3#4 but vcpkg could not compare it to 7.1.3
	[cmake] 
	[cmake] The two versions used incomparable schemes:
	[cmake]     "7.1.3" was of scheme string
	[cmake]     "7.1.3#4" was of scheme relaxed
	[cmake] 
	[cmake] This can be resolved by adding an explicit override to the preferred version, for example:
	[cmake] 
	[cmake]     "overrides": [
	[cmake]         { "name": "fmt", "version": "7.1.3" }
	[cmake]     ]

Again, it seems intuitively that if I say `>= 7.1.3`, that should also match `7.1.3#4`. But in any case, the "Getting started" example should just work out the box.

The above is for Windows. I get the same on Linux.

**Additional context**

This was previously reported as q1, q2 of https://github.com/microsoft/vcpkg/issues/18297. I reported multiple issues there, so as q3, q4 were resolved there, I am starting a new issue here.

**Comment by PhoebeHui** [comment] 2021-06-21 03:14
@tonygould, thanks for reporting a seperate issue for this again!

@vicroms, could you consider to improve the docs for it?

**Comment by tonygould** [comment] 2021-06-23 09:18
@PhoebeHui Are you sure these are not bugs in the tool? Surely the example on the vcpkg website should work as it stands? I.e., it should be possible to specify a baseline from January, and asking for version >= 7.3 should work?

**Comment by PhoebeHui** [comment] 2021-07-01 02:35
@tonygould, thanks, this should be a documentation bug. 

The commit [b60f003ccf5fe8613d029f49f835c8929a66eb61](https://github.com/microsoft/vcpkg/commit/b60f003ccf5fe8613d029f49f835c8929a66eb61) used in the example generated on Jan 16, however, the first [commit](https://github.com/microsoft/vcpkg/commit/68a74950d0400f5a803026d0860f49853984bf11) for baseline version checkin on Jan 22, so it can't find a baseline.json file. We should update it in example.

```
PS E:\vcpkg\vcpkg_debug\vcpkg> git show b60f003ccf5fe8613d029f49f835c8929a66eb61:versions/baseline.json
fatal: Path 'versions/baseline.json' exists on disk, but not in 'b60f003ccf5fe8613d029f49f835c8929a66eb61'.
```

For the second failures, it's relate to https://github.com/microsoft/vcpkg-tool/pull/7.
The provided baseline verison and latest vsersion has incomparable schemes, the schemes for baseline version is 'version-string', the latest version is 'version'. see https://github.com/microsoft/vcpkg/blob/master/versions/f-/fmt.json.
But we don't have a doc for it now.

**Comment by vicroms** [comment] 2021-07-15 22:38
Hi @tonygould 

I opened #18969 to fix the documentation issue with the Getting Started guide.

For your second issue:

```
[cmake] The two versions used incomparable schemes:
[cmake]     "7.1.3" was of scheme string
[cmake]     "7.1.3#4" was of scheme relaxed
```
It has to do with how [versioning schemes]() are implemented in vcpkg.

From `versions/f-/fmt.json`:
```

**Comment by vicroms** [comment] 2021-07-15 23:20
The second part of the issue is a bit more complicated.

```
[cmake] The two versions used incomparable schemes:
[cmake]     "7.1.3" was of scheme string (from "dependencies" section in manifest)
[cmake]     "7.1.3#4" was of scheme relaxed (taken from "builtin-baseline")
```
The issue lies in that by design we do not compare between versions that use different [version schemes](https://github.com/microsoft/vcpkg/blob/master/docs/users/versioning.md#version-schemes) (even if the conversion from one to the other seems obvious).

From `versions/f-/fmt.json`: 

```
{
      "git-tree": "230e140a15afbb9089537e153d8b83f5b994adbe",
      "version": "7.1.3",
      "port-version": 4
    },
    ...
    {
      "git-tree": "4f8427eb0bd40da1856d4e67bde39a4fda689d72",
      "version": "7.1.3",
      "port-version": 1
    },
    {
      "git-tree": "dd8cf5e1a2dce2680189a0744102d4b0f1cfb8b6",
      "version-string": "7.1.3",
      "port-version": 0
    },
```

We can see that `version-string` was used for `7.1.3#0` and starting from `7.1.3#1` it uses `version` instead. 
So, for any modern baseline this will always cause a version scheme conflict.

I think the easiest fix is to use version `7.1.3#1` in the Getting Started guide to avoid version scheme clashes in the future and as a follow-up create a new section in the docs explaining the cause for this issue and how to work around it.

**Comment by PhoebeHui** [comment] 2021-07-16 01:48
@vicroms, could you help confirm if there is bug here? both 7.1.2 and 7.1.3 are scheme string, however, they still failed to compare.

vcpkg.json
```
{
    "name": "versions-test",
    "version": "1.0.0",
    "dependencies": [
        {
            "name": "fmt",
            "version>=": "7.1.2"
        }
    ],
    "builtin-baseline": "99dc49dae7e170c3be63dd097230007f3bb73c4f"
}
```


```
E:\vcpkg\vcpkgtest\versioning\build>cmake  -G "Visual Studio 16 2019" "-DCMAKE_TOOLCHAIN_FILE=E:/vcpkg/vcpkg_debug/vcpkg/scripts/buildsystems/vcpkg.cmake" ..
-- Running vcpkg install
Error: Version conflict on fmt:x64-windows: baseline required 7.1.3 but vcpkg could not compare it to 7.1.2

The two versions used incomparable schemes:
    "7.1.2" was of scheme string
    "7.1.3" was of scheme string

This can be resolved by adding an explicit override to the preferred version, for example:

    "overrides": [
        { "name": "fmt", "version": "7.1.2" }
    ]

See `vcpkg help versioning` for more information.
-- Running vcpkg install - failed
CMake Error at E:/vcpkg/vcpkg_debug/vcpkg/scripts/buildsystems/vcpkg.cmake:835 (message):
  vcpkg install failed.  See logs for more information:
  E:\vcpkg\vcpkgtest\versioning\build\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.20/Modules/CMakeDetermineSystem.cmake:123 (include)
  CMakeLists.txt:4 (project)
-- Configuring incomplete, errors occurred!
```

**Comment by vicroms** [comment] 2021-07-16 17:28
@PhoebeHui  

It is not a bug, is intended by design. We cannot sort using `version-string`. It may seem obvious when the strings are `"7.1.2"` and `"7.1.3"`, but what if those were `"apple"` and `"orange"` instead? To get sorting behavior packages must use the other versioning schemes.

The only kind of sort behavior that is implemented with `version-string` is when the base version string is the same but they have a different port version, for example: `apple` < `apple#1` < `apple#2`.

**Comment by tonygould** [comment] 2021-07-18 12:57
Thanks for the explanations. It would be great if this were added to the FAQs.

**Comment by PhoebeHui** [comment] 2021-07-19 02:15
@vicroms, thanks for your explainations! It's already mentioned in https://github.com/microsoft/vcpkg/blob/master/docs/specifications/versioning.md#version-string. sorry I missed that.

**Comment by PhoebeHui** [comment] 2021-07-23 09:57
The PR has been merged, please reference latest docs.

**Closed by PhoebeHui** 2021-07-23 09:57 UTC
Labels: category:documentation, info:versioning
