### ISSUE TITLE
[grpc] Build error

### ISSUE THREAD

**Issue by vimesdev** [microsoft/vcpkg#29824] opened 2023-02-24 02:23 UTC
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
Linux ubuntu 4.15.0-204-generic #215-Ubuntu SMP Fri Jan 20 18:24:59 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Compiler: revision

**To Reproduce**

`./vcpkg install grpc`

**Failure logs**
root@ubuntu:/usr/dev/vcpkg# ./vcpkg install grpc
Computing installation plan...
The following packages will be built and installed:
    grpc[codegen,core]:x64-linux -> 1.51.1
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /root/.cache/vcpkg/archives in 42.53 ms. Use --debug to see more details.
Installing 1/1 grpc:x64-linux...
Building grpc[codegen,core]:x64-linux...
-- Using cached grpc-grpc-v1.51.1.tar.gz.
-- Cleaning sources at /usr/dev/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /usr/dev/vcpkg/downloads/grpc-grpc-v1.51.1.tar.gz
-- Applying patch 00001-fix-uwp.patch
-- Applying patch 00002-static-linking-in-linux.patch
-- Applying patch 00003-undef-base64-macro.patch
-- Applying patch 00004-link-gdi32-on-windows.patch
-- Applying patch 00005-fix-uwp-error.patch
-- Applying patch 00009-use-system-upb.patch
-- Applying patch snprintf.patch
-- Applying patch 00012-fix-use-cxx17.patch
-- Applying patch 00014-pkgconfig-upbdefs.patch
-- Applying patch 00015-disable-download-archive.patch
-- Using source at /usr/dev/vcpkg/buildtrees/grpc/src/v1.51.1-1066d25324.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /usr/dev/vcpkg/downloads/tools/cmake-3.25.1-linux/cmake-3.25.1-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j15
    Working Directory: /usr/dev/vcpkg/buildtrees/grpc/x64-linux-dbg
    See logs for more information:
      /usr/dev/vcpkg/buildtrees/grpc/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/grpc/portfile.cmake:69 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building grpc:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+grpc
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[grpc]+Build+error
Include '[grpc] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 82e03905f 2023-02-22 (29 hours ago)

Please use the prefilled template from /usr/dev/vcpkg/installed/vcpkg/issue_body.md when reporting your issue.

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by FrankXie05** [comment] 2023-02-24 02:30
@vimesdev Please provide the errror log. `/usr/dev/vcpkg/buildtrees/grpc/install-x64-linux-dbg-out.log`

**Comment by vimesdev** [comment] 2023-02-24 02:49
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10820202/install-x64-linux-dbg-out.log)

**Comment by FrankXie05** [comment] 2023-02-24 06:02
@vimesdev It should caused by out of memory, you can set environment variable `VCPKG_MAX_CONCURRENCY` to limit the number of parallel jobs.
```
c++: internal compiler error: Killed (program cc1plus)
```

**Comment by lilychen11** [comment] 2023-02-27 08:03
> @vimesdev It should caused by out of memory, you can set environment variable `VCPKG_MAX_CONCURRENCY` to limit the number of parallel jobs.
> 
> ```
> c++: internal compiler error: Killed (program cc1plus)
> ```
same problem, even though set VCPKG_MAX_CONCURRENCY=1, how to solve it?

**Comment by FrankXie05** [comment] 2023-02-28 02:12
@lilychen11 This issue should be fixed in Windows SDK 10.0.18362.0 and later versions. please update the version of your Windows SDK.

**Comment by kooBH** [comment] 2023-03-21 05:58
Any progress??

Same error on Ubuntu 20.04 

+ extract-err.log 
```
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: /home/kbh/work/vcpkg/downloads/grpc-grpc-v1.51.1.tar.gz
```

Downgraded grpc version -> didn't work  
Changed CMake version ->  didn't work

**Comment by lilychen11** [comment] 2023-03-21 09:40
> > @vimesdev It should caused by out of memory, you can set environment variable `VCPKG_MAX_CONCURRENCY` to limit the number of parallel jobs.
> > ```
> > c++: internal compiler error: Killed (program cc1plus)
> > ```
> 
> [install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10837470/install-x64-windows-dbg-out.log)
> 
> > 
> 
> same problem, even though set VCPKG_MAX_CONCURRENCY=1, how to solve it?

As for my case, I deleted all content in /Logs and /QLocal, then start init.exe and pacman get. Then the problem fixed.

**Comment by JonLiu1993** [comment] 2023-04-11 07:08
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Closed by JonLiu1993** 2023-04-11 07:08 UTC
Labels: category:question
