### ISSUE TITLE
[ffmpeg] Build error on x64-linux

### ISSUE THREAD

**Issue by bikundkumar** [microsoft/vcpkg#42500] opened 2024-12-03 15:42 UTC
Copy issue body from /home/code/ladybird/Build/release/vcpkg_installed/vcpkg/issue_body.md
Package: ffmpeg[avcodec,avdevice,avfilter,avformat,core,dav1d,openh264,opus,swresample,swscale,theora,vorbis,vpx,webp,zlib]:x64-linux@6.1.1#11

**Host Environment**

- Host: x64-linux
- Compiler: GNU 14.2.1
-    vcpkg-tool version: 2024-11-12-eb492805e92a2c14a230f5c3deb3e89f6771c321
    vcpkg-scripts version: b2cb0da53 2024-11-15 (3 weeks ago)

**To Reproduce**

`vcpkg install --no-print-usage`

**Failure logs**

```
Downloading ffmpeg-ffmpeg-n6.1.1.tar.gz
Successfully downloaded ffmpeg-ffmpeg-n6.1.1.tar.gz.
-- Extracting source /home/code/ladybird/Build/vcpkg/downloads/ffmpeg-ffmpeg-n6.1.1.tar.gz
-- Applying patch 0001-create-lib-libraries.patch
-- Applying patch 0002-fix-msvc-link.patch
-- Applying patch 0003-fix-windowsinclude.patch
-- Applying patch 0004-dependencies.patch
-- Applying patch 0005-fix-nasm.patch
-- Applying patch 0007-fix-lib-naming.patch
-- Applying patch 0012-Fix-ssl-110-detection.patch
-- Applying patch 0013-define-WINVER.patch
-- Applying patch 0020-fix-aarch64-libswscale.patch
-- Applying patch 0040-ffmpeg-add-av_stream_get_first_dts-for-chromium.patch
-- Applying patch 0041-add-const-for-opengl-definition.patch
-- Applying patch 0042-fix-arm64-linux.patch
-- Using source at /home/code/ladybird/Build/vcpkg/buildtrees/ffmpeg/src/n6.1.1-95b141da41.clean
-- Found external ninja('1.12.1').
-- Getting CMake variables for x64-linux
-- Building Options: --enable-pic --disable-doc --enable-debug --enable-runtime-cpudetect --disable-autodetect --target-os=linux --enable-pthreads --cc=cc --cxx=c++ --nm=nm --ar='ar' --ranlib=ranlib --strip=strip --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --disable-postproc --enable-swresample --enable-swscale --disable-alsa --disable-amf --disable-libaom --disable-libass --disable-avisynth --disable-bzlib --enable-libdav1d --disable-libfdk-aac --disable-libfontconfig --disable-libfreetype --disable-libfribidi --disable-iconv --disable-libilbc --disable-lzma --disable-libmp3lame --disable-libmodplug --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-ffnvcodec --disable-opencl --disable-opengl --enable-libopenh264 --disable-libopenjpeg --disable-libopenmpt --disable-openssl --enable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libssh --disable-libtensorflow --disable-libtesseract --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --disable-libx264 --disable-libx265 --disable-libxml2 --enable-zlib --disable-libsrt --disable-libmfx --enable-cross-compile --disable-static --enable-shared --pkg-config=/bin/pkg-config
-- Building Release Options: --enable-optimizations --extra-ldflags=-L"/home/code/ladybird/Build/release/vcpkg_installed/x64-linux/lib"
-- Building ffmpeg for Release
-- Fixing pkgconfig file: /home/code/ladybird/Build/vcpkg/packages/ffmpeg_x64-linux/lib/pkgconfig/libavcodec.pc
-- Fixing pkgconfig file: /home/code/ladybird/Build/vcpkg/packages/ffmpeg_x64-linux/lib/pkgconfig/libavdevice.pc
-- Fixing pkgconfig file: /home/code/ladybird/Build/vcpkg/packages/ffmpeg_x64-linux/lib/pkgconfig/libavfilter.pc
-- Fixing pkgconfig file: /home/code/ladybird/Build/vcpkg/packages/ffmpeg_x64-linux/lib/pkgconfig/libavformat.pc
-- Fixing pkgconfig file: /home/code/ladybird/Build/vcpkg/packages/ffmpeg_x64-linux/lib/pkgconfig/libavutil.pc
-- Fixing pkgconfig file: /home/code/ladybird/Build/vcpkg/packages/ffmpeg_x64-linux/lib/pkgconfig/libswresample.pc
-- Fixing pkgconfig file: /home/code/ladybird/Build/vcpkg/packages/ffmpeg_x64-linux/lib/pkgconfig/libswscale.pc
CMake Error at /home/code/ladybird/Build/release/vcpkg_installed/x64-linux/share/vcpkg-pkgconfig-get-modules/x_vcpkg_pkgconfig_get_modules.cmake:31 (execute_process):
  execute_process failed command indexes:

    1: "Abnormal exit with child return code: Segmentation fault"

Call Stack (most recent call first):
  buildtrees/versioning_/versions/ffmpeg/15b90b33b76e69c2d9b876b32c4c9b47c97846ed/portfile.cmake:892 (x_vcpkg_pkgconfig_get_modules)
  scripts/ports.cmake:196 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "builtin-baseline": "b2cb0da531c2f1f740045bfe7c4dac59f0b2b69c",
  "dependencies": [
    {
      "name": "curl",
      "features": [
        "brotli",
        "http2"
      ]
    },
    {
      "name": "dirent",
      "platform": "windows"
    },
    {
      "name": "ffmpeg",
      "platform": "!android",
      "features": [
        "avcodec",
        "avformat",
        "dav1d",
        "openh264",
        "opus",
        "webp",
        "theora",
        "vorbis",
        "vpx",
        "zlib"
      ]
    },
    {
      "name": "fontconfig",
      "platform": "linux | freebsd | openbsd | osx | windows"
    },
    {
      "name": "harfbuzz",
      "platform": "linux | freebsd | openbsd | windows",
      "features": [
        "freetype",
        "icu"
      ]
    },
    {
      "name": "harfbuzz",
      "platform": "osx",
      "features": [
        "coretext",
        "icu"
      ]
    },
    "icu",
    "libjpeg-turbo",
    "libjxl",
    {
      "name": "libpng",
      "features": [
        "apng"
      ]
    },
    "libproxy",
    {
      "name": "libavif",
      "features": [
        "dav1d"
      ]
    },
    {
      "name": "libwebp",
      "features": [
        "anim",
        "libwebpmux",
        "simd"
      ]
    },
    {
      "name": "mman",
      "platform": "windows"
    },
    {
      "name": "pthread",
      "platform": "windows"
    },
    "simdutf",
    {
      "name": "skia",
      "platform": "osx",
      "features": [
        "metal",
        "fontconfig",
        "harfbuzz",
        "icu"
      ]
    },
    {
      "name": "skia",
      "platform": "linux | freebsd | openbsd | windows",
      "features": [
        "freetype",
        "fontconfig",
        "harfbuzz",
        "icu",
        "vulkan"
      ]
    },
    {
      "name": "skia",
      "platform": "android"
    },
    "sqlite3",
    {
      "name": "vulkan",
      "platform": "!android"
    },
    {
      "name": "vulkan-headers",
      "platform": "!android"
    },
    "woff2"
  ],
  "overrides": [
    {
      "name": "curl",
      "version": "8.10.1#0"
    },
    {
      "name": "ffmpeg",
      "version": "6.1.1#11"
    },
    {
      "name": "fontconfig",
      "version": "2.14.2#1"
    },
    {
      "name": "icu",
      "version": "74.2#2"
    },
    {
      "name": "libjpeg-turbo",
      "version": "3.0.2"
    },
    {
      "name": "libjxl",
      "version": "0.11.0"
    },
    {
      "name": "libpng",
      "version": "1.6.43#3"
    },
    {
      "name": "libproxy",
      "version": "0.4.18#3"
    },
    {
      "name": "libavif",
      "version": "1.0.4#1"
    },
    {
      "name": "libwebp",
      "version": "1.4.0#1"
    },
    {
      "name": "simdutf",
      "version": "5.6.0#0"
    },
    {
      "name": "skia",
      "version": "129#0"
    },
    {
      "name": "sqlite3",
      "version": "3.46.1"
    },
    {
      "name": "woff2",
      "version": "1.0.2#4"
    }
  ]
}

```
</details>

**Comment by LilyWangLL** [comment] 2024-12-04 07:01
Duplicate of https://github.com/microsoft/vcpkg/issues/42084.

**Closed by LilyWangLL** 2024-12-04 07:01 UTC
Labels: requires:repro
