### ISSUE TITLE
[openal-soft:x86-windows][x86 system] [openal-soft:x64-windows][x64 system] build failure

### ISSUE THREAD

**Issue by tobbi** [microsoft/vcpkg#7790] opened 2019-08-20 21:26 UTC
**Host Environment**
- OS: Windows 10 x86
- Compiler: MSBuild

**To Reproduce**
`./vcpkg install openal-soft:x86-windows`

**Failure logs** 
[install-x86-windows-dbg-out.log.zip](https://github.com/microsoft/vcpkg/files/3522655/install-x86-windows-dbg-out.log.zip)

**Additional context**
This issue only occurs on AppVeyor builds and only on 32 bits. 

Here's the complete openal-soft subdirectory in the buildtrees directory:
[openal-soft-buildtree.zip](https://github.com/microsoft/vcpkg/files/3522661/openal-soft-buildtree.zip)

**Comment by tobbi** [comment] 2019-08-20 21:27
Example AppVeyor job that failed:
https://ci.appveyor.com/project/supertux/supertux-9ml4d

**Comment by tobbi** [comment] 2019-08-27 22:57
This no longer only affects x86, but the build error surfaced on x64 as well:
https://ci.appveyor.com/project/supertux/supertux-o8t59/builds/26992849

**Comment by tobbi** [comment] 2019-08-27 23:47
The issue is closely linked to the build image used by AppVeyor. If I set it to use the previous image, then the build succeeds, as can be seen here (64bit):
https://ci.appveyor.com/project/supertux/supertux-o8t59/builds/27003374
and here (32 bit):
https://ci.appveyor.com/project/supertux/supertux-9ml4d/builds/27003373

The last Windows images update happened on August 1, 2019. These are the changes:
https://www.appveyor.com/updates/2019/08/01/

**Comment by tobbi** [comment] 2019-08-27 23:52
The culprit is definitely the Windows 10 SDK installed with that update.

**Comment by JackBoosY** [comment] 2019-09-18 08:09
It seems that is a Windows SDK bug, @Rastaban could you confirm this?

**Comment by Rastaban** [comment] 2019-09-24 23:37
It is not clear to me if this is a Windows SDK bug, a configuration issue in the AppVeyor, or a bug in the portfile.  I have been unable to reproduce the issue locally using the latest release of the windows SDK.  Is there a way to check the version of the sdk in the AppVeyor image?

**Comment by tobbi** [comment] 2019-11-14 20:58
@Rastaban @JackBoosY: I changed the os specifier to "Visual Studio 2019" and the issue *apparently* vanished. Can anyone of you try to reproduce the issue with our previous generator "Visual Studio 2015"?

**Comment by zrax** [comment] 2020-01-22 00:13
Here's a version with the full log output on the Visual Studio 2015 image (minimal [build script](https://github.com/H-uru/PlasmaPrefix/blob/dbglog/appveyor.yml) for easier reproducibility):  https://ci.appveyor.com/project/zrax/plasmaprefix/builds/30272072

Like others, I can build it locally fine...

**Comment by NancyLi1013** [comment] 2020-05-22 06:55
```
5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(32): error C2054: expected '(' to follow 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(37): error C2085: 'CopyFileFromAppW': not in formal parameter list (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(40): error C2061: syntax error: identifier 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(51): error C2054: expected '(' to follow 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(60): error C2085: 'CreateFileFromAppW': not in formal parameter list (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(32): error C2054: expected '(' to follow 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alAuxEffectSlot.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(63): error C2061: syntax error: identifier 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(37): error C2085: 'CopyFileFromAppW': not in formal parameter list (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alAuxEffectSlot.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(77): error C2054: expected '(' to follow 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(40): error C2061: syntax error: identifier 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alAuxEffectSlot.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(80): error C2085: 'DeleteFileFromAppW': not in formal parameter list (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(51): error C2054: expected '(' to follow 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alAuxEffectSlot.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(83): error C2061: syntax error: identifier 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(60): error C2085: 'CreateFileFromAppW': not in formal parameter list (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alAuxEffectSlot.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(98): error C2054: expected '(' to follow 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(63): error C2061: syntax error: identifier 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alAuxEffectSlot.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(103): error C2085: 'GetFileAttributesExFromAppW': not in formal parameter list (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(77): error C2054: expected '(' to follow 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alAuxEffectSlot.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(106): error C2061: syntax error: identifier 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(80): error C2085: 'DeleteFileFromAppW': not in formal parameter list (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alAuxEffectSlot.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(117): error C2054: expected '(' to follow 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(83): error C2061: syntax error: identifier 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alAuxEffectSlot.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(120): error C2085: 'RemoveDirectoryFromAppW': not in formal parameter list (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(98): error C2054: expected '(' to follow 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alAuxEffectSlot.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(123): error C2061: syntax error: identifier 'WINSTORAGEAPI' (compiling source file C:\Tools\vcpkg\buildtrees\openal-soft\src\oft-1.19.1-db129601f2\OpenAL32\alBuffer.c) [C:\Tools\vcpkg\buildtrees\openal-soft\x86-windows-dbg\OpenAL.vcxproj]
     5>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(103): error C2085: 'GetFileAttributesExFromAppW': not in formal parameter list (compiling source file 
```

**Comment by Pospelove** [comment] 2020-06-20 21:36
Reproduced on Windows 8.1 + VS 2019

**Comment by BillyONeal** [comment] 2020-11-06 02:19
I believe Robert's comment here demonstrates the root cause; openal looking for additional Windows SDKs rather than trying to use the vcpkg provided one: https://github.com/microsoft/vcpkg/pull/12318#issuecomment-655782037

**Comment by JonLiu1993** [comment] 2022-01-27 08:19
@tobbi ,Thanks for posting this issue. Did you report this issue on upstream? And does this issue fixed?

**Comment by JackBoosY** [comment] 2022-07-29 07:14
Close this PR until upstream fixes this.

**Closed by JackBoosY** 2022-07-29 07:14 UTC
Labels: category:port-bug, depends:upstream-changes
