### ISSUE TITLE
Can't find ZeroMQ from CMake project

### ISSUE THREAD

**Issue by wdx04** [Microsoft/vcpkg#2476] opened 2017-12-31 08:54 UTC
Hi,

I installed ZeroMQ using "vcpkg install zeromq:x64-windows" command. But when I try to use ZeroMQ in my project, I got the following CMake error:

```
CMake Error at C:/vcpkg/installed/x64-windows/share/zeromq/ZeroMQConfig.cmake:48 (get_target_property):
  get_target_property() called with non-existent target "libzmq-static".
Call Stack (most recent call first):
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:222 (_find_package)
  CMakeLists.txt:48 (find_package)
```

It seems ZeroMQConfig.cmake wants to find both static and dynamic versions of ZeroMQ. This is wrong behavior because "zeromq:x64-windows" was supposed to be a dynamic library.

**Comment by hmenke** [comment] 2018-01-01 04:32
I have a similar issue.  CMake can no longer find `libzmq.dll` using `find_library`.  It worked a few months ago.  It also seems that since then the verbosity of the build was reduced so I can no longer see which files vcpkg actually installs.  I reproduced my problem in a test repo and set up a test build on AppVeyor.
https://github.com/hmenke/vcpkg_zeromq/tree/master
https://ci.appveyor.com/project/hmenke/vcpkg-zeromq/build/1.0.1

**Comment by ras0219-msft** [comment] 2018-01-04 03:53
Thanks for reporting this issue! It should be fixed in the latest master.

The issue was with the upstream zeromq cmake config files -- they are not set up to correctly handle installation of only one of the targets. I've added a vcpkg-local patch that accounts for this.

**Closed** 2018-01-04 03:52 UTC
Labels: port bug

**Comment by ras0219-msft** [comment] 2018-01-04 03:56
@hmenke The CMakelists.txt provided by zeromq appears to create "boost-style" lib files on windows now (`libzmq-mt-4_2_3.lib`) so they unfortunately won't be locatable with `find_library(X NAMES libzmq-static)` like you have in [1]. However, I've fixed `find_package()` so you can use that (just run `vcpkg install zeromq` to get the full details).


[1] https://github.com/hmenke/vcpkg_zeromq/tree/master
