### ISSUE TITLE
[cpr] build failure

### ISSUE THREAD

**Issue by vader-coder** [microsoft/vcpkg#13855] opened 2020-10-02 20:37 UTC
**Host Environment**
- OS: Windows 10
- Compiler: g++

**To Reproduce**
`vcpkg install cpr`

**Failure logs** 
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 7;"Couldn't connect to server"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:181 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:438 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

Error: Building package zlib:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Comment by gijzelaerr** [comment] 2020-10-03 07:00
duplicate of https://github.com/microsoft/vcpkg/issues/13852

**Closed** 2020-10-06 10:33 UTC
