### ISSUE TITLE
[Prometheus-cpp] build failure, vcpkg in broken state

### ISSUE THREAD

**Issue by jdx-john** [microsoft/vcpkg#15625] opened 2021-01-13 16:50 UTC
**Host Environment**
- OS: Windows 10
- Compiler: VS2019

**To Reproduce**
`./vcpkg install prometheus-cpp`

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: ninja -v
    Working Directory: C:/github/microsoft/vcpkg/buildtrees/prometheus-cpp/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\github\microsoft\vcpkg\buildtrees\prometheus-cpp\config-x86-windows-out.log
```
[config-x86-windows-out.txt](https://github.com/microsoft/vcpkg/files/5809984/config-x86-windows-out.txt)

**Additional context**
I had this building just fine for several weeks. But ever since I tried to adjust the triplet, it's all gone wrong. I've totally wiped and rebuilt vcpkg from source and then I tried again and got same problem. The log suggests some dependency problem (I think) but I see no way to force it to re-get all dependencies, and nothing short of nuking it from orbit gets it working again. 

The log file has this entry:
```
CMake Error at C:/github/microsoft/vcpkg/scripts/buildsystems/vcpkg.cmake:634 (_find_package):
  Could not find a package configuration file provided by "civetweb" with any
  of the following names:

    civetwebConfig.cmake
    civetweb-config.cmake

  Add the installation prefix of "civetweb" to CMAKE_PREFIX_PATH or set
  "civetweb_DIR" to a directory containing one of the above files.  If
  "civetweb" provides a separate development package or SDK, be sure it has
  been installed.
```
However when doing a brand new, clean build I see I have civet-web installed, and was able to install prometheus-cpp successfully. It's like it's been deleted and it doesn't know how to get it back.

vcpkg has so few options I cannot see how I've got so messed up, unlike cmake where it is very easy to break something!

**Comment by jdx-john** [comment] 2021-01-13 17:32
OK so I decided to try and rebuild *civetweb*:
```

C:\github\microsoft\vcpkg>vcpkg remove civetweb
The following packages will be removed:
    civetweb:x86-windows
Removing package civetweb:x86-windows...
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/debug/: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/debug/lib/: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/debug/lib/civetweb-cpp.lib: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/debug/lib/civetweb.lib: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/include/: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/include/CivetServer.h: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/include/civetweb.h: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/lib/: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/lib/civetweb-cpp.lib: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/lib/civetweb.lib: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/share/: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/share/civetweb/: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/share/civetweb/civetweb-config-version.cmake: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/share/civetweb/civetweb-config.cmake: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/share/civetweb/civetweb-targets-debug.cmake: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/share/civetweb/civetweb-targets-release.cmake: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/share/civetweb/civetweb-targets.cmake: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/share/civetweb/copyright: file not found
Warning: C:\github\microsoft\vcpkg\installed\x86-windows/share/civetweb/vcpkg_abi_info.txt: file not found
Removing package civetweb:x86-windows... done
```

Then I tried to install prometheus-cpp again, this time it failed on another dependency (zlib). Looking in my buildtrees dir:
![image](https://user-images.githubusercontent.com/1654627/104487545-273a9100-55c5-11eb-8503-d6f3def71cec.png)

So somehow I have half-deleted all my dependencies, it seems. But there is no way to repair them. I thought deleting buildtrees would force a rebuild?

**Comment by JackBoosY** [comment] 2021-01-14 05:54
It seems that the folder _C:\github\microsoft\vcpkg\installed\x86-windows_ is completely deleted, currectlly don't know who did that.

vcpkg will delete the folder in _buildtrees/port/src_ only when rebuilding the port, and other files will not be deleted.
So I think this is caused by anti-virus.

**Comment by jdx-john** [comment] 2021-01-14 09:54
@JackBoosY since there is no `remove *` command, is it safe to manually delete that folder? Or only the contents?

**Comment by jdx-john** [comment] 2021-01-14 09:58
A remove + all dependencies or remove all would be handy though.

**Comment by JackBoosY** [comment] 2021-01-15 02:07
@jdx-john You shouldn't delete _installed_ folder manually because this destroys the database where vcpkg stores installation information.

**Comment by jdx-john** [comment] 2021-01-15 10:03
@JackBoosY I think this may be the issue - I got a bit delete-happy since I couldn't see a way to clean a port and its dependencies.

If you edit a triplet, it doesn't seem to pick this up for rebuilding so manually cleaning seems to be required; can I find a list of all the dependency projects for <port> so I can check which ones?

**Comment by viromer** [comment] 2021-01-15 12:14
You can use the undocumented `x-set-installed` command to delete all installed packages like so:

`vcpkg x-set-installed - -triplet x64-windows`

There is an old PR to add regex syntax to the remove command that was never merged that we may want to resurrect.

**Comment by JackBoosY** [comment] 2021-01-21 07:48
@BillyONeal Should we add a vcpkg feature to do that?

**Comment by JackBoosY** [comment] 2021-07-26 06:31
You can add option `--clean-after-build` to `install` command to remove _buildtrees_, _packages_ and _downloads_ after build.

**Comment by JackBoosY** [comment] 2021-09-30 06:30
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Closed by JackBoosY** 2021-09-30 06:30 UTC
Labels: category:question
