### ISSUE TITLE
'CMake' failed while extracting

### ISSUE THREAD

**Issue by amssss0** [microsoft/vcpkg#33972] opened 2023-09-24 19:21 UTC
**Describe the bug**
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

```
C:\Users\amsssss>vcpkg install glfw3
warning: In the September 2023 release, the default triplet for vcpkg libraries
changed from x86-windows to the detected host triplet (x64-windows). For the old
 behavior, add --triplet x86-windows . To suppress this message, add --triplet x
64-windows .
Computing installation plan...
The following packages will be built and installed:
    glfw3:x64-windows -> 3.3.8#2
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.11) Downloadi
ng portable powershell-core 7.2.11...
Downloading powershell-core...
https://github.com/PowerShell/PowerShell/releases/download/v7.2.11/PowerShell-7.
2.11-win-x86.zip->F:\vcpkg\downloads\PowerShell-7.2.11-win-x86.zip
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.11/P
owerShell-7.2.11-win-x86.zip
Extracting powershell-core...
'CMake' failed while extracting F:\vcpkg\downloads\PowerShell-7.2.11-win-x86.zip
.
```

**Environment**
- OS: Windows 7

**Comment by MonicaLiu0311** [comment] 2023-09-26 03:20
Duplicate of #33904.

**Closed by MonicaLiu0311** 2023-09-26 03:20 UTC
Labels: category:vcpkg-bug
