### ISSUE TITLE
[colmap] Build error

### ISSUE THREAD

**Issue by asterix01** [microsoft/vcpkg#29458] opened 2023-02-05 18:55 UTC
Package: colmap[core,cuda,tests]:x64-windows-static -> 2022-03-14#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30147.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 0ba60bfef 2023-02-03 (2 days ago)

**To Reproduce**

`vcpkg install colmap[cuda,tests]:x64-windows-static`

**Failure logs**

```
-- Using cached colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz.
-- Cleaning sources at C:/projects/colmap/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/projects/colmap/vcpkg/downloads/colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at C:/projects/colmap/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-static-dbg
-- Configuring x64-windows-static-rel
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/projects/colmap/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg
    See logs for more information:
      C:\projects\colmap\vcpkg\buildtrees\colmap\install-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:59 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\projects\colmap\vcpkg\buildtrees\colmap\install-x64-windows-static-dbg-out.log</summary>

```
[1/1278] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DVL_DISABLE_AVX -IC:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -IC:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\eigen3 -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5 -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtCore -IC:\projects\colmap\vcpkg\installed\x64-windows-static\tools\qt5\mkspecs\win32-msvc -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtOpenGL -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtWidgets -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folib\VLFeat\CMakeFiles\vlfeat.dir\hikmeans.c.obj /Fdlib\VLFeat\CMakeFiles\vlfeat.dir\vlfeat.pdb /FS -c C:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\VLFeat\hikmeans.c
[2/1278] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -IC:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -IC:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\eigen3 -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5 -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtCore -IC:\projects\colmap\vcpkg\installed\x64-windows-static\tools\qt5\mkspecs\win32-msvc -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtOpenGL -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtWidgets -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folib\LSD\CMakeFiles\lsd.dir\lsd.c.obj /Fdlib\LSD\CMakeFiles\lsd.dir\lsd.pdb /FS -c C:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\LSD\lsd.c
[3/1278] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -IC:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -IC:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\eigen3 -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5 -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtCore -IC:\projects\colmap\vcpkg\installed\x64-windows-static\tools\qt5\mkspecs\win32-msvc -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtOpenGL -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtWidgets -IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folib\FLANN\CMakeFiles\flann.dir\ext\lz4.c.obj /Fdlib\FLANN\CMakeFiles\flann.dir\flann.pdb /FS -c C:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\FLANN\ext\lz4.c
...
Skipped 4029 lines
...

[1252/1278] C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe   /TP -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DCMS_NO_REGISTER_KEYWORD -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGFLAGS_IS_A_DLL=0 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DOPJ_STATIC -DQT_ACCESSIBILITY_SUPPORT_LIB -DQT_CORE_LIB -DQT_EVENTDISPATCHER_SUPPORT_LIB -DQT_FONTDATABASE_SUPPORT_LIB -DQT_GUI_LIB -DQT_OPENGL_LIB -DQT_SVG_LIB -DQT_THEME_SUPPORT_LIB -DQT_WIDGETS_LIB -DQT_WINDOWSUIAUTOMATION_SUPPORT_LIB -IC:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -IC:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\eigen3 -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5 -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtCore -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\tools\qt5\mkspecs\win32-msvc -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtOpenGL -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtWidgets -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtGui -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\webp -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\OpenEXR -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\Imath -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\GKlib -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtSvg -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtEventDispatcherSupport -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtFontDatabaseSupport -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtThemeSupport -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtAccessibilitySupport -external:IC:\projects\colmap\vcpkg\installed\x64-windows-static\include\qt5\QtWindowsUIAutomationSupport -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W3 /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1  /EHsc /Zc:__cplusplus -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /bigobj /showIncludes /Fosrc\util\CMakeFiles\opengl_utils_test.dir\opengl_utils_test.cc.obj /Fdsrc\util\CMakeFiles\opengl_utils_test.dir\ /FS -c C:\projects\colmap\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\util\opengl_utils_test.cc
[1253/1278] cmd.exe /C "cd . && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\util\CMakeFiles\string_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\string_test.rsp  /out:src\util\string_test.exe /implib:src\util\string_test.lib /pdb:src\util\string_test.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
[1254/1278] cmd.exe /C "cd . && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\optim\CMakeFiles\ransac_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\ransac_test.rsp  /out:src\optim\ransac_test.exe /implib:src\optim\ransac_test.lib /pdb:src\optim\ransac_test.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
[1255/1278] cmd.exe /C "cd /D C:\projects\colmap\vcpkg\buildtrees\colmap\x64-windows-static-dbg\src\mvs\CMakeFiles\gpu_mat_test.dir && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E make_directory C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg/src/mvs/CMakeFiles/gpu_mat_test.dir//. && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg/src/mvs/CMakeFiles/gpu_mat_test.dir//./gpu_mat_test_generated_gpu_mat_test.cu.obj -D generated_cubin_file:STRING=C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg/src/mvs/CMakeFiles/gpu_mat_test.dir//./gpu_mat_test_generated_gpu_mat_test.cu.obj.cubin.txt -P C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg/src/mvs/CMakeFiles/gpu_mat_test.dir//gpu_mat_test_generated_gpu_mat_test.cu.obj.Debug.cmake"
FAILED: src/mvs/CMakeFiles/gpu_mat_test.dir/gpu_mat_test_generated_gpu_mat_test.cu.obj C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg/src/mvs/CMakeFiles/gpu_mat_test.dir/gpu_mat_test_generated_gpu_mat_test.cu.obj 
cmd.exe /C "cd /D C:\projects\colmap\vcpkg\buildtrees\colmap\x64-windows-static-dbg\src\mvs\CMakeFiles\gpu_mat_test.dir && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E make_directory C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg/src/mvs/CMakeFiles/gpu_mat_test.dir//. && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -D verbose:BOOL=OFF -D build_configuration:STRING=Debug -D generated_file:STRING=C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg/src/mvs/CMakeFiles/gpu_mat_test.dir//./gpu_mat_test_generated_gpu_mat_test.cu.obj -D generated_cubin_file:STRING=C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg/src/mvs/CMakeFiles/gpu_mat_test.dir//./gpu_mat_test_generated_gpu_mat_test.cu.obj.cubin.txt -P C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg/src/mvs/CMakeFiles/gpu_mat_test.dir//gpu_mat_test_generated_gpu_mat_test.cu.obj.Debug.cmake"
gpu_mat_test.cu
C:\projects\colmap\vcpkg\installed\x64-windows-static\include\boost/test/unit_test_log.hpp(111): warning: overloaded virtual function "boost::unit_test::test_observer::test_unit_skipped" is only partially overridden in class "boost::unit_test::unit_test_log_t"

C:\projects\colmap\vcpkg\installed\x64-windows-static\include\boost/test/unit_test_log.hpp(111): warning: overloaded virtual function "boost::unit_test::test_observer::test_unit_skipped" is only partially overridden in class "boost::unit_test::unit_test_log_t"

C:\projects\colmap\vcpkg\installed\x64-windows-static\include\boost/throw_exception.hpp(224): error: identifier "__builtin_FILE" is undefined

C:\projects\colmap\vcpkg\installed\x64-windows-static\include\boost/throw_exception.hpp(224): error: identifier "__builtin_LINE" is undefined

C:\projects\colmap\vcpkg\installed\x64-windows-static\include\boost/throw_exception.hpp(224): error: identifier "__builtin_FUNCTION" is undefined

C:\projects\colmap\vcpkg\installed\x64-windows-static\include\boost/throw_exception.hpp(224): error: identifier "__builtin_COLUMN" is undefined

4 errors detected in the compilation of "C:/projects/colmap/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean/src/mvs/gpu_mat_test.cu".
gpu_mat_test.cu
CMake Error at gpu_mat_test_generated_gpu_mat_test.cu.obj.Debug.cmake:280 (message):
  Error generating file
  C:/projects/colmap/vcpkg/buildtrees/colmap/x64-windows-static-dbg/src/mvs/CMakeFiles/gpu_mat_test.dir//./gpu_mat_test_generated_gpu_mat_test.cu.obj


[1256/1278] cmd.exe /C "cd . && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\retrieval\CMakeFiles\visual_index_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\visual_index_test.rsp  /out:src\retrieval\visual_index_test.exe /implib:src\retrieval\visual_index_test.lib /pdb:src\retrieval\visual_index_test.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
[1257/1278] cmd.exe /C "cd . && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\util\CMakeFiles\threading_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\threading_test.rsp  /out:src\util\threading_test.exe /implib:src\util\threading_test.lib /pdb:src\util\threading_test.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
[1258/1278] cmd.exe /C "cd . && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\util\CMakeFiles\timer_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\timer_test.rsp  /out:src\util\timer_test.exe /implib:src\util\timer_test.lib /pdb:src\util\timer_test.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
[1259/1278] cmd.exe /C "cd . && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\util\CMakeFiles\opengl_utils_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\opengl_utils_test.rsp  /out:src\util\opengl_utils_test.exe /implib:src\util\opengl_utils_test.lib /pdb:src\util\opengl_utils_test.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
[1260/1278] cmd.exe /C "cd . && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\base\CMakeFiles\similarity_transform_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\similarity_transform_test.rsp  /out:src\base\similarity_transform_test.exe /implib:src\base\similarity_transform_test.lib /pdb:src\base\similarity_transform_test.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
[1261/1278] cmd.exe /C "cd . && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\estimators\CMakeFiles\generalized_absolute_pose_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\generalized_absolute_pose_test.rsp  /out:src\estimators\generalized_absolute_pose_test.exe /implib:src\estimators\generalized_absolute_pose_test.lib /pdb:src\estimators\generalized_absolute_pose_test.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
[1262/1278] cmd.exe /C "cd . && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\estimators\CMakeFiles\generalized_relative_pose_test.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\generalized_relative_pose_test.rsp  /out:src\estimators\generalized_relative_pose_test.exe /implib:src\estimators\generalized_relative_pose_test.lib /pdb:src\estimators\generalized_relative_pose_test.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
[1263/1278] cmd.exe /C "cd . && C:\projects\colmap\vcpkg\downloads\tools\cmake-3.25.1-windows\cmake-3.25.1-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\exe\CMakeFiles\colmap_exe.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\link.exe  @CMakeFiles\colmap_exe.rsp  /out:src\exe\colmap.exe /implib:src\exe\colmap.lib /pdb:src\exe\colmap.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console  && cd ."
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

**Comment by JonLiu1993** [comment] 2023-02-23 10:39
@asterix01, Duplicate of #28542, Please refer to @StarGate-One' s advice:
https://github.com/microsoft/vcpkg/issues/28542#issuecomment-1364755314

**Comment by JonLiu1993** [comment] 2023-03-03 07:29
@asterix01, Have you tried the suggestions given above?

**Comment by JonLiu1993** [comment] 2023-03-03 07:35
@asterix01, Look like thie issue is fixed, so I closed this issue.

**Closed by JonLiu1993** 2023-03-03 07:35 UTC
Labels: category:port-bug
