### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by evelyndooley** [microsoft/vcpkg#36731] opened 2024-02-13 18:12 UTC
Package: openssl:x64-windows@3.2.1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.38.33134.0
-    vcpkg-tool version: 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b
    vcpkg-scripts version: 7ba0ba733 2024-02-12 (19 hours ago)

**To Reproduce**

`vcpkg install openssl`
**Failure logs**

```
-- Downloading https://github.com/openssl/openssl/archive/openssl-3.2.1.tar.gz -> openssl-openssl-openssl-3.2.1.tar.gz...
-- Extracting source C:/Users/evely/src/vcpkg/downloads/openssl-openssl-openssl-3.2.1.tar.gz
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at C:/Users/evely/src/vcpkg/buildtrees/openssl/src/nssl-3.2.1-8707343470.clean
-- Downloading https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_5380_5361/strawberry-perl-5.38.0.1-64bit-portable.zip -> strawberry-perl-5.38.0.1-64bit-portable.zip...
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip;https://gstreamer.freedesktop.org/src/mirror/nasm-2.16.01-win64.zip -> nasm-2.16.01-win64.zip...
-- Getting CMake variables for x64-windows
-- Downloading https://download.qt.io/official_releases/jom/jom_1_1_4.zip;https://mirrors.ocf.berkeley.edu/qt/official_releases/jom/jom_1_1_4.zip;https://mirrors.ukfast.co.uk/sites/qt.io/official_releases/jom/jom_1_1_4.zip -> jom_1_1_4.zip...
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Prerunning x64-windows-rel
-- Building x64-windows-rel
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON install_runtime install_ssldirs
    Working Directory: C:/Users/evely/src/vcpkg/buildtrees/openssl/x64-windows-rel
    See logs for more information:
      C:\Users\evely\src\vcpkg\buildtrees\openssl\install-x64-windows-rel-nmake-out.log
      C:\Users\evely\src\vcpkg\buildtrees\openssl\install-x64-windows-rel-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:69 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:74 (include)
  scripts/ports.cmake:170 (include)



```
<details><summary>C:\Users\evely\src\vcpkg\buildtrees\openssl\install-x64-windows-rel-nmake-out.log</summary>

```
	"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 depend
	"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs
	"C:\Users\evely\src\vcpkg\downloads\tools\nasm\nasm-2.16.01\nasm.exe"  -Ox -f win64 -DNEAR -g -o crypto\sha\libcrypto-shlib-sha1-x86_64.obj "crypto\sha\sha1-x86_64.asm"
```
</details>

<details><summary>C:\Users\evely\src\vcpkg\buildtrees\openssl\install-x64-windows-rel-nmake-err.log</summary>

```
crypto\sha\sha1-x86_64.asm:1296: error: symbol `K_XX_XX' not defined
crypto\sha\sha1-x86_64.asm:1507: error: symbol `K_XX_XX' not defined
crypto\sha\sha1-x86_64.asm:2720: error: symbol `K_XX_XX' not defined
crypto\sha\sha1-x86_64.asm:3874: error: symbol `K_XX_XX' not defined
crypto\sha\sha1-x86_64.asm:4658: error: invalid combination of opcode and operands
NMAKE : fatal error U1077: '"C:\Users\evely\src\vcpkg\downloads\tools\nasm\nasm-2.16.01\nasm.exe"  -Ox -f win64 -DNEAR -g -o crypto\sha\libcrypto-shlib-sha1-x86_64.obj "crypto\sha\sha1-x86_64.asm"' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs' : return code '0x2'
Stop.
```
</details>

**Comment by evelyndooley** [comment] 2024-02-13 18:36
Worked the second time.

**Comment by JonLiu1993** [comment] 2024-02-18 07:34
Duplicate of #36175

**Closed by JonLiu1993** 2024-02-18 07:34 UTC
Labels: category:question
