### ISSUE TITLE
[llvm] Cross-compilation is not supported

### ISSUE THREAD

**Issue by abique** [microsoft/vcpkg#14560] opened 2020-11-13 14:10 UTC
**Host Environment**
- OS: Windows (x64)
- Compiler: Visual Studio 2019 16.8.1 (latest as of today)

**To Reproduce**
`./vcpkg --triplet=arm64-windows-static install cairo freetype llvm[target-aarch64,tools,utils]`

**Failure logs** 
```
[242/2885] cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=utils\TableGen\CMakeFiles\llvm-tblgen.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\arm64\link.exe  utils\TableGen\CMakeFiles\llvm-tblgen.dir\AsmMatcherEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\AsmWriterEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\AsmWriterInst.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\Attributes.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CallingConvEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeEmitterGen.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenDAGPatterns.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenHwModes.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenInstruction.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenMapTable.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenRegisters.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenSchedule.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CodeGenTarget.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DAGISelEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DAGISelMatcherEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DAGISelMatcherGen.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DAGISelMatcherOpt.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DAGISelMatcher.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DFAEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DFAPacketizerEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\DisassemblerEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\ExegesisEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\FastISelEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\FixedLenDecoderEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\GICombinerEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\GlobalISelEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\InfoByHwMode.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\InstrInfoEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\InstrDocsEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\IntrinsicEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\OptEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\OptParserEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\OptRSTEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\PredicateExpander.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\PseudoLoweringEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\RISCVCompressInstEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\RegisterBankEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\RegisterInfoEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\SDNodeProperties.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\SearchableTableEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\SubtargetEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\SubtargetFeatureInfo.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\TableGen.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\Types.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\X86DisassemblerTables.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\X86EVEX2VEXTablesEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\X86FoldTablesEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\X86ModRMFilters.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\X86RecognizableInstr.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\WebAssemblyDisassemblerEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\CTagsEmitter.cpp.obj utils\TableGen\CMakeFiles\llvm-tblgen.dir\__\__\resources\windows_version_resource.rc.res  /out:bin\llvm-tblgen.exe /implib:lib\llvm-tblgen.lib /pdb:bin\llvm-tblgen.pdb /version:0.0 /machine:ARM64 /STACK:10000000 /nologo    /debug /INCREMENTAL /subsystem:console  lib\LLVMSupportd.lib  lib\LLVMTableGend.lib  lib\LLVMTableGenGlobalISeld.lib  lib\LLVMSupportd.lib  psapi.lib  shell32.lib  ole32.lib  uuid.lib  advapi32.lib  delayimp.lib  -delayload:shell32.dll  -delayload:ole32.dll  lib\LLVMDemangled.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
[243/2885] cmd.exe /C "cd /D C:\dev\vcpkg\buildtrees\llvm\arm64-windows-static-dbg && C:\dev\vcpkg\buildtrees\llvm\arm64-windows-static-dbg\bin\llvm-tblgen.exe -gen-attrs -I C:/dev/vcpkg/buildtrees/llvm/src/org-10.0.0-cfac4b4b0f.clean/llvm/lib/IR -I C:/dev/vcpkg/buildtrees/llvm/src/org-10.0.0-cfac4b4b0f.clean/llvm/include C:/dev/vcpkg/buildtrees/llvm/src/org-10.0.0-cfac4b4b0f.clean/llvm/lib/IR/AttributesCompatFunc.td --write-if-changed -o lib/IR/AttributesCompatFunc.inc -d lib/IR/AttributesCompatFunc.inc.d"
FAILED: lib/IR/AttributesCompatFunc.inc 
cmd.exe /C "cd /D C:\dev\vcpkg\buildtrees\llvm\arm64-windows-static-dbg && C:\dev\vcpkg\buildtrees\llvm\arm64-windows-static-dbg\bin\llvm-tblgen.exe -gen-attrs -I C:/dev/vcpkg/buildtrees/llvm/src/org-10.0.0-cfac4b4b0f.clean/llvm/lib/IR -I C:/dev/vcpkg/buildtrees/llvm/src/org-10.0.0-cfac4b4b0f.clean/llvm/include C:/dev/vcpkg/buildtrees/llvm/src/org-10.0.0-cfac4b4b0f.clean/llvm/lib/IR/AttributesCompatFunc.td --write-if-changed -o lib/IR/AttributesCompatFunc.inc -d lib/IR/AttributesCompatFunc.inc.d"
This version of C:\dev\vcpkg\buildtrees\llvm\arm64-windows-static-dbg\bin\llvm-tblgen.exe is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.
```
[arm64-windows-static.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/5537289/arm64-windows-static.vcpkg_abi_info.txt)
[config-arm64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/5537292/config-arm64-windows-static-out.log)
[install-arm64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/5537293/install-arm64-windows-static-dbg-out.log)
[stdout-arm64-windows-static.log](https://github.com/microsoft/vcpkg/files/5537295/stdout-arm64-windows-static.log)

**Comment by abique** [comment] 2020-11-13 14:17
Hi @strega-nil, I saw that you are the last contributor to this package so I hope it is OK to raise your attention.

By the way, do you have plans to support llvm 11?

Regards,
Alexandre

**Comment by strega-nil** [comment] 2020-11-13 21:29
Unfortunately, it looks like the LLVM port doesn't support cross compilation... we currently have real trouble with cross-compiling ports that require tools to be built. We hope that we can add better support for this Soon (tm), but until then supporting cross compilation for LLVM would require quite a bit of work.

We don't generally update ports like LLVM without the community doing most of the work. However, I can look into it :)

**Comment by abique** [comment] 2020-11-13 21:38
Thank you very much.

I understand the issue and I agree, it is likely a bug in LLVM build system and tools like tblgen should be built for the host and the target I suppose.

Maybe it would be a good idea to have a flag to indicate that it won't build using cross-compilation?

Thank you very much for looking into LLVM 11, I expect it will be quite straight forward on its own, but the packages using it might break. We will see.

Good luck!

**Comment by strega-nil** [comment] 2020-11-13 21:57
Thanks!

**Comment by NickStrupat** [comment] 2021-02-14 06:45
@abique Did you mean to be doing...

`./vcpkg --triplet=x64-windows-static install cairo freetype llvm[target-aarch64,tools,utils]`

...such that it builds LLVM as an x64-win lib, where the LLVM lib can target aarch-64?

**Comment by yurybura** [comment] 2021-05-20 11:38
Duplicate of #11973

**Closed** 2022-01-29 09:41 UTC
Labels: category:community-triplet
