### ISSUE TITLE
[boost-mpi] build failure

### ISSUE THREAD

**Issue by OmenWild** [microsoft/vcpkg#8984] opened 2019-11-12 17:38 UTC
**Host Environment**
- OS: Ubuntu 18.04.3 LTS
- Compiler: gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)

**To Reproduce**
`./vcpkg install boost-mpi`

**Failure logs** 
```root@soil:/admin/software/xenial/vcpkg# ./vcpkg install boost-mpi
The following packages will be built and installed:
    boost-mpi[core]:x64-linux
Starting package 1/1: boost-mpi:x64-linux
Building package boost-mpi[core]:x64-linux...
-- Using cached /admin/software/xenial/vcpkg/downloads/boostorg-mpi-boost-1.71.0.tar.gz
-- Extracting source /admin/software/xenial/vcpkg/downloads/boostorg-mpi-boost-1.71.0.tar.gz
-- Using source at /admin/software/xenial/vcpkg/buildtrees/boost-mpi/src/ost-1.71.0-10a11de14d
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at installed/x64-linux/share/boost-build/boost-modular-build.cmake:93 (message):
  No libraries were produced.  This indicates a failure while building the
  boost library.
Call Stack (most recent call first):
  ports/boost-mpi/portfile.cmake:14 (boost_modular_build)
  scripts/ports.cmake:94 (include)


Error: Building package boost-mpi:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-mpi:x64-linux
  Vcpkg version: 2019.09.12-unknownhash-external

Additionally, attach any relevant sections from the log files above.

root@soil:/admin/software/xenial/vcpkg# ./vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

root@soil:/admin/software/xenial/vcpkg# git pull
Already up to date.
root@soil:/admin/software/xenial/vcpkg# 
```

**Additional context**
The 80+ prerequisites for boost-mpi compile and install just fine, but boost-mpi fails. I tried an Ubuntu 16.04.5 LTS with `gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~16.04~ppa1)` installed, but it had the exact same problem.

I have attached all the non-empty logs from `vcpkg/buildtrees/boost-mpi/`.

[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/3837431/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/3837432/config-x64-linux-dbg-out.log)
[config-x64-linux-rel-err.log](https://github.com/microsoft/vcpkg/files/3837433/config-x64-linux-rel-err.log)
[config-x64-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/3837434/config-x64-linux-rel-out.log)
[install-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/3837435/install-x64-linux-dbg-out.log)
[install-x64-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/3837436/install-x64-linux-rel-out.log)

Thank you,
   Omen

**Comment by Voskrese** [comment] 2019-11-12 17:52
https://www.boost.org/doc/libs/1_71_0/doc/html/mpi/getting_started.html#mpi.installation

`apt install libopenmpi-dev`
?

**Comment by JackBoosY** [comment] 2019-11-13 03:11
Confirmed.

**Comment by gnaggnoyil** [comment] 2019-11-14 07:53
Met this issue too on Ubuntu 18.04 with gcc 7.4. So what's the root cause of this issue? Or is there any commit where this issue won't happen so that we can roll back?

**Comment by JackBoosY** [comment] 2019-11-15 03:12
@gnaggnoyil I think it should be rolled back to the previous version of boost.

**Comment by c4x-admin** [comment] 2019-12-09 11:23
Also so on a fresh Amazon Linux 2 instance with gcc 7.3.1

**Comment by acdemiralp** [comment] 2019-12-09 12:51
GCC 9.2.0 on CentOS also.

**Comment by JackBoosY** [comment] 2019-12-19 03:20
Confirmed, `@PORT@` was not successfully configured in `user-config.jam`.

**Comment by JackBoosY** [comment] 2019-12-19 05:33
For temporary workaround:
- change `.lib` to `.a` in _VCPKG_PATH/installed/x64-linux/share/boost-build/user-config.jam_
- add` "-DPORT=${PORT}"  "-DCURRENT_INSTALLED_DIR=${CURRENT_INSTALLED_DIR}"` to _VCPKG_PATH/installed/x64-linux/share/boost-build/boost-modular-build.cmake_ line 88

We will solve this issue in another PR.

**Comment by PhoebeHui** [comment] 2020-07-23 01:45
This issue should be fixed now, please get latest source and try again, reopen this issue if it still be a problem for you.

Starting package 23/23: boost-mpi:x64-linux
Building package boost-mpi[core]:x64-linux...
Could not locate cached archive: /home/ubuntu18/.cache/vcpkg/archives/74/74a16feb9e7fcba38b9012da3965391181b7a405.zip
-- Downloading https://github.com/boostorg/mpi/archive/boost-1.73.0.tar.gz...
-- Extracting source /home/ubuntu18/vcpkg/downloads/boostorg-mpi-boost-1.73.0.tar.gz
-- Using source at /home/ubuntu18/vcpkg/buildtrees/boost-mpi/src/ost-1.73.0-f69fd70f20.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Packaging headers
-- Packaging headers done
-- Using cached /home/ubuntu18/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: /home/ubuntu18/vcpkg/packages/boost-mpi_x64-linux/share/boost-mpi/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /home/ubuntu18/.cache/vcpkg/archives/74/74a16feb9e7fcba38b9012da3965391181b7a405.zip
Building package boost-mpi[core]:x64-linux... done
Installing package boost-mpi[core]:x64-linux...
Installing package boost-mpi[core]:x64-linux... done
Elapsed time for package boost-mpi:x64-linux: 1.189 min

**Closed by PhoebeHui** 2020-07-23 01:45 UTC
Labels: category:port-bug
