### ISSUE TITLE
[tensorflow-cc] build failure

### ISSUE THREAD

**Issue by trade-commander1** [microsoft/vcpkg#7995] opened 2019-08-30 14:35 UTC
**Host Environment**
Windows 10 64 bit (1903) VM (VMWareWorkstation)

**To Reproduce**
.\vcpkg.exe install tensorflow-cc:x86-windows-static tensorflow-cc:x64-windows-static
**Failure logs** 
Build fails. From log:
ERROR: C:/projekte/dev_apps/vcpkg/buildtrees/.bzl/_bazel_general/yvqyet6t/external/snappy/BUILD.bazel:7:1: C++ compilation of rule '@snappy//:snappy' failed (Exit 2): cl.exe failed: error executing command 
[logs.zip](https://github.com/microsoft/vcpkg/files/3560328/logs.zip)

**Comment by JackBoosY** [comment] 2019-09-03 01:59
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\yvals_core.h(298): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.15 or newer.`

What's version of your Visual Studio?

I can reproduce the build failure but the error is different:
1, The `::tensorflow::internal::LogMessage` in logging.h `::` could not be recognized.
2. Generated x64 but expect x86.

**Comment by trade-commander1** [comment] 2019-09-03 15:24
Hello, Visual Studio Version is `15.9.15`, currently latest.
Just tried to build 64 bit only 

`.\vcpkg.exe install tensorflow-cc:x64-windows-static`

and this failed as well.

**Comment by JackBoosY** [comment] 2019-09-04 02:43
@trade-commander1 Yeah, so I'm fixing static build now.

**Comment by trade-commander1** [comment] 2019-09-04 22:32
@JackBoosY 
Made a fresh run (so deleted buildtree ..cc, download,etc.). Still fails.
Logs attached. Thank you for help.
[log.zip](https://github.com/microsoft/vcpkg/files/3576722/log.zip)

**Comment by JackBoosY** [comment] 2019-09-05 02:36
The error I encountered was in the macro LOG `::tensorflow` is not recognized.
Error in your logs:
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\yvals_core.h(298): fatal error C1189: #error:  STL1001: Unexpected compiler version, expected MSVC 19.15 or newer.`

So I guess Visual Studio 2017 or newer is required to build tensorflow.

**Comment by trade-commander1** [comment] 2019-09-05 11:26
Thank you  for picking this for me.  I use latest VS 17 update. It seems you need VS 19.
Only the god of programmers knows what happens when migrate to VS 19.
Will all the other vcpkg libraries build with VS 19?

**Comment by trade-commander1** [comment] 2019-09-06 11:04
Hello,
with VS 2019 installed, build was successfull. Thank you.

**Comment by trade-commander1** [comment] 2019-09-06 11:06
Perhaps a comment for build issues i had: It seems to hang at "configure..." Then type y press Enter to proceed.  Also, do not forget to run 
`vcpkg integrate install `
before build

**Comment by JackBoosY** [comment] 2019-09-09 02:42
@trade-commander1  Thanks, I will check it with Visual Studio 2019. And I opened a issue in the github page of tensorflow-cc.

**Comment by JackBoosY** [comment] 2019-09-09 05:42
Failure on Visual Studio 2019 16.2.1.

**Comment by Voskrese** [comment] 2019-09-17 09:09
for myself
I have made, understated version for errors

edit `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.16.27023\include\yvals_core.h` str 297

to `#if _MSC_VER < 1900	// Coarse-grained, not inspecting _MSC_FULL_VER`

))

**Comment by JackBoosY** [comment] 2019-09-17 09:25
@Voskrese  I think this is not a Windows SDK bug, it is a source code error. So your solution is temporary.

**Comment by Voskrese** [comment] 2019-09-17 09:29
> So your solution is temporary.

that's right, temporary )

**Comment by jgehw** [comment] 2020-07-23 16:18
FYI: I had a more recent reincarnation of this problem:

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.26.28801\include\yvals_core.h(298): fatal error C1189: #error: STL1001: Unexpected compiler version, expected MSVC 19.25 or newer.`

Examining the log files, I found out that the most recent include files were used, but an older compiler (14.16.27023, although 14.26.28801 was also available).

I worked around this issue by uninstalling pre-2019 toolchains (MSVC v140 and v141).

**Comment by a0174** [comment] 2021-05-28 22:01
I found this thread [from a link here](https://github.com/microsoft/vcpkg/issues/10356) -- which closely resembles the error i'm getting `Error: Building package tensorflow-cc:x86-windows failed with: BUILD_FAILED` -- i'm not sure if it relates to #7995 though

**Comment by jgehw** [comment] 2021-05-31 17:03
@a0174 can you please have a look at the end of file `C:\Users\<USER>\Desktop\vcpkg\buildtrees\tensorflow-cc\build-x64-windows-dbg-out.log`? There should be an error message, which is the cause. (For some strange reason I don't understand, the `bazel` build tool or the `vcpkg` wrapper exchanges `stdout` and `stderr`, so the error log you provided contains just the notification that something went wrong, but the output log will contain the error details...)

I assume the two warnings are unrelated. (Probably `bazel` re-tried the download and it worked the second time. Otherwise I would have expected execution to stop there.)

**Comment by JackBoosY** [comment] 2022-07-29 07:16
According to the [official reply](https://github.com/tensorflow/tensorflow/issues/40561#issuecomment-718133737), I think this issue can be resolved by updating tf-cc.

**Comment by JonLiu1993** [comment] 2023-04-23 08:30
Fixed by PR https://github.com/microsoft/vcpkg/pull/24861.

**Closed by JonLiu1993** 2023-04-23 08:30 UTC
Labels: category:port-bug, category:port-update
