### ISSUE TITLE
[ libmysql] build failure

### ISSUE THREAD

**Issue by Eschryn** [microsoft/vcpkg#11335] opened 2020-05-13 13:59 UTC
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio Build Tools 2019 16.5.5

**To Reproduce**
`./vcpkg install libmysql:x64-windows`

**Failure logs** 
-err.log:
```
FEHLER: Auf dem Remotesystem muss Windows 2000 oder höher ausgeführt werden.
```

```
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: TASKKILL /F /IM gpg-agent.exe /fi "memusage gt 2"
    Working Directory: C:/Users/<USER>/vcpkg/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\Users\<USER>\vcpkg\vcpkg\buildtrees\icu\-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:121 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:78 (vcpkg_acquire_msys)
  scripts/ports.cmake:90 (include)


Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2020.02.04-nohash
```

**Additional context**
I tried updating vcpkg

**Comment by cenit** [comment] 2020-05-13 20:55
Do you have spaces in the path? If so, please move vcpkg to a folder without spaces

**Comment by timautry** [comment] 2020-05-13 21:23
Translated - `ERROR: Windows 2000 or higher must be running on the remote system.`
This message does appear to originate from vcpkg - but from Windows itself while trying to negotiate a secure connection.

**Comment by NancyLi1013** [comment] 2020-05-14 06:22
Hi @Eschryn 
Thanks for posting this issue.
It seems that this is not a port bug. It might be something with the permission on your machine.

Could you please refer to this [link ](https://www.computerhope.com/forum/index.php?topic=128953.0) or look for some other similar info to try it again?

Since I am also not familiar with this. I did some search about this, but I'm not sure if this can work for you.

**Comment by NancyLi1013** [comment] 2020-05-18 06:31
@Eschryn 
Could you please help confirm if this only happens for `libmysql`?
Can you install other ports successfully?

**Comment by timautry** [comment] 2020-05-18 16:54
I think @Eschryn had the same issue with icu - #11334, but it was closed as a duplicate.

**Comment by Eschryn** [comment] 2020-05-18 19:26
Sorry for the late reply - yes i have this issue so far only with this port. Also the link you provided - the images aren't available anymore and the link that was added in the post is broken.

**Comment by NancyLi1013** [comment] 2020-05-19 02:05
`libmysql `has been updated to 8.0.20.
Could you please try to update vcpkg and rebuild this port?

**Comment by NancyLi1013** [comment] 2020-05-29 06:21
@Eschryn 
Does this issue still exist with the latest version?

**Comment by NancyLi1013** [comment] 2020-12-03 09:10
I cannot reproduce this on my machine. Please update vcpkg to the latest version to rebuild or clone a new vcpkg repo.

It might be something with msys, please see https://github.com/microsoft/vcpkg/issues/9427

Please feel free to reopen this if it is still a problem for you.

**Closed by NancyLi1013** 2020-12-03 09:10 UTC
Labels: requires:repro
