### ISSUE TITLE
[boost-variant2] Build error on x64-linux

### ISSUE THREAD

**Issue by sivachandran** [microsoft/vcpkg#38991] opened 2024-05-28 14:04 UTC
Package: boost-variant2:x64-linux@1.85.0

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.4.0
-    vcpkg-tool version: 2024-04-23-d6945642ee5c3076addd1a42c331bbf4cfc97457
    vcpkg-scripts version: dee924de7 2024-05-27 (8 hours ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Downloading https://github.com/boostorg/variant2/archive/boost-1.85.0.tar.gz -> boostorg-variant2-boost-1.85.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /home/sivachandran/Workspace/personal/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /home/sivachandran/Workspace/personal/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://github.com/boostorg/variant2/archive/boost-1.85.0.tar.gz --create-dirs --output /home/sivachandran/Workspace/personal/vcpkg/downloads/boostorg-variant2-boost-1.85.0.tar.gz.1408568.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after   651367 us
[DEBUG] Trying to hash /home/sivachandran/Workspace/personal/vcpkg/downloads/boostorg-variant2-boost-1.85.0.tar.gz.1408568.part
[DEBUG] /home/sivachandran/Workspace/personal/vcpkg/downloads/boostorg-variant2-boost-1.85.0.tar.gz.1408568.part has hash f4f79ab208c534a7e7a285e2722dbe14c7d810a8ad9e73dd2a6de51862b3b08928802251e8661815e5bf9f82eefd10125a984724ae4670823307edc93cd679a8
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/boostorg/variant2/archive/boost-1.85.0.tar.gz
File: /home/sivachandran/Workspace/personal/vcpkg/downloads/boostorg-variant2-boost-1.85.0.tar.gz.1408568.part
Expected hash: 1a5fc662247f3e8437dfeec552fc3c5c380112db4a2e6b0c9e7abad1c06ec0d07dcbb528c244884f2507ac14174f4db3fadfd211e84d9bcd26a5ab5f33cb4d97
Actual hash: f4f79ab208c534a7e7a285e2722dbe14c7d810a8ad9e73dd2a6de51862b3b08928802251e8661815e5bf9f82eefd10125a984724ae4670823307edc93cd679a8
[DEBUG] /source/src/vcpkg/base/downloads.cpp(997): 
[DEBUG] Time in subprocesses: 651367us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 848us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 655 ms (652891us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  buildtrees/versioning_/versions/boost-variant2/71aeea8a9326c7b978940c83970790090ddcf8f9/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "dependencies": [
    "boost-headers",
    "boost-optional",
    "boost-lexical-cast",
    "boost-algorithm",
    "xerces-c",
    "openssl",
    "gtest",
    "nowide",
    "log4cplus",
    "udt",
    "cpp-netlib"
  ],
  "builtin-baseline": "829c9e3def84d777b609784d0820dbfa3284d342"
}

```
</details>

**Comment by Neumann-A** [comment] 2024-05-28 16:16
duplicate of #38974

**Comment by LilyWangLL** [comment] 2024-05-29 05:57
Duplicate of https://github.com/microsoft/vcpkg/issues/38974, PR #38979 will fix this issue.

**Closed by LilyWangLL** 2024-05-29 05:57 UTC
Labels: category:port-bug
