### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by MaxWu8** [microsoft/vcpkg#32619] opened 2023-07-18 11:05 UTC
### Operating system

windows

### Steps to reproduce the behavior

```Shell
I wanted to download colmap using vcpkg, but I always receive the following error message. However, my git pull and vcpkg are up to date.

.\vcpkg install colmap[cuda,tests]:x64-windows
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
  * cgal[core,qt]:x64-windows -> 5.5.2#1
    colmap[core,cuda,tests]:x64-windows -> 2023-03-12#1
  * cuda:x64-windows -> 10.1#13
  * flann:x64-windows -> 2019-04-07#7
  * freeglut:x64-windows -> 3.4.0
  * freeimage:x64-windows -> 3.18.0#25
  * glew:x64-windows -> 2.2.0#3
  * imath:x64-windows -> 3.1.9
  * jasper[core,default-features,opengl]:x64-windows -> 4.0.0#2
  * jxrlib:x64-windows -> 2019.10.9#6
  * lcms:x64-windows -> 2.14
  * libjpeg-turbo:x64-windows -> 2.1.5.1#2
  * libraw:x64-windows -> 0.21.1#1
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows -> 1.3.0#1
  * lz4:x64-windows -> 1.9.4#1
  * openexr:x64-windows -> 3.1.8
  * opengl:x64-windows -> 2022-12-04#3
  * opengl-registry:x64-windows -> 2022-09-29#1
  * openjpeg:x64-windows -> 2.5.0
  * openssl:x64-windows -> 3.1.1#1
  * pcre2[core,jit,platform-default-features]:x64-windows -> 10.42
  * pkgconf:x64-windows -> 1.8.0#5
  * qt5-3d:x64-windows -> 5.15.10
  * qt5-activeqt:x64-windows -> 5.15.10
  * qt5-base:x64-windows -> 5.15.10#3
  * qt5-declarative[core,d3d12,platform-default-features]:x64-windows -> 5.15.10
  * qt5-gamepad:x64-windows -> 5.15.10
  * qt5-imageformats[core,tiff,webp]:x64-windows -> 5.15.10
  * qt5-script:x64-windows -> 5.15.10
  * qt5-svg:x64-windows -> 5.15.10
  * qt5-tools:x64-windows -> 5.15.10
  * qt5-xmlpatterns:x64-windows -> 5.15.10
  * sqlite3[core,json1]:x64-windows -> 3.42.0#1
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.5.1#2
  * vcpkg-pkgconfig-get-modules:x64-windows -> 2023-02-25
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\maxim\AppData\Local\vcpkg\archives in 840 us. Use --debug to see more details.
Installing 1/35 libjpeg-turbo:x64-windows...
Building libjpeg-turbo:x64-windows...
-- Using cached libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz.
-- Cleaning sources at C:/Users/maxim/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/maxim/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-2.1.5.1.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Using source at C:/Users/maxim/vcpkg/buildtrees/libjpeg-turbo/src/2.1.5.1-f411453282.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip -> nasm-2.16.01-win64.zip...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\Users\maxim\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\Users\maxim\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1003):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 2us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 2371us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.5 min (91227705us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_find_acquire_program.cmake:172 (vcpkg_download_distfile)
  ports/libjpeg-turbo/portfile.cmake:21 (vcpkg_find_acquire_program)
  scripts/ports.cmake:147 (include)

error: building libjpeg-turbo:x64-windows failed with: BUILD_FAILED
Elapsed time to handle libjpeg-turbo:x64-windows: 1.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libjpeg-turbo
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libjpeg-turbo]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2Fmaxim%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by autoantwort** [comment] 2023-07-18 11:31
See https://github.com/microsoft/vcpkg/issues/32600

**Comment by Cheney-W** [comment] 2023-07-19 02:01
Duplicate of https://github.com/microsoft/vcpkg/issues/32600

**Closed by Cheney-W** 2023-07-19 02:01 UTC
Labels: category:question
