### ISSUE TITLE
[boost-spirit] build failure

### ISSUE THREAD

**Issue by OlafvdSpek** [microsoft/vcpkg#9241] opened 2019-12-07 10:00 UTC
**Host Environment**
- OS: Windows 7
- Compiler: MSVC 16.5

**To Reproduce**
`./vcpkg install boost-spirit`

**Failure logs** 
```
PS C:\vc\vcpkg> ./vcpkg install boost-spirit
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be built and installed:
    boost-spirit[core]:x86-windows
Starting package 1/1: boost-spirit:x86-windows
Building package boost-spirit[core]:x86-windows...
Warning: abi keys are missing values:
    boost-algorithm
    boost-filesystem
    boost-foreach
    boost-iostreams
    boost-lexical-cast
    boost-locale
    boost-math
    boost-phoenix
    boost-proto
    boost-range
    boost-regex
    boost-thread
    boost-unordered

-- Using cached C:/VC/vcpkg/downloads/boostorg-spirit-boost-1.71.0.tar.gz
-- Using source at C:/VC/vcpkg/buildtrees/boost-spirit/src/ost-1.71.0-80737223c6
-- Packaging headers
-- Packaging headers done
-- Using cached C:/VC/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: C:/VC/vcpkg/packages/boost-spirit_x86-windows/share/boost-spirit/copyright
-- Performing post-build validation
There should be no empty directories in C:\vc\vcpkg\packages\boost-spirit_x86-windows
The following empty directories were found:

    C:/vc/vcpkg/packages/boost-spirit_x86-windows/include/boost/spirit/home/karma/nonterminal

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)


Found 1 error(s). Please correct the portfile:
    C:\vc\vcpkg\ports\boost-spirit\portfile.cmake
-- Performing post-build validation done
Error: Building package boost-spirit:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-spirit:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
```

**Comment by OlafvdSpek** [comment] 2019-12-07 14:43
Note it doesn't happen on a fresh install.. could it be caused by cruft left from previous port versions?

**Comment by PhoebeHui** [comment] 2019-12-09 03:23
@OlafvdSpek, thanks for reporting this issue!

However, I can't repro this issue, it's hard to say what caused the problem. From the failure that spirit/home/karma/nonterminal is empty, actually it should contains some headers, it looks you used cached boost-spirit source, it might due to the headers removed in cached source.

**Comment by OlafvdSpek** [comment] 2019-12-09 08:51
Are you saying there's a bug in the vcpkg caching system?

**Comment by PhoebeHui** [comment] 2019-12-09 10:07
It's not a bug, I mean if you modified boost-spirit build tree, it will affect build results when you try to build it again.

**Comment by OlafvdSpek** [comment] 2019-12-09 10:08
I'm pretty sure I didn't do that.

**Comment by PhoebeHui** [comment] 2019-12-09 10:20
Could you double confirm if C:/VC/vcpkg/buildtrees/boost-spirit/src/ost-1.71.0-80737223c6/include/boost/spirit/home/karma/nonterminal is empty?

**Comment by OlafvdSpek** [comment] 2019-12-09 10:28
No, I deleted the entire vcpkg instance once I noticed installing from scratch worked.
Feel free to close if you think it's a one-time issue.

**Comment by PhoebeHui** [comment] 2019-12-09 10:57
Since we can't repro it, closed it now, and feel free reopen it if you encounter it again.

**Closed by PhoebeHui** 2019-12-09 10:57 UTC
Labels: needs-repro
