### ISSUE TITLE
Ports should include a sample program demonstrating consumption of the port

### ISSUE THREAD

**Issue by jumpinjackie** [microsoft/vcpkg#921] opened 2017-04-08 07:15 UTC
It would serve as a nice simple "unit test" that the port in question works (if you ever setup CI for vcpkg, you can compile and run all the sample programs)

It would also double as documentation on how the port is consumed in CMake/MSBuild/etc

**Comment by KindDragon** [comment] 2017-04-09 17:01
Check issue #72 about that

**Comment by LilyWangL** [comment] 2020-05-27 07:40
Thanks for posting this issue. Closed as duplicate of #72.

**Closed by LilyWangL** 2020-05-27 07:40 UTC
Labels: category:documentation, category:vcpkg-feature
