### ISSUE TITLE
[openssl] doesn't support spaces in path

### ISSUE THREAD

**Issue by Aneutronic** [Microsoft/vcpkg#762] opened 2017-03-10 07:27 UTC
I have been repeatedly getting errors when I try to build OpenSSL with the tuple x64-windows. I keep getting the error message:
`CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Program Files/vcpkg/downloads/cmake-3.8.0-rc1-win32-x86/bin/cmake.exe;--build;.
    Working Directory: C:/Program Files/vcpkg/buildtrees/openssl/x64-windows-rel
    See logs for more information:
      C:\Program Files\vcpkg\buildtrees\openssl\build-x64-windows-rel-out.log
      C:\Program Files\vcpkg\buildtrees\openssl\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  ports/openssl/portfile.cmake:43 (vcpkg_execute_required_process)
  scripts/ports.cmake:73 (include)

Error: Building package openssl:x64-windows failed with: BUILD_FAILED
Please ensure sure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x64-windows
  Vcpkg version: 0.0.75-da09a8136d32890ab5f3804d9abcc5f9685a30e0

Additionally, attach any relevant sections from the log files above.`

The mentioned log files are here.
build-x64-windows-rel-out.log:
[http://pastebin.com/0FQVrSzZ](http://pastebin.com/0FQVrSzZ)

build-x64-windows-rel-err.log
[http://pastebin.com/q7C6mEma](http://pastebin.com/q7C6mEma)

I have no idea what is going on. My version of vcpkg is current, my portfiles are current, and other packages are installing just fine.

Please help!

**Comment by ras0219-msft** [comment] 2017-03-10 19:21
Unfortunately, OpenSSL currently breaks if you have spaces on the path to Vcpkg. We're trying to fix this, but it requires patching OpenSSL's perl-based buildsystem.

The best workaround is to move your vcpkg enlistment to a folder like `C:\vcpkg`. An advanced alternative you might try is using the `subst` command to remap your Vcpkg folder to look like a drive, then build OpenSSL via that -- I haven't tried this, but it might work if you really want to put vcpkg inside program files.

**Comment by ras0219-msft** [comment] 2017-03-10 19:22
Duplicate of #222

**Comment by alexkaratarakis** [comment] 2017-03-20 23:10
Fixed with 463862b94bbad473452605f9f2b3e3d25abb8816.

**Closed by alexkaratarakis** 2017-03-20 23:10 UTC
Labels: port bug
