### ISSUE TITLE
[Podofo] Update to 0.9.7

### ISSUE THREAD

**Issue by VasudhaSahu** [microsoft/vcpkg#16516] opened 2021-03-03 12:15 UTC
Library name:  Podofo

Latest version: 0.9.7

Portfiles and other necessary updates required to get an updated podofo version binaries.

**Comment by JonLiu1993** [comment] 2021-03-04 01:39
Duplicate of #16358

**Closed by JonLiu1993** 2021-03-04 01:39 UTC
Labels: category:port-update

**Comment by VasudhaSahu** [comment] 2021-03-04 08:03
Thanks Team!
