### ISSUE TITLE
[x265] build failure

### ISSUE THREAD

**Issue by akilaln** [microsoft/vcpkg#13047] opened 2020-08-21 04:56 UTC
**Host Environment**
- OS: Windows 10
- Compiler: VS2015

**To Reproduce**
`./vcpkg install openimageio`

**Failure logs** 
Starting package 70/80: x265:x86-windows
Building package x265[core]:x86-windows...
Could not locate cached archive: C:\Users\alakshminarayanan\AppData\Local\vcpkg/archives\f1\f1e716cb3dc26793b04bf0b0e0d145e433b420f9.zip
-- Downloading https://bitbucket.com/multicoreware/x265/get/3.2.tar.gz...
-- Downloading https://bitbucket.com/multicoreware/x265/get/3.2.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:176 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_bitbucket.cmake:127 (vcpkg_download_distfile)
  ports/x265/portfile.cmake:3 (vcpkg_from_bitbucket)
  scripts/ports.cmake:79 (include)

Error: Building package x265:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: x265:x86-windows
  Vcpkg version: 2020.06.15-nohash

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by akilaln** [comment] 2020-08-21 05:07
https://bitbucket.com/multicoreware/x265/get/3.2.tar.gz doesn't exist

**Comment by JonLiu1993** [comment] 2020-08-21 06:38
Thanks for posting this issue. Closed as duplicate of #13035

**Closed** 2020-08-21 06:52 UTC
Labels: category:port-bug
