### ISSUE TITLE
Is it really a good idea to merge debug and release artifacts?

### ISSUE THREAD

**Issue by Fleischner** [microsoft/vcpkg#6895] opened 2019-06-13 22:35 UTC
A serious question. Is it really useful to merge debug and release builds in vcpkg???
I know this was chosen a long time ago, and might be difficult to change, but...

I'm trying to build a new library and currently need to merge generated files as ordered by the post-build check.

So I checked with meld for differences between the files generated by debug and release, and there are so many tiny differences that make merging a nightmare. Why is this required at all? Just for perfection? I see so many roots for strange bugs caused by this, if files in the debug folder get deleted without precise checking. Also differences that are triggered by tuning build options may stay undetected. 

And issues are real. E.g #5540 linking to wrong libraries. Or Qt where dynamic loaded modules get shuffled making distribution unnecessary difficult. 

Looking at disk space, libs and pdbs are by far the major factor. Those must be installed for both targets anyway. So merging includes and cmake files isn't very useful.

Why not leaving debug and release alone, same as x32 and x64 get separate install locations? What are the design drivers for this setup? Can anyone explain?

**Comment by Neumann-A** [comment] 2019-06-14 07:44
> So I checked with meld for differences between the files generated by debug and release, and there are so many tiny differences that make merging a nightmare. 

A list of examples would be nice. If there are differences in the /include folder VCPKG has serious problems. The share folder with the *.cmake files on the other hand must be merged somehow or it totally breaks cmake assumptions about config files and targets for multi configuration generators.

**Comment by heydojo** [comment] 2019-07-15 05:53
@Fleischner
vcpkg is still a fairly young project and a lot of the challenges like the ones you mention are there to solve. Some of the things that pose the biggest challenge are architectural and others are the result of decision making.

There are several well known projects which exist already which attempt to solve the same challenges as vcpkg and it appears (without being too overly critical) that vcpkg has not really learned enough from all of them.
Like for instance, there are design decisions made in other projects which manage libraries (and more) that looking at now, manage derivation in more maintainable and reproducible ways.
This is of course just my opinion.

What you are describing appears to be the result of a design choice. The result of which was pretty inevitable. For better or worse.

**Comment by JackBoosY** [comment] 2020-02-19 13:32
> And issues are real. E.g #5540 linking to wrong libraries. Or Qt where dynamic loaded modules get shuffled making distribution unnecessary difficult.

I think that is a port bug.

We provide both the debug and release libraries by default, because engineers need to perform in-depth debugging.
And we provide a way to generate only debug or release libraries: add `set(VCPKG_BUILD_TYPE debug)` or add `set(VCPKG_BUILD_TYPE release)` to the triplet file.

**Comment by JackBoosY** [comment] 2020-06-01 09:56
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Closed by JackBoosY** 2020-06-01 09:56 UTC
Labels: category:question
