### ISSUE TITLE
[protobuf] update to 3.17.3

### ISSUE THREAD

**Issue by Spejik** [microsoft/vcpkg#19825] opened 2021-08-31 11:36 UTC
Library name: protobuf ([link](https://github.com/protocolbuffers/protobuf))

New version number: 3.17.3

Other information that may be useful (release notes, etc...)  
The version on vcpkg is 3.15.8, which gives a compilation error when using protoc 3.17.3 (proto compiler)  
There is an open issue with the same idea https://github.com/microsoft/vcpkg/issues/18382, but it has no activity since Jun 11

**Comment by JonLiu1993** [comment] 2021-09-01 08:07
Duplicate of #18382, I will commit a pr to update protobuf

**Closed by JonLiu1993** 2021-09-01 08:07 UTC
Labels: category:port-update
