### ISSUE TITLE
vcpkg tool still aborts with "value was null" error.

### ISSUE THREAD

**Issue by GeorgePimpleton** [microsoft/vcpkg#32191] opened 2023-06-23 19:12 UTC
Here's my command line commands I issue to initiate an upgrade with vcpkg:
```
D:\Programming\vcpkg>bootstrap-vcpkg -disableMetrics
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-06-15/vcpkg.exe -> D:\Programming\vcpkg\vcpkg.exe... done.
Validating signature... done.

D:\Programming\vcpkg>git pull
Already up to date.

D:\Programming\vcpkg>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
The following packages differ from their port versions:
        catch2:x64-windows               3.3.2 -> 3.3.2#1
        libjpeg-turbo:x64-windows        2.1.5.1#1 -> 2.1.5.1#2
To update these packages and all dependencies, run
.\vcpkg upgrade'
To only remove outdated packages, run
.\vcpkg remove --outdated

D:\Programming\vcpkg>vcpkg upgrade --no-dry-run >> install.txt

D:\Programming\vcpkg>
```
Here's  the output of the upgrade command:
```
The following packages will be rebuilt:
  * catch2:x64-windows -> 3.3.2#1
  * catch2:x64-windows-static -> 3.3.2#1
  * catch2:x86-windows -> 3.3.2#1
  * fltk[core,opengl]:x64-windows -> 1.3.8#5
  * fltk[core,opengl]:x64-windows-static -> 1.3.8#5
  * fltk[core,opengl]:x86-windows -> 1.3.8#5
  * libjpeg-turbo:x64-windows -> 2.1.5.1#2
  * libjpeg-turbo:x64-windows-static -> 2.1.5.1#2
  * libjpeg-turbo:x86-windows -> 2.1.5.1#2
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.5.0#3
  * tiff[core,jpeg,lzma,zip]:x64-windows-static -> 4.5.0#3
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.5.0#3
  * wxwidgets[core,debug-support,sound]:x64-windows -> 3.2.2.1#3
  * wxwidgets[core,debug-support,sound]:x64-windows-static -> 3.2.2.1#3
  * wxwidgets[core,debug-support,sound]:x86-windows -> 3.2.2.1#3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x64-windows-static...
Detecting compiler hash for triplet x86-windows...
Removing 1/30 catch2:x64-windows
Elapsed time to handle catch2:x64-windows: 407 ms
Removing 2/30 catch2:x64-windows-static
Elapsed time to handle catch2:x64-windows-static: 213 ms
Removing 3/30 catch2:x86-windows
Elapsed time to handle catch2:x86-windows: 308 ms
Removing 4/30 fltk:x64-windows-static
Elapsed time to handle fltk:x64-windows-static: 248 ms
Removing 5/30 fltk:x86-windows
Elapsed time to handle fltk:x86-windows: 197 ms
Removing 6/30 fltk:x64-windows
Elapsed time to handle fltk:x64-windows: 207 ms
Removing 7/30 wxwidgets:x64-windows
Elapsed time to handle wxwidgets:x64-windows: 1.3 s
Removing 8/30 tiff:x64-windows
Elapsed time to handle tiff:x64-windows: 62.8 ms
Removing 9/30 libjpeg-turbo:x64-windows
Elapsed time to handle libjpeg-turbo:x64-windows: 163 ms
Removing 10/30 wxwidgets:x64-windows-static
Elapsed time to handle wxwidgets:x64-windows-static: 1.1 s
Removing 11/30 tiff:x64-windows-static
Elapsed time to handle tiff:x64-windows-static: 43.3 ms
Removing 12/30 libjpeg-turbo:x64-windows-static
Elapsed time to handle libjpeg-turbo:x64-windows-static: 112 ms
Removing 13/30 wxwidgets:x86-windows
Elapsed time to handle wxwidgets:x86-windows: 2.2 s
Removing 14/30 tiff:x86-windows
Elapsed time to handle tiff:x86-windows: 53 ms
Removing 15/30 libjpeg-turbo:x86-windows
Elapsed time to handle libjpeg-turbo:x86-windows: 141 ms
Installing 16/30 catch2:x64-windows...
Building catch2:x64-windows...
-- Note: catch2 only supports static library linkage. Building static library.
-- Downloading https://github.com/catchorg/Catch2/archive/v3.3.2.tar.gz -> catchorg-Catch2-v3.3.2.tar.gz...
-- Extracting source D:/Programming/vcpkg/downloads/catchorg-Catch2-v3.3.2.tar.gz
-- Applying patch fix-install-path.patch
-- Using source at D:/Programming/vcpkg/buildtrees/catch2/src/v3.3.2-2807d59720.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: D:/Programming/vcpkg/packages/catch2_x64-windows/lib/pkgconfig/catch2-with-main.pc
-- Fixing pkgconfig file: D:/Programming/vcpkg/packages/catch2_x64-windows/lib/pkgconfig/catch2.pc
-- Downloading https://mirror.msys2.org/mingw/mingw32/mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw32/mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw32/mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw32/mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw32/mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw32/mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst -> mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/msys/x86_64/msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst;https://repo.msys2.org/msys/x86_64/msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/msys/x86_64/msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst;https://mirror.selfnet.de/msys2/msys/x86_64/msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst -> msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst...
-- Using msys root at D:/Programming/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Fixing pkgconfig file: D:/Programming/vcpkg/packages/catch2_x64-windows/debug/lib/pkgconfig/catch2-with-main.pc
-- Fixing pkgconfig file: D:/Programming/vcpkg/packages/catch2_x64-windows/debug/lib/pkgconfig/catch2.pc
-- Installing: D:/Programming/vcpkg/packages/catch2_x64-windows/share/catch2/copyright
-- Performing post-build validation
internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(888): Value was null
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.
```

**Comment by autoantwort** [comment] 2023-06-24 00:52
Duplicate of https://github.com/microsoft/vcpkg/issues/31908

**Closed** 2023-06-25 06:47 UTC
Labels: category:vcpkg-bug

**Comment by GeorgePimpleton** [comment] 2023-06-25 15:37
vcpkg 2023-06-22 fixed the bug, now the bootstrap.ps1 script needs to be fixed/updated so it is properly distributed when doing a git pull update.

I did a manual edit update to the script to get the new vcpkg version and was able to do a proper installed packages update without having it fail.
