### ISSUE TITLE
find_file_recursively_up suddently causing problems

### ISSUE THREAD

**Issue by Bogfoot** [microsoft/vcpkg#21119] opened 2021-11-01 22:17 UTC
When trying to use vcpkg in any way from any dir other than ~/vcpkg/ (it's installed in that dir, path to vcpkg is ~/vcpkg/vcpkg) I get this:

└[~]> ./vcpkg/vcpkg list
find_file_recursively_up(/home/bogfoot/vcpkg/vcpkg, .vcpkg-root): Not a directory

I just removed and reinstalled vcpkg and I keep getting this message. My .zshrc does not contain any lines which mention vcpkg.
In the meantime, I created a command to change dir to ~/vcpkg/, run the command with arguments $, and change back to current dir.
Does anyone have a fix other than what I just described?

I'm on Ubuntu.

P.S. CMake is confused now due to this. :(

**Comment by Neumann-A** [comment] 2021-11-01 22:22
Hmm I also see this in GA:
`Cannot open assembly 'find_file_recursively_up(/home/runner/work/StochasticPhysics/StochasticPhysics/vcpkg/vcpkg,': No such file or directory.`

**Comment by BillyONeal** [comment] 2021-11-02 00:04
Duplicate of #21107

**Closed by BillyONeal** 2021-11-02 00:04 UTC
