### ISSUE TITLE
[ffmpeg] Recent PR breaks libx264 support

### ISSUE THREAD

**Issue by itsmattkc** [microsoft/vcpkg#21499] opened 2021-11-17 19:47 UTC
**Describe the bug**
PR #21028, which updated libx264 to the latest stable version, also introduced a patch into FFmpeg which seems to have broken it's ability to function with libx264 at runtime.

**Environment**
- OS: Windows 11 22000.318 x64
- Compiler: Visual Studio 2019 x64

**To Reproduce**
1. `./vcpkg install ffmpeg[x264]`
2. FFmpeg will appear to compile correctly, however calling `avcodec_find_encoder_by_name("libx264")` will return `nullptr` and listing the codecs with `av_codec_iterate` will show no instance of libx264.
3. Comment out patch `0019` in FFmpeg's `portfile.cmake`.
4. Reinstall FFmpeg with `./vcpkg remove ffmpeg` and `./vcpkg install ffmpeg[x264]`
5. FFmpeg will once again compile correctly, however this time `avcodec_find_encoder_by_name("libx264")` will return a valid encoder and listing the codecs with `av_codec_iterate` will correctly show libx264 and libx264rgb in the list.

**Expected behavior**
FFmpeg compiled with the `[x264]` feature should actually make libx264 usable through FFmpeg. It's particularly concerning that while this patch seems to completely break libx264 in FFmpeg, no compilation/build error is thrown, which makes this bug harder to detect and diagnose. 

**Failure logs** 
N/A

**Additional context**
The PR does not provide information about why the patch was introduced or exactly what it's supposed to do, so it's hard to judge whether the patch should be removed outright or if it just needs to be modified. As mentioned earlier, the patch can simply be commented out and FFmpeg will still build perfectly fine, so whatever the patch is intended to do, it doesn't appear to be strictly necessary.

It's worth noting that the configure line printed by vcpkg ***does*** include `--enable-libx264`, so it does "think" that libx264 is being compiled. The patch is just somehow breaking it regardless without causing a compilation error:
```
-- Building Options: --toolchain=msvc --enable-pic --disable-doc --enable-debug --enable-runtime-cpudetect --enable-asm --enable-x86asm --enable-gpl --disable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --disable-postproc --enable-swresample --enable-swscale --disable-libaom --disable-libass --disable-avisynth --disable-bzlib --disable-libdav1d --disable-libfdk-aac --disable-libfontconfig --disable-libfreetype --disable-libfribidi --disable-iconv --disable-libilbc --disable-lzma --disable-libmp3lame --disable-libmodplug --disable-cuda --disable-nvenc --disable-nvdec  --disable-cuvid --disable-ffnvcodec --disable-opencl --disable-opengl --disable-libopenh264 --disable-libopenjpeg --disable-openssl --disable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libssh --disable-libtensorflow --disable-libtesseract --disable-libtheora --disable-libvorbis --disable-libvpx --disable-libwebp --enable-libx264 --disable-libx265 --disable-libxml2 --disable-zlib  --disable-static --enable-shared --extra-cflags=-DHAVE_UNISTD_H=0
```

**Comment by JackBoosY** [comment] 2021-12-06 07:07
Hmm.. can you please provide a sample code to reproduce that?
cc @Sibras

**Comment by itsmattkc** [comment] 2021-12-06 07:27
1. Install FFmpeg with the x264 feature enabled: `vcpkg install ffmpeg[x264]`
2. Compile the following simple program with the `vcpkg.cmake` toolchain file:

    <details>
    <summary>CMakeLists.txt</summary>

    ```
    cmake_minimum_required(VERSION 3.20)

    project(x264test LANGUAGES C)

    find_package(FFMPEG REQUIRED)

    add_executable(x264test
      main.c
    )

    target_link_libraries(x264test PRIVATE ${FFMPEG_LIBRARIES})
    target_include_directories(x264test PRIVATE ${FFMPEG_INCLUDE_DIRS})
    ```
    </details>

    <details>
    <summary>main.c</summary>

    ```
    #include <libavcodec/avcodec.h>
    #include <stdio.h>

    int main()
    {
        AVCodec *codec = avcodec_find_encoder_by_name("libx264");
        if (codec != NULL) {
            printf("Found libx264\n");
        } else {
            printf("Did NOT find libx264\n");
        }

        return 0;
    }
    ```
    </details>

3. Run `x264test.exe`
4. Despite compiling FFmpeg with the x264 feature enabled, `Did NOT find libx264` is printed.

**Comment by Sibras** [comment] 2021-12-06 07:50
I can reproduce the issue. One of ffmpegs internal self checks is failing and then silently overriding the enable-libx264 option (which it shouldn't do obviously). Seems to be some checks for old functionality that isn't even used anymore so Ill provide a PR to fix it.

**Comment by Sibras** [comment] 2021-12-07 12:19
Should be fixed in current master now.

**Comment by JackBoosY** [comment] 2021-12-08 06:48
Okay, if anyone meet this issue again, please ping me to reopen this issue!

**Closed by JackBoosY** 2021-12-08 06:48 UTC
Labels: category:port-bug

**Comment by fbriggs** [comment] 2024-10-15 19:25
I'm seeing this issue again in 2024, or something similar. avcodec_find_encoder_by_name("libx264")  doesn't work when installing ffmpeg via vcpkg no matter what other dependencies I include.

**Comment by dg0yt** [comment] 2024-10-15 20:28
@fbriggs Open a new issue and attach a config log.
