### ISSUE TITLE
python3-x64.osx build failure

### ISSUE THREAD

**Issue by puppuluri** [microsoft/vcpkg#12311] opened 2020-07-07 15:02 UTC
**Host Environment**
- OS: OSX
- Compiler: revision

 Package: python3:x64-osx
  Vcpkg version: 2020.06.15-unknownhash

**To Reproduce**
`./vcpkg install python3`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.
Building package python3[core]:x64-osx...
-- Using cached /Users/puppuluri/projects/br/core/build/vcpkg/downloads/python-cpython-v3.8.3.tar.gz
-- Extracting source /Users/puppuluri/projects/br/core/build/vcpkg/downloads/python-cpython-v3.8.3.tar.gz
-- Using source at /Users/puppuluri/projects/br/core/build/vcpkg/buildtrees/python3/src/v3.8.3-43b03f2bf0
-- Configuring x64-osx-rel
-- Building x64-osx-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: make install -j 9
    Working Directory: /Users/puppuluri/projects/br/core/build/vcpkg/buildtrees/python3/src/v3.8.3-43b03f2bf0-x64-osx-release
    See logs for more information:
      /Users/puppuluri/projects/br/core/build/vcpkg/buildtrees/python3/make-build-x64-osx-release-out.log
      /Users/puppuluri/projects/br/core/build/vcpkg/buildtrees/python3/make-build-x64-osx-release-err.log

Call Stack (most recent call first):
  ports/python3/portfile.cmake:150 (vcpkg_execute_build_process)
  scripts/ports.cmake:76 (include)

Error: Building package python3:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-osx
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment] 2020-07-08 02:48
Hi @puppuluri 
Thanks for posting this issue.
Could you please provide the error info from _/Users/puppuluri/projects/br/core/build/vcpkg/buildtrees/python3/make-build-x64-osx-release-out.log_ and _/Users/puppuluri/projects/br/core/build/vcpkg/buildtrees/python3/make-build-x64-osx-release-err.log_?

**Comment by NancyLi1013** [comment] 2020-08-04 09:10
I cannot reproduce this issue on my local. 
I'm closing this issue for now since no active in a long time.

**Closed by NancyLi1013** 2020-08-04 09:10 UTC
Labels: requires:more-information, requires:repro
