### ISSUE TITLE
[sqlite3] cmake fails while building downloaded packages from `vcpkg install <PACKAGE-NAME>` at command `ninja -v`

### ISSUE THREAD

**Issue by hamidb80** [microsoft/vcpkg#17110] opened 2021-04-06 07:23 UTC
cmake fails while building downloaded packages from `vcpkg install <PACKAGE-NAME>` at command `ninja -v`

I also tried different versions of ninja, camke, vcpkg and different packages but i got the same error

**Environment**
- OS: Windows 10
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86

**To Reproduce**
1. ./vcpkg install <PACKAGE-NAME>
2. See error

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: ninja -v
    Working Directory: C:/vcpkg/buildtrees/<PACKAGE-NAME>/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\<PACKAGE-NAME>\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:319 (vcpkg_execute_required_process)
  ports/sqlite3/portfile.cmake:27 (vcpkg_configure_cmake)
  scripts/ports.cmake:128 (include)


Error: Building package <PACKAGE-NAME>:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: <PACKAGE-NAME>:x86-windows
  Vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

Additionally, attach any relevant sections from the log files above.
```

log file:
[config-x86-windows-out.log.txt](https://github.com/microsoft/vcpkg/files/6262760/config-x86-windows-out.log.txt)

**Comment by JackBoosY** [comment] 2021-04-06 07:49
Can you please uninstall the cmake you manually installed and try again?

Thanks.

**Comment by hamidb80** [comment] 2021-04-06 07:55
> Can you please uninstall the cmake you manually installed

i did it 3 times.

also when i enter `ninja -v` in powershell it says:
```
ninja: error: loading 'build.ninja': The system cannot find the file specified.

```

**Comment by JackBoosY** [comment] 2021-04-06 07:59
So I think this issue a permission issue, please clone vcpkg in non-system disk and try again.

Thanks.

**Comment by hamidb80** [comment] 2021-04-06 08:29
> So I think this issue a permission issue, please clone vcpkg in non-system disk and try again

I  cloned vcpkg in `E:\vcpkg` but again, i got the same error
I also tried to run powershell as admin but the resukt was the same

**Comment by hamidb80** [comment] 2021-04-06 09:16
> also when i enter `ninja -v` manually in powershell it says:
> 
> ```
> ninja: error: loading 'build.ninja': The system cannot find the file specified.
> ```

I think this is the root of the problem

**Comment by hamidb80** [comment] 2021-04-06 18:59
that was because I had both `mingw` and `VC` installed, after removing `mingw` paths from environment variables, the problem got fixed/

**Comment by JackBoosY** [comment] 2021-04-06 22:58
Please keep this issue open until we fix this bug.

**Comment by dg0yt** [comment] 2021-04-13 07:28
> that was because I had both `mingw` and `VC` installed, after removing `mingw` paths from environment variables, the problem got fixed/

Did this `mingw` refer to MSYS2? 

One of the subsystems in MSYS2 is not suitable/meant for building software for windows, and the `cmake` MSYS2 package with `/usr/bin/cmake.exe` belongs to that subsystem. So adding this to the path probably needs to be avoided.

**Comment by hamidb80** [comment] 2021-04-14 22:43
> Did this `mingw` refer to MSYS2?

how can I know that?

**Comment by dg0yt** [comment] 2021-04-15 04:14
> how can I know that?

It was installed on your computer:

> "that was because I had both mingw and VC installed, after removing mingw paths from environment variables, the problem got fixed/"

If this mingw is still there, you can check for `/usr/bin/pacman.exe`.
OTOH, there is no hint pointing towards mingw in the log file.

**Comment by hamidb80** [comment] 2021-04-15 07:43
> Did this mingw refer to MSYS2?
I have `MSYS2` installed but it's path is not in environment variables

there are some files with `msys`  in it in `C:\msys64\usr\bin`


> there is no hint pointing towards `mingw` in the log file
that's why I opened this issue

**Comment by hamidb80** [comment] 2021-04-15 07:45
> So adding this to the path probably needs to be avoided.

if this is really the cause of the problem, it should be mentioned in the docs

**Comment by aminya** [comment] 2022-05-18 08:53
I hit the same issue after installing MinGW. `ninja` accepts `--version` as a command-line argument, but it doesn't accept `-v`.

```
> ninja -v                                        
ninja: error: loading 'build.ninja': The system cannot find the file specified.

> ninja --version 
1.10.2
```

I think wherever `ninja -v` is called should be replaced by `ninja --version`. 

Blocks https://github.com/aminya/project_options/pull/126

**Comment by JackBoosY** [comment] 2022-05-18 09:30
> People suggest creating a build.ninja file if it is missing
> 
> [ninja-build/ninja#1463 (comment)](https://github.com/ninja-build/ninja/issues/1463#issuecomment-1119514124)

`build.ninja` will be genereated by cmake in the configure process.

**Comment by aminya** [comment] 2022-05-19 02:39
I realized that the problem is not `ninja -v`, but a package failure (Eigen in my case). The error handling doesn't show the error, and that's why I thought the issue is with ninja.

```cmake
-- Performing Test standard_math_library_linked_to_automatically
-- Performing Test standard_math_library_linked_to_automatically - Failed
-- Performing Test standard_math_library_linked_to_as_m
-- Performing Test standard_math_library_linked_to_as_m - Failed
CMake Error at CMakeLists.txt:108 (message):
  Can't link to the standard math library.  Please report to the Eigen
  developers, telling them about your platform.

```

**Comment by aminya** [comment] 2022-05-21 05:14
This was a MinGW bug. The latest MinGW of chocolatey is buggy compared to the one on the [repository itself](https://github.com/brechtsanders/winlibs_mingw/releases/).
For this reason, I have updated setup-cpp to directly install MinGW from this repository. My tests for GCC now pass.

https://github.com/aminya/setup-cpp

This issue can be closed

**Comment by sfhacker** [comment] 2022-05-21 06:34
@aminya Please, AVOID mixing environments. You are looking for trouble. Your system is now polluted and broken.

**Comment by aminya** [comment] 2022-05-21 06:40
@sfhacker How does your comment relate to this discussion? 😶

**Comment by JackBoosY** [comment] 2022-05-23 02:26
@aminya Ignor him, he often posts off-topic comments.
I will close this issue after the upstream owner confirms.

**Comment by JackBoosY** [comment] 2022-07-29 07:40
Is this issue fixed?

**Comment by PhoebeHui** [comment] 2023-04-13 03:11
This should be MinGW bug which have been fixed now, I installed the latest version of mingw and added it to PATH, the sqlite3 have been successfully installed.

**Closed by PhoebeHui** 2023-04-13 03:11 UTC
Labels: category:port-bug, depends:upstream-changes
