### ISSUE TITLE
[gmp] Build error

### ISSUE THREAD

**Issue by RefenRefen** [microsoft/vcpkg#30562] opened 2023-03-30 23:45 UTC
I tried to install gmp on windows 10 64 bit but this is the error:
I'm not a C++ programmer so please try to answer clearly and full instruction that i can follow

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_acquire_msys.cmake:26 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_acquire_msys.cmake:67 (z_vcpkg_acquire_msys_download_package)
  scripts/cmake/vcpkg_acquire_msys.cmake:345 (z_vcpkg_acquire_msys_declare_package)
  scripts/cmake/vcpkg_configure_make.cmake:224 (vcpkg_acquire_msys)
  ports/gmp/portfile.cmake:85 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)

error: building gmp:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[gmp]+Build+error&body=Copy+issue+body+from+C%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by dg0yt** [comment] 2023-03-31 05:34
Duplicates https://github.com/microsoft/vcpkg/issues/30530
Needs #30546.

**Comment by MonicaLiu0311** [comment] 2023-03-31 07:04
Duplicate of https://github.com/microsoft/vcpkg/issues/30542

**Closed by MonicaLiu0311** 2023-03-31 07:04 UTC
