### ISSUE TITLE
MsBuild Error: Exception Processing Message 0xc0000005

### ISSUE THREAD

**Issue by crazybie** [Microsoft/vcpkg#1889] opened 2017-09-29 08:55 UTC
On my windows 7 system, with vs2013 and vs2017 installed, when install any package from vcpkg, it pops up an error message box:
MsBuild Error: Exception Processing Message 0xc0000005
![qq 20171103103140](https://user-images.githubusercontent.com/7721769/32358617-81b8fc7e-c082-11e7-94d3-9cb13c61735f.png)

and reports error (from log file): 
CMake Error at F:/opensource/vcpkg/scripts/cmake/vcpkg_get_windows_sdk.cmake:10 (message):
  Could not find Windows SDK
Call Stack (most recent call first):
  F:/opensource/vcpkg/scripts/buildsystems/vcpkg.cmake:80 (vcpkg_get_windows_sdk)
  F:/opensource/vcpkg/downloads/cmake-3.9.3-win32-x86/share/cmake-3.9/Modules/CMakeDetermineSystem.cmake:94 (include)
  CMakeLists.txt:125 (PROJECT)

I do have windows SDK 10 installed and I also tried to install SDK 8 but the issue remains.

[config-x86-windows-rel-err.log](https://github.com/Microsoft/vcpkg/files/1343715/config-x86-windows-rel-err.log)

**Comment by Cheney-W** [comment] 2019-02-28 06:38
@crazybie , Thanks for reporting this issue.
I can't reproduce it with the latest vcpkg and VS2017 15.9.7 in Win10 1809, so I close it first.
Please open a new issue if this is still a problem for you.

**Closed by Cheney-W** 2019-02-28 06:38 UTC
