### ISSUE TITLE
OpenSSL-UWP version upgrade?

### ISSUE THREAD

**Issue by arsdever** [microsoft/vcpkg#12109] opened 2020-06-25 14:01 UTC
Hi folks. As I see here

https://github.com/microsoft/vcpkg/blob/70ab27fcad50241d72e0fe235ec4012f0ce7551e/ports/openssl-uwp/portfile.cmake#L31

It is used `v1.1.1d` here, but the existing version in the `OpenSSL` webpage is `v1.1.1g`. I wonder if this is intended to be this particular version or can be upgraded to the latest?

**Comment by Septarius** [comment] 2020-06-26 05:47
Duplicate of #11127 the pull request to update the openssl version is currently pending.

**Comment by arsdever** [comment] 2020-06-26 12:03
@Septarius  thanks for the update. I need a small hint. I just grabbed the PR you made and tried to build the library through `Conan` using the approach `vcpkg` provides. So here's the `Conan` code snippet for the build function
```
        elif self.settings.os == "WindowsStore":
            #tools.replace_in_file("src/include/openssl/dtls1.h", "<winsock.h>", "<winsock2.h>")
            #tools.replace_in_file("src/include/openssl/rand.h", "#  include <windows.h>", "#ifndef _WINSOCKAPI_\n#define _WINSOCKAPI_\n#endif\n#  include <windows.h>")
            with tools.environment_append({'PATH': self.deps_env_info["strawberryperl"].path}):
                vcvars = tools.vcvars_command(self.settings)
                config_command = "Configure  enable-static-engine enable-capieng no-unit-test no-ssl2 no-asm no-uplink no-tests -utf-8 shared"
                config_mapping = { "x86"    : "VC-WIN32-UWP",
                                   "x86_64" : "VC-WIN64A-UWP",
                                   "armv7"  : "VC-WIN32-ARM-UWP",
                                   "armv8"  : "VC-WIN64-ARM-UWP" }
                arch_config = config_mapping[str(self.settings.arch)]
                if self.settings.build_type == "Debug":
                    arch_config = "debug-" + arch_config
                self.run("%s && cd src && perl %s %s -FS" % (vcvars, config_command, arch_config))
                self.run("%s && cd src && nmake && nmake test" % vcvars)
```

> Note: the first two lines are commented out, because of the source code doesn't match the strings we are trying to replace and this throws an error

The compilation process finishes successfully, but the linker fails with below message
```
cryptlib.obj : error LNK2019: unresolved external symbol GetStdHandle referenced in function OPENSSL_showfatal
randfile.obj : error LNK2019: unresolved external symbol GetEnvironmentVariableW referenced in function RAND_file_name
libcrypto-1_1-arm64.dll : fatal error LNK1120: 2 unresolved externals
NMAKE : fatal error U1077: 'link' : return code '0x1'
```
Is this something you have faced so far?

> PS I know there might be a question _"Why are you not using `vcpkg`"_. It is not my choice.

**Comment by Septarius** [comment] 2020-06-27 18:36
I can't say that I faced this before, I have limited experience with UWP and less so with ARM64-UWP so I don't have a toolchain to compile ARM. I was just continuing the original PR since it had stalled out; the UWP patch was already done. 
I know there isn't official support for the community triplets and using Conan makes it less likely that you will find much experience with it here. Sorry I couldn't be much help in this instance :)

**Comment by arsdever** [comment] 2020-06-27 19:58
@Septarius Thanks for what you have already done. No worries about what you can't help. It's not supposed that you should have known all the stuff especially when it is related to Conan. I just wanted to know whether or not you faced. Thanks anyways. BTW should I close this issue or you will do it when the PR is closed?

**Comment by Septarius** [comment] 2020-06-27 19:59
I think if you closed it it would be better. I don't have the ability to close issues either. Best of luck!

**Closed** 2020-06-27 21:00 UTC
