### ISSUE TITLE
[msmpi] build failure

### ISSUE THREAD

**Issue by BenKey** [microsoft/vcpkg#17622] opened 2021-05-02 01:48 UTC
**Host Environment**
- OS: [Windows 10 Pro Version 20H2 build 19042.928 with Windows Feature Experience Pack 120.2212.551.0
- Compiler: Microsoft Visual Studio Community 2019 Version 16.9.4

**To Reproduce**
`./vcpkg install msmpi --triplet x64-windows`

This fails with the following error.

```
  File does not have expected hash:

          File path: [ D:/vcpkg/downloads/temp/msmpisdk-10.1.12498.msi ]
      Expected hash: [ 330fad53c1979dfae786abed228d82c82207f0d61148e2efc1f37c8931838b806eb50554e7f006a56962f748a21f7017c540bd70444b7a93a72c313a64e9254c ]
        Actual hash: [ b0087dfd21423bf87b94b17d7cb03576838585371bbf8b03cca95c3ad73670108c7bc6517b0de852ef595072cc4143be2011636e7242bcb080394d94294848a7 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".
```

I **do not** have a proxy configured!

**Comment by jmkerloch** [comment] 2021-05-04 16:22
Issue confirmed for me.
Our github CI doesn't work anymore since we need boost-mpi installation. 
@JackBoosY : do you have any idea of when this could be merged to the master.

**Comment by JackBoosY** [comment] 2021-05-05 14:32
@jmkerloch Not so long.

**Comment by jmkerloch** [comment] 2021-05-05 15:13
@JackBoosY thanks ! Can't wait to see our CI goes green !

**Closed** 2021-05-06 20:45 UTC
Labels: category:port-update
