### ISSUE TITLE
[Eigen] update to 3.4.0

### ISSUE THREAD

**Issue by bmarques1995** [microsoft/vcpkg#19702] opened 2021-08-22 22:27 UTC
Library name: Eigen

New version number: 3.4.0

Other information that may be useful (release notes, etc...)

**Comment by autoantwort** [comment] 2021-08-22 22:30
Duplicate of #19680

**Comment by JonLiu1993** [comment] 2021-08-23 09:09
@bmarques1995, thanks for posting this issue, it is duplicate of #19680, we will temporarily close this issue.

**Closed by JonLiu1993** 2021-08-23 09:09 UTC
Labels: category:port-update
