### ISSUE TITLE
Error: Building package eigen3:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by semyalodennis** [microsoft/vcpkg#12099] opened 2020-06-25 05:40 UTC
**Host Environment**
- OS: Windows..
- Compiler: msvc++ 14.2

**To Reproduce**
`.\vcpkg install eigen3:x64-windows`

**Failure logs** 
-Error: Building package eigen3:x64-windows failed with: BUILD_FAILED

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment] 2020-06-28 08:15
Hi @semyalodennis 
Thanks for posting this issue.
Could you please post the error info?
I cannot reproduce this on my machine with Visual Studio 2019.

```
PS F:\tools\vcpkg> .\vcpkg.exe install eigen3:x64-windows
Computing installation plan...
The following packages will be built and installed:
    eigen3[core]:x64-windows
Starting package 1/1: eigen3:x64-windows
Building package eigen3[core]:x64-windows...
-- Downloading https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.tar.gz...
-- Extracting source F:/tools/vcpkg/downloads/libeigen-eigen-3.3.7.tar.gz
-- Using source at F:/tools/vcpkg/buildtrees/eigen3/src/3.3.7-c7b55a8243
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig
-- Fixing pkgconfig - release
-- Checking file: F:/tools/vcpkg/packages/eigen3_x64-windows/lib/pkgconfig/eigen3.pc
-- Fixing pkgconfig - debug
-- Checking file: F:/tools/vcpkg/packages/eigen3_x64-windows/debug/lib/pkgconfig/eigen3.pc
-- Fixing pkgconfig --- finished
-- Performing post-build validation
-- Performing post-build validation done
Building package eigen3[core]:x64-windows... done
Installing package eigen3[core]:x64-windows...
Installing package eigen3[core]:x64-windows... done
Elapsed time for package eigen3:x64-windows: 1.359 min

Total elapsed time: 1.361 min

The package eigen3:x64-windows provides CMake targets:

    find_package(Eigen3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Eigen3::Eigen)
```

**Comment by semyalodennis** [comment] 2020-06-30 13:59
Hello team,

Thanks for the reply.
I found out later that my installing path was too long coz other libraries
were failing to install in the same way like eigen 3. When I shortened the
path, it installed successfully.

Thank you.

**Comment by NancyLi1013** [comment] 2020-07-01 01:45
Thanks for your update.
You are right. `eigen3 `has related with the path length. 

You can see this info in ports/eigne3/portfile.cmake file.
[vcpkg_buildpath_length_warning(37)](https://github.com/microsoft/vcpkg/blob/master/ports/eigen3/portfile.cmake#L3)

I'm closing this issue for now since it has been solved.

**Closed by NancyLi1013** 2020-07-01 01:45 UTC
Labels: requires:repro

**Comment by semyalodennis** [comment] 2020-07-01 04:51
Great.
Thanks NancyLi1013 .
