### ISSUE TITLE
[vtk] Build error

### ISSUE THREAD

**Issue by huangjxbq** [microsoft/vcpkg#27081] opened 2022-10-03 12:07 UTC
**Host Environment**

- OS: Windows
- Compiler: Microsoft Visual Studio Community 2019 16.11.19

**To Reproduce**

`./vcpkg install vtk[all]:x64-windows`

**Failure logs**

--- Could NOT find Git (missing: GIT_EXECUTABLE) 
CMake Error at CMake/vtkModuleRemote.cmake:146 (message):
  error: could not find git for clone of MomentInvariants
Call Stack (most recent call first):
  Remote/MomentInvariants.remote.cmake:5 (vtk_fetch_module)
  Remote/CMakeLists.txt:9 (include)

- Attach .\vcpkg\buildtrees\vtk\config-x64-windows-out.log mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by JonLiu1993** [comment] 2022-10-08 09:18
Cofirmed.

**Comment by Bzz2745** [comment] 2023-01-13 06:33
I also ran into this bug, I wonder if you found a way to fix it?

**Comment by JonLiu1993** [comment] 2024-01-19 02:09
Using the latest VTk version now encountering the following error:
````
CMake Warning at F:/Feature-test/boost/scripts/buildsystems/vcpkg.cmake:859 (_find_package):
  By not providing "Findospray.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ospray", but
  CMake did not find one.

  Could not find a package configuration file provided by "ospray" (requested
  version 2.1) with any of the following names:

    osprayConfig.cmake
    ospray-config.cmake

  Add the installation prefix of "ospray" to CMAKE_PREFIX_PATH or set
  "ospray_DIR" to a directory containing one of the above files.  If "ospray"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMake/vtkModule.cmake:4573 (find_package)
  Rendering/RayTracing/CMakeLists.txt:58 (vtk_module_find_package)


CMake Error at CMake/vtkModule.cmake:4579 (message):
  Could not find the ospray external dependency.
Call Stack (most recent call first):
  Rendering/RayTracing/CMakeLists.txt:58 (vtk_module_find_package)
````
Duplicate of https://github.com/microsoft/vcpkg/issues/25579

**Closed by JonLiu1993** 2024-01-19 02:09 UTC
Labels: category:port-bug
