### ISSUE TITLE
qt5 cannot be downloaded on my pc

### ISSUE THREAD

**Issue by Playerfff** [microsoft/vcpkg#34348] opened 2023-10-08 08:22 UTC
Hi @liangshoulong @chen610620, thanks for reporting this issue.
Since qt has been upgrade to 5.12.4, we fixed this issue. Please update vcpkg and rebuild qt5.

Thanks.

_Originally posted by @JackBoosY in https://github.com/microsoft/vcpkg/issues/5881#issuecomment-531622876_
            

Hi, this question merged again on my PC. qt5 version is 5.15.11 and my vcpkg is downloaded just now. while i am using the command: ./vcpkg install qt5:x64-windows-static

my error is below:
10070@DESKTOP-5O9L071 MINGW64 ~/Workspace/vcpkg (master)
$ ./vcpkg.exe install qt5:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
  * brotli:x64-windows -> 1.1.0
  * brotli:x64-windows-static -> 1.1.0
  * bzip2[core,tool]:x64-windows -> 1.0.8#5
  * bzip2[core,tool]:x64-windows-static -> 1.0.8#5
  * double-conversion:x64-windows -> 3.3.0
  * double-conversion:x64-windows-static -> 3.3.0
  * egl-registry:x64-windows -> 2022-09-20
  * egl-registry:x64-windows-static -> 2022-09-20
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.12.1#4
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows-static -> 2.12.1#4
  * harfbuzz:x64-windows-static -> 8.2.1
  * harfbuzz:x64-windows -> 8.2.1
  * libjpeg-turbo:x64-windows -> 3.0.0#2
  * libjpeg-turbo:x64-windows-static -> 3.0.0#2
  * liblzma:x64-windows-static -> 5.4.3#1
  * libpng:x64-windows -> 1.6.39#1
  * libpng:x64-windows-static -> 1.6.39#1
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows-static -> 1.3.2
  * openssl:x64-windows -> 3.1.3
  * openssl:x64-windows-static -> 3.1.3
  * pcre2[core,jit,platform-default-features]:x64-windows -> 10.42#1
  * pcre2[core,jit,platform-default-features]:x64-windows-static -> 10.42#1
  * pkgconf:x64-windows -> 1.8.0#5
    qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols,quickcontrols2,svg,tools,translations,websockets]:x64-windows-static -> 5.15.11
  * qt5-activeqt:x64-windows-static -> 5.15.11
  * qt5-base:x64-windows -> 5.15.11#1
  * qt5-base:x64-windows-static -> 5.15.11#1
  * qt5-declarative[core,d3d12,platform-default-features]:x64-windows-static -> 5.15.11
  * qt5-graphicaleffects:x64-windows-static -> 5.15.11
  * qt5-imageformats[core,tiff,webp]:x64-windows-static -> 5.15.11
  * qt5-multimedia:x64-windows-static -> 5.15.11
  * qt5-networkauth:x64-windows-static -> 5.15.11
  * qt5-quickcontrols:x64-windows-static -> 5.15.11
  * qt5-quickcontrols2:x64-windows-static -> 5.15.11
  * qt5-svg:x64-windows-static -> 5.15.11
  * qt5-tools:x64-windows-static -> 5.15.11
  * qt5-translations:x64-windows-static -> 5.15.11
  * qt5-websockets:x64-windows-static -> 5.15.11
  * sqlite3[core,json1]:x64-windows -> 3.43.1
  * sqlite3[core,json1]:x64-windows-static -> 3.43.1
  * tiff[core,jpeg,lzma,zip]:x64-windows-static -> 4.6.0
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars:x64-windows -> 2023-03-02
  * vcpkg-pkgconfig-get-modules:x64-windows -> 2023-09-06
  * vcpkg-tool-meson:x64-windows -> 0.63
  * zlib:x64-windows -> 1.3
  * zlib:x64-windows-static -> 1.3
  * zstd:x64-windows -> 1.5.5#1
  * zstd:x64-windows-static -> 1.5.5#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:2802".
A suitable version of powershell-core was not found (required v7.2.11) Downloading portable powershell-core 7.2.11...
Extracting powershell-core...
'CMake' failed while extracting C:\Users\10070\Workspace\vcpkg\downloads\PowerShell-7.2.11-win-x86.zip.

**Comment by MonicaLiu0311** [comment] 2023-10-08 09:03
>    Extracting powershell-core...
>   'CMake' failed while extracting C:\Users\10070\Workspace\vcpkg\downloads\PowerShell-7.2.11-win-x86.zip.

This is an error that occurs when extracting.

**Comment by MonicaLiu0311** [comment] 2023-10-08 09:05
Duplicate of https://github.com/microsoft/vcpkg/issues/33904.

**Closed by MonicaLiu0311** 2023-10-08 09:05 UTC
Labels: category:vcpkg-bug
