### ISSUE TITLE
[cpr] update to 1.6.0

### ISSUE THREAD

**Issue by John4266** [microsoft/vcpkg#16960] opened 2021-03-30 07:15 UTC
Library name: CPR

New version number: 1.6.0

Other information that may be useful (release notes, etc...)
Port Github: https://github.com/whoshuu/cpr

The new version includes fixes for static buildings on windows.

**Comment by JonLiu1993** [comment] 2021-05-12 03:04
Duplicate of #17841

**Closed by JonLiu1993** 2021-05-12 03:04 UTC
Labels: category:port-update
