### ISSUE TITLE
i hope somebody can add the spidermonkey or google v8 lib to the list

### ISSUE THREAD

**Issue by joywish** [Microsoft/vcpkg#1784] opened 2017-09-05 14:22 UTC
i hope  somebody can can add the spidermonkey or google v8 lib to the list

**Comment by atkawa7** [comment] 2017-09-05 15:02
@joywish 👍  see #372

**Comment by NancyLi1013** [comment] 2019-04-23 08:09
Duplicate of #372.

**Closed by NancyLi1013** 2019-04-23 08:09 UTC
Labels: new port request - consider making a PR!
