### ISSUE TITLE
[osgearth] build failure

### ISSUE THREAD

**Issue by jepessen** [microsoft/vcpkg#11696] opened 2020-06-01 15:46 UTC
**Host Environment**
- OS: Ubuntu 20.04 64 bit (WSL2)
- Compiler: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

**To Reproduce**
`./vcpkg install osgearth`

**Failure logs** 
Starting package 1/14: osgearth:x64-linux
Building package osgearth[core]:x64-linux...
-- Note: osgearth only supports dynamic library linkage. Building dynamic library.
CMake Error at ports/osgearth/portfile.cmake:8 (message):
  Could not determine osg version
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)

Error: Building package osgearth:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: osgearth:x64-linux
  Vcpkg version: 2020.02.04-unknownhash

This error does not allow me to build osgearth.

vcpkg revision is 6d36e2a86baf8d227fc6dce587bd69997d67fb5e

**Comment by LilyWangL** [comment] 2020-06-02 09:52
Waiting for PR #11715 merge, this PR fix osg build error.

**Comment by jepessen** [comment] 2020-06-02 21:29
> Have you installed osg?

Yes it's installed.

**Comment by LilyWangL** [comment] 2020-06-04 09:25
Thanks for posting this issue. Closed as duplicate of #11614.

**Closed by LilyWangL** 2020-06-04 09:25 UTC
Labels: requires:repro
