### ISSUE TITLE
installing openssl fails (needed by curl)

### ISSUE THREAD

**Issue by bitsrules** [Microsoft/vcpkg#2200] opened 2017-11-15 02:45 UTC
When I try to install openssl it fails. I am using Windows 7.
Package: openssl:x86-windows
Vcpkg version: 0.0.97-2017-11-14-2b7cd655c8d52ce40453497ecc06c81dc2977aab

The error messages says:
`-- Downloading https://www.openssl.org/source/openssl-1.0.2m.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this  libcurl due to a build-time decision."
`
and when I check the openssl web site the file is not there.

Here is what I tried to do:
```
C:\dev\github\vcpkg>.\vcpkg.exe install curl  --debug
The following packages will be built and installed:
    curl:x86-windows
  * libssh2:x86-windows
  * openssl:x86-windows
Additional packages (*) will be installed to complete this operation.
Starting package 1/3: openssl:x86-windows
Building package openssl:x86-windows...
[DEBUG] _wpopen("where.exe cmake 2>&1")
[DEBUG] _pclose() returned 1
[DEBUG] _wpopen(""C:\dev\github\vcpkg\downloads\cmake-3.9.5-win32-x86\bin\cmake.
exe" --version 2>&1")
[DEBUG] _pclose() returned 0
[DEBUG] _wpopen("where.exe git 2>&1")
[DEBUG] _pclose() returned 0
[DEBUG] _wpopen(""C:\dev\github\vcpkg\downloads\MinGit-2.15.0-32-bit\cmd\git.exe
" --version 2>&1")
[DEBUG] _pclose() returned 0
[DEBUG] _wpopen(""C:\dev\github\vcpkg\downloads\cmake-3.9.5-win32-x86\bin\cmake.
exe" "-DCMAKE_TRIPLET_FILE=C:/dev/github/vcpkg/triplets/x86-windows.cmake" -P "C
:/dev/github/vcpkg/scripts/get_triplet_environment.cmake" 2>&1")
[DEBUG] _pclose() returned 0
[DEBUG] _wpopen("powershell -NoProfile -ExecutionPolicy Bypass -Command "& {& 'C
:\dev\github\vcpkg\scripts\findVisualStudioInstallationInstances.ps1' }" 2>&1")
[DEBUG] _pclose() returned 0
[DEBUG] CreateProcessW(cmd.exe /c ""C:\Program Files (x86)\Microsoft Visual Stud
io\2017\Professional\VC\Auxiliary\Build\vcvarsall.bat"  amd64_x86   2>&1 && "C:\
dev\github\vcpkg\downloads\cmake-3.9.5-win32-x86\bin\cmake.exe" "-DCMD=BUILD" "-
DPORT=openssl" "-DCURRENT_PORT_DIR=C:/dev/github/vcpkg/ports/openssl/." "-DTARGE
T_TRIPLET=x86-windows" "-DVCPKG_PLATFORM_TOOLSET=v141" "-DVCPKG_USE_HEAD_VERSION
=0" "-D_VCPKG_NO_DOWNLOADS=0" "-DGIT=C:/dev/github/vcpkg/downloads/MinGit-2.15.0
-32-bit/cmd/git.exe" "-DFEATURES=" -P "C:/dev/github/vcpkg/scripts/ports.cmake""
)
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.4.3
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64_x86'
-- CURRENT_INSTALLED_DIR=C:/dev/github/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/dev/github/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/dev/github/vcpkg/packages/openssl_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/dev/github/vcpkg/buildtrees/openssl
-- CURRENT_PORT_DIR=C:/dev/github/vcpkg/ports/openssl/.
-- Downloading https://www.openssl.org/source/openssl-1.0.2m.tar.gz...
-- Downloading https://www.openssl.org/source/openssl-1.0.2m.tar.gz... Failed. S
tatus: 4;"A requested feature, protocol or option was not found built-in in this
 libcurl due to a build-time decision."
-- Downloading https://www.openssl.org/source/old/1.0.2/openssl-1.0.2m.tar.gz...

-- Downloading https://www.openssl.org/source/old/1.0.2/openssl-1.0.2m.tar.gz...
 Failed. Status: 4;"A requested feature, protocol or option was not found built-
in in this libcurl due to a build-time decision."
CMake Error at C:/dev/github/vcpkg/scripts/cmake/vcpkg_download_distfile.cmake:9
1 (message):


      Failed to download file.
      Add mirrors or submit an issue at https://github.com/Microsoft/vcpkg/issue
s

Call Stack (most recent call first):
  C:/dev/github/vcpkg/ports/openssl/portfile.cmake:19 (vcpkg_download_distfile)
  C:/dev/github/vcpkg/scripts/ports.cmake:72 (include)


[DEBUG] CreateProcessW() returned 1
Error: Building package openssl:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x86-windows
  Vcpkg version: 0.0.97-2017-11-14-2b7cd655c8d52ce40453497ecc06c81dc2977aab

Additionally, attach any relevant sections from the log files above.
[DEBUG] ..\src\vcpkg\install.cpp(526)

```

**Comment by alexkaratarakis** [comment] 2017-11-16 08:52
Just to clarify, downloading:
https://www.openssl.org/source/openssl-1.0.2m.tar.gz
does not work?

**Comment by NancyLi1013** [comment] 2019-02-19 06:51
Hi @bitsrules, does it work normally on your machine now?
I can't reproduce it . could you please help confirm whether this issue has been fixed on your machine?
If fixed, please close it.
Thanks.

**Comment by NancyLi1013** [comment] 2019-02-26 02:12
Please open a new issue if this is still a problem for you.

**Closed by NancyLi1013** 2019-02-26 02:12 UTC
Labels: needs-repro
