### ISSUE TITLE
[vcpkg upgrade] Crash when trying to update a specific port that is not installed

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg#24789] opened 2022-05-18 21:58 UTC
Logs:
```
>vcpkg upgrade catch2 --no-dry-run --triplet x64-windows
The following packages are not installed:
    catch2:x64-windows

internal error: D:\a\_work\1\s\src\vcpkg\commands.upgrade.cpp(191): vcpkg has crashed; no additional details are available.
```

**Expected behaviour**
Exit without crash

**Comment by LilyWangLL** [comment] 2022-06-10 09:35
Closed as duplicate of #21117.

**Closed by LilyWangLL** 2022-06-10 09:35 UTC
Labels: category:vcpkg-bug
