### ISSUE TITLE
[openvdb] build failure

### ISSUE THREAD

**Issue by freestriker** [microsoft/vcpkg#31206] opened 2023-05-02 09:06 UTC
### Operating system

Windows 11 22H2 22621.1635

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install openvdb --triplet=x64-windows
```

### Failure logs

[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/11371529/install-x64-windows-static-dbg-out.log)

### Additional context

installed latest vcpkg and english version vs2022 community
the default x86-windows was compiled successed by vcpkg, but the x64-windows-static is faild

**Comment by Adela0814** [comment] 2023-05-05 10:16
Duplicate of https://github.com/microsoft/vcpkg/issues/26993.

**Closed by Adela0814** 2023-05-05 10:16 UTC
Labels: category:port-bug
