### ISSUE TITLE
Error: Building package opengl:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by icsharp** [microsoft/vcpkg#8219] opened 2019-09-17 15:54 UTC
**Host Environment**
- OS: Windows 10.0.17134

**To Reproduce**
`./vcpkg install tesseract:x64-windows

**Failure logs** 
The following packages will be built and installed:
  * leptonica[core]:x64-windows
  * libwebp[core]:x64-windows
  * opengl[core]:x64-windows
  * tesseract[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: opengl:x64-windows
Building package opengl[core]:x64-windows...
CMake Error at ports/opengl/portfile.cmake:20 (message):
  **Cannot find Windows 10.0.18362.0 SDK.**  File does not exist: C:\Program
  Files (x86)\Windows Kits\10\Lib\10.0.18362.0\um\x64\OpenGL32.Lib
Call Stack (most recent call first):
  scripts/ports.cmake:91 (include)

Error: Building package opengl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opengl:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**

I used Visual Studio 2019 but I could not find the low version Windows 10.0.18362.0 SDK in Visual Studio Installer.  Windows 10.0.18362.0 SDK should be embedded in VS 2017 rather than VS2019 .

**Comment by LilyWangL** [comment] 2019-09-18 02:30
Thanks for posting this issue. Closed as duplicate of #5495. Please pay attention to the progress of issue #5495.

**Closed by LilyWangL** 2019-09-18 02:30 UTC
Labels: port bug
