### ISSUE TITLE
libogg build fails without CMake v3.7.2 x86 binaries installed, fails to check for prerequisites

### ISSUE THREAD

**Issue by 4creators** [Microsoft/vcpkg#613] opened 2017-01-30 21:39 UTC
While testing vcpkg libraries libogg x86 build failed indicating in logs that no c and cxx compilers were detected (win10 v1607, VS2015 U3, VS2017 RC, CMake v3.7.2.x64 available via PATH). Accidentally by building sqlite3 which installed CMake 3.7.2. x86 binaries the error was fixed.

Seems that library does not handle properly x64 and x86 builds and in situation when use of x86 CMake is a requirement and does not check prerequisites and installs them if needed like sqlite3 does.

**Comment by ras0219-msft** [comment] 2017-01-31 03:04
(Probably) duplicate of #611. I'll reopen this if we can determine it's package specific.

**Closed by ras0219-msft** 2017-01-31 03:04 UTC
