### ISSUE TITLE
vcpkg tool: `vcpkg-configuraion.json` now requires `default-registry` to be present

### ISSUE THREAD

**Issue by antkmsft** [microsoft/vcpkg#29585] opened 2023-02-11 02:28 UTC
Before November-December 2022, it was possible to have a `vcpkg-configuration.json` that looked like this:
```json
{
  "registries": [
    {
      "kind": "git",
      "repository": "https://github.com/Azure/azure-sdk-vcpkg-betas",
      "baseline": "733d7216b2e19365127b8578e1b4b2056dcaa970",
      "packages": [
        "azure-core-cpp",
        "azure-identity-cpp",
        "azure-security-keyvault-certificates-cpp",
        "azure-security-keyvault-keys-cpp",
        "azure-security-keyvault-secrets-cpp",
        "azure-storage-blobs-cpp",
        "azure-storage-common-cpp",
        "azure-storage-files-datalake-cpp",
        "azure-storage-files-shares-cpp",
        "azure-storage-queues-cpp",
        "azure-security-attestation-cpp",
        "azure-core-tracing-opentelemetry-cpp"
      ]
    }
  ]
}
```

All worked fine. It would pull the ports that are listed in the config from our private registry, and the ones that are not there, it would pull from this repo.

Now if you use it (`vcpkg install azure-core-cpp`), it says:
```
error: The configuration defined in C:\src\vcpkg\vcpkg-configuration.json is invalid.
Using registries requires that a baseline is set for the default registry or that the default registry is null.
See https://github.com/Microsoft/vcpkg/tree/master/docs/users/registries.md for more details.
```

Setting `"default-registry"` to `null` does not work for us because it will not fall through this repo for the packages that are not found (our dependencies such as `curl`).

If we set it, it requires `baseline` to be set to a commit SHA from this repo. We also don't want to do that, because we want for the users' vcpkg to keep working exactly as before, with the current baseline of what they had. And logistically, for us, updating it regularly will be hard (here is our consumption model: https://github.com/Azure/azure-sdk-vcpkg-betas/blob/12068478c142d6fb95df9cdf960a0bb22c026300/README.md).

**Comment by BillyONeal** [comment] 2023-02-11 07:59
@vicroms I believe this check was added in:

https://github.com/microsoft/vcpkg-tool/pull/778/files#diff-a7dc1f432d5bfbd00785a5742acaa7861bf9279fabbcb1131612ee56f89bf8eaR182-R200

**Comment by strega-nil-ms** [comment] 2023-02-13 16:41
For classic installations, it makes sense to not have a baseline (the baseline is just the classic style `git clone`)

**Comment by gracicot** [comment] 2023-02-17 18:37
I was also hit by this, we updated the vcpkg repo but we kept vcpkg-tool to `2022-11-10` to avoid this problem. We simply want to keep our current config working unless there's a port guide somewhere and it's not a bug.

**Comment by antkmsft** [comment] 2023-02-24 01:05
Can this be fixed within the next week? We have automation that updates https://github.com/Azure/azure-sdk-vcpkg-betas/, and we're going to run it in a week from now to toggle the next series of beta releases. With this bug, in place, we'll need to craft it by hand (plus customers using it won't be able to use the pirvate registry as intended).

**Comment by BillyONeal** [comment] 2023-02-25 06:39
I think @vicroms was working on a fix; if he has something ready by then we can do a tool release just to pick that up but can't promise anything at this time. The behavior you were experiencing wasn't really "intended" behavior; my extremely limited understanding is that as a result it wouldn't give you the behavior you're expecting reliably; but we do intend to put the behavior you expect in place.

**Comment by strega-nil-ms** [comment] 2023-02-28 18:17
@BillyONeal fwiw, my intention was the old behaviour.

**Comment by antkmsft** [comment] 2023-04-07 17:12
Maybe you could at least make `default-registry.baseline` optional (missing = latest SHA), so then we could put it in the `vcpkg-configuration.json` that we publish in our private registry (https://github.com/Azure/azure-sdk-vcpkg-betas) and that would practically be equivalent of the consumption model that we intend to offer to our customers.

**Comment by antkmsft** [comment] 2023-04-07 17:30
It's not how it used to be, but maybe then the same could be done for `registries[N].baseline`, and that would enable convenient consumption model for us: user patches their vcpkg installation once, and get special channel for our ports forever (unless we add new ports that were not listed in the `vcpkg-configuration.json` at a time they copied config to their vcpkg dierectory).

**Comment by bmegli** [comment] 2023-06-29 09:40
@antkmsft 

> All worked fine. It would pull the ports that are listed in the config from our private registry, and the ones that are not there, it would pull from this repo.

I think you might replicate this behavior with [`builtin`](https://learn.microsoft.com/en-us/vcpkg/maintainers/registries#builtin-registries) registry
- this should point default to your local clone of vcpkg
- it's a bummer you still need to define baseline sha
  - just paste the commit SHA of your local vcpkg clone (e.g. `git log`)

> we want for the users' vcpkg to keep working exactly as before, with the current baseline of what they had.
- they would paste their clone commit SHA as baseline

```json
{
  "default-registry": {
    "kind": "builtin",
    "baseline": "4a1035927d26de8601513a0591ba99213d3bcfbc"
  },
{
  "registries": [
    {
      "kind": "git",
      "repository": "https://github.com/Azure/azure-sdk-vcpkg-betas",
      "baseline": "733d7216b2e19365127b8578e1b4b2056dcaa970",
      "packages": [
        "azure-core-cpp",
        "azure-identity-cpp",
        "azure-security-keyvault-certificates-cpp",
        "azure-security-keyvault-keys-cpp",
        "azure-security-keyvault-secrets-cpp",
        "azure-storage-blobs-cpp",
        "azure-storage-common-cpp",
        "azure-storage-files-datalake-cpp",
        "azure-storage-files-shares-cpp",
        "azure-storage-queues-cpp",
        "azure-security-attestation-cpp",
        "azure-core-tracing-opentelemetry-cpp"
      ]
    }
  ]
}
```

----------------------------------

@strega-nil-ms

> For classic installations, it makes sense to not have a baseline (the baseline is just the classic style git clone)

Totally agreed. The above may be a way to say it explicitly (unfortunately you still need to dump the local git clone SHA as baseline)

**Comment by gracicot** [comment] 2023-07-01 21:15
I am still affected by this issue and I have not upgraded since.

This is a **breaking change** and any breaking change should have an official port guide. Please, I just want to know if this is gonna be fixed, and if not, how can I port my projects to the new vcpkg. Thank you.

**Comment by antkmsft** [comment] 2023-07-07 00:48
Thank you @vicroms - speaking for ourselves, the solution works us.

**Comment by gracicot** [comment] 2023-07-07 03:10
@vicroms Thank you! I'll do that then when upgrading. Now it's clear that it was intentional and there's a clear step to port the config

**Comment by vicroms** [comment] 2023-07-17 18:16
Closed as this change was intended by design.

**Closed by vicroms** 2023-07-17 18:16 UTC
Labels: category:vcpkg-bug

**Comment by gracicot** [comment] 2023-07-17 18:55
Ah! I got it working. We can ask vcpkg to fetch the baseline from the vcpkg repo instead of the builtin one.

Here's the lines I needed to add in my configuration:

```js
	"default-registry": {
	  "kind": "git",
	  "repository": "https://github.com/microsoft/vcpkg",
	  "baseline": "f6a5d4e8eb7476b8d7fc12a56dff300c1c986131"
	},
```
