### ISSUE TITLE
pcl BUILD_FAILED with vcpkg  compiler vs2022_17.0.1

### ISSUE THREAD

**Issue by EsMgAl** [microsoft/vcpkg#21531] opened 2021-11-19 04:00 UTC
the log show the error: D:\vcpkg\buildtrees\pcl\src\89d532cf08-fd49a85837.clean\surface\src\3rdparty\opennurbs\opennurbs_lookup.cpp(670) : fatal error C1001: Internal compiler error.
(compiler file 'd:\a01\_work\20\s\src\vctools\Compiler\Utc\src\p2\main.c', line 217)

use the baseline:"builtin-baseline": "cbc22a396c88d098247fe7f79f0913a952e1f77d"

**Comment by JonLiu1993** [comment] 2021-11-19 06:34
@EsMgAl ,Thanks for posting this issue , pcl build error with vs2022. it's duplicate of issue https://github.com/microsoft/vcpkg/issues/19561#issuecomment-898879852, let's track this issue in it, template close this issue,
please feel free reopen this issue if you have another question.

**Closed by JonLiu1993** 2021-11-19 06:34 UTC
Labels: requires:repro
