### ISSUE TITLE
[v8] build failure

### ISSUE THREAD

**Issue by MrAhmedSayedAli** [microsoft/vcpkg#15939] opened 2021-01-29 14:53 UTC
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install v8`

**Failure logs** 
```
    Error code: 1
    See logs for more information:
      F:\CPP\vcpkg\buildtrees\v8\generate-x86-windows-dbg-out.log
      F:\CPP\vcpkg\buildtrees\v8\generate-x86-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_gn.cmake:47 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_gn.cmake:55 (generate)
  ports/v8/portfile.cmake:145 (vcpkg_configure_gn)
  scripts/ports.cmake:128 (include)


Error: Building package v8:x86-windows failed with: BUILD_FAILED
```

**buildtrees\v8\generate-x86-windows-dbg-err.log**
```
Traceback (most recent call last):
  File "F:/CPP/vcpkg/buildtrees/v8/src/15c22b1cff-c34597ce8b.clean/build/toolchain/win/setup_toolchain.py", line 304, in <module>
    main()
  File "F:/CPP/vcpkg/buildtrees/v8/src/15c22b1cff-c34597ce8b.clean/build/toolchain/win/setup_toolchain.py", line 254, in main
    vc_lib_path = FindFileInEnvList(env, 'LIB', ';', 'msvcrt.lib')
  File "F:/CPP/vcpkg/buildtrees/v8/src/15c22b1cff-c34597ce8b.clean/build/toolchain/win/setup_toolchain.py", line 211, in FindFileInEnvList
    file_name, env_name, '\n'.join(parts))
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86

Check if it is installed.
Traceback (most recent call last):
  File "F:/CPP/vcpkg/buildtrees/v8/src/15c22b1cff-c34597ce8b.clean/build/toolchain/win/setup_toolchain.py", line 304, in <module>
    main()
  File "F:/CPP/vcpkg/buildtrees/v8/src/15c22b1cff-c34597ce8b.clean/build/toolchain/win/setup_toolchain.py", line 254, in main
    vc_lib_path = FindFileInEnvList(env, 'LIB', ';', 'msvcrt.lib')
  File "F:/CPP/vcpkg/buildtrees/v8/src/15c22b1cff-c34597ce8b.clean/build/toolchain/win/setup_toolchain.py", line 211, in FindFileInEnvList
    file_name, env_name, '\n'.join(parts))
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86

Check if it is installed.
```

**Comment by JackBoosY** [comment] 2021-02-01 03:03
Can you provide your installed Windows 10 SDK version?
And please check folder _C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0_ if it exist.

**Comment by MrAhmedSayedAli** [comment] 2021-02-03 20:30
@JackBoosY 
yes C:\Program Files (x86)\Windows Kits\10\Lib\10.0.19041.0  exist.

**Comment by JackBoosY** [comment] 2021-02-04 02:42
@Kwizatz  Can you please take a look?
The path to find msvcrt.lib is incorrect.

**Comment by Kwizatz** [comment] 2021-02-04 04:08
What are the contents of
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86
? 
Is the x86 sdk installed and not just x64?
Note that you must install the stand alone sdk, Not within the VS installer, but this seems to be the case here. 

I am working on the update to 8.8, which will include a check for the SDK.

**Comment by Kwizatz** [comment] 2021-02-04 04:43
I think, this could be the same issue as  #15351

**Comment by JackBoosY** [comment] 2021-02-04 05:39
@Kwizatz `msvcrt.lib` should in Visual Studio directory, not Windows SDK directory.

**Comment by MrAhmedSayedAli** [comment] 2021-02-04 14:55
![01](https://user-images.githubusercontent.com/7157140/106910185-a412e380-6709-11eb-92ff-b57710658b47.png)
![02](https://user-images.githubusercontent.com/7157140/106910205-a8d79780-6709-11eb-9af4-7121a89cfa8c.png)
![03](https://user-images.githubusercontent.com/7157140/106910217-ad03b500-6709-11eb-969a-ec28a6b8f75b.png)
![04](https://user-images.githubusercontent.com/7157140/106910231-b12fd280-6709-11eb-99b7-ad8295ce1f89.png)

**Comment by Kwizatz** [comment] 2021-02-04 16:14
Hi @JackBoosY 
> @Kwizatz `msvcrt.lib` should in Visual Studio directory, not Windows SDK directory.

Right, however there's been no changes since last time and @heretic13 reported a successful compilation in #15351,
so there has to be something wrong with the VS studio installation, the LIB env variable listing ONLY these 2 directories is suspect:

`AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86`

Shouldn't it also point to something inside C:\Program Files (x86)\Microsoft Visual Studio\2019?

**Comment by Kwizatz** [comment] 2021-02-04 16:21
Hi @MrAhmedSayedAli 

Quick question, are you running vcpkg from a "x86 Native Tools Command Prompt For VS 2019"?

**Comment by MrAhmedSayedAli** [comment] 2021-02-04 16:26
@Kwizatz 
![01](https://user-images.githubusercontent.com/7157140/106923057-5a7cc580-6716-11eb-90ae-0ce9e53f33bc.png)

**Comment by Kwizatz** [comment] 2021-02-04 16:36
Ok, It may be the other thing I was thinking of...

You have the Windows SDK installed in drive C, the VCPKG repo at F and Visual Studio installed in D.

That may be affecting how GN/setup_toolchain.py/vs_toolchain.py finds the paths somehow.

**Comment by JackBoosY** [comment] 2021-02-05 02:24
@Kwizatz  I think so.

**Comment by Kwizatz** [comment] 2021-02-05 02:39
@JackBoosY is this configuration supported by vcpkg?
I guess I can try to reproduce the setup with a VM... But I rather not 😜

**Comment by JackBoosY** [comment] 2021-02-05 05:39
@Kwizatz Sadly, not.

**Comment by odysseus654** [comment] 2021-04-25 01:31
I hacked at this for a little while (with my Visual Studio installed on D:) and managed to get something working with these changes to the portfile (hopefully nothing else I did was relevant):
```Diff
index a76869fe03..d9b5ad1074 100644
--- a/cmake/ports/v8/portfile.cmake
+++ b/cmake/ports/v8/portfile.cmake
@@ -2,6 +2,7 @@
 set(pkgver "9.0.257.17")

 set(ENV{DEPOT_TOOLS_WIN_TOOLCHAIN} 0)
+set(ENV{GYP_MSVS_OVERRIDE_PATH} "D:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\")

 get_filename_component(GIT_PATH ${GIT} DIRECTORY)
 vcpkg_find_acquire_program(PYTHON2)
@@ -22,7 +23,7 @@ if(WIN32)
   vcpkg_add_to_path("${MSYS_ROOT}/usr/bin")
 endif()

-set(VCPKG_KEEP_ENV_VARS PATH;DEPOT_TOOLS_WIN_TOOLCHAIN)
+set(VCPKG_KEEP_ENV_VARS PATH;DEPOT_TOOLS_WIN_TOOLCHAIN;GYP_MSVS_OVERRIDE_PATH)

 function(v8_fetch)
   set(oneValueArgs DESTINATION URL REF SOURCE)
```
This obviously isn't something that can be PRed as-is but might be useful as a direction to go in (for starters, would be nice to know how to get an environment variable from cmdline to the portfile rather than hardcoding it in here).

**Comment by Kwizatz** [comment] 2021-04-25 18:08
@odysseus654 was this before or after stable version 9.0.x merged this week?

That last patch might take care of this as it sets the path GN expects to be set, but this change could probably a missing piece of the puzzle.

Thanks!

**Comment by Kwizatz** [comment] 2021-04-25 18:15
Most portable way would be something similar to:
```diff
index a76869fe03..d9b5ad1074 100644
--- a/cmake/ports/v8/portfile.cmake
+++ b/cmake/ports/v8/portfile.cmake
@@ -2,6 +2,7 @@
 set(pkgver "9.0.257.17")

 set(ENV{DEPOT_TOOLS_WIN_TOOLCHAIN} 0)
+string(REGEX REPLACE "\\\\+$" "" WindowsSdkDir $ENV{WindowsSdkDir})
+set(ENV{GYP_MSVS_OVERRIDE_PATH} "${WindowsSdkDir}")

 get_filename_component(GIT_PATH ${GIT} DIRECTORY)
 vcpkg_find_acquire_program(PYTHON2)
@@ -22,7 +23,7 @@ if(WIN32)
   vcpkg_add_to_path("${MSYS_ROOT}/usr/bin")
 endif()

-set(VCPKG_KEEP_ENV_VARS PATH;DEPOT_TOOLS_WIN_TOOLCHAIN)
+set(VCPKG_KEEP_ENV_VARS PATH;DEPOT_TOOLS_WIN_TOOLCHAIN;GYP_MSVS_OVERRIDE_PATH)

 function(v8_fetch)
   set(oneValueArgs DESTINATION URL REF SOURCE)
```
but checking that the build is for Windows.

**Comment by odysseus654** [comment] 2021-04-25 20:16
This was whatever was on HEAD yesterday, done after staring at _LoadToolchainEnv in setup_toolchain.py for long enough (_DetectVisualStudioPath appears to be dependent on the "ProgramFiles(x86)" environment variable to find stuff).

${WindowsSdkDir} wouldn't work for me in this case, that's pointing to C:\Program Files (x86)\Windows Kits\10\. It might work to use VSINSTALLDIR though.

**Comment by MonicaLiu0311** [comment] 2023-04-21 08:37
`V8` has been updated to [9.1.269.39#5](https://github.com/microsoft/vcpkg/blob/master/ports/v8/vcpkg.json), I have not reproduced it with `VS 2019`; if it is still an issue, please reopen.

**Closed by MonicaLiu0311** 2023-04-21 08:37 UTC
Labels: category:port-bug
