### ISSUE TITLE
Add ipopt 

### ISSUE THREAD

**Issue by traversaro** [microsoft/vcpkg#233] opened 2016-10-31 23:32 UTC
It would be great to have a port for the ipopt library ( https://projects.coin-or.org/Ipopt ) .
With respect to other ports, this may be particularly tricky as some of ipopt dependencies are Fortran libraries, see http://www.coin-or.org/Ipopt/documentation/node15.html .

**Comment by ras0219-msft** [comment] 2016-11-02 00:53
The prebuilt binaries all link to the VS2010 runtime, so those are unfortunately not really suitable to use.

It looks like they recommend using the free fortran compiler `f2c` on windows at http://www.netlib.org/f2c. The portfile can download this during the build, so that should work.

On the other hand, it looks like their only build system is autoconf based, which is a much more serious blocker. We might be able to use [WSL](https://msdn.microsoft.com/en-us/commandline/wsl/faq#what-is-windows-subsystem-for-linux-wsl) for this, though that would restrict it to Win10+.

More completely, we will most likely need to use MSYS2 to build this. I've opened #241 to track that.

**Comment by tkelman** [comment] 2016-12-06 19:11
Ipopt depends on BLAS, LAPACK (https://github.com/Microsoft/vcpkg/issues/23), and at least one sparse linear solver to be functional. The only redistributable sparse solver that currently works is called MUMPS and it's in Fortran 90 so f2c does not work for it. Need to use either gfortran, or ifort, or one of the other sparse solver options (but those aren't freely downloadable unless you're an academic).

**Comment by traversaro** [comment] 2016-12-07 08:37
At the institution for which I work (https://www.iit.it/) we build binaries of IPOPT with MUMPS for MSVC 10/11/12 and soon 14, using the Intel Fortran compiler. 

Currently we distribute them in an installer [1] with some other dependencies that we use, but I can try to get binaries of MUMPS  suitable to be used in the vcpkg of ipopt.  

[1] : http://wiki.icub.org/wiki/Downloads

**Comment by tkelman** [comment] 2016-12-07 13:48
Is vcpkg intended to be for source builds only? Having non reproducible binary artifact dependencies would be a bit of an issue in that case, wouldn't it? Granted we're building on an OS and with a toolchain that aren't open source, but there's an assumption of easy availability for those components that everything else can be bootstrapped from, right?

**Comment by traversaro** [comment] 2016-12-09 10:13
@tkelman at the moment, several ports just download and extract binaries already available, see for example [tbb](https://github.com/Microsoft/vcpkg/blob/master/ports/tbb/portfile.cmake). 

I think this make sense for ports without dependencies (because for a port with dependencies a change in the dependencies need to trigger a new build) and for project that is not possible to compile otherwise, as in this case.

**Comment by tkelman** [comment] 2016-12-09 11:10
> several ports just download and extract binaries already available

That largely defeats the purpose of having a build-from-source package management system. Homebrew and Nix do a very good job of distinguishing components that are built within the closed system from source in a controlled manner vs components that are used as binaries from elsewhere (casks in homebrew terminology, "impure environments" in nix). If vcpkg is going to require you to read the portfile for everything you install to know whether or not it's doing this, that greatly diminishes its usefulness.

If vcpkg is going to download binaries that were not built by vcpkg, then users have no way of verifying how they were built or reproducing them from a minimal bootstrapped environment (i.e. minimal toolchain install and nothing else) and sources. Isn't that one of the motivating design factors here, "developers need source code"? If that's not a principle that the public port files will follow, then I suspect people are more likely to use a package manager like conda that is designed to primarily download binaries and not require a toolchain for end-user package installation (and happens to have a much better selection of available packages, but that's mostly beside the point here).

**Comment by traversaro** [comment] 2016-12-09 12:16
@tkelman I think you raise some interesting points for the `vcpkg` mantainers, but they are probably not directly related to goal of getting a working `ipopt` port given the current choices in `vcpkg`design. Probably a new issue is a more suitable place for discussing this aspects of `vcpkg`?

**Comment by traversaro** [comment] 2016-12-09 12:57
Thanks a lot for this point, it is definitely interesting.

**Comment by ras0219-msft** [comment] 2016-12-09 20:40
> Is vcpkg intended to be for source builds only?

@tkelman While from-source is definitely preferred when available, having a binary-only package is still better than not having a package at all. For example, I'd happily accept (and prefer!) a rewrite of the `tbb` port that builds from source instead -- however I don't think we should hold the ecosystem hostage to force it.

We also completely recognize that there are many closed-source libraries out there that _are_ successfully solving problems and we do believe in giving developers the option of using them if they believe the trade-offs are worth it.

If you'd like to continue discussing this point in another issue, I'd be happy to do so, especially around auditing! We certainly understand the need to audit your dependencies and if we can do better in this area (explicitly marking binary packages, perhaps?) then we should.

**Comment by traversaro** [comment] 2017-01-03 20:46
I just found (thanks to https://github.com/Microsoft/vcpkg/issues/485#issuecomment-270219347) an alternative CMake-based build system for IPOPT, in which MUMPS is built with `gfortran` and then linked to Visual Studio thanks to the [`GNUtoMS`](https://cmake.org/cmake/help/v3.7/prop_tgt/GNUtoMS.html) CMake property:
https://github.com/ampl/coin/blob/master/Ipopt/CMakeLists.txt

**Comment by traversaro** [comment] 2017-08-18 11:13
Relevant: @albertziegenhagel pushed a port for MUMPS (a key dependency of IPOPT) in his own form of vcpkg, see https://github.com/Microsoft/vcpkg/pull/1098#issuecomment-321012602.   This port requires the amazing Fortran support in vcpkg introduced by : https://github.com/Microsoft/vcpkg/pull/1098 .

**Comment by chrisdembia** [comment] 2018-09-19 01:47
Any progress on this?

**Comment by tkelman** [comment] 2018-09-19 12:20
That would not be suitable, you need a full Bunch-Kaufman indefinite factorization for Ipopt since it's designed to also (locally) solve non-convex problems. So nothing in SuiteSparse will help either. The only open-source solver I'm aware of that would be fully capable but isn't supported by Ipopt yet is https://github.com/ralna/spral, but that also depends on Fortran (it's by the same authors as the various HSL solvers, but newer).

**Comment by traversaro** [comment] 2018-09-19 12:55
Thanks for the info and the links @tkelman .

**Comment by traversaro** [comment] 2020-04-09 16:17
Related issue on Ipopt issue tracker: https://github.com/coin-or/Ipopt/issues/370 .

**Comment by Janos95** [comment] 2020-05-19 14:35
Maybe another way would be to use the pardiso solver which is part of intel mkl? I think there is already a port for mkl.

**Comment by NancyLi1013** [comment] 2020-07-16 02:15
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Comment by eike-fokken** [comment] 2021-08-12 11:41
I guess there are good news on this:

https://github.com/coin-or/Ipopt/pull/446

Apparently spral support has been merged into ipopt and at least on version 3.14, my ipopt configure script knows the option `--with-spral-cflags` and its relatives.

**Comment by Cheney-W** [comment] 2022-11-03 07:26
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Closed by Cheney-W** 2022-11-03 07:26 UTC
Labels: category:new-port, info:good-first-issue

**Comment by zynfly** [comment] 2023-01-09 11:01
It would be great to have a port for the ipopt library. I also encountered the problem of compiling ipopt on Windows.

**Comment by traversaro** [comment] 2023-04-11 14:12
If I am not wrong this was finally fixed in https://github.com/microsoft/vcpkg/pull/29398, thanks to everyone involved!
