### ISSUE TITLE
vcpkg init/install/update commands

### ISSUE THREAD

**Issue by agurodriguez** [microsoft/vcpkg#4632] opened 2018-11-01 16:31 UTC
👋!

Just a question (kind of a feature request also): Is viable and, in such case, there is any plan to include `init`/`install`/`update` commands in `vcpkg` like other package managers?

I know c++ is a complex language and sometimes building a project is a project itself and maybe it's difficult to generalize every use case, but I was thinking that having those commands to bootstrap the project creation could be awesome. 

I imagine something like having a kind of `package.json` file which tracks all the packages installed for the project so my teammates just need to type `vcpkg install` in order to have all the project deps in their computers. Also [this whole process](https://github.com/Microsoft/vcpkg/blob/master/docs/examples/using-sqlite.md#step-2-use) could be reduced to just type `vcpkg init --type [cmake|vs] <project_name>`.

Maybe if it's a dumb idea, I'm just a curious soul in the C++ world so I don't know if what I'm proposing is even a good idea. But I thought "it should be on the table".

Thanks for understanding!

**Comment by agurodriguez** [comment] 2018-11-08 00:47
I think what I'm asking for is very similar to #2420

**Comment by wangli28** [comment] 2019-07-25 08:49
Thanks for posting this issue. Closed as duplicate of #2420.

**Closed by wangli28** 2019-07-25 08:49 UTC
Labels: vcpkg feature
