### ISSUE TITLE
[tiff] build failure

### ISSUE THREAD

**Issue by Tunghohin** [microsoft/vcpkg#38039] opened 2024-04-08 07:57 UTC
### Operating system

Windows11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install qt5-imageformats[tiff]
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    qt5-imageformats[core,tiff,webp]:x64-windows@5.15.13#1
  * tiff[core,jpeg,lzma,zip]:x64-windows@4.6.0#4
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:7890".
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\MSN\AppData\Local\vcpkg\archives in 76.4 us. Use --debug to see more details.
Installing 1/2 tiff[core,jpeg,lzma,zip]:x64-windows@4.6.0#4...
Building tiff[core,jpeg,lzma,zip]:x64-windows@4.6.0#4...
-- Using cached libtiff-libtiff-v4.6.0.tar.gz.
-- Cleaning sources at C:/Users/MSN/vcpkg/buildtrees/tiff/src/v4.6.0-cea7694842.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/MSN/vcpkg/downloads/libtiff-libtiff-v4.6.0.tar.gz
-- Applying patch FindCMath.patch
-- Applying patch requires-lerc.patch
-- Using source at C:/Users/MSN/vcpkg/buildtrees/tiff/src/v4.6.0-cea7694842.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/Users/MSN/vcpkg/buildtrees/tiff/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\Users\MSN\vcpkg\buildtrees\tiff\config-x64-windows-dbg-CMakeCache.txt.log
      C:\Users\MSN\vcpkg\buildtrees\tiff\config-x64-windows-rel-CMakeCache.txt.log
      C:\Users\MSN\vcpkg\buildtrees\tiff\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/tiff/portfile.cmake:33 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)

error: building tiff:x64-windows failed with: BUILD_FAILED
Elapsed time to handle tiff:x64-windows: 7.6 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+tiff
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[tiff]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FMSN%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

According to the backtrace of the cmake log, it was found that the crash occurred in this function(line 38 set_and_check)
![屏幕截图 2024-04-08 145046](https://github.com/microsoft/vcpkg/assets/88049360/a248ee98-ec0f-4738-9668-b66dbfdd7dd3)

The error version log shows that the include dir for WebP is not correct.

Modify line 38, the build error is fixed, the cmake log when the error occurred has been overwritten.

I've modified this
```
set_and_check(WebP_INCLUDE_DIR "${PACKAGE_${CMAKE_FIND_PACKAGE_NAME}_COUNTER_1}/include")
```
to this
```
set_and_check(WebP_INCLUDE_DIR "${PACKAGE_${CMAKE_FIND_PACKAGE_NAME}_COUNTER_1}/${VCPKG_TARGET_TRIPLET}/include")
```

**Comment by Osyotr** [comment] 2024-04-08 08:07
https://github.com/microsoft/vcpkg/issues/37968

**Comment by WangWeiLin-MV** [comment] 2024-04-08 09:07
Duplicate of #37968

**Closed by WangWeiLin-MV** 2024-04-08 09:07 UTC
Labels: category:port-bug
