### ISSUE TITLE
[draco] Build error

### ISSUE THREAD

**Issue by apurvazaveri** [microsoft/vcpkg#29298] opened 2023-01-30 21:16 UTC
Package: draco[core]:x64-osx -> 1.5.3

**Host Environment**

- Host: x64-osx
- Compiler: AppleClang 12.0.5.12050022
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 91dd61bd4 2023-01-27 (3 days ago)

**To Reproduce**

`vcpkg install colmap:x64-osx`

**Failure logs**

```
-- Downloading https://github.com/google/draco/archive/1.5.3.tar.gz -> google-draco-1.5.3.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 1000: popen( curl --fail -L https://github.com/google/draco/archive/1.5.3.tar.gz --create-dirs --output /Users/apzaveri/Documents/my_work/VirtualMakeOver/third_party/colmap/vcpkg/downloads/google-draco-1.5.3.tar.gz.32800.part 2>&1)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after  8262568 us
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/google/draco/archive/1.5.3.tar.gz
File: /Users/apzaveri/Documents/my_work/VirtualMakeOver/third_party/colmap/vcpkg/downloads/google-draco-1.5.3.tar.gz.32800.part
Expected hash: 8575ea78e0d8025facddbd42453b0251387f4e31eb0854135e050fc26aaf0d28ed30ccc3f93578fdc6cdb50369c2ef735291f1f5fb60238b289e0ee019446e1d
Actual hash: c2ee8f4d05d322257c064dcb86f7cbbcf6674c14e6e52a6304860e394ce2f4d82c0fe4a0a638a7edd062e5f2289aa5cf9316242ee54b860bd0fca437e8bfb490
[DEBUG] /Users/runner/work/1/s/src/vcpkg/base/downloads.cpp(956): 
[DEBUG] Time in subprocesses: 8262568 us
[DEBUG] Time in parsing JSON: 8 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 2385 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 8.474 s (8469862 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/draco/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by BillyONeal** [comment] 2023-01-30 21:18
Duplicate of https://github.com/microsoft/vcpkg/issues/29288

**Closed by BillyONeal** 2023-01-30 21:18 UTC
Labels: category:port-bug
