### ISSUE TITLE
boost-exception:arm64-ios build failure

### ISSUE THREAD

**Issue by Stannieman** [microsoft/vcpkg#13688] opened 2020-09-23 15:38 UTC
**Host Environment**
- OS: OSX
- Compiler: Apple Clang 12.0.0

**To Reproduce**
`./vcpkg install boost-exception:arm64-ios`

**Failure logs** 
```
CMake Error at installed/arm64-ios/share/boost-build/boost-modular-build.cmake:47 (message):
  The x86 boost-build tools must be installed to build for non-x86/x64
  platforms.  Please run `vcpkg install boost-build:x86-windows`.
Call Stack (most recent call first):
  ports/boost-exception/portfile.cmake:12 (boost_modular_build)
  scripts/ports.cmake:79 (include)
```

**Additional context**
I found this script (https://github.com/faithfracture/Apple-Boost-BuildScript) to build Boost for iOS and that works like a charm.
It seems to be the only (convenient) way to get Boost working on an iOS device currently.

Now I’m trying to get Boost building for iOS using VCPKG, which is not currently supported.

Based on some previous PR that added s390x support I came up with this:
https://github.com/microsoft/vcpkg/compare/master...Stannieman:master

After these changes the build completes successfully, but when I check the resulting binaries with lipo they are for x86_64 instead of arm64.
Other libraries in VCPKG do build for arm64-ios just fine and boost also builds fine for x64-ios and even x86-ios, so it must be something specific to arm + iOS/OSX that’s missing here.
I also found that ARM64 for OSX doesn’t work either.

Maybe boost-build is not configured properly?
Any idea what could be missing in my PR or point me in the right direction?
I did try to contact the author of the script via email but can't reach him.

Regards
Stan

**Comment by JackBoosY** [comment] 2020-09-24 03:08
This is not usual scenario we're working on now, but we accept PRs for fixing this issue. Sorry for that.

**Comment by Stannieman** [comment] 2020-09-24 06:25
> This is not usual scenario we're working on now, but we accept PRs for fixing this issue. Sorry for that.

Then what is the usual scenario? I kind of need it and this repo and the author of the script are the only starting points I have.
I could maybe get away with the other script but that's not ideal for a CI environment.
Boost is very widely used and OSX is also going to ARM now, so for sure I'm not the only one who would like it working in vcpkg...

**Comment by JackBoosY** [comment] 2020-09-24 07:03
@Stannieman That's unofficial triplet, and I think @alcroito can help you.

**Comment by alcroito** [comment] 2020-09-24 11:43
Boost is built using their own build tool and build system based on b2, and the vcpkg boost port needs to forward the necessary arguments to b2.

Looking at https://github.com/faithfracture/Apple-Boost-BuildScript/blob/master/boost.sh#L603

 we see that the shell script provides the architecture and target-os via a user-config.jam file.

I believe `ports/boost-modular-build-helper/boost-modular-build.cmake` and perhaps `ports/boost-modular-build-helper/user-config.jam` need to be adapted to to pass the relevant os and arch flags, based on values in `VCPKG_CMAKE_SYSTEM_NAME` and `VCPKG_TARGET_ARCHITECTURE`

**Comment by Stannieman** [comment] 2020-09-28 11:50
I will have a look.
This also makes me wonder whether the s390x support that was added actually works, maybe it also just spits out an x86-64 binary.

**Comment by david-antiteum** [comment] 2020-12-11 11:08
Same error for arm64-osx :(

**Comment by Stannieman** [comment] 2020-12-11 11:39
I'm off from work until the end of the year so I can dedicate some time for this. Especially with the new M1 Macs the interest in this will be growing.
Note that I don't normally develop for Apple, so fingers crossed :D

**Comment by david-antiteum** [comment] 2020-12-11 11:56
@Stannieman Happy to help. I have a Mac mini with a M1 with me :)

**Comment by PhoebeHui** [comment] 2021-04-02 03:45
```
 The x86 boost-build tools must be installed to build for non-x86/x64
  platforms.  Please run `vcpkg install boost-build:x86-windows`.
```
This issue should be fixed now, could you please try vcpkg latest source and see if it still be a problem for you?

**Comment by Stannieman** [comment] 2021-04-06 09:46
> ```
>  The x86 boost-build tools must be installed to build for non-x86/x64
>   platforms.  Please run `vcpkg install boost-build:x86-windows`.
> ```
> 
> This issue should be fixed now, could you please try vcpkg latest source and see if it still be a problem for you?

It indeed builds now from a clean checkout so that has been fixed. But it still produces x86-64 binaries when you try to cross compile for ARM64.

**Comment by StefAviator** [comment] 2021-05-26 15:47
I've implemented a fix based on the provided build script. I am setting the appropriate compiler options in user-config.jam and using the second part of the builder in boost-modular-build-helper. The provided command outputs .a boost library files which are 'arm' when checked with lipo.

I would appreciate to get some feedback. Anyone with an M1 to test it is also welcome. PR is here:

https://github.com/microsoft/vcpkg/pull/18124/files

**Comment by StefAviator** [comment] 2021-05-28 08:00
@david-antiteum Can you confirm that the boost components function on your Mac mini with M1 with this fix?

**Comment by Stannieman** [comment] 2021-05-28 08:51
> I did yesterday the compilation using master WITHOUT your fixes (to have a baseline) and it works. b2 is now an arm64 binary as are the libs.

@StefAviator is acutally my collegea and we just confirmed this is not the case.
But you have an M1 and probably it indeed compiles for ARM64 just fine. We are talking about cross compiling from an Intel box.

**Comment by StefAviator** [comment] 2021-05-28 08:58
So compiling on an arm64 system outputs arm64, but compiling on an x86 system for arm64 currently incorrectly outputs x86. The proper test for the fix would be to take code built with the boost libraries on a x86 machine and test it on a laptop with M1.

**Comment by StefAviator** [comment] 2021-05-31 13:37
@david-aimsun could you kindly try out the PR (18124) and confirm if everything is still the same when you compile on your Mac with M1? Thanks.

**Comment by david-antiteum** [comment] 2021-06-24 09:12
All right, my bad. My alter ego says that he was able to compile fine, what is true BUT the generated files were x86_64 and not arm64. So I have applied you patches with this error:

error: toolset gcc initialization:
error: version '12.0.0' requested but 'g++-12.0.0' not found and version '12.0.5' of default 'g++' does not match
error: initialized from /Users/Shared/vcpkg/buildtrees/boost-exception/arm64-osx-rel/user-config.jam:37

**Comment by wintergt** [comment] 2021-07-08 06:01
I will make an update that uses y our system's g++.

**Comment by StefAviator** [comment] 2021-07-19 13:10
This is now fixed by a recent merge [#18529](https://github.com/microsoft/vcpkg/pull/18529). I can confirm arm64-osx/ios builds produce arm64 libraries. 

@david-antiteum Feel free to confirm it works on your system with M1 but I do believe it will.

**Comment by david-antiteum** [comment] 2021-07-19 14:07
@StefAviator Probably. I have found the error on my side. gcc 12.0.5 is the version in macOS Monterey (and 12.0.0 the one used in Big Sur). Not sure why the patch version is important but ... anyway, close the case, my issue is a different one now.

**Comment by StefAviator** [comment] 2021-07-19 14:47
@david-antiteum Yes you have 12.0.5 and it specifies gcc should be 12.0.0, that is why you are getting the error. The fix I was going to do is to set the user-config to 
> gcc: @CMAKE_CXX_COMPILER_VERSION@ : @CMAKE_CXX_COMPILER@
Then it will use whatever version gcc is on your system. However if you use the latest vcpkg (clone again or git pull) then you should not have any more errors and just see it work and produce arm64 libraries since it doesn't use user-config only cmake.

**Comment by david-antiteum** [comment] 2021-07-20 08:21
@StefAviator No need for a user-config.jam file, as you say, installing Vcpkg again solves my problem. Thanks.

**Comment by Stannieman** [comment] 2021-08-02 13:09
Indeed seems to work now, perfect!

**Closed** 2021-08-02 13:10 UTC
Labels: category:community-triplet
