### ISSUE TITLE
Show users current  rate of progress

### ISSUE THREAD

**Issue by MoriartyShan** [microsoft/vcpkg#11062] opened 2020-04-28 01:56 UTC
****
When I installed some 3rd party packages, it is quite normal that long time downloading may happen. And after that, a long time building will happen again. During these kinds of time, vcpkg will show me what it is doing, but will not tell me how long it will takes, such as download speed, how much it left, building speed(something like make in linux), and other things. Thanks

**Comment by LilyWangL** [comment] 2020-04-28 03:11
Thanks for posting this issue. Closed as duplicate of #4879.

**Closed by LilyWangL** 2020-04-28 03:11 UTC
Labels: vcpkg feature
