### ISSUE TITLE
install package suggest

### ISSUE THREAD

**Issue by fawdlstty** [microsoft/vcpkg#4666] opened 2018-11-07 02:24 UTC
run cmd: vcpkg upgrade --no-dry-run
suggest step:
1. backup old version
2. uninstall old version
3. download and install new version
4. if fail, rollback
5. remove backup
6. process other package

now: first uninstall all, and second install all
if offline or install failed, i can't use package

**Comment by wangli28** [comment] 2019-07-25 08:41
Thanks for posting this issue. Closed as duplicate of #4360.

**Closed by wangli28** 2019-07-25 08:41 UTC
Labels: vcpkg feature
