### ISSUE TITLE
[New Port Request] <`Mesa <https://mesa3d.org>`_ - The 3D Graphics Library>

### ISSUE THREAD

**Issue by llduncangithub** [microsoft/vcpkg#13534] opened 2020-09-15 04:17 UTC
Library name:mesa3d

Library description:
The Mesa project began as an open-source implementation of the OpenGL specification - a system for rendering interactive 3D graphics.
Over the years the project has grown to implement more graphics APIs, including OpenGL ES (versions 1, 2, 3), OpenCL, OpenMAX, VDPAU, VA API, XvMC and Vulkan.
A variety of device drivers allows the Mesa libraries to be used in many different environments ranging from software emulation to complete hardware acceleration for modern GPUs.
Mesa ties into several other open-source projects: the Direct Rendering Infrastructure and X.org to provide OpenGL support on Linux, FreeBSD and other operating systems.

Source repository URL:
git clone https://gitlab.freedesktop.org/mesa/mesa.git
git clone https://gitlab.freedesktop.org/mesa/demos.git

Project homepage (if different from the source repository):
https://mesa3d.org

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Neumann-A** [comment] 2020-09-15 18:53
duplicate of #6705

**Closed** 2020-11-17 05:57 UTC
Labels: category:new-port, info:good-first-issue
