### ISSUE TITLE
[GTest] Unexpected behavior when including gtest.lib and gmock.lib

### ISSUE THREAD

**Issue by demconLMA** [microsoft/vcpkg#38315] opened 2024-04-22 08:35 UTC
**Describe the bug**
When using Gtest package you cannot include both, gtest.lib and gmock.lib libraries. Doing so triggers this issue: 
https://github.com/google/googletest/issues/2690 . If only gmock.lib is included, test fails (as expected) but will not be detected in VS test explorer. 

**Environment**
- OS: Windows 
 VS 2022 17.9.6 with vcpkg 2023.11.20 gtest version 1.14.0. 

**To Reproduce**
Include gtest.lib and gmock.lib to the project. Example code: 
```
#include <gtest/gtest.h>
#include <gmock/gmock.h>

class Base
{
public:
    ~Base() = default;

    virtual void tick() = 0;
};

class MockBase : public Base
{
public:
    MOCK_METHOD(void, tick, (), (override));
};

TEST(MockBase, expect_call) 
{
    MockBase mock;
    EXPECT_CALL(mock, tick());
}

TEST(MockBase, strict_expect_call) 
{
    testing::StrictMock<MockBase> mock;
    EXPECT_CALL(mock, tick());
}

int main(int argc, char* argv[])
{
    ::testing::InitGoogleTest(&argc, argv);
    ::testing::InitGoogleMock(&argc, argv);
    return RUN_ALL_TESTS();
}
```
If test is ran from executable or via test explorer, it reports no errors, while in the log it is detected.
```
[----------] 2 tests from MockBase
[ RUN      ] MockBase.expect_call
c:\checkouts\platform\communication\ethercat\ethercattest\tests\testethercatanalogout16s.cpp(21): error: Actual function call count doesn't match EXPECT_CALL(mock, tick())...
         Expected: to be called once
           Actual: never called - unsatisfied and active

[       OK ] MockBase.expect_call (1 ms)
[ RUN      ] MockBase.strict_expect_call
c:\checkouts\platform\communication\ethercat\ethercattest\tests\testethercatanalogout16s.cpp(27): error: Actual function call count doesn't match EXPECT_CALL(mock, tick())...
         Expected: to be called once
           Actual: never called - unsatisfied and active

[       OK ] MockBase.strict_expect_call (0 ms)
[----------] 2 tests from MockBase (3 ms total)
```
**Expected behavior**
Test should fail and be detected in VS test explorer. This issue is not present when including only gmock.lib, but then tests are not detected in the test explorer in VS.

**Comment by Neumann-A** [comment] 2024-04-24 16:31
@Cheney-W Is there a reason you did not close this directly? This seems totally unrelated to vcpkg.

**Comment by Cheney-W** [comment] 2024-04-25 10:40
I didn't close it directly because I wanted to reproduce this issue locally to see if different versions of VS would yield different results.
From the results, it appears that this scenario did not occur.

**Closed by Cheney-W** 2024-04-25 10:40 UTC
Labels: depends:upstream-changes
