### ISSUE TITLE
restclient-cpp can not resolve symbol

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#8300] opened 2019-09-23 07:21 UTC
os  : win10 x64
compliler  : msvc2017
lib : restclient-cpp
error message : can not resolve symbol
error LNK2019: 无法解析的外部符号 "struct RestClient::Response __cdecl RestClient::get(class std::basic_string<char,struct std::char_traits,class std::allocator > const &)" (?get@RestClient@@ya?AUResponse@1@AEBV?$basic_string@DU?$char_traits@D@std@@v?$allocator@D@2@@std@@@z)，该符号在函数 main 中被引用

**Comment by LilyWangL** [comment] 2019-09-25 07:54
Hi @how0723, thanks for posting issue. Can you provide the steps to reproduce this issue?

**Comment by LilyWangL** [comment] 2019-11-27 08:56
Thanks for posting this issue. Closed as duplicate of #8404.

**Closed by LilyWangL** 2019-11-27 08:56 UTC
Labels: Question
