### ISSUE TITLE
[ffmpeg] Build error

### ISSUE THREAD

**Issue by 0x6369616e** [microsoft/vcpkg#32399] opened 2023-07-05 01:48 UTC
Hello Guys, I cant build ffmpeg[all]:x64-windows-static...

This is the generated output:

```
-- Building Release Options: --enable-optimizations
-- Building ffmpeg for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/unknown/Desktop/vcpkg/vcpkg_ffmpeg/vcpkg/downloads/tools/msys2/46e5d880d9d050b3/usr/bin/bash.exe ./build.sh
    Working Directory: C:/Users/unknown/Desktop/vcpkg/vcpkg_ffmpeg/vcpkg/buildtrees/ffmpeg/x64-windows-static-rel
    Error code: 1
    See logs for more information:
      C:\Users\unknown\Desktop\vcpkg\vcpkg_ffmpeg\vcpkg\buildtrees\ffmpeg\build-x64-windows-static-rel-config.log
      C:\Users\unknown\Desktop\vcpkg\vcpkg_ffmpeg\vcpkg\buildtrees\ffmpeg\build-x64-windows-static-rel-out.log

Call Stack (most recent call first):
  ports/ffmpeg/portfile.cmake:596 (vcpkg_execute_required_process)
  scripts/ports.cmake:147 (include)


error: building ffmpeg:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle ffmpeg:x64-windows-static: 2 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
```

###  build-x64-windows-static-rel-config.log

```
    BUILD_ARCH=x86_64
OPTION_VARIABLE=OPTIONS_x86_64
=== CONFIGURING ===
ERROR: libopenmpt >= 0.2.6557 not found using pkg-config

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.libera.chat.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
```

Is there an fix for it? 

Best Regards

**Comment by Adela0814** [comment] 2023-07-05 06:28
Duplicate of https://github.com/microsoft/vcpkg/issues/30030.

**Closed by Adela0814** 2023-07-05 06:28 UTC
