### ISSUE TITLE
WinHttpReceiveResponse() failed: 12002 when installing 7zip

### ISSUE THREAD

**Issue by Yossarius** [microsoft/vcpkg#18872] opened 2021-07-08 22:17 UTC
**Host Environment**
- OS: Windows x64

**To Reproduce**
`./vcpkg install 7zip`

**Failure logs** 
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Error: Failed to download from mirror set:
https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0: WinHttpReceiveResponse() failed: 12002

**Additional context**
I'm asking for this because I'm trying to install other libraries but they all need 7zip
Also, I tried downloading directry from nuget.org, but it didn't work also! maybe that is the issue!

**Comment by JonLiu1993** [comment] 2021-07-09 06:13
Duplicate of #18734

**Closed by JonLiu1993** 2021-07-09 06:13 UTC
Labels: category:question
