### ISSUE TITLE
Error while building Python module using Boost: cannot open file 'python37.lib'

### ISSUE THREAD

**Issue by KestutisMa** [microsoft/vcpkg#10649] opened 2020-04-01 17:46 UTC
**Describe the bug**
While building HelloWorld example from https://github.com/TNG/boost-python-examples using Boost-Python error appears:
`python37.lib` is not found during cmake build:
```[build] LINK : fatal error LNK1104: cannot open file 'python37.lib'```
Although during cmake configure it shows correct file location:
```
[cmake] -- Found PythonLibs: optimized;C:/OpenGL/fentonGjOpenGL/vcpkg/installed/x64-windows/lib/python37.lib;debug;C:/OpenGL/fentonGjOpenGL/vcpkg/installed/x64-windows/debug/lib/python37_d.lib (found suitable version "3.7.3", minimum required is "3") 
[cmake] -- PYTHON_LIBRARIES = optimized;C:/OpenGL/fentonGjOpenGL/vcpkg/installed/x64-windows/lib/python37.lib;debug;C:/OpenGL/fentonGjOpenGL/vcpkg/installed/x64-windows/debug/lib/python37_d.lib
```

**Environment**
- OS: Windows 10
- Compiler: MSVC 19.24.28315.0
- Visual Studio Code with CMake extension (by Microsoft)

**To Reproduce**
1. ./vcpkg install boost-python:x64-windows
2. git clone https://github.com/TNG/boost-python-examples
3. Open that folder with vscode *(I use vscode, but you could use command line cmake)*
4. Create file settings.json in .vscode folder:
```
{
    "cmake.configureSettings": {
    "CMAKE_TOOLCHAIN_FILE": "C:/OpenGL/fentonGjOpenGL/vcpkg/scripts/buildsystems/vcpkg.cmake"
}
}
```
Repro code when building with CMake (press F7 in vscode)

**Expected behavior**
I want to build python module using Boost-Python in C++.
I try to build HelloWorld example from https://github.com/TNG/boost-python-examples.

**Failure logs** 
-CMake configure output
https://pastebin.com/s0QLzpn7
- Build output
https://pastebin.com/9MJdQMxe

**Comment by yurybura** [comment] 2020-04-01 21:08
I think Release configuration should build without error.
Duplicate of #5097.

**Comment by PhoebeHui** [comment] 2020-04-03 07:30
@yurybura, thanks for your comments!

@KestutisMa, could you tri to build with release configuration and see if this issue stil occur?

**Comment by KestutisMa** [comment] 2020-04-07 13:00
Thanks for yours attention. Yes, using release configuration build https://github.com/TNG/boost-python-examples was successful.

**Comment by Hoikas** [comment] 2020-09-04 13:53
Based on the above commentary from OP. it looks like this issue should be closed?

**Comment by FranciscoPombal** [comment] 2020-10-06 18:24
> Based on the above commentary from OP. it looks like this issue should be closed?

No, debug build still fails. I can reproduce this (although some time has passed since the OP, so in my case the error is with Python 3.8: `[build] LINK : fatal error LNK1104: cannot open file 'python38.lib'`).

This is very strange, since `python38.lib` appears nowhere in the problematic `link.exe` command line. I suppose it is a transitive dependency of something.

**Comment by PhoebeHui** [comment] 2021-02-25 08:00
Duplicated to https://github.com/microsoft/vcpkg/issues/5097.

**Closed by PhoebeHui** 2021-02-25 08:00 UTC

**Comment by wenzhi66** [comment] 2023-09-19 02:36
https://blog.csdn.net/weixin_42123332/article/details/124133761
