### ISSUE TITLE
Add Tensorflow & Caffe libraries

### ISSUE THREAD

**Issue by mostafaSataki** [microsoft/vcpkg#4455] opened 2018-10-12 11:29 UTC
Hi.
Please add Tensorflow & Caffe libraries .

**Comment by Neumann-A** [comment] 2018-10-12 11:37
Duplicate of:
Tensorflow: #3048
and
Caffe: #294 (Port in #2848?)
Please search before posting issues and close this one.

**Comment by NancyLi1013** [comment] 2019-05-07 08:06
Hi @mostafaSataki, thanks for posting this issue. Please pay attention to the progress about Tensorfow in #3048 and Caffe in #294.

**Closed by NancyLi1013** 2019-05-07 08:06 UTC
Labels: new port request - consider making a PR!
