### ISSUE TITLE
[python3:x64-linux] build failure

### ISSUE THREAD

**Issue by hcyang99** [microsoft/vcpkg#11751] opened 2020-06-03 17:26 UTC
**Host Environment**
- OS: rhel 8.2
- Compiler: gcc version 8.3.1 20191121 (Red Hat 8.3.1-5)

**To Reproduce**
`./vcpkg install boost`

**Failure logs** 
```
Building package python3[core]:x64-linux...
-- Using cached /home/hcyang/Documents/vcpkg/downloads/python-cpython-v3.7.3.tar.gz
-- Extracting source /home/hcyang/Documents/vcpkg/downloads/python-cpython-v3.7.3.tar.gz
-- Using source at /home/hcyang/Documents/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91
-- Configuring x64-linux-rel
-- Building x64-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: make install -j 5
    Working Directory: /home/hcyang/Documents/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-release
    See logs for more information:
      /home/hcyang/Documents/vcpkg/buildtrees/python3/make-build-x64-linux-release-out.log
      /home/hcyang/Documents/vcpkg/buildtrees/python3/make-build-x64-linux-release-err.log

Call Stack (most recent call first):
  ports/python3/portfile.cmake:144 (vcpkg_execute_build_process)
  scripts/ports.cmake:90 (include)


Error: Building package python3:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: python3:x64-linux
  Vcpkg version: 2020.02.04-unknownhash
```
```
/usr/bin/ld: /home/hcyang/Documents/vcpkg/installed/x64-linux/lib/libffi.a(unix64.S.o): relocation R_X86_64_PC32 against symbol `abort@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: /home/hcyang/Documents/vcpkg/installed/x64-linux/lib/libffi.a(unix64.S.o): relocation R_X86_64_PC32 against symbol `abort@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/home/hcyang/Documents/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-release/Lib/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hcyang/Documents/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-release/Lib/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hcyang/Documents/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-release/Lib/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/home/hcyang/Documents/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-release/Lib/ensurepip/__init__.py", line 204, in _main
    default_pip=args.default_pip,
  File "/home/hcyang/Documents/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-release/Lib/ensurepip/__init__.py", line 117, in _bootstrap
    return _run_pip(args + [p[0] for p in _PROJECTS], additional_paths)
  File "/home/hcyang/Documents/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-release/Lib/ensurepip/__init__.py", line 27, in _run_pip
    import pip._internal
  File "/tmp/tmpk68cjhkh/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/__init__.py", line 40, in <module>
  File "/tmp/tmpk68cjhkh/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/tmp/tmpk68cjhkh/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 12, in <module>
  File "/tmp/tmpk68cjhkh/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/commands/__init__.py", line 6, in <module>
  File "/tmp/tmpk68cjhkh/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/commands/completion.py", line 6, in <module>
  File "/tmp/tmpk68cjhkh/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/base_command.py", line 20, in <module>
  File "/tmp/tmpk68cjhkh/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/download.py", line 37, in <module>
  File "/tmp/tmpk68cjhkh/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/utils/glibc.py", line 3, in <module>
  File "/home/hcyang/Documents/vcpkg/buildtrees/python3/src/v3.7.3-1161ad7a91-x64-linux-release/Lib/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
make: *** [Makefile:1130: install] Error 1
```

**Comment by NancyLi1013** [comment] 2020-06-04 09:00
Hi @hcyang99 
Thanks for posting this issue.
Could you please remove `libffi `and rebuild `python3`?
I cannot reproduce this on my local with gcc 9.2.1 Ubuntu 18.6.

**Comment by hcyang99** [comment] 2020-06-04 12:55
Deleted the whole vcpkg folder, re-cloned and re-built everything and the problem was still there.

**Comment by hcyang99** [comment] 2020-06-04 12:56
@NancyLi1013 Deleted the whole vcpkg folder, re-cloned and re-built everything and the problem was still there.

**Comment by hcyang99** [comment] 2020-06-04 13:18
I think the problem should be in the x86 assembly file "unix64.S" calling abort(). Not sure how to deal with this.

**Comment by hcyang99** [comment] 2020-06-04 13:33
Here is part of the build log of libffi. Maybe there should have been a "-fPIC" flag running this command?

[5/11] /usr/bin/cc -DFFI_BUILDING -Iinclude -I. -I/home/hcyang/Documents/vcpkg/buildtrees/libffi/src/v3.3-2d8a36299e/include -O3 -DNDEBUG -MD -MT CMakeFiles/libffi.dir/src/x86/unix64.S.o -MF CMakeFiles/libffi.dir/src/x86/unix64.S.o.d -o CMakeFiles/libffi.dir/src/x86/unix64.S.o -c /home/hcyang/Documents/vcpkg/buildtrees/libffi/src/v3.3-2d8a36299e/src/x86/unix64.S

**Comment by jsutes** [comment] 2020-06-04 16:38
I'm running into this same issue on CentOS 8 when I tried to install boost.

**Comment by NancyLi1013** [comment] 2020-06-15 09:52
Hi all, 
`python3 `has been updated to 3.8. Could you please try to update vcpkg and rebuild this?

**Comment by jsutes** [comment] 2020-06-15 14:52
@NancyLi1013 Starting with an empty up-to-date vcpkg setup, I can now successfully install boost.

But when I try to update my old vcpkg folder, remove the old half-built boost packages, and rerun `./vcpkg install boost` command, it fails.  I see that it installed the new python 3.8 version, but it now fails when building boost-python.  It might be getting confused with the old python 3.7 files still existing in my vcpkg folder.  I see some references to
`include path: "/home/AzureUser/vcpkg/installed/x64-linux/include/python3.7m;/home/AzureUser/vcpkg/installed/x64-linux/include/python3.8"`
in the `vcpkg/buildtrees/boost-python/install-x64-linux-dbg-out.log` file.

Starting with a fresh vcpkg setup is a good enough solution for me at the moment, but perhaps there's something that could be improved with updating from an old setup.

**Comment by NancyLi1013** [comment] 2020-06-16 02:57
Hi @jsutes and @hcyang99 
Thanks for your update. 
As for the problem caused by update, first, we need to remove all the files generated by the old version. Then try to update and rebuild the new version.

**Comment by jsutes** [comment] 2020-06-16 12:08
@NancyLi1013 Thank you.
I ended up deleting my old vcpkg folder since I was running out of disk space so I can't easily test updating my old setup. But what you describe makes sense. Thanks again.

**Comment by NancyLi1013** [comment] 2020-06-17 02:33
@jsutes 
Thanks for your above info. Personally, this issue should be fixed. I'm closing this issue for now.
Please feel free to reopen this or open a new issue if you still have any problems.

**Closed by NancyLi1013** 2020-06-17 02:33 UTC
Labels: category:port-bug
