### ISSUE TITLE
Update to cmake 3.18.4 broke windows cross-compilation with clang-cl

### ISSUE THREAD

**Issue by Nemirtingas** [microsoft/vcpkg#14705] opened 2020-11-22 13:10 UTC
**Describe the bug**
Since the update to cmake 3.18.4, I can't crosscompile for Windows with clang-cl

**Environment**
- OS: Linux Ubuntu 18.04
- Compiler: llvm + clang-cl 9

**Failure logs** 
```
[16/17] : && CMAKE_AR-NOTFOUND  /machine:X86 /nologo /out:zlib.lib CMakeFiles/zlib.dir/adler32.obj CMakeFiles/zlib.dir/compress.obj CMakeFiles/zlib.dir/crc32.obj CMakeFiles/zlib.dir/deflate.obj CMakeFiles/zlib.dir/gzclose.obj CMakeFiles/zlib.dir/gzlib.obj CMakeFiles/zlib.dir/gzread.obj CMakeFiles/zlib.dir/gzwrite.obj CMakeFiles/zlib.dir/inflate.obj CMakeFiles/zlib.dir/infback.obj CMakeFiles/zlib.dir/inftrees.obj CMakeFiles/zlib.dir/inffast.obj CMakeFiles/zlib.dir/trees.obj CMakeFiles/zlib.dir/uncompr.obj CMakeFiles/zlib.dir/zutil.obj  && :
FAILED: zlib.lib 
: && CMAKE_AR-NOTFOUND  /machine:X86 /nologo /out:zlib.lib CMakeFiles/zlib.dir/adler32.obj CMakeFiles/zlib.dir/compress.obj CMakeFiles/zlib.dir/crc32.obj CMakeFiles/zlib.dir/deflate.obj CMakeFiles/zlib.dir/gzclose.obj CMakeFiles/zlib.dir/gzlib.obj CMakeFiles/zlib.dir/gzread.obj CMakeFiles/zlib.dir/gzwrite.obj CMakeFiles/zlib.dir/inflate.obj CMakeFiles/zlib.dir/infback.obj CMakeFiles/zlib.dir/inftrees.obj CMakeFiles/zlib.dir/inffast.obj CMakeFiles/zlib.dir/trees.obj CMakeFiles/zlib.dir/uncompr.obj CMakeFiles/zlib.dir/zutil.obj  && :
/bin/sh: 1: CMAKE_AR-NOTFOUND: not found
ninja: build stopped: subcommand failed.
```

Using CMake version 3.17.2 works fine:
```
[16/17] : && /usr/bin/lld-link-9 /lib  /machine:X86 /nologo /out:zlib.lib CMakeFiles/zlib.dir/adler32.obj CMakeFiles/zlib.dir/compress.obj CMakeFiles/zlib.dir/crc32.obj CMakeFiles/zlib.dir/deflate.obj CMakeFiles/zlib.dir/gzclose.obj CMakeFiles/zlib.dir/gzlib.obj CMakeFiles/zlib.dir/gzread.obj CMakeFiles/zlib.dir/gzwrite.obj CMakeFiles/zlib.dir/inflate.obj CMakeFiles/zlib.dir/infback.obj CMakeFiles/zlib.dir/inftrees.obj CMakeFiles/zlib.dir/inffast.obj CMakeFiles/zlib.dir/trees.obj CMakeFiles/zlib.dir/uncompr.obj CMakeFiles/zlib.dir/zutil.obj  && :
[16/17] cd /vcpkg/buildtrees/zlib/x86-windows-nemirtingas-rel && /vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake -P cmake_install.cmake
```

**Comment by JackBoosY** [comment] 2020-11-23 05:59
Does the cmake 3.19.0 fixed this issue?

Seems related to https://github.com/Kitware/CMake/commit/08460462006d3d3a050317476fff4c8961da01c5

**Comment by JackBoosY** [comment] 2020-11-23 06:09
Can you use https://github.com/microsoft/vcpkg/pull/14716 changes and try again?

Thanks.

**Comment by Nemirtingas** [comment] 2020-11-23 08:58
Hi, I'll try asap

**Comment by Nemirtingas** [comment] 2020-11-26 17:09
Hmm, still not working with cmake 3.19.1...
```
[2/5] : && CMAKE_AR-NOTFOUND  /machine:X86 /nologo /out:lib/libglew32.lib CMakeFiles/glew_s.dir/vcpkg/buildtrees/glew/src/glew-0d6dec840c.clean/src/glew.c.obj  && :
FAILED: lib/libglew32.lib 
: && CMAKE_AR-NOTFOUND  /machine:X86 /nologo /out:lib/libglew32.lib CMakeFiles/glew_s.dir/vcpkg/buildtrees/glew/src/glew-0d6dec840c.clean/src/glew.c.obj  && :
/bin/sh: 1: CMAKE_AR-NOTFOUND: not found
```

**Comment by JackBoosY** [comment] 2020-11-27 07:16
I can confirm this is a upstream bug, see https://gitlab.kitware.com/cmake/cmake/-/issues/16410

**Comment by Nemirtingas** [comment] 2020-11-27 07:21
Hi, are you sure ? This issue has been opened 4years ago, my issue is only since the new version. I've sent a comment to the cmake discourse about this, I hope they find the commit that broke it. Till then I've forked vcpkg and reversed the cmake update 😢

**Comment by JackBoosY** [comment] 2020-11-27 07:49
I didn't notice the time...
I think it is. And it can only be resolved by the upstream.

**Comment by Nemirtingas** [comment] 2020-12-03 23:32
Fixed by changing the CMake toolchain file. I've set explicitly CMAKE_AR to llvm-lib-9. They seem to have changed the linker behavior.

**Comment by JackBoosY** [comment] 2020-12-04 02:26
Please wait for cmake solve this issue and #14176 merged.

**Comment by mathstuf** [comment] 2020-12-04 23:42
I think there was something related to clang-cl and linker stuff lately. @bradking?

**Comment by bradking** [comment] 2020-12-07 14:21
The problem is discussed in [CMake Issue 21532](https://gitlab.kitware.com/cmake/cmake/-/issues/21532).  With MSVC-ABI tools, CMake used to use `link /lib ...` to create static libraries.  Now it uses just `lib` ... because the old option was undocumented.  This means `CMAKE_AR` is now needed where as previously `CMAKE_LINKER` was enough.  For toolchain files that relied on explicitly setting the binutils variables, and that set `CMAKE_LINKER` but not `CMAKE_AR`, it now fails.  Setting `CMAKE_AR` is the correct solution.

**Comment by JackBoosY** [comment] 2020-12-08 02:40
> Setting `CMAKE_AR` is the correct solution.

Will this issue be solved by cmake or should it be solved by vcpkg?

**Comment by bradking** [comment] 2020-12-08 13:07
It should be solved by vcpkg.  CMake correctly searches for `CMAKE_AR` when needed, but if the tool is named `llvm-lib-9` instead of `llvm-lib` then it won't be found.  This should have been true for `CMAKE_LINKER` as well, so something must already be setting that to `lld-link-9`.  Wherever that is done should also set `CMAKE_AR` to `llvm-lib-9`.

**Comment by Nemirtingas** [comment] 2020-12-08 13:25
I don't quite understand, the issue was CMAKE_AR not being defined, so I've defined it in the cross-compiler toolchain file: https://github.com/Nemirtingas/clang-msvc-sdk/commit/caa217f357e29efdab25cb64e7b76f299ff0b80a

That was the issue right ? Neither CMake or vcpkg is currently broken ?

**Comment by bradking** [comment] 2020-12-08 13:35
If vcpkg is using `clang-msvc-sdk`, then the fix to the latter should resolve this.

**Comment by JackBoosY** [comment] 2020-12-09 07:05
`clang-msvc-sdk` isn't provided by Visual Studio. @BillyONeal can you double confirm this?

**Comment by Nemirtingas** [comment] 2020-12-09 07:54
As far as I know, clang-msvc-sdk is a fork of https://github.com/llvm-mirror/llvm/blob/master/cmake/platforms/WinMsvc.cmake to allow Windows MSVC based apps cross-compilation using cmake.

Thats why I closed this issue in the first place, its not a bug in CMake nor vcpkg. Its just that recent versions of CMake changed the linker detection behavior.

**Comment by bradking** [comment] 2020-12-09 12:02
This was fixed in LLVM's `WinMsvc.cmake` in llvm/llvm-project@ee7ee71f40e904a8380d6439ac4741304b4a2dfd.  See its commit message for details.

**Comment by JackBoosY** [comment] 2020-12-10 02:01
Fine, I'm closing this issuse now.

**Closed by JackBoosY** 2020-12-10 02:01 UTC
Labels: category:tool-update
