### ISSUE TITLE
[ffmpeg] not supprt video4linux2 device

### ISSUE THREAD

**Issue by Smalldy** [microsoft/vcpkg#34696] opened 2023-10-24 10:18 UTC
**Describe the bug**
1. add ffmpeg with feature ffmpeg(build ffmpeg execute), and build ,
```
    "name" : "ffmpeg",
    "version>=" : "6.0#1",
    "features": [
      "nvcodec",
      "x264",
      "x265",
      "gpl",
      "nonfree"
    ]
   ```
2. add a usb camera to yout pc 

THEN 

- `./ffmpeg -y -t 5 -f video4linux2  -i /dev/video0  out.mov`  ---> i got `unknown input format: 'video4linux2'`
- function `av_input_video_device_next()`   can not get my usb camera device 
- ./ffmpeg -devices can not found my usb camera

**Environment**
- OS: ubuntu20.04
- IDE: clion  g++ cmake  unix makefile

what should I do? Am I miss some feature?

**Comment by Smalldy** [comment] 2023-10-24 10:53
I found    the option `--enable-libv4l2         enable libv4l2/v4l-utils [no]`  in `<ffmpeg_source>/configure --help` command

**Comment by Smalldy** [comment] 2023-10-24 11:47
I have made some efforts.
First, I went to vcpkg's build tree directory, and then executed this:
```
 ./configure  --prefix=/home/ldh/workspace/vcpkg/packages/ffmpeg_x64-linux --enable-pic --disable-doc --enable-debug --enable-runtime-cpudetect --disable-autodetect --target-os=linux --enable-pthreads --cc=cc --cxx=c++ --nm=nm --ar=ar --ranlib=ranlib --enable-nonfree --enable-gpl --enable-ffmpeg --disable-ffplay --disable-ffprobe --enable-avcodec --enable-avdevice --enable-avformat --enable-avfilter --disable-postproc --enable-swresample --enable-swscale --disable-alsa --disable-amf --disable-libaom --disable-libass --disable-avisynth --disable-bzlib --disable-libdav1d --disable-libfdk-aac --disable-libfontconfig --disable-libfreetype --disable-libfribidi --disable-iconv --disable-libilbc --disable-lzma --disable-libmp3lame --disable-libmodplug --enable-cuda --enable-nvenc --enable-nvdec --enable-cuvid --enable-ffnvcodec --disable-opencl --disable-opengl --disable-libopenh264 --disable-libopenjpeg --disable-libopenmpt --disable-openssl --disable-libopus --disable-sdl2 --disable-libsnappy --disable-libsoxr --disable-libspeex --disable-libssh --disable-libtensorflow --disable-libtesseract --disable-libtheora --disable-libvorbis --disable-libvpx --disable-libwebp --enable-libx264 --enable-libx265 --disable-libxml2 --disable-zlib --disable-libsrt --disable-libmfx --enable-cross-compile --pkg-config-flags=--static --enable-optimizations --arch=x86_64 --enable-asm --enable-x86asm --enable-libv4l2
```

But I got the error string: `ERROR: libv4l2 not found using pkg-config

`

**Comment by dg0yt** [comment] 2023-10-24 17:12
There is no port for video4linux in vcpkg. You might add v4l development packages via your system package manager, and you might add the flag via a custom port overlay or via custom triplet file.

**Comment by Smalldy** [comment] 2023-10-25 07:01
> There is no port for video4linux in vcpkg. You might add v4l development packages via your system package manager, and you might add the flag via a custom port overlay or via custom triplet file.vcpkg 中没有 video4linux 的端口。您可以通过系统包管理器添加 v4l 开发包，也可以通过自定义端口覆盖或自定义三元组文件添加标志。

After `sudo apt-get install libv4l-dev` , I got `WARNING: Disabled v4l2_indev because not any dependency is satisfied: linux_videodev2_h sys_videoio_h`  in  `<vcpkg>/buildtrees/ffmpeg/build-x64-linux-rel-config.log` .

Not work.

**Comment by Smalldy** [comment] 2023-10-25 07:02
Log is too long, if there is any requirement for it, I'll post it

**Comment by Smalldy** [comment] 2023-10-25 10:21
**There is no need to add any feature.**


reason is ffmpeg configure can not found the header file videoio.h  

Just ` sudo ln -s /usr/include/linux/videodev2.h /usr/include/sys/videoio.h` , and everything will be ok.

before that, make sure you can find /usr/include/linux/videodev2.h , it's from libv4l2, usually already installed in your ubuntu20.

@dg0yt  @MonicaLiu0311  this issue can be closed

**Comment by vipcxj** [comment] 2024-10-29 08:30
@MonicaLiu0311 I don't think this counts as a solution. It's just a temporary workaround. i'm having the same problem, and i don't have videoio.h on my machine, but i do have videodev2.h. If I hadn't searched for this issue, people wouldn't even know what's wrong. The best solution would be for the port to detect this and make ffmpeg use videodev2.h instead of videoio.h. If that doesn't work, at least the port should hint at this workaround!

**Comment by Smalldy** [comment] 2024-10-29 09:44
you are right, this is not the missing of  "feature", It's reallay a problem for the pkg's user. 
I would like to reopen this issue, if you want to post more infomation for it, But I don't have permission to open it again :(

**Comment by vipcxj** [comment] 2024-10-29 10:29
@Smalldy Hi I copied the port as overlay to enable me to modify him, I tried adding --enable-indev=v4l2 but it didn't work. It compiles fine but still can't find v4l2, how did you fix it? Do I need to add enable-v4l2? The documentation says this option is for v4l2-utils
Also I looked at the source code and ffmpeg automatically uses videodev2.h if it doesn't find videoio.h so I don't understand how the soft linking works

**Comment by vipcxj** [comment] 2024-10-29 11:21
@MonicaLiu0311  I foud "check_headers linux/videodev2.h" is never executed, so ffmpeg configure never find videodev2.h, then it disable the indev-v4l2. however it check header sys/video.io.h, so the workaround take effect.
After that, I compared the configure file again and again, and found that the configure of "branch release/6.1" doesn't match the one downloaded by vcpkg, whose ffmpeg version is 6.1.1, which use source " tag n6.1.1", this version of the configure missed "check_headers linux/videodev2.h". Then I investigated further and found that only the latest "tag n7.1" version fixes this problem. I'll try again to verify my guess. If it's correct, then you can close this issue, because the latest ffmpeg in vcpkg is 7.1.

**Comment by vipcxj** [comment] 2024-10-29 11:32
@MonicaLiu0311 The latest ffmpeg in vcpkg use source “n7.0.2”, not "n7.1", so it is not fixed at this moment.

**Comment by Smalldy** [comment] 2024-10-30 04:15
Greate research !

**Comment by dg0yt** [comment] 2024-10-30 07:21
When commenting on a issue which was opened and closed a while ago, always check the current version of vcpkg first. 

`ffmpeg` is a difficult port. Not using regular vcpkg maintainer functions. Not using regular autotools. Many dependencies. There were significant improvements in the past months.

> Log is too long, if there is any requirement for it, I'll post it

Appending logs encourages informed feedback. Looking at logs can be done on any device, at any time, but trying to reproduce a problem needs rare resources.

**Comment by vipcxj** [comment] 2024-10-30 09:08
@dg0yt I've locally updated the ffmpeg overlay port to 7.1 and confirmed that it solves the issue. i was going to post a pr but realized you already did. 
By the way, ffmpeg has a ton of patches, is it a chooice to merge them? Because the patches are so fragmented, I'm manually updating them one by one, and it toke me much time. If it was synthesized into one big patch, maybe I could just use git to do the update all at once.

**Closed** 2024-11-21 10:06 UTC
Labels: category:question
