### ISSUE TITLE
building qtwebengine:x64-windows failed

### ISSUE THREAD

**Issue by mazalet** [microsoft/vcpkg#38278] opened 2024-04-19 22:56 UTC
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/15046126/install-x64-windows-dbg-out.log)

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vcpkg/issues/36321
```

**Comment by JonLiu1993** [comment] 2024-04-22 08:38
Duplicate of https://github.com/microsoft/vcpkg/issues/34971.

**Closed by JonLiu1993** 2024-04-22 08:38 UTC
