### ISSUE TITLE
Building package boost-system:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by artin-phares** [Microsoft/vcpkg#6249] opened 2019-04-28 12:39 UTC
... while installing cpprestsdk:x64-windows

<details>
<summary>log</summary>

```
./build/vcpkg/vcpkg.exe install cpprestsdk:x64-windows
The following packages will be built and installed:
  * boost-algorithm[core]:x64-windows
  * boost-array[core]:x64-windows
  * boost-asio[core]:x64-windows
  * boost-assert[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-bind[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-compatibility[core]:x64-windows
  * boost-concept-check[core]:x64-windows
  * boost-config[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-container-hash[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-conversion[core]:x64-windows
  * boost-core[core]:x64-windows
  * boost-coroutine[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-detail[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-function[core]:x64-windows
  * boost-function-types[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-fusion[core]:x64-windows
  * boost-integer[core]:x64-windows
  * boost-intrusive[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iterator[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-modular-build-helper[core]:x64-windows
  * boost-move[core]:x64-windows
  * boost-mpl[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-optional[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-predef[core]:x64-windows
  * boost-preprocessor[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-smart-ptr[core]:x64-windows
  * boost-static-assert[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-throw-exception[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tuple[core]:x64-windows
  * boost-type-index[core]:x64-windows
  * boost-type-traits[core]:x64-windows
  * boost-typeof[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-utility[core]:x64-windows
  * boost-vcpkg-helpers[core]:x64-windows
  * boost-winapi[core]:x64-windows
  * brotli[core]:x64-windows
    cpprestsdk[brotli,core,default-features,websockets]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * websocketpp[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/63: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 13.88 s
Starting package 2/63: brotli:x64-windows
Building package brotli[core]:x64-windows...
-- Downloading https://github.com/google/brotli/archive/v1.0.2.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/google-brotli-v1.0.2.tar.gz
-- Applying patch install.patch
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/brotli/src/v1.0.2-052e040e54
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/brotli_x64-windows/share/brotli/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package brotli[core]:x64-windows... done
Installing package brotli[core]:x64-windows...
Installing package brotli[core]:x64-windows... done
Elapsed time for package brotli:x64-windows: 36.14 s
Starting package 3/63: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
-- Downloading https://www.openssl.org/source/openssl-1.0.2q.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/openssl-1.0.2q.tar.gz
-- Applying patch ConfigureIncludeQuotesFix.patch
-- Applying patch STRINGIFYPatch.patch
-- Applying patch EnableWinARM32.patch
-- Applying patch EmbedSymbolsInStaticLibsZ7.patch
-- Applying patch EnableWinARM64.patch
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14/win32/nasm-2.14-win32.zip...
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip...
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/openssl-windows_x64-windows/share/openssl-windows/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x64-windows... done
Installing package openssl-windows[core]:x64-windows...
Installing package openssl-windows[core]:x64-windows... done
Elapsed time for package openssl-windows:x64-windows: 5.382 min
Starting package 4/63: openssl:x64-windows
Building package openssl[core]:x64-windows...
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/openssl_x64-windows/share/openssl//usage
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl[core]:x64-windows... done
Installing package openssl[core]:x64-windows...
Installing package openssl[core]:x64-windows... done
Elapsed time for package openssl:x64-windows: 1.443 s
Starting package 5/63: boost-modular-build-helper:x64-windows
Building package boost-modular-build-helper[core]:x64-windows...
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-modular-build-helper[core]:x64-windows... done
Installing package boost-modular-build-helper[core]:x64-windows...
Installing package boost-modular-build-helper[core]:x64-windows... done
Elapsed time for package boost-modular-build-helper:x64-windows: 1.246 s
Starting package 6/63: boost-vcpkg-helpers:x64-windows
Building package boost-vcpkg-helpers[core]:x64-windows...
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-vcpkg-helpers[core]:x64-windows... done
Installing package boost-vcpkg-helpers[core]:x64-windows...
Installing package boost-vcpkg-helpers[core]:x64-windows... done
Elapsed time for package boost-vcpkg-helpers:x64-windows: 1.204 s
Starting package 7/63: boost-compatibility:x64-windows
Building package boost-compatibility[core]:x64-windows...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-compatibility-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-compatibility/src/ost-1.69.0-b809a8cf93
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.65.1/LICENSE_1_0.txt...
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-compatibility_x64-windows/share/boost-compatibility/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-compatibility[core]:x64-windows... done
Installing package boost-compatibility[core]:x64-windows...
Installing package boost-compatibility[core]:x64-windows... done
Elapsed time for package boost-compatibility:x64-windows: 2.977 s
Starting package 8/63: boost-config:x64-windows
Building package boost-config[core]:x64-windows...
-- Downloading https://github.com/boostorg/config/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-config-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-config/src/ost-1.69.0-89bfb246de
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-config_x64-windows/share/boost-config/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-config[core]:x64-windows... done
Installing package boost-config[core]:x64-windows...
Installing package boost-config[core]:x64-windows... done
Elapsed time for package boost-config:x64-windows: 4.207 s
Starting package 9/63: boost-assert:x64-windows
Building package boost-assert[core]:x64-windows...
-- Downloading https://github.com/boostorg/assert/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-assert-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-assert/src/ost-1.69.0-08c52545eb
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-assert_x64-windows/share/boost-assert/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-assert[core]:x64-windows... done
Installing package boost-assert[core]:x64-windows...
Installing package boost-assert[core]:x64-windows... done
Elapsed time for package boost-assert:x64-windows: 2.839 s
Starting package 10/63: boost-predef:x64-windows
Building package boost-predef[core]:x64-windows...
-- Downloading https://github.com/boostorg/predef/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-predef-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-predef/src/ost-1.69.0-8f2cd404c9
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-predef_x64-windows/share/boost-predef/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-predef[core]:x64-windows... done
Installing package boost-predef[core]:x64-windows...
Installing package boost-predef[core]:x64-windows... done
Elapsed time for package boost-predef:x64-windows: 4.213 s
Starting package 11/63: boost-winapi:x64-windows
Building package boost-winapi[core]:x64-windows...
-- Downloading https://github.com/boostorg/winapi/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-winapi-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-winapi/src/ost-1.69.0-6c1d425716
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-winapi_x64-windows/share/boost-winapi/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-winapi[core]:x64-windows... done
Installing package boost-winapi[core]:x64-windows...
Installing package boost-winapi[core]:x64-windows... done
Elapsed time for package boost-winapi:x64-windows: 4.13 s
Starting package 12/63: boost-preprocessor:x64-windows
Building package boost-preprocessor[core]:x64-windows...
-- Downloading https://github.com/boostorg/preprocessor/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-preprocessor-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-preprocessor/src/ost-1.69.0-bcf23f78cc
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-preprocessor_x64-windows/share/boost-preprocessor/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-preprocessor[core]:x64-windows... done
Installing package boost-preprocessor[core]:x64-windows...
Installing package boost-preprocessor[core]:x64-windows... done
Elapsed time for package boost-preprocessor:x64-windows: 7.118 s
Starting package 13/63: boost-detail:x64-windows
Building package boost-detail[core]:x64-windows...
-- Downloading https://github.com/boostorg/detail/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-detail-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-detail/src/ost-1.69.0-d5ef7077df
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-detail_x64-windows/share/boost-detail/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-detail[core]:x64-windows... done
Installing package boost-detail[core]:x64-windows...
Installing package boost-detail[core]:x64-windows... done
Elapsed time for package boost-detail:x64-windows: 2.928 s
Starting package 14/63: boost-throw-exception:x64-windows
Building package boost-throw-exception[core]:x64-windows...
-- Downloading https://github.com/boostorg/throw_exception/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-throw_exception-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-throw-exception/src/ost-1.69.0-a86b5dd870
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-throw-exception_x64-windows/share/boost-throw-exception/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-throw-exception[core]:x64-windows... done
Installing package boost-throw-exception[core]:x64-windows...
Installing package boost-throw-exception[core]:x64-windows... done
Elapsed time for package boost-throw-exception:x64-windows: 2.487 s
Starting package 15/63: boost-build:x64-windows
Building package boost-build[core]:x64-windows...
-- Downloading https://github.com/boostorg/build/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-build-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-build/src/ost-1.69.0-1d1e4d577d
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.69.0/boostcpp.jam...
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-build_x64-windows/share/boost-build/copyright
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-build_x64-windows/tools/boost-build/boostcpp.jam
-- Bootstrapping...
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-build[core]:x64-windows... done
Installing package boost-build[core]:x64-windows...
Installing package boost-build[core]:x64-windows... done
Elapsed time for package boost-build:x64-windows: 43.53 s
Starting package 16/63: boost-core:x64-windows
Building package boost-core[core]:x64-windows...
-- Downloading https://github.com/boostorg/core/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-core-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-core/src/ost-1.69.0-af8c37b85e
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-core_x64-windows/share/boost-core/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-core[core]:x64-windows... done
Installing package boost-core[core]:x64-windows...
Installing package boost-core[core]:x64-windows... done
Elapsed time for package boost-core:x64-windows: 3.368 s
Starting package 17/63: boost-static-assert:x64-windows
Building package boost-static-assert[core]:x64-windows...
-- Downloading https://github.com/boostorg/static_assert/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-static_assert-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-static-assert/src/ost-1.69.0-ed1accba2d
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-static-assert_x64-windows/share/boost-static-assert/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-static-assert[core]:x64-windows... done
Installing package boost-static-assert[core]:x64-windows...
Installing package boost-static-assert[core]:x64-windows... done
Elapsed time for package boost-static-assert:x64-windows: 2.826 s
Starting package 18/63: boost-integer:x64-windows
Building package boost-integer[core]:x64-windows...
-- Downloading https://github.com/boostorg/integer/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-integer-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-integer/src/ost-1.69.0-0016500641
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/packages/boost-integer_x64-windows/share/boost-integer/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-integer[core]:x64-windows... done
Installing package boost-integer[core]:x64-windows...
Installing package boost-integer[core]:x64-windows... done
Elapsed time for package boost-integer:x64-windows: 3.098 s
Starting package 19/63: boost-system:x64-windows
Building package boost-system[core]:x64-windows...
-- Downloading https://github.com/boostorg/system/archive/boost-1.69.0.tar.gz...
-- Extracting source D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/downloads/boostorg-system-boost-1.69.0.tar.gz
-- Using source at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-system/src/ost-1.69.0-9d1d01900c
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/tools/boost-build/b2.exe;--stagedir=D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-system/x64-windows-rel/stage;--build-dir=D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-system/x64-windows-rel;--user-config=D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-system/x64-windows-rel/user-config.jam;-j4;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/include";-sBZIP2_INCLUDE="D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=64;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/lib";variant=release;debug-symbols=on
    Working Directory: D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-system/src/ost-1.69.0-9d1d01900c/build
    Error code: 1
    See logs for more information:
      D:\Projects\_tmp\docker\vcpkg-example\build\vcpkg\buildtrees\boost-system\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:270 (vcpkg_execute_required_process)
  ports/boost-system/portfile.cmake:14 (boost_modular_build)
  scripts/ports.cmake:71 (include)


Error: Building package boost-system:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-system:x64-windows
  Vcpkg version: 2018.11.23-nohash
```

</details>

**Comment by wangli28** [comment] 2019-04-29 03:08
Hi @artin-phares, thank you for posting the issue, can you provide the build log?
`D:\Projects\_tmp\docker\vcpkg-example\build\vcpkg\buildtrees\boost-system\build-x64-windows-rel-out.log`

I installed it successfully with VS2017 15.9.11 and VCPKG latest source.

> PS F:\b\vcpkg> .\vcpkg.exe install cpprestsdk:x64-windows
The following packages will be built and installed:
\  * boost-algorithm[core]:x64-windows
\  * boost-array[core]:x64-windows
\  * boost-asio[core]:x64-windows
\  * boost-assert[core]:x64-windows
\  * boost-atomic[core]:x64-windows
\  * boost-bind[core]:x64-windows
\  * boost-build[core]:x64-windows
\  * boost-chrono[core]:x64-windows
\  * boost-concept-check[core]:x64-windows
\  * boost-container[core]:x64-windows
\  * boost-container-hash[core]:x64-windows
\  * boost-context[core]:x64-windows
\  * boost-conversion[core]:x64-windows
\  * boost-core[core]:x64-windows
\  * boost-coroutine[core]:x64-windows
\  * boost-date-time[core]:x64-windows
\  * boost-exception[core]:x64-windows
\  * boost-function[core]:x64-windows
\  * boost-function-types[core]:x64-windows
\  * boost-functional[core]:x64-windows
\  * boost-fusion[core]:x64-windows
\  * boost-integer[core]:x64-windows
\  * boost-intrusive[core]:x64-windows
\  * boost-io[core]:x64-windows
\  * boost-iterator[core]:x64-windows
\  * boost-lambda[core]:x64-windows
\  * boost-lexical-cast[core]:x64-windows
\  * boost-math[core]:x64-windows
\  * boost-modular-build-helper[core]:x64-windows
\  * boost-move[core]:x64-windows
\  * boost-mpl[core]:x64-windows
\  * boost-numeric-conversion[core]:x64-windows
\  * boost-optional[core]:x64-windows
\  * boost-pool[core]:x64-windows
\  * boost-predef[core]:x64-windows
\  * boost-range[core]:x64-windows
\  * boost-ratio[core]:x64-windows
\  * boost-rational[core]:x64-windows
\  * boost-regex[core]:x64-windows
\  * boost-smart-ptr[core]:x64-windows
\  * boost-static-assert[core]:x64-windows
\  * boost-system[core]:x64-windows
\  * boost-thread[core]:x64-windows
\  * boost-throw-exception[core]:x64-windows
\  * boost-tokenizer[core]:x64-windows
\  * boost-tuple[core]:x64-windows
\  * boost-type-index[core]:x64-windows
\  * boost-type-traits[core]:x64-windows
\  * boost-typeof[core]:x64-windows
\  * boost-unordered[core]:x64-windows
\  * boost-utility[core]:x64-windows
\  * boost-winapi[core]:x64-windows
\  * brotli[core]:x64-windows
\    cpprestsdk[brotli,core,default-features,websockets]:x64-windows
\  * openssl[core]:x64-windows
\  * openssl-windows[core]:x64-windows
\  * websocketpp[core]:x64-windows
\  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/58: zlib:x64-windows
Building package zlib[core]:x64-windows..
......
Starting package 14/58: boost-system:x64-windows
Building package boost-system[core]:x64-windows...
-- Downloading https://github.com/boostorg/system/archive/boost-1.69.0.tar.gz...
-- Extracting source F:/b/vcpkg/downloads/boostorg-system-boost-1.69.0.tar.gz
-- Using source at F:/b/vcpkg/buildtrees/boost-system/src/ost-1.69.0-9d1d01900c
-- Building x64-windows-rel
-- Building x64-windows-rel done
-- Building x64-windows-dbg
-- Building x64-windows-dbg done
-- Packaging x64-windows-rel
-- Packaging x64-windows-rel done
-- Packaging x64-windows-dbg
-- Packaging x64-windows-dbg done
-- Packaging headers
-- Packaging headers done
-- Using cached F:/b/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: F:/b/vcpkg/packages/boost-system_x64-windows/share/boost-system/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-system[core]:x64-windows... done
Installing package boost-system[core]:x64-windows...
Installing package boost-system[core]:x64-windows... done
Elapsed time for package boost-system:x64-windows: 5.555 s
......
Building package cpprestsdk[brotli,core,default-features,websockets]:x64-windows... done
Installing package cpprestsdk[brotli,core,default-features,websockets]:x64-windows...
Installing package cpprestsdk[brotli,core,default-features,websockets]:x64-windows... done
Elapsed time for package cpprestsdk:x64-windows: 1.394 min
\
Total elapsed time: 10.84 min
\
The package cpprestsdk:x64-windows provides CMake targets:
\
    find_package(cpprestsdk CONFIG REQUIRED)
    # Note: 1 target(s) were omitted.
    target_link_libraries(main PRIVATE cpprestsdk::cpprest cpprestsdk::cpprestsdk_zlib_internal cpprestsdk::cpprestsdk_boost_internal cpprestsdk::cpprestsdk_openssl_internal)

**Comment by artin-phares** [comment] 2019-04-29 05:16
Sure,

<details>
<summary>build-x64-windows-rel-out.log</summary>

```
notice: found boost-build.jam at D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/tools/boost-build/boost-build.jam
notice: loading Boost.Build from D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/tools/boost-build/src/kernel
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    D:\Projects\_tmp\docker\vcpkg-example\build\vcpkg\buildtrees\boost-system\x64-windows-rel\user-config.jam
notice: Searching 'D:\Projects\_tmp\docker\vcpkg-example\build\vcpkg\buildtrees\boost-system\x64-windows-rel' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/buildtrees/boost-system/x64-windows-rel'.

warning: Did not find command for MSVC toolset. If you have Visual Studio 2017 installed you will need to specify the full path to the command, set VS150COMNTOOLS for your installation, or build from the 'Visual Studio Command Prompt for VS 2017'.

notice: will use 'cl.exe' for msvc, condition <toolset>msvc
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>', setup: 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>32', setup: 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>32', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>', setup: 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>32', setup: 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>32', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>64', setup: 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>64', setup: 'amd64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>64', setup: 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>64', setup: 'amd64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>', setup: 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>', setup: 'x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>64', setup: 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>64', setup: 'x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'x86_arm'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'D:/Projects/_tmp/docker/vcpkg-example/build/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'x86_arm'
notice: [cmdline-cfg] toolset msvc-14.1 not previously configured; attempting to auto-configure now
error: msvc initialization: parameter 'version' inconsistent
error: no value was specified in earlier initialization
error: an explicit value is specified now


```

</details>

**Comment by artin-phares** [comment] 2019-04-29 05:30
I've fresh reinstalled vcpkg right now, ` .\vcpkg.exe install cpprestsdk:x64-windows`, and see same error.

**Comment by wangli28** [comment] 2019-04-29 08:27
Duplicate of #5976, so close it.

**Closed by wangli28** 2019-04-29 08:27 UTC
Labels: needs-repro
