### ISSUE TITLE
[OpenCV] update to 4.8.0

### ISSUE THREAD

**Issue by Chenyang-Sun** [microsoft/vcpkg#32864] opened 2023-08-01 05:28 UTC
### Library name

OpenCV

### New version number

4.8.0

### Other information that may be useful (release notes, etc...)

https://github.com/opencv/opencv.git
https://opencv.org/

**Comment by Cheney-W** [comment] 2023-08-01 05:49
Duplicate of https://github.com/microsoft/vcpkg/issues/32463

**Closed** 2023-08-01 06:46 UTC
Labels: category:port-update
