### ISSUE TITLE
[vtk:x64-windows] build failure

### ISSUE THREAD

**Issue by lidar-nevermore** [microsoft/vcpkg#8287] opened 2019-09-22 08:40 UTC
**Host Environment**
- OS: [Win10, 1903]
- Compiler: MSVC 2015

**To Reproduce**
./vcpkg install vtk:x64-windows

**Failure logs** 
The following packages will be built and installed:
    vtk[core]:x64-windows
Starting package 1/1: vtk:x64-windows
Building package vtk[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/Kitware-VTK-v8.2.0.tar.gz
-- Using source at C:/vcpkg/buildtrees/vtk/src/v8.2.0-b37306c27c
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v

    Working Directory: C:/vcpkg/buildtrees/vtk/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\vtk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/vtk/portfile.cmake:134 (vcpkg_install_cmake)
  scripts/ports.cmake:85 (include)

Error: Building package vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 2019.08.27-nohash

**Additional context**
In  install-x64-windows-dbg-out.log:
C:\vcpkg\buildtrees\vtk\x64-windows-dbg\ThirdParty\glew\vtk_glew.h(40): fatal error C1083: Cannot open include file: 'GL/glew.h': No such file or directory

I checked the log and found that the error was caused by lacking of  include file 'GL/glew.h'.
I tried to run ‘./vcpkg install opengl:x64-windows’, but still couldn't get through it.

[vtk_x64-windows.zip](https://github.com/microsoft/vcpkg/files/3639514/vtk_x64-windows.zip)
[vcpkg.zip](https://github.com/microsoft/vcpkg/files/3639519/vcpkg.zip)
[vcpkg-master.zip](https://github.com/microsoft/vcpkg/files/3639521/vcpkg-master.zip)

**Comment by Neumann-A** [comment] 2019-09-22 15:18
> Vcpkg version: 2019.08.27-nohash

update VCPKG. This was fixed in #7967 and is due to a CMake regression

**Comment by lidar-nevermore** [comment] 2019-09-22 16:29
> > Vcpkg version: 2019.08.27-nohash
> 
> update VCPKG. This was fixed in #7967 and is due to a CMake regression

It works. Many thanks!

**Closed** 2019-09-22 16:32 UTC
Labels: port bug
