### ISSUE TITLE
Launching powershell failed or was denied when trying to fetch cmake

### ISSUE THREAD

**Issue by frederich** [Microsoft/vcpkg#1921] opened 2017-10-04 06:44 UTC
```
No suitable version of cmake was found (requires 3.8.0 or higher). Download portable version?
[Y] Yes  [N] No  [A] Always Allow Downloads  [?] Hilfe (Standard ist "Y"):
Launching powershell failed or was denied
```

**Comment by alexkaratarakis** [comment] 2017-10-04 20:11
I think we have had this issue in the past but it has been fixed.
Judging from the version of required cmake (`3.8.0`) you are using an older version of `vcpkg`. Please do:
```
git pull
.\bootstrap-vcpkg.bat
```

Then try again and report the result.

**Comment by frederich** [comment] 2017-10-05 06:27
Hello @alexkaratarakis, no I had used the latest HEAD revsion vcpkg version.

**Comment by frederich** [comment] 2017-10-05 07:38
```
F:\Dev\vcpkg>.\vcpkg install zlib
The following packages will be built and installed:
    zlib:x86-windows-static
Starting package 1/1: zlib:x86-windows-static
Building package zlib:x86-windows-static...
A suitable version of cmake was not found (required v3.9.3). Downloading portable cmake v3.9.3...
Launching powershell failed or was denied when trying to fetch cmake version 3.9.3.
(No sufficient installed version was found)
```

**Comment by alexkaratarakis** [comment] 2017-11-06 02:53
@frederich 
I believe the root cause was found and fixed: #2127. Please try again with the latest master.

**Comment by NancyLi1013** [comment] 2019-02-19 07:37
Hi @frederich , could you please help confirm whether this issue exists on your machine now?
If fixed, please close it.
Thanks.

**Comment by NancyLi1013** [comment] 2019-03-27 08:58
Please open a new issue if this is still a problem for you.

**Closed by NancyLi1013** 2019-03-27 08:58 UTC
Labels: needs-repro
