### ISSUE TITLE
[wil] Installing wil is incredibly slow

### ISSUE THREAD

**Issue by UMU618** [microsoft/vcpkg#42682] opened 2024-12-13 06:25 UTC
### Is your feature request related to a problem? Please describe.

```
-- Using cached Microsoft-wil-v1.0.240803.1.tar.gz.
-- Cleaning sources at D:/d/vcpkg/buildtrees/wil/src/0.240803.1-02f2b37103.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/d/vcpkg/downloads/Microsoft-wil-v1.0.240803.1.tar.gz
-- Using source at D:/d/vcpkg/buildtrees/wil/src/0.240803.1-02f2b37103.clean
-- Found external ninja('1.12.1').
-- Configuring x64-windows
```

Stuck for over half an hour...

### Proposed solution

None

**Comment by UMU618** [comment] 2024-12-13 08:17
repro this issue on 2 machines.
Deleting `%VCPKG_ROOT%\buildtrees\wil` can solve.

**Comment by jimwang118** [comment] 2024-12-13 08:22
Ok, the issue is solved, I will close this issue.

**Closed by jimwang118** 2024-12-13 08:22 UTC
Labels: category:question
