### ISSUE TITLE
[ffmpeg] build fails: https://www.nasm.us down 

### ISSUE THREAD

**Issue by daschuer** [microsoft/vcpkg#32741] opened 2023-07-25 05:30 UTC
**Describe the bug**
Building of ffmpeg fails, because downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip fails.

**Environment**
- OS: Windows, GiHub workflow runner

**To Reproduce**
1. ./vcpkg install ffmpeg 
2. See error
```
Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
error: https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip: WinHttpSendRequest failed with exit code 12002
```
Full log: https://github.com/daschuer/vcpkg/actions/runs/5650189952/job/15306093276

**Comment by MonicaLiu0311** [comment] 2023-07-25 06:04
Duplicate of https://github.com/microsoft/vcpkg/issues/32600.

The upstream nasm webpage cannot be accessed, waiting for the upstream website to recover. You can get [the cache file here](https://github.com/microsoft/vcpkg/issues/32600#issuecomment-1638907069) and put it in the `[VCPKG_ROOT]/downloads` directory to temporarily solve the problem.

**Comment by BillyONeal** [comment] 2023-07-25 19:21
Closed as duplicate and reopened the other one since it is down again

**Closed by BillyONeal** 2023-07-25 19:21 UTC
Labels: depends:upstream-changes
