### ISSUE TITLE
Support multiple versions of a same package

### ISSUE THREAD

**Issue by Firefly35** [microsoft/vcpkg#4275] opened 2018-09-13 09:25 UTC
For now, vcpkg doesn't seem to support several versions for a same package. 
In day to day work a developer often has to deal with several projects, each of these depending on several packages that can be used by another project with another version.
For instance, project A depends on opencv 3.1 while project B depends on opencv 3.2, and the A project is on the release path and can't spend time to migrate towards the new version.
In this context, we expect to have some kind of packages/x64_os/opencv/version structure to maintain several versions of the package.
It requires vcpkg to provide an additionnal version option upon install ...

**Comment by LilyWangL** [comment] 2019-12-11 09:50
Thanks for posting this issue. Closed as duplicate of #2823.

**Closed by LilyWangL** 2019-12-11 09:50 UTC
Labels: vcpkg feature
