### ISSUE TITLE
[libssh] Wrong LIBSSH_LIBRARY variable on Linux

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#7784] opened 2019-08-20 14:37 UTC
**Describe the bug**
libssh 0.7.6 wrong LIBSSH_LIBRARY variable on Linux

**Environment**
- OS: Linux
- Compiler: gcc 7.4

**To Reproduce**
1. Use Linux. No error on Windows MSVC
1. `./vcpkg install libssh`
2. Create a simple CMake project with 
```
find_package(libssh)
target_link_libraries(main PRIVATE ${LIBSSH_LIBRARIES})
target_include_directories(main PRIVATE ${LIBSSH_INCLUDE_DIRS})
```

**Expected behavior**
Link successfully with `LIBSSH_LIBRARIES` = `libssh.a` (static) or `libssh.so` (dynamic)

**Failure logs** 
undefined reference to `ssh_new`
because `LIBSSH_LIBRARIES` is `ssh.lib` (static or dynamic)

**Additional context**
Bug only affect Linux/Mac. Windows MSVC is fine.
`ports/libssh/fix-config-cmake.patch` has changes for MSVC, but not working on Linux.
Also, `ports/libssh/portfile.cmake` has a part `if(VCPKG_LIBRARY_LINKAGE STREQUAL "static")` to handle static library
The patched file is in `installed/x64-linux/share/libssh/libssh-config.cmake` that always contains `ssh.lib` so it does not work on Linux

**Comment by shuitianxu** [comment] 2019-08-23 08:11
@linquize Thanks for reporting this issue.
My Steps to reproduce the behavior:
1.Use Linux and Windows MSVC
2./vcpkg install libssh
3.Create CMakeLists.txt as follows:

cmake_minimum_required(VERSION 3.10.2)
project(main LANGUAGES C)
add_library(main darray.c)
target_include_directories(main PRIVATE ${LIBSSH_INCLUDE_DIRS})

4.Create empty file darray.c
5.Put CMakeLists.txt and darray.c to same folder
6.Enter the folder in Powershell or bash 
7.Excute cmake .

The CMake project run success. I cannot repro this issue now.

**Comment by linquize** [comment] 2019-08-23 13:42
You need to call at least one function from libssh, such as `ssh_new()` in `main()`.

**Comment by linquize** [comment] 2019-08-29 15:45
You need to call at least one function from `libssh`, such as `ssh_new()` in `main()`.

**Comment by NancyLi1013** [comment] 2020-01-02 02:33
Hi @linquize 
Someone has submitted a PR #4983 to update this port to the latest version 0.9.3.
Could you please try to take a look and help confirm if this can work for you?

**Comment by linquize** [comment] 2020-01-02 09:32
I tried #4983.
With libssh 0.9.3, I need to change my sample `CMakeLists.txt` to
```
find_package(libssh CONFIG REQUIRED)
target_link_libraries(main PRIVATE ssh)
```
Then the linker succeeded on Linux.

**Comment by NancyLi1013** [comment] 2020-01-03 01:38
Thanks for your testing and instant reply.
Since this version has supported `find_package() `via `CONFIG `mode.
Let's wait for the PR to be merged.

**Comment by NancyLi1013** [comment] 2020-02-06 03:57
Hi @linquize sorry for waiting for so long time.
The PR has been merged.
Please try to update vcpkg and rebuild this port.

**Closed by NancyLi1013** 2020-02-06 03:57 UTC
Labels: port bug

**Comment by linquize** [comment] 2020-02-07 10:40
Tried libssh 0.9.3 on Windows and Linux

DllMain: ssh_init failed

**Comment by NancyLi1013** [comment] 2020-02-08 05:02
@linquize thanks for your feedback.
If there is something wrong different from that before, please open a new issue.

Thanks.

**Comment by linquize** [comment] 2020-02-11 12:23
New issue #10012
