### ISSUE TITLE
[CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134] build failure

### ISSUE THREAD

**Issue by camjrwalker** [microsoft/vcpkg#31165] opened 2023-04-28 11:48 UTC
### Operating system

Windows 10 Pro 22H2 OS Build 19045.2846

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
PS C:\src\vcpkg> .\vcpkg.exe install boost:x64-windows boost:x86-windows
```

### Failure logs

Installing 134/317 boost-units:x64-windows...
Elapsed time to handle boost-units:x64-windows: 1.6 s
Installing 135/317 boost-odeint:x64-windows...
Elapsed time to handle boost-odeint:x64-windows: 1.9 s
Installing 136/317 boost-outcome:x64-windows...
Elapsed time to handle boost-outcome:x64-windows: 959 ms
Installing 137/317 expat:x64-windows...
Elapsed time to handle expat:x64-windows: 60.6 ms
Installing 138/317 libffi:x64-windows...
Elapsed time to handle libffi:x64-windows: 52.9 ms
Installing 139/317 openssl:x64-windows...
Building openssl[core]:x64-windows...
-- Downloading https://github.com/openssl/openssl/archive/openssl-3.1.0.tar.gz -> openssl-openssl-openssl-3.1.0.tar.gz...
-- Extracting source C:/src/vcpkg/downloads/openssl-openssl-openssl-3.1.0.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at C:/src/vcpkg/buildtrees/openssl/src/nssl-3.1.0-1ebd9e680e.clean
-- Downloading https://www.nasm.us/pub/nasm/releasebuilds/2.16.01/win64/nasm-2.16.01-win64.zip -> nasm-2.16.01-win64.zip...
-- Downloading https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip -> strawberry-perl-5.32.1.1-32bit.zip...
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Downloading https://download.qt.io/official_releases/jom/jom_1_1_3.zip;https://mirrors.ocf.berkeley.edu/qt/official_releases/jom/jom_1_1_3.zip -> jom_1_1_3.zip...
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Prerunning x64-windows-rel
-- Building x64-windows-rel
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON install_runtime install_ssldirs
    Working Directory: C:/src/vcpkg/buildtrees/openssl/x64-windows-rel
    See logs for more information:
      C:\src\vcpkg\buildtrees\openssl\install-x64-windows-rel-nmake-out.log
      C:\src\vcpkg\buildtrees\openssl\install-x64-windows-rel-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:50 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:68 (include)
  scripts/ports.cmake:147 (include)

error: building openssl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error&body=Copy+issue+body+from+C%3A%2Fsrc%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
[install-x64-windows-rel-nmake-err.log](https://github.com/microsoft/vcpkg/files/11353131/install-x64-windows-rel-nmake-err.log)
[install-x64-windows-rel-nmake-out.log](https://github.com/microsoft/vcpkg/files/11353132/install-x64-windows-rel-nmake-out.log)

### Additional context

Tried a few things to resolve the issue:

    1) Ensured that I was using the latest version of vcpkg by running the following command in the terminal: vcpkg update.

    2) Checked if there are any known issues with building OpenSSL using vcpkg by visiting the link provided in the error message. I couldn't see any?

    3) Checked if any prerequisites missing on my system. None found.

**Comment by dg0yt** [comment] 2023-04-28 19:38
Duplicate of #30645.

**Closed** 2023-05-04 02:48 UTC
Labels: category:port-bug
