### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by CatalinSerafimescu** [microsoft/vcpkg#32025] opened 2023-06-15 10:31 UTC
Package: openssl:x64-windows -> 3.1.1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32532.0
-    vcpkg-tool version: 2023-06-08-19a3cb921a585fce63c0651f56a991a5a08bdc60
    vcpkg-scripts version: dc6188d0e 2023-06-14 (7 hours ago)

**To Reproduce**

`vcpkg install openssl`

**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.1.1.tar.gz.
-- Cleaning sources at C:/Work/vcpkg/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Work/vcpkg/downloads/openssl-openssl-openssl-3.1.1.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at C:/Work/vcpkg/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: C:/Work/vcpkg/buildtrees/openssl/x64-windows-dbg
    See logs for more information:
      C:\Work\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log
      C:\Work\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:50 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:68 (include)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\Work\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log</summary>

```
	"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\nmake.exe" /LU                 depend
	"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs
	"C:\Work\vcpkg\downloads\tools\nasm\nasm-2.16.01\nasm.exe"  -Ox -f win64 -DNEAR -g -o crypto\bn\libcrypto-shlib-rsaz-x86_64.obj "crypto\bn\rsaz-x86_64.asm"
```
</details>
<details><summary>C:\Work\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log</summary>

```
crypto\bn\rsaz-x86_64.asm:1: error: parser: instruction expected
crypto\bn\rsaz-x86_64.asm:6: error: parser: instruction expected
crypto\bn\rsaz-x86_64.asm:9: error: parser: instruction expected
crypto\bn\rsaz-x86_64.asm:10: warning: `PTR' is not a NASM keyword [-w+ptr]
crypto\bn\rsaz-x86_64.asm:11: warning: `PTR' is not a NASM keyword [-w+ptr]

.....

crypto\bn\rsaz-x86_64.asm:2266: error: parser: instruction expected
crypto\bn\rsaz-x86_64.asm:2267: warning: label alone on a line without a colon might be in error [-w+label-orphan]
NMAKE : fatal error U1077: '"C:\Work\vcpkg\downloads\tools\nasm\nasm-2.16.01\nasm.exe"  -Ox -f win64 -DNEAR -g -o crypto\bn\libcrypto-shlib-rsaz-x86_64.obj "crypto\bn\rsaz-x86_64.asm"' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs' : return code '0x2'
Stop.
```
</details>

**Comment by CatalinSerafimescu** [comment] 2023-06-15 10:32
I already tried suggestions from other threads, no luck

**Comment by Adela0814** [comment] 2023-06-15 11:02
Duplicate of https://github.com/microsoft/vcpkg/issues/30645.

**Closed by Adela0814** 2023-06-15 11:02 UTC
