### ISSUE TITLE
[<openimageio>] build failure

### ISSUE THREAD

**Issue by Hurleyworks** [microsoft/vcpkg#8585] opened 2019-10-14 01:23 UTC
**Host Environment**
- OS: [Windows.]
- Compiler: MVSC Community 2019  version 16.3.3

**To Reproduce**
`./vcpkg install openimageio::x64-windows-static

**Failure logs** 
cl : Command line warning D9025 : overriding '/W3' with '/W1'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1766): error C2027: use of undefined type 'OpenImageIO_v2_1::ImageBufImpl'
D:\ActiveWorks\Code\Opensource\build_util\vcpkg\buildtrees\openimageio\src\1f1a9e36cd-9b16117fec\src\include\OpenImageIO/imagebuf.h(49): note: see declaration of 'OpenImageIO_v2_1::ImageBufImpl'
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1765): note: while compiling class template member function 'void std::default_delete<_Ty>::operator ()(_Ty *) noexcept const'
        with
        [
            _Ty=OpenImageIO_v2_1::ImageBufImpl
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1875): note: see reference to function template instantiation 'void std::default_delete<_Ty>::operator ()(_Ty *) noexcept const' being compiled
        with
        [
            _Ty=OpenImageIO_v2_1::ImageBufImpl
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1804): note: see reference to class template instantiation 'std::default_delete<_Ty>' being compiled
        with
        [
            _Ty=OpenImageIO_v2_1::ImageBufImpl
        ]
D:\ActiveWorks\Code\Opensource\build_util\vcpkg\buildtrees\openimageio\src\1f1a9e36cd-9b16117fec\src\include\OpenImageIO/imagebuf.h(1399): note: see reference to class template instantiation 'std::unique_ptr<OpenImageIO_v2_1::ImageBufImpl,std::default_delete<_Ty>>' being compiled
        with
        [
            _Ty=OpenImageIO_v2_1::ImageBufImpl
        ]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1766): error C2338: can't delete an incomplete type
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.23.28105\include\memory(1767): warning C4150: deletion of pointer to incomplete type 'OpenImageIO_v2_1::ImageBufImpl'; no destructor called
D:\ActiveWorks\Code\Opensource\build_util\vcpkg\buildtrees\openimageio\src\1f1a9e36cd-9b16117fec\src\include\OpenImageIO/imagebuf.h(49): note: see declaration of 'OpenImageIO_v2_1::ImageBufImpl'

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangL** [comment] 2019-10-14 01:49
Thanks for posting this issue. Closed as duplicate of #8344. Please pay attention to the progress of issue  #8344.

**Closed by LilyWangL** 2019-10-14 01:49 UTC
Labels: port bug
