### ISSUE TITLE
[brotli] build failure

### ISSUE THREAD

**Issue by mattdurak** [microsoft/vcpkg#29290] opened 2023-01-30 20:23 UTC
Package: brotli[core]:x64-windows-static-bs -> 1.0.9#4

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31937.0
-    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: f14984af3 2023-01-09 (3 weeks ago)

**To Reproduce**

`vcpkg install cpprestsdk`

**Failure logs**

```
-- Downloading https://github.com/google/brotli/archive/e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz -> google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/google/brotli/archive/e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/google/brotli/archive/e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz
File: C:\src\els\deps\vcpkg\downloads\google-brotli-e61745a6b7add50d380cfd7d3883dd6c62fc2c71.tar.gz.140260.part
Expected hash: 303444695600b70ce59708e06bf21647d9b8dd33d772c53bbe49320f2f8f95ca8a7d6df2d29b7f36ff99001967e2d28380e0e305d778031940a3a5c6585f9a4f
Actual hash: 3ee43e88ad53ee4bcaeed8dd09b183c42c65f057f8604f7e51a216612d6c0b7df9462d4706b5de7419c61f5d91ade3626c9cfdbd770370991b13044eea0f16ec
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956): 
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 1030 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 571.1 ms (560265 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/brotli/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)



```

**Additional context**

Happens when installing cpprestsdk from the latest vcpkg tag (`git checkout 2023.01.09`). Problem seems to be that a bunch of the downloads that happen fail with hash mis-matches. This is after cleaning my local vcpkg director (`git clean -xdff`).

Triplet x64-windows-static-bs is:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_PLATFORM_TOOLSET v143)
```

**Comment by mattdurak** [comment] 2023-01-30 20:33
Well I guess #29288 is tracking the same thing and has more comments...

**Comment by BillyONeal** [comment] 2023-01-30 20:55
Dupe of https://github.com/microsoft/vcpkg/issues/29288

**Closed by BillyONeal** 2023-01-30 20:55 UTC
Labels: category:port-bug
