### ISSUE TITLE
Question on Eigen3 include base directory

### ISSUE THREAD

**Issue by Fleischner** [microsoft/vcpkg#1284] opened 2017-06-14 22:48 UTC
The eigen3 port copies its header files to .\Eigen\eigen3 subdirectory. 
However one of my external libraries expects the headers in .\eigen3 subdirectory.
I think also the find eigen3 cmake script adds an include path with the .\Eigen\ directory in the path.
And #include <eigen3\eigen> feels more clean.

**Comment by ras0219-msft** [comment] 2017-06-15 05:23
In my current enlistment, I have:
```
>vcpkg list eigen
eigen3:x64-windows          3.3.3-2          C++ template library for linear algebra: matrices...
> vcpkg owns eigen3/Eigen/Core
eigen3:x64-windows: x64-windows/include/eigen3/Eigen/Core
```

which means that currently `#include <eigen3/Eigen/Core>` should work.

I think I may have misunderstood your comment -- are you suggesting it should be moved to some other directory?

**Comment by codicodi** [comment] 2017-06-15 09:10
AFAIK the recommended way is to [#include <Eigen/Core>](https://github.com/RLovelett/eigen/blob/a46d2e7337c4656f00abe54a8115f6d76153a048/demos/mix_eigen_and_c/binary_library.cpp#L15)

**Comment by Fleischner** [comment] 2017-06-15 10:00
Sorry I mixed up the names:

Just checked with the newest version. Currently the eigen3 port generates the following two directories under the include base directory:
.\eigen3\Eigen\
.\eigen3\unsupported

When using vcpkg integrate command, as codicodi mentioned, I had source files that expect to find the Eigen headers in the directory:
.\Eigen\
But this also means the Eigen port will create an .\unsupported folder in the base include folder.

**Comment by Fleischner** [comment] 2017-06-15 10:37
At the moment there is only one port that uses eigen3 dependency. That is ceres. In one file Ceres also includes with #include <Eigen\Dense>

As far as I understand there is currently an inconsistency that is not checked:
- During port build include files are found with cmake scripts using additional include directories
- After vcpkg integrate all include files are expected to be found from the base include directory

What about a very easy consistency checker for the installed ports:
Run over all installed header files and check that all #includes work by checking that the included files can be either found from the base include directory or from the directory of the current include file. This should be quite easy to accomplish.
Even better to also check that there are not 2 header files with the same name and very similar contents in two different folders. That marks a hidden dependency. Eg: opencv2\flann folder or vtk\vtkglew folders. I don’t expect types from this internal dependencies to cross library boundaries. But how knows. This is a source for horrible errors…

Hopefully all this vanishes with the upcoming module system.

**Comment by Voskrese** [comment] 2017-06-15 23:24
Failed to find Eigen - Could not find file:

third_party\ceres-solver\build>cmake .. -DCMAKE_TOOLCHAIN_FILE="E:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_PREFIX_PATH="E:/tools/vcpkg/installed/x86-windows" -DCMAKE_INSTALL_PREFIX="E:/tools/vcpkg/packages/ceres_x86-windows"
_________
ceres-solver\build>cmake .. -DCMAKE_TOOLCHAIN_FILE="E:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_PREFIX_PATH="E:/tools/vcpkg/installed/x86-windows" -DCMAKE_INSTALL_PREFIX="E:/tools/vcpkg/packages/ceres_x86-windows" **-DEIGEN_INCLUDE_DIR="E:/tools/vcpkg/installed/x86-windows/include/eigen3"**

```
-- Found Eigen: E:/tools/vcpkg/installed/x86-windows/include/eigen3 (found version "3.2.4")
-- Found Eigen version 3.2.4: E:/tools/vcpkg/installed/x86-windows/include/eigen3
```

**Comment by traversaro** [comment] 2017-06-16 08:16
The `FindEigen.cmake` shipped with Ceres 1.12.0 does not search for the `Eigen3Config.cmake` file installed by the vcpkg `eigen3` port. This has been fixed in this commit: https://github.com/ceres-solver/ceres-solver/commit/ec5bd23237ccde9e4fef5bca769da5cc81d7ba52 . The next version of ceres should work fine without any modification to the vcpkg toolchain file.

**Comment by jasjuang** [comment] 2017-06-16 20:15
@traversaro I actually tried `vcpkg install ceres --head` but I am getting a build fail. Were you able to install the latest ceres successfully?

``````
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Release;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/m
    Working Directory: C:/dev/vcpkg/buildtrees/ceres/x64-windows-rel
    See logs for more information:
      C:\dev\vcpkg\buildtrees\ceres\package-x64-windows-rel-out.log
      C:\dev\vcpkg\buildtrees\ceres\package-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:49 (vcpkg_execute_required_process)
  ports/ceres/portfile.cmake:57 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package ceres:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: ceres:x64-windows
  Vcpkg version: 0.0.81-c5ac9898999b712b7bac2fbc497825882d5e9011

Additionally, attach any relevant sections from the log files above.
``````

**Comment by jasjuang** [comment] 2017-07-05 16:50
@Fleischner  I finally resolved the ceres compilation issue for head after working with the ceres maintainer and the next problem I encountered immediately is this Eigen base folder problem. As you mentioned in Ceres when they include Eigen it is included like `#include <Eigen\Dense>` instead of `#include <eigen3\Eigen\Dense>`. Do you think we can simply alter the installation of Eigen by simply removed the unsupported folder (not gonna be used anyways...) and move the Eigen folder inside eigen3 up a level?

.\eigen3\Eigen
.\eigen3\unsupported

becomes

.\Eigen

With that being said CeresConfig.cmake does not pick up the variable EIGEN_INCLUDE_DIR for some reason despite it being specified in line 42 of https://github.com/Microsoft/vcpkg/blob/master/ports/ceres/portfile.cmake . I added a line `message("Eigen include directory is ` ${EIGEN_INCLUDE_DIR})` in CeresConfig.cmake and when I run cmake it shows nothing.

**Comment by traversaro** [comment] 2017-07-05 17:03
@jasjuang I fail to see the role of `CeresConfig.cmake` file. That file should be **generated** by Ceres and then executed by any third party library calling `find_package(Ceres)`, so I don't understand why it should be executed when configuring the ceres port.

**Comment by jasjuang** [comment] 2017-07-05 18:01
@traversaro I am exactly trying to solve the cmake error problem when using ceres in my own project. If I build Ceres, Eigen, Glog, GFlags from source `find_package(Ceres)` works without a problem, but if I install Ceres, Eigen, Glog, GFlags by vcpkg `find_package(Ceres)` will show a Eigen not found problem because of this base folder issue. 

I am confused why `${EIGEN_INCLUDE_DIR}` is specified during ceres installation but it's not saved into CeresConfig.cmake for future use (referring to `find_package(Ceres)`) after it finished installing.

**Comment by traversaro** [comment] 2017-07-06 07:46
@jasjuang Ok. So ceres itself is compiling fine, while your downstream project is not? 
This is strange, because both should use the same logic contained in the `FindEigen.cmake`, as the `CeresConfig.cmake` is not saving the `EIGEN_INCLUDE_DIR` passed at Ceres configure time, as this would render the ceres installation not relocatable. 

Are you compiling your downstream project using the vcpkg toolchain or some otherway (i.e. `CMAKE_PREFIX_PATH`) to make sure that the Eigen3 cmake package is correctly found. Just to check, can you check that `find_package(Eigen3)` works fine in your project?

**Comment by KindDragon** [comment] 2017-07-06 14:35
BTW Ceres should be fixed in PR #1390

**Comment by traversaro** [comment] 2017-07-06 14:59
Yes, indeed https://github.com/Microsoft/vcpkg/pull/1390/commits/11a98b78e07fd5b5bcef8cce3d1258ebdd6858d4#diff-fb6fec59a13ccffba5ec0e80174503e8L66 was clearly a problem for any downstream project using ceres , as `find_package(Eigen)` (rather than `find_package(Eigen3)`) was used in `CeresConfig.cmake`.

**Comment by KindDragon** [comment] 2017-07-06 17:16
JFYI Ceres FindEigen.cmake call inside `find_package(Eigen3 NO_MODULE)`

**Comment by jasjuang** [comment] 2017-07-06 20:16
@KindDragon I checked the ceres part in PR #1390 and yes if you keep the `FindEigen.cmake` that comes with Ceres then it could potentially solve it (will test further tonight), but weren't you worried that this `FindEigen.cmake` can affect other packages that use Eigen as mentioned in #1250?

@traversaro Yes ceres itself is compiling fine, while my downstream project is not.

**Comment by KindDragon** [comment] 2017-07-06 20:32
@jasjuang If I understand correct, it only affects libraries that use `find_package(Eigen)`, but everyone who uses `find_package(Eigen)` already should have it own FindEigen.cmake. So probably they should be fine

**Comment by jasjuang** [comment] 2017-07-06 20:53
@KindDragon Yes but that's precisely where the problem is. Whoever that is still using `find_package(Eigen)` instead of `find_package(Eigen3)` are using the old eigen that doesn't have cmake config files, which means they will have their own FindEigen.cmake to use `find_package(Eigen)` in module mode. If we keep the FindEigen.cmake from ceres, that means there will be two FindEigen.cmake attempting to use `find_package(Eigen)` in module mode. Which file gets the priority?

On a second thought, I don't think we need to worry about this because people should be using the newer eigen anyways...

**Comment by patrikhuber** [comment] 2018-03-27 15:10
Hi, just chiming in here as I was the one who just opened #3140.

> Do you think we can simply alter the installation of Eigen by simply removing the unsupported folder (not gonna be used anyways...)

This would be a terrible idea. For example, the Tensor module is in `unsupported/`.

> But this also means the Eigen port will create an .\unsupported folder in the base include folder.

Unfortunately that seems an unavoidable consequence of that.

According to the Eigen documentation http://eigen.tuxfamily.org/dox/GettingStarted.html, `Eigen/Core` is the way to include Eigen. And every open-source project that I use includes Eigen in this way. I would not recommend any project deviate from the official Eigen documentation and use `eigen3/Eigen/Core`.

It's a bit unfortunate that Eigen structures its include directories in that way, particularly where they put the  `unsupported` directory. It would be much better if they changed their upstream and put everything in one include directory like `include/` and then also put the `unsupported/` stuff there.

**Comment by LilyWangLL** [comment] 2022-06-15 08:52
Fixed by https://github.com/microsoft/vcpkg/pull/13739

**Closed by LilyWangLL** 2022-06-15 08:52 UTC
Labels: category:port-feature
