### ISSUE TITLE
there is no package for armadillo library

### ISSUE THREAD

**Issue by how0723** [Microsoft/vcpkg#2425] opened 2017-12-22 02:56 UTC
there is no package for armadillo library

conradsnicta/armadillo-code: source code repo for Armadillo C++ linear algebra (matrix) library - http://arma.sourceforge.net
https://github.com/conradsnicta/armadillo-code/

**Comment by jasjuang** [comment] 2018-01-01 07:10
Please consider making a new port for this and submit a PR!

**Comment by arthur-tacca** [comment] 2018-01-08 10:00
This is a dupe of #1491

**Comment by NancyLi1013** [comment] 2019-02-15 02:42
The PR has been merged. So it should be closed.

**Closed by NancyLi1013** 2019-02-15 02:42 UTC
Labels: new port request - consider making a PR!
