### ISSUE TITLE
[vcpkg] format-manifest crashes when vcpkg.json file is not UTF-8

### ISSUE THREAD

**Issue by Cheney-W** [microsoft/vcpkg#16405] opened 2021-02-25 07:41 UTC
**Repro Steps:**
1. Save the following codes into the ports\realsense2\vcpkg.json file: (The following code is missing a comma)
{
  "name": "realsense2",
  "version-semver": "2.42.0",
  "homepage": "https://github.com/IntelRealSense/librealsense",
  "description": "**Intel® RealSense™** SDK 2.0 is a cross-platform library for **Intel® RealSense™** depth cameras (D400 series and the SR300)"
  "dependencies": [
    {
      "name": "libusb",
      "platform": "linux"
    }
  ]
}
2. Run .\vcpkg.exe format-manifest .\ports\realsense2\vcpkg.json

**Expected Result:**
Failed to parse ... .\ports\realsense2\vcpkg.json: ... .\ports\realsense2\vcpkg.json:6:3: error: Unexpected character; expected comma or close brace
   on expression:   "dependencies": [
..............................^

**Actual Result:**
No output after executing the command.

**Comment:**
1. If the code error occurs before the "description" sentence(For example, "homapage" write one less double quote at the end), then format-manifest can detect the error.
2. If delete the small labels in the upper right corner of **Intel®** and **RealSense™**, then format-manifest can work normally.

**Comment by Cheney-W** [comment] 2021-02-25 08:34
It seems that copying the error code directly from the above to the local vcpkg.json file cannot reproduce this issue. Please use following file:
[vcpkg.log](https://github.com/microsoft/vcpkg/files/6041601/vcpkg.log)

![Capture](https://user-images.githubusercontent.com/38240633/109125653-43664c00-7787-11eb-8cf8-740e6dfb6f45.PNG)

**Comment by strega-nil** [comment] 2021-02-25 19:53
The issue is not the special characters; it's the lack of the comma...

**Comment by strega-nil** [comment] 2021-02-25 20:38
UAF, yay!

**Comment by Cheney-W** [comment] 2021-03-01 10:18
Thanks for your change!

**Comment by strega-nil** [comment] 2021-03-01 16:42
The change hasn't been merged yet to the vcpkg repo, so I think we shouldn't close it yet.

**Comment by Cheney-W** [comment] 2021-03-02 01:18
I have tested your change by locally building the vcpkg.exe and then I could see the utf-8 error occured. I think you have solved this issue as expected(We should fail on a file that isn't UTF-8).
![image](https://user-images.githubusercontent.com/38240633/109581706-bda42100-7b37-11eb-9d2e-4df3314c2477.png)

**Comment by NancyLi1013** [comment] 2021-07-21 10:29
Closing this issue for now, since the changes has been merged to vcpkg master branch.

Currently, the result is like this:

```
PS F:\latest\vcpkg> .\vcpkg.exe format-manifest ./ports/realsense2/vcpkg.json
Succeeded in formatting the manifest files.
```

**Closed by NancyLi1013** 2021-07-21 10:29 UTC
Labels: category:vcpkg-feature, info:manifests
