### ISSUE TITLE
[icu] build failure due to msys

### ISSUE THREAD

**Issue by DoctorDendrite** [microsoft/vcpkg#11544] opened 2020-05-23 23:12 UTC
**Host Environment**
- OS: Windows 10
- Cmake: 3.17.2 (x86)

**Expected**
Successful installation of package *icu x64*

**Actual**
Error code: Access violation

**To Reproduce**
`vcpkg install icu:x64-windows`

**Failure logs** 
- Console:
```
PS C:\tools> vcpkg install icu:x64-windows
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x64-windows
Starting package 1/1: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached C:/tools/vcpkg/downloads/icu4c-65_1-src.tgz
-- Using source at C:/tools/vcpkg/buildtrees/icu/src/c-65_1-src-702c9cff96
-- Acquiring MSYS Packages...
      0 [main] bash (25876) shared_info::initialize: size of shared memory region changed from 51128 to 40888
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/tools/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed make automake1.15"
    Working Directory: C:/tools/vcpkg/downloads/tools/msys2
    Error code: Access violation
    See logs for more information:
      C:\tools\vcpkg\buildtrees\icu\msys-pacman-x64-windows-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:108 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:78 (vcpkg_acquire_msys)
  scripts/ports.cmake:90 (include)


Error: Building package icu:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows
  Vcpkg version: 2020.02.04-nohash
```

- vcpkg\buildtrees\icu\msys-pacman-x64-windows-err.log:
```
0 [main] bash (25876) shared_info::initialize: size of shared memory region changed from 51128 to 40888
```

**Comment by Osyotr** [comment] 2020-05-25 18:07
Same error with `vcpkg install fribidi:x64-windows-static-md`

**Comment by NancyLi1013** [comment] 2020-05-26 05:49
Seems like something with `msys2`. 
Could you please try to remove msys2 first and then update vcpkg and rebuild this?

**Comment by NancyLi1013** [comment] 2020-05-29 06:07
@DoctorDendrite  and @Osyotr 

Please let me know if you still this problem with the latest vcpkg.

**Comment by Osyotr** [comment] 2020-05-29 06:47
@NancyLi1013 can't reproduce with latest vcpkg.

**Comment by DoctorDendrite** [comment] 2020-05-31 22:46
@NancyLi1013 
`Installing package icu[core]:x64-windows... done`
Success!

**Comment by NancyLi1013** [comment] 2020-06-01 08:16
Thanks for your update. 
I'm closing this issue for now.

**Closed by NancyLi1013** 2020-06-01 08:16 UTC
Labels: requires:repro
