### ISSUE TITLE
[sentencepiece] build failure

### ISSUE THREAD

**Issue by tikegami-mw** [microsoft/vcpkg#12267] opened 2020-07-05 02:44 UTC
**Host Environment**
- OS: Windows 10 Home 1903 Build 18362.900
- Compiler: Microsoft Visual C++ 2019   00435-60000-00000-AA459

**To Reproduce**
`./vcpkg install sentencepiece`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    sentencepiece[core]:x86-windows
Starting package 1/1: sentencepiece:x86-windows
Building package sentencepiece[core]:x86-windows...
-- Note: sentencepiece only supports static library linkage. Building static library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:51 (message):
  sentencepiece only supports static crt linkage
Call Stack (most recent call first):
  ports/sentencepiece/portfile.cmake:4 (vcpkg_check_linkage)
  scripts/ports.cmake:76 (include)

Error: Building package sentencepiece:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sentencepiece:x86-windows
  Vcpkg version: 2020.02.04-nohash

**Additional context**
I double-checked that the portfile is the latest version.

**Comment by JonLiu1993** [comment] 2020-11-13 06:33
@tikegami-mw ,Thanks for posting this issue. sentencepiece only support static library linkage, so you can build sentencepiece:x86-windows-static or sentencepiece:x64-windows-static

**Comment by sfhacker** [comment] 2020-11-14 14:40
![image](https://user-images.githubusercontent.com/25817529/99149646-7e1a0c00-26e3-11eb-8c65-2747b8140b96.png)

**Comment by JonLiu1993** [comment] 2021-12-15 07:54
@tikegami-mw ,
Since currently `sentencepiece ` only supports static CRT linkage. The problem you encountered is expected.

https://github.com/microsoft/vcpkg/blob/40a0fb232833dbc1b526394929f10b71627c2269/ports/sentencepiece/portfile.cmake#L1-L3

**Comment by JonLiu1993** [comment] 2021-12-15 07:54
Closing this issue since it is intended behavior.

**Closed by JonLiu1993** 2021-12-15 07:54 UTC
Labels: category:question
