### ISSUE TITLE
Boost now unusable with c++11/c++14/c++17

### ISSUE THREAD

**Issue by aPSopt** [Microsoft/vcpkg#2438] opened 2017-12-24 13:32 UTC
I installed last boost 1.66 though vcpkg. It is installed in new way as set of subliraries.
Next I tried to use boost with MSVS c++17 and saw fails:

> Info: Boost.Config is older than your compiler version

Also there are a lot of compile errors of usage the auto_ptr that already not present in the std namespace.

How to use boost library in old way? I dont like new style - early I didnt have such troubles.

**_Update_**

I built my project without any modernt compiler keys. Few projects was build succesfully, but all tests project that used boost test framework have linkage errors:
```
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "public: static class boost::unit_test::unit_test_log_t & __cdecl boost::unit_test::singleton<class boost::unit_test::unit_test_log_t>::instance(void)" (?instance@?$singleton@Vunit_test_log_t@unit_test@boost@@@unit_test@boost@@SAAEAVunit_test_log_t@23@XZ) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(test_tools.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "class boost::unit_test::master_test_suite_t & __cdecl boost::unit_test::framework::master_test_suite(void)" (?master_test_suite@framework@unit_test@boost@@YAAEAVmaster_test_suite_t@23@XZ) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(framework.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "public: void __cdecl boost::unit_test::unit_test_log_t::set_checkpoint(class boost::unit_test::basic_cstring<char const >,unsigned __int64,class boost::unit_test::basic_cstring<char const >)" (?set_checkpoint@unit_test_log_t@unit_test@boost@@QEAAXV?$basic_cstring@$$CBD@23@_K0@Z) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(unit_test_log.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "public: __cdecl boost::test_tools::assertion_result::assertion_result(bool)" (??0assertion_result@test_tools@boost@@QEAA@_N@Z) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(test_tools.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "public: __cdecl boost::test_tools::assertion_result::~assertion_result(void)" (??1assertion_result@test_tools@boost@@QEAA@XZ) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(test_tools.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "bool __cdecl boost::test_tools::tt_detail::report_assertion(class boost::test_tools::assertion_result const &,class boost::unit_test::lazy_ostream const &,class boost::unit_test::basic_cstring<char const >,unsigned __int64,enum boost::test_tools::tt_detail::tool_level,enum boost::test_tools::tt_detail::check_type,unsigned __int64,...)" (?report_assertion@tt_detail@test_tools@boost@@YA_NAEBVassertion_result@23@AEBVlazy_ostream@unit_test@3@V?$basic_cstring@$$CBD@63@_KW4tool_level@123@W4check_type@123@3ZZ) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(test_tools.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "public: static class boost::unit_test::decorator::collector & __cdecl boost::unit_test::singleton<class boost::unit_test::decorator::collector>::instance(void)" (?instance@?$singleton@Vcollector@decorator@unit_test@boost@@@unit_test@boost@@SAAEAVcollector@decorator@23@XZ) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(test_tools.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "public: __cdecl boost::unit_test::test_case::test_case(class boost::unit_test::basic_cstring<char const >,class boost::unit_test::basic_cstring<char const >,unsigned __int64,class boost::function<void __cdecl(void)> const &)" (??0test_case@unit_test@boost@@QEAA@V?$basic_cstring@$$CBD@12@0_KAEBV?$function@$$A6AXXZ@2@@Z) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(test_tree.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl boost::unit_test::ut_detail::normalize_test_case_name(class boost::unit_test::basic_cstring<char const >)" (?normalize_test_case_name@ut_detail@unit_test@boost@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$basic_cstring@$$CBD@23@@Z) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(test_tree.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "public: __cdecl boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(class boost::unit_test::test_case *,class boost::unit_test::decorator::collector &,unsigned long)" (??0auto_test_unit_registrar@ut_detail@unit_test@boost@@QEAA@PEAVtest_case@23@AEAVcollector@decorator@23@K@Z) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(test_tree.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "public: __cdecl boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(class boost::unit_test::basic_cstring<char const >,class boost::unit_test::basic_cstring<char const >,unsigned __int64,class boost::unit_test::decorator::collector &)" (??0auto_test_unit_registrar@ut_detail@unit_test@boost@@QEAA@V?$basic_cstring@$$CBD@23@0_KAEAVcollector@decorator@23@@Z) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(test_tree.obj)
1>boost_unit_test_framework-vc140-mt-gd-1_66.lib(boost_unit_test_framework-vc141-mt-gd-x64-1_66.dll) : error LNK2005: "public: __cdecl boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(int)" (??0auto_test_unit_registrar@ut_detail@unit_test@boost@@QEAA@H@Z) already defined in boost_test_exec_monitor-vc140-mt-gd-1_66.lib(test_tree.obj)
```

I notify that in this solution the code wasnt change except new boost libraries from vcpkg. And early it was build succesfully without any warnings.
So now the boost library break. 
Now it have unusable state.

**Comment by ras0219-msft** [comment] 2018-01-03 23:43
Duplicate of #2444

**Closed by ras0219-msft** 2018-01-03 23:43 UTC

**Comment by ras0219-msft** [comment] 2018-01-04 01:46
Thank you for reporting -- this should be fixed in master!
