### ISSUE TITLE
[vcpkg integrate] find_file_recursively_up(D:\vcpkg, .vcpkg-root): The parameter is incorrect.

### ISSUE THREAD

**Issue by creativegamer03** [microsoft/vcpkg#19524] opened 2021-08-12 12:25 UTC
When i was about to install the package i needed for my project, which i ran `vcpkg install jsoncpp` on cmd, i get the error:
`find_file_recursively_up(D:\vcpkg, .vcpkg-root): The parameter is incorrect.`

I installed `vcpkg` on my SD card since my main drive is getting full, due to something filling up the space (I mostly blame windows updates since my device can't run smoothly on 20H2, so I stayed on 1909). However, this error is just annoying. Please fix.

**Comment by JackBoosY** [comment] 2021-08-13 02:40
Can you add `--debug` to the install command and provide the output?

Thanks.

**Comment by ahmetabdi** [comment] 2021-08-13 15:14
Getting the same here

```
vcpkg integrate install --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
find_file_recursively_up(D:\Github\vcpkg, .vcpkg-root): The parameter is incorrect.
[DEBUG] C:\a\1\s\src\vcpkg\vcpkgpaths.cpp(294)
[DEBUG] Exiting after 26429 us (4997 us)
```

**Comment by ehsanrs2** [comment] 2021-08-22 16:30
recommend a short install path like `C:\src\vcpkg `or `C:\dev\vcpkg`, since otherwise, you may run into path issues for some port build systems.

**Comment by JackBoosY** [comment] 2021-08-23 02:56
@strega-nil-ms can you please take a look?

Thanks.

**Comment by JustWannaFly** [comment] 2021-08-30 15:14
I'm running into the same issue and found that if I move the `vcpkg` folder to my C drive it goes away, so apparently it's related to cloning onto a drive other than `C://` in windows. It would be nice to see this fixed or at least noted in the setup instructions

**Comment by Lvdi** [comment] 2021-09-02 03:08
> I'm running into the same issue and found that if I move the `vcpkg` folder to my `C:` drive it goes away, so apparently it's related to cloning onto a drive other than `C:` in windows. It would be nice to see this fixed or at least noted in the setup instructions

Looks like this issue is related to putting the vcpkg folder on a **removable media** (an SD card in the case of @creativegamer03 and a USB drive in my case).

The particular drive letter does not matter as long as it is not a removable drive.

**Comment by JustWannaFly** [comment] 2021-09-02 03:36
> The particular drive letter does not matter as long as it is not a removable drive.

All I know is I tried installing it on my `D:` drive (which is a 2TB HDD not a removable drive) and was running into this issue until I moved my install over to my `C:` drive. I'm not sure on the reason but the only difference was installing it on a secondary harddrive vs the disk windows is installed on.

**Comment by Lvdi** [comment] 2021-09-02 03:40
> > The particular drive letter does not matter as long as it is not a removable drive.
> 
> All I know is I tried installing it on my `D:` drive (which is a 2TB HDD not a removable drive) and was running into this issue until I moved my install over to my `C:` drive. I'm not sure on the reason but the only difference was installing it on a secondary harddrive vs the disk windows is installed on.

Well, I have no idea then...
In my case, I moved vcpkg from a USB drive (`E:`) to a secondary HDD (`D:`) and everything works.

**Comment by JoelJoly** [comment] 2021-09-02 12:12
I have the exact same bug and moving from an external SSD on D: to my internal SSD C: fixed the issue.

**Comment by strega-nil-ms** [comment] 2021-09-07 23:48
Hmm, can I request someone do the following: in your `vcpkg` repo, on the external SSD or w/e:

```cmd
> git init vcpkg-tool
> git -C vcpkg-tool fetch https://github.com/strega-nil/vcpkg-tool find-file-recursively-up-debug
> git -C vcpkg-tool checkout FETCH_HEAD
> cmake -B vcpkg-tool-build -S vcpkg-tool -DBUILD_TESTING=OFF
> cmake --build vcpkg-tool-build
> cp vcpkg-tool-build/Debug/vcpkg.exe .
```

and then try again?

**Comment by OlgaYuki** [comment] 2021-09-12 10:40
Hello, strega-nil-ms! 
Just tried:
> git init vcpkg-tool
> git -C vcpkg-tool fetch https://github.com/strega-nil/vcpkg-tool find-file-recursively-up-debug
> git -C vcpkg-tool checkout FETCH_HEAD
> cmake -B vcpkg-tool-build -S vcpkg-tool -DBUILD_TESTING=OFF
> cmake --build vcpkg-tool-build
> cp vcpkg-tool-build/Debug/vcpkg.exe .

and get: 

E:\src\vcpkg>vcpkg install cpprestsdk --debug 
> [DEBUG] Feature flag 'binarycaching' unset 
> [DEBUG] Feature flag 'manifests' unset
> [DEBUG] Feature flag 'compilertracking' unset 
> [DEBUG] Feature flag 'registries' unset 
> [DEBUG] Feature flag 'versions' unset 
> [DEBUG] BuiltinRegistry initialized with: ""
> find_file_recursively_up(E:\src\vcpkg, .vcpkg-root): The parameter is incorrect.
> [DEBUG] D:\a\_work\1\s\src\vcpkg\vcpkgpaths.cpp(294)
> [DEBUG] Exiting after 30.15 ms us (29421 us)

**Comment by strega-nil-ms** [comment] 2021-09-15 17:37
@OlgaYuki that doesn't look correct. Where are you running the first bit, and what is the output?

**Comment by warmwarm** [comment] 2021-09-23 05:50
I had the same issue when I put vcpkg on a tf card.
The card is in exFAT, when I changed it to NTFS, the issue gone.
Hope this information is meaningful.

**Comment by strega-nil-ms** [comment] 2021-09-23 20:12
I cannot figure out what is the problem if someone doesn't run the test binary.

**Comment by jpbruyere** [comment] 2021-09-27 13:57
I confirm that moving from a fat disk to ntfs (c:) solves the problem.

**Comment by rudi-lab** [comment] 2021-10-30 08:23
I had the same problem. Then I tried to set the vcpkg root directory and got:

`PS D:\Projects\test-vcpkg\test_vcpkg> .\vcpkg\vcpkg search sdl2 --vcpkg-root="D:\Projects\test-vcpkg\test_vcpkg\vcpkg" --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: D:\Projects\test-vcpkg\test_vcpkg\vcpkg
[DEBUG] Using installed-root: D:\Projects\test-vcpkg\test_vcpkg\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using downloads-root: D:\Projects\test-vcpkg\test_vcpkg\vcpkg\downloads
[DEBUG] Using packages-root: D:\Projects\test-vcpkg\test_vcpkg\vcpkg\packages
[DEBUG] Using scripts-root: D:\Projects\test-vcpkg\test_vcpkg\vcpkg\scripts
[DEBUG] Using ports-root: D:\Projects\test-vcpkg\test_vcpkg\vcpkg\ports
[DEBUG] Using versions-root: D:\Projects\test-vcpkg\test_vcpkg\vcpkg\versions
Error: while loading 3fd:
The port directory (D:\Projects\test-vcpkg\test_vcpkg\vcpkg\ports\3fd) does not exist
Error: failed to load port from D:\Projects\test-vcpkg\test_vcpkg\vcpkg\ports\3fd
Note: Updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
[DEBUG] D:\a\_work\1\s\src\vcpkg\registries.cpp(382)
[DEBUG] Exiting after %s (%d us)`

The D:\Projects\test-vcpkg\test_vcpkg\vcpkg\ports\3fd and it's files actually DOES exist. D: is a SD card BTW.

**Comment by creativegamer03** [comment] 2021-11-03 09:20
So this problem only happens when vcpkg is on a non-NTFS drive. will there be an update/fix to support such just in case a particular case (like mine) happens?

**Comment by KrishnaPG** [comment] 2021-11-27 08:27
Getting the same problem and hoping to see a fix

**Comment by dg0yt** [comment] 2021-12-24 11:22
> I cannot figure out what is the problem if someone doesn't run the test binary.

@strega-nil-ms Can't you test with a non-NTFS drive (SD card, USB stick with exFAT)?

**Comment by strega-nil-ms** [comment] 2021-12-29 22:57
@dg0yt I don't own a windows machine

**Comment by dg0yt** [comment] 2021-12-30 05:40
@strega-nil-ms But I assume there is at least one vcpkg team member who has got all of Windows, Visual Studio, and a cheap USB stick?

**Comment by strega-nil-ms** [comment] 2022-01-03 18:55
@dg0yt oh, sure; poke @BillyONeal ?

**Comment by BillyONeal** [comment] 2022-01-03 21:17
I don't have an easy way to test this at the moment because I'm both under COVID quarantine and my "beefy" laptop which could reasonably run VMs broke on my trip :(. When the laptop broke I ordered parts to make my home desktop workstation-ish; those parts are supposed to be delivered today but who knows. Worst case I get out of "COVID jail" on Wednesday and should be able to use my work workstation again and test.

**Comment by BillyONeal** [comment] 2022-01-03 21:18
(I do have a cheap USB stick but given that this isn't super urgent I would rather just wait to run it in a VM I already have with an extra throwaway disk formatted as exFAT)

**Comment by PhoebeHui** [comment] 2022-01-04 01:50
Hope you are safe! @BillyONeal

**Comment by BillyONeal** [comment] 2022-01-05 23:13
Luckily it was just a phone notification that I *might* have been near a COVID person, I didn't get COVID myself :). Sorry, I got parts yesterday but forgot about this item. Trying now...

**Comment by BillyONeal** [comment] 2022-01-06 00:49
![image](https://user-images.githubusercontent.com/1544943/148310375-6ad31a18-90b4-42da-b799-dde42616e5ea.png)

Looks like this is still unhappy on exFAT. I don't think this is actually the same bug @creativegamer03 was talking about, since that should have been fixed by https://github.com/microsoft/vcpkg-tool/pull/244, but it is the bug that was dupe'd into this one.

**Comment by BillyONeal** [comment] 2022-01-06 01:28
This problem is https://github.com/microsoft/STL/issues/233

**Comment by BillyONeal** [comment] 2022-01-06 01:34
Unfortunately it doesn't look like that problem is easy to workaround without vcpkg entirely reimplementing `std::filesystem::symlink_status` itself. That's doable, particularly given that vcpkg doesn't care about full fidelity behavior, but given that there's already pending changes that will fix it in the standard library I would prefer to just let that happen unless this is extremely urgent:?

**Comment by JackBoosY** [comment] 2022-07-29 07:51
@BillyONeal I saw https://github.com/microsoft/STL/pull/2373 was merged, so is this issue fixed?

**Comment by BillyONeal** [comment] 2023-03-21 20:42
Can anyone with this problem check if the issue is fixed now?

**Closed** 2023-03-27 17:05 UTC
Labels: category:vcpkg-bug
