### ISSUE TITLE
Why isn't the base build 64bit?

### ISSUE THREAD

**Issue by rinechran** [microsoft/vcpkg#27193] opened 2022-10-12 06:02 UTC
32bit os are too old and i Don't think it shuold be maintained 

I think 64 bits should be the default value of vcpkg.

Why is the default value 32 bits?

**Comment by Cheney-W** [comment] 2022-10-12 08:59
Duplicate of https://github.com/microsoft/vcpkg/discussions/17254

**Closed by Cheney-W** 2022-10-12 08:59 UTC
Labels: category:question
