### ISSUE TITLE
Update OpenCV to 4.0.0

### ISSUE THREAD

**Issue by jasjuang** [microsoft/vcpkg#4758] opened 2018-11-19 05:11 UTC
Can someone please do this? @UnaNancyOwen @cenit @patrikhuber

**Comment by cenit** [comment] 2018-11-19 09:48
the problem is that OpenCV3 could still be interesting (openCV2 also, from some points of view). In fact I also pushed a port of OpenCV2 but never got merged... shall we add a "new" port, keeping opencv3 at least still available? Removing all the C lib interfaces (many already broken, that's why OCV2 was interesting also) could be a disaster for many people working on "old" projects

**Comment by UnaNancyOwen** [comment] 2018-11-19 13:29
The C API (old style API) has been deprecated since OpenCV 3.0. It was already five years ago. They removed it in OpenCV 4.0. OpenCV had taken a sufficient transition term for convert to C++ API (new style API) for users.
I think there is already no need to leave the old version.

**Comment by huangqinjin** [comment] 2018-11-19 13:35
OpenCV4 can coexist with OpenCV3 under linux: headers are installed into `/usr/local/include/opencv4/opencv2` and config.cmake into `/usr/local/lib64/cmake/opencv4`. You can switch version between 3 and 4 by `find_package(OpenCV 3)` and `find_package(OpenCV 4)`. Add a new port `opencv4`.

**Comment by UnaNancyOwen** [comment] 2018-11-19 14:11
I think it is difficult to coexist OpenCV 3.x and OpenCV 4.x under Windows (and Vcpkg) at least. What do you think? (@huangqinjin Thank you for giving me good information. 👍)

**Comment by cenit** [comment] 2018-11-19 21:04
no problem in coexisting, like opencv2 can already coexist with opencv3...
also, C API is still used a lot, no matter if it has been deprecated or not. I can't understand why removing thing should be appreciated. If there's one thing I really love from microsoft, it is their dedication towards backwards compatibility. It is difficult to build the future, continuously forgetting the past and rebuilding things again and again... 
Apart from the famous VLC problems with OpenCV 3.4.1, when they mistakingly forgot one C API from the release, just think about many projects related to PCL, or even YOLO..... there are many examples, bigger or smaller. All of them, they DEPEND on those C API, and removing OpenCV3 would break all of them in a breeze!

**Comment by UnaNancyOwen** [comment] 2018-11-20 06:31
> the coexistance problem can be solved through exclusivity. If you have one installed, others are prohibited, like it is already done for different implementations of the same library.

Yes, It is right. It can coexist by exclusive control. I agree.

I think there are several ways to implement exclusive control.
@alexkaratarakis @ras0219-msft Let's ask the administrator's opinion. 

1. Implement OpenCV 4.x (mainstream) and OpenCV 3.4.x (legacy) in one opencv port. It is switch by option. For example, <code>vcpkg install opencv</code> (default) is install OpenCV 4.x, <code>vcpkg install opencv[legacy]</code> is install OpenCV 3.4.x.

2. Implement OpenCV 4.x (mainstream) and OpenCV 3.4.x (legacy) on different two ports. For example, opencv port is isntall OpenCV 4.x and opencv3 port is install OpenCV 3.4.x. In this case, If different one port is installed, display warning and stop installation.

3. Other ideas. Do you have any good ideas?

**Comment by cenit** [comment] 2018-11-20 08:20
Something on the line of libmysql/libmariadb for me would be perfect...
https://github.com/Microsoft/vcpkg/blob/008c5d8668b9a0b42dee249057bac223a3e3f896/ports/libmysql/portfile.cmake#L2

**Comment by cenit** [comment] 2018-11-20 13:00
also, tbh, OpenCV port has been broken with latest update. I am sorry it took me too much time (working too much lately), but I just tried to update and *at least* the ffmpeg feature is broken #4636  (it has not been updated to the latest port, still the patch has been accepted). Again and again, OpenCV port has been broken just to hurry a patch to update to latest version...

**Comment by patrikhuber** [comment] 2018-11-20 20:38
I'd also suggest a flag `[legacy]` or so (though that might be confusing since normally this is used for OpenCV's modules), or a separate package/portfile. It would be best to move the package `opencv` to 4.0, and for people who still need 3.x, have them move to an `opencv-3` package. In that way, the `opencv` can always stay the latest version, which is what people would expect from a package without a version number.

OpenCV is an example where this is in my opinion warranted, as unfortunately people are really slow at upgrading and there's a **ton** of research code out there that depends on opencv-2 or opencv-3 and which will never be updated (or in years).

**Comment by cenit** [comment] 2019-05-03 09:51
WIP in #5169

**Closed** 2019-08-12 16:22 UTC
Labels: port update
