### ISSUE TITLE
Getting ZLIB error when using folly (x64-windows-static)

### ISSUE THREAD

**Issue by jz-fb** [microsoft/vcpkg#13344] opened 2020-09-04 01:40 UTC
When building a project with folly  (x64-windows-static) I get the error below

## Error:
` $ cmake .. -DBUILD_BENCHMARKS=ON`
` -- git Version: v1.5.0-01c0ab7c`
` -- Version: 1.5.0`
` -- Performing Test HAVE_STD_REGEX -- success`
` -- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile`
` -- Performing Test HAVE_POSIX_REGEX -- failed to compile`
` -- Performing Test HAVE_STEADY_CLOCK -- success`
`  --`
CMake Error at C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.18/Modules/FindZLIB.cmake:115 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  C:/Program Files/CMake/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  C:/Users/pcc/Desktop/disp2/thirdparty/vcpkg/installed/x64-windows-static/share/folly/folly-config.cmake:5 (find_dependency)
  benchmarks/CMakeLists.txt:22 (find_package)

`
 -- Configuring incomplete, errors occurred!`
See also "C:/Users/pcc/Desktop/disp2/dispenso/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/pcc/Desktop/disp2/dispenso/build/CMakeFiles/CMakeError.log".`

## Root cmakelists.txt:
`cmake_minimum_required(VERSION 3.12)
project(Dispenso VERSION 0.1.0)

if (WIN32)
set(CMAKE_TOOLCHAIN_FILE "../thirdparty/vcpkg/scripts/buildsystems/vcpkg.cmake")
add_compile_definitions(NOMINMAX)
set(CMAKE_CXX_STANDARD 17)
endif (WIN32)

set(CMAKE_PREFIX_PATH "${CMAKE_SOURCE_DIR}/../thirdparty/vcpkg/installed/x64-windows-static/share/ ${CMAKE_PREFIX_PATH}")`  ** without this line find_package() for folly doesn't work **

if (WIN32)
set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS TRUE)
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /MT")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} /MTd")
endif (WIN32)

 `# Setup VCPKG for windows`
if (WIN32)
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)
endif (WIN32)
 ....
if(BUILD_BENCHMARKS)
    ############# Benchmarks
    add_subdirectory(benchmarks)
endif (BUILD_BENCHMARKS)`

 ##  Benchmarks cmakelists.txt:
```
`    
find_package(folly REQUIRED)
include_directories(${FOLLY_INCLUDE_DIR})
 ...
add_executable(
    future_benchmark
    ./future_benchmark.cpp
)

target_link_libraries(
    future_benchmark
    PUBLIC thread_pool
    PUBLIC task_set
    PUBLIC thread_benchmark_common
    PUBLIC folly
    PUBLIC ${Boost_LIBRARIES} ${FOLLY_LIBRARIES} ${FOLLY_LINK_LIBRARIES}
    PUBLIC concurrentqueue
    PUBLIC gflags
)
if (WIN32)
target_link_libraries(
    future_benchmark
    PUBLIC ws2_32
    PUBLIC synchronization
)
endif (WIN32)
```
`

**Comment by NancyLi1013** [comment] 2020-09-04 01:49
Have you tried the latest commit? This issue should be fixed via #13278. 

Is this the same issue as #13287 that you posted before? If the issue wasn't fixed, we can reopen it. It's not necessary to create a new one.

**Comment by jz-fb** [comment] 2020-09-04 01:59
Git log shows I'm at last commit of: Fix ffmpeg build for PATH with spaces. (#13275), so I should have it. I literally cloned it a few hours back.

**Comment by NancyLi1013** [comment] 2020-09-04 05:48
Does this issue only exist on static build or not? Have you tried to build `fooly:x64-windows`?

**Comment by NancyLi1013** [comment] 2020-09-04 06:45
Also please try to use like this:

```
find_package(folly CONFIG REQUIRED)
target_link_libraries(main PRIVATE Folly::folly Folly::folly_deps Folly::follybenchmark Folly::folly_test_util)
```

**Comment by jz-fb** [comment] 2020-09-04 20:33
The non-static version is even worse. It starts asking for all the prior dependencies and once I specify their directory locations we're back to zlib again.

**Comment by NancyLi1013** [comment] 2020-09-08 06:43
Sorry, I cannot reproduce this on my machine.
Please use` find_package(folly CONFIG REQUIRED)` to find `folly`. Also the current issue that `ZLIB `cannot be found seems to be strange, which is different from this [here](https://github.com/microsoft/vcpkg/issues/13196).

Could you please try to refer to #13196 to try this again?

**Comment by deleeuwict** [comment] 2020-09-10 07:35
Hi, i have exactly the same ZLIB error when building boost for x64-windows-static on a fresh compiled vcpkg install.

**Comment by NancyLi1013** [comment] 2020-09-15 08:27
Does the path you used contains Upper character or spaces on your machine?
Uppercase issue, please see #12709.  

Spaces issue will fixed by #13126.

**Comment by deleeuwict** [comment] 2020-09-15 09:34
> Does the path you used contains Upper character or spaces on your machine?
> Uppercase issue, please see #12709.
> 
> Spaces issue will fixed by #13126.

No, the base path on my machine is c:\code\vcpkg

**Comment by NancyLi1013** [comment] 2020-10-14 06:39
Sorry for the long delay, but I still cannot reproduce this issue on my machine. So I have no idea what's wrong with your environment now.

```
PS F:\new\vcpkg> .\vcpkg.exe install zlib:x64-windows
Computing installation plan...
The following packages will be built and installed:
    zlib[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: zlib:x64-windows
Building package zlib[core]:x64-windows...
Could not locate cached archive: C:\Users\AppData\Local\vcpkg\archives\db\dbed138fc2cf727d1d830f40646871fd12b70f4a.zip
-- Using cached F:/new/vcpkg/downloads/zlib1211.tar.gz
-- Extracting source F:/new/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at F:/new/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Using msys root at F:/new/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: F:/new/vcpkg/packages/zlib_x64-windows/lib/pkgconfig/zlib.pc
-- Fixing pkgconfig file: F:/new/vcpkg/packages/zlib_x64-windows/debug/lib/pkgconfig/zlib.pc
-- Installing: F:/new/vcpkg/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\AppData\Local\vcpkg\archives\db\dbed138fc2cf727d1d830f40646871fd12b70f4a.zip
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 1.616 min

Total elapsed time: 2.158 min

The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)
```

**Comment by NancyLi1013** [comment] 2020-12-30 07:45
Hi @deleeuwict 

Could you please try to update to the latest vcpkg and rebuild this port?

**Comment by deleeuwict** [comment] 2020-12-30 10:19
> Hi @deleeuwict
> 
> Could you please try to update to the latest vcpkg and rebuild this port?

Hi, 

Could you tell me the procedure of upgrading vckpkg without losing my installation?

**Comment by NancyLi1013** [comment] 2021-02-08 10:51
Sorry for the long delay.

You can use `git pull `to update vcpkg to the latest version.

**Comment by NancyLi1013** [comment] 2021-03-23 07:14
@deleeuwict 

Is this still a problem for your after update to the latest version?

**Comment by NancyLi1013** [comment] 2021-04-20 07:38
Closing this issue for now. Please feel free to reopen this issue if it is still a problem for you.

**Closed by NancyLi1013** 2021-04-20 07:38 UTC
Labels: category:question, requires:repro
