### ISSUE TITLE
[gtk] missing `.pc` file for pkg-config

### ISSUE THREAD

**Issue by Glavo** [microsoft/vcpkg#7641] opened 2019-08-11 05:42 UTC
****
When I tried to find gtk in CMake like this, it failed: 
```cmake
find_package(PkgConfig REQUIRED)
pkg_check_modules(GTK3 REQUIRED gtk+-3.0)
```
There is no `.pc` fileassociated with GTK+ 3  in under `C:\vcpkg\installed\x64-windows\lib\pkgconfig`. 

**Proposed solution**
Add the `.pc` associated with GTK+ 3.

**Comment by Glavo** [comment] 2020-04-03 21:10
Is there any progress on this issue?

**Comment by JackBoosY** [comment] 2020-04-07 03:15
@Glavo Sorry for late, gtk's pkgconfig files should be installed in _VCPKG_PATH/installed/TRIPLET/lib/pkgconfig_ now.
Could you check this?

Thanks.

**Comment by zdyang** [comment] 2021-02-20 07:25
It looks like the `gtk3.pc` for gtk3 is still missing?

I installed `gtk3:x64-windows` with vcpkg but could not find the .pc file. The files in my `pkgconfig` folder are as following
```
 Directory of C:\Users\zidong\workspace\vcpkg\installed\x64-windows\lib\pkgconfig

2021/02/18  16:43    <DIR>          .
2021/02/18  16:43    <DIR>          ..
2021/02/18  16:12               280 atk.pc
2021/02/18  16:13               221 bzip2.pc
2021/02/18  16:42               326 epoxy.pc
2021/02/18  16:14               263 expat.pc
2021/02/18  16:39               535 fontconfig.pc
2021/02/18  16:15               370 freetype2.pc
2021/02/18  16:12               435 gio-2.0.pc
2021/02/18  16:12               331 gio-windows-2.0.pc
2021/02/18  16:12               373 glib-2.0.pc
2021/02/18  16:12               288 gmodule-2.0.pc
2021/02/18  16:12               288 gmodule-export-2.0.pc
2021/02/18  16:12               287 gmodule-no-export-2.0.pc
2021/02/18  16:12               285 gobject-2.0.pc
2021/02/18  16:12               242 gthread-2.0.pc
2021/02/18  16:43               264 harfbuzz-subset.pc
2021/02/18  16:43               256 harfbuzz.pc
2021/02/18  16:16               281 json-c.pc
2021/02/18  16:13               294 libbrotlicommon.pc
2021/02/18  16:13               322 libbrotlidec.pc
2021/02/18  16:13               322 libbrotlienc.pc
2021/02/18  16:09               277 libffi.pc
2021/02/18  16:10               343 libpcre.pc
2021/02/18  16:10               348 libpcre16.pc
2021/02/18  16:10               348 libpcre32.pc
2021/02/18  16:10               288 libpcrecpp.pc
2021/02/18  16:10               331 libpcreposix.pc
2021/02/18  16:14               283 libpng.pc
2021/02/18  16:14               283 libpng16.pc
2021/02/18  16:10               290 zlib.pc
              29 File(s)          9,054 bytes
               2 Dir(s)  22,730,084,352 bytes free
```
Version Infos
- OS: Win 10
- vcpkg version: 2021-01-13-768d8f95c9e752603d2c5901c7a7c7fbdb08af35

Thanks

**Comment by JackBoosY** [comment] 2021-02-20 08:12
@zdyang Yes I confirmed.

**Comment by Neumann-A** [comment] 2021-04-26 20:41
@JackBoosY #13100 has been merged so this shouldn't be an issue any longer

**Closed** 2021-04-27 09:38 UTC
Labels: category:port-feature
