### ISSUE TITLE
Failures when vcpkg install folly:x64-windows --head

### ISSUE THREAD

**Issue by PhoebeHui** [Microsoft/vcpkg#2090] opened 2017-10-31 08:11 UTC
We want to build latest Folly revision from github with latest MSVC compiler, I got command ‘vcpkg install folly:x64-windows --head’  from https://vcpkg.readthedocs.io/en/latest/maintainers/vcpkg_from_github/ to use latest revision from github https://github.com/facebook/folly. 

My question is how I know what the revision it used? can I pass the revision that I want it build?

Also I noticed there is a failure when build folly, the issue in installing double-conversion:x64-windows which folly needed. See the failure like below, it says ‘file RENAME failed … because the file exist’, I double confirm the file doesn’t exsit. And there is no CMake folder under D:/VCPKG/src/packages/double-conversion_x64-windows/debug. I use the latest VCPKG revision '3457d89'

Starting package 6/12: double-conversion:x64-windows
Building package double-conversion:x64-windows from HEAD...
-- CURRENT_INSTALLED_DIR=D:/VCPKG/src/installed/x64-windows
-- DOWNLOADS=D:/VCPKG/src/downloads
-- CURRENT_PACKAGES_DIR=D:/VCPKG/src/packages/double-conversion_x64-windows
-- CURRENT_BUILDTREES_DIR=D:/VCPKG/src/buildtrees/double-conversion
-- CURRENT_PORT_DIR=D:/VCPKG/src/ports/double-conversion/.
-- Downloading https://github.com/google/double-conversion/archive/master.tar.gz...
-- Downloading https://github.com/google/double-conversion/archive/master.tar.gz... OK
-- Extracting source D:/VCPKG/src/downloads/google-double-conversion-master.tar.gz
-- Extracting done
-- Applying patch D:/VCPKG/src/ports/double-conversion/001-fix-arm.patch
-- Applying patch D:/VCPKG/src/ports/double-conversion/001-fix-arm.patch done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
CMake Error at ports/double-conversion/portfile.cmake:26 (file):
  file RENAME failed to rename

    D:/VCPKG/src/packages/double-conversion_x64-windows/debug/CMake/double-conversionLibraryDepends-debug.cmake

  to

    D:/VCPKG/src/packages/double-conversion_x64-windows/debug/CMake/double-conversionTargets-debug.cmake

  because: File exists

Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)

Error: Building package double-conversion:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: double-conversion:x64-windows
  Vcpkg version: 0.0.94

Additionally, attach any relevant sections from the log files above.

**Comment by KindDragon** [comment] 2017-10-31 08:32
Try install double-conversion without `--head` before folly `vcpkg install double-conversion`

**Comment by ras0219-msft** [comment] 2017-10-31 09:17
Thanks for reporting this issue! There's a few pieces that actually contributed to this failure:

1. We shouldn't be propagating `--head` down to dependencies; I'm going to investigate this further and fix it.
2. `double-conversion` failed to build from `--head`; I've fixed this in the latest `master`.

I recommend @KindDragon's suggestion since that's our intended behavior.

**Comment by PhoebeHui** [comment] 2017-10-31 09:33
Thank you @KindDragon and @ras0219-msft  for the quick response!

I have tried, it works, 3 sources need install before folly, list below:
    vcpkg install double-conversion:x64-windows
    vcpkg install gflags:x64-windows
    vcpkg install glog:x64-windows

Is there is a way that I can I pass the revision from the github that I want it build? like vcpkg install folly:x64-windows ecd0fb3’ ☺

**Comment by ras0219-msft** [comment] 2017-10-31 10:11
I've pushed a fix for 1. above, so you should now be able to simply run `vcpkg install folly:x64-windows --head`!

Now, as for specific revisions -- if you'd like to "pin" to a specific version for any reason, you should edit the port itself and specify your new ref. This is easy to do with `vcpkg edit folly` and then changing the `vcpkg_from_github` block to be something like:
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO facebook/folly
    REF ecd0fb3....
    SHA512 000
    HEAD_REF master
)
```
(If you run the install command once, the error message will tell you the correct SHA512 to use).

This way, you'll have consistent, reliable behavior in the future. `--head` is really meant to temporarily tighten the loop between developers (so when the dev says "I fixed it in master!" you have something you can try ;)).

To discover the commit used after installing with `--head`, you can run `vcpkg list folly --x-full-desc`. The version listed will be the git sha1.

**Closed by ras0219-msft** 2017-10-31 10:11 UTC
Labels: vcpkg bug

**Comment by PhoebeHui** [comment] 2017-10-31 10:20
Cool! Thank you!

I will use --head, it's much simple than another way.
