### ISSUE TITLE
[opencv] build failure about libjpeg-turbo:x86-windows

### ISSUE THREAD

**Issue by Erixar** [microsoft/vcpkg#18946] opened 2021-07-14 11:43 UTC
**Host Environment**
- OS: [Windows]

I'm tring to install opencv by vcpkg,and got some problem when building libjpeg-turbo:x86-windows

F:\Git\vcpkg>vcpkg install opencv
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x86-windows -> 2.0.6
  * liblzma[core]:x86-windows -> 5.2.5#2
  * libpng[core]:x86-windows -> 1.6.37#15
  * libwebp[core,nearlossless,simd,unicode]:x86-windows -> 1.1.0#3
    opencv[core,dnn,jpeg,png,quirc,tiff,webp]:x86-windows -> 4.5.2
  * opencv4[core,dnn,jpeg,png,quirc,tiff,webp]:x86-windows -> 4.5.2
  * protobuf[core]:x64-windows -> 3.15.8#3
  * protobuf[core]:x86-windows -> 3.15.8#3
  * quirc[core]:x86-windows -> 1.1#2
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.3.0
  * vcpkg-cmake[core]:x64-windows -> 2021-06-25#4
  * vcpkg-cmake-config[core]:x64-windows -> 2021-05-22
  * zlib[core]:x86-windows -> 1.2.11#10
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\6b\6b0397ffc5a6d749138dca0a628a8b522038cbe24afe54e1fc8b311a3c0a840d.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\57\5794386d876665bce0f93cf39d0b7f3eefd900d80ebcf36ea30d2b0659796d2b.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\2d\2d45ff6d68591ce4431759446a4f8d889e6e75aa1e18ec2bb526e24cabe1afc9.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\f0\f0a130ad13f9ae549d45285f800cb6e5b7c5c4978204e5826ce2505043c611ce.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\99\99e64b7c4b2b1cc0a28f5fc5058ebcb1bbfca157b5065ad47aba3129a737f2a0.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\f8\f84f43917e9b1fa19715ec165aa4d1f40c3183d9ff43f155e4ea06c88dad6db6.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\92\92fd91cf098a06c5529bb7d74e28dd349e3e4424a6a4fb7d8062e61f49a60e30.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\b8\b854f75fec7c0e9089ded1fe8c216ec394cdc6e1472b8eb1d38c0e8ef3a86483.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\66\660b44f651ba1595be53b92121cab50e429346387eb0ceb75bae88bd108c77af.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\5a\5a2c598ade043abb4603ad514a06883a12670f81eafe562c0cac3c57f4a72c16.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\d4\d4163a69bdaeb73e981856432fc20fffa12725ceb2425535d284278270eb7dee.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\cb\cb6df8df01d46f279fcb4c8268eb525e3d92b37d07e5b8f7cbae0670ddab0739.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\73\73d711f3cce78299355fb11435a44406f1da7a7b97307ab82990cfe7794e6c60.zip
Starting package 1/13: libjpeg-turbo:x86-windows
Building package libjpeg-turbo[core]:x86-windows...
-- Using F:/Git/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz
-- Cleaning sources at F:/Git/vcpkg/buildtrees/libjpeg-turbo/src/b2d5000173-96baffe5bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Git/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Applying patch fix-incompatibility-for-c11-c17.patch
-- Using source at F:/Git/vcpkg/buildtrees/libjpeg-turbo/src/b2d5000173-96baffe5bc.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/libjpeg-turbo/portfile.cmake:35 (vcpkg_check_features)
  scripts/ports.cmake:139 (include)

-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: F:/Git/vcpkg/buildtrees/libjpeg-turbo/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\Git\vcpkg\buildtrees\libjpeg-turbo\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/libjpeg-turbo/portfile.cmake:40 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)

Error: Building package libjpeg-turbo:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libjpeg-turbo:x86-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Additionally, attach any relevant sections from the log files above.

**Failure logs** 
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/6815712/config-x86-windows-out.log)

**Comment by JonLiu1993** [comment] 2021-07-15 02:40
@Erixar ,Thanks for posting this issue.
--mt=CMAKE_MT-NOTFOUND
Please re-install Windows SDK and try again.

Thanks.

**Comment by Erixar** [comment] 2021-07-15 12:20
> @Erixar ,Thanks for posting this issue.
> --mt=CMAKE_MT-NOTFOUND
> Please re-install Windows SDK and try again.
> 
> Thanks.

I've re-installed Windows 10 SDK(10.0.19041.0) by Visual Studio, and looks like nothing happened.

F:\Git\vcpkg>vcpkg install opencv
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x86-windows -> 2.0.6
  * liblzma[core]:x86-windows -> 5.2.5#2
  * libpng[core]:x86-windows -> 1.6.37#15
  * libwebp[core,nearlossless,simd,unicode]:x86-windows -> 1.1.0#3
    opencv[core,dnn,jpeg,png,quirc,tiff,webp]:x86-windows -> 4.5.2
  * opencv4[core,dnn,jpeg,png,quirc,tiff,webp]:x86-windows -> 4.5.2
  * protobuf[core]:x64-windows -> 3.15.8#3
  * protobuf[core]:x86-windows -> 3.15.8#3
  * quirc[core]:x86-windows -> 1.1#2
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.3.0
  * vcpkg-cmake[core]:x64-windows -> 2021-06-25#4
  * vcpkg-cmake-config[core]:x64-windows -> 2021-05-22
  * zlib[core]:x86-windows -> 1.2.11#10
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x86-windows...
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\6b\6b0397ffc5a6d749138dca0a628a8b522038cbe24afe54e1fc8b311a3c0a840d.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\57\5794386d876665bce0f93cf39d0b7f3eefd900d80ebcf36ea30d2b0659796d2b.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\2d\2d45ff6d68591ce4431759446a4f8d889e6e75aa1e18ec2bb526e24cabe1afc9.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\f0\f0a130ad13f9ae549d45285f800cb6e5b7c5c4978204e5826ce2505043c611ce.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\99\99e64b7c4b2b1cc0a28f5fc5058ebcb1bbfca157b5065ad47aba3129a737f2a0.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\f8\f84f43917e9b1fa19715ec165aa4d1f40c3183d9ff43f155e4ea06c88dad6db6.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\92\92fd91cf098a06c5529bb7d74e28dd349e3e4424a6a4fb7d8062e61f49a60e30.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\b8\b854f75fec7c0e9089ded1fe8c216ec394cdc6e1472b8eb1d38c0e8ef3a86483.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\66\660b44f651ba1595be53b92121cab50e429346387eb0ceb75bae88bd108c77af.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\5a\5a2c598ade043abb4603ad514a06883a12670f81eafe562c0cac3c57f4a72c16.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\d4\d4163a69bdaeb73e981856432fc20fffa12725ceb2425535d284278270eb7dee.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\cb\cb6df8df01d46f279fcb4c8268eb525e3d92b37d07e5b8f7cbae0670ddab0739.zip
Could not locate cached archive: C:\Users\Erixar\AppData\Local\vcpkg\archives\73\73d711f3cce78299355fb11435a44406f1da7a7b97307ab82990cfe7794e6c60.zip
Starting package 1/13: libjpeg-turbo:x86-windows
Building package libjpeg-turbo[core]:x86-windows...
-- Using F:/Git/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz
-- Cleaning sources at F:/Git/vcpkg/buildtrees/libjpeg-turbo/src/b2d5000173-96baffe5bc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Git/vcpkg/downloads/libjpeg-turbo-libjpeg-turbo-10ba6ed3365615ed5c2995fe2d240cb2d5000173.tar.gz
-- Applying patch add-options-for-exes-docs-headers.patch
-- Applying patch workaround_cmake_system_processor.patch
-- Applying patch fix-incompatibility-for-c11-c17.patch
-- Using source at F:/Git/vcpkg/buildtrees/libjpeg-turbo/src/b2d5000173-96baffe5bc.clean
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/libjpeg-turbo/portfile.cmake:35 (vcpkg_check_features)
  scripts/ports.cmake:139 (include)


-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: F:/Git/vcpkg/buildtrees/libjpeg-turbo/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      F:\Git\vcpkg\buildtrees\libjpeg-turbo\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/libjpeg-turbo/portfile.cmake:40 (vcpkg_configure_cmake)
  scripts/ports.cmake:139 (include)


Error: Building package libjpeg-turbo:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libjpeg-turbo:x86-windows
  Vcpkg version: 2021-05-05-e8977e69d9a3fb462d9ad42013d83a7682706659

Additionally, attach any relevant sections from the log files above.
[config-x86-windows-out.log](https://github.com/microsoft/vcpkg/files/6822997/config-x86-windows-out.log)

**Comment by JonLiu1993** [comment] 2021-07-16 08:44
@Erixar, have you installed the English package  in Visual Studio?

**Comment by Erixar** [comment] 2021-07-16 10:11
> @Erixar, have you installed the English package in Visual Studio?
Yes, already installed

**Comment by cenit** [comment] 2021-07-16 10:43
c++ workload in vs installer is enabled?

**Comment by Erixar** [comment] 2021-07-16 11:49
> c++ workload in vs installer is enabled?

Looks like that's the problem, I've tried to print Hello World and cl.exe do not work well. I'll re-install Visual Studio and try again. thanks

**Comment by JonLiu1993** [comment] 2021-07-19 10:18
@Erixar ,Is this problem solved?

**Comment by Erixar** [comment] 2021-07-19 11:35
> @Erixar ,Is this problem solved?

yes,yes. I don't know what happened, but everything goes well. thanks for your help and sorry to let you know that so late.

**Comment by cenit** [comment] 2021-07-19 12:01
please close the issue if the problem is gone

**Closed** 2021-07-19 12:54 UTC
Labels: requires:repro
