### ISSUE TITLE
[opencv4:x86-windows] build failure

### ISSUE THREAD

**Issue by tan-wei** [microsoft/vcpkg#7981] opened 2019-08-30 02:17 UTC
**Host Environment**
- OS: Windows_zhCN
- Compiler: MSVC 2017

**To Reproduce**
`./vcpkg.exe install opencv4[ade,contrib,core,dnn,eigen,ffmpeg,gdcm,halide,ipp,jasper,jpeg,nonfree,openexr,opengl,openmp,ovis,png,sfm,tbb,tiff,vtk,webp,world,qt]`

**Failure logs** 
```
The following packages will be built and installed:
    opencv4[ade,contrib,core,dnn,eigen,ffmpeg,gdcm,halide,ipp,jasper,jpeg,nonfree,openexr,opengl,openmp,ovis,png,qt,sfm,tbb,tiff,vtk,webp,world]:x86-windows
Starting package 1/1: opencv4:x86-windows
Building package opencv4[ade,contrib,core,dnn,eigen,ffmpeg,gdcm,halide,ipp,jasper,jpeg,nonfree,openexr,opengl,openmp,ovis,png,qt,sfm,tbb,tiff,vtk,webp,world]:x86-windows...
-- Using cached C:/vcpkg/downloads/opencv-opencv-4.1.1.tar.gz
-- Using source at C:/vcpkg/buildtrees/opencv4/src/4.1.1-d4651a36c2
-- Using cached C:/vcpkg/downloads/opencv-opencv_contrib-4.1.1.tar.gz
-- Using source at C:/vcpkg/buildtrees/opencv4/src/4.1.1-521dd00bd2
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/0ea90e7a8f3f7876d450e4149c97c74f-boostdesc_bgm.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/232c966b13651bd0e46a1497b0852191-boostdesc_bgm_bi.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/324426a24fa56ad9c5b8e3e0b3e5303e-boostdesc_bgm_hd.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/202e1b3e9fec871b04da31f7f016679f-boostdesc_binboost_064.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/98ea99d399965c03d555cef3ea502a0b-boostdesc_binboost_128.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/e6dcfa9f647779eb1ce446a8d759b6ea-boostdesc_binboost_256.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/boostdesc/0ae0675534aa318d9668f2a179c2a052-boostdesc_lbgm.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/e8d0dcd54d1bcfdc29203d011a797179-vgg_generated_48.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/7126a5d9a8884ebca5aea5d63d677225-vgg_generated_64.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/7cd47228edec52b6d82f46511af325c5-vgg_generated_80.i
-- Using cached C:/vcpkg/downloads/opencv-cache/xfeatures2d/vgg/151805e03568c9f490a5e3a872777b75-vgg_generated_120.i
-- Using cached C:/vcpkg/downloads/opencv-cache/data/7505c44ca4eb54b4ab1e4777cb96ac05-face_landmark_model.dat
-- Using cached C:/vcpkg/downloads/opencv-cache/tiny_dnn/adb1c512e09ca2c7a6faef36f9c53e59-v1.0.0a3.tar.gz
-- Using cached C:/vcpkg/downloads/opencv-cache/ippicv/0157251a2eb9cd63a3ebc7eed0f3e59e-ippicv_2019_win_ia32_20180723_general.zip
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_fixup_cmake_targets.cmake:98 (message):
  'C:/vcpkg/packages/opencv4_x86-windows/debug/share/opencv' does not exist.
Call Stack (most recent call first):
  ports/opencv4/portfile.cmake:318 (vcpkg_fixup_cmake_targets)
  scripts/ports.cmake:85 (include)


Error: Building package opencv4:x86-windows failed with: BUILD_FAILED
```

**Additional context**
Retry with clean directories doesn't work either.

**Comment by PhoebeHui** [comment] 2019-08-30 03:19
@tan-wei, this issue should fix by vcpkg latest commit [9e68729b](https://github.com/microsoft/vcpkg/commit/9e68729bb6b62537314c7ab315c2dcf6dc2476b0), could you get latest vcpkg source and execute bootstap-vcpkg.bat, and build opencv4 again? I verified, everything build successfully for me with latest commit.

**Comment by tan-wei** [comment] 2019-08-30 03:24
@PhoebeHui OK, I'll try it now. If fixed I'll close the issue.

**Comment by tan-wei** [comment] 2019-08-30 04:09
@PhoebeHui Oops, something else happens, maybe related with the fearture `qt`:
[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3558235/install-x86-windows-dbg-out.log)
Actully, I've met this issue several days before, so I update `vcpkg` and rebuild `qt5`. I can confirm that without feature `qt`, it will success. However, this time the same issue occurs.

I can see lots of link errors with `qt` in the log file. So what can I do to fix this? Thanks!

**Comment by cenit** [comment] 2019-08-31 06:41
Qt is problematic at the moment, there are many PR trying to fix it. Look for #7667
I hope that the qt feature will be fixed when that will land

**Comment by tan-wei** [comment] 2019-08-31 10:14
@cenit OK, maybe I should wait for some days after `qt` is update to 5.12.4

**Comment by Neumann-A** [comment] 2019-09-04 18:44
hmm i see that link line:

`-LIBPATH:C:\vcpkg\installed\x86-windows\lib opengl32.lib glu32.lib 3rdparty\ippicv\ippicv_win\icv\lib\ia32\ippicvmt.lib C:\vcpkg\installed\x86-windows\debug\lib\Halide.lib C:\vcpkg\installed\x86-windows\debug\lib\aded.lib C:\vcpkg\installed\x86-windows\debug\lib\zlibd.lib C:\vcpkg\installed\x86-windows\debug\lib\jpegd.lib C:\vcpkg\installed\x86-windows\debug\lib\webpd.lib C:\vcpkg\installed\x86-windows\debug\lib\webpdecoderd.lib C:\vcpkg\installed\x86-windows\debug\lib\webpdemuxd.lib C:\vcpkg\installed\x86-windows\debug\lib\libwebpmuxd.lib C:\vcpkg\installed\x86-windows\debug\lib\libpng16d.lib C:\vcpkg\installed\x86-windows\debug\lib\zlibd.lib C:\vcpkg\installed\x86-windows\debug\lib\gdcmMSFF.lib C:\vcpkg\installed\x86-windows\debug\lib\tiffd.lib C:\vcpkg\installed\x86-windows\debug\lib\lzmad.lib C:\vcpkg\installed\x86-windows\debug\lib\jpegd.lib C:\vcpkg\installed\x86-windows\debug\lib\zlibd.lib C:\vcpkg\installed\x86-windows\debug\lib\jasperd.lib C:\vcpkg\installed\x86-windows\debug\lib\jpegd.lib C:\vcpkg\installed\x86-windows\debug\lib\Half-2_3_d.lib C:\vcpkg\installed\x86-windows\debug\lib\Iex-2_3_d.lib C:\vcpkg\installed\x86-windows\debug\lib\Imath-2_3_d.lib C:\vcpkg\installed\x86-windows\debug\lib\IlmImf-2_3_d.lib C:\vcpkg\installed\x86-windows\debug\lib\IlmThread-2_3_d.lib comctl32.lib gdi32.lib ole32.lib setupapi.lib ws2_32.lib C:\vcpkg\installed\x86-windows\debug\lib\Qt5Testd.lib C:\vcpkg\installed\x86-windows\debug\lib\Qt5Concurrentd.lib C:\vcpkg\installed\x86-windows\debug\lib\Qt5OpenGLd.lib C:\vcpkg\installed\x86-windows\debug\lib\zlibd.lib C:\vcpkg\installed\x86-windows\debug\lib\Halide.lib C:\vcpkg\installed\x86-windows\lib\hdf5.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\glew32d.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkInteractionStyle-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkFiltersExtraction-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkFiltersStatistics-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkImagingFourier-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkRenderingLOD-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkFiltersModeling-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkIOPLY-8.2.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\double-conversion.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\lz4.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\lz4d.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\lzma.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\zlib.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\zlibd.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkFiltersTexture-8.2.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\freetype.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\freetyped.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkIOExport-8.2.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\jpeg.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\jpegd.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\libpng16.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\libpng16d.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\tiff.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\tiffd.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkIOXML-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkIOXMLParser-8.2.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\expat.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkRenderingContext2D-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkRenderingGL2PSOpenGL2-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkgl2ps-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkIOGeometry-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkIOLegacy-8.2.lib 3rdparty\lib\quircd.lib C:\vcpkg\installed\x86-windows\debug\lib\OgreBites_d.lib C:\vcpkg\installed\x86-windows\debug\lib\OgreHLMS_d.lib C:\vcpkg\installed\x86-windows\debug\lib\OgreMeshLodGenerator_d.lib C:\vcpkg\installed\x86-windows\debug\lib\OgreOverlay_d.lib C:\vcpkg\installed\x86-windows\debug\lib\OgreProperty_d.lib C:\vcpkg\installed\x86-windows\debug\lib\OgreRTShaderSystem_d.lib C:\vcpkg\installed\x86-windows\debug\lib\OgreTerrain_d.lib C:\vcpkg\installed\x86-windows\debug\lib\OgreVolume_d.lib C:\vcpkg\installed\x86-windows\debug\lib\jpegd.lib C:\vcpkg\installed\x86-windows\debug\lib\webpd.lib C:\vcpkg\installed\x86-windows\debug\lib\webpdecoderd.lib C:\vcpkg\installed\x86-windows\debug\lib\webpdemuxd.lib C:\vcpkg\installed\x86-windows\debug\lib\libwebpmuxd.lib C:\vcpkg\installed\x86-windows\debug\lib\tiffd.lib C:\vcpkg\installed\x86-windows\debug\lib\lzmad.lib C:\vcpkg\installed\x86-windows\debug\lib\jasperd.lib C:\vcpkg\installed\x86-windows\debug\lib\Half-2_3_d.lib C:\vcpkg\installed\x86-windows\debug\lib\Iex-2_3_d.lib C:\vcpkg\installed\x86-windows\debug\lib\Imath-2_3_d.lib C:\vcpkg\installed\x86-windows\debug\lib\IlmImf-2_3_d.lib C:\vcpkg\installed\x86-windows\debug\lib\IlmThread-2_3_d.lib gdi32.lib ole32.lib setupapi.lib C:\vcpkg\installed\x86-windows\lib\hdf5.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\glew32d.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\double-conversion.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\lz4.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\lz4d.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\lzma.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\zlib.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\zlibd.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\freetype.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\freetyped.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\jpeg.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\jpegd.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\libpng16.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\libpng16d.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\tiff.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\debug\lib\tiffd.lib C:\vcpkg\installed\x86-windows\share\vtk\..\..\lib\expat.lib C:\vcpkg\installed\x86-windows\debug\lib\tbb_debug.lib C:\vcpkg\installed\x86-windows\debug\lib\libprotobufd.lib C:\vcpkg\installed\x86-windows\debug\lib\gdcmDICT.lib C:\vcpkg\installed\x86-windows\debug\lib\gdcmIOD.lib C:\vcpkg\installed\x86-windows\lib\expat.lib C:\vcpkg\installed\x86-windows\debug\lib\gdcmDSED.lib C:\vcpkg\installed\x86-windows\debug\lib\gdcmCommon.lib crypt32.lib C:\vcpkg\installed\x86-windows\debug\lib\gdcmjpeg8.lib C:\vcpkg\installed\x86-windows\debug\lib\gdcmjpeg12.lib C:\vcpkg\installed\x86-windows\debug\lib\gdcmjpeg16.lib C:\vcpkg\installed\x86-windows\debug\lib\openjp2.lib C:\vcpkg\installed\x86-windows\debug\lib\gdcmcharls.lib rpcrt4.lib C:\vcpkg\installed\x86-windows\debug\lib\Qt5Widgetsd.lib C:\vcpkg\installed\x86-windows\debug\lib\Qt5Guid.lib C:\vcpkg\installed\x86-windows\debug\lib\Qt5Cored.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkImagingCore-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkRenderingFreeType-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\freetyped.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkRenderingOpenGL2-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkRenderingCore-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkCommonColor-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkFiltersGeometry-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkFiltersSources-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkFiltersGeneral-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkCommonComputationalGeometry-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkFiltersCore-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\libpng16d.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkIOImage-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkDICOMParser-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkmetaio-8.2.lib comctl32.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkIOCore-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkCommonExecutionModel-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkCommonDataModel-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkCommonTransforms-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkCommonMisc-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkCommonMath-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkCommonSystem-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtkCommonCore-8.2.lib C:\vcpkg\installed\x86-windows\debug\lib\vtksys-8.2.lib Psapi.lib C:\vcpkg\installed\x86-windows\debug\lib\avformat.lib C:\vcpkg\installed\x86-windows\debug\lib\avdevice.lib C:\vcpkg\installed\x86-windows\debug\lib\avcodec.lib C:\vcpkg\installed\x86-windows\debug\lib\avutil.lib C:\vcpkg\installed\x86-windows\debug\lib\swscale.lib C:\vcpkg\installed\x86-windows\debug\lib\avfilter.lib C:\vcpkg\installed\x86-windows\debug\lib\swresample.lib C:\vcpkg\installed\x86-windows\debug\lib\zlibd.lib ws2_32.lib wsock32.lib Secur32.lib bcrypt.lib C:\vcpkg\installed\x86-windows\debug\lib\OgrePaging_d.lib C:\vcpkg\installed\x86-windows\debug\lib\manual-link\OgreMain_d.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib `

and see that  VTK will link a lot of libraries wrongly in a debug build( just search for `share\vtk\..\..\lib` in that line)

**Comment by cenit** [comment] 2019-09-04 21:13
Vtk and qt were not deeply tested features mostly because those port themselves had many problems. I fixed so many others along the road, that those were just feeling like black holes with no come back. How is your work going on with qt? I hope to be able to have qt feature working for free after you finished that. For vtk, the problem is that its dependencies are not correctly stored and for any downstream project it will forward links to both debug and release libs......

**Comment by tan-wei** [comment] 2019-09-12 00:20
@cenit Sorry for the delay. I will try it again today.

**Comment by cenit** [comment] 2019-09-13 09:50
my experience with qt is very low. I can't answer your questions as of now (but i have to learn it soon to be able to manage some projects with it). I would be glad if you could look at it in the meantime.

**Comment by Neumann-A** [comment] 2019-09-13 15:17
@tan-wei:

Just add `-DCMAKE_AUTOMOC=ON` to the  `vcpkg_configure_cmake` call in the portfile of opencv4. Should solve your problem. To be save you could also add  `-DCMAKE_AUTORCC=ON` or even `-DCMAKE_AUTOUIC=ON` depending upon if the opencv4 source tree has .qrc or .uic files. 

```
Installing package opencv4[ade,contrib,core,dnn,eigen,ffmpeg,gdcm,halide,ipp,jasper,jpeg,nonfree,openexr,opengl,openmp,png,qt,sfm,tbb,tiff,vtk,world]:x86-windows...
Installing package opencv4[ade,contrib,core,dnn,eigen,ffmpeg,gdcm,halide,ipp,jasper,jpeg,nonfree,openexr,opengl,openmp,png,qt,sfm,tbb,tiff,vtk,world]:x86-windows... done
Elapsed time for package opencv4:x86-windows: 24.61 min

Total elapsed time: 24.61 min

The package opencv4:x86-windows provides CMake targets:

    find_package(OpenCV CONFIG REQUIRED)
    # Note: 4 target(s) were omitted.
    target_link_libraries(main PRIVATE numeric multiview opencv_sfm opencv_world)
```
(i removed sdl1 ports since i cannot currently build those due to a windows SDK bug)

I let @cenit figure out when he has to add those flags to the port ;)

**Comment by cenit** [comment] 2019-09-13 17:58
Wonderful. Thanks

**Comment by tan-wei** [comment] 2019-09-14 02:06
@Neumann-A Thanks a lot!

**Comment by tan-wei** [comment] 2019-09-14 06:09
@Neumann-A I confirm that it sucess after adding the `-DCMAKE_AUTOMOC=ON`. The issue should be closed after the flag is added when feature `qt` is enabled.

By the way, for `SDL1`, there's a tiny solution described in #7535. The issue is related to the bug of the SDK indeed.

**Comment by JackBoosY** [comment] 2019-09-18 08:02
Thanks @Neumann-A  @cenit

**Closed** 2020-07-28 00:43 UTC
Labels: category:port-bug
