### ISSUE TITLE
[V8] build failure

### ISSUE THREAD

**Issue by ZRR666** [microsoft/vcpkg#26588] opened 2022-08-29 16:51 UTC
**Host Environment**
- OS: Windows10
- Compiler: VS2017 

**To Reproduce**
`./vcpkg install v8`

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: C:/src/vcpkg/downloads/tools/gn/q5ExVHmXyD34Q_Tzb-aRxsPipO-e37-csVRhVM7IJh0C/gn.exe gen C:/src/vcpkg/buildtrees/v8/x86-windows-static-dbg "--args=is_component_build=false target_cpu=\"x86\" v8_monolithic=true v8_use_external_startup_data=false use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/c/src/vcpkg/installed/x86-windows-static/debug/lib/pkgconfig\""
    Working Directory: C:/src/vcpkg/buildtrees/v8/src/a883683717-e774d37ef1.clean
    Error code: 1
    See logs for more information:
      C:\src\vcpkg\buildtrees\v8\generate-x86-windows-static-dbg-out.log
      C:\src\vcpkg\buildtrees\v8\generate-x86-windows-static-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_gn.cmake:8 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_gn.cmake:35 (z_vcpkg_configure_gn_generate)
  ports/v8/portfile.cmake:150 (vcpkg_configure_gn)
  scripts/ports.cmake:147 (include)

error: building v8:x86-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+v8
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[v8]+Build+error
Include '[v8] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: e85b5bb95 2022-08-26 (3 days ago)

You can also use the prefilled template from C:\src\vcpkg\installed\vcpkg\issue_body.md.

**Comment by ZRR666** [comment] 2022-08-29 16:58
![image](https://user-images.githubusercontent.com/41984214/187254134-4be8333d-2938-4233-8de7-837ec8de07c2.png)
![Uploading image.png…]()

**Comment by LilyWangLL** [comment] 2022-08-30 03:09
Closed as duplicate of #15351.

**Closed by LilyWangLL** 2022-08-30 03:09 UTC
Labels: category:port-bug
