### ISSUE TITLE
[graphicsmagick] Build error

### ISSUE THREAD

**Issue by ttrueb** [microsoft/vcpkg#27431] opened 2022-10-24 10:50 UTC
Package: graphicsmagick[core]:x64-windows -> 1.3.37#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.33.31630.0
-    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: 934a99dc1 2022-10-21 (2 days ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached GraphicsMagick-1.3.37-windows.7z.
-- Cleaning sources at C:/Users/truebt/vcpkg/buildtrees/graphicsmagick/src/2e465a2909-adf106de54.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/truebt/vcpkg/downloads/GraphicsMagick-1.3.37-windows.7z
-- Applying patch dynamic_bzip2.patch
-- Applying patch disable_graphicsmagick_modules.patch
-- Using source at C:/Users/truebt/vcpkg/buildtrees/graphicsmagick/src/2e465a2909-adf106de54.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: C:/Users/truebt/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j9
    Working Directory: C:/Users/truebt/vcpkg/buildtrees/graphicsmagick/x64-windows-rel
    See logs for more information:
      C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:78 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:18 (vcpkg_build_cmake)
  ports/graphicsmagick/portfile.cmake:30 (vcpkg_install_cmake)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\install-x64-windows-rel-out.log</summary>

```
[1/209] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   -DDLL -DMAGICK_IMPLEMENTATION -DWIN32 -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DLL -D_MAGICKLIB_ -D_VISUALC_ -D_WANDLIB_ -D_WIN32 -D_WIN32_WINNT=0x0501 -Dgraphicsmagick_EXPORTS -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\. -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++ -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++\lib -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\wand -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\jbig\libjbig -external:IC:\Users\truebt\GitHub\ImageConverterCpp\cmake-build-debug\vcpkg_installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\graphicsmagick.dir\coders\braille.c.obj /FdCMakeFiles\graphicsmagick.dir\ /FS -c C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\coders\braille.c
Magick lib DLL export interface
Magick module DLL export interface
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/nt_base.h(95): warning C4005: 'HAVE_FT2BUILD_H': macro redefinition
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/magick_config.h(123): note: see previous definition of 'HAVE_FT2BUILD_H'
[2/209] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   -DDLL -DMAGICK_IMPLEMENTATION -DWIN32 -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DLL -D_MAGICKLIB_ -D_VISUALC_ -D_WANDLIB_ -D_WIN32 -D_WIN32_WINNT=0x0501 -Dgraphicsmagick_EXPORTS -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\. -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++ -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++\lib -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\wand -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\jbig\libjbig -external:IC:\Users\truebt\GitHub\ImageConverterCpp\cmake-build-debug\vcpkg_installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\graphicsmagick.dir\coders\art.c.obj /FdCMakeFiles\graphicsmagick.dir\ /FS -c C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\coders\art.c
Magick lib DLL export interface
Magick module DLL export interface
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/nt_base.h(95): warning C4005: 'HAVE_FT2BUILD_H': macro redefinition
...
Skipped 754 lines
...

[150/209] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   -DDLL -DMAGICK_IMPLEMENTATION -DWIN32 -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DLL -D_MAGICKLIB_ -D_VISUALC_ -D_WANDLIB_ -D_WIN32 -D_WIN32_WINNT=0x0501 -Dgraphicsmagick_EXPORTS -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\. -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++ -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++\lib -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\wand -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\jbig\libjbig -external:IC:\Users\truebt\GitHub\ImageConverterCpp\cmake-build-debug\vcpkg_installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\graphicsmagick.dir\magick\import.c.obj /FdCMakeFiles\graphicsmagick.dir\ /FS -c C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick\import.c
Magick lib DLL export interface
Magick module DLL export interface
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/nt_base.h(95): warning C4005: 'HAVE_FT2BUILD_H': macro redefinition
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/magick_config.h(123): note: see previous definition of 'HAVE_FT2BUILD_H'
[151/209] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   -DDLL -DMAGICK_IMPLEMENTATION -DWIN32 -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DLL -D_MAGICKLIB_ -D_VISUALC_ -D_WANDLIB_ -D_WIN32 -D_WIN32_WINNT=0x0501 -Dgraphicsmagick_EXPORTS -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\. -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++ -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++\lib -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\wand -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\jbig\libjbig -external:IC:\Users\truebt\GitHub\ImageConverterCpp\cmake-build-debug\vcpkg_installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\graphicsmagick.dir\magick\magick.c.obj /FdCMakeFiles\graphicsmagick.dir\ /FS -c C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick\magick.c
Magick lib DLL export interface
Magick module DLL export interface
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/nt_base.h(95): warning C4005: 'HAVE_FT2BUILD_H': macro redefinition
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/magick_config.h(123): note: see previous definition of 'HAVE_FT2BUILD_H'
[152/209] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   -DDLL -DMAGICK_IMPLEMENTATION -DWIN32 -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DLL -D_MAGICKLIB_ -D_VISUALC_ -D_WANDLIB_ -D_WIN32 -D_WIN32_WINNT=0x0501 -Dgraphicsmagick_EXPORTS -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\. -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++ -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++\lib -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\wand -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\jbig\libjbig -external:IC:\Users\truebt\GitHub\ImageConverterCpp\cmake-build-debug\vcpkg_installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\graphicsmagick.dir\magick\module.c.obj /FdCMakeFiles\graphicsmagick.dir\ /FS -c C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick\module.c
Magick lib DLL export interface
Magick module DLL export interface
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/nt_base.h(95): warning C4005: 'HAVE_FT2BUILD_H': macro redefinition
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/magick_config.h(123): note: see previous definition of 'HAVE_FT2BUILD_H'
[153/209] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   -DDLL -DMAGICK_IMPLEMENTATION -DWIN32 -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DLL -D_MAGICKLIB_ -D_VISUALC_ -D_WANDLIB_ -D_WIN32 -D_WIN32_WINNT=0x0501 -Dgraphicsmagick_EXPORTS -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\. -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++ -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++\lib -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\wand -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\jbig\libjbig -external:IC:\Users\truebt\GitHub\ImageConverterCpp\cmake-build-debug\vcpkg_installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\graphicsmagick.dir\magick\map.c.obj /FdCMakeFiles\graphicsmagick.dir\ /FS -c C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick\map.c
Magick lib DLL export interface
Magick module DLL export interface
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/nt_base.h(95): warning C4005: 'HAVE_FT2BUILD_H': macro redefinition
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/magick_config.h(123): note: see previous definition of 'HAVE_FT2BUILD_H'
[154/209] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   -DDLL -DMAGICK_IMPLEMENTATION -DWIN32 -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DLL -D_MAGICKLIB_ -D_VISUALC_ -D_WANDLIB_ -D_WIN32 -D_WIN32_WINNT=0x0501 -Dgraphicsmagick_EXPORTS -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\. -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++ -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++\lib -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\wand -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\jbig\libjbig -external:IC:\Users\truebt\GitHub\ImageConverterCpp\cmake-build-debug\vcpkg_installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\graphicsmagick.dir\magick\log.c.obj /FdCMakeFiles\graphicsmagick.dir\ /FS -c C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick\log.c
Magick lib DLL export interface
Magick module DLL export interface
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/nt_base.h(95): warning C4005: 'HAVE_FT2BUILD_H': macro redefinition
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/magick_config.h(123): note: see previous definition of 'HAVE_FT2BUILD_H'
[155/209] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   -DDLL -DMAGICK_IMPLEMENTATION -DWIN32 -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DLL -D_MAGICKLIB_ -D_VISUALC_ -D_WANDLIB_ -D_WIN32 -D_WIN32_WINNT=0x0501 -Dgraphicsmagick_EXPORTS -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\. -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++ -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++\lib -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\wand -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\jbig\libjbig -external:IC:\Users\truebt\GitHub\ImageConverterCpp\cmake-build-debug\vcpkg_installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\graphicsmagick.dir\magick\monitor.c.obj /FdCMakeFiles\graphicsmagick.dir\ /FS -c C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick\monitor.c
Magick lib DLL export interface
Magick module DLL export interface
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/nt_base.h(95): warning C4005: 'HAVE_FT2BUILD_H': macro redefinition
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/magick_config.h(123): note: see previous definition of 'HAVE_FT2BUILD_H'
[156/209] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   -DDLL -DMAGICK_IMPLEMENTATION -DWIN32 -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DLL -D_MAGICKLIB_ -D_VISUALC_ -D_WANDLIB_ -D_WIN32 -D_WIN32_WINNT=0x0501 -Dgraphicsmagick_EXPORTS -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\. -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++ -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++\lib -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\wand -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\jbig\libjbig -external:IC:\Users\truebt\GitHub\ImageConverterCpp\cmake-build-debug\vcpkg_installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\graphicsmagick.dir\magick\montage.c.obj /FdCMakeFiles\graphicsmagick.dir\ /FS -c C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick\montage.c
Magick lib DLL export interface
Magick module DLL export interface
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/nt_base.h(95): warning C4005: 'HAVE_FT2BUILD_H': macro redefinition
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/magick_config.h(123): note: see previous definition of 'HAVE_FT2BUILD_H'
[157/209] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1433~1.316\bin\Hostx64\x64\cl.exe   -DDLL -DMAGICK_IMPLEMENTATION -DWIN32 -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_DLL -D_MAGICKLIB_ -D_VISUALC_ -D_WANDLIB_ -D_WIN32 -D_WIN32_WINNT=0x0501 -Dgraphicsmagick_EXPORTS -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\. -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++ -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\Magick++\lib -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\wand -IC:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\jbig\libjbig -external:IC:\Users\truebt\GitHub\ImageConverterCpp\cmake-build-debug\vcpkg_installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /FoCMakeFiles\graphicsmagick.dir\magick\nt_base.c.obj /FdCMakeFiles\graphicsmagick.dir\ /FS -c C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick\nt_base.c
Magick lib DLL export interface
Magick module DLL export interface
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/nt_base.h(95): warning C4005: 'HAVE_FT2BUILD_H': macro redefinition
C:\Users\truebt\vcpkg\buildtrees\graphicsmagick\src\2e465a2909-adf106de54.clean\magick/magick_config.h(123): note: see previous definition of 'HAVE_FT2BUILD_H'
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "imageconvertercpp",
  "version-string": "0.1.0",
  "dependencies": [
    "graphicsmagick"
  ]
}

```
</details>

**Comment by LilyWangLL** [comment] 2022-10-25 09:49
Thanks for posting this issue. This issue is a Visual Studio bug, we should wait for Visual Studio team fix this.
Closed as duplicate of #27170.

**Closed by LilyWangLL** 2022-10-25 09:49 UTC
Labels: depends:upstream-changes
