### ISSUE TITLE
[eigen3] Build error

### ISSUE THREAD

**Issue by croman-dev** [microsoft/vcpkg#30550] opened 2023-03-30 14:05 UTC
Package: eigen3[core]:x86-windows -> 3.4.0#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.16.27049.0
-    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: d10d511f2 2023-03-29 (14 hours ago)

**To Reproduce**

`vcpkg install opencv2`

**Failure logs**

```
-- Downloading https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz -> libeigen-eigen-3.4.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
[DEBUG] Trying to hash C:\vcpkg\downloads\libeigen-eigen-3.4.0.tar.gz.9764.part
[DEBUG] C:\vcpkg\downloads\libeigen-eigen-3.4.0.tar.gz.9764.part has hash c16161558323c340bf48d18bb28e78f45a505ea0d9579ef746c78c5513b84af92db6435dd839573cc27c8558de83ad7c25b5d57e1b74677f3022c0dc4f6d3765
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://gitlab.com/libeigen/eigen/-/archive/3.4.0/eigen-3.4.0.tar.gz
File: C:\vcpkg\downloads\libeigen-eigen-3.4.0.tar.gz.9764.part
Expected hash: ba75ecb760e32acf4ceaf27115468e65d4f77c44f8d519b5a13e7940af2c03a304ad433368cb6d55431f307c5c39e2666ab41d34442db3cf441638e51f5c3b6a
Actual hash: c16161558323c340bf48d18bb28e78f45a505ea0d9579ef746c78c5513b84af92db6435dd839573cc27c8558de83ad7c25b5d57e1b74677f3022c0dc4f6d3765
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(960): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 1090us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 1.2468441 s (1225970us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_gitlab.cmake:118 (vcpkg_download_distfile)
  ports/eigen3/portfile.cmake:3 (vcpkg_from_gitlab)
  scripts/ports.cmake:147 (include)



```

**Comment by Neumann-A** [comment] 2023-03-30 19:16
duplicate of  #30481. Should be solved now

**Closed** 2023-03-31 02:31 UTC
Labels: category:port-bug
