### ISSUE TITLE
[pkgconf] Build error on x64-windows

### ISSUE THREAD

**Issue by iJahid** [microsoft/vcpkg#39304] opened 2024-06-15 05:59 UTC
Hi
I am unable to install vcpkg for darknet yolov4

 .\vcpkg.exe install darknet[opencv-base]:x64-windows

when i run the command on pwoershell it got stuck on ninja
errors :

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/yolo/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe install -v
    Working Directory: D:/yolo/vcpkg/buildtrees/pkgconf/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\yolo\vcpkg\buildtrees\pkgconf\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-tool-meson/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/pkgconf/portfile.cmake:67 (vcpkg_install_meson)
  scripts/ports.cmake:175 (include)

please somebody help me

**Comment by LilyWangLL** [comment] 2024-06-17 04:02
Please provide the error log: _D:\yolo\vcpkg\buildtrees\pkgconf\package-x64-windows-dbg-out.log_.

**Comment by LilyWangLL** [comment] 2024-06-18 03:03
Closed as duplicate of https://github.com/microsoft/vcpkg/issues/33052.

**Closed by LilyWangLL** 2024-06-18 03:03 UTC
Labels: requires:more-information
