### ISSUE TITLE
[pcl] build failure

### ISSUE THREAD

**Issue by Camuvingian** [microsoft/vcpkg#12294] opened 2020-07-06 21:02 UTC
**Host Environment**
- OS: Windows
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x86

**To Reproduce**
`./vcpkg install pcl`

**Failure logs** 
PS F:\C++Libraries\Vcpkg\vcpkg-master> .\vcpkg install pcl
Computing installation plan...
The following packages will be built and installed:
  * eigen3[core]:x86-windows
  * expat[core]:x86-windows
  * flann[core]:x86-windows
  * freetype[bzip2,core,png]:x86-windows
  * glew[core]:x86-windows
  * hdf5[core,szip,zlib]:x86-windows
  * jsoncpp[core]:x86-windows
  * libharu[core,notiffsymbols]:x86-windows
  * libiconv[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * libogg[core]:x86-windows
  * libpng[core]:x86-windows
  * libtheora[core]:x86-windows
  * libxml2[core]:x86-windows
  * lz4[core]:x86-windows
  * netcdf-c[core]:x86-windows
    pcl[core]:x86-windows
  * pegtl-2[core]:x86-windows
  * proj4[core,database]:x86-windows
  * pugixml[core]:x86-windows
  * qhull[core]:x86-windows
  * sqlite3[core,tool]:x86-windows
  * szip[core]:x86-windows
  * tiff[core]:x86-windows
  * utfcpp[core]:x86-windows
  * vtk[core]:x86-windows
  * xxhash[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/27: eigen3:x86-windows
Building package eigen3[core]:x86-windows...
CMake Warning at scripts/cmake/vcpkg_buildpath_length_warning.cmake:4 (message):
  eigen3's buildsystem uses very long paths and may fail on your system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  ports/eigen3/portfile.cmake:3 (vcpkg_buildpath_length_warning)
  scripts/ports.cmake:76 (include)

-- Using cached F:/C++Libraries/Vcpkg/vcpkg-master/downloads/libeigen-eigen-3.3.7.tar.gz
-- Using source at F:/C++Libraries/Vcpkg/vcpkg-master/buildtrees/eigen3/src/3.3.7-c7b55a8243
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Fixing pkgconfig
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:207 (list):
  list sub-command FILTER, mode REGEX failed to compile regex
  "F:/C++Libraries/Vcpkg/vcpkg-master/packages/eigen3_x86-windows/debug/".
Call Stack (most recent call first):
  ports/eigen3/portfile.cmake:36 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:76 (include)

RegularExpression::compile(): Nested *?+.
RegularExpression::compile(): Error in compile.
Error: Building package eigen3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: eigen3:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Additional context**
N/A

**Comment by Camuvingian** [comment] 2020-07-06 21:45
Work around was to comment out the `vcpkg_fixup_pkgconfig()` call on line 28 or ports\eigen3\portfile.cmake as shown below. I doubt this would be deemed a fix, but in any case, for my purposes it gets around the problem. 

```
include(vcpkg_common_functions)

vcpkg_buildpath_length_warning(37)

vcpkg_from_gitlab(
    GITLAB_URL https://gitlab.com
    OUT_SOURCE_PATH SOURCE_PATH
    REPO libeigen/eigen
    REF 3.3.7
    SHA512 4cc3717b9cbe78335e05f724919497214edd482d4812aeb1a9fd6da5b3f6d1b194bb93ed0dab9e734b4334a5b88e8f8c339c43c1b2044332286ef5e758f9ecf4
    HEAD_REF master
)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DBUILD_TESTING=OFF
        -DEIGEN_BUILD_PKGCONFIG=ON
    OPTIONS_RELEASE
        -DCMAKEPACKAGE_INSTALL_DIR=${CURRENT_PACKAGES_DIR}/share/eigen3
        -DPKGCONFIG_INSTALL_DIR=${CURRENT_PACKAGES_DIR}/lib/pkgconfig
    OPTIONS_DEBUG
        -DCMAKEPACKAGE_INSTALL_DIR=${CURRENT_PACKAGES_DIR}/debug/share/eigen3
        -DPKGCONFIG_INSTALL_DIR=${CURRENT_PACKAGES_DIR}/debug/lib/pkgconfig
)

vcpkg_install_cmake()

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include ${CURRENT_PACKAGES_DIR}/debug/share)

file(READ "${CURRENT_PACKAGES_DIR}/share/eigen3/Eigen3Targets.cmake" EIGEN_TARGETS)
string(REPLACE "set(_IMPORT_PREFIX " "get_filename_component(_IMPORT_PREFIX \"\${CMAKE_CURRENT_LIST_DIR}/../..\" ABSOLUTE) #" EIGEN_TARGETS "${EIGEN_TARGETS}")
file(WRITE "${CURRENT_PACKAGES_DIR}/share/eigen3/Eigen3Targets.cmake" "${EIGEN_TARGETS}")

#vcpkg_fixup_pkgconfig()

file(GLOB INCLUDES ${CURRENT_PACKAGES_DIR}/include/eigen3/*)
# Copy the eigen header files to conventional location for user-wide MSBuild integration
file(COPY ${INCLUDES} DESTINATION ${CURRENT_PACKAGES_DIR}/include)

# Put the licence file where vcpkg expects it
file(COPY ${SOURCE_PATH}/COPYING.README DESTINATION ${CURRENT_PACKAGES_DIR}/share/eigen3)
file(RENAME ${CURRENT_PACKAGES_DIR}/share/eigen3/COPYING.README ${CURRENT_PACKAGES_DIR}/share/eigen3/copyright)
```

**Comment by BillyONeal** [comment] 2020-07-07 02:22
I observe that the most recent attempt by our CI to build this succeeded: https://dev.azure.com/vcpkg/public/_build/results?buildId=39820

```
Starting package 980/1312: pcl:x86-windows
Building package pcl[core]:x86-windows...
-- Downloading https://github.com/PointCloudLibrary/pcl/archive/pcl-1.9.1.tar.gz...
-- Extracting source D:/downloads/PointCloudLibrary-pcl-pcl-1.9.1.tar.gz
-- Applying patch pcl_utils.patch
-- Applying patch pcl_config.patch
-- Applying patch use_flann_targets.patch
-- Applying patch boost-1.70.patch
-- Applying patch cuda_10_1.patch
-- Applying patch use_target_link_libraries_in_pclconfig.patch
-- Applying patch fix-link-libpng.patch
-- Applying patch boost-1.73.patch
-- Using source at D:/buildtrees/pcl/src/pcl-1.9.1-f2ec88a858
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: D:/packages/pcl_x86-windows/share/pcl/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: W:\d9\d9506db43f8043034921f34abc1ec6ac8bc50219.zip
Building package pcl[core]:x86-windows... done
Installing package pcl[core]:x86-windows...
Installing package pcl[core]:x86-windows... done
Elapsed time for package pcl:x86-windows: 10.13 min
```

There may be races in the pcl port?

**Comment by LilyWangL** [comment] 2020-07-07 08:26
Thanks for posting this issue. I can't reproduce this issue locally, I can install `eigen3` successfully. PR #11550 will fix some bug of function `vcpkg_fixup_pkgconfig()`, please waiting for PR #11550 merged and rebuild `eigen3` again.

**Comment by LilyWangL** [comment] 2020-08-20 02:34
Pinging @Camuvingian for response, does this issue still occur?

**Comment by Camuvingian** [comment] 2020-08-20 07:59
> Pinging @Camuvingian for response, does this issue still occur?

I don’t know. The fix I put in place worked, so I moved on...

**Comment by LilyWangL** [comment] 2020-08-20 09:14
Could you use the latest vcpkg to install pcl? If this issue can not reproduce, I will close this issue.

**Comment by LilyWangL** [comment] 2020-09-09 09:49
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Closed by LilyWangL** 2020-09-09 09:49 UTC
Labels: requires:repro
