### ISSUE TITLE
vcpkg upgrade error

### ISSUE THREAD

**Issue by camcc591** [microsoft/vcpkg#33263] opened 2023-08-18 23:25 UTC
I received an error while upgrading vcpkg for gmp. The text below is the end of the PowerShell output.

-- Generating configure for x64-windows
-- Finished generating configure for x64-windows
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Installing x64-windows-dbg
-- Building x64-windows-rel
-- Installing x64-windows-rel
-- Fixing pkgconfig file: C:/dev/vcpkg/packages/gmp_x64-windows/lib/pkgconfig/gmp.pc
-- Fixing pkgconfig file: C:/dev/vcpkg/packages/gmp_x64-windows/lib/pkgconfig/gmpxx.pc
-- Fixing pkgconfig file: C:/dev/vcpkg/packages/gmp_x64-windows/debug/lib/pkgconfig/gmp.pc
-- Fixing pkgconfig file: C:/dev/vcpkg/packages/gmp_x64-windows/debug/lib/pkgconfig/gmpxx.pc
-- Installing: C:/dev/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-bases.exe
-- Installing: C:/dev/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-fac.exe
-- Installing: C:/dev/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-fib.exe
-- Installing: C:/dev/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-jacobitab.exe
-- Installing: C:/dev/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-psqr.exe
-- Installing: C:/dev/vcpkg/packages/gmp_x64-windows/manual-tools/gmp/gen-trialdivtab.exe
-- Installing: C:/dev/vcpkg/packages/gmp_x64-windows/share/gmp/usage
-- Performing post-build validation
internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(888): Value was null
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.
PS C:\dev\vcpkg>

Below are the steps I used to get here.
1.	open a PowerShell window
2.	cd c:\dev\vcpkg
3.	PS> git pull
4.	PS> .\vcpkg update
5.	if updates are available
a.	(optional) PS> .\vcpkg upgrade
b.	PS> .\vcpkg upgrade --no-dry-run
c.	PS> .\vcpkg install gmp

I noticed the internal error message refers to drive d. My d-drive is a recovery partition on my hard drive. I don't understand why the script would be accessing that drive.

**Comment by camcc591** [comment] 2023-08-18 23:28
Sorry. The steps to reproduce have an extra line. The error occurred with PS> .\vcpkg upgrade --no-dry-run

**Comment by autoantwort** [comment] 2023-08-19 14:33
Please update your vcpkg version :)

**Comment by JonLiu1993** [comment] 2023-08-21 07:58
Duplicate of https://github.com/microsoft/vcpkg/issues/31908

**Closed by JonLiu1993** 2023-08-21 07:58 UTC
Labels: category:vcpkg-bug
