### ISSUE TITLE
[<sentencepiece>] build failure

### ISSUE THREAD

**Issue by gaoshiping** [microsoft/vcpkg#21128] opened 2021-11-02 08:14 UTC
**Host Environment**
- OS: Windows 10 19042.1320
- Compiler: revision

**To Reproduce**
`./vcpkg install sentencepiece`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    sentencepiece[core]:x86-windows -> 0.1.95#1
Detecting compiler hash for triplet x86-windows...
Restored 0 packages from C:\Users\ShiPing Gao\AppData\Local\vcpkg\archives in 222.8 us. Use --debug to see more details.
Starting package 1/1: sentencepiece:x86-windows
Building package sentencepiece[core]:x86-windows...
-- Note: sentencepiece only supports static library linkage. Building static library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:70 (message):
  sentencepiece only supports static crt linkage
Call Stack (most recent call first):
  ports/sentencepiece/portfile.cmake:2 (vcpkg_check_linkage)
  scripts/ports.cmake:142 (include)

Error: Building package sentencepiece:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: sentencepiece[core]:x86-windows -> 0.1.95#1
  vcpkg version: 2021-10-25-b4bff9afacafb0a234a8f20fd6451b2362c0f9a0
  vcpkg-tool version: 35443ee27 2021-11-01 (10 hours ago)

Additionally, attach any relevant sections from the log files above.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by NancyLi1013** [comment] 2021-11-04 09:14
Hi @gaoshiping 

Thanks for posting this issue. Since currently `sentencepiece ` only supports static CRT linkage. The problem you encountered is expected.

https://github.com/microsoft/vcpkg/blob/40a0fb232833dbc1b526394929f10b71627c2269/ports/sentencepiece/portfile.cmake#L1-L3

**Comment by NancyLi1013** [comment] 2021-11-18 07:46
Closing this issue since it is intended behavior.

**Closed by NancyLi1013** 2021-11-18 07:46 UTC
Labels: category:question
