### ISSUE TITLE
linker error on rocksdb with gcc

### ISSUE THREAD

**Issue by gocarlos** [microsoft/vcpkg#5051] opened 2018-12-29 18:06 UTC
using gcc 6.5 on ubuntu 18.04
```cmake
find_package(RocksDB CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME}
                      PRIVATE RocksDB::rocksdb
                              RocksDB::rocksdb-shared)
```

```
/home/ladmin/vcpkg/installed/x64-linux/debug/lib/librocksdbd.a(format.cc.o): In function `rocksdb::Zlib_Uncompress(rocksdb::UncompressionContext const&, char const*, unsigned long, int*, unsigned int, int)':
/home/ladmin/vcpkg/buildtrees/rocksdb/src/v5.15.10-2d53c7e6ef/util/compression.h:526: undefined reference to `inflateInit2_'
/home/ladmin/vcpkg/buildtrees/rocksdb/src/v5.15.10-2d53c7e6ef/util/compression.h:535: undefined reference to `inflateSetDictionary'
/home/ladmin/vcpkg/buildtrees/rocksdb/src/v5.15.10-2d53c7e6ef/util/compression.h:551: undefined reference to `inflate'
/home/ladmin/vcpkg/buildtrees/rocksdb/src/v5.15.10-2d53c7e6ef/util/compression.h:577: undefined reference to `inflateEnd'
/home/ladmin/vcpkg/buildtrees/rocksdb/src/v5.15.10-2d53c7e6ef/util/compression.h:585: undefined reference to `inflateEnd'
/home/ladmin/vcpkg/installed/x64-linux/debug/lib/librocksdbd.a(block_based_table_builder.cc.o): In function `rocksdb::Zlib_Compress(rocksdb::CompressionContext const&, unsigned int, char const*, unsigned long, std::__cxx11::basic_string<char,std::char_traits<char>, std::allocator<char> >*)':
/home/ladmin/vcpkg/buildtrees/rocksdb/src/v5.15.10-2d53c7e6ef/util/compression.h:445: undefined reference to `deflateInit2_'
/home/ladmin/vcpkg/buildtrees/rocksdb/src/v5.15.10-2d53c7e6ef/util/compression.h:455: undefined reference to `deflateSetDictionary'
/home/ladmin/vcpkg/buildtrees/rocksdb/src/v5.15.10-2d53c7e6ef/util/compression.h:457: undefined reference to `deflateEnd'
/home/ladmin/vcpkg/buildtrees/rocksdb/src/v5.15.10-2d53c7e6ef/util/compression.h:471: undefined reference to `deflate'
/home/ladmin/vcpkg/buildtrees/rocksdb/src/v5.15.10-2d53c7e6ef/util/compression.h:480: undefined reference to `deflateEnd'
collect2: error: ld returned 1 exit status
CMakeFiles/runtime_db.dir/build.make:87: recipe for target 'runtime_db' failed
make[2]: *** [runtime_db] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/runtime_db.dir/all' failed
make[1]: *** [CMakeFiles/runtime_db.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by NancyLi1013** [comment] 2020-03-09 13:27
Hi @gocarlos 
Thanks for posting this issue.
Sorry for the late reply.
`rocksdb `has been updated. Could you please update vcpkg and try to build it again?

**Comment by NancyLi1013** [comment] 2020-04-09 06:00
This issue should be fixed now.
I cannot reproduce this on both  Ubuntu 18.04 and  Ubuntu 16.04.

**Closed by NancyLi1013** 2020-04-09 06:00 UTC
