### ISSUE TITLE
support for Qt VS Tools?

### ISSUE THREAD

**Issue by star-e** [microsoft/vcpkg#2643] opened 2018-01-25 05:33 UTC
Is there any way to use Qt VS Tools with vcpkg-built qt binaries? 
It seems that files built with qmake and vcpkg have different folder structures. Qt VS Tools cannot find qmake.exe and other required files when using vcpkg built ones.
My projects use Qt VS Tools intensively. Without it, I don't know how to use qt (moc, qt designer, etc) on windows. :(

I have successfully built and installed all qt 5.9.2 modules(x64-windows), on Windows 10 machine, using VS 2017 15.5.4, vcpkg 0.0.103.

**Comment by glachancecmaisonneuve** [comment] 2018-01-25 07:09
vcpkg gives you everything you need to work with the tools as they are installed, which is the qt_release.conf and qt_debug.conf files that are provided in vcpkg_root/installed/x64-windows/tools folder.  

The problem is that neither QtDesigner nor QtVsTools are able to handle a qt.conf file.  The solution is to use Qt's own redistribuable package, or to use anything at all besides the Qt graphical tools to build (command line qmake, msbuild within or out of visual studio, cmake, ninja, jom, etc.) 

You will want to close this issue here as there is nothing more to be done on vcpkg's side.  You should open an issue with Qt and tell them to fix their tools.

**Comment by Zhou-Zhenglong** [comment] 2018-01-25 08:22
Thanks! I got it.

**Comment by kthulhu** [comment] 2018-08-30 22:05
Excuse me for bringing that up again, but this qt.conf doesn't work for me on Windows.
Can anyone share his setup of vcpkg/Qt5.11.1 or close versions?
VS Tools are just erroring over and over with '..\Vcpkg\installed\x64-windows\tools\qt5\bin\qmake.exe cannot be found'.
Any help would be appreciated.

**Comment by studiosi** [comment] 2018-09-06 19:14
I have found that the tools try to add a /bin/ to the folder you specify so you need to create a bin folder inside the {whatever}/tools/qt5 and copy all the files there. Then it will complain about not having a qmake.conf file inside such bin folder, and then it is trying to find a qmake.conf file in the {whatever}/mkspecs/win32-msvc. If you create the file there, it causes an error, object reference not set to an instance of an object. That's as far as I have been able to go so far.

**Comment by kthulhu** [comment] 2018-09-08 02:41
In Vcpkg\installed\x64-windows\tools\qt5\
I see qt_debug.conf  and qt_release.conf which are remind me the one posted above.
Assuming it worked for that author of that message, and that maybe someone made a fix for that and put those files in there, there's a question: how to make them work?

Or maybe it's worth to contact Qt VSTools guys and ask them if they can fix that.
Not sure options do we have here.

**Comment by nedsociety** [comment] 2018-12-25 11:33
> Or maybe it's worth to contact Qt VSTools guys and ask them if they can just support vcpkg build.
> Not sure what options do we have here.

No. This issue should be reopened. [Qt devs have decided to set it as non-issue on their end.](https://bugreports.qt.io/browse/QTVSADDINBUG-545) We don't have much choice but to set directory structures right.

**Comment by Zhou-Zhenglong** [comment] 2019-01-25 02:17
We may need vcpkg supporting QtVsTools directory structure, or providing us some way to change the deployment methods.
[https://bugreports.qt.io/browse/QTVSADDINBUG-545](url)

**Comment by Neumann-A** [comment] 2020-04-27 10:47
@JackBoosY Please add blocked by upstream to this issue. I played I bit with it and only Release build can currently be correctly setup using the QtVsTools.

**Comment by dahubley** [comment] 2020-09-22 12:24
I'm wondering if there has been any movement on this. Seems the qt vs tool people have made it so the tool will work fairly easily with vcpkg. Works fine in release but in debug I keep getting linker errors related QT5Networkd.lib and libcrypto.lib. Any thoughts?

![image](https://user-images.githubusercontent.com/35534426/93881478-5abf7b80-fcb5-11ea-90bf-ec02f4699a5d.png)

**Comment by lukadriel7** [comment] 2020-10-17 15:18
Hello, from what I get as error, it seems that the qt vs tool assume the debug libraries are located in the same directory as the release ones. The solution would be to change the path for the debug libs

**Comment by evakili** [comment] 2020-10-27 18:05
@lukadriel7 Could you provide some details about your workaround?

**Comment by dahubley** [comment] 2020-10-27 18:14
@lukadriel7 @evakili If you use the debug versions of the binaries for debug builds they automatically know where to find the debug binaries. QT appears to have resolved this.

**Comment by evakili** [comment] 2020-10-28 15:55
@dahubley Where you tell VS tools to use debug binaries?

**Comment by dahubley** [comment] 2020-10-28 16:07
![image](https://user-images.githubusercontent.com/35534426/97463371-70603a80-191e-11eb-8889-00dc2dc091d1.png)
You can specify the binaries on this screen

**Comment by evakili** [comment] 2020-10-28 16:11
@dahubley  I try this before, but the following error occurred: `C:\Users\____\AppData\Local\QtMsBuild\qt_globals.targets(268,5): error MSB4181: The "QtRunWork" task returned false but did not log an error.`

**Comment by lukadriel7** [comment] 2020-10-29 14:13
@evakili This is how I did:

1. Open your project property manager tab
2. Add a new property sheet for the Debug and Release configuration of your project
3. Open the property sheet and add a new macro containing the paths to the libraries (Debug libs for debug config, release libs for release config), save and exit
4. Go to your project properties(all configurations) -> linker -> input and add your newly created macro as well as other dependencies(user32.lib, kernel32.lib, ...)
5. uncheck inherit from parent or default project
6. save your config and enjoy compiling in debug mode

**Comment by dahubley** [comment] 2020-10-29 17:23
A actually think this issue is closed?

**Comment by evakili** [comment] 2020-10-29 19:45
IMO the above workarounds are not real solutions, but some hacks. So this issue should be kept open till the integration works without handy hacks.
Also, the above workarounds have limitations in other scenarios, like debugging, using Qt tools in build events, and etc.

**Comment by mediabuff** [comment] 2020-12-15 17:03
You may set QMake_QT_INSTALL_LIBS_ = " ....\vcpkg\installed\x86-windows\debug\lib" in your project file.

Has to go before 'qt.props' - so place it after 

 <Import Project="$(VCTargetsPath)\Microsoft.Cpp.props" />

**Comment by JackBoosY** [comment] 2022-07-29 07:04
Close this PR until upstream fixes this.

**Closed by JackBoosY** 2022-07-29 07:04 UTC
Labels: category:port-feature, depends:upstream-changes

**Comment by wluter** [comment] 2023-06-19 17:05
After a lot of frustration I was able to get my environment to build a dynamic Debug configuration. To help others here is my situation:

1. I wanted both dynamic and static builds for both debug and release.
2. I also wanted to us Qt Visual Studio tools and vcpkg with Visual Studio 2022.
3. I needed Qt5 libraries built in vcpkg.

I found that dynamic-release and static-release built and worked fine but dynamic-debug and static-debug needed tweaks.

For static-debug the tweak was as listed above: Change "Qt Project Settings" -> "Paths" -> "Qt Binaries" from bin to Debug/bin.

For dynamic debug you do the same as static-debug but if you use the resource compiler or the user interface compiler (rcc.exe or uic.exe) you must also add to the system path the path where the vcpkg debug dlls are located which is <vcpkg export bundle location>\installed\x64-windows\debug\bin

**Comment by xroot3** [comment] 2023-11-03 02:18
This issue is closed?or just soveld in qt5 but not qt6?
I install PCL via vcpkg ,and as its dependency,qt6 was installed automatic,but I Failed to create a new qt project.The error info show as the first picture.

When I open the .vcxproj file I created,the error info show as the second picture.
![1](https://github.com/microsoft/vcpkg/assets/68690994/514f15b4-a107-4871-a558-6402576bd52a)

When I open the .vcxproj file I created,the error info show as the second picture.
![2](https://github.com/microsoft/vcpkg/assets/68690994/45b1371a-e749-4d85-bd3e-ea67e60db9a0)

Then I  found there was no mkspecs folder in the Qt6 folder which is exist bin folder.

**Comment by wluter** [comment] 2023-11-03 13:07
I would not say it is solved but the work-around works for me. There is something confusing about Qt5 + Qt Visual Studio tools and the overlap of using Qt5 by vcpkg versus Qt5 by separate library (not vcpkg). Here are the main problems I faced:

1. If you use vcpkg + manifest file then updates to vcpkg will rebuild any time there is a Qt5 update/patch/fix. This takes > 2 hours on my system to rebuild.
2. It is confusing/not easy with vcpkg to freeze a certain commit or version to hold Qt5 and stop rebuilding.
3. The combination of Qt5 and vcpkg is clumsy to use and you have to find the right tweaks of Qt5 to get dynamic/static along with release/debug configurations.

So now I build Qt5 using vcpkg command line and export to a folder for both static and dynamic. Then I configure VS .props files for the Qt5 version using Qt Visual Studio tools and point to the release/debug and static/dynamic export builds. But I still have to configure the .props files properly to point at the correct configuration (Release/Build)
