### ISSUE TITLE
vcpkg upgrade error

### ISSUE THREAD

**Issue by hros** [microsoft/vcpkg#32189] opened 2023-06-23 15:40 UTC
step to reproduce:
```
git pull
./bootstrap-vcpkg.sh
vcpkg upgrade --no-dry-run
```

packages upgraded:
```
The following packages will be rebuilt:
  * icu[core,tools]:x64-linux -> 73.1
```
At the end:
```
-- Performing post-build validation
internal error: /mnt/vss/_work/1/s/src/vcpkg/commands.build.cpp(888): Value was null
```

**Comment by autoantwort** [comment] 2023-06-24 00:53
Duplicate of https://github.com/microsoft/vcpkg/issues/31908

**Closed** 2023-06-25 03:11 UTC
Labels: category:vcpkg-bug, requires:vcpkg-tool-release
