### ISSUE TITLE
[libtorch] update to 2.1.2

### ISSUE THREAD

**Issue by Arech** [microsoft/vcpkg#35741] opened 2023-12-17 08:51 UTC
### Library name

libtorch

### New version number

2.1.2

### Other information that may be useful (release notes, etc...)

Hi, I was wondering are there plans to update `libtorch` part of [pytorch](https://pytorch.org/) library to the [latest 2.* branch](https://github.com/pytorch/pytorch/releases)? Current port uses [v1.12.1](https://github.com/microsoft/vcpkg/blob/0e47c1985273129e4d0ee52ff73bed9125555de8/ports/libtorch/vcpkg.json#L3C15-L3C21) which is almost [1.5 years old](https://github.com/pytorch/pytorch/tree/v1.12.1) and it's really a lot in a such dynamic field as Machine Learning.

**Comment by LilyWangLL** [comment] 2024-01-03 06:03
Closed as duplicate of #30224.

**Closed by LilyWangLL** 2024-01-03 06:03 UTC
Labels: category:port-update
