### ISSUE TITLE
building gtk3:x64-linux failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by clearspring987** [microsoft/vcpkg#29744] opened 2023-02-20 03:08 UTC
**Host Environment**

- OS: ubuntu1604
- Compiler: gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~16.04)

**To Reproduce**

`./vcpkg install gtk3`

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
  * at-spi2-atk[core]:x64-linux -> 2.38.0
  * at-spi2-core[core]:x64-linux -> 2.44.1#1
  * atk[core]:x64-linux -> 2.38.0#5
  * cairo[core,fontconfig,freetype,gobject,x11]:x64-linux -> 1.17.6#5
  * gdk-pixbuf[core]:x64-linux -> 2.42.9#5
  * glib[core]:x64-linux -> 2.75.3
    gtk3[core]:x64-linux -> 3.24.34#2
  * pango[core]:x64-linux -> 1.50.12#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 7 package(s) from /home/zqqmsi/.cache/vcpkg/archives in 242.8 ms. Use --debug to see more details.
Installing 1/8 glib:x64-linux...
Elapsed time to handle glib:x64-linux: 75.99 ms
Installing 2/8 at-spi2-core:x64-linux...
Elapsed time to handle at-spi2-core:x64-linux: 11.09 ms
Installing 3/8 atk:x64-linux...
Elapsed time to handle atk:x64-linux: 12.35 ms
Installing 4/8 at-spi2-atk:x64-linux...
Elapsed time to handle at-spi2-atk:x64-linux: 4.48 ms
Installing 5/8 cairo:x64-linux...
Elapsed time to handle cairo:x64-linux: 23.22 ms
Installing 6/8 gdk-pixbuf:x64-linux...
Elapsed time to handle gdk-pixbuf:x64-linux: 24.86 ms
Installing 7/8 pango:x64-linux...
Elapsed time to handle pango:x64-linux: 9.516 ms
Installing 8/8 gtk3:x64-linux...
Building gtk3[core]:x64-linux...
-- Using cached GNOME-gtk-3.24.34.tar.gz.
-- Cleaning sources at /home/zqqmsi/vcpkg-2023.01.09/buildtrees/gtk3/src/3.24.34-ff64a81b83.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/zqqmsi/vcpkg-2023.01.09/downloads/GNOME-gtk-3.24.34.tar.gz
-- Applying patch 0001-build.patch
-- Applying patch cairo-cpp-linkage.patch
-- Using source at /home/zqqmsi/vcpkg-2023.01.09/buildtrees/gtk3/src/3.24.34-ff64a81b83.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Package x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/zqqmsi/vcpkg-2023.01.09/downloads/tools/ninja/1.10.2-linux/ninja install -v
    Working Directory: /home/zqqmsi/vcpkg-2023.01.09/buildtrees/gtk3/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/zqqmsi/vcpkg-2023.01.09/buildtrees/gtk3/package-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/gtk3/portfile.cmake:79 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)

error: building gtk3:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gtk3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gtk3]+Build+error
Include '[gtk3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: a325228 2023-02-18 (2 天前)

- Attach ***every failure log file*** mentioned in the console output.

[package-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10779018/package-x64-linux-dbg-out.log)

**Additional context**
get build error when installing opencv, then found it's gtk3 and glib problem. Already try the latest port files, problem still unsolved. do not know what to do with this, maybe just because ubuntu1604 is too old?

**Comment by dg0yt** [comment] 2023-02-20 05:33
Maybe its the mix of the old system with two extra lib managers (miniconda3, vcpkg).
~~~
FAILED: gdk/gdkresources.c 
/home/zqqmsi/vcpkg-2023.01.09/installed/x64-linux/tools/glib/glib-compile-resources gdk/gdk.gresource.xml --sourcedir ../src/3.24.34-ff64a81b83.clean/gdk/. --sourcedir ../src/3.24.34-ff64a81b83.clean/gdk --c-name _gdk --internal --generate --target gdk/gdkresources.c --manual-register --dependency-file gdk/gdkresources.c.d
/home/zqqmsi/vcpkg-2023.01.09/installed/x64-linux/tools/glib/glib-compile-resources: symbol lookup error: /home/zqqmsi/vcpkg-2023.01.09/installed/x64-linux/tools/glib/glib-compile-resources: undefined symbol: g_string_free_and_steal
...
[8/903] /home/zqqmsi/vcpkg-2023.01.09/miniconda3/bin/python3 ...
~~~

**Comment by clearspring987** [comment] 2023-02-20 08:23
> Maybe its the mix of the old system with two extra lib managers (miniconda3, vcpkg).
> 
> ```
> FAILED: gdk/gdkresources.c 
> /home/zqqmsi/vcpkg-2023.01.09/installed/x64-linux/tools/glib/glib-compile-resources gdk/gdk.gresource.xml --sourcedir ../src/3.24.34-ff64a81b83.clean/gdk/. --sourcedir ../src/3.24.34-ff64a81b83.clean/gdk --c-name _gdk --internal --generate --target gdk/gdkresources.c --manual-register --dependency-file gdk/gdkresources.c.d
> /home/zqqmsi/vcpkg-2023.01.09/installed/x64-linux/tools/glib/glib-compile-resources: symbol lookup error: /home/zqqmsi/vcpkg-2023.01.09/installed/x64-linux/tools/glib/glib-compile-resources: undefined symbol: g_string_free_and_steal
> ...
> [8/903] /home/zqqmsi/vcpkg-2023.01.09/miniconda3/bin/python3 ...
> ```

I remove miniconda and upgrade my default python to 3.11, remove buildtrees, packages, and installed directories, so everything is new. 
My x64-linux.cmake need to be customed like this, otherwise build process get error before gtk3 got compiled:
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CXX_FLAGS "${VCPKG_CXX_FLAGS} -fPIC")
set(VCPKG_C_FLAGS "${VCPKG_C_FLAGS} -fPIC")

Problem still unsolved and seems nothing changed, here is error log file.
[package-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/10781970/package-x64-linux-dbg-out.log)

Failure logs here:
Computing installation plan...
The following packages will be built and installed:
  * at-spi2-atk[core]:x64-linux -> 2.38.0
  * at-spi2-core[core]:x64-linux -> 2.44.1#1
  * atk[core]:x64-linux -> 2.38.0#5
  * cairo[core,fontconfig,freetype,gobject,x11]:x64-linux -> 1.17.6#5
  * gdk-pixbuf[core]:x64-linux -> 2.42.9#5
  * glib[core]:x64-linux -> 2.75.3
    gtk3[core]:x64-linux -> 3.24.34#2
  * pango[core]:x64-linux -> 1.50.12#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 7 package(s) from /home/zqqmsi/.cache/vcpkg/archives in 224.2 ms. Use --debug to see more details.
Installing 1/8 glib:x64-linux...
Elapsed time to handle glib:x64-linux: 73.61 ms
Installing 2/8 at-spi2-core:x64-linux...
Elapsed time to handle at-spi2-core:x64-linux: 11.49 ms
Installing 3/8 atk:x64-linux...
Elapsed time to handle atk:x64-linux: 12.54 ms
Installing 4/8 at-spi2-atk:x64-linux...
Elapsed time to handle at-spi2-atk:x64-linux: 3.384 ms
Installing 5/8 cairo:x64-linux...
Elapsed time to handle cairo:x64-linux: 20.65 ms
Installing 6/8 gdk-pixbuf:x64-linux...
Elapsed time to handle gdk-pixbuf:x64-linux: 21.62 ms
Installing 7/8 pango:x64-linux...
Elapsed time to handle pango:x64-linux: 10.96 ms
Installing 8/8 gtk3:x64-linux...
Building gtk3[core]:x64-linux...
-- [OVERLAY] Loading triplet configuration from: /home/zqqmsi/vcpkg-2023.01.09/triplets/x64-linux.cmake
-- Using cached GNOME-gtk-3.24.34.tar.gz.
-- Cleaning sources at /home/zqqmsi/vcpkg-official/buildtrees/gtk3/src/3.24.34-ff64a81b83.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/zqqmsi/vcpkg-official/downloads/GNOME-gtk-3.24.34.tar.gz
-- Applying patch 0001-build.patch
-- Applying patch cairo-cpp-linkage.patch
-- Using source at /home/zqqmsi/vcpkg-official/buildtrees/gtk3/src/3.24.34-ff64a81b83.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Configuring x64-linux-dbg
-- Configuring x64-linux-dbg done
-- Configuring x64-linux-rel
-- Configuring x64-linux-rel done
-- Package x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /home/zqqmsi/vcpkg-official/downloads/tools/ninja/1.10.2-linux/ninja install -v
    Working Directory: /home/zqqmsi/vcpkg-official/buildtrees/gtk3/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/zqqmsi/vcpkg-official/buildtrees/gtk3/package-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/gtk3/portfile.cmake:79 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)


error: building gtk3:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gtk3
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[gtk3]+Build+error
Include '[gtk3] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: a325228 2023-02-18 (2 天前)

**Comment by Adela0814** [comment] 2023-04-17 07:21
Duplicate of https://github.com/microsoft/vcpkg/issues/27516.

**Closed by Adela0814** 2023-04-17 07:21 UTC
Labels: category:community-triplet
