### ISSUE TITLE
How do I set the path in `vcpkg/ports/intel-mkl/portfile.cmake`

### ISSUE THREAD

**Issue by benam2** [microsoft/vcpkg#26488] opened 2022-08-23 23:24 UTC
I faced with this error while trying to install `flashlight-cuda` : 
```Could not find MKL.  Before continuing, please download and install MKL```
When I looked at the code inside `./vcpkg/ports/intel-mkl/portfile.cmake` I realized the path for MKL is set for windows.

Culd you please help me how can I set the path while the MKL is installed in linux and conda. I have tried this but it raises the exact same error:

```
set(MKLROOT ./conda/envs/asr/lib/cmake//mkl)
set(INTEL_ROOT ./conda/envs/asr/lib/cmake/)
```

Thanks for your time

**Comment by Cheney-W** [comment] 2022-08-24 07:48
Duplicate of https://github.com/microsoft/vcpkg/issues/15204

**Closed by Cheney-W** 2022-08-24 07:48 UTC
Labels: category:port-feature
