### ISSUE TITLE
[openexr] Build error

### ISSUE THREAD

**Issue by ZHAOmin991029** [microsoft/vcpkg#32134] opened 2023-06-21 01:57 UTC
E:\app\vcpkg\vcpkg-master>vcpkg install openexr:x64-windows
Computing installation plan...
The following packages will be built and installed:
    openexr:x64-windows -> 3.1.7
Detecting compiler hash for triplet x64-windows...
-- Automatically setting HTTP(S)_PROXY environment variables to "127.0.0.1:7890".
Restored 0 package(s) from C:\Users\29493\AppData\Local\vcpkg\archives in 269 us. Use --debug to see more details.
Installing 1/1 openexr:x64-windows...
Building openexr:x64-windows...
-- Using cached AcademySoftwareFoundation-openexr-v3.1.7.tar.gz.
-- Cleaning sources at E:/app/vcpkg/vcpkg-master/buildtrees/openexr/src/v3.1.7-1f7f501e1c.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/app/vcpkg/vcpkg-master/downloads/AcademySoftwareFoundation-openexr-v3.1.7.tar.gz
-- Using source at E:/app/vcpkg/vcpkg-master/buildtrees/openexr/src/v3.1.7-1f7f501e1c.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: E:/app/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j5
    Working Directory: E:/app/vcpkg/vcpkg-master/buildtrees/openexr/x64-windows-dbg
    See logs for more information:
      E:\app\vcpkg\vcpkg-master\buildtrees\openexr\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openexr/portfile.cmake:25 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building openexr:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openexr:x64-windows: 1.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openexr
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[openexr]+Build+error&body=Copy+issue+body+from+E%3A%2Fapp%2Fvcpkg%2Fvcpkg-master%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by JonLiu1993** [comment] 2023-06-21 02:03
Duplicate of #32133.

**Closed by JonLiu1993** 2023-06-21 02:03 UTC
