### ISSUE TITLE
[qtbase] Build error

### ISSUE THREAD

**Issue by ixblaze16xi** [microsoft/vcpkg#33700] opened 2023-09-11 10:12 UTC
Package: qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,egl,fontconfig,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,xcb,xcb-xlib,xkb,xkbcommon-x11,xlib,xrender,zstd]:x64-linux -> 6.5.2#1

**Host Environment**

- Host: x64-linux
- Compiler: GNU 8.5.0
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 962e5e39f 2023-09-08 (3 days ago)

**To Reproduce**

`vcpkg install Qt`
[issue_body.md](https://github.com/microsoft/vcpkg/files/12574822/issue_body.md)

Additional log from "issue_body.md" attached

**Comment by jimwang118** [comment] 2023-09-12 06:04
This issue could be reproduced with vcpkg 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416. I will try to fix it.

**Comment by jimwang118** [comment] 2023-12-20 09:19
On Ubuntu systems, run sudo apt-get install '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev by following the required port instructions. Solve this problem.

**Comment by legerch** [comment] 2023-12-22 08:31
Hello @jimwang118 , I have the same issue under Ubuntu 22.04 LTS, what do you mean by "following the required port instructions", what are those port instructions ? (I'm sorry I look over documentation and package port but can't find anything)
Because even after using `apt install` of needed packages, issue is still here

**Comment by jimwang118** [comment] 2023-12-22 08:46
> Hello @jimwang118 , I have the same issue under Ubuntu 22.04 LTS, what do you mean by "following the required port instructions", what are those port instructions ? (I'm sorry I look over documentation and package port but can't find anything) Because even after using `apt install` of needed packages, issue is still here

Can you provide your error log?

**Comment by legerch** [comment] 2023-12-22 08:59
> Can you provide your error log?

Thank you for your reply, I have submitted an issue at https://github.com/microsoft/vcpkg/issues/35815 with all error logs (to not hijack this thread)

**Comment by jimwang118** [comment] 2023-12-27 09:09
Duplicate of https://github.com/microsoft/vcpkg/issues/35815

**Closed by jimwang118** 2023-12-27 09:09 UTC
Labels: category:question
