### ISSUE TITLE
[glib] Build failure

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#39771] opened 2024-07-08 18:22 UTC
Package: glib:arm64-osx -> 2.78.4#3

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 15.0.0.15000309
-    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: 81c2e2ba6 2024-06-24 (6 days ago)

**To Reproduce**

`vcpkg x-test-features --failure-logs=logs --ci-feature-baseline=scripts/ci.feature.baseline.txt --all`
**Failure logs**

```
-- Found Python version '3.12.4 at /opt/homebrew/bin/python3'
-- Using meson: /Users/leanderSchulten/git_projekte/vcpkg/downloads/tools/meson-1.3.2-5ee8cb/meson.py
-- Using cached glib-2.78.4.tar.xz.
-- Extracting source /Users/leanderSchulten/git_projekte/vcpkg/downloads/glib-2.78.4.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean
-- Found external ninja('1.12.1').
-- Configuring arm64-osx-dbg
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
-- Configuring arm64-osx-dbg done
-- Configuring arm64-osx-rel
-- Configuring arm64-osx-rel done
-- Package arm64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /opt/homebrew/bin/ninja install -v
    Working Directory: /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/arm64-osx-dbg
    Error code: 1
    See logs for more information:
      /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/package-arm64-osx-dbg-out.log

Call Stack (most recent call first):
  vcpkg_installed/arm64-osx/share/vcpkg-tool-meson/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:56 (vcpkg_install_meson)
  scripts/ports.cmake:191 (include)



```
<details><summary>/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/package-arm64-osx-dbg-out.log</summary>

```
[1/582] /opt/homebrew/opt/python@3.12/bin/python3.12 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org. --output-directory gio --generate-c-code gdbus-daemon-generated --c-namespace _G ../src/glib-2-322e03f702.clean/gio/dbus-daemon.xml
FAILED: gio/gdbus-daemon-generated.h gio/gdbus-daemon-generated.c 
/opt/homebrew/opt/python@3.12/bin/python3.12 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org. --output-directory gio --generate-c-code gdbus-daemon-generated --c-namespace _G ../src/glib-2-322e03f702.clean/gio/dbus-daemon.xml
Traceback (most recent call last):
  File "/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[2/582] /opt/homebrew/opt/python@3.12/bin/python3.12 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org.freedesktop.portal. --output-directory gio --generate-c-code xdp-dbus --c-namespace GXdp ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Documents.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.OpenURI.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.ProxyResolver.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Trash.xml
FAILED: gio/xdp-dbus.h gio/xdp-dbus.c 
/opt/homebrew/opt/python@3.12/bin/python3.12 gio/gdbus-2.0/codegen/gdbus-codegen --interface-prefix org.freedesktop.portal. --output-directory gio --generate-c-code xdp-dbus --c-namespace GXdp ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Documents.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.OpenURI.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.ProxyResolver.xml ../src/glib-2-322e03f702.clean/gio/org.freedesktop.portal.Trash.xml
Traceback (most recent call last):
  File "/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/gdbus-codegen", line 53, in <module>
    from codegen import codegen_main
  File "/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/codegen_main.py", line 29, in <module>
    from . import dbustypes
  File "/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/dbustypes.py", line 22, in <module>
    from . import utils
  File "/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/arm64-osx-dbg/gio/gdbus-2.0/codegen/utils.py", line 22, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
[3/582] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -Iglib/libcharset/libcharset.a.p -Iglib/libcharset -I../src/glib-2-322e03f702.clean/glib/libcharset -I. -I../src/glib-2-322e03f702.clean -I/Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/arm64-osx/include -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g '-DGLIB_CHARSETALIAS_DIR="/Users/leanderSchulten/git_projekte/vcpkg/packages/glib_arm64-osx/debug/lib"' -MD -MQ glib/libcharset/libcharset.a.p/localcharset.c.o -MF glib/libcharset/libcharset.a.p/localcharset.c.o.d -o glib/libcharset/libcharset.a.p/localcharset.c.o -c ../src/glib-2-322e03f702.clean/glib/libcharset/localcharset.c
[4/582] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/arm64-osx/include -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmimealias.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmimealias.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmimealias.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmimealias.c
[5/582] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -Igio/xdgmime/libxdgmime.a.p -Igio/xdgmime -I../src/glib-2-322e03f702.clean/gio/xdgmime -I. -I../src/glib-2-322e03f702.clean -I/Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/arm64-osx/include -fvisibility=hidden -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 -g -D_GNU_SOURCE -fno-strict-aliasing -DG_DISABLE_CAST_CHECKS -Wimplicit-fallthrough -Wmisleading-indentation -Wmissing-field-initializers -Wnonnull -Wunused -Wno-unused-parameter -Wno-cast-function-type -Wno-pedantic -Wno-format-zero-length -Wno-variadic-macros -Werror=format=2 -Werror=init-self -Werror=missing-include-dirs -Werror=pointer-arith -Werror=unused-result -Wstrict-prototypes -Wno-bad-function-cast -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=pointer-sign -Wno-string-plus-int -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk -g -DHAVE_CONFIG_H -DXDG_PREFIX=_gio_xdg -MD -MQ gio/xdgmime/libxdgmime.a.p/xdgmime.c.o -MF gio/xdgmime/libxdgmime.a.p/xdgmime.c.o.d -o gio/xdgmime/libxdgmime.a.p/xdgmime.c.o -c ../src/glib-2-322e03f702.clean/gio/xdgmime/xdgmime.c
[6/582] /opt/homebrew/opt/python@3.12/bin/python3.12 /Users/leanderSchulten/git_projekte/vcpkg/downloads/tools/meson-1.3.2-5ee8cb/meson.py --internal exe --capture gobject/glib-enumtypes.h -- /opt/homebrew/opt/python@3.12/bin/python3.12 gobject/glib-mkenums --template ../src/glib-2-322e03f702.clean/gobject/glib-enumtypes.h.template ../src/glib-2-322e03f702.clean/gobject/../glib/gunicode.h
[7/582] /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 versions-macros ../src/glib-2-322e03f702.clean/glib/gversionmacros.h.in glib/gversionmacros.h
[8/582] /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GMODULE gmodule/gmodule-visibility.h
[9/582] /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GIO gio/gio-visibility.h
[10/582] /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GLIB glib/glib-visibility.h
[11/582] /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/glib/src/glib-2-322e03f702.clean/tools/gen-visibility-macros.py 2.78.4 visibility-macros GOBJECT gobject/gobject-visibility.h
[12/582] /opt/homebrew/opt/python@3.12/bin/python3.12 /Users/leanderSchulten/git_projekte/vcpkg/downloads/tools/meson-1.3.2-5ee8cb/meson.py --internal exe --capture gio/gioenumtypes.h -- /opt/homebrew/opt/python@3.12/bin/python3.12 gobject/glib-mkenums --template ../src/glib-2-322e03f702.clean/gio/gioenumtypes.h.template ../src/glib-2-322e03f702.clean/gio/gappinfo.h ../src/glib-2-322e03f702.clean/gio/gasyncinitable.h ../src/glib-2-322e03f702.clean/gio/gasyncresult.h ../src/glib-2-322e03f702.clean/gio/gbufferedinputstream.h ../src/glib-2-322e03f702.clean/gio/gbufferedoutputstream.h ../src/glib-2-322e03f702.clean/gio/gbytesicon.h ../src/glib-2-322e03f702.clean/gio/gcancellable.h ../src/glib-2-322e03f702.clean/gio/gcontenttype.h ../src/glib-2-322e03f702.clean/gio/gcharsetconverter.h ../src/glib-2-322e03f702.clean/gio/gconverter.h ../src/glib-2-322e03f702.clean/gio/gconverterinputstream.h ../src/glib-2-322e03f702.clean/gio/gconverteroutputstream.h ../src/glib-2-322e03f702.clean/gio/gdatagrambased.h ../src/glib-2-322e03f702.clean/gio/gdatainputstream.h ../src/glib-2-322e03f702.clean/gio/gdataoutputstream.h ../src/glib-2-322e03f702.clean/gio/gdebugcontroller.h ../src/glib-2-322e03f702.clean/gio/gdebugcontrollerdbus.h ../src/glib-2-322e03f702.clean/gio/gdrive.h ../src/glib-2-322e03f702.clean/gio/gemblem.h ../src/glib-2-322e03f702.clean/gio/gemblemedicon.h ../src/glib-2-322e03f702.clean/gio/gfile.h ../src/glib-2-322e03f702.clean/gio/gfileattribute.h ../src/glib-2-322e03f702.clean/gio/gfileenumerator.h ../src/glib-2-322e03f702.clean/gio/gfileicon.h ../src/glib-2-322e03f702.clean/gio/gfileinfo.h ../src/glib-2-322e03f702.clean/gio/gfileinputstream.h ../src/glib-2-322e03f702.clean/gio/gfilemonitor.h ../src/glib-2-322e03f702.clean/gio/gfilenamecompleter.h ../src/glib-2-322e03f702.clean/gio/gfileoutputstream.h ../src/glib-2-322e03f702.clean/gio/gfileiostream.h ../src/glib-2-322e03f702.clean/gio/gfilterinputstream.h ../src/glib-2-322e03f702.clean/gio/gfilteroutputstream.h ../src/glib-2-322e03f702.clean/gio/gicon.h ../src/glib-2-322e03f702.clean/gio/ginetaddress.h ../src/glib-2-322e03f702.clean/gio/ginetaddressmask.h ../src/glib-2-322e03f702.clean/gio/ginetsocketaddress.h ../src/glib-2-322e03f702.clean/gio/ginitable.h ../src/glib-2-322e03f702.clean/gio/ginputstream.h ../src/glib-2-322e03f702.clean/gio/gio.h ../src/glib-2-322e03f702.clean/gio/gio-autocleanups.h ../src/glib-2-322e03f702.clean/gio/gioenums.h ../src/glib-2-322e03f702.clean/gio/gioerror.h ../src/glib-2-322e03f702.clean/gio/giomodule.h ../src/glib-2-322e03f702.clean/gio/gioscheduler.h ../src/glib-2-322e03f702.clean/gio/giostream.h ../src/glib-2-322e03f702.clean/gio/giotypes.h ../src/glib-2-322e03f702.clean/gio/gloadableicon.h ../src/glib-2-322e03f702.clean/gio/gmount.h ../src/glib-2-322e03f702.clean/gio/gmemoryinputstream.h ../src/glib-2-322e03f702.clean/gio/gmemorymonitor.h ../src/glib-2-322e03f702.clean/gio/gmemoryoutputstream.h ../src/glib-2-322e03f702.clean/gio/gmountoperation.h ../src/glib-2-322e03f702.clean/gio/gnativesocketaddress.h ../src/glib-2-322e03f702.clean/gio/gnativevolumemonitor.h ../src/glib-2-322e03f702.clean/gio/gnetworkaddress.h ../src/glib-2-322e03f702.clean/gio/gnetworkmonitor.h ../src/glib-2-322e03f702.clean/gio/gnetworkservice.h ../src/glib-2-322e03f702.clean/gio/goutputstream.h ../src/glib-2-322e03f702.clean/gio/gpermission.h ../src/glib-2-322e03f702.clean/gio/gpollableinputstream.h ../src/glib-2-322e03f702.clean/gio/gpollableoutputstream.h ../src/glib-2-322e03f702.clean/gio/gpollableutils.h ../src/glib-2-322e03f702.clean/gio/gpowerprofilemonitor.h ../src/glib-2-322e03f702.clean/gio/gproxy.h ../src/glib-2-322e03f702.clean/gio/gproxyaddress.h ../src/glib-2-322e03f702.clean/gio/gproxyaddressenumerator.h ../src/glib-2-322e03f702.clean/gio/gproxyresolver.h ../src/glib-2-322e03f702.clean/gio/gresolver.h ../src/glib-2-322e03f702.clean/gio/gresource.h ../src/glib-2-322e03f702.clean/gio/gseekable.h ../src/glib-2-322e03f702.clean/gio/gsimpleasyncresult.h ../src/glib-2-322e03f702.clean/gio/gsimpleiostream.h ../src/glib-2-322e03f702.clean/gio/gsimplepermission.h ../src/glib-2-322e03f702.clean/gio/gsimpleproxyresolver.h ../src/glib-2-322e03f702.clean/gio/gsocket.h ../src/glib-2-322e03f702.clean/gio/gsocketaddress.h ../src/glib-2-322e03f702.clean/gio/gsocketaddressenumerator.h ../src/glib-2-322e03f702.clean/gio/gsocketclient.h ../src/glib-2-322e03f702.clean/gio/gsocketconnectable.h ../src/glib-2-322e03f702.clean/gio/gsocketconnection.h ../src/glib-2-322e03f702.clean/gio/gsocketcontrolmessage.h ../src/glib-2-322e03f702.clean/gio/gsocketlistener.h ../src/glib-2-322e03f702.clean/gio/gsocketservice.h ../src/glib-2-322e03f702.clean/gio/gsrvtarget.h ../src/glib-2-322e03f702.clean/gio/gsubprocess.h ../src/glib-2-322e03f702.clean/gio/gsubprocesslauncher.h ../src/glib-2-322e03f702.clean/gio/gtask.h ../src/glib-2-322e03f702.clean/gio/gtcpconnection.h ../src/glib-2-322e03f702.clean/gio/gtcpwrapperconnection.h ../src/glib-2-322e03f702.clean/gio/gthemedicon.h ../src/glib-2-322e03f702.clean/gio/gthreadedsocketservice.h ../src/glib-2-322e03f702.clean/gio/gtlsbackend.h ../src/glib-2-322e03f702.clean/gio/gtlscertificate.h ../src/glib-2-322e03f702.clean/gio/gtlsclientconnection.h ../src/glib-2-322e03f702.clean/gio/gtlsconnection.h ../src/glib-2-322e03f702.clean/gio/gtlsdatabase.h ../src/glib-2-322e03f702.clean/gio/gtlsfiledatabase.h ../src/glib-2-322e03f702.clean/gio/gtlsinteraction.h ../src/glib-2-322e03f702.clean/gio/gtlspassword.h ../src/glib-2-322e03f702.clean/gio/gtlsserverconnection.h ../src/glib-2-322e03f702.clean/gio/gdtlsconnection.h ../src/glib-2-322e03f702.clean/gio/gdtlsclientconnection.h ../src/glib-2-322e03f702.clean/gio/gdtlsserverconnection.h ../src/glib-2-322e03f702.clean/gio/gunixconnection.h ../src/glib-2-322e03f702.clean/gio/gunixcredentialsmessage.h ../src/glib-2-322e03f702.clean/gio/gunixfdlist.h ../src/glib-2-322e03f702.clean/gio/gunixsocketaddress.h ../src/glib-2-322e03f702.clean/gio/gvfs.h ../src/glib-2-322e03f702.clean/gio/gvolume.h ../src/glib-2-322e03f702.clean/gio/gvolumemonitor.h ../src/glib-2-322e03f702.clean/gio/gzlibcompressor.h ../src/glib-2-322e03f702.clean/gio/gzlibdecompressor.h ../src/glib-2-322e03f702.clean/gio/glistmodel.h ../src/glib-2-322e03f702.clean/gio/gliststore.h ../src/glib-2-322e03f702.clean/gio/gapplication.h ../src/glib-2-322e03f702.clean/gio/gapplicationcommandline.h ../src/glib-2-322e03f702.clean/gio/gactiongroup.h ../src/glib-2-322e03f702.clean/gio/gactionmap.h ../src/glib-2-322e03f702.clean/gio/gsimpleactiongroup.h ../src/glib-2-322e03f702.clean/gio/gremoteactiongroup.h ../src/glib-2-322e03f702.clean/gio/gactiongroupexporter.h ../src/glib-2-322e03f702.clean/gio/gdbusactiongroup.h ../src/glib-2-322e03f702.clean/gio/gaction.h ../src/glib-2-322e03f702.clean/gio/gpropertyaction.h ../src/glib-2-322e03f702.clean/gio/gsimpleaction.h ../src/glib-2-322e03f702.clean/gio/gmenumodel.h ../src/glib-2-322e03f702.clean/gio/gmenu.h ../src/glib-2-322e03f702.clean/gio/gmenuexporter.h ../src/glib-2-322e03f702.clean/gio/gdbusmenumodel.h ../src/glib-2-322e03f702.clean/gio/gnotification.h ../src/glib-2-322e03f702.clean/gio/gosxappinfo.h ../src/glib-2-322e03f702.clean/gio/gsettingsbackend.h ../src/glib-2-322e03f702.clean/gio/gsettingsschema.h ../src/glib-2-322e03f702.clean/gio/gsettings.h ../src/glib-2-322e03f702.clean/gio/gdbusauthobserver.h ../src/glib-2-322e03f702.clean/gio/gcredentials.h ../src/glib-2-322e03f702.clean/gio/gdbusutils.h ../src/glib-2-322e03f702.clean/gio/gdbuserror.h ../src/glib-2-322e03f702.clean/gio/gdbusaddress.h ../src/glib-2-322e03f702.clean/gio/gdbusconnection.h ../src/glib-2-322e03f702.clean/gio/gdbusmessage.h ../src/glib-2-322e03f702.clean/gio/gdbusnameowning.h ../src/glib-2-322e03f702.clean/gio/gdbusnamewatching.h ../src/glib-2-322e03f702.clean/gio/gdbusproxy.h ../src/glib-2-322e03f702.clean/gio/gdbusintrospection.h ../src/glib-2-322e03f702.clean/gio/gdbusmethodinvocation.h ../src/glib-2-322e03f702.clean/gio/gdbusserver.h ../src/glib-2-322e03f702.clean/gio/gdbusinterface.h ../src/glib-2-322e03f702.clean/gio/gdbusinterfaceskeleton.h ../src/glib-2-322e03f702.clean/gio/gdbusobject.h ../src/glib-2-322e03f702.clean/gio/gdbusobjectskeleton.h ../src/glib-2-322e03f702.clean/gio/gdbusobjectproxy.h ../src/glib-2-322e03f702.clean/gio/gdbusobjectmanager.h ../src/glib-2-322e03f702.clean/gio/gdbusobjectmanagerclient.h ../src/glib-2-322e03f702.clean/gio/gdbusobjectmanagerserver.h ../src/glib-2-322e03f702.clean/gio/gtestdbus.h gio/gnetworking.h
ninja: build stopped: subcommand failed.
```
</details>

**Comment by autoantwort** [comment] 2024-07-08 18:28
A workaround is to install `setuptools` globally, for example on mac by running `brew install python-setuptools`

**Comment by FrankXie05** [comment] 2024-07-09 07:53
Duplicate of https://github.com/microsoft/vcpkg/issues/39217

**Closed by FrankXie05** 2024-07-09 07:53 UTC
Labels: category:question
