### ISSUE TITLE
eglext_angle.h not copied at install

### ISSUE THREAD

**Issue by mediabuff** [microsoft/vcpkg#14890] opened 2020-12-02 01:25 UTC
include\EGL\eglext_angle.h  should be copied to the install\... \include like eglext.h

**Comment by NancyLi1013** [comment] 2020-12-02 09:45
Hi @mediabuff 

Thanks for your posting this issue.

It seems that there is no eglext_angle.h in current `angle `version. We need to update angle to the latest to add this header.

**Comment by mediabuff** [comment] 2020-12-10 12:27
Also, angle_util.lib is not built - as this library is required to run angle samples

**Comment by NancyLi1013** [comment] 2021-03-09 07:51
Hi @robmikh @driver1998 @isanych 

Would you like to help update `angle `to the latest? I checked the latest source codes and found there were a lot of changes. Since I'm not familiar with this port. So could anyone help?

Thanks in advance.

**Comment by robmikh** [comment] 2021-03-11 00:24
Unfortunately I no longer use ANGLE for my cross-platform projects (I've moved onto [wgpu](https://github.com/gfx-rs/wgpu)), so I don't have a good way to validate a potential port update. I can't make promises about my schedule and when I may have time for this, but having a good way to validate changes would help me or whomever picks this up.

**Comment by NancyLi1013** [comment] 2021-03-11 07:58
@robmikh 

Thanks for your response. It doesn't matter even though you have no enough time to do this. Can you give some advice on the new version update? Maybe I can try to do some work.

**Comment by hanseuljun** [comment] 2021-03-17 01:51
I submitted a pull request that includes eglext_angle.h. The issue was caused by all header files with "EGL" in their name being excluded at the end of ports/angle/CMakeLists.txt.

Since I worked on this one before reading this issue, this PR does not solve the angle_util.lib issue or points at the up-to-date version of ANGLE.

**Comment by hanseuljun** [comment] 2021-03-17 01:56
This PR also does not let you call eglCreateDeviceANGLE directly. At least in my machine for x64-windows.

The way I currently work with it is through using eglGetProcAddress. I first call
PFNEGLCREATEDEVICEANGLEPROC createDeviceANGLE = (PFNEGLCREATEDEVICEANGLEPROC)eglGetProcAddress("eglCreateDeviceANGLE");
then use createDeviceANGLE instead of eglCreateDeviceANGLE.

**Comment by Neumann-A** [comment] 2023-02-27 22:43
@LilyWangLL Close. The header is copied according to the file list.

**Comment by LilyWangLL** [comment] 2023-02-28 07:43
Now `eglext_angle.h` has installed to include folder of `angle`, so I am closing this issue for now.

**Closed by LilyWangLL** 2023-02-28 07:43 UTC
Labels: category:port-feature, category:port-update
