### ISSUE TITLE
[boost] build failure x64-windows-static

### ISSUE THREAD

**Issue by SKNo** [microsoft/vcpkg#38498] opened 2024-04-30 15:45 UTC
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install boost:x64-windows-static
```

### Failure logs

```
E:\Lib\vcpkg>vcpkg install boost:x64-windows-static
Computing installation plan...
The following packages will be built and installed:
    boost:x64-windows-static@1.84.0#1
  * boost-cobalt:x64-windows-static@1.84.0#1
  * boost-parameter-python:x64-windows-static@1.84.0#1
  * boost-python[core,python3]:x64-windows-static@1.84.0#1
  * boost-redis:x64-windows-static@1.84.0#1
  * python3:x64-windows-static@3.11.8#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows-static...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from E:\Lib\vcpkg_binary_cache\archives in 425 us. Use --debug to see more details.
Installing 1/6 boost-cobalt:x64-windows-static@1.84.0#1...
Building boost-cobalt:x64-windows-static@1.84.0#1...
-- Using cached boostorg-cobalt-boost-1.84.0.tar.gz.
-- Cleaning sources at E:/Lib/vcpkg/buildtrees/boost-cobalt/src/ost-1.84.0-f1b8232bac.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Lib/vcpkg/downloads/boostorg-cobalt-boost-1.84.0.tar.gz
-- Using source at E:/Lib/vcpkg/buildtrees/boost-cobalt/src/ost-1.84.0-f1b8232bac.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: E:/Lib/vcpkg/buildtrees/boost-cobalt/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\Lib\vcpkg\buildtrees\boost-cobalt\config-x64-windows-static-dbg-CMakeCache.txt.log
      E:\Lib\vcpkg\buildtrees\boost-cobalt\config-x64-windows-static-rel-CMakeCache.txt.log
      E:\Lib\vcpkg\buildtrees\boost-cobalt\config-x64-windows-static-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-boost/boost-install.cmake:55 (vcpkg_cmake_configure)
  ports/boost-cobalt/portfile.cmake:12 (boost_configure_and_install)
  scripts/ports.cmake:175 (include)


error: building boost-cobalt:x64-windows-static failed with: BUILD_FAILED
Elapsed time to handle boost-cobalt:x64-windows-static: 3 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-cobalt
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[boost-cobalt]+Build+error+on+x64-windows-static&body=Copy+issue+body+from+E%3A%2FLib%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/15167235/config-x64-windows-static-out.log)

### Additional context

According to the log file it is searching for "boost_asio" 
I am totally confused :  before today's `git pull`, I could install or upgrade **all boost-xxx libraries** by `vcpkg install boost:x64-windows-static` or `vcpkg upgrade boost:x64-windows-static`  without any problem.
Am I missing something?
Thank you

**Comment by SKNo** [comment] 2024-04-30 16:14
Also `vcpkg upgrade/install boost:x64-windows`, only upgrades/installs a small subset of boost libraries and 
sub-libraries from `boost-accumulators` to `boost-yap` are not automatically upgraded / installed. 
Should I install upgrade/install one sub-library at time? Just try to figure it out.
Thank you

**Comment by Neumann-A** [comment] 2024-04-30 17:28
The problem is that this works fine:
```
Installing 55/55 boost-cobalt:x64-windows-static@1.84.0#1...
Building boost-cobalt:x64-windows-static@1.84.0#1...
-- Downloading https://github.com/boostorg/cobalt/archive/boost-1.84.0.tar.gz -> boostorg-cobalt-boost-1.84.0.tar.gz...
-- Extracting source E:/vcpkg_cache/downloads/boostorg-cobalt-boost-1.84.0.tar.gz
-- Using source at E:/vcpkg_folders/various/buildtrees/boost-cobalt/src/ost-1.84.0-f1b8232bac.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: E:/vcpkg_folders/various/packages/boost-cobalt_x64-windows-static/share/boost-cobalt/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 1.1 s.
Elapsed time to handle boost-cobalt:x64-windows-static: 6.7 s
boost-cobalt:x64-windows-static package ABI: 01054a8a6ffa3b8edf490aae2e73d650f2d4bba5dd694b89eecb6998a1a55ed6
Total install time: 1 min
The package boost-cobalt is compatible with built-in CMake targets of FindBoost.cmake:

    find_package(Boost REQUIRED COMPONENTS cobalt)
    target_link_libraries(main PRIVATE Boost::cobalt)

or the generated cmake configs via:

    find_package(boost_cobalt REQUIRED CONFIG)
    target_link_libraries(main PRIVATE Boost::cobalt)

```

If I locally test it with a clean checkout

**Comment by SKNo** [comment] 2024-04-30 17:31
Okay,  I will delete all boost buildtrees and try again.

**Comment by Neumann-A** [comment] 2024-04-30 17:38
`vcpkg remove boost-uninstall --recurse` would be enough for the triplets you want to upgrade

**Comment by SKNo** [comment] 2024-04-30 17:44
> `vcpkg remove boost-uninstall --recurse` would be enough for the triplets you want to upgrade
Not working .. will do with a clean checkout

**Comment by SKNo** [comment] 2024-04-30 17:56
I do re-bootstrapped after each `git pull.` I guess my buildtree is messed up. I will do a new and clean checkout  (will take lot of time to rebuild everything). I will confirm here if everything is Ok (permitting to close or keep issues open) 
Thank you

**Comment by SKNo** [comment] 2024-05-01 13:18
@Neumann-A 
I confirm that after a clean and new checkout, all builds worked out correctly (I compile on a laptop, so took a long time)
I have no idea what happend to my buildtrees (I have not done anything out of ordinary), so I leave it to you to keep this issue and the other one (https://github.com/microsoft/vcpkg/issues/38487) open or close.
While I am here, I have a question wrt to the new ports, I see most (all?) of requests for new ports are going inactive (including mine https://github.com/microsoft/vcpkg/issues/35648 ) What is the new policy for the new ports? 
Thank you

**Comment by MonicaLiu0311** [comment] 2024-05-06 09:28
> While I am here, I have a question wrt to the new ports, I see most (all?) of requests for new ports are going inactive (including mine #35648 ) What is the new policy for the new ports?

We are no longer actively adding new ports. If users want to add new ports, they can submit a Pull Request themselves. We will accept and review.

**Comment by MonicaLiu0311** [comment] 2024-05-06 09:29
Duplicate of #38487.

**Closed by MonicaLiu0311** 2024-05-06 09:29 UTC
Labels: category:port-bug

**Comment by pavel-cpp** [comment] 2024-08-06 13:38
I also have the same problem, completely reinstalled vcpkg, but the boost-cobalt error occurs

```json
{
    "builtin-baseline": "a2367ceec5f092d8777606ca110426cadd7ed7db",
    "dependencies": [
        {
            "name": "grpc",
            "features": [ "codegen" ]
        },
        "protobuf",
        "boost"
    ],
    "overrides": [
        { "name": "grpc", "version": "1.60.0" },
        { "name": "protobuf", "version": "4.25.1" },
        { "name": "boost", "version": "1.84.0" }
    ]
}
```

**Comment by dg0yt** [comment] 2024-08-07 05:18
@pavel-cpp boost-cobalt is not related to this issue. Cf. https://github.com/microsoft/vcpkg/issues/40290#issuecomment-2269639431

**Comment by dg0yt** [comment] 2024-08-07 05:19
@pavel-cpp Basically, don't depend on complete `boost` unless you have to.

**Comment by JackBoosY** [comment] 2024-12-31 05:47
Fixed.
