### ISSUE TITLE
[python3] Build error

### ISSUE THREAD

**Issue by shengxiaoyi1993** [microsoft/vcpkg#34600] opened 2023-10-19 12:33 UTC
# issue when build boost ->  python3

## issue description
```
[sxy@localhost vcpkg]$ ./vcpkg install boost
Computing installation plan...
The following packages will be built and installed:
    boost:x64-linux -> 1.83.0#1
  * boost-parameter-python:x64-linux -> 1.83.0
  * boost-poly-collection:x64-linux -> 1.83.0
  * boost-process:x64-linux -> 1.83.0
  * boost-program-options:x64-linux -> 1.83.0
  * boost-python[core,python3]:x64-linux -> 1.83.0
  * boost-sort:x64-linux -> 1.83.0
  * boost-stacktrace:x64-linux -> 1.83.0
  * boost-statechart:x64-linux -> 1.83.0
  * boost-test:x64-linux -> 1.83.0
  * boost-timer:x64-linux -> 1.83.0
  * boost-type-erasure:x64-linux -> 1.83.0
  * boost-url:x64-linux -> 1.83.0
  * boost-wave:x64-linux -> 1.83.0
  * python3:x64-linux -> 3.11.5
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 0 package(s) from /home/sxy/.cache/vcpkg/archives in 112 us. Use --debug to see more details.
Installing 1/15 python3:x64-linux...
Building python3:x64-linux...
-- Using cached python-cpython-v3.11.5.tar.gz.
-- Cleaning sources at /home/sxy/Work/local_repo/Github/clone/vcpkg/buildtrees/python3/src/v3.11.5-244658b11a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/sxy/Work/local_repo/Github/clone/vcpkg/downloads/python-cpython-v3.11.5.tar.gz
-- Applying patch 0001-only-build-required-projects.patch
-- Applying patch 0003-use-vcpkg-zlib.patch
-- Applying patch 0004-devendor-external-dependencies.patch
-- Applying patch 0005-dont-copy-vcruntime.patch
-- Applying patch 0008-python.pc.patch
-- Applying patch 0010-dont-skip-rpath.patch
-- Applying patch 0012-force-disable-curses.patch
-- Applying patch 0014-fix-get-python-inc-output.patch
-- Applying patch 0015-dont-use-WINDOWS-def.patch
-- Applying patch 0002-static-library.patch
-- Applying patch 0011-gcc-ldflags-fix.patch
-- Using source at /home/sxy/Work/local_repo/Github/clone/vcpkg/buildtrees/python3/src/v3.11.5-244658b11a.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/sxy/Work/local_repo/Github/clone/vcpkg/buildtrees/python3/src/v3.11.5-244658b11a.clean/
    Error code: 1
    See logs for more information:
      /home/sxy/Work/local_repo/Github/clone/vcpkg/buildtrees/python3/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:635 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:257 (vcpkg_configure_make)
  scripts/ports.cmake:168 (include)


[sxy@localhost vcpkg]$ cat /home/sxy/Work/local_repo/Github/clone/vcpkg/buildtrees/python3/autoconf-x64-linux-err.log
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
configure.ac:18: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1
```
## environment

- centos 8 
```
[sxy@localhost vcpkg]$ uname -a
Linux localhost.localdomain 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- automake
```
[sxy@localhost vcpkg]$ automake --version
automake (GNU automake) 1.16.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv2+: GNU GPL version 2 or later <https://gnu.org/licenses/gpl-2.0.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Tom Tromey <tromey@redhat.com>
       and Alexandre Duret-Lutz <adl@gnu.org>.

[sxy@localhost vcpkg]$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim Demaille.

```
- autoconf-archive-2023.02.20.tar.xz

## complain
- boost is so widely used, but vcpkg cannot make it easy to use.

**Comment by shengxiaoyi1993** [comment] 2023-10-19 12:34
in addirion, I'm using gcc version 11.2.1 20210728 (Red Hat 11.2.1-1) (GCC)

**Comment by MonicaLiu0311** [comment] 2023-10-20 02:50
you probably need to install autoconf-archive

**Comment by MonicaLiu0311** [comment] 2023-10-20 02:53
Duplicate of https://github.com/microsoft/vcpkg/issues/33080.

**Closed by MonicaLiu0311** 2023-10-20 02:53 UTC
Labels: category:question

**Comment by shengxiaoyi1993** [comment] 2023-10-20 03:22
> you probably need to install autoconf-archive

Thanks for reply. I have already compiled and installed `autoconf-archive-2023.02.20.tar.xz`, as it didn't have sourece in yum or dnf repo.
But I have wondered that automake or other tools can find it

**Comment by MonicaLiu0311** [comment] 2023-10-20 06:17
sudo apt install autoconf-archive

**Comment by shengxiaoyi1993** [comment] 2023-10-21 07:08
> sudo apt install autoconf-archive

not use apt in centos generally
