### ISSUE TITLE
Error: Building package icu:x64-windows-v141 failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by OneOfMyClassmate** [microsoft/vcpkg#11603] opened 2020-05-27 02:59 UTC
Hi, nice to see you. I have a question about the error that is difficult for me to solve.
When I build icu package on Windows 10 by using cmd prompt, the below error occurs. How can I fix it?

The cmd says : 

Starting package 19/104: icu:x64-windows-v141
Building package icu[core]:x64-windows-v141...
-- Using cached C:/Users/dlwns/Documents/slam6d-code-r2223-trunk/slam6d-code-r2223-trunk/build/3rdparty/vcpkg/downloads/icu4c-65_1-src.tgz
-- Using source at C:/Users/dlwns/Documents/slam6d-code-r2223-trunk/slam6d-code-r2223-trunk/build/3rdparty/vcpkg/buildtrees/icu/src/c-65_1-src-702c9cff96
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: C:/Users/dlwns/Documents/slam6d-code-r2223-trunk/slam6d-code-r2223-trunk/build/3rdparty/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed make automake1.15"
    Working Directory: C:/Users/dlwns/Documents/slam6d-code-r2223-trunk/slam6d-code-r2223-trunk/build/3rdparty/vcpkg/downloads/tools/msys2
    Error code: 1
    See logs for more information:
      C:\Users\dlwns\Documents\slam6d-code-r2223-trunk\slam6d-code-r2223-trunk\build\3rdparty\vcpkg\buildtrees\icu\msys-pacman-x64-windows-v141-out.log
      C:\Users\dlwns\Documents\slam6d-code-r2223-trunk\slam6d-code-r2223-trunk\build\3rdparty\vcpkg\buildtrees\icu\msys-pacman-x64-windows-v141-err.log
[msys-pacman-x64-windows-v141-err.log](https://github.com/microsoft/vcpkg/files/4686739/msys-pacman-x64-windows-v141-err.log)
[msys-pacman-x64-windows-v141-out.log](https://github.com/microsoft/vcpkg/files/4686740/msys-pacman-x64-windows-v141-out.log)

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:108 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:78 (vcpkg_acquire_msys)
  scripts/ports.cmake:90 (include)

Error: Building package icu:x64-windows-v141 failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows-v141
  Vcpkg version: 2020.02.04-nohash-external

Additionally, attach any relevant sections from the log files above.
vcpkg install failed

C:\Users\dlwns\Documents\slam6d-code-r2223-trunk\slam6d-code-r2223-trunk\windows>vcpkg update
'vcpkg' is not recognized as an internal or external command,
operable program or batch file.

According to log files,

(1) C:\Users\dlwns\Documents\slam6d-code-r2223-trunk\slam6d-code-r2223-trunk\build\3rdparty\vcpkg\buildtrees\icu\msys-pacman-x64-windows-v141-out.log

says that 

_:: Synchronizing package databases...
 mingw32 is up to date
 mingw64 is up to date
 msys is up to date
resolving dependencies...
looking for conflicting packages..._

_Packages (6) db-5.3.28-2  gdbm-1.18.1-3  libgdbm-1.18.1-3  perl-5.30.2-1  automake1.15-1.15.1-1  make-4.3-1_

_Total Installed Size:  54.07 MiB_

_:: Proceed with installation? [Y/n] 
checking keyring...
checking package integrity...
loading package files...
Errors occurred, no packages were upgraded._

, and 

(2) C:\Users\dlwns\Documents\slam6d-code-r2223-trunk\slam6d-code-r2223-trunk\build\3rdparty\vcpkg\buildtrees\icu\msys-pacman-x64-windows-v141-err.log

says that 

_error: could not open file /var/cache/pacman/pkg/libgdbm-1.18.1-3-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/gdbm-1.18.1-3-x86_64.pkg.tar.zst: Child process exited with status 127
error: failed to commit transaction (cannot open package file)_

I appreciate your help, if you help me solve this error.
Thank you, in advance.

**Comment by NancyLi1013** [comment] 2020-05-27 06:38
Hi @OneOfMyClassmate 
Thanks for posting this issue.
I noticed there are two questions you mentioned above.

- icu build failed 

   The error is related with msys2. This issue should be fixed now. You can update vcpkg and try to rebuild this.
 
- 'vcpkg' is not recognized as an internal or external command

  You need to execute`.\vcpkg update` instead of `vcpkg update`.
In addition,  please use `git pull ` to update vcpkg to the latest commit instead of `vcpkg update`.

Note: We recommend to use `powershell ` instead of `cmd`, especially when you use auto-completion of commands, such as `.\vcpkg integrate install`.

**Comment by OneOfMyClassmate** [comment] 2020-05-27 08:22
Hi, Nancy, thank you for your great answers. I tried the below steps according to your answers.

(Step 1) I tried to update vcpkg using Powershell, and Powershell said that:

_PS C:\Users\dlwns\Documents\slam6d-code-r2223-trunk\slam6d-code-r2223-trunk\build\3rdparty\vcpkg> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating._


(step 2)
I downloaded and install Git from https://git-scm.com/download/win, and tried to update vcpkg :

_dlwns@DESKTOP-GTTPS4E MINGW64 ~/Documents/slam6d-code-r2223-trunk/slam6d-code-r2223-trunk/build/3rdparty/vcpkg
$ .\vcpkg update
bash: .vcpkg: command not found_

it does not find command, so I tried _.\vcpkg integrate install_ :

_dlwns@DESKTOP-GTTPS4E MINGW64 ~/Documents/slam6d-code-r2223-trunk/slam6d-code-r2223-trunk/build/3rdparty/vcpkg
$ ./vcpkg integrate install
Applied user-wide integration for this vcpkg root._

_All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available._

_CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/Users/dlwns/Documents/slam6d-code-r2223-trunk/slam6d-code-r2223-trunk/build/3rdparty/vcpkg/scripts/buildsystems/vcpkg.cmake"_

(step 3) I rebuild this, but the same error came out.
What I should have done? Is there anything I miss?

**Comment by NancyLi1013** [comment] 2020-05-27 08:53
Based on the original issue you met, you need to update vcpkg use `git pull` first, `vcpkg update` is not needed in this case.

Please also remove `msys2` from _vcpkg_root/downloads_ and _vcpkg_root/downloads/tools/_  then try to rebuild.

As for vcpkg update, you might refer to this [doc](https://github.com/microsoft/vcpkg/blob/master/docs/about/faq.md#how-do-i-update-libraries) to learn more about this command.

Note: On your machine, vcpkg_root path is _C:\Users\dlwns\Documents\slam6d-code-r2223-trunk\slam6d-code-r2223-trunk\build\3rdparty\vcpkg_.

If you want to use this `powershell`, you need to open `powershell `in vcpkg_root directory.
`./vcpkg integrate install` is not needed currently. After you installed the ports successfully, you can execute this command.

**Comment by OneOfMyClassmate** [comment] 2020-05-27 13:25
I see, so I did what you said.

First, I updated vcpkg by using _git pull_.

_vcpkg_root>git init
_vcpkg_root>git pull http://github.com/microsoft/vcpkg.git_

Second, I removed _msys2_ from _vcpkg_root/downloads_ and _vcpkg/downloads/tools_, and tried to rebuild.

When I rebuild my project, I used _build.cmd_ located in _C:/Users/dlwns/Documents/slam6d-code-r2223-trunk/slam6d-code-r2223-trunk_ on git CMD . This file should be used as :
> build [srcDir] [outDir]

But, the same error still comes out. Then, what else I should do to fix it?

**Comment by NancyLi1013** [comment] 2020-05-28 08:38
You should only use `git pull` to update without anything else.
The usage like this:
```
PS F:\test\vcpkg> git pull
remote: Enumerating objects: 31, done.
remote: Counting objects: 100% (31/31), done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 37 (delta 24), reused 24 (delta 22), pack-reused 6
Unpacking objects: 100% (37/37), done.
From https://github.com/Microsoft/vcpkg
   ea07b5d3c..d9b4acf02  master     -> origin/master
Updating ea07b5d3c..d9b4acf02
Fast-forward
 ports/ace/CONTROL                                  |  3 +-
 ports/ace/portfile.cmake                           | 15 +++++-----
 ports/libpopt/CONTROL                              |  2 +-
 ports/libpopt/portfile.cmake                       |  6 +---
 scripts/azure-pipelines/linux/azure-pipelines.yml  |  1 +
 scripts/azure-pipelines/osx/azure-pipelines.yml    |  1 +
 .../azure-pipelines/windows/azure-pipelines.yml    |  7 +++++
 scripts/ci.baseline.txt                            | 10 -------
 toolsrc/include/vcpkg/commands.h                   |  5 ++++
 toolsrc/src/vcpkg/commands.ci.cpp                  | 10 ++-----
 toolsrc/src/vcpkg/commands.ciclean.cpp             | 32 ++++++++++++++++++++++
 toolsrc/src/vcpkg/commands.cpp                     |  1 +
 toolsrc/vcpkglib/vcpkglib.vcxproj                  |  1 +
 toolsrc/vcpkglib/vcpkglib.vcxproj.filters          |  3 ++
 14 files changed, 63 insertions(+), 34 deletions(-)
 create mode 100644 toolsrc/src/vcpkg/commands.ciclean.cpp
```
If you have updated to the latest, it will show:
```
PS F:\test\vcpkg> git pull
Already up to date.
```
Could you please clone vcpkg to another directory and rebuild this port?

**Comment by OneOfMyClassmate** [comment] 2020-05-31 08:34
Thanks for your advice, Nancy!
I solved this problem. What I found out was that the path was too long for Windows to find. So I changed _vcpkg_root_ path from _C:\Users\dlwns\Documents\slam6d-code-r2223-trunk\slam6d-code-r2223-trunk\build\3rdparty\vcpkg_ to _C:\slam6d\build\3rdparty\vcpkg_. This was all that I did, and the error did not occur.
However, I am really curious about why the root path affects what I wanted to do. Do you know why?

**Comment by NancyLi1013** [comment] 2020-06-04 10:05
Since windows has the limit to the path length. 
Please refer to this [doc](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#maximum-path-length-limitation) to learn more about this.

**Comment by NancyLi1013** [comment] 2020-06-10 01:45
Personally, this issue has been solved, I'm closing this issue for now.
Please open a new issue if you have any other problem when using vcpkg.

**Closed by NancyLi1013** 2020-06-10 01:45 UTC
Labels: category:question

**Comment by Davichet-e** [comment] 2020-06-23 16:32
I've the same problem, but making shorter the PATH does not help. Actually `VCPKG_ROOT=C:\Program Files\vcpkg` and all other info about the error is the same as above. I tried also `git pull` but all is up to date.
> 
> 
> Based on the original issue you met, you need to update vcpkg use `git pull` first, `vcpkg update` is not needed in this case.
> 
> Please also remove `msys2` from _vcpkg_root/downloads_ and _vcpkg_root/downloads/tools/_ then try to rebuild.
> 
> As for vcpkg update, you might refer to this [doc](https://github.com/microsoft/vcpkg/blob/master/docs/about/faq.md#how-do-i-update-libraries) to learn more about this command.
> 
> Note: On your machine, vcpkg_root path is _C:\Users\dlwns\Documents\slam6d-code-r2223-trunk\slam6d-code-r2223-trunk\build\3rdparty\vcpkg_.
> 
> If you want to use this `powershell`, you need to open `powershell `in vcpkg_root directory.
> `./vcpkg integrate install` is not needed currently. After you installed the ports successfully, you can execute this command.

I also tried this but it does not help either. Quite confused, any advise?

**Comment by NancyLi1013** [comment] 2020-06-24 02:18
@Davichet-e 
Could you please help confirm if the root cause of your problem is the same as that of this issue?

This issue is caused by `msys2`, the error like this:
```
error: could not open file /var/cache/pacman/pkg/libgdbm-1.18.1-3-x86_64.pkg.tar.zst: Child process exited with status 127
error: could not open file /var/cache/pacman/pkg/gdbm-1.18.1-3-x86_64.pkg.tar.zst: Child process exited with status 127
error: failed to commit transaction (cannot open package file)
```

This issue has been fixed in current master branch.

If you downloaded `msys2 `before this and still encountered this issue, please remove `msys2` and rebuild it again.

If you have new problems for `icu`, please open a new issue to track it.

**Comment by Davichet-e** [comment] 2020-06-26 17:41
@NancyLi1013 Two days later, I updated using `git pull` and now it worked.
```
From https://github.com/Microsoft/vcpkg
   aef838536..9f8cc9ee8  master     -> origin/master
```
All good now. Have a great day.
