### ISSUE TITLE
ceres[suitesparse]:x64-windows build failure

### ISSUE THREAD

**Issue by spindensity** [microsoft/vcpkg#8336] opened 2019-09-25 13:39 UTC
**Host Environment**
- OS: Windows 10 1903
- MSVC 2019 16.3.0

**To Reproduce**
```
vcpkg install suitesparse[metis]:x64-windows
vcpkg install ceres[suitesparse]:x64-windows
```

**Failure logs** 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3652742/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/3652743/install-x64-windows-dbg-out-1.log)

**Additional context**
If suitesparse package built with metis installed first, ceres[suitesparse] can't be built successfully.

**Comment by JackBoosY** [comment] 2019-09-26 06:52
@spindensity, thanks for reporting this issue!
Sadly, I cannot repro it in my machine, but I found something interesting:
`LINK : fatal error LNK1104: cannot open file 'SuiteSparse::metis.lib'`

So, for deep positioning of this problem, please provide the configure log file:
`configure-x64-windows-dbg-out.log`/`configure-x64-windows-dbg-err.log`

Thanks.

**Comment by spindensity** [comment] 2019-09-26 09:48
OK, hope it helps.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/3657127/config-x64-windows-out.log)

`config-x64-windows-err.log` is an empty file.

**Comment by JackBoosY** [comment] 2019-09-26 10:05
```
CMake Warning (dev) at C:/Dev/BasicTools/vcpkg/scripts/buildsystems/vcpkg.cmake:195 (_add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "ceres" links to target "SuiteSparse::metis" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  internal/ceres/CMakeLists.txt:205 (add_library)
```
Interesting... Can you remove suitesparse, update vcpkg and rebuild suitesparse?

**Comment by spindensity** [comment] 2019-09-26 12:47
@JackBoosY 

Ok, I deleted `buildtrees`, `installed`, `packages` directories, updated vcpkg, rebuilt related packages and upload all screenshots and logs here. Hope this helps.

# Update vcpkg

![Snipaste_2019-09-26_20-07-28](https://user-images.githubusercontent.com/33576822/65688399-a721ac80-e09d-11e9-95b0-a0ef265c9e3a.png)
![Snipaste_2019-09-26_20-21-12](https://user-images.githubusercontent.com/33576822/65688419-ac7ef700-e09d-11e9-8cae-9900f1bac21d.png)

# Build `suitesparse[metis]`
![Snipaste_2019-09-26_20-22-20](https://user-images.githubusercontent.com/33576822/65688525-e3550d00-e09d-11e9-8e16-ce3ec64f0d1f.png)
![Snipaste_2019-09-26_20-23-18](https://user-images.githubusercontent.com/33576822/65688604-fff14500-e09d-11e9-99e0-3e2ad79fb308.png)
![Snipaste_2019-09-26_20-23-39](https://user-images.githubusercontent.com/33576822/65688619-054e8f80-e09e-11e9-9a46-07cfb9251be2.png)
![Snipaste_2019-09-26_20-24-40](https://user-images.githubusercontent.com/33576822/65688628-0bdd0700-e09e-11e9-9bce-04384f3dd865.png)
![Snipaste_2019-09-26_20-25-04](https://user-images.githubusercontent.com/33576822/65688640-0f708e00-e09e-11e9-8330-c595d451a1e9.png)

# Build `ceres[suitesparse]`
![Snipaste_2019-09-26_20-28-13](https://user-images.githubusercontent.com/33576822/65688810-51013900-e09e-11e9-9da4-437ae5fc2b28.png)
![Snipaste_2019-09-26_20-28-34](https://user-images.githubusercontent.com/33576822/65688826-55c5ed00-e09e-11e9-8cc4-9fd79e0f4677.png)
![Snipaste_2019-09-26_20-29-04](https://user-images.githubusercontent.com/33576822/65688838-5a8aa100-e09e-11e9-9e6b-d757a7922231.png)
![Snipaste_2019-09-26_20-29-23](https://user-images.githubusercontent.com/33576822/65688852-5f4f5500-e09e-11e9-870c-add62c380040.png)
![Snipaste_2019-09-26_20-30-19](https://user-images.githubusercontent.com/33576822/65688857-62e2dc00-e09e-11e9-83ef-74ce389a894b.png)
![Snipaste_2019-09-26_20-30-36](https://user-images.githubusercontent.com/33576822/65688882-6ece9e00-e09e-11e9-829f-fa1d6cd82eca.png)

# Logs

[metis_logs.zip](https://github.com/microsoft/vcpkg/files/3657736/metis_logs.zip)
[suitesparse_logs.zip](https://github.com/microsoft/vcpkg/files/3657738/suitesparse_logs.zip)
[ceres_logs.zip](https://github.com/microsoft/vcpkg/files/3657739/ceres_logs.zip)

**Comment by JackBoosY** [comment] 2019-09-27 10:09
Please provide your generated cmake files in _C:/Dev/BasicTools//vcpkg/packages/suitesparse_x64-windows/share/suitesparse_.

Thanks.

**Comment by spindensity** [comment] 2019-09-27 11:33
@JackBoosY 

[cmakefiles.zip](https://github.com/microsoft/vcpkg/files/3662521/cmakefiles.zip)

**Comment by janholt** [comment] 2019-09-27 17:56
Possible solution is

- add cmake config file for metis;
- make suitesparse to find metis by find_package, and declare metis as its dependence in suitesparse-config.cmake.

**Comment by JackBoosY** [comment] 2019-09-29 02:45
Confirmed, no target `SuiteSparse::metis` are found in _suitesparse-targets-debug/release.cmake_.

**Comment by JackBoosY** [comment] 2019-10-08 09:51
Hi @spindensity, thanks for reporting this issue.
Since #8376 has been merged, this issue should be fixed.
Please update vcpkg and rebuild ceres[suitesparse].

Thanks.

**Closed by JackBoosY** 2019-10-08 09:51 UTC
Labels: port bug
