### ISSUE TITLE
Could not locate a complete Visual Studio instance

### ISSUE THREAD

**Issue by jinkilee** [microsoft/vcpkg#38970] opened 2024-05-28 03:04 UTC
### Operating system

Windows 10 (22H2, 19045.4412)

### Steps to reproduce the behavior

```Shell
# 1. the content of Dockerfile.1
----
ARG BASE_IMAGE=mcr.microsoft.com/windows:10.0.19042.1889

FROM ${BASE_IMAGE}
SHELL ["cmd", "/S", "/C"]

RUN mkdir c:\tmp
WORKDIR /tmp

### step2: install choco and something
RUN powershell.exe Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine
RUN powershell.exe [Net.ServicePointManager]::Expect100Continue=$true;[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls,[Net.SecurityProtocolType]::Tls11,[Net.SecurityProtocolType]::Tls12,[Net.SecurityProtocolType]::Ssl3;Invoke-Expression( New-Object System.Net.WebClient ).DownloadString('https://chocolatey.org/install.ps1')
RUN choco install git docker unzip -y

### step3: install cmake
ARG CMAKE_VERSION=3.27.1
ARG CMAKE_FILE=cmake-${CMAKE_VERSION}-windows-x86_64
ARG CMAKE_SOURCE=https://github.com/Kitware/CMake/releases/download/v${CMAKE_VERSION}/${CMAKE_FILE}.zip
ADD ${CMAKE_SOURCE} ${CMAKE_FILE}.zip
RUN unzip %CMAKE_FILE%.zip
RUN move %CMAKE_FILE% "c:\CMake"
RUN setx PATH "c:\CMake\bin;%PATH%"

### step3: some environment variables
ENV CMAKE_TOOLCHAIN_FILE /vcpkg/scripts/buildsystems/vcpkg.cmake
ENV VCPKG_TARGET_TRIPLET x64-windows
LABEL CMAKE_VERSION=${CMAKE_VERSION}

### step4: install python
# Be aware that pip can interact badly with VS cmd shell so need to pip install before
# vsdevcmd.bat (see https://bugs.python.org/issue38989)
ARG PYTHON_VERSION=3.8.10
ARG PYTHON_SOURCE=https://www.python.org/ftp/python/${PYTHON_VERSION}/python-${PYTHON_VERSION}-amd64.exe
ADD ${PYTHON_SOURCE} python-${PYTHON_VERSION}-amd64.exe
RUN python-%PYTHON_VERSION%-amd64.exe /quiet InstallAllUsers=1 PrependPath=1 Include_doc=0 TargetDir="C:\python%PYTHON_VERSION%"
RUN mklink "C:\python%PYTHON_VERSION%\python3.exe" "C:\python%PYTHON_VERSION%\python.exe"
RUN pip install --upgrade wheel setuptools docker
RUN pip install grpcio-tools
LABEL PYTHON_VERSION=${PYTHON_VERSION}

### step5: install build tools
ARG BUILDTOOLS_VERSION=17.7.34024.191
ADD https://aka.ms/vscollect.exe "C:\tmp\collect.exe"
ARG CHANNEL_URL=https://aka.ms/vs/17/release/channel
ADD ${CHANNEL_URL} "C:\tmp\VisualStudio.chman"
ARG BUILD_TOOLS_SOURCE=https://aka.ms/vs/17/release/vs_buildtools.exe
ADD ${BUILD_TOOLS_SOURCE} vs_buildtools.exe
ARG VS_INSTALL_PATH_WP="C:\BuildTools"
RUN vs_buildtools.exe --quiet --wait --norestart --nocache install --installPath %VS_INSTALL_PATH_WP% --channelUri "C:\tmp\VisualStudio.chman" --installChannelUri "C:\tmp\VisualStudio.chman" --add Microsoft.VisualStudio.Workload.VCTools --includeRecommended --locale "En-us"
LABEL BUILDTOOLS_VERSION=${BUILDTOOLS_VERSION}

### step6: install vcpkage
WORKDIR /
ARG VCPGK_VERSION=2023.07.21
RUN git clone --single-branch --depth=1 -b %VCPGK_VERSION% https://github.com/microsoft/vcpkg.git
WORKDIR /vcpkg
RUN bootstrap-vcpkg.bat
RUN vcpkg.exe update
RUN vcpkg.exe install openssl:x64-windows openssl-windows:x64-windows rapidjson:x64-windows re2:x64-windows boost-interprocess:x64-windows boost-stacktrace:x64-windows zlib:x64-windows pthread:x64-windows b64:x64-windows
RUN vcpkg.exe integrate install

### step7: finally finished
CMD C:\BuildTools\VC\Auxiliary\Build\vcvars64.bat &&
----

# 2. build docker
docker build -t win10-1 -f Dockerfile.1 .
```

### Failure logs

Step 47/49 : RUN vcpkg.exe install openssl:x64-windows openssl-windows:x64-windows rapidjson:x64-windows re2:x64-windows boost-interprocess:x64-windows boost-stacktrace:x64-windows zlib:x64-windows pthread:x64-windows b64:x64-windows
 ---> Running in 52cdbc9a5756
Computing installation plan...
The following packages will be built and installed:
    b64:x64-windows -> 2.0.0.1#2
  * boost-array:x64-windows -> 1.82.0#2
  * boost-assert:x64-windows -> 1.82.0#2
  * boost-build:x64-windows -> 1.82.0#2
  * boost-config:x64-windows -> 1.82.0#2
  * boost-container:x64-windows -> 1.82.0#2
  * boost-container-hash:x64-windows -> 1.82.0#2
  * boost-core:x64-windows -> 1.82.0#2
  * boost-describe:x64-windows -> 1.82.0#2
    boost-interprocess:x64-windows -> 1.82.0#2
  * boost-intrusive:x64-windows -> 1.82.0#2
  * boost-modular-build-helper:x64-windows -> 1.82.0#4
  * boost-move:x64-windows -> 1.82.0#2
  * boost-mp11:x64-windows -> 1.82.0#2
  * boost-predef:x64-windows -> 1.82.0#2
  * boost-preprocessor:x64-windows -> 1.82.0#2
    boost-stacktrace:x64-windows -> 1.82.0#2
  * boost-static-assert:x64-windows -> 1.82.0#2
  * boost-throw-exception:x64-windows -> 1.82.0#2
  * boost-tuple:x64-windows -> 1.82.0#2
  * boost-type-traits:x64-windows -> 1.82.0#2
  * boost-uninstall:x64-windows -> 1.82.0#2
  * boost-unordered:x64-windows -> 1.82.0#2
  * boost-vcpkg-helpers:x64-windows -> 1.82.0#2
  * boost-winapi:x64-windows -> 1.82.0#2
    openssl:x64-windows -> 3.1.1#1
    openssl-windows:x64-windows -> deprecated
    pthread:x64-windows -> 3.0.0#2
  * pthreads:x64-windows -> 3.0.0#14
    rapidjson:x64-windows -> 2023-04-27
    re2:x64-windows -> 2023-02-01
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-config:x64-windows -> 2022-02-06#1
  * vcpkg-cmake-get-vars:x64-windows -> 2023-03-02
    zlib:x64-windows -> 1.2.13
Additional packages (*) will be modified to complete this operation.
error: in triplet x64-windows: Unable to find a valid Visual Studio instance
Could not locate a complete Visual Studio instance
The following paths were examined for Visual Studio instances:
    C:\BuildTools\VC\Auxiliary/Build\vcvarsall.bat

### Additional context

To fix it, I tried the followings, but none of them works. (https://github.com/microsoft/vcpkg/issues/22074)
1. https://github.com/microsoft/vcpkg/issues/22074#issuecomment-1022840591

RUN vs_buildtools.exe --quiet --wait --norestart --nocache install \
	--installPath %VS_INSTALL_PATH_WP% \
	--channelUri C:\tmp\VisualStudio.chman \
	--installChannelUri C:\tmp\VisualStudio.chman \
	--add Microsoft.VisualStudio.Component.Windows10SDK \
	--add Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core \
	--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
	--add Microsoft.Component.MSBuild \
	--add Microsoft.VisualStudio.Component.Windows10SDK.19041 \
	--locale "En-us"

2. https://github.com/microsoft/vcpkg/issues/22074#issuecomment-1667191508
RUN .\vs_buildtools.exe --quiet --wait --norestart --nocache install \
	--installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2022\BuildTools" \
	--channelUri C:\TEMP\VisualStudio.chman \
	--installChannelUri C:\TEMP\VisualStudio.chman \
	--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
	--add Microsoft.Component.MSBuild

3. execute collect.exe to collect error logs
I just skiped `vcpkg install ...` and `vcpkg integrate install` and execute `collect.exe` and got the error message from `.log`

[0a60:001e][2024-05-28T11:09:07] Package Microsoft.Net.4.8.KB5003306 is not applicable: The current OS Version '10.0.19042.0' is not in the supported version range '[10.0.18362,10.0.18363]'.
[0a60:001e][2024-05-28T11:09:07] Package Microsoft.Net.4.8.KB5003304 is not applicable: The current OS Version '10.0.19042.0' is not in the supported version range '[10.0.19041,10.0.19042)'.
[0a60:001e][2024-05-28T11:09:07] Package Microsoft.VisualStudio.NuGet.PowershellBindingRedirect is not applicable: The current OS Version '10.0.19042.0' is not in the supported version range '[6.1,6.2)'.

so I re-built docker image with `ARG BASE_IMAGE=mcr.microsoft.com/windows:10.0.19042.1889` but this also did not helped.

**Comment by MonicaLiu0311** [comment] 2024-05-29 08:33
Duplicate of #22074.

**Closed by MonicaLiu0311** 2024-05-29 08:33 UTC
Labels: category:port-bug

**Comment by MonicaLiu0311** [comment] 2024-05-29 08:35
Please discuss this in https://github.com/microsoft/vcpkg/issues/22074.
