### ISSUE TITLE
[libjpeg-turbo] Build error

### ISSUE THREAD

**Issue by sanderPostma** [microsoft/vcpkg#29297] opened 2023-01-30 21:08 UTC
**Host Environment**

Host: x64-windows
Compiler: MSVC 19.31.31107.0
vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75 vcpkg-scripts version: 91dd61bd4 2023-01-27 (3 days ago)

**To Reproduce**

vcpkg install libvpx:x64-windows-static libyuv:x64-windows-static opus:x64-windows-static

**Failure logs**
````
-- Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.4.tar.gz -> libjpeg-turbo-libjpeg-turbo-2.1.4.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.4.tar.gz
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/2.1.4.tar.gz
File: C:\-DEV\3rd-party\vcpkg\downloads\libjpeg-turbo-libjpeg-turbo-2.1.4.tar.gz.21280.part
Expected hash: d3e92d614168355827e0ed884ff847cc7df8f6f1fb7b673c6c99afdf61fdfc0372afe5d30fdbf5e743335e2a7a27ca9f510c67d213e5cb2315a8d946e9414575
Actual hash: 4ccf20aa95b9bd5737191049aea33c8b8aeff768cc5f042e4a9aa184dbe5003f34237e14ba4d7bc2f68209c368341ed4759f491d8eb00dc91b17289042abe411
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956): 
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 7 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 1135 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 490.2 ms (483345 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/libjpeg-turbo/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)
````
**Additional context**

Not using any proxy or VPN.

**Comment by BillyONeal** [comment] 2023-01-30 21:13
Duplicate of https://github.com/microsoft/vcpkg/issues/29288

**Closed by BillyONeal** 2023-01-30 21:13 UTC
Labels: category:port-bug
