### ISSUE TITLE
Error: Building package tiff:x86-uwp failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by renfengyi** [Microsoft/vcpkg#4830] opened 2018-11-27 08:50 UTC
PS D:\Software\Hololens-SpeactorView-iPad\github\vcpkg> .\vcpkg install opencv[contrib]:x86-uwp --recurse
The following packages will be built and installed:
    opencv[contrib,core,eigen,flann,jpeg,opengl,png,tiff]:x86-uwp
  * tiff[core]:x86-uwp
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: tiff:x86-uwp
Building package tiff[core]:x86-uwp...
-- Using cached D:/Software/Hololens-SpeactorView-iPad/github/vcpkg/downloads/tiff-4.0.10.tar.gz
-- Using source at D:/Software/Hololens-SpeactorView-iPad/github/vcpkg/buildtrees/tiff/src/4.0.10-208d032666
-- Configuring x86-uwp
-- Building x86-uwp-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: D:/Software/Hololens-SpeactorView-iPad/github/vcpkg/downloads/tools/cmake-3.12.4-windows/cmake-3.12.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: D:/Software/Hololens-SpeactorView-iPad/github/vcpkg/buildtrees/tiff/x86-uwp-dbg
    See logs for more information:
      D:\Software\Hololens-SpeactorView-iPad\github\vcpkg\buildtrees\tiff\install-x86-uwp-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/tiff/portfile.cmake:37 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package tiff:x86-uwp failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: tiff:x86-uwp
  Vcpkg version: 2018.11.23-nohash

**Comment by Voskrese** [comment] 2018-11-28 05:29
https://github.com/Microsoft/vcpkg/search?q=tiff%3Ax86-uwp&type=Issues

**Comment by NancyLi1013** [comment] 2019-03-22 08:02
@renfengyi , thank you for posting this issue.  Could you please try it again on your machine? 
I can install it successfully on my machine now.

**Comment by NancyLi1013** [comment] 2019-04-02 07:50
@renfengyi, this port has been updated. I cannot reproduce it now. So this issue should be fixed. Please open a new issue or reopen this if this is still a problem for you.

**Closed by NancyLi1013** 2019-04-02 07:50 UTC
Labels: port bug
