### ISSUE TITLE
Failed at [C:\vcpkg\toolsrc\src\vcpkg\vcpkglib.cpp(216)] with message: no such file or directory

### ISSUE THREAD

**Issue by psionic12** [microsoft/vcpkg#12389] opened 2020-07-12 11:05 UTC
Currently I installed WSL (ubuntu version) on my pc, and use the commands as blow to create a Linux version of vcpkg executable:

```
cd /mnt/c/vcpkg
./bootstrap-vcpkg.sh
```

after this, no matters what packages I want install, it will build, while failed with an error when installing:
```
Failed at [../src/vcpkg/vcpkglib.cpp(216)] with message:
No such file or directory
```

for example of `./vcpkg install tinyxml2:x64-linux`:

```
Computing installation plan...
The following packages will be built and installed:
    tinyxml2[core]:x64-linux
Starting package 1/1: tinyxml2:x64-linux
Building package tinyxml2[core]:x64-linux...
-- Using cached /mnt/c/vcpkg/downloads/leethomason-tinyxml2-8.0.0.tar.gz
-- Using source at /mnt/c/vcpkg/buildtrees/tinyxml2/src/8.0.0-5a686de2e4
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig
-- Fixing pkgconfig - release
-- Checking file: /mnt/c/vcpkg/packages/tinyxml2_x64-linux/lib/pkgconfig/tinyxml2.pc
-- Fixing pkgconfig - debug
-- Checking file: /mnt/c/vcpkg/packages/tinyxml2_x64-linux/debug/lib/pkgconfig/tinyxml2.pc
-- Fixing pkgconfig --- finished
-- Installing: /mnt/c/vcpkg/packages/tinyxml2_x64-linux/share/tinyxml2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package tinyxml2[core]:x64-linux... done
Installing package tinyxml2[core]:x64-linux...
Failed at [../src/vcpkg/vcpkglib.cpp(216)] with message:
No such file or directory
```

**Comment by psionic12** [comment] 2020-07-12 11:06
I want to debug with GDB to find what's going on in vcpkglib.cpp, but the GDB said that vcpkg do not have symbols:

```
(gdb) file ./vcpkg
Reading symbols from ./vcpkg...(no debugging symbols found)...done.
```

I'd like to help, so can anyone tells me how to debug vcpkg (either on Linux or Windows)?

**Comment by psionic12** [comment] 2020-07-12 11:49
Anybody knows how to build a debug version of VCPKG? It seems that it only build a release one with out debug symbols.

**Comment by Voskrese** [comment] 2020-07-12 11:54
`./vcpkg install tinyxml2:x64-linux --debug`
?

**Comment by psionic12** [comment] 2020-07-12 12:01
@Voskrese I mean debug version of executable "vcpkg"

**Comment by Voskrese** [comment] 2020-07-12 12:05
why? what will it give?

open `.../src/vcpkg/vcpkglib.cpp` -- `str (216)`

open **portfile tinyxml2**

`vcpkg edit tinyxml2`

**Comment by psionic12** [comment] 2020-07-12 16:06
@Voskrese 
It gives me debug symbols so that I can debug with GDB because I cannot figure out what's wrong just from the source file.

**Comment by NancyLi1013** [comment] 2020-07-15 07:39
Hi @psionic12 
Thanks for posting this issue.

@ras0219-msft 
Could you please help take a look about this issue?

**Comment by psionic12** [comment] 2020-07-15 07:53
@NancyLi1013 I found that if the error happened, both Windows and WSL sides will report `No such file or directory` error, I had to deleted the vcpkg directory and re-download the whole project.

And what's more, I use x64-windows triplet.

Hope these can help you.

**Comment by NancyLi1013** [comment] 2020-07-15 09:03
@psionic12 
Thanks for your above info.
I cannot reproduce this issue on Windows, WSL and Linux.
On WSL and Linux, you should use x64-linux triplet and on Windows, it should be x64-windows.

Could you please try to rebuild this in a new vcpkg repo?

**Comment by psionic12** [comment] 2020-07-15 10:59
Hi @NancyLi1013, did you use the same vcpkg directory both in Windows and WSL? I may not mentioned clearly, here are more details:

I put my vcpkg project at `C:\`, and it works well. And then I enable the WSL and installed Ubuntu 18.04 from Windows Store.

Then I accessed the vcpkg folder (which is originally on Windows `C:/`) from `/mnt/c/vcpkg` (where the C partition mounted), then run the script ` bootstrap-vcpkg.sh`

The key information here is that I use the exactly the same vcpkg through different systems.

**Comment by NancyLi1013** [comment] 2020-07-20 07:44
@psionic12 
Thanks for clarifying this. Now I see what you want to express.
But I didn't encounter the same error with you.

```
vruil@ruiltest01:/mnt/f/tools/vcpkg$ ./vcpkg install tinyxml2:x64-linux
Computing installation plan...
The following packages will be built and installed:
    tinyxml2[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: tinyxml2:x64-linux
Building package tinyxml2[core]:x64-linux...
Could not locate cached archive: /home/vruil/.cache/vcpkg/archives/64/6415a0267e4ce38392d7d424b7cc05d72f1524c5.zip
-- Using cached /mnt/f/tools/vcpkg/downloads/leethomason-tinyxml2-8.0.0.tar.gz
-- Cleaning sources at /mnt/f/tools/vcpkg/buildtrees/tinyxml2/src/8.0.0-5a686de2e4.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /mnt/f/tools/vcpkg/downloads/leethomason-tinyxml2-8.0.0.tar.gz
-- Applying patch fix-symbol-exports.patch
-- Applying patch fix-debug-postfix.patch
-- Using source at /mnt/f/tools/vcpkg/buildtrees/tinyxml2/src/8.0.0-5a686de2e4.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig
-- Fixing pkgconfig - release
-- Checking file: /mnt/f/tools/vcpkg/packages/tinyxml2_x64-linux/lib/pkgconfig/tinyxml2.pc
-- Fixing pkgconfig - debug
-- Checking file: /mnt/f/tools/vcpkg/packages/tinyxml2_x64-linux/debug/lib/pkgconfig/tinyxml2.pc
-- Fixing pkgconfig --- finished
-- Installing: /mnt/f/tools/vcpkg/packages/tinyxml2_x64-linux/share/tinyxml2/copyright
-- Performing post-build validation
-- Performing post-build validation done
sh: 1: zip: not found
Failed to store binary cache /home/vruil/.cache/vcpkg/archives/64/6415a0267e4ce38392d7d424b7cc05d72f1524c5.zip: Invalid cross-device link
Building package tinyxml2[core]:x64-linux... done
Installing package tinyxml2[core]:x64-linux...
Installing package tinyxml2[core]:x64-linux... done
Elapsed time for package tinyxml2:x64-linux: 9.753 s

Total elapsed time: 12.48 s
```

**Comment by psionic12** [comment] 2020-07-20 07:56
well... so you can use the same directory both in windows and WSL, right?

By the way do you know how to build a debug version of vcpkg executable on Ubuntu? With debug version with debug symbols I may figure out what happened in my case.

**Comment by NancyLi1013** [comment] 2020-07-21 08:51
You might try to use `gdb `to debug. 
BTW, does this issue only happen on `tinyxml2 `or not?

**Comment by NancyLi1013** [comment] 2020-07-23 02:19
I'm sorry, I have no idea about this now.
Could you please try to clone vcpkg to another directory (which is not in _C:_) and rebuild this again?

**Comment by NancyLi1013** [comment] 2020-08-07 10:12
Does this issue still exist on your machine?

**Comment by psionic12** [comment] 2020-08-08 10:04
Yes it does, and currently I use two machines for different operating system, I think it's acceptable to close this issue if no others occurs this problem.

**Comment by NancyLi1013** [comment] 2020-08-13 06:38
Considering this special case and I cannot reproduce it. So I'm closing this issue for now.

Please feel free to reopen it if anyone else also happens the same problem.

**Closed by NancyLi1013** 2020-08-13 06:38 UTC
Labels: requires:repro
