### ISSUE TITLE
Pango headers are no longer being found

### ISSUE THREAD

**Issue by Pentarctagon** [microsoft/vcpkg#17537] opened 2021-04-27 14:34 UTC
**Describe the bug**
For Wesnoth's CI jobs we had a successful Windows CI job 22 hours ago, and then starting with the next build 13 hours ago it is failing with the error `fatal error C1083: Cannot open include file: 'pango/pango.h': No such file or directory`.  This seems to correspond with 546813ae7b9e2873dd3d38e78b27ac5582feae10.

**Environment**
- OS: Windows
- Compiler: Whatever the compiler version used for `windows-2019` jobs in github actions.

**To Reproduce**
1. Attempt to compile a C++ file that `#include`s the pango header.

**Expected behavior**
The build does not fail.

**Failure logs** 
https://github.com/wesnoth/wesnoth/runs/2443782276

**Comment by Neumann-A** [comment] 2021-04-27 20:14
How do you try to link or find headers of pango?

**Comment by Pentarctagon** [comment] 2021-04-27 20:32
We are not using cmake to build - we have projectfiles for VS2019 at https://github.com/wesnoth/wesnoth/tree/master/projectfiles/VC16 and have previously only needed to do the steps listed in the README for the build to succeed.

**Comment by Neumann-A** [comment] 2021-04-27 20:53
Yeah the lazy VS integration is broken in more than just that but I won't be fixing that....
The pango headers have been "moved"/correctly installed to the upstream intended install location nothing more. 
If somebody from the MS team decides to move them back so be it.

**Comment by Pentarctagon** [comment] 2021-04-27 20:56
If you don't intend to fix it, then what is the correct solution?

**Comment by Neumann-A** [comment] 2021-04-27 21:14
> If you don't intend to fix it, then what is the correct solution?

Depends on what you want to hear:
a) Commit to one buildsystem like CMake instead of 6? and improve the quality of your CMake buildscripts
b) add `$(_ZVcpkgCurrentInstalledDir)include/pango-1.0` to the additional include directories in the vs solution? (But you probably need to add more than that since some deps also have been moved into an API/versioned include folder
c) use vcpkg with manifest mode so that people don't need to manually install your deps. 

But the correct solution is probably for the VS integration to use the pkgconfig information of the relevant ports for include and linkage.

**Comment by Pentarctagon** [comment] 2021-04-27 21:38
(c) sounds like a generally useful thing to do anyway, so if that solves this problem as well then even better.

**Comment by Neumann-A** [comment] 2021-04-27 21:45
(c) was just an addon and no solution

**Comment by Pentarctagon** [comment] 2021-04-27 21:50
So the only actual solution is either to:
a) use cmake to generate the VS2019 project files
b) manually insert (what appears to be) an internal vcpkg variable in a bunch of places

**Comment by JackBoosY** [comment] 2021-07-23 08:42
I can confirm this issue was resolved after openblas update.

**Comment by JackBoosY** [comment] 2021-07-23 08:53
Close by accident.

**Comment by MonicaLiu0311** [comment] 2023-04-21 09:06
`pango` has been updated to `1.50.14`, this issue will be closed; if it is still an issue, please reopen.

**Closed by MonicaLiu0311** 2023-04-21 09:06 UTC
Labels: category:port-bug
