### ISSUE TITLE
[libpng] Build apng optional feature failed with --clean-after-build option

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#9849] opened 2020-01-30 19:59 UTC
**Describe the bug**
libpng with apng optional feature fails on new vcpkg install or vcpkg with --clean=after-build

**Environment**
- OS: [Windows 10 Pro x64 Version 1909 18363.628]
- Compiler: VS2017 v15.9.19 VCToolsVersion=14.16.27023
                   VS2019 v16.4.3 VCToolsVersion=14.24.28314

**To Reproduce**
**1.** SYSTEM@ANDROMEDA 01/30/2020 14:49:35 D:\Git\vs2019.test
```
->vcpkg install libpng[core,apng]
The following packages will be built and installed:
    libpng[apng,core]:x64-windows
Starting package 1/1: libpng:x64-windows
Building package libpng[apng,core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/libpng-1.6.37-apng.patch.gz
-- Using cached E:/Git/vcpkg.downloads/glennrp-libpng-v1.6.37.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:97 (file):
  file SHA512 failed to read file
  "D:/Git/vs2019.test/buildtrees/libpng/src/libpng-1.6.37-apng.patch": No
  such file or directory
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/libpng/portfile.cmake:30 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)

Error: Building package libpng:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpng:x64-windows
  Vcpkg version: 2020.01.17-nohash-external

Additionally, attach any relevant sections from the log files above.
```
**2.** Reviewing the portfile.cmake (attached) it appears the install is trying to download a patch to the buildtrees\libpng\src directory before that directory exists.

[portfile.cmake.txt](https://github.com/microsoft/vcpkg/files/4135982/portfile.cmake.txt)

**Expected behavior**
Should install libpng core and apng optional feature at the same time.

**Failure logs** 
_No logs produced._

**Additional context**
If you perform the following:
1. .\vcpkg install libpng[core]
2. .\vcpkg install libpng[apng] --recurse

One can get both the core and apng feature installed (unless you use the --clean-after-build option as it removes the buildtrees\libpng directory) as the download location buildtrees\libpng\src directory exists to to store the the apng patch .

**Comment by NancyLi1013** [comment] 2020-02-04 14:19
Hi @timautry thanks for posting this issue.
I try to build this with the following commands：
First, I used `.\vcpkg install libpng[core,apng]`, it can be built successfully.
Then I used` .\vcpkg remove libpng[core,apng] --recurse`.
At last, I used `.\vcpkg install libpng[core,apng] --clean-after-build`. It can be built successfully too.

So I cannot reproduce this on my local.
Could you please help confirm if the steps I used are correct? Or I missed something from your description?

**Comment by timautry** [comment] 2020-02-04 14:37
It only happens if the .\buildtrees\libpng\src folder doesn't exist - I can repeat it over and over.
Make sure the .\buildtrees\libpng\src foloder does not exist - if it exists, then delete it, then try it again.
The portfile.cmake is definitely trying to put the apng patch (libpng-1.6.37-apng.patch) in .\buildtrees\libpng\src
I just created a fresh install of vcpkg and tried again:
.\vcpkg install libpng[core,apng] zlib[core]
SYSTEM@ANDROMEDA 02/04/2020  9:09:44 D:\Git\vs2019.test
->vcpkg install libpng[core,apng] zlib[core]
Computing installation plan...
The following packages will be built and installed:
    libpng[apng,core]:x64-windows
    zlib[core]:x64-windows
Starting package 1/2: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source E:/Git/vcpkg.downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Using source at D:/Git/vs2019.test/buildtrees/zlib/src/1.2.11-f690224aeb
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Git/vs2019.test/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x64-windows... done
Installing package zlib[core]:x64-windows...
Installing package zlib[core]:x64-windows... done
Elapsed time for package zlib:x64-windows: 7.662 s
Starting package 2/2: libpng:x64-windows
Building package libpng[apng,core]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/libpng-1.6.37-apng.patch.gz
-- Using cached E:/Git/vcpkg.downloads/glennrp-libpng-v1.6.37.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:97 (file):
  file SHA512 failed to read file
  "D:/Git/vs2019.test/buildtrees/libpng/src/libpng-1.6.37-apng.patch": No
  such file or directory
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:139 (vcpkg_extract_source_archive_ex)
  ports/libpng/portfile.cmake:30 (vcpkg_from_github)
  scripts/ports.cmake:90 (include)


Error: Building package libpng:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libpng:x64-windows
  Vcpkg version: 2020.01.18-nohash-external

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment] 2020-03-13 02:43
This issue has not been fixed. Why do you close it?

**Comment by timautry** [comment] 2020-07-14 00:04
I close, I no longer use product.

**Comment by PhoebeHui** [comment] 2020-07-14 01:28
We will close this issue after the PR merged.

**Comment by NancyLi1013** [comment] 2020-07-14 08:46
Using the latest version to rebuild and I cannot reproduce this issue now. Please try to update to the latest vcpkg to build.

**Closed by NancyLi1013** 2020-07-14 08:46 UTC
Labels: category:port-bug
