### ISSUE TITLE
[openal-soft:x86-windows] build failure

### ISSUE THREAD

**Issue by TheFloatingBrain** [microsoft/vcpkg#12325] opened 2020-07-08 09:36 UTC
**Host Environment**
- OS: Windows
- Compiler: 19.26.28806 or 19.16.27040 (2017 installed, recently installed 2019)
**To Reproduce**
`./vcpkg install sfml:x64-windows`
or
`./vcpkg upgrade --no-dry-run` (with SFML x86 installed)

**Failure logs** 
For `x64-windows`

```
Error: Building package openal-soft:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openal-soft:x64-windows
  Vcpkg version: 2020.06.15-nohash
```

For `vcpkg ugrade --no-dry-run`
```
Error: Building package openal-soft:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openal-soft:x86-windows
  Vcpkg version: 2020.06.15-nohash
```
**Relevant sections from the log files above.**

For `x64-windows`
```
Building package openal-soft[core]:x64-windows...
-- Downloading https://github.com/kcat/openal-soft/archive/a01dbeb09f0a6cdb1f2946b9fdf6c16c8b979066.tar.gz...
-- Extracting source C:/Users/TheFl/Programs/vcpkg/vcpkg/downloads/kcat-openal-soft-a01dbeb09f0a6cdb1f2946b9fdf6c16c8b979066.tar.gz
-- Applying patch dont-export-symbols-in-static-build.patch
-- Using source at C:/Users/TheFl/Programs/vcpkg/vcpkg/buildtrees/openal-soft/src/6c8b979066-d69ae4cc2c.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Users/TheFl/Programs/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/Users/TheFl/Programs/vcpkg/vcpkg/buildtrees/openal-soft/x64-windows-dbg
    See logs for more information:
      C:\Users\TheFl\Programs\vcpkg\vcpkg\buildtrees\openal-soft\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openal-soft/portfile.cmake:61 (vcpkg_install_cmake)
  scripts/ports.cmake:76 (include)
```

For `vcpkg ugrade --no-dry-run`
```
Building package openal-soft[core]:x86-windows...
-- Using cached C:/Users/TheFl/Programs/vcpkg/vcpkg/downloads/kcat-openal-soft-a01dbeb09f0a6cdb1f2946b9fdf6c16c8b979066.tar.gz
-- Cleaning sources at C:/Users/TheFl/Programs/vcpkg/vcpkg/buildtrees/openal-soft/src/6c8b979066-d69ae4cc2c.clean. Pass --editable to vcpkg to reuse sources.
-- Extracting source C:/Users/TheFl/Programs/vcpkg/vcpkg/downloads/kcat-openal-soft-a01dbeb09f0a6cdb1f2946b9fdf6c16c8b979066.tar.gz
-- Applying patch dont-export-symbols-in-static-build.patch
-- Using source at C:/Users/TheFl/Programs/vcpkg/vcpkg/buildtrees/openal-soft/src/6c8b979066-d69ae4cc2c.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/Users/TheFl/Programs/vcpkg/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/Users/TheFl/Programs/vcpkg/vcpkg/buildtrees/openal-soft/x86-windows-dbg
    See logs for more information:
      C:\Users\TheFl\Programs\vcpkg\vcpkg\buildtrees\openal-soft\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openal-soft/portfile.cmake:61 (vcpkg_install_cmake)
  scripts/ports.cmake:76 (include)
```

**Comment by TheFloatingBrain** [comment] 2020-07-08 21:39
Did a quick google and noticed this [similar issue](https://github.com/microsoft/vcpkg/issues/9431) (failed at the same line in the same script) I did not uninstall vs2017 (though I did install 2019) however restarting did not work.

**Comment by TheFloatingBrain** [comment] 2020-07-08 22:26
I just took a look at the logs, here I can see that there seems to be some sort of issue regarding a windows kit being used, the first error being: 
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(32,1): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int (compiling source file ... \vcpkg\buildtrees\openal-soft\src\6c8b979066-d69ae4cc2c.clean\al\error.cpp) [... \vcpkg\buildtrees\openal-soft\x64-windows-dbg\OpenAL.vcxproj]
```

I see a few "redefinition" errors mixed in there somewhere: 

```
4>C:\Program Files (x86)\Windows Kits\10\Include\10.0.18362.0\um\fileapifromapp.h(40,1): error C2086: 'int WINSTORAGEAPI': redefinition (compiling source file C:\Users\TheFl\Programs\vcpkg\vcpkg\buildtrees\openal-soft\src\6c8b979066-d69ae4cc2c.clean\al\error.cpp) [C:\Users\TheFl\Programs\vcpkg\vcpkg\buildtrees\openal-soft\x64-windows-dbg\OpenAL.vcxproj]
```

Could there be some issue with double consumption of the dependancy?

[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4893550/install-x86-windows-dbg-out.log)

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4893549/install-x64-windows-dbg-out.log)

**Comment by LilyWangL** [comment] 2020-07-09 02:18
Thanks for posting this issue. Closed as duplicate of #10825.

**Closed by LilyWangL** 2020-07-09 02:18 UTC
Labels: category:port-bug

**Comment by TheFloatingBrain** [comment] 2020-07-09 02:31
@LilyWangL Thank you, is there an official fix/resolution?

**Comment by LilyWangL** [comment] 2020-07-09 05:55
> @LilyWangL Thank you, is there an official fix/resolution?

Can you try #12318 changes work for you?

**Comment by TheFloatingBrain** [comment] 2020-07-11 06:48
Attempted `vcpkg.exe install --head openal-soft:x64-windows` no go :(

**Comment by LilyWangL** [comment] 2020-07-13 03:22
Waiting for #12318 merged, you can try to install openal-soft:x64-windows again.

**Comment by TheFloatingBrain** [comment] 2020-07-13 12:27
Same issue
