### ISSUE TITLE
[New Port Request] clipper2

### ISSUE THREAD

**Issue by MichaelGoulding** [microsoft/vcpkg#27236] opened 2022-10-14 16:56 UTC
Library name: clipper2

Library description: Polygon Clipping and Offsetting Library

Source repository URL: https://github.com/AngusJohnson/Clipper2

Project homepage (if different from the source repository): http://www.angusj.com/clipper2/Docs/Overview.htm

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by dg0yt** [comment] 2022-10-15 16:18
Duplicate of #26448.

**Comment by LilyWangLL** [comment] 2022-10-17 01:10
> Duplicate of #26448.

**Closed by LilyWangLL** 2022-10-17 01:10 UTC
Labels: category:new-port, info:good-first-issue
