### ISSUE TITLE
[Request] Chromium Embedded Framework (CEF)

### ISSUE THREAD

**Issue by Nemandza82** [microsoft/vcpkg#3821] opened 2018-07-01 07:06 UTC
The Chromium Embedded Framework (CEF) is a simple framework for embedding Chromium-based browsers in other applications.

The address is: https://bitbucket.org/chromiumembedded/cef

It would be very helpful if CEF could be used in vcpkg.

**Comment by jolting** [comment] 2019-04-24 19:14
Dupe of #332

**Comment by NancyLi1013** [comment] 2019-06-21 07:06
Thanks for posting this request. Please pay attention to the progress of issue #332.

**Closed by NancyLi1013** 2019-06-21 07:06 UTC
Labels: new port request - consider making a PR!
