### ISSUE TITLE
[x264] build failure: file RENAME failed to rename - because: File exists

### ISSUE THREAD

**Issue by traumedy** [microsoft/vcpkg#8632] opened 2019-10-16 20:03 UTC
**Host Environment**
- OS: [Windows 10]
- Compiler: Visual Studio 2017
- Fresh clone of VCPKG (no existing files)

**To Reproduce**
`vcpkg install x264`

**Failure logs** 
```
-- Installing x64-windows-dbg
-- Installing x64-windows-rel
CMake Error at ports/x264/portfile.cmake:37 (file):
  file RENAME failed to rename

    D:/temp/vcpkg/packages/x264_x64-windows/bin/x264.exe

  to

    D:/temp/vcpkg/packages/x264_x64-windows/tools/x264/x264.exe

  because: File exists

Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)
```

**Additional context**
Problem occurs with static and non-static triplets, x64 and x86.
Everything seems to build correctly, just the last stage of install fails?

**Comment by LilyWangL** [comment] 2019-10-17 02:54
Thanks for posting this issue. Closed as duplicate of #8473. Please pay attention to the progress of issue #8473.

**Closed by LilyWangL** 2019-10-17 02:54 UTC
Labels: port bug
