### ISSUE TITLE
CMake cache generation runs vcpkg install regardless of package changes

### ISSUE THREAD

**Issue by Pectacius** [microsoft/vcpkg#17852] opened 2021-05-12 05:10 UTC
**Describe the bug**
Regenerating CMake cache runs `vcpkg install` even though no packages have changed.

**Environment**
- OS: Windows
- Compiler: MSVC 2019

**To Reproduce**
1. Using visual studio UI which essentially runs
`"cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\%USERNAME%\<root_project_dir>\out\install\x64-Debug" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\PROFESSIONAL\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\%USERNAME%\<root_project_dir>" 2>&1"`
2. Output:
```
1> Working directory: C:\Users\%USERNAME%<root_project_dir>\out\build\x64-Debug
1> [CMake] -- Running vcpkg install
1> [CMake] Detecting compiler hash for triplet x64-windows...
1> [CMake] The following packages will be built and installed:
1> [CMake]     brotli[core]:x64-windows -> 1.0.9#1
1> [CMake]     bzip2[core]:x64-windows -> 1.0.8#1
1> [CMake]     catch2[core]:x64-windows -> 2.13.1#1
1> [CMake]     double-conversion[core]:x64-windows -> 3.1.5
1> [CMake]     egl-registry[core]:x64-windows -> 2020-02-20
1> [CMake]     freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.10.4
1> [CMake]     harfbuzz[core]:x64-windows -> 2.7.4#2
1> [CMake]     icu[core]:x64-windows -> 69.1#9
1> [CMake]     libjpeg-turbo[core]:x64-windows -> 2.0.6
1> [CMake]     libpng[core]:x64-windows -> 1.6.37#14
1> [CMake]     openssl[core]:x64-windows -> 1.1.1k#1
1> [CMake]     pcre2[core]:x64-windows -> 10.35#2
1> [CMake]     qt5-base[core]:x64-windows -> 5.15.2#7
1> [CMake]     sqlite3[core]:x64-windows -> 3.35.4
1> [CMake]     vcpkg-pkgconfig-get-modules[core]:x64-windows -> 2021-04-02
1> [CMake]     zlib[core]:x64-windows -> 1.2.11#10
1> [CMake]     zstd[core]:x64-windows -> 1.4.9
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\35\359e9aa841f708e5165136eb764eea79a0f429c9.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\d1\d14d45f1db7a0b18bb48d26793c768cbb0696ea6.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\52\529c62f75bc034bbf3323202c2fc26f3eaa1aa10.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\53\531a99d9ae8b3c2071182f224cff537346257759.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\d6\d6502ecacecc54b69d12f1938c45777b343e96c3.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\56\564424286b81b5390bda023914cc3dd9c7f70276.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\26\26d0e141ce286d41501cdb808b4485757e74550b.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\fb\fb5d352cd87c86d3b7b203a6238e86b60afe6aa4.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\53\53db6ab7cae639ad56daa14c311486b3deede6d2.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\38\384e07396d46abba86e8efd16e5661e8f7ab5458.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\0a\0a14fab15ed4b79cb018789196914f1b44554d88.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\57\575bf44a07911395fc2698c2336c7029f8c3fd26.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\25\2583f9b0ae231896045c8d4c0820285d27eda3d7.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\bb\bba346278232999790cde6291adb7446610d6cf8.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\dc\dc223c3d24919cc745c36829c643f62814ebd8cf.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\e6\e6b7763458513e8147637911755ffdfd088c959e.zip
1> [CMake] Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\70\70b707d4a26ab027eac834825f0496188808ef0b.zip
1> [CMake] Starting package 1/17: catch2:x64-windows
1> [CMake] Building package catch2[core]:x64-windows...
1> [CMake] Building package catch2[core]:x64-windows... done
1> [CMake] Installing package catch2[core]:x64-windows...
1> [CMake] Installing package catch2[core]:x64-windows... done
1> [CMake] Elapsed time for package catch2:x64-windows: 512.5 ms
1> [CMake] Starting package 2/17: zstd:x64-windows
1> [CMake] Building package zstd[core]:x64-windows...
1> [CMake] Building package zstd[core]:x64-windows... done
1> [CMake] Installing package zstd[core]:x64-windows...
1> [CMake] Installing package zstd[core]:x64-windows... done
1> [CMake] Elapsed time for package zstd:x64-windows: 370.8 ms
1> [CMake] Starting package 3/17: zlib:x64-windows
1> [CMake] Building package zlib[core]:x64-windows...
1> [CMake] Building package zlib[core]:x64-windows... done
1> [CMake] Installing package zlib[core]:x64-windows...
1> [CMake] Installing package zlib[core]:x64-windows... done
1> [CMake] Elapsed time for package zlib:x64-windows: 130 ms
1> [CMake] Starting package 4/17: vcpkg-pkgconfig-get-modules:x64-windows
1> [CMake] Building package vcpkg-pkgconfig-get-modules[core]:x64-windows...
1> [CMake] Building package vcpkg-pkgconfig-get-modules[core]:x64-windows... done
1> [CMake] Installing package vcpkg-pkgconfig-get-modules[core]:x64-windows...
1> [CMake] Installing package vcpkg-pkgconfig-get-modules[core]:x64-windows... done
1> [CMake] Elapsed time for package vcpkg-pkgconfig-get-modules:x64-windows: 59.99 ms
1> [CMake] Starting package 5/17: sqlite3:x64-windows
1> [CMake] Building package sqlite3[core]:x64-windows...
1> [CMake] Building package sqlite3[core]:x64-windows... done
1> [CMake] Installing package sqlite3[core]:x64-windows...
1> [CMake] Installing package sqlite3[core]:x64-windows... done
1> [CMake] Elapsed time for package sqlite3:x64-windows: 597.3 ms
1> [CMake] Starting package 6/17: pcre2:x64-windows
1> [CMake] Building package pcre2[core]:x64-windows...
1> [CMake] Building package pcre2[core]:x64-windows... done
1> [CMake] Installing package pcre2[core]:x64-windows...
1> [CMake] Installing package pcre2[core]:x64-windows... done
1> [CMake] Elapsed time for package pcre2:x64-windows: 1.409 s
1> [CMake] Starting package 7/17: openssl:x64-windows
1> [CMake] Building package openssl[core]:x64-windows...
1> [CMake] Building package openssl[core]:x64-windows... done
1> [CMake] Installing package openssl[core]:x64-windows...
1> [CMake] Installing package openssl[core]:x64-windows... done
1> [CMake] Elapsed time for package openssl:x64-windows: 2.31 s
1> [CMake] Starting package 8/17: libpng:x64-windows
1> [CMake] Building package libpng[core]:x64-windows...
1> [CMake] Building package libpng[core]:x64-windows... done
1> [CMake] Installing package libpng[core]:x64-windows...
1> [CMake] Installing package libpng[core]:x64-windows... done
1> [CMake] Elapsed time for package libpng:x64-windows: 280.4 ms
1> [CMake] Starting package 9/17: libjpeg-turbo:x64-windows
1> [CMake] Building package libjpeg-turbo[core]:x64-windows...
1> [CMake] Building package libjpeg-turbo[core]:x64-windows... done
1> [CMake] Installing package libjpeg-turbo[core]:x64-windows...
1> [CMake] Installing package libjpeg-turbo[core]:x64-windows... done
1> [CMake] Elapsed time for package libjpeg-turbo:x64-windows: 242.2 ms
1> [CMake] Starting package 10/17: icu:x64-windows
1> [CMake] Building package icu[core]:x64-windows...
1> [CMake] Building package icu[core]:x64-windows... done
1> [CMake] Installing package icu[core]:x64-windows...
1> [CMake] Installing package icu[core]:x64-windows... done
1> [CMake] Elapsed time for package icu:x64-windows: 4.095 s
1> [CMake] Starting package 11/17: bzip2:x64-windows
1> [CMake] Building package bzip2[core]:x64-windows...
1> [CMake] Building package bzip2[core]:x64-windows... done
1> [CMake] Installing package bzip2[core]:x64-windows...
1> [CMake] Installing package bzip2[core]:x64-windows... done
1> [CMake] Elapsed time for package bzip2:x64-windows: 268.1 ms
1> [CMake] Starting package 12/17: brotli:x64-windows
1> [CMake] Building package brotli[core]:x64-windows...
1> [CMake] Building package brotli[core]:x64-windows... done
1> [CMake] Installing package brotli[core]:x64-windows...
1> [CMake] Installing package brotli[core]:x64-windows... done
1> [CMake] Elapsed time for package brotli:x64-windows: 810.1 ms
1> [CMake] Starting package 13/17: freetype:x64-windows
1> [CMake] Building package freetype[brotli,bzip2,core,png,zlib]:x64-windows...
1> [CMake] Building package freetype[brotli,bzip2,core,png,zlib]:x64-windows... done
1> [CMake] Installing package freetype[brotli,bzip2,core,png,zlib]:x64-windows...
1> [CMake] Installing package freetype[brotli,bzip2,core,png,zlib]:x64-windows... done
1> [CMake] Elapsed time for package freetype:x64-windows: 734.9 ms
1> [CMake] Starting package 14/17: harfbuzz:x64-windows
1> [CMake] Building package harfbuzz[core]:x64-windows...
1> [CMake] Building package harfbuzz[core]:x64-windows... done
1> [CMake] Installing package harfbuzz[core]:x64-windows...
1> [CMake] Installing package harfbuzz[core]:x64-windows... done
1> [CMake] Elapsed time for package harfbuzz:x64-windows: 528.3 ms
1> [CMake] Starting package 15/17: egl-registry:x64-windows
1> [CMake] Building package egl-registry[core]:x64-windows...
1> [CMake] Building package egl-registry[core]:x64-windows... done
1> [CMake] Installing package egl-registry[core]:x64-windows...
1> [CMake] Installing package egl-registry[core]:x64-windows... done
1> [CMake] Elapsed time for package egl-registry:x64-windows: 59.86 ms
1> [CMake] Starting package 16/17: double-conversion:x64-windows
1> [CMake] Building package double-conversion[core]:x64-windows...
1> [CMake] Building package double-conversion[core]:x64-windows... done
1> [CMake] Installing package double-conversion[core]:x64-windows...
1> [CMake] Installing package double-conversion[core]:x64-windows... done
1> [CMake] Elapsed time for package double-conversion:x64-windows: 122.5 ms
1> [CMake] Starting package 17/17: qt5-base:x64-windows
1> [CMake] Building package qt5-base[core]:x64-windows...
1> [CMake] Building package qt5-base[core]:x64-windows... done
1> [CMake] Installing package qt5-base[core]:x64-windows...
1> [CMake] Installing package qt5-base[core]:x64-windows... done
1> [CMake] Elapsed time for package qt5-base:x64-windows: 45.9 s
1> [CMake] 
1> [CMake] Total elapsed time: 1.387 min
1> [CMake] 
1> [CMake] -- Running vcpkg install - done
1> [CMake] -- The CXX compiler identification is MSVC 19.28.29914.0
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Configuring done
1> [CMake] -- Generating done
1> [CMake] -- Build files have been written to: C:/Users/%USERNAME%/<root_project_dir>/out/build/x64-Debug
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted code model.
1> Extracted includes paths.
1> CMake generation finished.
```
**Expected behavior**
`vcpkg` should not be running `vcpkg` when no packages have changed based from my understanding that `vcpkg` caches. Notice how it retries to build install all the dependencies such as Qt even though none of the packages have changed.

**Some extra details**
I am using vcpkg as a submodule and I do include the following before the `project` in my CMakeLists.txt

```
set(CMAKE_TOOLCHAIN_FILE ${CMAKE_CURRENT_SOURCE_DIR}/extern/vcpkg/scripts/buildsystems/vcpkg.cmake
  CACHE STRING "Vcpkg toolchain file")

set(VCPKG_FEATURE_FLAGS versions)
```

@strega-nil

**Comment by Osyotr** [comment] 2021-05-12 19:12
Maybe connected to this issue:
https://developercommunity.visualstudio.com/t/The-toolchain-file-has-changed-message/1409097

**Comment by Pectacius** [comment] 2021-05-12 20:34
I tried again with regenerating CMake cache this time I recloned the project in a clean directory and I also removed the `Qt` dependency (takes too long to build) so the only dependency is `Catch`. I also ran CMake outside of visual studio so the command to generate the cache is not the super long thing that visual studio uses.

First time I run `cmake -B./build -G Ninja  .`

I get this output
```
-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
The following packages will be built and installed:
    catch2[core]:x64-windows -> 2.13.1#1
Using cached binary package: C:\Users\%USERNAME%\AppData\Local\vcpkg\archives\35\359e9aa841f708e5165136eb764eea79a0f429c9.zip
Starting package 1/1: catch2:x64-windows
Building package catch2[core]:x64-windows...
Building package catch2[core]:x64-windows... done
Installing package catch2[core]:x64-windows...
Installing package catch2[core]:x64-windows... done
Elapsed time for package catch2:x64-windows: 194.2 ms

Total elapsed time: 283.2 ms

-- Running vcpkg install - done
```
which makes sense because it needs to redownload Catch.

After that is done. I re-run it again with same command `cmake -B./build -G Ninja  .`

and I get this output:
```
-- Running vcpkg install
Detecting compiler hash for triplet x64-windows...
All requested packages are currently installed.

Total elapsed time: 4 us

-- Running vcpkg install - done
```

This is what I am expecting because Catch is already installed. Notice how unlike the output from the first post there is no message of it reattempting to build and install the dependencies. i.e. the message
```
1> [CMake] Starting package 1/17: catch2:x64-windows
1> [CMake] Building package catch2[core]:x64-windows...
1> [CMake] Building package catch2[core]:x64-windows... done
1> [CMake] Installing package catch2[core]:x64-windows...
1> [CMake] Installing package catch2[core]:x64-windows... done
1> [CMake] Elapsed time for package catch2:x64-windows: 512.5 ms
```
does not show.

**Comment by JackBoosY** [comment] 2021-05-13 02:46
Ping @strega-nil-ms @strega-nil  for reply.

**Comment by strega-nil-ms** [comment] 2021-05-25 00:46
This is intended; cmake cache generation is, by its nature, kind of where this all happens. You'll also get stuff like globs being recalculated. In general, unless you're changing variable values, you don't ever need to reconfigure (and if you are changing variable values, that might invalidate vcpkg's installed directory).

We do _not_ run on build, and this is the action that one _should_ take most often; reconfiguring should rarely if ever happen.

Closing as "intended behaviour".

Thanks @Pectacius for the report! If you have any other questions, please don't hesitate to ask.

**Closed by strega-nil-ms** 2021-05-25 00:46 UTC
Labels: requires:discussion
