### ISSUE TITLE
[SDL1:x86-windows] build failure

### ISSUE THREAD

**Issue by Christsnatcher** [microsoft/vcpkg#7535] opened 2019-08-03 12:45 UTC
**Host Environment**
- Windows 8.1 x64
- MSVC++ 14.22 _MSC_VER == 1922 Visual Studio 2019

**To Reproduce**
vcpkg install sdl1:x86-windows

**Failure logs** 
D:\Code\Repos\vcpkg>vcpkg install sdl1:x86-windows
The following packages will be built and installed:
    sdl1[core]:x86-windows
Starting package 1/1: sdl1:x86-windows
Building package sdl1[core]:x86-windows...
-- Downloading https://github.com/SDL-Mirror/SDL/archive/release-1.2.15.tar.gz...
-- Extracting source D:/Code/Repos/vcpkg/downloads/SDL-Mirror-SDL-release-1.2.15.tar.gz
-- Applying patch export-symbols-only-in-shared-build.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/sdl1/src/ase-1.2.15-2ca6426de6
-- Installing: D:/Code/Repos/vcpkg/buildtrees/sdl1/src/ase-1.2.15-2ca6426de6/VisualC/SDL/SDL.vcxproj
-- Installing: D:/Code/Repos/vcpkg/buildtrees/sdl1/src/ase-1.2.15-2ca6426de6/VisualC/SDLmain/SDLmain.vcxproj
-- Building VisualC/SDL1_2017.sln for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:58 (message):
    Command failed: msbuild D:/Code/Repos/vcpkg/buildtrees/sdl1/x86-windows-rel/ase-1.2.15-2ca6426de6/VisualC/SDL1_2017.sln /p:Configuration=Release /t:Rebuild /p:Platform=Win32 /p:PlatformToolset=v142 /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /p:WindowsTargetPlatformVersion=10.0.18362.0 /m
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/sdl1/x86-windows-rel/ase-1.2.15-2ca6426de6
    Error code: 1
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\sdl1\build-x86-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_msbuild.cmake:157 (vcpkg_execute_required_process)
  ports/sdl1/portfile.cmake:27 (vcpkg_install_msbuild)
  scripts/ports.cmake:74 (include)

Error: Building package sdl1:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl1:x86-windows
  Vcpkg version: 2019.07.18-nohash

**Additional context**
Building sdl1 x64 did work flawlessly, but since the latest update I'm unable to build x86 as you can see. I already tried to change my environmental variables on my x64 system to point to the resp. 32-bit files / folders, but no success. Many thanks in advance for your help!
[SDL1_x86.zip](https://github.com/microsoft/vcpkg/files/3463826/SDL1_x86.zip)

**Comment by greenbrettmichael** [comment] 2019-08-06 20:05
there appears to be an issue with an escape character in the download  D:/Code/Repos/vcpkg/buildtrees/sdl1/x86-windows-rel/ase-1.2.15-2ca6426de6

**Comment by Christsnatcher** [comment] 2019-08-07 04:14
Ah, that's good to know (and relieving), thank you very much. Hopefully it will be possible to fix it "soon".

**Comment by JackBoosY** [comment] 2019-08-15 08:14
Hi @Christsnatcher, thanks for reporting this issue!
I cannot repro this issue on Win10/VS2017, please provide the failure log `D:\Code\Repos\vcpkg\buildtrees\sdl1\build-x86-windows-rel-out.log`.

Thanks.

**Comment by Christsnatcher** [comment] 2019-08-15 10:08
Hello @JackBoosY, the failure log is included in the .zipfile attached to my initial post, in particular in "sdl1_buildtrees\sdl1". I just tried to compile the source (ase-1.2.15-2ca6426de6) manually using Visual Studio 2017 / 2019 with the Windows SDSs 8.1 / 10 and the Toolsets v141 / v142 (see attachment), and you're right, all v141 builds are succfessful no matter which SDK is being used, while all v142 builds fail. So it seems that vcpkg retargets the solution to use the v142 toolset which makes it fail eventually (at least that's my conclusion).
[Compiling_SDL1.zip](https://github.com/microsoft/vcpkg/files/3505152/Compiling_SDL1.zip)

**Comment by JackBoosY** [comment] 2019-08-16 06:15
Confirmed. It's a windows SDK bug. I have two workarounds:
1, Switch your compiler to Visual Studio 2017.
2, Modify the _vcpkg/ports/sdl1/SDL_dynamic.vcxproj(SDL_static.vcxproj)_, add line
`<WindowsTargetPlatformVersion> INSTALLED_WIN_SDK_VER </WindowsTargetPlatformVersion>` under label `<PropertyGroup Label="Globals">` , the **INSTALLED_WIN_SDK_VER**  must be **lower** than **10.0.18362.0**.

We have to wait for the windows SDK to fix this issue.

**Comment by Christsnatcher** [comment] 2019-08-16 07:50
Hello,
firstly, thank you for the explanation. I tried the second method first and it doesn't work, apparently, because not the .vcxproject file in "ports" is used for building, but instead the one in "buildtrees\sdl1\x86-windows-rel\ase-1.2.15-2ca6426de6\VisualC". I then altered this file, but it apparently gets hash-checked and overwritten with the original one which has the "wrong" SDK version; this happens even if I set the file to read-only.

So my question would be (sorry), how to actually switch the compiler used by vcpkg to Visual Studio 2017 by default without having to uninstall VS 2019?

Thanks again!

**Comment by JackBoosY** [comment] 2019-08-16 08:02
@Christsnatcher  Add `set(VCPKG_PLATFORM_TOOLSET v141)` to _vcpkg\triplets\YOU_CHOSSEN_TRIPLET.cmake_.

And yes, I confirm this is a SDK bug.

**Comment by JackBoosY** [comment] 2019-08-16 08:24
I have a tiny solution:
Modify _vcpkg/ports/sdl1/portfile.cmake_:
Add `TARGET_PLATFORM_VERSION INSTALLED_WIN_SDK_VER ` to the end of vcpkg_install_msbuild.
Like:
```
vcpkg_install_msbuild(
    SOURCE_PATH ${SOURCE_PATH}
    PROJECT_SUBPATH VisualC/SDL1_2017.sln
    INCLUDES_SUBPATH include
    LICENSE_SUBPATH COPYING
    ALLOW_ROOT_INCLUDES
	TARGET_PLATFORM_VERSION 10.0.17763.0
)
```
And, INSTALLED_WIN_SDK_VER must be lower than 10.0.18362.0.

**Comment by Christsnatcher** [comment] 2019-08-16 09:22
Thank you very much, your "tiny solution" did work pretty fine - without having to manually edit / set the "INSTALLED_WIN_SDK_VER" value, Anyways, many thanks again!

**Comment by tan-wei** [comment] 2019-08-23 05:24
Works for me after given a target platform version.

**Comment by tan-wei** [comment] 2019-09-14 02:31
@JackBoosY , for the latest version of `vcpkg`, the solution failed with the log:
```
Building package sdl1[core]:x86-windows...
-- Using cached C:/vcpkg/downloads/SDL-Mirror-SDL-release-1.2.15.tar.gz
CMake Error at scripts/cmake/vcpkg_extract_source_archive_ex.cmake:87 (file):
  file SHA512 failed to read file
  "C:/vcpkg/ports/sdl1/TARGET_PLATFORM_VERSION": No such file or directory
Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:114 (vcpkg_extract_source_archive_ex)
  ports/sdl1/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:91 (include)


Error: Building package sdl1:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl1:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
```
It seems that `TARGET_PLATFORM_VERSION` is required when given `TARGET_PLATFORM_VERSION` in the `portfile.cmake`.

**Comment by tan-wei** [comment] 2019-09-14 03:26
So the tiny solution does not work now. I try to add SDK version in `SDL_dynamic.vcxproj` etc. work for me now. Maybe the issue should be closed after the bug of SDK is fixed.

**Comment by PhoebeHui** [comment] 2019-09-25 11:06
PR https://github.com/microsoft/vcpkg/pull/8327 should address this issue, this appears to be an existing issue with sdl1 that was exposed with the sdk update.

**Comment by JackBoosY** [comment] 2019-09-26 06:24
Since #8327 has been merged, this issue should be fixed.
Please update vcpkg and rebuild sdl1.

Thanks.

**Closed by JackBoosY** 2019-09-26 06:24 UTC
Labels: port bug
