### ISSUE TITLE
[libuv] build failure

### ISSUE THREAD

**Issue by rs333** [microsoft/vcpkg#29302] opened 2023-01-30 22:04 UTC
Package: libuv[core]:x64-windows -> 1.44.2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31937.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: f14984af3 2023-01-09 (3 weeks ago)

**To Reproduce**

`vcpkg install libuv:x64-windows`

**Failure logs**

```
-- Downloading https://github.com/libuv/libuv/archive/0c1fa696aa502eb749c2c4735005f41ba00a27b8.tar.gz -> libuv-libuv-0c1fa696aa502eb749c2c4735005f41ba00a27b8.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/libuv/libuv/archive/0c1fa696aa502eb749c2c4735005f41ba00a27b8.tar.gz
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/libuv/libuv/archive/0c1fa696aa502eb749c2c4735005f41ba00a27b8.tar.gz
File: C:\devtools\vcpkg\downloads\libuv-libuv-0c1fa696aa502eb749c2c4735005f41ba00a27b8.tar.gz.7252.part
Expected hash: 4b63745d48c5318d75ef3580fc6d6288b1ca26a25f69fbef2af4b6fe1d1fe1255986cbb1fb5124e1ba6cd324868ebccdc6f6965e08e3e0fbde29f22e7e20ce89
Actual hash: 9e517c311593120b6a78d613a256e2bab76bb6ab36a5095cab035b58c058e5724fd7d7130263d88f172561825ab9f628ab0990ac49da582e28da237c1bb4e147
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956): 
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 754 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 550.5 ms (544614 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/libuv/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)



```

**Additional context**

Note that the system is not using a proxy and the error appears to be related to the hash and the error occurs regardless as to whether vcpkg install is run in command prompt or powershell.

**Comment by BillyONeal** [comment] 2023-01-30 22:05
Duplicate of https://github.com/microsoft/vcpkg/issues/29288

**Closed by BillyONeal** 2023-01-30 22:05 UTC
Labels: category:port-bug
