### ISSUE TITLE
[colmap] build failure

### ISSUE THREAD

**Issue by acse-pms122** [microsoft/vcpkg#32130] opened 2023-06-20 19:24 UTC
### Operating system

Windows 11, VS Code 2022

### Steps to reproduce the behavior

```Shell
.\vcpkg install colmap[cuda,tests]:x64-windows
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows -> 2023-03-12#1
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\pauls\AppData\Local\vcpkg\archives in 80.8 us. Use --debug to see more details.
Installing 1/1 colmap:x64-windows...
Building colmap[core,cuda,tests]:x64-windows...
-- Using cached colmap-colmap-30da037ce19bdceb6d239c45342fadb221bdabb2.tar.gz.
-- Cleaning sources at C:/Users/pauls/vcpkg/buildtrees/colmap/src/b221bdabb2-e3968635af.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/pauls/vcpkg/downloads/colmap-colmap-30da037ce19bdceb6d239c45342fadb221bdabb2.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at C:/Users/pauls/vcpkg/buildtrees/colmap/src/b221bdabb2-e3968635af.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/pauls/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/Users/pauls/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\Users\pauls\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building colmap:x64-windows failed with: BUILD_FAILED
Elapsed time to handle colmap:x64-windows: 1.3 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[colmap]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2Fpauls%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

The contents of C:\Users\pauls\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log are as follows:

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/11805802/install-x64-windows-dbg-out.log)

**Comment by jimwang118** [comment] 2023-06-21 05:41
Duplicate of [#30272](https://github.com/microsoft/vcpkg/issues/30272)

**Closed by jimwang118** 2023-06-21 05:41 UTC
Labels: category:port-bug
