### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by juanilogo** [microsoft/vcpkg#36709] opened 2024-02-12 08:00 UTC
Package: openssl[core]:x64-windows -> 3.2.1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31935.0
-    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 345ac44ab 2024-02-09 (2 days ago)

**To Reproduce**

`vcpkg install open62541`

**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.2.1.tar.gz.
-- Cleaning sources at C:/Users/Juan/vcpkg/buildtrees/openssl/src/nssl-3.2.1-8707343470.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/Juan/vcpkg/downloads/openssl-openssl-openssl-3.2.1.tar.gz
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at C:/Users/Juan/vcpkg/buildtrees/openssl/src/nssl-3.2.1-8707343470.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Using cached nasm-2.16.01-win64.zip.
CMake Error at scripts/cmake/vcpkg_extract_archive.cmake:19 (message):
  C:/Users/Juan/vcpkg/downloads/tools/nasm was an extraction target, but it
  already exists.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:203 (vcpkg_extract_archive)
  ports/openssl/windows/portfile.cmake:60 (vcpkg_find_acquire_program)
  ports/openssl/portfile.cmake:74 (include)
  scripts/ports.cmake:170 (include)



```

**Additional context**

**Comment by Cheney-W** [comment] 2024-02-18 07:06
Duplicate of https://github.com/microsoft/vcpkg/issues/35746

**Closed by Cheney-W** 2024-02-18 07:06 UTC
Labels: category:question
