### ISSUE TITLE
[protobuf] Build error

### ISSUE THREAD

**Issue by lionc0** [microsoft/vcpkg#26580] opened 2022-08-29 05:57 UTC
**Host Environment**
- OS: win10
- Compiler: 
-    MSVC 19.29.30137.0
-    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
     vcpkg-scripts version: unknown

**To Reproduce**
`./vcpkg install opencv:x64-windows`

**Failure logs**
```
-- Using cached protocolbuffers-protobuf-c9869dc7803eb0a21d7e589c40ff4f9288cd34ae.tar.gz.
-- Cleaning sources at C:/Working/vcpkg-2022.08.15/buildtrees/protobuf/src/9288cd34ae-9c2e104673.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Working/vcpkg-2022.08.15/downloads/protocolbuffers-protobuf-c9869dc7803eb0a21d7e589c40ff4f9288cd34ae.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch compile_options.patch
-- Using source at C:/Working/vcpkg-2022.08.15/buildtrees/protobuf/src/9288cd34ae-9c2e104673.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: C:/Working/vcpkg-2022.08.15/downloads/tools/powershell-core-7.2.5-windows/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file C:/Working/vcpkg-2022.08.15/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Working/vcpkg-2022.08.15/packages/protobuf_x64-windows/tools/protobuf/protoc.exe -installedDir C:/Working/vcpkg-2022.08.15/packages/protobuf_x64-windows/bin -verbose
    Working Directory: C:/Working/vcpkg-2022.08.15
    Error code: 1
    See logs for more information:
      C:\Working\vcpkg-2022.08.15\buildtrees\protobuf\copy-tool-dependencies-0-out.log
      C:\Working\vcpkg-2022.08.15\buildtrees\protobuf\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/protobuf/portfile.cmake:81 (vcpkg_copy_tools)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\Working\vcpkg-2022.08.15\buildtrees\protobuf\copy-tool-dependencies-0-out.log</summary>

```
[33;1mVERBOSE: Resolving base path C:/Working/vcpkg-2022.08.15/packages/protobuf_x64-windows/tools/protobuf/protoc.exe...[0m
[33;1mVERBOSE: Resolving C:/Working/vcpkg-2022.08.15/packages/protobuf_x64-windows/tools/protobuf/protoc.exe...[0m
```
</details>
<details><summary>C:\Working\vcpkg-2022.08.15\buildtrees\protobuf\copy-tool-dependencies-0-err.log</summary>

```
[91mWrite-Error: [0mC:\Working\vcpkg-2022.08.15\scripts\buildsystems\msbuild\applocal.ps1:40
[96mLine |
[96m  40 | [0m         $mtx = [96mgetMutex($targetBinaryDir)[0m
[96m     | [91m                ~~~~~~~~~~~~~~~~~~~~~~~~~~
[91m[96m     | [91mCannot invoke method. Method invocation is supported only on core types in this language mode.
[0m
```
</details>

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[copy-tool-dependencies-0-err.log](https://github.com/microsoft/vcpkg/files/9441880/copy-tool-dependencies-0-err.log)
[copy-tool-dependencies-0-out.log](https://github.com/microsoft/vcpkg/files/9441881/copy-tool-dependencies-0-out.log)

**Comment by FrankXie05** [comment] 2022-08-29 06:47
@lionc0 Thanks for posting this issue, The problem is with [`PowerShell Constrained Language Mode`](https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/), you can set a environment variable `__PSLockdownPolicy` to `0` will solve this problem. :)

**Comment by lionc0** [comment] 2022-08-29 07:09
> @lionc0 Thanks for posting this issue, The problem is with [`PowerShell Constrained Language Mode`](https://devblogs.microsoft.com/powershell/powershell-constrained-language-mode/), you can set a environment variable `__PSLockdownPolicy` to `0` will solve this problem. :)

got it! thanks a lot!

**Comment by FrankXie05** [comment] 2022-08-30 02:24
@lionc0 Does the issue still occur?

**Comment by FrankXie05** [comment] 2022-08-30 07:07
Duplicate of #25829

**Comment by lionc0** [comment] 2022-09-05 10:07
> @lionc0 Does the issue still occur?

nope，fixed it already with  __PSLockdownPolicy ！

**Closed** 2022-09-05 10:17 UTC
Labels: category:question

**Comment by FrankXie05** [comment] 2023-05-08 08:07
@panyuanzhi Could you please run command `$ExecutionContext.SessionState.LanguageMode` on `PowerShell`?

**Comment by panyuanzhi** [comment] 2023-05-08 08:09
> @panyuanzhi
> 
> ```
> Cannot invoke method. Method invocation is supported only on core types in this language mode.
> ```
> 
> Is this also the problem?

@FrankXie05  yes,the same promblem.

the language mode is constrained.and I can't modify it.
![image](https://user-images.githubusercontent.com/12220654/236771206-6cd4b1ed-afd7-4abe-9ad2-6a5f0c89f029.png)

**Comment by FrankXie05** [comment] 2023-05-08 08:13
Well, this is restricted mode. 🫤

**Comment by FrankXie05** [comment] 2023-05-08 08:19
@panyuanzhi 
Can try: 
1. Run PowerShell as an administrator.

2. Run: `Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process`
The above command sets the policy to `RemoteSigned`, which allows you to run local scripts, but requires digitally signed remote scripts to run.

3. Run again to view the mode `$ExecutionContext.SessionState.LanguageMode`
It shuold be `FullLanguage`

![image](https://user-images.githubusercontent.com/65999885/236773217-21a23dad-f9f6-4c92-82ad-45f3a1bada5b.png)

**Comment by panyuanzhi** [comment] 2023-05-08 08:22
@FrankXie05 it doesn't work.
![image](https://user-images.githubusercontent.com/12220654/236773771-ea144a2e-a9ae-4a0d-8c6b-28ee93bae814.png)

**Comment by panyuanzhi** [comment] 2023-05-08 08:22
> @FrankXie05 it doesn't work. ![image](https://user-images.githubusercontent.com/12220654/236773771-ea144a2e-a9ae-4a0d-8c6b-28ee93bae814.png)

I have run it as administrator

**Comment by FrankXie05** [comment] 2023-05-08 08:25
Just run command `Set-ExecutionPolicy RemoteSigned` :)
![image](https://user-images.githubusercontent.com/65999885/236774487-a9f3ea07-8a55-4d42-8a96-2d0d85151b73.png)

**Comment by panyuanzhi** [comment] 2023-05-08 08:29
@FrankXie05  I run the command,it does't show the any text.
![image](https://user-images.githubusercontent.com/12220654/236775502-8d5e195f-947d-4c5f-9f1b-ffeb59189402.png)

**Comment by FrankXie05** [comment] 2023-05-08 08:38
@panyuanzhi Do you have powershell on this machine?

**Comment by FrankXie05** [comment] 2023-05-08 08:47
If you are running `PowerShell` on a managed computer or in a restricted network environment, you may be restricted by Group Policy or other security policies that prevent you from changing the language mode。

**Comment by panyuanzhi** [comment] 2023-05-08 08:51
> Just run command `Set-ExecutionPolicy RemoteSigned` :) ![image](https://user-images.githubusercontent.com/65999885/236774487-a9f3ea07-8a55-4d42-8a96-2d0d85151b73.png)

@FrankXie05  I try it on my own powershell,but it also does't work.I give up but thanks also.
![image](https://user-images.githubusercontent.com/12220654/236780541-8454cbda-6aa4-4605-ba99-67f0255f9477.png)

**Comment by panyuanzhi** [comment] 2023-05-08 09:05
@FrankXie05  it failed 😢

**Comment by FrankXie05** [comment] 2023-05-09 09:13
@panyuanzhi Is the modification unsuccessful?
