### ISSUE TITLE
vcpkg hangs when when installing any package

### ISSUE THREAD

**Issue by vnen** [microsoft/vcpkg#3391] opened 2018-04-30 16:40 UTC
I'm using the latest vcpkg (a9d989ec) with Windows 10 (build 16299.371) and every time I try to install a package it hangs forever in one of the steps.

Looking at the task manager, I noticed that there's a cmake process without any activity. Maybe it's a problem with CMake? I have the version 3.11.1 of CMake installed.

If I kill the cmake process, vcpkg stops with `BUILD_FAILED` message.

**Comment by VisitantP** [comment] 2018-05-16 14:50
I too experience the same problem. vckpg hangs the OS when I tried to install caffe2 package!

**Comment by marsermd** [comment] 2018-11-15 22:52
Maybe it's related to [https://github.com/Microsoft/vcpkg/issues/2654](this issue)? 
Are you running out of memory before it hangs?

**Comment by Cheney-W** [comment] 2019-02-15 06:10
@vnen , I can't reproduce your issue with the latest vcpkg:2018.11.23-nohash and Win10 1809(build 17763.316), I think this issue has been fixed, could you help confirm? If this issue was fixed, please close this issue. Thank you.

**Comment by vnen** [comment] 2019-02-15 14:45
Tried today with latest commit (f9c461cecea07a7cee49547074447fa90e9ea9e9).

I've been more patient now and discovered that it finishes but takes way too long (9min when installing OpenSSL, 11.2min installing curl). It stops on the `Performing CMake integration test` phase and keeps there for a long time without using much of the computer resources. CPU usage is close to 0 and I still have over 8GB of available memory, so definitely not running out. It only fully uses the CPU in the building step.

I think the time it takes to finish is still an issue, but if it's supposed to take that long then you may close the issue. Again, maybe is an issue with CMake (I have version 3.13.4 installed), but I'm not sure how to pinpoint the source of the stall.

<details>
<summary>Log of installing openssl and curl</summary>

```
PS G:\workspace\vcpkg> .\vcpkg install openssl openssl-windows
The following packages will be built and installed:
    openssl[core]:x86-windows
    openssl-windows[core]:x86-windows
Starting package 1/2: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
-- Downloading http://strawberryperl.com/download/5.24.1.1/strawberry-perl-5.24.1.1-32bit-portable.zip...
-- Downloading https://www.openssl.org/source/openssl-1.0.2q.tar.gz...
-- Extracting source G:/workspace/vcpkg/downloads/openssl-1.0.2q.tar.gz
-- Applying patch G:/workspace/vcpkg/ports/openssl-windows/ConfigureIncludeQuotesFix.patch
-- Applying patch G:/workspace/vcpkg/ports/openssl-windows/STRINGIFYPatch.patch
-- Applying patch G:/workspace/vcpkg/ports/openssl-windows/EnableWinARM32.patch
-- Applying patch G:/workspace/vcpkg/ports/openssl-windows/EmbedSymbolsInStaticLibsZ7.patch
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.12.02/win32/nasm-2.12.02-win32.zip...
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_2.zip...
-- Configure x86-windows-rel
-- Configure x86-windows-rel done
-- Build x86-windows-rel
-- Build x86-windows-rel done
-- Configure x86-windows-dbg
-- Configure x86-windows-dbg done
-- Build x86-windows-dbg
-- Build x86-windows-dbg done
-- Installing: G:/workspace/vcpkg/packages/openssl-windows_x86-windows/share/openssl-windows/copyright
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl-windows[core]:x86-windows... done
Installing package openssl-windows[core]:x86-windows...
Installing package openssl-windows[core]:x86-windows... done
Elapsed time for package openssl-windows:x86-windows: 8.885 min
Starting package 2/2: openssl:x86-windows
Building package openssl[core]:x86-windows...
-- Installing: G:/workspace/vcpkg/packages/openssl_x86-windows/share/openssl//usage
-- Performing post-build validation
-- Performing post-build validation done
Building package openssl[core]:x86-windows... done
Installing package openssl[core]:x86-windows...
Installing package openssl[core]:x86-windows... done
Elapsed time for package openssl:x86-windows: 5.8 s

Total elapsed time: 8.981 min

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

The package openssl is compatible with built-in CMake targets:

    find_package(OpenSSL REQUIRED)
    target_link_libraries(main PRIVATE OpenSSL::SSL OpenSSL::Crypto)

PS G:\workspace\vcpkg> .\vcpkg install curl
The following packages will be built and installed:
    curl[core,ssl,winssl]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: zlib:x86-windows
Building package zlib[core]:x86-windows...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source G:/workspace/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch G:/workspace/vcpkg/ports/zlib/cmake_dont_build_more_than_needed.patch
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: G:/workspace/vcpkg/packages/zlib_x86-windows/share/zlib/copyright
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package zlib[core]:x86-windows... done
Installing package zlib[core]:x86-windows...
Installing package zlib[core]:x86-windows... done
Elapsed time for package zlib:x86-windows: 4.578 min
Starting package 2/2: curl:x86-windows
Building package curl[core,ssl,winssl]:x86-windows...
-- Downloading https://github.com/curl/curl/archive/curl-7_61_1.tar.gz...
-- Extracting source G:/workspace/vcpkg/downloads/curl-curl-curl-7_61_1.tar.gz
-- Applying patch 0001_cmake.patch
-- Applying patch 0002_fix_uwp.patch
-- Applying patch 0003_fix_libraries.patch
-- Applying patch 0004_nghttp2_staticlib.patch
-- Using source at G:/workspace/vcpkg/buildtrees/curl/src/url-7_61_1-e11be184c4
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: G:/workspace/vcpkg/packages/curl_x86-windows/share/curl/copyright
-- Performing CMake integration test
-- Performing post-build validation
-- Performing post-build validation done
Building package curl[core,ssl,winssl]:x86-windows... done
Installing package curl[core,ssl,winssl]:x86-windows...
Installing package curl[core,ssl,winssl]:x86-windows... done
Elapsed time for package curl:x86-windows: 6.629 min

Total elapsed time: 11.21 min

The package curl is compatible with built-in CMake targets:

    find_package(CURL REQUIRED)
    target_link_libraries(main PRIVATE ${CURL_LIBRARIES})
    target_include_directories(main PRIVATE ${CURL_INCLUDE_DIRS})

PS G:\workspace\vcpkg>
```
</details>

**Comment by Cheney-W** [comment] 2019-05-15 03:04
Tested with the latest vcpkg, I got below results:
Elapsed time for package openssl-windows:x86-windows: 6.031 min
Elapsed time for package openssl:x86-windows: 2.488 s
Total elapsed time: 6.073 min

Elapsed time for package zlib:x86-windows: 44.02 s
Elapsed time for package curl:x86-windows: 3.129 min
Total elapsed time: 3.863 min

Please try to install them again, if the installation time is reduced, please close this issue.

**Comment by NancyLi1013** [comment] 2019-06-24 08:09
@vnen, thanks for posting this issue and your patience. Please feel free to reopen it if this is still a problem for you.

**Closed by NancyLi1013** 2019-06-24 08:09 UTC
Labels: Question

**Comment by Simran-B** [comment] 2020-03-03 23:58
`vcpkg install qt5-base:x64-windows` hangs after reporting a successful compilation and installation, not making any apparent progress even after more than 2 hours when I try to build a Docker image. See https://github.com/moby/moby/issues/40266#issuecomment-594229962 for details.
