### ISSUE TITLE
[PCL] x64 windows build failure

### ISSUE THREAD

**Issue by Zoylamb** [microsoft/vcpkg#21494] opened 2021-11-17 15:58 UTC
**Host Environment**
- OS: Windows 10 x64
- Compiler: VS2019

**To Reproduce**
`./vcpkg install pcl[tools,vtk]`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    pcl[core,tools,vtk]:x64-windows -> 1.12.0
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\olambert.RDVISION\AppData\Local\vcpkg\archives in 759.4 us. Use --debug to see more details.
Starting package 1/1: pcl:x64-windows
Building package pcl[core,tools,vtk]:x64-windows...
-- Downloading https://github.com/PointCloudLibrary/pcl/archive/f36a69a5e89953708990c4669317f989d532cf08.tar.gz -> PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz...
-- Extracting source F:/Commun/VisualTools/vcpkg/downloads/PointCloudLibrary-pcl-f36a69a5e89953708990c4669317f989d532cf08.tar.gz
-- Applying patch add-gcc-version-check.patch
-- Applying patch fix-check-sse.patch
-- Applying patch fix-find-qhull.patch
-- Applying patch fix-numeric-literals-flag.patch
-- Applying patch pcl_config.patch
-- Applying patch pcl_utils.patch
-- Applying patch remove-broken-targets.patch
-- Applying patch fix-cmake_find_library_suffixes.patch
-- Using source at F:/Commun/VisualTools/vcpkg/buildtrees/pcl/src/89d532cf08-fd49a85837.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Warning at installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:485 (message):
  The following variables are not used in CMakeLists.txt:

      PCL_BUILD_WITH_FLANN_DYNAMIC_LINKING_WIN32

  Please recheck them and remove the unnecessary options from the
  `vcpkg_cmake_configure` call.

  If these options should still be passed for whatever reason, please use the
  `MAYBE_UNUSED_VARIABLES` argument.
Call Stack (most recent call first):
  ports/pcl/portfile.cmake:42 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)

-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j5
    Working Directory: F:/Commun/VisualTools/vcpkg/buildtrees/pcl/x64-windows-dbg
    See logs for more information:
      F:\Commun\VisualTools\vcpkg\buildtrees\pcl\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/pcl/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:142 (include)

Error: Building package pcl:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: pcl[core,tools,vtk]:x64-windows -> 1.12.0
  vcpkg version: 1a5075baf 2021-11-17 (2 hours ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535

Additionally, attach any relevant sections from the log files above.

-Please attach any additional failure logs mentioned in the console output
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7556016/install-x64-windows-dbg-out.log)
.

**Comment by JonLiu1993** [comment] 2021-11-18 06:58
@Zoylamb ,Thanks for posting this issue,Duplicate of #19561 ,we track in issue #19561,Temporarily close this issue

**Comment by Zoylamb** [comment] 2021-11-18 07:23
@JonLiu1993 

I don't get why is duplicate of https://github.com/microsoft/vcpkg/issues/19561

My error is about OpenMP error...

Last error in log :

F:\Commun\VisualTools\vcpkg\buildtrees\pcl\src\89d532cf08-fd49a85837.clean\io\src\real_sense_2_grabber.cpp(294): error C3016: 'index': index variable in OpenMP 'for' statement must have signed integral type
F:\Commun\VisualTools\vcpkg\buildtrees\pcl\src\89d532cf08-fd49a85837.clean\io\src\real_sense_2_grabber.cpp(229): note: see reference to function template instantiation 'std::shared_ptr<pcl::PointCloud<pcl::PointXYZ>> pcl::RealSense2Grabber::convertRealsensePointsToPointCloud<pcl::PointXYZ,pcl::RealSense2Grabber::convertDepthToPointXYZ::<lambda_5504f3ee7daf55e4dbb7b522799496b7>>(const rs2::points &,Functor)' being compiled
        with
        [
            Functor=pcl::RealSense2Grabber::convertDepthToPointXYZ::<lambda_5504f3ee7daf55e4dbb7b522799496b7>
        ]

**Comment by JonLiu1993** [comment] 2021-11-18 07:46
@Zoylamb ,Sorry for my mistake, I reopen the issue, I will investigate in depth

**Comment by JonLiu1993** [comment] 2021-11-18 09:03
@Zoylamb ,I investigated this errorC3016 and issue#19561 the same error,
https://github.com/microsoft/vcpkg/issues/21219#issuecomment-962376818

**Closed by JonLiu1993** 2021-11-18 09:03 UTC
Labels: category:question
