### ISSUE TITLE
[libpq:x64_windows_static, cmake] Failure to properly link in application

### ISSUE THREAD

**Issue by dave-juicelabs** [microsoft/vcpkg#16423] opened 2021-02-25 23:46 UTC
The libpq port builds just fine in vcpkg and works from a cmake perspective but once I go to build the application I have linked libpq to through cmake I get linker errors. It appears as though there are multiple libraries that need to be linked to the application instead of just libpq.lib. After playing with the libraries, it appears, libpgport.lib, libpgcommon.lib and Secur32.lib are required. I assume these are all linked together in the shared library case where libpq.dll is created.

The cmake find_package(PostgreSQL REQUIRED) needs to be update to take in to account these extra libraries that are needed in the static build scenario.

**vcpkg Commit SHA**
319b8f06ebbf8f524df78b4578fb0efeb6772c50

**Environment**
- OS: Windows 10
- Compiler: CMake + Visual Studio 2019

**To Reproduce**
1. ./vcpkg install libpq
2. In CMake
  - find_package(PostgreSQL REQUIRED)
  - target_link_libraries(${PROJECT_NAME} PRIVATE PostgreSQL::PostgreSQL)

**Expected behavior**
Clean build without linker errors.

**Failure logs** 
11>lld-link : error : undefined symbol: pg_set_noblock
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:2491
11>>>>               libpq.lib(fe-connect.obj):($LN47)
11>
11>lld-link : error : undefined symbol: pg_snprintf
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:2299
11>>>>               libpq.lib(fe-connect.obj):($keep_going$204)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:7050
11>>>>               libpq.lib(fe-connect.obj):($LN4)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:1176
11>>>>               libpq.lib(fe-connect.obj):(connectOptions2)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:4990
11>>>>               libpq.lib(fe-connect.obj):(parseServiceInfo)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:5005
11>>>>               libpq.lib(fe-connect.obj):($next_file$16)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-secure-openssl.c:1428
11>>>>               libpq.lib(fe-secure-openssl.obj):($LN12)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-secure-openssl.c:838
11>>>>               libpq.lib(fe-secure-openssl.obj):(initialize_SSL)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-secure-openssl.c:864
11>>>>               libpq.lib(fe-secure-openssl.obj):(initialize_SSL)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-secure-openssl.c:924
11>>>>               libpq.lib(fe-secure-openssl.obj):(initialize_SSL)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-secure-openssl.c:1108
11>>>>               libpq.lib(fe-secure-openssl.obj):(initialize_SSL)
11>>>> referenced 2 more times
11>
11>lld-link : error : undefined symbol: pg_sprintf
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:6693
11>>>>               libpq.lib(fe-connect.obj):($LN12)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-exec.c:908
11>>>>               libpq.lib(fe-exec.obj):($LN8)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-protocol2.c:116
11>>>>               libpq.lib(fe-protocol2.obj):($LN17)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-protocol2.c:118
11>>>>               libpq.lib(fe-protocol2.obj):($LN17)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-protocol2.c:153
11>>>>               libpq.lib(fe-protocol2.obj):($LN23)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-protocol2.c:156
11>>>>               libpq.lib(fe-protocol2.obj):($LN23)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth.c:398
11>>>>               libpq.lib(fe-auth.obj):(pg_SSPI_startup)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\win32.c:317
11>>>>               libpq.lib(win32.obj):($LN15)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\win32.c:324
11>>>>               libpq.lib(win32.obj):($LN15)
11>
11>lld-link : error : undefined symbol: pg_fprintf
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:6821
11>>>>               libpq.lib(fe-connect.obj):(defaultNoticeProcessor)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:7077
11>>>>               libpq.lib(fe-connect.obj):(default_threadlock)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:7085
11>>>>               libpq.lib(fe-connect.obj):(default_threadlock)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:7090
11>>>>               libpq.lib(fe-connect.obj):(default_threadlock)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-exec.c:1021
11>>>>               libpq.lib(fe-exec.obj):($LN29)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\backend\utils\mb\encnames.c:567
11>>>>               libpq.lib(encnames.obj):($LN12)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-misc.c:102
11>>>>               libpq.lib(fe-misc.obj):($LN5)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-misc.c:118
11>>>>               libpq.lib(fe-misc.obj):($LN5)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-misc.c:185
11>>>>               libpq.lib(fe-misc.obj):($LN5)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-misc.c:207
11>>>>               libpq.lib(fe-misc.obj):($LN5)
11>>>> referenced 10 more times
11>
11>lld-link : error : undefined symbol: pgwin32_fopen
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:5038
11>>>>               libpq.lib(fe-connect.obj):(parseServiceFile)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:6925
11>>>>               libpq.lib(fe-connect.obj):(passwordFromFile)
11>
11>lld-link : error : undefined symbol: strlcpy
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:4384
11>>>>               libpq.lib(fe-connect.obj):($LN4)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:4415
11>>>>               libpq.lib(fe-connect.obj):($LN6)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:4983
11>>>>               libpq.lib(fe-connect.obj):(parseServiceInfo)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:4295
11>>>>               libpq.lib(fe-connect.obj):(internal_cancel)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:4305
11>>>>               libpq.lib(fe-connect.obj):($retry3$12)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:4326
11>>>>               libpq.lib(fe-connect.obj):($retry4$13)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-protocol2.c:508
11>>>>               libpq.lib(fe-protocol2.obj):($LN21)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-protocol3.c:213
11>>>>               libpq.lib(fe-protocol3.obj):($LN28)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-protocol3.c:927
11>>>>               libpq.lib(fe-protocol3.obj):($LN24)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-secure-openssl.c:836
11>>>>               libpq.lib(fe-secure-openssl.obj):(initialize_SSL)
11>>>> referenced 4 more times
11>
11>lld-link : error : undefined symbol: pg_get_encoding_from_locale
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:6686
11>>>>               libpq.lib(fe-connect.obj):($LN12)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:1293
11>>>>               libpq.lib(fe-connect.obj):(connectOptions2)
11>
11>lld-link : error : undefined symbol: inet_net_ntop
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:1550
11>>>>               libpq.lib(fe-connect.obj):(getHostaddr)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:1559
11>>>>               libpq.lib(fe-connect.obj):(getHostaddr)
11>
11>lld-link : error : undefined symbol: pg_gai_strerror
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:2309
11>>>>               libpq.lib(fe-connect.obj):($keep_going$204)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:2322
11>>>>               libpq.lib(fe-connect.obj):($keep_going$204)
11>
11>lld-link : error : undefined symbol: pg_getaddrinfo_all
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:2305
11>>>>               libpq.lib(fe-connect.obj):($keep_going$204)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:2318
11>>>>               libpq.lib(fe-connect.obj):($keep_going$204)
11>
11>lld-link : error : undefined symbol: pg_freeaddrinfo_all
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:4031
11>>>>               libpq.lib(fe-connect.obj):(release_conn_addrinfo)
11>
11>lld-link : error : undefined symbol: pg_link_canary_is_frontend
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-connect.c:1920
11>>>>               libpq.lib(fe-connect.obj):(connectDBStart)
11>
11>lld-link : error : undefined symbol: pg_tolower
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-exec.c:2907
11>>>>               libpq.lib(fe-exec.obj):($LN32)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-exec.c:2956
11>>>>               libpq.lib(fe-exec.obj):($LN32)
11>
11>lld-link : error : undefined symbol: pg_vsnprintf
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-exec.c:883
11>>>>               libpq.lib(fe-exec.obj):($LN8)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\pqexpbuffer.c:310
11>>>>               libpq.lib(pqexpbuffer.obj):(appendPQExpBufferVA)
11>
11>lld-link : error : undefined symbol: pg_strcasecmp
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-protocol2.c:115
11>>>>               libpq.lib(fe-protocol2.obj):($LN17)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-protocol2.c:152
11>>>>               libpq.lib(fe-protocol2.obj):($LN23)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-protocol3.c:2203
11>>>>               libpq.lib(fe-protocol3.obj):(build_startup_packet)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-secure-common.c:128
11>>>>               libpq.lib(fe-secure-common.obj):($LN11)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-secure-common.c:61
11>>>>               libpq.lib(fe-secure-common.obj):(wildcard_certificate_match)
11>
11>lld-link : error : undefined symbol: pg_md5_encrypt
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth.c:1078
11>>>>               libpq.lib(fe-auth.obj):($LN5)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth.c:1183
11>>>>               libpq.lib(fe-auth.obj):($LN19)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth.c:745
11>>>>               libpq.lib(fe-auth.obj):(pg_password_sendauth)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth.c:751
11>>>>               libpq.lib(fe-auth.obj):(pg_password_sendauth)
11>
11>lld-link : error : undefined symbol: pg_strong_random
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth-scram.c:780
11>>>>               libpq.lib(fe-auth-scram.obj):($LN8)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth-scram.c:317
11>>>>               libpq.lib(fe-auth-scram.obj):(build_client_first_message)
11>
11>lld-link : error : undefined symbol: pg_b64_encode
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth-scram.c:331
11>>>>               libpq.lib(fe-auth-scram.obj):(build_client_first_message)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth-scram.c:460
11>>>>               libpq.lib(fe-auth-scram.obj):(build_client_final_message)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth-scram.c:502
11>>>>               libpq.lib(fe-auth-scram.obj):(build_client_final_message)
11>
11>lld-link : error : undefined symbol: pg_b64_decode
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth-scram.c:580
11>>>>               libpq.lib(fe-auth-scram.obj):(read_server_first_message)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth-scram.c:664
11>>>>               libpq.lib(fe-auth-scram.obj):(read_server_final_message)
11>
11>lld-link : error : undefined symbol: pg_b64_enc_len
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth-scram.c:324
11>>>>               libpq.lib(fe-auth-scram.obj):(build_client_first_message)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth-scram.c:454
11>>>>               libpq.lib(fe-auth-scram.obj):(build_client_final_message)
11>>>> referenced by ...\vcpkg\buildtrees\libpq\x64-windows-static-dbg\src\interfaces\libpq\fe-auth-scram.c:500
11>>>>               libpq.lib(fe-auth-scram.obj):(build_client_final_message)
11>

**Comment by NancyLi1013** [comment] 2021-02-26 06:05
Hi @dave-juicelabs 

Thanks for posting this issue.

Could you please help provide your application sample? I cannot reproduce this with the usage in CMakeLists.txt.
```
find_package(PostgreSQL REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE PostgreSQL::PostgreSQL)
```

**Comment by ahupp** [comment] 2021-02-26 18:25
I've included a self-contained test cmake project that repos this in https://github.com/microsoft/vcpkg/issues/15632

**Comment by NancyLi1013** [comment] 2021-11-18 10:11
Thanks for your information @ahupp.

Closing this issue. Let's move the attention to #15632 to track this problem.

**Closed by NancyLi1013** 2021-11-18 10:11 UTC
Labels: requires:repro
