### ISSUE TITLE
[qtbase] `windeployqt` cannot find `Qt6Widgetsd.dll` if `CMAKE_BUILD_TYPE=Debug`

### ISSUE THREAD

**Issue by midrare** [microsoft/vcpkg#36250] opened 2024-01-19 02:55 UTC
**Describe the bug**
If the project was built with `CMAKE_BUILD_TYPE=Debug`, `windeployqt` logic looks in wrong folder for DLLs. (Deploy with `CMAKE_BUILD_TYPE=Release` works fine.)

**Environment**
- OS: Windows 11 x64
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32825 for x64

**To Reproduce**
1. Set up MCVE.
	**vcpkg.json**  
	```json
	{
	    "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
	    "name": "qt6-port-bug",
	    "version-semver": "0.1.0",
	    "builtin-baseline": "97dd26728e3856ed1ab62ee74ee3a391d9c81d19",
	    "dependencies": [
	        {
	            "name": "qtbase",
	            "version>=": "6.6.1"
	        },
	        {
	            "name": "qttranslations",
	            "version>=": "6.6.1"
	        }
	    ]
	}
	```  
  
	**CMakeLists.txt**
	```cmake
	cmake_minimum_required(VERSION 3.21)
	
	project("qt6portbug" VERSION "0.1.0" LANGUAGES C CXX RC)
	
	find_package(Qt6Core "6.6.1" CONFIG REQUIRED)
	find_package(Qt6Gui "6.6.1" CONFIG REQUIRED)
	find_package(Qt6Widgets "6.6.1" CONFIG REQUIRED)
	
	qt_standard_project_setup()
	
	qt_add_executable(qt6portbug main.cpp)
	target_link_libraries(qt6portbug PRIVATE Qt6::Core Qt6::Gui Qt6::Widgets)
	set_target_properties(qt6portbug PROPERTIES WIN32_EXECUTABLE ON)
	
	qt_generate_deploy_app_script(
	    TARGET qt6portbug
	    OUTPUT_SCRIPT qt6portbug_QTDEPLOY_SCRIPT
	    NO_UNSUPPORTED_PLATFORM_ERROR
	)
	
	install(TARGETS qt6portbug BUNDLE DESTINATION .)
	install(SCRIPT "${qt6portbug_QTDEPLOY_SCRIPT}")
	```  
  
    **main.cpp**
	````cpp
	#include <QApplication>
	#include <QMainWindow>
	
	auto main(int argc, char* argv[]) -> int {
	    QApplication app(argc, argv);
	    return app.exec();
	}
	````
2. Build project
	```bash
	cd qt6-port-bug
	cmake -B build -S . -G "Ninja" -DCMAKE_PROJECT_TOP_LEVEL_INCLUDES=C:/Apps/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_APPLOCAL_DEPS=OFF
	cmake --build build
	```
3. Run Qt6 deploy logic
	```bash
	cmake --install build --prefix "C:/qt6-port-bug/install"
	```
   ```bash
	Unable to find dependent libraries of C:\qt6-port-bug\build\vcpkg_installed\x64-windows\tools\Qt6\bin\Qt6Widgetsd.dll :Cannot open 'C:/qt6-port-bug/build/vcpkg_installed/x64-windows/tools/Qt6/bin/Qt6Widgetsd.dll': The system cannot find the file specified.
	```
   It seems like `windeployqt` is looking in the wrong folder altogether.

**Expected behavior**
DLLs are found in correct locations and deployed to correct file paths.

**Failure logs**
```bash
C:\qt6-port-bug> cmake --install build --prefix "C:/qt6-port-bug/install"
-- Install configuration: "Debug"
-- Up-to-date: C:/qt6-port-bug/install/bin/qt6portbug.exe
-- Writing C:/qt6-port-bug/install/bin/qt.conf
-- Running Qt deploy tool for C:/qt6-port-bug/build/qt6portbug.exe in working directory 'C:/qt6-port-bug/install'
'C:/qt6-port-bug/build/vcpkg_installed/x64-windows/tools/Qt6/bin/windeployqt.debug.bat' 'C:/qt6-port-bug/build/qt6portbug.exe' '--dir' '.' '--libdir' 'bin' '--plugindir' 'plugins' '--force'
Unable to find dependent libraries of C:\qt6-port-bug\build\vcpkg_installed\x64-windows\tools\Qt6\bin\Qt6Widgetsd.dll :Cannot open 'C:/qt6-port-bug/build/vcpkg_installed/x64-windows/tools/Qt6/bin/Qt6Widgetsd.dll': The system cannot find the file specified.
```

**Additional context**
This seems to be the exact same issue as https://github.com/microsoft/vcpkg/issues/17840 but the problem was not fixed and `qtbase` inherited the issue.

**Comment by jimwang118** [comment] 2024-01-19 06:20
Duplicate of https://github.com/microsoft/vcpkg/issues/17840

**Comment by midrare** [comment] 2024-01-19 20:37
Why is this a duplicate? They're two separate packages.

**Comment by midrare** [comment] 2024-01-20 12:08
@jimwang118 Non-qt5 discussion is [not allowed](https://github.com/microsoft/vcpkg/issues/17840#issuecomment-1902035756) in https://github.com/microsoft/vcpkg/issues/17840. Please re-open.

**Comment by amensel** [comment] 2024-01-20 16:06
Seconding @midrare's request to reopen this. Even though it's the same bug, if we're not allowed to discuss Qt6 issues in #17840 then this can't be closed as a dupe.

Working around this is a real nuisance.

**Closed** 2024-01-24 18:36 UTC
Labels: category:port-bug

**Comment by magjac** [comment] 2024-07-27 12:34
Please reopen. I use 821100d967e1737d96414a308e3f7cbe0d1abf18 and still have this problem:
```
'C:/Users/magjac/graphviz/windows/dependencies/libraries/vcpkg/installed/x64-windows/tools/Qt6/bin/windeployqt.debug.bat' 'C:/Users/magjac/graphviz/build/cmd/gvedit/Debug/gvedit.exe' '--dir' '.' '--libdir' 'bin' '--plugindir' 'plugins' '--qml-deploy-dir' 'qml' '--translationdir' 'translations' '--force' '--no-translations' '--qtpaths' 'C:/Users/magjac/graphviz/windows/dependencies/libraries/vcpkg/installed/x64-windows/tools/Qt6/bin/qtpaths6.exe' '--no-translations'
Warning: Translations will not be available due to the following error.
Cannot open C:/Users/magjac/graphviz/windows/dependencies/libraries/vcpkg/installed/x64-windows/translations/Qt6/catalogs.json
Unable to find dependent libraries of C:\Users\magjac\graphviz\windows\dependencies\libraries\vcpkg\installed\x64-windows\bin\Qt6Widgetsd.dll :Cannot open 'C:/Users/magjac/graphviz/windows/dependencies/libraries/vcpkg/installed/x64-windows/bin/Qt6Widgetsd.dll': The system cannot find the file specified.
```
I managed to work around it with:
```
  qt_generate_deploy_app_script(
      TARGET gvedit
      OUTPUT_SCRIPT deploy_script
      DEPLOY_TOOL_OPTIONS
        # workaround for https://github.com/microsoft/vcpkg/issues/17840 or
        # https://github.com/microsoft/vcpkg/issues/36250
        $<$<CONFIG:DEBUG>:--qtpaths ${WINDOWS_DEPENDENCY_VCPKG_DIR}/tools/Qt6/bin/qtpaths.debug.bat>
    )
    install(SCRIPT ${deploy_script})
```

**Comment by jimwang118** [comment] 2024-07-29 02:11
I suggest you open a new issue and we will fix it in time.
