### ISSUE TITLE
fftw3[openmp] fails to build

### ISSUE THREAD

**Issue by UniversalBinary** [microsoft/vcpkg#12453] opened 2020-07-16 22:20 UTC
PS C:\vcpkg> vcpkg install fftw3[openmp] fftw3[avx2] fftw3[threads]
Computing installation plan...
The following packages will be built and installed:
    fftw3[avx2,core,openmp,threads]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: fftw3:x86-windows
Building package fftw3[avx2,core,openmp,threads]:x86-windows...
Could not locate cached archive: C:\Users\gnost\AppData\Local\vcpkg\archives\05\05eb8474974b14f92b52ef0ee48e1777f8a62163.zip
-- Using cached C:/vcpkg/downloads/fftw-3.3.8.tar.gz
-- Extracting source C:/vcpkg/downloads/fftw-3.3.8.tar.gz
-- Applying patch omp_test.patch
-- Applying patch patch_targets.patch
-- Applying patch fftw3_arch_fix.patch
-- Applying patch aligned_malloc.patch
-- Using source at C:/vcpkg/buildtrees/fftw3/src/fftw-3-6b62db95a0.clean
-- Configuring x86-windows-dbg
-- Configuring x86-windows-rel
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: C:/vcpkg/buildtrees/fftw3/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\fftw3\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/fftw3/portfile.cmake:55 (vcpkg_install_cmake)
  scripts/ports.cmake:76 (include)

Error: Building package fftw3:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fftw3:x86-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

The log file is attached below:

[install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/4934540/install-x86-windows-dbg-out.log)

**Comment by LilyWangL** [comment] 2020-07-17 07:16
Thanks for posting this issue. Closed as duplicate of #10930.

**Closed by LilyWangL** 2020-07-17 07:16 UTC
Labels: category:port-bug
