### ISSUE TITLE
Package installation stopping after "Computing installation plan..." no errors given.

### ISSUE THREAD

**Issue by Sadkawt** [microsoft/vcpkg#18633] opened 2021-06-24 14:23 UTC
**Describe the bug**
Installing packages doesn't work and i'm not given an error message.

**Environment**
- OS: Windows
- Compiler: MSVC

**To Reproduce**
1. git clone https://github.com/microsoft/vcpkg
2. .\vcpkg\bootstrap-vcpkg.bat
3. .\vcpkg\vcpkg integrate install
4. .\vcpkg\vcpkg install raylib

**Expected behavior**
For a package to be installed, and for vcpkg.exe to be compiled on the machine instead of downloaded from github.

**Failure logs** 
[log.txt](https://github.com/microsoft/vcpkg/files/6709923/log.txt)

**Additional context**
Very confused as to why this happens, isn't ".\vcpkg\bootstrap-vcpkg.bat" supposed to compile an executable instead of downloading one? I've tried reinstalling vcpkg multiple times and have gotten this same result everytime.

**Comment by JonLiu1993** [comment] 2021-06-25 08:01
@Sadkawt ,Thanks for posting this issue.
Please add --DEBUG to your installation command, like "./vcpkg install raylib --DEBUG"and then send the complete log after running the command

**Comment by Sadkawt** [comment] 2021-06-25 08:11
@JonLiu1993, here you go.
[log2.txt](https://github.com/microsoft/vcpkg/files/6714606/log2.txt)

**Comment by JonLiu1993** [comment] 2021-06-25 08:19
@Sadkawt ,This issue is duplicate of #18636. We will track and solve it in issue #18636. This pr is temporarily turned off

**Closed by JonLiu1993** 2021-06-25 08:19 UTC
Labels: category:question

**Comment by PhoebeHui** [comment] 2021-06-25 08:50
@Sadkawt, what the revison of visual studio do you use?

**Comment by Sadkawt** [comment] 2021-06-25 08:59
@PhoebeHui Microsoft Visual Studio Community 2019, Version 16.10.2 (Is this what you're asking for?)

**Comment by PhoebeHui** [comment] 2021-06-25 09:02
@Sadkawt, yes, thanks for your response!

Could you try to download vcpkg from https://github.com/microsoft/vcpkg-tool/releases/tag/2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9 and replace the one in your local machine, and see if the issue persist?

I can't repro this issue locally, I want to confirm if it hit a compiler bug or the issue from vcpkg latest release.

**Comment by Sadkawt** [comment] 2021-06-25 09:12
@PhoebeHui Hello again, looks to me like the issue still persists :/. 
[log3.txt](https://github.com/microsoft/vcpkg/files/6714995/log3.txt)

**Comment by PhoebeHui** [comment] 2021-06-25 09:15
@Sadkawt, thanks for the information!
