### ISSUE TITLE
Exiv2 update to 0.27.4

### ISSUE THREAD

**Issue by ndurner** [microsoft/vcpkg#18840] opened 2021-07-06 18:46 UTC
Library name:Exiv2 

New version number: 0.27.4

**Comment by EvanAW** [comment] 2021-07-06 21:57
Exiv2 was updated to 0.27.4 an hour ago. 
See: https://github.com/microsoft/vcpkg/commit/75a90ccfb1f8d1206f1fb5900c27bf14d0a9aeb7

**Comment by JonLiu1993** [comment] 2021-07-07 01:52
@ndurner ,Thanks for posting this issue,this issue duplicate of #18690,so this issue will be closed

**Closed by JonLiu1993** 2021-07-07 01:52 UTC
