### ISSUE TITLE
MLPACK build failure

### ISSUE THREAD

**Issue by Blakjak88** [microsoft/vcpkg#21649] opened 2021-11-24 15:45 UTC
**Host Environment**
- OS: Windows 10 Pro
- Compiler: MSVC C++22

**To Reproduce**
`./vcpkg install mlpack`

**Failure logs** 
```
D:\sdk\vcpkg>vcpkg install mlpack
Computing installation plan...
The following packages will be built and installed:
    mlpack[core]:x64-windows-static -> 3.4.1#2
Detecting compiler hash for triplet x64-windows-static...
Restored 0 packages from D:\Users\davea\AppData\Local\vcpkg\archives in 193.9 us. Use --debug to see more details.
Starting package 1/1: mlpack:x64-windows-static
Building package mlpack[core]:x64-windows-static...
-- Downloading https://github.com/mlpack/mlpack/archive/7ae9ddda86c1751b6509ceb48b27d182feaae439.tar.gz -> mlpack-mlpack-7ae9ddda86c1751b6509ceb48b27d182feaae439.tar.gz...
-- Cleaning sources at D:/sdk/vcpkg/buildtrees/mlpack/src/82feaae439-787f7149b5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/sdk/vcpkg/downloads/mlpack-mlpack-7ae9ddda86c1751b6509ceb48b27d182feaae439.tar.gz
-- Applying patch cmakelists.patch
-- Applying patch fix-configure-error.patch
-- Applying patch fix-test-dependency.patch
-- Applying patch fix-dependencies.patch
-- Using source at D:/sdk/vcpkg/buildtrees/mlpack/src/82feaae439-787f7149b5.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: ninja -v
    Working Directory: D:/sdk/vcpkg/buildtrees/mlpack/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\sdk\vcpkg\buildtrees\mlpack\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:368 (vcpkg_execute_required_process)
  ports/mlpack/portfile.cmake:31 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package mlpack:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mlpack:x64-windows-static
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e
```
**Additional context**
All latest VCPKG packages of Armadillo, Ensmallen, Cereal, etc. are installed.

**Comment by JonLiu1993** [comment] 2021-11-25 02:24
@Blakjak88 ,Thanks for posting this issue, could you please provide the error log:
````
See logs for more information:
D:\sdk\vcpkg\buildtrees\mlpack\config-x64-windows-static-out.log
````

**Comment by Blakjak88** [comment] 2021-11-25 06:57
[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/7600846/config-x64-windows-static-out.log)

**Comment by JackBoosY** [comment] 2021-11-26 02:30
```
CMake Error at D:/sdk/vcpkg/installed/x64-windows-static/share/Armadillo/ArmadilloConfig.cmake:12 (include):
  include could not find requested file:

    /share/Armadillo/ArmadilloLibraryDepends.cmake
```
This issue should be fixed by PR #20439, can you please confirm that?

Thanks.

**Comment by JackBoosY** [comment] 2021-11-29 02:49
@Blakjak88 
```
git clone https://github.com/PhoebeHui/vcpkg.git
git checkout master
git merge --no-ff PhoebeHui-dev/Phoebe/vcpkg-cmake-config
git push origin master
```

**Comment by JonLiu1993** [comment] 2021-12-08 08:28
@Blakjak88 ,Do you use the steps above to confirm whether the problem is resolved?

**Comment by JackBoosY** [comment] 2021-12-10 03:00
Close this issue via #20439 merged.
If you still meet this issue, please reopen!

**Closed by JackBoosY** 2021-12-10 03:00 UTC
Labels: requires:more-information
