### ISSUE TITLE
[boost-build] Build error

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#28618] opened 2022-12-29 11:24 UTC
**Host Environment**

- OS: Windows 10 x64
- Compiler: MSVC 2022

**To Reproduce**

`./vcpkg install boost`

**Failure logs**

I have checked their are no network or proxy issues on my end.
Other packages are being installed properly.

```
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x64-windows-static...
Restored 39 package(s) from C:\Users\IshaanKarnik\AppData\Local\vcpkg\archives in 1.857 s. Use --debug to see more details.
Installing 1/124 boost-build:x64-windows...
Building boost-build[core]:x64-windows...
-- Using cached boostorg-build-boost-1.81.0.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/boost-build/src/ost-1.81.0-150c15c955.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/boostorg-build-boost-1.81.0.tar.gz
-- Applying patch 0002-fix-get-version.patch
-- Using source at C:/vcpkg/buildtrees/boost-build/src/ost-1.81.0-150c15c955.clean
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt: WinHttpSendRequest failed with exit code 12002
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt: WinHttpSendRequest failed with exit code 12002
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt: WinHttpSendRequest failed with exit code 12002
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt: WinHttpSendRequest failed with exit code 12002
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 2047 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 2.918 min (175075293 us)
```

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

```
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/boost-build/portfile.cmake:19 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)

error: building boost-build:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-build]+Build+error
Include '[boost-build] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: ecce05107 2022-12-28 (7 hours ago)
```

**Comment by LilyWangLL** [comment] 2023-03-20 07:42
Thanks for posting this issue. Please make sure your network is good or the proxy is available, make sure you can access https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt normally.

I think this issue could be closed as duplicate of https://github.com/microsoft/vcpkg/issues/29395. If this still is a problem for you, please reopen this issue with more info.

**Closed by LilyWangLL** 2023-03-20 07:42 UTC
Labels: category:question
