### ISSUE TITLE
[libpq] x64-osx-dynamic build error

### ISSUE THREAD

**Issue by faming-wang** [microsoft/vcpkg#22247] opened 2021-12-29 14:27 UTC
**Host Environment**
- OS: macOS  12.0.1
- Compiler: Apple clang version 13.0.0 (clang-1300.0.29.3)

**To Reproduce**
`vcpkg install libpq:x64-osx-dynamic`

**Failure logs** 
Computing installation plan...
The following packages will be built and installed:
    libpq[bonjour,core,openssl,zlib]:x64-osx-dynamic -> 12.9#1
Detecting compiler hash for triplet x64-osx-dynamic...
Restored 0 packages from /Users/Apple/.cache/vcpkg/archives in 27.13 us. Use --debug to see more details.
Starting package 1/1: libpq:x64-osx-dynamic
Building package libpq[bonjour,core,openssl,zlib]:x64-osx-dynamic...
-- Using community triplet x64-osx-dynamic. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/Apple/vcpkg/triplets/community/x64-osx-dynamic.cmake
-- Using cached postgresql-12.9.tar.bz2.
-- Cleaning sources at /Users/Apple/vcpkg/buildtrees/libpq/src/tgresql-12-07bd5aa2da.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/Apple/vcpkg/downloads/postgresql-12.9.tar.bz2
-- Applying patch patches/windows/install.patch
-- Applying patch patches/windows/win_bison_flex.patch
-- Applying patch patches/windows/openssl_exe_path.patch
-- Applying patch patches/windows/Solution.patch
-- Applying patch patches/windows/MSBuildProject_fix_gendef_perl.patch
-- Applying patch patches/windows/msgfmt.patch
-- Applying patch patches/windows/python_lib.patch
-- Applying patch patches/windows/fix-compile-flag-Zi.patch
-- Applying patch patches/windows/minimize_install.patch
-- Using source at /Users/Apple/vcpkg/buildtrees/libpq/src/tgresql-12-07bd5aa2da.clean
-- Getting CMake variables for x64-osx-dynamic-dbg
-- Getting CMake variables for x64-osx-dynamic-rel
-- Configuring x64-osx-dynamic-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /bin/bash -c "V=1 ././configure  \"--with-openssl\" \"--with-zlib\" \"--without-readline\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--enable-debug\" \"--prefix=/Users/Apple/vcpkg/installed/x64-osx-dynamic/debug\" \"--bindir=\\${prefix}/../tools/libpq/debug/bin\" \"--sbindir=\\${prefix}/../tools/libpq/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libpq\""
    Working Directory: /Users/Apple/vcpkg/buildtrees/libpq/x64-osx-dynamic-dbg
    Error code: 1
    See logs for more information:
      /Users/Apple/vcpkg/buildtrees/libpq/config-x64-osx-dynamic-dbg-out.log
      /Users/Apple/vcpkg/buildtrees/libpq/config-x64-osx-dynamic-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:796 (vcpkg_execute_required_process)
  ports/libpq/portfile.cmake:287 (vcpkg_configure_make)
  scripts/ports.cmake:142 (include)

Error: Building package libpq:x64-osx-dynamic failed with: BUILD_FAILED

**Additional context**
Error in the
 /Users/Apple/vcpkg/buildtrees/libpq/x64-osx-dynamic-dbg/config.log file
line 8660: dyld[72665]: Library not loaded: @rpath/libssl.1.1.dylib
[config.log](https://github.com/microsoft/vcpkg/files/7789300/config.log)
[config-x64-osx-dynamic-dbg-err.log](https://github.com/microsoft/vcpkg/files/7789322/config-x64-osx-dynamic-dbg-err.log)
[config-x64-osx-dynamic-dbg-out.log](https://github.com/microsoft/vcpkg/files/7789323/config-x64-osx-dynamic-dbg-out.log)

**Comment by faming-wang** [comment] 2021-12-29 14:30
The following packages are already installed: openssl[core]:x64-osx-dynamic -> 1.1.1l#4

**Comment by JackBoosY** [comment] 2022-05-10 07:33
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by daschuer** [comment] 2022-06-10 05:48
I can confirm that this is still an issue with the latest main, please reopen.
It has been tested here: https://github.com/daschuer/vcpkg/actions/runs/2471345461
creating the same error messages.

**Comment by daschuer** [comment] 2022-06-10 05:51
`Reason: tried: '/usr/local/lib/libssl.1.1.dylib' (no such file), '/usr/lib/libssl.1.1.dylib' (no such file)`

It the lookup path for libssl is wrong?

**Comment by daschuer** [comment] 2022-06-10 05:56
from openssl logs:
```
-- Installing: /Users/runner/mixxx-vcpkg/packages/openssl_x64-osx-dynamic-min10.12/debug/lib/libssl.3.dylib
-- Installing: /Users/runner/mixxx-vcpkg/packages/openssl_x64-osx-dynamic-min10.12/debug/lib/libssl.dylib
-- Installing: /Users/runner/mixxx-vcpkg/packages/openssl_x64-osx-dynamic-min10.12/debug/lib/libcrypto.3.dylib
-- Installing: /Users/runner/mixxx-vcpkg/packages/openssl_x64-osx-dynamic-min10.12/debug/lib/libcrypto.dylib
```

**Comment by daschuer** [comment] 2022-06-10 06:13
This one seems to be related https://github.com/microsoft/vcpkg/issues/24089

**Comment by Thomas1664** [comment] 2022-06-10 06:52
I looked at your repo. You are still using an old version of the vcpkg catalogue. Consequently, you're not getting the fix introduced in #24090.

**Comment by daschuer** [comment] 2022-06-10 15:29
The branch does contain the patch form #24090, see: https://github.com/daschuer/vcpkg/blob/f5c1628f057d433defe6d2ec5b4a5f18cd6c929b/ports/openssl/unix/CMakeLists.txt#L266

But I will merge from microsoft/main and start the build again, just in case.

**Comment by Thomas1664** [comment] 2022-06-10 21:19
There is nothing I can do about this because I'm not familiar with makefiles and I can't figure out where `1.1.dylib` comes from. What I suspect is that makefile will find your system's openssl first, which then causes autoconf to search for openssl 1.1.

I suggest to open an issue upstream to request support for openssl 3.
Furthermore, you could pin your baseline to openssl 1.1.1. Please note that 1.1.1x won't be updated. Consequently you have to do the updates by yourself.

**Comment by daschuer** [comment] 2022-06-11 12:59
Here is a build with the recent master merged: https://github.com/daschuer/vcpkg/runs/6833707010

After applying the patch that keeps the config.log, I see that the issue has shifted: 
``` 
dyld: Library not loaded: @rpath/liblz4d.dylib
  Referenced from: /Users/runner/mixxx-vcpkg/buildtrees/libpq/x64-osx-dynamic-min10.12-dbg/./conftest
  Reason: image not found
```

[config.log-x64-osx-dynamic-min10.12-dbg.log](https://github.com/microsoft/vcpkg/files/8883911/config.log-x64-osx-dynamic-min10.12-dbg.log)

**Comment by daschuer** [comment] 2022-06-11 14:45
The liblzz4d.dylib is installed:
``` 
-- Installing: /Users/runner/mixxx-vcpkg/packages/lz4_x64-osx-dynamic-min10.12/debug/lib/liblz4d.dylib
``` 

does anyone have an idea how to fix that?

**Comment by dg0yt** [comment] 2022-06-11 15:04
You are in the land of unsupported triplets... and vcpkg doesn't "support" dynamic linkage because it lacks expert to help resolve the dynamic lib lookup for running artifacts.

- vcpkg does properly build all dependencies.
- libpq's configure tries to run a test program during the build.
- This test program fails to find dependencies (`@rpath/<dylib>`).

You can try to set environment variable `DYLD_LIBRARY_PATH` to `<vpckg_installed>/[debug/]lib`.
Another option might be to patch out this test. (How would it work in cross builds?)

**Comment by olsen232** [comment] 2022-09-29 20:56
I've hit this same issue - I think it's relevant that it fails when configuring the debug build-type. The release build-type seems to work. Something (perhaps DYLD_LIBRARY_PATH or the rpath?) seems to be be configured so as to find the release libraries but not the debug libraries.
I've tried to just disable the debug build-type since I don't care about it at all using `set(VCPKG_BUILD_TYPE release)` but oddly it doesn't work - it still fails while trying to configure the debug build-type. Looking into it more...

**Comment by olsen232** [comment] 2022-09-29 21:55
FYI I moved `set(VCPKG_BUILD_TYPE release)` out of my root `CMakeLists.txt` and into `vcpkg-overlay-triplets/x64-osx.cmake` and now it is taking effect. I'm still too ignorant about my build system to know why but this may help somebody

**Comment by dg0yt** [comment] 2022-09-30 07:30
I can reproduce the issue. I'm afraid this is a more general issue for *-osx-dynamic while maintaining relocatability: Executables compiled during configuration/build cannot resolve vcpkg dylibs immediately.

- vcpkg installs dylibs with "unresolved" install name:
   ~~~
  vcpkg % otool -D installed/x64-osx-dynamic/debug/lib/liblz4d.dylib 
  installed/x64-osx-dynamic/debug/lib/liblz4d.dylib:
  @rpath/liblz4d.dylib
  ~~~
  This is fairly okay, but...
- When using the dylib in an executable, before applocal deployment as in vcpkg's `tools/${PORT}`, the default `RPATH` provided by the executable isn't sufficient to locate the dylibs when running that executable. This is what we see here with `conftest`:
  ~~~
  configure:16791: gcc -o conftest -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -Wno-compound-token-split-by-macro -g -fPIC -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk  -I/Users/dg0yt/dev/vcpkg/installed/x64-osx-dynamic/debug/lib/pkgconfig/../../../include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk -L/Users/dg0yt/dev/vcpkg/installed/x64-osx-dynamic/debug/lib -L/Users/dg0yt/dev/vcpkg/installed/x64-osx-dynamic/debug/lib/pkgconfig/../../lib  conftest.c -L/Users/dg0yt/dev/vcpkg/installed/x64-osx-dynamic/debug/lib/pkgconfig/../../lib -llz4d -L/Users/dg0yt/dev/vcpkg/installed/x64-osx-dynamic/debug/lib/pkgconfig/../../lib -lssl -L/Users/dg0yt/dev/vcpkg/installed/x64-osx-dynamic/debug/lib/pkgconfig/../../lib -lcrypto -L/Users/dg0yt/dev/vcpkg/installed/x64-osx-dynamic/debug/lib/pkgconfig/../../lib -lz -lm  >&5
  configure:16791: $? = 0
  configure:16791: ./conftest
  dyld[73277]: Library not loaded: '@rpath/liblz4d.dylib'
    Referenced from: '/Users/dg0yt/dev/vcpkg/buildtrees/libpq/x64-osx-dynamic-dbg/conftest'
    Reason: tried: '/usr/local/lib/liblz4d.dylib' (no such file), '/usr/lib/liblz4d.dylib' (no such file)
  ././configure: line 2121: 73277 Abort trap: 6           ./conftest$ac_exeext
  ~~~
- This might be resolved in various ways, but not for free: 
  - We might set `DYLD_LIBRARY_PATH`, but this is intrusive and can quickly break system programs.
  - We might try to set `DYLD_LIBRARY_PATH_FALLBACK`, but AFAIU macOS has security mechanisms that clean this variable before running system programs, including the shell. It is not enough to set it before starting `configure`.
  - We may pass `-Wl,-rpath...`, but this will lead to absolute paths also in the desired installed libraries and programs. It probably needs `install_name_tool -delete_rpath ...` to clean this up after installation.
  - Anything else?
    (These types of configuration tests suck. For cross builds, they cannot work at all.)

**Comment by dg0yt** [comment] 2022-10-05 05:59
Well, we can just pass `DYLD_FALLBACK_LIBRARY_PATH` as a parameter to `configure`.

**Closed** 2022-10-05 21:58 UTC
Labels: category:community-triplet
