### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by Kurbaba123** [microsoft/vcpkg#37137] opened 2024-03-05 09:29 UTC
Package: openssl:x64-windows@3.2.1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33521.0
-    vcpkg-tool version: 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b
    vcpkg-scripts version: 4d184cfdc 2024-03-05 (37 minutes ago)

**To Reproduce**

`vcpkg install openssl:x64-windows`
**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.2.1.tar.gz.
-- Cleaning sources at C:/libs/vcpkg/buildtrees/openssl/src/nssl-3.2.1-8707343470.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/libs/vcpkg/downloads/openssl-openssl-openssl-3.2.1.tar.gz
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at C:/libs/vcpkg/buildtrees/openssl/src/nssl-3.2.1-8707343470.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Prerunning x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Windows/PERL Configure enable-static-engine enable-capieng no-tests no-docs shared no-apps no-makedepend VC-WIN64A --debug --prefix=C:\\libs\\vcpkg\\packages\\openssl_x64-windows\\debug --openssldir=C:\\libs\\vcpkg\\packages\\openssl_x64-windows\\debug AS=C:\\libs\\vcpkg\\downloads\\tools\\nasm\\nasm-2.16.01\\nasm.exe "CC=C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x64\\cl.exe" "CFLAGS=  -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1  " "AR=C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x64\\lib.exe" "ARFLAGS=-machine:x64 -nologo" "LD=C:\\Program Files\\Microsoft Visual Studio\\2022\\Professional\\VC\\Tools\\MSVC\\14.39.33519\\bin\\Hostx64\\x64\\link.exe" "LDFLAGS= -machine:x64 -nologo    -debug -INCREMENTAL "
    Working Directory: C:/libs/vcpkg/buildtrees/openssl/x64-windows-dbg
    Error code: %1 is not a valid Win32 application
    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:125 (vcpkg_execute_required_process)
  ports/openssl/windows/portfile.cmake:69 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:74 (include)
  scripts/ports.cmake:172 (include)



```

**Comment by JonLiu1993** [comment] 2024-03-05 09:41
Duplicate of https://github.com/microsoft/vcpkg/issues/32787.

**Closed by JonLiu1993** 2024-03-05 09:41 UTC
