### ISSUE TITLE
[llvm:x64-windows-dbg] build failure

### ISSUE THREAD

**Issue by luki446** [microsoft/vcpkg#13505] opened 2020-09-12 20:32 UTC
**Host Environment**
- OS: Windows 10 x64 professional 19041.508

**To Reproduce**
`.\vcpkg.exe install llvm:x64-windows`

**Failure logs** 

PS D:\Projects\vcpkg> .\vcpkg.exe install llvm:x64-windows
Computing installation plan...
The following packages will be built and installed:
    llvm[clang,core,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-rtti,lld,tools]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: llvm:x64-windows
Building package llvm[clang,core,disable-abi-breaking-checks,disable-assertions,disable-clang-static-analyzer,enable-rtti,lld,tools]:x64-windows...
Could not locate cached archive: C:\Users\luki\AppData\Local\vcpkg/archives\03\03e0a6eede08b0d4f1cf727968a331a4beea355f.zip
-- Note: llvm only supports static library linkage. Building static library.
-- Using cached D:/Projects/vcpkg/downloads/llvm-llvm-project-llvmorg-10.0.0.tar.gz
-- Cleaning sources at D:/Projects/vcpkg/buildtrees/llvm/src/org-10.0.0-5e71087b84.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Projects/vcpkg/downloads/llvm-llvm-project-llvmorg-10.0.0.tar.gz
-- Applying patch 0001-allow-to-use-commas.patch
-- Applying patch 0002-fix-install-paths.patch
-- Applying patch 0003-fix-vs2019-v16.6.patch
-- Applying patch 0004-fix-dr-1734.patch
-- Using source at D:/Projects/vcpkg/buildtrees/llvm/src/org-10.0.0-5e71087b84.clean
-- Configuring x64-windows
-- Building x64-windows-dbg

**Additional context**
While trying to install x64 llvm everything stopped at building x64-windows-dbg and It's standing like this for around 4 hours and probably won't go further.

**Comment by NancyLi1013** [comment] 2020-09-14 06:24
Hi @luki446 
Thanks for posting this issue.

Since `llvm `needs a long time to build. This should be as intended.  But I'm not sure the specific build time. 
Could you please try it again?

**Comment by NancyLi1013** [comment] 2020-09-29 08:20
I'm closing this issue for now since there is no any response in a long time.
Please feel free to reopen this if it is still a problem for you.

**Closed by NancyLi1013** 2020-09-29 08:20 UTC
Labels: category:question
