### ISSUE TITLE
[GRPC] [C-ARES] build failure on self hosted runners

### ISSUE THREAD

**Issue by diehard2** [microsoft/vcpkg#38050] opened 2024-04-08 21:01 UTC
### Operating system

Ubuntu 22.04

### Compiler

gcc 11.4

### Steps to reproduce the behavior

```Shell
`vcpkg/vcpkg install grpc`
```

### Failure logs

[config-x64-linux-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/14910807/config-x64-linux-dbg-CMakeCache.txt.log)
[config-x64-linux-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/14910809/
[config-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/14910810/config-x64-linux-out.log)
config-x64-linux-rel-CMakeCache.txt.log)

### Additional context

The command is working on github's default runners, however it isn't working on my company's self-hosted runners. I'm unable to see any obvious difference between the two. The action is very simple. 

``` 
name: CI

on:
  workflow_dispatch:


jobs:
  compile:
    name: VCPKG DEBUG
    runs-on: ubuntu-latest
    steps:
    - name: Install package
      run: |
        sudo apt-get update
        sudo apt-get install perl autoconf-archive ninja-build cmake pkg-config
    - name: Install vcpkg
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        vcpkg/bootstrap-vcpkg.sh
        env
    - name: Install grpc
      run: |
          set +e
          vcpkg/vcpkg install grpc
          echo "***** debug *****"
          cat /home/runner/work/vcpkg_ci_debug/vcpkg_ci_debug/vcpkg/buildtrees/grpc/config-x64-linux-dbg-CMakeCache.txt.log
          echo "***** release *****"
          cat /home/runner/work/vcpkg_ci_debug/vcpkg_ci_debug/vcpkg/buildtrees/grpc/config-x64-linux-rel-CMakeCache.txt.log
          echo "***** general *****"
          cat /home/runner/work/vcpkg_ci_debug/vcpkg_ci_debug/vcpkg/buildtrees/grpc/config-x64-linux-out.log

```

It appears that ${PACKAGE_PREFIX_DIR} from 

``` 
get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../" **ABSOLUTE)
set_and_check(c-ares_INCLUDE_DIR** "${PACKAGE_PREFIX_DIR}/include") 
```

is resolving to "/home/ubuntu/actions-runner/_work/vcpkg_debug/vcpkg_debug/vcpkg_installed/include" rather than 
"/home/ubuntu/actions-runner/_work/vcpkg_debug/vcpkg_debug/vcpkg_installed/x64-linux/include. I tried just creating that directory, but then it failed to find re2 components. Thanks for any help.

**Comment by dg0yt** [comment] 2024-04-09 05:59
Don't use CMake 3.29.1

https://github.com/microsoft/vcpkg/issues/37968

**Comment by Cheney-W** [comment] 2024-04-09 07:33
Duplicate of https://github.com/microsoft/vcpkg/issues/37968

**Closed by Cheney-W** 2024-04-09 07:33 UTC
Labels: category:port-bug
