### ISSUE TITLE
[libigl] Can not download libigl of version 2.4.0

### ISSUE THREAD

**Issue by zone-1614** [microsoft/vcpkg#29240] opened 2023-01-29 01:24 UTC
The default version of libigl is `2.3.0`. I change it to `2.4.0` in the file `vcpkg/ports/libigl/vcpkg.json`. And then i remove the libigl
`vcpkg remove libigl`. Reinstall `vcpkg install libigl[imgui]:x64-windows`, 
 but it doesn't work, vcpkg still download the version 2.3.0

**Comment by Adela0814** [comment] 2023-01-29 02:27
There is already a [PR: 27963](https://github.com/microsoft/vcpkg/pull/27963) about upgrading the `libigl` version, please try this PR. Thanks.

**Comment by Adela0814** [comment] 2023-01-29 02:28
Duplicate of issue: https://github.com/microsoft/vcpkg/issues/23354

**Closed** 2023-01-29 02:28 UTC
Labels: category:port-update
