### ISSUE TITLE
[qt5-activeqt] Build error

### ISSUE THREAD

**Issue by mi-robin** [microsoft/vcpkg#33817] opened 2023-09-16 23:13 UTC
Package: qt5-activeqt:x64-windows -> 5.15.10

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30147.0
- vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
  vcpkg-scripts version: e8c2a04eb 2023-09-15 (25 hours ago)

**To Reproduce**

`vcpkg install qt5:x64-windows`
**Failure logs**

```
CMake Warning at scripts/cmake/vcpkg_buildpath_length_warning.cmake:4 (message):
  qt5-activeqt's buildsystem uses very long paths and may fail on your
  system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  installed/x64-windows/share/qt5/qt_download_submodule.cmake:13 (vcpkg_buildpath_length_warning)
  installed/x64-windows/share/qt5/qt_submodule_installation.cmake:5 (qt_download_submodule)
  ports/qt5-activeqt/portfile.cmake:2 (qt_submodule_installation)
  scripts/ports.cmake:147 (include)


-- Using cached qtactiveqt-everywhere-opensource-src-5.15.10.tar.xz.
-- Cleaning sources at D:/desktop/_dev/vcpkg/buildtrees/qt5-activeqt/src/5.15.10-d7c32d7988.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/desktop/_dev/vcpkg/downloads/qtactiveqt-everywhere-opensource-src-5.15.10.tar.xz
-- Using source at D:/desktop/_dev/vcpkg/buildtrees/qt5-activeqt/src/5.15.10-d7c32d7988.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at D:/desktop/_dev/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package build-x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/nmake.exe" -j 21
    Working Directory: D:/desktop/_dev/vcpkg/buildtrees/qt5-activeqt/x64-windows-dbg
    See logs for more information:
      D:\desktop\_dev\vcpkg\buildtrees\qt5-activeqt\package-build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_qmake.cmake:3 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_qmake.cmake:76 (z_run_jom_build)
  installed/x64-windows/share/qt5/qt_build_submodule.cmake:11 (vcpkg_build_qmake)
  installed/x64-windows/share/qt5/qt_submodule_installation.cmake:9 (qt_build_submodule)
  ports/qt5-activeqt/portfile.cmake:2 (qt_submodule_installation)
  scripts/ports.cmake:147 (include)
```

<details><summary>D:\desktop\_dev\vcpkg\buildtrees\qt5-activeqt\package-build-x64-windows-dbg-err.log</summary>

```
Microsoft (R) Program Maintenance Utility Version 14.29.30147.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1065: invalid option 'j'
Stop.
```

</details>

**Comment by nanthony21** [comment] 2023-09-17 02:55
I believe this is true same error described in #25653

**Comment by FrankXie05** [comment] 2023-09-19 06:40
Duplicate of https://github.com/microsoft/vcpkg/issues/25653

**Closed by FrankXie05** 2023-09-19 06:40 UTC
