### ISSUE TITLE
[icu] Build error

### ISSUE THREAD

**Issue by PooyaEimandar** [microsoft/vcpkg#33071] opened 2023-08-09 09:58 UTC
Package: icu[core,tools]:arm64-osx -> 73.1

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 14.0.3.14030022
-    vcpkg-tool version: 2023-08-02-6d13efa755f9b5e101712d210199e4139b4c29f6
    vcpkg-scripts version: 247662ef3 2023-08-08 (15 hours ago)

**To Reproduce**

`vcpkg install qtbase`

**Failure logs**

```
-- Downloading https://github.com/unicode-org/icu/releases/download/release-73-1/icu4c-73_1-src.tgz -> icu4c-73_1-src.tgz...
-- Extracting source /Users/pooyaeimandar/Codes/vcpkg/downloads/icu4c-73_1-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Applying patch fix-win-build.patch
-- Using source at /Users/pooyaeimandar/Codes/vcpkg/buildtrees/icu/src/c-73_1-src-3575e21c7c.clean
-- Found external ninja('1.11.1').
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
-- Generating configure for arm64-osx
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /opt/homebrew/bin/autoreconf -vfi
    Working Directory: /Users/pooyaeimandar/Codes/vcpkg/buildtrees/icu/src/c-73_1-src-3575e21c7c.clean/source
    Error code: 2
    See logs for more information:
      /Users/pooyaeimandar/Codes/vcpkg/buildtrees/icu/autoconf-arm64-osx-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:635 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:54 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)



```
<details><summary>/Users/pooyaeimandar/Codes/vcpkg/buildtrees/icu/autoconf-arm64-osx-err.log</summary>

```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
Can't exec "aclocal": No such file or directory at /opt/homebrew/Cellar/autoconf/2.71/share/autoconf/Autom4te/FileUtils.pm line 274.
autoreconf: error: aclocal failed with exit status: 2
```
</details>

**Additional context**

**Comment by MonicaLiu0311** [comment] 2023-08-09 10:30
Duplicate of #24870.

**Closed by MonicaLiu0311** 2023-08-09 10:30 UTC
Labels: category:tool-update
