### ISSUE TITLE
armv7:  get_regular_files_non_recursive(/vcpkg/triplets): Value too large for defined data type

### ISSUE THREAD

**Issue by vladimir-voinea** [microsoft/vcpkg#21755] opened 2021-11-29 16:18 UTC
**Describe the bug**
I am getting an error when installing packages on armv7, using Docker multiarch build.

**Environment**
- OS: Docker multibuild via buildx, on armv7 target
- Compiler: revision

**To Reproduce**

In Dockerfile:

FROM ubuntu:20.10
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && apt install -yy -q --no-install-recommends ca-certificates libssl-dev git build-essential autoconf libtool pkg-config libtool curl make g++ zip unzip tar ninja-build
RUN curl -L -o cmake-3.22.0.tar.gz https://github.com/Kitware/CMake/releases/download/v3.22.0/cmake-3.22.0.tar.gz && file cmake-3.22.0.tar.gz && tar xvf cmake-3.22.0.tar.gz && cd cmake-3.22.0 && ./bootstrap && make && make install && cd / && rm -rf ./cmake-3.22.0*
RUN git clone https://github.com/microsoft/vcpkg
RUN ./vcpkg/bootstrap-vcpkg.sh
ENV VCPKG_FORCE_SYSTEM_BINARIES=1
RUN ./vcpkg/vcpkg install restinio json-dto spdlog
RUN ./vcpkg/vcpkg integrate install

Built with:
docker buildx build --push --platform linux/amd64,linux/arm/v7 -t image_name_goes_here .

**Expected behavior**
Package installation should be successful on armv7. This arch is needed for Docker images for Raspberry Pi 3B+

**Failure logs** 
 => ERROR [linux/arm/v7 12/14] RUN ./vcpkg/vcpkg install restinio json-dto spdlog                 0.4s
------
 > [linux/arm/v7 12/14] RUN ./vcpkg/vcpkg install restinio json-dto spdlog:
#17 0.286 get_regular_files_non_recursive(/vcpkg/triplets): Value too large for defined data type
------
Dockerfile:39
--------------------
  37 |     RUN ./vcpkg/bootstrap-vcpkg.sh
  38 |     ENV VCPKG_FORCE_SYSTEM_BINARIES=1
  39 | >>> RUN ./vcpkg/vcpkg install restinio json-dto spdlog
  40 |     RUN ./vcpkg/vcpkg integrate install
  41 |     
--------------------
error: failed to solve: rpc error: code = Unknown desc = process "/bin/sh -c ./vcpkg/vcpkg install restinio json-dto spdlog" did not complete successfully: exit code: 1

**Additional context**
The vcpkg commands run without error for the linux/amd64 Docker build target.

**Comment by autoantwort** [comment] 2021-11-30 01:08
Duplicate of #21189 :)

**Comment by JonLiu1993** [comment] 2021-11-30 09:40
@vladimir-voinea ,Thanks for posting this issue, this issue duplicate of #21189, temporarily close this issue, we will track it in issue #21189

**Closed by JonLiu1993** 2021-11-30 09:40 UTC
Labels: category:vcpkg-bug, info:registries
