### ISSUE TITLE
[harfbuzz] Build error

### ISSUE THREAD

**Issue by xroot3** [microsoft/vcpkg#34370] opened 2023-10-09 08:43 UTC
How to reproduce issue:
I Install Visual Studio 2017 inWindows10,
Try to install with following commands in the command line:
vcpkg install pcl[*]:x64-windows
__________________________________________________________________________________________________________
Copy issue body from C:/Program Files/vcpkg-master/installed/vcpkg/issue_body.md
Building harfbuzz:x64-windows...
-- Using cached harfbuzz-harfbuzz-8.2.1.tar.gz.
-- Cleaning sources at C:/Program Files/vcpkg-master/buildtrees/harfbuzz/src/8.2.1-63f9ae7085.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Program Files/vcpkg-master/downloads/harfbuzz-harfbuzz-8.2.1.tar.gz
-- Using source at C:/Program Files/vcpkg-master/buildtrees/harfbuzz/src/8.2.1-63f9ae7085.clean
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/Program Files/vcpkg-master/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/vcpkg-master/downloads/tools/ninja/1.10.2-windows/ninja.exe" install -v
    Working Directory: C:/Program Files/vcpkg-master/buildtrees/harfbuzz/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Program Files\vcpkg-master\buildtrees\harfbuzz\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:70 (vcpkg_install_meson)
  scripts/ports.cmake:168 (include)

**Comment by FrankXie05** [comment] 2023-10-09 08:47
@xroot3 Please provide the error log: `C:\Program Files\vcpkg-master\buildtrees\harfbuzz\package-x64-windows-dbg-out.log`

**Comment by xroot3** [comment] 2023-10-09 08:56
> @xroot3 Please provide the error log: `C:\Program Files\vcpkg-master\buildtrees\harfbuzz\package-x64-windows-dbg-out.log`

[package-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12844128/package-x64-windows-dbg-out.log)

**Comment by FrankXie05** [comment] 2023-10-09 08:59
```
C:\Program Files\vcpkg-master\buildtrees\harfbuzz\src\8.2.1-63f9ae7085.clean\src\hb-subset.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
ninja: build stopped: subcommand failed.
```
Duplicate of https://github.com/microsoft/vcpkg/issues/34037

**Closed by FrankXie05** 2023-10-09 08:59 UTC
Labels: requires:more-information

**Comment by xroot3** [comment] 2023-10-09 09:12
> ```
> C:\Program Files\vcpkg-master\buildtrees\harfbuzz\src\8.2.1-63f9ae7085.clean\src\hb-subset.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
> ninja: build stopped: subcommand failed.
> ```
> 
> Duplicate of #34037

But #34037 is still Open?

**Comment by FrankXie05** [comment] 2023-10-09 09:40
Yes, It will be fixed by PR https://github.com/microsoft/vcpkg/pull/34346
