### ISSUE TITLE
./vcpkg install curl[tool] fails

### ISSUE THREAD

**Issue by martti-cloudkey** [microsoft/vcpkg#14834] opened 2020-11-29 18:02 UTC
-- Installing: /home/martti/temp/vcpkg/packages/curl_x64-linux/share/curl/curl-config
-- Fixing pkgconfig file: /home/martti/temp/vcpkg/packages/curl_x64-linux/lib/pkgconfig/libcurl.pc
-- CHECK_LIB_lber_RELEASE:CHECK_LIB_lber_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:233 (message):
  Library "lber" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:299 (vcpkg_fixup_pkgconfig_check_files)
  ports/curl/portfile.cmake:185 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:136 (include)

Error: Building package curl:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: curl:x64-linux
  Vcpkg version: 2020.11.12-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment] 2020-11-30 03:10
Will be fixed in #14807.

**Comment by klalumiere** [comment] 2020-12-09 00:20
For some reasons I'm not able to reproduce the issue anymore, either on my machine or in a Docker container (I used `rikorose/gcc-cmake`). Maybe the issue will also be solved for you too if you pull `master`. :thinking:

**Closed** 2020-12-23 07:19 UTC
Labels: category:port-bug
