### ISSUE TITLE
[vcpkg upgrade] [boost] upgrade boost will not upgrade boost-* packages

### ISSUE THREAD

**Issue by zibingrong** [microsoft/vcpkg#14470] opened 2020-11-09 02:21 UTC
**Describe the bug**
upgrade boost will not upgrade boost-* packages.
I think it should upgrade all boost-* packages to current version.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 16.7.7
**To Reproduce**

1. .\vcpkg.exe upgrade boost:x64-windows
2. See error:
The following packages will be rebuilt:
  * boost[core]:x64-windows
The following packages will be built and installed:
  * boost-stl-interfaces[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
If you are sure you want to rebuild the above packages, run this command with the --no-dry-run option.

**Comment by PhoebeHui** [comment] 2020-11-09 08:32
Confrimed, this issue could reproduce.

As a workround, you can try following steps:

1. ./vcpkg remove boost-uninstall:x64-windows
2. Get vcpkg source by 'git pull'
3. ./vcpkg install boost:x64-windows

**Comment by strega-nil** [comment] 2020-11-09 22:29
This is kind of the issue with how we've implemented boost; it's not really a bug, just the way it works right now. We don't really have plans to fix this at this point, and I don't know how we'd do it in the future.

Assigning to @ras0219 since he seems like he might be interested in this.

**Comment by zibingrong** [comment] 2020-11-10 03:36
@PhoebeHui I try your workaround steps but failed:

 .\vcpkg.exe remove boost-uninstall:x64-windows
The following packages are not installed, so not removed:
    boost-uninstall:x64-windows
Package boost-uninstall:x64-windows is not installed

 .\vcpkg.exe install boost-uninstall:x64-windows
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    boost-uninstall[core]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: boost-uninstall:x64-windows
Building package boost-uninstall[core]:x64-windows...
Could not locate cached archive: C:\Users\liugu\AppData\Local\vcpkg\archives\b5\b50d4a1f9aab9fdf55e127513a44ec144eec8ad2.zip
--
Please use the following command when you need to remove all boost ports/components:
    "./vcpkg remove boost-uninstall:x64-windows --recurse"

-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\liugu\AppData\Local\vcpkg\archives\b5\b50d4a1f9aab9fdf55e127513a44ec144eec8ad2.zip
Building package boost-uninstall[core]:x64-windows... done
Installing package boost-uninstall[core]:x64-windows...
Installing package boost-uninstall[core]:x64-windows... done
Elapsed time for package boost-uninstall:x64-windows: 908.5 ms

Total elapsed time: 5.995 s

 .\vcpkg.exe remove boost-uninstall:x64-windows
The following packages will be removed:
    boost-uninstall:x64-windows
Removing package boost-uninstall:x64-windows...
Removing package boost-uninstall:x64-windows... done

**Comment by PhoebeHui** [comment] 2020-11-10 05:43
@zibingrong, I see, boost-uninstall has been added by https://github.com/microsoft/vcpkg/pull/12851 on Aug, it doesn't work for previous revision, please try following steps instead.

./vcpkg remove boost-vcpkg-helpers --recurse
./vcpkg remove boost-modular-build-helper
./vcpkg remove boost-build

**Comment by zibingrong** [comment] 2020-11-11 08:40
> @zibingrong, I see, boost-uninstall has been added by #12851 on Aug, it doesn't work for previous revision, please try following steps instead.
> 
> ./vcpkg remove boost-vcpkg-helpers --recurse
> ./vcpkg remove boost-modular-build-helper
> ./vcpkg remove boost-build

@PhoebeHui It is work. Thank you very much.

**Comment by strega-nil** [comment] 2020-11-11 17:39
This seems to have been figured out! Thanks y'all, if you need any other help please don't hesitate to open another issue.

**Closed by strega-nil** 2020-11-11 17:39 UTC
Labels: category:vcpkg-feature
