### ISSUE TITLE
Error: Building package pcre:x86-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by wangsunner** [Microsoft/vcpkg#4781] opened 2018-11-21 08:51 UTC
E:\tmp\cpp\vcpkg>vcpkg.exe install glib
The following packages will be built and installed:
  * gettext[core]:x86-windows
    glib[core]:x86-windows
  * libffi[core]:x86-windows
  * libiconv[core]:x86-windows
  * pcre[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/6: pcre:x86-windows
Building package pcre[core]:x86-windows...
Warning: The following VS instances are excluded because the English language pack is unavailable.
    C:\Program Files (x86)\Microsoft Visual Studio\2017\Community
Please install the English language pack.
-- Using cached E:/tmp/cpp/vcpkg/downloads/pcre-8.41.zip
-- Extracting source E:/tmp/cpp/vcpkg/downloads/pcre-8.41.zip
-- Applying patch E:/tmp/cpp/vcpkg/ports/pcre/fix-option-2.patch
-- Applying patch E:/tmp/cpp/vcpkg/ports/pcre/fix-arm-config-define.patch
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: E:/tmp/cpp/vcpkg/buildtrees/pcre/x86-windows-rel/vcpkg-parallel-configure
    See logs for more information:
      E:\tmp\cpp\vcpkg\buildtrees\pcre\config-x86-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:257 (vcpkg_execute_required_process)
  ports/pcre/portfile.cmake:24 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)

Error: Building package pcre:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pcre:x86-windows
  Vcpkg version: 2018.10.20-nohash

**Comment by NancyLi1013** [comment] 2019-04-16 02:23
Hi @wangsunner, thanks for posting this issue. The package pcre has been updated and It should be fixed now. we cannot reproduce it. Please feel free to reopen this or open a new issue if this is still a problem for you.

**Closed by NancyLi1013** 2019-04-16 02:23 UTC
Labels: needs-repro
