### ISSUE TITLE
[OpenImageIO] Upgrade to 2.3.8.0

### ISSUE THREAD

**Issue by HWiman-ICONIC** [microsoft/vcpkg#20858] opened 2021-10-20 07:19 UTC
There is a [new release ](https://github.com/OpenImageIO/oiio/releases/tag/v2.3.8.0)available with improved cmake build (and other fixes and features of course): 

> We no longer install a FindOpenImageIO.cmake module. It was incomplete, out
of date, and wholly unnecessary now that we correctly export a config file
OpenImageIOConfig.cmake and friends. #3098

Thanks!

**Comment by JonLiu1993** [comment] 2021-12-31 06:50
Duplicate of #22263

**Closed by JonLiu1993** 2021-12-31 06:50 UTC
Labels: category:port-update
