### ISSUE TITLE
[pcl] Visualization headers are not installed

### ISSUE THREAD

**Issue by JorgeRomeoInfaimon** [microsoft/vcpkg#15130] opened 2020-12-15 09:17 UTC
When pcl libraries are installed, I am trying to compile some samples found in the tutorials, but I cannot compile because the pcl/visualization headers cannot be found.

They do not exist in vcpkg/installed/include directory. Maybe they should be installed and the required components compiled.

**Comment by JackBoosY** [comment] 2020-12-16 09:59
I think if we need to use the feature `visualization`, we should enable the feature vtk first.
Will check later.

**Comment by JackBoosY** [comment] 2020-12-17 02:55
```
-- The following subsystems will not be built:
--   visualization: VTK was not found.
```

**Comment by JackBoosY** [comment] 2020-12-17 05:57
```
CMake Deprecation Warning at F:/vcpkg/installed/x86-windows/share/vtk/vtk-config.cmake:64 (message):
  The new name for the 'vtkChartsCore' component is 'ChartsCore'
Call Stack (most recent call first):
  F:/vcpkg/scripts/buildsystems/vcpkg.cmake:625 (_find_package)
  CMakeLists.txt:394 (find_package)


CMake Deprecation Warning at F:/vcpkg/installed/x86-windows/share/vtk/vtk-config.cmake:64 (message):
  The new name for the 'vtkCommonCore' component is 'CommonCore'
Call Stack (most recent call first):
  F:/vcpkg/scripts/buildsystems/vcpkg.cmake:625 (_find_package)
  CMakeLists.txt:394 (find_package)
...
CMake Warning at F:/vcpkg/scripts/buildsystems/vcpkg.cmake:625 (_find_package):
  Found package configuration file:

    F:/vcpkg/installed/x86-windows/share/vtk/vtk-config.cmake

  but it set VTK_FOUND to FALSE so package "VTK" is considered to be NOT
  FOUND.  Reason given by package:

  Could not find the VTK package with the following required components:
  RenderingContextOpenGL.
```
After searching for this issue from upstream(https://github.com/PointCloudLibrary/pcl/issues/4412), I found that pcl does not support VTK 9.0 in our master branch now.
Waiting for upstream fix this issue(https://github.com/PointCloudLibrary/pcl/pull/4262).

**Comment by VXallset** [comment] 2021-01-13 09:39
Any update pls?

**Comment by JackBoosY** [comment] 2021-01-13 10:09
@VXallset Waiting for [official fix](https://github.com/PointCloudLibrary/pcl/pull/4262).

**Comment by HelliceSaouli** [comment] 2021-02-28 09:23
What should we do can we use some old version ?

**Comment by JackBoosY** [comment] 2021-03-01 02:48
https://github.com/PointCloudLibrary/pcl/pull/4262 was merged, I will handle this issue in the nearly future.

**Comment by JackBoosY** [comment] 2021-03-19 02:47
Since the changes is huge, I think we should wait for the next release of pcl.

**Comment by JorgeRomeoInfaimon** [comment] 2021-03-19 08:13
Understood. Thanks for your hard work!

**Comment by tungts1101** [comment] 2021-06-20 18:29
As missing the visualizer header is quite cumbersome in visualizing data, should you recommend a proper way to install an older version of PCL with vcpkg?

**Comment by JackBoosY** [comment] 2021-06-21 03:04
We should update to 1.11.1.

**Comment by JackBoosY** [comment] 2021-06-22 07:52
Hi guys, since pcl was updated to 1.11.1 in vcpkg, is this issue resolved?

**Comment by HelliceSaouli** [comment] 2021-06-22 16:59
@JackBoosY still the same issue

**Comment by JackBoosY** [comment] 2021-06-23 07:38
The version 1.11.1 doesn't include the changes, waiting for 1.11.2 release.

**Comment by HelliceSaouli** [comment] 2021-07-06 17:49
1.12.0 is out you guys any news here .??

**Comment by JonLiu1993** [comment] 2021-07-07 09:44
@HelliceSaouli ,Currently pcl1.12.0 is released as a pre-release version. Users may have problems when using it. It will be updated after the official version is released according to our policy.

**Comment by raahilsha-z** [comment] 2021-07-07 16:45
PCL just pushed their release a couple hours ago, and I've opened a pull request here with those changes:

https://github.com/microsoft/vcpkg/pull/18855

**Comment by HelliceSaouli** [comment] 2021-07-07 23:30
EPIC, Thank you guys

**Comment by YhQIAO** [comment] 2021-09-22 12:11
Is this issue fixed in 2021.9?

**Comment by JackBoosY** [comment] 2021-09-23 02:45
@YhQIAO See https://github.com/microsoft/vcpkg/pull/18855#issuecomment-922207871.

**Comment by JackBoosY** [comment] 2021-12-01 08:20
I confirmed this feature is still not added, I will open a PR to add it.

**Closed** 2021-12-17 17:07 UTC
Labels: category:port-feature, category:port-bug, category:port-update
