### ISSUE TITLE
[gumbo] Build error

### ISSUE THREAD

**Issue by beached** [microsoft/vcpkg#29307] opened 2023-01-31 01:07 UTC
Package: gumbo[core]:x64-linux -> 0.10.1#5

**Host Environment**

- Host: x64-linux
- Compiler: GNU 12.2.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 9588a0026 2023-01-30 (2 minutes ago)

**To Reproduce**

`vcpkg install gumbo`

**Failure logs**

```
-- Downloading https://github.com/google/gumbo-parser/archive/v0.10.1.tar.gz -> google-gumbo-parser-v0.10.1.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 1000: popen( curl --fail -L https://github.com/google/gumbo-parser/archive/v0.10.1.tar.gz --create-dirs --output /home/dwright/other_ppl/vcpkg/downloads/google-gumb
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after   817927 us
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/google/gumbo-parser/archive/v0.10.1.tar.gz
File: /home/dwright/other_ppl/vcpkg/downloads/google-gumbo-parser-v0.10.1.tar.gz.52832.part
Expected hash: bb1fb55cd07076ab6a9f38dc14db50397dbdca9a04ace4895dfba8b8cbc09038a96e26070c09c75fa929ada2e815affe233c1e2ecd8afe2aba6201647cf277d1
Actual hash: 250653ffc64db4c64aa84ed8114b7f86442e2016af1c2c7a9aeef892b32d81091611691cd61d970d6def3df73924d43c2ad5d796e9b5e029671cac96eb19a33d
[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(956):
[DEBUG] Time in subprocesses: 817927 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 14 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 828.9 ms (828858 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/gumbo/portfile.cmake:3 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)



```

**Additional context**
I manually downloaded the file, that says it has not been updated since 2015 from github and the hash matches the 25... one that is being found by vcpkg, not the expected one that starts with bb...

**Comment by MonicaLiu0311** [comment] 2023-01-31 02:32
Dupe of https://github.com/microsoft/vcpkg/issues/29288.

**Closed by MonicaLiu0311** 2023-01-31 02:32 UTC
Labels: category:port-bug

**Comment by beached** [comment] 2023-01-31 02:35
Thanks, I was just reading about that.  Sorry to bother you.
