### ISSUE TITLE
[protobuf] respect the VCPKG_BUILD_TYPE var

### ISSUE THREAD

**Issue by jonatino** [microsoft/vcpkg#39283] opened 2024-06-14 06:02 UTC
### Is your feature request related to a problem? Please describe.

Right now protobuf doesn't respect the `VCPKG_BUILD_TYPE` variable causing a `x64-windows-dbg`, `x64-windows-rel`, `x64-windows-static-release-rel` when my triplet is set to `x64-windows-static-release` which sets `VCPKG_BUILD_TYPE` to `release`. This causes slow build times needing to build 3 different version and since protobuf is a large repo, a significant amount of disk space is wasted. 

### Proposed solution

Update the `protobuf` vcpkg to properly respect the `VCPKG_BUILD_TYPE` environment variable to avoid useless builds and wasted disk space.

**Comment by jimwang118** [comment] 2024-06-14 06:37
Duplicate of https://github.com/microsoft/vcpkg/issues/39284

**Closed by jimwang118** 2024-06-14 06:37 UTC
Labels: category:port-feature
