### ISSUE TITLE
boost_python debug links to python3 release

### ISSUE THREAD

**Issue by ulrichard** [microsoft/vcpkg#5097] opened 2019-01-08 07:21 UTC
I am in the process of using some more libraries from vcpkg, namely python and boost. Release builds are mostly working, but when launching the debug build, the python environment is not properly initialized. I suspect that it is related to the fact that boost_python36-vc141-mt-gd-x64-1_68.dll (debug) has a dependency on python36.dll (release), and that I didn't find an option to specify "python-debugging=on" in the boost port.
Apparently this issue was fixed once in the past:
https://github.com/Microsoft/vcpkg/pull/1453/commits/d88f53de9c284cfc67ba21707d60a44ba41ede8a

**Comment by ulrichard** [comment] 2019-01-08 15:31
With boost 1.69 from
https://github.com/Microsoft/vcpkg/pull/5059
still boost_python36-vc141-mt-gd-x64-1_69.dll (debug) has a dependency on python36.dll (release)

**Comment by ulrichard** [comment] 2019-01-08 15:49
Maybe there are cases where it is ok to link a release dll from a debug build as long as it has a pure C ABI. But we also link directly to the python lib as found by the cmake built in finder script. This is the debug version of the python lib for debug builds. Now this combination for sure wrecks havoc. So we definitely must be able to instruct boost to link against the debug python lib.

**Comment by perrog** [comment] 2019-01-13 16:34
I have the same problem. But I'm also struggling to understand how link.exe can depend on python36_d.lib when it is nowhere explicitly referenced. 

pyconfig.h properly imports pragma comment ( lib: python36.lib ) indirectly via include boost/python.h. There is one place in vcpkg.targets which adds "$(VcpkgRoot)debug\lib\*.lib" to AdditionalDependencies, probably this make link.exe try all .libs and take the most appropriate one. Have command-line arguments higher precedence than source code pragma commen (lib) in link.exe? Does link.exe really work as expected here? Anyway, giving link.exe a help to find python36.lib solves the problem, and I set this in my local project.
      <AdditionalLibraryDirectories>$(VcpkgRoot)lib;%(AdditionalDependencies)</AdditionalLibraryDirectories>
      <AdditionalDependencies>python36.lib;%(AdditionalDependencies)</AdditionalDependencies>

(I would expect AdditionalLibraryDirectories should be enough, since the source code reference python36.lib, but stating python36.lib again in AdditionalDependencies also required.)

**Comment by xobs** [comment] 2019-08-15 08:42
This might be the cause of issues that I'm seeing when attempting to link against boost-python for x64-windows-static, where the process silently exits with return code `0xc0000409`.

**Comment by Shatur95** [comment] 2020-10-30 15:52
@perrog, yes, this is the root of the issue.
Temporary workaround for target that links with Boost.Python:

```cmake
if(VCPKG_TOOLCHAIN)
    target_link_directories(${PROJECT_NAME} PRIVATE ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/lib;${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET}/debug/lib)
endif()
```

**Comment by frivard-coveo** [comment] 2020-12-16 19:49
I also have the same problem.
My application has a link library to both Python3 and boost-python.
The port Python3  builds python39_d.lib.
But the port boost-python produces `boost_python39-vc142-mt-gd-x64-1_74.dll` which depends on python39.dll (release).
After a full build, the build output directory contains python39_d.dll, because I specified that I link Python3 (this is ok), but my application can't start because it is missing python39.dll, from the transitive dependency on boost-python.

**Comment by PhoebeHui** [comment] 2021-12-27 07:49
This issue should be fixed by https://github.com/microsoft/vcpkg/blob/master/ports/boost-python/b2-options.cmake.

**Comment by PhoebeHui** [comment] 2021-12-29 02:11
The fix doesn't work, it still depends on python310.dll.

![image](https://user-images.githubusercontent.com/20694052/147620807-7ce0cba1-18e6-4bf1-930d-d25ced60fd3d.png)

**Comment by yurybura** [comment] 2021-12-29 11:02
@PhoebeHui Have you defined BOOST_DEBUG_PYTHON before build?

**Comment by PhoebeHui** [comment] 2021-12-29 11:41
@yurybura, thank you! I forget that, after I define BOOST_DEBUG_PYTHON, it links to python3 debug libs.

![image](https://user-images.githubusercontent.com/20694052/147658690-16c6115a-26c4-4a3c-afde-780ce8895595.png)

**Closed by PhoebeHui** 2021-12-29 11:41 UTC
Labels: category:port-bug

**Comment by Bardo91** [comment] 2022-03-31 17:12
> @yurybura, thank you! I forget that, after I define BOOST_DEBUG_PYTHON, it links to python3 debug libs.
> 
> ![image](https://user-images.githubusercontent.com/20694052/147658690-16c6115a-26c4-4a3c-afde-780ce8895595.png)

I am stuck with the same problem. Where did you need to set it exactly? 

I tried in the CMakeLists of my project, in the cached variables of the CMakePresets but neither of them worked. It still asks me for the Release libraries. 

I found this issue https://github.com/microsoft/vcpkg/issues/23374 , and I understood that what I need is to modify boost compilation.
