### ISSUE TITLE
[qt5] build failure

### ISSUE THREAD

**Issue by MoetaYuko** [microsoft/vcpkg#11775] opened 2020-06-04 14:47 UTC
**Host Environment**
- OS: Windows 10 2004
- Compiler: VS2019+MSVC

**To Reproduce**
`./vcpkg install qt5`

**Failure logs** 

```
❯ vcpkg install qt5
Computing installation plan...
The following packages will be built and installed:
  * icu[core]:x64-windows
  * jasper[core]:x64-windows
  * libjpeg-turbo[core]:x64-windows
  * liblzma[core]:x64-windows
  * libwebp[core,nearlossless,simd,unicode]:x64-windows
  * opengl[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * pcre2[core]:x64-windows
    qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols2,svg,tools]:x64-windows
  * qt5-activeqt[core]:x64-windows
  * qt5-base[core]:x64-windows
  * qt5-declarative[core]:x64-windows
  * qt5-imageformats[core]:x64-windows
  * qt5-multimedia[core]:x64-windows
  * qt5-networkauth[core]:x64-windows
  * qt5-quickcontrols2[core]:x64-windows
  * qt5-svg[core]:x64-windows
  * qt5-tools[core]:x64-windows
  * sqlite3[core]:x64-windows
  * tiff[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/22: icu:x64-windows
Building package icu[core]:x64-windows...
-- Using cached D:/tools/vcpkg/downloads/icu4c-67_1-src.tgz
-- Using source at D:/tools/vcpkg/buildtrees/icu/src/c-67_1-src-39ba50b26e
-- Downloading https://www.python.org/ftp/python/3.7.3/python-3.7.3-embed-amd64.zip...
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/tools/vcpkg/downloads/python-3.7.3-embed-amd64.zip
```

**Additional context**

Can be related to https://github.com/microsoft/vcpkg/pull/10767 but my cmake is already the latest 3.17.2.

`python-3.7.3-embed-amd64.zip` probably failed to extract, there's only one `python.exe` in `vcpkg\downloads\tools\python\python-3.7.3-x64` while all its dependencies are missing.

System language: zh_CN
Filesystem hosting vcpkg: exfat

**Comment by dianlujitao** [comment] 2020-06-05 01:42
Same thing happened to another dependency after the workaround:

```
Starting package 1/17: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Downloading http://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/tools/vcpkg/downloads/strawberry-perl-5.30.0.1-32bit.zip
-- Downloading https://www.openssl.org/source/openssl-1.1.1d.tar.gz...
-- Extracting source D:/tools/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Using source at D:/tools/vcpkg/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip...
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/tools/vcpkg/downloads/jom_1_1_3.zip
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: PERL-NOTFOUND Configure enable-static-engine enable-capieng no-ssl2 -utf-8 shared VC-WIN64A --prefix=D:/tools/vcpkg/packages/openssl-windows_x64-windows --openssldir=D:/tools/vcpkg/packages/openssl-windows_x64-windows -FS
    Working Directory: D:/tools/vcpkg/buildtrees/openssl-windows/x64-windows-rel
    Error code: 系统找不到指定的文件。
    See logs for more information:

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:77 (vcpkg_execute_required_process)
  scripts/ports.cmake:76 (include)


Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x64-windows
  Vcpkg version: 2020.02.04-nohash
```

**Comment by JackBoosY** [comment] 2020-06-05 02:18
Hi @dianlujitao, thanks for reporting this issue!
It seems like your network has problem, could you use VPN or SS, or set a proxy?

Thanks.

**Comment by dianlujitao** [comment] 2020-06-05 02:25
Essentially I'm using a proxy and the downloaded packages are not corrupted, I'm able to manually extract them.

This is probably the root cause:

```
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
```

https://github.com/Microsoft/vcpkg/issues/5951 was closed while its corresponding [upstream bug](https://gitlab.kitware.com/cmake/cmake/-/issues/19132) stayed opened.

**Comment by JackBoosY** [comment] 2020-06-05 02:29
This issue should be fixed by update cmake to 3.17.0, can you check if your vcpkg is up to date?

**Comment by dianlujitao** [comment] 2020-06-05 02:33
My vcpkg HEAD is https://github.com/microsoft/vcpkg/commit/3eeeb1b0d346570813f2257238bf3ad4fe5f752d.

```
❯ .\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe --version
cmake version 3.17.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

**Comment by JackBoosY** [comment] 2020-06-05 02:46
That's a bad news, I thought it was fixed.
Okay, please use https://github.com/microsoft/vcpkg/issues/10552#issuecomment-604384846 workaround.

**Comment by dianlujitao** [comment] 2020-06-05 03:05
The workaround doesn't work, the checkbox is not ticked by default. I'm considering converting exfat to ntfs:\

**Comment by nil-is-lin** [comment] 2021-02-03 13:21
> The workaround doesn't work, the checkbox is not ticked by default. I'm considering converting exfat to ntfs:\

Has the problem been solved after replacing exfat with ntfs? I also encountered the same problem, and it did not work after extract manually. I don't know how to deal with it.

**Comment by dianlujitao** [comment] 2021-02-03 14:31
> > The workaround doesn't work, the checkbox is not ticked by default. I'm considering converting exfat to ntfs:\
> 
> @dianlujitao Has the problem been solved after replacing exfat with ntfs? I also encountered the same problem, and it did not work after extract manually. I don't know how to deal with it.

Yes, I've been using NTFS for my TF card since then and no longer encounter such random weird issues.

**Comment by skyleo** [comment] 2022-09-26 00:31
For me python failed because a folder along the path where my vcpkg repository was inside had a space in it's name.

Removing the space fixed it for me.

**Comment by JackBoosY** [comment] 2022-09-27 02:55
> > The workaround doesn't work, the checkbox is not ticked by default. I'm considering converting exfat to ntfs:\
> 
> @dianlujitao Has the problem been solved after replacing exfat with ntfs? I also encountered the same problem, and it did not work after extract manually. I don't know how to deal with it.

exfat is a cmake issue.

**Comment by JonLiu1993** [comment] 2022-12-08 08:07
@MoetaYuko, sorry for reply you so late, Does this issue persist in the latest vcpkg? I can successfully install qt5 locally
````
PS F:\test\vcpkg> ./vcpkg install qt5
Computing installation plan...
The following packages are already installed:
    qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols,quickcontrols2,svg,tools,translations,websockets]:x86-windows -> 5.15.7#1
qt5:x86-windows is already installed
Restored 0 package(s) from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 185 us. Use --debug to see more details.
Total elapsed time: 140.2 ms
````

**Comment by MoetaYuko** [comment] 2022-12-08 08:11
> @MoetaYuko, sorry for reply you so late, Does this issue persist in the latest vcpkg? I can successfully install qt5 locally
> 

Dunno, I no longer build this on exfat so this issue no longer applies to me, as mentioned before:
> Yes, I've been using NTFS for my TF card since then and no longer encounter such random weird issues.

Feel free to close it.

**Closed** 2023-02-15 08:34 UTC
Labels: requires:repro
