### ISSUE TITLE
building qt: qtdeclarative:x64-windows failed with build failure

### ISSUE THREAD

**Issue by breazyyrn** [microsoft/vcpkg#30446] opened 2023-03-26 19:52 UTC
error: building qtdeclarative:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+qtdeclarative
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[qtdeclarative]+Build+error
Include '[qtdeclarative] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: e249dfb52 2023-03-20 (6 days ago)

**Comment by autoantwort** [comment] 2023-03-26 20:04
Please use the autogenerated issue body mentioned in the console.

**Comment by Neumann-A** [comment] 2023-03-26 22:43
Probably same issue as always with qtdeclarative. Build paths are too long. Use `--x-buildtrees-root=<some_short_path>` (in manifest mode passed via `VCPKG_INSTALL_OPTIONS`)

**Comment by Talaqalotaibipmp** [comment] 2023-03-26 22:48
ربما نفس المشكلة كما هو الحال دائما مع qtdeclarative. بناء المسارات طويلة جدا. استخدم (في وضع البيان الذي تم تمريره عبر --x-buildtrees-root=<some_short_path>VCPKG_INSTALL_OPTIONS)

**Comment by LilyWangLL** [comment] 2023-03-27 09:51
Please provide the error log.

**Comment by PhoebeHui** [comment] 2023-03-29 08:55
@breazyyrn @Talaqalotaibipmp, could you please provide the full failure logs?

**Comment by Krzmbrzl** [comment] 2023-04-04 18:44
I also encountered a build error with qtdeclarative and here is the accompanying information:
Package: qtdeclarative[core]:x64-windows -> 6.4.3

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.35.32216.1
-    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: b619a233f 2023-04-03 (26 hours ago)

**To Reproduce**

`vcpkg install qt`

**Failure logs**

```
CMake Warning at scripts/cmake/vcpkg_buildpath_length_warning.cmake:4 (message):
  qtdeclarative's buildsystem uses very long paths and may fail on your
  system.

  We recommend moving vcpkg to a short path such as 'C:\src\vcpkg' or using
  the subst command.
Call Stack (most recent call first):
  ports/qtdeclarative/portfile.cmake:4 (vcpkg_buildpath_length_warning)
  scripts/ports.cmake:147 (include)


-- Using cached qtdeclarative-everywhere-src-6.4.3.tar.xz.
-- Cleaning sources at C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/src/here-src-6-7df1742173.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/ctxuser/Documents/vcpkg/downloads/qtdeclarative-everywhere-src-6.4.3.tar.xz
-- Using source at C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/src/here-src-6-7df1742173.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j21
    Working Directory: C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg
    See logs for more information:
      C:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:337 (vcpkg_cmake_install)
  ports/qtdeclarative/portfile.cmake:25 (qt_install_submodule)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\install-x64-windows-dbg-out.log</summary>

```
[1/2933] cmd.exe /C "cd /D C:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmltyperegistrar && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_autogen C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/qmltyperegistrar/CMakeFiles/qmltyperegistrar_autogen.dir/AutogenInfo.json Debug && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E touch C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/qmltyperegistrar/qmltyperegistrar_autogen/timestamp && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E cmake_transform_depfile Ninja gccdepfile C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/src/here-src-6-7df1742173.clean C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/src/here-src-6-7df1742173.clean/src/qmltyperegistrar C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/qmltyperegistrar C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/qmltyperegistrar/qmltyperegistrar_autogen/deps C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/CMakeFiles/d/4438b079df7781979bcc5ad3ba929aab9d143edc5d3c8ac77e8102abceadbef8.d"
[2/2933] cmd.exe /C "cd /D C:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmlintegration && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E touch C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/qmlintegration/timestamp"
[3/2933] cmd.exe /C "cd /D C:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmlintegration && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -DIN_FILES=C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/qmlintegration/qt_lib_qmlintegration_private.pri;C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/qmlintegration/Debug/qt_lib_qmlintegration_private.cmake -DOUT_FILE=C:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/../share/Qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri -DLIBRARY_PREFIXES= -DLIBRARY_SUFFIXES=.dll;.lib -DLINK_LIBRARY_FLAG=-l -DCONFIGS=Debug "-DIMPLICIT_LINK_DIRECTORIES=C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/ATLMFC/lib/x64;C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/lib/x64;C:/Program Files (x86)/Windows Kits/10/lib/10.0.22000.0/ucrt/x64;C:/Program Files (x86)/Windows Kits/10//lib/10.0.22000.0//um/x64;" -P C:/Users/ctxuser/Documents/vcpkg/installed/x64-windows/share/Qt6/QtGenerateLibPri.cmake"
...
Skipped 5671 lines
...
s2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/cmake_pch.hxx /showIncludes /Fosrc\quickdialogs2\quickdialogs2quickimpl\CMakeFiles\QuickDialogs2QuickImpl.dir\qquickfontdialogimpl.cpp.obj /Fdsrc\quickdialogs2\quickdialogs2quickimpl\CMakeFiles\QuickDialogs2QuickImpl.dir\ /FS -c C:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\quickdialogs2\quickdialogs2quickimpl\qquickfontdialogimpl.cpp
cl : Command line warning D9025 : overriding '/EHs' with '/EHs-'
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
[2837/2933] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\cl.exe   /TP -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_QUICKDIALOGS2QUICKIMPL_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DEPRECATED_WARNINGS_SINCE=0x070000 -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_GUI_LIB -DQT_LEAN_HEADERS=1 -DQT_MOC_COMPAT -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2IMPL_LIB -DQT_QUICKDIALOGS2UTILS_LIB -DQT_QUICKTEMPLATES2_LIB -DQT_QUICK_LIB -DQT_USE_QSTRINGBUILDER -DQuickDialogs2QuickImpl_EXPORTS -DUNICODE -DWIN32 -DWIN64 -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_USE_MATH_DEFINES -D_WIN64 -D_WINDLL -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2quickimpl\QuickDialogs2QuickImpl_autogen\include -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\quickdialogs2\quickdialogs2quickimpl -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2quickimpl -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl\6.4.3\QtQuickDialogs2QuickImpl -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qml -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml\6.4.3\QtQml -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlIntegration -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\qmlintegration -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmlintegration -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quick -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick\6.4.3\QtQuick -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmlmodels -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels\6.4.3\QtQmlModels -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quicktemplates2 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2\6.4.3\QtQuickTemplates2 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickcontrols2impl -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2Impl\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2Impl\6.4.3\QtQuickControls2Impl -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2Impl -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2Utils -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2utils -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2Utils\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2Utils\6.4.3\QtQuickDialogs2Utils -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtCore\6.4.3 -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtCore\6.4.3\QtCore -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtCore -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6 -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\share\Qt6\mkspecs\win32-msvc -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtNetwork -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtGui -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtOpenGL -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtGui\6.4.3 -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtGui\6.4.3\QtGui -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /W3 /EHs-c- /wd4530 /wd4577 -Zc:__cplusplus -permissive- -utf-8 -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:externConstexpr -Zc:wchar_t -bigobj -std:c++17 /YuC:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/quickdialogs2/quickdialogs2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/cmake_pch.hxx /FpC:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/quickdialogs2/quickdialogs2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/./cmake_pch.cxx.pch /FIC:/Users/ctxuser/Documents/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/quickdialogs2/quickdialogs2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/cmake_pch.hxx /showIncludes /Fosrc\quickdialogs2\quickdialogs2quickimpl\CMakeFiles\QuickDialogs2QuickImpl.dir\qquickfolderbreadcrumbbar.cpp.obj /Fdsrc\quickdialogs2\quickdialogs2quickimpl\CMakeFiles\QuickDialogs2QuickImpl.dir\ /FS -c C:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\quickdialogs2\quickdialogs2quickimpl\qquickfolderbreadcrumbbar.cpp
cl : Command line warning D9025 : overriding '/EHs' with '/EHs-'
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
[2838/2933] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\cl.exe   /TP -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DEPRECATED_WARNINGS_SINCE=0x070000 -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_GUI_LIB -DQT_LEAN_HEADERS=1 -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_OPENGL_LIB -DQT_PLUGIN -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2_LIB -DQT_QUICKTEMPLATES2_LIB -DQT_QUICK_LIB -DUNICODE -DWIN32 -DWIN64 -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_WIN64 -Dqtquickcontrols2nativestyleplugin_EXPORTS -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quicknativestyle\qtquickcontrols2nativestyleplugin_autogen\include -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\quicknativestyle -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quicknativestyle -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\quicknativestyle\items -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\quicknativestyle\qstyle -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\quicknativestyle\util -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qml -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml\6.4.3\QtQml -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlIntegration -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\qmlintegration -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmlintegration -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\quicknativestyle\qstyle\windows -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickcontrols2 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2\6.4.3\QtQuickControls2 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quick -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick\6.4.3\QtQuick -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmlmodels -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels\6.4.3\QtQmlModels -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quicktemplates2 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2\6.4.3 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2\6.4.3\QtQuickTemplates2 -IC:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2 -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtCore\6.4.3 -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtCore\6.4.3\QtCore -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtCore -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6 -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\share\Qt6\mkspecs\win32-msvc -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtNetwork -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtGui\6.4.3 -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtGui\6.4.3\QtGui -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtGui -external:IC:\Users\ctxuser\Documents\vcpkg\installed\x64-windows\include\Qt6\QtOpenGL -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /W3 /EHs-c- /wd4530 /wd4577 -Zc:__cplusplus -permissive- -utf-8 -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:externConstexpr -Zc:wchar_t -bigobj -std:c++17 /showIncludes /Fosrc\quicknativestyle\CMakeFiles\qtquickcontrols2nativestyleplugin.dir\items\qquickstyleitemtreeindicator.cpp.obj /Fdsrc\quicknativestyle\CMakeFiles\qtquickcontrols2nativestyleplugin.dir\ /FS -c C:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\src\here-src-6-7df1742173.clean\src\quicknativestyle\items\qquickstyleitemtreeindicator.cpp
cl : Command line warning D9025 : overriding '/EHs' with '/EHs-'
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**
Manually inspecting that output file reveals this line:
```
C:\Users\ctxuser\Documents\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl\6.4.3\QtQuickDialogs2QuickImpl\private/qquickabstractcolorpicker_p.h(1): fatal error C1083: Cannot open include file: '../../../../../../src/here-src-6-7df1742173.clean/src/quickdialogs2/quickdialogs2quickimpl/qquickabstractcolorpicker_p.h': No such file or directory
```
which seems like the underlying error.

Please let me know if you need any additional information.

**Comment by Neumann-A** [comment] 2023-04-04 18:46
again https://github.com/microsoft/vcpkg/issues/30446#issuecomment-1484247259 

`C:/Users/ctxuser/Documents/vcpkg/buildtrees/` is too long

**Comment by breazyyrn** [comment] 2023-04-04 18:57
Sorry for the late response guys! Been very busy this past week. Although, I'm very happy to say that I fixed the problem using GPT-4's help lol. Instead of windows, I just built Bitcoin Core all over again using Ubuntu and I had no troubles at all. Just had a lot of problems in regards to dependencies when trying to build on windows, was a task that took me over a week to navigate but it only took me a day with Ubuntu and everything is running perfectly now. Thank you all for your help!

**Comment by breazyyrn** [comment] 2023-04-04 19:03
If you do have access to ChatGPT plus and GPT-4 option that is provided once subscribed, and you are interested in building, I suggest using this prompt (remember on GPT-4), replace my username and names with yours, and replace the directories to your correct directories, let me know if it works. If you don't have access to GPT-4 try it on regular ChatGPT if it doesn't work I'll happily provide you with what I get when I input the prompt on my computer. Please note that on this prompt I clearly mentioned that I already had the vcpkg, sudo and automake folders since I tried building it before, but don't think you need them with this implementation anyways.

Here's the Prompt I kept: I'm working on building the Bitcoin Repository, I've tried it before but due to some errors I have to start it again, this time I downloaded it into my external storage to be efficient with the storage which I have. My directory now is: D:\Bitcoin   ...here are the build instructions from github, i already have vcpkg since I have worked on it before so I had saved it in a file earlier, I also have automake on the file: Skip to content
Search or jump to…
Pull requests
Issues
Codespaces
Marketplace
Explore
 
@breazyyrn 
bitcoin
/
bitcoin
Public
Fork your own copy of bitcoin/bitcoin
Code
Issues
375
Pull requests
313
Projects
7
Security
Insights
bitcoin/doc/build-windows.md
@suriyaa
suriyaa doc: Correct linked Microsoft URLs
Latest commit f84e445 on Dec 29, 2022
 History
 22 contributors
@fanquake@laanwj@sipsorcery@hebasto@practicalswift@wbarobinson@maitrebitcoin@nvercamm@merland@LucianaMarques@Thoragh@klementtan
102 lines (68 sloc)  4.14 KB

WINDOWS BUILD NOTES
Below are some notes on how to build Bitcoin Core for Windows.

The options known to work for building Bitcoin Core on Windows are:

On Linux, using the Mingw-w64 cross compiler tool chain.
On Windows, using Windows Subsystem for Linux (WSL) and Mingw-w64.
On Windows, using Microsoft Visual Studio. See README.md.
Other options which may work, but which have not been extensively tested are (please contribute instructions):

On Windows, using a POSIX compatibility layer application such as cygwin or msys2.
Installing Windows Subsystem for Linux
Follow the upstream installation instructions, available here.

Cross-compilation for Ubuntu and Windows Subsystem for Linux
The steps below can be performed on Ubuntu or WSL. The depends system will also work on other Linux distributions, however the commands for installing the toolchain will be different.

First, install the general dependencies:

sudo apt update
sudo apt upgrade
sudo apt install build-essential libtool autotools-dev automake pkg-config bsdmainutils curl git
A host toolchain (build-essential) is necessary because some dependency packages need to build host utilities that are used in the build process.

See dependencies.md for a complete overview.

If you want to build the windows installer with make deploy you need NSIS:

sudo apt install nsis
Acquire the source in the usual way:

git clone https://github.com/bitcoin/bitcoin.git
cd bitcoin
Building for 64-bit Windows
The first step is to install the mingw-w64 cross-compilation tool chain:

on modern systems (Ubuntu 21.04 Hirsute Hippo or newer, Debian 11 Bullseye or newer):
sudo apt install g++-mingw-w64-x86-64-posix
on older systems:
sudo apt install g++-mingw-w64-x86-64
Once the toolchain is installed the build steps are common:

Note that for WSL the Bitcoin Core source path MUST be somewhere in the default mount file system, for example /usr/src/bitcoin, AND not under /mnt/d/. If this is not the case the dependency autoconf scripts will fail. This means you cannot use a directory that is located directly on the host Windows file system to perform the build.

Additional WSL Note: WSL support for launching Win32 applications results in Autoconf configure scripts being able to execute Windows Portable Executable files. This can cause unexpected behaviour during the build, such as Win32 error dialogs for missing libraries. The recommended approach is to temporarily disable WSL support for Win32 applications.

Build using:

PATH=$(echo "$PATH" | sed -e 's/:\/mnt.*//g') # strip out problematic Windows %PATH% imported var
sudo bash -c "echo 0 > /proc/sys/fs/binfmt_misc/status" # Disable WSL support for Win32 applications.
cd depends
make HOST=x86_64-w64-mingw32
cd ..
./autogen.sh
CONFIG_SITE=$PWD/depends/x86_64-w64-mingw32/share/config.site ./configure --prefix=/
make # use "-j N" for N parallel jobs
sudo bash -c "echo 1 > /proc/sys/fs/binfmt_misc/status" # Enable WSL support for Win32 applications.
Depends system
For further documentation on the depends system see README.md in the depends directory.

Installation
After building using the Windows subsystem it can be useful to copy the compiled executables to a directory on the Windows drive in the same directory structure as they appear in the release .zip archive. This can be done in the following way. This will install to c:\workspace\bitcoin, for example:

make install DESTDIR=/mnt/c/workspace/bitcoin
You can also create an installer using:

make deploy
Footer
© 2023 GitHub, Inc.
Footer navigation
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About

**Comment by Krzmbrzl** [comment] 2023-04-05 06:02
> C:/Users/ctxuser/Documents/vcpkg/buildtrees/ is too long

@Neumann-A That's odd though, because I (think I) have enabled long paths for my Windows installation, so I assumed this problem shouldn't occur?
Anyway, I am moving my vcpkg root directory now to see if that does indeed fix the issue.

**Comment by Neumann-A** [comment] 2023-04-05 06:21
Long path support means nothing if the tools dont enable it via the manifest and they dont.

**Comment by Krzmbrzl** [comment] 2023-04-05 09:57
Meh. Anyway, thanks for your help - moving vcpkg to `C:\vcpkg` indeed solved the issue :+1:

**Comment by LilyWangLL** [comment] 2023-04-06 06:16
Since this issue has been resolved, I am closing this issue for now. Thanks for everyone's help.

**Closed by LilyWangLL** 2023-04-06 06:16 UTC
Labels: category:question

**Comment by Tanqingshan** [comment] 2023-11-08 02:30
> again [#30446 (comment)](https://github.com/microsoft/vcpkg/issues/30446#issuecomment-1484247259)
> 
> `C:/Users/ctxuser/Documents/vcpkg/buildtrees/` is too long

I used F:/vcpkg, but it still failed. :(
