### ISSUE TITLE
sdl2-image fails to build on 20190314

### ISSUE THREAD

**Issue by Christsnatcher** [Microsoft/vcpkg#5659] opened 2019-03-13 18:35 UTC
Since I pulled today the latest vcpkg build and told it to "upgrade" it failed on the new sdl2-image build, both for x86 and x64.

```
D:\VS2017\Source\Repos\vcpkg>vcpkg install sdl2-image:x64-windows
The following packages will be built and installed:
    sdl2-image[core]:x64-windows
Starting package 1/1: sdl2-image:x64-windows
Building package sdl2-image[core]:x64-windows...
-- Using cached D:/VS2017/Source/Repos/vcpkg/downloads/SDL2_image-2.0.4.zip
-- Using source at D:/VS2017/Source/Repos/vcpkg/buildtrees/sdl2-image/src/2.0.4-b922bec5e4
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: D:/VS2017/Source/Repos/vcpkg/buildtrees/sdl2-image/x64-windows-dbg
    See logs for more information:
      D:\VS2017\Source\Repos\vcpkg\buildtrees\sdl2-image\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/sdl2-image/portfile.cmake:45 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package sdl2-image:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sdl2-image:x64-windows
  Vcpkg version: 2018.11.23-nohash

Additionally, attach any relevant sections from the log files above.

D:\VS2017\Source\Repos\vcpkg>vcpkg install sdl2-image:x64-windows
The following packages will be built and installed:
    sdl2-image[core]:x64-windows
Starting package 1/1: sdl2-image:x64-windows
Building package sdl2-image[core]:x64-windows...
-- Using cached D:/VS2017/Source/Repos/vcpkg/downloads/SDL2_image-2.0.4.zip
-- Using source at D:/VS2017/Source/Repos/vcpkg/buildtrees/sdl2-image/src/2.0.4-b922bec5e4
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No
    Working Directory: D:/VS2017/Source/Repos/vcpkg/buildtrees/sdl2-image/x64-windows-dbg
    See logs for more information:
      D:\VS2017\Source\Repos\vcpkg\buildtrees\sdl2-image\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/sdl2-image/portfile.cmake:44 (vcpkg_install_cmake)
  scripts/ports.cmake:71 (include)
```

[install-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2963054/install-x64-windows-rel-out.log)
[install-x86-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2963055/install-x86-windows-dbg-out.log)
[install-x86-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2963056/install-x86-windows-rel-out.log)
[config-x64-windows-out.log](https://github.com/Microsoft/vcpkg/files/2963057/config-x64-windows-out.log)
[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/2963058/config-x86-windows-out.log)
[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2963059/install-x64-windows-dbg-out.log)

**Comment by vicroms** [comment] 2019-03-13 23:39
Hi @Christsnatcher 


I found the ofending lines:

```
include_directories(${SDL_INCLUDE_DIR})
include_directories(${SDL_INCLUDE_DIR}/SDL2)
```

This makes it so that `sdl2-image` finds `include/SDL.h` installed by `sdl1` instead of `SDL2/SDL.h`, which would be the correct header to include.  The reason for this is that it also looks for `png.h` installed by `libpng` in `/include`

A workaround is to modify the `CMakeLists.txt` inside the `sdl2-image` port, and change the order of `include_directories` like this:

```
include_directories(${SDL_INCLUDE_DIR})
include_directories(${SDL_INCLUDE_DIR}/SDL2)
```

That would make it build.

**Comment by vicroms** [comment] 2019-03-14 00:10
Duplicate of #5474

**Closed by vicroms** 2019-03-14 00:10 UTC
Labels: port bug
