### ISSUE TITLE
[freeimage] build failure due to xz

### ISSUE THREAD

**Issue by dsvensson** [microsoft/vcpkg#38013] opened 2024-04-06 20:56 UTC
### Operating system

Windows

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
Depend on freeimage.
```

### Failure logs

Same as https://github.com/microsoft/vcpkg/issues/38007

### Additional context

Make lzma an optional dependency. Seems to be pulled in via tiff at least.

**Comment by JonLiu1993** [comment] 2024-04-07 07:45
Duplicate of https://github.com/microsoft/vcpkg/issues/37893.

**Comment by dsvensson** [comment] 2024-04-08 22:44
Agreed. It's a bit broken that you can't depend on freeimage without opting into a whole slew of unwanted dependencies.

**Comment by JackBoosY** [comment] 2024-04-10 02:57
Port feature request.

**Comment by dg0yt** [comment] 2024-04-10 05:35
> Port feature request.

Port bug.

**Closed** 2024-04-12 14:59 UTC
Labels: category:port-bug, depends:upstream-changes
