### ISSUE TITLE
Error Installing boost-fiber on macos

### ISSUE THREAD

**Issue by harikrishnan94** [microsoft/vcpkg#5314] opened 2019-02-06 15:27 UTC
`./vcpkg install boost-fiber` output follows.

The following packages will be built and installed:
    boost-fiber[core]:x64-osx
Starting package 1/1: boost-fiber:x64-osx
Building package boost-fiber[core]:x64-osx... 
-- Using cached /Users/xxx/code/vcpkg/downloads/boostorg-fiber-boost-1.69.0.tar.gz
-- Using source at /Users/xxx/code/vcpkg/buildtrees/boost-fiber/src/ost-1.69.0-fdcb31a571
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
-- Building x64-osx-rel
CMake Error at installed/x64-osx/share/boost-build/boost-modular-build.cmake:85 (message):
  No libraries were produced.  This indicates a failure while building the
  boost library.
Call Stack (most recent call first):
  ports/boost-fiber/portfile.cmake:19 (boost_modular_build)
  scripts/ports.cmake:71 (include)

Error: Building package boost-fiber:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-fiber:x64-osx
  Vcpkg version: 2018.11.23-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by PhoebeHui** [comment] 2019-02-19 02:19
I tried install boost-fiber with lastet vcpkg source:
bysdeMBP-6:vcpkg-master bys$ ./vcpkg install boost-fiber
The following packages will be built and installed:
  * boost-algorithm[core]:x64-osx
  * boost-atomic[core]:x64-osx
  * boost-bind[core]:x64-osx
  * boost-chrono[core]:x64-osx
  * boost-container[core]:x64-osx
  * boost-context[core]:x64-osx
  * boost-date-time[core]:x64-osx
  * boost-exception[core]:x64-osx
    boost-fiber[core]:x64-osx
  * boost-filesystem[core]:x64-osx
  * boost-function[core]:x64-osx
  * boost-functional[core]:x64-osx
  * boost-intrusive[core]:x64-osx
  * boost-lambda[core]:x64-osx
  * boost-lexical-cast[core]:x64-osx
  * boost-math[core]:x64-osx
  * boost-numeric-conversion[core]:x64-osx
  * boost-pool[core]:x64-osx
  * boost-range[core]:x64-osx
  * boost-ratio[core]:x64-osx
  * boost-regex[core]:x64-osx
  * boost-system[core]:x64-osx
  * boost-thread[core]:x64-osx
  * boost-type-index[core]:x64-osx
  * boost-unordered[core]:x64-osx
Additional packages (*) will be modified to complete this operation.
Starting package 1/25: boost-regex:x64-osx
Building package boost-regex[core]:x64-osx... 
-- Using cached /Users/bys/Downloads/vcpkg-master/downloads/boostorg-regex-boost-1.69.0.tar.gz
-- Using source at /Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:175 (message):
    Command failed: /Users/bys/Downloads/vcpkg-master/downloads/tools/cmake-3.12.4-osx/cmake-3.12.4-Darwin-x86_64/CMake.app/Contents/bin/cmake;--build;.;--config;Debug;--target;install;--;-v;-j1
    Working Directory: /Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg
    See logs for more information:
      /Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  installed/x64-osx/share/boost-build/boost-modular-build.cmake:82 (vcpkg_install_cmake)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:71 (include)

Error: Building package boost-regex:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-osx
  Vcpkg version: 2018.11.23-unknownhash

 /Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/install-x64-osx-dbg-out.log:
[1/2] cd /Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997/build && /Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/b2 --user-config=/Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg/user-config.jam --stagedir=/Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg/stage --build-dir=/Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg runtime-link=static link=static address-model=64 target-os=darwin toolset=clang -sZLIB_BINARY=z -sZLIB_LIBPATH="/usr/lib/libz.dylib" -sBZIP2_BINARY=bz2d -sBZIP2_LIBPATH="BZIP2_LIBPATH-NOTFOUND" variant=debug --layout=system --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -sZLIB_INCLUDE="/usr/include" -sBZIP2_INCLUDE="/usr/include" -sICU_PATH="ICU_PATH-NOTFOUND" -j1 -sBOOST_ROOT=/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build -sBOOST_BUILD_PATH=/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build --debug-configuration --ignore-site-config --hash -q architecture=x86 threading=multi threadapi=pthread debug-symbols=on
FAILED: CMakeFiles/boost 
cd /Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997/build && /Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/b2 --user-config=/Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg/user-config.jam --stagedir=/Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg/stage --build-dir=/Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg runtime-link=static link=static address-model=64 target-os=darwin toolset=clang -sZLIB_BINARY=z -sZLIB_LIBPATH="/usr/lib/libz.dylib" -sBZIP2_BINARY=bz2d -sBZIP2_LIBPATH="BZIP2_LIBPATH-NOTFOUND" variant=debug --layout=system --with-atomic --with-random --with-date_time --with-filesystem --with-system --with-thread --with-chrono -sZLIB_INCLUDE="/usr/include" -sBZIP2_INCLUDE="/usr/include" -sICU_PATH="ICU_PATH-NOTFOUND" -j1 -sBOOST_ROOT=/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build -sBOOST_BUILD_PATH=/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build --debug-configuration --ignore-site-config --hash -q architecture=x86 threading=multi threadapi=pthread debug-symbols=on
notice: found boost-build.jam at /Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/boost-build.jam
notice: loading Boost.Build from /Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/src/kernel
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    /Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg/user-config.jam
notice: Searching '/Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from '/Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg'.
warning: toolset gcc initialization:
warning: can not find user-provided command '/Volumes/Macintosh' 'HD' '2/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++'
warning: initialized from /Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg/user-config.jam:21
/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/src/tools/gcc.jam:164: in gcc.init from module gcc
error: toolset gcc initialization:
error: provided command '/Volumes/Macintosh' 'HD' '2/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++' not found
error: initialized from /Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg/user-config.jam:21
/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/src/build/toolset.jam:44: in toolset.using from module toolset
/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/src/build/project.jam:1102: in using from module project-rules
/Users/bys/Downloads/vcpkg-master/buildtrees/boost-regex/x64-osx-dbg/user-config.jam:21: in modules.load from module user-config
/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/src/build-system.jam:255: in load-config from module build-system
/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/src/build-system.jam:449: in load-configuration-files from module build-system
/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/src/build-system.jam:607: in load from module build-system
/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/src/kernel/modules.jam:295: in import from module modules
/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/src/kernel/bootstrap.jam:139: in boost-build from module
/Users/bys/Downloads/vcpkg-master/installed/x64-osx/tools/boost-build/boost-build.jam:8: in module scope from module

ninja: build stopped: subcommand failed.

**Comment by yurybura** [comment] 2021-09-22 20:10
@PhoebeHui This issue was fixed in #18529.

**Comment by PhoebeHui** [comment] 2021-09-23 06:52
Thanks for taking a look! I confirmed that the issue has been fixed.

**Closed by PhoebeHui** 2021-09-23 06:52 UTC
Labels: category:port-bug
