### ISSUE TITLE
[python3] Build error

### ISSUE THREAD

**Issue by shinuexx** [microsoft/vcpkg#34508] opened 2023-10-16 08:48 UTC
Package: python3:x64-linux -> 3.11.5

**Host Environment**

- Host: x64-linux

- Compiler: GNU 11.4.0

-    vcpkg-tool version: 2023-09-15-ac02a9f660977426b8ec6392919fbb1d51b10998

    vcpkg-scripts version: 486a4640d 2023-10-13 (2 days ago)

**To Reproduce**

`vcpkg install boost`

**Failure logs**

```

-- Using cached python-cpython-v3.11.5.tar.gz.

-- Cleaning sources at /home/shinuexx/repo/vcpkg/buildtrees/python3/src/v3.11.5-244658b11a.clean. Use --editable to skip cleaning for the packages you specify.

-- Extracting source /home/shinuexx/repo/vcpkg/downloads/python-cpython-v3.11.5.tar.gz

-- Applying patch 0001-only-build-required-projects.patch

-- Applying patch 0003-use-vcpkg-zlib.patch

-- Applying patch 0004-devendor-external-dependencies.patch

-- Applying patch 0005-dont-copy-vcruntime.patch

-- Applying patch 0008-python.pc.patch

-- Applying patch 0010-dont-skip-rpath.patch

-- Applying patch 0012-force-disable-curses.patch

-- Applying patch 0014-fix-get-python-inc-output.patch

-- Applying patch 0015-dont-use-WINDOWS-def.patch

-- Applying patch 0002-static-library.patch

-- Applying patch 0011-gcc-ldflags-fix.patch

-- Using source at /home/shinuexx/repo/vcpkg/buildtrees/python3/src/v3.11.5-244658b11a.clean

-- Getting CMake variables for x64-linux-dbg

-- Getting CMake variables for x64-linux-rel

-- Generating configure for x64-linux

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):

    Command failed: /usr/bin/autoreconf -vfi

    Working Directory: /home/shinuexx/repo/vcpkg/buildtrees/python3/src/v3.11.5-244658b11a.clean/

    Error code: 1

    See logs for more information:

      /home/shinuexx/repo/vcpkg/buildtrees/python3/autoconf-x64-linux-err.log



Call Stack (most recent call first):

  scripts/cmake/vcpkg_configure_make.cmake:635 (vcpkg_execute_required_process)

  ports/python3/portfile.cmake:257 (vcpkg_configure_make)

  scripts/ports.cmake:168 (include)







```

<details><summary>/home/shinuexx/repo/vcpkg/buildtrees/python3/autoconf-x64-linux-err.log</summary>

```

autoreconf: export WARNINGS=

autoreconf: Entering directory '.'

autoreconf: configure.ac: not using Gettext

autoreconf: running: aclocal --force 

autoreconf: configure.ac: tracing

autoreconf: configure.ac: not using Libtool

autoreconf: configure.ac: not using Intltool

autoreconf: configure.ac: not using Gtkdoc

autoreconf: running: /usr/bin/autoconf --force

configure.ac:18: error: possibly undefined macro: AC_MSG_ERROR

      If this token and others are legitimate, please use m4_pattern_allow.

      See the Autoconf documentation.

autoreconf: error: /usr/bin/autoconf failed with exit status: 1

```

</details>

**Comment by MonicaLiu0311** [comment] 2023-10-16 08:53
Duplicate of #33080.

**Closed by MonicaLiu0311** 2023-10-16 08:53 UTC
Labels: category:question
