### ISSUE TITLE
error: building colmap:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Nebuluss** [microsoft/vcpkg#32168] opened 2023-06-22 08:42 UTC
### Operating system

Windows

### Compiler

Visual studio 2022

### Steps to reproduce the behavior

```Shell
(nerfstudio) PS D:\nerfstudio\vcpkg> vcpkg install colmap[cuda]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda]:x64-windows -> 2023-03-12#1
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Laurent\AppData\Local\vcpkg\archives in 145 us. Use --debug to see more details.
Installing 1/1 colmap:x64-windows...
Building colmap[core,cuda]:x64-windows...
-- Using cached colmap-colmap-30da037ce19bdceb6d239c45342fadb221bdabb2.tar.gz.
-- Cleaning sources at D:/Nerfstudio/vcpkg/buildtrees/colmap/src/b221bdabb2-e3968635af.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Nerfstudio/vcpkg/downloads/colmap-colmap-30da037ce19bdceb6d239c45342fadb221bdabb2.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at D:/Nerfstudio/vcpkg/buildtrees/colmap/src/b221bdabb2-e3968635af.clean
-- Found external ninja('1.11.1').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/Nerfstudio/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: D:/Nerfstudio/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      D:\Nerfstudio\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)


error: building colmap:x64-windows failed with: BUILD_FAILED
Elapsed time to handle colmap:x64-windows: 1.1 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[colmap]+Build+error&body=Copy+issue+body+from+D%3A%2FNerfstudio%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

(nerfstudio) PS D:\nerfstudio\vcpkg> vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
(nerfstudio) PS D:\nerfstudio\vcpkg> git pull
Already up to date.
```

### Failure logs

(nerfstudio) PS D:\nerfstudio\vcpkg> vcpkg install colmap[cuda]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda]:x64-windows -> 2023-03-12#1
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Laurent\AppData\Local\vcpkg\archives in 145 us. Use --debug to see more details.
Installing 1/1 colmap:x64-windows...
Building colmap[core,cuda]:x64-windows...
-- Using cached colmap-colmap-30da037ce19bdceb6d239c45342fadb221bdabb2.tar.gz.
-- Cleaning sources at D:/Nerfstudio/vcpkg/buildtrees/colmap/src/b221bdabb2-e3968635af.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Nerfstudio/vcpkg/downloads/colmap-colmap-30da037ce19bdceb6d239c45342fadb221bdabb2.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at D:/Nerfstudio/vcpkg/buildtrees/colmap/src/b221bdabb2-e3968635af.clean
-- Found external ninja('1.11.1').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/Nerfstudio/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j21
    Working Directory: D:/Nerfstudio/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      D:\Nerfstudio\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building colmap:x64-windows failed with: BUILD_FAILED
Elapsed time to handle colmap:x64-windows: 1.1 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[colmap]+Build+error&body=Copy+issue+body+from+D%3A%2FNerfstudio%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

(nerfstudio) PS D:\nerfstudio\vcpkg> vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
(nerfstudio) PS D:\nerfstudio\vcpkg> git pull
Already up to date.

**Comment by Nebuluss** [comment] 2023-06-22 08:50
the log file https://pastebin.com/GXkKce9D

**Comment by MonicaLiu0311** [comment] 2023-06-25 06:50
Duplicate of https://github.com/microsoft/vcpkg/issues/30272

**Closed by MonicaLiu0311** 2023-06-25 06:50 UTC
Labels: category:port-bug
