### ISSUE TITLE
[boost-build] Build error

### ISSUE THREAD

**Issue by acgetchell** [microsoft/vcpkg#26529] opened 2022-08-26 03:00 UTC
**Host Environment**
- OS: macOS 12.5.1
- Compiler: Xcode 13.4.1

**To Reproduce**
`./vcpkg install`

**Failure logs**
```
-- [COMMUNITY] Loading triplet configuration from: /Users/adam/projects/vcpkg/triplets/community/arm64-osx.cmake
-- Downloading https://github.com/boostorg/build/archive/boost-1.80.0.tar.gz -> boostorg-build-boost-1.80.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 26069: popen( curl --fail -L https://github.com/boostorg/build/archive/boost-1.80.0.tar.gz --create-dirs --output /Users/adam/projects/vcpkg/downloads/boostorg-build-boost-1.80.0.tar.gz.26069.part 2>&1)
[DEBUG] 26069: cmd_execute_and_stream_data() returned 0 after   682415 us
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/boostorg/build/archive/boost-1.80.0.tar.gz ]
       File path : [ /Users/adam/projects/vcpkg/downloads/boostorg-build-boost-1.80.0.tar.gz.26069.part ]
   Expected hash : [ 9076732697f9d8f682b5857f6552b537e7745fedfcee3b82083d497a1f58a795ae73c652ab2a04340b9264155738f4eccfe33095bc996169a4e5117e641644fb ]
     Actual hash : [ 11ac21b27c5c656951784734c6642a2d4efa185e074ec48561f2800203b639d4a628fec6d356bb733494889141327a7ac730ce127449bfc7d509d5d213216995 ]


[DEBUG] /Users/runner/work/1/s/src/vcpkg/base/downloads.cpp(766): 
[DEBUG] Time in subprocesses: 695782 us
[DEBUG] Time in parsing JSON: 4 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 550 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 707.3 ms (693064 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-build/portfile.cmake:9 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)


error: building boost-build:arm64-osx failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-build
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[boost-build]+Build+error
Include '[boost-build] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: a9dc9a4b3 2022-08-25 (5 hours ago)

You can also use the prefilled template from /Users/adam/projects/bistellar-flip/vcpkg_installed/vcpkg/issue_body.md.
```
**Additional context**

Uses https://github.com/acgetchell/bistellar-flip/blob/master/vcpkg.json

**Comment by acgetchell** [comment] 2022-08-26 03:03
Perhaps resolved by https://github.com/microsoft/vcpkg/pull/26527?

**Comment by alexbaden** [comment] 2022-08-26 04:22
I am seeing this as well, both with boost 1.80 and with the baseline forced to the commit before 1.80 (23e74ca2c2a31fa6147a32813613159aef31b908).

**Comment by FrankXie05** [comment] 2022-08-26 05:54
Duplicate of #26525  @acgetchell We will deal with this issue as soon as possible. :)

**Closed by FrankXie05** 2022-08-26 05:54 UTC

**Comment by acgetchell** [comment] 2022-08-26 20:35
Fixed via https://github.com/microsoft/vcpkg/pull/26527
