### ISSUE TITLE
[glm] build failure

### ISSUE THREAD

**Issue by hktonylee** [microsoft/vcpkg#29289] opened 2023-01-30 19:49 UTC
**Host Environment**

- OS: Ubuntu 20.04
- Compiler: N/A

**To Reproduce**

`./vcpkg install glm`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

```
Computing installation plan...
The following packages will be built and installed:
    glm[core]:x64-linux -> 0.9.9.8#1
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from /home/SomeUser/.cache/vcpkg/archives in 3.334 us. Use --debug to see more details.
Starting package 1/1: glm:x64-linux
Building package glm[core]:x64-linux...
-- Downloading https://github.com/g-truc/glm/archive/bf71a834948186f4097caa076cd2663c69a10e1e.tar.gz -> g-truc-glm-bf71a834948186f4097caa076cd2663c69a10e1e.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 475380: popen(curl --fail -L https://github.com/g-truc/glm/archive/bf71a834948186f4097caa076cd2663c69a10e1e.tar.gz --create-dirs --output /home/SomeUser/vcpkg/downloads/g-truc-glm-bf71a834948186f4097caa076cd2663c69a10e1e.tar.gz.475380.part 2>&1)
[DEBUG] 475380: cmd_execute_and_stream_data() returned 0 after  1965095 us
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/g-truc/glm/archive/bf71a834948186f4097caa076cd2663c69a10e1e.tar.gz ]
       File path : [ /home/SomeUser/vcpkg/downloads/g-truc-glm-bf71a834948186f4097caa076cd2663c69a10e1e.tar.gz.475380.part ]
   Expected hash : [ 226266c02af616a96fb19ee32cf3f98347daa43a4fde5d618d36b38709dce1280de126c542524d40725ecf70359edcc5b60660554c65ce246514501fb4c9c87c ]
     Actual hash : [ 65e0fa6056f2996687740e593a583d372c482ad59b160598903d8f53a2d99b2c1d72e0503cf3200d28d78e0223133cfb22394aafd494dfd92974d99042f39021 ]


[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(741):
[DEBUG] Time in subprocesses: 1965095 us
[DEBUG] Time in parsing JSON: 1 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 0 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 1.983 s (1982818 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:84 (message):

      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. Your proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:309 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:182 (vcpkg_download_distfile)
  ports/glm/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:145 (include)


error: building glm:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glm
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glm]+Build+error
including:
  package: glm[core]:x64-linux -> 0.9.9.8#1
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: 5e95befcd 2023-01-26 (4 days ago)

Additionally, attach any relevant sections from the log files above.
```

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by BillyONeal** [comment] 2023-01-30 20:55
Dupe of https://github.com/microsoft/vcpkg/issues/29288

**Closed by BillyONeal** 2023-01-30 20:55 UTC
Labels: category:port-bug
