### ISSUE TITLE
[pybind11] Python version selection does not work

### ISSUE THREAD

**Issue by rib2bit** [microsoft/vcpkg#23796] opened 2022-03-27 01:08 UTC
**Describe the bug**

Pybind11' s Python version selection variable `PYTHON_EXECUTABLE` does not work correctly after fad0644ade71fc4a77cc85f9c6c265aac721f7ca.

**Environment**

- OS: Ubuntu 20.04
- Compiler: clang++

**To Reproduce**

1. ./vcpkg install pybind11
2. CMake project with Pybind11 for example from [cmake_example](https://github.com/pybind/cmake_example):  
    `CMakeLists.txt`
    ```cmake
    cmake_minimum_required(VERSION 3.4...3.18)
    project(cmake_example)

    find_package(pybind11 CONFIG REQUIRED)
    pybind11_add_module(cmake_example main.cpp)

    # EXAMPLE_VERSION_INFO is defined by setup.py and passed into the C++ code as a
    # define (VERSION_INFO) here.
    target_compile_definitions(cmake_example
                            PRIVATE VERSION_INFO=${EXAMPLE_VERSION_INFO})
    ```  
    [`main.cpp`](https://github.com/pybind/cmake_example/blob/master/src/main.cpp)
3.  CMake build with the system installed Python:  
    ```bash
    $ cmake -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -S . -B build
    -- The C compiler identification is Clang 12.0.1
    -- The CXX compiler identification is Clang 12.0.1
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Check for working C compiler: /usr/bin/clang-12 - skipped
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Check for working CXX compiler: /usr/bin/clang++-12 - skipped
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- Found PythonLibs: /vcpkg/installed/x64-linux/lib/libpython3.10.a (found version "3.10.2") 
    -- Performing Test HAS_FLTO
    -- Performing Test HAS_FLTO - Success
    -- Performing Test HAS_FLTO_THIN
    -- Performing Test HAS_FLTO_THIN - Success
    -- Found pybind11: /vcpkg/installed/x64-linux/include (found version "2.9.1")
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /workspaces/pybind11test/build
    ```
4.  `Found PythonLIbs` `libpython3.10.a` does not correspond to the specified Python executable version:
    ```bash
    $ /usr/bin/python3 --version
    Python 3.8.10
    ```

**Expected behavior**

This may be caused from the vcpkg's [replacement](https://github.com/microsoft/vcpkg/commit/fad0644ade71fc4a77cc85f9c6c265aac721f7ca#diff-808ad9071e07e79b93c9246bcb8e2897e44385cf18ffe3dea235dcea5a9d7a51) from `find_package PythonLibsNew` to `find_package PythonLibs`.

After manually undoing this change, `PythonLibs` is detected correctly in CMake builds.

```bash
$ cmake -DCMAKE_TOOLCHAIN_FILE=/vcpkg/scripts/buildsystems/vcpkg.cmake -G Ninja -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3 -S . -B build
-- The C compiler identification is Clang 12.0.1
-- The CXX compiler identification is Clang 12.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-12 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++-12 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.8.so
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- Performing Test HAS_FLTO_THIN
-- Performing Test HAS_FLTO_THIN - Success
-- Found pybind11: /vcpkg/installed/x64-linux/include (found version "2.9.1")
-- Configuring done
-- Generating done
-- Build files have been written to: /workspaces/pybind11test/build
```

**Comment by Hoikas** [comment] 2022-03-27 03:08
The pybind11 port uses the python3 install from vcpkg, not your system python. Therefore, the behavior you are experiencing is the intended behavior.

**Comment by rib2bit** [comment] 2022-03-27 04:27
@Hoikas Thank you for your response.  
Is it also intended that the Python version is ignored even if the port's user set it expricitly? I think this would mean pybind11 port cannot build the modules for Python version older than vcpkg's libpython (currently < 3.10).

**Comment by Adela0814** [comment] 2022-05-11 08:52
Close this issue because it's expected.

**Closed by Adela0814** 2022-05-11 08:52 UTC
Labels: category:question
