### ISSUE TITLE
[rapidjson] Build error

### ISSUE THREAD

**Issue by dicarne** [microsoft/vcpkg#25519] opened 2022-07-01 09:30 UTC
**Host Environment**
- OS: Ubuntu 22.04LTS
- Compiler: `vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e`

**To Reproduce**
`./vcpkg install rapidjson:x64-linux`

**Failure logs**
```
Computing installation plan...
The following packages will be built and installed:
    rapidjson[core]:x64-linux -> 2022-06-28
Detecting compiler hash for triplet "x64-linux"...
Restored 0 packages from /home/dicarne/.cache/vcpkg/archives in 5.4 us. Use --debug to see more details.
Installing 1/1 rapidjson:x64-linux...
Building rapidjson[core]:x64-linux...
-- Downloading https://github.com/Tencent/rapidjson/archive/232389d4f1012dddec4ef84861face2d2ba85709.tar.gz -> Tencent-rapidjson-232389d4f1012dddec4ef84861face2d2ba85709.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 1829853: popen(curl --fail -L https://github.com/Tencent/rapidjson/archive/232389d4f1012dddec4ef84861face2d2ba85709.tar.gz --create-dirs --output /home/dicarne/GitHub/vcpkg/downloads/Tencent-rapidjson-232389d4f1012dddec4ef84861face2d2ba85709.tar.gz.1829853.part 2>&1)
[DEBUG] 1829853: cmd_execute_and_stream_data() returned 0 after  1930421 us
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/Tencent/rapidjson/archive/232389d4f1012dddec4ef84861face2d2ba85709.tar.gz ]
       File path : [ /home/dicarne/GitHub/vcpkg/downloads/Tencent-rapidjson-232389d4f1012dddec4ef84861face2d2ba85709.tar.gz.1829853.part ]
   Expected hash : [ 60bfbfe4884122aa9ae8755531da18ce4a793bb217c06474dd8c5afe0f2f5df280c40be2f303c1740f5af14c7ad5cc2a57f08de5205cc7ab27d6166b0f49130d ]
     Actual hash : [ 0d7d751179abdaa6ebf6167d522651a2d13bc024d20c7e3f775c7397a8aab4cd866a6c91a55521ad7847e910822fcf982625c7308c74f5df663e6fd81336c9fc ]
```

**Additional context**
no proxy. Looks like a hash error. Attempts have failed multiple times.

**Comment by JonLiu1993** [comment] 2022-07-01 09:34
Duplicate of https://github.com/microsoft/vcpkg/issues/25508, will be fixed in https://github.com/microsoft/vcpkg/pull/25509

**Closed** 2022-07-01 09:34 UTC
