### ISSUE TITLE
[intel-mkl] support for Intel OpenAPI

### ISSUE THREAD

**Issue by MaxC2** [microsoft/vcpkg#15910] opened 2021-01-27 11:51 UTC
**Is your feature request related to a problem? Please describe.**
Not really a feature but an update of the build configuration that allow to find MKL in the new (OpenAPI) default path

**Proposed solution**
Currently, the MKL library is not installed but detected. The detection is, for my own case (windows OS), based on a common path : 

`C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\mkl`

That is know as environment variable `MKLROOT`

Since the Intel MKL come with the Intel OpenAPI bundle installer, the new `MKLROOT` become (always for windows OS):

`C:\Program Files (x86)\Intel\oneAPI\mkl\latest`

Where `latest` is a shortcut to the lastest installed version, here for me:

`C:\Program Files (x86)\Intel\oneAPI\mkl\2021.1.1`

The subsequent directory structure is similar to the oldest `IntelSWTools` directory.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Neumann-A** [comment] 2021-01-27 22:28
Duplicate of #15548

**Closed** 2021-01-28 02:31 UTC
Labels: category:port-feature
