### ISSUE TITLE
Error while installing OpenNI2 (chacked on two PCs)

### ISSUE THREAD

**Issue by MrCairo90** [Microsoft/vcpkg#4092] opened 2018-08-15 16:40 UTC
Hello,
I'm trying to install, but there is an error in file scripts/cmake/vcpkg_execute_required_process.cmake:56, err msg:

 Command failed: msbuild;C:/vcpkg/buildtrees/openni2/x64-windows/2.2-beta2-a8c7829707/OpenNI.sln;/p:Configuration=Release;/t:Rebuild;/p:Platform=x64;/p:PlatformToolset=v141;/p:VCPkgLocalAppDataDisabled=true;/p:UseIntelMKL=No;/p:WindowsTargetPlatformVersion=10.0.17134.0;/m
    Working Directory: C:/vcpkg/buildtrees/openni2/x64-windows-rel
    See logs for more information:
      C:\vcpkg\buildtrees\openni2\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_msbuild.cmake:119 (vcpkg_execute_required_process)
  ports/openni2/portfile.cmake:46 (vcpkg_build_msbuild)
  scripts/ports.cmake:71 (include)

Error: Building package openni2:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openni2:x64-windows
  Vcpkg version: 0.0.113-nohash

I know that similar issue was solved here #1937 but solution didn't help me. 
- Victor

**Comment by Voskrese** [comment] 2018-08-15 18:50
> See logs for more information:
> C:\vcpkg\buildtrees\openni2\build-x64-windows-rel-out.log

**Comment by MrCairo90** [comment] 2018-08-15 18:56
[build-x64-windows-rel-out.log](https://github.com/Microsoft/vcpkg/files/2291338/build-x64-windows-rel-out.log)
looks like there is a problem with NuiApi.h

**Comment by Voskrese** [comment] 2018-08-15 19:19
`'NuiApi.h': No such file or directory`
https://github.com/Microsoft/vcpkg/issues/1927#issuecomment-334685776

**Comment by MrCairo90** [comment] 2018-08-15 20:06
I followed instructions and i have the same issue.
after changing file replace_environment_variable.patch and deleting  folder C:\vcpkg\buildtrees\openni2 there is problem with 
Applying patch C:/vcpkg/ports/openni2/replace_environment_variable.patch
Applying patch failed. This is expected if this patch was previously applied.

All other patchs were applied correcty.

**Comment by NancyLi1013** [comment] 2019-03-04 07:00
Thanks for posting this issue. And I cannot reproduce it on the latest vcpkg. So close it first.
Please open a new issue if this is still a problem for you.

**Closed by NancyLi1013** 2019-03-04 07:00 UTC
Labels: needs-repro
