### ISSUE TITLE
[tensorflow-cc 2.10.0] build failure

### ISSUE THREAD

**Issue by over-shine** [microsoft/vcpkg#27474] opened 2022-10-26 13:52 UTC
**Host Environment**

- OS: windows11
- Compiler: VS2019

**To Reproduce**

`./vcpkg install tensorflow-cc:x64-windows`
version: 2.10.0
**Failure logs**

![image](https://user-images.githubusercontent.com/30746603/198044044-6d79c6bc-1fbf-4ff7-ac69-04cb3ed9e1e2.png)

config-x64-windows-dbg-out.log: Cannot find bazel. Please install bazel/bazelisk.

**Comment by calebtt** [comment] 2022-10-30 10:35
also experiencing this issue
OS: Windows 11
Compiler: VS2022

To Repro:
./vcpkg install tensorflow:x64-windows

**Comment by TimBate** [comment] 2022-11-01 22:37
also experiencing this issue (technically mine is [tensorflow] Build error)
OS: Windows 10
Compiler: VS2022

vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
vcpkg-scripts version: fcfda3c78 2022-10-31 (22 hours ago)

**Comment by Adela0814** [comment] 2022-11-15 10:31
@JackyYin Do you have any suggestion for this problem?

**Comment by JackyYin** [comment] 2022-11-15 10:48
Hello @over-shine,
Could you please also provide the log in `D:\vcpkg\buildtrees\tensorflow-cc\config-x64-windows-dbg-out.log` ?

**Comment by Adela0814** [comment] 2022-11-16 02:52
This is all the content in the config-x64-windows-dbg-out.log：
`Cannot find bazel. Please install bazel/bazelisk.`

**Comment by JackyYin** [comment] 2022-11-16 08:37
Hi @Adela0814,

Could you try again with this approach?

https://github.com/microsoft/vcpkg/issues/27252#issuecomment-1316170566

**Comment by Adela0814** [comment] 2022-11-16 09:16
I cannot get the version of `bazel`, there should be an issue with the installation of `vcpkg tool bazel`
![image](https://user-images.githubusercontent.com/95600143/202138735-ada5c264-0a4c-4b85-9164-9f321406e185.png)

`bazel` in my local(`installed/x64-windows/tools`):
![image](https://user-images.githubusercontent.com/95600143/202138368-9542c8b2-1a7a-4b2e-b217-75d22a1e8d6a.png)

**Comment by JackyYin** [comment] 2022-11-16 16:19
@Adela0814 ,

Seems like it's because of the filename is renamed to `bazel` instead of `bazel.exe`.

Could you try again with this branch?
https://github.com/JackyYin/vcpkg/tree/tensorflow-2.10.0-windows-build

**Comment by Adela0814** [comment] 2022-11-17 02:46
I got a new error using this branch,
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: E:/ten/vcpkg/downloads/tools/msys2/70289b324bc026d6/usr/bin/bash.exe --noprofile --norc -c "E:/ten/vcpkg/installed/x64-windows/tools/bazel.exe --output_user_root='E:/ten/vcpkg/buildtrees/tensorflow-cc/.bzl' --max_idle_secs=1 build -s --verbose_failures --jobs=9 --compilation_mode=dbg --features=fastbuild --features=fully_static_link    --python_path='E:/ten/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow_cc.dll ///tensorflow:install_headers"
    Working Directory: E:/ten/vcpkg/buildtrees/tensorflow-cc/x64-windows-dbg
    See logs for more information:
      E:\ten\vcpkg\buildtrees\tensorflow-cc\build-x64-windows-dbg-err.log
```
[build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/10027297/build-x64-windows-dbg-err.log)

**Comment by JackyYin** [comment] 2022-11-17 05:29
@Adela0814,

Seems like we need to add `list(JOIN BUILD_OPTS " " BUILD_OPTS)` for windows to correctly parse the bazel command.

Could you re-pull my branch and try again?

**Comment by Adela0814** [comment] 2022-11-17 05:56
> @Adela0814,
> 
> Seems like we need to add `list(JOIN BUILD_OPTS " " BUILD_OPTS)` for windows to correctly parse the bazel command.
> 
> Could you re-pull my branch and try again?

The same error.

**Comment by dg0yt** [comment] 2022-11-17 06:19
> Seems like we need to add `list(JOIN BUILD_OPTS " " BUILD_OPTS)` for windows to correctly parse the bazel command.

It makes sence to collect options in a list (with `vcpkg_list`) and to do post-processing for forming a command line. (As done in `vcpkg_configure_make`.) But it is not as simple as `list(JOIN ..)` but must properly deal with quoting items which (may) contain space or quotes. 
The current code already is inconsistent in collecting options.  I see two parameter added as one item, including space.

> I got a new error using this branch,
> ...
> [build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/10027297/build-x64-windows-dbg-err.log)

This log contains:
~~~
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false
ERROR: --experimental_link_static_libraries_once=false :: Unrecognized option: --experimental_link_static_libraries_once=false
/usr/bin/bash: line 1: 9: command not found
/usr/bin/bash: line 1: --compilation_mode=dbg: command not found
~~~
The bash script or command line should be checked for special characters (`;`, line break).

**Comment by over-shine** [comment] 2022-11-17 13:35
> Hello @over-shine, Could you please also provide the log in `D:\vcpkg\buildtrees\tensorflow-cc\config-x64-windows-dbg-out.log` ?

Cannot find bazel. Please install bazel/bazelisk.

**Comment by JackyYin** [comment] 2022-11-18 06:44
> > @Adela0814,
> > Seems like we need to add `list(JOIN BUILD_OPTS " " BUILD_OPTS)` for windows to correctly parse the bazel command.
> > Could you re-pull my branch and try again?
> 
> The same error.

Did you remove `buildtrees`, `installed` and `packages` directories before re-install tensorflow?

I saw a different result after checkout to my git branch.
Environment:
- OS: win11
- compiler: VS2022

**Comment by calebtt** [comment] 2022-11-21 04:58
So what are we to take from this? Tensorflow just doesn't work with vcpkg ? It still doesn't work, even though bazel is obviously on the PATH available to all users and using -release doesn't work either.

**Comment by esohns** [comment] 2022-12-17 17:46
Same issue
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/10252300/config-x64-windows-dbg-out.log)

**Comment by ssiamantas** [comment] 2022-12-20 11:42
I had the same issue. I had `bazel` installed under `vcpkg\installed\x64-windows\tools`, but the file didn't have the .exe extension, so I renamed the file to `bazel.exe`. 

Afterwards, I ran `./vcpkg install tensorflow:x64-windows` (I know OP was installing tensorflow-cc, but I guess it should be the root cause for both cases), and got another error.

```
-- Configuring TensorFlow (dbg)
-- Warning: Building TensorFlow can take an hour or more.
-- Build Tensorflow with concurrent level: 9
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: F:/vcpkg/downloads/tools/msys2/70289b324bc026d6/usr/bin/bash.exe --noprofile --norc -c "'F:/vcpkg/installed/x64-windows/tools/bazel.exe' --output_user_root='F:/vcpkg/buildtrees/tensorflow/.bzl' --max_idle_secs=1 build --verbose_failures --jobs 9 --compilation_mode=dbg --features=fastbuild    --python_path='F:/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers"
    Working Directory: F:/vcpkg/buildtrees/tensorflow/x64-windows-dbg
    See logs for more information:
      F:\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:281 (vcpkg_execute_build_process)
  ports/tensorflow/portfile.cmake:5 (include)
  scripts/ports.cmake:147 (include)
```

and the output of `build-x64-windows-dbg-err.log` was:

```
Extracting Bazel installation...
Starting local Bazel server and connecting to it...
ERROR: Expected value after --jobs
/usr/bin/bash: line 1: 9: command not found
/usr/bin/bash: line 1: --compilation_mode=dbg: command not found
```

Note that `vcpkg-tool-bazel` installed the 5.2.0 version of bazel, while tensorflow was searching for 5.1.1 (I checked that in `vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelversion`). So, I downloaded 5.1.1 from [here]. (https://github.com/bazelbuild/bazel/releases?q=5.1.1&expanded=true) 

Then, I ran `./vcpkg install tensorflow:x64-windows` again, only to get the same error.

Hope this helps further to the debugging process. Will keep you posted.

**Comment by ssiamantas** [comment] 2022-12-20 12:27
UPDATE

After changing `set(BUILD_OPTS --jobs ${VCPKG_CONCURRENCY})` to `set(BUILD_OPTS --jobs=${VCPKG_CONCURRENCY})`, I was able to proceed a little bit, only to stop at another error. See below:

```
-- Configuring TensorFlow (dbg)
-- Warning: Building TensorFlow can take an hour or more.
-- Build Tensorflow with concurrent level: 9
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: F:/vcpkg/downloads/tools/msys2/70289b324bc026d6/usr/bin/bash.exe --noprofile --norc -c "'F:/vcpkg/installed/x64-windows/tools/bazel.exe' --output_user_root='F:/vcpkg/buildtrees/tensorflow/.bzl' --max_idle_secs=1 build --verbose_failures --jobs=9 --compilation_mode=dbg --features=fastbuild    --python_path='F:/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers"
    Working Directory: F:/vcpkg/buildtrees/tensorflow/x64-windows-dbg
    See logs for more information:
      F:\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:281 (vcpkg_execute_build_process)
  ports/tensorflow/portfile.cmake:5 (include)
  scripts/ports.cmake:147 (include)
```

and the output of build-x64-windows-dbg-err.log was:

```
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from f:\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=F:/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python.exe
INFO: Reading rc options for 'build' from f:\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  'build' options: --define framework_shared_object=true --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true --experimental_cc_shared_library --experimental_link_static_libraries_once=false
INFO: Reading rc options for 'build' from f:\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=F:/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python3.exe --action_env PYTHON_LIB_PATH=F:/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/lib/python3.8/site-packages --python_path=F:/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python3.exe --define=with_xla_support=false --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Reading rc options for 'build' from f:\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/ir,tensorflow/compiler/mlir/tfrt/tests/analysis,tensorflow/compiler/mlir/tfrt/tests/jit,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_tfrt,tensorflow/compiler/mlir/tfrt/tests/lhlo_to_jitrt,tensorflow/compiler/mlir/tfrt/tests/tf_to_corert,tensorflow/compiler/mlir/tfrt/tests/tf_to_tfrt_data,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/graph_executor,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file f:\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file f:\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file f:\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --copt=/W0 --host_copt=/W0 --copt=/Zc:__cplusplus --host_copt=/Zc:__cplusplus --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --features=compiler_param_file --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --cxxopt=/std:c++17 --host_cxxopt=/std:c++17 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file f:\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --define framework_shared_object=false --experimental_link_static_libraries_once=false
WARNING: Usage: bazel build <options> <targets>.
Invoke `bazel help build` for full description of usage and options.
Your request is correct, but requested an empty set of targets. Nothing will be built.
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/tensorflow/runtime/archive/6ca793b5d862ef6c50f242d77a811f06cce9b60a.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
WARNING: Download from https://storage.googleapis.com/mirror.tensorflow.org/github.com/llvm/llvm-project/archive/0538e5431afdb1fa05bdcedf70ee502ccfcd112a.tar.gz failed: class java.io.FileNotFoundException GET returned 404 Not Found
Analyzing: 0 targets (0 packages loaded, 0 targets configured)
INFO: Analyzed 0 targets (0 packages loaded, 0 targets configured).
INFO: Found 0 targets...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
INFO: Elapsed time: 168.424s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
/usr/bin/bash: line 1: --compilation_mode=dbg: command not found
```

**Comment by kilasuelika** [comment] 2023-02-17 11:20
> 

I have exactly the same problem with you.

**Comment by kilasuelika** [comment] 2023-02-17 11:20
> I had the same issue. I had `bazel` installed under `vcpkg\installed\x64-windows\tools`, but the file didn't have the .exe extension, so I renamed the file to `bazel.exe`.
> 
> Afterwards, I ran `./vcpkg install tensorflow:x64-windows` (I know OP was installing tensorflow-cc, but I guess it should be the root cause for both cases), and got another error.
> 
> ```
> -- Configuring TensorFlow (dbg)
> -- Warning: Building TensorFlow can take an hour or more.
> -- Build Tensorflow with concurrent level: 9
> CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
>     Command failed: F:/vcpkg/downloads/tools/msys2/70289b324bc026d6/usr/bin/bash.exe --noprofile --norc -c "'F:/vcpkg/installed/x64-windows/tools/bazel.exe' --output_user_root='F:/vcpkg/buildtrees/tensorflow/.bzl' --max_idle_secs=1 build --verbose_failures --jobs 9 --compilation_mode=dbg --features=fastbuild    --python_path='F:/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers"
>     Working Directory: F:/vcpkg/buildtrees/tensorflow/x64-windows-dbg
>     See logs for more information:
>       F:\vcpkg\buildtrees\tensorflow\build-x64-windows-dbg-err.log
> 
> Call Stack (most recent call first):
>   installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:281 (vcpkg_execute_build_process)
>   ports/tensorflow/portfile.cmake:5 (include)
>   scripts/ports.cmake:147 (include)
> ```
> 
> and the output of `build-x64-windows-dbg-err.log` was:
> 
> ```
> Extracting Bazel installation...
> Starting local Bazel server and connecting to it...
> ERROR: Expected value after --jobs
> /usr/bin/bash: line 1: 9: command not found
> /usr/bin/bash: line 1: --compilation_mode=dbg: command not found
> ```
> 
> Note that `vcpkg-tool-bazel` installed the 5.2.0 version of bazel, while tensorflow was searching for 5.1.1 (I checked that in `vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelversion`). So, I downloaded 5.1.1 from [here]. (https://github.com/bazelbuild/bazel/releases?q=5.1.1&expanded=true)
> 
> Then, I ran `./vcpkg install tensorflow:x64-windows` again, only to get the same error.
> 
> Hope this helps further to the debugging process. Will keep you posted.

I have exactly the same problem.

**Comment by EsMgAl** [comment] 2023-04-04 06:59
I have exactly the same problem and I have tried everything. But can not solve this issue!

**Comment by Adela0814** [comment] 2023-04-17 07:32
This is a conflict issue between bazel and vs2022, could you try this solution ?
https://github.com/bazelbuild/bazel/issues/14232#issuecomment-1007946021.
Close this issue because it is not a vcpkg issue. hope your issue can be resolved.

**Closed by Adela0814** 2023-04-17 07:32 UTC
Labels: category:port-bug
