### ISSUE TITLE
[glib] “glibconfig.h”: No such file or directory

### ISSUE THREAD

**Issue by UnknownObject000** [microsoft/vcpkg#32239] opened 2023-06-26 12:17 UTC
**Describe the bug**
Error C1083: “glibconfig.h”: No such file or directory when compile.

**Environment**
- OS: Windows 11 Professional Workstation
- Compiler: Visual Studio 2022 (MSVC17)

**To Reproduce**
Compile such code:
```c++
#include <gst/gst.h>
#include <gst/app/gstappsink.h>

int main()
{
	return 0;
}
```

**Expected behavior**
Successfully compiled.

**Failure logs**
已启动生成...
1>------ 已启动生成: 项目: Picture2MP4, 配置: Release x64 ------
1>Picture2MP4.cpp
1>F:\vcpkg\installed\x64-windows\include\glib-2.0\glib\gtypes.h(34,10): fatal  error C1083: 无法打开包括文件: “glibconfig.h”: No such file or directory
1>已完成生成项目“Picture2MP4.vcxproj”的操作 - 失败。
========== 版本: 0 成功，1 失败，0 更新，0 跳过 ==========
========== 占用时间 00:00.531 ==========

**Additional context**
I have searched the vcpkg install directory and can't find any file named “glibconfig.h”, both the ```x64-windows/include``` and ```x86-windows/include``` directories are the same.

**Comment by SchaichAlonso** [comment] 2023-06-26 14:50
glib installs some headers into `lib/glib-2.0/include` on top of `include`.
If you're using cmake I'd recommend to use [KDE's find script for glib2](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/find-modules/FindGLIB2.cmake).

**Comment by MonicaLiu0311** [comment] 2023-06-27 07:31
> ```c++
> #include <gst/gst.h>
> #include <gst/app/gstappsink.h>
> 
> int main()
> {
> 	return 0;
> }
> ```

I guess you should have made a mistake, `gst/gst.h` is the header file of `gstreamer`.

**Comment by MonicaLiu0311** [comment] 2023-06-27 07:33
When using `glib`, this error is reproduced, because `glibconfig.h` is installed in the `lib/glib-2.0/include/` directory, and the correct installation location should be `include/glib-2.0/`.

```
PS E:\vcpkg01> ./vcpkg version
vcpkg package management program version 2023-06-15-8c254a5fb6c503615834fc66bd0717664a339a2e

See LICENSE.txt for license information.
```

**Comment by dg0yt** [comment] 2023-06-27 07:56
> the correct installation location should be `${VCPKG_INSTALL_DIR}/include/glib-2.0/`.

AFAIU this would be the "convenience" location for some vcpkg users. Upstream deliberately chose a different "correct" location, and probably takes care of covering it in exported configuration. Moving it may break some other users.

**Comment by UnknownObject000** [comment] 2023-06-27 08:03
> glib installs some headers into `lib/glib-2.0/include` on top of `include`. If you're using cmake I'd recommend to use [KDE's find script for glib2](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/find-modules/FindGLIB2.cmake).

This works for me.

**Comment by UnknownObject000** [comment] 2023-06-27 08:03
> > ```c++
> > #include <gst/gst.h>
> > #include <gst/app/gstappsink.h>
> > 
> > int main()
> > {
> > 	return 0;
> > }
> > ```
> 
> I guess you should have made a mistake, `gst/gst.h` is the header file of `gstreamer`.

Yes, but it needs glib to work.

**Closed** 2023-06-27 08:04 UTC
Labels: category:port-bug

**Comment by SchaichAlonso** [comment] 2023-06-27 08:18
The reason the `glibconfig.h` include file is installed into a library path rather then into an include path is that some unix/linux systems have implemented simultanous 32-bit and 64-bit support by installing 32-bit libraries into `/usr/lib32` and `/usr/local/lib32` while 64-bit libraries are placed into `/usr/lib64` and `/usr/local/lib64`.
On such systems, there will be only one set of include paths independend of the compilation target architecture, however, some include files are specific to their library's architecture. This is resolved by placing the target specific include files into the library path, and using pkg-config to communicate this to a build process.

i.e. it's an attempt to keep `include` platform independent, and use `lib/${library}/include` for platform dependend include files. Note that many projects don't care about this diffentiation and just put all includes into the same path.
