### ISSUE TITLE
Boost post build validation fails

### ISSUE THREAD

**Issue by navidR** [Microsoft/vcpkg#691] opened 2017-02-19 05:52 UTC
-- Performing post-build validation
There should be no empty directories in C:/Users/navid/AppData/Local/Lib/vcpkg/packages/boost_x86-windows
The following empty directories were found:

    C:/Users/navid/AppData/Local/Lib/vcpkg/packages/boost_x86-windows/bin
    C:/Users/navid/AppData/Local/Lib/vcpkg/packages/boost_x86-windows/debug/bin
    C:/Users/navid/AppData/Local/Lib/vcpkg/packages/boost_x86-windows/debug/lib
    C:/Users/navid/AppData/Local/Lib/vcpkg/packages/boost_x86-windows/lib

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/a/dir ${CURRENT_PACKAGES_DIR}/some/other/dir)

-- Performing post-build validation done
Found 1 error(s). Please correct the portfile:
    C:\Users\navid\AppData\Local\Lib\vcpkg\ports\boost\portfile.cmake
Error: Building package boost:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure sure you're using the latest portfiles with `vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost:x86-windows
  Vcpkg version: 0.0.74-128ba92feeba2f474d19a5fc738fb60338b5e70a

**Comment by ras0219-msft** [comment] 2017-02-19 08:18
This is caused by Boost not supporting the latest VS2017 preview.

I'm closing this as a duplicate of #683 -- let's work on this issue there.

**Closed by ras0219-msft** 2017-02-19 08:18 UTC
