### ISSUE TITLE
[glfw3] Build error

### ISSUE THREAD

**Issue by pettaa123** [microsoft/vcpkg#29292] opened 2023-01-30 20:24 UTC
Package: glfw3[core]:x86-windows -> 3.3.8#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30147.0
-    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 91dd61bd4 2023-01-27 (3 days ago)

**To Reproduce**

`vcpkg install glfw3:x86-windows`

**Failure logs**

```
-- Downloading https://github.com/glfw/glfw/archive/7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz -> glfw-glfw-7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/glfw/glfw/archive/7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/glfw/glfw/archive/7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz
File: E:\git\vcpkg\downloads\glfw-glfw-7482de6071d21db77a7236155da44c172a7f6c9e.tar.gz.2952.part
Expected hash: ec45b620338cf36a8dbdf7aaf54d7c3a49a1be4ae1a1ef95f1531094fec670870713969bbc23476769d374c7a71d93f6540ab64c46fb5f66f4402bb2d15c7d87
Actual hash: f2541cc801adb9a4d6ea6932c234953240d902212bd0a2d3a6f8d95c1dbff3adbd8e8e757ae991a544d979000c351c209d5e4054f71427d1a0490dbbfe0763fb
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956): 
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 1 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 1322 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 432.3 ms (427300 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/glfw3/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by willeccles** [comment] 2023-01-30 20:39
Same issue as #29288.

**Comment by BillyONeal** [comment] 2023-01-30 20:55
Dupe of https://github.com/microsoft/vcpkg/issues/29288

**Closed by BillyONeal** 2023-01-30 20:55 UTC
Labels: category:port-bug
