### ISSUE TITLE
SFML x64-windows-static fails on Windows 10

### ISSUE THREAD

**Issue by esduran** [microsoft/vcpkg#7118] opened 2019-07-01 23:49 UTC
I have the latest version of vcpkg installed on my Windows 10 PC. I tried installing sfml:x64-windows-static and I get the following error message:
```
Error: Building package openal-soft:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openal-soft:x64-windows-static
  Vcpkg version: 2019.06.21-nohash
```

**Comment by cskrisz** [comment] 2019-07-02 00:17
Can't reproduce. Do you have any additional logs?

**Comment by n42k** [comment] 2019-07-02 01:54
I tried installing sfml:x64-windows-static but stumbled upon a different error:
```
C:\Users\n42k\vcpkg>vcpkg install sfml:x64-windows-static
The following packages will be built and installed:
  * bzip2[core]:x64-windows-static
  * freetype[core]:x64-windows-static
  * libflac[core]:x64-windows-static
  * libogg[core]:x64-windows-static
  * libpng[core]:x64-windows-static
  * libvorbis[core]:x64-windows-static
  * openal-soft[core]:x64-windows-static
    sfml[core]:x64-windows-static
  * stb[core]:x64-windows-static
  * zlib[core]:x64-windows-static
Additional packages (*) will be modified to complete this operation.
Starting package 1/10: zlib:x64-windows-static
Building package zlib[core]:x64-windows-static...
CMake Error at scripts/ports.cmake:37 (message):
  Unsupported target triplet.  Triplet file does not exist:


Error: Building package zlib:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: zlib:x64-windows-static
  Vcpkg version: 2019.06.21-nohash
```

I get the same error as you if I install `openal-soft:x64-windows-static` directly. It seems like dependencies are being installed in a different order.

**Comment by wangli28** [comment] 2019-07-02 02:15
Hi @n42k, thanks for your feedback! Because VCPKG has been updated, you can run this command `.\bootstrap-vcpkg.bat` to update VCPKG.

**Comment by n42k** [comment] 2019-07-02 02:25
I was able to successfully compile `sfml:x64-windows-static` after running `.\bootstrap-vcpkg.bat`. Thank you, I'll take that in mind next time.

**Comment by esduran** [comment] 2019-07-02 03:16
That fixed worked for me as well. Thank you @wangli28

**Comment by wangli28** [comment] 2019-08-20 07:42
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Closed by wangli28** 2019-08-20 07:42 UTC
Labels: needs-repro
