### ISSUE TITLE
[New Port Request] SingleApplication

### ISSUE THREAD

**Issue by nickdademo** [microsoft/vcpkg#27653] opened 2022-11-04 06:17 UTC
Library name: SingleApplication

Library description: This is a replacement of the QtSingleApplication for Qt5 and Qt6.

Source repository URL: https://github.com/itay-grudev/SingleApplication

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by FrankXie05** [comment] 2022-11-04 07:33
Duplicate of https://github.com/microsoft/vcpkg/issues/26136

**Comment by nickdademo** [comment] 2023-11-10 02:40
I have created a vcpkg port for this - can we reopen this issue? Also, would `qt-single-application` be a more appropriate name for the port?

**Comment by FrankXie05** [comment] 2023-11-10 02:46
@nickdademo As long as the name is brief and clear, we can completely accept `qt-single-application`. :)

**Comment by dg0yt** [comment] 2023-11-10 04:48
> @nickdademo As long as the name is brief and clear, we can completely accept `qt-single-application`. :)

`<GH-orga>-<GH-repo>`: `itay-grudev-singleapplication`
Avoids confusion about its origin.

**Comment by PanForPancakes** [comment] 2023-12-27 15:26
So since PR was merged this issue could be closed now?

**Comment by FrankXie05** [comment] 2023-12-28 02:28
> So since PR was merged this issue could be closed now?

Yes, thanks.

**Closed by FrankXie05** 2023-12-28 02:28 UTC
Labels: category:new-port, info:good-first-issue
