### ISSUE TITLE
Update librealsense to v2.19

### ISSUE THREAD

**Issue by jasjuang** [microsoft/vcpkg#5753] opened 2019-03-20 17:00 UTC
Can someone update librealsense to v2.19? There's a major pain point that has been resolved in the latest release. https://github.com/IntelRealSense/librealsense/issues/3065 @UnaNancyOwen @claudiofantacci

**Comment by vicroms** [comment] 2019-03-21 07:59
There's an open PR #5275 to update to v2.18 but it has met with some roadblocks.
Right now, we don't have the bandwidth to address the issue, so any help provided would be greatly appreciated.

**Comment by claudiofantacci** [comment] 2019-03-21 08:03
Hey! I can work on it from tomorrow :-)

**Comment by claudiofantacci** [comment] 2019-03-22 10:19
I'm wokring on this right now, but, as I'm not working with OpenNI, I will only be able to update and test the update.

**Comment by claudiofantacci** [comment] 2019-03-22 15:00
The current version of the portfile has several errors under Windows.
The most important one concerns the installation of the debug build into the installation folder.
I'm investigating this and it seems an error introduced while fixing the portfile for Linux.

**Comment by claudiofantacci** [comment] 2019-03-22 15:05
Also, I'm trying to configure the portfile to use `ninja` but there is a problem while fetching `libusb` from internet with `git`. I'm investigating whether the problem is in the `librealsense` CMakeLists or if it is a CMake issue in the [`ExternalProject_Add`](https://cmake.org/cmake/help/latest/module/ExternalProject.html) command.

Anyway, I hope to have a working updated portfile as soon as possible, with or without upstream fixes.

**Comment by claudiofantacci** [comment] 2019-03-26 11:33
I'm finally able to compile configure and compile the library using `ninja`.

There is a permission/privileges conflict between processes when using `ninja` with `-DBUILD_WITH_TM2=ON` triggered by the custom target created with `EcternalProject_Add`.
I'll open a PR upstream to have feedback.

If you leave it to `-DBUILD_WITH_TM2=ON` (as default configuration), `ninja` build now complete succesfully. The `-DBUILD_WITH_TM2=OFF` was necessary due to the following error https://github.com/IntelRealSense/librealsense/issues/3483 that however I fixed with a patch that I'm trying to discuss upstream.

I'm trying the new portfile locally and then I'll update the PR.

**Closed** 2019-06-17 21:38 UTC
Labels: port update
