### ISSUE TITLE
lapack-reference:x64-windows build failure

### ISSUE THREAD

**Issue by spindensity** [microsoft/vcpkg#12902] opened 2020-08-14 06:46 UTC
**Host Environment**
- OS: `Windows 10 20H1`;
- Compiler: `MSVC 2019 16.7.1`.

**To Reproduce**
`vcpkg install lapack-reference:x64-windows`

**Failure logs** 
Console output:
```
Computing installation plan...
The following packages will be built and installed:
    lapack-reference[blas-select,core,noblas]:x64-windows
Detecting compiler hash for triplet x64-windows...
Starting package 1/1: lapack-reference:x64-windows
Building package lapack-reference[blas-select,core,noblas]:x64-windows...
Could not locate cached archive: C:\Users\spindensity\AppData\Local\vcpkg\archives\af\afc102535fceb1dfecf5f23a17ddda0d57e826ba.zip
-- Using cached D:/Repository/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Cleaning sources at D:/Repository/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Repository/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Using source at D:/Repository/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/Repository/vcpkg/buildtrees/lapack-reference/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Repository\vcpkg\buildtrees\lapack-reference\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/lapack-reference/portfile.cmake:56 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package lapack-reference:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: lapack-reference:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above
```

Log(`D:\Repository\vcpkg\buildtrees\lapack-reference\config-x64-windows-out.log`):
```
[1/2] cmd /c "cd .. && "D:/Repository/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "D:/Repository/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean" "-DUSE_OPTIMIZED_BLAS=ON" "-DCBLAS=OFF" "-DCMAKE_GNUtoMS=ON" "-DCMAKE_Fortran_COMPILER=D:/Repository/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gfortran.exe" "-DCMAKE_C_COMPILER=D:/Repository/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gcc.exe" "-DCMAKE_Fortran_FLAGS_INIT:STRING= -mabi=ms -m64 " "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Repository/vcpkg/scripts/toolchains/mingw.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/Repository/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/Repository/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/Repository/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/Repository/vcpkg/packages/lapack-reference_x64-windows""

FAILED: ../CMakeCache.txt 

cmd /c "cd .. && "D:/Repository/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "D:/Repository/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean" "-DUSE_OPTIMIZED_BLAS=ON" "-DCBLAS=OFF" "-DCMAKE_GNUtoMS=ON" "-DCMAKE_Fortran_COMPILER=D:/Repository/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gfortran.exe" "-DCMAKE_C_COMPILER=D:/Repository/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gcc.exe" "-DCMAKE_Fortran_FLAGS_INIT:STRING= -mabi=ms -m64 " "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Repository/vcpkg/scripts/toolchains/mingw.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/Repository/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/Repository/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/Repository/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=D:/Repository/vcpkg/packages/lapack-reference_x64-windows""

CMake Error at CMakeLists.txt:3 (project):
  The Ninja generator does not support Fortran using Ninja version

    1.8.2

  due to lack of required features.  Ninja 1.10 or higher is required.


-- Configuring incomplete, errors occurred!
See also "D:/Repository/vcpkg/buildtrees/lapack-reference/x64-windows-rel/CMakeFiles/CMakeOutput.log".
[2/2] cmd /c "cd ../../x64-windows-dbg && "D:/Repository/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "D:/Repository/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean" "-DUSE_OPTIMIZED_BLAS=ON" "-DCBLAS=OFF" "-DCMAKE_GNUtoMS=ON" "-DCMAKE_Fortran_COMPILER=D:/Repository/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gfortran.exe" "-DCMAKE_C_COMPILER=D:/Repository/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gcc.exe" "-DCMAKE_Fortran_FLAGS_INIT:STRING= -mabi=ms -m64 " "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Repository/vcpkg/scripts/toolchains/mingw.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/Repository/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/Repository/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/Repository/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=D:/Repository/vcpkg/packages/lapack-reference_x64-windows/debug""

FAILED: ../../x64-windows-dbg/CMakeCache.txt 

cmd /c "cd ../../x64-windows-dbg && "D:/Repository/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "D:/Repository/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean" "-DUSE_OPTIMIZED_BLAS=ON" "-DCBLAS=OFF" "-DCMAKE_GNUtoMS=ON" "-DCMAKE_Fortran_COMPILER=D:/Repository/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gfortran.exe" "-DCMAKE_C_COMPILER=D:/Repository/vcpkg/downloads/tools/msys2/msys64/mingw64/bin/gcc.exe" "-DCMAKE_Fortran_FLAGS_INIT:STRING= -mabi=ms -m64 " "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=D:/Repository/vcpkg/scripts/toolchains/mingw.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=D:/Repository/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=D:/Repository/vcpkg" "-D_VCPKG_INSTALLED_DIR=D:/Repository/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=D:/Repository/vcpkg/packages/lapack-reference_x64-windows/debug""

CMake Error at CMakeLists.txt:3 (project):
  The Ninja generator does not support Fortran using Ninja version

    1.8.2

  due to lack of required features.  Ninja 1.10 or higher is required.


-- Configuring incomplete, errors occurred!
See also "D:/Repository/vcpkg/buildtrees/lapack-reference/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.
```

**Comment by LilyWangL** [comment] 2020-08-14 06:52
Thanks for posting this issue. Closed as duplicate of #12888. This issue will be fixed in PR #12895.

**Closed by LilyWangL** 2020-08-14 06:52 UTC
