### ISSUE TITLE
[CPR]  Update to 1.8.3 (again, see details)

### ISSUE THREAD

**Issue by Binary-System** [microsoft/vcpkg#25237] opened 2022-06-14 20:04 UTC
Library name: CPR

New version number: 1.8.3

Other information that may be useful:
1.8.3 is currently included but there where features added to 1.8.3 after the inclusion into vcpkg. (Like ReserveSize and others)

**Comment by JonLiu1993** [comment] 2022-06-15 07:42
@Binary-System ,Thanks for posting this issue, when the next release version pubilsh, I will update this port.

**Comment by JonLiu1993** [comment] 2022-07-18 09:31
Duplicate of #25833

**Closed by JonLiu1993** 2022-07-18 09:31 UTC
Labels: category:port-update
