### ISSUE TITLE
Cannot use static compiled arrow package

### ISSUE THREAD

**Issue by aavbsouza** [microsoft/vcpkg#28566] opened 2022-12-26 20:22 UTC
Hello everyone I am trying to use the static compiled arrow package 
(`vcpkg --triplet=x64-windows-static arrow[core,parquet]`). The build occurs without issues. However When I try to use the targets generated I get this error:

```bash
C:\Users\localuser\install\bin\cmake.EXE --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug "-DCMAKE_C_COMPILER:FILEPATH=C:\Program Files\LLVM\bin\clang.exe" "-DCMAKE_CXX_COMPILER:FILEPATH=C:\Program 
Files\LLVM\bin\clang++.exe" -Sc:/Users/localuser/Downloads/parquet_export/parquet_export -Bc:/Users/localuser/Downloads/parquet_export/parquet_export/build -G Ninja -DCMAKE_TOOLCHAIN_FILE=C:\Users\localuser\Downloads\vcpkg\scripts\buildsystems\vcpkg.cmake  -DVCPKG_TARGET_TRIPLET=x64-windows-static
Not searching for unused variables given on the command line.
-- The C compiler identification is Clang 15.0.6 with GNU-like command-line
-- The CXX compiler identification is Clang 15.0.6 with GNU-like command-line
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/LLVM/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/LLVM/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - no
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE  
-- Found SnappyAlt: C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/debug/lib/snappy.lib  
-- Found Brotli: C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/debug/lib/brotlicommon-static.lib  
-- Found OpenSSL: C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/debug/lib/libcrypto.lib (found version "3.0.7")  
CMake Warning (dev) at C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/thrift/ThriftConfig.cmake:59 (if):
  if given arguments:

    "TRUE" "AND" "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/arrow/FindThriftAlt.cmake:42 (find_package)
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  C:/Users/localuser/install/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/arrow/ArrowConfig.cmake:105 (find_dependency)
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  parquet-export/CMakeLists.txt:31 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found thrift: C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static
CMake Warning (dev) at C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/thrift/ThriftConfig.cmake:76 (if):
  if given arguments:

    "TRUE" "AND" "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/arrow/FindThriftAlt.cmake:42 (find_package)
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  C:/Users/localuser/install/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/arrow/ArrowConfig.cmake:105 (find_dependency)
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  parquet-export/CMakeLists.txt:31 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/thrift/ThriftConfig.cmake:80 (if):
  if given arguments:

    "TRUE" "AND" "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/arrow/FindThriftAlt.cmake:42 (find_package)
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  C:/Users/localuser/install/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/arrow/ArrowConfig.cmake:105 (find_dependency)
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  parquet-export/CMakeLists.txt:31 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/thrift/ThriftConfig.cmake:84 (if):
  if given arguments:

    "TRUE" "AND" "ON"

  An argument named "ON" appears in a conditional statement.  Policy CMP0012
  is not set: if() recognizes numbers and boolean constants.  Run "cmake
  --help-policy CMP0012" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.
Call Stack (most recent call first):
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/arrow/FindThriftAlt.cmake:42 (find_package)
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  C:/Users/localuser/install/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/arrow/ArrowConfig.cmake:105 (find_dependency)
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  parquet-export/CMakeLists.txt:31 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found ZLIB: optimized;C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/lib/zlib.lib;debug;C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/debug/lib/zlibd.lib (found version "1.2.13") 
-- Found BZip2: optimized;C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/lib/bz2.lib;debug;C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/debug/lib/bz2d.lib (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
CMake Error at C:/Users/localuser/install/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find utf8proc (missing: utf8proc_LIB) (found version "2.7.0")
Call Stack (most recent call first):
  C:/Users/localuser/install/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/arrow/Findutf8proc.cmake:104 (find_package_handle_standard_args)
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  C:/Users/localuser/install/share/cmake-3.25/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/share/arrow/ArrowConfig.cmake:105 (find_dependency)
  C:/Users/localuser/Downloads/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  parquet-export/CMakeLists.txt:31 (find_package)


-- Configuring incomplete, errors occurred!
See also "C:/Users/localuser/Downloads/parquet_export/parquet_export/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/localuser/Downloads/parquet_export/parquet_export/build/CMakeFiles/CMakeError.log"
```

The error is:

```bash
-- Found BZip2: optimized;C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/lib/bz2.lib;debug;C:/Users/localuser/Downloads/vcpkg/installed/x64-windows-static/debug/lib/bz2d.lib (found version "1.0.8") 
-- Looking for BZ2_bzCompressInit
-- Looking for BZ2_bzCompressInit - found
CMake Error at C:/Users/localuser/install/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find utf8proc (missing: utf8proc_LIB) (found version "2.7.0")
```

Actually I do not need to use the bz2 compression is there a way to pass the necessary flags to the arrow installation procedure to disable this compressor ?

thanks

**Comment by Neumann-A** [comment] 2022-12-26 23:36
Did you miss a `cmake_minimum_required` at the top of your `CMakeLists.txt`?

**Comment by aavbsouza** [comment] 2022-12-26 23:38
Hello @Neumann-A  I am using this:
```
cmake_minimum_required(VERSION 3.20)
```

**Comment by Neumann-A** [comment] 2022-12-27 00:16
Is it the first line in your `CMakeLists.txt`?

**Comment by aavbsouza** [comment] 2022-12-27 00:22
Hello @Neumann-A  is the second one after the project name

```cmake
project(projectName)
cmake_minimum_required(VERSION 3.20)
...
```

**Comment by Neumann-A** [comment] 2022-12-27 00:27
https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html : Reread the Note there

**Comment by aavbsouza** [comment] 2022-12-27 02:40
Hello @Neumann-A  I have tried to change the order as suggested on the cmake documentation but with no effect. I am still getting the same error message.  However I was able to use a custom port files to build and use the arrow library statically on windows. For this custom port files I have mostly disabled external dependencies of the arrow library that is not useful for this particular use case. I am using the manifest option for the `vcpkg.json`  and also using the overlay-ports option for this file. This is a very useful  arrangement to use.

Would be possible to the custom port be "confused" with a normal port ?  As in `my-custom-port` also being the name for a public port file ?

thanks =)

**Comment by Neumann-A** [comment] 2022-12-27 22:19
Try passsing `-DARROW_PACKAGE_KIND=vcpkg`. The problem is that arrows find modules are adding CMake lib suffixes and prefixes manually for the `find_library` call which is wrong. (dont know why somebody added ARROW_PACKAGE_KIND instead of generally fixing the issue.)

**Comment by jimwang118** [comment] 2023-02-15 06:54
This problem has been solved in the latest vcpkg. I need to close this issue, please reopen this issue if you have a better solution.

**Closed by jimwang118** 2023-02-15 06:54 UTC
Labels: category:question
