### ISSUE TITLE
[sqlite3] Downstream CMake users of dynamic-linkage builds not able to find Threads

### ISSUE THREAD

**Issue by venabled** [microsoft/vcpkg#24428] opened 2022-04-26 13:45 UTC
****

**Is your feature request related to a problem? Please describe.**
Right now, consuming sqlite3 in a project which uses the unofficial::sqlite3 CMake configs (linux, dynamic linkage), I get this error:

```
CMake Error at /home/venabled/source/vcpkg/installed/x64-linux/share/unofficial-sqlite3/unofficial-sqlite3-targets.cmake:55 (set_target_properties):
  The link interface of target "unofficial::sqlite3::sqlite3" contains:

    Threads::Threads

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /home/venabled/source/vcpkg/installed/x64-linux/share/unofficial-sqlite3/unofficial-sqlite3-config.cmake:7 (include)
  /home/venabled/source/vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
  /home/venabled/cmake-3.23.1-linux-x86_64/share/cmake-3.23/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /home/venabled/source/vcpkg/installed/x64-linux/share/proj4/proj4-config.cmake:13 (find_dependency)
  /home/venabled/source/vcpkg/scripts/buildsystems/vcpkg.cmake:816 (_find_package)
  geospatial/CMakeLists.txt:15 (find_package)
  ```

**Proposed solution**
Double check the creation of the sqlite3 CMake Config, right now it looks like (after generator expressions and installation):

```
venabled@maximus:~/source/navlib/vcpkgbuild$ cat ~/source/vcpkg/installed/x64-linux/share/unofficial-sqlite3/unofficial-sqlite3-config.cmake 

include(CMakeFindDependencyMacro)
find_dependency(Threads)

include(${CMAKE_CURRENT_LIST_DIR}/unofficial-sqlite3-targets.cmake)
venabled@maximus:~/source/navlib/vcpkgbuild$ 
```

Removing the if statement or fixing it such that "dynamic" STREQUAL "dynamic" fixes the issue:

```
#if("dynamic" STREQUAL "static" AND NOT WIN32)
    include(CMakeFindDependencyMacro)
    find_dependency(Threads)
#endif()

include(${CMAKE_CURRENT_LIST_DIR}/unofficial-sqlite3-targets.cmake)
```

**Comment by Neumann-A** [comment] 2022-04-26 21:05
Did you try https://cmake.org/cmake/help/latest/module/FindSQLite3.html instead?

**Comment by venabled** [comment] 2022-04-26 21:11
I did, but it's in a cmake config for another port (proj) which I didn't write.

**Comment by Neumann-A** [comment] 2022-04-26 21:13
cc @dg0yt

**Comment by dg0yt** [comment] 2022-04-27 05:05
#### 1. Fix the sqlite3 build system

vcpkg has its own build system for sqlite3, so maybe it has its own bugs?
https://github.com/microsoft/vcpkg/blob/fb02a785618a1fbaced32b206171e09fd57d4622/ports/sqlite3/CMakeLists.txt#L128-L136

IMO these libraries should be `PRIVATE`, not `PUBLIC`. Then CMake act differently for downstream usage.

#### 2. (Un-)Guard downstream usage

The proj config follows the pattern of other ports, doing `find_dependency` only when building with static linkage.
If the condition on linkage type is removed, errors like this won't appear (as report by the OP).
However, in a sane environment, this shouldn't be needed for dynamic linkage.

#### 3. Support my cmake-validate port / PR

With integrated validation, this issue would have been discovered early, close to the root cause.

**Comment by Cheney-W** [comment] 2022-07-14 10:31
Fixed by https://github.com/microsoft/vcpkg/pull/25460

**Closed by Cheney-W** 2022-07-14 10:31 UTC
Labels: category:port-bug, category:community-triplet
