### ISSUE TITLE
scintilla is missing from the repo

### ISSUE THREAD

**Issue by suroh** [Microsoft/vcpkg#3006] opened 2018-03-11 14:04 UTC
Whil attempting to install Scintilla I was given an error stating it could not be found. This has so far only happened with this package.

`C:\vcpkg-master>vcpkg install scintilla`
`Error: while loading scintilla: no such file or directory`

**Comment by glachancecmaisonneuve** [comment] 2018-03-12 17:19
can't reproduce.  try again in a clean tree?

**Comment by suroh** [comment] 2018-03-12 22:59
Same result. I'm going to do this in a vm.

**Comment by NancyLi1013** [comment] 2019-02-13 02:38
@suroh , Could you please help us confirm whether there is still a problem on your machine now. If yes, please provide more info about your testing environment. If no problem, please close this issue.
Thanks!

**Comment by NancyLi1013** [comment] 2019-03-01 05:50
Please open a new issue if this is still a problem for you.

**Closed by NancyLi1013** 2019-03-01 05:50 UTC
Labels: needs-repro
