### ISSUE TITLE
[colmap] building failure

### ISSUE THREAD

**Issue by juanmcc** [microsoft/vcpkg#28078] opened 2022-11-30 08:25 UTC
**Describe the bug**
I can't install colmap on Windows 10.

**Environment**
- OS: Windows 10
- Compiler: cmake-3.24

**To Reproduce**
1. ./vcpkg install colmap[cuda,tests]:x64-windows
2. See error
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: C:/Users/anton/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j17
    Working Directory: C:/Users/anton/vcpkg/buildtrees/colmap/x64-windows-rel
    See logs for more information:
      C:\Users\anton\vcpkg\buildtrees\colmap\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:59 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building colmap:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
Include '[colmap] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: 4e368f639 2022-11-28 (16 hours ago)

**Expected behavior**
The installation can't be finished.

**Failure logs**
-(please attached failure logs)

[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/10121014/install-x64-windows-rel-out.log)

**Comment by Cheney-W** [comment] 2022-12-01 03:19
Closing this issue as duplicate of https://github.com/microsoft/vcpkg/issues/25303.

**Closed by Cheney-W** 2022-12-01 03:19 UTC
Labels: depends:upstream-changes
