### ISSUE TITLE
[python3] Build error

### ISSUE THREAD

**Issue by exsystem** [microsoft/vcpkg#33393] opened 2023-08-26 13:08 UTC
Package: python3:arm64-osx -> 3.11.4#4

**Host Environment**

- Host: arm64-osx
- Compiler: AppleClang 14.0.3.14030022
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 436a061a5 2023-08-25 (17 hours ago)

**To Reproduce**

`vcpkg install boost`
**Failure logs**

```
-- Using cached python-cpython-v3.11.4.tar.gz.
-- Cleaning sources at /Users/exsystem/.vcpkg-clion/vcpkg/buildtrees/python3/src/v3.11.4-ce6efd80c0.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/exsystem/.vcpkg-clion/vcpkg/downloads/python-cpython-v3.11.4.tar.gz
-- Applying patch 0001-only-build-required-projects.patch
-- Applying patch 0003-use-vcpkg-zlib.patch
-- Applying patch 0004-devendor-external-dependencies.patch
-- Applying patch 0005-dont-copy-vcruntime.patch
-- Applying patch 0008-python.pc.patch
-- Applying patch 0010-dont-skip-rpath.patch
-- Applying patch 0012-force-disable-curses.patch
-- Applying patch 0014-fix-get-python-inc-output.patch
-- Applying patch 0015-dont-use-WINDOWS-def.patch
-- Applying patch 0002-static-library.patch
-- Using source at /Users/exsystem/.vcpkg-clion/vcpkg/buildtrees/python3/src/v3.11.4-ce6efd80c0.clean
-- Getting CMake variables for arm64-osx-dbg
-- Getting CMake variables for arm64-osx-rel
-- Generating configure for arm64-osx
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /opt/homebrew/bin/autoreconf -vfi
    Working Directory: /Users/exsystem/.vcpkg-clion/vcpkg/buildtrees/python3/src/v3.11.4-ce6efd80c0.clean/
    Error code: 1
    See logs for more information:
      /Users/exsystem/.vcpkg-clion/vcpkg/buildtrees/python3/autoconf-arm64-osx-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:635 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:257 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)



```
<details><summary>/Users/exsystem/.vcpkg-clion/vcpkg/buildtrees/python3/autoconf-arm64-osx-err.log</summary>

```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /opt/homebrew/Cellar/autoconf/2.71/bin/autoconf --force
configure.ac:18: error: possibly undefined macro: AC_MSG_ERROR
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: error: /opt/homebrew/Cellar/autoconf/2.71/bin/autoconf failed with exit status: 1
```
</details>

**Comment by Neumann-A** [comment] 2023-08-26 14:29
you probably need to install autoconf-archive

**Comment by MonicaLiu0311** [comment] 2023-10-20 02:53
Duplicate of #33080.

**Closed by MonicaLiu0311** 2023-10-20 02:53 UTC
Labels: category:question
