### ISSUE TITLE
vcpkg export preserves orignal file locations in cmake files

### ISSUE THREAD

**Issue by Kicer86** [microsoft/vcpkg#15320] opened 2020-12-26 21:44 UTC
**Describe the bug**
vcpkg export generates package with absolute paths.

**Environment**
- OS: Windows

**To Reproduce**
1. ./vcpkg export <any_package> --raw --output=c:\exported_package

in c:\exported_package you can find many cmake an pc files containing original, full paths to files.
This makes package quite useless as it cannot be shared (unless other users place it in the same location)

**Expected behavior**
exported package should be more flexible

**Comment by NancyLi1013** [comment] 2020-12-28 08:12
Hi @Kicer86 

Thanks for posting this issue.

Could you please help provide which packages that you installed contain origional, full paths?

I tried to export `zlib ` as an example and found no absolute path in the files. So I think it might be related with the ports.

**Comment by Kicer86** [comment] 2020-12-28 10:17
Hi

Try exiv2 (another one is dlib, but it is heavy to build): 
vcpkg.exe export exiv2  --raw --output=c:\exported

and then:
```
$ grep -IR "C:/vcpkg" /c/exported/
/c/exported/installed/x64-windows/debug/lib/libcharset.la:dependency_libs=' -L=C:/vcpkg/installed/x64-windows/debug/lib -L=C:/vcpkg/installed/x64-windows/debug/lib/manual-link'
/c/exported/installed/x64-windows/debug/lib/libiconv.la:dependency_libs=' -L=C:/vcpkg/installed/x64-windows/debug/lib -L=C:/vcpkg/installed/x64-windows/debug/lib/manual-link'
/c/exported/installed/x64-windows/debug/lib/pkgconfig/exiv2.pc:prefix=C:/vcpkg/packages/exiv2_x64-windows/debug
/c/exported/installed/x64-windows/lib/libcharset.la:dependency_libs=' -L=C:/vcpkg/installed/x64-windows/lib -L=C:/vcpkg/installed/x64-windows/lib/manual-link'
/c/exported/installed/x64-windows/lib/libiconv.la:dependency_libs=' -L=C:/vcpkg/installed/x64-windows/lib -L=C:/vcpkg/installed/x64-windows/lib/manual-link'
/c/exported/installed/x64-windows/lib/pkgconfig/exiv2.pc:prefix=C:/vcpkg/packages/exiv2_x64-windows
```

Another issue is this:
```
$ grep -IR "packages/" /c/exported/
/c/exported/installed/x64-windows/debug/lib/pkgconfig/exiv2.pc:prefix=C:/vcpkg/packages/exiv2_x64-windows/debug
/c/exported/installed/x64-windows/lib/pkgconfig/exiv2.pc:prefix=C:/vcpkg/packages/exiv2_x64-windows
```

as **packages** dir is not included in export.

**Comment by NancyLi1013** [comment] 2020-12-30 06:34
Hi @Kicer86 

For exiv2.pc, it is a port bug for `exiv2`. we can add `vcpkg_fixup_pkgconfig()` to fix the path.

For libcharset.la and libiconv.la, it should be a port bug for `libiconv`. I'm investigating how to fix it now.

**Comment by NancyLi1013** [comment] 2020-12-30 08:46
@Neumann-A 

Could you please help take a look the path issue in `libiconv`? 

Currently, libcharset.la and libiconv.la contains absolute path.

**Comment by Neumann-A** [comment] 2020-12-30 22:10
@NancyLi1013 those files are generated and used by libtool. I have not yet figured out a way to make them relativ but i also have not found a dependency/consumer on those files yet to even test making them relative. As such just leave them be until somebody comes up with an issue/testcase concerning the consumption on those files.

**Comment by NancyLi1013** [comment] 2020-12-31 02:55
@Neumann-A 

Thank you so much for your investigation and above details. I also have no idea about the path problem now.

@Kicer86

Could you please help describe what the specific problem when you use these files?

**Comment by Kicer86** [comment] 2020-12-31 15:42
@NancyLi1013 frankly speaking I just found it invalid but it is not an issue for me. I guess pkg-config would complain but I did not test it.

So I believe @Neumann-A is right here

**Comment by NancyLi1013** [comment] 2021-01-21 09:23
The issue caused by `exiv2 `has been fixed now.

For the path issue in `libicov`, it seems this doesn't cause any problems now. There are also no available ways to solve this.

So I'm closing this issue for now. We can open a new issue if there is problem in the future.

**Closed by NancyLi1013** 2021-01-21 09:23 UTC
Labels: category:port-bug
