### ISSUE TITLE
error: Failed to download from mirror set, does not have the right hash

### ISSUE THREAD

**Issue by gillianlaming** [microsoft/vcpkg#29296] opened 2023-01-30 21:03 UTC
Package: libzip[bzip2,core,default-aes,wincrypto]:x86-windows -> 1.9.2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31937.0
-    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 1e9facc79 2023-01-15 (2 weeks ago)

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Downloading https://github.com/nih-at/libzip/archive/5532f9baa0c44cc5435ad135686a4ea009075b9a.tar.gz -> nih-at-libzip-5532f9baa0c44cc5435ad135686a4ea009075b9a.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/nih-at/libzip/archive/5532f9baa0c44cc5435ad135686a4ea009075b9a.tar.gz
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/nih-at/libzip/archive/5532f9baa0c44cc5435ad135686a4ea009075b9a.tar.gz
File: D:\CxCache\Microsoft.Build.Vcpkg.2023.1.16.232-1e9facc79\tools\downloads\nih-at-libzip-5532f9baa0c44cc5435ad135686a4ea009075b9a.tar.gz.67872.part
Expected hash: 1105bc48c8a554a7fce84028197427b02ff53508592889b37e81cc419eb208d91112b98df2bf2d6f5629887e4418230ee36e3bf03c9ae39cdc39cfa90e7e3e7f
Actual hash: 0f9d86a2479815856ad5dc0fb3f5ac1b037924204dc7c728c82abe4b2868307f7b8e9ee193e82dfe5dc16ed524c88d326f789975d9468c137dd01dd9caaa852f
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956): 
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 12 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 1282 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 563.4 ms (352125 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/libzip/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "sitecontainer-dependencies",
  "version-string": "0.1.0-dev",
  "dependencies": [
    "bzip2",
    "libzip"
  ]
}

```
</details>

**Comment by gillianlaming** [comment] 2023-01-30 21:09
I am not using a proxy btw

**Comment by BillyONeal** [comment] 2023-01-30 21:12
Duplicate of https://github.com/microsoft/vcpkg/issues/29288

**Closed by BillyONeal** 2023-01-30 21:12 UTC
Labels: category:port-bug
