### ISSUE TITLE
[grpc] UPB library order wrong again?

### ISSUE THREAD

**Issue by Anpopela-Xbox** [microsoft/vcpkg#28938] opened 2023-01-13 21:44 UTC
**Describe the bug**
We're seeing a repeat of this bug: https://github.com/microsoft/vcpkg/issues/26751
Upb link order is wrong causing the vcpkg of grpc to not be usable. (At least not if you're using pkg-config) When using pkg-config to try to build against grpc++ you get a series of linker errors related to grpc.

**Environment**
- OS: Linux
- Compiler:  (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

**To Reproduce**
1. ./vcpkg install grpc
2. Attempt to build a demo file linking against grpc++. Use `pkg-config grpc++ --libs`
3. Observe linker errors

For a more specific example you can follow the repro steps from the other issue I attached

**Expected behavior**
The pkg-config should support linking to grpc++ automatically.

This is the library order that we got to actually link for us:
`-lgrpc -laddress_sorting -lre2 -lupb_textformat -lupb_mini_table -lupb -lupb_collections -lupb_reflection -lupb_extension_registry -lupb_json -lupb_fastdecode -lupb_utf8_range -ldescriptor_upb_proto -lcares -lz`

**Failure logs**
[FailureLogs.txt](https://github.com/microsoft/vcpkg/files/10415197/FailureLogs.txt)

**Additional context**
The real problem here is that gRpc's cmake file "cheats" when it comes to upb. Instead of organizing the libraries carefully like vcpkg does, they instead use their submodule of upb and create their own library with exactly the files they want in it. This bypasses the whole library problem vcpkg hits. It also means vcpkg is going to be stuck constantly rearranging these libraries as changes are made to upb. It might make sense for someone to ask upb to formally publish the library that grpc makes for itself.

@Tradias I'm curious how you generated the upb ordering that's currently checked in.

**Comment by Tradias** [comment] 2023-01-13 22:27
I wasn't even aware that the order matters nor that it got fixed by victor recently. I initially created the order randomly.

In the past, I had already brought up the issue that vcpkg should not offer upb as its own port. It is not ready for that and even says so in their github README. It causes vcpkg to create a giant patch for upb and gRPC to make things work. Rearranging pkg-config linkage is only a tiny part of it.

**Comment by Anpopela-Xbox** [comment] 2023-01-14 02:04
I'll be honest, I also had no idea library order could matter. I normally work in windows so I wonder if the MSVC++'s linker handles this automatically or if I've just gotten lucky. 

Regardless in this case its definitely clear that the order does matter. I'll see if I can distill the necessary order further after the long weekend. Thanks for the quick reply!!

**Comment by Tradias** [comment] 2023-01-15 12:29
I cannot reproduce the problem with GCC11 on Ubuntu 20.04. But I have noticed that you have added a library to the link list that wasn't there before: `upb_mini_table`. Maybe that is the whole reason it didn't work for you. Anyways I am about to open a pr that updates gRPC to 1.51.1 and uses your link order.

**Closed** 2023-01-16 20:53 UTC
Labels: category:port-bug

**Comment by Anpopela-Xbox** [comment] 2023-01-17 23:39
We didn't modify anything until after we hit the issue, so I'm not sure what originally caused it. If it comes up again I'll create something more directly reproducible so we can investigate further.

In the mean time I can confirm your fix works! Thank you very much.
