### ISSUE TITLE
Windows x64 FLTK not setup properly

### ISSUE THREAD

**Issue by jlfilion** [microsoft/vcpkg#12291] opened 2020-07-06 18:41 UTC
I am running Windows 10.0.18363 with Visual Studio 2019 installed. I have updated vcpkg and I'm running git version 2.26.0.windows.1 and cmake version 3.17.0-rc3.

I installed fltk with the following command:

vcpkg.exe install fltk:x64-windows

I added to my cmake file:

find_package(FLTK CONFIG REQUIRED)

I have been unable to get find_package(FLTK CONFIG REQUIRED) to work for fltk:x64-windows. I get the following errors:

$ cmake ..
-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
CMake Error at C:/Users/jfilion/vcpkg/installed/x64-windows/share/fltk/FLTK-Targets.cmake:93 (message):
  The imported target "fltk_SHARED" references the file

     "C:/Users/jfilion/vcpkg/installed/x64-windows/debug/lib/fltk_SHAREDd.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/Users/jfilion/vcpkg/installed/x64-windows/share/fltk/FLTK-Targets.cmake"

  but not all the files it references.

It appears fltk_SHAREDd.lib is referenced by FLTK-Targets.cmake but was not included. Is there something more required by me besides installing fltk:x64-windows and trying to use find_package(FLTK CONFIG REQUIRED)?

Thanks,
Joe

**Comment by PhoebeHui** [comment] 2020-07-07 10:18
@jlfilion, thanks for reporting this issue!

Confirmed, In vcpkg portfile.cmake, the static libs removed and renamed the shared libs to fltk, however the cmake targets file doesn't update it, so it failed here. however, it has another issue after we fix the libs name.

The root cause is fltk mess the libs when buildiing static and shared libs:
fltk built and used static library fltk in shared builds(fltk_forms_SHARED, fltk_images_SHARED,fltk_gl_SHARED), see https://github.com/fltk/fltk/blob/master/src/CMakeLists.txt#L587, from the comments:
```
# Note to devs: As of 08 Aug 2016 we can build shared libs (dlls)
# under Windows with Visual Studio (MSVC) but we can't link for instance
# fltk_images_SHARED with fltk_SHARED - we have to use fltk, i.e. the
# "static" object library instead. I don't know how to fix this, but
# at least we can build shared libraries (dlls) with Visual Studio.
# AlbrechtS
```
That means we can't remove the static libs when building shared libs, if not, it still failed to find the libraries.
Actually, I tried to distinguish the libs and link the shared libs instead, it failed with lots of link errors on windows. I'm not sure how to fix them now. @ras0219, could you give some guildines for fixing this issue?

**Comment by PhoebeHui** [comment] 2020-07-14 01:15
Fixed via https://github.com/microsoft/vcpkg/pull/12273

**Comment by PhoebeHui** [comment] 2020-07-31 05:43
@jlfilion, the PR has been merged, please get latest source and try to build again.

**Closed by PhoebeHui** 2020-07-31 05:43 UTC
Labels: category:port-bug

**Comment by jlfilion** [comment] 2020-08-02 15:01
Yes. It works now. Thank you so much for the help.

Joe
