### ISSUE TITLE
[re2] Build error on x64-windows

### ISSUE THREAD

**Issue by tigerpy** [microsoft/vcpkg#38147] opened 2024-04-12 05:30 UTC
Package: re2:x64-windows@2024-04-01#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33523.0
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: 582a4de14 2024-04-11 (9 hours ago)

**To Reproduce**

`vcpkg install grpc:x64-windows`
**Failure logs**

```
-- Downloading https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1 -> 9ebe4a22cad8a025b68a9594bdff3c047a111333.patch...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Disabling metrics because vcpkg.disable-metrics exists
[DEBUG] Trying to load bundleconfig from C:\temp\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\temp\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1
[DEBUG] Trying to hash C:\temp\dev\vcpkg\downloads\9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.17812.part
[DEBUG] C:\temp\dev\vcpkg\downloads\9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.17812.part has hash 83c1a4cc4ddd6e1443f5201f7f00cf6a0729d0a0fb8fc5068c3d80766238d72f019f1fddaeffebcc2d4322a07daf2203214121cdda039b10a5f39214b9fa8647
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1
File: C:\temp\dev\vcpkg\downloads\9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.17812.part
Expected hash: 167a0153bf24e77db2b8555a7d6391acf740dc4720a71e6ce19a3533c7e0a49923d9584ff32544a454837a25eedace00cb2ef9ddbf4250deb5f2c5aeda04ac26
Actual hash: 83c1a4cc4ddd6e1443f5201f7f00cf6a0729d0a0fb8fc5068c3d80766238d72f019f1fddaeffebcc2d4322a07daf2203214121cdda039b10a5f39214b9fa8647
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1031): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 107us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 427 ms (427168us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/re2/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:175 (include)



```

**Comment by tigerpy** [comment] 2024-04-12 05:31
Output from terminal window:

C:\temp\dev\vcpkg>vcpkg install grpc:x64-windows
Computing installation plan...
The following packages will be built and installed:
    grpc[codegen,core]:x64-windows@1.51.1#3
  * re2:x64-windows@2024-04-01#1
  * upb[codegen,core]:x64-windows@2022-06-21#1
  * zlib:x64-windows@1.3.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\tiger\AppData\Local\vcpkg\archives in 167 us. Use --debug to see more details.
Installing 1/4 re2:x64-windows@2024-04-01#1...
Building re2:x64-windows@2024-04-01#1...
-- Downloading https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1 -> 9ebe4a22cad8a025b68a9594bdff3c047a111333.patch...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Disabling metrics because vcpkg.disable-metrics exists
[DEBUG] Trying to load bundleconfig from C:\temp\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\temp\dev\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1
[DEBUG] Trying to hash C:\temp\dev\vcpkg\downloads\9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.17812.part
[DEBUG] C:\temp\dev\vcpkg\downloads\9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.17812.part has hash 83c1a4cc4ddd6e1443f5201f7f00cf6a0729d0a0fb8fc5068c3d80766238d72f019f1fddaeffebcc2d4322a07daf2203214121cdda039b10a5f39214b9fa8647
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1
File: C:\temp\dev\vcpkg\downloads\9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.17812.part
Expected hash: 167a0153bf24e77db2b8555a7d6391acf740dc4720a71e6ce19a3533c7e0a49923d9584ff32544a454837a25eedace00cb2ef9ddbf4250deb5f2c5aeda04ac26
Actual hash: 83c1a4cc4ddd6e1443f5201f7f00cf6a0729d0a0fb8fc5068c3d80766238d72f019f1fddaeffebcc2d4322a07daf2203214121cdda039b10a5f39214b9fa8647
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1031):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 107us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 427 ms (427168us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.


Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/re2/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:175 (include)


error: building re2:x64-windows failed with: BUILD_FAILED
Elapsed time to handle re2:x64-windows: 491 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+re2
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[re2]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Ftemp%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by WangWeiLin-MV** [comment] 2024-04-12 05:40
Duplicate of #38146

**Closed by WangWeiLin-MV** 2024-04-12 05:40 UTC
Labels: category:port-bug
