### ISSUE TITLE
[7-Zip] update to 21.06

### ISSUE THREAD

**Issue by Tarek-Hasan** [microsoft/vcpkg#22063] opened 2021-12-17 10:39 UTC
Library name: 7-Zip

New version number: 21.06

Other information that may be useful (release notes, etc...)
Released on 24 Nov 2021
https://www.7-zip.org/download.html
mirror: https://sourceforge.net/projects/sevenzip/files/7-Zip/21.06/

**Comment by xavier2k6** [comment] 2021-12-17 11:23
Duplicate of #21567

**Comment by Tarek-Hasan** [comment] 2021-12-17 18:15
Feel free to delete this issue.

**Comment by PhoebeHui** [comment] 2021-12-20 06:22
Closing in favor of https://github.com/microsoft/vcpkg/issues/21567.

**Closed by PhoebeHui** 2021-12-20 06:22 UTC
Labels: category:port-update
