### ISSUE TITLE
[tensorflow] Build error

### ISSUE THREAD

**Issue by huwqchn** [microsoft/vcpkg#26609] opened 2022-08-31 10:11 UTC
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=0 --terminal_columns=80
INFO: Reading rc options for 'build' from d:\tools\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=D:/tools/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python.exe
INFO: Reading rc options for 'build' from d:\tools\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  'build' options: --define framework_shared_object=true --java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --host_java_toolchain=@tf_toolchains//toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --define=with_xla_support=true --config=short_logs --config=v2 --define=no_aws_support=true --define=no_hdfs_support=true
INFO: Reading rc options for 'build' from d:\tools\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=D:/tools/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python3.exe --action_env PYTHON_LIB_PATH=D:/tools/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/lib/python3.8/site-packages --python_path=D:/tools/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python3.exe --define=with_xla_support=false --copt=/d2ReducedOptimizeHugeFunctions --host_copt=/d2ReducedOptimizeHugeFunctions --define=override_eigen_strong_inline=true
INFO: Reading rc options for 'build' from d:\tools\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc:
  'build' options: --deleted_packages=tensorflow/compiler/mlir/tfrt,tensorflow/compiler/mlir/tfrt/benchmarks,tensorflow/compiler/mlir/tfrt/jit/python_binding,tensorflow/compiler/mlir/tfrt/jit/transforms,tensorflow/compiler/mlir/tfrt/python_tests,tensorflow/compiler/mlir/tfrt/tests,tensorflow/compiler/mlir/tfrt/tests/saved_model,tensorflow/compiler/mlir/tfrt/transforms/lhlo_gpu_to_tfrt_gpu,tensorflow/core/runtime_fallback,tensorflow/core/runtime_fallback/conversion,tensorflow/core/runtime_fallback/kernel,tensorflow/core/runtime_fallback/opdefs,tensorflow/core/runtime_fallback/runtime,tensorflow/core/runtime_fallback/util,tensorflow/core/tfrt/common,tensorflow/core/tfrt/eager,tensorflow/core/tfrt/eager/backends/cpu,tensorflow/core/tfrt/eager/backends/gpu,tensorflow/core/tfrt/eager/core_runtime,tensorflow/core/tfrt/eager/cpp_tests/core_runtime,tensorflow/core/tfrt/fallback,tensorflow/core/tfrt/gpu,tensorflow/core/tfrt/run_handler_thread_pool,tensorflow/core/tfrt/runtime,tensorflow/core/tfrt/saved_model,tensorflow/core/tfrt/saved_model/tests,tensorflow/core/tfrt/tpu,tensorflow/core/tfrt/utils
INFO: Found applicable config definition build:short_logs in file d:\tools\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file d:\tools\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file d:\tools\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --copt=/W0 --copt=/D_USE_MATH_DEFINES --host_copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --copt=/experimental:preprocessor --host_copt=/experimental:preprocessor --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --verbose_failures --features=compiler_param_file --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file d:\tools\vcpkg\buildtrees\tensorflow\x64-windows-dbg\.bazelrc: --define framework_shared_object=false
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: 2 targets (1 packages loaded, 0 targets configured)
Analyzing: 2 targets (27 packages loaded, 133 targets configured)
INFO: Repository local_config_def_file_filter instantiated at:
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/WORKSPACE:15:14: in <toplevel>
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace2.bzl:1079:19: in workspace
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace2.bzl:105:30: in _tf_toolchains
Repository rule def_file_filter_configure defined at:
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl:55:44: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_def_file_filter':
   Traceback (most recent call last):
	File "D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl", line 37, column 28, in _def_file_filter_configure_impl
		auto_configure_fail("Couldn't find undname.exe under %s, please check your VC installation and set BAZEL_VC environment variable correctly." % vc_path)
	File "D:/tools/vcpkg/buildtrees/tensorflow/.bzl/46huyqcu/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: Error fetching repository: Traceback (most recent call last):
	File "D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/tools/def_file_filter/def_file_filter_configure.bzl", line 37, column 28, in _def_file_filter_configure_impl
		auto_configure_fail("Couldn't find undname.exe under %s, please check your VC installation and set BAZEL_VC environment variable correctly." % vc_path)
	File "D:/tools/vcpkg/buildtrees/tensorflow/.bzl/46huyqcu/external/bazel_tools/tools/cpp/lib_cc_configure.bzl", line 112, column 9, in auto_configure_fail
		fail("\n%sAuto-Configuration Error:%s %s\n" % (red, no_color, msg))
Error in fail: 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
INFO: Repository com_google_absl instantiated at:
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/WORKSPACE:15:14: in <toplevel>
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace2.bzl:1082:28: in workspace
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace2.bzl:58:9: in _initialize_third_party
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/absl/workspace.bzl:14:20: in repo
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/repo.bzl:113:21: in tf_http_archive
Repository rule _tf_http_archive defined at:
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/third_party/repo.bzl:66:35: in <toplevel>
Analyzing: 2 targets (65 packages loaded, 198 targets configured)
INFO: Repository rules_proto instantiated at:
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/WORKSPACE:23:14: in <toplevel>
  D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/workspace0.bzl:120:20: in workspace
  D:/tools/vcpkg/buildtrees/tensorflow/.bzl/46huyqcu/external/com_github_grpc_grpc/bazel/grpc_extra_deps.bzl:29:18: in grpc_extra_deps
  D:/tools/vcpkg/buildtrees/tensorflow/.bzl/46huyqcu/external/com_google_protobuf/protobuf_deps.bzl:42:21: in protobuf_deps
Repository rule http_archive defined at:
  D:/tools/vcpkg/buildtrees/tensorflow/.bzl/46huyqcu/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
ERROR: D:/tools/vcpkg/buildtrees/tensorflow/x64-windows-dbg/tensorflow/BUILD:1102:8: //tensorflow:tensorflow_filtered_def_file depends on @local_config_def_file_filter//:def_file_filter in repository @local_config_def_file_filter which failed to fetch. no such package '@local_config_def_file_filter//': 
Auto-Configuration Error: Couldn't find undname.exe under C:\Program Files\Microsoft Visual Studio\2022\Community\VC, please check your VC installation and set BAZEL_VC environment variable correctly.
ERROR: Analysis of target '//tensorflow:tensorflow.dll' failed; build aborted: Analysis failed
INFO: Elapsed time: 14.738s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (65 packages loaded, 198 targets configured)
FAILED: Build did NOT complete successfully (65 packages loaded, 198 targets configured)

**Comment by LilyWangLL** [comment] 2022-09-02 10:12
Closed as duplicate of #21246. This issue will fixed by #24861.

**Closed by LilyWangLL** 2022-09-02 10:12 UTC
Labels: category:port-bug
