### ISSUE TITLE
Let `vcpkg install` check only the relevant ports instead of all

### ISSUE THREAD

**Issue by playgithub** [microsoft/vcpkg#24302] opened 2022-04-21 11:36 UTC
****

**Problem**

e.g.
1. private port "libabc" in git branch `branch-abc`
2. `git switch branch-abc`
3. `vcpkg install libabc`
4. `git switch master`
5. `vcpkg install zlib`, error  as below
    ```sh
    Computing installation plan...
    Error: while loading libabc:
    The port directory (<vcpkg-root>\ports\libabc) does not exist
    Error: failed to load port from <vcpkg-root>\ports\libabc
    note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.
    ```

**Proposed solution**
`vcpkg install` checks only relevant ports.

If `vcpkg install` check all ports, it'll be less convenient when do PR in a new branch, because when testing, the same error above will occur. There are solutions, but not necessary when `vcpkg install` check only relevant ports.

**Additional context**
https://github.com/microsoft/vcpkg/discussions/24259

**Comment by Neumann-A** [comment] 2022-04-21 13:11
this is a duplicate of another issue. Unable to find it currently.

**Comment by JackBoosY** [comment] 2022-04-22 02:43
The reason for this issue is that we need to first analyze all ports and build a dependency graph, and judge the installation order according to the graph.

**Comment by dg0yt** [comment] 2022-04-22 03:35
> The reason for this issue is that we need to first analyze all ports and build a dependency graph, and judge the installation order according to the graph.

Right, vcpkg must at least know when to remove an orphan port due to removed dependencies. And without the build recipe, the port would also block upgrades.
But at least some operations could continue. Installing an independent port might work as well as does removing the orphan port.

**Comment by playgithub** [comment] 2022-04-22 04:05
> The reason for this issue is that we need to first analyze all ports and build a dependency graph, and judge the installation order according to the graph.

What about ignore the missing libs when build the dependency graph?

**Comment by Neumann-A** [comment] 2022-04-22 08:02
Feel free to comment on https://github.com/microsoft/vcpkg-tool/pull/516

**Comment by Neumann-A** [comment] 2022-04-22 09:18
duplicate to #15836

**Closed** 2022-04-22 09:27 UTC
Labels: category:vcpkg-feature
