### ISSUE TITLE
[openimageio] build failure

### ISSUE THREAD

**Issue by kangstarr** [microsoft/vcpkg#8812] opened 2019-10-30 09:57 UTC
**Host Environment**
- OS: Windows 10
- Compiler: VS2019Pro

**To Reproduce**
`./vcpkg.exe install openimageio`

**Failure logs** 
The following packages will be built and installed:
    openimageio[core]:x64-windows
Starting package 1/1: openimageio:x64-windows
Building package openimageio[core]:x64-windows...
-- Using cached C:/vcpkg/downloads/OpenImageIO-oiio-ad1ab61a56c63d770e4beb335efe8b1f1a9e36cd.tar.gz
-- Using source at C:/vcpkg/buildtrees/openimageio/src/1f1a9e36cd-9b16117fec
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
    Working Directory: C:/vcpkg/buildtrees/openimageio/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\openimageio\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/openimageio/portfile.cmake:66 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package openimageio:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openimageio:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
- [install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3788101/install-x64-windows-dbg-out.log)

**Additional context**
None

**Comment by ChaoJia** [comment] 2019-10-30 22:49
This is the same issue as https://github.com/microsoft/vcpkg/issues/8344. It should be a [Visual studio 2019 issue](https://developercommunity.visualstudio.com/content/problem/749973/vcpkgopenimageio-use-of-undefined-type-after-upgra.html).  OIIO cannot be built with VS 16.3+. For now the solution is to uninstall VS, then either install vs 16.2.x or [stick to the baseline ](https://docs.microsoft.com/en-us/visualstudio/install/update-servicing-baseline?view=vs-2019). If it is not an urgent issue for you, please keep your VS up to date, and let me know when the issue is fixed in a newer version. Then I'll update my VS 😈

**Comment by JackBoosY** [comment] 2019-10-31 01:38
I can build it successfully on Visual Studio 2017.

**Comment by timautry** [comment] 2019-10-31 17:59
@ChaoJia I gave the "-T v141" toolset specification in the portfile.cmake file a try, but in the
[Uploading config-x64-windows-out.log…] it shows Ninja does not support toolset specification, but toolset v141 was specified. :( 
It was worth a shot, I really appreciate your suggestion... :)

Thanks and have a wonderful day!!!

**Comment by ChaoJia** [comment] 2019-10-31 19:11
@timautry then you can comment out `PREFER_NINJA`, I think this time it will work, but please let me know if it does not 😄 

```
vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    # PREFER_NINJA
    OPTIONS ${FEATURE_OPTIONS}
        -T v141
        -DOIIO_BUILD_TOOLS=OFF
    ...
```

**Comment by timautry** [comment] 2019-10-31 23:51
Neither of the above options worked. I do have a workable version under VS2017 I can use if needed until the next version of OIIO is released with a fix for VS2019 and toolset 14.2.

**Comment by ChaoJia** [comment] 2019-11-01 08:12
@timautry that's quite bizarre. The second solution is guaranteed to work, provided that toolset v141 has been installed, and the modifications made in the portfile.cmake have been undone.

**Comment by LilyWangL** [comment] 2020-03-23 10:00
@kangstarr Thanks for posting this issue. Does the issue still occur? I installed it successfully with Visual Studio 2019 and VCPKG latest source.

**Comment by LilyWangL** [comment] 2020-06-17 08:00
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Closed by LilyWangL** 2020-06-17 08:00 UTC
Labels: category:port-bug
