### ISSUE TITLE
[fontconfig] build failure

### ISSUE THREAD

**Issue by ventsin** [microsoft/vcpkg#15490] opened 2021-01-07 04:32 UTC
**Host Environment**
- OS: Linux Manjaro
- Compiler: g++

**To Reproduce**
`./vcpkg install fontconfig`

**Failure logs** 
```--- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:108 (message):
    Command failed: /usr/bin/autoreconf -vfi
    Working Directory: /home/venny/projects/vctest/vcpkg/buildtrees/fontconfig/src/75c13b2421-4651fd65ce.clean/
    Error code: 1
    See logs for more information:
      /home/venny/projects/vctest/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-out.log
      /home/venny/projects/vctest/vcpkg/buildtrees/fontconfig/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:536 (vcpkg_execute_required_process)
  ports/fontconfig/portfile.cmake:25 (vcpkg_configure_make)
  scripts/ports.cmake:136 (include)


Error: Building package fontconfig:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: fontconfig:x64-linux
  Vcpkg version: 2020.11.12-unknownhash
```

The mentioned log files are attached.
[autoconf-x64-linux-err.log](https://github.com/microsoft/vcpkg/files/5779601/autoconf-x64-linux-err.log)
[autoconf-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/5779602/autoconf-x64-linux-out.log)

**Additional context**
I tried installing the nana package, but it failed at fontconfig.
Installing fontconfig directly renders the same result.

**Comment by NancyLi1013** [comment] 2021-01-07 06:51
Hi @ventsin 

Thanks for posting this issue.

```
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal -I m4 --output=aclocal.m4t
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
```
Could you please try to install `automake `to rebuild this?

**Comment by ventsin** [comment] 2021-01-07 08:07
Thanks for the quick reply. With `automake` I managed to complete the install but I haven't been able to build with this package.
This is the output from make:
```
Scanning dependencies of target calc
[ 50%] Building CXX object CMakeFiles/calc.dir/calc.cpp.o
[100%] Linking CXX executable calc
/usr/bin/ld: ../../vcpkg/installed/x64-linux/lib/libfontconfig.a(fccache.o): undefined reference to symbol 'uuid_generate_random@@UUID_1.0'
/usr/bin/ld: /usr/lib/libuuid.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/calc.dir/build.make:127: calc] Error 1
make[1]: *** [CMakeFiles/Makefile2:95: CMakeFiles/calc.dir/all] Error 2
make: *** [Makefile:103: all] Error 2
```

It was generated with this CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.0)
set(CMAKE_TOOLCHAIN_FILE ./vcpkg/scripts/buildsystems/vcpkg.cmake)

project(calc)

add_executable(${PROJECT_NAME} calc.cpp)

find_package(unofficial-nana CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE unofficial::nana::nana)
```

I'm by no means an experienced CMake user, but this CMakeLists.txt worked perfectly in Visual Studio on my Windows machine, so I don't think it's the problem. But then again, I wouldn't know.

**Comment by NancyLi1013** [comment] 2021-01-07 09:43
Could you please also provide the content in calc.cpp?

I can build this successfully.
```
Scanning dependencies of target calc
[ 50%] Building CXX object CMakeFiles/calc.dir/calc.cpp.o
[100%] Linking CXX executable calc
[100%] Built target calc
```

**Comment by NancyLi1013** [comment] 2021-01-07 09:54
You may need to add `find_library(UUID_LIBRARIES NAMES uuid libuuid) `to your CMakeLists.txt. Since `libuuid `is required by `fontconfig `on linux platform.

**Comment by ventsin** [comment] 2021-01-07 10:09
calc.cpp for now is just a small nana test:
```
#include <nana/gui.hpp>

int main()
{
    nana::form fm;
    fm.caption("build worked!");
    fm.show();
    
    nana::exec();
    return 0;
}
```
I tried adding `uuid` as you suggested but the error remains the same. ;(

**Comment by Neumann-A** [comment] 2021-01-07 23:09
#15144 should close your linkage issue

**Comment by NancyLi1013** [comment] 2021-01-11 09:28
@ventsin 

Please update vcpkg to the latest version to rebuild this.

**Comment by ventsin** [comment] 2021-01-11 21:28
Thank you, again.
Unfortunately, the issue seems to persist.

I completely erased my vcpkg and build directories for a fresh bootstrap and install, but I still have the same error when building.
Are there any other logs I could upload to help diagnose the issue?

**Comment by Neumann-A** [comment] 2021-01-11 22:40
@ventsin did you delete your cmakecache?

**Comment by ventsin** [comment] 2021-01-12 00:56
@Neumann-A Yes, along with everything else in the build directory.

**Comment by Neumann-A** [comment] 2021-01-12 07:52
Ah i see the issue is in the nana port itself. The vcpkg vendored cmakelists.txt does:
```
  find_library(FONTCONFIG_LIB NAMES fontconfig)
  target_link_libraries(nana PUBLIC ${FONTCONFIG_LIB})
```
which is of course insufficient. 
It should do:
```
  find_package(Fontconfig)
  target_link_libraries(nana PUBLIC Fontconfig::Fontconfig)
```
and also do a `find_dependency` call for Fontconfig in the config.cmake.

**Comment by NancyLi1013** [comment] 2021-01-12 08:40
@Neumann-A 

Thanks for your investigation and solution.

@ventsin 

Could you please help confirm if this can work fine for you?

**Comment by ventsin** [comment] 2021-01-12 21:55
It works perfectly!
![image](https://user-images.githubusercontent.com/11967147/104378956-8639d080-5507-11eb-974b-ba922d384817.png)
Thanks a lot.

**Comment by JackBoosY** [comment] 2021-01-13 01:41
Please make sure this issue open until #15595 merged.

**Closed** 2021-01-13 04:14 UTC
Labels: category:port-bug
