### ISSUE TITLE
vcpkg upgrade error

### ISSUE THREAD

**Issue by kossiBlaise** [microsoft/vcpkg#38581] opened 2024-05-05 20:42 UTC
vcpkg upgrade does not even start

E:\vcpkg>vcpkg upgrade
error: The control or manifest file for boost-vcpkg-helpers could not be loaded
due to the following error. Please remove boost-vcpkg-helpers and try again.
E:\vcpkg\ports\boost-vcpkg-helpers: error: boost-vcpkg-helpers does not exist

**Comment by kossiBlaise** [comment] 2024-05-05 20:47
boost-vcpkg-helpers does not exist sphysically in e;\vcpkg\ports

**Comment by Neumann-A** [comment] 2024-05-05 21:30
duplicate of #38487

**Closed** 2024-05-06 09:10 UTC
Labels: category:port-bug
