### ISSUE TITLE
[<assimp>] build failure

### ISSUE THREAD

**Issue by MicSm** [microsoft/vcpkg#13216] opened 2020-08-29 11:17 UTC
**Host Environment**
- OS: Windows 7 x64
- Compiler: VS 2017

**To Reproduce**
`./vcpkg install assimp

**Failure logs** 
-- Using cached D:/Program Files/vcpkg/downloads/zlib1211.tar.gz
-- Cleaning sources at D:/Program Files/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Program Files/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at D:/Program Files/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using cached D:/Program Files/vcpkg/downloads/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz
-- Using cached D:/Program Files/vcpkg/downloads/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst
-- Fixing pkgconfig file: D:/Program Files/vcpkg/packages/zlib_x86-windows/lib/pkgconfig/zlib.pc
-- CHECK_LIB_zlib_RELEASE:CHECK_LIB_zlib_RELEASE-NOTFOUND
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:232 (message):
  Library "zlib" was not found! If it is a system library use the
  SYSTEM_LIBRARIES parameter for the vcpkg_fixup_pkgconfig call! Otherwise,
  correct the *.pc file
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:298 (vcpkg_fixup_pkgconfig_check_files)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

**Additional context**
Package: zlib: x86-windows
Vcpkg version: 2020.06.15-nohash

**Comment by Hoikas** [comment] 2020-08-30 19:05
This is caused by a bug in vcpkg with paths containing spaces - fixed by #13126. In the meantime, you can work around it by cloning vcpkg to a path without a space, eg `C:\vcpkg`.

**Comment by JonLiu1993** [comment] 2020-09-03 09:20
Hi @MicSm ,
According to @Hoikas ’s suggestion, you can verify if it is feasible？

**Comment by MicSm** [comment] 2020-09-04 11:32
> Hi @MicSm ,
> According to @Hoikas ’s suggestion, you can verify if it is feasible？

Hi @JonLiu1993 ,

Right now I made a full reinstall of vcpkg, and it seems there is another one error as well 
(after executing vcpkg.exe install assimp):

-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Extracting source D:/vcpkg/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Using source at D:/vcpkg/buildtrees/zlib/src/1.2.11-63309e48e5.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz... Failed. Status: 35;"SSL connect error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:178 (message):
      
      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:403 (vcpkg_download_distfile)
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:270 (vcpkg_find_acquire_program)
  ports/zlib/portfile.cmake:48 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:79 (include)

**Comment by MicSm** [comment] 2020-09-04 11:36
@JonLiu1993 As I see, my vcpkg installation was compiled with VS 2019 compiler and it is possible to download directly from browser that archive: https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz

**Comment by JonLiu1993** [comment] 2020-09-07 09:25
Hi @MicSm ,
I feel your problem has been solved, can I close the issue?

**Comment by MicSm** [comment] 2020-09-07 10:47
> Hi @MicSm ,
> I feel your problem has been solved, can I close the issue?

Yes, but need to fix another one from my above message about when vcpkg tries to download https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-1-any.pkg.tar.xz and fails

**Comment by PhoebeHui** [comment] 2020-12-31 07:33
@MicSm, this issue has been fixed, please get latest source and try again.

**Closed by PhoebeHui** 2020-12-31 07:33 UTC
Labels: category:tool-update
