### ISSUE TITLE
[HDF5] build failure

### ISSUE THREAD

**Issue by ndl303** [microsoft/vcpkg#23421] opened 2022-03-07 21:37 UTC
**Host Environment**
- OS: [e.g. Window x64-windows.]
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install hdf5`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Not sure, but is CMake failing to find perl the cause of the error. I was unable to install any perl interfaces with vcpkg. I used to be able to install HDF5 on Windows machines  with `vcpkg` as I have several machines that have installed the package in the last few months.  I was just setting up a new system and hit the problem.

[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/8200990/config-x64-windows-dbg-err.log)
[console.txt](https://github.com/microsoft/vcpkg/files/8200983/console.txt)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8200984/config-x64-windows-dbg-out.log)

**Comment by FrankXie05** [comment] 2022-03-08 02:02
Thanks for posting this issue. Sorry, I didn't reproduce it locally, 
Could you please make sure you are using the latest `vcpkg`, delete the local cache and try again？ :)

**Comment by ndl303** [comment] 2022-03-08 02:31
Hi Frank, thanks for the quick response. I’ll take a look tomorrow but I installed vcpkg from GitHub this afternoon so it’s unlikely to be too far out of date. Maybe your version is too old as I have HDF5 working on older installations pf vcpkg.

Thanks

**Comment by FrankXie05** [comment] 2022-03-09 06:25
@ndl303 Thanks for the log you provided, it seems to be the same problem as this #21696, could you please try this solution(https://github.com/cyang-kth/fmm/issues/227)?

**Comment by FrankXie05** [comment] 2022-03-16 05:57
@ndl303 Is still work for this issue? :)

**Comment by FrankXie05** [comment] 2022-03-17 02:52
Since this issue can't be reproduced, I am closing this issue for now. If you have any question, please open a new issue.

**Closed by FrankXie05** 2022-03-17 02:52 UTC
Labels: requires:repro

**Comment by saulthu** [comment] 2022-04-04 05:45
Exact same problem here, same symptoms. Windows 10 using x64-windows, Visual Studio 2019, happens whether running `./vcpkg install hdf5` or using a manifest file. This packages was working, not sure what the exact version was, but I just updated vcpkg and now this will not build, errors being with popen/pclose during linking of ConversionTests.c.obj.

**Comment by saulthu** [comment] 2022-04-04 06:41
Uninstalling VS2019 and installing VS2022 fixed the problem. Sad that this was forced in this case.
