### ISSUE TITLE
[angle] build failure

### ISSUE THREAD

**Issue by how0723** [microsoft/vcpkg#10489] opened 2020-03-20 14:56 UTC
**Host Environment**
- OS: linux/debian x64
- Compiler: gcc 8.3

**To Reproduce**
`root@unique-gig-2:/home/vcpkg-2020.01# ./vcpkg install angle
The following packages will be built and installed:
    angle[core]:x64-linux
  * egl-registry[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: egl-registry:x64-linux
Building package egl-registry[core]:x64-linux...
-- Downloading https://github.com/KhronosGroup/EGL-Registry/archive/598f20e3b7b7eec3e8d8a83e64b9592a21c55bb6.tar.gz...
-- Extracting source /home/vcpkg-2020.01/downloads/KhronosGroup-EGL-Registry-598f20e3b7b7eec3e8d8a83e64b9592a21c55bb6.tar.gz
-- Using source at /home/vcpkg-2020.01/buildtrees/egl-registry/src/2a21c55bb6-51d4798b6f
-- Installing: /home/vcpkg-2020.01/packages/egl-registry_x64-linux/share/egl-registry/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package egl-registry[core]:x64-linux... done
Installing package egl-registry[core]:x64-linux...
Installing package egl-registry[core]:x64-linux... done
Elapsed time for package egl-registry:x64-linux: 979 ms
Starting package 2/2: angle:x64-linux
Building package angle[core]:x64-linux...
-- Note: angle only supports dynamic library linkage. Building dynamic library.
CMake Warning at ports/angle/portfile.cmake:4 (message):
  Building with a gcc version less than 6.1 is not supported.
Call Stack (most recent call first):
  scripts/ports.cmake:94 (include)

-- Downloading https://github.com/google/angle/archive/1fdf6ca5141d8e349e875eab6e51d93d929a7f0e.tar.gz...
-- Extracting source /home/vcpkg-2020.01/downloads/google-angle-1fdf6ca5141d8e349e875eab6e51d93d929a7f0e.tar.gz
-- Applying patch 001-fix-uwp.patch
-- Applying patch 002-fix-builder-error.patch
-- Using source at /home/vcpkg-2020.01/buildtrees/angle/src/3d929a7f0e-ac85ee4a0e
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: /home/vcpkg-2020.01/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v
    Working Directory: /home/vcpkg-2020.01/buildtrees/angle/x64-linux-dbg
    See logs for more information:
      /home/vcpkg-2020.01/buildtrees/angle/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/angle/portfile.cmake:40 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package angle:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: angle:x64-linux
  Vcpkg version: 2020.01.17-unknownhash

Additionally, attach any relevant sections from the log files above.`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by linquize** [comment] 2020-03-20 15:58
Seems Duplicate of #10381

**Comment by NancyLi1013** [comment] 2020-03-23 01:54
Hi @how0723 
Thanks for posting this issue.
Could you please help provide the failure log?

**Comment by NancyLi1013** [comment] 2020-03-24 05:42
Also `angle `has been updated to the latest version.
Please try to update vcpkg and build it agian. In addition, please help confim if this is similar to #10381.

**Comment by NancyLi1013** [comment] 2020-04-03 03:22
Close this issue due to no response.
 Please feel free to reopen this if this is still a problem for you and you can confirm this is not the same issue as #10381.

**Closed by NancyLi1013** 2020-04-03 03:22 UTC
Labels: needs-repro
