### ISSUE TITLE
[qtapplicationmanager] x64-windows pipeline test failure

### ISSUE THREAD

**Issue by JackBoosY** [microsoft/vcpkg#23680] opened 2022-03-21 06:54 UTC
Failure log:
```
FAILED: bin/appman-dumpqmltypes.exe src/tools/dumpqmltypes/qmltypes D:/buildtrees/qtapplicationmanager/x64-windows-dbg/src/tools/dumpqmltypes/qmltypes 
cmd.exe /C "cd . && D:\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\tools\dumpqmltypes\CMakeFiles\appman-dumpqmltypes.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1431~1.311\bin\Hostx64\x64\link.exe  @CMakeFiles\appman-dumpqmltypes.rsp  /out:bin\appman-dumpqmltypes.exe /implib:src\tools\dumpqmltypes\appman-dumpqmltypes.lib /pdb:bin\appman-dumpqmltypes.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console   -DYNAMICBASE -NXCOMPAT  && cmd.exe /C "cd /D D:\buildtrees\qtapplicationmanager\x64-windows-dbg\src\tools\dumpqmltypes && D:\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe -E env "PATH=D:\buildtrees\qtapplicationmanager\x64-windows-dbg\src\tools\dumpqmltypes\\;D:\packages\qtapplicationmanager_x64-windows\debug\bin\\;D:\installed\x64-windows\bin\\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VC\VCPackages\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\Roslyn\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Team Tools\Performance Tools\x64\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Team Tools\Performance Tools\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\\;C:\Program Files (x86)\HTML Help Workshop\;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\\x64\;C:\Program Files (x86)\Windows Kits\10\bin\\x64\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\\MSBuild\Current\Bin\amd64\;C:\Windows\Microsoft.NET\Framework64\v4.0.30319\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\\;C:\Program Files\PowerShell\7\;C:\Windows\system32\;C:\Windows\;C:\Windows\system32\Wbem\;C:\Windows\system32\WindowsPowerShell\v1.0\\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VC\Linux\bin\ConnectionManagerExe\;D:/downloads/tools/perl/5.32.1.1/perl/bin\;D:/downloads/tools/python/python-3.10.2-x64\;D:/downloads/tools/ninja/1.10.2-windows\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.31.31103\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Team Tools\Performance Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\HTML Help Workshop;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\;C:\Program Files\PowerShell\7;C:\Windows\system32;C:\Windows;C:\Windows\system32\Wbem;C:\Windows\system32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\Llvm\x64\bin;C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\VC\Linux\bin\ConnectionManagerExe;D:/downloads/tools/perl/5.32.1.1/perl/bin;D:/downloads/tools/python/python-3.10.2-x64;D:/downloads/tools/ninja/1.10.2-windows" D:/buildtrees/qtapplicationmanager/x64-windows-dbg/bin/appman-dumpqmltypes D:/buildtrees/qtapplicationmanager/x64-windows-dbg/src/tools/dumpqmltypes/qmltypes""
Exit code 0xc0000135

[254/255] cmd.exe /C "cd . && D:\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe -E vs_link_exe --intdir=src\tools\testrunner\CMakeFiles\appman-qmltestrunner.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MICROS~1\2022\ENTERP~1\VC\Tools\MSVC\1431~1.311\bin\Hostx64\x64\link.exe  src\tools\testrunner\CMakeFiles\appman-qmltestrunner.dir\appman-qmltestrunner_autogen\mocs_compilation.cpp.obj src\tools\testrunner\CMakeFiles\appman-qmltestrunner.dir\appman-qmltestrunner_resource.rc.res src\tools\testrunner\CMakeFiles\appman-qmltestrunner.dir\__\appman\appman.cpp.obj src\tools\testrunner\CMakeFiles\appman-qmltestrunner.dir\amtest.cpp.obj src\tools\testrunner\CMakeFiles\appman-qmltestrunner.dir\testrunner.cpp.obj src\tools\testrunner\CMakeFiles\appman-qmltestrunner.dir\.rcc\qrc_build-config.cpp.obj  /out:bin\appman-qmltestrunner.exe /implib:src\tools\testrunner\appman-qmltestrunner.lib /pdb:bin\appman-qmltestrunner.pdb /version:0.0 /machine:x64 /nologo    /debug /INCREMENTAL /subsystem:console   -DYNAMICBASE -NXCOMPAT  lib\Qt6AppManMaind.lib  D:\installed\x64-windows\debug\lib\Qt6QuickTestd.lib  D:\installed\x64-windows\debug\lib\Qt6Testd.lib  lib\Qt6AppManSharedMaind.lib  D:\installed\x64-windows\debug\lib\Qt6Widgetsd.lib  lib\Qt6AppManDBusd.lib  lib\Qt6AppManWindowd.lib  lib\Qt6AppManManagerd.lib  lib\Qt6AppManIntentServerd.lib  lib\Qt6AppManNotificationd.lib  D:\installed\x64-windows\debug\lib\Qt6Quickd.lib  D:\installed\x64-windows\debug\lib\Qt6OpenGLd.lib  D:\installed\x64-windows\debug\lib\Qt6QmlModelsd.lib  lib\Qt6AppManIntentClientd.lib  lib\Qt6AppManPluginInterfacesd.lib  lib\Qt6AppManCryptod.lib  advapi32.lib  crypt32.lib  lib\Qt6AppManMonitord.lib  D:\installed\x64-windows\debug\lib\Qt6Guid.lib  d3d11.lib  dxgi.lib  dxguid.lib  lib\Qt6AppManPackaged.lib  lib\Qt6AppManApplicationd.lib  lib\Qt6AppManCommond.lib  D:\installed\x64-windows\debug\lib\Qt6DBusd.lib  D:\installed\x64-windows\debug\lib\Qt6Concurrentd.lib  D:\installed\x64-windows\debug\lib\Qt6Qmld.lib  D:\installed\x64-windows\debug\lib\Qt6Networkd.lib  D:\installed\x64-windows\debug\lib\Qt6Cored.lib  mpr.lib  userenv.lib  ws2_32.lib  shell32.lib  lib\Qt6BundledStackwalkerd.lib  D:\installed\x64-windows\debug\lib\yaml.lib  D:\installed\x64-windows\debug\lib\archive.lib  user32.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib && cd ."
ninja: build stopped: subcommand failed.
```

It seems that the Visual Studio 2022 installation has some bugs in our pipeline image.

Related: https://github.com/microsoft/vcpkg/pull/22516 https://github.com/microsoft/vcpkg/pull/22878 https://github.com/microsoft/vcpkg/pull/23259

**Comment by Thomas1664** [comment] 2022-03-21 08:04
Duplicate of #23613

**Closed** 2022-03-21 08:41 UTC
Labels: category:infrastructure
