### ISSUE TITLE
[boost] update to 1.74.0

### ISSUE THREAD

**Issue by Blakjak88** [microsoft/vcpkg#13878] opened 2020-10-05 03:08 UTC
Library name:   BOOST

New version number:   1.74.0

Other information that may be useful (release notes, etc...)

**Comment by kelleyma49** [comment] 2020-10-08 21:18
duplicate of https://github.com/microsoft/vcpkg/issues/13033

**Comment by PhoebeHui** [comment] 2020-10-09 03:25
Thanks kelleyma49!

**Closed by PhoebeHui** 2020-10-09 03:25 UTC
Labels: category:port-update
