### ISSUE TITLE
How do I specify compiler type ?

### ISSUE THREAD

**Issue by Mr-Leshiy** [microsoft/vcpkg#16444] opened 2021-02-27 08:59 UTC
Is it possible to specify the compiler type for package that I want to build and download throw 'install' command. 
Here is the case where it should be necessary https://github.com/google/googletest/blob/master/googletest/README.md#incorporating-into-an-existing-cmake-project.

**Comment by MrROBUST** [comment] 2021-02-28 19:22
Likely a duplicate of #16368

**Comment by JonLiu1993** [comment] 2021-03-01 02:10
Thanks for posting this issue,Duplicate of #16368

**Closed by JonLiu1993** 2021-03-01 02:10 UTC
Labels: category:question
