### ISSUE TITLE
Can't find glfw3

### ISSUE THREAD

**Issue by rgozim** [microsoft/vcpkg#6697] opened 2019-05-30 21:34 UTC
Tested on Windows and OSX

After `vcpkg install glfw3`, add `find_package(glfw3 CONFIG REQUIRED)` to CMakeLists.txt.

The following error is received:

```
CMake Error at CMakeLists.txt:12 (find_package):
  Could not find a package configuration file provided by "glfw3" with any of
  the following names:

    glfw3Config.cmake
    glfw3-config.cmake

  Add the installation prefix of "glfw3" to CMAKE_PREFIX_PATH or set
  "glfw3_DIR" to a directory containing one of the above files.  If "glfw3"
  provides a separate development package or SDK, be sure it has been
  installed.
```

**Comment by wangli28** [comment] 2019-05-31 02:27
Hi @rgozim, please try again as follows:

1. Add this code to file `CMakeSettings.json` on your Visual studio:
```
      "variables": [
        {
          "name": "CMAKE_TOOLCHAIN_FILE",
          "value": "VCPKG_PATH\\scripts\\buildsystems\\vcpkg.cmake"
        }
```

2. Modify the value of `generator` to `Visual Studio ...` and comment `"buildCommandArgs": "-v"` in file `CMakeSettings.json`.

Like this:
```
{
  "configurations": [
    {
      "name": "x86-Debug",
      "generator": "Visual Studio 15 2017",
      "configurationType": "Debug",
      "inheritEnvironments": [
        "msvc_x86"
      ],
      "buildRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\build\\${name}",
      "installRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\install\\${name}",
      "cmakeCommandArgs": "",
      //"buildCommandArgs": "-v",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "CMAKE_TOOLCHAIN_FILE",
          "value": "E:\\test\\vcpkg\\scripts\\buildsystems\\vcpkg.cmake"
        }
      ]
    }
  ]
}

```

**Comment by rgozim** [comment] 2019-05-31 08:30
Hi @wangli28 

Thanks for the reply.

I was using Visual Studio Code with the cmd arguments `-DCMAKE_TOOLCHAIN_FILE=[my vcpkg root]\scripts\buildsystems\vcpkg.cmake`

I also modified my CMakeLists.txt file to contain (before `project()`) to double check:

```
if(DEFINED ENV{VCPKG_ROOT} AND NOT DEFINED CMAKE_TOOLCHAIN_FILE)
  set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
      CACHE STRING "")
endif()
```

**Comment by PhoebeHui** [comment] 2019-09-18 09:52
The fix merged,  please get latest vcpkg and try again.

**Closed by PhoebeHui** 2019-09-18 09:52 UTC
Labels: port bug

**Comment by shash29-dev** [comment] 2021-08-21 11:05
Same issue. 
Visual Studio can't find GLFW.
Also,
find_package(glfw3 CONFIG REQUIRED) returns same error as in this thread.

Vcpkg package management program version 2021-08-12-85ab112d5ee102bc6eac8cdbbfdd173a71374e04

**Comment by PhoebeHui** [comment] 2021-08-23 09:02
@shash29-dev, could you please report a new issue instead?

**Comment by arsdever** [comment] 2023-12-27 10:55
With the commit https://github.com/PhoebeHui/vcpkg/commit/d73e5209e89308a61d4e08547db48b3ccfb6e8bd the patch for creating the config file is removed, so the issue is actual again.

**Comment by rafarafarafarafael** [comment] 2024-10-07 21:40
I'm also facing the same exact issue.

> [cmake] CMake Warning at external/vcpkg/scripts/buildsystems/vcpkg.cmake:274 (message):
[cmake]   Unable to determine target architecture.  Consider providing a value for
[cmake]   the CMAKE_OSX_ARCHITECTURES cache variable.  Continuing without vcpkg.
[cmake] Call Stack (most recent call first):
[cmake]   CMakeLists.txt:29 (include)
[cmake] 
[cmake] 
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error at CMakeLists.txt:32 (find_package):
[cmake]   Could not find a package configuration file provided by "glfw3" with any of
[cmake]   the following names:
[cmake] 
[cmake]     glfw3Config.cmake
[cmake]     glfw3-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "glfw3" to CMAKE_PREFIX_PATH or set
[cmake]   "glfw3_DIR" to a directory containing one of the above files.  If "glfw3"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
