### ISSUE TITLE
[liblzma]:Invalid URL

### ISSUE THREAD

**Issue by Rhenus-Re** [microsoft/vcpkg#37992] opened 2024-04-05 11:31 UTC
![%M}(UV3BGP2IEQZ0QVAJXF4](https://github.com/microsoft/vcpkg/assets/63099121/f5d9bde7-0c81-41f3-adb3-c70a52c51cfe)
https://[github.com/tukaani-project/xz/archive/v5.4.4.tar.gz](https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz)

**Comment by bansan85** [comment] 2024-04-05 15:05
Look at #37839

See temporary workaround at https://github.com/microsoft/vcpkg/issues/37962#issuecomment-2036223908

**Comment by LilyWangLL** [comment] 2024-04-07 07:14
Duplicate of https://github.com/microsoft/vcpkg/issues/37893.

**Closed by LilyWangLL** 2024-04-07 07:14 UTC
