### ISSUE TITLE
[gtest] Build error

### ISSUE THREAD

**Issue by eugeniomiro** [microsoft/vcpkg#30682] opened 2023-04-05 16:35 UTC
**Host Environment**

- Host: x64-linux (WSL Ubuntu 23.04 on Windows 11)
- Compiler: GNU 12.2.0
-    vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7
    vcpkg-scripts version: a7b6122f6 2023-02-24 (6 weeks ago)

- Host is a WSL Ubuntu distro running on a Windows 11 Pro Insider Preview Build 25330
- What I see is that pkg-config is running from a Strawberry Perl installation from Windows, which is not part of WSL nor Ubuntu. I tried installing pkg-config on Ubuntu but failed miserably.
- The repo where the code is stored is in a Windows drive mounted on /mnt/d as is with the WSL default configuration.

**To Reproduce**

`./vcpkg install `

**Failure logs**

```
-- Using cached google-googletest-v1.13.0.tar.gz.
-- Cleaning sources at /home/eugeniomiro/vcpkg/buildtrees/gtest/src/v1.13.0-0674f4ed11.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/eugeniomiro/vcpkg/downloads/google-googletest-v1.13.0.tar.gz
-- Applying patch 001-fix-UWP-death-test.patch
-- Applying patch clang-tidy-no-lint.patch
-- Applying patch fix-main-lib-path.patch
-- Using source at /home/eugeniomiro/vcpkg/buildtrees/gtest/src/v1.13.0-0674f4ed11.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest.cc
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest_main.cc
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest-all.cc
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest-assertion-result.cc
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest-death-test.cc
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest-filepath.cc
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest-internal-inl.h
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest-matchers.cc
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest-port.cc
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest-printers.cc
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest-test-part.cc
-- Installing: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/src/gtest-typed-test.cc
-- Fixing pkgconfig file: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/lib/pkgconfig/gmock.pc
-- Fixing pkgconfig file: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/lib/pkgconfig/gmock_main.pc
-- Fixing pkgconfig file: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/lib/pkgconfig/gtest.pc
-- Fixing pkgconfig file: /home/eugeniomiro/vcpkg/packages/gtest_x64-linux/lib/pkgconfig/gtest_main.pc
CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:135 (message):
  /mnt/c/Strawberry/perl/bin/pkg-config --exists gmock failed with error
  code: No such file or directory

      ENV{PKG_CONFIG_PATH}: "/home/eugeniomiro/vcpkg/packages/gtest_x64-linux/lib/pkgconfig:/home/eugeniomiro/vcpkg/packages/gtest_x64-linux/share/pkgconfig:/mnt/d/repos/server/vcpkg_installed/x64-linux/lib/pkgconfig:/mnt/d/repos/server/vcpkg_installed/x64-linux/share/pkgconfig"
      output: 
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:200 (z_vcpkg_fixup_pkgconfig_check_files)
  buildtrees/versioning_/versions/gtest/3f70f42192aacc5f8242c14d959d02a802f7559c/portfile.cmake:49 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:147 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "server",
  "version-string": "6.6.0",
  "builtin-baseline": "a7b6122f6b6504d16d96117336a0562693579933",
  "dependencies": [
    {
      "name": "boost-program-options",
      "version>=": "1.78.0"
    },
    {
      "name": "boost-filesystem",
      "version>=": "1.78.0"
    },
    {
      "name": "gtest",
      "version>=": "1.11.0"
    }
  ]
}

```
</details>

**Comment by JonLiu1993** [comment] 2023-04-06 08:08
@eugeniomiro, Thanks for posting this issue, I use your vcpkg.json file install gtest successfully in linux machine:
````
vzhli17@vzhli17001:~/vcpkg$ ./vcpkg install
Detecting compiler hash for triplet x64-linux...
All requested packages are currently installed.
Restored 0 package(s) from /home/vzhli17/.cache/vcpkg/archives in 1.8 us. Use --debug to see more details.
Total install time: 15.3 us
The package boost is compatible with built-in CMake targets:

    find_package(Boost REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE Boost::boost Boost::<lib1> Boost::<lib2> ...)

The package gtest is compatible with built-in CMake targets:

    enable_testing()

    find_package(GTest CONFIG REQUIRED)
    target_link_libraries(main PRIVATE GTest::gtest GTest::gtest_main GTest::gmock GTest::gmock_main)

    add_test(AllTestsInMain main)


```` 
I found that your issue is very similar to the error of this [issue](https://github.com/microsoft/vcpkg/issues/29872), so I will try to fix this error locally

**Comment by JonLiu1993** [comment] 2023-05-31 07:44
@eugeniomiro, sorry for reply you so late, could you please re-clone vcpkg with another disk and try again? Because of this error, I can't reproduce it locally, and I found an [issue ](https://github.com/microsoft/vcpkg/issues/27651)with the same error as yours, it is because of the path problem.

**Comment by eugeniomiro** [comment] 2023-05-31 12:30
@JonLiu1993, I figured my actual problem. I saw in the log I started with that pkg-config was taken from 
```
/mnt/c/Strawberry/perl/bin/pkg-config
```
which is not a Linux path but a Windows one, therefore the binary was not aware of WSL. Then I installed pkg-config using
```
sudo apt install pkg-config 
```
in my WSL environment, logged out, logged back in and it worked.

Thank you very much for taking the time to help me.

**Comment by dg0yt** [comment] 2023-05-31 19:19
How do these Windows paths get into the WSL vcpkg? It must be fixed if it is breaking builds. 

The failing script does `vcpkg_find_acquire_program(PKGCONFIG)` which will pick `pkg-config` from the `PATH` or raise an error.

@eugeniomiro Did you install the Linux tools mentioned in https://github.com/microsoft/vcpkg/#installing-linux-developer-tools?

**Comment by dg0yt** [comment] 2023-05-31 19:28
Hm, `build-essential` doesn't include `pkg-config`. Maybe it should add this package and other essentials (`autoconf` etc.).

**Comment by eugeniomiro** [comment] 2023-06-01 00:58
> How do these Windows paths get into the WSL vcpkg? It must be fixed if it is breaking builds.
> 
> The failing script does `vcpkg_find_acquire_program(PKGCONFIG)` which will pick `pkg-config` from the `PATH` or raise an error.
> 
> @eugeniomiro Did you install the Linux tools mentioned in https://github.com/microsoft/vcpkg/#installing-linux-developer-tools?

Hi @dg0yt. I installed everything as shown on [the **vcpkg** getting started page](https://vcpkg.io/en/getting-started.html) in the Linux tab.

**Comment by eugeniomiro** [comment] 2023-06-01 01:04
Regarding the build essentials tools, I was migrating a project which already had all those requirements, I only had to add **zip** by hand, which I did while I was migrating the CMake script.

**Comment by JonLiu1993** [comment] 2023-06-06 08:24
This problem has been solved, I will close this issue, if you have other problems, I will reopen it.

**Closed by JonLiu1993** 2023-06-06 08:24 UTC
Labels: requires:repro
