### ISSUE TITLE
build c-ares failed

### ISSUE THREAD

**Issue by shanfl** [Microsoft/vcpkg#2637] opened 2018-01-24 02:00 UTC
Package: c-ares:x86-windows
  Vcpkg version: 0.0.100-2017-12-15-76096c95f1d3cbb85779ccd78c30513eec32b517

**Comment by shanfl** [comment] 2018-01-24 02:00
The following packages will be built and installed:
    c-ares[core]:x86-windows
Starting package 1/1: c-ares:x86-windows
Building package c-ares:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/packages/c-ares_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/buildtrees/c-ares
-- CURRENT_PORT_DIR=C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/ports/c-ares/.
-- Using cached C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/downloads/c-ares-c-ares-cares-1_13_0.tar.gz
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Configuring x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:44 (message):
    Command failed: C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/downloads/cmake-3.10.0-win32-x86/bin/cmake.exe;C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/buildtrees/c-ares/src/c-ares-cares-1_13_0;-DCARES_STATIC=OFF;-DCARES_SHARED=ON;-DBUILD_SHARED_LIBS=ON;-DCMAKE_CXX_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP ;-DCMAKE_C_FLAGS= /DWIN32 /D_WINDOWS /W3 /utf-8 /MP ;-DVCPKG_TARGET_TRIPLET=x86-windows;-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON;-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON;-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE;-DCMAKE_VERBOSE_MAKEFILE=ON;-DVCPKG_APPLOCAL_DEPS=OFF;-DCMAKE_TOOLCHAIN_FILE=C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/scripts/buildsystems/vcpkg.cmake;-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON;-DCMAKE_CXX_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_C_FLAGS_RELEASE=/MD /O2 /Oi /Gy /DNDEBUG /Z7 ;-DCMAKE_SHARED_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-DCMAKE_EXE_LINKER_FLAGS_RELEASE=/DEBUG /INCREMENTAL:NO /OPT:REF /OPT:ICF ;-G;Ninja;-DCMAKE_BUILD_TYPE=Release;-DCMAKE_INSTALL_PREFIX=C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/packages/c-ares_x86-windows
    Working Directory: C:/Users/Dell-OptiPlex7040-sh/Homework/vcpkg/buildtrees/c-ares/x86-windows-rel
    See logs for more information:
      C:\Users\Dell-OptiPlex7040-sh\Homework\vcpkg\buildtrees\c-ares\config-x86-windows-rel-out.log
      C:\Users\Dell-OptiPlex7040-sh\Homework\vcpkg\buildtrees\c-ares\config-x86-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:205 (vcpkg_execute_required_process)
  ports/c-ares/portfile.cmake:19 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)


Error: Building package c-ares:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: c-ares:x86-windows
  Vcpkg version: 0.0.100-2017-12-15-76096c95f1d3cbb85779ccd78c30513eec32b517

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment] 2019-03-22 10:07
@shanfl ,thank you for posting this issue. This issue should be fixed now and I cannot reproduce it on my machine.
Please open a new issue if this is still a problem for you.

**Closed by NancyLi1013** 2019-03-22 10:07 UTC
Labels: needs-repro
