### ISSUE TITLE
magnum:x64-windows build failure

### ISSUE THREAD

**Issue by e9x** [microsoft/vcpkg#19261] opened 2021-07-31 03:32 UTC
**Host Environment**
- OS: Windows 11
- Compiler: Not relevant; Nothing can be compiled

**To Reproduce**
`./vcpkg install --head corrade:x64-windows magnum:x64-windows`

**Failure logs** 
```
-- Downloading https://api.github.com/repos/mosra/magnum/git/refs/heads/master -> mosra-magnum-master.tar.gz.version...
-- Skipping hash check for D:/dev/vcpkg/downloads/temp/mosra-magnum-master.tar.gz.version.
-- Downloading https://github.com/mosra/magnum/archive/master.tar.gz -> mosra-magnum-master.tar.gz...
-- Skipping hash check for D:/dev/vcpkg/downloads/temp/mosra-magnum-master.tar.gz.
-- Extracting source D:/dev/vcpkg/downloads/mosra-magnum-master.tar.gz
-- Applying patch 001-tools-path.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:61 (message):
  Applying patch failed: Checking patch modules/FindCorrade.cmake...

  error: while searching for:

          if(_component MATCHES ${_CORRADE_EXECUTABLE_COMPONENTS})
              add_executable(Corrade::${_component} IMPORTED)



              find_program(CORRADE_${_COMPONENT}_EXECUTABLE corrade-${_component})
              mark_as_advanced(CORRADE_${_COMPONENT}_EXECUTABLE)



              if(CORRADE_${_COMPONENT}_EXECUTABLE)



  error: patch failed: modules/FindCorrade.cmake:397

  error: modules/FindCorrade.cmake: patch does not apply

  Checking patch modules/FindMagnum.cmake...

  error: while searching for:

          if(_component MATCHES ${_MAGNUM_EXECUTABLE_COMPONENTS})
              add_executable(Magnum::${_component} IMPORTED)



              find_program(MAGNUM_${_COMPONENT}_EXECUTABLE magnum-${_component})
              mark_as_advanced(MAGNUM_${_COMPONENT}_EXECUTABLE)



              if(MAGNUM_${_COMPONENT}_EXECUTABLE)



  error: patch failed: modules/FindMagnum.cmake:493

  error: modules/FindMagnum.cmake: patch does not apply

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive.cmake:230 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:32 (vcpkg_extract_source_archive)
  scripts/cmake/vcpkg_from_github.cmake:179 (vcpkg_extract_source_archive_ex)
  ports/magnum/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:140 (include)


Error: Building package magnum:x64-windows failed with: BUILD_FAILED
```

**Additional context**
As far as I can tell, git can't apply the patch 001-tools-path which is necessary for the port.
I am able to install magnum:x64-windows without the `--head` flag but it is a very old version that doesn't contain headers such as `Magnum/Shaders/VertexColorGL.h`.

**Comment by autoantwort** [comment] 2021-07-31 18:07
So the port builds normally, but you are requesting a port update :)

**Comment by autoantwort** [comment] 2021-07-31 18:12
Ah it is already uses the latest release, but the latest release is one year old.

**Comment by e9x** [comment] 2021-07-31 18:23
I am not requesting a port update because this is a bug. Building from the head branch should have worked.

**Comment by NancyLi1013** [comment] 2021-08-02 06:57
Hi @e9x 

Thanks for posting this issue.

Since this is caused by using `--head` instead of the stable version in vcpkg. We cannot make sure if this can work fine on unstable git commit.

If you have the request to the new changes on master, you can use [overlay-ports](https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md) to update the patch on your local.

**Comment by NancyLi1013** [comment] 2021-08-06 09:59
Closing this issue for now, please feel free to reopen this issue if you have any problems when using overlay-ports.

**Closed by NancyLi1013** 2021-08-06 09:59 UTC
Labels: category:question
