### ISSUE TITLE
vcpkg glib failed with BUILD_FAILED

### ISSUE THREAD

**Issue by NiceBlueChai** [microsoft/vcpkg#27552] opened 2022-10-30 07:49 UTC
Package: glib[core]:x86-windows -> 2.74.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.33.31630.0
-    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install glib`

**Failure logs**

```
-- Using cached glib-2.74.0.tar.xz.
-- Cleaning sources at C:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/buildtrees/glib/src/glib-2-22354247da.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/downloads/glib-2.74.0.tar.xz
-- Applying patch use-libiconv-on-windows.patch
-- Applying patch libintl.patch
-- Using source at C:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/buildtrees/glib/src/glib-2-22354247da.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x86-windows
-- Configuring x86-windows-dbg
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/downloads/tools/msys2/9a1ec3f33446b195
-- Configuring x86-windows-dbg done
-- Configuring x86-windows-rel
-- Configuring x86-windows-rel done
-- Package x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:96 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" install -v
    Working Directory: C:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/buildtrees/glib/x86-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Users\NiceBlueChai\scoop\apps\vcpkg\2022.10.19\buildtrees\glib\package-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/glib/portfile.cmake:47 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\Users\NiceBlueChai\scoop\apps\vcpkg\2022.10.19\buildtrees\glib\package-x86-windows-dbg-out.log</summary>

```
[1/467] "C:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/downloads/tools/python/python-3.10.5-x86/python.exe" "../src/glib-2-22354247da.clean/gio/data-to-c.py" "../src/glib-2-22354247da.clean/gio/../glib/gconstructor.h" "gconstructor_code" "gio/gconstructor_as_data.h"
[2/467] "C:/Program Files (x86)/Windows Kits/10/bin/10.0.19041.0/x64/rc.exe" "/nologo" "/foglib/glib_glib.rc_glib.res" "glib/glib.rc"
[3/467] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x86/cl.exe" "-Iglib\gnulib\libgnulib.a.p" "-Iglib\gnulib" "-I..\src\glib-2-22354247da.clean\glib\gnulib" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/installed/x86-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/Zi" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_ENABLE_DEBUG" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DGCC_LINT=1" "-DLIBDIR=\"C:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/packages/glib_x86-windows/debug/lib\"" "-DGLIB_COMPILATION" "-DG_LOG_DOMAIN=\"GLib\"" "-DHAVE_ISNAN_IN_LIBC" "-DHAVE_ISNAND_IN_LIBC" "-DHAVE_ISNANF_IN_LIBC" "-DHAVE_ISNANL_IN_LIBC" "/Fdglib\gnulib\libgnulib.a.p\printf-frexp.c.pdb" /Foglib/gnulib/libgnulib.a.p/printf-frexp.c.obj "/c" ../src/glib-2-22354247da.clean/glib/gnulib/printf-frexp.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
[4/467] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x86/cl.exe" "-Iglib\gnulib\libgnulib.a.p" "-Iglib\gnulib" "-I..\src\glib-2-22354247da.clean\glib\gnulib" "-I." "-I..\src\glib-2-22354247da.clean" "-Iglib" "-I..\src\glib-2-22354247da.clean\glib" "-IC:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/installed/x86-windows/include" "/MDd" "/nologo" "/showIncludes" "/utf-8" "/W4" "/Od" "/Zi" "/FImsvc_recommended_pragmas.h" "/utf-8" "-D_GNU_SOURCE" "-DG_ENABLE_DEBUG" "/wo4057" "/wd4068" "/wo4090" "/wd4100" "/wd4116" "/wo4125" "/wd4127" "/wd4146" "/wd4152" "/wd4201" "/wd4232" "/wo4245" "/wo4267" "/wd4334" "/wo4389" "/wo4702" "/wd4706" "-nologo" "-DWIN32" "-D_WINDOWS" "-W3" "-utf-8" "-MP" "-D_DEBUG" "-MDd" "-Z7" "-Ob0" "-Od" "-RTC1" "-DGCC_LINT=1" "-DLIBDIR=\"C:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/packages/glib_x86-windows/debug/lib\"" "-DGLIB_COMPILATION" "-DG_LOG_DOMAIN=\"GLib\"" "-DHAVE_ISNAN_IN_LIBC" "-DHAVE_ISNAND_IN_LIBC" "-DHAVE_ISNANF_IN_LIBC" "-DHAVE_ISNANL_IN_LIBC" "/Fdglib\gnulib\libgnulib.a.p\printf-frexpl.c.pdb" /Foglib/gnulib/libgnulib.a.p/printf-frexpl.c.obj "/c" ../src/glib-2-22354247da.clean/glib/gnulib/printf-frexpl.c
cl : Command line warning D9025 : overriding '/W4' with '/W3'
...
Skipped 333 lines
...
./src/glib-2-22354247da.clean/gio/gunixfdlist.h" "../src/glib-2-22354247da.clean/gio/gunixsocketaddress.h" "../src/glib-2-22354247da.clean/gio/gvfs.h" "../src/glib-2-22354247da.clean/gio/gvolume.h" "../src/glib-2-22354247da.clean/gio/gvolumemonitor.h" "../src/glib-2-22354247da.clean/gio/gzlibcompressor.h" "../src/glib-2-22354247da.clean/gio/gzlibdecompressor.h" "../src/glib-2-22354247da.clean/gio/glistmodel.h" "../src/glib-2-22354247da.clean/gio/gliststore.h" "../src/glib-2-22354247da.clean/gio/gapplication.h" "../src/glib-2-22354247da.clean/gio/gapplicationcommandline.h" "../src/glib-2-22354247da.clean/gio/gactiongroup.h" "../src/glib-2-22354247da.clean/gio/gactionmap.h" "../src/glib-2-22354247da.clean/gio/gsimpleactiongroup.h" "../src/glib-2-22354247da.clean/gio/gremoteactiongroup.h" "../src/glib-2-22354247da.clean/gio/gactiongroupexporter.h" "../src/glib-2-22354247da.clean/gio/gdbusactiongroup.h" "../src/glib-2-22354247da.clean/gio/gaction.h" "../src/glib-2-22354247da.clean/gio/gpropertyaction.h" "../src/glib-2-22354247da.clean/gio/gsimpleaction.h" "../src/glib-2-22354247da.clean/gio/gmenumodel.h" "../src/glib-2-22354247da.clean/gio/gmenu.h" "../src/glib-2-22354247da.clean/gio/gmenuexporter.h" "../src/glib-2-22354247da.clean/gio/gdbusmenumodel.h" "../src/glib-2-22354247da.clean/gio/gnotification.h" "../src/glib-2-22354247da.clean/gio/gsettingsbackend.h" "../src/glib-2-22354247da.clean/gio/gsettingsschema.h" "../src/glib-2-22354247da.clean/gio/gsettings.h" "../src/glib-2-22354247da.clean/gio/gdbusauthobserver.h" "../src/glib-2-22354247da.clean/gio/gcredentials.h" "../src/glib-2-22354247da.clean/gio/gdbusutils.h" "../src/glib-2-22354247da.clean/gio/gdbuserror.h" "../src/glib-2-22354247da.clean/gio/gdbusaddress.h" "../src/glib-2-22354247da.clean/gio/gdbusconnection.h" "../src/glib-2-22354247da.clean/gio/gdbusmessage.h" "../src/glib-2-22354247da.clean/gio/gdbusnameowning.h" "../src/glib-2-22354247da.clean/gio/gdbusnamewatching.h" "../src/glib-2-22354247da.clean/gio/gdbusproxy.h" "../src/glib-2-22354247da.clean/gio/gdbusintrospection.h" "../src/glib-2-22354247da.clean/gio/gdbusmethodinvocation.h" "../src/glib-2-22354247da.clean/gio/gdbusserver.h" "../src/glib-2-22354247da.clean/gio/gdbusinterface.h" "../src/glib-2-22354247da.clean/gio/gdbusinterfaceskeleton.h" "../src/glib-2-22354247da.clean/gio/gdbusobject.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectskeleton.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectproxy.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectmanager.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectmanagerclient.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectmanagerserver.h" "../src/glib-2-22354247da.clean/gio/gtestdbus.h" "gio/gnetworking.h"
FAILED: gio/gioenumtypes.h 
"C:\Users\NiceBlueChai\scoop\apps\vcpkg\2022.10.19\downloads\tools\python\python-3.10.5-x86\python.exe" "C:\Users\NiceBlueChai\scoop\persist\vcpkg\installed\x64-windows\tools\meson\meson.py" "--internal" "exe" "--capture" "gio\gioenumtypes.h" "--" "C:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/downloads/tools/python/python-3.10.5-x86/python.exe" "gobject/glib-mkenums" "--template" "../src/glib-2-22354247da.clean/gio/gioenumtypes.h.template" "../src/glib-2-22354247da.clean/gio/gappinfo.h" "../src/glib-2-22354247da.clean/gio/gasyncinitable.h" "../src/glib-2-22354247da.clean/gio/gasyncresult.h" "../src/glib-2-22354247da.clean/gio/gbufferedinputstream.h" "../src/glib-2-22354247da.clean/gio/gbufferedoutputstream.h" "../src/glib-2-22354247da.clean/gio/gbytesicon.h" "../src/glib-2-22354247da.clean/gio/gcancellable.h" "../src/glib-2-22354247da.clean/gio/gcontenttype.h" "../src/glib-2-22354247da.clean/gio/gcharsetconverter.h" "../src/glib-2-22354247da.clean/gio/gconverter.h" "../src/glib-2-22354247da.clean/gio/gconverterinputstream.h" "../src/glib-2-22354247da.clean/gio/gconverteroutputstream.h" "../src/glib-2-22354247da.clean/gio/gdatagrambased.h" "../src/glib-2-22354247da.clean/gio/gdatainputstream.h" "../src/glib-2-22354247da.clean/gio/gdataoutputstream.h" "../src/glib-2-22354247da.clean/gio/gdebugcontroller.h" "../src/glib-2-22354247da.clean/gio/gdebugcontrollerdbus.h" "../src/glib-2-22354247da.clean/gio/gdrive.h" "../src/glib-2-22354247da.clean/gio/gemblem.h" "../src/glib-2-22354247da.clean/gio/gemblemedicon.h" "../src/glib-2-22354247da.clean/gio/gfile.h" "../src/glib-2-22354247da.clean/gio/gfileattribute.h" "../src/glib-2-22354247da.clean/gio/gfileenumerator.h" "../src/glib-2-22354247da.clean/gio/gfileicon.h" "../src/glib-2-22354247da.clean/gio/gfileinfo.h" "../src/glib-2-22354247da.clean/gio/gfileinputstream.h" "../src/glib-2-22354247da.clean/gio/gfilemonitor.h" "../src/glib-2-22354247da.clean/gio/gfilenamecompleter.h" "../src/glib-2-22354247da.clean/gio/gfileoutputstream.h" "../src/glib-2-22354247da.clean/gio/gfileiostream.h" "../src/glib-2-22354247da.clean/gio/gfilterinputstream.h" "../src/glib-2-22354247da.clean/gio/gfilteroutputstream.h" "../src/glib-2-22354247da.clean/gio/gicon.h" "../src/glib-2-22354247da.clean/gio/ginetaddress.h" "../src/glib-2-22354247da.clean/gio/ginetaddressmask.h" "../src/glib-2-22354247da.clean/gio/ginetsocketaddress.h" "../src/glib-2-22354247da.clean/gio/ginitable.h" "../src/glib-2-22354247da.clean/gio/ginputstream.h" "../src/glib-2-22354247da.clean/gio/gio.h" "../src/glib-2-22354247da.clean/gio/gio-autocleanups.h" "../src/glib-2-22354247da.clean/gio/gioenums.h" "../src/glib-2-22354247da.clean/gio/gioerror.h" "../src/glib-2-22354247da.clean/gio/giomodule.h" "../src/glib-2-22354247da.clean/gio/gioscheduler.h" "../src/glib-2-22354247da.clean/gio/giostream.h" "../src/glib-2-22354247da.clean/gio/giotypes.h" "../src/glib-2-22354247da.clean/gio/gloadableicon.h" "../src/glib-2-22354247da.clean/gio/gmount.h" "../src/glib-2-22354247da.clean/gio/gmemoryinputstream.h" "../src/glib-2-22354247da.clean/gio/gmemorymonitor.h" "../src/glib-2-22354247da.clean/gio/gmemoryoutputstream.h" "../src/glib-2-22354247da.clean/gio/gmountoperation.h" "../src/glib-2-22354247da.clean/gio/gnativesocketaddress.h" "../src/glib-2-22354247da.clean/gio/gnativevolumemonitor.h" "../src/glib-2-22354247da.clean/gio/gnetworkaddress.h" "../src/glib-2-22354247da.clean/gio/gnetworkmonitor.h" "../src/glib-2-22354247da.clean/gio/gnetworkservice.h" "../src/glib-2-22354247da.clean/gio/goutputstream.h" "../src/glib-2-22354247da.clean/gio/gpermission.h" "../src/glib-2-22354247da.clean/gio/gpollableinputstream.h" "../src/glib-2-22354247da.clean/gio/gpollableoutputstream.h" "../src/glib-2-22354247da.clean/gio/gpollableutils.h" "../src/glib-2-22354247da.clean/gio/gpowerprofilemonitor.h" "../src/glib-2-22354247da.clean/gio/gproxy.h" "../src/glib-2-22354247da.clean/gio/gproxyaddress.h" "../src/glib-2-22354247da.clean/gio/gproxyaddressenumerator.h" "../src/glib-2-22354247da.clean/gio/gproxyresolver.h" "../src/glib-2-22354247da.clean/gio/gresolver.h" "../src/glib-2-22354247da.clean/gio/gresource.h" "../src/glib-2-22354247da.clean/gio/gseekable.h" "../src/glib-2-22354247da.clean/gio/gsimpleasyncresult.h" "../src/glib-2-22354247da.clean/gio/gsimpleiostream.h" "../src/glib-2-22354247da.clean/gio/gsimplepermission.h" "../src/glib-2-22354247da.clean/gio/gsimpleproxyresolver.h" "../src/glib-2-22354247da.clean/gio/gsocket.h" "../src/glib-2-22354247da.clean/gio/gsocketaddress.h" "../src/glib-2-22354247da.clean/gio/gsocketaddressenumerator.h" "../src/glib-2-22354247da.clean/gio/gsocketclient.h" "../src/glib-2-22354247da.clean/gio/gsocketconnectable.h" "../src/glib-2-22354247da.clean/gio/gsocketconnection.h" "../src/glib-2-22354247da.clean/gio/gsocketcontrolmessage.h" "../src/glib-2-22354247da.clean/gio/gsocketlistener.h" "../src/glib-2-22354247da.clean/gio/gsocketservice.h" "../src/glib-2-22354247da.clean/gio/gsrvtarget.h" "../src/glib-2-22354247da.clean/gio/gsubprocess.h" "../src/glib-2-22354247da.clean/gio/gsubprocesslauncher.h" "../src/glib-2-22354247da.clean/gio/gtask.h" "../src/glib-2-22354247da.clean/gio/gtcpconnection.h" "../src/glib-2-22354247da.clean/gio/gtcpwrapperconnection.h" "../src/glib-2-22354247da.clean/gio/gthemedicon.h" "../src/glib-2-22354247da.clean/gio/gthreadedsocketservice.h" "../src/glib-2-22354247da.clean/gio/gtlsbackend.h" "../src/glib-2-22354247da.clean/gio/gtlscertificate.h" "../src/glib-2-22354247da.clean/gio/gtlsclientconnection.h" "../src/glib-2-22354247da.clean/gio/gtlsconnection.h" "../src/glib-2-22354247da.clean/gio/gtlsdatabase.h" "../src/glib-2-22354247da.clean/gio/gtlsfiledatabase.h" "../src/glib-2-22354247da.clean/gio/gtlsinteraction.h" "../src/glib-2-22354247da.clean/gio/gtlspassword.h" "../src/glib-2-22354247da.clean/gio/gtlsserverconnection.h" "../src/glib-2-22354247da.clean/gio/gdtlsconnection.h" "../src/glib-2-22354247da.clean/gio/gdtlsclientconnection.h" "../src/glib-2-22354247da.clean/gio/gdtlsserverconnection.h" "../src/glib-2-22354247da.clean/gio/gunixconnection.h" "../src/glib-2-22354247da.clean/gio/gunixcredentialsmessage.h" "../src/glib-2-22354247da.clean/gio/gunixfdlist.h" "../src/glib-2-22354247da.clean/gio/gunixsocketaddress.h" "../src/glib-2-22354247da.clean/gio/gvfs.h" "../src/glib-2-22354247da.clean/gio/gvolume.h" "../src/glib-2-22354247da.clean/gio/gvolumemonitor.h" "../src/glib-2-22354247da.clean/gio/gzlibcompressor.h" "../src/glib-2-22354247da.clean/gio/gzlibdecompressor.h" "../src/glib-2-22354247da.clean/gio/glistmodel.h" "../src/glib-2-22354247da.clean/gio/gliststore.h" "../src/glib-2-22354247da.clean/gio/gapplication.h" "../src/glib-2-22354247da.clean/gio/gapplicationcommandline.h" "../src/glib-2-22354247da.clean/gio/gactiongroup.h" "../src/glib-2-22354247da.clean/gio/gactionmap.h" "../src/glib-2-22354247da.clean/gio/gsimpleactiongroup.h" "../src/glib-2-22354247da.clean/gio/gremoteactiongroup.h" "../src/glib-2-22354247da.clean/gio/gactiongroupexporter.h" "../src/glib-2-22354247da.clean/gio/gdbusactiongroup.h" "../src/glib-2-22354247da.clean/gio/gaction.h" "../src/glib-2-22354247da.clean/gio/gpropertyaction.h" "../src/glib-2-22354247da.clean/gio/gsimpleaction.h" "../src/glib-2-22354247da.clean/gio/gmenumodel.h" "../src/glib-2-22354247da.clean/gio/gmenu.h" "../src/glib-2-22354247da.clean/gio/gmenuexporter.h" "../src/glib-2-22354247da.clean/gio/gdbusmenumodel.h" "../src/glib-2-22354247da.clean/gio/gnotification.h" "../src/glib-2-22354247da.clean/gio/gsettingsbackend.h" "../src/glib-2-22354247da.clean/gio/gsettingsschema.h" "../src/glib-2-22354247da.clean/gio/gsettings.h" "../src/glib-2-22354247da.clean/gio/gdbusauthobserver.h" "../src/glib-2-22354247da.clean/gio/gcredentials.h" "../src/glib-2-22354247da.clean/gio/gdbusutils.h" "../src/glib-2-22354247da.clean/gio/gdbuserror.h" "../src/glib-2-22354247da.clean/gio/gdbusaddress.h" "../src/glib-2-22354247da.clean/gio/gdbusconnection.h" "../src/glib-2-22354247da.clean/gio/gdbusmessage.h" "../src/glib-2-22354247da.clean/gio/gdbusnameowning.h" "../src/glib-2-22354247da.clean/gio/gdbusnamewatching.h" "../src/glib-2-22354247da.clean/gio/gdbusproxy.h" "../src/glib-2-22354247da.clean/gio/gdbusintrospection.h" "../src/glib-2-22354247da.clean/gio/gdbusmethodinvocation.h" "../src/glib-2-22354247da.clean/gio/gdbusserver.h" "../src/glib-2-22354247da.clean/gio/gdbusinterface.h" "../src/glib-2-22354247da.clean/gio/gdbusinterfaceskeleton.h" "../src/glib-2-22354247da.clean/gio/gdbusobject.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectskeleton.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectproxy.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectmanager.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectmanagerclient.h" "../src/glib-2-22354247da.clean/gio/gdbusobjectmanagerserver.h" "../src/glib-2-22354247da.clean/gio/gtestdbus.h" "gio/gnetworking.h"
--- stderr ---
Traceback (most recent call last):

  File "C:\Users\NiceBlueChai\scoop\apps\vcpkg\2022.10.19\buildtrees\glib\x86-windows-dbg\gobject\glib-mkenums", line 486, in <module>

    write_output(prod)

  File "C:\Users\NiceBlueChai\scoop\apps\vcpkg\2022.10.19\buildtrees\glib\x86-windows-dbg\gobject\glib-mkenums", line 97, in write_output

    print(output, file=output_stream)

UnicodeEncodeError: 'gbk' codec can't encode character '\xa9' in position 17: illegal multibyte sequence


[117/467] "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.33.31629/bin/Hostx64/x86/link.exe" @glib/glib-2.0-0.dll.rsp
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/RELEASE' specification
   Creating library glib\glib-2.0.lib and object glib\glib-2.0.exp
[118/467] "C:\Users\NiceBlueChai\scoop\apps\vcpkg\2022.10.19\downloads\tools\python\python-3.10.5-x86\python.exe" "C:\Users\NiceBlueChai\scoop\persist\vcpkg\installed\x64-windows\tools\meson\meson.py" "--internal" "exe" "--capture" "gobject\glib-enumtypes.h" "--" "C:/Users/NiceBlueChai/scoop/apps/vcpkg/2022.10.19/downloads/tools/python/python-3.10.5-x86/python.exe" "gobject/glib-mkenums" "--template" "../src/glib-2-22354247da.clean/gobject/glib-enumtypes.h.template" "../src/glib-2-22354247da.clean/gobject/../glib/gunicode.h"
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

**Comment by dg0yt** [comment] 2022-10-30 08:09
Duplicates  #27409.

**Comment by LilyWangLL** [comment] 2022-10-31 07:00
Closed as duplicate of https://github.com/microsoft/vcpkg/issues/27409.

**Closed by LilyWangLL** 2022-10-31 07:00 UTC
Labels: category:port-bug
