### ISSUE TITLE
How do I can install sdl2:x64-mingw

### ISSUE THREAD

**Issue by jimboyeah** [microsoft/vcpkg#12375] opened 2020-07-11 09:31 UTC
>vcpkg install sdl2:x64-mingw
Computing installation plan...
The following packages will be built and installed:
    sdl2[core]:x64-mingw
Unable to determine toolchain to use for triplet x64-mingw with CMAKE_SYSTEM_NAME MinGW

**Comment by jimboyeah** [comment] 2020-07-11 10:20
我遇到这个问题有点恶心，因为 vcpkg 的源代码忽略了 MinGW：

	>vcpkg install assimp:x64-mingw
	Computing installation plan...
	The following packages will be built and installed:
	    assimp[core]:x64-mingw
	  * minizip[core]:x64-mingw
	  * rapidjson[core]:x64-mingw
	  * zlib[core]:x64-mingw
	Additional packages (*) will be modified to complete this operation.
	Unable to determine toolchain to use for triplet x64-mingw with CMAKE_SYSTEM_NAME MinGW

解决方法是修改 build.cpp 重新编译 vcpkg：

	diff --git a/toolsrc/src/vcpkg/build.cpp b/toolsrc/src/vcpkg/build.cpp
	index c61c6b7..d7c78aa 100644
	--- a/toolsrc/src/vcpkg/build.cpp
	+++ b/toolsrc/src/vcpkg/build.cpp
	@@ -558,6 +558,10 @@ namespace vcpkg::Build
	         else if (cmake_system_name == "Android")
	         {
	             return m_paths.scripts / fs::u8path("toolchains/android.cmake");
	+        }
	+        else if (cmake_system_name == "MinGW")
	+        {
	+            return m_paths.scripts / fs::u8path("toolchains/mingw.cmake");
	         }
	         else if (cmake_system_name.empty() || cmake_system_name == "Windows" || cmake_system_name == "WindowsStore")
	         {
	--

**Comment by longnguyen2004** [comment] 2020-07-11 10:26
Duplicate of #12065

**Comment by LilyWangL** [comment] 2020-07-31 09:05
Thanks for posting this issue. This issue has been fixed by PR #12084. So I am closing this issue for now.

**Closed by LilyWangL** 2020-07-31 09:05 UTC
Labels: category:question
