### ISSUE TITLE
[tomlplusplus] build failure

### ISSUE THREAD

**Issue by zyf2008Neptune** [microsoft/vcpkg#39041] opened 2024-05-30 11:16 UTC
### Operating system

Windows

### Compiler

Clang/MSVC

### Steps to reproduce the behavior

```Shell
visual studio 2022
in vcpkg.json "dependencies"["tomlplusplus"]
in CMakeLists.txt find_package(tomlplusplus CONFIG REQUIRED)
```

### Failure logs

Build started at 2024-05-30T19:09:58.276969
Main binary: C:\Users\XXX\AppData\Local\vcpkg\downloads\tools\python\python-3.11.8-x64\python.exe
Build Options: -Dgenerate_cmake_config=false -Dbuild_tests=false -Dbuild_examples=false -Dbuildtype=plain -Doptimization=plain -Ddebug=true '-Dcmake_prefix_path=['"'"'D:/study/github/XXX/build/vcpkg_installed/x64-windows-static-md/debug'"'"','"'"'D:/study/github/XXX/build/vcpkg_installed/x64-windows-static-md'"'"','"'"'D:/study/github/XXX/build/vcpkg_installed/x64-windows-static-md/share'"'"']' -Dprefix=D:/study/github/XXX/build/vcpkg_installed/vcpkg/pkgs/tomlplusplus_x64-windows-static-md/debug -Dincludedir=../include -Dlibdir=lib -Dbackend=ninja -Dwrap_mode=nodownload '--native-file D:/study/github/XXX/build/vcpkg_installed/vcpkg/blds/tomlplusplus/meson-x64-windows-static-md-dbg.log'
Python system: Windows
The Meson build system
Version: 0.62.1
Source dir: D:\study\github\XXX\build\vcpkg_installed\vcpkg\blds\tomlplusplus\src\v3.4.0-52dc53a92a.clean
Build dir: D:\study\github\XXX\build\vcpkg_installed\vcpkg\blds\tomlplusplus\x64-windows-static-md-dbg
Build type: native build

..\src\v3.4.0-52dc53a92a.clean\meson.build:6:0: ERROR: Value "plain" (of type "string") for combo option "Optimization level" is not one of the choices. Possible choices are (as string): "0", "g", "1", "2", "3", "s".

**Comment by dg0yt** [comment] 2024-05-30 11:27
Similar to https://github.com/microsoft/vcpkg/issues/39035#issuecomment-2138876967.

**Comment by LilyWangLL** [comment] 2024-05-31 02:10
Duplicate of #39035.

**Closed by LilyWangLL** 2024-05-31 02:10 UTC
Labels: category:port-bug
