### ISSUE TITLE
[yasm-tool:x86] build failure

### ISSUE THREAD

**Issue by BrettDong** [microsoft/vcpkg#17350] opened 2021-04-19 03:23 UTC
**Host Environment**
- OS: Windows 7 SP1 x64
- Compiler: Visual Studio 2019 Community Edition v16.9.2, CL 19.28.29913
(Already updated vcpkg to the latest version)

**To Reproduce**

`./vcpkg --triplet x86-windows install yasm-tool yasm-tool-helper`

**Failure logs** 
Console output:
```
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-w
in32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j3
    Working Directory: C:/vcpkg/buildtrees/yasm-tool/x86-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\yasm-tool\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/yasm-tool/portfile.cmake:25 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package yasm-tool:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: yasm-tool:x86-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.
```

Last few lines in build log:
```
[51/125] cmd.exe /C "cd /D C:\vcpkg\buildtrees\yasm-tool\x86-windows-dbg\modules && C:\vcpkg\downloads\tools\python\python-3.9.2-x86\python.exe C:/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean/modules/arch/x86/gen_x86_insn.py C:/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/modules/x86insns.c C:/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/modules/x86insn_gas.gperf C:/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/modules/x86insn_nasm.gperf"
FAILED: modules/x86insns.c modules/x86insn_gas.gperf modules/x86insn_nasm.gperf 
cmd.exe /C "cd /D C:\vcpkg\buildtrees\yasm-tool\x86-windows-dbg\modules && C:\vcpkg\downloads\tools\python\python-3.9.2-x86\python.exe C:/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean/modules/arch/x86/gen_x86_insn.py C:/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/modules/x86insns.c C:/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/modules/x86insn_gas.gperf C:/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/modules/x86insn_nasm.gperf"
[52/125] cmd.exe /C "cd /D C:\vcpkg\buildtrees\yasm-tool\x86-windows-dbg\modules && C:\vcpkg\buildtrees\yasm-tool\x86-windows-dbg\tools\re2c\re2c.exe -s -o C:/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/modules/lc3bid.c C:/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean/modules/arch/lc3b/lc3bid.re"
[53/125] cmd.exe /C "cd /D C:\vcpkg\buildtrees\yasm-tool\x86-windows-dbg\modules && C:\vcpkg\buildtrees\yasm-tool\x86-windows-dbg\tools\genperf\genperf.exe C:/vcpkg/buildtrees/yasm-tool/src/d25248d823-818ed1bbf4.clean/modules/arch/x86/x86cpu.gperf C:/vcpkg/buildtrees/yasm-tool/x86-windows-dbg/modules/x86cpu.c"
ninja: build stopped: subcommand failed.
```

Full log: [install-x86-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/6333023/install-x86-windows-dbg-out.log)

**Comment by JonLiu1993** [comment] 2021-04-19 05:52
Duplicate of #17334

**Closed by JonLiu1993** 2021-04-19 05:52 UTC
