### ISSUE TITLE
[minc]:x64-linux-dynamic build failure

### ISSUE THREAD

**Issue by dweckmann** [microsoft/vcpkg#15463] opened 2021-01-05 13:28 UTC
**Host Environment**
- OS: Ubuntu 20.04 LTS
- Compiler: gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

**To Reproduce**
`./vcpkg install minc`

**Failure logs** 
[config-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/5770356/config-x64-linux-dbg-err.log)
[config-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/5770358/config-x64-linux-dbg-out.log)

**Additional context**
Again, the problem arise only in dynamic linkage type.

`#include <hdf5.h>` doesn't work meaning an `target_include_directories` or `target_link_libraries` is missing somewhere...

**Comment by Cheney-W** [comment] 2022-01-29 09:10
I could install this port successfully with the latest vcpkg  2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761 in linux. Could you please have a try?

**Comment by dweckmann** [comment] 2022-01-31 08:29
> I could install this port successfully with the latest vcpkg 2021-12-09-724cea8b33cbf06c645f5095fa29773697da9761 in linux. Could you please have a try?

Sorry, it is still failing.

The point is to use a custom triplet, with dynamic linkage.

As the dynamic linkage seems unsupported right now for Linux, I'm not sure this Issue are still relevant.

**Comment by Cheney-W** [comment] 2022-02-07 06:29
There is a [discussion](https://github.com/microsoft/vcpkg/discussions/19127) about making Linux support dynamic linkage, I think this issue could be closed and then tracked by that discussion.

**Comment by LilyWangLL** [comment] 2022-10-21 09:25
Closed as duplicate of https://github.com/microsoft/vcpkg/discussions/19127.

**Closed by LilyWangLL** 2022-10-21 09:25 UTC
Labels: requires:repro
