### ISSUE TITLE
Mupdf link error when use in my project

### ISSUE THREAD

**Issue by sadokfire** [microsoft/vcpkg#31899] opened 2023-06-08 19:27 UTC
**Describe the bug**
Library Mupdf (1.19.0-rc2#1) build success, but have linkage problem. I found problem with previous version #9416

**Environment**
- OS: win 11
- Compiler:  VS 2022 (v143, 10.0.22000.0)
- Cmake: 3.23.2

**To Reproduce**
1. ./vcpkg install libmupdf:x64-windows
```
Computing installation plan...
The following packages will be built and installed:
    libmupdf[core]:x64-windows -> 1.19.0-rc2#1
Detecting compiler hash for triplet x64-windows...
Restored 1 package(s) from C:\Users\me\AppData\Local\vcpkg\archives in 840.5796 ms. Use --debug to see more details.
Installing 1/1 libmupdf:x64-windows...
Elapsed time to handle libmupdf:x64-windows: 3.4273337 s
Total install time: 19.2020903 s
```
2. Create cmake project sandbox with
```
target_link_libraries(
     PRIVATE libmupdf
 ```
3. Compile project via VS 2022
4. Compile error

**Expected behavior**
Compiled without "unresolved external symbol"

**Failure logs**
```
2>------ Build started: Project: mupdfTest, Configuration: Debug x64 ------
2>LINK : warning LNK4098: defaultlib 'MSVCRT' conflicts with use of other libs; use /NODEFAULTLIB:library
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_CharisSIL_cff
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_CharisSIL_cff_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_CharisSIL_Italic_cff
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_CharisSIL_Italic_cff_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_CharisSIL_Bold_cff
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_CharisSIL_Bold_cff_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_CharisSIL_BoldItalic_cff
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_CharisSIL_BoldItalic_cff_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_NotoSerif_Regular_otf
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_NotoSerif_Regular_otf
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_NotoSerif_Regular_otf
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_NotoSerif_Regular_otf_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_NotoSerif_Regular_otf_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_NotoSerif_Regular_otf_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_SourceHanSerif_Regular_ttc
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_SourceHanSerif_Regular_ttc
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_SourceHanSerif_Regular_ttc
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_SourceHanSerif_Regular_ttc
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_SourceHanSerif_Regular_ttc_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_SourceHanSerif_Regular_ttc_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_SourceHanSerif_Regular_ttc_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_SourceHanSerif_Regular_ttc_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_NotoNastaliqUrdu_Regular_otf
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_NotoNastaliqUrdu_Regular_otf_size
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_NotoNaskhArabic_Regular_otf
2>libmupdf.lib(noto.c.obj) : error LNK2001: unresolved external symbol _binary_NotoNaskhArabic_Regular_otf_size
...
```

**Comment by LilyWangLL** [comment] 2023-06-15 10:39
Closed as duplicate of #9416.

**Closed by LilyWangLL** 2023-06-15 10:39 UTC
Labels: category:port-bug
