### ISSUE TITLE
[darknet] build failure

### ISSUE THREAD

**Issue by Goru1890** [microsoft/vcpkg#17124] opened 2021-04-07 08:16 UTC
**Host Environment**
- OS: Windows
- Compiler: VisualStudio2019BuildTools

**To Reproduce**
`./vcpkg install darknet[opencv3-cuda,cudnn]:x64-windows`

Fails because of this same error https://github.com/AlexeyAB/darknet/issues/7533

Maybe the version of darknet in vcpkg should be updated.

**Comment by NancyLi1013** [comment] 2021-04-09 08:00
Hi @Goru1890 

Thanks for posting this issue.

I cannot reproduce this on my machine with Visual Studio 2017 and CUDA 11.2.

```
Starting package 22/22: darknet:x64-windows
Building package darknet[core,cuda,cudnn,opencv3-cuda]:x64-windows...
-- Using cached F:/tool/vcpkg/downloads/AlexeyAB-darknet-00d578e327c22638ea12e73c4efb74c798c08de5.tar.gz
-- Extracting source F:/tool/vcpkg/downloads/AlexeyAB-darknet-00d578e327c22638ea12e73c4efb74c798c08de5.tar.gz
-- Using source at F:/tool/vcpkg/buildtrees/darknet/src/c798c08de5-d29893808b
CMake Deprecation Warning at scripts/cmake/vcpkg_check_features.cmake:182 (message):
  calling `vcpkg_check_features` without the `FEATURES` keyword has been
  deprecated.

      Please add the `FEATURES` keyword to the call.
Call Stack (most recent call first):
  ports/darknet/portfile.cmake:9 (vcpkg_check_features)
  scripts/ports.cmake:142 (include)


-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/tool/vcpkg/packages/darknet_x64-windows/share/darknet/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package darknet[core,cuda,cudnn,opencv3-cuda]:x64-windows... done
Installing package darknet[core,cuda,cudnn,opencv3-cuda]:x64-windows...
Installing package darknet[core,cuda,cudnn,opencv3-cuda]:x64-windows... done
Elapsed time for package darknet:x64-windows: 3.49 min

Total elapsed time: 4.578 h

The package darknet:x64-windows provides CMake targets:

    find_package(Darknet CONFIG REQUIRED)
    target_link_libraries(main PRIVATE Darknet::dark)
```

**Comment by Goru1890** [comment] 2021-04-13 08:39
Thanks for the reply, I tried it at well with VS2017 and that worked for me, but not with VS2019.
But if I wanna try to install Qt with VS2019, it only work with VS2019.

It's a little bit annoying to uninstall and install different VS version anytime you want to install something different.

**Comment by NancyLi1013** [comment] 2021-04-13 08:46
Yes, I will also try to confirm the result with VS2019. Thanks for your update.

**Comment by AlexeyAB** [comment] 2021-04-13 21:35
@Goru1890 @NancyLi1013 @Goru1890 @cenit 
Is this bug fixed in VCPKG?

**Comment by cenit** [comment] 2021-04-15 16:18
nope, it depends on #15942 which in turn depends on https://github.com/AlexeyAB/darknet/pull/7279 . 
We can try to speed up things now a little bit more

**Comment by NancyLi1013** [comment] 2021-04-30 03:09
@cenit 

There is still some other work that needs to be done to fix this issue after PR #15942 merged. Is this right?

**Comment by cenit** [comment] 2021-04-30 05:52
nope, it should be ok now

**Comment by NancyLi1013** [comment] 2021-04-30 07:40
Thanks for your confirmation @cenit.

@AlexeyAB and @Goru1890 

Could you please update vcpkg to the latest version to rebuild this?

**Comment by Goru1890** [comment] 2021-05-23 09:02
After a successful installation of darknet[opencv3-cuda,cudnn]:x64-windows, darknet is not able to use the GPU. 

I think there was some architecture incompatibilities with darknet and the new rtx 3000 series, I have a 3060.

**Comment by cenit** [comment] 2021-05-23 11:35
you need the CUDA feature to enable cuda!

darknet[cuda,cudnn,opencv3-cuda]

**Comment by cenit** [comment] 2021-05-23 11:35
but cudnn should enable it automatically, if not that's a bug in the portfile. Let me check it later :)

**Comment by Goru1890** [comment] 2021-05-24 09:54
> you need the CUDA feature to enable cuda!
> 
> darknet[cuda,cudnn,opencv3-cuda]

[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/6531434/config-x64-windows-dbg-err.log)
 I got this error

**Comment by NancyLi1013** [comment] 2021-05-25 00:55
@Goru1890 

```
CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:861 (_find_package):
  By not providing "FindCUDNN.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "CUDNN", but
  CMake did not find one.

  Could not find a package configuration file provided by "CUDNN" with any of
  the following names:

    CUDNNConfig.cmake
    cudnn-config.cmake

  Add the installation prefix of "CUDNN" to CMAKE_PREFIX_PATH or set
  "CUDNN_DIR" to a directory containing one of the above files.  If "CUDNN"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:253 (find_package)
```
The above error has been fixed in PR #18005. You can update vcpkg to try this again. Please let me know if this is still a problem for you.

**Comment by cenit** [comment] 2021-05-25 03:48
he didn't have that error but another one, which should have already been fixed days ago by https://github.com/microsoft/vcpkg/pull/17644

is it possible that he's still using an old vcpkg version?

please git pull

**Comment by Goru1890** [comment] 2021-05-25 07:08
> please @Goru1890 do a git pull

I always do a git pull before trying to install something with vcpkg.

**Comment by cenit** [comment] 2021-05-25 07:28
> I always do a git pull before trying to install something with vcpkg.

and also a vcpkg update && vcpkg upgrade ?

**Comment by Goru1890** [comment] 2021-05-25 07:33
> and also a vcpkg update && vcpkg upgrade ?

I didn't try that, I will try it.

**Comment by Goru1890** [comment] 2021-05-25 07:53
![image](https://user-images.githubusercontent.com/35274844/119460574-1d792500-bd3f-11eb-8246-bd7ffff8a49e.png)

**Comment by cenit** [comment] 2021-05-25 08:24
and if you try a darknet[cudnn, ...] installation you still have the same failure?

**Comment by Goru1890** [comment] 2021-05-25 10:07
Yes

**Comment by cenit** [comment] 2021-05-25 10:10
can you please remove and reinstall cudnn

.\vcpkg remove cudnn
.\vcpkg install cudnn

and post full console logs about this process, and then verify if darknet still produces same error?

**Comment by cenit** [comment] 2021-05-25 10:11
also please show output of this command

`dir F:\tool\vcpkg\installed\x64-windows\share\cudnn`

**Comment by cenit** [comment] 2021-05-25 10:13
I just saw you have F:\tools\vcpkg and C:\vcpkg
are you sure you are not mixing two different vcpkg installations and having one updated and the other not? do you have any VCPKG_ROOT env variable defined?

**Comment by Goru1890** [comment] 2021-05-25 16:15
> .\vcpkg remove cudnn
> .\vcpkg install cudnn

I removed darknet, cudnn, and opencv3

And then I runned vcpkg install darknet[cudnn,cuda,opencv3-cuda]:x64-windows again

Now it works perfectly, thanks for your help.

**Comment by cenit** [comment] 2021-05-25 20:29
please close issue :)

**Comment by NancyLi1013** [comment] 2021-05-26 01:51
Thanks for your help @cenit.

I'm closing this issue for now since this issue has been solved.

**Closed by NancyLi1013** 2021-05-26 01:51 UTC
Labels: requires:repro
