### ISSUE TITLE
expat:x64-windows build failure

### ISSUE THREAD

**Issue by crdevvv** [microsoft/vcpkg#30771] opened 2023-04-11 11:04 UTC
### Operating system

- Host: x64-windows   -  vcpkg-tool version: 2023-02-16-12e657924d99511514c0287ca5ce46882d3657c7     vcpkg-scripts version: unknown

### Compiler

Compiler: MSVC 19.35.32216.1

### Steps to reproduce the behavior

```Shell
`vcpkg install glew eigen3 libjpeg-turbo libpng openexr tiff ffmpeg lz4 zstd python3 catch2`
```

### Failure logs

-- Downloading https://github.com/libexpat/libexpat/archive/R_2_5_0.tar.gz -> libexpat-libexpat-R_2_5_0.tar.gz...
-- Extracting source C:/Users/Cristiano/Desktop/criss/ORB_SLAM3/Pangolin/scripts/vcpkg/downloads/libexpat-libexpat-R_2_5_0.tar.gz
-- Using source at C:/Users/Cristiano/Desktop/criss/ORB_SLAM3/Pangolin/scripts/vcpkg/buildtrees/expat/src/R_2_5_0-56671c0753.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files (x86)/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: C:/Users/Cristiano/Desktop/criss/ORB_SLAM3/Pangolin/scripts/vcpkg/buildtrees/expat/x64-windows-dbg
    See logs for more information:
      C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/expat/portfile.cmake:28 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

```
<details><summary>C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\install-x64-windows-dbg-out.log</summary>

```
[1/6] C:/PROGRA~2/CMake/bin/cmcldeps.exe RC C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\win32\version.rc CMakeFiles\expat.dir\win32\version.rc.res.d CMakeFiles\expat.dir\win32\version.rc.res "Nota: file incluso  " "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.35.32215/bin/Hostx64/x64/cl.exe" C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe -DVER_FILEVERSION=2,5,0,0 -DXML_ENABLE_VISIBILITY=1 -D_CRT_SECURE_NO_WARNINGS -Dexpat_EXPORTS -I C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\x64-windows-dbg -I C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib -c65001 /DWIN32 -D_DEBUG   -wd4996 /fo CMakeFiles\expat.dir\win32\version.rc.res C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\win32\version.rc
[2/6] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\cl.exe   -DVER_FILEVERSION=2,5,0,0 -DXML_ENABLE_VISIBILITY=1 -D_CRT_SECURE_NO_WARNINGS -Dexpat_EXPORTS -IC:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\x64-windows-dbg -IC:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   -fno-strict-aliasing -fvisibility=hidden /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    -wd4996 /showIncludes /FoCMakeFiles\expat.dir\lib\xmlparse.c.obj /FdCMakeFiles\expat.dir\ /FS -c C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\xmlparse.c
FAILED: CMakeFiles/expat.dir/lib/xmlparse.c.obj 
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\cl.exe   -DVER_FILEVERSION=2,5,0,0 -DXML_ENABLE_VISIBILITY=1 -D_CRT_SECURE_NO_WARNINGS -Dexpat_EXPORTS -IC:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\x64-windows-dbg -IC:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   -fno-strict-aliasing -fvisibility=hidden /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    -wd4996 /showIncludes /FoCMakeFiles\expat.dir\lib\xmlparse.c.obj /FdCMakeFiles\expat.dir\ /FS -c C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\xmlparse.c
cl : warning della riga di comando D9002 : l'opzione sconosciuta '-fno-strict-aliasing' verrà ignorata
cl : warning della riga di comando D9002 : l'opzione sconosciuta '-fvisibility=hidden' verrà ignorata
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(187): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(187): error C2091: la funzione restituisce una funzione
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(187): error C2143: errore di sintassi: ')' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(187): error C2143: errore di sintassi: '{' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(187): error C2059: errore di sintassi: 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(187): error C2059: errore di sintassi: ')'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(202): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(202): error C2091: la funzione restituisce una funzione
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(202): error C2143: errore di sintassi: ')' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(202): error C2143: errore di sintassi: '{' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(202): error C2059: errore di sintassi: 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(202): error C2059: errore di sintassi: ')'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(218): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(218): error C2091: la funzione restituisce una funzione
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(218): error C2143: errore di sintassi: ')' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(218): error C2143: errore di sintassi: '{' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(218): error C2059: errore di sintassi: 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(218): error C2059: errore di sintassi: ')'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(230): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(230): error C2091: la funzione restituisce una funzione
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(230): error C2143: errore di sintassi: ')' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(230): error C2143: errore di sintassi: '{' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(230): error C2059: errore di sintassi: 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(230): error C2059: errore di sintassi: ')'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(255): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(255): error C2091: la funzione restituisce una funzione
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(255): error C2143: errore di sintassi: ')' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(255): error C2143: errore di sintassi: '{' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(255): error C2059: errore di sintassi: 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(255): error C2059: errore di sintassi: ')'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(267): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(267): error C2091: la funzione restituisce una funzione
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(267): error C2143: errore di sintassi: ')' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(267): error C2143: errore di sintassi: '{' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(267): error C2059: errore di sintassi: 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(267): error C2059: errore di sintassi: ')'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(281): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(281): error C2091: la funzione restituisce una funzione
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(281): error C2143: errore di sintassi: ')' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(281): error C2143: errore di sintassi: '{' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(281): error C2059: errore di sintassi: 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(281): error C2059: errore di sintassi: ')'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(364): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(364): error C2091: la funzione restituisce una funzione
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(364): error C2143: errore di sintassi: ')' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(364): error C2143: errore di sintassi: '{' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(364): error C2059: errore di sintassi: 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(364): error C2059: errore di sintassi: ')'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(547): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(547): error C2091: la funzione restituisce una funzione
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(547): error C2143: errore di sintassi: ')' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(547): error C2143: errore di sintassi: '{' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(547): error C2059: errore di sintassi: 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(547): error C2059: errore di sintassi: ')'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(551): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(551): error C2091: la funzione restituisce una funzione
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(551): error C2143: errore di sintassi: ')' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(551): error C2143: errore di sintassi: '{' mancante prima di 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(551): error C2059: errore di sintassi: 'stringa'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(551): error C2059: errore di sintassi: ')'
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(554): error C2143: errore di sintassi: ')' mancante prima di '('
C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\expat.h(554): fatal error C1003: il conteggio degli errori supera 100. Interruzione della compilazione
[3/6] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\cl.exe   -DVER_FILEVERSION=2,5,0,0 -DXML_ENABLE_VISIBILITY=1 -D_CRT_SECURE_NO_WARNINGS -Dexpat_EXPORTS -IC:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\x64-windows-dbg -IC:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   -fno-strict-aliasing -fvisibility=hidden /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    -wd4996 /showIncludes /FoCMakeFiles\expat.dir\lib\xmlrole.c.obj /FdCMakeFiles\expat.dir\ /FS -c C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\xmlrole.c
cl : warning della riga di comando D9002 : l'opzione sconosciuta '-fno-strict-aliasing' verrà ignorata
cl : warning della riga di comando D9002 : l'opzione sconosciuta '-fvisibility=hidden' verrà ignorata
[4/6] C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\cl.exe   -DVER_FILEVERSION=2,5,0,0 -DXML_ENABLE_VISIBILITY=1 -D_CRT_SECURE_NO_WARNINGS -Dexpat_EXPORTS -IC:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\x64-windows-dbg -IC:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP   -fno-strict-aliasing -fvisibility=hidden /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    -wd4996 /showIncludes /FoCMakeFiles\expat.dir\lib\xmltok.c.obj /FdCMakeFiles\expat.dir\ /FS -c C:\Users\Cristiano\Desktop\criss\ORB_SLAM3\Pangolin\scripts\vcpkg\buildtrees\expat\src\R_2_5_0-56671c0753.clean\expat\lib\xmltok.c
cl : warning della riga di comando D9002 : l'opzione sconosciuta '-fno-strict-aliasing' verrà ignorata
cl : warning della riga di comando D9002 : l'opzione sconosciuta '-fvisibility=hidden' verrà ignorata
ninja: build stopped: subcommand failed.

**Comment by LilyWangLL** [comment] 2023-04-12 02:16
Thanks for posting this issue. Duplicate of issue https://github.com/microsoft/vcpkg/issues/24600, #27066, please install English package and rebuild `expat`.

**Comment by LilyWangLL** [comment] 2023-04-26 02:39
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Closed by LilyWangLL** 2023-04-26 02:39 UTC
Labels: category:question
