### ISSUE TITLE
[vtk] Build error

### ISSUE THREAD

**Issue by KirkPen** [microsoft/vcpkg#29680] opened 2023-02-16 01:11 UTC
**Host Environment**
windows 10 pro

**To Reproduce**
vcpkg install vtk[all]
with opencv[cuda,tbb] already installed

**Failure logs**
[issue_body.md](https://github.com/microsoft/vcpkg/files/10750941/issue_body.md)
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/10751951/config-x64-windows-out.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10751952/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/10751953/config-x64-windows-dbg-CMakeCache.txt.log)

```
- Cut and paste the appropriate build messages from the console output.
- D:\Dev\vcpkg>vcpkg install vtk[all] --recurse
Computing installation plan...
The following packages will be built and installed:
  * cgns[core,hdf5,lfs,lfsselector,mpi]:x64-windows -> 4.3.0#3
  * ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-windows -> 5.1.2#4
  * freeglut[core]:x64-windows -> 3.4.0
  * freexl[core]:x64-windows -> 1.0.6#1
  * gdal[core,curl,default-features,expat,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,postgresql,qhull,recommended-features,sqlite3,webp,zstd]:x64-windows -> 3.6.2#2
  * geos[core]:x64-windows -> 3.11.1
  * harfbuzz[core]:x64-windows -> 6.0.0
  * hdf5[core,cpp,parallel,szip,tools,zlib]:x64-windows -> 1.12.2#6
  * icu[core,tools]:x64-windows -> 72.1#3
  * jasper[core,default-features,opengl]:x64-windows -> 4.0.0
  * json-c[core]:x64-windows -> 2022-06-26#2
  * lerc[core]:x64-windows -> 4.0#1
  * libevent[core,thread]:x64-windows -> 2.1.12+20230128
  * libffi[core]:x64-windows -> 3.4.4
  * libgeotiff[core]:x64-windows -> 1.7.1#2
  * libkml[core]:x64-windows -> 1.3.0#11
  * libmysql[core]:x64-windows -> 8.0.20#9
  * libpq[core,lz4,openssl,zlib]:x64-windows -> 14.4#3
  * libspatialite[core,freexl,geocallbacks]:x64-windows -> 5.0.1#9
  * matio[core,hdf5,zlib]:x64-windows -> 1.5.23#2
  * minizip[core]:x64-windows -> 1.2.13
  * mpi[core]:x64-windows -> 1#3
  * msmpi[core]:x64-windows -> 10.1.12498#4
  * netcdf-c[core,dap,hdf5,nczarr,netcdf-4,platform-default-features]:x64-windows -> 4.8.1#2
  * parmetis[core]:x64-windows -> 2022-07-27
  * pcre2[core]:x64-windows -> 10.40#1
  * proj[core,net,tiff]:x64-windows -> 9.1.1
  * python3[core]:x64-windows -> 3.10.7#5
  * qtbase[brotli,concurrent,core,dbus,default-features,doubleconversion,freetype,gui,harfbuzz,icu,jpeg,network,opengl,openssl,pcre2,png,sql,sql-psql,sql-sqlite,testlib,thread,widgets,zstd]:x64-windows -> 6.4.2
  * qtdeclarative[core]:x64-windows -> 6.4.2#1
  * qtimageformats[core,default-features,jasper,tiff,webp]:x64-windows -> 6.4.2
  * qtshadertools[core]:x64-windows -> 6.4.2
  * qttools[assistant,core,designer,linguist]:x64-windows -> 6.4.2#1
  * seacas[core,mpi]:x64-windows -> 2022-11-22#1
  * sqlite3[core,rtree,tool]:x64-windows -> 3.40.1#1
  * uriparser[core]:x64-windows -> 0.9.7
    vtk[all,atlmfc,core,gdal,geojson,mpi,python,qt,utf8,vtkm]:x64-windows -> 9.2.0-pv5.11.0#2
  * vtk-m[core,mpi]:x64-windows -> 1.9.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Kirk\AppData\Local\vcpkg\archives in 2.222 ms. Use --debug to see more details.
Installing 1/38 msmpi:x64-windows...
.......

CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "D:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/Dev/vcpkg/buildtrees/vtk/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Dev\vcpkg\buildtrees\vtk\config-x64-windows-dbg-CMakeCache.txt.log
      D:\Dev\vcpkg\buildtrees\vtk\config-x64-windows-rel-CMakeCache.txt.log
      D:\Dev\vcpkg\buildtrees\vtk\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:202 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)


error: building vtk:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vtk
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[vtk]+Build+error
Include '[vtk] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 959f8e317 2023-02-15 (5 hours ago)
```

**Additional context**
first try had error about missing MFC in Visual Studio 2022 so I added that and it got farther.
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by MonicaLiu0311** [comment] 2023-02-16 08:55
Confirmed, reproduced locally. 

Maybe fixed by #29260.

**Comment by Neumann-A** [comment] 2023-02-16 09:41
No the problem is that vcpkg cannot express the fact that if upstream is build with x than downstream also needs to be build with x. the solution here is to also request the `mpi` feature of `vtk`

**Comment by dg0yt** [comment] 2023-02-16 10:14
Duplicates #22892

**Closed** 2023-02-16 10:59 UTC
Labels: category:port-bug
