### ISSUE TITLE
The release build of SDL2-mixer depends on the debug build of SDL2

### ISSUE THREAD

**Issue by ldicker83** [microsoft/vcpkg#9985] opened 2020-02-09 03:40 UTC
The title basically says it all. The Release builds (both x86 and x64) rely on the debug build of SDL2 (SDL2d.dll not found).

EDIT:
Forgot to mention that I came across #6152 which appears to correct the issue in SDL2-image (I don't see it in that package) but it still appears in SDL2-mixer.

**Comment by DanRStevens** [comment] 2020-02-15 21:28
Setting reference to related issue #9984.

It looks like PR #5948 may have solved this problem.

**Comment by NancyLi1013** [comment] 2020-03-16 09:44
Hi @ldicker83 

Thanks for posting this issue.
Sorry for the late reply. 
Could you please post the fail log about this.
I can build it successfully on my local.

**Comment by NancyLi1013** [comment] 2020-03-25 06:51
This issue should be fixed. I cannot reproduce it on my local.
Please try to update vcpkg to the latest version and build this port again.
Please feel free to reopen this issue if this is still a problem for you.

**Closed by NancyLi1013** 2020-03-25 06:51 UTC
Labels: port bug

**Comment by ldicker83** [comment] 2020-04-08 22:42
It appears to be fixed with the latest sync I tried a few days ago. Thank you for looking into this!
