### ISSUE TITLE
vtk[qt] build failure

### ISSUE THREAD

**Issue by atnTeosit** [microsoft/vcpkg#9451] opened 2019-12-26 16:20 UTC
**Host Environment**
- OS:Windows
- Compiler: Visual Studio 2017

**To Reproduce**
`./vcpkg install vtk[qt]`

**Additional context**
vtkGUISupportQt-8.2 not compiled
workaround:
set(VTK_WITH_QT ON) in ports/vtk/portfile.cmake

**Comment by drescherjm** [comment] 2019-12-26 17:18
I think this is a duplicate of https://github.com/microsoft/vcpkg/issues/9023

**Comment by JackBoosY** [comment] 2020-01-09 09:25
Thanks @drescherjm.
Duplicate with #9023.

**Closed by JackBoosY** 2020-01-09 09:25 UTC
Labels: port bug
