### ISSUE TITLE
[Protobuf] update to <3.19.0>

### ISSUE THREAD

**Issue by GJC1979** [microsoft/vcpkg#23240] opened 2022-02-23 14:22 UTC
Library name: Protobuf

New version number: 3.19.0

Please can upload the update of Protobuf to version 3.19.0

**Comment by JonLiu1993** [comment] 2022-02-24 01:36
Duplicate of #21365, let's track this issue in pr #21365

**Closed by JonLiu1993** 2022-02-24 01:36 UTC
Labels: category:port-update
