### ISSUE TITLE
[openssl:x64-windows] build failure

### ISSUE THREAD

**Issue by bc913** [microsoft/vcpkg#12771] opened 2020-08-05 23:47 UTC
**Host Environment**
- OS: Windows 10 Pro - Version 1909
- Compiler: MSVC 19.27.29110 - MSBUILD version: 16.7.0.37604

**To Reproduce**
- Clone repo under C:/dev/vcpkg
- Run Powershell or Cmd or Developer Cmd Prompt ( does not matter if you run as admin or not)
- Run ./bootstrap-vcpkg.bat -disableMetrics -win64 (does not work w/o arguments, too.)
- (Optional) Run .\vcpkg.exe integrate install
- `./vcpkg install openssl:x64-windows`

**Failure logs** 

**Console output**:

Starting package 1/2: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
Could not locate cached archive: C:\Users\feybo\AppData\Local\vcpkg\archives\76\763c692aa0fb3c54b0957172551f67fa3685b958.zip
-- Downloading https://strawberry.perl.bot/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip...
-- Downloading https://www.openssl.org/source/openssl-1.1.1g.tar.gz...
-- Extracting source C:/dev/vcpkg/downloads/openssl-1.1.1g.tar.gz
-- Using source at C:/dev/vcpkg/buildtrees/openssl-windows/src/openssl-1-bb2a9a5801.clean
-- Downloading http://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win32/nasm-2.14.02-win32.zip...
-- Downloading http://download.qt.io/official_releases/jom/jom_1_1_3.zip...
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: nmake -f makefile install_sw install_ssldirs
    Working Directory: C:/dev/vcpkg/buildtrees/openssl-windows/x64-windows-rel
    Error code: 2
    See logs for more information:
      C:\dev\vcpkg\buildtrees\openssl-windows\build-x64-windows-rel-1-out.log
      C:\dev\vcpkg\buildtrees\openssl-windows\build-x64-windows-rel-1-err.log

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:95 (vcpkg_execute_required_process)
  scripts/ports.cmake:79 (include)

Error: Building package openssl-windows:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl-windows:x64-windows
  Vcpkg version: 2020.06.15-nohash

**build-x64-windows-rel-1-out.log**:

"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe" /                   
depend && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe" /                   _build_libs
	nasm  -Ox -f win64 -DNEAR -g -o engines\e_padlock-x86_64.obj "engines\e_padlock-x86_64.asm"

**build-x64-windows-rel-1-err.log** (I've provided the last meaningful lines. Check the attached file for full content.

engines\e_padlock-x86_64.asm:1168: error: parser: instruction expected
engines\e_padlock-x86_64.asm:1170: warning: `PTR' is not a NASM keyword [-w+ptr]
engines\e_padlock-x86_64.asm:1170: error: comma, colon, decorator or end of line expected after operand
engines\e_padlock-x86_64.asm:1171: error: parser: instruction expected
engines\e_padlock-x86_64.asm:1174: warning: `PTR' is not a NASM keyword [-w+ptr]
engines\e_padlock-x86_64.asm:1174: error: comma, colon, decorator or end of line expected after operand
engines\e_padlock-x86_64.asm:1175: warning: `PTR' is not a NASM keyword [-w+ptr]
engines\e_padlock-x86_64.asm:1175: error: comma, colon, decorator or end of line expected after operand
engines\e_padlock-x86_64.asm:1177: error: parser: instruction expected
engines\e_padlock-x86_64.asm:1178: error: label `padlock_ctr32_encrypt' inconsistently redefined
engines\e_padlock-x86_64.asm:935: note: label `padlock_ctr32_encrypt' originally defined here
engines\e_padlock-x86_64.asm:1178: error: parser: instruction expected
engines\e_padlock-x86_64.asm:1184: error: parser: instruction expected
**engines\e_padlock-x86_64.asm:1185: warning: macro `SEGMENT' exists, but not taking 0 parameters [-w+macro-params]
engines\e_padlock-x86_64.asm:1185: error: parser: instruction expected
engines\e_padlock-x86_64.asm:1187: error: parser: instruction expected
engines\e_padlock-x86_64.asm:1190: error: label `_DATA' inconsistently redefined
engines\e_padlock-x86_64.asm:1185: note: label `_DATA' originally defined here
engines\e_padlock-x86_64.asm:1190: error: parser: instruction expected
engines\e_padlock-x86_64.asm:1191: warning: label alone on a line without a colon might be in error [-w+orphan-labels]
NMAKE : fatal error U1077: 'C:/dev/vcpkg/downloads/tools/nasm/nasm-2.14.02\nasm.EXE' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.27.29110\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.**

**Additional context**
The branch and the packages are already up-to-date. It fails w/ or w/o arguments. It fails for all prompts whether it is run w/ admin privileges or not. When I try to install boost or qt5 w/ x64-windows, it fails at openssl build step as mentioned above.

[build-x64-windows-rel-1-err.log](https://github.com/microsoft/vcpkg/files/5031733/build-x64-windows-rel-1-err.log)
[build-x64-windows-rel-0-err.log](https://github.com/microsoft/vcpkg/files/5031734/build-x64-windows-rel-0-err.log)
[build-x64-windows-rel-0-out.log](https://github.com/microsoft/vcpkg/files/5031735/build-x64-windows-rel-0-out.log)

**Comment by LilyWangL** [comment] 2020-08-06 09:01
Thanks for posting this issue. Closed as duplicate of #9848.

**Closed by LilyWangL** 2020-08-06 09:01 UTC
