### ISSUE TITLE
[flann] Build error on x64-mingw-static

### ISSUE THREAD

**Issue by dongfangZh** [microsoft/vcpkg#42272] opened 2024-11-21 04:47 UTC
Package: flann:x64-mingw-static@2019-04-07#7

**Host Environment**

- Host: x64-windows
- Compiler: GNU 14.2.0
-    vcpkg-tool version: 2024-10-18-e392d7347fe72dff56e7857f7571c22301237ae6
    vcpkg-scripts version: 7fd612ee1 2024-11-05 (2 weeks ago)

**To Reproduce**

`vcpkg install pcl:x64-mingw-static`

**Failure logs**

```
-- Using cached flann-lib-flann-1d04523268c388dabf1c0865d69e1b638c8c7d9d.tar.gz.
-- Cleaning sources at D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg_new/downloads/flann-lib-flann-1d04523268c388dabf1c0865d69e1b638c8c7d9d.tar.gz
-- Applying patch fix-build-error.patch
-- Applying patch fix-dependency-hdf5.patch
-- Applying patch fix_undefined_pot_t.patch
-- Using source at D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean
-- Configuring x64-mingw-static-dbg
-- Configuring x64-mingw-static-rel
-- Building x64-mingw-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j9
    Working Directory: D:/vcpkg_new/buildtrees/flann/x64-mingw-static-dbg
    See logs for more information:
      D:\vcpkg_new\buildtrees\flann\install-x64-mingw-static-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/flann/portfile.cmake:35 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)



```

<details><summary>D:\vcpkg_new\buildtrees\flann\install-x64-mingw-static-dbg-out.log</summary>

```
Change Dir: 'D:/vcpkg_new/buildtrees/flann/x64-mingw-static-dbg'

Run Build Command(s): D:/vcpkg_new/downloads/tools/ninja/1.10.2-windows/ninja.exe -v -v -j9 install
[1/5] C:\mingw64\bin\x86_64-w64-mingw32-g++.exe -D_FLANN_VERSION=1.9.1 -ID:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp -isystem D:/vcpkg_new/installed/x64-mingw-static/include -g   -Wall -Wno-unknown-pragmas -Wno-unused-function -fPIC -MD -MT src/cpp/CMakeFiles/flann_cpp_s.dir/flann/flann_cpp.cpp.obj -MF src\cpp\CMakeFiles\flann_cpp_s.dir\flann\flann_cpp.cpp.obj.d -o src/cpp/CMakeFiles/flann_cpp_s.dir/flann/flann_cpp.cpp.obj -c D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/flann_cpp.cpp
In file included from D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/util/params.h:33,
                 from D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/flann.hpp:42,
                 from D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/flann_cpp.cpp:30:
D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/util/any.h: In member function 'virtual void flann::anyimpl::big_any_policy<T>::static_delete(void**)':
D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/util/any.h:81:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
   81 |         if (* x) delete (* reinterpret_cast<T**>(x)); *x = NULL;
      |         ^~
D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/util/any.h:81:55: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
   81 |         if (* x) delete (* reinterpret_cast<T**>(x)); *x = NULL;
      |                                                       ^
[2/5] C:\WINDOWS\system32\cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E rm -f lib\libflann_cppd.a && C:\mingw64\bin\ar.exe qc lib\libflann_cppd.a  src/cpp/CMakeFiles/flann_cpp_s.dir/flann/flann_cpp.cpp.obj && C:\mingw64\bin\ranlib.exe lib\libflann_cppd.a && cd ."
[3/5] C:\mingw64\bin\x86_64-w64-mingw32-g++.exe -DFLANN_STATIC -D_FLANN_VERSION=1.9.1 -ID:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp -isystem D:/vcpkg_new/installed/x64-mingw-static/include -g   -Wall -Wno-unknown-pragmas -Wno-unused-function -fPIC -MD -MT src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.obj -MF src\cpp\CMakeFiles\flann_s.dir\flann\flann.cpp.obj.d -o src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.obj -c D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/flann.cpp
FAILED: src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.obj 
C:\mingw64\bin\x86_64-w64-mingw32-g++.exe -DFLANN_STATIC -D_FLANN_VERSION=1.9.1 -ID:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp -isystem D:/vcpkg_new/installed/x64-mingw-static/include -g   -Wall -Wno-unknown-pragmas -Wno-unused-function -fPIC -MD -MT src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.obj -MF src\cpp\CMakeFiles\flann_s.dir\flann\flann.cpp.obj.d -o src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.obj -c D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/flann.cpp
In file included from D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/util/params.h:33,
                 from D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/flann.hpp:42,
                 from D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/flann.h:603,
                 from D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/flann.cpp:31:
D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/util/any.h: In member function 'virtual void flann::anyimpl::big_any_policy<T>::static_delete(void**)':
D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/util/any.h:81:9: warning: this 'if' clause does not guard... [-Wmisleading-indentation]
   81 |         if (* x) delete (* reinterpret_cast<T**>(x)); *x = NULL;
      |         ^~
D:/vcpkg_new/buildtrees/flann/src/638c8c7d9d-cbccfeb2cc.clean/src/cpp/flann/util/any.h:81:55: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
   81 |         if (* x) delete (* reinterpret_cast<T**>(x)); *x = NULL;
      |                                                       ^
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.obj: too many sections (130346)
C:\Users\Viking\AppData\Local\Temp\ccMk1jgD.s: Assembler messages:
C:\Users\Viking\AppData\Local\Temp\ccMk1jgD.s: Fatal error: can't write 503 bytes to section .text of src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.obj: 'file too big'
C:/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/as.exe: src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.obj: too many sections (130346)
C:\Users\Viking\AppData\Local\Temp\ccMk1jgD.s: Fatal error: src/cpp/CMakeFiles/flann_s.dir/flann/flann.cpp.obj: file too big
ninja: build stopped: subcommand failed.
```
</details>

**Comment by JonLiu1993** [comment] 2024-11-21 07:59
Duplicate of https://github.com/microsoft/vcpkg/issues/42022

**Closed by JonLiu1993** 2024-11-21 07:59 UTC
Labels: category:community-triplet
