### ISSUE TITLE
[realsense2:x86-windows] build failure - could not find git for clone of libusb

### ISSUE THREAD

**Issue by mediadog** [microsoft/vcpkg#10555] opened 2020-03-25 20:07 UTC
**Host Environment**
- OS: Win7 x64 Enterprise
- Compiler: VS Pro 2017

**To Reproduce**
`./vcpkg install realsens2`

**Failure logs** 
config-x86-windows-out.log contains:

-- libusb not found; using internal version (missing: LIBUSB_LIB LIBUSB_INC) 
CMake Error at D:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/ExternalProject.cmake:2427 (message):
  error: could not find git for clone of libusb
Call Stack (most recent call first):
  D:/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/share/cmake-3.14/Modules/ExternalProject.cmake:3211 (_ep_add_download_command)
  CMake/external_libusb.cmake:3 (ExternalProject_Add)
  CMake/libusb_config.cmake:11 (include)
  src/win7/CMakeLists.txt:11 (include)
  src/CMakeLists.txt:41 (include)
  CMakeLists.txt:56 (include)

**Additional context**

However the stdout of the 'vcpkg install realsense2' command said git was downloaded:

Building package realsense2[core]:x86-windows...
A suitable version of git was not found (required v2.25.1). Downloading portable git v2.25.1...
Downloading git...
  https://github.com/git-for-windows/git/releases/download/v2.25.1.windows.1/PortableGit-2.25.1-32-bit.7z.exe -> D:\vcpkg\downloads\PortableGit-2.25.1-32-bit.7z.exe
Extracting git...
-- Downloading https://github.com/IntelRealSense/librealsense/archive/9f99fa9a509555f85bffc15ce27531aaa6db6f7e.tar.gz...
-- Extracting source D:/vcpkg/downloads/IntelRealSense-librealsense-9f99fa9a509555f85bffc15ce27531aaa6db6f7e.tar.gz

**Comment by LilyWangL** [comment] 2020-03-27 07:46
@mediadog I can't reproduce this issue locally. I sync PR #10550 changes to my local VCPKG and build realsense2 successfully on Windows 7 X64. Could you please provide the all log file config-x86-windows-out.log?

**Comment by mediadog** [comment] 2020-03-28 02:34
My clone of #10550 did build, but I had installed Git so expect it was using that and not doing the git download and use of that local package.  I'll have to uninstall Git and try again, thanks.

**Comment by mediadog** [comment] 2020-03-29 16:58
If git is not already installed, then yes this error still happens.  So not sure why it says it is downloading and extracting git before this and then not using it.

**Comment by LilyWangL** [comment] 2020-03-30 01:57
The PR #10550 has been merged, you can update VCPKG or git clone new VCPKG to rebuild realsense2. Thanks for posting this issue. Please open a new issue if this is still a problem for you.

**Closed by LilyWangL** 2020-03-30 01:57 UTC
Labels: needs-repro
