### ISSUE TITLE
[glad] build failure

### ISSUE THREAD

**Issue by Krophil** [microsoft/vcpkg#15481] opened 2021-01-06 16:48 UTC
**Host Environment**
- OS: Windows 7
- Compiler: cmake 3.19.2
- Vcpkg version: 2020.11.12-nohash

**To Reproduce**
`./vcpkg install glad:x64-windows`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    glad[core]:x64-windows -> 0.1.33-1
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\pierre.brunet\AppData\Local\vcpkg\archives\3c\3c8d06eabe73517e96cbd84c537c32c16ca2bfcb.zip
Starting package 1/1: glad:x64-windows
Building package glad[core]:x64-windows...
-- Note: glad only supports static library linkage. Building static library.
-- Using cached C:/vcpkg/downloads/Dav1dde-glad-de6c39e3040c987323b8ed078c36442f4fb681b3.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/glad/src/2f4fb681b3-78068df8f5.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/Dav1dde-glad-de6c39e3040c987323b8ed078c36442f4fb681b3.tar.gz
-- Applying patch encoding.patch
-- Using source at C:/vcpkg/buildtrees/glad/src/2f4fb681b3-78068df8f5.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.19.2-windows/cmake-3.19.2-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v
 -j13
    Working Directory: C:/vcpkg/buildtrees/glad/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\glad\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/glad/portfile.cmake:38 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)
```

Content of C:\vcpkg\buildtrees\glad\install-x64-windows-dbg-out.log : 
```
[1/4] cmd.exe /C "cd /D C:\vcpkg\buildtrees\glad\src\2f4fb681b3-78068df8f5.clean && C:\vcpkg\downloads\tools\python\python-3.9.0-x64\python.exe -m glad --profile=compatibility --out-path=C:/vcpkg/buildtrees/glad/x64-windows-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"
FAILED: src/glad.c include/glad/glad.h 
cmd.exe /C "cd /D C:\vcpkg\buildtrees\glad\src\2f4fb681b3-78068df8f5.clean && C:\vcpkg\downloads\tools\python\python-3.9.0-x64\python.exe -m glad --profile=compatibility --out-path=C:/vcpkg/buildtrees/glad/x64-windows-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"
ninja: build stopped: subcommand failed.
```

The fact that I still use Windows 7 can be the real issue...

**Comment by NancyLi1013** [comment] 2021-01-07 07:29
Hi @Krophil 

Thanks for posting this issue.

Sorry, I cannot reproduce this on my local. I'm also not sure what happened from above information.

Could you please hep provide `config-x64-windows-out.log`?

**Comment by Krophil** [comment] 2021-01-07 09:01
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5780540/config-x64-windows-out.log)
Hi @NancyLi1013 
There it is. Sorry, I'm not sure it helps much...

**Comment by NancyLi1013** [comment] 2021-01-07 09:58
Could you please also attach _install-x64-windows-dbg-out.log_? Or please help confirm if you have provided the full log in install-x64-windows-dbg-out.log.

Thanks.

**Comment by Krophil** [comment] 2021-01-07 10:48
Yes, sorry it was the same content. Here it is to confirm.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5781118/install-x64-windows-dbg-out.log)

**Comment by NancyLi1013** [comment] 2021-01-08 06:59
Sorry, I cannot get any conclusion why you build failed according to current information.

Could you please try to comment out `PREFER_NINJA` in `vcpkg_configure_cmake() `to rebuild this port?

**Comment by NancyLi1013** [comment] 2021-01-13 07:59
@Krophil 

Can you build successfully after removing `PREFER_NINJA `?

**Comment by Krophil** [comment] 2021-01-13 11:55
Hi, I'm so sorry for the delay. I was working on another project and could not find the time to test it. I'm gonna try that this evening. Thank you

**Comment by NancyLi1013** [comment] 2021-02-04 10:32
@Krophil 

Sorry for my mistake. I missed your build environment Windows 7 before this.

Could you please run the command `cmd.exe /C "cd /D C:\vcpkg\buildtrees\glad\src\2f4fb681b3-78068df8f5.clean && C:\vcpkg\downloads\tools\python\python-3.9.0-x64\python.exe -m glad --profile=compatibility --out-path=C:/vcpkg/buildtrees/glad/x64-windows-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"`  on your machine?

On my Windows 7 machine, it failed due to this:

`the program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer`

**Comment by Krophil** [comment] 2021-02-04 10:54
@NancyLi1013 Oh thank you ! Indeed, I have the same error. I tried to search for a solution in 10 min but I haven't found a solution for the moment. I'll get back to you if I find something. Thank you, at least I have a lead

**Comment by Fedr** [comment] 2021-12-01 13:59
I have the same issue with GLAD on Windows 10 with the latest vcpkg:
```
Starting package 104/128: glad:x64-windows-meshrus
Building package glad[core,loader]:x64-windows-meshrus...
-- Note: glad only supports static library linkage. Building static library.
-- Downloading https://github.com/Dav1dde/glad/archive/7ece538856bf124d798ab323c8e1e64ebb83cb50.tar.gz -> Dav1dde-glad-7ece538856bf124d798ab323c8e1e64ebb83cb50.tar.gz...
-- Extracting source C:/lib/vcpkg/downloads/Dav1dde-glad-7ece538856bf124d798ab323c8e1e64ebb83cb50.tar.gz
-- Applying patch encoding.patch
-- Applying patch find_python.patch
-- Using source at C:/lib/vcpkg/buildtrees/glad/src/4ebb83cb50-009ec283eb.clean
-- This version of glad uses the compatibility profile. To use the core profile instead, create an overlay port of this with GLAD_PROFILE set to 'core' or set GLAD_PROFILE to 'core' in a custom triplet.
-- This recipe is at C:/lib/vcpkg/ports/glad
-- See the overlay ports documentation at https://github.com/microsoft/vcpkg/blob/master/docs/specifications/ports-overlay.md
-- Found external ninja('1.10.2').
-- Configuring x64-windows-meshrus
-- Building x64-windows-meshrus-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/lib/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j25
    Working Directory: C:/lib/vcpkg/buildtrees/glad/x64-windows-meshrus-dbg
    See logs for more information:
      C:\lib\vcpkg\buildtrees\glad\install-x64-windows-meshrus-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:102 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:41 (vcpkg_cmake_build)
  ports/glad/portfile.cmake:141 (vcpkg_cmake_install)
  scripts/ports.cmake:142 (include)


Error: Building package glad:x64-windows-meshrus failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+glad
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[glad]+Build+error
including:
  package: glad[core,loader]:x64-windows-meshrus -> 0.1.34#3
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: 1b664707c 2021-11-30 (11 hours ago)
```

The contents of install-x64-windows-meshrus-dbg-out.log:
```
[1/4] cmd.exe /C "cd /D C:\lib\vcpkg\buildtrees\glad\src\4ebb83cb50-009ec283eb.clean && C:\Windows\python.exe -m glad --profile=compatibility --out-path=C:/lib/vcpkg/buildtrees/glad/x64-windows-meshrus-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"
FAILED: include/glad/glad.h src/glad.c C:/lib/vcpkg/buildtrees/glad/x64-windows-meshrus-dbg/include/glad/glad.h C:/lib/vcpkg/buildtrees/glad/x64-windows-meshrus-dbg/src/glad.c 
cmd.exe /C "cd /D C:\lib\vcpkg\buildtrees\glad\src\4ebb83cb50-009ec283eb.clean && C:\Windows\python.exe -m glad --profile=compatibility --out-path=C:/lib/vcpkg/buildtrees/glad/x64-windows-meshrus-dbg --api= --generator=c-debug --extensions= --spec=gl --reproducible"
ninja: build stopped: subcommand failed.
```

Can I help you somehow with the reproduction of this issue?

**Comment by LilyWangLL** [comment] 2021-12-02 09:08
I will confirm this issue soon.

**Comment by LilyWangLL** [comment] 2021-12-14 09:53
@Fedr Since This is by design. VCPKG use `vcpkg_find_acquire_program(PYTHON3)` in glad's portfile.cmake, `vcpkg_find_acquire_program` will first use python which download be user.

**Comment by FrankXie05** [comment] 2022-01-28 10:04
@Krophil Is still work for this issue? Make sure you are using the latest vcpkg. Please reply me.

**Comment by Krophil** [comment] 2022-01-28 13:50
Hi
I'm sorry but i've changed my system and don't use vcpkg anymore. Maybe someone else can try that...
I'll be in touch if I retry that.

Le 28 janvier 2022 11:04:39 GMT+01:00, Frank ***@***.***> a écrit :
***@***.*** Is still work for this issue? Make sure you are using the latest vcpkg. Please reply me.

**Comment by HexDecimal** [comment] 2022-11-09 21:33
So when installing GLAD it calls `vcpkg_find_acquire_program(PYTHON3)` and the version that installs is Python 3.10.

Python dropped support for Windows 7 after Python 3.8.  So it'd make sense that Python 3.9 or later would crash with missing runtime libraries when run on Windows 7.

**Comment by LilyWangLL** [comment] 2023-04-20 09:29
Python 3.9 and above do not support Windows 7, so I am closing this issue for now.

**Closed by LilyWangLL** 2023-04-20 09:29 UTC
Labels: category:question
