### ISSUE TITLE
VTK uses vcpkg to compile and display blurry screen on the system running on the VMWare

### ISSUE THREAD

**Issue by WangZP10969** [microsoft/vcpkg#23071] opened 2022-02-13 04:44 UTC
**Describe the bug**
VTK uses vcpkg to compile and display blurry screen on VMWare, but directly using the same version of VTK to compile, the display is normal.

**Environment**
- OS: Windows10 
- Compiler: Visual Studio 2022 17.0.6

**To Reproduce**
1.Compile and generate VTK library with vcpkg
.\vcpkg install vtk:x64-windows
\vcpkg export vtk:x64-windows --raw
2. Generate vtk library directly using vtk9.0.3 source code
https://github.com/Kitware/VTK/releases/tag/v9.0.3
3. Test Cylinder routines separately in VMWare
[Cylinder.zip](https://github.com/microsoft/vcpkg/files/8054975/Cylinder.zip)

**Expected behavior**
vcpkg compilation on virtual machine
![image](https://user-images.githubusercontent.com/47802547/153738941-4a8b8c07-b95a-46ec-8e80-bd7d7834c698.png)
Compile directly with vtk9.0.3 source code
![image](https://user-images.githubusercontent.com/47802547/153739033-298a0ba9-de2d-40b6-a88b-a108e494c686.png)

**Failure logs** 
-(please attached failure logs)

**Additional context**
I covered the header file, lib and dll compiled with vtk source code into the package exported by vcpkg, and it can also be displayed normally.
![image](https://user-images.githubusercontent.com/47802547/153739336-aa862f05-aefc-4e8b-9516-20cc18047193.png)

**Comment by Osyotr** [comment] 2022-02-13 14:48
Maybe if you build with opengl feature, it'll work:
`vcpkg install vtk[opengl]`

**Comment by WangZP10969** [comment] 2022-02-13 16:43
> Maybe if you build with opengl feature, it'll work: `vcpkg install vtk[opengl]`

@Osyotr I tried it and it didn't work, the following is the compilation record.
[vcpkg.txt](https://github.com/microsoft/vcpkg/files/8056101/vcpkg.txt)
It's a good idea though, I'll try multiple modules and see if that makes a difference.
Thank you for your suggestion.

**Comment by JackBoosY** [comment] 2022-02-14 03:09
This problem should be caused by an array/pointer out of bounds somewhere in the vtk rendering code. Needs digging into the code.

**Comment by WangZP10969** [comment] 2022-02-14 04:43
> This problem should be caused by an array/pointer out of bounds somewhere in the vtk rendering code. Needs digging into the code.

@JackBoosY To add, this may be related to the rendering of the window itself, because even if no objects are displayed, such a blurry screen will still appear.

**Comment by JackBoosY** [comment] 2022-02-14 06:04
I would like to report this to vtk side, since I don't use vtk before.

**Comment by WangZP10969** [comment] 2022-02-15 01:45
@Neumann-A 
Thank you for your suggestion
1. For compiling with source code, I only added support for mfc, and modified debug_postfix and install paths
For compiling with vcpkg, I installed vtk[atlmfc,opengl] using the current master
2. I'm not sure what the opengl driver you are referring to, the display settings I see from the system settings are shown in the picture below
![image](https://user-images.githubusercontent.com/47802547/153976747-b5ae9717-0ad3-431b-8df5-0526034a6c05.png)
![image](https://user-images.githubusercontent.com/47802547/153976933-45646827-5c93-4c5f-9e5d-fae2edebff3b.png)
3. I will try, I have never used mesa before, I think I need some time to learn how to use it first

**Comment by WangZP10969** [comment] 2022-02-15 17:20
I tested it, compile directly from source code: 
Compiling with the vtk source code downloaded by vcpkg will cause a blurry screen
Kitware-VTK-2959413ff190bc6e3ff40f5b6c1342edd2e5233f.tar.gz
Using the mirror on github will not
https://github.com/Kitware/VTK/releases/tag/v9.0.3

**Comment by Neumann-A** [comment] 2022-02-15 23:21
Is it fixed if you build v9.1.0? If yes we could try to find the patch/mr which fixes it (or broke it) and integrate that into vcpkg.

**Comment by WangZP10969** [comment] 2022-02-16 01:11
> Is it fixed if you build v9.1.0? If yes we could try to find the patch/mr which fixes it (or broke it) and integrate that into vcpkg. 

@Neumann-A Where of source code will be used on vcpkg？Please give me a link about it.

**Comment by JackBoosY** [comment] 2022-02-16 02:36
https://github.com/microsoft/vcpkg/blob/016788b220b5063fa5e73e6f7ad56283d239727a/ports/vtk/portfile.cmake#L7-L12

**Comment by WangZP10969** [comment] 2022-02-16 06:02
I use the path in the update branch of vtk9.1.0 #23057  for testing, and it is normally.
https://github.com/raahilsha-z/vcpkg/blob/d5b79d0adb85e67338d42d5456a9aa77c9020fc9/ports/vtk/portfile.cmake#L7-L12
https://github.com/Kitware/VTK/archive/285daeedd58eb890cb90d6e907d822eea3d2d092.tar.gz 
![image](https://user-images.githubusercontent.com/47802547/154201475-5f3c2a17-035c-498b-a4e8-df5855e01078.png)

Using vcpkg master, will be blurry.
https://github.com/Kitware/VTK/archive/2959413ff190bc6e3ff40f5b6c1342edd2e5233f.tar.gz 
![image](https://user-images.githubusercontent.com/47802547/154205684-4dd20065-52d9-4333-823c-20793a2bdb08.png)

**Comment by JackBoosY** [comment] 2022-02-16 07:19
Does this issue also occur on the local machine?

**Comment by WangZP10969** [comment] 2022-02-16 07:21
> Does this issue also occur on the local machine?

@JackBoosY No, none of the vtk I've tested have had problems on the local system so far

**Comment by JackBoosY** [comment] 2022-02-16 07:29
> @JackBoosY No, none of the vtk I've tested had problems on the local machine so far. Using the executable file generated by release, there will be a blurry screen in VMWare, but it will be displayed normally when copied to the local machine

I'm guessing you are building vtk and the apps locally and using them in the virtual machine. So this issue is caused due to the inconsisten opengl driver between on the local and the virtual machine.

**Comment by WangZP10969** [comment] 2022-02-16 07:37
> I'm guessing you are building vtk and the apps locally and using them in the virtual machine. So this issue is caused due to the inconsisten opengl driver between on the local and the virtual machine.
@JackBoosY 
No, I compile and develop completely in vmware, but due to display problems, I need to copy the executable file to the local machine to see the effect.
My local machine doesn't have any development environment installed and can only execute executable files

**Comment by JackBoosY** [comment] 2022-02-16 07:40
Can you please also report this to the upstream first?

**Comment by WangZP10969** [comment] 2022-02-16 07:45
I will, I have only asked in the vtk forum before, not directly on vtk's gitlab.
https://discourse.vtk.org/t/display-based-on-vtk-cannot-be-displayed-normally-on-vmware-virtual-machine/7586

It seems like this is a version-specific issue, I think it should be sufficient to provide a link to the source code and a way to reproduce the issue on vtk.

**Comment by WangZP10969** [comment] 2022-02-17 04:23
Add
Mesa3D is working
https://github.com/pal1000/mesa-dist-win/#installation-and-usage
Using the MSVC package of Mesa3D for configuration, and turning off the 3D acceleration of the VM is effective, but the display efficiency will be much slower
![image](https://user-images.githubusercontent.com/47802547/154404939-7cd2e013-e930-4dc6-926e-866dc744e27a.png)

**Comment by JackBoosY** [comment] 2022-02-17 07:02
> Add Mesa3D is working https://github.com/pal1000/mesa-dist-win/#installation-and-usage Using the MSVC package of Mesa3D for configuration, and turning off the 3D acceleration of the VM is effective, but the display efficiency will be much slower

That's just avoid this issue, and it maybe a upstream bug.

**Comment by FrankXie05** [comment] 2022-03-03 05:48
@WangZP10969 Is still work for this issue? Looks like upstream has responded.

**Comment by WangZP10969** [comment] 2022-03-04 23:19
> @WangZP10969 Is still work for this issue? Looks like upstream has responded.

I just saw it, I will respond later

**Comment by JackBoosY** [comment] 2022-03-07 09:27
According to the upstream reply, I think I can close this issue now.

**Closed by JackBoosY** 2022-03-07 09:27 UTC
Labels: category:question
