### ISSUE TITLE
[vcpkg-cmake-config] Wrong *Config.cmake files for CMake 3.29.1

### ISSUE THREAD

**Issue by SimiPro** [microsoft/vcpkg#37968] opened 2024-04-04 10:51 UTC
**Describe the bug**
Suddenly some of the libraries i use: tinyobjloader, tesseract, effolkronium_random have a wrong path in their corresponding *Config.cmake file. 

The vcpkg phase works fine and then when I try to do find_package it crashes usually out of the *Config.cmake file from functions such as set_and_check.  

**Environment**
- OS: Linux
- Compiler: revision gcc-11

**To Reproduce**
1. ./vcpkg install effolkronium-random ( I used manifest mode) 
2. find_package(effolkronium_random CONFIG REQUIRED)
3. see error

You can also checkout this repo: https://github.com/SimiPro/starter-cmake-vcpkg-simple 
and it crashes when you build the target app1. 

But if you comment out the "find_package(effolkronium_random CONFIG REQUIRED)" in the apps/app1/CMakeLists.txt
it works. 

**Expected behavior**
No error

**Failure logs**
[cmake] CMake Error at out/build/dev-debug-test/vcpkg_installed/x64-linux/share/effolkronium_random/effolkronium_randomConfig.cmake:11 (message):
[cmake]   File or directory
[cmake]   /home/simi/projects/starter_cmake_vcpkg/out/build/dev-debug-test/vcpkg_installed/x64-linux/share/include
[cmake]   referenced by variable EFFOLKRONIUM_RANDOM_INCLUDE_DIR does not exist !
[cmake] Call Stack (most recent call first):
[cmake]   out/build/dev-debug-test/vcpkg_installed/x64-linux/share/effolkronium_random/effolkronium_randomConfig.cmake:26 (set_and_check)
[cmake]   out/build/dev-debug-test/_deps/vcpkg-src/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
[cmake]   libs/lib1/CMakeLists.txt:11 (find_package)

**Additional context**

I can fix them. Usually the path is one to deep or one to less deep. But obviously after each configure i have to re-fix it. 

concrete example would be the path effolkronium_randomConfig.cmake 
this line: 
```get_filename_component(PACKAGE_${CMAKE_FIND_PACKAGE_NAME}_COUNTER_1 "${CMAKE_CURRENT_LIST_DIR}/../" ABSOLUTE)```

Should be: ```get_filename_component(PACKAGE_${CMAKE_FIND_PACKAGE_NAME}_COUNTER_1 "${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)```

You can also see the error in the github action on the project: 
https://github.com/SimiPro/starter-cmake-vcpkg-simple/actions/runs/8553715519/job/23437459032

**Comment by yhyu13** [comment] 2024-04-04 13:21
Hi,

My vcpkg fork is a bit old 53bef8994c541b6561884a8395ea35715ece75db but having a similar problem just poped out today!

I am having similar problem with `vckpkg install opentelementry-cpp` on linux-64. Instead of missing one `../`, my case was having one extra `../`:

Error
```
CMake Error at Build/Release/vcpkg_installed/x64-linux/share/absl/abslConfig.cmake:16 (message):
  File or directory
  /home/hangyu5/Documents/Gitrepo-My/HLVM-Engine/Engine/Source/Common/Build/Release/vcpkg_installed/include
  referenced by variable OPENTELEMETRY_CPP_INCLUDE_DIRS does not exist !
```

Where `Build/Release/vcpkg_installed/x64-linux/share/absl/abslConfig.cmake:16` reads as 

```
get_filename_component(PACKAGE_${CMAKE_FIND_PACKAGE_NAME}_COUNTER_1 "${CMAKE_CURRENT_LIST_DIR}/../../../" ABSOLUTE)
```

but it should be `"${CMAKE_CURRENT_LIST_DIR}/../../" ABSOLUTE)`. The errorneous cmake config has ignored the x64-linux directory

Note, my build directory passed to cmake binary is ./Build/Release. I'm not sure if vcpkg has handled these path correctly.

Thanks!

**Comment by dg0yt** [comment] 2024-04-04 17:27
Does CMake 3.29 generate different config files? It smells like `vcpkg_cmake_config_fixup` no longer correctly handling moving the directory to `share`.

**Comment by m-kuhn** [comment] 2024-04-04 17:31
I discover https://github.com/Kitware/CMake/releases/tag/v3.29.1 was released yesterday

**Comment by SimiPro** [comment] 2024-04-04 17:37
> Does CMake 3.29 generate different config files? It smells like `vcpkg_cmake_config_fixup` no longer correctly handling moving the directory to `share`.

Yea you are absolutely right!

https://github.com/SimiPro/starter-cmake-vcpkg-simple/actions/runs/8558878135/job/23454354767

Fixing the cmake version to ~3.28 we build successfully. I don't remember updating, thanks for the help! 

I think we should still keep this issue open to fix it for 3.29 ?

**Comment by m-kuhn** [comment] 2024-04-04 17:42
3.29.0 is also fine, just https://github.com/opengisch/QField/actions/runs/8558906456/job/23454442829?pr=5149 goes further than tiff

**Comment by m-kuhn** [comment] 2024-04-04 22:09
It would be nice to open an upstream issue, but my inexistant knowledge about the construct `${PACKAGE_${CMAKE_FIND_PACKAGE_NAME}_COUNTER_1}` doesn't allow me to come up with a wording

**Comment by dg0yt** [comment] 2024-04-05 04:28
I don't think it is fair to attribute this to CMake. That tool doesn't do anything wrong this time. (But they really shouldn't change it in patch releases.) It is `vcpkg_cmake_config_fixup` which promises to be able to move cmake config.

**Comment by WangWeiLin-MV** [comment] 2024-04-07 03:56
`CMake` regression in `3.29.1` at [Kitware - CMake - !9390](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9390).

**Comment by teo-tsirpanis** [comment] 2024-04-09 15:37
Will be fixed by #38078.

**Comment by dg0yt** [comment] 2024-04-10 00:20
> It would be nice to open an upstream issue, but my inexistant knowledge about the construct `${PACKAGE_${CMAKE_FIND_PACKAGE_NAME}_COUNTER_1}` doesn't allow me to come up with a wording

For the record https://gitlab.kitware.com/cmake/cmake/-/issues/25873

**Comment by bradking** [comment] 2024-04-11 15:09
CMake 3.29.2 [reverts](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9420) the change.

**Comment by m-kuhn** [comment] 2024-04-11 16:09
> CMake 3.29.2 [reverts](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9420) the change.

Shall we close or will this be an issue again with 3.30?

**Comment by bradking** [comment] 2024-04-11 16:24
I suggest closing this for now.  The change will likely not be restored by 3.30 in the same way.  [CMake Issue 25827](https://gitlab.kitware.com/cmake/cmake/-/issues/25827) tracks the problem originally motivating the change.

**Comment by WangWeiLin-MV** [comment] 2024-04-12 02:07
Since `CMake` version `3.29.2` reverted these changes in [Kitware -CMake - 9420](https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9420), closed this issue.

**Closed by WangWeiLin-MV** 2024-04-12 02:07 UTC
Labels: category:port-bug
