### ISSUE TITLE
Feature request to specify version when try to install a package

### ISSUE THREAD

**Issue by JasonYang-MSFT** [microsoft/vcpkg#5040] opened 2018-12-27 07:09 UTC
`vcpkg install cpprestsdk` will only able to install the newest version of cpprestsdk.
But sometimes user wants to install a specific version which may already run on customer's production for a very long time.

**Comment by LilyWangL** [comment] 2019-12-11 09:46
Thanks for posting this issue. Closed as duplicate of #1681.

**Closed by LilyWangL** 2019-12-11 09:46 UTC
Labels: vcpkg feature
