### ISSUE TITLE
[zydis] Update to latest version

### ISSUE THREAD

**Issue by 0xAL3INO** [microsoft/vcpkg#30383] opened 2023-03-23 13:37 UTC
Hi, the [ZYDIS ](https://github.com/zyantific/zydis/tree/5488b7caba739a89febe3b1a83cc86d6ec136cbb)vcpkg version seems to be out of date. Please fix =]

**Comment by JonLiu1993** [comment] 2023-04-13 09:59
Duplicate of https://github.com/microsoft/vcpkg/issues/28301

**Closed by JonLiu1993** 2023-04-13 09:59 UTC
Labels: category:port-update
