### ISSUE TITLE
[abseil] Build error

### ISSUE THREAD

**Issue by compoundradius** [microsoft/vcpkg#29305] opened 2023-01-31 00:11 UTC
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Windows 10
- Compiler: revision
Visual Studio Community 2022

**To Reproduce**

`./vcpkg install grpc`

-- Downloading https://github.com/abseil/abseil-cpp/archive/8c0b94e793a66495e0b1f34a5eb26bd7dc672db0.tar.gz -> abseil-abseil-cpp-8c0b94e793a66495e0b1f34a5eb26bd7dc672db0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/abseil/abseil-cpp/archive/8c0b94e793a66495e0b1f34a5eb26bd7dc672db0.tar.gz
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/abseil/abseil-cpp/archive/8c0b94e793a66495e0b1f34a5eb26bd7dc672db0.tar.gz
File: C:\dev\vcpkg\downloads\abseil-abseil-cpp-8c0b94e793a66495e0b1f34a5eb26bd7dc672db0.tar.gz.8904.part
Expected hash: a076c198103dc5cf22ac978fe7754dd34cb2e782d7db1c2c98393c94639e461bfe31b10c0663f750f743bc1c0c245fd4b6115356f136fe14bd036d267caf2a8b
Actual hash: d794ac35028ac5adfd4e12fa5973472b8230f090c6408af47571daf837e824e8de4ab89f9f96e5be4bb7dfe264c70470857097a563c260c4a4c86bfa3b6fe554
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 105 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 595.1 ms (594993 us)
- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by BillyONeal** [comment] 2023-01-31 00:33
Duplicate of https://github.com/microsoft/vcpkg/issues/29288

**Closed by BillyONeal** 2023-01-31 00:33 UTC
Labels: category:port-bug
