### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by alLiucb** [microsoft/vcpkg#40995] opened 2024-09-15 04:36 UTC
Package: openssl:x64-windows@3.3.2#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.41.34120.0
-    vcpkg-tool version: 2024-08-01-fd884a0d390d12783076341bd43d77c3a6a15658
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install boost:x64-windows`

**Failure logs**

```
-- Using cached openssl-openssl-210dc9a50dfd99caa1cf7c3d2fa42850124b1bbc.patch.
-- Using cached openssl-openssl-openssl-3.3.2.tar.gz.
-- Extracting source D:/vcpkg-master/downloads/openssl-openssl-openssl-3.3.2.tar.gz
-- Applying patch cmake-config.patch
-- Applying patch command-line-length.patch
-- Applying patch script-prefix.patch
-- Applying patch asm-armcap.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Applying patch D:/vcpkg-master/downloads/openssl-openssl-210dc9a50dfd99caa1cf7c3d2fa42850124b1bbc.patch
-- Using source at D:/vcpkg-master/buildtrees/openssl/src/nssl-3.3.2-515f0a0017.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "D:/visual studio2019/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: D:/vcpkg-master/buildtrees/openssl/x64-windows-dbg
    See logs for more information:
      D:\vcpkg-master\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log
      D:\vcpkg-master\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:74 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:76 (include)
  scripts/ports.cmake:192 (include)



```

<details><summary>D:\vcpkg-master\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log</summary>

```
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
NMAKE : fatal error U1077: '"D:\visual studio2019\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"D:\\vcpkg-master\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"D:\\vcpkg-master\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"D:\\vcpkg-master\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"D:\visual studio2019\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs' : return code '0x2'
Stop.
```
</details>

<details><summary>D:\vcpkg-master\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log</summary>

```
	"D:\visual studio2019\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\nmake.exe" /LU                 depend
	"D:\visual studio2019\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs
	"D:\visual studio2019\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"D:\\vcpkg-master\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"D:\\vcpkg-master\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"D:\\vcpkg-master\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c"
cversion.c
crypto\cversion.c(60): warning C4129: 'V': unrecognized character escape sequence
crypto\cversion.c(60): warning C4129: 'T': unrecognized character escape sequence
crypto\cversion.c(60): warning C4129: 'M': unrecognized character escape sequence
crypto\cversion.c(60): warning C4129: 'H': unrecognized character escape sequence
crypto\cversion.c(60): warning C4129: 'c': unrecognized character escape sequence
crypto\cversion.c(60): error C2143: syntax error: missing ';' before 'constant'
crypto\cversion.c(60): error C2143: syntax error: missing ';' before 'string'
```
</details>

**Comment by alLiucb** [comment] 2024-09-15 04:38
Please ignore "D:\visual studio2019", as this path actually contains my installation of VS2022.

**Comment by greenozon** [comment] 2024-09-16 20:35
just gave it a try and was not able to reproduce your issue...
maybe the issue is up to spaces in the path?

```
c:\Dev\vcpkg>vcpkg install openssl
Computing installation plan...
The following packages will be built and installed:
    openssl:x64-windows@3.3.2#1
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Dev/VS2019/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\user\AppData\Local\vcpkg\archives in 174 us. Use --debug to see more details.
Installing 1/1 openssl:x64-windows@3.3.2#1...
Building openssl:x64-windows@3.3.2#1...
-- Downloading https://github.com/openssl/openssl/commit/210dc9a50dfd99caa1cf7c3d2fa42850124b1bbc.patch?full_index=1 -> openssl-openssl-210dc9a50dfd99caa1cf7c3d2fa42850124b1bbc.patch...
-- Downloading https://github.com/openssl/openssl/archive/openssl-3.3.2.tar.gz -> openssl-openssl-openssl-3.3.2.tar.gz...
-- Extracting source C:/Dev/vcpkg/downloads/openssl-openssl-openssl-3.3.2.tar.gz
-- Applying patch cmake-config.patch
-- Applying patch command-line-length.patch
-- Applying patch script-prefix.patch
-- Applying patch asm-armcap.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Applying patch C:/Dev/vcpkg/downloads/openssl-openssl-210dc9a50dfd99caa1cf7c3d2fa42850124b1bbc.patch
-- Using source at C:/Dev/vcpkg/buildtrees/openssl/src/nssl-3.3.2-515f0a0017.clean
-- Downloading https://github.com/StrawberryPerl/Perl-Dist-Strawberry/releases/download/SP_54001_64bit_UCRT/strawberry-perl-5.40.0.1-64bit-portable.zip -> strawberry-perl-5.40.0.1-64bit-portable.zip..
.
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Prerunning x64-windows-rel
-- Building x64-windows-rel
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows/lib/pkgconfig/libcrypto.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows/lib/pkgconfig/libssl.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows/lib/pkgconfig/openssl.pc
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.2.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.3-3-x86_64.pkg.tar.zst.
-- Using msys root at C:/Dev/vcpkg/downloads/tools/msys2/1e74ca60daa10104
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows/debug/lib/pkgconfig/libcrypto.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows/debug/lib/pkgconfig/libssl.pc
-- Fixing pkgconfig file: C:/Dev/vcpkg/packages/openssl_x64-windows/debug/lib/pkgconfig/openssl.pc
-- Installing: C:/Dev/vcpkg/packages/openssl_x64-windows/share/openssl/usage
-- Installing: C:/Dev/vcpkg/packages/openssl_x64-windows/share/openssl/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 3.1 s.
Elapsed time to handle openssl:x64-windows: 7.8 min
openssl:x64-windows package ABI: 68ae4d5b14429f5679b8a223923e884064f1439bb622c5cb5f68011f40ab106f
Total install time: 7.8 min
openssl is compatible with built-in CMake targets:

  find_package(OpenSSL REQUIRED)
  target_link_libraries(main PRIVATE OpenSSL::SSL)
  target_link_libraries(main PRIVATE OpenSSL::Crypto)

```

**Comment by alLiucb** [comment] 2024-09-18 08:55
I don't think that's the reason, there's [the same problem](https://github.com/microsoft/vcpkg/issues/39912#issue-2407467122) here @greenozon

**Comment by greenozon** [comment] 2024-09-18 08:58
there are 2 clues from that issue:

1)  It is recommended that you use the VS Enterprise Edition.
2)  it is a problem with handling space characters in VS path.

which one do you mean

**Comment by JonLiu1993** [comment] 2024-09-18 09:28
Duplicate of #39912, Let's focus on tracking this issue in #39912. I think you can try to install it once without spaces in VS path.

**Closed by JonLiu1993** 2024-09-18 09:28 UTC
Labels: category:question
