### ISSUE TITLE
[azure-kinect-sensor-sdk] build failure

### ISSUE THREAD

**Issue by Crazysiri** [microsoft/vcpkg#12995] opened 2020-08-19 07:47 UTC
**Host Environment**
- OS: [Ubuntu]

**To Reproduce**
`./vcpkg install azure-kinect-sensor-sdk`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    azure-kinect-sensor-sdk[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
Starting package 1/1: azure-kinect-sensor-sdk:x64-linux
Building package azure-kinect-sensor-sdk[core]:x64-linux...
Could not locate cached archive: /home/benebot/.cache/vcpkg/archives/a9/a98e910b32ea3d3d79dd203f9f798ea7c1f8542c.zip
-- Using cached /home/benebot/vcpkg/downloads/microsoft-Azure-Kinect-Sensor-SDK-v1.4.0-alpha.0.tar.gz
-- Cleaning sources at /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-30d96b3859.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/benebot/vcpkg/downloads/microsoft-Azure-Kinect-Sensor-SDK-v1.4.0-alpha.0.tar.gz
-- Applying patch fix-builds.patch
-- Applying patch disable-c4275.patch
-- Applying patch fix-dependency-imgui.patch
-- Using source at /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-30d96b3859.clean
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /home/benebot/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-30d96b3859.clean -DK4A_BUILD_DOCS=OFF -DBUILD_TOOLS=OFF -DK4A_SOURCE_LINK=OFF -DK4A_MTE_VERSION=ON -DBUILD_EXAMPLES=OFF -DWITH_TEST=OFF -DIMGUI_EXTERNAL_PATH=/home/benebot/vcpkg/installed/x64-linux/include/bindings -DCMAKE_MAKE_PROGRAM=/home/benebot/vcpkg/downloads/tools/ninja-1.10.0-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/benebot/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/benebot/vcpkg -D_VCPKG_INSTALLED_DIR=/home/benebot/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/benebot/vcpkg/packages/azure-kinect-sensor-sdk_x64-linux/debug
    Working Directory: /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/config-x64-linux-dbg-out.log
      /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:309 (vcpkg_execute_required_process)
  ports/azure-kinect-sensor-sdk/portfile.cmake:24 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package azure-kinect-sensor-sdk:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: azure-kinect-sensor-sdk:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.
```
**Additional context**
```
CMake Error at /home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake:455 (_find_package):
  Could not find a package configuration file provided by "gtest" with any of
  the following names:

    gtestConfig.cmake
    gtest-config.cmake

  Add the installation prefix of "gtest" to CMAKE_PREFIX_PATH or set
  "gtest_DIR" to a directory containing one of the above files.  If "gtest"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:104 (find_package)
```

**Comment by JackBoosY** [comment] 2020-08-19 07:49
Please provide failure log:
_/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/config-x64-linux-dbg-out.log_
_/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/config-x64-linux-dbg-err.log_

**Comment by Crazysiri** [comment] 2020-08-19 07:50
config-x64-linux-dbg-out.log:

-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc - works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ - works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: x86_64
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Success
-- Configuring incomplete, errors occurred!
See also "/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/x64-linux-dbg/CMakeFiles/CMakeOutput.log".

**Comment by Crazysiri** [comment] 2020-08-19 07:51
config-x64-linux-dbg-err.log:
CMake Error at /home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake:455 (_find_package):
  Could not find a package configuration file provided by "gtest" with any of
  the following names:

    gtestConfig.cmake
    gtest-config.cmake

  Add the installation prefix of "gtest" to CMAKE_PREFIX_PATH or set
  "gtest_DIR" to a directory containing one of the above files.  If "gtest"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:104 (find_package)

**Comment by JackBoosY** [comment] 2020-08-19 07:56
Could you remove `gtest` and rebuild `azure-kinect-sensor-sdk`?

Thanks.

**Comment by Crazysiri** [comment] 2020-08-19 08:00
I've tried it but it seems like not works.

benebot@benebot:~/vcpkg$ ./vcpkg remove gtest
The following packages will be removed:
    gtest:x64-linux
Removing package gtest:x64-linux...
Removing package gtest:x64-linux... done
benebot@benebot:~/vcpkg$ ./vcpkg install azure-kinect-sensor-sdk
Computing installation plan...
The following packages will be built and installed:
    azure-kinect-sensor-sdk[core]:x64-linux
  * gtest[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Starting package 1/2: gtest:x64-linux
Building package gtest[core]:x64-linux...
Using cached binary package: /home/benebot/.cache/vcpkg/archives/a9/a9c3aad0fe70fa09435d8644c61271ffbd65452b.zip
Building package gtest[core]:x64-linux... done
Installing package gtest[core]:x64-linux...
Installing package gtest[core]:x64-linux... done
Elapsed time for package gtest:x64-linux: 56.76 ms
Starting package 2/2: azure-kinect-sensor-sdk:x64-linux
Building package azure-kinect-sensor-sdk[core]:x64-linux...
Could not locate cached archive: /home/benebot/.cache/vcpkg/archives/88/88d71ae7ba07a518719462cd9d615e8a817b583e.zip
-- Using cached /home/benebot/vcpkg/downloads/microsoft-Azure-Kinect-Sensor-SDK-v1.4.0-alpha.0.tar.gz
-- Cleaning sources at /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-30d96b3859.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/benebot/vcpkg/downloads/microsoft-Azure-Kinect-Sensor-SDK-v1.4.0-alpha.0.tar.gz
-- Applying patch fix-builds.patch
-- Applying patch disable-c4275.patch
-- Applying patch fix-dependency-imgui.patch
-- Using source at /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-30d96b3859.clean
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: /home/benebot/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-30d96b3859.clean -DK4A_BUILD_DOCS=OFF -DBUILD_TOOLS=OFF -DK4A_SOURCE_LINK=OFF -DK4A_MTE_VERSION=ON -DBUILD_EXAMPLES=OFF -DWITH_TEST=OFF -DIMGUI_EXTERNAL_PATH=/home/benebot/vcpkg/installed/x64-linux/include/bindings -DCMAKE_MAKE_PROGRAM=/home/benebot/vcpkg/downloads/tools/ninja-1.10.0-linux/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/benebot/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=/home/benebot/vcpkg -D_VCPKG_INSTALLED_DIR=/home/benebot/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/benebot/vcpkg/packages/azure-kinect-sensor-sdk_x64-linux/debug
    Working Directory: /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/x64-linux-dbg
    Error code: 1
    See logs for more information:
      /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/config-x64-linux-dbg-out.log
      /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:309 (vcpkg_execute_required_process)
  ports/azure-kinect-sensor-sdk/portfile.cmake:24 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package azure-kinect-sensor-sdk:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: azure-kinect-sensor-sdk:x64-linux
  Vcpkg version: 2020.06.15-unknownhash

Additionally, attach any relevant sections from the log files above.

**Comment by JackBoosY** [comment] 2020-08-19 08:04
Oh, sorry, x64-linux.

**Comment by Crazysiri** [comment] 2020-08-19 08:09
you mean it's not supported for x64-linux,right? and when will it be supported?thanks @JackBoosY

**Comment by JackBoosY** [comment] 2020-08-19 08:19
@Crazysiri Yeah, that's what I mean.

**Comment by JackBoosY** [comment] 2020-08-19 08:21
Since we don't have `libuvc`, and this port depends on it, I can't support it now.

**Comment by Crazysiri** [comment] 2020-08-19 08:27
where to see support list ? thanks 
and how about clone from the original git and cmake and make ? do you just mean vcpkg not support it or the sdk doesn't support it.

**Comment by JackBoosY** [comment] 2020-08-19 08:34
In _SOUCE_PATH\extern\libuvc\CMakeLists.txt_:
```cmake
if("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
    if (NOT TARGET uvc_static)
        set(CMAKE_BUILD_TARGET Static)
        add_subdirectory(src EXCLUDE_FROM_ALL)
    else()
        message(STATUS "uvc_static is already a target. Skipping adding it twice")
    endif()

    add_library(libuvc::libuvc ALIAS uvc_static)
    target_include_directories(uvc_static PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_LIST_DIR}/src/include>")
    target_include_directories(uvc_static PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/src/include>")

endif()
```
Since this folder is a git link, vcpkg did not download it.

**Comment by Crazysiri** [comment] 2020-08-19 08:41
could I build uvc myself and put it in some folder?and where's the folder

**Comment by JackBoosY** [comment] 2020-08-19 08:58
@Crazysiri You may also need #12997, and modify _SOURCE_PATH/CMakeLists.txt_, change `find_package(gtest` to `find_package(GTest`.
Using command `./vcpkg install azure-kinect-sensor-sdk --editable`, put uvc source to _VCPKG_ROOT/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-30d96b3859/extern/libuvc/src_.

**Comment by Crazysiri** [comment] 2020-08-19 09:22
what's the SOURCE_PATH? the azure-kinect-sensor-sdk path?

**Comment by JackBoosY** [comment] 2020-08-19 09:27
_SOURCE_PATH_ == _VCPKG_ROOT/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-30d96b3859_

**Comment by Crazysiri** [comment] 2020-08-19 10:06
ok , I'll try.thanks!

**Comment by Crazysiri** [comment] 2020-08-20 07:12
hi, there is new errors after I do all the thing you tell me . @JackBoosY 

cat /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/config-x64-linux-dbg-err.log


CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LibUSB
    linked by target "k4a_usb_cmd" in directory /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-30d96b3859/src/usbcommand

CMake Error at /home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake:372 (_add_library):
  Target "k4a_color" links to target "libuvc::libuvc" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/color/CMakeLists.txt:17 (add_library)


CMake Error at /home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake:372 (_add_library):
  Target "k4a_color" links to target "libjpeg-turbo::libjpeg-turbo" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/color/CMakeLists.txt:17 (add_library)


CMake Error at /home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake:372 (_add_library):
  Target "k4a" links to target "libuvc::libuvc" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  src/sdk/CMakeLists.txt:5 (add_library)


CMake Error at /home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake:372 (_add_library):
  Target "k4a" links to target "libjpeg-turbo::libjpeg-turbo" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/sdk/CMakeLists.txt:5 (add_library)


CMake Error at /home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake:372 (_add_library):
  Target "k4a" links to target "libuvc::libuvc" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
Call Stack (most recent call first):
  src/sdk/CMakeLists.txt:5 (add_library)


CMake Error at /home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake:372 (_add_library):
  Target "k4a" links to target "libjpeg-turbo::libjpeg-turbo" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/sdk/CMakeLists.txt:5 (add_library)


CMake Error at /home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake:372 (_add_library):
  Target "k4a_color" links to target "libuvc::libuvc" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  src/color/CMakeLists.txt:17 (add_library)


CMake Error at /home/benebot/vcpkg/scripts/buildsystems/vcpkg.cmake:372 (_add_library):
  Target "k4a_color" links to target "libjpeg-turbo::libjpeg-turbo" but the
  target was not found.  Perhaps a find_package() call is missing for an
  IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
  src/color/CMakeLists.txt:17 (add_library)


CMake Warning:
  Manually-specified variables were not used by the project:

    IMGUI_EXTERNAL_PATH
    VCPKG_PLATFORM_TOOLSET
    VCPKG_SET_CHARSET_FLAG


CMake Generate step failed.  Build files cannot be regenerated correctly.

**Comment by JackBoosY** [comment] 2020-08-20 07:27
```Target "k4a_color" links to target "libuvc::libuvc" but the target was not found.```
This proves that libuvc was not configure correctly.

**Comment by Crazysiri** [comment] 2020-08-20 07:40
here is the screenshots for the folder.  is it correct? what should I do  after put the source to the folder? thanks. 
<img width="840" alt="截屏2020-08-20 下午3 38 36" src="https://user-images.githubusercontent.com/7479347/90730810-550ff800-e2fb-11ea-821c-f4b1db0a979f.png">

**Comment by JackBoosY** [comment] 2020-08-20 07:43
I think it's becuase the libuvc version is incorrect, you may need to download it using [this url](https://github.com/microsoft/libuvc/tree/5fc483d596c63f1bcd36be35d512468c0b75c5f3).

**Comment by Crazysiri** [comment] 2020-08-20 08:20
I clone git from  https://github.com/microsoft/libuvc.git
then git checkout  5fc483d596c63f1bcd36be35d512468c0b75c5f3
then put the file to the path
I get the same issues

**Comment by Crazysiri** [comment] 2020-08-20 08:21
after run './vcpkg install azure-kinect-sensor-sdk --editable' I get the same issues

**Comment by JackBoosY** [comment] 2020-08-20 09:00
I will give you a complete solution tomorrow.

**Comment by JackBoosY** [comment] 2020-08-21 07:03
For some reason libusb cannot be found, I need to fix it first (Requied by this port).

**Comment by Crazysiri** [comment] 2020-08-21 08:03
ok，thanks .

**Comment by JackBoosY** [comment] 2020-08-26 02:19
Since #13057 merged, I will continue to add this support.

**Comment by JackBoosY** [comment] 2020-08-26 07:34
Sadly, akss doesn't support latest libuvc, we need to wait for upstream fix it.
Here is modified akss and libuvc port files:
[ports.zip](https://github.com/microsoft/vcpkg/files/5128260/ports.zip)

**Comment by Crazysiri** [comment] 2020-08-26 08:44
thanks, and Can I do something to complete this? like put  libuvc source to the folder and install it ?

**Comment by JackBoosY** [comment] 2020-08-26 08:47
@Crazysiri In the zip package, I already added libuvc as a new port. So you can unzip that and put them into _VCPKG_ROOT/ports_, them use `./vcpkg install azure-kinect-sensor-sdk --editable`.

**Comment by Crazysiri** [comment] 2020-08-26 09:56
new error:
is it the libuvc not correct?

[8/64] /usr/bin/c++  -DARCHITECTURE_x86_64=1 -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/benebot/vcpkg/installed/x64-linux/share/inc -I/home/benebot/vcpkg/installed/x64-linux/share/pal/linux -I/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/../include -Isrc/sdk/include -isystem /home/benebot/vcpkg/installed/x64-linux/include/azureiot -isystem /home/benebot/vcpkg/installed/x64-linux/include -fPIC -Werror -Werror -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -Wextra -Wno-missing-field-initializers -Werror -std=gnu++11 -MD -MT src/color/CMakeFiles/k4a_color.dir/uvc_camerareader.cpp.o -MF src/color/CMakeFiles/k4a_color.dir/uvc_camerareader.cpp.o.d -o src/color/CMakeFiles/k4a_color.dir/uvc_camerareader.cpp.o -c /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/color/uvc_camerareader.cpp
FAILED: src/color/CMakeFiles/k4a_color.dir/uvc_camerareader.cpp.o
/usr/bin/c++  -DARCHITECTURE_x86_64=1 -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/benebot/vcpkg/installed/x64-linux/share/inc -I/home/benebot/vcpkg/installed/x64-linux/share/pal/linux -I/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/../include -Isrc/sdk/include -isystem /home/benebot/vcpkg/installed/x64-linux/include/azureiot -isystem /home/benebot/vcpkg/installed/x64-linux/include -fPIC -Werror -Werror -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -Wextra -Wno-missing-field-initializers -Werror -std=gnu++11 -MD -MT src/color/CMakeFiles/k4a_color.dir/uvc_camerareader.cpp.o -MF src/color/CMakeFiles/k4a_color.dir/uvc_camerareader.cpp.o.d -o src/color/CMakeFiles/k4a_color.dir/uvc_camerareader.cpp.o -c /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/color/uvc_camerareader.cpp
/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/color/uvc_camerareader.cpp: In member function ‘k4a_result_t UVCCameraReader::Start(uint32_t, uint32_t, float, k4a_image_format_t, void (*)(k4a_result_t, k4a_capture_t, void*), void*)’:
/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/color/uvc_camerareader.cpp:111:23: error: ‘UVC_COLOR_FORMAT_NV12’ was not declared in this scope
         frameFormat = UVC_COLOR_FORMAT_NV12;
                       ^
/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/color/uvc_camerareader.cpp: In member function ‘void UVCCameraReader::Callback(uvc_frame_t*)’:
/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/color/uvc_camerareader.cpp:1126:44: error: ‘uvc_frame_t {aka struct uvc_frame}’ has no member named ‘metadata_bytes’
         size_t bufferLeft = (size_t)frame->metadata_bytes;
                                            ^
/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/color/uvc_camerareader.cpp:1129:89: error: ‘uvc_frame_t {aka struct uvc_frame}’ has no member named ‘metadata’
             PKSCAMERA_METADATA_ITEMHEADER pItem = (PKSCAMERA_METADATA_ITEMHEADER)frame->metadata;
                                                                                         ^
/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/color/uvc_camerareader.cpp:1244:44: error: ‘uvc_frame_t {aka struct uvc_frame}’ has no member named ‘capture_time_finished’
             uint64_t ts = (uint64_t)frame->capture_time_finished.tv_sec * 1000000000;
                                            ^
/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/color/uvc_camerareader.cpp:1245:36: error: ‘uvc_frame_t {aka struct uvc_frame}’ has no member named ‘capture_time_finished’
             ts += (uint64_t)frame->capture_time_finished.tv_nsec;
                                    ^
[9/64] /usr/bin/c++  -DARCHITECTURE_x86_64=1 -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/benebot/vcpkg/installed/x64-linux/share/inc -I/home/benebot/vcpkg/installed/x64-linux/share/pal/linux -I/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/../include -Isrc/sdk/include -isystem /home/benebot/vcpkg/installed/x64-linux/include/azureiot -isystem /home/benebot/vcpkg/installed/x64-linux/include -fPIC -Werror -Werror -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -Wextra -Wno-missing-field-initializers -Werror -std=gnu++11 -MD -MT src/color/CMakeFiles/k4a_color.dir/color.cpp.o -MF src/color/CMakeFiles/k4a_color.dir/color.cpp.o.d -o src/color/CMakeFiles/k4a_color.dir/color.cpp.o -c /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/color/color.cpp
[10/64] /usr/bin/c++  -DARCHITECTURE_x86_64=1 -DEBML_STATIC_DEFINE -DFMT_LOCALE -DSPDLOG_COMPILED_LIB -DSPDLOG_FMT_EXTERNAL -I/home/benebot/vcpkg/installed/x64-linux/share/inc -I/home/benebot/vcpkg/installed/x64-linux/share/pal/linux -I/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/../include -Isrc/sdk/include -I/home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/include -isystem /home/benebot/vcpkg/installed/x64-linux/include/azureiot -isystem /home/benebot/vcpkg/installed/x64-linux/include -fPIC -Werror -Werror -g -fPIC -fvisibility=hidden -fvisibility-inlines-hidden   -Wall -Wextra -Wno-missing-field-initializers -Werror -std=gnu++11 -MD -MT src/record/internal/CMakeFiles/k4a_record.dir/iocallback.cpp.o -MF src/record/internal/CMakeFiles/k4a_record.dir/iocallback.cpp.o.d -o src/record/internal/CMakeFiles/k4a_record.dir/iocallback.cpp.o -c /home/benebot/vcpkg/buildtrees/azure-kinect-sensor-sdk/src/.0-alpha.0-b125ea5fc7/src/record/internal/iocallback.cpp
ninja: build stopped: subcommand failed.

**Comment by JackBoosY** [comment] 2020-08-26 09:59
@Crazysiri Yes, that's what I said "doesn't support latest libuvc".

**Comment by Crazysiri** [comment] 2020-08-26 10:04
can I use a correct version ? the version in the portfile.cmake is f3f6d8a646480fcbecc433a3a81066ddc24476e1,can I change it and ./vcpkg install libuvc --editable ? and which version support this?

**Comment by Crazysiri** [comment] 2020-08-26 10:05
I mean the correct commit id.

**Comment by JackBoosY** [comment] 2020-08-27 02:16
@Crazysiri Fine, you need to change the repo to `microsoft`, and set the REF to `f3f6d8a646480fcbecc433a3a81066ddc24476e1`.

**Comment by jvhoffbauer** [comment] 2020-11-02 11:06
Will this be fixed in the official version anytime soon?

**Comment by JackBoosY** [comment] 2020-11-03 06:39
@jvhoffbauer I wish that.

**Comment by jvhoffbauer** [comment] 2020-11-03 09:05
I see. Can I do anything to fix it?

**Comment by jvhoffbauer** [comment] 2020-11-03 09:08
Do I understand correctly, that the problem is that both azure-kinect-sensor-sdk and akss are requiring different versions of libuvc?

**Comment by JackBoosY** [comment] 2020-11-03 09:12
@jvhoffbauer You may need to report this issue to upstream and wait for them to support the latest libuvc.

**Closed** 2021-03-29 17:17 UTC
Labels: category:port-feature, depends:upstream-changes
