### ISSUE TITLE
[New port request] pytorch.

### ISSUE THREAD

**Issue by DiegoViqueira** [microsoft/vcpkg#6345] opened 2019-05-08 06:42 UTC
It will be nice to have libtorch (c++ library from PyTorch ) on vcpkg,
The github repo https://github.com/pytorch/pytorch

**Comment by Fleischner** [comment] 2019-05-10 09:03
Looking forward for this too.
But this issue redundant to #5209

**Comment by NancyLi1013** [comment] 2019-05-17 07:07
Duplicate of #5209. So close it.

**Closed by NancyLi1013** 2019-05-17 07:07 UTC
Labels: new port request - consider making a PR!
