### ISSUE TITLE
[Python ] Cannot find Python

### ISSUE THREAD

**Issue by orbingol** [microsoft/vcpkg#17351] opened 2021-04-19 06:45 UTC
**Describe the bug**

vcpkg cannot find python development libraries when the python version is v3.9 and finds the system python when python version is 3.8. Python v3.8 is selected via "versions" feature as discussed in [here](https://devblogs.microsoft.com/cppblog/take-control-of-your-vcpkg-dependencies-with-versioning-support/).

**Environment**
- OS: Ubuntu 20.02 but I was able to reproduce on Windows 10
- Compiler: GCC 9.3.0 x64 for Ubuntu, Visual Studio 2019 for Windows

**To Reproduce**

I've created a repo with the files that may be used to reproduce the issue:

For Python 3.9

1. git clone --recursive https://github.com/orbingol/python-vcpkg.git
2. cd python-vcpkg
3. cd py39
4. mkdir build
5. cd build
6. cmake ..
7. The error would be

```
CMake Error at /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Python (missing: Python_LIBRARIES Development
  Development.Module Development.Embed) (found version "3.9.2")
Call Stack (most recent call first):
  /usr/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.20/Modules/FindPython.cmake:556 (find_package_handle_standard_args)
  build/vcpkg_installed/x64-linux/share/python/vcpkg-cmake-wrapper.cmake:67 (_find_package)
  /home/onur/projects/python-vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:815 (include)
  CMakeLists.txt:7 (find_package)
```

For Python 3.8

1. git clone --recursive https://github.com/orbingol/python-vcpkg.git
2. cd python-vcpkg
3. cd py38
4. mkdir build
5. cd build
6. cmake ..
7. There is no error but cmake finds the system python

```
-- Found Python: /usr/include/python3.8 (found version "3.8.5") found components: Development Development.Module Development.Embed 
```

**Expected behavior**

CMake should find the python libraries installed in the `build\vcpkg_installed\{VCPKG_DEFAULT_TRIPLET}` directory .

**Failure logs** 
The logs are attached above but I could provide more details if needed.

**Additional context**
N/A

**Comment by JonLiu1993** [comment] 2021-04-21 02:44
@orbingol, thanks for your issue, I noticed that you have a problem when using python, but the vcpkg library does not contain python, maybe you can submit the issue to vcpkg Upstream, I will close the issue, if you have other questions, you can reopen it

**Comment by Hoikas** [comment] 2021-04-21 02:56
The built-in CMake support for Python with vcpkg didn't land until the python3 port was upgraded to 3.9, so finding 3.8 with the built in FindPython3 probably won't work. I haven't tested the python3 port against CMake 3.20 though. Have you tried earlier versions of CMake, eg 3.19 or 3.18. I used those when developing the wrapper.

**Comment by orbingol** [comment] 2021-04-21 05:43
@Hoikas thanks for your reply!

I've tested with cmake v3.19.8 and it looks like the same:

```
CMake Error at /home/onur/bin/cmake-3.19.8-Linux-x86_64/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Python (missing: Python_LIBRARIES Development
  Development.Module Development.Embed) (found version "3.9.2")
Call Stack (most recent call first):
  /home/onur/bin/cmake-3.19.8-Linux-x86_64/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /home/onur/bin/cmake-3.19.8-Linux-x86_64/share/cmake-3.19/Modules/FindPython.cmake:470 (find_package_handle_standard_args)
  build/vcpkg_installed/x64-linux/share/python/vcpkg-cmake-wrapper.cmake:67 (_find_package)
  /home/onur/projects/python-vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:815 (include)
  CMakeLists.txt:7 (find_package)
```

With cmake v3.18.6

```CMake Error at /home/onur/bin/cmake-3.18.6-Linux-x86_64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Python (missing: Python_LIBRARIES Development
  Development.Module Development.Embed) (found version "3.9.2")
Call Stack (most recent call first):
  /home/onur/bin/cmake-3.18.6-Linux-x86_64/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /home/onur/bin/cmake-3.18.6-Linux-x86_64/share/cmake-3.18/Modules/FindPython.cmake:436 (find_package_handle_standard_args)
  build/vcpkg_installed/x64-linux/share/python/vcpkg-cmake-wrapper.cmake:67 (_find_package)
  /home/onur/projects/python-vcpkg/vcpkg/scripts/buildsystems/vcpkg.cmake:815 (include)
  CMakeLists.txt:7 (find_package)
```

**Comment by JackBoosY** [comment] 2021-04-28 10:18
@orbingol Since cmake in vcpkg was updated to 3.20.0, is this issue resolved?

**Comment by orbingol** [comment] 2021-04-29 04:09
@JackBoosY I am still observing the same issue with the updated vcpkg.

**Comment by JackBoosY** [comment] 2021-05-03 07:20
I used the sample project you provided, but I did not receive an error:
```
1> Command line: C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2017\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe  -G "Visual Studio 15 2017 Win64" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\usr\CMakeBuilds\e0616a0a-fa87-7732-a2e7-216f9e80a99c\install\x64-Debug"  -DCMAKE_TOOLCHAIN_FILE="F:/vcpkg/scripts/buildsystems/vcpkg.cmake"  -DCMAKE_CXX_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe"  -DCMAKE_C_COMPILER="C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/HostX86/x64/cl.exe"  -DCMAKE_CONFIGURATION_TYPES="Debug" "G:\17351\python-vcpkg\py38"
1> Working directory: C:\Users\usr\CMakeBuilds\e0616a0a-fa87-7732-a2e7-216f9e80a99c\build\x64-Debug
1> -- Running vcpkg install
1> -- Running vcpkg install - done
1> -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19042.
1> -- The C compiler identification is MSVC 19.16.27045.0
1> -- The CXX compiler identification is MSVC 19.16.27045.0
1> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
1> -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
1> -- Detecting C compiler ABI info
1> -- Detecting C compiler ABI info - done
1> -- Detecting C compile features
1> -- Detecting C compile features - done
1> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
1> -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
1> -- Detecting CXX compiler ABI info
1> -- Detecting CXX compiler ABI info - done
1> -- Detecting CXX compile features
1> -- Detecting CXX compile features - done
1> -- Found Python: C:/Users/usr/CMakeBuilds/e0616a0a-fa87-7732-a2e7-216f9e80a99c/build/x64-Debug/vcpkg_installed/x64-windows/lib/python38.lib (found version "3.8.3") found components:  Development 
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: C:/Users/usr/CMakeBuilds/e0616a0a-fa87-7732-a2e7-216f9e80a99c/build/x64-Debug
1> Starting CMake target info extraction ...
1> CMake server connection made.
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted code model.
1> Extracted CTest info.
1> Collating data ...
1> Target info extraction done.

```

**Comment by orbingol** [comment] 2021-05-03 22:42
@JackBoosY you probably don't have a python distribution installed and added to the path. If the only python is the vcpkg python and the python version is v3.8.x (like you tested), it'll work. Otherwise, fails. Python 3.9.x is another issue. It'll find Python but it won't find the Development libraries.

Both are tested on Ubuntu 20.04 x64.

**Comment by Hoikas** [comment] 2021-05-04 00:46
`1> -- Found Python: C:/Users/usr/CMakeBuilds/e0616a0a-fa87-7732-a2e7-216f9e80a99c/build/x64-Debug/vcpkg_installed/x64-windows/lib/python38.lib (found version "3.8.3") found components:  Development `

vcpkg is very out of date...

**Comment by JackBoosY** [comment] 2021-05-05 14:29
@orbingol  Can you make sure your vcpkg is latest?

**Comment by orbingol** [comment] 2021-05-06 13:06
> @orbingol Can you make sure your vcpkg is latest?

@JackBoosY you are using `-DCMAKE_TOOLCHAIN_FILE="F:/vcpkg/scripts/buildsystems/vcpkg.cmake"` while configuring. Please remove that option, then it should use the `vcpkg` package comes with the repo (updated a week ago or so)

**Comment by orbingol** [comment] 2021-05-06 13:49
> I used the sample project you provided, but I did not receive any errors:

Also @JackBoosY, please refer to the following Azure Pipelines build for more details:

https://dev.azure.com/orbingol/python-vcpkg/_build/results?buildId=2&view=results

According to the pipeline results, only Windows and macOS py39 builds seem to find the python installed by vcpkg. Although it shows success, the others seem to find the system python (please scroll down the logs to see which python is found). In addition, some py38 builds are failing due to some other errors.

**Comment by JackBoosY** [comment] 2021-05-07 07:23
@orbingol First, we should handle the libffi issue in https://github.com/microsoft/vcpkg/pull/17637.

**Comment by orbingol** [comment] 2021-05-08 23:19
@JackBoosY I've updated `vcpkg` to the latest version as of this post, but it is still failing. Seems like the `libffi` issue is specific to the Windows py38 builds via versioning. The others look like success on the CI but still not finding the correct python installed by `vcpkg`.

**Comment by JackBoosY** [comment] 2021-05-20 06:26
Confirmed.

**Comment by O-Tom** [comment] 2022-04-15 14:36
I came across the same issue under a debian VM:
```
CMake Error at /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find Python3 (missing: Python3_LIBRARIES Development
  Development.Embed) (found version "3.10.2")
Call Stack (most recent call first):
  /usr/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.18/Modules/FindPython/Support.cmake:2984 (find_package_handle_standard_args)
  /usr/share/cmake-3.18/Modules/FindPython3.cmake:389 (include)
  /home/tom/src/vcpkg/sdk/installed/x64-linux/share/python3/vcpkg-cmake-wrapper.cmake:70 (_find_package)
  /home/tom/src/vcpkg/sdk/scripts/buildsystems/vcpkg.cmake:770 (include)
```
From the call stack I found that vcpkg was relying on the bundled cmake module to locate python.
As of today, the linux distribution I'm using comes with cmake 3.18.
In this particular cmake version, `FindPython.cmake` is not up to date with current python versions. It's stuck at version 3.9:
![image](https://user-images.githubusercontent.com/6274985/163573590-982c31cc-b3e1-4b44-8346-edc03d26a610.png)

The vcpkg build I use is based on python 3.10 and because of the above limitation, cmake is unable to give a correct answer to `find_package`.
If I edit `Support.cmake`and manually add 3.10 to the list of supported versions...
![image](https://user-images.githubusercontent.com/6274985/163582044-2dad52a6-c2a4-409a-81b4-249afb116742.png)
...it all works as expected:
```
-- Found Python3: /home/tom/src/vcpkg/sdk/installed/x64-linux/include/python3.10 (found version "3.10.2") found components: Development Development.Module Development.Embed
```

**Comment by dg0yt** [comment] 2023-05-28 17:08
Is this still an active issue?

**Comment by Osyotr** [comment] 2024-10-18 10:54
I think this can be closed now.

**Closed** 2024-10-21 06:17 UTC
Labels: category:port-bug, info:versioning
