### ISSUE TITLE
vcpkg-configuration.json: Allow for branch/tag names as "baseline" values

### ISSUE THREAD

**Issue by martingalvan-nordic** [microsoft/vcpkg#27583] opened 2022-11-01 09:46 UTC
****

**Is your feature request related to a problem? Please describe.**
We're using vcpkg manifest mode in our project, and have a vcpkg-configuration.json file with registry entries for vcpkg itself as well as a set of overlay ports we maintain for convenience. Both entries have to use a git commit hash as their "baseline" value, which means that we need to update the overlay ports' hash every time we push something new to master. This is tedious and error-prone, and has been the source of various issues in the past.

**Proposed solution**
It would be good to be able to specify a branch/tag name instead of a commit hash. That way, we could have e.g. "2022.10.19" for the vcpkg baseline, and "master" for the overlay ports.

**Comment by dg0yt** [comment] 2022-11-01 09:52
Duplicate of #25044, now #25087.

**Closed** 2022-11-01 10:13 UTC
Labels: category:vcpkg-feature
