### ISSUE TITLE
Can not find header file while using vcpkg with vscode and cmake

### ISSUE THREAD

**Issue by NeoxyCN** [microsoft/vcpkg#28486] opened 2022-12-22 05:46 UTC
I installed sdl2:x86-windows by vcpkg. And now I want to use it in vcpkg with cmake, but when I type `#include "SDL2/SDL.h`, vscode told me that no such files. 

settings.json
`{
    "cmake.configureSettings": {
      "CMAKE_TOOLCHAIN_FILE": "D:/source/vcpkg/scripts/buildsystems/vcpkg.cmake"
    }
  }`

c_cpp_properties.json
`{
    "configurations": [
        {
            "name": "Win32",
            "includePath": [
                "${workspaceFolder}/**",
                "${vcpkgRoot}/x86-windows/include"
            ],
            "defines": [
                "_DEBUG",
                "UNICODE",
                "_UNICODE"
            ],
            "windowsSdkVersion": "10.0.19041.0",
            "compilerPath": "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.32.31326/bin/Hostx64/x86/cl.exe",
            "cStandard": "c17",
            "cppStandard": "c++17",
            "intelliSenseMode": "windows-msvc-x86",
            "configurationProvider": "ms-vscode.cmake-tools"
        }
    ],
    "version": 4
}`

I am confused that which one I should choose
<img width="461" alt="1" src="https://user-images.githubusercontent.com/23608082/209065522-85a24822-02da-4161-a9ff-a73c732a8785.png">

And should I change the IntelliSense mode into windows-msvc-x86 in C/C++ Extension?

**Comment by FrankXie05** [comment] 2022-12-22 06:33
@NeoxyCN Yes maybe intelligence is not that smart for different triplets. By the way, make sure you have `c++` and `cmake` extension tools installed. :)

**Comment by FrankXie05** [comment] 2022-12-30 07:02
does the issue still occur?

**Comment by NeoxyCN** [comment] 2023-01-02 04:37
> does the issue still occur?

Yes,.  it still occur. I have no idea about this....

**Comment by NeoxyCN** [comment] 2023-01-02 04:40
@FrankXie05  Yes,. it still occur. I have no idea about this. I created a new project and used CMake to configure it again, but vscode still coud not find header files

**Comment by FrankXie05** [comment] 2023-01-19 08:04
Could you please provide a list of the tools you have installed ?

**Comment by NeoxyCN** [comment] 2023-02-07 05:55
> Could you please provide a list of the tools you have installed ?

CMake, Visual Sudio Code, vcpkg, MinGW, Visual Studio 2022.
That's all.

**Comment by LilyWangLL** [comment] 2023-02-14 09:51
Thanks for posting this issue. You could use vcpkg with VS first. About using vcpkg on VS Code, it looks like we can't integrate vcpkg to VS Code now, we need double confirm the use with VS Code, the similar issue https://github.com/microsoft/vcpkg/issues/29243.

**Comment by LilyWangLL** [comment] 2023-02-14 09:53
I think this issue could be closed as duplicate of #29243, if you have other question, please reopen this issue.

**Closed by LilyWangLL** 2023-02-14 09:53 UTC
Labels: category:question

**Comment by jaypowers** [comment] 2024-08-24 18:11
Hi I'm currently having this issue.

My tools are:

1. visual studio community edition with C/C++ option
2. (default vcpkg/cmake current as of post date, from VS community edition)
3. Visual Studio Code
4. Powershell

I belive I also followed the website, here's the steps to reproduce.

1. open PS dev prompt
2. open code .
3. open terminal in vscode
4. set $env paths (just to be sure)
5. vcpkg new --application
6. vcpkg add port raylib
7. vcpkg install
8. vcpkg integrate install
9. then make CMakeLists.txt

```
cmake_minimum_required(VERSION 3.16)
project(cycles)

include_directories(vcpkg_installed/x64-windows/include)

find_package(raylib 5 QUIET)

add_executable(cycles main.cpp)
```

10. cmake, build run etc... then still doesn't find "raylib.h"

I'm mentioning this here, even though I'm using vscode, I'm not certain it's vscode, since I'm running cmake
also I've tried many other things to get the .h file recognized, I'm sure I'm doing something wrong, any thoughts?

**Comment by sfhacker** [comment] 2024-08-24 22:56
This issue is from 2022!
