### ISSUE TITLE
nghttp2 doesn't currently support static library build

### ISSUE THREAD

**Issue by alroyso** [Microsoft/vcpkg#2716] opened 2018-02-03 06:27 UTC
nghttp2:x86-windows-static  安装失败  怎么解决。

**Comment by pravic** [comment] 2018-02-04 08:30
Duplicate of #2706.

**Comment by ras0219-msft** [comment] 2018-02-08 00:01
This should be fixed in the latest master. Thanks!

**Closed by ras0219-msft** 2018-02-08 00:01 UTC
