### ISSUE TITLE
[openssl] FindOpenssl first finds openssl under the system path

### ISSUE THREAD

**Issue by IshaanKarnik** [microsoft/vcpkg#21545] opened 2021-11-19 15:01 UTC
**Host Environment**
- OS: Windows 10 64-bit
- Compiler: Visual Studios 2022

**To Reproduce**
`./vcpkg install paho-mqttpp3`

I refered the https://github.com/microsoft/vcpkg/issues/7167.
I cross checked, I am using MSVC library version.

**Failure logs** 
```
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\kpec_software_002\AppData\Local\vcpkg\archives in 3.46 ms. Use --debug to see more details.
Starting package 1/6: paho-mqtt:x64-windows
Building package paho-mqtt[core]:x64-windows...
-- Using cached eclipse-paho.mqtt.c-3b7ae6348bc917d42c04efa962e4868c09bbde9f.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/paho-mqtt/src/8c09bbde9f-fe1489e34b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/eclipse-paho.mqtt.c-3b7ae6348bc917d42c04efa962e4868c09bbde9f.tar.gz
-- Applying patch remove_compiler_options.patch
-- Applying patch fix-install-path.patch
-- Applying patch fix-unresolvedsymbol-arm.patch
-- Using source at C:/vcpkg/buildtrees/paho-mqtt/src/8c09bbde9f-fe1489e34b.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j5
    Working Directory: C:/vcpkg/buildtrees/paho-mqtt/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\paho-mqtt\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:106 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/paho-mqtt/portfile.cmake:26 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package paho-mqtt:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  package: paho-mqtt[core]:x64-windows -> 1.3.9
  vcpkg version: 56e89ebc2 2021-11-18 (9 hours ago)
  vcpkg-tool version: 2021-11-15-ec76affcc987efbf172b7da0b05df711b48fa535
```
```
> [59/61] cmd.exe /C "cd . && C:\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=src\CMakeFiles\paho-mqtt3as.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\link.exe  src\CMakeFiles\common_ssl_obj.dir\MQTTTime.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolClient.c.obj src\CMakeFiles\common_ssl_obj.dir\Clients.c.obj src\CMakeFiles\common_ssl_obj.dir\utf-8.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacket.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacketOut.c.obj src\CMakeFiles\common_ssl_obj.dir\Messages.c.obj src\CMakeFiles\common_ssl_obj.dir\Tree.c.obj src\CMakeFiles\common_ssl_obj.dir\Socket.c.obj src\CMakeFiles\common_ssl_obj.dir\Log.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistence.c.obj src\CMakeFiles\common_ssl_obj.dir\Thread.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolOut.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistenceDefault.c.obj src\CMakeFiles\common_ssl_obj.dir\SocketBuffer.c.obj src\CMakeFiles\common_ssl_obj.dir\LinkedList.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProperties.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTReasonCodes.c.obj src\CMakeFiles\common_ssl_obj.dir\Base64.c.obj src\CMakeFiles\common_ssl_obj.dir\SHA1.c.obj src\CMakeFiles\common_ssl_obj.dir\WebSocket.c.obj src\CMakeFiles\common_ssl_obj.dir\StackTrace.c.obj src\CMakeFiles\common_ssl_obj.dir\Heap.c.obj src\CMakeFiles\paho-mqtt3as.dir\MQTTAsync.c.obj src\CMakeFiles\paho-mqtt3as.dir\MQTTAsyncUtils.c.obj src\CMakeFiles\paho-mqtt3as.dir\SSLSocket.c.obj  /out:src\paho-mqtt3as.dll /implib:src\paho-mqtt3as.lib /pdb:src\paho-mqtt3as.pdb /dll /version:1.3 /machine:x64 /nologo    /debug /INCREMENTAL  "C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib"  "C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib"  ws2_32.lib  crypt32.lib  RpcRT4.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
> FAILED: src/paho-mqtt3as.dll src/paho-mqtt3as.lib 
> cmd.exe /C "cd . && C:\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=src\CMakeFiles\paho-mqtt3as.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\link.exe  src\CMakeFiles\common_ssl_obj.dir\MQTTTime.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolClient.c.obj src\CMakeFiles\common_ssl_obj.dir\Clients.c.obj src\CMakeFiles\common_ssl_obj.dir\utf-8.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacket.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacketOut.c.obj src\CMakeFiles\common_ssl_obj.dir\Messages.c.obj src\CMakeFiles\common_ssl_obj.dir\Tree.c.obj src\CMakeFiles\common_ssl_obj.dir\Socket.c.obj src\CMakeFiles\common_ssl_obj.dir\Log.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistence.c.obj src\CMakeFiles\common_ssl_obj.dir\Thread.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolOut.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistenceDefault.c.obj src\CMakeFiles\common_ssl_obj.dir\SocketBuffer.c.obj src\CMakeFiles\common_ssl_obj.dir\LinkedList.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProperties.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTReasonCodes.c.obj src\CMakeFiles\common_ssl_obj.dir\Base64.c.obj src\CMakeFiles\common_ssl_obj.dir\SHA1.c.obj src\CMakeFiles\common_ssl_obj.dir\WebSocket.c.obj src\CMakeFiles\common_ssl_obj.dir\StackTrace.c.obj src\CMakeFiles\common_ssl_obj.dir\Heap.c.obj src\CMakeFiles\paho-mqtt3as.dir\MQTTAsync.c.obj src\CMakeFiles\paho-mqtt3as.dir\MQTTAsyncUtils.c.obj src\CMakeFiles\paho-mqtt3as.dir\SSLSocket.c.obj  /out:src\paho-mqtt3as.dll /implib:src\paho-mqtt3as.lib /pdb:src\paho-mqtt3as.pdb /dll /version:1.3 /machine:x64 /nologo    /debug /INCREMENTAL  "C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib"  "C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib"  ws2_32.lib  crypt32.lib  RpcRT4.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
> LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\link.exe src\CMakeFiles\common_ssl_obj.dir\MQTTTime.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolClient.c.obj src\CMakeFiles\common_ssl_obj.dir\Clients.c.obj src\CMakeFiles\common_ssl_obj.dir\utf-8.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacket.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacketOut.c.obj src\CMakeFiles\common_ssl_obj.dir\Messages.c.obj src\CMakeFiles\common_ssl_obj.dir\Tree.c.obj src\CMakeFiles\common_ssl_obj.dir\Socket.c.obj src\CMakeFiles\common_ssl_obj.dir\Log.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistence.c.obj src\CMakeFiles\common_ssl_obj.dir\Thread.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolOut.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistenceDefault.c.obj src\CMakeFiles\common_ssl_obj.dir\SocketBuffer.c.obj src\CMakeFiles\common_ssl_obj.dir\LinkedList.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProperties.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTReasonCodes.c.obj src\CMakeFiles\common_ssl_obj.dir\Base64.c.obj src\CMakeFiles\common_ssl_obj.dir\SHA1.c.obj src\CMakeFiles\common_ssl_obj.dir\WebSocket.c.obj src\CMakeFiles\common_ssl_obj.dir\StackTrace.c.obj src\CMakeFiles\common_ssl_obj.dir\Heap.c.obj src\CMakeFiles\paho-mqtt3as.dir\MQTTAsync.c.obj src\CMakeFiles\paho-mqtt3as.dir\MQTTAsyncUtils.c.obj src\CMakeFiles\paho-mqtt3as.dir\SSLSocket.c.obj /out:src\paho-mqtt3as.dll /implib:src\paho-mqtt3as.lib /pdb:src\paho-mqtt3as.pdb /dll /version:1.3 /machine:x64 /nologo /debug /INCREMENTAL C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib ws2_32.lib crypt32.lib RpcRT4.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:src\CMakeFiles\paho-mqtt3as.dir/intermediate.manifest src\CMakeFiles\paho-mqtt3as.dir/manifest.res" failed (exit code 1120) with the following output:
>    Creating library src\paho-mqtt3as.lib and object src\paho-mqtt3as.exp
> SSLSocket.c.obj : error LNK2019: unresolved external symbol SSL_get_peer_certificate referenced in function SSLSocket_connect
> src\paho-mqtt3as.dll : fatal error LNK1120: 1 unresolved externals
> [60/61] cmd.exe /C "cd . && C:\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=src\CMakeFiles\paho-mqtt3cs.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\link.exe  src\CMakeFiles\common_ssl_obj.dir\MQTTTime.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolClient.c.obj src\CMakeFiles\common_ssl_obj.dir\Clients.c.obj src\CMakeFiles\common_ssl_obj.dir\utf-8.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacket.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacketOut.c.obj src\CMakeFiles\common_ssl_obj.dir\Messages.c.obj src\CMakeFiles\common_ssl_obj.dir\Tree.c.obj src\CMakeFiles\common_ssl_obj.dir\Socket.c.obj src\CMakeFiles\common_ssl_obj.dir\Log.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistence.c.obj src\CMakeFiles\common_ssl_obj.dir\Thread.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolOut.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistenceDefault.c.obj src\CMakeFiles\common_ssl_obj.dir\SocketBuffer.c.obj src\CMakeFiles\common_ssl_obj.dir\LinkedList.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProperties.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTReasonCodes.c.obj src\CMakeFiles\common_ssl_obj.dir\Base64.c.obj src\CMakeFiles\common_ssl_obj.dir\SHA1.c.obj src\CMakeFiles\common_ssl_obj.dir\WebSocket.c.obj src\CMakeFiles\common_ssl_obj.dir\StackTrace.c.obj src\CMakeFiles\common_ssl_obj.dir\Heap.c.obj src\CMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.obj src\CMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.obj  /out:src\paho-mqtt3cs.dll /implib:src\paho-mqtt3cs.lib /pdb:src\paho-mqtt3cs.pdb /dll /version:1.3 /machine:x64 /nologo    /debug /INCREMENTAL  "C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib"  "C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib"  ws2_32.lib  crypt32.lib  RpcRT4.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
> FAILED: src/paho-mqtt3cs.dll src/paho-mqtt3cs.lib 
> cmd.exe /C "cd . && C:\vcpkg\downloads\tools\cmake-3.21.1-windows\cmake-3.21.1-windows-i386\bin\cmake.exe -E vs_link_dll --intdir=src\CMakeFiles\paho-mqtt3cs.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\mt.exe --manifests  -- C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\link.exe  src\CMakeFiles\common_ssl_obj.dir\MQTTTime.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolClient.c.obj src\CMakeFiles\common_ssl_obj.dir\Clients.c.obj src\CMakeFiles\common_ssl_obj.dir\utf-8.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacket.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacketOut.c.obj src\CMakeFiles\common_ssl_obj.dir\Messages.c.obj src\CMakeFiles\common_ssl_obj.dir\Tree.c.obj src\CMakeFiles\common_ssl_obj.dir\Socket.c.obj src\CMakeFiles\common_ssl_obj.dir\Log.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistence.c.obj src\CMakeFiles\common_ssl_obj.dir\Thread.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolOut.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistenceDefault.c.obj src\CMakeFiles\common_ssl_obj.dir\SocketBuffer.c.obj src\CMakeFiles\common_ssl_obj.dir\LinkedList.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProperties.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTReasonCodes.c.obj src\CMakeFiles\common_ssl_obj.dir\Base64.c.obj src\CMakeFiles\common_ssl_obj.dir\SHA1.c.obj src\CMakeFiles\common_ssl_obj.dir\WebSocket.c.obj src\CMakeFiles\common_ssl_obj.dir\StackTrace.c.obj src\CMakeFiles\common_ssl_obj.dir\Heap.c.obj src\CMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.obj src\CMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.obj  /out:src\paho-mqtt3cs.dll /implib:src\paho-mqtt3cs.lib /pdb:src\paho-mqtt3cs.pdb /dll /version:1.3 /machine:x64 /nologo    /debug /INCREMENTAL  "C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib"  "C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib"  ws2_32.lib  crypt32.lib  RpcRT4.lib  kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib  && cd ."
> LINK Pass 1: command "C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\link.exe src\CMakeFiles\common_ssl_obj.dir\MQTTTime.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolClient.c.obj src\CMakeFiles\common_ssl_obj.dir\Clients.c.obj src\CMakeFiles\common_ssl_obj.dir\utf-8.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacket.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacketOut.c.obj src\CMakeFiles\common_ssl_obj.dir\Messages.c.obj src\CMakeFiles\common_ssl_obj.dir\Tree.c.obj src\CMakeFiles\common_ssl_obj.dir\Socket.c.obj src\CMakeFiles\common_ssl_obj.dir\Log.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistence.c.obj src\CMakeFiles\common_ssl_obj.dir\Thread.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolOut.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistenceDefault.c.obj src\CMakeFiles\common_ssl_obj.dir\SocketBuffer.c.obj src\CMakeFiles\common_ssl_obj.dir\LinkedList.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProperties.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTReasonCodes.c.obj src\CMakeFiles\common_ssl_obj.dir\Base64.c.obj src\CMakeFiles\common_ssl_obj.dir\SHA1.c.obj src\CMakeFiles\common_ssl_obj.dir\WebSocket.c.obj src\CMakeFiles\common_ssl_obj.dir\StackTrace.c.obj src\CMakeFiles\common_ssl_obj.dir\Heap.c.obj src\CMakeFiles\paho-mqtt3cs.dir\MQTTClient.c.obj src\CMakeFiles\paho-mqtt3cs.dir\SSLSocket.c.obj /out:src\paho-mqtt3cs.dll /implib:src\paho-mqtt3cs.lib /pdb:src\paho-mqtt3cs.pdb /dll /version:1.3 /machine:x64 /nologo /debug /INCREMENTAL C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib ws2_32.lib crypt32.lib RpcRT4.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:src\CMakeFiles\paho-mqtt3cs.dir/intermediate.manifest src\CMakeFiles\paho-mqtt3cs.dir/manifest.res" failed (exit code 1120) with the following output:
>    Creating library src\paho-mqtt3cs.lib and object src\paho-mqtt3cs.exp
> SSLSocket.c.obj : error LNK2019: unresolved external symbol SSL_get_peer_certificate referenced in function SSLSocket_connect
> src\paho-mqtt3cs.dll : fatal error LNK1120: 1 unresolved externals
> ninja: build stopped: subcommand failed.
```

**Comment by JackBoosY** [comment] 2021-11-22 04:23
```
C:\PROGRA~1\MIB055~1\2022\COMMUN~1\VC\Tools\MSVC\1430~1.307\bin\Hostx64\x64\link.exe src\CMakeFiles\common_ssl_obj.dir\MQTTTime.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolClient.c.obj src\CMakeFiles\common_ssl_obj.dir\Clients.c.obj src\CMakeFiles\common_ssl_obj.dir\utf-8.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacket.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPacketOut.c.obj src\CMakeFiles\common_ssl_obj.dir\Messages.c.obj src\CMakeFiles\common_ssl_obj.dir\Tree.c.obj src\CMakeFiles\common_ssl_obj.dir\Socket.c.obj src\CMakeFiles\common_ssl_obj.dir\Log.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistence.c.obj src\CMakeFiles\common_ssl_obj.dir\Thread.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProtocolOut.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTPersistenceDefault.c.obj src\CMakeFiles\common_ssl_obj.dir\SocketBuffer.c.obj src\CMakeFiles\common_ssl_obj.dir\LinkedList.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTProperties.c.obj src\CMakeFiles\common_ssl_obj.dir\MQTTReasonCodes.c.obj src\CMakeFiles\common_ssl_obj.dir\Base64.c.obj src\CMakeFiles\common_ssl_obj.dir\SHA1.c.obj src\CMakeFiles\common_ssl_obj.dir\WebSocket.c.obj src\CMakeFiles\common_ssl_obj.dir\StackTrace.c.obj src\CMakeFiles\common_ssl_obj.dir\Heap.c.obj src\CMakeFiles\paho-mqtt3as.dir\MQTTAsync.c.obj src\CMakeFiles\paho-mqtt3as.dir\MQTTAsyncUtils.c.obj src\CMakeFiles\paho-mqtt3as.dir\SSLSocket.c.obj /out:src\paho-mqtt3as.dll /implib:src\paho-mqtt3as.lib /pdb:src\paho-mqtt3as.pdb /dll /version:1.3 /machine:x64 /nologo /debug /INCREMENTAL C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib ws2_32.lib crypt32.lib RpcRT4.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:src\CMakeFiles\paho-mqtt3as.dir/intermediate.manifest src\CMakeFiles\paho-mqtt3as.dir/manifest.res

> SSLSocket.c.obj : error LNK2019: unresolved external symbol SSL_get_peer_certificate referenced in function SSLSocket_connect
> src\paho-mqtt3as.dll : fatal error LNK1120: 1 unresolved externals
```

_C:\Program Files\OpenSSL-Win64\lib\VC\libssl64MDd.lib_
_C:\Program Files\OpenSSL-Win64\lib\VC\libcrypto64MDd.lib_

Please remove path _C:\Program Files\OpenSSL-Win64_ in environment `PATH` and try again.

**Comment by IshaanKarnik** [comment] 2021-11-22 15:43
Tried that didn't help.

**Comment by JackBoosY** [comment] 2021-11-23 02:11
@IshaanKarnik  Can you move those 2 folder to other place then try again?
This issue is caused by cmake find the custom openssl, not in the vcpkg.

Thanks.

**Comment by IshaanKarnik** [comment] 2021-11-27 18:15
@JackBoosY I formatted my PC and reinstalled everything. I had installed OpenSSL (C:\Program Files\OpenSSL-Win64) even before installing vcpkg and it didn't cause any problem while building paho-mqtt.

**Comment by JackBoosY** [comment] 2021-11-29 03:06
In fact, cmake obviously finds the openssl you manually installed first, let me see how to avoid this.

**Comment by JackBoosY** [comment] 2021-11-29 08:07
According to `FindOpenssl.cmake` provided by [cmake](https://github.com/Kitware/CMake/blob/master/Modules/FindOpenSSL.cmake#L147-L184).

We should always install vcpkg cmake wrapper and undefine `OPENSSL_ROOT_DIR` and set it to _VCPKG_ROOT/installed/TRIPLET_.

**Comment by jimwang118** [comment] 2023-08-15 02:19
This issue has been fixed by PR [22701](https://github.com/microsoft/vcpkg/pull/22701).

**Closed by jimwang118** 2023-08-15 02:19 UTC
Labels: category:port-bug
