### ISSUE TITLE
[vcpkg CI][llvm][salome-med-fichier] don't store on the ci and compile each PR.

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#34923] opened 2023-11-05 18:10 UTC
**Describe the bug**

**Environment**
- OS: windows/linux
- Compiler: -

**To Reproduce**
Create a pull request in vcpkg repo.
Repro code when

**Expected behavior**
It should be install and store 2 of these ports:
- llvm
- salome-med-fichier

**Failure logs**
-(please attached failure logs)
```
error: curl failed to put file to https://vcpkgbinarycacheeastasia.blob.core.windows.net/cache/be70087e7caa1035e8b69e32e03c0396a2a0f7fa56567f0365bc3b9309eab2e7.zip?sv=2023-01-03&st=2023-10-17T21%3A12%3A46Z&se=2024-01-15T21%3A12%3A46Z&sr=c&sp=rcwl&sig=zzYWiaIqPLZRhNBnUzkHREwOCbtheH7R7uL44pqL6Pw%3D with exit code 0 and http code 413.
Stored binaries in 0 destinations in 17 min.
```
```
warning: Failed to compress folder "D:\packages\salome-med-fichier_x64-windows": error: 7zip failed with exit code: (1).
```

**Additional context**
https://dev.azure.com/vcpkg/public/_build/results?buildId=96287&view=logs&jobId=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&j=7922e5c4-0103-5f8f-ad17-45ce9bb98e80&t=66eef212-08d6-5e6c-a560-7d01149d0188
https://dev.azure.com/vcpkg/public/_build/results?buildId=96287&view=logs&j=f79cfdd7-47a8-597f-8f57-dc3e21a8f2ad&t=da63cf11-1f12-503b-6d64-3b2fb713c172

http error code:
413
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413
413 Content Too Large

7zip error code:
https://7zip.bugaco.com/7zip/MANUAL/cmdline/exit_codes.htm
Warning (Non fatal error(s)). For example, one or more files were locked by some other application, so they were not compressed.

**Comment by autoantwort** [comment] 2023-11-05 18:41
Duplicate of https://github.com/microsoft/vcpkg/issues/21905#issuecomment-1013422776

**Closed** 2023-11-06 06:43 UTC
Labels: category:port-bug
