### ISSUE TITLE
[parallelstl] find_package unable to find ParallelSTLConfig.cmake

### ISSUE THREAD

**Issue by rksouthee** [microsoft/vcpkg#9419] opened 2019-12-23 10:48 UTC
After successfully installing `parallelstl:x64-windows` and then attempting to use `find_package(ParallelSTL)` results in the following error:

```
CMake Warning at vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package):
  By not providing "FindParallelSTL.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "ParallelSTL", but CMake did not find one.

  Could not find a package configuration file provided by "ParallelSTL" with
  any of the following names:

    ParallelSTLConfig.cmake
    parallelstl-config.cmake

  Add the installation prefix of "ParallelSTL" to CMAKE_PREFIX_PATH or set
  "ParallelSTL_DIR" to a directory containing one of the above files.  If
  "ParallelSTL" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)
```

It seems that `ParallelSTLConfig.cmake` is not being copied into `vcpkg\installed\x64-windows\share\parallelstl`. I copied `ParallelSTLConfig.cmake` and `ParallelSTLTargets.cmake` into `vcpkg\installed\windows\share\parallelstl`, I also had to replace the line `find_dependency(TBB 2018 REQUIRED tbb)` to `find_dependency(TBB REQUIRED tbb)` in `ParallelSTLConfig.cmake`. With these modifications I'm able to successfully compile an application using parallelstl, however, if I attempt to add the line `find_package(TBB CONFIG REQUIRED)` to my `CMakeLists.txt` which already includes the line `find_package(ParallelSTL CONFIG REQUIRED)` I get an error:

```
CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:195 (_add_library):
  _add_library cannot create imported target "TBB::tbb" because another
  target with the same name already exists.
Call Stack (most recent call first):
  C:/Tools/vcpkg/installed/x64-windows/share/tbb/TBBConfig.cmake:46 (add_library)
  C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake:263 (_find_package)
  CMakeLists.txt:9 (find_package)
```

**Comment by NancyLi1013** [comment] 2019-12-25 09:58
Hi @rksouthee thanks for posting this issue.
 Current version in vcpkg doesn't copy `ParallelSTLConfig.cmake` `ParallelSTLTargets.cmake` to _share/parallelstl_ directory.
I will fix it.
As for the error caused by adding `find_package(TBB CONFIG REQUIRED)
` to CMkaeLists.txt, I don't know why you need to add this line.
Since` TBB::tbb` has been linked to `ParallelSTL`, which will cause conflicts with `ParallelSTL`.
If needed, you can put` find_package(TBB CONFIG REQUIRED)`
before `find_package(ParallelSTL CONFIG REQUIRED)`.

**Comment by rksouthee** [comment] 2019-12-25 13:04
I was already using TBB which is the reason I had the `find_package(TBB CONFIG REQUIRED)` line. Reordering doesn't help and produces the same error.

**Comment by NancyLi1013** [comment] 2019-12-26 01:19
Could you help provide your project case including CMakeLists.txt?
I cannot reproduce it on my local.

**Comment by rksouthee** [comment] 2019-12-26 05:41
I've created a minimal example

```cmd
> dir /b
CMakeLists.txt
hello_pstl.cpp
hello_tbb.cpp

> type CMakeLists.txt
cmake_minimum_required(VERSION 3.12)

project(tbb-test LANGUAGES CXX)

#find_package(TBB CONFIG REQUIRED)
find_package(ParallelSTL CONFIG REQUIRED)

add_executable(hello-tbb hello_tbb.cpp)
target_link_libraries(hello-tbb PRIVATE TBB::tbb)

add_executable(hello-pstl hello_pstl.cpp)
target_link_libraries(hello-pstl PRIVATE pstl::ParallelSTL)

> md build && pushd build && cmake -A x64 -G "Visual Studio 16 2019" -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake .. && popd
-- The CXX compiler identification is MSVC 19.23.28106.4
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.23.28105/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/work/tbb-test/build

> msbuild /nologo /v:q /property:GenerateFullPaths=true build\tbb-test.sln

> cd \Tools\vcpkg

> vcpkg version
Vcpkg package management program version 2019.09.12-nohash

See LICENSE.txt for license information.

> vcpkg list
parallelstl:x64-windows                            20190522-1       Parallel STL is an implementation of the C++ sta...
tbb:x64-windows                                    2019_U8-2        Intel's Threading Building Blocks.

> dir /b installed\x64-windows\share\parallelstl
copyright
ParallelSTLConfig.cmake
ParallelSTLTargets.cmake
vcpkg_abi_info.txt

> fc buildtrees\parallelstl\x64-windows-dbg\ParallelSTLConfig.cmake installed\x64-windows\share\parallelstl\ParallelSTLConfig.cmake
Comparing files BUILDTREES\PARALLELSTL\X64-WINDOWS-DBG\ParallelSTLConfig.cmake and INSTALLED\X64-WINDOWS\SHARE\PARALLELSTL\PARALLELSTLCONFIG.CMAKE
***** BUILDTREES\PARALLELSTL\X64-WINDOWS-DBG\ParallelSTLConfig.cmake
if(PARALLELSTL_BACKEND STREQUAL "tbb")
    find_dependency(TBB 2018 REQUIRED tbb)
endif()
***** INSTALLED\X64-WINDOWS\SHARE\PARALLELSTL\PARALLELSTLCONFIG.CMAKE
if(PARALLELSTL_BACKEND STREQUAL "tbb")
    find_dependency(TBB REQUIRED tbb)
endif()
*****
```

**Comment by NancyLi1013** [comment] 2019-12-26 07:45
Thanks for your above info.
It seems that new version has solved this issue. I test on my local and there is no problem about this.
But you still need to put` find_package(TBB CONFIG REQUIRED)`
before `find_package(ParallelSTL CONFIG REQUIRED)`.
I will update this port to the latest version.

**Comment by NancyLi1013** [comment] 2019-12-26 08:45
I submitted a PR to fix this issue.
Could you help take a look and if this can work for you?

**Comment by rksouthee** [comment] 2019-12-26 10:18
@NancyLi1013 I checked out your branch, and it correctly finds ParallelSTL. An issue now is that one can't write:

```cpp
#include <pstl/algorithm>
#include <pstl/execution>
#include <pstl/memory>
#include <pstl/numeric>
```

These headers are located in the `stdlib` directory of parallelstl. I'm not sure why they're separated, the `parallelstl\windows\pstlvars.bat` adds `stdlib` to the `INCLUDE` environment variable, but they don't seem to install when using CMake.

As for the issue regarding putting `find_package(TBB CONFIG REQUIRED)` before ParallelSTL, this was an issue with the CMake version I had (3.16.2). I've switched to 3.14.7 and I'm not having that issue now.

**Comment by NancyLi1013** [comment] 2019-12-27 01:23
Thanks for your testing and feedback about this issue.
I will go further investigation the issue about `stdlib`.

**Comment by NancyLi1013** [comment] 2019-12-27 07:02
@rksouthee I viewed the source code and found that `stdlib` seems to be not used except for test.
So we can ignore them.
I have disabled `stdlib ` in CMakeLists.txt now. 
Current version should work normally.

**Comment by rksouthee** [comment] 2019-12-27 07:25
If one doesn't have access to the header files in `stdlib` then parallelstl isn't useful. See [Getting Started](https://software.intel.com/en-us/articles/get-started-with-parallel-stl) link on the GitHub repository. The examples (and the examples in intel's repository) use the header files found in `stdlib`.

I don't think `stdlib` should be disabled.

**Comment by NancyLi1013** [comment] 2020-01-03 08:20
I have added `stdlib `to `parallelstl`. 
This should work for you. Please help check if this is what you expected.

**Comment by rksouthee** [comment] 2020-01-03 13:09
@NancyLi1013 Everything is working perfectly, thank you for your help with this issue

**Comment by NancyLi1013** [comment] 2020-01-07 01:16
Thanks for your reply.
The PR has been merged. I close this issue now.

**Closed by NancyLi1013** 2020-01-07 01:16 UTC
Labels: port bug
