### ISSUE TITLE
[request] add download progress bar

### ISSUE THREAD

**Issue by jiakai1000** [microsoft/vcpkg#4954] opened 2018-12-12 04:10 UTC
sometimes my download took too long time.

**Comment by soroshsabz** [comment] 2019-02-14 16:36
ITNOA

I think download progress bar and install progress bar is very pretty and some useful for PowerShell something like `apt` command in ubuntu.

**Comment by wangli28** [comment] 2019-07-25 08:20
Thanks for posting this issue. Closed as duplicate of #4879.

**Closed by wangli28** 2019-07-25 08:20 UTC
Labels: vcpkg feature
