### ISSUE TITLE
[tesseract[training-tools] Build error

### ISSUE THREAD

**Issue by c-toyama** [microsoft/vcpkg#28965] opened 2023-01-15 13:01 UTC
Package: tesseract[core,training-tools]:x64-windows -> 5.2.0#3

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.31.31104.0
-    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 472ed329f 2023-01-13 (2 days ago)

**To Reproduce**

`vcpkg install tesseract[training-tools]:x64-windows`

**Failure logs**

```
-- Using cached tesseract-ocr-tesseract-5ad5325a0aa8effc47ca033625b6a51682f82767.tar.gz.
-- Cleaning sources at C:/apps/vcpkg/buildtrees/tesseract/src/1682f82767-2e636863e8.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/apps/vcpkg/downloads/tesseract-ocr-tesseract-5ad5325a0aa8effc47ca033625b6a51682f82767.tar.gz
-- Using source at C:/apps/vcpkg/buildtrees/tesseract/src/1682f82767-2e636863e8.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Warning at scripts/cmake/vcpkg_copy_pdbs.cmake:44 (message):
  Could not find a matching pdb file for:

      C:/apps/vcpkg/packages/tesseract_x64-windows/bin/tesseract52.dll
      C:/apps/vcpkg/packages/tesseract_x64-windows/debug/bin/tesseract52d.dll

Call Stack (most recent call first):
  ports/tesseract/portfile.cmake:47 (vcpkg_copy_pdbs)
  scripts/ports.cmake:147 (include)


-- Fixing pkgconfig file: C:/apps/vcpkg/packages/tesseract_x64-windows/lib/pkgconfig/tesseract.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/apps/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/apps/vcpkg/packages/tesseract_x64-windows/debug/lib/pkgconfig/tesseract.pc
CMake Error at scripts/cmake/vcpkg_copy_tools.cmake:36 (message):
  Couldn't find tool "ambiguous_words":

      "C:/apps/vcpkg/packages/tesseract_x64-windows/bin/ambiguous_words.exe" does not exist
Call Stack (most recent call first):
  ports/tesseract/portfile.cmake:74 (vcpkg_copy_tools)
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by Adela0814** [comment] 2023-01-16 04:07
Duplicate of https://github.com/microsoft/vcpkg/issues/26847

**Closed by Adela0814** 2023-01-16 04:07 UTC
Labels: category:port-bug
