### ISSUE TITLE
vcpkg export keep asking for emcc

### ISSUE THREAD

**Issue by kotori2** [microsoft/vcpkg#25182] opened 2022-06-11 07:42 UTC
**Describe the bug**
`vcpkg export` keep asking for `emcc`

**Environment**
- OS: Windows 11 21H2
- Compiler: Android NDK 23.2.8568313

**To Reproduce**
1. `vcpkg install mbedtls  --triplet arm64-android`
2. `vcpkg export mbedtls  --triplet arm64-android --prefab`

**Expected behavior**
No error happens

**Failure logs**
```
PS C:\vcpkg> ./vcpkg export mbedtls  --triplet arm64-android --prefab
The following packages are already built and will be exported:
    mbedtls:arm64-android
  * vcpkg-cmake:x64-windows
  * vcpkg-cmake-config:x64-windows
Additional packages (*) need to be exported to complete this operation.
d8187afd-ea4a-4fc3-9aa4-a6782e1ed9af
CMake Error at buildtrees/30.vcpkg_tags.cmake:17 (message):
  The emcc compiler not found in PATH
Call Stack (most recent call first):
  buildtrees/30.vcpkg_tags.cmake:41 (vcpkg_triplet_file)
  buildtrees/30.vcpkg_tags.cmake:73 (vcpkg_get_tags)
```

**Comment by JavaCS** [comment] 2022-06-16 03:27
some issue on macOS with M1

**Comment by glanium** [comment] 2022-06-17 07:26
same here but other packages.
needs urgent fix!!

**Comment by leleliu008** [comment] 2022-07-02 08:47
If this issue still there, you are welcome to use https://github.com/leleliu008/ndk-pkg as an immediate solution.

**Comment by rogerou** [comment] 2022-07-12 02:51
same issue on windows

**Comment by ylz-at** [comment] 2022-07-22 02:06
same issue on windows

**Comment by rpavlik** [comment] 2022-09-30 15:12
Oh this is a dupe of #12359

**Comment by LilyWangLL** [comment] 2022-10-23 03:25
Closed as duplicate of https://github.com/microsoft/vcpkg/issues/12359.

**Closed by LilyWangLL** 2022-10-23 03:25 UTC
Labels: category:community-triplet
