### ISSUE TITLE
use vcpkg to install openssl

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#26630] opened 2022-09-01 07:19 UTC
![image](https://user-images.githubusercontent.com/6965518/187854870-8c74167f-e1e1-49a2-b247-a122bf9d23eb.png)

windows 10 x64

vcpkg install openssl:x64-windows openssl:x64-windows-static

![image](https://user-images.githubusercontent.com/6965518/187855038-107d2984-a140-41a0-bbfe-d664852dcc95.png)

can't done it without kill cmd.exe, please fix it

**Comment by WangHHY19931001** [comment] 2022-09-01 07:20
now need kill jom.exe sub cmd.exe to done

**Comment by LilyWangLL** [comment] 2022-09-06 10:16
Thanks for posting this issue. Did you install anti-virus on your machine?

**Comment by 333fps** [comment] 2022-10-08 08:06
Same problem here. No firewall, no anti-virus....

**Comment by WangHHY19931001** [comment] 2022-10-17 09:41
No firewall, no anti-virus

**Comment by FrankXie05** [comment] 2023-02-14 10:19
Duplicate of https://github.com/microsoft/vcpkg/issues/24134

**Closed by FrankXie05** 2023-02-14 10:19 UTC
Labels: requires:repro
