### ISSUE TITLE
The download link is invalid

### ISSUE THREAD

**Issue by Sunquymans** [microsoft/vcpkg#38008] opened 2024-04-06 14:29 UTC
I'm using the command line "VCPKG install liblzma" has a problem during install, including "https://github.com/tukaani-project/xz/archive/v5.6.0.tar.gz" this resource is no longer exist

**Comment by Cheney-W** [comment] 2024-04-07 06:17
Duplicate of [37968](https://github.com/microsoft/vcpkg/issues/37968)

**Closed** 2024-04-07 06:17 UTC
Labels: depends:upstream-changes
