### ISSUE TITLE
ffmpeg / libavcodec causing linker error by not using -fPIC

### ISSUE THREAD

**Issue by eladm-ultrawis** [microsoft/vcpkg#34906] opened 2023-11-04 19:23 UTC
I have a project that links a bunch of static libraries into a single dynamic library. One of my dependencies is ffmpeg (current baseline is pretty much latest (be7f163bf2985c965aa4757162ad20f799b88a21).

I use clang-16 compiler as specified in the following triplet / toolchain files:

toolchain:
```
set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
```
triplet:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME Linux)
set(VCPKG_CHAINLOAD_TOOLCHAIN_FILE ${CMAKE_CURRENT_LIST_DIR}/../toolchains/clang-toolchain.cmake)
```

When vcpkg builds ffmpeg, I can see in the logs that vcpkg passes --enable-pic as it should.  
All my libraries build fine, however when linking I get the following linker error:

```
/usr/bin/ld: /workspace/cranebit/vcpkg_installed/x64-linux-clang/debug/lib/libavcodec.a(h264_intrapred.o): warning: relocation against `ff_pb_3' in read-only section `.text'
/usr/bin/ld: /workspace/cranebit/vcpkg_installed/x64-linux-clang/debug/lib/libavcodec.a(simple_idct10.o): relocation R_X86_64_PC32 against symbol `ff_pw_32' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

I think this is a bug with the ffmpeg port. 
How can I fix this?

**Environment**
- OS: Linux Ubuntu 22.04
- Compiler: clang 16

**Comment by eladm-ultrawis** [comment] 2023-11-05 15:43
I also tried the same code with gcc 12, and I get similar errors:
```
cpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_synchronization.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_graphcycles_internal.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_kernel_timeout_internal.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_time.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_civil_time.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_time_zone.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_crc_cord_state.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_crc32c.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_crc_internal.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_crc_cpu_detect.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_str_format_internal.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_bad_optional_access.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_stacktrace.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_strerror.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_symbolize.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_malloc_internal.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_debugging_internal.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_demangle_internal.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_strings.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_string_view.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_strings_internal.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_base.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_spinlock_wait.a  -lrt  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_int128.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_bad_variant_access.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_throw_delegate.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_raw_logging_internal.a  /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libabsl_log_severity.a && :
/usr/bin/ld: /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libavcodec.a(h264_intrapred.o): warning: relocation against `ff_pb_3' in read-only section `.text'
/usr/bin/ld: /workspace/cranebit/vcpkg_installed/x64-linux-gcc-13/debug/lib/libavcodec.a(hevcdec.o): relocation R_X86_64_PC32 against symbol `ff_h264_cabac_tables' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

**Comment by Adela0814** [comment] 2023-11-06 06:30
Duplicate of https://github.com/microsoft/vcpkg/issues/31185.

**Closed** 2023-11-06 06:31 UTC
Labels: category:port-bug
