### ISSUE TITLE
In-tree CONTROL file (like e.g. Gemfile.lock or requirements.txt)?

### ISSUE THREAD

**Issue by zx64** [microsoft/vcpkg#4935] opened 2018-12-10 02:12 UTC
I couldn't see any reference to this concept in the documentation, so I'm filing this issue as a question:
Is there support/would such a feature be considered in scope for external projects not part of the vcpkg ports tree to somehow specify their dependencies so the following use case would work:
```
> git clone https://github.com/someuser/someproject
> cd someproject
> vcpkg install -r vcpkg_requirements.txt
```
(`install -r etc.` being obviously bikeshedable, I just went with what [pip](https://pip.readthedocs.io/en/1.1/requirements.html) does to flesh out the use case)

**Comment by wangli28** [comment] 2019-07-25 08:37
Thanks for posting this issue. Closed as duplicate of #4686.

**Comment by sylveon** [comment] 2019-07-25 18:11
It's not a duplicate. Issue #4686 is about installing ports from another directory than the regular ports directory, this is about adding a file in a project which tells vcpkg which ports to install so that the project builds correctly, kind of like `packages.config` does for NuGet.

**Comment by ubsan** [comment] 2019-07-25 20:15
Reopened as not-a-duplicate 😄

**Comment by ubsan** [comment] 2019-07-25 20:18
We have Plans for this, but we need to do quite a bit of design and engineering work, so it's unlikely to come soon.

**Comment by PhoebeHui** [comment] 2021-05-08 05:47
I think this can be solved by using [manifest](https://github.com/microsoft/vcpkg/blob/master/docs/users/manifests.md) feature. Please reopen this issue if I misunderstand something here.

**Closed by PhoebeHui** 2021-05-08 05:47 UTC
Labels: category:vcpkg-feature

**Comment by dg0yt** [comment] 2021-05-08 06:09
> `vcpkg install -r vcpkg_requirements.txt`

There are also response files. So you can do:
~~~
vcpkg install @vcpkg_requirements.txt
~~~

But be warned that these files can supply any parameter, not just package names.
