### ISSUE TITLE
[shiva_sfml] Portfile needs refactoring

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#6583] opened 2019-05-23 13:35 UTC
Tries to manually link all dependencies from the portfile (although cmake port):
https://github.com/microsoft/vcpkg/blob/52dfee03b570971599767e10508e54bff95dc4cd/ports/shiva-sfml/portfile.cmake#L69-L141

Better: 
Patch find_package und find_libraries call in shiva_sfml to do the right thing. The current way is probably also susceptible to OS changes and static/dynamic name changes in libraries.

**Comment by Thomas1664** [comment] 2022-02-15 20:20
@Neumann-A , @FrankXie05 
It seems that the port `shiva-sfml` is kind of a duplicate of `shiva`. Both ports use the same repo and the same tag.
Because the portfile of `shiva-sfml` is ugly I suggest to remove this port. The description says that `shiva-sfml` contains plugins for `shiva` but I can't see that `shiva-sfml` adds any functionality.

**Comment by FrankXie05** [comment] 2022-03-04 06:47
@Neumann-A What do you think about what [Thomas1664](https://github.com/Thomas1664) said ？

**Comment by Neumann-A** [comment] 2022-03-04 06:56
@FrankXie05 I don't know anything about the details of shiva-sfml/shiva. I just observed the portfile and saw it did questionable stuff. Maybe the port was created when features in vcpkg were not yet available?

**Comment by FrankXie05** [comment] 2022-04-13 07:31
cc @BillyONeal Both port shiva and port shiva_sfml seem to be doing the same thing, is it necessary to keep two identical ports?

**Comment by dg0yt** [comment] 2023-05-26 21:12
Both ports are unmaintained... and only ci.baseline.txt ensures that they are not build in the same triplet. 
Now I have to add shiva-sfml fails for android.

**Comment by PhoebeHui** [comment] 2023-05-31 08:06
> cc @BillyONeal Both port shiva and port shiva_sfml seem to be doing the same thing, is it necessary to keep two identical ports?

Hi @Milerius, since you are the author of this port, can we merge shiva and port shiva_sfml togather, is it possible to use SHIVA_USE_SFML_AS_RENDERER and SHIVA_INSTALL_PLUGINS as features in shiva instead?

**Comment by PhoebeHui** [comment] 2023-05-31 08:07
Related to https://github.com/microsoft/vcpkg/issues/9116

**Closed** 2023-10-13 03:30 UTC
Labels: category:port-update
