### ISSUE TITLE
ITK install fails if hdf5 is installed. 

### ISSUE THREAD

**Issue by MarkIanHolland** [Microsoft/vcpkg#3867] opened 2018-07-08 11:54 UTC
I found I couldn't install ITK on Windows 10 if VTK has already been installed. Seems to be down to the hdf5 dependency, it's mentioned in the [comments ](https://github.com/Microsoft/vcpkg/blob/47f362db993e31588f72f08e2982b04ae924430c/ports/itk/portfile.cmake#L42)of the ITK portfile.

Windows 10, Version 1709.
The steps to reproduce: vcpkg install vtk, [~~add disable_parallel_configure~~]( https://github.com/Microsoft/vcpkg/issues/3115#issuecomment-399488948) vcpkg install itk
OR more specifically: vcpkg install hdf5[cpp], [~~add disable_parallel_configure~~]( https://github.com/Microsoft/vcpkg/issues/3115#issuecomment-399488948) vcpkg install itk
The outcome you expected: Install successful
The actual outcome: **[BUILD_FAILED](https://github.com/Microsoft/vcpkg/files/2171436/output.txt)**
> -- Building x64-windows-dbg
> CMake Error at scripts/cmake/vcpkg_build_cmake.cmake:170 (message):
>     Command failed: C:/vcpkg/downloads/tools/cmake-3.11.4-windows/cmake-3.11.4-win32-x86/bin/cmake.exe;--build;.;--config;Debug;--target;install;--;-v;-j1
>     Working Directory: C:/vcpkg/buildtrees/itk/x64-windows-dbg
>     See logs for more information:
>       C:\vcpkg\buildtrees\itk\install-x64-windows-dbg-out.log

**[install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2171438/install-x64-windows-dbg-out.log)**
> C:\vcpkg\installed\x64-windows\include\H5Tpkg.h(23): fatal error C1189: #error:  "Do not include this file outside the H5T package!"

I tried specifying HDF5[cpp] as a [build dependency](https://github.com/Microsoft/vcpkg/pull/3425/commits/ed9357a5aafea7192932b5874264bd103fc61255) for ITK. [BUILD_FAILED](https://github.com/Microsoft/vcpkg/files/2173210/output2.txt), problems with the hdf5-static target.  [install-x64-windows-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2173209/install-x64-windows-dbg-out.log). Adding a [patch](https://github.com/MarkIanHolland/vcpkg/blob/ITK/ports/itk/find-hdf5.patch) to help find the targets seemed to work for me, but only occasionally.

**Comment by sarthakpati** [comment] 2018-07-12 20:09
I am having better luck by ensuring that ITK/VTK build HDF5 on their own. I have no idea whether or not this is the right way to go, though.

**Comment by alexkaratarakis** [comment] 2018-07-13 23:15
@sarthakpati 
The preferred way is to consume HDF5 (and generally any dependencies) from vcpkg. This ensures that any dependency is consistent across all libraries consuming it.

**Comment by sarthakpati** [comment] 2018-07-16 13:03
@alexkaratarakis of course I agree with this, but I haven't found a way to get the builds working that way, for whatever reason.

**Comment by MarkIanHolland** [comment] 2018-07-17 12:40
Setting `VCPKG_LIBRARY_LINKAGE `to `static `leads to a successful build for me. I'm assuming thats bad practice for a portfile, and more custom triplet territory?

I also tried to configure ITK to BUILD_SHARED_LIBS but I still seem to get a [hdf5-static target error](https://github.com/Microsoft/vcpkg/files/2201616/install-x64-windows-dbg-out.log). 

```
if(VCPKG_LIBRARY_LINKAGE STREQUAL static)
    list(APPEND ADDITIONAL_OPTIONS -DBUILD_SHARED_LIBS=OFF)
else()
    list(APPEND ADDITIONAL_OPTIONS -DBUILD_SHARED_LIBS=ON)
endif()
```

**Comment by KrisThielemans** [comment] 2018-08-10 14:37
I wonder if this isn't due to bugs in `FindHDF5.cmake` in older CMake versions which I helped fixing. Try CMake 3.11 or later.

**Comment by sarthakpati** [comment] 2018-08-10 14:52
@MarkIanHolland static linkage is unfortunately not an option for me since I am trying to use this in a project that needs Qt. Until now, I have been simply linking against Qt built dynamically but compiling static version of ITK and VTK but with vcpkg this is not possible.

@KrisThielemans I have CMake 3.11.4 and still no dice.

**Comment by sarthakpati** [comment] 2018-09-26 07:05
@MarkIanHolland I used the mixed type linkage to solve my issue. In essence, ensuring static linkage works fine! Thanks.

**Comment by tetsuh** [comment] 2018-10-06 00:15
Looks ITK's Modules/ThirdParty/HDF5/CMakeLists.txt has confusion with config mode and module mode of find_package().
I modified it only  for config mode, then CMake works with hdf5::hdf5-shared
```
  if(ITK_BUILD_SHARED_LIBS)
    set(ITKHDF5_LIBRARIES hdf5::hdf5-shared hdf5::hdf5_cpp-shared)
  else()
    set(ITKHDF5_LIBRARIES hdf5::hdf5-static hdf5::hdf5_cpp-static)
  endif()
```
I successfully build itk:x64-windows with -DITK_USE_SYSTEM_HDF5=ON
https://github.com/tetsuh/vcpkg/commits/itk-hdf5-config_mode-find_package

**Comment by MarkIanHolland** [comment] 2018-10-09 12:41
Great! Any chance of a PR?

**Comment by tetsuh** [comment] 2018-10-12 06:08
Sure, I make PR.  I confirmed itk:x86-windows. I'll check x64-static and x86-static also.  thnx.

**Comment by tetsuh** [comment] 2019-01-05 00:32
I just rebased PR #4472 based on latest master branch.
It may or  may not merged because ad-hoc patch to ITK build.

I know ports/vtk contain similar patches to fix cmake find modules.
but I would not like such changes which makes maintain harder.

I will consider improvements that ITK itself can support both configuration mode and module mode.

**Closed** 2019-03-07 20:00 UTC
Labels: port bug
