### ISSUE TITLE
VTK does not compile

### ISSUE THREAD

**Issue by dzenanz** [Microsoft/vcpkg#739] opened 2017-03-07 16:30 UTC
```
-- CURRENT_INSTALLED_DIR=C:/Libs/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Libs/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Libs/vcpkg/packages/vtk_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Libs/vcpkg/buildtrees/vtk
-- CURRENT_PORT_DIR=C:/Libs/vcpkg/ports/vtk/.
-- Downloading http://www.vtk.org/files/release/7.1/VTK-7.1.0.tar.gz...
-- Downloading http://www.vtk.org/files/release/7.1/VTK-7.1.0.tar.gz... OK
-- Testing integrity of downloaded file...
-- Testing integrity of downloaded file... OK
-- Extracting source C:/Libs/vcpkg/downloads/VTK-7.1.0.tar.gz
-- Extracting done
-- Applying patch C:/Libs/vcpkg/ports/vtk/transfer-3rd-party-module-definitions.patch
-- Applying patch C:/Libs/vcpkg/ports/vtk/transfer-3rd-party-module-definitions.patch done
-- Applying patch C:/Libs/vcpkg/ports/vtk/transfer-hdf5-definitions.patch
-- Applying patch C:/Libs/vcpkg/ports/vtk/transfer-hdf5-definitions.patch done
-- Applying patch C:/Libs/vcpkg/ports/vtk/netcdf-use-hdf5-definitions.patch
-- Applying patch C:/Libs/vcpkg/ports/vtk/netcdf-use-hdf5-definitions.patch done

-- Applying patch C:/Libs/vcpkg/ports/vtk/dont-define-ssize_t.patch
-- Applying patch C:/Libs/vcpkg/ports/vtk/dont-define-ssize_t.patch done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:14 (message):
    Command failed: C:/Program Files/CMake/bin/cmake.exe;--build;.;--config;Release;--target;install;--;-v
    Working Directory: C:/Libs/vcpkg/buildtrees/vtk/x64-windows-rel
    See logs for more information:
      C:\Libs\vcpkg\buildtrees\vtk\package-x64-windows-rel-out.log
      C:\Libs\vcpkg\buildtrees\vtk\package-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:66 (vcpkg_install_cmake)
  scripts/ports.cmake:73 (include)


Error: Building package vtk:x64-windows failed with: BUILD_FAILED
```
*-rel-out.log contains: `LINK : fatal error LNK1181: cannot open input file 'hdf5-shared.lib'`. Indeed, file `hdf5-shared.lib` does not exist on my computer, but rather `hdf5.lib`.

@RobertSpir Did you test VTK installation with shared libraries or only static libraries?

**Comment by ras0219-msft** [comment] 2017-03-08 00:51
hdf5's CMake configure files provide a target named "hdf5-shared" which _should_ cause linking against `hdf5.lib` and inclusion of the appropriate header directory. I've done some initial debugging and it looks like the target is defined as expected.

However, somehow, the actual link process is resolving `hdf5-shared` as a library name instead of a target.

**Comment by phsucharee** [comment] 2017-04-16 00:01
The problem is in the FindHDF5.cmake under C:\vcpkg\buildtrees\vtk\src\VTK-7.1.0\CMake:

```
# include the default FindHDF5.cmake.
if(CMAKE_VERSION VERSION_LESS 3.6.1)
  include(${CMAKE_CURRENT_LIST_DIR}/NewCMake/FindHDF5.cmake)
else()
  include(${CMAKE_ROOT}/Modules/FindHDF5.cmake)
endif()
```

Since the version of CMake that comes with VS2017 is a fork of CMake 3.6 with version number 3.6.20160606-g0391f-MSVC, the lines above pick the FindHDF5.cmake from this version, which causes this behaviour.

It should pick the FindHDF5.cmake that comes with vtk in the NewCMake folder, that will put together the right library path and names for hdf5.

To solve this issue I just commented the if-else-clause out and included the NewCMake/FindHDF5.cmake version directly. Though I'm not sure why the default FindHDF5.cmake was included in the first place.

**Comment by jasjuang** [comment] 2017-06-09 21:02
I ran into the same problem and @phsucharee 's temporary fix works for me.

**Closed** 2017-07-05 03:03 UTC
Labels: port bug
