### ISSUE TITLE
[magnum-plugins] Build failue

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#31112] opened 2023-04-25 14:13 UTC
Package: magnum-plugins[core,meshoptimizersceneconverter]:x64-osx -> 2020.06#10

**Host Environment**

- Host: x64-osx
- Compiler: AppleClang 14.0.3.14030022
-    vcpkg-tool version: 2999-12-31-unknownhash
    vcpkg-scripts version: 5787cfa69 2023-04-24 (10 hours ago)

**To Reproduce**

`vcpkg install --enforce-port-checks --allow-unsupported`

**Failure logs**

```
-- Using cached mosra-magnum-plugins-v2020.06.tar.gz.
-- Cleaning sources at /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/src/v2020.06-79ad147c2a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /Users/leanderSchulten/git_projekte/vcpkg/downloads/mosra-magnum-plugins-v2020.06.tar.gz
-- Applying patch 002-fix-stb-conflict.patch
-- Using source at /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/src/v2020.06-79ad147c2a.clean
CMake Warning at ports/magnum-plugins/portfile.cmake:59 (message):
  Features cgltfimporter, glslangshaderconverter, ktximageconverter,
  ktximporter, openexrimageconverter, openexrimporter,
  spirvtoolsshaderconverter and stbdxtimageconverter are not available when
  building non-head version.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)


-- Found external ninja('1.11.1').
-- Configuring x64-osx
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /Users/leanderSchulten/git_projekte/vcpkg/downloads/tools/cmake-3.25.1-osx/cmake-3.25.1-macos-universal/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j11
    Working Directory: /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/x64-osx-dbg
    See logs for more information:
      /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  vcpkg_installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  vcpkg_installed/arm64-osx/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/magnum-plugins/portfile.cmake:87 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)



```
<details><summary>/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/install-x64-osx-dbg-out.log</summary>

```
[1/5] cd /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/src/v2020.06-79ad147c2a.clean/src/MagnumPlugins/MeshOptimizerSceneConverter && /Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/tools/corrade/corrade-rc MeshOptimizerSceneConverter /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/x64-osx-dbg/src/MagnumPlugins/MeshOptimizerSceneConverter/resources_MeshOptimizerSceneConverter.conf /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/x64-osx-dbg/src/MagnumPlugins/MeshOptimizerSceneConverter/resource_MeshOptimizerSceneConverter.cpp
[2/5] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCORRADE_IS_DEBUG_BUILD -DCORRADE_STATIC_PLUGIN -I/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/src/v2020.06-79ad147c2a.clean/src -I/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/x64-osx-dbg/src -isystem /Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/include -isystem /Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/include/MagnumExternal/OpenGL -fPIC -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -fPIC -std=c++11 -Wall -Wextra -Wold-style-cast -Winit-self -Werror=return-type -Wmissing-declarations -Wpedantic -fvisibility=hidden -fvisibility-inlines-hidden -Wmissing-prototypes -Wno-shorten-64-to-32 -MD -MT src/MagnumPlugins/MeshOptimizerSceneConverter/CMakeFiles/MeshOptimizerSceneConverter.dir/resource_MeshOptimizerSceneConverter.cpp.o -MF src/MagnumPlugins/MeshOptimizerSceneConverter/CMakeFiles/MeshOptimizerSceneConverter.dir/resource_MeshOptimizerSceneConverter.cpp.o.d -o src/MagnumPlugins/MeshOptimizerSceneConverter/CMakeFiles/MeshOptimizerSceneConverter.dir/resource_MeshOptimizerSceneConverter.cpp.o -c /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/x64-osx-dbg/src/MagnumPlugins/MeshOptimizerSceneConverter/resource_MeshOptimizerSceneConverter.cpp
[3/5] /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCORRADE_IS_DEBUG_BUILD -DCORRADE_STATIC_PLUGIN -I/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/src/v2020.06-79ad147c2a.clean/src -I/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/x64-osx-dbg/src -isystem /Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/include -isystem /Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/include/MagnumExternal/OpenGL -fPIC -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -fPIC -std=c++11 -Wall -Wextra -Wold-style-cast -Winit-self -Werror=return-type -Wmissing-declarations -Wpedantic -fvisibility=hidden -fvisibility-inlines-hidden -Wmissing-prototypes -Wno-shorten-64-to-32 -MD -MT src/MagnumPlugins/MeshOptimizerSceneConverter/CMakeFiles/MeshOptimizerSceneConverter.dir/MeshOptimizerSceneConverter.cpp.o -MF src/MagnumPlugins/MeshOptimizerSceneConverter/CMakeFiles/MeshOptimizerSceneConverter.dir/MeshOptimizerSceneConverter.cpp.o.d -o src/MagnumPlugins/MeshOptimizerSceneConverter/CMakeFiles/MeshOptimizerSceneConverter.dir/MeshOptimizerSceneConverter.cpp.o -c /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/src/v2020.06-79ad147c2a.clean/src/MagnumPlugins/MeshOptimizerSceneConverter/MeshOptimizerSceneConverter.cpp
FAILED: src/MagnumPlugins/MeshOptimizerSceneConverter/CMakeFiles/MeshOptimizerSceneConverter.dir/MeshOptimizerSceneConverter.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DCORRADE_IS_DEBUG_BUILD -DCORRADE_STATIC_PLUGIN -I/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/src/v2020.06-79ad147c2a.clean/src -I/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/x64-osx-dbg/src -isystem /Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/include -isystem /Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/include/MagnumExternal/OpenGL -fPIC -g -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.3.sdk -fPIC -std=c++11 -Wall -Wextra -Wold-style-cast -Winit-self -Werror=return-type -Wmissing-declarations -Wpedantic -fvisibility=hidden -fvisibility-inlines-hidden -Wmissing-prototypes -Wno-shorten-64-to-32 -MD -MT src/MagnumPlugins/MeshOptimizerSceneConverter/CMakeFiles/MeshOptimizerSceneConverter.dir/MeshOptimizerSceneConverter.cpp.o -MF src/MagnumPlugins/MeshOptimizerSceneConverter/CMakeFiles/MeshOptimizerSceneConverter.dir/MeshOptimizerSceneConverter.cpp.o.d -o src/MagnumPlugins/MeshOptimizerSceneConverter/CMakeFiles/MeshOptimizerSceneConverter.dir/MeshOptimizerSceneConverter.cpp.o -c /Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/src/v2020.06-79ad147c2a.clean/src/MagnumPlugins/MeshOptimizerSceneConverter/MeshOptimizerSceneConverter.cpp
/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/src/v2020.06-79ad147c2a.clean/src/MagnumPlugins/MeshOptimizerSceneConverter/MeshOptimizerSceneConverter.cpp:318:27: error: no matching function for call to 'meshopt_simplifySloppy'
            vertexCount = meshopt_simplifySloppy(outputIndices.data(), inputIndices, out.indexCount(), static_cast<const float*>(positions.data()), out.vertexCount(), positions.stride(), targetIndexCount);
                          ^~~~~~~~~~~~~~~~~~~~~~
/Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/include/meshoptimizer.h:962:15: note: candidate function template not viable: requires at least 8 arguments, but 7 were provided
inline size_t meshopt_simplifySloppy(T* destination, const T* indices, size_t index_count, const float* vertex_positions, size_t vertex_count, size_t vertex_positions_stride, size_t target_index_count, float target_error, float* result_error)
              ^
/Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/include/meshoptimizer.h:354:35: note: candidate function not viable: requires 9 arguments, but 7 were provided
MESHOPTIMIZER_EXPERIMENTAL size_t meshopt_simplifySloppy(unsigned int* destination, const unsigned int* indices, size_t index_count, const float* vertex_positions, size_t vertex_count, size_t vertex_positions_stride, size_t target_index_count, float target_error, float* result_error);
                                  ^
/Users/leanderSchulten/git_projekte/vcpkg/buildtrees/magnum-plugins/src/v2020.06-79ad147c2a.clean/src/MagnumPlugins/MeshOptimizerSceneConverter/MeshOptimizerSceneConverter.cpp:320:27: error: no matching function for call to 'meshopt_simplify'
            vertexCount = meshopt_simplify(outputIndices.data(), inputIndices, out.indexCount(), static_cast<const float*>(positions.data()), out.vertexCount(), positions.stride(), targetIndexCount, targetError);
                          ^~~~~~~~~~~~~~~~
/Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/include/meshoptimizer.h:953:15: note: candidate template ignored: could not match 'const T *' against 'Containers::ArrayView<const UnsignedInt>' (aka 'ArrayView<const unsigned int>')
inline size_t meshopt_simplify(T* destination, const T* indices, size_t index_count, const float* vertex_positions, size_t vertex_count, size_t vertex_positions_stride, size_t target_index_count, float target_error, unsigned int options, float* result_error)
              ^
/Users/leanderSchulten/git_projekte/vcpkg/vcpkg_installed/x64-osx/include/meshoptimizer.h:339:26: note: candidate function not viable: requires 10 arguments, but 8 were provided
MESHOPTIMIZER_API size_t meshopt_simplify(unsigned int* destination, const unsigned int* indices, size_t index_count, const float* vertex_positions, size_t vertex_count, size_t vertex_positions_stride, size_t target_index_count, float target_error, unsigned int options, float* result_error);
                         ^
2 errors generated.
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg-tool/main/docs/vcpkg.schema.json",
  "name": "lichtsteuerung",
  "version-string": "2.0 $.0",
  "dependencies": [
    {
      "name": "magnum-plugins",
      "default-features": false,
      "features": [
        "meshoptimizersceneconverter"
      ]
    }
  ],
  "$overrides": [
    {
      "name": "capstone",
      "version": "4.0.1-120373dc"
    }
  ],
  "$builtin-baseline": "338f99eed499b6df1628829e40695b396a70a1f7"
}

```
</details>

**Comment by autoantwort** [comment] 2023-04-25 15:38
I guess magnum-plugins is too old and the used dependency to new?

**Comment by LilyWangLL** [comment] 2023-04-26 02:31
Closed as duplicate of https://github.com/microsoft/vcpkg/issues/30975.

**Closed by LilyWangLL** 2023-04-26 02:31 UTC
Labels: category:port-bug
