### ISSUE TITLE
vcpkg install fails when CLICOLOR_FORCE=1

### ISSUE THREAD

**Issue by silvakj** [microsoft/vcpkg#20430] opened 2021-09-29 15:00 UTC
**Describe the bug**
If the environment variable `CLICOLOR_FORCE` is enabled, the `vcpkg install` command fails during the `Computing installation plan...` step.

I **assume** the issue is related to [this section of code in the vcpkg tool repo](https://github.com/microsoft/vcpkg-tool/blob/main/src/vcpkg/cmakevars.cpp#L240-L262). Vcpkg makes an internal call to CMake and parses the output. Since the CMake output is not being sent to the terminal it would normally be raw output,  but with `CLICOLOR_FORCE` enabled (which is done to produce colorized command line output in containerized pipeline environments where tty is disabled) the internal call to CMake is producing colorized code which is failing to be parsed by vcpkg.

**Assumed** fix. Vcpkg needs to prevent colorized output from internal calls to CMake, or vcpkg needs to strip/clean color data from output of internal CMake calls.

**Environment**
- OS: Linux (discovered in RHEL7 Docker container)
- Compiler: any

**To Reproduce**
1. export CLICOLOR_FORCE=1
2. ./vcpkg install xxxx
3. See error

**Expected behavior**
Package successfully installs.

**Failure logs** 
Output:
```
Computing installation plan...
Failed to parse CMake console output to locate port start/end markers
```

**Additional context**
Workaround: Set `CLICOLOR_FORCE=0` prior to calling `vcpkg install`

**Comment by PhoebeHui** [comment] 2021-09-30 06:51
@silvakj, thanks for bringing up this!

Confirmed, this issue could be reproed via ubuntu 18.04, @BillyONeal, could you please take a look?

```
./vcpkg install cjson --debug
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: /home/phoebe/test/vcpkg
[DEBUG] Using installed-root: /home/phoebe/test/vcpkg/installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: /home/phoebe/test/vcpkg/buildtrees
[DEBUG] Using downloads-root: /home/phoebe/test/vcpkg/downloads
[DEBUG] Using packages-root: /home/phoebe/test/vcpkg/packages
[DEBUG] Using scripts-root: /home/phoebe/test/vcpkg/scripts
[DEBUG] Using ports-root: /home/phoebe/test/vcpkg/ports
[DEBUG] Using versions-root: /home/phoebe/test/vcpkg/versions
[DEBUG] Default binary cache path is: /home/phoebe/.cache/vcpkg/archives
Computing installation plan...
[DEBUG] Found path: /usr/local/bin/cmake
[DEBUG] Found path: /usr/bin/cmake
[DEBUG] popen(/home/phoebe/test/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake --version 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after     4964 us
[DEBUG] popen(/home/phoebe/test/vcpkg/downloads/tools/cmake-3.21.1-linux/cmake-3.21.1-linux-x86_64/bin/cmake -DVCPKG_ROOT_DIR=/home/phoebe/test/vcpkg -DPACKAGES_DIR=/home/phoebe/test/vcpkg/packages -DBUILDTREES_DIR=/home/phoebe/test/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=/home/phoebe/test/vcpkg/installed -DDOWNLOADS=/home/phoebe/test/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P /home/phoebe/test/vcpkg/buildtrees/0.vcpkg_tags.cmake 2>&1)
[DEBUG] cmd_execute_and_stream_data() returned 0 after     5039 us
Failed to parse CMake console output to locate port start/end markers
[DEBUG] /home/phoebe/test/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-09-10/src/vcpkg/cmakevars.cpp(248)
```

**Comment by BillyONeal** [comment] 2021-10-01 23:39
> @BillyONeal, could you please take a look?

Looks like a legitimate bug but not something I have time to address right now.

**Comment by aminya** [comment] 2021-10-30 06:32
I also faced the issue when I ran cmake from make files. Directly calling cmake in bash does not have this issue. Very strange error

**Comment by aminya** [comment] 2021-10-30 06:39
> > @BillyONeal, could you please take a look?
> 
> Looks like a legitimate bug but not something I have time to address right now.

This affects building things inside WSL. I believe this is a very important bug.

**Comment by dg0yt** [comment] 2021-10-30 07:19
> I believe this is a very important bug.

You can easily workaround by putting `CLICOLOR_FORCE=0` in front of your `vcpkg` call.

**Comment by aminya** [comment] 2021-10-30 08:08
> > I believe this is a very important bug.
> 
> You can easily workaround by putting `CLICOLOR_FORCE=0` in front of your `vcpkg` call.

Did not work for me from inside a Makefile. It was time to switch to a better task runner like [Task.dev](https://taskfile.dev/#/). Fortunately, it works there without the need for setting env variables.

**Comment by dg0yt** [comment] 2021-10-30 08:43
Also affects macOS.

**Comment by niyue** [comment] 2021-11-09 13:26
It seems this should be resolved by the Vcpkg-tool 2021-11-02, however, I gave it a test and the problem still exist (at least in my testing setup), additionally, in my setup, I cannot workaround the issue even by setting the env var CLICOLOR_FORCE=0

I created a minimum env using docker for reproducing this issue. You can check it out here:
[vcpkg-cmake-port-marker.zip](https://github.com/microsoft/vcpkg/files/7504975/vcpkg-cmake-port-marker.zip)

There are three files in the archive:
1) A `Makefile` with contents like
```
build:
	CLICOLOR_FORCE=0 /usr/src/vcpkg/vcpkg install fmt
```
2) A `Dockerfile` with debian:bullseye-20210927 as base image, and install vcpkg inside the container
3) A `docker-compose.yml` building the container (setting the env var `CLICOLOR_FORCE` to 0 as well)

After using docker-compose to `build` and `exec` /bin/bash in the container, simply running the following command to get it reproduced:
```
cd /usr/src
make
```

It will report error like below:
```
root@207fedb0e0c2:~# make
CLICOLOR_FORCE=0 /usr/src/vcpkg/vcpkg install fmt
Computing installation plan...
Failed to parse CMake console output to locate port start/end markers
make: *** [Makefile:2: build] Error 1
root@207fedb0e0c2:~# vcpkg --version
Vcpkg package management program version 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42

See LICENSE.txt for license information.
root@207fedb0e0c2:~# /usr/src/vcpkg/vcpkg --version
Vcpkg package management program version 2021-11-02-af04ebf6274fd6f7a941bff4662b3955c64f6f42

See LICENSE.txt for license information.
```
As you can see, the vcpkg is updated to the latest version (2021-11-02-xxx), which seems to get this issue addressed according to the release notes.

**Comment by dg0yt** [comment] 2021-11-09 15:37
@niyue Can you check if `CLICOLOR` is set in your environment?

IIUC the reference for these variables is https://bixense.com/clicolors/.

**Comment by BillyONeal** [comment] 2021-11-09 18:06
Given that you're explicitly turning the environment variable off @niyue , that seems to be at least a different bug, unrelated to the `CLICOLOR_FORCE` one. Given the docker context I suspect what's actually happening is attempting to run cmake is failing completely with some form of error message that we don't know how to parse.

**Comment by niyue** [comment] 2021-11-09 22:52
@dg0yt 
> @niyue Can you check if CLICOLOR is set in your environment?

I disable it by setting it to `0` explicitly, both in the `docker-compose.yml` for the container and prepending `CLICOLOR_FORCE=0` to the `vcpkg install` command, but it doesn't help. 
You can check out the attached archive for reproducing the issue.

**Comment by niyue** [comment] 2021-11-09 22:52
@BillyONeal 
> that seems to be at least a different bug
> I suspect what's actually happening is attempting to run cmake is failing completely with some form of error message that we don't know how to parse

It could be a different bug but the error message looks the same. I think it probably relates with running vcpkg inside `Makefile`. I tried running the same command inside `Makefile` or a shell script, and it will report such an error, but if I paste the same vcpkg install command and run it directly within bash, it will work.
@BillyONeal Do you think if I need to file another issue for this?

**Comment by dg0yt** [comment] 2021-11-09 23:09
> I disable it by setting it to `0` explicitly, both in the `docker-compose.yml` for the container and prepending `CLICOLOR_FORCE=0` to the `vcpkg install` command, but it doesn't help.

Please note the spelling: 
Is `CLICOLOR` (!) set in your environment?
Not `CLICOLOR_FORCE`.

**Comment by BillyONeal** [comment] 2021-11-09 23:30
>It could be a different bug but the error message looks the same

That error message is emitted whenever cmake's output was funny for some reason. Please also respond to dg0yt.

**Comment by niyue** [comment] 2021-11-10 00:27
@dg0yt 

> Please note the spelling:
> Is CLICOLOR (!) set in your environment?

Sorry I didn't realize the difference initially. I tried setting `CLICOLOR=0` and it did work. Thanks for the help.

```
root@16ca5338b3ee:/usr/src# export CLICOLOR=1
root@16ca5338b3ee:/usr/src# make
/usr/src/vcpkg/vcpkg install fmt
Computing installation plan...
Failed to parse CMake console output to locate port start/end markers
make: *** [Makefile:2: build] Error 1

root@16ca5338b3ee:/usr/src# export CLICOLOR=0
root@16ca5338b3ee:/usr/src# make
/usr/src/vcpkg/vcpkg install fmt
Computing installation plan...
The following packages will be built and installed:
    fmt[core]:x64-linux -> 8.0.1
Detecting compiler hash for triplet x64-linux...
```

**Comment by tlemo** [comment] 2021-12-01 18:17
FYI, I just submited a [PR](https://github.com/microsoft/vcpkg-tool/pull/290) to fix this.

**Comment by PhoebeHui** [comment] 2021-12-29 08:41
The latest release already included the fix.

**Closed by PhoebeHui** 2021-12-29 08:41 UTC
Labels: category:vcpkg-bug, requires:vcpkg-tool-release

**Comment by OkamiMks** [comment] 2022-05-06 09:15
Hi, I recently came across the same error.

**I managed to solve it by downloading the Cmake package again, at https://cmake.org/download/**

I hope it can help anyone who encounters this same error in the future <3
