### ISSUE TITLE
 boost-regex:x64-windows failed with : BUILD_FAILED

### ISSUE THREAD

**Issue by antecessor** [Microsoft/vcpkg#6244] opened 2019-04-28 00:28 UTC
I will be grateful if someone tell what is the problem:

I am running on VS2019. 

```
Starting package 33/142: boost-regex:x64-windows
Building package boost-regex[core]:x64-windows...
-- Using cached E:/vcpkg-master/vcpkg/downloads/boostorg-regex-boost-1.69.0.tar.gz
-- Using source at E:/vcpkg-master/vcpkg/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: E:/vcpkg-master/vcpkg/installed/x64-windows/tools/boost-build/b2.exe;--stagedir=E:/vcpkg-master/vcpkg/buildtrees/boost-regex/x64-windows-rel/stage;--build-dir=E:/vcpkg-master/vcpkg/buildtrees/boost-regex/x64-windows-rel;--user-config=E:/vcpkg-master/vcpkg/buildtrees/boost-regex/x64-windows-rel/user-config.jam;-j4;--debug-configuration;--debug-building;--debug-generators;--disable-icu;--ignore-site-config;--hash;-q;-sZLIB_INCLUDE="E:/vcpkg-master/vcpkg/installed/x64-windows/include";-sBZIP2_INCLUDE="E:/vcpkg-master/vcpkg/installed/x64-windows/include";threading=multi;threadapi=win32;runtime-link=shared;link=shared;address-model=64;architecture=x86;toolset=msvc-14.1;-sZLIB_BINARY=zlib;-sZLIB_LIBPATH="E:/vcpkg-master/vcpkg/installed/x64-windows/lib";-sBZIP2_BINARY=bz2;-sBZIP2_LIBPATH="E:/vcpkg-master/vcpkg/installed/x64-windows/lib";variant=release;debug-symbols=on
    Working Directory: E:/vcpkg-master/vcpkg/buildtrees/boost-regex/src/ost-1.69.0-80bf9a4997/build
    Error code: 1
    See logs for more information:
      E:\vcpkg-master\vcpkg\buildtrees\boost-regex\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/boost-build/boost-modular-build.cmake:270 (vcpkg_execute_required_process)
  ports/boost-regex/portfile.cmake:20 (boost_modular_build)
  scripts/ports.cmake:71 (include)


Error: Building package boost-regex:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-regex:x64-windows
  Vcpkg version: 2018.11.23-nohash

```

**Comment by wangli28** [comment] 2019-04-29 08:25
Duplicate of #5976, so close it.

**Closed by wangli28** 2019-04-29 08:25 UTC
