### ISSUE TITLE
[boost-build] Build error

### ISSUE THREAD

**Issue by davidc538** [microsoft/vcpkg#26531] opened 2022-08-26 05:20 UTC
Package: boost-build[core]:x64-linux -> 1.80.0
**Host Environment**
- Host: x64-linux
- Compiler: GNU 11.2.0
-    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: a9dc9a4b3 2022-08-25 (8 hours ago)

**To Reproduce**
`vcpkg install boost-iostreams`

**Failure logs**
```
-- Downloading https://github.com/boostorg/build/archive/boost-1.80.0.tar.gz -> boostorg-build-boost-1.80.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] 6547: popen( curl --fail -L https://github.com/boostorg/build/archive/boost-1.80.0.tar.gz --create-dirs --output /home/david/C/vcpkg/downloads/boostorg-build-boost-1.80.0.tar.gz.6547.part 2>&1)
[DEBUG] 6547: cmd_execute_and_stream_data() returned 0 after   673828 us
Error: Failed to download from mirror set:
File does not have the expected hash:
             url : [ https://github.com/boostorg/build/archive/boost-1.80.0.tar.gz ]
       File path : [ /home/david/C/vcpkg/downloads/boostorg-build-boost-1.80.0.tar.gz.6547.part ]
   Expected hash : [ 9076732697f9d8f682b5857f6552b537e7745fedfcee3b82083d497a1f58a795ae73c652ab2a04340b9264155738f4eccfe33095bc996169a4e5117e641644fb ]
     Actual hash : [ 11ac21b27c5c656951784734c6642a2d4efa185e074ec48561f2800203b639d4a628fec6d356bb733494889141327a7ac730ce127449bfc7d509d5d213216995 ]


[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(766): 
[DEBUG] Time in subprocesses: 674590 us
[DEBUG] Time in parsing JSON: 0 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 56 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 693.6 ms (692723 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/boost-build/portfile.cmake:9 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by FrankXie05** [comment] 2022-08-26 05:50
Duplicate of #26525

**Closed by FrankXie05** 2022-08-26 05:50 UTC
