### ISSUE TITLE
[gmp] Build error on x64-windows

### ISSUE THREAD

**Issue by pushkaraj-gode** [microsoft/vcpkg#42526] opened 2024-12-04 19:13 UTC
Installing 1/18 gmp:x64-windows@6.3.0...
Building gmp:x64-windows@6.3.0...
E:\trial\server\vcpkg\buildtrees\versioning_\versions\gmp\c28d96e8dd3ed941ba550f1e9d9f7bf1f2a83ac8: info: installing overlay port from here
-- Using cached gmp-6.3.0.tar.xz.
-- Cleaning sources at E:/trial/server/vcpkg/buildtrees/gmp/src/v6.3.0-036e54f1a3.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/trial/server/vcpkg/downloads/gmp-6.3.0.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Using source at E:/trial/server/vcpkg/buildtrees/gmp/src/v6.3.0-036e54f1a3.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Using cached msys2-autoconf-wrapper-20240607-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20240607-1-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.43.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-4-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.037-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.72-2.72-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.17-1.17-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.35-2-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.10.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.6.3-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.013-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.38.2-2-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.5.20240831-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libxcrypt-4.4.36-1-x86_64.pkg.tar.zst.
-- Using msys root at E:/trial/server/vcpkg/downloads/tools/msys2/2db36fb050d01f45
-- Generating configure for x64-windows
-- Finished generating configure for x64-windows
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst.
-- Using msys root at E:/trial/server/vcpkg/downloads/tools/msys2/21caed2f81ec917b
-- Configuring x64-windows-dbg
-- Finished generating configure for x64-windows
-- Using cached msys2-mingw-w64-x86_64-pkgconf-1~2.3.0-1-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst.
-- Using msys root at E:/trial/server/vcpkg/downloads/tools/msys2/21caed2f81ec917b
-- Configuring x64-windows-dbg

After this this stucks **in my case does not even go ahead** and other windows machines it fails with below errors

**1st machine output is as below**

Make Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/Log/TEMP/vcpkg/downloads/tools/msys2/2db36fb050d01f45/usr/bin/make.exe -j 9 --trace -f Makefile all
    Working Directory: D:/Log/TEMP/vcpkg/buildtrees/gmp/x64-windows-dbg/
    See logs for more information:
      D:\Log\TEMP\vcpkg\buildtrees\gmp\build-x64-windows-dbg-out.log
      D:\Log\TEMP\vcpkg\buildtrees\gmp\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:136 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  buildtrees/versioning_/versions/gmp/c28d96e8dd3ed941ba550f1e9d9f7bf1f2a83ac8/portfile.cmake:92 (vcpkg_install_make)
  scripts/ports.cmake:196 (include)

error: building gmp:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle gmp:x64-windows: 25 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[gmp]+Build+error+on+x64-

2nd machine 

CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/workspace/trial/server/vcpkg/downloads/tools/msys2/2db36fb050d01f45/usr/bin/make.exe -j 13 --trace -f Makefile all
    Working Directory: C:/workspace/trial/server/vcpkg/buildtrees/gmp/x64-windows-dbg/
    See logs for more information:
      C:\workspace\trial\server\vcpkg\buildtrees\gmp\build-x64-windows-dbg-out.log
      C:\workspace\trial\server\vcpkg\buildtrees\gmp\build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_make.cmake:136 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_make.cmake:2 (vcpkg_build_make)
  buildtrees/versioning_/versions/gmp/c28d96e8dd3ed941ba550f1e9d9f7bf1f2a83ac8/portfile.cmake:92 (vcpkg_install_make)
  scripts/ports.cmake:192 (include)

**Comment by LilyWangLL** [comment] 2024-12-05 06:10
Please provide the error log:
```
D:\Log\TEMP\vcpkg\buildtrees\gmp\build-x64-windows-dbg-out.log
D:\Log\TEMP\vcpkg\buildtrees\gmp\build-x64-windows-dbg-err.log
```

**Comment by pushkaraj-gode** [comment] 2024-12-05 06:54
[build-x64-windows-dbg-out.log](https://github.com/user-attachments/files/18018608/build-x64-windows-dbg-out.log)
[build-x64-windows-dbg-err.log](https://github.com/user-attachments/files/18018609/build-x64-windows-dbg-err.log)
[issue_body.md](https://github.com/user-attachments/files/18018610/issue_body.md)

**Comment by LilyWangLL** [comment] 2024-12-06 07:45
Duplicate of https://github.com/microsoft/vcpkg/issues/41804, this issue has been fixed by https://github.com/microsoft/vcpkg/pull/41814, please install the latest version of `gmp`.

**Closed by LilyWangLL** 2024-12-06 07:45 UTC
Labels: category:question

**Comment by pushkaraj-gode** [comment] 2024-12-08 16:12
I already tried with latest version of gmp 6.3.0#1 as well still the response is same it gets stuck just like i mentioned in the issue
