### ISSUE TITLE
[colmap] Build error

### ISSUE THREAD

**Issue by weihohoho** [microsoft/vcpkg#27723] opened 2022-11-09 03:24 UTC
Package: colmap[core,cuda,tests]:x64-windows -> 2022-03-14#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31933.0
-    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: e79c0d2b5 2022-11-08 (15 hours ago)

**To Reproduce**

`vcpkg install colmap[cuda,tests]:x64-windows`

**Failure logs**

```
-- Using cached colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz.
-- Cleaning sources at E:/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkg/downloads/colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at E:/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: E:/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j17
    Working Directory: E:/vcpkg/buildtrees/colmap/x64-windows-rel
    See logs for more information:
      E:\vcpkg\buildtrees\colmap\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:59 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building colmap:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[colmap]+Build+error
Include '[colmap] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-10-17-3247920fbdd47d08f36cbd480addd9890d3c2435
    vcpkg-scripts version: e79c0d2b5 2022-11-08 (15 hours ago)


```
<details><summary>E:\vcpkg\buildtrees\colmap\install-x64-windows-rel-out.log</summary>

```
[1/342] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DCUDA_ENABLED -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DVL_DISABLE_AVX -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -IE:\vcpkg\installed\x64-windows\include -IE:\vcpkg\installed\x64-windows\include\eigen3 -IE:\vcpkg\installed\x64-windows\include\qt5 -IE:\vcpkg\installed\x64-windows\include\qt5\QtCore -IE:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IE:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IE:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IE:\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /Folib\VLFeat\CMakeFiles\vlfeat.dir\array.c.obj /Fdlib\VLFeat\CMakeFiles\vlfeat.dir\vlfeat.pdb /FS -c E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\VLFeat\array.c
[2/342] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DCGAL_ENABLED -DCUDA_ENABLED -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DRELEASE -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -IE:\vcpkg\installed\x64-windows\include -IE:\vcpkg\installed\x64-windows\include\eigen3 -IE:\vcpkg\installed\x64-windows\include\qt5 -IE:\vcpkg\installed\x64-windows\include\qt5\QtCore -IE:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IE:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IE:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IE:\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W0 /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /Folib\PoissonRecon\CMakeFiles\poisson_recon.dir\CmdLineParser.cpp.obj /Fdlib\PoissonRecon\CMakeFiles\poisson_recon.dir\poisson_recon.pdb /FS -c E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\PoissonRecon\CmdLineParser.cpp
[3/342] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DCGAL_ENABLED -DCUDA_ENABLED -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DRELEASE -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -IE:\vcpkg\installed\x64-windows\include -IE:\vcpkg\installed\x64-windows\include\eigen3 -IE:\vcpkg\installed\x64-windows\include\qt5 -IE:\vcpkg\installed\x64-windows\include\qt5\QtCore -IE:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IE:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IE:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IE:\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W0 /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /Folib\PoissonRecon\CMakeFiles\poisson_recon.dir\Factor.cpp.obj /Fdlib\PoissonRecon\CMakeFiles\poisson_recon.dir\poisson_recon.pdb /FS -c E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\PoissonRecon\Factor.cpp
...
Skipped 7263 lines
...

[137/342] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DBOOST_ALL_DYN_LINK=1 -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DCUDA_ENABLED -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DIMATH_DLL -DOPENEXR_DLL -DOPENGL_ENABLED -DOPENMP_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DWIN32_LEAN_AND_MEAN -D_MWAITXINTRIN_H_INCLUDED -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -external:IE:\vcpkg\installed\x64-windows\include -external:IE:\vcpkg\installed\x64-windows\include\eigen3 -external:IE:\vcpkg\installed\x64-windows\include\qt5 -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtCore -external:IE:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtGui -external:IE:\vcpkg\installed\x64-windows\include\OpenEXR -external:IE:\vcpkg\installed\x64-windows\include\Imath -external:IE:\vcpkg\installed\x64-windows\include\GKlib -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W3 /MD /O2 /Oi /Gy /DNDEBUG /Z7  /EHsc /Zc:__cplusplus -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /bigobj /showIncludes /Fosrc\CMakeFiles\colmap.dir\mvs\meshing.cc.obj /Fdsrc\CMakeFiles\colmap.dir\colmap.pdb /FS -c E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(166): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(195): warning C4267: 'argument': conversion from 'size_t' to 'int', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(205): warning C4244: 'argument': conversion from 'const double' to 'const float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(205): warning C4244: 'argument': conversion from 'const double' to 'const float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(205): warning C4244: 'argument': conversion from 'const double' to 'const float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(244): warning C4267: '=': conversion from 'size_t' to 'uint32_t', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(294): warning C4267: 'initializing': conversion from 'size_t' to 'int', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(294): warning C4267: 'initializing': conversion from 'size_t' to 'const int', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(329): warning C4267: 'argument': conversion from 'size_t' to '_Ty', possible loss of data
        with
        [
            _Ty=boost::random::seed_seq::result_type
        ]
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(335): warning C4267: 'argument': conversion from 'size_t' to 'const uint32_t', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(441): warning C4244: 'argument': conversion from 'double' to '_Ty', possible loss of data
        with
        [
            _Ty=float
        ]
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(625): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(625): warning C4244: 'initializing': conversion from 'double' to 'const float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(704): warning C4244: 'argument': conversion from 'const double' to 'const float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(704): warning C4244: 'argument': conversion from 'const double' to 'const float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(725): warning C4267: 'argument': conversion from 'size_t' to 'const int', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(771): warning C4244: '+=': conversion from 'const double' to 'float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(778): warning C4244: '+=': conversion from 'double' to '_Ty', possible loss of data
        with
        [
            _Ty=float
        ]
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(814): warning C4244: '+=': conversion from 'double' to '_Ty', possible loss of data
        with
        [
            _Ty=float
        ]
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(819): warning C4244: '+=': conversion from 'const double' to 'float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(906): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(905): warning C4244: 'initializing': conversion from 'double' to 'const float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(908): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(907): warning C4244: 'initializing': conversion from 'double' to 'const float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(954): warning C4244: 'initializing': conversion from '_Ty' to 'float', possible loss of data
        with
        [
            _Ty=double
        ]
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(953): warning C4244: 'initializing': conversion from '_Ty' to 'const float', possible loss of data
        with
        [
            _Ty=double
        ]
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(982): warning C4244: 'initializing': conversion from 'double' to 'float', possible loss of data
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(981): warning C4244: 'initializing': conversion from 'double' to 'const float', possible loss of data
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\xmemory(680): warning C4244: 'argument': conversion from 'const double' to 'const float', possible loss of data
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(863): note: see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,const double&,const double&,const double&>(_Alloc &,_Objty *const ,const double &,const double &,const double &)' being compiled
        with
        [
            _Alloc=std::allocator<colmap::PlyMeshVertex>,
            _Ty=colmap::PlyMeshVertex,
            _Objty=colmap::PlyMeshVertex
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(863): note: see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,const double&,const double&,const double&>(_Alloc &,_Objty *const ,const double &,const double &,const double &)' being compiled
        with
        [
            _Alloc=std::allocator<colmap::PlyMeshVertex>,
            _Ty=colmap::PlyMeshVertex,
            _Objty=colmap::PlyMeshVertex
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(845): note: see reference to function template instantiation '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_back_with_unused_capacity<const double&,const double&,const double&>(const double &,const double &,const double &)' being compiled
        with
        [
            _Ty=colmap::PlyMeshVertex
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(845): note: see reference to function template instantiation '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_back_with_unused_capacity<const double&,const double&,const double&>(const double &,const double &,const double &)' being compiled
        with
        [
            _Ty=colmap::PlyMeshVertex
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(927): note: see reference to function template instantiation '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_one_at_back<const double&,const double&,const double&>(const double &,const double &,const double &)' being compiled
        with
        [
            _Ty=colmap::PlyMeshVertex
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(927): note: see reference to function template instantiation '_Ty &std::vector<_Ty,std::allocator<_Ty>>::_Emplace_one_at_back<const double&,const double&,const double&>(const double &,const double &,const double &)' being compiled
        with
        [
            _Ty=colmap::PlyMeshVertex
        ]
E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\mvs\meshing.cc(977): note: see reference to function template instantiation 'void std::vector<colmap::PlyMeshVertex,std::allocator<colmap::PlyMeshVertex>>::emplace_back<const double&,const double&,const double&>(const double &,const double &,const double &)' being compiled
[138/342] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DBOOST_ALL_DYN_LINK=1 -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DCUDA_ENABLED -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DIMATH_DLL -DOPENEXR_DLL -DOPENGL_ENABLED -DOPENMP_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DWIN32_LEAN_AND_MEAN -D_MWAITXINTRIN_H_INCLUDED -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -external:IE:\vcpkg\installed\x64-windows\include -external:IE:\vcpkg\installed\x64-windows\include\eigen3 -external:IE:\vcpkg\installed\x64-windows\include\qt5 -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtCore -external:IE:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtGui -external:IE:\vcpkg\installed\x64-windows\include\OpenEXR -external:IE:\vcpkg\installed\x64-windows\include\Imath -external:IE:\vcpkg\installed\x64-windows\include\GKlib -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W3 /MD /O2 /Oi /Gy /DNDEBUG /Z7  /EHsc /Zc:__cplusplus -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /bigobj /showIncludes /Fosrc\CMakeFiles\colmap.dir\estimators\generalized_relative_pose.cc.obj /Fdsrc\CMakeFiles\colmap.dir\colmap.pdb /FS -c E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\generalized_relative_pose.cc
[139/342] C:\PROGRA~1\MICROS~4\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DBOOST_ALL_DYN_LINK=1 -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DCUDA_ENABLED -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DIMATH_DLL -DOPENEXR_DLL -DOPENGL_ENABLED -DOPENMP_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DWIN32_LEAN_AND_MEAN -D_MWAITXINTRIN_H_INCLUDED -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -IE:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -external:IE:\vcpkg\installed\x64-windows\include -external:IE:\vcpkg\installed\x64-windows\include\eigen3 -external:IE:\vcpkg\installed\x64-windows\include\qt5 -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtCore -external:IE:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -external:IE:\vcpkg\installed\x64-windows\include\qt5\QtGui -external:IE:\vcpkg\installed\x64-windows\include\OpenEXR -external:IE:\vcpkg\installed\x64-windows\include\Imath -external:IE:\vcpkg\installed\x64-windows\include\GKlib -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W3 /MD /O2 /Oi /Gy /DNDEBUG /Z7  /EHsc /Zc:__cplusplus -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /bigobj /showIncludes /Fosrc\CMakeFiles\colmap.dir\estimators\generalized_absolute_pose_coeffs.cc.obj /Fdsrc\CMakeFiles\colmap.dir\colmap.pdb /FS -c E:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\generalized_absolute_pose_coeffs.cc
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

**Comment by JackBoosY** [comment] 2022-11-09 06:30
please upload the full log instead.
there doesn't contain any error message in your provided log info.

**Comment by weihohoho** [comment] 2022-11-09 14:30
> please upload the full log instead. there doesn't contain any error message in your provided log info.

Thanks for the reminder. I've compile colmap again and the same problem persists. The lastest log updated above. Thanks!

**Comment by LilyWangLL** [comment] 2022-11-10 02:15
I can't get error message from your log, but `colmap` has a [Visual Studio bug](https://developercommunity.visualstudio.com/t/fatal-error-C1001:-Internal-compiler-err/10076899) now. Could you check your local log is same with issue https://github.com/microsoft/vcpkg/issues/25303?

**Comment by LilyWangLL** [comment] 2022-11-10 06:28
Thanks for your reply, I am closing this issue as duplicate of #25303.

**Closed by LilyWangLL** 2022-11-10 06:28 UTC
Labels: depends:upstream-changes
