### ISSUE TITLE
[wxwidgets] cmake integration failure

### ISSUE THREAD

**Issue by justinboneh** [microsoft/vcpkg#27316] opened 2022-10-19 06:43 UTC
**Host Environment**

- OS: Windows
- Compiler: 
  - Visual Studio 16 2019
  - CMake 3.24.2

**To Reproduce**

1. `.\vcpkg.exe install wxwidgets:x64-windows` - **finishes successfully**
2. On CMake, `find_package(wxWidgets COMPONENTS base core gl adv aui html)` - **fails**

**Failure logs**

> CMake Error at E:/workspace/vcpkg/installed/x64-windows/share/wxwidgets/vcpkg-cmake-wrapper.cmake:62 (if):
>   if given arguments:
> 
>     "WIN32" "AND" "CMAKE_HOST_WIN32" "AND" "dynamic" "STREQUAL" "static" "AND" "NOT" "wx::core" "IN_LIST" "wxWidgets_LIBRARIES"
> 
>   Unknown arguments specified

[CMakeError.log](https://github.com/microsoft/vcpkg/files/9817500/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/9817501/CMakeOutput.log)

**Additional context**

Commenting out the lines below solves the issue, as it's supposed to evaluate to `false` anyway (`"dynamic" STREQUAL "static"`):
https://github.com/microsoft/vcpkg/blob/414cc952861980514795153d4304810f40369773/ports/wxwidgets/vcpkg-cmake-wrapper.cmake#L57-L70

**Comment by dg0yt** [comment] 2022-10-19 06:54
Well, usage of this port is CI tested, although not with all components. 
What is your project's `cmake_minimum_required`?
What is stdout/stderr of your CMake run? The attached log files are pointless for this issue.

**Comment by justinboneh** [comment] 2022-10-22 09:25
I'm actually using a third-party repository, [mrpt](https://github.com/MRPT/mrpt).
They set `cmake_minimum_required(VERSION 3.8)`.

The stdout/stderr log is 
[CMakeStdOutStdErr.log](https://github.com/microsoft/vcpkg/files/9843977/CMakeStdOutStdErr.log)
attached.

**Comment by dg0yt** [comment] 2022-10-22 10:26
~~~
  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  IN_LIST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  E:/workspace/vcpkg/scripts/buildsystems/vcpkg.cmake:788 (include)
  cmakemodules/script_wxwidgets.cmake:44 (find_package)
  CMakeLists.txt:300 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at E:/workspace/vcpkg/installed/x64-windows/share/wxwidgets/vcpkg-cmake-wrapper.cmake:62 (if):
  if given arguments:

    "WIN32" "AND" "CMAKE_HOST_WIN32" "AND" "dynamic" "STREQUAL" "static" "AND" "NOT" "wx::core" "IN_LIST" "wxWidgets_LIBRARIES"

  Unknown arguments specified
~~~
So this stumbles over `IN_LIST`. That's what I expected. We can set the given policy in the wrapper.

However, mrpt has a problem, too: It calls `cmake_minimum_required` after `project`. That is the reason why CMP0057 is not already set: The order of the command must be switched for the policies to take effect. So there can be more unexpected behaviour in that project.

**Comment by justinboneh** [comment] 2022-10-22 10:28
Thanks. I'll open an issue there as well.

**Closed** 2022-10-24 23:54 UTC
Labels: category:port-bug
