### ISSUE TITLE
scope_exit compilation error

### ISSUE THREAD

**Issue by sn2234** [Microsoft/vcpkg#2475] opened 2017-12-30 13:27 UTC
Steps to reproduce:
Create console app
Add #include <boost/scope_exit.hpp>
Try to compile
The following errors appear:
vcpkg\installed\x64-windows\include\boost\scope_exit.hpp(419): error C2988: unrecognizable template declaration/definition
vcpkg\installed\x64-windows\include\boost\scope_exit.hpp(427): note: see reference to class template instantiation 'boost::scope_exit::aux::msvc_typeof_this::msvc_extract_type<ID,T>' being compiled
vcpkg\installed\x64-windows\include\boost\scope_exit.hpp(419): error C2143: syntax error: missing ';' before '<'
vcpkg\installed\x64-windows\include\boost\scope_exit.hpp(419): error C2913: explicit specialization; 'boost::scope_exit::aux::msvc_typeof_this::id2type_impl' is not a specialization of a class template
vcpkg\installed\x64-windows\include\boost\scope_exit.hpp(419): error C2059: syntax error: '<'
vcpkg\installed\x64-windows\include\boost\scope_exit.hpp(419): error C2334: unexpected token(s) preceding '{'; skipping apparent function body

**Comment by sn2234** [comment] 2017-12-30 13:28
The corresponding template specification is marked with comment:
// VC8.0 specific bug-feature.
Probably it's a hack for an outdated compiler version
Removing the faulting specification resolves compilation error, although I've not tested the functionality yet

**Comment by NancyLi1013** [comment] 2019-02-15 05:56
@sn2234 ，could you please try it again? And I cannot reproduce it now. 
If there is no problem on your machine, please help close it.
Thanks.
Note: I test this issue on windows 10  64-bit with VS 2017.

**Closed** 2019-02-16 01:27 UTC
