### ISSUE TITLE
Vcpkg pops up annoying console that quickly disappears

### ISSUE THREAD

**Issue by aslze** [microsoft/vcpkg#11491] opened 2020-05-21 08:47 UTC
**Describe the bug**
Every time vcpkg is run on the console, another console pops-up and immediately disappears. Just a bit annoying. I guess vcpkg is running another program as a subprocess: if using `std::system()` that is normal, and annoying. IMO it should use another method like `CreateProcess` with *show window* flag as `WM_HIDE`.

**Environment**
Windows 10 Version 10.0.18363 Build 18363

**To Reproduce**
1. ./vcpkg [[with or without more arguments]]

**Expected behavior**
Running silently in the existing console.

**Comment by aslze** [comment] 2020-05-21 13:58
BTW, this is Vcpkg 2020.02.04-nohash

**Comment by LilyWangLL** [comment] 2022-06-10 09:22
Thanks for posting this issue. I can't reproduce this issue locally on the latest vcpkg, so I am closing this issue for now. If there are new information about this issue, please reopen this issue.

**Closed by LilyWangLL** 2022-06-10 09:22 UTC
Labels: category:vcpkg-bug
