### ISSUE TITLE
[gtkmm] build failure

### ISSUE THREAD

**Issue by yingshaoxo** [microsoft/vcpkg#14704] opened 2020-11-22 12:23 UTC
**Host Environment**
- OS: Linux pop-os 5.4.0-7642-generic #46~1598628707~20.04~040157c-Ubuntu SMP Fri Aug 28 18:02:16 UTC  x86_64 x86_64 x86_64 GNU/Linux

**To Reproduce**
`./vcpkg install gtkmm`

**Failure logs** 
```bash
yingshaoxo@pop-os:~/Documents/vcpkg$ vcpkg install gtkmm
Computing installation plan...
The following packages will be built and installed:
  * atkmm[core]:x64-linux
  * brotli[core]:x64-linux
  * bzip2[core]:x64-linux
  * cairo[core,gobject]:x64-linux
  * cairomm[core]:x64-linux
  * dirent[core]:x64-linux
  * expat[core]:x64-linux
  * fontconfig[core]:x64-linux
  * freetype[bzip2,core,png]:x64-linux
  * gdk-pixbuf[core]:x64-linux
  * gtk[core]:x64-linux
    gtkmm[core]:x64-linux
  * harfbuzz[core,glib]:x64-linux
  * json-c[core]:x64-linux
  * libepoxy[core]:x64-linux
  * libpng[core]:x64-linux
  * libuuid[core]:x64-linux
  * pango[core]:x64-linux
  * pangomm[core]:x64-linux
  * pixman[core]:x64-linux
  * pthread[core]:x64-linux
  * pthreads[core]:x64-linux
  * ragel[core]:x64-linux
  * tool-meson[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/b9/b93cf1b9eef6c38337e7ac08f943f3c9e688c83b.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/ec/ec291a5774f34f4fcd6c97c492b384bcaf4505e0.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/12/124a081fcd194e0b2e04e224ef975b76a5647f33.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/ae/ae056dd213066a0da38e9fc44bb4b1c6112221ee.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/26/268043aab2e0916b995f5fb5c7d0209eb94bdda8.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/90/903eec9ede3bf84f69f18442f366f1e39d313987.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/2d/2d3ce8ed483607948acc85ee4795703a2217ab7e.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/64/64eee7d9d40fca627982e9d254ad1a395a0f49cc.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/63/63228d24d7af07112dec768fb317b33b3110d725.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/5f/5f618ae41b358d285ab37292715e2bc0a04472aa.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/f2/f2fd68637d3fe90326b790a8685a7be7f7280e2e.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/19/19513a387baca88e8664e0df31ea05ad4256c880.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/ad/ad315b170fc07cb1b5d7c8086be7b7b7c009cd52.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/19/19e065b4e1b387adaafb48bf87641b7eb4e7ece0.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/03/03bbf8543c2d57d9b3765eeb1a687df5d927694b.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/ae/aefc756edf398a366d9329033446b678cd12e8ae.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/cc/cc4b28a81d1efd4be728a5e428b484ba45f74d5c.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/cc/cc894d55b2936b4447d469ed82d2d6de22b4abd6.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/e2/e2930d84ad94a1e5c486feb2c6bced23c429f79f.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/e0/e0aef45eff054a7c7df03d1ba3d19d093819b8f8.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/d5/d5510656bf15eef3449b2281b32b5ad0d29134a6.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/a4/a423879d9b5886c34a800add16383a53955120e7.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/20/20791f96a315793cff6d32ff738b38e0618d1def.zip
Could not locate cached archive: /home/yingshaoxo/.cache/vcpkg/archives/14/148b3050b81921814a032c79a5cf4257800e7795.zip
Starting package 1/24: atkmm:x64-linux
Building package atkmm[core]:x64-linux...
CMake Error at scripts/cmake/vcpkg_fail_port_install.cmake:94 (message):
  Target 'Linux' not supported by atkmm!

Call Stack (most recent call first):
  ports/atkmm/portfile.cmake:1 (vcpkg_fail_port_install)
  scripts/ports.cmake:136 (include)


Error: Building package atkmm:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: atkmm:x64-linux
  Vcpkg version: 2020.11.12-unknownhash

Additionally, attach any relevant sections from the log files above.
``

**Comment by NancyLi1013** [comment] 2020-11-23 08:25
Hi @yingshaoxo 

Thanks for posting this issue.

`atkmm `only supports windows platform now.

**Comment by yingshaoxo** [comment] 2020-11-23 08:29
> Hi @yingshaoxo
> 
> Thanks for posting this issue.
> 
> `atkmm `only supports windows platform now.

But how can i use gtkmm under Linux if I can't build atkmm?

I just want to install gtkmm, then do some development with it under Linux.

Of course I love vcpkg, but how can I make it to work with this purpose?

**Comment by NancyLi1013** [comment] 2020-11-23 09:27
@yingshaoxo 

Since `atkmm `is one of required dependencies for `gtkmm`.  Without `atkmm `, `gtkmm` cannot be built on Linux in vcpkg.

I'm sorry, there are no ways to make it work on non Windows now.

**Comment by yingshaoxo** [comment] 2020-11-23 18:40
@NancyLi1013 

Thanks, I have figured it out.

This is a bug that just happened with vcpkg: https://github.com/microsoft/vcpkg/issues/9564

atkmm can be compiled independently.

**Comment by NancyLi1013** [comment] 2020-11-24 02:05
Thanks for your update. It's so great that you have found another way to use `gtkmm `on Linux. Also thanks for your help to pointing this out. It seems that you use `gtkmm `that is not provided by vcpkg.  

The root cause of this issue is the same as that in #9564. So let's track this issue there and I'm closing this for now.

**Closed by NancyLi1013** 2020-11-24 02:05 UTC
Labels: category:port-feature
