### ISSUE TITLE
A bug about URL resource cannot access.

### ISSUE THREAD

**Issue by fingerecho** [microsoft/vcpkg#13146] opened 2020-08-26 00:53 UTC
****

**Is your feature request related to a problem? Please describe.**
./vcpkg.exe install boost
output as follows:
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.73.0.tar.gz...
-- Extracting source C:/ProgramData/vcpkg/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at C:/ProgramData/vcpkg/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c.clean
-- Packaging headers
-- Packaging headers done
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt...
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt... Failed. Status: 6;"Couldn't resolve host name"

**Proposed solution**
Swap the `https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt` url, this url cannot archive.

**Describe alternatives you've considered**
Update the url resource.

**Additional context**
fingerecho@DESKTOP-FIBJKKG:/mnt/c/Users/86185/.temp$ wget -c  https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt
Will not apply HSTS. The HSTS database must be a regular and non-world-writable file.
ERROR: could not open HSTS store at '/home/fingerecho/.wget-hsts'. HSTS will be disabled.
--2020-08-26 08:44:40--  https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... failed: Connection refused.
fingerecho@DESKTOP-FIBJKKG:/mnt/c/Users/86185/.temp$ w3m  https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt
w3m: Can't load https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt.

**Comment by Voskrese** [comment] 2020-08-26 00:59
`wget -c https://raw.githubusercontent.com/boostorg/boost/boost-1.73.0/LICENSE_1_0.txt`

![2020-08-26_085905](https://user-images.githubusercontent.com/10104740/91242595-739e4500-e77a-11ea-8a92-ab0c4032545d.png)

**Comment by LilyWangL** [comment] 2020-08-26 03:31
Thanks for posting this issue. Closed as duplicate of #13001 #12383.

**Closed by LilyWangL** 2020-08-26 03:31 UTC
Labels: requires:repro
