### ISSUE TITLE
Mac 12.4 no python command error

### ISSUE THREAD

**Issue by Dariusz1989** [microsoft/vcpkg#24828] opened 2022-05-20 13:54 UTC
**Describe the bug**
Hey
Latest macos does not have build in python, that cause some havoc with vcpkg as python then is not found on path. Even after adding python to path/alliasing/etc it does not work.

**Environment**
MacOs 12.3/12.4

**To Reproduce**
Just compile any app, during linking vcpkg calls python /xxx the python command is not found.

**Expected behavior**
Link exe. I can copy paste command in to terminal & give it valid python then it works. But this is not suitable fort large projects...

Is there any fix for this, or how can I tell vcpkg which python exe to use& where its located?

**Comment by autoantwort** [comment] 2022-05-20 17:13
Duplicate of #24696 :)

**Comment by JonLiu1993** [comment] 2022-05-23 02:26
@Dariusz1989 ,Thanks for posting this issue, this issue Duplicate of https://github.com/microsoft/vcpkg/issues/24696 let,s track in it

**Closed** 2022-05-23 09:19 UTC
Labels: category:vcpkg-bug
