### ISSUE TITLE
Surprising behavior when upgrading with an outdated executable

### ISSUE THREAD

**Issue by olafurw** [microsoft/vcpkg#11805] opened 2020-06-05 20:59 UTC
**Describe the bug**
I was calling `vcpkg.exe upgrade --no-dry-run` because fmt needed updating.

![image](https://user-images.githubusercontent.com/103783/83921696-35971380-a77f-11ea-9ed4-a69c8d16f70d.png)

It tells me to re-build using bootstrap. Which I do.

![image](https://user-images.githubusercontent.com/103783/83921815-7db63600-a77f-11ea-8b17-da21b70368f1.png)

Then I run `vcpkg.exe upgrade --no-dry-run` again to fix the issue. And I get a message that doesn't make me trust that everything is built and up to date. Just a "everything is fine".

![image](https://user-images.githubusercontent.com/103783/83921915-afc79800-a77f-11ea-952c-0d41b91ea6bc.png)

What happened to the previously failed fmt build? 
- Is it ok? If it is, how about telling me that. 
- Is it not? How about building it again.

**Environment**
- OS: Windows
- Compiler: 
Vcpkg package management program version 2020.02.04-nohash
MSVC 2019 16.6.0

**Comment by olafurw** [comment] 2020-06-05 21:02
As I post this, I go to remove and re-install fmt. And I see this.

![image](https://user-images.githubusercontent.com/103783/83922266-4e53f900-a780-11ea-9008-eefb556c0c8f.png)

This is an even bigger surprise to me. So on a failure, the package is just considered not installed? Where was this stated. I see nothing about this in the logs.

Also, regarding running `--dry-run` above, I did run it without dry run at the start, and nothing about not being compatible there. So much for a dry run :)

![image](https://user-images.githubusercontent.com/103783/83922452-9b37cf80-a780-11ea-9c02-b29f38257484.png)

**Comment by LilyWangL** [comment] 2020-06-09 09:03
Thanks for posting this issue. Closed as duplicate of #10654.

**Closed by LilyWangL** 2020-06-09 09:03 UTC
Labels: category:vcpkg-bug
