### ISSUE TITLE
[v8] Build error on x64-windows-static

### ISSUE THREAD

**Issue by FF69B3** [microsoft/vcpkg#42429] opened 2024-11-29 10:08 UTC
Package: v8:x64-windows-static@9.1.269.39#8

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30157.0
-    vcpkg-tool version: 2024-11-12-eb492805e92a2c14a230f5c3deb3e89f6771c321
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install v8:x64-windows-static`

**Failure logs**

```
-- Found external ninja('1.10.2').
-- Using cached msys2-pkgconf-2.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.037-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.5.4-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.6.3-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.013-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.5.20240831-2-x86_64.pkg.tar.zst.
-- Using msys root at H:/vcpkg/vcpkg/downloads/tools/msys2/ef3aca4e9386e8df
-- Using cached H:/vcpkg/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Cleaning sources at H:/vcpkg/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source H:/vcpkg/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Applying patch H:/vcpkg/vcpkg/ports/v8/v8.patch
-- Using source at H:/vcpkg/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean
-- Fetching submodules
-- Generating v8 build files. Please wait...
-- Generating build (x64-windows-static-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: H:/vcpkg/vcpkg/installed/x64-windows/tools/gn/gn.exe gen H:/vcpkg/vcpkg/buildtrees/v8/x64-windows-static-dbg "--args=is_component_build=false target_cpu=\"x64\" v8_monolithic=true v8_use_external_startup_data=false use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/h/vcpkg/vcpkg/installed/x64-windows-static/debug/lib/pkgconfig\""
    Working Directory: H:/vcpkg/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean
    Error code: 1
    See logs for more information:
      H:\vcpkg\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-out.log
      H:\vcpkg\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:10 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:34 (z_vcpkg_gn_configure_generate)
  ports/v8/portfile.cmake:161 (vcpkg_gn_configure)
  scripts/ports.cmake:196 (include)



```

<details><summary>H:\vcpkg\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-out.log</summary>

```
ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: H:/vcpkg/vcpkg/buildtrees/v8/x64-windows-static-dbg/
Command: H:/vcpkg/vcpkg/downloads/tools/python/python-3.12.7-x64/python.exe H:/vcpkg/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean/build/vs_toolchain.py get_toolchain_dir
Returned 1.
See //build/toolchain/win/BUILD.gn:8:1: whence it was imported.
import("//build/config/win/visual_studio_version.gni")
^----------------------------------------------------
See //BUILD.gn:1195:1: which caused the file to be included.
action("postmortem-metadata") {
^------------------------------
```
</details>

<details><summary>H:\vcpkg\vcpkg\buildtrees\v8\generate-x64-windows-static-dbg-err.log</summary>

```
H:\vcpkg\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Traceback (most recent call last):
  File "H:\vcpkg\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 573, in <module>
    sys.exit(main())
             ^^^^^^
  File "H:\vcpkg\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\vcpkg\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 546, in GetToolchainDir
    runtime_dll_dirs = SetEnvironmentAndGetRuntimeDllDirs()
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\vcpkg\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 106, in SetEnvironmentAndGetRuntimeDllDirs
    os.environ['GYP_MSVS_OVERRIDE_PATH'] = DetectVisualStudioPath()
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\vcpkg\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 197, in DetectVisualStudioPath
    version_as_year = GetVisualStudioVersion()
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\vcpkg\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 186, in GetVisualStudioVersion
    raise Exception('No supported Visual Studio can be found.'
Exception: No supported Visual Studio can be found. Supported versions are: 16.0 (2019), 15.0 (2017).
```
</details>

**Comment by MonicaLiu0311** [comment] 2024-12-02 06:11
Duplicate of #33447.

**Closed by MonicaLiu0311** 2024-12-02 06:11 UTC
Labels: category:port-bug
