### ISSUE TITLE
[tensorflow] Remove tensorflow packet on Windows

### ISSUE THREAD

**Issue by libbooze** [microsoft/vcpkg#18887] opened 2021-07-09 19:10 UTC
Tensorflow on Windows is unusable, without users manually hacking the produced libraries.

https://github.com/tensorflow/tensorflow/issues/23542
https://stackoverflow.com/questions/62954634/tensorflow-2-3-unresolved-external-symbols-in-machine-generated-files-when-build

This is confusing since "ok" installed packets fail during link phase because missing exported symbols.

Regardless of "who should fix it/whose fault it is" fact is that having a broken package in vcpkg is bad for user perspective of vcpkg quality. 

As I presume that it is unlikely somebody will write a magic fix for this since it does not seem trivial so I think proper thing is to remove the tensorflow packet for Windows. 

If it matters broken version I tried is 2.4#2, but I presume all of them are broken.

note: build(installing tensorflow_cc with vcpkg) works fine, I get .lib and .dll (in both Release and Debug variants), but if you actually try to actually write some TF code that uses those libs then you get LNK2019.

as for repro:
install tensorflow_cc and try to actually use to build some toy TF project. Some of missing symbols are:

LNK2019: unresolved external symbol "public: __cdecl tensorflow::SessionOptions::SessionOptions(void)”

LNK2019: unresolved external symbol "class tensorflow::Status __cdecl tensorflow::NewSession(struct tensorflow::SessionOptions const &,class tensorflow::Session * *)"

**Comment by JackBoosY** [comment] 2021-07-14 06:06
Sorry for late, can you please provide a sample project to reproduce this bug?

**Comment by libboze** [comment] 2021-07-14 11:51
@JackBoosY 
5 days including weekend is what I consider fast.

So now back to how to reproduce:
As I wrote: install the TF packet, integrate with VS(to make it easy to use it), write some toy program that uses TF and it will fail with linker errors.
In particular try to use
SessionOptions::SessionOptions or any other items patched in medium link bellow.
You will get linker errors.

This is expected and it matches this blog post:
https://medium.com/vitrox-publication/deep-learning-frameworks-tensorflow-build-from-source-on-windows-python-c-cpu-gpu-d3aa4d0772d8

(TF does NOT export symbols so that medium posts suggest manually editing TF source to add TF_EXPORT in front of important stuff).

note: I am 99+% certain in what I am saying because I have TF working (built from source using above method), but I wanted to switch to using package manager since I do not like to maintain such a huge dependency.

Additionally I have done DUMPBIN / EXPORTS on "my" dll(it contains the symbols missing), also it works fine when i use it in my program. DUMPBIN /EXPORTS on vcpkg dll does **not** contain necessary symbols.

here is the search results in Notepad++ for .dll built using above medium post:
![image](https://user-images.githubusercontent.com/47703951/125616734-de35c015-62fd-45fa-b9c9-61e79348f400.png)

here is the search results in Notepad++ for .dll installed using vcpkg
![image](https://user-images.githubusercontent.com/47703951/125616773-2167bac6-1a84-481a-a845-535d10f9612e.png)



Sorry for a long reply, so recap:

1. I have TF working(built manually using medium post that shows where to stick TF_EXPORT), my application that uses TF links fine.
2. I wanted to move to vcpkg package TF
3. That failed since TF in vcpkg does not export necessary symbols, so my application build fails at link stage.
4. This is hard to fix since you would need to modify TF source to get it to work, not sure if vcpkg team wants to commit to that kind of maintenance burden.
5. Since I think it is hard to fix this I suggest you remove the package from vcpkg, but if you are willing to make the patches to TF sources to get it working that would be great. 



P.S. If you wonder why TF does not export those symbols by default:  I have no idea... you can check the 3 y old issue I linked in my first comment.

**Comment by libboze** [comment] 2021-07-14 12:52
Just double checked, unfortunately I made a mistake, in my original post i said I am using 2.4 package, I was using 2.3 package.
2.3 package is indeed missing exported symbols, TF2.4 seems to be fine. 
Apologies for false alarm.

**Comment by libboze** [comment] 2021-07-14 14:21
Ah I was right originally, vcpkg tensorflow is still broken. 
So reopening.
For context(not that it matters I feel) I am using vcpkg without integration, just having this in my FindTensorflow file:
`include(D:/vcpkg/installed/x64-windows/share/tensorflow-cc/tensorflow-cc-config.cmake)`
As for version here it is:

./vcpkg.exe list

tensorflow-cc:x64-windows                          2.4.1            Library for computation using data flow graphs f...

tensorflow-common:x64-windows                      2.4.1#2          This meta package holds common files for the C [...
 
![image](https://user-images.githubusercontent.com/47703951/125638278-d7c1f52b-8896-403a-8a6e-6128327c552a.png)

**Comment by JackBoosY** [comment] 2021-08-02 07:43
@libboze  Can you please provide a sample project (contains some code) to reproduce this issue?

**Comment by JackBoosY** [comment] 2021-08-02 07:50
cc @jgehw do you know why?

**Comment by libbooze** [comment] 2021-08-02 20:10
> 
> @libboze Can you please provide a sample project (contains some code) to reproduce this issue?

My failures were in "large real" project so I can not just easily reduce it to the example project. I believe @jgehw will agree with me that problem is in missing exported symbols.
As mentioned before my problems exactly match the problems mentioned in medium [link](https://medium.com/vitrox-publication/deep-learning-frameworks-tensorflow-build-from-source-on-windows-python-c-cpu-gpu-d3aa4d0772d8) ( **Step 11: Build and Test Shared DLL Library for C++ API (CPU & GPU)** chapter) so I am 99+% certain that is the issue.

If @jgehw does not see this or he is too busy to reply I will try to find some time in 4-5 days(weekend) to make a simple C++ program that fails.

**Comment by JackBoosY** [comment] 2021-08-03 01:55
> problem is in missing exported symbols.

I checked the source code, the upstream doesn't export them either, so is it by design?

**Comment by libbooze** [comment] 2021-08-03 07:38
> 
> 
> > problem is in missing exported symbols.
> 
> I checked the source code, the upstream doesn't export them either, so is it by design?

It is probably by "bug", not by design, from what I saw TF does not have any CI for Debug Windows build. 
As mentioned in first comment I am not the first to notice this. https://github.com/tensorflow/tensorflow/issues/23542

**Comment by jgehw** [comment] 2021-08-03 19:34
I wasn't aware of these C++ linking issues because I'm only using the C API on Windows, which is working fine, and because another vcpkg user, I was in contact with, apparently used the C++ API via static linking.

According to the upstream thread @libbooze mentioned, there doesn't seem to be an easy fix.

I strongly disagree with removal of the vcpkg tensorflow Windows ports because the C version [tensorflow] is working fine both as DLL and with static linkage, and because the C++ version [tensorflow-cc] is reported to work with static linkage (x64-windows-static triplet).
@JackBoosY Maybe it makes sense to issue `message(FATAL_ERROR "TensorFlow doesn't support the C++ API via dynamic linkage on Windows. Please consider using static linkage (x64-windows-static triplet).")` for the [tensorflow-cc] port and dynamic linkage on Windows?

**Comment by libbooze** [comment] 2021-08-03 20:05
> I wasn't aware of these C++ linking issues because I'm only using the C API on Windows, which is working fine, and because another vcpkg user, I was in contact with, apparently used the C++ API via static linking.
> 
> According to the upstream thread @libbooze mentioned, there doesn't seem to be an easy fix.
> 
> I strongly disagree with removal of the vcpkg tensorflow Windows ports because the C version [tensorflow] is working fine both as DLL and with static linkage, and because the C++ version [tensorflow-cc] is reported to work with static linkage (x64-windows-static triplet).

My apologies, I had no idea that vcpkg supports static linking... or C libraries. 

As for static linking: don't you then again run into the problem for Debug builds since MSVC can not handle pdbs over around 6GB? Or the mentioned vcpkg user only uses TF in Release builds?

In any case I agree the issue exists for current dll ports and something needs to be done to make cause of this clear.

**Comment by jgehw** [comment] 2021-08-04 15:21
> As for static linking: don't you then again run into the problem for Debug builds since MSVC can not handle pdbs over around 6GB? Or the mentioned vcpkg user only uses TF in Release builds?

Microsoft sadly indeed didn't remove the 4GB limit on x64 Windows from the internals of .pdb files, and even more annoying, from .lib files. While there was an easy work-around for the .pdb files (I reduced the size of the .pdb file below 4GB by limiting some debug features using `/DEBUG:FASTLINK` instead of `/DEBUG:FULL`), it was more painful to work around the 4GB limit on .lib files: I needed to split TensorFlow into several .lib files (cf. `convert_lib_params_windows.py` and `generate_static_link_cmd_windows.py`).

**Comment by libbooze** [comment] 2021-08-07 01:59
@jgehw  thank you for making the pull request. 
I wish TF people fixed this, but will probably [not happen](https://github.com/tensorflow/tensorflow/issues/50744).
Also not sure if you are right person to report this to, but I think 2.**5** is incompatible with Eigen 3.3.9 (at least IIRC on my machine it was broken since both Eigen and TF specialized std::hash for same type), so if there are any plans to update TF version in vcpkg this could be another issue that could hit users. TF 2.5 works with custom git commit that they use internally, but it is not really fun experience for users since they just picked random commit from Eigen, not a tagged release.

Again this is for TF 2.5, current version in vcpkg is 2.4, so this only applies for future.

**Comment by jgehw** [comment] 2021-08-07 07:35
@libbooze thanks for reporting the TF 2.5 / Eigen 3.3.9 incompatibility. Do you know if this is fixed in TF 2.6(-rc*)? (My plan was to skip 2.5 and update to 2.6 soon.)

**Comment by libbooze** [comment] 2021-08-07 12:46
> 
> 
> @libbooze thanks for reporting the TF 2.5 / Eigen 3.3.9 incompatibility. Do you know if this is fixed in TF 2.6(-rc*)? (My plan was to skip 2.5 and update to 2.6 soon.)

Sorry, did not try. 
Here is where I think they specify eigen versions:
https://github.com/tensorflow/tensorflow/commits/master/third_party/eigen3/workspace.bzl

I am not an really following Eigen macros policy, but is seems TF went from unreleased 3.4 to unreleased 3.3 (https://github.com/tensorflow/tensorflow/commits/master/third_party/eigen3/workspace.bzl)

 this is what they used in March:

https://gitlab.com/libeigen/eigen/-/blob/f612df273689a19d25b45ca4f8269463207c4fee/Eigen/src/Core/util/Macros.h

this is what they use now:

https://gitlab.com/libeigen/eigen/-/blob/12e8d57108c50d8a63605c6eb0144c838c128337/Eigen/src/Core/util/Macros.h

If 2.6 works with Eigen version in vcpkg: I have no idea.... did not try it. 

Also it seems they used to patch Eigen, but thankfully I can not find the patch file in 2.6(I hope it was not just moved).

https://github.com/tensorflow/tensorflow/blob/r2.4/third_party/eigen3/gpu_packet_math.patch

**Closed** 2021-08-12 00:24 UTC
Labels: category:port-bug, depends:upstream-changes
