### ISSUE TITLE
[icu:x64-windows-static] build failure

### ISSUE THREAD

**Issue by Nightloewe** [microsoft/vcpkg#17518] opened 2021-04-26 14:12 UTC
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019?

**To Reproduce**
`./vcpkg install icu:x64-windows-static`

**Failure logs** 
```
-- Using msys root at D:/vcpkg/downloads/tools/msys2/20befe66cf35bf25
-- Configuring x64-windows-static-rel
-- Configuring x64-windows-static-rel done
-- Configuring x64-windows-static-dbg
-- Configuring x64-windows-static-dbg done
-- Package x64-windows-static-rel
-- Restarting Build without parallelism because memory exceeded
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: D:/vcpkg/downloads/tools/msys2/20befe66cf35bf25/usr/bin/bash.exe --noprofile --norc -c "make -j 5"
    Working Directory: D:/vcpkg/buildtrees/icu/x64-windows-static-rel
    See logs for more information:
      D:\vcpkg\buildtrees\icu\make-build-x64-windows-static-rel-out.log
      D:\vcpkg\buildtrees\icu\make-build-x64-windows-static-rel-err.log
      D:\vcpkg\buildtrees\icu\make-build-x64-windows-static-rel-out-1.log
      D:\vcpkg\buildtrees\icu\make-build-x64-windows-static-rel-err-1.log

Call Stack (most recent call first):
  ports/icu/portfile.cmake:164 (vcpkg_execute_build_process)
  scripts/ports.cmake:142 (include)


Error: Building package icu:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: icu:x64-windows-static
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e
```

**Additional context**
I already reinstalled vcpkg completely, but it still fails

**Comment by JackBoosY** [comment] 2021-04-26 16:31
Please provide the following logs:
 D:\vcpkg\buildtrees\icu\make-build-x64-windows-static-rel-out.log
 D:\vcpkg\buildtrees\icu\make-build-x64-windows-static-rel-err.log

**Comment by Nightloewe** [comment] 2021-04-26 20:10
[make-build-x64-windows-static-rel-err.log](https://github.com/microsoft/vcpkg/files/6379932/make-build-x64-windows-static-rel-err.log)
[make-build-x64-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/6379938/make-build-x64-windows-static-rel-out.log)

**Comment by NancyLi1013** [comment] 2021-04-29 06:34
Thanks for posting this issue @Nightloewe
I cannot reproduce this on my machine.

From make-build-x64-windows-static-rel-out.log, we get the error info:

```
LINK.EXE -subsystem:console -DEBUG -INCREMENTAL:NO -OPT:REF -OPT:ICF  -nologo -out:../../bin/gencfu.exe gencfu.o ../../lib/sicutu.lib ../../lib/sicuin.lib ../../lib/sicuuc.lib ../../stubdata/sicudt.lib advapi32.lib 
LINK : fatal error LNK1104: cannot open file '..\..\bin\gencfu.exe'
config.status: creating tools/gencfu/gencfu.1
```
Could you please check if `gencfu.exe` exists in _/cygdrive/d/vcpkg/buildtrees/icu/x64-windows-static-rel/bin/gencfu.exe_?

**Comment by Nightloewe** [comment] 2021-05-12 20:25
@NancyLi1013 I checken it and the file does not exist.

**Comment by NancyLi1013** [comment] 2021-05-13 10:13
@Nightloewe 
Could you please help confirm if you installed Virus software and also disabled it on your machine?

**Comment by Nightloewe** [comment] 2021-05-22 19:22
@NancyLi1013 You mean Antivirus software? Yes, I have installed Bitdefender Antivirus. I tried again and now the compilation works, I did not change anything on my system.

**Comment by NancyLi1013** [comment] 2021-05-24 08:30
> @NancyLi1013 You mean Antivirus software? Yes, I have installed Bitdefender Antivirus. I tried again and now the compilation works, I did not change anything on my system.

Yes, Antivirus software. So you can build it successfully now, right?

**Comment by Nightloewe** [comment] 2021-06-06 14:05
> > @NancyLi1013 You mean Antivirus software? Yes, I have installed Bitdefender Antivirus. I tried again and now the compilation works, I did not change anything on my system.
> 
> Yes, Antivirus software. So you can build it successfully now, right?

Yes, it worked without disabling antivirus software.

**Comment by NancyLi1013** [comment] 2021-06-07 02:21
Thanks for your feedback. I'm closing this issue since it cannot be reproduced now.

**Closed by NancyLi1013** 2021-06-07 02:21 UTC
Labels: requires:repro
