### ISSUE TITLE
libpq vs2022 vcpkg install err

### ISSUE THREAD

**Issue by DaXiaWei** [microsoft/vcpkg#30155] opened 2023-03-13 12:46 UTC
**Host Environment**

- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**

`./vcpkg install libpq`

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.
[issue_body.md](https://github.com/microsoft/vcpkg/files/10957411/issue_body.md)

**Comment by DaXiaWei** [comment] 2023-03-13 13:08
i install english pack but 。。。

**Comment by FrankXie05** [comment] 2023-03-14 02:40
@DaXiaWei  Duplicate of https://github.com/microsoft/vcpkg/issues/26416

**Closed by FrankXie05** 2023-03-14 02:40 UTC
Labels: category:question

**Comment by DaXiaWei** [comment] 2023-03-14 06:50
update VS problem solved think you @FrankXie05 and @JonLiu1993
