### ISSUE TITLE
[uvw] build failure

### ISSUE THREAD

**Issue by hihig2001** [microsoft/vcpkg#25682] opened 2022-07-11 06:48 UTC
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
'vcpkg.json' with uvw dependency.

**Failure logs**

> 
> 1> [CMake] CMake Error at C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package):
> 1> [CMake] Could not find a package configuration file provided by "unofficial-libuv"
> 1> [CMake] with any of the following names:
> 1> [CMake]
> 1> [CMake] unofficial-libuvConfig.cmake
> 1> [CMake] unofficial-libuv-config.cmake
> 1> [CMake]
> 1> [CMake] Add the installation prefix of "unofficial-libuv" to CMAKE_PREFIX_PATH or
> 1> [CMake] set "unofficial-libuv_DIR" to a directory containing one of the above
> 1> [CMake] files. If "unofficial-libuv" provides a separate development package or
> 1> [CMake] SDK, be sure it has been installed.
> 1> [CMake] Call Stack (most recent call first):
> 1> [CMake] out/build/windows-msvc-debug-hard-mode/vcpkg_installed/x64-windows/share/uvw/uvw-config.cmake:1 (find_package)
> 1> [CMake] C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:824 (_find_package)
> 1> [CMake] knuckles/CMakeLists.txt:13 (find_package)

**Additional context**

hi guys i got this error from 'uvw' in vcpkg.
i'm using 'vcpkg.json' and constrained version by specifying builtin-baseline

"builtin-baseline": "98f8d00e89fb6a8019c2045cfa1edbe9d92d3405"

if there are anything that i need to modify to make it work please let me know about it.

https://github.com/microsoft/vcpkg/issues/25563
https://github.com/microsoft/vcpkg/issues/24743
https://github.com/microsoft/vcpkg/pull/24745

**Comment by JackBoosY** [comment] 2022-07-11 06:51
Is this come from your custom project or other ports which in vcpkg?

Please use the official libuv targets in your custom project since they are provided by the upstream.

**Comment by hihig2001** [comment] 2022-07-11 06:51
vcpkg.json

```

{
  "name": "knuckles",
  "version-string": "0.0.1",
  "builtin-baseline": "0d7603c4efc351da97b43c1952ba943e76f9b35f",
  "dependencies": [
    {
      "name": "fmt",
      "version>=": "8.1.1"
    },
    {
      "name": "uvw"
    }
  ],
  "features": {
    "tests": {
      "description": "Build the tests of the package's tests",
      "dependencies": [
        {
          "name": "catch2",
          "version>=": "2.13.8"
        }
      ]
    }
  }
}
```

**Comment by hihig2001** [comment] 2022-07-11 06:52
cmake

`add_library(knuckles_lib "./src/lib.cpp" )
target_link_libraries(knuckles_lib PRIVATE project_options project_warnings) # link project_options/warnings

# Includes
set(knuckles_lib_INCLUDE_DIR "include") # must be relative paths
target_include_directories(knuckles_lib PUBLIC "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/${knuckles_lib_INCLUDE_DIR}>"
                                         "$<INSTALL_INTERFACE:./${CMAKE_INSTALL_INCLUDEDIR}>")

# Find dependencies:
set(knuckles_lib_DEPENDENCIES_CONFIGURED fmt uvw)

foreach(DEPENDENCY ${knuckles_lib_DEPENDENCIES_CONFIGURED})
  find_package(${DEPENDENCY} CONFIG REQUIRED)
endforeach()

# Link dependencies:
target_link_system_libraries(knuckles_lib PRIVATE fmt::fmt uvw::uvw)

if("${CMAKE_SYSTEM_NAME}" STREQUAL "Windows")
    target_link_system_libraries(knuckles_lib PRIVATE wsock32 ws2_32)
endif()

if(FEATURE_UNIT_TESTS)
  add_subdirectory("./test")
endif()
`

**Comment by hihig2001** [comment] 2022-07-11 06:55
I use 'project_option' for cmake extension besides that I don't know anything about 'unoficial-libuv' I tracked way that i was using uvw. Is there maybe some reason that name value has wrong?

**Comment by JackBoosY** [comment] 2022-07-11 06:55
Confirmed. No idea why we don't figure it out in our tests.

**Comment by JackBoosY** [comment] 2022-07-11 06:57
Wait. port `uvw` also be fixed in PR https://github.com/microsoft/vcpkg/tree/master/ports/uvw. Maybe you should update your builtin-baseline.

**Comment by hihig2001** [comment] 2022-07-11 07:00
but i pulled the git in recent version
"builtin-baseline": "98f8d00e89fb6a8019c2045cfa1edbe9d92d3405"
is the HEAD revision i think?

**Comment by hihig2001** [comment] 2022-07-11 07:05
oh wait i updated 'builtin-baseline'
previous commented one is that version that i reverted past builtin-baseline to make it my project work after i found the bug.

**Comment by hihig2001** [comment] 2022-07-11 07:27
it leads same error

**Comment by JackBoosY** [comment] 2022-07-11 07:50
Ah, I know why.
Wait a minute.

**Closed** 2022-07-11 23:20 UTC
Labels: category:port-bug
