### ISSUE TITLE
[protobuf] update to v3.20.1

### ISSUE THREAD

**Issue by SpenserCai** [microsoft/vcpkg#24603] opened 2022-05-07 16:56 UTC
Library name:
protobuf
New version number:
v3.20.1
Other information that may be useful (release notes, etc...)

**Comment by brendanburkhart** [comment] 2022-05-08 21:06
Duplicate of https://github.com/microsoft/vcpkg/issues/24305

**Comment by JonLiu1993** [comment] 2022-05-09 02:27
Duplicate of https://github.com/microsoft/vcpkg/issues/24305

**Closed by JonLiu1993** 2022-05-09 02:27 UTC
Labels: category:port-update
