### ISSUE TITLE
Warning: Could not find a matching pdb file for:

### ISSUE THREAD

**Issue by martin-s** [Microsoft/vcpkg#1766] opened 2017-09-03 15:42 UTC
See issue #587.
If dumpbin.exe prints localized message, script fails to find pdb files. If I print out environment variable "VSLANG", it is empty.

Tested on Windows 7/10, vcpkg head version, Microsoft (R) COFF/PE Dumper Version 14.00.24215.1, Language: non-english
Port: unrar

**Comment by Cheney-W** [comment] 2019-02-28 07:03
@martin-s , Thanks for reporting this issue.
I can't reproduce your issue with the latest vcpkg, so I close it first.
Please open a new issue if this is still a problem for you.

**Closed by Cheney-W** 2019-02-28 07:03 UTC
