### ISSUE TITLE
Error: Building package qt5-script:x86-windows

### ISSUE THREAD

**Issue by luzhskij** [Microsoft/vcpkg#4643] opened 2018-11-02 06:15 UTC
Package: qt5-script:x86-windows
Vcpkg version: 2018.10.20-nohash

Please update the version in vcpkg\ports\qt5-script\control and hash in portfile.cmake.

**Comment by Neumann-A** [comment] 2018-11-02 08:41
duplicate of #4571  
in progress see #4629

**Comment by ras0219-msft** [comment] 2018-11-07 22:50
Should be fixed by #4629, thanks for reporting!

**Closed by ras0219-msft** 2018-11-07 22:50 UTC
