### ISSUE TITLE
[ffmpeg] build failure on Debian Sid WSL

### ISSUE THREAD

**Issue by LeenHawk** [microsoft/vcpkg#32217] opened 2023-06-25 11:25 UTC
### Operating system

Linux (Debian Sid WSL)

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
`./vcpkg install ffmpeg --triplet=x64-linux`
```

### Failure logs

[build-x64-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/11859522/build-x64-linux-rel-out.log)
[build-x64-linux-rel-config.log](https://github.com/microsoft/vcpkg/files/11859523/build-x64-linux-rel-config.log)
[build-x64-linux-rel-err.log](https://github.com/microsoft/vcpkg/files/11859524/build-x64-linux-rel-err.log)

**Comment by LilyWangLL** [comment] 2023-06-26 07:10
This issue can't repro on Ubuntu 22.04.2 LTS, `ffmpeg` installed succeed on the latest vcpkg.
```
user@user002:~/lily/0626$ ./vcpkg install ffmpeg
Installing 1/1 ffmpeg:x64-linux...
Building ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-linux...
-- Using cached ffmpeg-ffmpeg-n5.1.2.tar.gz.
-- Cleaning sources at /home/user/lily/0626/buildtrees/ffmpeg/src/n5.1.2-f31542651f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /home/user/lily/0626/downloads/ffmpeg-ffmpeg-n5.1.2.tar.gz
......
-- Dependencies (release): -pthread;m;atomic
-- Dependencies (debug):   -pthread;m;atomic
-- Installing: /home/user/lily/0626/packages/ffmpeg_x64-linux/share/ffmpeg/usage
-- Installing: /home/user/lily/0626/packages/ffmpeg_x64-linux/share/ffmpeg/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 18 s.
Elapsed time to handle ffmpeg:x64-linux: 2.6 min
Total install time: 2.6 min
To use ffmpeg add the following to your CMake project:

    find_package(FFMPEG REQUIRED)
    target_include_directories(main PRIVATE ${FFMPEG_INCLUDE_DIRS})
    target_link_directories(main PRIVATE ${FFMPEG_LIBRARY_DIRS})
    target_link_libraries(main PRIVATE ${FFMPEG_LIBRARIES})

user@user002:~/lily/0626$ ./vcpkg --version
vcpkg package management program version 2023-06-15-8c254a5fb6c503615834fc66bd0717664a339a2e
```

**Comment by LilyWangLL** [comment] 2023-06-26 07:17
Your error message in build-x64-linux-rel-config.log are similar with https://stackoverflow.com/questions/55813663/ffmpeg-compilation-failed-with-cuda-libnpp-not-found, maybe you could refer to the solution from it.

**Comment by LeenHawk** [comment] 2023-06-26 10:45
> Your error message in build-x64-linux-rel-config.log are similar with https://stackoverflow.com/questions/55813663/ffmpeg-compilation-failed-with-cuda-libnpp-not-found, maybe you could refer to the solution from it.

I have tried to do it on Ubuntu2204 on WSL and it failed, too. It seems a problem in WSL? There is files on Ubuntu logs:
[build-x64-linux-rel-err.log](https://github.com/microsoft/vcpkg/files/11867583/build-x64-linux-rel-err.log)
[build-x64-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/11867584/build-x64-linux-rel-out.log)
[build-x64-linux-rel-config.log](https://github.com/microsoft/vcpkg/files/11867585/build-x64-linux-rel-config.log)

**Comment by LilyWangLL** [comment] 2023-06-27 02:13
> I have tried to do it on a fresh Ubuntu2204 on WSL and it failed, too. It seems a problem in WSL?

I think so.

**Comment by dg0yt** [comment] 2023-06-27 05:57
Given
~~~
WARNING: pkg-config not found, library detection may fail.
~~~
I would start with installing `pkg-config`.

**Comment by dg0yt** [comment] 2023-06-27 06:00
~~~
src/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
make: *** [/opt/vcpkg/buildtrees/ffmpeg/src/n5.1.2-f31542651f.clean/ffbuild/common.mak:81: libavformat/adtsenc.o] Error 1
~~~
This can't be explained with WSL.

**Comment by LeenHawk** [comment] 2023-06-27 10:20
I try to compile it on a fresh Ubuntu2204 wsl instance, success. But I try to compile it in a Debian Sid WSL, it failed.. It's so puzzling. And the error message is as same as the first mentioned...

**Comment by LeenHawk** [comment] 2023-06-27 10:21
I guess that it may be caused by WSLg because I install gedit in Debian.. I'll compiled ffmpeg again in a really fresh Debian Sid instance..

**Comment by LeenHawk** [comment] 2023-06-27 10:46
> I guess that it may be caused by WSLg because I install gedit in Debian.. I'll compiled ffmpeg again in a really fresh Debian Sid instance..

Result is: Failed, too. Emm, I don't know what is wrong... It seemed too puzzling... There are my logs. As a user, I can't give more information...
[build-x64-linux-rel-config.log](https://github.com/microsoft/vcpkg/files/11881031/build-x64-linux-rel-config.log)
[build-x64-linux-rel-err.log](https://github.com/microsoft/vcpkg/files/11881029/build-x64-linux-rel-err.log)
[build-x64-linux-rel-out.log](https://github.com/microsoft/vcpkg/files/11881030/build-x64-linux-rel-out.log)

**Comment by LeenHawk** [comment] 2023-06-27 10:52
It is producible on Debian Sid WSL but not Ubuntu 2204...

**Comment by iSerganov** [comment] 2023-07-26 22:01
Having this issue too with the latest debian:sid docker image

**Comment by LeenHawk** [comment] 2023-07-27 00:33
> Having this issue too with the latest debian:sid docker image

Maybe caused by GCC 13? Debian sid uses gcc 13 but ubuntu uses gcc 12 by default

**Comment by iSerganov** [comment] 2023-07-27 11:48
Not sure, I have found [here](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1910693.html) that [this patch](https://tracker.debian.org/news/1436528/accepted-qtwebengine-opensource-src-51514dfsg-3-source-into-experimental/) seems to be helpful in this case. But I am not sure how to apply it...

And if my assumptions is correct, the issue is fixed in latest `experimental` Debian.

**Comment by LeenHawk** [comment] 2023-07-28 01:01
> Also fails on `experimental` Debian with gcc 13.1. However builds perfectly on Debian `bookworm` with gcc 12. I have opened a bug on FFMPEG board - https://trac.ffmpeg.org/ticket/10491. Let's see what they say.

It's seems ffmpeg use a patch to fix it. We need to wait backporting

**Comment by LeenHawk** [comment] 2023-07-29 08:48
Emm, I backport it by myself.  I test it in Debian Sid.

**Comment by LeenHawk** [comment] 2023-07-29 09:37
This patch should be removed after ffmpeg release 6.1 (maybe months later?)

**Closed** 2023-07-31 18:34 UTC
Labels: requires:repro
