### ISSUE TITLE
How do I install boost lib compiled with /guard:cf & /Qspectre flags

### ISSUE THREAD

**Issue by mattfjh** [microsoft/vcpkg#23388] opened 2022-03-05 15:26 UTC
I added the following settings in my triplet files and hope b2 can use them when compiling boost lib. But the boost lib didn't pass the BinSkim check. How can I fix this?

_set(VCPKG_CXX_FLAGS "/Qspectre /guard:cf")
set(VCPKG_LINKER_FLAGS "/guard:cf /DYNAMICBASE")
set(VCPKG_C_FLAGS "/Qspectre /guard:cf")_

some logs in install-x64-windows-rel-out.log. it seems the flags in the jam file not correct. 

_notice: Searching 'xxxx\tools\vcpkg\buildtrees\boost-atomic\x64-windows-rel' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'C:/git/CMD-NativeThinClients/tools/vcpkg/buildtrees/boost-atomic/x64-windows-rel'.
xxxx\tools\vcpkg\buildtrees\boost-atomic\x64-windows-rel\user-config.jam:6: Unescaped special character in argument <cxxflags>/guard:cf
xxxx\tools\vcpkg\buildtrees\boost-atomic\x64-windows-rel\user-config.jam:7: Unescaped special character in argument <cflags>/guard:cf
xxxx\tools\vcpkg\buildtrees\boost-atomic\x64-windows-rel\user-config.jam:8: Unescaped special character in argument <linkflags>/machine:x64
xxxx\tools\vcpkg\buildtrees\boost-atomic\x64-windows-rel\user-config.jam:8: Unescaped special character in argument <linkflags>/INCREMENTAL:NO
xxxx\tools\vcpkg\buildtrees\boost-atomic\x64-windows-rel\user-config.jam:8: Unescaped special character in argument <linkflags>/OPT:REF
xxxx\tools\vcpkg\buildtrees\boost-atomic\x64-windows-rel\user-config.jam:8: Unescaped special character in argument <linkflags>/OPT:ICF
xxxx\tools\vcpkg\buildtrees\boost-atomic\x64-windows-rel\user-config.jam:8: Unescaped special character in argument <linkflags>/guard:cf_

**Comment by PhoebeHui** [comment] 2022-03-07 09:55
@mattfjh, this issue would be fixed by PR https://github.com/microsoft/vcpkg/pull/23001, could you help test if the PR works for you? the 2 flags are expected to apply correct with the changes.

**Comment by PhoebeHui** [comment] 2022-03-08 07:02
Double confirmed, PR #23001 has fixed this issue.

**Comment by mattfjh** [comment] 2022-03-09 18:39
The generated parameters doesn't seem right. should be /guard:cf /Qspectre

![image](https://user-images.githubusercontent.com/2165842/157508977-3fb64325-525a-4619-b781-051a89bb500c.png)

**Comment by vicroms** [comment] 2022-03-16 21:26
@mattfjh 

That is intended, [the compilar command-line syntax accepts both `-option` and `/option`](https://docs.microsoft.com/en-us/cpp/build/reference/compiler-command-line-syntax?view=msvc-170).

https://github.com/microsoft/vcpkg/blob/c7366f8416df3b31d518d9e42aded06673bebf95/ports/vcpkg-cmake/cmake_get_vars/CMakeLists.txt#L142-L150

**Comment by mattfjh** [comment] 2022-03-17 04:41
thanks @vicroms . I used [BinSkim ](https://github.com/Microsoft/binskim)to scan the dll and got this error. Any idea what else could be wrong?

![image](https://user-images.githubusercontent.com/2165842/158738383-1b3dc6f7-b104-450c-a996-2cb90361b612.png)

**Comment by mattfjh** [comment] 2022-03-17 05:06
Ah, I think the issue happens because the linker flag is not used -  I have the following linker flag in the triplets file


set(VCPKG_LINKER_FLAGS "/GUARD:CF /DYNAMICBASE")

**Comment by PhoebeHui** [comment] 2022-03-17 06:36
The flag may need to be applied to all boost dependency components, not just the boost-atomic.

**Comment by vicroms** [comment] 2022-03-21 22:54
Can confirm with latest commit https://github.com/microsoft/vcpkg/pull/23001/commits/74bc293ee0bfca2fb3b80f8714ccb476f07ef2fb that binskim doesn't complain about linker flags anymore.

However, I'm still not sure how to make vcpkg use a spectre mitigated runtime.

**Closed** 2022-03-30 21:52 UTC
Labels: category:port-bug
