### ISSUE TITLE
rapidjson missing GetLength() function

### ISSUE THREAD

**Issue by ray42** [microsoft/vcpkg#3401] opened 2018-05-01 13:59 UTC
Using vcpkg, I have installed rapidjson 1.1.0. But I keep getting the error that 

'GetLength' is not a member of rapidjson::GenericStringBuffer<rapidjson::UTF8<char>,rapidjson::CrtAllocator>'	

It's clearly there, look at line 85: http://rapidjson.org/stringbuffer_8h_source.html
But it's missing in my vcpkg\installed\x86-windows-custom\include\rapidjson\stringbuffer.h file.

What do I do about it? Thank you.

**Comment by arthur-tacca** [comment] 2018-05-01 14:14
Looking at the source repo for rapidjson, it appears that `GetLength()` [was added](https://github.com/Tencent/rapidjson/commit/5cd62c235d0ff1ccc2f9822047a470f62ad947f6) on 2016-09-22. The latest release is 1.1.0 which was released on 2016-08-25 (see [the Readme](https://github.com/Tencent/rapidjson)) and is the version installed by vcpkg. Discussion of making a new release can be found on the rapidjson bug tracker at Tencent/rapidjson#1006

**Comment by raymonwhite42** [comment] 2018-05-01 14:28
I see, thank you. I should have done more investigative work.

**Comment by pravic** [comment] 2018-05-03 11:15
Isn't it better to close this issue since the problem is clear? Just stopped by.

**Closed** 2019-07-08 06:16 UTC
Labels: port bug
