### ISSUE TITLE
Error: Building package tiff:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Luna19950606** [microsoft/vcpkg#8358] opened 2019-09-26 13:01 UTC
Package: tiff:x64-windows
  Vcpkg version: 2019.09.12-nohash

Error: Building package tiff:x64-windows failed with: BUILD_FAILED

**Comment by LilyWangL** [comment] 2019-09-27 08:36
Hi @Luna19950606, I can't reproduce this issue locally. Can you provide your build log?

**Comment by Luna19950606** [comment] 2019-09-30 02:56
Lily Thank you so much for replying me! But I already find a solution. I just mannually downloaded the required installing files and then run the script agian and it worked.

**Comment by LilyWangL** [comment] 2019-09-30 06:43
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Closed by LilyWangL** 2019-09-30 06:43 UTC
Labels: needs-repro
