### ISSUE TITLE
[<gmp:x64-windows>] build failure

### ISSUE THREAD

**Issue by 010722** [microsoft/vcpkg#33506] opened 2023-09-02 05:58 UTC
### Operating system

Windows

### Steps to reproduce the behavior

```Shell
vcpkg instal
```

### Failure logs

Package: gmp:x64-windows -> 6.2.1#21

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32822.0
-    vcpkg-tool version: 2023-06-22-f19f3d9939100085fe2f7e41502d60b08e2083b6
    vcpkg-readonly: true
    vcpkg-scripts version: 638b1588be3a265a9c7ad5b212cef72a1cad336a

**To Reproduce**

`vcpkg install `

**Failure logs**

```
-- Using cached gmp-6.2.1.tar.xz.
-- Cleaning sources at C:/Users/zguan/Desktop/stroke-universe/code/Ciallo/vcpkg_installed/vcpkg/blds/gmp/src/v6.2.1-0c723d4b6f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/zguan/AppData/Local/vcpkg/downloads/gmp-6.2.1.tar.xz
-- Applying patch asmflags.patch
-- Applying patch cross-tools.patch
-- Applying patch subdirs.patch
-- Applying patch msvc_symbol.patch
-- Applying patch arm64-coff.patch
-- Applying patch gmp-arm64-asm-fix-5f32dbc41afc.patch
-- Using source at C:/Users/zguan/Desktop/stroke-universe/code/Ciallo/vcpkg_installed/vcpkg/blds/gmp/src/v6.2.1-0c723d4b6f.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.40-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.34-3-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.36.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libcrypt-2.1-4-x86_64.pkg.tar.zst.
CMake Error at scripts/cmake/vcpkg_acquire_msys.cmake:150 (file):
  file SHA512 failed to read file "C:/Program Files/Microsoft Visual
  Studio/2022/Community/VC/vcpkg/scripts/msys/compile_wrapper_consider_clang-cl.patch":
  No such file or directory
Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:220 (z_vcpkg_acquire_msys_collect_hashes)
  scripts/cmake/vcpkg_configure_make.cmake:228 (vcpkg_acquire_msys)
  C:/Users/zguan/AppData/Local/vcpkg/registries/git-trees/726604ff590362102d805e16508ae20730583101/portfile.cmake:85 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)



```

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "ciallo",
  "version": "0.0.2",
  "dependencies": [
    "spdlog",
    "glfw3",
    "glad",
    "stb",
    "entt",
    "glm",
    "cgal"
  ],
  "builtin-baseline": "4a600e9fea71bd7872080cbb716797e04d30e6d3"
}

```
</details>

**Comment by dg0yt** [comment] 2023-09-02 16:03
https://github.com/microsoft/vcpkg/issues/31565.
Some versions of Visual Studio ship vcpkg but lack `scripts/msys/compile_wrapper_consider_clang-cl.patch`.

**Comment by FrankXie05** [comment] 2023-09-04 06:12
Duplicate of https://github.com/microsoft/vcpkg/issues/31565

**Closed by FrankXie05** 2023-09-04 06:12 UTC
Labels: category:question

**Comment by 010722** [comment] 2023-09-04 09:43
Final solution that worked: download compile_wrapper_consider_clang-cl.patch from https://github.com/microsoft/vcpkg/blob/4a600e9fea71bd7872080cbb716797e04d30e6d3/scripts/cmake/compile_wrapper_consider_clang-cl.patch#L4 directly and put in scripts/msys/compile_wrapper_consider_clang-cl.patch.
