### ISSUE TITLE
[liblzma] Build error on x64-windows

### ISSUE THREAD

**Issue by swatantra1** [microsoft/vcpkg#37970] opened 2024-04-04 13:54 UTC
While i am tying to run - "./vcpkg.exe install boost"

i am getting the following error

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/liblzma/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)

error: building liblzma:x64-windows failed with: BUILD_FAILED
Elapsed time to handle liblzma:x64-windows: 854 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+liblzma
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[liblzma]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2Fswatantra05s%2FDesktop%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by bansan85** [comment] 2024-04-04 14:14
Duplicate of #37839

See workaround at https://github.com/microsoft/vcpkg/issues/37962#issuecomment-2036223908

**Comment by jimwang118** [comment] 2024-04-07 02:34
Duplicate of https://github.com/microsoft/vcpkg/issues/37893.

**Closed by jimwang118** 2024-04-07 02:34 UTC
Labels: depends:upstream-changes
