### ISSUE TITLE
[mbedtls] find_package not available

### ISSUE THREAD

**Issue by kotori2** [microsoft/vcpkg#18356] opened 2021-06-09 20:31 UTC
I've tried `find_package(mbedtls CONFIG REQUIRED)` but it throws me an error
```
CMake Error at /Users/kotori0/vcpkg/scripts/buildsystems/vcpkg.cmake:772 (_find_package):
  Could not find a package configuration file provided by "mbedtls" with any
  of the following names:

    mbedtlsConfig.cmake
    mbedtls-config.cmake

  Add the installation prefix of "mbedtls" to CMAKE_PREFIX_PATH or set
  "mbedtls_DIR" to a directory containing one of the above files.  If
  "mbedtls" provides a separate development package or SDK, be sure it has
  been installed.
```

I also tried to ignore that error and link directly:
```
target_link_libraries(project mbedtls)
```
But it will fail: 
```
ld: library not found for -lmbedtls
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
So what should I do to use mbedtls with vcpkg?

**Comment by kotori2** [comment] 2021-06-09 20:54
Okay it seems it's missing some install calls in CMakefiles. 
Tried the following patch and it still producing a lot of errors.
```
diff --git a/library/CMakeLists.txt b/Users/kotori0/Downloads/CMakeLists.txt
index 4b99331..e9eea99 100644
--- a/library/CMakeLists.txt
+++ b/library/CMakeLists.txt
@@ -208,8 +208,14 @@ foreach(target IN LISTS target_libraries)
     target_compile_definitions(${target}
         PRIVATE ${thirdparty_def})
     install(TARGETS ${target}
+            EXPORT mbedTLS-config
             DESTINATION ${LIB_INSTALL_DIR}
             PERMISSIONS OWNER_READ OWNER_WRITE GROUP_READ WORLD_READ)
+    install(EXPORT mbedTLS-config
+            FILE mbedTLS-config.cmake
+            NAMESPACE mbedTLS::
+            DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/mbedTLS
+    )
 endforeach(target)

 add_custom_target(lib DEPENDS mbedcrypto mbedx509 mbedtls)

```

**Comment by JackBoosY** [comment] 2021-06-10 06:24
mbedtls has NOT been added this patch in vcpkg, causing it to not generate any cmake configuration files.
Even if it has a vcpkg cmake wrapper, but it only support Windows and enable feature `pthreads`.

**Comment by zhaoweny** [comment] 2021-07-12 13:44
FYI, mbed TLS 3.0 [released](https://github.com/ARMmbed/mbedtls/releases/tag/v3.0.0) with proper CMake find_package support.

> Add CMake package config generation for CMake projects consuming Mbed TLS

**Comment by JonLiu1993** [comment] 2022-07-29 08:55
Duplicate of #25703

**Closed by JonLiu1993** 2022-07-29 08:55 UTC
Labels: category:port-update

**Comment by rzr** [comment] 2023-08-26 06:45
Would it make sense to backport cmake support to 2.28 branch ?

I am sure others did before.

This would be desirable for debian packaging:

https://salsa.debian.org/debian-iot-team/mbedtls/

Regards
