### ISSUE TITLE
ethash-0.5.0

### ISSUE THREAD

**Issue by suifeng0001** [microsoft/vcpkg#16925] opened 2021-03-28 05:50 UTC
Library name:

Library description:

Source repository URL:https://codeload.github.com/chfast/ethash/tar.gz/v0.5.0

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by autoantwort** [comment] 2021-03-28 20:24
Duplicate of #16808

**Closed** 2021-03-29 02:11 UTC
Labels: category:new-port, info:good-first-issue
