### ISSUE TITLE
[python3] Build error on python3:arm64-osx@3.11.8

### ISSUE THREAD

**Issue by WeiTing1991** [microsoft/vcpkg#41065] opened 2024-09-18 23:56 UTC
Host Environment
Host: arm64-osx
Compiler: AppleClang 16.0.0.16000026

```
Installing 32/33 python3:x64-osx@3.11.8#4...
Building python3:x64-osx@3.11.8#4...
CMake Warning at ports/python3/portfile.cmake:7 (message):
Call Stack (most recent call first):
  scripts/ports.cmake:192 (include)

-- Using cached python-cpython-v3.11.8.tar.gz.
-- Cleaning sources at 
-- Applying patch 0001-only-build-required-projects.patch
-- Applying patch 0003-use-vcpkg-zlib.patch
-- Applying patch 0004-devendor-external-dependencies.patch
-- Applying patch 0005-dont-copy-vcruntime.patch
-- Applying patch 0008-python.pc.patch
-- Applying patch 0010-dont-skip-rpath.patch
-- Applying patch 0012-force-disable-modules.patch
-- Applying patch 0014-fix-get-python-inc-output.patch
-- Applying patch 0015-dont-use-WINDOWS-def.patch
-- Applying patch 0016-undup-ffi-symbols.patch
-- Applying patch 0018-fix-sysconfig-include.patch
-- Applying patch 0002-static-library.patch

-- Getting CMake variables for x64-osx-dbg
-- Getting CMake variables for x64-osx-rel
-- Generating configure for x64-osx
-- Finished generating configure for x64-osx
-- Configuring x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /opt/homebrew/bin/bash -c "V=1 ./../src/v3.11.8-31d17ab840.clean/configure --host=x86_64-apple-darwin \"--with-openssl=`workfolder`/vcpkg_installed/x64-osx\" \"--without-ensurepip\" \"--with-suffix=\" \"--with-system-expat\" \"--without-readline\" \"--disable-test-modules\" \"LIBS=-liconv -lintl\" \"--with-build-python=`workfolder`/vcpkg_installed/arm64-osx/tools/python3/python3.11\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--with-pydebug\" \"vcpkg_rpath=`workfolder`/vcpkg_installed/x64-osx/debug/lib\" \"--prefix=`workfolder`/vcpkg_installed/x64-osx/debug\" \"--bindir=\\${prefix}/../tools/python3/debug/bin\" \"--sbindir=\\${prefix}/../tools/python3/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/python3\""
    Working Directory: `workfolder`VCPKG/buildtrees/python3/x64-osx-dbg
    Error code: 1

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:866 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:274 (vcpkg_configure_make)
  scripts/ports.cmake:192 (include)

```
i try to install the miss package , but it doesnt work.
Also i try to install it without manifest mode, which leads the same result.
 
here i have provide the install script that i use.
vcpkg.json 
```
{
  "name": "app",
  "version-string": "0.1.0",
  "dependencies": [
      "glfw3",
      "glad" ,
      "opengl-registry",
      "implot",
      "python3",
      "pybind11",

    {
      "name": "imgui",
      "features": ["glfw-binding", "opengl3-binding"]
    }
  ]
```

install.sh 
```
#!/usr/bin/env bash

VCPKG_TARGET_TRIPLET="x64-osx"
VCPKG_DIR="$PWD/VCPKG"
INSTALLED_SHARED_DIR="$PWD/vcpkg_installed"  # Replace with actual path

# Check if dependencies are already installed
if [ ! -d "$INSTALLED_SHARED_DIR" ]; then
    rm -rf "$INSTALLED_SHARED_DIR"

    echo "Dependencies not installed. Installing..."

    # Define the path to the vcpkg executable
    pushd "$VCPKG_DIR" || exit

    # Run vcpkg install command
    ./vcpkg install --triplet="$VCPKG_TARGET_TRIPLET"

    # Check the result of the installation
    if [ $? -ne 0 ]; then
        echo "Failed to install dependencies with Vcpkg."
        exit 1
    fi

    popd || exit
fi

exit 0
```

**Comment by jimwang118** [comment] 2024-09-19 03:10
I have reproduced this issue locally.

**Comment by jimwang118** [comment] 2024-10-30 07:13
Duplicate of https://github.com/microsoft/vcpkg/issues/41055.

**Closed by jimwang118** 2024-10-30 07:13 UTC
Labels: category:port-bug
