### ISSUE TITLE
How can I use static libraries ?

### ISSUE THREAD

**Issue by eftales** [microsoft/vcpkg#7467] opened 2019-07-30 08:47 UTC
I want build my project by static linking. I got a solution in this page .
https://devblogs.microsoft.com/cppblog/vcpkg-updates-static-linking-is-now-available/
The method mentioned is as follows.
![solution](https://user-images.githubusercontent.com/26356125/62113492-49642480-b2e7-11e9-9135-6d579d45d635.png)
But it don't work in Visual Studio 2019 .
When I put that in my .vcxproj file , then rebuild it . It shows 
error LNK2001	unresolved external symbol  __imp__PathIsRelativeA@4
![bug report](https://user-images.githubusercontent.com/26356125/62114512-67328900-b2e9-11e9-8b76-7ace70afe4f3.png)
![added](https://user-images.githubusercontent.com/26356125/62113929-21c18c00-b2e8-11e9-96f0-a4d4e1d8adbe.png)
Static linking isn't available for  Visual Studio 2019 ?
If it can ,how can I use it ?

Thank you very much .

**Comment by crusader-mike** [comment] 2019-07-31 20:53
try linking `Shlwapi.lib` (vcpkg integration with msbuild doesn't pull additional dependencies, you have to specify them manually)

**Comment by BillyONeal** [comment] 2020-05-20 00:50
I just tried this and it worked just fine. Can you double check? Note that you'll need to install libraries under the associated chosen triplet for them to be found.

**Comment by Cheney-W** [comment] 2021-08-10 09:26
I also can't reproduce this issue in the latest vcpkg(2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfd).
Meanwhile, instead of modifying the vcxproj file, you can now set the use of static in Project->Properties->vcpkg in the ide interface:
![image](https://user-images.githubusercontent.com/38240633/128842912-7ebc4ae3-ee4e-4a6b-9828-66715002271f.png)

**Comment by JackBoosY** [comment] 2022-06-10 06:40
This issue should be fixed.

**Closed by JackBoosY** 2022-06-10 06:40 UTC
Labels: category:vcpkg-bug, requires:author-response
