### ISSUE TITLE
[libwebp] build failure

### ISSUE THREAD

**Issue by cenit** [microsoft/vcpkg#17397] opened 2021-04-20 18:33 UTC
https://github.com/microsoft/vcpkg/commit/85a48c1ed558210cab67a03209510c4bf6e5e285#r49765488

in a release-only triplet, portfile is broken because it tries in any case to modify debug pkgconfig files

**Comment by Hoikas** [comment] 2021-04-20 19:47
Dupe of #17359

**Closed** 2021-04-20 21:40 UTC
