### ISSUE TITLE
[libtorch] build failure

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#29545] opened 2023-02-09 02:20 UTC
**Host Environment**

- OS: Windows11
- Compiler: msvc vc143

**To Reproduce**

` ./vcpkg install libtorch[cuda,dist,leveldb,opencv,tbb,xnnpack,zstd]:x64-windows`

**Failure logs**

Installing 3/3 libtorch:x64-windows...
Building libtorch[core,cuda,dist,leveldb,opencv,tbb,xnnpack,zstd]:x64-windows...
-- Downloading https://github.com/pytorch/pytorch/archive/v1.12.1.tar.gz -> pytorch-pytorch-v1.12.1.tar.gz...
-- Extracting source D:/vcpkg/downloads/pytorch-pytorch-v1.12.1.tar.gz
-- Applying patch pytorch-pr-85958.patch
-- Applying patch fix-cmake.patch
-- Applying patch fix-fbgemm-include.patch
-- Applying patch fix-c10-glog.patch
-- Applying patch use-flatbuffers2.patch
-- Applying patch fix-windows.patch
-- Using source at D:/vcpkg/buildtrees/libtorch/src/v1.12.1-d15308d103.clean
-- Using flatc: D:/vcpkg/installed/x64-windows/tools/flatbuffers/flatc.exe
-- Using protoc: D:/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/vcpkg/downloads/tools/python/python-3.10.7-x64/Scripts/pip.exe install virtualenv --no-warn-script-location
    Working Directory: D:/vcpkg/buildtrees/libtorch
    Error code: 1
    See logs for more information:

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:61 (vcpkg_execute_required_process)
  ports/libtorch/portfile.cmake:34 (x_vcpkg_get_python_packages)
  scripts/ports.cmake:147 (include)

error: building libtorch:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libtorch
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[libtorch]+Build+error
Include '[libtorch] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 1c48ec7f4 2023-02-07 (26 hours ago)

**Additional context**

torch only support python version 3.6-3.9.

**Comment by JackBoosY** [comment] 2023-02-09 03:34
Can you please manually run command `D:/vcpkg/downloads/tools/python/python-3.10.7-x64/Scripts/pip.exe install virtualenv --no-warn-script-location` then provide the output?

**Comment by Bzz2745** [comment] 2023-02-09 03:51
> Can you please manually run command `D:/vcpkg/downloads/tools/python/python-3.10.7-x64/Scripts/pip.exe install virtualenv --no-warn-script-location` then provide the output?

Fatal error in launcher: Unable to create process using '"D:\ProgramFiles\vcpkg\downloads\tools\python\python-3.10.7-x64\python.exe"  "D:\vcpkg\downloads\tools\python\python-3.10.7-x64\Scripts\pip.exe" install virtualenv --no-warn-script-location': ???????????

**Comment by Bzz2745** [comment] 2023-02-09 03:53
> > Can you please manually run command `D:/vcpkg/downloads/tools/python/python-3.10.7-x64/Scripts/pip.exe install virtualenv --no-warn-script-location` then provide the output?
> 
> Fatal error in launcher: Unable to create process using '"D:\ProgramFiles\vcpkg\downloads\tools\python\python-3.10.7-x64\python.exe" "D:\vcpkg\downloads\tools\python\python-3.10.7-x64\Scripts\pip.exe" install virtualenv --no-warn-script-location': ???????????

Oh, I know:I have move vcpkg from D:\ProgramFiles to D:\. But how can I solve it? reinstall python?

**Comment by JackBoosY** [comment] 2023-02-09 06:32
> Oh, I know:I have move vcpkg from D:\ProgramFiles to D:. But how can I solve it? reinstall python?

Move vcpkg folder to other path should not affect anything. This may be a port `vcpkg-get-python-packages` bug which shouldn't contains absolutely path.  cc @jimwang118 

Please remove port `vcpkg-get-python-packages` then try again.

**Comment by JackBoosY** [comment] 2023-02-09 06:33
cc @Neumann-A Do you know why it happened?

**Comment by dg0yt** [comment] 2023-02-09 06:48
> Move vcpkg folder to other path should not affect anything.

... unless some absolute path landed in relevant files. We care about avoiding absolute paths artifact contents because they are meant to be portable. But we don't care about `downloads\tools` which are more or less transient.

**Comment by jimwang118** [comment] 2023-02-10 09:06
Do you have Python installed? If so, can you provide the version number of Python you are using?

**Comment by Bzz2745** [comment] 2023-02-10 13:56
> Do you have Python installed? If so, can you provide the version number of Python you are using?

I have already create a python venv with conda(miniconda or anaconda) ,python version 3.9,with torch and tensorflow.

**Comment by jimwang118** [comment] 2023-02-13 05:50
> I have already create a python venv with conda(miniconda or anaconda) ,python version 3.9,with torch and tensorflow.
I use Python3.10 and cmake3.25.1 locally and then install it without any problem. Did you try to reinstall libtorch with a higher version of Python and Cmake?

**Comment by jimwang118** [comment] 2023-02-13 05:58
>I have already create a python venv with conda(miniconda or anaconda) ,python version 3.9,with torch and tensorflow.

I use Python3.10 and cmake3.25.1 locally and then install it without any problem. Did you try to reinstall libtorch with a higher version of Python and Cmake?

**Comment by JackBoosY** [comment] 2023-02-13 05:59
@jimwang118 Can you reproduce this issue? I think it's easy to reproduce.

**Comment by dg0yt** [comment] 2023-02-13 06:16
Remove `downloads/tools`. As I said, this location is not expected to be relocatable, but it should be cheap to restore from `downloads` as needed.

**Comment by JackBoosY** [comment] 2023-02-13 06:22
> Remove `downloads/tools`. As I said, this location is not expected to be relocatable, but it should be cheap to restore from `downloads` as needed.

In my limited understanding, should python not write some files containing absolute paths after extracting the binaries?

**Comment by dg0yt** [comment] 2023-02-13 06:33
> > Remove `downloads/tools`. As I said, this location is not expected to be relocatable, but it should be cheap to restore from `downloads` as needed.
> 
> In my limited understanding, should python not write some files containing absolute paths after extracting the binaries?

This is what I expect for `downloads/tools`. And it is okay.

**Comment by JackBoosY** [comment] 2023-02-13 07:19
> This is what I expect for `downloads/tools`. And it is okay.

I don't understand, if the absolute path is in _installed_, re-download tools can't fix it.

**Comment by dg0yt** [comment] 2023-02-13 07:56
I didn't refer to re-download (expensive) but aim at a clean re-setup from downloaded archives. It will remove any modifications or added files since the original extraction (which happened in another location here).

**Comment by JackBoosY** [comment] 2023-02-13 08:02
> I didn't refer to re-download (expensive) but aim at a clean re-setup from downloaded archives. It will remove any modifications or added files since the original extraction (which happened in another location here).

It's not clear that where caused this issue I think?

**Comment by jimwang118** [comment] 2023-02-23 05:50
@Bzz2745 Do you have any new progress on this issue?

**Closed** 2023-02-23 06:08 UTC
Labels: category:port-bug

**Comment by dwhaynes** [comment] 2023-08-23 07:33
Any news?

**Comment by dwhaynes** [comment] 2023-08-23 07:34
Why is this closed if there is no solution?
