### ISSUE TITLE
[gettext:x64-windows] build failure

### ISSUE THREAD

**Issue by ZnoozeJooze** [microsoft/vcpkg#19411] opened 2021-08-06 10:45 UTC
**Host Environment**
- Windows 10
- First run vcpkg update + git pull

**To Reproduce**
`./vcpkg install gtk`

**Failure logs** 
Building package gettext[core]:x64-windows...
-- Using D:/repositories/ui1000_devel/3rd_party/vcpkg/downloads/gettext-0.21.tar.gz
-- Cleaning sources at D:/repositories/ui1000_devel/3rd_party/vcpkg/buildtrees/gettext/src/0.21-d3cbdc875d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/repositories/ui1000_devel/3rd_party/vcpkg/downloads/gettext-0.21.tar.gz
-- Applying patch 0002-Fix-uwp-build.patch
-- Applying patch 0003-Fix-win-unicode-paths.patch
-- Applying patch rel_path.patch
-- Applying patch android.patch
-- Using source at D:/repositories/ui1000_devel/3rd_party/vcpkg/buildtrees/gettext/src/0.21-d3cbdc875d.clean
-- Getting CMake variables for x64-windows
-- Using msys root at D:/repositories/ui1000_devel/3rd_party/vcpkg/downloads/tools/msys2/703e5aa15d402568
-- Using msys root at D:/repositories/ui1000_devel/3rd_party/vcpkg/downloads/tools/msys2/aa5af7b2aa7e90e8
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Using msys root at D:/repositories/ui1000_devel/3rd_party/vcpkg/downloads/tools/msys2/aaafe87dcead272e
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_build_make.cmake:201 (message):
  libtool could not find a file being linked against!
Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_make.cmake:26 (vcpkg_build_make)
  ports/gettext/portfile.cmake:96 (vcpkg_install_make)
  ports/gettext/portfile.cmake:138 (build_libintl_only)
  scripts/ports.cmake:141 (include)

Error: Building package gettext:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: gettext:x64-windows
  Vcpkg version: 2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
I ran it multiple times w/out any effect.

**Comment by dg0yt** [comment] 2021-08-06 10:54
Duplicate of #19337. Patch waiting to be merged.

**Comment by cenit** [comment] 2021-08-08 13:39
#19361 is merged, this issue can be closed

**Comment by JonLiu1993** [comment] 2021-08-09 01:47
@ZnoozeJooze ,Thanks for posting this issue,pr #19361 is merged,please update your vcpkg and try again

**Closed by JonLiu1993** 2021-08-09 01:47 UTC
Labels: category:tool-update
