### ISSUE TITLE
vcpkg commands alter the terminal window & font

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#2396] opened 2017-12-18 17:56 UTC
My default Powershell window looks like this after opening (standard Powershell, with posh-git):
![default](https://user-images.githubusercontent.com/4967343/34120103-680accc2-e41c-11e7-978e-40537f1592ed.png)
After executing a `vcpkg` command, it rescales the window and the font size changes:
![after](https://user-images.githubusercontent.com/4967343/34120106-694346a0-e41c-11e7-8cba-a7821b9cca3b.png)

I would expect the vcpkg command not to change the terminal?

**Comment by navidR** [comment] 2017-12-18 22:08
I believe it is a bug related to "Lucida" font. I changed my default font to Consolas and hasn't happened again.

**Comment by ras0219-msft** [comment] 2017-12-20 00:14
This is a really terrible bug that is related to our internal calling of `chcp 65001`. You can reproduce this issue yourself (without vcpkg) by running:
```
>chcp 65001
>powershell
```
However, we can't avoid calling `chcp 65001` because it causes builds to break.

You're absolutely right that we should not cause your terminal to resize and change font!

**Comment by sridmad** [comment] 2018-01-24 22:52
using chcp 65001 in either powershell windows or Windows Command prompt does not change the font size when the font is set to Lucidia Console. Can you please investigate why this call from vcpkg causes the font and font size to change?

I see the following when running vcpkg in Windows command prompt.
* Lucidia Console is set as my Font and font size set to 18
* running chcp 65001 in the command prompt does not change the font size of the window.
* running vcpkg in the window changes the font used by the window to Raster Fonts , 8 x 12

OS version - Microsoft Windows [Version 10.0.16299.192]

**Comment by MikeGitb** [comment] 2018-01-24 23:47
@sridmad: To reproduce this you have to start a new powershell from inside the open Powershell window (just type Powershell) after you changed the code page.

**Comment by sridmad** [comment] 2018-01-24 23:56
Looks like a Poweshell issue that has been there since 2013 at least. 

https://windowsserver.uservoice.com/forums/301869-powershell/suggestions/11088003-powershell-4-console-font-issue

Vote for the user voice issue if you this this issue with vcpkg.

**Comment by NancyLi1013** [comment] 2020-05-28 07:54
Hi all, 
I cannot reproduce this issue with powershell 5.1 on my local. 
I'm closing this issue for now. Please reopen this if it is still a problem for you.

**Closed by NancyLi1013** 2020-05-28 07:54 UTC
Labels: category:vcpkg-bug
