### ISSUE TITLE
[openblas] BUILD_FAILED

### ISSUE THREAD

**Issue by weidom** [microsoft/vcpkg#17393] opened 2021-04-20 12:29 UTC
```
Starting package 14/162: openblas:x64-windows
Building package openblas[core]:x64-windows...
-- Downloading https://github.com/xianyi/OpenBLAS/archive/63b03efc2af332c88b86d4fd8079d00f4b439adf.tar.gz -> xianyi-OpenBLAS-63b03efc2af332c88b86d4fd8079d00f4b439adf.tar.gz...
-- Extracting source D:/vcpkg/downloads/xianyi-OpenBLAS-63b03efc2af332c88b86d4fd8079d00f4b439adf.tar.gz
-- Applying patch uwp.patch
-- Applying patch fix-space-path.patch
-- Applying patch fix-redefinition-function.patch
-- Applying patch fix-pkg-config.patch
-- Applying patch fix-uwp-build.patch
-- Using source at D:/vcpkg/buildtrees/openblas/src/0f4b439adf-917c2f6847.clean
-- Downloading https://strawberryperl.com/download/5.30.0.1/strawberry-perl-5.30.0.1-32bit.zip -> strawberry-perl-5.30.0.1-32bit.zip...
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:105 (message):
    Command failed: ninja -v
    Working Directory: D:/vcpkg/buildtrees/openblas/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\openblas\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:324 (vcpkg_execute_required_process)
  ports/openblas/portfile.cmake:68 (vcpkg_configure_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package openblas:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openblas:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.
```

**Comment by weidom** [comment] 2021-04-20 12:31
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/6343489/config-x64-windows-out.log)

**Comment by JonLiu1993** [comment] 2021-04-21 08:30
@weidom ,Please git pull the vcpkg and reinstall openblas:x64-windows,and What is the current version of your openblas?

**Comment by JackBoosY** [comment] 2021-05-08 06:28
```
CMake Error at cmake/prebuild.cmake:517 (ParseGetArchVars):
  ParseGetArchVars Function invoked with incorrect arguments for function
  named: ParseGetArchVars
Call Stack (most recent call first):
  cmake/system.cmake:160 (include)
  CMakeLists.txt:69 (include)
```
In _source/cmake/prebuild.cmake_ line 510:
```cmake
execute_process(COMMAND "${BLASHELPER_BINARY_DIR}/${GETARCH_BIN}" 0 OUTPUT_VARIABLE GETARCH_MAKE_OUT)
...
  message(STATUS "GETARCH results:\n${GETARCH_MAKE_OUT}")
...
  ParseGetArchVars(${GETARCH_MAKE_OUT})
```

The value `GETARCH_MAKE_OUT` is empty, that caused this issue.

**Comment by Cheney-W** [comment] 2021-06-15 10:28
This issue is caused by a conflict between the name of a macro defined inside source and the name of a structure member in Windows SDK, and we will submit an issue to the upstream for fixing this issue.

**Comment by Cheney-W** [comment] 2021-06-16 07:18
I have submitted an issue https://github.com/xianyi/OpenBLAS/issues/3274 to upstream.

**Comment by Cheney-W** [comment] 2021-06-17 02:02
This issue has been fixed in the upstream by https://github.com/xianyi/OpenBLAS/pull/3276.

**Closed** 2021-06-21 20:32 UTC
Labels: category:port-bug
