### ISSUE TITLE
[OpenImageIO] find_package failed

### ISSUE THREAD

**Issue by xehoth** [microsoft/vcpkg#20522] opened 2021-10-05 06:20 UTC
**Host Environment**
- OS: Windows10 21H1
- Compiler: Visual Studio 2019 with MSVC 19.29.30133

**To Reproduce**
`./vcpkg install openimageio:x64-windows`
Then, use `find_package(OpenImageIO CONFIG REQUIRED)` in `CMakeLists.txt`.
When configuring, it gives the following error.

**Failure logs** 
```plain
CMake Error at C:/soft/vcpkg/installed/x64-windows/share/ilmbase/IlmBaseConfig.cmake:11 (message):
  File or directory /include referenced by variable OpenImageIO_INCLUDE_DIR
  does not exist !
Call Stack (most recent call first):
  C:/soft/vcpkg/installed/x64-windows/share/OpenImageIO/OpenImageIOConfig.cmake:45 (set_and_check)
  C:/soft/vcpkg/installed/x64-windows/share/OpenImageIO/vcpkg-cmake-wrapper.cmake:4 (_find_package)
  C:/soft/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  CMakeLists.txt:3 (find_package)
```

**Comment by jmacey** [comment] 2021-10-06 11:57
I can report that I am now getting the same issues on Linux (WSL Ubuntu 20 at present), 

```
 Found Threads: TRUE
-- Found ZLIB: optimized;/home/jmacey/vcpkg/installed/x64-linux/lib/libz.a;debug;/home/jmacey/vcpkg/installed/x64-linux/debug/lib/libz.a (found version "1.2.11")
-- Found Libsquish: /home/jmacey/vcpkg/installed/x64-linux/include
-- Found ZLIB: optimized;/home/jmacey/vcpkg/installed/x64-linux/lib/libz.a;debug;/home/jmacey/vcpkg/installed/x64-linux/debug/lib/libz.a (found suitable version "1.2.11", minimum required is "1.2.11")
CMake Error at /home/jmacey/vcpkg/installed/x64-linux/share/ilmbase/IlmBaseConfig.cmake:11 (message):
  File or directory /include referenced by variable OpenImageIO_INCLUDE_DIR
  does not exist !
Call Stack (most recent call first):
  /home/jmacey/vcpkg/installed/x64-linux/share/OpenImageIO/OpenImageIOConfig.cmake:45 (set_and_check)
  /home/jmacey/vcpkg/installed/x64-linux/share/openimageio/vcpkg-cmake-wrapper.cmake:4 (_find_package)
  /home/jmacey/vcpkg/scripts/buildsystems/vcpkg.cmake:740 (include)
  CMakeLists.txt:25 (find_package)
```

**Comment by dg0yt** [comment] 2021-10-06 12:30
> `File or directory /include`

This looks like a missing prefix. 
Do you have the current version of port `vcpkg-cmake-config`, including #20380?
If not:
~~~
git pull
./vcpkg remove --recurse vcpkg-cmake-config
./vcpkg install openimageio

**Comment by JackBoosY** [comment] 2021-10-22 02:29
@georgelyu  Can you please provide a mininum reproduce cmake code?

**Comment by JackBoosY** [comment] 2021-12-10 02:54
Since #20439 merged, can anyone test whether this issue is resolved?

Thanks.

**Comment by xehoth** [comment] 2021-12-10 03:04
> Since #20439 merged, can anyone test whether this issue is resolved?
> 
> Thanks.

The issue is solved. Thanks!

**Closed** 2021-12-10 03:06 UTC
Labels: category:port-bug, requires:repro
