### ISSUE TITLE
[libtorch] Build failure

### ISSUE THREAD

**Issue by yingliang-zhang** [microsoft/vcpkg#34784] opened 2023-10-30 07:04 UTC
Package: libtorch[core,xnnpack]:x64-windows -> 1.12.1#3

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32825.0
-    vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
    vcpkg-scripts version: 06c79a9af 2023-10-28 (28 hours ago)

**To Reproduce**

`vcpkg install libtorch`
**Failure logs**

```
-- Using cached pytorch-pytorch-v1.12.1.tar.gz.
-- Cleaning sources at D:/Vcpkg/buildtrees/libtorch/src/v1.12.1-e1cb316ec6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Vcpkg/downloads/pytorch-pytorch-v1.12.1.tar.gz
-- Applying patch pytorch-pr-85958.patch
-- Applying patch fix-cmake.patch
-- Applying patch fix-fbgemm-include.patch
-- Applying patch fix-c10-glog.patch
-- Applying patch use-flatbuffers2.patch
-- Applying patch fix-windows.patch
-- Applying patch fix_werror.patch
-- Using source at D:/Vcpkg/buildtrees/libtorch/src/v1.12.1-e1cb316ec6.clean
-- Using flatc: D:/Vcpkg/installed/x64-windows/tools/flatbuffers/flatc.exe
-- Using protoc: D:/Vcpkg/installed/x64-windows/tools/protobuf/protoc.exe
-- Using cached pypa-get-pip-38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz.
-- Cleaning sources at D:/Vcpkg/buildtrees/libtorch/src/8854625dd8-861bd167bd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Vcpkg/downloads/pypa-get-pip-38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz
-- Using source at D:/Vcpkg/buildtrees/libtorch/src/8854625dd8-861bd167bd.clean
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/Vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe D:/Vcpkg/buildtrees/libtorch/src/8854625dd8-861bd167bd.clean/public/get-pip.py --no-warn-script-location
    Working Directory: D:/Vcpkg/buildtrees/libtorch
    Error code: 1
    See logs for more information:
      D:\Vcpkg\buildtrees\libtorch\get-pip-x64-windows-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:48 (vcpkg_execute_required_process)
  ports/libtorch/portfile.cmake:35 (x_vcpkg_get_python_packages)
  scripts/ports.cmake:168 (include)



```
<details><summary>D:\Vcpkg\buildtrees\libtorch\get-pip-x64-windows-err.log</summary>

```
Traceback (most recent call last):
  File "D:\Vcpkg\buildtrees\libtorch\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 33324, in <module>
    main()
  File "D:\Vcpkg\buildtrees\libtorch\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 135, in main
    bootstrap(tmpdir=tmpdir)
  File "D:\Vcpkg\buildtrees\libtorch\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 111, in bootstrap
    monkeypatch_for_cert(tmpdir)
  File "D:\Vcpkg\buildtrees\libtorch\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 92, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand
  File "C:\Users\zhang\AppData\Local\Temp\tmpvdrddj3w\pip.zip\pip\_internal\commands\__init__.py", line 9, in <module>
  File "C:\Users\zhang\AppData\Local\Temp\tmpvdrddj3w\pip.zip\pip\_internal\cli\base_command.py", line 15, in <module>
  File "C:\Users\zhang\AppData\Local\Temp\tmpvdrddj3w\pip.zip\pip\_internal\cli\cmdoptions.py", line 23, in <module>
  File "C:\Users\zhang\AppData\Local\Temp\tmpvdrddj3w\pip.zip\pip\_internal\cli\parser.py", line 12, in <module>
  File "C:\Users\zhang\AppData\Local\Temp\tmpvdrddj3w\pip.zip\pip\_internal\configuration.py", line 24, in <module>
  File "C:\Users\zhang\AppData\Local\Temp\tmpvdrddj3w\pip.zip\pip\_internal\utils\appdirs.py", line 13, in <module>
  File "C:\Users\zhang\AppData\Local\Temp\tmpvdrddj3w\pip.zip\pip\_vendor\platformdirs\__init__.py", line 33, in <module>
  File "C:\Users\zhang\AppData\Local\Temp\tmpvdrddj3w\pip.zip\pip\_vendor\platformdirs\__init__.py", line 29, in _set_platform_dir_class
  File "importlib\__init__.py", line 126, in import_module
  File "C:\Users\zhang\AppData\Local\Temp\tmpvdrddj3w\pip.zip\pip\_vendor\platformdirs\windows.py", line 3, in <module>
  File "ctypes\__init__.py", line 8, in <module>
ImportError: DLL load failed while importing _ctypes: The specified module could not be found.
```
</details>

**Comment by JonLiu1993** [comment] 2023-10-30 10:04
Duplicate of #33346

**Closed by JonLiu1993** 2023-10-30 10:04 UTC
Labels: requires:repro
