### ISSUE TITLE
[wxwidgets] build failure

### ISSUE THREAD

**Issue by HWiman** [microsoft/vcpkg#14427] opened 2020-11-06 12:45 UTC
**Host Environment**
- OS: Linux (Ubuntu-20.04 WSL2)
- Compiler: gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0

**To Reproduce**
`./vcpkg install wxwidgets:x64-linux`

**Failure logs** 
-Building package wxwidgets[core]:x64-linux...
Could not locate cached archive: /home/hw/.cache/vcpkg/archives/bc/bcc3be52c8a02a8a83e2b7a522c5cd546f591f83.zip
-- Using cached /mnt/c/Dev/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.4.tar.gz
-- Cleaning sources at /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /mnt/c/Dev/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.4.tar.gz
-- Applying patch disable-platform-lib-dir.patch
-- Applying patch fix-stl-build-vs2019-16.6.patch
-- Using source at /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:141 (message):
    Command failed: /mnt/c/Dev/vcpkg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/x64-linux-dbg
    See logs for more information:
      /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:92 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/wxwidgets/portfile.cmake:41 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package wxwidgets:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: wxwidgets:x64-linux
  Vcpkg version: 2020.06.15-unknownhash
- Last part of log file: 
[61/791] cd /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean/build/cmake/lib/ribbon && /mnt/c/Dev/vcpkg
/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake -DCOTIRE_BUILD_TYPE:STRING=Debug -P /mnt/c/Dev/v
cpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean/build/cmake/modules/cotire.cmake precompile /mnt/c/Dev/vcpkg/build
trees/wxwidgets/x64-linux-dbg/libs/ribbon/wxribbon_CXX_cotire.cmake /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/x64-linux-dbg/
libs/ribbon/cotire/wxribbon_CXX_prefix.hxx /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/x64-linux-dbg/libs/ribbon/cotire/wxribb
on_CXX_prefix.hxx.gch /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean/src/ribbon/art_internal.cpp
[62/791] cd /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean/build/cmake/lib/html && /mnt/c/Dev/vcpkg/d
ownloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake -DCOTIRE_BUILD_TYPE:STRING=Debug -P /mnt/c/Dev/vcp
kg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean/build/cmake/modules/cotire.cmake precompile /mnt/c/Dev/vcpkg/buildtr
ees/wxwidgets/x64-linux-dbg/libs/html/wxhtml_CXX_cotire.cmake /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/x64-linux-dbg/libs/h
tml/cotire/wxhtml_CXX_prefix.hxx /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/x64-linux-dbg/libs/html/cotire/wxhtml_CXX_prefix.
hxx.gch /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean/src/html/helpctrl.cpp
[63/791] cd /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean/build/cmake/lib/richtext && /mnt/c/Dev/vcp
kg/downloads/tools/cmake-3.17.2-linux/cmake-3.17.2-Linux-x86_64/bin/cmake -DCOTIRE_BUILD_TYPE:STRING=Debug -P /mnt/c/Dev
/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean/build/cmake/modules/cotire.cmake precompile /mnt/c/Dev/vcpkg/bui
ldtrees/wxwidgets/x64-linux-dbg/libs/richtext/wxrichtext_CXX_cotire.cmake /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/x64-linu
x-dbg/libs/richtext/cotire/wxrichtext_CXX_prefix.hxx /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/x64-linux-dbg/libs/richtext/c
otire/wxrichtext_CXX_prefix.hxx.gch /mnt/c/Dev/vcpkg/buildtrees/wxwidgets/src/v3.1.4-b747a62900.clean/src/richtext/richt
extbuffer.cpp
ninja: build stopped: subcommand failed.

**Additional context**
### Tried to compile from PowerShell command line:
`.\vcpkg.exe install wxwidgets:x64-linux --debug`
but get:
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Using vcpkg-root: C:\Dev\vcpkg
[DEBUG] Using installed-root: C:\Dev\vcpkg\installed
[DEBUG] Using buildtrees-root: C:\Dev\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\Dev\vcpkg\downloads
[DEBUG] Using packages-root: C:\Dev\vcpkg\packages
[DEBUG] Using scripts-root: C:\Dev\vcpkg\scripts
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
[DEBUG] Default binary cache path is: C:\Users\hw\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] CreateProcessW("C:\Dev\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    42695 us
[DEBUG] CreateProcessW("C:\Dev\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe" -DVCPKG_ROOT_DIR=C:/Dev/vcpkg -DPACKAGES_DIR=C:/Dev/vcpkg/packages -DBUILDTREES_DIR=C:/Dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Dev/vcpkg/installed -DDOWNLOADS=C:/Dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Dev\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] cmd_execute_and_stream_data() returned 0 after    30466 us
The following packages will be built and installed:
    wxwidgets[core]:x64-linux
Detecting compiler hash for triplet x64-linux...
[DEBUG] Found path: C:\Program Files\Git\cmd/git.exe
[DEBUG] CreateProcessW("C:\Dev\vcpkg\downloads\tools\git-2.26.2-1-windows\mingw32\bin\git.exe" --version)
[DEBUG] cmd_execute_and_stream_data() returned 0 after    24207 us
[DEBUG] CreateProcessW("C:\Dev\vcpkg\downloads\tools\cmake-3.17.2-windows\cmake-3.17.2-win32-x86\bin\cmake.exe" -DCURRENT_PORT_DIR=C:/Dev/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=C:/Dev/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=C:/Dev/vcpkg/packages/detect_compiler_x64-linux -DCMD=BUILD -DTARGET_TRIPLET=x64-linux "-DTARGET_TRIPLET_FILE=C:\Dev\vcpkg\triplets\x64-linux.cmake" -DVCPKG_PLATFORM_TOOLSET=external -DDOWNLOADS=C:/Dev/vcpkg/downloads -DVCPKG_CONCURRENCY=9 -DGIT=C:/Dev/vcpkg/downloads/tools/git-2.26.2-1-windows/mingw32/bin/git.exe -DVCPKG_ROOT_DIR=C:/Dev/vcpkg -DPACKAGES_DIR=C:/Dev/vcpkg/packages -DBUILDTREES_DIR=C:/Dev/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/Dev/vcpkg/installed -DDOWNLOADS=C:/Dev/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\Dev\vcpkg\scripts\ports.cmake")
[DEBUG] -- Configuring x64-linux
[DEBUG] CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:85 (message):
[DEBUG]     Command failed: ninja -v
[DEBUG]     Working Directory: C:/Dev/vcpkg/buildtrees/detect_compiler/x64-linux-rel/vcpkg-parallel-configure
[DEBUG]     Error code: 1
[DEBUG]     See logs for more information:
[DEBUG]       C:\Dev\vcpkg\buildtrees\detect_compiler\config-x64-linux-out.log
[DEBUG]
[DEBUG] Call Stack (most recent call first):
[DEBUG]   scripts/cmake/vcpkg_configure_cmake.cmake:312 (vcpkg_execute_required_process)
[DEBUG]   scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
[DEBUG]   scripts/ports.cmake:79 (include)
[DEBUG]
[DEBUG]
[DEBUG] cmd_execute_and_stream_data() returned 1 after  1953664 us
[DEBUG]
[DEBUG] Compiler information tracking can be disabled by passing --feature-flags=-compilertracking
Error occurred while detecting compiler information. Pass `--debug` for more information.
[DEBUG] C:\Dev\vcpkg\toolsrc\src\vcpkg\build.cpp(584)
[DEBUG] Exiting after 2153244 us (2140800 us)

**Comment by LilyWangL** [comment] 2020-11-09 06:03
Thanks for posting this issue. `wxwidgets` build failed on Linux now. Closed as duplicate of #7931.

**Closed by LilyWangL** 2020-11-09 06:03 UTC
Labels: category:port-bug
