### ISSUE TITLE
[New Port Request] lepton

### ISSUE THREAD

**Issue by Zunnki0** [microsoft/vcpkg#25081] opened 2022-06-05 23:18 UTC
Library name: lepton

Library description: "A small C++ library for parsing, evaluating, differentiating, and analyzing mathematical expressions."

Source repository URL: https://github.com/rdinizcal/lepton

Project homepage: https://simtk.org/projects/lepton    (Is this the project homepage?)

________________________________________________________________________________________________________________________

I am trying to install the "lepton" library which is available on this link
https://github.com/rdinizcal/lepton

When I run 
      .\vcpkg search lepton 

it is not listed among the available options. Would it be possible to install it from the github link using vcpkg?

**Comment by FrankXie05** [comment] 2022-06-06 01:49
Duplicate of #25082

**Closed by FrankXie05** 2022-06-06 01:49 UTC
