### ISSUE TITLE
[ace] build failure

### ISSUE THREAD

**Issue by Osyotr** [microsoft/vcpkg#21525] opened 2021-11-18 23:04 UTC
**Host Environment**
- OS: WSL (Ubuntu 20.04.3 LTS (GNU/Linux 4.4.0-19041-Microsoft x86_64)
- Compiler: g++ (Ubuntu 10.3.0-1ubuntu1~20.04) 10.3.0

**To Reproduce**
`./vcpkg install ace[tao,ssl,wchar,zlib]`

**Failure logs** 
```
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: make ssl=1 debug=1 optimize=0 -j9
    Working Directory: /mnt/d/vcpkg/buildtrees/ace/src/ACE-TAO-7-f61ead9ce9.clean/TAO
    See logs for more information:
      /mnt/d/vcpkg/buildtrees/ace/make-x64-linux-dbg-out.log
      /mnt/d/vcpkg/buildtrees/ace/make-x64-linux-dbg-err.log

Call Stack (most recent call first):
  ports/ace/portfile.cmake:347 (vcpkg_execute_build_process)
  scripts/ports.cmake:142 (include)
```
[mwc-x64-linux-out.log](https://github.com/microsoft/vcpkg/files/7566386/mwc-x64-linux-out.log)
[make-x64-linux-dbg-out.log](https://github.com/microsoft/vcpkg/files/7566383/make-x64-linux-dbg-out.log)
[make-x64-linux-dbg-err.log](https://github.com/microsoft/vcpkg/files/7566384/make-x64-linux-dbg-err.log)

**Additional context**
vcpkg HEAD: `cbc22a396c88d098247fe7f79f0913a952e1f77d`
When I downgrade to `8831ef24eee7e04009fe464097680512e46138a4` , I get an error inside `vcpkg_fixup_pkgconfig`.

**Comment by Osyotr** [comment] 2021-11-19 08:10
Same error with recent update (https://github.com/microsoft/vcpkg/commit/3fe9e06430a263093fb6802b39c17263c09d6d93)

**Comment by Osyotr** [comment] 2021-12-13 14:04
@jwillemsen would you kindly take a look? Also, it seems that `wchar` feature is broken on linux.

**Comment by jwillemsen** [comment] 2021-12-13 14:14
Looks something that could be caused by using parallel make heavily. Can you try to not use `-j9` as part of the make flags? Why is this a static build, would expect a shared library build by default.

**Comment by Osyotr** [comment] 2021-12-13 14:33
@jwillemsen I think `-j9` is set by vcpkg and I have no way to change it. Static build is [default for linux ](https://github.com/microsoft/vcpkg/discussions/19127#discussioncomment-1049622). Dynamic build is also broken.

**Comment by jwillemsen** [comment] 2021-12-13 14:58
Looks some more work has to be done on the vcpkg packaging of ACE on Linux, maybe you can contribute some changes @Osyotr

**Comment by dg0yt** [comment] 2021-12-13 15:40
> I think `-j9` is set by vcpkg and I have no way to change it.

You can set environment variable `VCPKG_MAX_CONCURRENCY`.
https://vcpkg.io/en/docs/users/config-environment.html#vcpkg_max_concurrency

**Comment by Osyotr** [comment] 2021-12-13 15:41
Regarding `wchar` issue: it seems that resulting binaries do export wchar-versions of functions, but ace/config.h lacks `ACE_USES_WCHAR` macro

**Comment by jwillemsen** [comment] 2021-12-13 15:47
When `uses_wchar` is set as MPC flag it should be added to the makefiles, when you don't use [MPC](https://github.com/DOCGroup/MPC) you should do that yourself

**Comment by pierrebizz** [comment] 2021-12-15 19:38
@jwillemsen 

Actually, it's the static configuration that is broken; I don't think it's related to vcpkg
uname -a
Linux VM-Ubuntu20 5.11.0-43-generic #47-20.04.2-Ubuntu SMP Mon Dec 13 11:06:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I downloaded the file ACE+TAO-src-7.0.5.tar.gz
tar xzf ACE+TAO-src-7.0.5.tar.gz
cd ACE_wrappers
export ACE_ROOT=`pwd`
export TAO_ROOT=$ACE_ROOT/TAO
cd $TAO_ROOT
perl $ACE_ROOT/bin/mwc.pl -features "ssl=1,openssl11=1" -static -type gnuace TAO_ACE.mwc
cd $ACE_ROOT/ace
ln -s config-linux.h config.h
cd $ACE_ROOT/include/makeinclude
ln -s platform_linux.GNU platform_macros.GNU
cd $TAO_ROOT
make ssl=1

fails with
      |       ^~~~
TAO_IDL_BE_VIS_A will not be built due to the following disabled make macros: build_tao_idl_be
TAO_IDL_BE_VIS_C will not be built due to the following disabled make macros: build_tao_idl_be
TAO_IDL_BE_VIS_E will not be built due to the following disabled make macros: build_tao_idl_be
TAO_IDL_BE_VIS_I will not be built due to the following disabled make macros: build_tao_idl_be
TAO_IDL_BE_VIS_O will not be built due to the following disabled make macros: build_tao_idl_be
TAO_IDL_BE_VIS_S will not be built due to the following disabled make macros: build_tao_idl_be
TAO_IDL_BE_VIS_U will not be built due to the following disabled make macros: build_tao_idl_be
TAO_IDL_BE_VIS_V will not be built due to the following disabled make macros: build_tao_idl_be
TAO_IDL_EXE will not be built due to the following missing library: TAO_IDL_BE_VIS_V TAO_IDL_BE_VIS_A TAO_IDL_BE_VIS_O TAO_IDL_BE_VIS_C TAO_IDL_BE_VIS_E TAO_IDL_BE_VIS_I TAO_IDL_BE_VIS_S TAO_IDL_BE_VIS_U TAO_IDL_BE_VIS_C TAO_IDL_BE_VIS_A TAO_IDL_BE_VIS_E TAO_IDL_BE_VIS_V TAO_IDL_BE_VIS_S TAO_IDL_BE_VIS_O

**Comment by jwillemsen** [comment] 2021-12-15 19:54
That are all warnings you list

**Comment by pierrebizz** [comment] 2021-12-15 21:06
Well it is kind of an error: since TAO_IDL_EXE is not built, TAO won't be built

**Comment by pierrebizz** [comment] 2021-12-15 22:24
I had the same kind of error on CentOs 9 with the static configuration

**Comment by jwillemsen** [comment] 2021-12-16 07:28
I get the impression not all output is there, can you attach a full build log, maybe parallel make is messing up the output

**Comment by pierrebizz** [comment] 2021-12-16 17:54
bizz@covid-xix:~$ tar xzf ACE+TAO-7.0.5.tar.gz
bizz@covid-xix:~$ cd ACE_wrappers/
bizz@covid-xix:~/ACE_wrappers$ export ACE_ROOT=`pwd`
bizz@covid-xix:~/ACE_wrappers$ export TAO_ROOT=$ACE_ROOT/TAO
bizz@covid-xix:~/ACE_wrappers$ env | grep "ROOT"
ACE_ROOT=/home/bizz/ACE_wrappers
TAO_ROOT=/home/bizz/ACE_wrappers/TAO
bizz@covid-xix:~/ACE_wrappers$ cd ace/
bizz@covid-xix:~/ACE_wrappers/ace$ ln -s config-linux.h config.h
bizz@covid-xix:~/ACE_wrappers/ace$ cd ../include/makeinclude/
bizz@covid-xix:~/ACE_wrappers/include/makeinclude$ ln -s platform_linux.GNU platform_macros.GNU
bizz@covid-xix:~/ACE_wrappers/include/makeinclude$ cd $TAO_ROOT
bizz@covid-xix:~/ACE_wrappers/TAO$ perl $ACE_ROOT/bin/mwc.pl -type gnuace -features "ssl=1,openssl11=1,zlib=1" -static TAO_ACE.mwc
Using .../bizz/ACE_wrappers/bin/MakeProjectCreator/config/MPC.cfg
Generating 'gnuace' output using TAO_ACE.mwc
Skipping ACE_FOR_TAO (ace_for_tao.mpc); it requires ace_for_tao.
Skipping ACE_Qt4Reactor_moc (ace_qt4reactor.mpc); it requires qt4.
Skipping ACE_Qt4Reactor (ace_qt4reactor.mpc); it requires qt4.
Skipping ACE_Qt5Reactor_moc (ace_qt5reactor.mpc); it requires qt5.
Skipping ACE_Qt5Reactor (ace_qt5reactor.mpc); it requires qt5.
Skipping ACE_FoxReactor (ace_foxreactor.mpc); it requires fox.
Skipping ACE_XML_Utils (XML.mpc); it requires xerces.
Skipping QoS (qos.mpc); it requires qos.
Skipping ace_svcconf_gen (svcconfgen.mpc); it requires ace_svcconf_gen.
Skipping SSL_FOR_TAO (ssl_for_tao.mpc); it requires ace_for_tao.
Skipping Bzip2Compressor (Bzip2Compressor.mpc); it requires bzip2.
Skipping LzoCompressor (LzoCompressor.mpc); it requires lzo1.
Skipping TAO_QtResource (QtResource.mpc); it requires dummy_label.
Skipping TAO_FoxResource (FoxResource.mpc); it requires fox.
Skipping TAO_IDL_GEN (tao_idl_fe.mpc); it requires tao_idl_fe_gen.
Skipping NamingViewer (NamingViewer.mpc); it requires mfc.
Skipping wxNamingViewer (wxNamingViewer.mpc); it requires wxWindows.
Generation Time: 30s
bizz@covid-xix:~/ACE_wrappers/TAO$ make -j1 ssl=1 2>&1 | tee out.txt

resulted in the output attached; notice that I used -j1 to eliminate the parallel build hypothesis
[out.txt](https://github.com/microsoft/vcpkg/files/7729463/out.txt)

**Comment by jwillemsen** [comment] 2021-12-16 19:14
Looks static compilation has a basic problem. We currently don't have daily build/tests in a static configuration due to the huge disk space needs. Feel free to open a PR on ACE/TAO to resolve this or see https://github.com/DOCGroup/ACE_TAO/wiki/ACE-and-TAO-Commercial-support

**Comment by Osyotr** [comment] 2021-12-16 19:47
@jwillemsen dynamic build is also broken. In fact, I was initially building with unofficial `x64-linux-dynamic` triplet but re-checked with static triplet so that the issue would not receive `community triplet` badge.

**Comment by pierrebizz** [comment] 2021-12-17 18:15
I went back in time today, and the last build that worked was 6.5.12. The problem with the static build starts at 7.0.0.

My expertise with the build file generation is too low to find the reason however

**Comment by pierrebizz** [comment] 2022-01-06 19:57
I think this issue is resolved by https://github.com/microsoft/vcpkg/pull/22091 and could be closed.

The build proceeds further but fails with:

`CMake Error at scripts/cmake/vcpkg_fixup_pkgconfig.cmake:78 (message):
  /bin/pkg-config --exists TAO_CosProperty_Serv failed with error code: 1

      ENV{PKG_CONFIG_PATH}: "/home/bizz/vcpkg/packages/ace_x64-linux/lib/pkgconfig:/home/bizz/vcpkg/packages/ace_x64-linux/share/pkgconfig:/home/bizz/textml/vcpkg_installed/x64-linux/lib/pkgconfig:/home/bizz/textml/vcpkg_installed/x64-linux/share/pkgconfig"
      output: Package TAO_PortableServer_Skel was not found in the pkg-config search path.

  Perhaps you should add the directory containing
  `TAO_PortableServer_Skel.pc'

  to the PKG_CONFIG_PATH environment variable

  Package 'TAO_PortableServer_Skel', required by 'TAO_CosProperty_Serv', not
  found
Call Stack (most recent call first):
  scripts/cmake/vcpkg_fixup_pkgconfig.cmake:201 (z_vcpkg_fixup_pkgconfig_check_files)
  buildtrees/versioning_/versions/ace/1801922b3e4808edcd0b55b6a800bbb1c01687a6/portfile.cmake:434 (vcpkg_fixup_pkgconfig)
  scripts/ports.cmake:142 (include)

`

The following patch file corrects the problem, but I'm really not an expert in the dependency file
[ACETAO_dependencyFixed.txt](https://github.com/microsoft/vcpkg/files/7824377/ACETAO_dependencyFixed.txt)
s

**Comment by jwillemsen** [comment] 2022-01-20 09:02
See https://github.com/DOCGroup/ACE_TAO/releases/tag/ACE%2BTAO-7_0_6 for a new upstream release with several fixes related to this issue

**Closed** 2022-01-26 04:57 UTC
Labels: category:port-bug
