### ISSUE TITLE
What type of errors are the following two errors? Do I need to have visual studio installed or any other installation before installing this vcpkg???

### ISSUE THREAD

**Issue by charleswri631** [microsoft/vcpkg#18558] opened 2021-06-21 00:02 UTC
What type of errors are the following two errors? Do I need to have visual studio installed or any other installation before installing this vcpkg???

![vcpkg_ERROR](https://user-images.githubusercontent.com/65590698/122692318-4091da00-d202-11eb-8090-eadafa889730.png)

![vcpkg_ERROR_1](https://user-images.githubusercontent.com/65590698/122692319-44256100-d202-11eb-9cd0-126c23bc8366.png)

ANY IDEAS in regards to these errors? I will continue to investigate on your git hub website section on vcpkg.

**Comment by JonLiu1993** [comment] 2021-06-21 09:42
@charleswri631 ,I did not reproduce your issue on powershell, but we must install visual studio in the preparation phase，You can refer to our official [documentation ](https://github.com/microsoft/vcpkg#quick-start-windows)to understand what needs to be prepared before using vcpkg

**Comment by JackBoosY** [comment] 2021-07-20 09:11
It looks like you are using Visual Studio 2013, but vcpkg requires at least Visual Studio 2015.
This error is caused by a mismatch between MT/MD and VCPKG CRT linkage.

**Comment by NancyLi1013** [comment] 2021-08-06 08:52
Closing this issue for now. Please feel free to reopen this issue if it is still a problem for you.

**Closed by NancyLi1013** 2021-08-06 08:52 UTC
Labels: category:question
