### ISSUE TITLE
[bullet3] Add support for BulletRobotics & Extras

### ISSUE THREAD

**Issue by Spirit532** [microsoft/vcpkg#10808] opened 2020-04-13 08:01 UTC
****

**Is your feature request related to a problem? Please describe.**
The current port explicitly disables building and linking the Extras(-DBUILD_EXTRAS), which means the BulletRobotics code is not built, which cuts off a relatively big chunk of the library, and makes it significantly harder to use.

**Proposed solution**
Configure the library to optionally build BulletRobotics and other Extras.

**Describe alternatives you've considered**
Building outside vcpkg is a relatively painful solution, one that often results in hard to maintain projects.

**Additional context**
Look at the difference in complexity between the InverseKinematics example and the RobotSimulator/HelloBulletRobotics example.

**Comment by NancyLi1013** [comment] 2020-04-14 10:39
Hi @Spirit532 
Thanks for posting this issue.
I submitted a PR #10821 to add this feature.
Could you please help confirm if this can work for you?

**Comment by Spirit532** [comment] 2020-04-14 20:01
Hi @NancyLi1013
Just including extras appears to not work, as it creates a lot of linking errors.
Specifically a mismatch between MD_DynamicRelease(which the library appears to be stuck on) and MDd_DynamicDebug(which the project is built for).
This is additional issue, because Bullet in general does not officially support dynamic linking, and when installed using `x64-windows-static` exclusively, results in many missing files.

Please attempt to build it yourself and reproduce the issue. Create a new project, install `bullet3[*]:x64-windows-static`, try including `LinearMath/btTransform.h`, `bullet_robotics/b3RobotSimulatorClientAPI_NoGUI.h`, and then compiling the following:
```C
b3Vector3 test1 = b3MakeVector3(1, 1, 1);
b3Vector4 test2 = b3MakeVector4(1, 1, 1, 1);
b3RobotSimulatorClientAPI_NoGUI test3;
```

**Comment by NancyLi1013** [comment] 2020-04-15 01:43
Thanks for your test and feedback.
I will try to reproduce on my local.

**Comment by NancyLi1013** [comment] 2020-04-15 10:38
The error like this:
```
1>bullet3Project.obj : error LNK2019: unresolved external symbol "public: __cdecl b3RobotSimulatorClientAPI_NoGUI::b3RobotSimulatorClientAPI_NoGUI(void)" (??0b3RobotSimulatorClientAPI_NoGUI@@QEAA@XZ) referenced in function main
1>bullet3Project.obj : error LNK2019: unresolved external symbol "public: virtual __cdecl b3RobotSimulatorClientAPI_NoGUI::~b3RobotSimulatorClientAPI_NoGUI(void)" (??1b3RobotSimulatorClientAPI_NoGUI@@UEAA@XZ) referenced in function main
1>C:\Users\v-ruil\source\repos\bullet3Project\x64\Debug\bullet3Project.exe : fatal error LNK1120: 2 unresolved externals
1>Done building project "bullet3Project.vcxproj" -- FAILED.
```
It seems that `b3RobotSimulatorClientAPI_NoGUI `is from the source code listed in `example  `folder.
I removed `b3RobotSimulatorClientAPI_NoGUI test3;`, the project can build successfully.

I also tried to build example and set 
```
-DBUILD_BULLET2_DEMOS=ON
-DBUILD_BULLET3=ON 
```
but there were still some errors like this:
```
LINK : warning LNK4075: ignoring '/INCREMENTAL' due to '/OPT:ICF' specification
   Creating library examples\ExampleBrowser\App_ExampleBrowser.lib and object examples\ExampleBrowser\App_ExampleBrowser.exp
Error copying directory from "F:/test/vcpkg/buildtrees/bullet3/src/2.89-eb26871ed5/data" to "F:/test/vcpkg/buildtrees/bullet3/x64-windows-static-dbg/data".
[902/903] cmd.exe /C "cd . && F:\test\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=examples\SharedMemory\CMakeFiles\App_PhysicsServer_SharedMemory_VR.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100183~1.0\x64\mt.exe --manifests  -- "E:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.25.28610\bin\Hostx64\x64\link.exe"  @CMakeFiles\App_PhysicsServer_SharedMemory_VR.rsp  /out:examples\SharedMemory\App_PhysicsServer_SharedMemory_VR.exe /implib:examples\SharedMemory\App_PhysicsServer_SharedMemory_VR.lib /pdb:examples\SharedMemory\App_PhysicsServer_SharedMemory_VR.pdb /version:0.0  /machine:x64 /OPT:REF /OPT:ICF /INCREMENTAL:NO /debug /INCREMENTAL /subsystem:console  && cmd.exe /C "cd /D F:\test\vcpkg\buildtrees\bullet3\x64-windows-static-dbg\examples\SharedMemory && F:\test\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E copy_if_different F:/test/vcpkg/buildtrees/bullet3/src/2.89-eb26871ed5/examples/ThirdPartyLibs/openvr/bin/win64/openvr_api.dll F:/test/vcpkg/buildtrees/bullet3/x64-windows-static-dbg/examples/SharedMemory/openvr64pi.dll && cd /D F:\test\vcpkg\buildtrees\bullet3\x64-windows-static-dbg\examples\SharedMemory && F:\test\vcpkg\downloads\tools\cmake-3.14.0-windows\cmake-3.14.0-win32-x86\bin\cmake.exe -E copy_directory F:/test/vcpkg/buildtrees/bullet3/src/2.89-eb26871ed5/data F:/test/vcpkg/buildtrees/bullet3/x64-windows-static-dbg/data""
Microsoft (R) Incremental Linker Version 14.25.28612.0
```
I'm not sure why the files cannot be copied successfully.

**Comment by Spirit532** [comment] 2020-04-16 09:11
Well, yes, that is the issue that needs fixing. `b3RobotSimulatorClientAPI_NoGUI ` is a crucial part of the easier to use API.

**Comment by NancyLi1013** [comment] 2020-08-06 06:08
The link error is due to that `BUILD_SHARED_LIBS ` is disabled in Windows platform. Please see here https://github.com/bulletphysics/bullet3/issues/1794

It will be fixed by the PR https://github.com/bulletphysics/bullet3/pull/2389

So in my opinion, we can continue solving this issue after the link error is fixed by upstream.

**Closed** 2023-07-31 18:29 UTC
Labels: category:port-feature
