### ISSUE TITLE
[ms-quic] Build error on x64-windows

### ISSUE THREAD

**Issue by dawnlike** [microsoft/vcpkg#35321] opened 2023-11-25 17:51 UTC
```
PS C:\Users\Administrator> vcpkg install ms-quic
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    ms-quic:x64-windows -> 1.2.0
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\Administrator\AppData\Local\vcpkg\archives in 2.99 ms. Use --debug to see more details.
Installing 1/1 ms-quic:x64-windows...
Building ms-quic:x64-windows...
-- Using cached microsoft-msquic-v1.2.0.tar.gz.
-- Cleaning sources at D:/dev/vcpkg/buildtrees/ms-quic/src/v1.2.0-19ce393c24.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/dev/vcpkg/downloads/microsoft-msquic-v1.2.0.tar.gz
-- Applying patch fix-warnings.patch
-- Applying patch fix-platform.patch
-- Applying patch fix-install.patch
-- Using source at D:/dev/vcpkg/buildtrees/ms-quic/src/v1.2.0-19ce393c24.clean
-- Using cached quictls-openssl-a6e9d76db343605dae9b59d71d2811b195ae7434.tar.gz.
-- Extracting source D:/dev/vcpkg/downloads/quictls-openssl-a6e9d76db343605dae9b59d71d2811b195ae7434.tar.gz
-- Using source at D:/dev/vcpkg/buildtrees/ms-quic/src/b195ae7434-aa88ae7c62.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/dev/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/dev/vcpkg/buildtrees/ms-quic/x64-windows-dbg
    See logs for more information:
      D:\dev\vcpkg\buildtrees\ms-quic\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/ms-quic/portfile.cmake:64 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)


error: building ms-quic:x64-windows failed with: BUILD_FAILED
Elapsed time to handle ms-quic:x64-windows: 5.1 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ms-quic
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[ms-quic]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```
[build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/13464873/build-x64-windows-dbg-out.log)

**Comment by JonLiu1993** [comment] 2023-11-27 02:49
Duplicate of #29459, fixing by PR https://github.com/microsoft/vcpkg/pull/29568

**Closed by JonLiu1993** 2023-11-27 02:49 UTC
Labels: category:port-bug
