### ISSUE TITLE
[vcpkg upgrade] fail to upgrade installed libs

### ISSUE THREAD

**Issue by jsnhsu** [microsoft/vcpkg#31941] opened 2023-06-11 14:35 UTC
The error just happened after I git pull and get latest binary by using bootstrap-vcpkg.bat and run $> .\vcpkg.exe update then .\vcpkg.exe upgrade --no-dry-run

The Powershell shows:
........
Removing 317/634 vcpkg-cmake:x64-windows
Elapsed time to handle vcpkg-cmake:x64-windows: 11.6 ms
Installing 318/634 vcpkg-cmake:x64-windows...
Building vcpkg-cmake:x64-windows...
-- Installing: C:/CppTool/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: C:/CppTool/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: C:/CppTool/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: C:/CppTool/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: C:/CppTool/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(889): Value was null
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.

**Comment by Adela0814** [comment] 2023-06-12 07:45
Duplicate of https://github.com/microsoft/vcpkg/issues/31908.

**Closed** 2023-06-14 02:49 UTC
Labels: category:vcpkg-bug
