### ISSUE TITLE
vcpkg downloading MinGW 32bit on a 64bit system

### ISSUE THREAD

**Issue by luizfernandonb** [microsoft/vcpkg#18275] opened 2021-06-05 01:15 UTC
**Describe the bug**
I installed the `libwebsockets` library and when it came to installing the `pthread` library, vcpkg downloaded a 32-bit (i686) version of MinGW, so I set my VCPKG_DEFAULT_TRIPLET to 64-bit

**Environment**
- OS: Windows 10 21H1
- Compiler: Idk

**To Reproduce**
1. ./vcpkg install libwebsockets
2. See vcpkg log

**Expected behavior**
MinGW to be downloaded in 64-bit version

**Log** 
```Building package pthreads[core]:x64-windows... done
Installing package pthreads[core]:x64-windows...
Installing package pthreads[core]:x64-windows... done
Elapsed time for package pthreads:x64-windows: 1.356 min
Starting package 4/5: zlib:x64-windows
Building package zlib[core]:x64-windows...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz -> zlib1211.tar.gz...
-- Extracting source E:/vcpkg-2021.05.12/downloads/zlib1211.tar.gz
-- Applying patch cmake_dont_build_more_than_needed.patch
-- Applying patch 0001-Prevent-invalid-inclusions-when-HAVE_-is-set-to-0.patch
-- Applying patch add_debug_postfix_on_mingw.patch
-- Applying patch 0002-android-build-mingw.patch
-- Using source at E:/vcpkg-2021.05.12/buildtrees/zlib/src/1.2.11-e9a093319e.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- HERE: Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst -> msys-mingw-w64-i686-pkg-config-0.29.2-2-any.pkg.tar.zst...
-- Downloading https://repo.msys2.org/mingw/i686/mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst -> msys-mingw-w64-i686-libwinpthread-git-8.0.0.5906.c9a21571-1-any.pkg.tar.zst...
-- Using msys root at E:/vcpkg-2021.05.12/downloads/tools/msys2/50864d9fae363d6e
-- Fixing pkgconfig file: E:/vcpkg-2021.05.12/packages/zlib_x64-windows/lib/pkgconfig/zlib.pc
-- Fixing pkgconfig file: E:/vcpkg-2021.05.12/packages/zlib_x64-windows/debug/lib/pkgconfig/zlib.pc
-- Installing: E:/vcpkg-2021.05.12/packages/zlib_x64-windows/share/zlib/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\luizf\AppData\Local\vcpkg\archives\3f\3fde6987f5771213867ce8cca603b7caf0ebceb6.zip
```

**Additional context**
MinGW has a repository folder for 64-bit systems

Last line:
![image](https://user-images.githubusercontent.com/42288418/120875460-5193e780-c582-11eb-934c-013532225b97.png)

**Comment by ras0219-msft** [comment] 2021-06-05 02:06
This is by design because the x86 version of MSYS2 will work on all windows systems (x86, x64, and arm64) instead of needing to separately test and evaluate the "native" versions. These packages are only used during the build process, so they are not affected by your target triplet.

Thanks for posting this issue!

**Comment by luizfernandonb** [comment] 2021-06-05 03:47
> This is by design because the x86 version of MSYS2 will work on all windows systems (x86, x64, and arm64) instead of needing to separately test and evaluate the "native" versions. These packages are only used during the build process, so they are not affected by your target triplet.
> 
> Thanks for posting this issue!

Will the use of MinGW i686 generate an x86 library or does it not influence? Because if it does, it might be a mistake to use only the x86 version of MinGW

**Comment by dg0yt** [comment] 2021-06-05 04:37
IIRC only `pkg-config` is always downloaded in 32 bit. As long as it is not added to the `PATH`, this seems to be work well enough, at least until either the pkg-config or pkgconf ports are merged and used.

**Comment by NancyLi1013** [comment] 2021-06-28 07:59
I think this issue has been clarified now. So closing this issue.

**Closed by NancyLi1013** 2021-06-28 07:59 UTC
Labels: category:question
