### ISSUE TITLE
Can not access to server

### ISSUE THREAD

**Issue by NanFeng009** [Microsoft/vcpkg#2379] opened 2017-12-15 03:09 UTC
I can download the file from chrome successfully. but vcpkg report failure. please check output as below.

C:\src\vcpkg>vcpkg install cpprestsdk cpprestsdk:x64-windows
The following packages will be built and installed:
  * boost[core]:x86-windows
  * boost[core]:x64-windows
  * bzip2[core]:x86-windows
  * bzip2[core]:x64-windows
    cpprestsdk[core]:x86-windows
    cpprestsdk[core]:x64-windows
  * openssl[core]:x86-windows
  * openssl[core]:x64-windows
  * websocketpp[core]:x86-windows
  * websocketpp[core]:x64-windows
  * zlib[core]:x86-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/12: zlib:x86-windows
Building package zlib:x86-windows...
-- CURRENT_INSTALLED_DIR=C:/src/vcpkg/installed/x86-windows
-- DOWNLOADS=C:/src/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/src/vcpkg/packages/zlib_x86-windows
-- CURRENT_BUILDTREES_DIR=C:/src/vcpkg/buildtrees/zlib
-- CURRENT_PORT_DIR=C:/src/vcpkg/ports/zlib/.
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz...
-- Downloading http://www.zlib.net/zlib-1.2.11.tar.gz... Failed. Status: 7;"Couldn't connect to server"
-- Downloading https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz...
-- Downloading https://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz... Failed. Status: 7;"Couldn't connect to server"

**Comment by ras0219-msft** [comment] 2017-12-21 07:54
Thanks for posting this issue!

If you have a proxy, you may need to set the `HTTP_PROXY` and `HTTPS_PROXY` environment variables, because CMake uses curl internally to perform the download: https://stackoverflow.com/questions/24657501/proxy-settings-for-windows-7-command-prompt

**Comment by NancyLi1013** [comment] 2019-03-22 09:58
@NanFeng009 , this issue should be fixed now. And I cannot reproduce it on my machine. 
Please open a new issue if this is still a problem for you.

**Closed by NancyLi1013** 2019-03-22 09:58 UTC
Labels: needs-repro
