### ISSUE TITLE
With English Language Pack installed, still cannot find "suitable Visual Studio instances"

### ISSUE THREAD

**Issue by 2catycm** [microsoft/vcpkg#29127] opened 2023-01-23 02:29 UTC
**Describe the bug**
vcpkg seems doesn't recognize Visual Studio 2022 on WIndows 11. 

**Environment**
- OS: 版本	Windows 11 专业版
版本	22H2
安装日期	‎2022/‎12/‎7
操作系统版本	22623.1020
体验	Windows Feature Experience Pack 1000.22638.1000.0

- Compiler: 
![image](https://user-images.githubusercontent.com/41530341/213956141-269366d2-7a0b-4314-b251-00a784dc2993.png)

**To Reproduce**
1. install VS2022 on Win11 with different location than C:\, with Chinese and English Language Pack installed。 
2. ./vcpkg install opencv4:x64-windows

3. See error
![image](https://user-images.githubusercontent.com/41530341/213956313-81bb5dfa-a479-417e-b84b-6b8d586b0d35.png)

**Expected behavior**
It should find the VS2022.
In sites like stackoverflow, people says the most common case that vcpkg cannot find VS is that the English Language pack is not installed. however，vcpkg should report a warning on the ouput log in that situation. 

**Failure logs**
```log
Computing installation plan...
The following packages will be built and installed:
  * libjpeg-turbo[core]:x64-windows -> 2.0.6
  * liblzma[core]:x64-windows -> 5.2.5#2
  * libpng[core]:x64-windows -> 1.6.37#14
  * libwebp[core,nearlossless,simd,unicode]:x64-windows -> 1.1.0#1
    opencv4[core,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.5.1
  * protobuf[core]:x64-windows -> 3.14.0#1
  * quirc[core]:x64-windows -> 1.1#2
  * tiff[core]:x64-windows -> 4.1.0#1
  * zlib[core]:x64-windows -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
No suitable Visual Studio instances were found
```

**Additional context**

**Comment by MonicaLiu0311** [comment] 2023-01-28 07:38
I'm sorry that I can't reproduce your issue. Please uninstall the Chinese language pack, set [VCPKG_VISUAL_STUDIO_PATH](https://github.com/microsoft/vcpkg/blob/master/docs/users/triplets.md#vcpkg_visual_studio_path), and try again.

**Comment by MonicaLiu0311** [comment] 2023-01-28 07:42
Duplicate of https://github.com/microsoft/vcpkg/issues/25986.

**Closed by MonicaLiu0311** 2023-01-28 07:42 UTC
Labels: category:question
