### ISSUE TITLE
FindProj not working as expected

### ISSUE THREAD

**Issue by mathisloge** [microsoft/vcpkg#16906] opened 2021-03-26 15:55 UTC
so i've got a problem at #14628 .
Proj is currently at version 7.2.0 and it should be supported as stated in https://proj.org/development/cmake.html to use `find_package(PROJ REQUIRED)` however when i'm using it like that I'm getting the following error: 
```
CMake Error at D:/dev/vcpkg_mapnik/scripts/buildsystems/vcpkg.cmake:861 (_find_package):
  By not providing "FindPROJ.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PROJ", but
  CMake did not find one.

  Could not find a package configuration file provided by "PROJ" with any of
  the following names:

    PROJConfig.cmake
    proj-config.cmake

  Add the installation prefix of "PROJ" to CMAKE_PREFIX_PATH or set
  "PROJ_DIR" to a directory containing one of the above files.  If "PROJ"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  cmake/MapnikFindPackage.cmake:18 (find_package)
  CMakeLists.txt:209 (mapnik_find_package)

```
If I'm building proj without vcpgk this will work, so there have to be a bug in the portfile of proj?

**Comment by JackBoosY** [comment] 2021-03-30 06:31
We prefer you to use the following cmake code instead:
```
    find_package(proj4 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE PROJ::proj PROJ4::proj)
```

**Comment by mathisloge** [comment] 2021-03-30 07:25
This isn't quite the solution. Since proj has deprecated this and the project (mapnik) has a requirement on proj >=7.

I think that this should be fixed in vcpkg since the file itself is present but not working. 

If this will not be fixed, I need to create a fix in the port of mapnik.

**Comment by rhuijben** [comment] 2021-04-02 09:09
The update to 8.0.0 won't fix the problem as far as I can't tell. The problem is that the proj project dropped the 4 from its name, while vcpkg aliases proj to proj4 as that was how it used to be called.

The library was called proj4 for 20 years as it was incompatible with proj 1.0-3.x, but since then a few new versions were released with a new major number, as the project started using *semver*.

**Comment by JackBoosY** [comment] 2021-04-02 09:56
So we should add a cmake wrapper to avoid this.

**Comment by rhuijben** [comment] 2021-04-02 10:59
Not sure... I would prefer vcpkg to switch the dependency the other way around... Use proj4 as legacy name and use proj going forward, but I'm not sure who's decision this would be.

I could create a patch for the name change, but I'm not sure if something like that would be accepted. I would say the decision on how the backing project is called is at the project itself, not the packaging system. But then there could be collisions... Not sure.

**Comment by mathisloge** [comment] 2021-04-02 18:49
I would also prefer proj since proj itself deprecated that name.
https://proj.org/faq.html#what-happened-to-proj-4

**Comment by JackBoosY** [comment] 2021-08-03 00:46
And I've made a patch to fix this, see https://github.com/microsoft/vcpkg/pull/19298/commits/864a20b07ffb49c84b7df680cfac958c913d2819.

**Comment by dg0yt** [comment] 2021-08-03 04:23
> I would also prefer proj since proj itself deprecated that name.

@JackBoosY In case of misunderstanding: This refers to the port name in vcpkg. It does not refer to exported cmake target names!

**Comment by mathisloge** [comment] 2021-08-03 06:57
> > I would also prefer proj since proj itself deprecated that name.
> 
> @JackBoosY In case of misunderstanding: This refers to the port name in vcpkg. It does not refer to exported cmake target names!

It also refers to the export name (PROJ4) won't be used anymore. So we definitely need PROJ. But the above quoted comment wasn't meant to add a lower case target. Only the (from proj itself exported target) PROJ

**Closed** 2021-08-10 00:30 UTC
Labels: category:port-feature, category:port-update
