### ISSUE TITLE
[brotli] Build error

### ISSUE THREAD

**Issue by memuratozturk** [microsoft/vcpkg#23246] opened 2022-02-23 18:10 UTC
I tried and I get that error on my windows 10 latest update pc.

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+brotli
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[brotli]+Build+error
including:
  package: brotli[core]:x64-windows -> 1.0.9#2
    vcpkg-tool version: 2022-02-11-dac008bf9b55ef48e10bcc81e273b97a82bbf72d
    vcpkg-scripts version: daa7215f3 2022-02-22 (19 hours ago)

Additionally, attach any relevant sections from the log files above.

**Comment by JonLiu1993** [comment] 2022-02-24 01:40
Duplicate of #23245 , let's track this issue in pr #23245

**Closed by JonLiu1993** 2022-02-24 01:40 UTC
Labels: requires:more-information
