### ISSUE TITLE
[tiff] build failure

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#30537] opened 2023-03-30 06:21 UTC
Package: tiff[core,jpeg,lzma,zip]:x64-windows -> 4.5.0#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.35.32216.1
-    vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
    vcpkg-scripts version: d10d511f2 2023-03-29 (7 hours ago)

**To Reproduce**

`vcpkg install ffmpeg[all-nonfree]:x64-windows`

**Failure logs**

```
-- Downloading https://gitlab.com/libtiff/libtiff/-/archive/v4.5.0/libtiff-v4.5.0.tar.gz -> libtiff-libtiff-v4.5.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://gitlab.com/libtiff/libtiff/-/archive/v4.5.0/libtiff-v4.5.0.tar.gz
[DEBUG] Trying to hash C:\vcpkg\downloads\libtiff-libtiff-v4.5.0.tar.gz.5288.part
[DEBUG] C:\vcpkg\downloads\libtiff-libtiff-v4.5.0.tar.gz.5288.part has hash e45a0eb3229349db7d4707e8dd3557b1a744fd307820c40e70f598a2642e4122d98fcda660306ae8b3f9a49ea13dba55429d22b37dbc96e9038411310db56fc5
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://gitlab.com/libtiff/libtiff/-/archive/v4.5.0/libtiff-v4.5.0.tar.gz
File: C:\vcpkg\downloads\libtiff-libtiff-v4.5.0.tar.gz.5288.part
Expected hash: 5227cb7b496ac6829601d8d689233bd8f318c1d04e5ce3457cdd6eac9e4f8c80cd7211d90cd092c61ad38bc8a4949169a13eabd788c46c15bcee1f72519fa022
Actual hash: e45a0eb3229349db7d4707e8dd3557b1a744fd307820c40e70f598a2642e4122d98fcda660306ae8b3f9a49ea13dba55429d22b37dbc96e9038411310db56fc5
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(960): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 11us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 1240us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 16.4124879 s (16386516us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_gitlab.cmake:118 (vcpkg_download_distfile)
  ports/tiff/portfile.cmake:3 (vcpkg_from_gitlab)
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by MonicaLiu0311** [comment] 2023-03-30 06:54
Duplicate of https://github.com/microsoft/vcpkg/issues/30481

**Closed by MonicaLiu0311** 2023-03-30 06:54 UTC
Labels: category:question
