### ISSUE TITLE
[jasper] build failure

### ISSUE THREAD

**Issue by tqjxlm** [microsoft/vcpkg#15035] opened 2020-12-10 06:54 UTC
**Host Environment**
- OS: Windows
- Compiler: Visual Studio 2019

**To Reproduce**
`./vcpkg install jasper:x64-windows`

**Failure logs** 
```
[52/54] C:\PROGRA~2\MICROS~2\2019\PROFES~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe   -DJAS_BUILDING_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_GNU_SOURCE -Isrc\libjasper\include -ID:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\include -ID:\Tmp\vcpkg\installed\x64-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c11 /showIncludes /Fosrc\libjasper\CMakeFiles\libjasper.dir\base\jas_stream.c.obj /Fdsrc\libjasper\CMakeFiles\libjasper.dir\ /FS -c D:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\base\jas_stream.c
FAILED: src/libjasper/CMakeFiles/libjasper.dir/base/jas_stream.c.obj 
C:\PROGRA~2\MICROS~2\2019\PROFES~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\cl.exe   -DJAS_BUILDING_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_GNU_SOURCE -Isrc\libjasper\include -ID:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\include -ID:\Tmp\vcpkg\installed\x64-windows\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c11 /showIncludes /Fosrc\libjasper\CMakeFiles\libjasper.dir\base\jas_stream.c.obj /Fdsrc\libjasper\CMakeFiles\libjasper.dir\ /FS -c D:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\base\jas_stream.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\stdio.h(378): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\stdio.h(2437): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\corecrt_memory.h(76): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\corecrt_wstring.h(573): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\string.h(531): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\corecrt_search.h(188): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\stdlib.h(79): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\stdlib.h(1286): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\ctype.h(224): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\ucrt\corecrt_io.h(435): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\winbase.h(9200): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(487): warning C5103: pasting '/' and '/' does not result in a valid preprocessing token
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared\wtypes.h(745): note: in expansion of macro '_VARIANT_BOOL'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(487): error C2059: syntax error: '/'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(502): warning C5103: pasting '/' and '/' does not result in a valid preprocessing token
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared\wtypes.h(745): note: in expansion of macro '_VARIANT_BOOL'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(502): error C2059: syntax error: '/'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(529): warning C4094: untagged 'struct' declared no symbols
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(530): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(531): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(533): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(534): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(665): error C2079: 'varDefaultValue' uses undefined struct 'tagVARIANT'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(950): error C2079: 'varValue' uses undefined struct 'tagVARIANT'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\propidlbase.h(319): warning C5103: pasting '/' and '/' does not result in a valid preprocessing token
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\shared\wtypes.h(745): note: in expansion of macro '_VARIANT_BOOL'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\propidlbase.h(319): error C2059: syntax error: '/'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\propidlbase.h(378): error C2371: 'pvarVal': redefinition; different basic types
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\oaidl.h(510): note: see declaration of 'pvarVal'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\propidlbase.h(379): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\propidlbase.h(380): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\propidlbase.h(383): error C2059: syntax error: '}'
C:\Program Files (x86)\Windows Kits\10\include\10.0.17134.0\um\propidlbase.h(384): error C2059: syntax error: '}'
D:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\base\jas_stream.c(249): warning C4267: '=': conversion from 'size_t' to 'uint_fast32_t', possible loss of data
D:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\base\jas_stream.c(724): warning C4267: 'function': conversion from 'size_t' to 'unsigned int', possible loss of data
D:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\base\jas_stream.c(936): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
D:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\base\jas_stream.c(1074): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
D:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\base\jas_stream.c(1257): warning C4267: '=': conversion from 'size_t' to 'unsigned int', possible loss of data
D:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\base\jas_stream.c(1322): warning C4267: '+=': conversion from 'size_t' to 'uint_fast32_t', possible loss of data
D:\Tmp\vcpkg\buildtrees\jasper\src\2a853d25d7-8a915d701e.clean\src\libjasper\base\jas_stream.c(1330): warning C4267: 'initializing': conversion from 'size_t' to 'unsigned int', possible loss of data
ninja: build stopped: subcommand failed.
```

**Comment by JonLiu1993** [comment] 2020-12-10 07:45
@tqjxlm ,Thanks for posting this issue,Can you create a folder on a non-C drive and reinstall vcpkg to try it? I cannot reproduce your issue on windows 10
![Capture](https://user-images.githubusercontent.com/63675417/101736666-bc49f600-3afe-11eb-8bbc-954beef679e6.PNG)

**Comment by tqjxlm** [comment] 2020-12-10 09:07
@JonLiu1993 

In fact it's not on the C drive. There's more output if it is helpful

log file:
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5671525/install-x64-windows-dbg-out.log)

commandline:
D:\Tmp\vcpkg>.\vcpkg.exe install jasper:x64-windows
Computing installation plan...
The following packages will be built and installed:
    jasper[core]:x64-windows -> 2.0.20
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\tqjxlm\AppData\Local\vcpkg\archives\ba\ba535b3d845291a5cfe34ac3917ede9613eab611.zip
Starting package 1/1: jasper:x64-windows
Building package jasper[core]:x64-windows...
-- Using cached D:/Tmp/vcpkg/downloads/mdadams-jasper-d10a710f31da3d079a984d35ff6cc82a853d25d7.tar.gz
-- Cleaning sources at D:/Tmp/vcpkg/buildtrees/jasper/src/2a853d25d7-8a915d701e.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Tmp/vcpkg/downloads/mdadams-jasper-d10a710f31da3d079a984d35ff6cc82a853d25d7.tar.gz
-- Using source at D:/Tmp/vcpkg/buildtrees/jasper/src/2a853d25d7-8a915d701e.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: D:/Tmp/vcpkg/downloads/tools/cmake-3.18.4-windows/cmake-3.18.4-win32-x86/bin/cmake.exe --build . --config Debug --target install -- -v -j65
    Working Directory: D:/Tmp/vcpkg/buildtrees/jasper/x64-windows-dbg
    See logs for more information:
      D:\Tmp\vcpkg\buildtrees\jasper\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:27 (vcpkg_build_cmake)
  ports/jasper/portfile.cmake:28 (vcpkg_install_cmake)
  scripts/ports.cmake:136 (include)


Error: Building package jasper:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: jasper:x64-windows
  Vcpkg version: 2020.11.12-nohash

**Comment by Cheney-W** [comment] 2020-12-10 10:22
@tqjxlm 
This issue should be fixed in Windows SDK 10.0.18362.0 and later versions. please update the version of your Windows SDK.

**Comment by kossiBlaise** [comment] 2021-02-14 01:27
Hello,

Updating to the newest version of Powershell solved my build problem.

Cheers,

**Comment by JonLiu1993** [comment] 2021-09-16 02:46
@tqjxlm ,Does this problem still exist?

**Comment by JonLiu1993** [comment] 2021-09-28 08:27
Thanks for posting this issue. Please reopen this issue if it still be a problem for you.

**Closed by JonLiu1993** 2021-09-28 08:27 UTC
Labels: requires:repro

**Comment by oneThousand1000** [comment] 2022-03-16 13:24
I have installed the Windows SDK 10.0.19041.0 but I met the same problem`oaidl.h(487): error C2059: syntax error: '/'`, downgrading Windows SDK to 10.0.18362.0 solved my problem.
