### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by poisonousfire** [microsoft/vcpkg#36006] opened 2024-01-03 07:26 UTC
Package: openssl:x64-windows@3.2.0#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.38.33133.0
-    vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install openssl:x64-windows`
**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.2.0.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/openssl/src/nssl-3.2.0-06d693f20a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/openssl-openssl-openssl-3.2.0.tar.gz
-- Applying patch asm-comments.patch
-- Applying patch declspec-align.patch
-- Applying patch qt-msvc.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at D:/vcpkg/buildtrees/openssl/src/nssl-3.2.0-06d693f20a.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "D:/Visual Studio/IDE/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: D:/vcpkg/buildtrees/openssl/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log
      D:\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:69 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:77 (include)
  scripts/ports.cmake:170 (include)



```
<details><summary>D:\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log</summary>

```
cl: 命令行 warning D9025 :正在重写“/Zi”(用“/Z7”)
NMAKE : fatal error U1077: ��"D:\Visual Studio\IDE\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"D:\\vcpkg\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"D:\\vcpkg\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"D:\\vcpkg\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c"��: ���ش��롰0x2��
Stop.
NMAKE : fatal error U1077: ��"D:\Visual Studio\IDE\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs��: ���ش��롰0x2��
Stop.
```
</details>

<details><summary>D:\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log</summary>

```
	"D:\Visual Studio\IDE\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 depend
	"D:\Visual Studio\IDE\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs
	"D:\Visual Studio\IDE\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"D:\\vcpkg\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"D:\\vcpkg\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"D:\\vcpkg\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c"
cversion.c
crypto\cversion.c(60): warning C4129: “I”: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “V”: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “T”: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “M”: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “H”: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “c”: 不可识别的字符转义序列
crypto\cversion.c(60): error C2143: 语法错误: 缺少“;”(在“常数”的前面)
crypto\cversion.c(60): error C2143: 语法错误: 缺少“;”(在“字符串”的前面)
```
</details>

**Comment by Adela0814** [comment] 2024-01-03 08:11
Duplicate of https://github.com/microsoft/vcpkg/issues/32787.

**Closed** 2024-01-03 08:15 UTC
Labels: requires:repro
