### ISSUE TITLE
Initial download of cmake fails behind a proxy server

### ISSUE THREAD

**Issue by frederich** [Microsoft/vcpkg#125] opened 2016-10-07 11:21 UTC
I've tried vcpkg on a system with web-proxy. vcpkg cannot install boost, downloading cmake failed, see below. It works fine on a system without web-proxy.

```
D:\TEMP\vcpkg>vcpkg install boost

Download cmake
No suitable version of cmake was found (requires 3.5.0 or higher). Download
portable version?
[Y] Yes  [N] No  [A] Always Allow Downloads  [?] Hilfe (Standard ist "Y"):
Ausnahme beim Aufrufen von "ReadAllBytes" mit 1 Argument(en):  "Die Datei "D:\T
EMP\vcpkg\downloads\cmake-3.5.2-win32-x86.zip" konnte nicht gefunden werden."
Bei D:\TEMP\vcpkg\scripts\fetchDependency.ps1:163 Zeichen:47
+     $fileAsByteArray = [io.File]::ReadAllBytes <<<< ($downloadPath)
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DotNetMethodException

Es wurden mehrere nicht eindeutige Überladungen gefunden für "ComputeHash" und
die Argumentanzahl: "1".
Bei D:\TEMP\vcpkg\scripts\fetchDependency.ps1:164 Zeichen:48
+     $hashByteArray = $hashAlgorithm.ComputeHash <<<< ($fileAsByteArray)
    + CategoryInfo          : NotSpecified: (:) [], MethodException
    + FullyQualifiedErrorId : MethodCountCouldNotFindBest

Mismatching hash of the downloaded cmake
Bei D:\TEMP\vcpkg\scripts\fetchDependency.ps1:169 Zeichen:14
+         throw <<<<  [System.IO.FileNotFoundException] ("Mismatching hash of t
he downloaded " + $Dependency)
    + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
    + FullyQualifiedErrorId : Mismatching hash of the downloaded cmake

Launching powershell failed or was denied
```

**Comment by ras0219-msft** [comment] 2016-10-07 19:47
Duplicate of #101. Thanks for reporting this!

**Comment by ras0219-msft** [comment] 2016-10-11 11:47
Looking more closely, this isn't a duplicate! For the initial download of CMake we use BITS, which should pick up your Internet Explorer proxy settings.

https://msdn.microsoft.com/en-us/library/windows/desktop/aa362783(v=vs.85).aspx

Let us know if setting the IE proxy settings doesn't fix the issue!

**Closed by ras0219-msft** 2016-10-11 11:47 UTC
Labels: vcpkg feature
