### ISSUE TITLE
[python3] Build error on x64-linux

### ISSUE THREAD

**Issue by afpgit** [microsoft/vcpkg#41226] opened 2024-09-27 23:02 UTC
Package: python3:x64-linux@3.11.8#4

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.2.1
-    vcpkg-tool version: 2024-09-18-5f5da308dd1dd3cc49641c60eafff176e248a9dd
    vcpkg-scripts version: 0affe8710 2024-09-26 (32 hours ago)

**To Reproduce**

`vcpkg install boost:x64-linux`

**Failure logs**

```
CMake Warning at ports/python3/portfile.cmake:7 (message):
  python3 currently requires the following programs from the system package
  manager:

      autoconf automake autoconf-archive

  On Debian and Ubuntu derivatives:

      sudo apt-get install autoconf automake autoconf-archive

  On recent Red Hat and Fedora derivatives:

      sudo dnf install autoconf automake autoconf-archive

  On Arch Linux and derivatives:

      sudo pacman -S autoconf automake autoconf-archive

  On Alpine:

      apk add autoconf automake autoconf-archive

  On macOS:

      brew install autoconf automake autoconf-archive

Call Stack (most recent call first):
  scripts/ports.cmake:192 (include)


-- Using cached python-cpython-v3.11.8.tar.gz.
-- Cleaning sources at /root/programs/vcpkg/buildtrees/python3/src/v3.11.8-fe0ac5827a.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source /root/programs/vcpkg/downloads/python-cpython-v3.11.8.tar.gz
-- Applying patch 0001-only-build-required-projects.patch
-- Applying patch 0003-use-vcpkg-zlib.patch
-- Applying patch 0004-devendor-external-dependencies.patch
-- Applying patch 0005-dont-copy-vcruntime.patch
-- Applying patch 0008-python.pc.patch
-- Applying patch 0010-dont-skip-rpath.patch
-- Applying patch 0012-force-disable-modules.patch
-- Applying patch 0014-fix-get-python-inc-output.patch
-- Applying patch 0015-dont-use-WINDOWS-def.patch
-- Applying patch 0016-undup-ffi-symbols.patch
-- Applying patch 0018-fix-sysconfig-include.patch
-- Applying patch 0002-static-library.patch
-- Applying patch 0011-gcc-ldflags-fix.patch
-- Using source at /root/programs/vcpkg/buildtrees/python3/src/v3.11.8-fe0ac5827a.clean
-- Found external ninja('1.12.1').
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: /usr/local/bin/autoreconf -vfi
    Working Directory: /root/programs/vcpkg/buildtrees/python3/src/v3.11.8-fe0ac5827a.clean/
    Error code: 1
    See logs for more information:
      /root/programs/vcpkg/buildtrees/python3/autoconf-x64-linux-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:731 (vcpkg_execute_required_process)
  ports/python3/portfile.cmake:274 (vcpkg_configure_make)
  scripts/ports.cmake:192 (include)



```

<details><summary>/root/programs/vcpkg/buildtrees/python3/autoconf-x64-linux-err.log</summary>

```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: /usr/local/bin/autoconf --force
configure.ac:1: error: possibly undefined macro: dnl
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:18: error: possibly undefined macro: AC_MSG_ERROR
configure.ac:53: error: possibly undefined macro: AS_VAR_IF
configure.ac:60: error: possibly undefined macro: AC_DEFINE
configure.ac:81: error: possibly undefined macro: AC_CHECK_LIB
configure.ac:292: error: possibly undefined macro: AS_CASE
configure.ac:2685: error: possibly undefined macro: AC_CHECK_HEADERS
configure.ac:3474: error: possibly undefined macro: AC_SEARCH_LIBS
autoreconf: error: /usr/local/bin/autoconf failed with exit status: 1
```
</details>

<details><summary>yum list installed autoconf automake libtool gettext-devel m4 autoconf-archive pkgconfig</summary>

```

[root@S210-L112-002 vcpkg]# yum list installed autoconf automake libtool gettext-devel m4 autoconf-archive pkgconfig
Loaded plugins: fastestmirror
Repository centos-sclo-rh is listed more than once in the configuration
Repository centos-sclo-sclo is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * epel: d2lzkl7pfhq30w.cloudfront.net
Installed Packages
autoconf.noarch                   2.69-11.el7                   @base
autoconf-archive.noarch           2017.03.21-1.el7              @base
automake.noarch                   1.13.4-3.el7                  @base
gettext-devel.x86_64              0.19.8.1-3.el7                @base
libtool.x86_64                    2.4.2-22.el7_3                @base
m4.x86_64                         1.4.16-10.el7                 @base
pkgconfig.x86_64                  1:0.27.1-4.el7                installed
```

</details>

**Comment by Osyotr** [comment] 2024-09-27 23:12
Duplicate of #41223

**Closed** 2024-09-29 01:47 UTC
