### ISSUE TITLE
[openssl:x86] build failure

### ISSUE THREAD

**Issue by purpleguy31** [microsoft/vcpkg#11783] opened 2020-06-04 22:42 UTC
**Host Environment**
- OS: Windows 10 Home version 1909
- vcpkg version: 2020.02.04-nohash

**To Reproduce**
`vcpkg install openssl:x86-windows`

**Failure logs** 
```
Computing installation plan...
The following packages will be built and installed:
    openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: openssl-windows:x86-windows
Building package openssl-windows[core]:x86-windows...
-- Using cached D:/vcpkg/downloads/strawberry-perl-5.30.0.1-32bit.zip
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/vcpkg/downloads/strawberry-perl-5.30.0.1-32bit.zip
-- Using cached D:/vcpkg/downloads/openssl-1.1.1d.tar.gz
-- Using source at D:/vcpkg/buildtrees/openssl-windows/src/openssl-1-b1f8ae3e6c
-- Using cached D:/vcpkg/downloads/jom_1_1_3.zip
CMake Error: Problem with archive_write_finish_entry(): Can't restore time
CMake Error: Problem extracting tar: D:/vcpkg/downloads/jom_1_1_3.zip
-- Copying openssl release source files...
-- Copying openssl release source files... done
-- Configure x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: PERL-NOTFOUND Configure enable-static-engine enable-capieng no-ssl2 -utf-8 shared VC-WIN32 --prefix=D:/vcpkg/packages/openssl-windows_x86-windows --openssldir=D:/vcpkg/packages/openssl-windows_x86-windows -FS
    Working Directory: D:/vcpkg/buildtrees/openssl-windows/x86-windows-rel
    Error code: The system cannot find the file specified
    See logs for more information:

Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:77 (vcpkg_execute_required_process)
  scripts/ports.cmake:76 (include)
```
**Additional Context**
I encountered this issue when trying to install any package that involved extracting from a .zip file. (for instance installing libepoxy will do the same )
All of the error log files were empty

**Comment by LilyWangL** [comment] 2020-06-09 09:14
Thanks for posting this issue. Closed as duplicate of #11775.

**Closed by LilyWangL** 2020-06-09 09:14 UTC
Labels: requires:repro
