### ISSUE TITLE
[gmp] Build error vcpkg install GCAL

### ISSUE THREAD

**Issue by Davidleeeeee** [microsoft/vcpkg#28944] opened 2023-01-14 02:50 UTC
**Host Environment**

- OS: windows10
- Compiler: 
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: 6adca01a3 2022-12-22 (3 weeks ago)

**To Reproduce**

`./vcpkg install GCAL`

**Failure logs**
Downloading https://mirror.selfnet.de/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz
Downloading https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz
error: Failed to download from mirror set
error: https://repo.msys2.org/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://www2.futureware.at/~nickoe/msys2-mirror/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://mirror.yandex.ru/mirrors/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://mirrors.tuna.tsinghua.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://mirrors.ustc.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12030
error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12030
error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12030
error: https://mirror.bit.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: WinHttpSendRequest failed with exit code 12030
error: https://mirror.selfnet.de/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404
error: https://mirrors.sjtug.sjtu.edu.cn/msys2/msys/x86_64/libtool-2.4.6-9-x86_64.pkg.tar.xz: failed: status code 404

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by dpogue** [comment] 2023-01-14 04:14
Duplicate of https://github.com/microsoft/vcpkg/issues/28896
Should be fixed by https://github.com/microsoft/vcpkg/pull/28919

**Closed** 2023-01-16 09:29 UTC
Labels: category:tool-update
