### ISSUE TITLE
[grpc:x86-android] build failure

### ISSUE THREAD

**Issue by ionutcosminmihaipfa** [microsoft/vcpkg#16889] opened 2021-03-25 20:37 UTC
**Host Environment**
- OS: MacOS
- Compiler: Android NDK 23.0.7196353 or 21.1.6352462

**To Reproduce**
`./vcpkg install grpc:x86-android`

**Failure logs** 
```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /Users/someuser/vcpkg/downloads/tools/cmake-3.19.2-osx/cmake-3.19.2-macos-universal/CMake.app/Contents/bin/cmake --build . --config Debug --target install -- -v -j17
    Working Directory: /Users/someuser/vcpkg/buildtrees/grpc/x86-android-dbg
    See logs for more information:
      /Users/someuser/vcpkg/buildtrees/grpc/install-x86-android-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/grpc/portfile.cmake:69 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)


Error: Building package grpc:x86-android failed with: BUILD_FAILED
```

```
[894/909] cd /Users/someuser/vcpkg/buildtrees/grpc/src/9d5d76bc12-fad544a798.clean && /Users/someuser/vcpkg/installed/x86-android/tools/protobuf/protoc --grpc_out=generate_mock_code=true:/Users/someuser/vcpkg/buildtrees/grpc/x86-android-dbg/gens --cpp_out=/Users/someuser/vcpkg/buildtrees/grpc/x86-android-dbg/gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin -I . -I /Users/someuser/vcpkg/installed/x86-android/include src/proto/grpc/channelz/channelz.proto
FAILED: gens/src/proto/grpc/channelz/channelz.grpc.pb.cc gens/src/proto/grpc/channelz/channelz.grpc.pb.h gens/src/proto/grpc/channelz/channelz_mock.grpc.pb.h gens/src/proto/grpc/channelz/channelz.pb.cc gens/src/proto/grpc/channelz/channelz.pb.h 
cd /Users/someuser/vcpkg/buildtrees/grpc/src/9d5d76bc12-fad544a798.clean && /Users/someuser/vcpkg/installed/x86-android/tools/protobuf/protoc --grpc_out=generate_mock_code=true:/Users/someuser/vcpkg/buildtrees/grpc/x86-android-dbg/gens --cpp_out=/Users/someuser/vcpkg/buildtrees/grpc/x86-android-dbg/gens --plugin=protoc-gen-grpc=/usr/local/bin/grpc_cpp_plugin -I . -I /Users/someuser/vcpkg/installed/x86-android/include src/proto/grpc/channelz/channelz.proto
/bin/sh: /Users/someuser/vcpkg/installed/x86-android/tools/protobuf/protoc: cannot execute binary file
ninja: build stopped: subcommand failed.
```

**Comment by autoantwort** [comment] 2021-03-25 22:20
The problem is that it tries to execute a android binary on macOS. So we first have to compile for the host platform. This will be fixed by #16479

**Comment by ionutcosminmihaipfa** [comment] 2021-03-26 13:27
Thank you, I mention that using the changes in the above mentioned PR, there is a linking error related to glibc for the x64-android triplet(It's reproducing on Windows/Linux/MacOS): 
ld: error: undefined symbol: memcpy@GLIBC_2.2.5
>>> referenced by string.h:60 (/home/parallels/Android/Sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/bits/fortify/string.h:60)
>>>               CMakeFiles/gpr.dir/src/core/lib/gpr/wrap_memcpy.cc.o:(__wrap_memcpy)
>>> did you mean: wmemcpy
>>> defined in: /home/parallels/Android/Sdk/ndk/22.1.7171670/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/x86_64-linux-android/21/libc.so
clang++: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by autoantwort** [comment] 2021-03-26 14:16
> there is a linking error related to glibc for the x64-android triplet

Does this error happens before or after the current error? So is this PR an improvement or does it make the situation worse?

**Comment by ionutcosminmihaipfa** [comment] 2021-03-26 14:59
The PR is an improvement, it actually fixes the x86 which is now working and it gets the x64 passed the error coming from using the wrong protoc.

**Comment by ionutcosminmihaipfa** [comment] 2021-03-26 20:19
Should I create a separate issue for the GLIBC problem?

**Comment by JackBoosY** [comment] 2021-03-31 06:10
Is this issue solved?

**Comment by ionutcosminmihaipfa** [comment] 2021-04-01 20:11
Hi, yes for x86-android, for x64-android, I added a separate issue here: https://github.com/microsoft/vcpkg/issues/16961

**Closed** 2021-04-02 04:06 UTC
Labels: category:community-triplet
