### ISSUE TITLE
[libssh2 x86 / x64] build failure

### ISSUE THREAD

**Issue by Christsnatcher** [microsoft/vcpkg#12935] opened 2020-08-16 12:27 UTC
**Host Environment**
- Windows 8.1 x64
- MSVC++ 14.25 Visual Studio 2019

**To Reproduce**
vcpkg install libssh2:x86-windows
or
vcpkg install libssh2:x64-windows

**Failure logs** 
```
D:\Code\Repos\vcpkg>vcpkg install libssh2:x86-windows
Computing installation plan...
The following packages will be built and installed:
    libssh2[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: libssh2:x86-windows
Building package libssh2[core]:x86-windows...
Could not locate cached archive: C:\Users\Daniel\AppData\Local\vcpkg\archives\e9\e9afefb222a7e611dffd07fae8449e589972635c.zip
-- Downloading https://github.com/libssh2/libssh2/archive/42d37aa63129a1b2644bf6495198923534322d64.tar.gz...
-- Extracting source D:/Code/Repos/vcpkg/downloads/libssh2-libssh2-42d37aa63129a1b2644bf6495198923534322d64.tar.gz
-- Applying patch D:/Code/Repos/vcpkg/ports/libssh2/0001-Fix-UWP.patch
-- Using source at D:/Code/Repos/vcpkg/buildtrees/libssh2/src/3534322d64-e9146b9288.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:139 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- /p:VCPkgLocalAppDataDisabled=true /p:UseIntelMKL=No /m
    Working Directory: D:/Code/Repos/vcpkg/buildtrees/libssh2/x86-windows-dbg
    See logs for more information:
      D:\Code\Repos\vcpkg\buildtrees\libssh2\install-x86-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/libssh2/portfile.cmake:22 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package libssh2:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libssh2:x86-windows
  Vcpkg version: 2020.06.15-nohash
```

**Additional context**
I'll only refer to

https://github.com/microsoft/vcpkg/issues/9628 and https://github.com/microsoft/vcpkg/issues/12934

as this is just another example of the general vcpkg bug / issue / problem with building on non-Windows 10 pcs. The numbers of failing ports rise as we can see, and in my opinion it's about time to find and fix the actual culprit. Thank you.

[libssh2.zip](https://github.com/microsoft/vcpkg/files/5080624/libssh2.zip)

**Comment by linquize** [comment] 2020-08-16 12:54
What windows SDK version installed?

**Comment by Christsnatcher** [comment] 2020-08-16 13:22
10.0.10150.0
10.0.10240.0
10.0.10586.0
8.1

But this doesn't matter. CMake uses by default the SDK to configure which corresponds to the OS if you don't override the value, while vcpkg instructs the compiler to target the latest SDK, which causes the build failures on the three ports I mentioned.

**Comment by Voskrese** [comment] 2020-08-16 13:34
>      4>C:\Program Files (x86)\Windows Kits\8.1\Include\um\winnt.h(5239,1): error C2169: '_InterlockedAdd': intrinsic function, cannot be defined (compiling source file D:\Code\Repos\vcpkg\buildtrees\libssh2\src\3534322d64-e9146b9288.clean\src\openssl.c) [D:\Code\Repos\vcpkg\buildtrees\libssh2\x86-windows-dbg\src\libssh2.vcxproj]

`Windows Kits\8.1  error C2169`

**Comment by sfhacker** [comment] 2020-08-16 14:22
Just downloaded libssh2 and built it from source on Window 10 x64 // MinGW.
No issues at all.

![image](https://user-images.githubusercontent.com/25817529/90336409-1a6a3f00-e01f-11ea-831e-a23ac3a38ab2.png)

There is no need to specify/override anything!

I have read somewhere that we shouldn't install and/or mix several SDKs on the same PC.
Perhaps the OS version has nothing to do with the SDK version?

**Comment by linquize** [comment] 2020-08-16 14:22
Why did vcpkg pick Win 8.1 SDK instead of Win 10 SDK?

**Comment by Christsnatcher** [comment] 2020-08-16 14:41
@sfhacker : Of course it works on Windows 10, and it's not an issue of having multiple SDKs installed.
@linquize : CMake picks the Win 8.1 SDK if I don't override the SYSTEM_VERSION in the portfile, by default apparently as it corresponds to my OS. The compiler then targets the Win 10 SDK, which is the actual problem.
@Voskrese : It works as long as I specify an installed Win 10 SDK and OVERRIDE the default behavior, which is NO actual solution.

**Comment by Voskrese** [comment] 2020-08-16 14:45
as far as I know, your compiler is recommended for windows 10

> MSVC++ 14.25 Visual Studio 2019

MSVC++  14.16 / Win8 ?

**Comment by Christsnatcher** [comment] 2020-08-16 14:47
The compiler works perfectly fine on Win 8.1, never had any issues with it. And maybe I'm totally wrong here and there's nothing you guys can do actually as it's the default behavior of CMake / MSVC, don't know. But then I wonder why 99% of vcpkg ports build just fine?

**Comment by Christsnatcher** [comment] 2020-08-16 14:49
I think I'll just make a test and uninstall the Win 8.1 SDK, let's see what CMake targets then by default. What do you mean?

**Comment by Voskrese** [comment] 2020-08-16 15:08
https://www.google.com/search?client=firefox-b-d&q=_InterlockedAdd

https://developercommunity.visualstudio.com/content/problem/1139955/c-builds-with-windows-sdk-81-fail-after-upgrade-to.html

**Comment by Christsnatcher** [comment] 2020-08-16 20:04
Thank you so much, so finally I know it's neither a port bug nor a tool issue but just MS trying to push Win 10. Will do the changes suggested in the second article asap.

Also, just for information, I removed the Windows 8.1 SDK from my system and all CMake instances failed instantly as they actually are hardcoded to target the SDK version corresponding to the OS version by default.

Again, a big thanks and a huge sorry for all the trouble from me, I'm really grateful!

You can close my three open issues now if you fit.

**Comment by NancyLi1013** [comment] 2020-08-17 06:32
Hi @Christsnatcher 

Thanks for posting this issue. It seems that you have known what caused this problem.
Please let me know if this is still a problem for you. If not, I will close it.

@linquize @Voskrese @sfhacker 
Thanks for joining the discussion about this issue.

**Comment by Christsnatcher** [comment] 2020-08-17 10:25
Hello @NancyLi1013 ,

yes, know everything's clear regarding this matter. It's simply something non-Win 10 users have to live with principally. But, I found this interesting CMake issue on GitLab: https://gitlab.kitware.com/cmake/cmake/-/issues/17992

It basically describes exactly my problem, and the "solution" is implicitly given in "the SDK version selection picks an exact match if available and otherwise the latest SDK available". So I made sure to remove all traces of my Windows 8.1 SDK from the registry (as CMake checks there for available SDKs) and - boom - now everything works perfectly fine, CMake targets by default the highest versioned SDK now, just as the compiler does.

And sure, please close this issue as well as https://github.com/microsoft/vcpkg/issues/9628 and https://github.com/microsoft/vcpkg/issues/12934 (in case they should still be open), thank you very much!

**Comment by NancyLi1013** [comment] 2020-08-18 01:19
@Christsnatcher thank you very much for your information and kindly reminder.

**Closed by NancyLi1013** 2020-08-18 01:19 UTC
Labels: category:question

**Comment by linquize** [comment] 2020-08-18 02:53
The problem is Win 8.1 SDK, not the running windows version
