### ISSUE TITLE
[v8] Build failure on x64-windows

### ISSUE THREAD

**Issue by ethindp** [microsoft/vcpkg#36716] opened 2024-02-12 18:14 UTC
Package: v8:x64-windows@9.1.269.39#6

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.38.33135.0
-    vcpkg-tool version: 2024-01-11-710a3116bbd615864eef5f9010af178034cb9b44
    vcpkg-scripts version: 345ac44ab 2024-02-09 (3 days ago)

**To Reproduce**

`vcpkg install v8[*] sol2 lua[*]`
**Failure logs**

```
-- Found external ninja('1.11.0').
-- Using cached msys2-pkgconf-2.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.026-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.45-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.6-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.5-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.010-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-2-x86_64.pkg.tar.zst.
-- Using msys root at C:/Users/ethin/source/vcpkg/downloads/tools/msys2/65b7e009c675ae7a
-- Using cached C:/Users/ethin/source/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Cleaning sources at C:/Users/ethin/source/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/ethin/source/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Applying patch C:/Users/ethin/source/vcpkg/ports/v8/v8.patch
-- Using source at C:/Users/ethin/source/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean
-- Fetching submodules
-- Generating v8 build files. Please wait...
-- Generating build (x64-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/ethin/source/vcpkg/installed/x64-windows/tools/gn/gn.exe gen C:/Users/ethin/source/vcpkg/buildtrees/v8/x64-windows-dbg "--args=is_component_build=true target_cpu=\"x64\" v8_monolithic=false v8_use_external_startup_data=true use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/c/Users/ethin/source/vcpkg/installed/x64-windows/debug/lib/pkgconfig\""
    Working Directory: C:/Users/ethin/source/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean
    Error code: 1
    See logs for more information:
      C:\Users\ethin\source\vcpkg\buildtrees\v8\generate-x64-windows-dbg-out.log
      C:\Users\ethin\source\vcpkg\buildtrees\v8\generate-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:11 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:35 (z_vcpkg_gn_configure_generate)
  ports/v8/portfile.cmake:150 (vcpkg_gn_configure)
  scripts/ports.cmake:170 (include)



```
<details><summary>C:\Users\ethin\source\vcpkg\buildtrees\v8\generate-x64-windows-dbg-out.log</summary>

```
ERROR at //build/toolchain/win/BUILD.gn:54:3: Script returned non-zero exit code.
  exec_script("../../vs_toolchain.py",
  ^----------
Current dir: C:/Users/ethin/source/vcpkg/buildtrees/v8/x64-windows-dbg/
Command: C:/Users/ethin/source/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe C:/Users/ethin/source/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean/build/vs_toolchain.py copy_dlls C:/Users/ethin/source/vcpkg/buildtrees/v8/x64-windows-dbg Debug x64
Returned 1 and printed out:

Copying C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\dbghelp.dll to C:/Users/ethin/source/vcpkg/buildtrees/v8/x64-windows-dbg\dbghelp.dll...
Copying C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\dbgcore.dll to C:/Users/ethin/source/vcpkg/buildtrees/v8/x64-windows-dbg\dbgcore.dll...

See //BUILD.gn:1195:1: which caused the file to be included.
action("postmortem-metadata") {
^------------------------------
```
</details>

<details><summary>C:\Users\ethin\source\vcpkg\buildtrees\v8\generate-x64-windows-dbg-err.log</summary>

```
C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Traceback (most recent call last):
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 573, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 569, in main
    return commands[sys.argv[1]](*sys.argv[2:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 400, in CopyDlls
    _CopyDebugger(target_dir, target_cpu)
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py", line 433, in _CopyDebugger
    raise Exception('%s not found in "%s"\r\nYou must install'
Exception: api-ms-win-downlevel-kernel32-l2-1-0.dll not found in "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\api-ms-win-downlevel-kernel32-l2-1-0.dll"

You must installWindows 10 SDK version 10.0.19041.0 including the "Debugging Tools for Windows" feature.
Traceback (most recent call last):
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\toolchain\win\setup_toolchain.py", line 311, in <module>
    main()
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\toolchain\win\setup_toolchain.py", line 268, in main
    vc_lib_path = FindFileInEnvList(env, 'LIB', ';', 'msvcrt.lib')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\toolchain\win\setup_toolchain.py", line 209, in FindFileInEnvList
    assert optional, "%s is not found in %s:\n%s\nCheck if it is installed." % (
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
Check if it is installed.
```
</details>

**Comment by ethindp** [comment] 2024-02-12 18:16
It's worth noting that I do have all the dependencies installed. This was tried both inside and outside the x64 Native Tools Command Prompt for VS 2019.

**Comment by StarGate-One** [comment] 2024-02-12 18:54
>Exception: api-ms-win-downlevel-kernel32-l2-1-0.dll not found in "C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\api-ms-win-downlevel-kernel32-l2-1-0.dll"
>You must install Windows 10 SDK version 10.0.19041.0 including the "Debugging Tools for Windows" feature.

Looks like vcpkg cannot find a suitable installed Windows SDK?

**Comment by ethindp** [comment] 2024-02-12 19:00
@StarGate-One That's what it looks like, but I do have it installed, so I'm uncertain why the build tools can't find it.

**Comment by ethindp** [comment] 2024-02-12 20:42
I just reinstalled the windows SDKs and ensured that all the features were installed for each version I reinstalled, and though it doesn't complain about the Windows SDK missing, it still can't find the file it wants:

```
C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\vs_toolchain.py:12: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
  import pipes
Traceback (most recent call last):
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\toolchain\win\setup_toolchain.py", line 311, in <module>
    main()
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\toolchain\win\setup_toolchain.py", line 268, in main
    vc_lib_path = FindFileInEnvList(env, 'LIB', ';', 'msvcrt.lib')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\toolchain\win\setup_toolchain.py", line 209, in FindFileInEnvList
    assert optional, "%s is not found in %s:\n%s\nCheck if it is installed." % (
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x64
Check if it is installed.
Traceback (most recent call last):
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\toolchain\win\setup_toolchain.py", line 311, in <module>
    main()
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\toolchain\win\setup_toolchain.py", line 268, in main
    vc_lib_path = FindFileInEnvList(env, 'LIB', ';', 'msvcrt.lib')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ethin\source\vcpkg\buildtrees\v8\src\a883683717-d6c82ef7bb.clean\build\toolchain\win\setup_toolchain.py", line 209, in FindFileInEnvList
    assert optional, "%s is not found in %s:\n%s\nCheck if it is installed." % (
AssertionError: msvcrt.lib is not found in LIB:
C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x86
C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\um\x86
Check if it is installed.
```

I'm quite confused since the install for the version of the Windows SDK it wanted went well. I'm uncertain what's wrong with my setup or if this is a bug with vcpkg or the build system.

**Comment by JonLiu1993** [comment] 2024-02-18 07:59
This issue could be reproduced with vcpkg 2024-02-05-9c1e418fc6264dffcab6ca47746a648c35c379b9 and VS2022 17.8.7

**Comment by JonLiu1993** [comment] 2024-04-24 08:48
Duplicate of PR #https://github.com/microsoft/vcpkg/issues/22282

**Closed** 2024-04-24 08:49 UTC
Labels: category:port-bug
