### ISSUE TITLE
[openssl] Build error on x64-windows when vcpkg\downloads\tools\nasm already exists

### ISSUE THREAD

**Issue by Binary-System** [microsoft/vcpkg#37421] opened 2024-03-13 13:18 UTC
Package: openssl:x64-windows@3.2.1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30153.0
-    vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
    vcpkg-scripts version: 72c38122d 2024-03-12 (15 hours ago)

**To Reproduce**

`vcpkg install openssl`
**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.2.1.tar.gz.
-- Cleaning sources at R:/libs/vcpkg/buildtrees/openssl/src/nssl-3.2.1-8707343470.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source R:/libs/vcpkg/downloads/openssl-openssl-openssl-3.2.1.tar.gz
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at R:/libs/vcpkg/buildtrees/openssl/src/nssl-3.2.1-8707343470.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Using cached nasm-2.16.01-win64.zip.
CMake Error at scripts/cmake/vcpkg_extract_archive.cmake:19 (message):
  R:/libs/vcpkg/downloads/tools/nasm was an extraction target, but it already
  exists.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_find_acquire_program.cmake:203 (vcpkg_extract_archive)
  ports/openssl/windows/portfile.cmake:60 (vcpkg_find_acquire_program)
  ports/openssl/portfile.cmake:74 (include)
  scripts/ports.cmake:175 (include)

Solution:

Remove folder "R:/libs/vcpkg/downloads/tools/nasm"

**Comment by Cheney-W** [comment] 2024-03-14 08:36
Duplicate of https://github.com/microsoft/vcpkg/issues/35884

**Closed by Cheney-W** 2024-03-14 08:36 UTC
Labels: category:question
