### ISSUE TITLE
[mbedtls] update to 3.2.1

### ISSUE THREAD

**Issue by ghesketh** [microsoft/vcpkg#26205] opened 2022-08-06 02:14 UTC
Library name:  mbedtls

New version number: 3.2.1

Current vcpkg version of mbedtls is 2.28.1.  Versions 3.2.0 and 3.2.1 have many bugfixes and have API updates required for other libraries.

**Comment by xavier2k6** [comment] 2022-08-07 11:14
Duplicate of #25703

**Closed** 2022-08-08 01:56 UTC
Labels: category:port-update
