### ISSUE TITLE
Launching powershell failed or was denied when trying to fetch git version 2.14.1.

### ISSUE THREAD

**Issue by fishfreetaken** [Microsoft/vcpkg#1683] opened 2017-08-23 08:26 UTC
~\Documents\GitHub\vcpkg [master ≡]> .\vcpkg install sdl2 curl
The following packages will be built and installed:
    curl:x86-windows
  * libssh2:x86-windows
  * openssl:x86-windows
    sdl2:x86-windows
  * zlib:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package sdl2:x86-windows...
Launching powershell failed or was denied when trying to fetch git version 2.14.1.
(No sufficient installed version was found)

**Comment by alexkaratarakis** [comment] 2017-08-23 16:28
Installing latest git on your machine ([link](https://git-scm.com/download/win)) will avoid this issue altogether. 

However, if you wish to investigate: 
1) Open cmd (not powershell) in your vcpkg root.
2) Run:
`powershell -NoProfile -ExecutionPolicy Bypass -Command "scripts\fetchDependency.ps1 git"`

**Comment by fishfreetaken** [comment] 2017-08-25 03:58
Thanks! I update my git and it works!
but when building libuv x64, get a building error like this:

Error: Building package libuv:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libuv:x64-windows
  Vcpkg version: 0.0.84-unknownhash

**Comment by zhanMan** [comment] 2017-08-28 08:33
D:\vs2015\vcpkg-master>.\vcpkg.exe install opencv
The following packages will be built and installed:
  * libjpeg-turbo:x86-windows
  * liblzma:x86-windows
  * libpng:x86-windows
    opencv:x86-windows
  * tiff:x86-windows
  * zlib:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package zlib:x86-windows...
Launching powershell failed or was denied when trying to fetch git version 2.14.1.
(No sufficient installed version was found)
cmd admin：
D:\vs2015\vcpkg-master>powershell -NoProfile -ExecutionPolicy Bypass -Command "scripts\fetchDependency.ps1 git
Mismatching hash of the downloaded git
所在位置 D:\vs2015\vcpkg-master\scripts\fetchDependency.ps1:168 字符: 9
+         throw [System.IO.FileNotFoundException] ("Mismatching hash of ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileNotFoundException
    + FullyQualifiedErrorId : Mismatching hash of the downloaded git

What should I do???

**Comment by zhanMan** [comment] 2017-08-28 08:35
## D:\vs2015\vcpkg-master>.\vcpkg.exe install opencv
The following packages will be built and installed:

libjpeg-turbo:x86-windows
liblzma:x86-windows
libpng:x86-windows
opencv:x86-windows
tiff:x86-windows
zlib:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package zlib:x86-windows...
Launching powershell failed or was denied when trying to fetch git version 2.14.1.
(No sufficient installed version was found)
#  _cmd admin：_
## D:\vs2015\vcpkg-master>powershell -NoProfile -ExecutionPolicy Bypass -Command "scripts\fetchDependency.ps1 git
Mismatching hash of the downloaded git
所在位置 D:\vs2015\vcpkg-master\scripts\fetchDependency.ps1:168 字符: 9

**Comment by zhanMan** [comment] 2017-08-28 08:36
## D:\vs2015\vcpkg-master>.\vcpkg.exe install opencv

The following packages will be built and installed:

libjpeg-turbo:x86-windows
liblzma:x86-windows
libpng:x86-windows
opencv:x86-windows
tiff:x86-windows
zlib:x86-windows
Additional packages (*) will be installed to complete this operation.
Building package zlib:x86-windows...
Launching powershell failed or was denied when trying to fetch git version 2.14.1.
(No sufficient installed version was found)

## cmd admin：

## D:\vs2015\vcpkg-master>powershell -NoProfile -ExecutionPolicy Bypass -Command "scripts\fetchDependency.ps1 git

Mismatching hash of the downloaded git
所在位置 D:\vs2015\vcpkg-master\scripts\fetchDependency.ps1:168 字符: 9


## what should I do??

**Comment by zhanMan** [comment] 2017-08-28 09:26
## D:\vs2015\vcpkg-master>vcpkg install openssl:x64-windows zlib:x64-windows libuv:x64-windows
The following packages will be built and installed:
    libuv:x64-windows
    openssl:x64-windows
    zlib:x64-windows
Building package openssl:x64-windows...
Launching powershell failed or was denied when trying to fetch git version 2.14.1.
(No sufficient installed version was found)

**Comment by alexkaratarakis** [comment] 2017-08-30 22:58
@fishfreetaken 
Can you post the logfiles?

@zhanMan 
Please open a New Issue. I think you have an incompletely downloaded version of git. Please delete `Downloads/MinGit-2.14.1-32-bit.zip` and try again. Alternatively (and even better IMO), download and install the latest git from here: 
https://git-scm.com/download/win
This will allow you to completely bypass this issue.

**Comment by zhanMan** [comment] 2017-08-31 04:00
Thanks@alexkaratarakis

**Comment by alexkaratarakis** [comment] 2017-11-06 02:51
Closing.
Also, I think the root cause i the same as in #2127 so, this should no longer happen.

**Closed by alexkaratarakis** 2017-11-06 02:51 UTC
