### ISSUE TITLE
harfbuzz warning: Cannot set "HARFBUZZ_FOUND": current scope has no parent.

### ISSUE THREAD

**Issue by ylz-at** [microsoft/vcpkg#24111] opened 2022-04-13 03:58 UTC
**Describe the bug**
harfbuzz output warnings when I try to use qtbase.

```
CMake Warning (dev) at C:/vcpkg/installed/x64-windows-static-md/share/harfbuzz/harfbuzzConfig.cmake:68 (set):
  Cannot set "HARFBUZZ_FOUND": current scope has no parent.
Call Stack (most recent call first):
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:805 (_find_package)
  C:/vcpkg/installed/x64-windows-static-md/share/Qt6/FindWrapSystemHarfbuzz.cmake:9 (find_package)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:805 (_find_package)
  C:/vcpkg/installed/x64-windows-static-md/share/Qt6/QtFindWrapHelper.cmake:66 (find_package)
  C:/vcpkg/installed/x64-windows-static-md/share/Qt6/FindWrapHarfbuzz.cmake:3 (qt_find_package_system_or_bundled)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:805 (_find_package)
  C:/Program Files/CMake/share/cmake-3.23/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  C:/vcpkg/installed/x64-windows-static-md/share/Qt6Gui/Qt6GuiDependencies.cmake:45 (find_dependency)
  C:/vcpkg/installed/x64-windows-static-md/share/Qt6Gui/Qt6GuiConfig.cmake:40 (include)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:805 (_find_package)
  C:/vcpkg/installed/x64-windows-static-md/share/Qt6/Qt6Config.cmake:177 (find_package)
  C:/vcpkg/scripts/buildsystems/vcpkg.cmake:805 (_find_package)
  CMakeLists.txt:31 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Environment**
- OS: Windows
- Compiler: VS2022  MSVC 19.32.31326.0

**To Reproduce**
1. ./vcpkg install qtbase:x64-windows-static-md
2. use `find_package(Qt6 COMPONENTS Core Gui Widgets Required)`
3. See warning output when using `cmake.exe -DCMAKE_BUILD_TYPE=Debug -DVCPKG_TARGET_TRIPLET=x64-windows-static-md -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -G "CodeBlocks - NMake Makefiles" ..`

**Expected behavior**
No warnings

**Additional context**
triplet: x64-windows-static-md

**Comment by dg0yt** [comment] 2022-04-13 04:08
Duplicate of #23694.

**Closed** 2022-04-13 09:08 UTC
Labels: category:port-bug
