### ISSUE TITLE
Error building openjpeg:x64-windows-static

### ISSUE THREAD

**Issue by oddraly** [microsoft/vcpkg#6343] opened 2019-05-08 06:22 UTC
> Error: Building package openjpeg:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openjpeg:x64-windows-static
  Vcpkg version: 2018.11.23-nohash

When building freeimage downloaded from [sourceforge](http://freeimage.sourceforge.net/), it builds OK, but then it's not called openjpeg, but LibOpenJPEG.
Is it possible that this could be fixed?

**Comment by wangli28** [comment] 2019-05-08 08:54
Hi @oddraly, thank you for posting the issue, Can you provide the build log? What information did vcpkg gives to you?
Thanks.

**Comment by oddraly** [comment] 2019-05-08 09:29
Well there isn't really any build log, since it fails prior to the build, when checking if a static build is available.
As mentioned above, when I'm building in Visual Studio, the lib project is called LibOpenJPEG, and not openjpeg.
All of freeimage sub modules are static libs, in the project there.

The command line messages is saying, that missing static config is the problem:

> PS D:\Src\o\vcpkg> .\vcpkg.exe install openjpeg:x64-windows-static
The following packages will be built and installed:
    openjpeg[core]:x64-windows-static
Starting package 1/1: openjpeg:x64-windows-static
Building package openjpeg[core]:x64-windows-static...
-- Note: openjpeg only supports dynamic library linkage. Building dynamic library.
CMake Error at scripts/cmake/vcpkg_check_linkage.cmake:42 (message):
  Refusing to build unexpected dynamic library against the static CRT.  If
  this is desired, please configure your triplet to directly request this
  configuration.
Call Stack (most recent call first):
  ports/openjpeg/portfile.cmake:3 (vcpkg_check_linkage)
  scripts/ports.cmake:71 (include)

**Comment by wangli28** [comment] 2019-05-08 10:09
Static openjpeg build failed due to a recent intentional change, you can build it successfully by explicitly requesting the configuration in a custom triplet file. See more information here: #5937.

**Comment by oddraly** [comment] 2019-05-09 09:21
> Static openjpeg build failed due to a recent intentional change, you can build it successfully by explicitly requesting the configuration in a custom triplet file. See more information here: #5937.

Well, I'm able to explicitly build openjpeg dynamic version, but I'm still unable to make it a static lib.
I'm under the impression that VCPKG currently doesn't have any config available for building openjpeg as a static lib, am I wrong?

**Comment by Neumann-A** [comment] 2019-05-09 12:01
Open the portfile and remove:
`vcpkg_check_linkage(ONLY_DYNAMIC_LIBRARY)`
and add to the `vcpkg_configure_cmake` options
`-DBUILD_SHARED_LIBS=OFF`

@vicroms: was there a reason you did not conditionally switch openjpeg to a static build? From the looks of it openjpeg can be build as a static library.

**Comment by oddraly** [comment] 2019-05-09 12:32
Thanks for that info, now it builds

**Comment by oddraly** [comment] 2019-05-09 12:54
>  Error building freeimage:x64-windows-static

My original issue text is still valid though, still unable to build freeimage as static.
- install libwebp:x64-windows-static, is compiling fine.

When running install freeimage:x64-windows-static, I get this result:

> The following packages will be rebuilt:
>   * libwebp[all,core]:x64-windows-static
> The following packages will be built and installed:
>     freeimage[core]:x64-windows-static
>   * jxrlib[core]:x64-windows-static
> Additional packages (*) will be modified to complete this operation.
> If you are sure you want to rebuild the above packages, run the command with the --recurse option

And then, during freeimage build, libwebp is failing.

**Comment by cenit** [comment] 2019-05-10 15:20
update vcpkg with a git pull inside the folder, then retry :)
We fixed many bugs with freeimage, libwebp, openjpeg itself not so many hours ago

**Comment by sirjuddington** [comment] 2019-05-15 03:11
I'm getting a similar issue with the latest from git - `libwebp:x86-windows-static` compiles fine but `libwebp[all,core]:x86-windows-static` fails.

Looking at `install-x86-windows-static-dbg-out.log` for libwebp, there are a bunch of link errors to do with SDL:
```
SDL.lib(SDL_systimer.obj) : error LNK2019: unresolved external symbol __imp__timeSetEvent@20 referenced in function _SDL_SYS_TimerInit
SDL.lib(SDL_systimer.obj) : error LNK2019: unresolved external symbol __imp__timeKillEvent@4 referenced in function _SDL_SYS_TimerQuit
SDL.lib(SDL_systimer.obj) : error LNK2019: unresolved external symbol __imp__timeGetTime@0 referenced in function _SDL_GetTicks
SDL.lib(SDL_systimer.obj) : error LNK2019: unresolved external symbol __imp__timeBeginPeriod@4 referenced in function _SDL_SYS_TimerInit
SDL.lib(SDL_systimer.obj) : error LNK2019: unresolved external symbol __imp__timeEndPeriod@4 referenced in function _SDL_SYS_TimerQuit
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _GUID_XAxis
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _GUID_YAxis
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _GUID_ZAxis
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _GUID_RxAxis
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _GUID_RyAxis
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _GUID_RzAxis
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _GUID_Slider
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _GUID_Key
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _GUID_POV
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _IID_IDirectDraw2
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _IID_IDirectDrawSurface3
SDL.lib(SDL_dx5yuv.obj) : error LNK2001: unresolved external symbol _IID_IDirectDrawSurface3
SDL.lib(SDL_dx5video.obj) : error LNK2001: unresolved external symbol _IID_IDirectDrawGammaControl
SDL.lib(SDL_mmjoystick.obj) : error LNK2019: unresolved external symbol __imp__joyGetPosEx@8 referenced in function _SDL_SYS_JoystickInit
SDL.lib(SDL_mmjoystick.obj) : error LNK2019: unresolved external symbol __imp__joyGetNumDevs@0 referenced in function _SDL_SYS_JoystickInit
SDL.lib(SDL_mmjoystick.obj) : error LNK2019: unresolved external symbol __imp__joyGetDevCapsA@12 referenced in function _SDL_SYS_JoystickInit
SDL.lib(SDL_dibaudio.obj) : error LNK2019: unresolved external symbol __imp__waveOutGetErrorTextA@12 referenced in function _SetMMerror
SDL.lib(SDL_dibaudio.obj) : error LNK2019: unresolved external symbol __imp__waveOutOpen@24 referenced in function _DIB_OpenAudio
SDL.lib(SDL_dibaudio.obj) : error LNK2019: unresolved external symbol __imp__waveOutClose@4 referenced in function _DIB_CloseAudio
SDL.lib(SDL_dibaudio.obj) : error LNK2019: unresolved external symbol __imp__waveOutPrepareHeader@12 referenced in function _DIB_OpenAudio
SDL.lib(SDL_dibaudio.obj) : error LNK2019: unresolved external symbol __imp__waveOutUnprepareHeader@12 referenced in function _DIB_CloseAudio
SDL.lib(SDL_dibaudio.obj) : error LNK2019: unresolved external symbol __imp__waveOutWrite@12 referenced in function _DIB_PlayAudio
SDL.lib(SDL_syscdrom.obj) : error LNK2019: unresolved external symbol __imp__mciSendCommandA@16 referenced in function _SDL_SYS_CDioctl
SDL.lib(SDL_syscdrom.obj) : error LNK2019: unresolved external symbol __imp__mciGetErrorStringA@12 referenced in function _SDL_SYS_CDioctl
SDL.lib(SDL_dx5events.obj) : error LNK2001: unresolved external symbol _GUID_SysMouse
SDL.lib(SDL_dx5events.obj) : error LNK2001: unresolved external symbol _GUID_SysKeyboard
SDL.lib(SDL_dx5events.obj) : error LNK2001: unresolved external symbol _IID_IDirectInputDevice2A
vwebp_sdl.exe : fatal error LNK1120: 31 unresolved externals
```

**Comment by PhoebeHui** [comment] 2019-06-24 08:32
@oddraly. @sirjuddington, can you get vcpkg and try again, I tried, everything installed successfully now.

Starting package 13/16: libwebp:x64-windows-static
Building package libwebp[all,core]:x64-windows-static...
-- Downloading https://github.com/webmproject/libwebp/archive/v1.0.2.tar.gz...
-- Extracting source F:/vcpkg/downloads/webmproject-libwebp-v1.0.2.tar.gz
-- Applying patch 0001-build-fixes.patch
-- Applying patch 0002-cmake-config-add-backwards-compatibility.patch
-- Applying patch 0003-remove-missing-symbol.patch
-- Applying patch 0004-add-missing-linked-library.patch
-- Applying patch 0005-fix-static-build.patch
-- Using source at F:/vcpkg/buildtrees/libwebp/src/v1.0.2-3917ce9f58
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: F:/vcpkg/packages/libwebp_x64-windows-static/share/libwebp/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package libwebp[all,core]:x64-windows-static... done
Installing package libwebp[all,core]:x64-windows-static...
Installing package libwebp[all,core]:x64-windows-static... done
....
Starting package 16/16: freeimage:x64-windows-static
Building package freeimage[core]:x64-windows-static...
-- Downloading http://downloads.sourceforge.net/freeimage/FreeImage3180.zip...
-- Extracting source F:/vcpkg/downloads/FreeImage3180.zip
-- Applying patch F:/vcpkg/ports/freeimage/disable-plugins-depending-on-internal-third-party-libraries.patch
-- Applying patch F:/vcpkg/ports/freeimage/use-external-jpeg.patch
-- Applying patch F:/vcpkg/ports/freeimage/use-external-jxrlib.patch
-- Applying patch F:/vcpkg/ports/freeimage/use-external-libtiff.patch
-- Applying patch F:/vcpkg/ports/freeimage/use-external-openjpeg.patch
-- Applying patch F:/vcpkg/ports/freeimage/use-external-png-zlib.patch
-- Applying patch F:/vcpkg/ports/freeimage/use-external-rawlib.patch
-- Applying patch F:/vcpkg/ports/freeimage/use-external-webp.patch
-- Applying patch F:/vcpkg/ports/freeimage/use-external-openexr.patch
-- Applying patch F:/vcpkg/ports/freeimage/use-freeimage-config-include.patch
-- Applying patch F:/vcpkg/ports/freeimage/fix-function-overload.patch
-- Applying patch F:/vcpkg/ports/freeimage/use-typedef-as-already-declared.patch
-- Using source at F:/vcpkg/buildtrees/freeimage/src/eImage3180-2288df34d2
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package freeimage[core]:x64-windows-static... done
Installing package freeimage[core]:x64-windows-static...
Installing package freeimage[core]:x64-windows-static... done
Elapsed time for package freeimage:x64-windows-static: 2.948 min

Total elapsed time: 37.64 min

**Comment by oddraly** [comment] 2019-06-24 09:57
It builds fine here on my side as well now.

**Comment by oddraly** [comment] 2019-06-26 10:47
It seems like there is one thing still which isn't 100% correct.
OpenExr seems to build dynamic as well as static, which causes conflicts when trying to use the exported Nuget package.
Here is a list of the produced files from building OpenExr:
Half-2_3.lib
Half-2_3_s.lib
Iex-2_3.lib
Iex-2_3_s.lib
IexMath-2_3.lib
IexMath-2_3_s.lib
IlmImf-2_3.lib  ---> Static version seems to be missing
IlmImfUtil-2_3.lib ---> Static version seems to be missing
IlmThread-2_3.lib
IlmThread-2_3_s.lib
Imath-2_3.lib
Imath-2_3_s.lib

**Comment by sirjuddington** [comment] 2019-06-26 22:59
Yes I'm getting a similar issue now, static build tries to link both Half-2_3.lib and Half-2_3_s.lib. Removing Half-2_3.lib from vcpkg makes it compile ok, but the executable won't run - complaining about missing IlmImf and Iex dlls.

**Comment by T-Deuty** [comment] 2019-06-28 14:32
Hello,

I'd like to add that I cannot build freeimage due to libwebp failing. It installs libwebp[core]:x86-windows fine, but fails when freeimage requests libwebp[all,core]:x86-windows and when trying to install that separately.

The failure is in trying to find freeglut.h, which I have confirmed exists in the package repo.

I'll attach the log file.
[install-x86-windows-rel-out-1.log](https://github.com/microsoft/vcpkg/files/3339643/install-x86-windows-rel-out-1.log)

I'm sorry if this is unrelated to this thread, I saw the libwebp install issues above and thought it appropriate to look for help here. Thanks!

**Comment by PhoebeHui** [comment] 2019-09-29 08:09
It's better to report a separate issue to track if it's a unrelated issue.

@T-Deuty, I can't repro your issue, could you get latest source and try again, and report a new issue if it still be an problem for you.

For OpenEXR, we have issue 8175 to track. The original issue solved, so close this issue.

**Closed by PhoebeHui** 2019-09-29 08:09 UTC
Labels: needs-repro
