### ISSUE TITLE
[magnum-plugins] deployBinary incorrectly skipping over some binaries 

### ISSUE THREAD

**Issue by nairaner** [microsoft/vcpkg#15912] opened 2021-01-27 13:15 UTC
When using magnum-plugins[freetypefont] (possibly applies to any font plugin), only fonts plugins are copied to output directory after compiling programs. 

**Environment**
- OS: Windows 10
- Compiler: MSVC 19.28.29336.0

**To Reproduce**
1. ./vcpkg install magnum-plugins[pngimporter, freetypefont]
2. Compile program depending on pngimporter
3. Run application
4. Program crashes, because PngImporter plugin is missing
5. Check application plugin directory
6. There are only font plugins 

**Expected behavior**
In plugins directory there should be importers and fonts

**Failure logs** 
Logs generated by command based on one used by ninja:
```
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C:/Users/Ciampino/Documents/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/Ciampino/Documents/viewer2/cmake-build-relwithdebinfo/bin/processor.exe -installedDir C:/Users/Ciampino/Documents/viewer2/cmake-build-relwithdebinfo/vcpkg_installed/x64-windows/bin -verbose
```
There are versions for when freetypefont feature is both enabled and disabled. Command is run after deleting all files other than application binary. 
https://gist.github.com/nairaner/98c1a84c1824474942c6fb9eacc82403

**Additional context**
Our application is using vcpkg manifest file for specifying dependencies, but I don't believe it should cause this issue. Magnum has its own `magnumdeploy.ps1` script, but it is  vcpkg function `deployBinary` which skips over the plugins with message `Already present`

**Comment by JackBoosY** [comment] 2021-01-28 02:41
cc @Squareys

**Comment by Squareys** [comment] 2021-02-16 08:06
I was not able to reproduce your issue (though I don't use the manifest files), but maybe the somewhat related fixes in https://github.com/microsoft/vcpkg/pull/16245 will help.

**Comment by JackBoosY** [comment] 2021-02-18 07:35
@nairaner Can you please test PR #16245 whether it works?

Thanks.

**Comment by nairaner** [comment] 2021-02-18 17:10
This part fixes the issue
```
-    } elseif ($targetBinaryName -like "Magnum.dll" -or $targetBinaryName -like "Magnum-d.dll") {
+    } elseif ($targetBinaryName -like "MagnumTrade.dll" -or $targetBinaryName -like "MagnumTrade-d.dll") {
```

If I understand correctly deploying MagnumFonts.dll recursively deploys Magnum.dll and then calls to `deployBinary` from `deployPlugins` skips over plugins. Because MagnumTrade.dll is deployed directly this works correctly. 
If this is what happens, then this can start happening again and it is possibly bug in `deployBinary` not in port.

**Comment by JackBoosY** [comment] 2021-02-19 03:05
Close this issue via #16245 merged.

**Closed by JackBoosY** 2021-02-19 03:05 UTC
Labels: category:port-bug
