### ISSUE TITLE
CMD shell installer one-liner doesn't work

### ISSUE THREAD

**Issue by merlynomsft** [microsoft/vcpkg#26489] opened 2022-08-24 00:23 UTC
**Describe the bug**

**Environment**
- OS: Windows
- Compiler: N/A

**To Reproduce**
Run 

```curl -LO https://aka.ms/vcpkg-init.cmd && .\vcpkg-init.cmd```

From https://devblogs.microsoft.com/cppblog/vcpkg-artifacts/#acquire-vcpkg

Result:
**Expected behavior**
vcpkg should be successfully installed

**Failure logs**
```
C:\repos\accel-AppSamples\LocalSamples\IntercoreComms>curl -LO https://aka.ms/vcpkg-init.cmd && .\vcpkg-init.cmd
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100 22459  100 22459    0     0  16073      0  0:00:01  0:00:01 --:--:-- 16073
Commands:
  vcpkg search [pat]              Search for packages available to be built
  vcpkg install <pkg>...          Install a package
  vcpkg remove <pkg>...           Uninstall a package
  vcpkg remove --outdated         Uninstall all out-of-date packages
  vcpkg list                      List installed packages
```

**Additional context**
Possibly related to #26172

**Comment by LilyWangLL** [comment] 2022-08-24 06:59
Closed as duplicate of #26172.

**Closed by LilyWangLL** 2022-08-24 06:59 UTC
Labels: category:vcpkg-bug
