### ISSUE TITLE
[mlpack] build failure x64-windows CMake Error portfile.cmake:43(file) file must be called with at least two arguments

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#10384] opened 2020-03-11 11:56 UTC
**Host Environment**
- OS: [Microsoft Windows Version 1909 (OS Build 18363.719)]
- Compiler: Visual Studio
   - VS 2017 v15.9.21 VS Tools Version 14.16.27023
   - VS 2019 v16.4.6 VS Tools Version 14.24.28314

**To Reproduce**
`.\vcpkg install mlpack[core,tools]`
Computing installation plan...
The following packages will be built and installed:
    mlpack[core,tools]:x64-windows

**Failure logs** 
- Cut and past the appropriate build messages from the console output.
Building package mlpack[core,tools]:x64-windows...
-- Using cached E:/Git/vcpkg.downloads/mlpack-mlpack-a8af4882af5e163ae8c8023653c66c8914ac1c22.tar.gz
-- Using source at D:/Git/vs2017.prod/buildtrees/mlpack/src/8914ac1c22-a13fe85378
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: D:/Git/vs2017.prod/packages/mlpack_x64-windows/share/mlpack/copyright
**CMake Error at ports/mlpack/portfile.cmake:43 (file):**
  **file must be called with at least two arguments.**
Call Stack (most recent call first):
  scripts/ports.cmake:90 (include)

**Error: Building package mlpack:x64-windows failed with: BUILD_FAILED**
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: mlpack:x64-windows
  Vcpkg version: 2020.02.04-nohash-external

Additionally, attach any relevant sections from the log files above.

- Please attach any additional failure logs mentioned in the console output.
  All other logs are normal - no other error messages produced.

**Additional context**
 If line 39 of the mlpack portfile.cmake is changed:
 - from: **if("tools" IN_LIST FEATURES)**
 - to:  **if (${BUILD_TOOLS})**
The error is not produced and mlpack installs properly with the tools.

**Comment by timautry** [comment] 2020-03-11 20:17
@NancyLi1013 - let me clarify... if I change the mlpack portfile.cmake (see below) then mlpack builds, installs along with all the tools and completes normally.
- The **_BOLD ITALICS_** is commented out
- The **BOLD** I copied from the previous portfile.cmake

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO mlpack/mlpack
    REF a8af4882af5e163ae8c8023653c66c8914ac1c22 # 3.2.2
    SHA512 879dd24f6cface3e6e1a0990e912ca4463060725c7c105e1e7d228c90123b1f44728cbe1ae327fa20e0e4981626a5d1eb2c411257899ef849c9600891616eed4
    HEAD_REF master
    PATCHES
        cmakelists.patch
)

file(REMOVE ${SOURCE_PATH}/CMake/ARMA_FindACML.cmake)
file(REMOVE ${SOURCE_PATH}/CMake/ARMA_FindACMLMP.cmake)
file(REMOVE ${SOURCE_PATH}/CMake/ARMA_FindARPACK.cmake)
file(REMOVE ${SOURCE_PATH}/CMake/ARMA_FindBLAS.cmake)
file(REMOVE ${SOURCE_PATH}/CMake/ARMA_FindCBLAS.cmake)
file(REMOVE ${SOURCE_PATH}/CMake/ARMA_FindCLAPACK.cmake)
file(REMOVE ${SOURCE_PATH}/CMake/ARMA_FindLAPACK.cmake)
file(REMOVE ${SOURCE_PATH}/CMake/ARMA_FindMKL.cmake)
file(REMOVE ${SOURCE_PATH}/CMake/ARMA_FindOpenBLAS.cmake)
file(REMOVE ${SOURCE_PATH}/CMake/FindArmadillo.cmake)

**_#vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS_**
**_#    tools     BUILD_TOOLS_**
**_#)_**
**set(BUILD_TOOLS OFF)**
**if("tools" IN_LIST FEATURES)**
    **set(BUILD_TOOLS ON)**
**endif()**

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DBUILD_TESTS=${BUILD_TOOLS}
        -DBUILD_CLI_EXECUTABLES=${BUILD_TOOLS}
      **_# ${FEATURE_OPTIONS}_**
)
vcpkg_install_cmake()
vcpkg_copy_pdbs()

file(INSTALL ${SOURCE_PATH}/COPYRIGHT.txt DESTINATION ${CURRENT_PACKAGES_DIR}/share/${PORT} RENAME copyright)

**_#if("tools" IN_LIST FEATURES)_**
**if(BUILD_TOOLS)**
    file(MAKE_DIRECTORY ${CURRENT_PACKAGES_DIR}/tools)
    file(GLOB MLPACK_TOOLS ${CURRENT_PACKAGES_DIR}/bin/*.exe)
    file(COPY ${MLPACK_TOOLS} DESTINATION ${CURRENT_PACKAGES_DIR}/tools/${PORT})
    file(REMOVE_RECURSE ${MLPACK_TOOLS})
    file(GLOB MLPACK_TOOLS_DEBUG ${CURRENT_PACKAGES_DIR}/debug/bin/*.exe)
    file(REMOVE ${MLPACK_TOOLS_DEBUG})
endif()

file(REMOVE_RECURSE ${CURRENT_PACKAGES_DIR}/debug/include)

**Comment by NancyLi1013** [comment] 2020-03-12 01:42
Hi @timautry 
Thanks for posting this issue and your detail description about this.
I will check if this can work well later.

**Comment by NancyLi1013** [comment] 2020-03-13 02:16
@timautry 

I have confirmed that this is a bug. Why do you close this issue now?

**Comment by NancyLi1013** [comment] 2020-03-13 03:16
I have checked the source code. Since `BUILD_TOOLS` does not exist in `mlpack `source code. Even though we pass its value to `BUILD_TESTS `and  `BUILD_CLI_EXECUTABLES`. In fact, the values of these two options  are not updated via `vcpkg_check_features()` and `${FEATURE_OPTIONS}`.

So the *.exe files should not be genrated in this way.

In my opinion, there is no need to use `BUILD_TOOLS` here.

We can change like this：
```
vcpkg_check_features(OUT_FEATURE_OPTIONS FEATURE_OPTIONS
      tools BUILD_CLI_EXECUTABLES
)

vcpkg_configure_cmake(
SOURCE_PATH ${SOURCE_PATH}
PREFER_NINJA
OPTIONS
-DBUILD_TESTS=OFF
 ${FEATURE_OPTIONS}
)
```

**Comment by PhoebeHui** [comment] 2020-03-13 05:24
Sorry, it's my fault, I updated mlpack recently, I tested the features, and all passed, however, I forget to update the changes. 

@NancyLi1013, could you summit a fix for this?

**Comment by NancyLi1013** [comment] 2020-03-17 01:46
This issue should be fixed now. Please try to update vcpkg and build it again.

**Closed by NancyLi1013** 2020-03-17 01:46 UTC
Labels: port bug
