### ISSUE TITLE
[protobuf] Build error on x64-windows

### ISSUE THREAD

**Issue by tkontos** [microsoft/vcpkg#37031] opened 2024-02-28 12:27 UTC
[issue_body.md](https://github.com/microsoft/vcpkg/files/14433897/issue_body.md)
[patch-x64-windows-2-err.log](https://github.com/microsoft/vcpkg/files/14433919/patch-x64-windows-2-err.log)
[patch-x64-windows-0-err.log](https://github.com/microsoft/vcpkg/files/14433922/patch-x64-windows-0-err.log)
[copy-tool-dependencies-0-err.log](https://github.com/microsoft/vcpkg/files/14433928/copy-tool-dependencies-0-err.log)

**Comment by jimwang118** [comment] 2024-02-29 02:40
Sorry, I cannot reproduce this issue locally.
![image](https://github.com/microsoft/vcpkg/assets/122244446/6031cf38-6fdd-4998-82b3-e06bc6f00641)

**Comment by tkontos** [comment] 2024-02-29 09:51
Not sure how to generate a repro. I tried on 2 different computers with a clean install with the same results:
Microsoft Windows [Version 10.0.22631.3155]
(c) Microsoft Corporation. All rights reserved.

M:\____tracey\_vcpkg>git clone https://github.com/microsoft/vcpkg.git
Cloning into 'vcpkg'...
remote: Enumerating objects: 223875, done.
remote: Counting objects: 100% (7916/7916), done.
remote: Compressing objects: 100% (569/569), done.
remote: Total 223875 (delta 7572), reused 7506 (delta 7347), pack-reused 215959
Receiving objects: 100% (223875/223875), 66.49 MiB | 48.60 MiB/s, done.
Resolving deltas: 100% (147812/147812), done.
Updating files: 100% (11150/11150), done.

M:\____tracey\_vcpkg>cd vcpkg

M:\____tracey\_vcpkg\vcpkg>bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2024-02-07/vcpkg.exe -> M:\____tracey\_vcpkg\vcpkg\vcpkg.exe... done.
Validating signature... done.

vcpkg package management program version 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b

See LICENSE.txt for license information.
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

M:\____tracey\_vcpkg\vcpkg>vcpkg install protobuf
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    protobuf:x64-windows@3.21.12#1
  * vcpkg-cmake:x64-windows@2023-05-04
  * vcpkg-cmake-config:x64-windows@2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of 7zip was not found (required v23.1.0) Downloading portable 7zip 23.1.0...
Downloading 7zip...
https://github.com/ip7z/7zip/releases/download/23.01/7z2301-extra.7z->M:\____tracey\_vcpkg\vcpkg\downloads\7z2301-extra.7z
Downloading https://github.com/ip7z/7zip/releases/download/23.01/7z2301-extra.7z
Extracting 7zip...
Restored 0 package(s) from C:\Users\thank\AppData\Local\vcpkg\archives in 8.94 ms. Use --debug to see more details.
Installing 1/3 vcpkg-cmake:x64-windows@2023-05-04...
Building vcpkg-cmake:x64-windows@2023-05-04...
-- Installing: M:/____tracey/_vcpkg/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: M:/____tracey/_vcpkg/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: M:/____tracey/_vcpkg/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: M:/____tracey/_vcpkg/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: M:/____tracey/_vcpkg/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 43.3 ms.
Elapsed time to handle vcpkg-cmake:x64-windows: 84.1 ms
vcpkg-cmake:x64-windows package ABI: 3b723cf8364ba8901efea4ccd4abc897cbb20221ea1e32cd760377858d0e9503
Installing 2/3 vcpkg-cmake-config:x64-windows@2022-02-06#1...
Building vcpkg-cmake-config:x64-windows@2022-02-06#1...
-- Installing: M:/____tracey/_vcpkg/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake
-- Installing: M:/____tracey/_vcpkg/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg-port-config.cmake
-- Installing: M:/____tracey/_vcpkg/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 23.5 ms.
Elapsed time to handle vcpkg-cmake-config:x64-windows: 51.2 ms
vcpkg-cmake-config:x64-windows package ABI: c9fc8cfaf5b1a45d0986c49fba97e11b15ddcedc532861a5d3db87e2b80800b5
Installing 3/3 protobuf:x64-windows@3.21.12#1...
Building protobuf:x64-windows@3.21.12#1...
-- Downloading https://github.com/protocolbuffers/protobuf/archive/v3.21.12.tar.gz -> protocolbuffers-protobuf-v3.21.12.tar.gz...
-- Extracting source M:/____tracey/_vcpkg/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch compile_options.patch
-- Using source at M:/____tracey/_vcpkg/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/thank/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file M:/____tracey/_vcpkg/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary M:/____tracey/_vcpkg/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe -installedDir M:/____tracey/_vcpkg/vcpkg/packages/protobuf_x64-windows/bin -verbose
    Working Directory: M:/____tracey/_vcpkg/vcpkg
    Error code: -532462766
    See logs for more information:
      M:\____tracey\_vcpkg\vcpkg\buildtrees\protobuf\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/protobuf/portfile.cmake:92 (vcpkg_copy_tools)
  scripts/ports.cmake:172 (include)


error: building protobuf:x64-windows failed with: BUILD_FAILED
Elapsed time to handle protobuf:x64-windows: 27 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[protobuf]+Build+error+on+x64-windows&body=Copy+issue+body+from+M%3A%2F____tracey%2F_vcpkg%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md


M:\____tracey\_vcpkg\vcpkg>

**Comment by jimwang118** [comment] 2024-03-01 02:18
Please provide `M:____tracey_vcpkg\vcpkg\buildtrees\protobuf\copy-tool-dependencies-0-err.log` log.

**Comment by tkontos** [comment] 2024-03-01 10:04
Here it is
[copy-tool-dependencies-0-err.log](https://github.com/microsoft/vcpkg/files/14459488/copy-tool-dependencies-0-err.log)

**Comment by jimwang118** [comment] 2024-03-01 10:27
You remove the special characters from the path, use only alphabetic file paths, and then reinstall.

**Comment by tkontos** [comment] 2024-03-01 11:02
I don't understand what special characters to remove - if you mean the _ (underscore), I tried installing on M:\vcpkg with the same results:
M:\>git clone https://github.com/microsoft/vcpkg.git
Cloning into 'vcpkg'...
remote: Enumerating objects: 223909, done.
remote: Counting objects: 100% (11241/11241), done.
remote: Compressing objects: 100% (606/606), done.
remote: Total 223909 (delta 10874), reused 10803 (delta 10635), pack-reused 212668
Receiving objects: 100% (223909/223909), 68.38 MiB | 49.38 MiB/s, done.
Resolving deltas: 100% (148222/148222), done.
Updating files: 100% (11147/11147), done.

M:\>cd vcpkg

M:\vcpkg>vcpkg install protobuf
'vcpkg' is not recognized as an internal or external command,
operable program or batch file.

M:\vcpkg>bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2024-02-07/vcpkg.exe -> M:\vcpkg\vcpkg.exe... done.
Validating signature... done.

vcpkg package management program version 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b

See LICENSE.txt for license information.
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

M:\vcpkg>vcpkg install protobuf
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    protobuf:x64-windows@3.21.12#1
  * vcpkg-cmake:x64-windows@2023-05-04
  * vcpkg-cmake-config:x64-windows@2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of 7zip was not found (required v23.1.0) Downloading portable 7zip 23.1.0...
Downloading 7zip...
https://github.com/ip7z/7zip/releases/download/23.01/7z2301-extra.7z->M:\vcpkg\downloads\7z2301-extra.7z
Downloading https://github.com/ip7z/7zip/releases/download/23.01/7z2301-extra.7z
Extracting 7zip...
Restored 0 package(s) from C:\Users\thank\AppData\Local\vcpkg\archives in 9.5 ms. Use --debug to see more details.
Installing 1/3 vcpkg-cmake:x64-windows@2023-05-04...
Building vcpkg-cmake:x64-windows@2023-05-04...
-- Installing: M:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: M:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: M:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: M:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: M:/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 44 ms.
Elapsed time to handle vcpkg-cmake:x64-windows: 84.8 ms
vcpkg-cmake:x64-windows package ABI: 53b2f2e5c54b4a3691b5fcae9da6474ed8537e3e3cec93a701b71da8056da5de
Installing 2/3 vcpkg-cmake-config:x64-windows@2022-02-06#1...
Building vcpkg-cmake-config:x64-windows@2022-02-06#1...
-- Installing: M:/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg_cmake_config_fixup.cmake
-- Installing: M:/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/vcpkg-port-config.cmake
-- Installing: M:/vcpkg/packages/vcpkg-cmake-config_x64-windows/share/vcpkg-cmake-config/copyright
-- Performing post-build validation
Stored binaries in 1 destinations in 23.2 ms.
Elapsed time to handle vcpkg-cmake-config:x64-windows: 50.7 ms
vcpkg-cmake-config:x64-windows package ABI: 5108360284ecc555470e3ced3820e332f4e98810638796f99c0703164b155906
Installing 3/3 protobuf:x64-windows@3.21.12#1...
Building protobuf:x64-windows@3.21.12#1...
-- Downloading https://github.com/protocolbuffers/protobuf/archive/v3.21.12.tar.gz -> protocolbuffers-protobuf-v3.21.12.tar.gz...
-- Extracting source M:/vcpkg/downloads/protocolbuffers-protobuf-v3.21.12.tar.gz
-- Applying patch fix-static-build.patch
-- Applying patch fix-default-proto-file-path.patch
-- Applying patch compile_options.patch
-- Using source at M:/vcpkg/buildtrees/protobuf/src/v3.21.12-fdb7676342.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/thank/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file M:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary M:/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe -installedDir M:/vcpkg/packages/protobuf_x64-windows/bin -verbose
    Working Directory: M:/vcpkg
    Error code: -532462766
    See logs for more information:
      M:\vcpkg\buildtrees\protobuf\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/protobuf/portfile.cmake:92 (vcpkg_copy_tools)
  scripts/ports.cmake:172 (include)


error: building protobuf:x64-windows failed with: BUILD_FAILED
Elapsed time to handle protobuf:x64-windows: 28 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+protobuf
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[protobuf]+Build+error+o
n+x64-windows&body=Copy+issue+body+from+M%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

[copy-tool-dependencies-0-err.log](https://github.com/microsoft/vcpkg/files/14460172/copy-tool-dependencies-0-err.log)
[error-logs-x64-windows.txt](https://github.com/microsoft/vcpkg/files/14460173/error-logs-x64-windows.txt)

**Comment by jimwang118** [comment] 2024-03-12 02:02
```
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet' with working directory 'M:\vcpkg'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.PowerShell.GlobalTool.Shim.EntryPoint.Main(String[] args)

```
Judging from the error `code: -532462766` and the error log, this should be a compiler error, not a vcpkg error.

**Comment by tkontos** [comment] 2024-03-12 10:37
We are using the latest release of MSVC (17.9.2). Any suggestions? Maybe you can file a bug report for MSVC. Do you not test with MSVC?

**Comment by tkontos** [comment] 2024-03-16 13:11
I downloaded a win11 virtual machine, added the C++ package to VS2022, and got protobuf working for the latest version of the compiler (17.9.3). So this is not a compiler problem. It is not a protobuf problem either, since this also happens with other packages.

**Comment by dg0yt** [comment] 2024-03-16 14:40
Any chance to use a different powershell executable?

~~~
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/thank/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file M:/____tracey/_vcpkg/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary M:/____tracey/_vcpkg/vcpkg/packages/protobuf_x64-windows/tools/protobuf/protoc.exe -installedDir M:/____tracey/_vcpkg/vcpkg/packages/protobuf_x64-windows/bin -verbose
~~~
This is not the location where I would expect find `pwsh.exe` on my computer.

~~~
Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'dotnet' with working directory 'M:\____tracey\_vcpkg\vcpkg'. The system cannot find the file specified.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.PowerShell.GlobalTool.Shim.EntryPoint.Main(String[] args)
~~~
`'dotnet'` seems to match your location.
But this is not the kind of stack trace which I would expect from `pwsh.exe`.

**Comment by tkontos** [comment] 2024-03-18 16:07
Thanks for the help. Removing the folder 'C:/Users/thank/.dotnet' seems to have fixed the problem. I have no idea how this was installed on my computer (actually 2 computers).

**Comment by jimwang118** [comment] 2024-03-19 02:10
Thank you for your reply. If your problem is solved, I will close this issue. If you have new questions, please submit a new issue.

**Closed by jimwang118** 2024-03-19 02:10 UTC
Labels: requires:repro
