### ISSUE TITLE
[liblzma] Build error on x64-windows

### ISSUE THREAD

**Issue by JibinCJoy1** [microsoft/vcpkg#38027] opened 2024-04-07 16:50 UTC
Copy issue body from E:/vcpkg/installed/vcpkg/issue_body.md

E:\vcpkg>vcpkg install opencv
Computing installation plan...
The following packages will be built and installed:
  * liblzma:x64-windows@5.4.4
  * libpng:x64-windows@1.6.43
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows@1.3.2
    opencv[core,default-features]:x64-windows@4.8.0#1
  * opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows@4.8.0#15
  * protobuf:x64-windows@3.21.12#1
  * quirc:x64-windows@1.2
  * tiff[core,jpeg,lzma,zip]:x64-windows@4.6.0#4
  * vcpkg-get-python-packages:x64-windows@2024-01-24
  * zlib:x64-windows@1.3.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\jibin\AppData\Local\vcpkg\archives in 190 us. Use --debug to see more details.
Installing 1/10 liblzma:x64-windows@5.4.4...
Building liblzma:x64-windows@5.4.4...
-- Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz -> tukaani-project-xz-v5.4.4.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from E:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: E:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz
error: Failed to download from mirror set
error: https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz: failed: status code 404
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1031):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 620us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 829 ms (792754us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/liblzma/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)

error: building liblzma:x64-windows failed with: BUILD_FAILED
Elapsed time to handle liblzma:x64-windows: 929 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+liblzma
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[liblzma]+Build+error+on+x64-windows&body=Copy+issue+body+from+E%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by blb2** [comment] 2024-04-07 22:10
I ran into the same issue trying to pull in the freeimage package.

**Comment by WangWeiLin-MV** [comment] 2024-04-08 01:23
Duplicate of #37893

**Closed by WangWeiLin-MV** 2024-04-08 01:23 UTC
Labels: depends:upstream-changes
