### ISSUE TITLE
[liblzma] Build error on x64-linux

### ISSUE THREAD

**Issue by AhdaiTsai** [microsoft/vcpkg#37941] opened 2024-04-03 07:32 UTC
Package: liblzma:x64-linux@5.4.4

**Host Environment**

- Host: x64-linux
- Compiler: GNU 11.4.0
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: 11ed79186 2024-04-02 (5 hours ago)

**To Reproduce**

`vcpkg install cgal`
**Failure logs**

```
-- Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz -> tukaani-project-xz-v5.4.4.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /home/ahdai_tsai/github.com/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /home/ahdai_tsai/github.com/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz --create-dirs --output /home/ahdai_tsai/github.com/vcpkg/downloads/tukaani-project-xz-v5.4.4.tar.gz.118593.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after   492570 us
[DEBUG] Trying to hash /home/ahdai_tsai/github.com/vcpkg/downloads/tukaani-project-xz-v5.4.4.tar.gz.118593.part
[DEBUG] /home/ahdai_tsai/github.com/vcpkg/downloads/tukaani-project-xz-v5.4.4.tar.gz.118593.part has hash a3255a20cd687cd38f6a44f9473a6aa55b821d41b07456da1b8778384e01b31260ffdadd6d661588e75f5fb55f75e00363d934611e8ac2170cf6cd44683b7906
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz
File: /home/ahdai_tsai/github.com/vcpkg/downloads/tukaani-project-xz-v5.4.4.tar.gz.118593.part
Expected hash: c28461123562564e030f3f733f078bc4c840e87598d9f4b718d4bca639120d8133f969c45d7bdc62f33f081d789ec0f14a1791fb7da18515682bfe3c0c7362e0
Actual hash: a3255a20cd687cd38f6a44f9473a6aa55b821d41b07456da1b8778384e01b31260ffdadd6d661588e75f5fb55f75e00363d934611e8ac2170cf6cd44683b7906
[DEBUG] /mnt/vss/_work/1/s/src/vcpkg/base/downloads.cpp(1031): 
[DEBUG] Time in subprocesses: 492570us
[DEBUG] Time in parsing JSON: 5us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 355us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 515 ms (514140us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/liblzma/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)

**Comment by AhdaiTsai** [comment] 2024-04-03 07:35
seems https://github.com/tukaani-project/xz has been disabled 😅

<img width="498" alt="image" src="https://github.com/microsoft/vcpkg/assets/91944788/1f7d9dea-d21b-4180-8ad5-a7d1aee1e784">

**Comment by Cheney-W** [comment] 2024-04-03 07:38
Duplicate of #37893

**Closed by Cheney-W** 2024-04-03 07:38 UTC
Labels: depends:upstream-changes

**Comment by zzz-dog** [comment] 2024-04-09 02:58
I have found a workaround to fix this failure. 
Since liblzma has moved to https://github.com/xz-mirror/xz
just open portfile.cmake in your \vcpkg\ports\liblzma\ and replace tukaani-project with xz-mirror in line 3.
then vcpkg will download archives from the new url.
