### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by ZhangWeinian** [microsoft/vcpkg#39992] opened 2024-07-20 11:16 UTC
Package: openssl:x64-windows@3.3.1#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.40.33812.0
-    vcpkg-tool version: 2024-06-10-02590c430e4ed9215d27870138c2e579cc338772
    vcpkg-scripts version: 198d68dbc 2024-07-18 (2 days ago)

**To Reproduce**

`vcpkg install openssl:x64-windows --x-use-aria2`

**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.3.1.tar.gz.
-- Cleaning sources at E:/Project/vcpkg/buildtrees/openssl/src/nssl-3.3.1-1ae1909b44.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Project/vcpkg/downloads/openssl-openssl-openssl-3.3.1.tar.gz
-- Applying patch cmake-config.patch
-- Applying patch command-line-length.patch
-- Applying patch script-prefix.patch
-- Applying patch asm-armcap.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at E:/Project/vcpkg/buildtrees/openssl/src/nssl-3.3.1-1ae1909b44.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "D:/Software/VS 2022/VC/Tools/MSVC/14.40.33807/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: E:/Project/vcpkg/buildtrees/openssl/x64-windows-dbg
    See logs for more information:
      E:\Project\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log
      E:\Project\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:74 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:69 (include)
  scripts/ports.cmake:192 (include)



```

<details><summary>E:\Project\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log</summary>

```
cl: 命令行 warning D9025 :正在重写“/Zi”(用“/Z7”)
NMAKE : fatal error U1077: “"D:\Software\VS 2022\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"E:\\Project\\vcpkg\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"E:\\Project\\vcpkg\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"E:\\Project\\vcpkg\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"D:\Software\VS 2022\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs”: 返回代码“0x2”
Stop.
```
</details>

<details><summary>E:\Project\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log</summary>

```
	"D:\Software\VS 2022\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\nmake.exe" /LU                 depend
	"D:\Software\VS 2022\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs
	"D:\Software\VS 2022\VC\Tools\MSVC\14.40.33807\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"E:\\Project\\vcpkg\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"E:\\Project\\vcpkg\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"E:\\Project\\vcpkg\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c"
cversion.c
crypto\cversion.c(60): warning C4129: “V：: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “T：: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “M：: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “H：: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “c：: 不可识别的字符转义序列
crypto\cversion.c(60): error C2143: 语法错误: 缺少“;”(在“常数”的前面)
crypto\cversion.c(60): error C2143: 语法错误: 缺少“;”(在“字符串”的前面)
```
</details>

**Comment by sfhacker** [comment] 2024-07-20 15:09
This is NOT sustainable!

**Comment by ZhangWeinian** [comment] 2024-07-21 15:13
I referred to the discussions of people who had the same problem before, and it seems that this error has been fixed, but I unexpectedly encountered it! I tried some of the methods they proposed, but still couldn't install them correctly. At present, reinstalling Visual Studio 2022 in a path without spaces appears to be the final attempt……

**Comment by Cheney-W** [comment] 2024-07-22 02:53
What's the result after you reinstalled VS2022 in a path without space?

**Comment by ZhangWeinian** [comment] 2024-07-22 03:29
Currently, Visual Studio 2022 has not been reinstalled as it is being frequently used😂😂😂

**Comment by ZhangWeinian** [comment] 2024-07-22 03:30
> 在没有空间的路径中重新安装 VS2022 后会有什么结果？
Currently, Visual Studio 2022 has not been reinstalled as it is being frequently used😂😂😂

**Comment by ZhangWeinian** [comment] 2024-07-22 03:31
> What's the result after you reinstalled VS2022 in a path without space?

Currently, Visual Studio 2022 has not been reinstalled as it is being frequently used😂

**Comment by Cheney-W** [comment] 2024-07-22 09:47
Duplicate of https://github.com/microsoft/vcpkg/issues/38723

**Closed by Cheney-W** 2024-07-22 09:47 UTC
Labels: requires:repro
