### ISSUE TITLE
vcpkg_from_git does not work with SSH URL

### ISSUE THREAD

**Issue by jean-marc** [microsoft/vcpkg#6126] opened 2019-04-17 16:25 UTC
Environment: Win 7 32 bit, VS17, vcpkg version:
Vcpkg package management program version 2018.11.23-nohash

Creating a header-only library ports\test\portfile.cmake
```
vcpkg_from_git(
    ...
    URL ssh://git@example.org/repo/test.git
    ...
)
```
when running .\vcpkg build test I get this error message:
```
$ ./vcpkg.exe build test
-- Fetching ssh://git@cexample.org/repo/test.git...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: C:/Users/user/vcpkg/downloads/tools/git-2.20.0-windows/mingw32/bin/git.exe;fetch;ssh://git@example.org/repo/test.git;0;--depth;1;-n
    Working Directory: C:/Users/user/vcpkg/downloads/git-tmp
    Error code: 128
    See logs for more information:
      C:\Users\user\vcpkg\buildtrees\test\git-fetch-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_git.cmake:98 (vcpkg_execute_required_process)
  ports/pool-allocator/portfile.cmake:4 (vcpkg_from_git)
  scripts/ports.cmake:71 (include)
```
looking at git-fetch-err.log:
```
error: cannot spawn ssh: No such file or directory
fatal: unable to fork
```
The same repository can be cloned on the command-line without problem:
```
git clone ssh://git@example.org/repo/test.git
```
The HTTPS URL works fine

**Comment by Voskrese** [comment] 2019-04-17 17:35
[https://stackoverflow.com/questions/2643502/how-to-solve-permission-denied-publickey-error-when-using-git](url)

Add your key to your account via the website.
[https://github.com/settings/keys](url)

**Comment by jean-marc** [comment] 2019-04-17 17:41
I am not using github, the repository is hosted locally, git fails before starting the SSH connection.

**Comment by Voskrese** [comment] 2019-04-17 17:45
local **server** ssh and git?

ssh -vT git@github.com

ssh -vT git@ **localhost** or 127.0.0.1

**Comment by jean-marc** [comment] 2019-04-17 17:49
the git repository in on a private LAN, I just changed the name to example.org in my report.
The crux is that I can clone the repository with the same URL on the command line but run with cmake it fails because git cannot spawn the ssh process.

**Comment by Voskrese** [comment] 2019-04-17 17:57
https://github.com/Voskrese/vcpkg/blob/master/ports/labsound/portfile.cmake

**example**

```
set(GIT_URL "https://github.com/LabSound/LabSound.git")
set(GIT_REV "1567ec802d1525569ad3a46c97ef054679714fa7")
set(SOURCE_PATH ${CURRENT_BUILDTREES_DIR}/src/LabSound)
if(NOT EXISTS "${SOURCE_PATH}/.git")
	message(STATUS "Cloning and fetching submodules")
	vcpkg_execute_required_process(
	  COMMAND ${GIT} clone --recurse-submodules ${GIT_URL} ${SOURCE_PATH}
	  WORKING_DIRECTORY ${SOURCE_PATH}
	  LOGNAME clone
)
```

```
vcpkg_execute_required_process(
	  COMMAND ${GIT}
```

**Comment by jean-marc** [comment] 2019-04-17 17:59
this does not use a SSH git URL, it uses HTTPS, I don't have that option in my environment

**Comment by Voskrese** [comment] 2019-04-17 18:01
~~set(GIT_URL "https://github.com/LabSound/LabSound.git")~~
Is this a problem? it's just a link, replace
set(GIT_URL "ssh://git@example.org/repo/test.git")

**Comment by jean-marc** [comment] 2019-04-17 18:04
OK I will try that thanks, 
so I should not rely on vcpkg_from_git()?

**Comment by Voskrese** [comment] 2019-04-17 18:08
Only one thing, there will be a password request via SSH, how to handle it ... I don’t know

**Comment by jean-marc** [comment] 2019-04-17 18:46
sorry same problem, as soon as I replace git URL by ssh://git@... I get the same error:
```
error: cannot spawn ssh: No such file or directory
fatal: unable to fork
```

**Comment by Voskrese** [comment] 2019-04-17 18:54
set(GIT_URL "ssh://git@example.org/repo/rest")

**Comment by jean-marc** [comment] 2019-04-17 18:57
I have the correct URL, the problem is that git cannot use the ssh transport protocol when invoking from CMake hence the message

**Comment by Voskrese** [comment] 2019-04-17 19:21
no problem with the protocol

`edit https://github.com/Voskrese/vcpkg/blob/master/ports/labsound/portfile.cmake`

replace
set(GIT_URL "https://github.com/LabSound/LabSound.git")
to 
set(GIT_URL "ssh://git@github.com/LabSound/LabSound.git")

there is a problem as I said with access

error
```

Клонирование в «E:/tools/vcpkg/buildtrees/labsound/src/LabSound»…
git@github.com: Permission denied (publickey).
```

**Comment by jean-marc** [comment] 2019-04-17 19:28
well it seems our environment is different

**Comment by jean-marc** [comment] 2019-04-17 21:08
the fix seems to be setting the path to `ssh.exe`:
```
set(ENV{PATH} "C:/Users/user/vcpkg/downloads/tools/git-2.20.0-windows/usr/bin/"
vcpkg_from_git(
...)
```
so that `git.exe` knows how to spawn the SSH process

**Comment by Voskrese** [comment] 2019-04-17 23:01
good, that all is well

closing?

**Comment by jean-marc** [comment] 2019-04-18 16:02
I wouldn't think so, it took me while to figure it out, what would prevent
somebody else to run into the same problem?

**Comment by Voskrese** [comment] 2019-04-18 23:17
it's your business. ideology is as follows. time you closed. then the problem is solved, and having found a similar problem by searching, the user will know that these are solutions for his similar problem.

**Comment by cenit** [comment] 2019-04-21 17:31
vcpkg filters the environment variable “PATH” from the system, so technically it’s different launching from the command line and from inside vcpkg. Or better: vcpkg filters everything from the environment apart whitelisted variables. And path is not one of them.
The choice was done to “clean up” messy user environment and being able to cleanly define new toolchains. Yours (like ninja+cuda not working because relying on path) is a problem that arise from this PATH loss...

**Comment by jean-marc** [comment] 2019-04-22 16:23
Thanks for the information, just ran a test setting the GIT_SSH variable:
```
set(ENV{GIT_SSH} "C:/Users/user/vcpkg/downloads/tools/git-2.20.0-windows/usr/bin/ssh.exe")
```
and it works, would it make sense to whitelist this more specific variable?
On a separate note, setting the URL to a file:///... triggers a similar error:
```
error: cannot spawn sh: No such file or directory
fatal: unable to fork
```
but git does not use a matching environment variable (GIT_SH?): https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables#_miscellaneous

**Comment by JackBoosY** [comment] 2020-04-02 02:44
Close this issue via #9446 merged.

**Closed by JackBoosY** 2020-04-02 02:44 UTC
Labels: vcpkg feature
