### ISSUE TITLE
[x264] build failure

### ISSUE THREAD

**Issue by ilongshan** [microsoft/vcpkg#23933] opened 2022-04-02 06:20 UTC
**Host Environment**
- OS: Mac
- Compiler: Apple clang version 13.0.0 (clang-1300.0.29.3)

**To Reproduce**
`./vcpkg install`
```
{
  "name": "test",
  "version-string": "0.0.1",
  "dependencies": [
    {
      "name": "ffmpeg",
      "default-features": true,
      "features": [
        "x264"
      ]
    }
  ]
}
```

**Failure logs**
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
    Command failed: /bin/bash -c "V=1 ./../src/f21da01154-d285e80d59.clean/configure  \"--enable-strip\" \"--disable-lavf\" \"--disable-swscale\" \"--disable-avs\" \"--disable-ffms\" \"--disable-gpac\" \"--disable-lsmash\" \"--enable-debug\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/Users/xxx/yyy/cmake-build-debug/vcpkg_installed/arm64-osx/debug\""
    Working Directory: /Users/xxx/yyy/third_party/vcpkg/buildtrees/x264/arm64-osx-dbg
    Error code: 126
    See logs for more information:
      /Users/xxx/yyy/third_party/vcpkg/buildtrees/x264/config-arm64-osx-dbg-err.log
```

**Additional context**
[config-arm64-osx-dbg-err.log](https://github.com/microsoft/vcpkg/files/8401945/config-arm64-osx-dbg-err.log)

**Comment by Adela0814** [comment] 2022-04-02 06:49
Error message: `/bin/bash: ./../src/f21da01154-d285e80d59.clean/configure: Permission denied`. please check the permission.

**Comment by ilongshan** [comment] 2022-04-02 06:57
```
$ ls -lh configure 
-rw-r--r--  1 dulongshan  staff    53K Apr  2 14:14 configure
```

The permission is incorrect, because it is not executable.

**Comment by ilongshan** [comment] 2022-04-02 15:48
The file permission should be chanaged to be executable when packaging

**Comment by ilongshan** [comment] 2022-04-02 15:59
This file is in the tar. I cannot modify it. Hope its permission can be change when packaging

**Comment by dg0yt** [comment] 2022-04-04 05:33
The portfile could change the bits with `file(CHMOD ...)`.

**Comment by ilongshan** [comment] 2022-07-20 13:33
@Adela0814 I have tried to change the permission of configure with file(CHMOD ...) and it can be installed on Mac M1 now.
```
file(CHMOD "${SOURCE_PATH}/configure" FILE_PERMISSIONS
    OWNER_READ OWNER_WRITE OWNER_EXECUTE
    GROUP_READ
    WORLD_READ
)  
```

**Comment by dg0yt** [comment] 2022-08-04 05:42
I assume this was a purely local issue. I don't see this elsewhere (linux, x64-osx).

**Comment by ilongshan** [comment] 2022-08-04 06:44
I have digged into this issue to some extent, and find that the permission of the file configure is changed when applied the patch of ports/x264/uwp-cflags.patch in function z_vcpkg_apply_patches. The function calling chain is vcpkg_from_github -> vcpkg_extract_source_archive_ex -> vcpkg_extract_source_archive -> z_vcpkg_apply_patches. In z_vcpkg_apply_patches, for every path the function vcpkg_execute_in_download_mode will be called with the following parameter:
```
COMMAND "${GIT}" -c core.longpaths=true -c core.autocrlf=false --work-tree=. --git-dir=.git apply "${absolute_patch}" --ignore-whitespace --whitespace=nowarn --verbose
```
which for this x264 port is:
```
 git -c core.longpaths=true -c core.autocrlf=false --work-tree=. --git-dir=.git apply ~/Work/opensource/CodecLabs/QCello/third_party/vcpkg/ports/x264/uwp-cflags.patch --ignore-whitespace --whitespace=nowarn --verbose
```
After this command is applied, the permission of the file configure is changed from 755 to 644.

And with some expermients, I fond that it is related to the parameters "--work-tree=." and "--git-dir=.git". If remove these two parameters and rerun it again, the patch can be applied successifully and keeps the permission of the file configure unchanged:
```
 git -c core.longpaths=true -c core.autocrlf=false apply ~/Work/opensource/CodecLabs/QCello/third_party/vcpkg/ports/x264/uwp-cflags.patch --ignore-whitespace --whitespace=nowarn --verbose
```

I have read the manual of git and googled it, but cannot find the reason behand it or solution to it.


Hope this additional information can help to resolve this issue.

**Comment by dg0yt** [comment] 2022-08-04 07:58
That's really interesting. I still think it is a local issue because the patch is applied in the same way in vcpkg CI, and in our local machines, without problem. Which `git` is executed on your machine? Maybe it is some wrapper?

**Comment by ilongshan** [comment] 2022-09-15 09:23
Any update?

**Comment by ilongshan** [comment] 2022-11-23 00:26
Any update?

**Comment by sfhacker** [comment] 2022-11-23 05:00
You closed this issue & now you are still having issues?

**Comment by ilongshan** [comment] 2022-11-23 11:17
I deleted PATCHES part of x264/portfile.cmake mannually, so I can install x264. But it is just a workaround. This issue still exists.

**Comment by MonicaLiu0311** [comment] 2023-02-15 07:45
```
vcpkg@VCPKGMM-12 vcpkg % sw_vers
ProductName:    macOS
ProductVersion: 11.5.2
BuildVersion:   20G95
```

I have not reproduced your issue, the environment is as above; and I think this is a local issue, because nothing similar to yours has occurred.

Sorry, since there is no new progress on this issue for more than 3 months and no feedback from other users, I will close this issue, sorry again.

**Closed by MonicaLiu0311** 2023-02-15 07:45 UTC
Labels: info:manifests, category:community-triplet
