### ISSUE TITLE
For the needs of vcpkg use

### ISSUE THREAD

**Issue by brinkqiang** [microsoft/vcpkg#27002] opened 2022-09-27 02:01 UTC
I need a function that can easily get a specific version of a library.
For example: vcpkg vlist boost He can print out all versions of boost in the warehouse for me to choose, which can greatly improve work efficiency.

**Comment by Neumann-A** [comment] 2022-09-27 11:28
You mean:

https://github.com/microsoft/vcpkg/blob/master/versions/b-/boost.json

Just lookup the corresponding version file.

**Comment by brinkqiang** [comment] 2022-09-27 11:36
I mean the act of installing a specific version of a library is very common. Is it possible to provide a corresponding command to operate. Instead of me going to do these things manually.

**Comment by Neumann-A** [comment] 2022-09-27 11:52
> I mean the act of installing a specific version of a library is very common. Is it possible to provide a corresponding command to operate. Instead of me going to do these things manually.

Not in classic mode. You want to use vcpkg in manifest mode if you want to install a specific version.

**Comment by dg0yt** [comment] 2022-09-28 05:49
This turns into a FAQ. https://github.com/microsoft/vcpkg/discussions/25622.

**Comment by LilyWangLL** [comment] 2022-09-28 06:59
Closed as duplicate of https://github.com/microsoft/vcpkg/discussions/25622.

**Closed by LilyWangLL** 2022-09-28 06:59 UTC
Labels: category:question
