### ISSUE TITLE
[lerc] Build error: “min”: is not a member of 'std'

### ISSUE THREAD

**Issue by yaozw06** [microsoft/vcpkg#28866] opened 2023-01-11 03:09 UTC
**Host Environment**

- OS:  Windows 11
- Compiler: Visual Studio 2017

**To Reproduce**

`./vcpkg install lerc:x64-windows`

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
    lerc[core]:x64-windows -> 4.0
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\NING MEI\AppData\Local\vcpkg\archives in 125.5 us. Use --debug to see more details.
Installing 1/1 lerc:x64-windows...
Building lerc[core]:x64-windows...
-- Downloading https://github.com/Esri/lerc/archive/v4.0.0.tar.gz -> Esri-lerc-v4-36fe453b.0.0.tar.gz...
-- Cleaning sources at D:/devel/vcpkg/buildtrees/lerc/src/v4.0.0-ce5de9f790.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/devel/vcpkg/downloads/Esri-lerc-v4-36fe453b.0.0.tar.gz
-- Applying patch create_package.patch
-- Using source at D:/devel/vcpkg/buildtrees/lerc/src/v4.0.0-ce5de9f790.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: D:/devel/vcpkg/downloads/tools/cmake-3.25.0-windows/cmake-3.25.0-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/devel/vcpkg/buildtrees/lerc/x64-windows-dbg
    See logs for more information:
      D:\devel\vcpkg\buildtrees\lerc\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/lerc/portfile.cmake:14 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building lerc:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+lerc
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[lerc]+Build+error
Include '[lerc] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: c30de8e13 2023-01-10 (4 hours ago)

**Additional context**

[1/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\BitMask.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\BitMask.cpp
[2/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\RLE.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\RLE.cpp
[3/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_UnitTypes.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_UnitTypes.cpp
[4/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_Compression.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Compression.cpp
[5/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_Predictor.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Predictor.cpp
[6/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_Lerc2Ext.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Lerc2Ext.cpp
FAILED: CMakeFiles/Lerc.dir/src/LercLib/fpl_Lerc2Ext.cpp.obj 
C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_Lerc2Ext.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Lerc2Ext.cpp
D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Lerc2Ext.cpp(216): error C2039: “min”: is not a member of 'std'
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\vector(20): note: 参见“std”的声明
D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_Lerc2Ext.cpp(216): error C2065: “min”: undeclared identifier 
[7/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_EsriHuffman.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_EsriHuffman.cpp
FAILED: CMakeFiles/Lerc.dir/src/LercLib/fpl_EsriHuffman.cpp.obj 
C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\fpl_EsriHuffman.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_EsriHuffman.cpp
D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_EsriHuffman.cpp(350): error C2039: “min”: 不是“std”的成员
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Tools\MSVC\14.16.27023\include\vector(20): note: 参见“std”的声明
D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\fpl_EsriHuffman.cpp(350): error C2065: “min”: 未声明的标识符
[8/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Lerc1Decode\BitStuffer.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Lerc1Decode\BitStuffer.cpp
[9/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\BitStuffer2.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\BitStuffer2.cpp
[10/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Huffman.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Huffman.cpp
[11/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Lerc1Decode\CntZImage.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Lerc1Decode\CntZImage.cpp
[12/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Lerc_c_api_impl.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Lerc_c_api_impl.cpp
[13/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Lerc.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Lerc.cpp
[14/16] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DLERC_EXPORTS  /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++17 /showIncludes /FoCMakeFiles\Lerc.dir\src\LercLib\Lerc2.cpp.obj /FdCMakeFiles\Lerc.dir\ /FS -c D:\devel\vcpkg\buildtrees\lerc\src\v4.0.0-ce5de9f790.clean\src\LercLib\Lerc2.cpp
ninja: build stopped: subcommand failed.

**Comment by Cheney-W** [comment] 2023-01-11 03:33
Duplicate of https://github.com/microsoft/vcpkg/issues/27962

**Closed by Cheney-W** 2023-01-11 03:33 UTC
Labels: category:port-bug
