### ISSUE TITLE
Build customizations run before VCPKG

### ISSUE THREAD

**Issue by spectre-ns** [microsoft/vcpkg#26035] opened 2022-07-28 14:46 UTC
**Describe the bug**
When using the CUDA insight tool, the tool attempts to build files before vcpkg run.

**Environment**
- OS: Windows
- Compiler: VS 2019

**To Reproduce**
CUDA 11.2 build configuration enabled
Enable CUDA on a source file
Run in manifest mode and rebuild solution

**Expected behavior**
VCPKG installs all dependencies prior to the build starting

**Failure logs**
[Logs.txt](https://github.com/microsoft/vcpkg/files/9211497/Logs.txt)

**Additional context**

**Comment by spectre-ns** [comment] 2022-07-28 19:37
The work around was to add this command to the pre-build options:

$(VcpkgRoot)/vcpkg.exe install --triplet=$(VcpkgTriplet)

Seems uber hacky but it works.

**Comment by Adela0814** [comment] 2022-07-29 02:31
Could you please provide a simple project?

**Comment by spectre-ns** [comment] 2022-08-01 21:25
[ConsoleApplication6.zip](https://github.com/microsoft/vcpkg/files/9237499/ConsoleApplication6.zip)

**Comment by spectre-ns** [comment] 2022-08-01 21:27
That should build using vcpkg manifest but with CUDA 11.2 installed it tries to run the build customization before vcpkg. Shouldn't vcpkg be run before any part of the build starts? I could add any number of build customizations and I would hope vcpkg systematically works with all of them unless they directly interfere with vcpkg.

**Comment by spectre-ns** [comment] 2022-08-03 23:00
@Adela0814

**Comment by Cheney-W** [comment] 2022-08-04 07:44
Sorry, currently the running mechanism of manifest mode in msbuild project is only triggered by build command, it cannot be started before build command.

**Comment by Adela0814** [comment] 2022-09-09 08:22
Close this issue, this is not a bug.

**Closed by Adela0814** 2022-09-09 08:22 UTC
Labels: category:question
