### ISSUE TITLE
[ffmpeg] Build error x64-windows-static

### ISSUE THREAD

**Issue by ericCHxia** [microsoft/vcpkg#27046] opened 2022-09-30 05:34 UTC
**Host Environment**

- OS: windows
- Compiler: MSVC 19.28.29921

**To Reproduce**

`.\vcpkg.exe install ffmpeg[all,all-gpl,all-nonfree]:x64-windows-static`

**Failure logs**

vcpkg\buildtrees\ffmpeg\x64-windows-static-rel\ffbuild\config.log
```
BEGIN /c/Users/eric/AppData/Local/Temp/ffconf.BjKjJquQ/test.c
    1	int main(void){ return 0; }
END /c/Users/eric/AppData/Local/Temp/ffconf.BjKjJquQ/test.c
cl.exe @C:/vcpkg/buildtrees/ffmpeg/x64-windows-static-rel/cflags.rsp -nologo -DHAVE_UNISTD_H=0 -c -Fo/c/Users/eric/AppData/Local/Temp/ffconf.BjKjJquQ/test.o /c/Users/eric/AppData/Local/Temp/ffconf.BjKjJquQ/test.c
test.c
C:\Users\eric\AppData\Local\Temp\ffconf.BjKjJquQ\test.c : fatal error C1083: Cannot open compiler generated file: 'C:\c\Users\eric\AppData\Local\Temp\ffconf.BjKjJquQ\test.o': No such file or directory
C compiler test failed.
```
[full-config.log](https://github.com/microsoft/vcpkg/files/9681063/config.log)

**Additional context**

It's clear that the path `/c/Users/eric/AppData/Local/Temp/ffconf.BjKjJquQ/test.o` in the msys2 was erroneously translated to the path `C:\c\Users\eric\AppData\Local\Temp\ffconf.BjKjJquQ\test.o` by MSVC complier(cl.exe).

I have try to update "vcpkg". But that's invalid.

And I found that the problem is in the msvc instead of shell. 

I have fixed above problem by creating a SymbolicLink. It's not elegent.

But I face another error in compiling.

[build-x64-windows-static-rel-out.log](https://github.com/microsoft/vcpkg/files/9681384/build-x64-windows-static-rel-out.log)
[build-x64-windows-static-rel-err.log](https://github.com/microsoft/vcpkg/files/9681382/build-x64-windows-static-rel-err.log)

Finally, I success in building package and fixed above problem by running `make` in the "Developer PowerShell for VS 2019"

```
$env:PATH=$env:PATH+";C:\msys64\usr\bin;C:\msys64\mingw64\bin"
make
```

**Comment by sryze** [comment] 2022-10-13 08:10
I ran into the same issue with x64-windows build.

```
BEGIN /c/Users/myuser/AppData/Local/Temp/ffconf.v3JqVM0r/test.c
    1	int main(void){ return 0; }
END /c/Users/myuser/AppData/Local/Temp/ffconf.v3JqVM0r/test.c
cl.exe @E:/Tools/vcpkg/buildtrees/ffmpeg/x64-windows-rel/cflags.rsp -nologo -DHAVE_UNISTD_H=0 -c -Fo/c/Users/myuser/AppData/Local/Temp/ffconf.v3JqVM0r/test.o /c/Users/myuser/AppData/Local/Temp/ffconf.v3JqVM0r/test.c
test.c
C:\Users\myuser\AppData\Local\Temp\ffconf.v3JqVM0r\test.c : fatal error C1083: Cannot open compiler generated file: 'E:\c\Users\myuser\AppData\Local\Temp\ffconf.v3JqVM0r\test.o': No such file or directory
C compiler test failed.
```

**Comment by sryze** [comment] 2022-10-15 10:50
I was able to overcome the configure script error in https://github.com/microsoft/vcpkg/pull/27243, however, now there is an error during the link step of libavutil because apparently it uses the wrong command - cl.exe instead of link.exe (or cl.exe with /link flag):

```
cl.exe -dll -def:libavutil/avutil-56.def -implib:libavutil/avutil.lib -libpath:libavcodec -libpath:libavdevice -libpath:libavfilter -libpath:libavformat -libpath:libavresample -libpath:libavutil -libpath:libpostproc -libpath:libswscale -libpath:libswresample @E:/Tools/vcpkg/buildtrees/ffmpeg/x64-windows-rel/ldflags.rsp -nologo     -debug  -Felibavutil/avutil-56.dll libavutil/adler32.o libavutil/aes.o libavutil/aes_ctr.o libavutil/audio_fifo.o libavutil/avsscanf.o libavutil/avstring.o libavutil/base64.o libavutil/blowfish.o libavutil/bprint.o libavutil/buffer.o libavutil/camellia.o libavutil/cast5.o libavutil/channel_layout.o libavutil/color_utils.o libavutil/cpu.o libavutil/crc.o libavutil/des.o libavutil/dict.o libavutil/display.o libavutil/dovi_meta.o libavutil/downmix_info.o libavutil/encryption_info.o libavutil/error.o libavutil/eval.o libavutil/fifo.o libavutil/file.o libavutil/file_open.o libavutil/film_grain_params.o libavutil/fixed_dsp.o libavutil/float_dsp.o libavutil/frame.o libavutil/hash.o libavutil/hdr_dynamic_metadata.o libavutil/hmac.o libavutil/hwcontext.o libavutil/hwcontext_d3d11va.o libavutil/hwcontext_dxva2.o libavutil/imgutils.o libavutil/integer.o libavutil/intmath.o libavutil/lfg.o libavutil/lls.o libavutil/log.o libavutil/log2_tab.o libavutil/lzo.o libavutil/mastering_display_metadata.o libavutil/mathematics.o libavutil/md5.o libavutil/mem.o libavutil/murmur3.o libavutil/opt.o libavutil/parseutils.o libavutil/pixdesc.o libavutil/pixelutils.o libavutil/random_seed.o libavutil/rational.o libavutil/rc4.o libavutil/reverse.o libavutil/ripemd.o libavutil/samplefmt.o libavutil/sha.o libavutil/sha512.o libavutil/slicethread.o libavutil/spherical.o libavutil/stereo3d.o libavutil/tea.o libavutil/threadmessage.o libavutil/time.o libavutil/timecode.o libavutil/tree.o libavutil/twofish.o libavutil/tx.o libavutil/tx_double.o libavutil/tx_float.o libavutil/tx_int32.o libavutil/utils.o libavutil/video_enc_params.o libavutil/x86/cpu.o libavutil/x86/cpuid.o libavutil/x86/emms.o libavutil/x86/fixed_dsp.o libavutil/x86/fixed_dsp_init.o libavutil/x86/float_dsp.o libavutil/x86/float_dsp_init.o libavutil/x86/imgutils.o libavutil/x86/imgutils_init.o libavutil/x86/lls.o libavutil/x86/lls_init.o libavutil/x86/pixelutils.o libavutil/x86/pixelutils_init.o libavutil/xga_font_data.o libavutil/xtea.o  user32.lib bcrypt.lib 
LINK : fatal error LNK1561: entry point must be defined
```

If I try to manually run the above command with `/link` flag, it works.

Upon digging further, I found that the build.sh ffmpeg/build.sh script does not pass `--toolchain=msvc` to the configure script. It loks like `VCPKG_DETECTED_MSVC` is not being set anywhere. Any idea why ffmpeg build script uses that variable? I can't find documentation for it anywhere.

**Comment by MonicaLiu0311** [comment] 2023-02-14 10:19
Win10
VS 2022
```
PS E:\vcpkg02> ./vcpkg version
vcpkg package management program version 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75

See LICENSE.txt for license information.
```

I still can't reproduce your problem with the latest vcpkg, and this problem seems to be caused by the damage of vcpkg, and other users[ solved it](https://github.com/microsoft/vcpkg/pull/27243#issuecomment-1298344821) after re-cloning. 

So, I will close this issue, if it is still an issue, please reopen it.

**Closed by MonicaLiu0311** 2023-02-14 10:19 UTC
Labels: requires:repro
