### ISSUE TITLE
Visual Studio integration conflicts with local solution projects

### ISSUE THREAD

**Issue by lazyhamster** [microsoft/vcpkg#4562] opened 2018-10-25 09:04 UTC
There is issue with vcpkg VS integration and projects that have local copies of libraries already installed in vcpkg. If solution have a base project that depends on some library that simultaneously installed in vcpkg and present is same solution as dependent project then during linking base project will be linked with vcpkg version of the library and not with local solution project. Which I think is wrong behavior.

I will describe in more details.
Let's assume we have a console app that uses custom built zlib as a dependency (or any other lib that exists vcpkg repository).  We have a solution with 2 projects - app and zlib. In Visual Studio can add reference to zlib project to app project. And during app linking VS will automatically add path to zlib.lib import library to linker.
I have the following list of libraries for the linker for app project:

1. Standard Libs (kernel32, user32, etc)
2. Custom Libs from project settings.
3. Dependency Libs (e.g. $SolutionDir\zlib\bin\zlib.lib in our case)

Now we install vcpkg, install zlib in there and enable integration. Integration injects wildcarded path to lib dir (something like vcpkg_root\installed\x86-windows\lib\*.lib). And this path is injected before dependency libs. We have the following list of libs for the linker.

1. Standard Libs (kernel32, user32, etc)
2. Custom Libs from project settings.
3. Vcpkg libraries.
4. Dependency Libs (e.g. $SolutionDir\zlib\bin\zlib.lib in our case)

Because of the injection order zlib.lib from vcpkg repository is checked first and linked to our console app. Lib file from local zlib project is ignored. We actually end up with 2 copies of zlib: one from vcpkg and one from local project. Which is not in my opinion a desired outcome. Especially if we have some non-standard build for the library and want to use it.

The obvious solution would be to inject vcpkg lib path to the end of the list, after all dependent libraries. But I have no idea if it possible at all. Didn't find anything related to how set order for Link->AdditionalDependencies MSBuild items.

**Comment by mick-p1982** [comment] 2019-03-12 18:00
@Larrylll This is not a feature, this is a bug. And a very serious bug. It means building projects (e.g. CMake scripts) can only be done by abandoning vcpkg like so: `vcpkg remove opencv libusb`. What then is the point of vcpkg?

The integration is automatic. It's very hard to diagnose, since projects/solutions don't even get to opt into vcpkg. It's not obvious what is even happening when there is LNK2005 because there are multiple definitions, because there are multiple instances of the same libraries being linked, thanks to vcpkg. It's not transparent how vcpkg finds libraries either...

In this (https://github.com/HipsterSloth/PSVRTracker/issues/13) case the project links against `deps\local\staticlib\opencv_core330d.lib` which is a path to a real file of the same name. It's not just linking against the name of the `lib` file, but a path. And yet, not only does vkpkg inject its own library (so there are **2** of the same library being linked, and the linker attempts to include both, and so fails to link) IT EVEN INJECTS opencv_core3**2**0d.lib, which is not even the same library. (Notice vkpkg's name is 320d, not 330d.)

Here the project is expressly linking against its own file, and vcpkg is injecting its own library, on top of the other. And to reiterate, it's not even the same library.

Note, by coincidence, earlier the project was linking to its own 320d.lib, and somehow this did not fail to link. In that case, both `lib` files were named 320d, and it's anyone's guess which was used to link, if not both.

Vcpkg is a fallback mechanism, because developers cannot just alter received projects to satisfy vcpkg. The local library may be customized. And in any case, it took days of head-scratching to figure what the hell was happening. Vcpkg is not in the project's directories or command-line. The only way to see its injection is in the build output, that prints the real command line. And that can be a very, very long line of text, that does not wrap in Visual Studio's console. So it can only be seen by horizontally scrolling. Vcpkg does not announce itself in the output.

**Comment by Cheney-W** [comment] 2021-08-13 07:45
I can't reproduce this issue in the latest vcpkg(2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfd).

**Comment by Cheney-W** [comment] 2021-08-13 07:50
This issue should be fixed, please use the latest vcpkg. Thanks for reporting this issue to us!

**Closed by Cheney-W** 2021-08-13 07:50 UTC
Labels: category:vcpkg-bug
