### ISSUE TITLE
[angle] build error

### ISSUE THREAD

**Issue by johnco3** [microsoft/vcpkg#24901] opened 2022-05-24 18:12 UTC
**Host Environment**
- OS: Windows 11 22H2 - insider dev channel build
- Compiler: 17.2.2

**To Reproduce**
`.\vcpkg.exe install angle:x64-windows --debug`

**Failure logs**
[DEBUG] **********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.2.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
cdARN4xjKueKScMy9C6H
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\johnc\AppData\Roaming
CommandPromptType=Native
CommonProgramFiles=C:\Program Files (x86)\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=DELL-XPS
ComSpec=C:\WINDOWS\system32\cmd.exe
DevEnvDir=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\
ExtensionSdkDir=C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
Framework40Version=v4.0
FrameworkDir=C:\Windows\Microsoft.NET\Framework64\
FrameworkDir64=C:\Windows\Microsoft.NET\Framework64\
FrameworkVersion=v4.0.30319
FrameworkVersion64=v4.0.30319
HOMEDRIVE=C:
HOMEPATH=\Users\johnc
INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\cppwinrt
LIB=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.19041.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.19041.0\\um\x64
LIBPATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319
LOCALAPPDATA=C:\Users\johnc\AppData\Local
LOGONSERVER=\\DELL-XPS
NUMBER_OF_PROCESSORS=12
OS=Windows_NT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
Platform=x64
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=9e0a
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files (x86)
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Users\johnc\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\johnc\AppData\Local\Temp
TMP=C:\Users\johnc\AppData\Local\Temp
UCRTVersion=10.0.19041.0
UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
USERDOMAIN=DELL-XPS
USERDOMAIN_ROAMINGPROFILE=DELL-XPS
USERNAME=johnc
USERPROFILE=C:\Users\johnc
VCIDEInstallDir=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\
VCINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\
VCToolsInstallDir=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\
VCToolsRedistDir=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\14.32.31326\
VCToolsVersion=14.32.31326
VisualStudioVersion=17.0
VS170COMNTOOLS=C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\
VSCMD_ARG_app_plat=Desktop
VSCMD_ARG_HOST_ARCH=x64
VSCMD_ARG_TGT_ARCH=x64
VSCMD_ARG_VCVARS_VER=14.32.31326
VSCMD_VER=17.2.2
VSINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Community\
windir=C:\WINDOWS
PATH=C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\Team Tools\Performance Tools;C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Community\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\Tools\;C:\tools\vcpkg\downloads\tools\powershell-core-7.2.3-windows;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
VSLANG=1033
VSCMD_SKIP_SENDTELEMETRY=1
VCPKG_COMMAND=C:/tools/vcpkg/vcpkg.exe
WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.19041.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.19041.0
WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
WindowsSDKLibVersion=10.0.19041.0\
WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\
WindowsSDKVersion=10.0.19041.0\
X_VCPKG_RECURSIVE_DATA={}

__DOTNET_ADD_64BIT=1
__DOTNET_PREFERRED_BITNESS=64
__VSCMD_PREINIT_PATH=C:\tools\vcpkg\downloads\tools\powershell-core-7.2.3-windows;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\

[DEBUG] CreateProcessW("C:\tools\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe" -DCURRENT_PORT_DIR=C:/tools/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=C:/tools/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=C:/tools/vcpkg/packages/detect_compiler_x64-windows -D_HOST_TRIPLET=x64-windows -DCMD=BUILD -DDOWNLOADS=C:/tools/vcpkg/downloads -DTARGET_TRIPLET=x64-windows -DTARGET_TRIPLET_FILE=C:/tools/vcpkg/triplets/x64-windows.cmake -DVCPKG_BASE_VERSION=2022-05-05 -DVCPKG_CONCURRENCY=13 -DVCPKG_PLATFORM_TOOLSET=v143 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=C:/tools/vcpkg -DPACKAGES_DIR=C:/tools/vcpkg/packages -DBUILDTREES_DIR=C:/tools/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/tools/vcpkg/installed -DDOWNLOADS=C:/tools/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\tools\vcpkg\scripts\ports.cmake")
[DEBUG] -- Found external ninja('1.10.2').
[DEBUG] -- Configuring x64-windows
[DEBUG] [1/1] cmd /c "cd .. && "C:/tools/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe" "C:/tools/vcpkg/scripts/detect_compiler" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=C:/tools/vcpkg/packages/detect_compiler_x64-windows" "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=C:/tools/vcpkg" "-DZ_VCPKG_ROOT_DIR=C:/tools/vcpkg" "-D_VCPKG_INSTALLED_DIR=C:/tools/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF""
[DEBUG] -- The C compiler identification is MSVC 19.32.31329.0
[DEBUG] -- The CXX compiler identification is MSVC 19.32.31329.0
[DEBUG] #COMPILER_HASH#4bf8ad78607739da0dc32f9a85346888d3381057
[DEBUG] #COMPILER_C_HASH#824a8abaf9ae21a2596b4130e01c56245b2e4a08
[DEBUG] #COMPILER_C_VERSION#19.32.31329.0
[DEBUG] #COMPILER_C_ID#MSVC
[DEBUG] #COMPILER_CXX_HASH#824a8abaf9ae21a2596b4130e01c56245b2e4a08
[DEBUG] #COMPILER_CXX_VERSION#19.32.31329.0
[DEBUG] #COMPILER_CXX_ID#MSVC
[DEBUG] -- Configuring done
[DEBUG] -- Generating done
[DEBUG] CMake Warning:
[DEBUG]   Manually-specified variables were not used by the project:
[DEBUG]
[DEBUG]     BUILD_SHARED_LIBS
[DEBUG]     CMAKE_INSTALL_BINDIR
[DEBUG]     CMAKE_INSTALL_LIBDIR
[DEBUG]     _VCPKG_ROOT_DIR
[DEBUG]
[DEBUG]
[DEBUG] -- Build files have been written to: C:/tools/vcpkg/buildtrees/detect_compiler/x64-windows-rel
[DEBUG]
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 28940: cmd_execute_and_stream_data() returned 0 after  1644330 us
[DEBUG]
[DEBUG] Detected compiler hash for triplet x64-windows: 4bf8ad78607739da0dc32f9a85346888d3381057
[DEBUG] <abientries for angle:x64-windows>
[DEBUG]   001-fix-uwp.patch|1e89a9e67d6b91f43da9fb91e0d4d572559cf9607a60acc5b64cc9621aec603c
[DEBUG]   002-fix-builder-error.patch|ed6fd734073cb700917a940dcf421eaa02e529a6407ab77c8ed56072e367102e
[DEBUG]   003-fix-mingw.patch|67f12c439b0237b03baf6fbc14ccf8563134b91d8a0643bc9d78d0176360e6ff
[DEBUG]   CMakeLists.txt|ac792e7dd55b01a9e5193116e43abb39b3b5aac4952fe793c0dcf6e8b036b825
[DEBUG]   angle_commit.h|55480e2a599e318176a606eb7d970424fc8b14545ea4af5484c8116621ac5e54
[DEBUG]   cmake|3.22.2
[DEBUG]   egl-registry|f340926f6eed940cde9f457067096868029899ab09efb93c55654da502f2afa1
[DEBUG]   features|core
[DEBUG]   opengl-registry|3dc8ea3ac0eb9829360bdbcdc0ebf34cc382e4080a860733eb012c339f6b01f2
[DEBUG]   portfile.cmake|0416974444beb255ad7775ef89940c738a89b04e8f9ea07d40ba7c5d23dbb33f
[DEBUG]   ports.cmake|ab869f9ba3de5ccf4b3873e829acac6bdbe1cc38741015ab4036af75d04f7b6a
[DEBUG]   post_build_checks|2
[DEBUG]   powershell|7.2.3
[DEBUG]   third-party-zlib-far-undef.patch|d3401187d7dd3276960a8e8ca008cda942c358683a92f5e19e7a9f274c717e81
[DEBUG]   triplet|x64-windows
[DEBUG]   triplet_abi|2c399c001e38804fae09aa442cb313549a80b9e0f4b352a77f2df07ee1e71c32-c0600b35e024ce0485ed253ef5419f3686f7257cfb58cb6a24febcb600fc4b4c-4bf8ad78607739da0dc32f9a85346888d3381057
[DEBUG]   vcpkg.json|e38f5cef58a1df69f03d773a7740b6d1c0aa36721d82419d93f0c21e720a03be
[DEBUG]   vcpkg_configure_cmake|92d5900585087798667e9d0c9b23d99d039777e07de25d625857af2a61fac141
[DEBUG]   vcpkg_copy_pdbs|59e4c0d2321697848a899ba9537394cdee81725b11965c6d1341df53a6850380
[DEBUG]   vcpkg_fixup_cmake_targets|4ba01b095bb21f13622289497cc721c9b46bc336759340c9ad2b4ceb59d0660d
[DEBUG]   vcpkg_from_git|61f9fa58bd5c38d451f38f00d2d7edd6905f29946254c0485f9bc4e7f628d434
[DEBUG]   vcpkg_from_github|6f56958675e421e9fbd3974718a489e077f407f16f6e7473294e3c0f4aeceac5
[DEBUG]   vcpkg_install_cmake|6430f4795e65c4c44c545c590d431fe1a68d7444255d0da58362a267bbf6408d
[DEBUG]   zlib|cd2a8a8819b597778a64ef6822d90224ada8d891b483c57634f1f69c04680b9d
[DEBUG] </abientries>
Restored 0 packages from C:\Users\johnc\AppData\Local\vcpkg\archives in 230.8 us. Use --debug to see more details.
Installing 1/1 angle:x64-windows...
Building angle[core]:x64-windows...
[DEBUG] CreateProcessW("C:\tools\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe" -DALL_FEATURES= -DCURRENT_PORT_DIR=C:/tools/vcpkg/ports/angle -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=angle -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DZ_VCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/tools/vcpkg/scripts/toolchains/windows.cmake -DCMD=BUILD -DDOWNLOADS=C:/tools/vcpkg/downloads -DTARGET_TRIPLET=x64-windows -DTARGET_TRIPLET_FILE=C:/tools/vcpkg/triplets/x64-windows.cmake -DVCPKG_BASE_VERSION=2022-05-05 -DVCPKG_CONCURRENCY=13 -DVCPKG_PLATFORM_TOOLSET=v143 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=C:/tools/vcpkg -DPACKAGES_DIR=C:/tools/vcpkg/packages -DBUILDTREES_DIR=C:/tools/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=C:/tools/vcpkg/installed -DDOWNLOADS=C:/tools/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "C:\tools\vcpkg\scripts\ports.cmake")
-- Using cached google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz.
-- Cleaning sources at C:/tools/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/tools/vcpkg/downloads/google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz
-- Applying patch 001-fix-uwp.patch
-- Applying patch 002-fix-builder-error.patch
-- Applying patch 003-fix-mingw.patch
-- Using source at C:/tools/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean
-- Using cached C:/tools/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Extracting source C:/tools/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Applying patch third-party-zlib-far-undef.patch
-- Using source at C:/tools/vcpkg/buildtrees/angle/src/8ee76d4a8e-895bfc7289.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:158 (message):
    Command failed: C:/tools/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/tools/vcpkg/buildtrees/angle/x64-windows-dbg
    See logs for more information:
      C:\tools\vcpkg\buildtrees\angle\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:113 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:44 (vcpkg_build_cmake)
  ports/angle/portfile.cmake:64 (vcpkg_install_cmake)
  scripts/ports.cmake:146 (include)

[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 28940: cmd_execute_and_stream_data() returned 1 after 159110183 us
error: building angle:x64-windows failed with: BUILD_FAILED
[DEBUG] CreateProcessW("C:\Program Files\Git\cmd\git.exe" "--git-dir=C:\tools\vcpkg\.git" "--work-tree=C:\tools\vcpkg\.git" -c core.autocrlf=false show "--pretty=format:%h %cd (%cr)" -s --date=short HEAD)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 28940: cmd_execute_and_stream_data() returned 0 after    44594 us
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+angle
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[angle]+Build+error
Include '[angle] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-05-05-67e17c1782801cf481be9ac0b3765dff3e4bdeb8
    vcpkg-scripts version: eddbb406c 2022-05-24 (2 hours ago)

[DEBUG] D:\a\_work\1\s\src\vcpkg\install.cpp(555):
[DEBUG] Time in subprocesses: 162770056 us
[DEBUG] Time in parsing JSON: 3337 us
[DEBUG] Time in JSON reader: 2771 us
[DEBUG] Time in filesystem: 13054 us
[DEBUG] Time in loading ports: 21352 us
[DEBUG] Exiting after 2.714 min (162841674 us)

**Additional context**
Note: I have the latest git updated and boostrapped version of vcpkg along with a freshly updated compiler (which was updated to 17.2.2 earlier this morning in the hopes that it would resolve the issue, unfortunately that was not to be).  

I'm not sure if there is some alternative work around for ex downloading and linking against a prebuilt angle library.  Note, I modified my build triplet to include the v143 toolset by adding the following line `set(VCPKG_PLATFORM_TOOLSET v143)` to `triplets/x64-windows.cmake`,  but that does not seem to be the issue.
 
I added the --debug flag to the build in the hopes that it might shed some addition light.  From what I can tell the issue seems to be compiler related when bulding `SymbolTable_autogen.cpp` which results in 
```
C:\tools\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/StaticType.h(156): fatal error C1001: Internal compiler error.
(compiler file 'msc1.cpp', line 1693)
```
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8765216/install-x64-windows-dbg-out.log)

**Comment by DramaDesu** [comment] 2022-05-24 19:37
Same error

**Comment by dg0yt** [comment] 2022-05-24 20:30
Duplicate of #24704 (internal compiler error).

**Comment by Neumann-A** [comment] 2022-05-24 21:36
> Is there any known workaround you know of? 

Use VS 2019 or maybe just the toolset for it. Requires a custom triplet however.

**Comment by johnco3** [comment] 2022-05-24 21:55
@Neumann-A thanks, as part of my toolchain, I modified the toolset to use v143, however prior to adding the line `set(VCPKG_PLATFORM_TOOLSET v143)`, I also had this error.   Is there another way of using a vs2019 compatibility mode?

**Comment by Osyotr** [comment] 2022-05-24 22:47
@johnco3 VS2019 is `v142`, not `v143`

**Comment by Adela0814** [comment] 2022-05-25 06:25
Close this issue because of dup to https://github.com/microsoft/vcpkg/issues/24704

**Closed by Adela0814** 2022-05-25 06:25 UTC
Labels: category:question
