### ISSUE TITLE
opencolorio build failure with feature applications

### ISSUE THREAD

**Issue by simonbjork** [microsoft/vcpkg#9710] opened 2020-01-16 11:49 UTC
**Host Environment**
- OS: Windows

**To Reproduce**
`./vcpkg install opencolorio[applications]:x64-windows`

Applications needs openimageio (which works). I also tried to install it separetly.

**Failure logs** 
Building package opencolorio[applications,core]:x64-windows...
-- Using cached C:/src/vcpkg/downloads/imageworks-OpenColorIO-v1.1.1.tar.gz
-- Extracting source C:/src/vcpkg/downloads/imageworks-OpenColorIO-v1.1.1.tar.gz
-- Applying patch 0001-lcms-dependency-search.patch
-- Applying patch 0002-msvc-cpluscplus.patch
-- Applying patch 0003-osx-self-assign-field.patch
-- Applying patch 0004-yaml-dependency-search.patch
-- Applying patch 0005-tinyxml-dependency-search.patch
-- Using source at C:/src/vcpkg/buildtrees/opencolorio/src/v1.1.1-1d6edbb79c
-- Downloading https://www.python.org/ftp/python/2.7.16/python-2.7.16.msi...
-- Configuring x64-windows
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/src/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Release --target install -- -v
    Working Directory: C:/src/vcpkg/buildtrees/opencolorio/x64-windows-rel
    See logs for more information:
      C:\src\vcpkg\buildtrees\opencolorio\install-x64-windows-rel-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencolorio/portfile.cmake:56 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)

Error: Building package opencolorio:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencolorio:x64-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.
PS C:\src\vcpkg>

**Additional context**

Here's the log file:

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4070993/config-x64-windows-out.log)

**Comment by PhoebeHui** [comment] 2020-01-19 10:25
@simonbjork, thanks for reporting this issue!

Above PR should fix this issue.

**Comment by simonbjork** [comment] 2020-01-20 13:05
Hi, thanks for taking a look :)!

Not sure if I'm missing something, but it still gives me an error.
`./vcpkg install opencolorio[applications]:x64-windows`

```
Building package opencolorio[applications,core]:x64-windows...
-- Using cached C:/src/vcpkg/downloads/imageworks-OpenColorIO-v1.1.1.tar.gz
-- Using source at C:/src/vcpkg/buildtrees/opencolorio/src/v1.1.1-683f3d2bf1
-- Configuring x64-windows
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: C:/src/vcpkg/downloads/tools/cmake-3.14.0-windows/cmake-3.14.0-win32-x86/bin/cmake.exe --build . --config Release --target install -- -v
    Working Directory: C:/src/vcpkg/buildtrees/opencolorio/x64-windows-rel
    See logs for more information:
      C:\src\vcpkg\buildtrees\opencolorio\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/opencolorio/portfile.cmake:53 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)


Error: Building package opencolorio:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: opencolorio:x64-windows
  Vcpkg version: 2020.01.17-nohash
```

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4086267/config-x64-windows-out.log)

**Comment by PhoebeHui** [comment] 2020-01-21 03:10
@simonbjork, could you provide us failure log C:\src\vcpkg\buildtrees\opencolorio\install-x64-windows-rel-out.log?

**Comment by simonbjork** [comment] 2020-01-21 11:14
@PhoebeHui : Yes, I had tested with your PR before, but I wasn't really sure how to use it. I just downloaded your branch and copied the opencolorio port into my existing port dir (replaced the old one). What's the command to download and apply a PR from a separate branch?

I just tested again and cloned your entire branch and ran:

`vcpkg install opencolorio[applications]:x64-windows`

Again, I got an error. The file you requested doesn't exist, but I'll here's a few others.

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4090747/config-x64-windows-out.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/4090748/install-x64-windows-dbg-err.log)

**Comment by PhoebeHui** [comment] 2020-01-22 02:15
@simonbjork from your log, it seems that the patch applied failed, could you remove opencolorio source under buildtrees and try to rebuild it again?

The reason due to lcms library name change from 'lcms2' to 'lcms', so the patch updated it, from your log, I still see it try to find 'lcms2', so the patch applied failed.

The following packages will be built and installed:
    opencolorio[applications,core]:x64-windows
Starting package 1/1: opencolorio:x64-windows
Building package opencolorio[applications,core]:x64-windows...
-- Using cached F:/VCPKG/clean/vcpkg/downloads/imageworks-OpenColorIO-v1.1.1.tar.gz
-- Extracting source F:/VCPKG/clean/vcpkg/downloads/imageworks-OpenColorIO-v1.1.1.tar.gz
-- Applying patch 0001-lcms-dependency-search.patch
-- Applying patch 0002-msvc-cpluscplus.patch
-- Applying patch 0003-osx-self-assign-field.patch
-- Applying patch 0004-yaml-dependency-search.patch
-- Applying patch 0005-tinyxml-dependency-search.patch
-- Using source at F:/VCPKG/clean/vcpkg/buildtrees/opencolorio/src/v1.1.1-683f3d2bf1
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package opencolorio[applications,core]:x64-windows... done
Installing package opencolorio[applications,core]:x64-windows...
Installing package opencolorio[applications,core]:x64-windows... done
Elapsed time for package opencolorio:x64-windows: 1.803 min

Total elapsed time: 1.803 min

The package opencolorio:x64-windows provides CMake targets:

    find_package(opencolorio CONFIG REQUIRED)
    target_link_libraries(main PRIVATE OpenColorIO)

**Comment by simonbjork** [comment] 2020-01-22 07:33
Thanks, but I tried multiple times already, using your vcpkg branch. Should I clone master apply the patch? Could you provide the command to download/apply?

**Comment by PhoebeHui** [comment] 2020-01-22 08:15
@simonbjork, you can try below commands:
1. git clone https://github.com/PhoebeHui/vcpkg
2. cd vcpkg
3. git checkout dev/Phoebe/opencolorio
4 ./bootstrap-vcpkg
5. ./vcpkg install opencolorio[applications]:x64-windows

**Comment by simonbjork** [comment] 2020-01-22 08:29
That’s exactly what I did, twice. Hm, I’ll guess I could try again but it should be the same. So it does work for you? Which Visual Studio? Im using 15.9.

**Comment by PhoebeHui** [comment] 2020-01-23 02:13
@simonbjork, I'm using 15.9.11, this issue should not related to the compiler. Currently the PR has been merged, you can get vcpkg latest source, and remove buildtrees\opencolorio\src folder, and try to build again, let me know if it still be an issue, also please attach the failure log if it still be an problem for you.

I have double confirmed it works for me on master branch.

**Comment by simonbjork** [comment] 2020-01-23 09:20
@PhoebeHui : I just tested and it works perfectly. Not sure what happend befrore, but it was probably on my end. Thanks a lot :).

Any chance you could have a look at the issue regarding [python bindings](https://github.com/microsoft/vcpkg/issues/9657)?

**Comment by PhoebeHui** [comment] 2020-02-18 12:44
Glad to hear that works for you!

**Closed by PhoebeHui** 2020-02-18 12:44 UTC
Labels: port bug
