### ISSUE TITLE
[gstreamer] Build error

### ISSUE THREAD

**Issue by llduncangithub** [microsoft/vcpkg#25989] opened 2022-07-26 08:46 UTC
**Host Environment**
- OS:  Windows 10
- Compiler: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22

**To Reproduce**
` .\vcpkg install qt:x64-windows`

**Failure logs**
F:\vcpkg\buildtrees\gstreamer\src\1.19.2-d9c05dd5ad.clean\subprojects\gst-plugins-base\gst-libs\gst/gl/glprototypes/gstgl_compat.h(40): error C2371: 'GLsync': redefinition; different basic types
F:\vcpkg\installed\x64-windows\include\GL/glext.h(1386): note: see declaration of 'GLsync'
ninja: build stopped: subcommand failed.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by LilyWangLL** [comment] 2022-07-27 07:30
Thanks for posting this issue. Could you please provide the complete log file?

**Comment by LilyWangLL** [comment] 2022-07-28 09:21
Thanks for your reply. I can't reproduce this issue locally. I can install `gstreamer` on the latest vcpkg with Visual Studio 2019. Did you change the related file of `gstreamer`? `GL/glext.h` belongs to `opengl-registry`. And `gstreamer` and `opengl-registry` have not changed for a long time in vcpkg.

**Comment by LilyWangLL** [comment] 2022-08-05 06:45
Ping @llduncangithub for response.

**Comment by llduncangithub** [comment] 2022-08-05 07:10
更新opengl-registry库 问题消失发自我的平板-------- 原始邮件 --------发件人： Lily Wang ***@***.***>日期： 2022年8月5日周五 14:45收件人： microsoft/vcpkg ***@***.***>抄送： llduncangithub ***@***.***>, Mention ***@***.***>主    题： Re: [microsoft/vcpkg] [gstreamer] Build error (Issue #25989)
Ping @llduncangithub for response.

**Comment by LilyWangLL** [comment] 2022-08-05 07:13
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Closed by LilyWangLL** 2022-08-05 07:13 UTC
Labels: category:question
