### ISSUE TITLE
[PROJ] PROJ should find unofficial-sqlite3 instead of SQlite3 for better multiconfig support

### ISSUE THREAD

**Issue by dbs4261** [microsoft/vcpkg#41583] opened 2024-10-15 21:40 UTC
### Is your feature request related to a problem? Please describe.

I am working on a super build for a project that depends on PROJ. I've been struggling to debug a LNK4098 warning reporting that my application, which I am building in release mode, is linking with something that was built in debug mode. I have eventually tracked this issue down to PROJ. When running CMake with CMAKE_FIND_DEBUG_MODE, I realized that when PROJ is installed with VCPKG the resulting `proj-config.cmake` script calls `find_dependency(SQLite3)`, this then gets picked up by `cmake-3.29/Modules/FindSQLite3.cmake`. That's a problem because the default FindSQLite3 module searches with a `find_library` command and the debug and release versions of the library share the same name.

### Proposed solution

A patch should be added to change the find_package call of SQLite3 to unofficial-sqlite3 and update the corresponding imported targets.

### Describe alternatives you've considered

Another option would be to set CMAKE_FIND_PACKAGE_PREFER_CONFIG, but this can't be done on a package by package basis.

**Comment by dg0yt** [comment] 2024-10-17 05:04
I removed the usage of unofficial-sqlite3 in #37650 because I believed the multi-config usage was covered by `SQLite::SQLite3`. I can confirm now that this is not the case. The best fix would be fixed by a vcpkg cmake wrapper for SQLite3. But as an immediate fix to this issue, https://github.com/microsoft/vcpkg/pull/41566 now restores the workaround in port proj.

**Closed** 2024-10-18 22:04 UTC
Labels: category:port-bug
