### ISSUE TITLE
Libigl update to 2.4.0

### ISSUE THREAD

**Issue by Nosenzor** [microsoft/vcpkg#26942] opened 2022-09-23 11:02 UTC
Library name: Libigl
https://github.com/libigl/libigl

New version number: 2.4.0

Other information that may be useful (release notes, etc...)

The latest version of libigl (v2.4.0) introduces some breaking changes to its CMake build system. Please read the changelog page for instructions [on how to update your project accordingly.](https://libigl.github.io/changelog/)

**Comment by JonLiu1993** [comment] 2022-09-28 08:53
Duplicate of #23354

**Closed by JonLiu1993** 2022-09-28 08:53 UTC
Labels: category:port-update
