### ISSUE TITLE
[cuda] Build error on x64-windows

### ISSUE THREAD

**Issue by lukeshapatil** [microsoft/vcpkg#42310] opened 2024-11-22 10:19 UTC
Package: cuda:x64-windows@10.1#13

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.42.34433.0
-    vcpkg-tool version: 2024-11-12-eb492805e92a2c14a230f5c3deb3e89f6771c321
    vcpkg-scripts version: 834977918 2024-11-20 (2 days ago)

**To Reproduce**

`vcpkg install darknet[full]:x64-windows`

**Failure logs**

```
-- Executing NVCC-NOTFOUND --version resulted in error: 1
CMake Error at ports/cuda/vcpkg_find_cuda.cmake:69 (message):
  Could not find CUDA.  Before continuing, please download and install CUDA
  (v10.1.0 or higher) from:

      https://developer.nvidia.com/cuda-downloads

Call Stack (most recent call first):
  ports/cuda/portfile.cmake:9 (vcpkg_find_cuda)
  scripts/ports.cmake:196 (include)



```

**Comment by StarGate-One** [comment] 2024-11-22 23:12
>-- Executing NVCC-NOTFOUND --version resulted in error: 1
CMake Error at ports/cuda/vcpkg_find_cuda.cmake:69 (message):
  Could not find CUDA.  Before continuing, please download and install CUDA
  (v10.1.0 or higher) from:
>
>      https://developer.nvidia.com/cuda-downloads

You need download `CUDA` and install it.

**Comment by MonicaLiu0311** [comment] 2024-11-25 02:37
Duplicate of #41834.

**Closed** 2024-11-25 02:37 UTC
Labels: category:question
