### ISSUE TITLE
[ qtdeclarative[core]] Cannot open include file: 'qquicksaturationlightnesspicker_p.h': No such file or directory

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#29454] opened 2023-02-05 14:31 UTC
**Host Environment**

- OS: Windows11
- Compiler: msvc vc413

**To Reproduce**

`.\vcpkg install pcl[apps,cuda,opengl,openni2,pcap,qt,simulation,tools,visualization,vtk]:x64-windows ` or
`.\vcpkg install qt:x64-windows `

**Failure logs**

-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/ProgramFiles/CMake/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: D:/ProgramFiles/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg
    See logs for more information:
      D:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  installed/x64-windows/share/qtbase/qt_install_submodule.cmake:337 (vcpkg_cmake_install)
  ports/qtdeclarative/portfile.cmake:22 (qt_install_submodule)
  scripts/ports.cmake:147 (include)
**Additional context**
[2843/2933] D:\ProgramFiles\Microsoft\VisualStudio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe   /TP -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_QUICKDIALOGS2QUICKIMPL_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DEPRECATED_WARNINGS_SINCE=0x070000 -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_GUI_LIB -DQT_LEAN_HEADERS=1 -DQT_MOC_COMPAT -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2IMPL_LIB -DQT_QUICKDIALOGS2UTILS_LIB -DQT_QUICKTEMPLATES2_LIB -DQT_QUICK_LIB -DQT_USE_QSTRINGBUILDER -DQuickDialogs2QuickImpl_EXPORTS -DUNICODE -DWIN32 -DWIN64 -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_USE_MATH_DEFINES -D_WIN64 -D_WINDLL -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2quickimpl\QuickDialogs2QuickImpl_autogen\include -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\src\here-src-6-a31aea0fcd.clean\src\quickdialogs2\quickdialogs2quickimpl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2quickimpl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl\6.4.2\QtQuickDialogs2QuickImpl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qml -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml\6.4.2\QtQml -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlIntegration -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\src\here-src-6-a31aea0fcd.clean\src\qmlintegration -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmlintegration -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quick -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick\6.4.2\QtQuick -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmlmodels -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels\6.4.2\QtQmlModels -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quicktemplates2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2\6.4.2\QtQuickTemplates2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickcontrols2impl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2Impl\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2Impl\6.4.2\QtQuickControls2Impl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2Impl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2Utils -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2utils -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2Utils\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2Utils\6.4.2\QtQuickDialogs2Utils -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtCore\6.4.2 -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtCore\6.4.2\QtCore -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtCore -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6 -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\share\Qt6\mkspecs\win32-msvc -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtNetwork -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtGui -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtOpenGL -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtGui\6.4.2 -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtGui\6.4.2\QtGui -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /W3 /EHs-c- /wd4530 /wd4577 -Zc:__cplusplus -permissive- -utf-8 -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:externConstexpr -Zc:wchar_t -bigobj -std:c++17 /bigobj /YuD:/ProgramFiles/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/quickdialogs2/quickdialogs2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/cmake_pch.hxx /FpD:/ProgramFiles/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/quickdialogs2/quickdialogs2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/./cmake_pch.cxx.pch /FID:/ProgramFiles/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/quickdialogs2/quickdialogs2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/cmake_pch.hxx /showIncludes /Fosrc\quickdialogs2\quickdialogs2quickimpl\CMakeFiles\QuickDialogs2QuickImpl.dir\quickdialogs2quickimpl_qmltyperegistrations.cpp.obj /Fdsrc\quickdialogs2\quickdialogs2quickimpl\CMakeFiles\QuickDialogs2QuickImpl.dir\ /FS -c D:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2quickimpl\quickdialogs2quickimpl_qmltyperegistrations.cpp
FAILED: src/quickdialogs2/quickdialogs2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/quickdialogs2quickimpl_qmltyperegistrations.cpp.obj 
D:\ProgramFiles\Microsoft\VisualStudio\2022\Community\VC\Tools\MSVC\14.34.31933\bin\Hostx64\x64\cl.exe   /TP -DQT_ASCII_CAST_WARNINGS -DQT_BUILDING_QT -DQT_BUILD_QUICKDIALOGS2QUICKIMPL_LIB -DQT_CORE_LIB -DQT_DEPRECATED_WARNINGS -DQT_DEPRECATED_WARNINGS_SINCE=0x070000 -DQT_DISABLE_DEPRECATED_BEFORE=0x040800 -DQT_GUI_LIB -DQT_LEAN_HEADERS=1 -DQT_MOC_COMPAT -DQT_NETWORK_LIB -DQT_NO_CAST_FROM_ASCII -DQT_NO_CAST_TO_ASCII -DQT_NO_EXCEPTIONS -DQT_NO_JAVA_STYLE_ITERATORS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_OPENGL_LIB -DQT_QMLINTEGRATION_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKCONTROLS2IMPL_LIB -DQT_QUICKDIALOGS2UTILS_LIB -DQT_QUICKTEMPLATES2_LIB -DQT_QUICK_LIB -DQT_USE_QSTRINGBUILDER -DQuickDialogs2QuickImpl_EXPORTS -DUNICODE -DWIN32 -DWIN64 -D_CRT_SECURE_NO_WARNINGS -D_ENABLE_EXTENDED_ALIGNED_STORAGE -D_UNICODE -D_USE_MATH_DEFINES -D_WIN64 -D_WINDLL -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2quickimpl\QuickDialogs2QuickImpl_autogen\include -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\src\here-src-6-a31aea0fcd.clean\src\quickdialogs2\quickdialogs2quickimpl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2quickimpl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl\6.4.2\QtQuickDialogs2QuickImpl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qml -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml\6.4.2\QtQml -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQml -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlIntegration -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\src\here-src-6-a31aea0fcd.clean\src\qmlintegration -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmlintegration -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quick -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuick\6.4.2\QtQuick -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\qmlmodels -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQmlModels\6.4.2\QtQmlModels -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quicktemplates2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickTemplates2\6.4.2\QtQuickTemplates2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickcontrols2impl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2Impl\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2Impl\6.4.2\QtQuickControls2Impl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickControls2Impl -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2Utils -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2utils -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2Utils\6.4.2 -ID:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2Utils\6.4.2\QtQuickDialogs2Utils -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtCore\6.4.2 -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtCore\6.4.2\QtCore -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtCore -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6 -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\share\Qt6\mkspecs\win32-msvc -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtNetwork -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtGui -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtOpenGL -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtGui\6.4.2 -external:ID:\ProgramFiles\vcpkg\installed\x64-windows\include\Qt6\QtGui\6.4.2\QtGui -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -MDd /W3 /EHs-c- /wd4530 /wd4577 -Zc:__cplusplus -permissive- -utf-8 -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -Zc:referenceBinding -Zc:externConstexpr -Zc:wchar_t -bigobj -std:c++17 /bigobj /YuD:/ProgramFiles/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/quickdialogs2/quickdialogs2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/cmake_pch.hxx /FpD:/ProgramFiles/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/quickdialogs2/quickdialogs2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/./cmake_pch.cxx.pch /FID:/ProgramFiles/vcpkg/buildtrees/qtdeclarative/x64-windows-dbg/src/quickdialogs2/quickdialogs2quickimpl/CMakeFiles/QuickDialogs2QuickImpl.dir/cmake_pch.hxx /showIncludes /Fosrc\quickdialogs2\quickdialogs2quickimpl\CMakeFiles\QuickDialogs2QuickImpl.dir\quickdialogs2quickimpl_qmltyperegistrations.cpp.obj /Fdsrc\quickdialogs2\quickdialogs2quickimpl\CMakeFiles\QuickDialogs2QuickImpl.dir\ /FS -c D:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\src\quickdialogs2\quickdialogs2quickimpl\quickdialogs2quickimpl_qmltyperegistrations.cpp
cl : Command line warning D9025 : overriding '/EHs' with '/EHs-'
cl : Command line warning D9025 : overriding '/EHc' with '/EHc-'
D:\ProgramFiles\vcpkg\buildtrees\qtdeclarative\x64-windows-dbg\include\QtQuickDialogs2QuickImpl\6.4.2\QtQuickDialogs2QuickImpl\private/qquicksaturationlightnesspicker_p.h(1): fatal error C1083: Cannot open include file: '../../../../../../src/here-src-6-a31aea0fcd.clean/src/quickdialogs2/quickdialogs2quickimpl/qquicksaturationlightnesspicker_p.h': No such file or directory

**Comment by dg0yt** [comment] 2023-02-05 14:37
Read the warning before `-- Building x64-windows-dbg`.

**Comment by Bzz2745** [comment] 2023-02-05 14:49
I did'n see any error or warning before that,shoul I run te commond with --debug?
 This is information before that:
Computing installation plan...
The following packages will be built and installed:
    pcl[apps,core,cuda,opengl,openni2,pcap,qt,simulation,tools,visualization,vtk]:x64-windows -> 1.13.0
  * qtdeclarative[core]:x64-windows -> 6.4.2
  * qtimageformats[core,default-features,jasper,tiff,webp]:x64-windows -> 6.4.2
  * qttools[assistant,core,designer,linguist]:x64-windows -> 6.4.2#1
  * seacas[core]:x64-windows -> 2022-11-22#1
  * vtk[core,opengl,qt]:x64-windows -> 9.2.0-pv5.11.0#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\BaZunzhi\AppData\Local\vcpkg\archives in 2.024 ms. Use --debug to see more details.
Installing 1/6 qtdeclarative:x64-windows...
Building qtdeclarative[core]:x64-windows...
-- Using cached qtdeclarative-everywhere-src-6.4.2.tar.xz.
-- Extracting source D:/ProgramFiles/vcpkg/downloads/qtdeclarative-everywhere-src-6.4.2.tar.xz
-- Using source at D:/ProgramFiles/vcpkg/buildtrees/qtdeclarative/src/here-src-6-a31aea0fcd.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows

**Comment by dg0yt** [comment] 2023-02-05 16:23
No warning for this port indeed. But the symptoms remind of this warning e.g. in qtwebengine:
~~~
Buildtree path '...' is too long.
Consider passing --x-buildtrees-root=<shortpath> to vcpkg!
~~~
Your buildtree path: `D:/ProgramFiles/vcpkg/buildtrees/qtdeclarative`

**Comment by Neumann-A** [comment] 2023-02-05 20:42
duplicate of #28083

**Comment by Bzz2745** [comment] 2023-02-06 05:53
It worked,thanks  for your help!

**Comment by dg0yt** [comment] 2023-02-06 06:20
IMO the issue is not resolved until we add a warning to this port, too.

**Comment by Adela0814** [comment] 2023-02-06 06:42
> IMO the issue is not resolved until we add a warning to this port, too.

I will submit a PR for this.

**Closed** 2023-02-15 18:02 UTC
Labels: category:question

**Comment by vipcxj** [comment] 2024-03-17 10:25
Same issue. i had suspected that the paths were too long when i found `vcpkg_buildpath_length_warning(44)` in the portfile, but this warning was not triggered. On the other hand I also checked the registry and LongPathsEnabled was set to 1. So I ruled out that suspicion. I didn't realize it was really the problem until I saw this issue. I don't think this issue should be closed.
