### ISSUE TITLE
abseil build with clang failing due to '-ignore:4221'

### ISSUE THREAD

**Issue by jjpepper** [microsoft/vcpkg#13945] opened 2020-10-09 10:38 UTC
**Describe the bug**
Linking against abseil while using clang (not clang-cl) in windows yields the error 

`clang : error : unknown argument: '-ignore:4221'`

The file C:\vcpkg\installed\x64-windows\share\absl\abslTargets.cmake has 

```
set_target_properties(absl::log_severity PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "absl::core_headers;\$<LINK_ONLY:-ignore:4221>"
)
```

on each target (see the `<LINK_ONLY:-ignore:4221>` at the end).

The abseil source code file

[](https://github.com/abseil/abseil-cpp/blob/master/absl/copts/AbseilConfigureCopts.cmake) applies `${ABSL_MSVC_LINKOPTS}`
in an appropriate way for MSVC but not for WIN32.

The variable ABSL_MSVC_LINKOPTS is defined in [](https://github.com/abseil/abseil-cpp/blob/master/absl/copts/GENERATED_AbseilCopts.cmake),

```
list(APPEND ABSL_MSVC_LINKOPTS
    "-ignore:4221"
)
```

**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision
Windows 10, clang 10.0.0 (not clang-cl)

**To Reproduce**
1. ./vcpkg install absl
2. See error
Simply link against absl with cmake and build with clang.exe.  I've created a simple reproducer here, which assumes clang.exe is in the default installed location. https://github.com/jjpepper/vcpkg-absl-clang-problem

**Expected behavior**
I expect the sample program to compile and link when built in `x64-Clang-Release` configuration.  It is just a minimal program

`int main() { return 0; }`

**Failure logs** 
```
>------ Build All started: Project: vcpkg-absl-clang-problem, Configuration: x64-Clang-Release ------
  [1/2] Building CXX object CMakeFiles/main.dir/main.cpp.obj
  [2/2] Linking CXX executable main.exe
  FAILED: main.exe 
  cmd.exe /C "cd . && C:\PROGRA~1\LLVM\bin\clang.exe -fuse-ld=lld-link -nostartfiles -nostdlib -m64 -fdiagnostics-absolute-paths -O2 -g -DNDEBUG -Xclang -gcodeview -D_DLL -D_MT -Xclang --dependent-lib=msvcrt   CMakeFiles/main.dir/main.cpp.obj  -o main.exe -Xlinker /implib:main.lib -Xlinker /pdb:main.pdb -Xlinker /version:0.0   C:/vcpkg/installed/x64-windows/lib/absl_hash.lib  C:/vcpkg/installed/x64-windows/lib/absl_bad_variant_access.lib  C:/vcpkg/installed/x64-windows/lib/absl_city.lib  C:/vcpkg/installed/x64-windows/lib/absl_raw_hash_set.lib  C:/vcpkg/installed/x64-windows/lib/absl_bad_optional_access.lib  C:/vcpkg/installed/x64-windows/lib/absl_hashtablez_sampler.lib  C:/vcpkg/installed/x64-windows/lib/absl_exponential_biased.lib  C:/vcpkg/installed/x64-windows/lib/absl_synchronization.lib  C:/vcpkg/installed/x64-windows/lib/absl_graphcycles_internal.lib  C:/vcpkg/installed/x64-windows/lib/absl_stacktrace.lib  C:/vcpkg/installed/x64-windows/lib/absl_symbolize.lib  C:/vcpkg/installed/x64-windows/lib/absl_malloc_internal.lib  C:/vcpkg/installed/x64-windows/lib/absl_debugging_internal.lib  C:/vcpkg/installed/x64-windows/lib/absl_demangle_internal.lib  C:/vcpkg/installed/x64-windows/lib/absl_time.lib  C:/vcpkg/installed/x64-windows/lib/absl_strings.lib  C:/vcpkg/installed/x64-windows/lib/absl_strings_internal.lib  C:/vcpkg/installed/x64-windows/lib/absl_int128.lib  C:/vcpkg/installed/x64-windows/lib/absl_base.lib  C:/vcpkg/installed/x64-windows/lib/absl_dynamic_annotations.lib  C:/vcpkg/installed/x64-windows/lib/absl_spinlock_wait.lib  C:/vcpkg/installed/x64-windows/lib/absl_civil_time.lib  C:/vcpkg/installed/x64-windows/lib/absl_time_zone.lib  C:/vcpkg/installed/x64-windows/lib/absl_throw_delegate.lib  C:/vcpkg/installed/x64-windows/lib/absl_raw_logging_internal.lib  C:/vcpkg/installed/x64-windows/lib/absl_log_severity.lib  -ignore:4221  -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32 -loldnames && cmd.exe /C "cd /D C:\Users\jesse\source\repos\github\jjpepper\vcpkg-absl-clang-problem\out\build\x64-Clang-Release && powershell -noprofile -executionpolicy Bypass -file C:/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary C:/Users/jesse/source/repos/github/jjpepper/vcpkg-absl-clang-problem/out/build/x64-Clang-Release/main.exe -installedDir C:/vcpkg/installed/x64-windows/bin -OutVariable out""
C:\Users\jesse\source\repos\github\jjpepper\vcpkg-absl-clang-problem\out\build\x64-Clang-Release\clang : error : unknown argument: '-ignore:4221'
  ninja: build stopped: subcommand failed.

Build All failed.
```

**Additional context**

**Comment by jjpepper** [comment] 2020-10-15 16:10
It basically seems like clang.exe is behaving as though it is clang-cl.exe here.

**Comment by jjpepper** [comment] 2020-10-22 02:03
Hey @LilyWangL have you tried this?  Is clang.exe supported?  The reason I want this is that I'm seeing much worse machine code generated by clang-cl.exe.  Bizarre, right?

**Comment by LilyWangL** [comment] 2020-10-22 08:25
Sorry I am late. I try to reproduce this issue, but I build my project succeeded.
This is my CMakeSettings.json:
```
{
  "configurations": [
    {
      "name": "x64-Clang-Release",
      "generator": "Visual Studio 16 2019 Win64",
      "configurationType": "RelWithDebInfo",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "clang_cl_x64_x64" ],
      "variables": [
        {
          "name": "CMAKE_CXX_COMPILER",
          "value": "F:/LLVM/bin/clang.exe",
          "type": "STRING"
        },
        {
          "name": "CMAKE_C_COMPILER",
          "value": "F:/LLVM/bin/clang.exe",
          "type": "STRING"
        }
      ]
    }
  ]
}
```
This is my CMakeLists.txt:
```
cmake_minimum_required (VERSION 3.8)
# Add source to this project's executable.
add_executable (CMakeProject12 "CMakeProject12.cpp" "CMakeProject12.h")
# TODO: Add tests and install targets if needed.
find_package(absl CONFIG REQUIRED)
# Note: 119 target(s) were omitted.
target_link_libraries(CMakeProject12 PRIVATE absl::any absl::base absl::bits absl::city)
```
This is my CMakeProject12.cpp:
```
#include "CMakeProject12.h"
using namespace std;
int main()
{
	return 0;
}
```
This is result:
```
>------ Build started: Project: CMakeLists, Configuration: RelWithDebInfo ------
  Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
  Copyright (C) Microsoft Corporation. All rights reserved.
  
    Checking Build System
    Building Custom Rule C:/Users/vwangli/source/repos/CMakeProject12/CMakeProject12/CMakeLists.txt
    CMakeProject12.vcxproj -> C:\Users\vwangli\source\repos\CMakeProject12\out\build\x64-Clang-Release\CMakeProject12\RelWithDebInfo\CMakeProject12.exe
    Building Custom Rule C:/Users/vwangli/source/repos/CMakeProject12/CMakeLists.txt

Build succeeded.
```

**Comment by jjpepper** [comment] 2020-10-22 08:49
Can you try my code at `https://github.com/jjpepper/vcpkg-absl-clang-problem`.  Key differences:
I have ` "generator": "Ninja",`
I have `absl::flat_hash_map` linked
my main.cpp:
```
int main() { return 0; }
```
my CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.17)
project(vcpkg-absl-clang-problem VERSION 0.1 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17) 
find_package(absl CONFIG REQUIRED)

add_executable(main main.cpp)
target_link_libraries(main PUBLIC absl::flat_hash_map)
```

my CMakeSettings.json:
```
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Ninja",
      "configurationType": "Debug",
      "inheritEnvironments": [ "msvc_x64_x64" ],
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "variables": []
    },
    {
      "name": "x64-Clang-Release",
      "generator": "Ninja",
      "configurationType": "RelWithDebInfo",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "clang_cl_x64_x64" ],
      "variables": [
        {
          "name": "CMAKE_CXX_COMPILER",
          "value": "C:/Program Files/LLVM/bin/clang.exe",
          "type": "STRING"
        },
        {
          "name": "CMAKE_C_COMPILER",
          "value": "C:/Program Files/LLVM/bin/clang.exe",
          "type": "STRING"
        }
      ]
    }
  ]
}
```

**Comment by jjpepper** [comment] 2020-10-22 08:55
When I try with the same generator as you, I get the following error:

```
1> [CMake] -- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19041.
1> [CMake] CMake Error at C:\Users\jesse\source\repos\github\jjpepper\vcpkg-absl-clang-problem\CMakeLists.txt:2 (project):
1> [CMake]   Failed to run MSBuild command:
1> [CMake] 
1> [CMake]     C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/MSBuild/Current/Bin/MSBuild.exe
1> [CMake] 
1> [CMake]   to get the value of VCTargetsPath:
1> [CMake] 
1> [CMake]     Microsoft (R) Build Engine version 16.7.0+b89cb5fde for .NET Framework
1> [CMake]     Copyright (C) Microsoft Corporation. All rights reserved.
1> [CMake]     
1> [CMake]     Build started 22/10/2020 4:54:14 PM.
1> [CMake]     Project "C:\Users\jesse\source\repos\github\jjpepper\vcpkg-absl-clang-problem\out\build\x64-Clang-Release\CMakeFiles\3.17.20032601-MSVC_2\VCTargetsPath.vcxproj" on node 1 (default targets).
1> [CMake]     C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): error MSB8020: The build tools for ClangCl (Platform Toolset = 'ClangCl') cannot be found. To build using the ClangCl build tools, please install ClangCl build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\jesse\source\repos\github\jjpepper\vcpkg-absl-clang-problem\out\build\x64-Clang-Release\CMakeFiles\3.17.20032601-MSVC_2\VCTargetsPath.vcxproj]
1> [CMake]     Done Building Project "C:\Users\jesse\source\repos\github\jjpepper\vcpkg-absl-clang-problem\out\build\x64-Clang-Release\CMakeFiles\3.17.20032601-MSVC_2\VCTargetsPath.vcxproj" (default targets) -- FAILED.
1> [CMake]     
1> [CMake]     Build FAILED.
1> [CMake]     
1> [CMake]     "C:\Users\jesse\source\repos\github\jjpepper\vcpkg-absl-clang-problem\out\build\x64-Clang-Release\CMakeFiles\3.17.20032601-MSVC_2\VCTargetsPath.vcxproj" (default target) (1) ->
1> [CMake]     (PrepareForBuild target) -> 
1> [CMake]       C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(411,5): error MSB8020: The build tools for ClangCl (Platform Toolset = 'ClangCl') cannot be found. To build using the ClangCl build tools, please install ClangCl build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [C:\Users\jesse\source\repos\github\jjpepper\vcpkg-absl-clang-problem\out\build\x64-Clang-Release\CMakeFiles\3.17.20032601-MSVC_2\VCTargetsPath.vcxproj]
1> [CMake]     
1> [CMake]         0 Warning(s)
1> [CMake]         1 Error(s)
1> [CMake]     
1> [CMake]     Time Elapsed 00:00:00.17
1> [CMake]     
1> [CMake] 
1> [CMake]   Exit code: 1
1> [CMake] 
1> [CMake] 
1> [CMake] 
1> [CMake] -- Configuring incomplete, errors occurred!
```

**Comment by jjpepper** [comment] 2020-10-22 12:27
My vcpkg is 8 days old:
```
$ git log
commit bfe983d721a0f2e0cd492f4b5632a952072b7e93 (HEAD -> master, origin/master, origin/HEAD)
Author: Billy O'Neal <bion@microsoft.com>
Date:   Wed Oct 14 17:38:40 2020 -0700
```

I tried updating to the latest vcpkg and rebuilding, but the problem persists.

On top of that, I get a different new error in with clang-cl.exe when I add `#include <absl/container/flat_hash_map.h>`, so after hours of rebuilding, now my clang-cl build is broken too. :-(

```
  [1/2] Building CXX object CMakeFiles\main.dir\main.cpp.obj
  FAILED: CMakeFiles/main.dir/main.cpp.obj 
  C:\PROGRA~1\LLVM\bin\clang-cl.exe  /nologo -TP  -IC:\vcpkg\installed\x64-windows\include -m64 -fdiagnostics-absolute-paths  /DWIN32 /D_WINDOWS /GR /EHsc /Zi /O2 /Ob1 /DNDEBUG -MD   -std:c++17 /showIncludes /FoCMakeFiles\main.dir\main.cpp.obj /FdCMakeFiles\main.dir\ -c ..\..\..\main.cpp
  In file included from ..\..\..\main.cpp:1:
  In file included from C:\vcpkg\installed\x64-windows\include\absl/container/flat_hash_map.h:41:
  In file included from C:\vcpkg\installed\x64-windows\include\absl/container/internal/raw_hash_map.h:24:
  In file included from C:\vcpkg\installed\x64-windows\include\absl/container/internal/raw_hash_set.h:113:
  In file included from C:\vcpkg\installed\x64-windows\include\absl/container/internal/hashtablez_sampler.h:50:
  In file included from C:\vcpkg\installed\x64-windows\include\absl/synchronization/mutex.h:71:
  In file included from C:\vcpkg\installed\x64-windows\include\absl/synchronization/internal/kernel_timeout.h:32:
C:\vcpkg\installed\x64-windows\include\absl\base\internal\raw_logging.h(173,10): error : an attribute list cannot appear here
  ABSL_DLL ABSL_INTERNAL_ATOMIC_HOOK_ATTRIBUTES extern base_internal::AtomicHook<
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  C:\vcpkg\installed\x64-windows\include\absl\base\internal\atomic_hook.h(49,46): note: expanded from macro 'ABSL_INTERNAL_ATOMIC_HOOK_ATTRIBUTES'
  #define ABSL_INTERNAL_ATOMIC_HOOK_ATTRIBUTES ABSL_CONST_INIT
                                               ^~~~~~~~~~~~~~~
  C:\vcpkg\installed\x64-windows\include\absl\base\attributes.h(616,25): note: expanded from macro 'ABSL_CONST_INIT'
  #define ABSL_CONST_INIT [[clang::require_constant_initialization]]
                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  ninja: build stopped: subcommand failed.
```

**Comment by JackBoosY** [comment] 2020-10-23 07:05
In _VCPKG_ROOT/installed/TRIPLET/share/absl/abslTargets.cmake_:
```
INTERFACE_LINK_LIBRARIES "...;-ignore:4221"
```
I think `-ignore:4221` shouldn't be added into `INTERFACE_LINK_LIBRARIES`.

**Comment by LilyWangL** [comment] 2020-10-23 08:51
@jjpepper I think this is a source issue. Could you please submit an issue on source page: https://github.com/abseil/abseil-cpp?

**Comment by jjpepper** [comment] 2020-10-23 09:08
It’s not a source issue. I’ve examined the source. They switch off that
compiler switch for Win32 builds

**Comment by JackBoosY** [comment] 2020-10-23 09:20
https://github.com/abseil/abseil-cpp/blob/eb317a701b83bf9a4f2a035d75747a3d76a48324/CMake/AbseilHelpers.cmake#L190-L195
The options should be added in `target_compile_options` instead of `target_link_libraries`.
That casued this issue.

**Comment by jjpepper** [comment] 2020-10-23 14:32
@JackBoosY can you explain a bit more?  I don't think `-ignore:4221` will work with clang.exe at all, it's an MSVC or clang-cl.exe switch isn't it?  Are you saying that switch will work as a compile option to clang.exe (not clang-cl)?

**Comment by jjpepper** [comment] 2020-10-23 14:35
```
$ cat foo.cpp
int main() { return 0; }
```
and then
```
$ clang -ignore:4221 -o foo foo.cpp
clang: error: unknown argument: '-ignore:4221'
```

So I don't see how making it appear in target_compile_options will change anything?

**Comment by Milerius** [comment] 2020-12-25 10:49
any news on this one ?

**Comment by JackBoosY** [comment] 2020-12-28 02:27
@Milerius Blocked by the upstream. Although we can fix this issue in vcpkg, the fix requires upstream approval.

**Comment by Chronial** [comment] 2021-02-05 08:35
This has recently been fixed on abseil master (https://github.com/abseil/abseil-cpp/commit/58a9c6d53f93078101c2c0bd98d2951e74328a55), but is not released yet.

**Closed** 2021-02-08 21:48 UTC
Labels: category:port-bug

**Comment by triplef** [comment] 2023-01-26 08:25
FYI you can use this option with clang/lld-link like this: `-Wl,-ignore:4099`.

**Comment by chenzhuowansui** [comment] 2023-07-11 03:19
Hi, i'm still getting this link error when i'm building a program with gRPC on windows with clang. The version of abseil i'm using is "20230125.3", which seems like the latest version. 

Clang Version:
```
clang version 15.0.0
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

vcpkg version:
```
vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895

See LICENSE.txt for license information.
```

anyone could help me out here? many thanks!

**Comment by honeway** [comment] 2023-08-10 11:57
> Hi, i'm still getting this link error when i'm building a program with gRPC on windows with clang. The version of abseil i'm using is "20230125.3", which seems like the latest version.
> 
> Clang Version:
> 
> ```
> clang version 15.0.0
> Target: x86_64-pc-windows-msvc
> Thread model: posix
> InstalledDir: C:\Program Files\LLVM\bin
> ```
> 
> vcpkg version:
> 
> ```
> vcpkg package management program version 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
> 
> See LICENSE.txt for license information.
> ```
> 
> anyone could help me out here? many thanks!

I also get the issue.  The reason is that the grpc depends on a fixed  old version of abseil.
