### ISSUE TITLE
[gdal] build failure in osx pipeline

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#17040] opened 2021-04-02 12:59 UTC
**Host Environment**
- OS: macOS CI
- Compiler: unknown

**To Reproduce**
Run pipeline of #16577

**Failure logs** 
https://dev.azure.com/vcpkg/public/_build/results?buildId=51429&view=logs&jobId=0a61404f-5c45-5632-e83c-408b7fcca1d6&j=2644860b-263e-5de8-c39e-3f62c017aad0&t=0c846259-ebdc-51ce-09bf-fc9ed3a241c7

autoconf-x64-osx-err.log:
```
autoreconf: export WARNINGS=
autoreconf: Entering directory '.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: running: glibtoolize --copy --force
autoreconf: configure.ac: not using Intltool
autoreconf: configure.ac: not using Gtkdoc
autoreconf: running: aclocal --force 
autoreconf: running: /usr/local/Cellar/autoconf/2.71/bin/autoconf --force
configure.ac:49: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:49: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
m4/ax_cflags_warn_all.m4:26: AX_CFLAGS_WARN_ALL is expanded from...
configure.ac:49: the top level
configure.ac:50: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:50: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
lib/m4sugar/m4sh.m4:692: _AS_IF_ELSE is expanded from...
lib/m4sugar/m4sh.m4:699: AS_IF is expanded from...
./lib/autoconf/general.m4:2249: AC_CACHE_VAL is expanded from...
./lib/autoconf/general.m4:2270: AC_CACHE_CHECK is expanded from...
m4/ax_cflags_warn_all.m4:71: AX_CXXFLAGS_WARN_ALL is expanded from...
configure.ac:50: the top level
configure.ac:222: warning: The macro `AC_LIBTOOL_WIN32_DLL' is obsolete.
configure.ac:222: You should run autoupdate.
m4/ltoptions.m4:148: AC_LIBTOOL_WIN32_DLL is expanded from...
configure.ac:222: the top level
configure.ac:222: warning: AC_LIBTOOL_WIN32_DLL: Remove this warning and the call to _LT_SET_OPTION when you
configure.ac:222: put the 'win32-dll' option into LT_INIT's first parameter.
./lib/autoconf/general.m4:2434: AC_DIAGNOSE is expanded from...
m4/ltoptions.m4:148: AC_LIBTOOL_WIN32_DLL is expanded from...
configure.ac:222: the top level
configure.ac:223: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
configure.ac:223: You should run autoupdate.
m4/libtool.m4:99: AC_PROG_LIBTOOL is expanded from...
configure.ac:223: the top level
configure.ac:297: warning: The macro `AC_HEADER_STDC' is obsolete.
configure.ac:297: You should run autoupdate.
./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
configure.ac:297: the top level
configure.ac:350: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:350: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:350: the top level
configure.ac:376: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:376: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:376: the top level
configure.ac:505: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:505: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:505: the top level
configure.ac:980: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:980: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:980: the top level
configure.ac:999: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:999: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:999: the top level
configure.ac:1016: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:1016: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:1016: the top level
configure.ac:1037: warning: The macro `AC_CHECKING' is obsolete.
configure.ac:1037: You should run autoupdate.
./lib/autoconf/general.m4:2499: AC_CHECKING is expanded from...
configure.ac:1037: the top level
configure.ac:1041: warning: The macro `AC_CHECKING' is obsolete.
configure.ac:1041: You should run autoupdate.
./lib/autoconf/general.m4:2499: AC_CHECKING is expanded from...
configure.ac:1041: the top level
configure.ac:1058: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:1058: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:1058: the top level
configure.ac:1079: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:1079: You should run autoupdate.
./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:1079: the top level
configure.ac:3052: warning: AC_CHECK_HEADERS($NETCDF_INCLUDEDIR/netcdf_mem.h): you should use literals
./lib/autoconf/headers.m4:217: AC_CHECK_HEADERS is expanded from...
configure.ac:3052: the top level
configure.ac:3672: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:3672: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
m4/ax_oracle_oci.m4:41: AX_LIB_ORACLE_OCI is expanded from...
configure.ac:3672: the top level
configure.ac:3792: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:3792: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
m4/ax_lib_xerces.m4:37: AX_LIB_XERCES is expanded from...
configure.ac:3792: the top level
configure.ac:3816: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:3816: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
m4/ax_lib_expat.m4:37: AX_LIB_EXPAT is expanded from...
configure.ac:3816: the top level
configure.ac:3839: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:3839: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
m4/ax_lib_libkml.m4:48: AX_LIB_LIBKML is expanded from...
configure.ac:3839: the top level
configure.ac:3928: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:3928: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
m4/ax_oracle_oci.m4:41: AX_LIB_ORACLE_OCI is expanded from...
configure.ac:3928: the top level
configure.ac:4204: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:4204: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
m4/ax_lib_sqlite3.m4:32: AX_LIB_SQLITE3 is expanded from...
configure.ac:4204: the top level
configure.ac:4239: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:4239: You should run autoupdate.
./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
m4/ax_lib_sqlite3.m4:32: AX_LIB_SQLITE3 is expanded from...
configure.ac:4239: the top level
configure.ac:4448: warning: The macro `AC_CHECKING' is obsolete.
configure.ac:4448: You should run autoupdate.
./lib/autoconf/general.m4:2499: AC_CHECKING is expanded from...
configure.ac:4448: the top level
configure.ac:5611: warning: The macro `AC_CHECKING' is obsolete.
configure.ac:5611: You should run autoupdate.
./lib/autoconf/general.m4:2499: AC_CHECKING is expanded from...
configure.ac:5611: the top level
configure.ac:6009: warning: AC_OUTPUT should be used without arguments.
configure.ac:6009: You should run autoupdate.
autoreconf: running: /usr/local/Cellar/autoconf/2.71/bin/autoheader --force
autoreconf: configure.ac: not using Automake
autoreconf: './config.sub' is updated
autoreconf: './config.guess' is updated
configure.ac: error: required file 'config.rpath' not found
autoreconf: Leaving directory '.'

```

**Comment by PhoebeHui** [comment] 2021-04-02 13:32
Duplicate of https://github.com/microsoft/vcpkg/issues/16990

**Closed by PhoebeHui** 2021-04-02 13:32 UTC
Labels: requires:repro
