### ISSUE TITLE
brotli:x64-windows  build failure

### ISSUE THREAD

**Issue by bettojanea** [microsoft/vcpkg#12980] opened 2020-08-18 13:55 UTC
**Host Environment**
- OS: Windows 10
- Compiler: MSVC 19.27.29111.0

**To Reproduce**
`./vcpkg install cpprestsdk cpprestsdk:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
PS C:\dev\vcpkg>  .\vcpkg install cpprestsdk cpprestsdk:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * brotli[core]:x64-windows
    cpprestsdk[brotli,compression,core,default-features]:x64-windows
    cpprestsdk[brotli,compression,core,default-features]:x86-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Starting package 1/4: brotli:x64-windows
Building package brotli[core]:x64-windows...
Could not locate cached archive: C:\Users\bened\AppData\Local\vcpkg\archives\09\0972168266a4f4da734fe6b114049419121737df.zip
-- Downloading https://github.com/google/brotli/archive/v1.0.7.tar.gz...
-- Cleaning sources at C:/dev/vcpkg/buildtrees/brotli/src/v1.0.7-c2af986dcd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/google-brotli-v1.0.7.tar.gz
-- Applying patch install.patch
-- Applying patch fix-arm-uwp.patch
-- Applying patch pkgconfig.patch
-- Using source at C:/dev/vcpkg/buildtrees/brotli/src/v1.0.7-c2af986dcd.clean
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: C:/dev/vcpkg/buildtrees/brotli/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\brotli\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/brotli/portfile.cmake:13 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)

Error: Building package brotli:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: brotli:x64-windows
  Vcpkg version: 2020.06.15-nohash

-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/5090774/config-x64-windows-out.log)

**Comment by BaderEddineOuaich** [comment] 2020-08-18 14:29
The same issue happened to me with an old windows sdk.
i solved it by downloading the latest windows sdk build using the visual studio installer. 
it worth a shot in your case.

**Comment by LilyWangL** [comment] 2020-08-21 07:25
Thanks for posting this issue. Closed as duplicate of #12955.

**Closed by LilyWangL** 2020-08-21 07:25 UTC
Labels: category:question
