### ISSUE TITLE
[liblzma] Build error on x64-windows

### ISSUE THREAD

**Issue by JohnMickle** [microsoft/vcpkg#37911] opened 2024-04-02 00:11 UTC
Package: liblzma:x64-windows@5.4.4

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33519.0
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: ce1916404 2024-03-30 (3 days ago)

**To Reproduce**

`vcpkg install boost:x64-windows miniupnpc:x64-windows openssl:x64-windows`
**Failure logs**

```
-- Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz -> tukaani-project-xz-v5.4.4.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from D:\OpenDev\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: D:\OpenDev\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz
[DEBUG] Trying to hash D:\OpenDev\vcpkg\downloads\tukaani-project-xz-v5.4.4.tar.gz.11332.part
[DEBUG] D:\OpenDev\vcpkg\downloads\tukaani-project-xz-v5.4.4.tar.gz.11332.part has hash fdadd30ae9a23919092425fcc312e8c3369ff12d3ddc81197170b75b253e0a800ceafdd73a16a18c246816a7f3a5ae6076e8e6929a5905d370788542185aa015
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz
File: D:\OpenDev\vcpkg\downloads\tukaani-project-xz-v5.4.4.tar.gz.11332.part
Expected hash: c28461123562564e030f3f733f078bc4c840e87598d9f4b718d4bca639120d8133f969c45d7bdc62f33f081d789ec0f14a1791fb7da18515682bfe3c0c7362e0
Actual hash: fdadd30ae9a23919092425fcc312e8c3369ff12d3ddc81197170b75b253e0a800ceafdd73a16a18c246816a7f3a5ae6076e8e6929a5905d370788542185aa015
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1031): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 3us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 720us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 7.7 s (7646018us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/liblzma/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)



```

```[tasklist]
### Tasks
```

**Comment by marekr** [comment] 2024-04-02 02:24
duplicate of https://github.com/microsoft/vcpkg/issues/37839

**Closed** 2024-04-02 03:10 UTC
Labels: depends:upstream-changes
