### ISSUE TITLE
mhook build failure

### ISSUE THREAD

**Issue by BenKey** [microsoft/vcpkg#8748] opened 2019-10-26 00:50 UTC
**Host Environment**
- Windows 10 Pro 1903 64-bit
- Build Tools for Visual Studio 2019

**To Reproduce**

Install mhook as follows.

`vcpkg install duktape --triplet x64-windows`

**Failure logs** 

```
[1/6] C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\cl.exe   -DNO_SANITY_CHECKS -DUNICODE -DWIN32_LEAN_AND_MEAN -D_UNICODE  /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\mhook.dir\disasm-lib\disasm.c.obj /FdCMakeFiles\mhook.dir\mhook.pdb /FS -c E:\vcpkg\buildtrees\mhook\src\2.5.1-ecdcd8e2a0\disasm-lib\disasm.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

[2/6] C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\cl.exe   -DNO_SANITY_CHECKS -DUNICODE -DWIN32_LEAN_AND_MEAN -D_UNICODE  /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\mhook.dir\disasm-lib\cpu.c.obj /FdCMakeFiles\mhook.dir\mhook.pdb /FS -c E:\vcpkg\buildtrees\mhook\src\2.5.1-ecdcd8e2a0\disasm-lib\cpu.c
FAILED: CMakeFiles/mhook.dir/disasm-lib/cpu.c.obj 
C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\cl.exe   -DNO_SANITY_CHECKS -DUNICODE -DWIN32_LEAN_AND_MEAN -D_UNICODE  /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\mhook.dir\disasm-lib\cpu.c.obj /FdCMakeFiles\mhook.dir\mhook.pdb /FS -c E:\vcpkg\buildtrees\mhook\src\2.5.1-ecdcd8e2a0\disasm-lib\cpu.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(2487): error C2118: negative subscript
[3/6] C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\cl.exe   -DNO_SANITY_CHECKS -DUNICODE -DWIN32_LEAN_AND_MEAN -D_UNICODE  /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\mhook.dir\disasm-lib\disasm_x86.c.obj /FdCMakeFiles\mhook.dir\mhook.pdb /FS -c E:\vcpkg\buildtrees\mhook\src\2.5.1-ecdcd8e2a0\disasm-lib\disasm_x86.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

[4/6] C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1423~1.281\bin\Hostx64\x64\cl.exe   /TP -DNO_SANITY_CHECKS -DUNICODE -DWIN32_LEAN_AND_MEAN -D_UNICODE  /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\mhook.dir\mhook-lib\mhook.cpp.obj /FdCMakeFiles\mhook.dir\mhook.pdb /FS -c E:\vcpkg\buildtrees\mhook\src\2.5.1-ecdcd8e2a0\mhook-lib\mhook.cpp
Microsoft (R) C/C++ Optimizing Compiler Version 19.23.28106.4 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

ninja: build stopped: subcommand failed.
```

**Additional context**

The problem occurs in the following code block from winnt.h.

```
// Much of the Windows SDK assumes the default packing of structs.
#if !defined(WINDOWS_IGNORE_PACKING_MISMATCH) && !defined(__midl) && !defined(MIDL_PASS) && !defined(SORTPP_PASS) && !defined(RC_INVOKED)
#if defined(__cplusplus) && (_MSC_VER >= 1600)
static_assert(__alignof(LARGE_INTEGER) == 8, "Windows headers require the default packing option. Changing this can lead to memory corruption."
    " This diagnostic can be disabled by building with WINDOWS_IGNORE_PACKING_MISMATCH defined.");
#elif _MSC_VER >= 1300
#pragma warning(push)
#pragma warning(disable: 4116)
C_ASSERT(TYPE_ALIGNMENT(LARGE_INTEGER) == 8);
#pragma warning(pop)
#endif
#endif
```

The C_ASSERT fails because of the following code in disasm-lib\cpu.h.

```
#pragma pack(push,1)

#include <windows.h>
```

I think reversing the order of the lines might suffice to fix the build error but I am not certain.

**Comment by LilyWangL** [comment] 2019-10-28 08:05
Thanks for posting this issue. This issue belongs to the Windows platform. This is C2118 error with Windows Kits 10.0.18362.0 in winnt.h. You can install mhook:x64-windows successfully on Windows SDK Version 10.0.17763.0.

**Comment by LilyWangL** [comment] 2019-10-28 09:25
Thanks for posting this issue. This issue belongs to the Windows platform. This is C2118 error with Windows Kits 10.0.18362.0 in winnt.h. Mhook:x64-windows can install successfully on Windows SDK Version 10.0.17763.0. You can remove Windows SDK Version 10.0.18362.0 and install Windows SDK Version 10.0.17763.0.

**Comment by Christsnatcher** [comment] 2020-02-12 23:15
Just wanted to mention that it's still impossible to build mhook. And being forced to uninstall the current SDK isn't something I would call a valid solution, sorry. I would be very grateful if this issue could be fixed properly.

**Comment by Pospelove** [comment] 2020-02-27 08:45
It also can be reproduced with x86-windows triplet.

**Comment by BenKey** [comment] 2020-02-27 12:58
I found the blocked by upstream conclusion to be unsatisfactory. I found a solution in my fork but I did not do a pull request because of the aforementioned blocked by upstream conclusion. It turns out that all you need to do is define the preprocessor symbol WINDOWS_IGNORE_PACKING_MISMATCH while building the project.

I did this in [commit de00bf0f7f921c5ca589b13a96c0389ef843f033](https://github.com/BenKey/vcpkg/commit/de00bf0f7f921c5ca589b13a96c0389ef843f033).

Should I do a pull request?

**Comment by Christsnatcher** [comment] 2020-02-27 14:33
@BenKey:

I would definitely appreciate a proper solution for this issue, thank you very much!

**Comment by Pospelove** [comment] 2020-02-28 14:58
@BenKey Cool. Will be glad to see your PR.

**Comment by BenKey** [comment] 2020-02-28 15:36
Then I will do that this weekend.
*-- *

*Ciao,*
*Ben Key*
*Email: bkey76@gmail.com <bkey76@gmail.com>*
*Website: https://sullivanandkey.com/ <https://sullivanandkey.com/>*
*-- *

**Comment by LilyWangL** [comment] 2020-06-17 08:04
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Closed by LilyWangL** 2020-06-17 08:04 UTC
Labels: depends:upstream-changes

**Comment by Christsnatcher** [comment] 2020-06-18 02:39
I can confirm the issue is fixed, many thanks everyone!
