### ISSUE TITLE
[opencolorio] update to <2.0.0>

### ISSUE THREAD

**Issue by pengguoqing** [microsoft/vcpkg#16443] opened 2021-02-27 08:49 UTC
Library name:
opencolor

New version number:
2.0.0

Other information that may be useful (release notes, etc...)
the present version is 1.1.1

**Comment by mbraca** [comment] 2021-03-25 18:55
Yes, please!!

**Comment by JonLiu1993** [comment] 2021-06-01 07:25
Duplicate of #18004

**Closed by JonLiu1993** 2021-06-01 07:25 UTC
Labels: category:port-update
