### ISSUE TITLE
[pkgconf] Build error on x64-windows

### ISSUE THREAD

**Issue by jsnhsu** [microsoft/vcpkg#36773] opened 2024-02-15 16:36 UTC
I just fetch the latest vcpkg and upgrade all the package I've downloaded before.  It fails.  I tried to rename installed directory and get a refresh install packages but get the same error.

The command I used is:
> ./vcpkg.exe --triplet=x64-windows-static install boost

Here is the error:
Building pkgconf:x64-windows@2.1.0...
-- Using cached pkgconf-pkgconf-pkgconf-2.1.0.tar.gz.
-- Extracting source D:/CppTool/vcpkg/downloads/pkgconf-pkgconf-pkgconf-2.1.0.tar.gz
-- Using source at D:/CppTool/vcpkg/buildtrees/pkgconf/src/conf-2.1.0-7b1cf1fe7f.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
-- Package x64-windows-rel
-- Fixing pkgconfig file: D:/CppTool/vcpkg/packages/pkgconf_x64-windows/lib/pkgconfig/libpkgconf.pc
-- Fixing pkgconfig file: D:/CppTool/vcpkg/packages/pkgconf_x64-windows/debug/lib/pkgconfig/libpkgconf.pc
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/jhsu2/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file D:/CppTool/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/CppTool/vcpkg/packages/pkgconf_x64-windows/tools/pkgconf/pkgconf.exe -installedDir D:/CppTool/vcpkg/packages/pkgconf_x64-windows/bin -verbose
    Working Directory: D:/CppTool/vcpkg
    Error code: -532462766
    See logs for more information:
      D:\CppTool\vcpkg\buildtrees\pkgconf\copy-tool-dependencies-0-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:9 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_copy_tool_dependencies.cmake:41 (z_vcpkg_copy_tool_dependencies_search)
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/pkgconf/portfile.cmake:79 (vcpkg_copy_tools)
  scripts/ports.cmake:170 (include)
[copy-tool-dependencies-0-err.log](https://github.com/microsoft/vcpkg/files/14299502/copy-tool-dependencies-0-err.log)

I also checked the text in the log I attached, it looks like that the dotnet is missing.  But I tried to run the following command witin same Powershell that I used by the above comamnd. 

> C:/Users/jhsu2/.dotnet/tools/pwsh.exe -noprofile -executionpolicy Bypass -nologo -file D:/CppTool/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/CppTool/vcpkg/packages/pkgconf_x64-windows/tools/pkgconf/pkgconf.exe -installedDir D:/CppTool/vcpkg/packages/pkgconf_x64-windows/bin -verbose

It works but contains some missing files.  I'm not sure what's wrong.  Those files are really missing in the directory. Please refer to this attachment.
[cmd_error.txt](https://github.com/microsoft/vcpkg/files/14307177/cmd_error.txt)

And here is my working environment:
> dotnet --info
.NET SDK:
 Version:           8.0.200
 Commit:            438cab6a9d
 Workload version:  8.0.200-manifests.e575128c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.200\

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.2
  Architecture: x64
  Commit:       1381d5ebd2

**Comment by jsnhsu** [comment] 2024-02-17 12:13
Found a workaround for this issue

1. I try: (not sure if it actually fixed anything)
> winget install --id Microsoft.Powershell --source winget
2. Clone a fresh new vcpkg from github, then install all the packages again.  Now the libs work.

**Comment by tsondergaard** [comment] 2024-03-20 23:47
This issue is real and should not be closed. Here is a supplementary error report with some slightly different output:

Package: pkgconf:x64-windows@2.1.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33521.0
-    vcpkg-tool version: 2024-03-14-7d353e869753e5609a1f1a057df3db8fd356e49d
    vcpkg-scripts version: 898b728ed 2024-03-19 (24 hours ago)

**To Reproduce**

`vcpkg install pkgconf`
**Failure logs**

```
-- Using cached python-3.11.8-embed-amd64.zip.
-- Found Python version '3.11.8 at C:/vitaldev/t/vcpkg/downloads/tools/python/python-3.11.8-x64/python.exe'
-- Using meson: C:/vitaldev/t/vcpkg/downloads/tools/meson-1.3.2-4876a3/meson.py
-- Downloading https://github.com/pkgconf/pkgconf/archive/pkgconf-2.1.0.tar.gz -> pkgconf-pkgconf-pkgconf-2.1.0.tar.gz...
-- Extracting source C:/vitaldev/t/vcpkg/downloads/pkgconf-pkgconf-pkgconf-2.1.0.tar.gz
-- Using source at C:/vitaldev/t/vcpkg/buildtrees/pkgconf/src/conf-2.1.0-7b1cf1fe7f.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
-- Package x64-windows-rel
-- Fixing pkgconfig file: C:/vitaldev/t/vcpkg/packages/pkgconf_x64-windows/lib/pkgconfig/libpkgconf.pc
-- Fixing pkgconfig file: C:/vitaldev/t/vcpkg/packages/pkgconf_x64-windows/debug/lib/pkgconfig/libpkgconf.pc
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:31 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/pkgconf/portfile.cmake:79 (vcpkg_copy_tools)
  scripts/ports.cmake:175 (include)
```

Note that the problem goes away if I checkout git tag `2024.02.14` so this is a regression.

**Comment by tsondergaard** [comment] 2024-03-21 00:00
I've git bisected my way to the culprit:

```
C:\src\t\vcpkg>git bisect good
a664e41ee50b61adcc90a44a761eca139a4b7dd7 is the first bad commit
commit a664e41ee50b61adcc90a44a761eca139a4b7dd7
Author: Alexander Neumann <30894796+Neumann-A@users.noreply.github.com>
Date:   Mon Mar 11 22:09:15 2024 +0100

    [vcpkg-tool-meson] Update meson to 1.3.2 (#28084)

 ports/gdk-pixbuf/fix-static-deps.patch             |  12 +
 ports/gdk-pixbuf/portfile.cmake                    |   2 +-
 ports/gdk-pixbuf/vcpkg.json                        |   2 +-
 ports/glib/libintl.patch                           |   2 +-
 ports/glib/vcpkg.json                              |   1 +
 ports/gobject-introspection/portfile.cmake         |  10 +-
 ports/gobject-introspection/vcpkg.json             |   6 +-
 ports/libnice/vcpkg.json                           |   8 +-
 ports/mesa/portfile.cmake                          |   5 +
 ports/mesa/vcpkg.json                              |   1 +
 ports/thorvg/portfile.cmake                        |   4 +-
 ports/thorvg/vcpkg.json                            |   1 +
 ports/vcpkg-tool-meson/adjust-args.patch           |  12 +
 ports/vcpkg-tool-meson/adjust-python-dep.patch     |  46 +++
 ports/vcpkg-tool-meson/meson-intl.patch            |   5 +-
 ports/vcpkg-tool-meson/meson.template.in           |  41 ++
 ports/vcpkg-tool-meson/portfile.cmake              |  86 ++--
 .../remove-freebsd-pcfile-specialization.patch     |  23 +-
 ports/vcpkg-tool-meson/vcpkg-port-config.cmake     |  64 ++-
 ports/vcpkg-tool-meson/vcpkg.json                  |   3 +-
 ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake | 452 +++++++++++++++++++++
 ports/vcpkg-tool-meson/vcpkg_install_meson.cmake   |  71 ++++
 ports/xcb-proto/portfile.cmake                     |   4 +-
 ports/xcb-proto/vcpkg.json                         |   2 +-
 scripts/cmake/vcpkg_configure_meson.cmake          |  27 +-
 .../cmake/vcpkg_find_acquire_program(MESON).cmake  |   2 +-
 versions/baseline.json                             |  18 +-
 versions/g-/gdk-pixbuf.json                        |   5 +
 versions/g-/glib.json                              |   5 +
 versions/g-/gobject-introspection.json             |   5 +
 versions/l-/libnice.json                           |   5 +
 versions/m-/mesa.json                              |   5 +
 versions/t-/thorvg.json                            |   5 +
 versions/v-/vcpkg-tool-meson.json                  |   5 +
 versions/x-/xcb-proto.json                         |   5 +
 35 files changed, 849 insertions(+), 101 deletions(-)
 create mode 100644 ports/gdk-pixbuf/fix-static-deps.patch
 create mode 100644 ports/vcpkg-tool-meson/adjust-args.patch
 create mode 100644 ports/vcpkg-tool-meson/adjust-python-dep.patch
 create mode 100644 ports/vcpkg-tool-meson/meson.template.in
 create mode 100644 ports/vcpkg-tool-meson/vcpkg_configure_meson.cmake
 create mode 100644 ports/vcpkg-tool-meson/vcpkg_install_meson.cmake
```

@Neumann-A, could you take a look at this issue and maybe see if you can spot what the problem is?

**Comment by tsondergaard** [comment] 2024-03-21 00:22
Here is the full output of running `.\vcpkg install pkgconf` which shows vcpkg-tool-meson being built as a dependency:

```
Computing installation plan...
The following packages will be built and installed:
    pkgconf:x64-windows@2.1.0
  * vcpkg-tool-meson:x64-windows@1.3.2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
A suitable version of powershell-core was not found (required v7.2.16) Downloading portable powershell-core 7.2.16...
Downloading powershell-core...
https://github.com/PowerShell/PowerShell/releases/download/v7.2.16/PowerShell-7.2.16-win-x64.zip->C:\vitaldev\t\vcpkg\downloads\PowerShell-7.2.16-win-x64.zip
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.16/PowerShell-7.2.16-win-x64.zip
Extracting powershell-core...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Professional/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exe
Installing 1/2 vcpkg-tool-meson:x64-windows@1.3.2...
Building vcpkg-tool-meson:x64-windows@1.3.2...
-- Installing: C:/vitaldev/t/vcpkg/packages/vcpkg-tool-meson_x64-windows/share/vcpkg-tool-meson/copyright
-- Downloading https://www.python.org/ftp/python/3.11.8/python-3.11.8-embed-amd64.zip -> python-3.11.8-embed-amd64.zip...
-- Found Python version '3.11.8 at C:/vitaldev/t/vcpkg/downloads/tools/python/python-3.11.8-x64/python.exe'
-- Downloading https://github.com/mesonbuild/meson/archive/614d436232d3a86518164cbe2b8af12db3bde009.tar.gz -> meson-614d436232d3a86518164cbe2b8af12db3bde009.tar.gz...
cmake -E tar: warning: skipping symbolic link "meson-614d436232d3a86518164cbe2b8af12db3bde009/test cases/frameworks/35 boost symlinks/boost/include/boost" -> "../Cellar/boost/0.3.0/include/boost".
cmake -E tar: warning: skipping symbolic link "meson-614d436232d3a86518164cbe2b8af12db3bde009/test cases/frameworks/35 boost symlinks/boost/lib/boost_python-vc142-mt-gd-x32-0_3.lib" -> "../Cellar/boost-python/0.3.0/lib/boost_python-vc142-mt-gd-x32-0_3.lib".
cmake -E tar: warning: skipping symbolic link "meson-614d436232d3a86518164cbe2b8af12db3bde009/test cases/frameworks/35 boost symlinks/boost/lib/boost_python-vc142-mt-gd-x64-0_3.lib" -> "../Cellar/boost-python/0.3.0/lib/boost_python-vc142-mt-gd-x64-0_3.lib".
cmake -E tar: warning: skipping symbolic link "meson-614d436232d3a86518164cbe2b8af12db3bde009/test cases/frameworks/35 boost symlinks/boost/lib/boost_regex-vc142-mt-gd-x32-0_3.lib" -> "../Cellar/boost/0.3.0/lib/boost_regex-vc142-mt-gd-x32-0_3.lib".
cmake -E tar: warning: skipping symbolic link "meson-614d436232d3a86518164cbe2b8af12db3bde009/test cases/frameworks/35 boost symlinks/boost/lib/boost_regex-vc142-mt-gd-x64-0_3.lib" -> "../Cellar/boost/0.3.0/lib/boost_regex-vc142-mt-gd-x64-0_3.lib".
cmake -E tar: warning: skipping symbolic link "meson-614d436232d3a86518164cbe2b8af12db3bde009/test cases/frameworks/35 boost symlinks/boost/lib/libboost_python.so.0.3.0" -> "../Cellar/boost-python/0.3.0/lib/libboost_python.so.0.3.0".
cmake -E tar: warning: skipping symbolic link "meson-614d436232d3a86518164cbe2b8af12db3bde009/test cases/frameworks/35 boost symlinks/boost/lib/libboost_regex.so.0.3.0" -> "../Cellar/boost/0.3.0/lib/libboost_regex.so.0.3.0".
-- Applying patch C:/vitaldev/t/vcpkg/packages/vcpkg-tool-meson_x64-windows/share/vcpkg-tool-meson/adjust-args.patch
-- Applying patch C:/vitaldev/t/vcpkg/packages/vcpkg-tool-meson_x64-windows/share/vcpkg-tool-meson/meson-intl.patch
-- Applying patch C:/vitaldev/t/vcpkg/packages/vcpkg-tool-meson_x64-windows/share/vcpkg-tool-meson/adjust-python-dep.patch
-- Applying patch C:/vitaldev/t/vcpkg/packages/vcpkg-tool-meson_x64-windows/share/vcpkg-tool-meson/remove-freebsd-pcfile-specialization.patch
-- Using meson: C:/vitaldev/t/vcpkg/downloads/tools/meson-1.3.2-4876a3/meson.py
-- Performing post-build validation
Elapsed time to handle vcpkg-tool-meson:x64-windows: 5.4 s
vcpkg-tool-meson:x64-windows package ABI: ec3c3af1374aba6cb6c97b93268e7f64d0f6a47a661cc13a7304934a532b1197
Installing 2/2 pkgconf:x64-windows@2.1.0...
Building pkgconf:x64-windows@2.1.0...
-- Using cached python-3.11.8-embed-amd64.zip.
-- Found Python version '3.11.8 at C:/vitaldev/t/vcpkg/downloads/tools/python/python-3.11.8-x64/python.exe'
-- Using meson: C:/vitaldev/t/vcpkg/downloads/tools/meson-1.3.2-4876a3/meson.py
-- Downloading https://github.com/pkgconf/pkgconf/archive/pkgconf-2.1.0.tar.gz -> pkgconf-pkgconf-pkgconf-2.1.0.tar.gz...
-- Extracting source C:/vitaldev/t/vcpkg/downloads/pkgconf-pkgconf-pkgconf-2.1.0.tar.gz
-- Using source at C:/vitaldev/t/vcpkg/buildtrees/pkgconf/src/conf-2.1.0-7b1cf1fe7f.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Package x64-windows-dbg
-- Package x64-windows-rel
-- Fixing pkgconfig file: C:/vitaldev/t/vcpkg/packages/pkgconf_x64-windows/lib/pkgconfig/libpkgconf.pc
-- Fixing pkgconfig file: C:/vitaldev/t/vcpkg/packages/pkgconf_x64-windows/debug/lib/pkgconfig/libpkgconf.pc
CMake Error at scripts/cmake/vcpkg_copy_tool_dependencies.cmake:31 (message):
  Could not find PowerShell Core; please open an issue to report this.
Call Stack (most recent call first):
  scripts/cmake/vcpkg_copy_tools.cmake:48 (vcpkg_copy_tool_dependencies)
  ports/pkgconf/portfile.cmake:79 (vcpkg_copy_tools)
  scripts/ports.cmake:175 (include)


error: building pkgconf:x64-windows failed with: BUILD_FAILED
Elapsed time to handle pkgconf:x64-windows: 8.5 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+pkgconf
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[pkgconf]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fvitaldev%2Ft%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```

**Comment by dg0yt** [comment] 2024-03-21 04:40
Maybe fixed by  #37585?

**Comment by tsondergaard** [comment] 2024-03-21 13:21
@dg0yt, yes, the tools directory being clobbered is indeed the problem.

**Comment by BillyONeal** [comment] 2024-03-21 20:19
Should be fixed by https://github.com/microsoft/vcpkg/pull/37585

**Closed by BillyONeal** 2024-03-21 20:19 UTC
Labels: category:question
