### ISSUE TITLE
[box2d] build failure

### ISSUE THREAD

**Issue by yupaul** [microsoft/vcpkg#9462] opened 2019-12-27 11:30 UTC
**Host Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
`.\vcpkg install box2d:x64-windows`

**Failure logs** 
The following packages will be built and installed:
    box2d[core]:x64-windows
Starting package 1/1: box2d:x64-windows
Building package box2d[core]:x64-windows...
-- Note: box2d only supports static library linkage. Building static library.
-- Downloading https://github.com/erincatto/Box2D/archive/374664b2a4ce2e7c24fbad6e1ed34bebcc9ab6bc.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):

  File does not have expected hash:

          File path: [ C:/vcpkg/downloads/temp/erincatto-Box2D-374664b2a4ce2e7c24fbad6e1ed34bebcc9ab6bc.tar.gz ]
      Expected hash: [ 39074bab01b36104aa685bfe39b40eb903d9dfb54cc3ba8098125db5291f55a8a9e578fc59563b2e8743abbbb26f419be7ae1524e235e7bd759257f99ff96bda ]
        Actual hash: [ 89a46287a7dcb937d58454237d8ca0d3f5788bd544ccd045a282c38c7d197380fa5c5264c5dcfa9e19f250b3c9887dbe2252b188fc7ecc40b74ed241d7634650 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:182 (test_hash)
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/box2d/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)

Error: Building package box2d:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: box2d:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by PhoebeHui** [comment] 2020-01-02 10:45
@yupaul , thanks for reporting this issue!

Above PR should address this issue.

**Comment by WeskerPower** [comment] 2020-01-05 11:35
any solution ?

**Comment by VitalZero** [comment] 2020-01-06 16:16
This is too easy to fix. 
Just go to "vcpkg-master/ports/box2d" and in there, modify the portfile.cmake.
look up for SHA512 and change the hash: 39074bab01b36104aa685bfe39b40eb903d9dfb54cc3ba8098125db5291f55a8a9e578fc59563b2e8743abbbb26f419be7ae1524e235e7bd759257f99ff96bda
for: 89a46287a7dcb937d58454237d8ca0d3f5788bd544ccd045a282c38c7d197380fa5c5264c5dcfa9e19f250b3c9887dbe2252b188fc7ecc40b74ed241d7634650 (or the one you get as in the file received)

It worked for me:

-- Note: box2d only supports static library linkage. Building static library.
-- Downloading https://github.com/erincatto/Box2D/archive/374664b2a4ce2e7c24fbad6e1ed34bebcc9ab6bc.t
ar.gz...
-- Extracting source C:/vcpkg/vcpkg-master/downloads/erincatto-Box2D-374664b2a4ce2e7c24fbad6e1ed34be
bcc9ab6bc.tar.gz
-- Using source at C:/vcpkg/vcpkg-master/buildtrees/box2d/src/ebcc9ab6bc-726f8acd9e
-- Downloading https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-win.zip...
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package box2d[core]:x86-windows... done
Installing package box2d[core]:x86-windows...
Installing package box2d[core]:x86-windows... done
Elapsed time for package box2d:x86-windows: 29.54 s

Total elapsed time: 29.54 s

The package box2d:x86-windows provides CMake targets:

    find_package(unofficial-box2d CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::box2d::Box2D)

**Comment by PhoebeHui** [comment] 2020-01-09 08:14
@yupaul @WeskerPower, the PR has been merged, above issue should be fixed, please get vcpkg latest source and try again.

**Closed by PhoebeHui** 2020-01-09 08:14 UTC
Labels: port bug

**Comment by WeskerPower** [comment] 2020-01-09 08:26
Im having the same issue but then again i might now update it, when i pull it it gives me ID	Author	Date	Message
f2c10569022387becf694f16e20068a67fd6c3e0	Phoebe <20694052+PhoebeHui@users.noreply.github.com>	1/9/2020 12:33:48 AM +00:00	Update baseline (#9579)


the error seems to be the same thing
`.\vcpkg install box2d
The following packages will be built and installed:
    box2d[core]:x86-windows
Starting package 1/1: box2d:x86-windows
Building package box2d[core]:x86-windows...
-- Note: box2d only supports static library linkage. Building static library.
-- Downloading https://github.com/erincatto/Box2D/archive/37e2dc25f8da158abda10324d75cb4d1db009adf.tar.gz...
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):


  File does not have expected hash:

          File path: [ E:/Gits/vcpkg/downloads/temp/erincatto-Box2D-37e2dc25f8da158abda10324d75cb4d1db009adf.tar.gz ]
      Expected hash: [ 89a46287a7dcb937d58454237d8ca0d3f5788bd544ccd045a282c38c7d197380fa5c5264c5dcfa9e19f250b3c9887dbe2252b188fc7ecc40b74ed241d7634650 ]
        Actual hash: [ c9021b6bbc8ee405e38418bdadc136814fb66d5f4928ffd06d2ed016751613ecc3e82e7f60851fdc7a2e13594f68c21e7b7adb06d35a5a02314235132556d174 ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".



Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:182 (test_hash)
  scripts/cmake/vcpkg_from_github.cmake:132 (vcpkg_download_distfile)
  ports/box2d/portfile.cmake:5 (vcpkg_from_github)
  scripts/ports.cmake:94 (include)


Error: Building package box2d:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: box2d:x86-windows
  Vcpkg version: 2019.09.12-nohash

Additionally, attach any relevant sections from the log files above.`

**Comment by PhoebeHui** [comment] 2020-01-09 08:32
@WeskerPower, could you clean the source and try again?

Double confirmed, it works well for me.
PS F:\vcpkg\src> ./vcpkg install box2d
The following packages will be built and installed:
    box2d[core]:x86-windows
Starting package 1/1: box2d:x86-windows
Building package box2d[core]:x86-windows...
-- Note: box2d only supports static library linkage. Building static library.
-- Downloading https://github.com/erincatto/Box2D/archive/37e2dc25f8da158abda10324d75cb4d1db009adf.tar.gz...
-- Extracting source F:/VCPKG/src/downloads/erincatto-Box2D-37e2dc25f8da158abda10324d75cb4d1db009adf.tar.gz
-- Applying patch export-targets.patch
-- Using source at F:/VCPKG/src/buildtrees/box2d/src/d1db009adf-75c8a0adf4
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Installing: F:/VCPKG/src/packages/box2d_x86-windows/share/box2d/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package box2d[core]:x86-windows... done
Installing package box2d[core]:x86-windows...
Installing package box2d[core]:x86-windows... done
Elapsed time for package box2d:x86-windows: 15.63 s

Total elapsed time: 15.63 s

The package box2d:x86-windows provides CMake targets:

    find_package(unofficial-box2d CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::box2d::box2d)

**Comment by WeskerPower** [comment] 2020-01-09 09:07
after some pull i got it working indeed it is working now sorry 

```
-- Installing: E:/Gits/vcpkg/packages/box2d_x86-windows/share/box2d/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package box2d[core]:x86-windows... done
Installing package box2d[core]:x86-windows...
Installing package box2d[core]:x86-windows... done
Elapsed time for package box2d:x86-windows: 1.05 min

Total elapsed time: 1.05 min

The package box2d:x86-windows provides CMake targets:

    find_package(unofficial-box2d CONFIG REQUIRED)
    target_link_libraries(main PRIVATE unofficial::box2d::box2d)
```

problems with  cache
