### ISSUE TITLE
Package: vtk:x64-windows build failure

### ISSUE THREAD

**Issue by GoldenswordYJF** [microsoft/vcpkg#9055] opened 2019-11-20 11:34 UTC
**Host Environment**
- Windows10 1903 18362.239
- Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
[x64-windows.vcpkg_abi_info.txt](https://github.com/microsoft/vcpkg/files/3868952/x64-windows.vcpkg_abi_info.txt)

**To Reproduce**
`./vcpkg install vtk:x64-windows`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
-Please attach any additional failure logs mentioned in the console output.

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by GoldenswordYJF** [comment] 2019-11-20 11:41
Building package vtk[core]:x64-windows...
-- Using cached D:/OpenSrc/vcpkg-master/downloads/Kitware-VTK-v8.2.0.tar.gz
-- Using source at D:/OpenSrc/vcpkg-master/buildtrees/vtk/src/v8.2.0-fc49221417
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: D:/OpenSrc/vcpkg-master/buildtrees/vtk/x64-windows-dbg
    See logs for more information:
      D:\OpenSrc\vcpkg-master\buildtrees\vtk\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:96 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/vtk/portfile.cmake:120 (vcpkg_install_cmake)
  scripts/ports.cmake:94 (include)


Error: Building package vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows
  Vcpkg version: 2019.09.12-nohash

**Comment by LilyWangL** [comment] 2019-11-22 06:19
Hi @GoldenswordYJF, can you provide this log?
`D:\OpenSrc\vcpkg-master\buildtrees\vtk\install-x64-windows-dbg-out.log`

Thanks.

**Comment by GoldenswordYJF** [comment] 2019-11-25 11:36
@LilyWangL ,Hi, here it is, thanks.

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/3886382/install-x64-windows-dbg-out.log)

**Comment by LilyWangL** [comment] 2019-11-26 05:54
Hi @GoldenswordYJF, thanks for your log. I can't reproduce this issue locally. How much disk space have you remaining?

**Comment by GoldenswordYJF** [comment] 2019-11-27 03:20
Hi，
My laptop's free disk space is about 50 GB.

At 2019-11-26 13:54:25, "Lily" <notifications@github.com> wrote:


Hi @GoldenswordYJF, thanks for your log. I can't reproduce this issue locally. How much disk space have you remaining?

**Comment by GoldenswordYJF** [comment] 2019-11-28 10:16
Hi,
    Today, I tried to install VTK again, It was successed, and I notified that, there's message like bellow:
    Restarting Build without parallelism because memory exceeded.
    I think before failure must caused by memory exceed.  but it was not able to restart without parallelism.
    Furthermore,, My laptop has 16GB memory, it was not exhausted during building.

**Comment by LilyWangL** [comment] 2019-11-29 03:03
I think so. It built failed because of your device memory exceed. You can clear up something to make it build successfully. Thanks for posting this issue, I am closing this issue for now.

**Closed by LilyWangL** 2019-11-29 03:03 UTC
Labels: needs-repro
