### ISSUE TITLE
[grpc] update to 1.45.2

### ISSUE THREAD

**Issue by PriitUring** [microsoft/vcpkg#24313] opened 2022-04-21 18:30 UTC
Library name: grpc

New version number: 1.45.2

https://github.com/grpc/grpc/releases/tag/v1.45.2

**Comment by JonLiu1993** [comment] 2022-05-20 09:55
Duplicate of https://github.com/microsoft/vcpkg/issues/24557

**Closed by JonLiu1993** 2022-05-20 09:55 UTC
Labels: category:port-update
