### ISSUE TITLE
cannot install openssl

### ISSUE THREAD

**Issue by maorp** [Microsoft/vcpkg#5752] opened 2019-03-20 16:21 UTC
Package: openssl-windows:x64-windows
  Vcpkg version: 2018.11.23-nohash

**Comment by maorp** [comment] 2019-03-20 16:25
D:\dev\vcpkg>vcpkg install openssl:x64-windows
The following packages will be built and installed:
    openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/2: openssl-windows:x64-windows
Building package openssl-windows[core]:x64-windows...
-- Using cached D:/dev/vcpkg/downloads/openssl-1.0.2q.tar.gz
-- Applying patch D:/dev/vcpkg/ports/openssl-windows/ConfigureIncludeQuotesFix.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/dev/vcpkg/ports/openssl-windows/STRINGIFYPatch.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/dev/vcpkg/ports/openssl-windows/EnableWinARM32.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch D:/dev/vcpkg/ports/openssl-windows/EmbedSymbolsInStaticLibsZ7.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Configure x64-windows-rel
-- Configure x64-windows-rel done
-- Build x64-windows-rel
-- Build x64-windows-rel done
-- Configure x64-windows-dbg
-- Configure x64-windows-dbg done
-- Build x64-windows-dbg
-- Build x64-windows-dbg done
-- Installing: D:/dev/vcpkg/packages/openssl-windows_x64-windows/share/openssl-windows/copyright
-- Performing CMake integration test
CMake Error at scripts/cmake/vcpkg_test_cmake.cmake:71 (message):
  CMake integration test failed; unable to find_package(OpenSSL MODULE
  REQUIRED)
Call Stack (most recent call first):
  ports/openssl-windows/portfile.cmake:171 (vcpkg_test_cmake)
  scripts/ports.cmake:71 (include)

**Comment by jwillemsen** [comment] 2019-03-20 17:14
See https://github.com/Microsoft/vcpkg/pull/5747

**Comment by jwillemsen** [comment] 2019-03-20 17:15
Duplicate of https://github.com/Microsoft/vcpkg/issues/5713

**Comment by jwillemsen** [comment] 2019-03-27 14:06
Should be fixed

**Comment by LarryIII** [comment] 2019-03-28 06:37
vcpkg_test_cmake() has been disabled by c2ad1ba. With that change openssl-windows will build so I am closing this issue for now. Please re-open if this is still a issue for you. Thank you!

**Closed by LarryIII** 2019-03-28 06:37 UTC
Labels: port bug
