### ISSUE TITLE
Poppler 

### ISSUE THREAD

**Issue by kossiBlaise** [microsoft/vcpkg#9673] opened 2020-01-14 00:25 UTC
Library name: Poppler

Library description: Poppler is a package to manipulate PDF documents

Source repository URL: https://anongit.freedesktop.org/git/poppler/poppler.git

Project homepage (if different from the source repository): https://poppler.freedesktop.org/releases.html

Anything else that is useful to know when adding (such as optional features the library may have that should be included): We really need to have the VS binaries for this package

**Comment by nazar554** [comment] 2020-01-14 19:18
duplicate of #4702 ?

**Comment by LilyWangL** [comment] 2020-05-25 06:14
If you wish to add this port in the future, you can reopen this issue, but we're closing it for now.

**Closed by LilyWangL** 2020-05-25 06:14 UTC
Labels: category:new-port, info:good-first-issue

**Comment by playgithub** [comment] 2020-11-13 08:54
need poppler
