### ISSUE TITLE
Vcpkg crashes while installing 7zip

### ISSUE THREAD

**Issue by rmccampbell** [microsoft/vcpkg#23448] opened 2022-03-09 08:56 UTC
**Describe the bug**
I pulled the latest revision of vcpkg (hash 857bccdad005957391854448a15ba30e8c118503) and ran `vcpkg upgrade`, after a while I got the error "vcpkg has crashed; no additional details are available.", right after "Extracting 7zip...". I then tried installing a few packages and got the same error. See full log below.

**Environment**
- OS: Windows 10
- Compiler: MSVC (but the error isn't during compilation)

**To Reproduce**
1. ./vcpkg install any package
2. Wait for download/build
3. vcpkg crashes; see below

**Expected behavior**
vcpkg does not crash

**Failure logs** 
```
❯ vcpkg.exe install fmt
Computing installation plan...
The following packages will be built and installed:
    fmt[core]:x64-windows -> 8.1.1#1
Detecting compiler hash for triplet x64-windows...
Restored 0 packages from C:\Users\Ryan\AppData\Local\vcpkg\archives in 389.3 us. Use --debug to see more details.
Starting package 1/1: fmt:x64-windows
Building package fmt[core]:x64-windows...
-- Using cached fmtlib-fmt-8.1.1.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/fmt/src/8.1.1-11f8359597.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/fmtlib-fmt-8.1.1.tar.gz
-- Applying patch fix-write-batch.patch
-- Applying patch fix-invalid-command.patch
-- Using source at C:/vcpkg/buildtrees/fmt/src/8.1.1-11f8359597.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/vcpkg/packages/fmt_x64-windows/share/fmt/copyright
-- Fixing pkgconfig file: C:/vcpkg/packages/fmt_x64-windows/lib/pkgconfig/fmt.pc
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
-- Fixing pkgconfig file: C:/vcpkg/packages/fmt_x64-windows/debug/lib/pkgconfig/fmt.pc
-- Installing: C:/vcpkg/packages/fmt_x64-windows/share/fmt/usage
-- Performing post-build validation
-- Performing post-build validation done
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Extracting 7zip...
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Extracting 7zip...
Error: vcpkg has crashed; no additional details are available.
The source line is D:\a\_work\1\s\src\vcpkg\archives.cpp(100)

```

**Comment by JackBoosY** [comment] 2022-03-09 09:29
Related PR: https://github.com/microsoft/vcpkg/pull/23424
cc @BillyONeal

**Comment by JackBoosY** [comment] 2022-03-09 09:32
Related code: 
https://github.com/microsoft/vcpkg-tool/blob/85dc3d9d4e1e7b643f811eac0b9d884419fead79/src/vcpkg/archives.cpp#L93-L109

**Comment by ningdr** [comment] 2022-03-09 11:17
-- Performing post-build validation
-- Performing post-build validation done
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Extracting 7zip...
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Extracting 7zip...
Error: vcpkg has crashed; no additional details are available.
The source line is D:\a\_work\1\s\src\vcpkg\archives.cpp(100)

**Comment by mattkotys** [comment] 2022-03-09 14:20
Having the same problem, repeatable on at least two packages (eigen3, fmt)

**Comment by mattkotys** [comment] 2022-03-09 14:58
Go to vcpkg install directory, and type
`.\bootstrap-vcpkg.bat`

**Comment by BillyONeal** [comment] 2022-03-09 18:13
This has been a rapidly moving issue, please confirm the version of vcpkg in use with the problem. You can get the version with `vcpkg version` (or `vcpkg --version`).

If the one you're using is older than `Vcpkg package management program version 2022-03-08-85dc3d9d4e1e7b643f811eac0b9d884419fead79` please try to fetch that copy and continue.

**Comment by rmccampbell** [comment] 2022-03-09 22:59
Confirmed the version I have is 2022-03-08-85dc3d9d4e1e7b643f811eac0b9d884419fead79. How is the version different from the commit hash?

**Comment by rmccampbell** [comment] 2022-03-09 23:07
Actually that's odd, I was able to check out an earlier commit and install things fine, and just now when I switched back to head (same commit) I don't see the problem any more. Maybe it was a problem with the 7zip file it was downloading that was somehow fixed externally?

**Comment by BillyONeal** [comment] 2022-03-09 23:09
> Confirmed the version I have is 2022-03-08-85dc3d9d4e1e7b643f811eac0b9d884419fead79.

And that version is still exhibiting the reported problem?

> How is the version different from the commit hash?

The tool `vcpkg.exe` had its development moved to https://github.com/microsoft/vcpkg-tool/ when we started doing binary releases of the tool, which means its commit SHA is no longer related to the commit of this repo you have. That 85dc3d9d4e1e7b643f811eac0b9d884419fead79 corresponds to https://github.com/microsoft/vcpkg-tool/commit/85dc3d9d4e1e7b643f811eac0b9d884419fead79

> Actually that's odd, I was able to check out an earlier commit and install things fine, and just now when I switched back to head (same commit) I don't see the problem any more.

That means there was a change to this repo made which needed a newer `vcpkg.exe`. Probably the changes necessary to start getting 7zip by unpacking it with CMake rather than going through MSI.

**Comment by rmccampbell** [comment] 2022-03-09 23:16
Well I don't see the problem now on 2022-03-08-85dc3d9d4e1e7b643f811eac0b9d884419fead79. I had switched to the older revision last night, then switched back just now to check the version, and noticed when I tried installing something it worked. I see that the 7zip folder in downloads\tools is updated as well.

**Comment by rmccampbell** [comment] 2022-03-09 23:20
Actually I forgot I did run .\bootstrap-vcpkg.bat this morning, I assume that fetched the newer version of vcpkg, but I didn't actually try it until now

**Comment by BillyONeal** [comment] 2022-03-09 23:21
Bootstrap fetches the version of the tool corresponding to the version of the registry you're currently using. If you change branches in the catalog, you may have to bootstrap again. (Although this is rare, it did happen in this case as a result of msiexec getting broken by us)

**Comment by JackBoosY** [comment] 2022-03-10 02:41
So this issue should be fixed?

**Comment by rhuijben** [comment] 2022-03-10 08:31
Just updated my github action in my own repository to use commit 5a8a1dfff8e2dffd4c8cc2d1fc0da379ffd18b25 of vcpkg (=current master at this time) and can reproduce this issue.

```
Run vcpkg.exe install "tiff[core]:x64-windows-static-md" "proj[core,tiff]:x64-windows-static-md" "tiff[core]:x86-windows-static-md" "proj[core,tiff]:x86-windows-static-md"
Computing installation plan...
The following packages will be built and installed:
  * liblzma[core]:x64-windows-static-md -> 5.2.5#5
  * liblzma[core]:x86-windows-static-md -> 5.2.5#5
  * nlohmann-json[core]:x64-windows-static-md -> 3.[10](https://github.com/AmpScm/SharpProj/runs/5492637501?check_suite_focus=true#step:7:10).5
  * nlohmann-json[core]:x86-windows-static-md -> 3.10.5
    proj[core,tiff]:x64-windows-static-md -> 9.0.0
    proj[core,tiff]:x86-windows-static-md -> 9.0.0
  * sqlite3[core,tool]:x64-windows -> 3.37.2#1
  * sqlite3[core]:x64-windows-static-md -> 3.37.2#1
  * sqlite3[core]:x86-windows-static-md -> 3.37.2#1
    tiff[core,lzma,zip]:x64-windows-static-md -> 4.3.0#6
    tiff[core,lzma,zip]:x86-windows-static-md -> 4.3.0#6
  * vcpkg-cmake[core]:x64-windows -> 2022-01-19
  * vcpkg-cmake-config[core]:x64-windows -> 2022-02-06
  * zlib[core]:x64-windows-static-md -> 1.2.[11](https://github.com/AmpScm/SharpProj/runs/5492637501?check_suite_focus=true#step:7:11)#[13](https://github.com/AmpScm/SharpProj/runs/5492637501?check_suite_focus=true#step:7:13)
  * zlib[core]:x86-windows-static-md -> 1.2.11#13
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x64-windows-static-md...
Detecting compiler hash for triplet x86-windows-static-md...
Restored 0 packages from D:\a\SharpProj\b\vcpkg_cache in 310.7 us. Use --debug to see more details.
Starting package 1/[15](https://github.com/AmpScm/SharpProj/runs/5492637501?check_suite_focus=true#step:7:15): vcpkg-cmake:x64-windows
Building package vcpkg-cmake[core]:x64-windows...
-- Installing: D:/a/SharpProj/SharpProj/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: D:/a/SharpProj/SharpProj/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: D:/a/SharpProj/SharpProj/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: D:/a/SharpProj/SharpProj/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_get_vars.cmake
-- Installing: D:/a/SharpProj/SharpProj/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/cmake_get_vars
-- Installing: D:/a/SharpProj/SharpProj/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/cmake_get_vars/CMakeLists.txt
-- Installing: D:/a/SharpProj/SharpProj/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: D:/a/SharpProj/SharpProj/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
-- Performing post-build validation done
A suitable version of 7zip was not found (required v[21](https://github.com/AmpScm/SharpProj/runs/5492637501?check_suite_focus=true#step:7:21).7.0). Downloading portable 7zip v21.7.0...
Downloading 7zip...
  https://www.7-zip.org/a/7z2107-extra.7z -> D:\a\SharpProj\SharpProj\vcpkg\downloads\7z2107-extra.7z
Extracting 7zip...
A suitable version of 7zip was not found (required v21.7.0). Downloading portable 7zip v21.7.0...
Extracting 7zip...
Error: vcpkg has crashed; no additional details are available.
The source line is D:\a\_work\1\s\src\vcpkg\archives.cpp(101)
```

**Comment by dg0yt** [comment] 2022-03-10 08:37
> `Error: vcpkg has crashed; no additional details are available.`

Given that vcpkg-tool doesn't really (need to) crash here, it should be modified to report repo and tool version (as it does for failed ports). After all, this issue is bound to a combination of repo version (data files) and vcpkg-tool version (fetch method).

**Comment by rhuijben** [comment] 2022-03-10 09:49
Could https://github.com/microsoft/vcpkg/commit/43cb9a9026bf30dcc96e9f24bdeb826eb61386f2#r68373892 be related?

But a tool that requires itself to extract looks dangerous.

**Comment by rhuijben** [comment] 2022-03-10 09:54
And https://github.com/microsoft/vcpkg-tool/commit/7dfebffb2b25c0fda564dd60346d9c9674475f7f also touches this code.

**Comment by fabiosvm** [comment] 2022-03-11 01:15
I got around this bug by installing vcpkg as follows:
`
  curl -sSLO https://github.com/microsoft/vcpkg/archive/refs/tags/2022.02.23.tar.gz
  tar -xzf 2022.02.23.tar.gz
  cd vcpkg-2022.02.23
  bootstrap-vcpkg.bat
  vcpkg integrate install
`

**Comment by BillyONeal** [comment] 2022-03-11 02:20
> Just updated my github action in my own repository to use commit [5a8a1df](https://github.com/microsoft/vcpkg/commit/5a8a1dfff8e2dffd4c8cc2d1fc0da379ffd18b25) of vcpkg (=current master at this time) and can reproduce this issue.

Is the copy of vcpkg.exe in use at least as new as that commit?

> > `Error: vcpkg has crashed; no additional details are available.`
> 
> Given that vcpkg-tool doesn't really (need to) crash here, it should be modified to report repo and tool version (as it does for failed ports). After all, this issue is bound to a combination of repo version (data files) and vcpkg-tool version (fetch method).

The problem here is that people are using older copies of the tool so the cat's kinda already out of the bag. (Although I agree for future releases improving diagnostics is always good)

If it is up to me we remove vcpkgTools.xml completely which would also erase this problem. (It's caused by the old tool not liking coordinated changes we made to vcpkgTools.xml to workaround msi)

**Comment by rhuijben** [comment] 2022-03-11 05:30
> > Just updated my github action in my own repository to use commit [5a8a1df](https://github.com/microsoft/vcpkg/commit/5a8a1dfff8e2dffd4c8cc2d1fc0da379ffd18b25) of vcpkg (=current master at this time) and can reproduce this issue.
> 
> Is the copy of vcpkg.exe in use at least as new as that commit?

It is a standard GitHub action, so yes it calls the bootstrap she'll script and uses the current version, as reported by the already posted build output.

The very popular standard vcpkg buildscript on GitHub is broken against master on GitHub's windows 2022 action runners.

> 
> > > `Error: vcpkg has crashed; no additional details are available.`
> > 
> > 
> > Given that vcpkg-tool doesn't really (need to) crash here, it should be modified to report repo and tool version (as it does for failed ports). After all, this issue is bound to a combination of repo version (data files) and vcpkg-tool version (fetch method).
> 
> The problem here is that people are using older copies of the tool so the cat's kinda already out of the bag. (Although I agree for future releases improving diagnostics is always good)

This is with the very last 2022-03-09 release

> 
> If it is up to me we remove vcpkgTools.xml completely which would also erase this problem. (It's caused by the old tool not liking coordinated changes we made to vcpkgTools.xml to workaround msi)

**Comment by rhuijben** [comment] 2022-03-11 05:36
This script used to work on windows-latest boys
```
- name: Setup VCPKG
      uses: lukka/run-vcpkg@v10
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgGitCommitId: 5a8a1dfff8e2dffd4c8cc2d1fc0da379ffd18b25

    - name: Ensure Proj packages are available
      run: vcpkg.exe install "tiff[core]:x64-windows-static-md" "proj[core,tiff]:x64-windows-static-md" "tiff[core]:x86-windows-static-md" "proj[core,tiff]:x86-windows-static-md"
```
But now fails with the mentioned error, before building the first real package

**Comment by BillyONeal** [comment] 2022-03-14 22:46
Right, that looks like the commit SHA of the vcpkg repo was updated to one later than that supported by the copy of vcpkg deployed by that task. You should be able to verify by running `vcpkg.exe --version` there.

**Comment by rhuijben** [comment] 2022-03-20 13:13
@BillyONeal to state the obvious.

```
Run vcpkg.exe --version
Vcpkg package management program version 2022-02-24-7efe7f2b04912a7d674f86a406f9f27[11](https://github.com/AmpScm/SharpProj/runs/5617505634?check_suite_focus=true#step:4:11)c0221c6

See LICENSE.txt for license information.
```

**Comment by rhuijben** [comment] 2022-03-21 10:45
It looks like GitHub actions has an older cached 'vcpkg.exe' somewhere on `%PATH%` on windows-latest, so running bootstrap and then running vcpkg.exe runs a different version than just downloaded.

`where vcpkg` doesn't give me a hint on where it comes from, but a hard path towards vcpkg.exe fixes my issues

**Comment by JackBoosY** [comment] 2022-04-02 08:26
Resolved by updating vcpkg-tool. Please git pull vcpkg and run bootstrap script again.

**Closed by JackBoosY** 2022-04-02 08:26 UTC
Labels: category:vcpkg-bug
