### ISSUE TITLE
[gsl] update to 2.7

### ISSUE THREAD

**Issue by MehdiChinoune** [microsoft/vcpkg#18240] opened 2021-06-02 09:23 UTC
Library name: GNU Scientific Library

New version number: 2.7

Other information that may be useful (release notes, etc...)

**Comment by MehdiChinoune** [comment] 2021-07-02 05:09
Any progress?

**Comment by JonLiu1993** [comment] 2021-09-22 02:53
Duplicate of #20256 ,Fix by #20268

**Closed by JonLiu1993** 2021-09-22 02:53 UTC
Labels: category:port-update
