### ISSUE TITLE
[Android] VCPKG incompatible with NDK-26-beta1

### ISSUE THREAD

**Issue by Hackerl** [microsoft/vcpkg#33179] opened 2023-08-15 06:20 UTC
**Describe the bug**
NDK-26 uses LLVM-17, but clang-17 removes the "-avoid-version" option, so the compilation fails.
```cmake=
        if(VCPKG_TARGET_IS_ANDROID)
            set(ENV{LDFLAGS} "-avoid-version $ENV{LDFLAGS}")
            set(ENV{LDFLAGS_FOR_BUILD} "-avoid-version $ENV{LDFLAGS_FOR_BUILD}")
        endif()
```
> https://github.com/microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_configure_make.cmake#L800-L803

![image](https://github.com/microsoft/vcpkg/assets/15811751/2b7acc8f-0ca7-421d-b3e2-9d343e2b3c1d)

**Environment**
- OS: [Linux]
- Compiler: NDK-26(clang-17)

1. export ANDROID_NDK_HOME=android-ndk-r26-beta1 CC=android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang CXX=android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
2. vcpkg install "libiconv:arm64-android"

**Failure logs**
```
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: /usr/bin/bash -c "V=1 ./../src/v1.17-84a471678e.clean/configure --host=aarch64-linux-android \"--enable-extra-encodings\" \"--without-libiconv-prefix\" \"--without-libintl-prefix\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--prefix=/opt/vcpkg/installed/arm64-android/debug\" \"--bindir=\\${prefix}/../tools/libiconv/debug/bin\" \"--sbindir=\\${prefix}/../tools/libiconv/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/libiconv\""
    Working Directory: /opt/vcpkg/buildtrees/libiconv/arm64-android-dbg
    Error code: 77
    See logs for more information:
      /opt/vcpkg/buildtrees/libiconv/config-arm64-android-dbg-config.log
      /opt/vcpkg/buildtrees/libiconv/config-arm64-android-dbg-out.log
      /opt/vcpkg/buildtrees/libiconv/config-arm64-android-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:838 (vcpkg_execute_required_process)
  ports/libiconv/portfile.cmake:29 (vcpkg_configure_make)
  scripts/ports.cmake:147 (include)
```

libiconv:
```
clang-17: error: argument to '-V' is missing (expected 1 value)
clang-17: error: no input files
configure:5044: $? = 1
configure:5033: /home/liupan.patte/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -qversion >&5
clang-17: error: unknown argument '-qversion'; did you mean '--version'?
clang-17: error: no input files
configure:5044: $? = 1
configure:5033: /home/liupan.patte/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -version >&5
clang-17: error: unknown argument '-version'; did you mean '--version'?
clang-17: error: no input files
configure:5044: $? = 1
configure:5064: checking whether the C compiler works
configure:5086: /home/liupan.patte/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -g -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wformat -Werror=format-security -fPIC -fno-limit-debug-info --target=aarch64-none-linux-android21 -DANDROID -D_FORTIFY_SOURCE=2 --sysroot=/home/liupan.patte/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/sysroot -avoid-version --target=aarch64-none-linux-android21 -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments --sysroot=/home/liupan.patte/android-ndk-r26-beta1/toolchains/llvm/prebuilt/linux-x86_64/sysroot conftest.c -latomic -lm >&5
clang: error: unknown argument: '-avoid-version'
configure:5090: $? = 1
configure:5130: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "libiconv"
| #define PACKAGE_TARNAME "libiconv"
| #define PACKAGE_VERSION "1.17"
| #define PACKAGE_STRING "libiconv 1.17"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "libiconv"
| #define VERSION "1.17"
| /* end confdefs.h.  */
|
| int
| main (void)
| {
|
|   ;
|   return 0;
| }
configure:5135: error: in `/opt/vcpkg/buildtrees/libiconv/arm64-android-dbg':
configure:5137: error: C compiler cannot create executables
See `config.log' for more details
```

**Additional context**
I modified vcpkg_configure_make.cmake to remove the "-avoid-version" option, and the installation was successful.

**Comment by dg0yt** [comment] 2023-08-15 07:05
Probably needs #31228. `C5` there has some related context.

**Comment by JonLiu1993** [comment] 2023-11-17 02:28
Duplicate of https://github.com/microsoft/vcpkg/issues/31332

**Closed by JonLiu1993** 2023-11-17 02:28 UTC
Labels: category:community-triplet
