### ISSUE TITLE
[libpq] Build error

### ISSUE THREAD

**Issue by ersagu** [microsoft/vcpkg#30644] opened 2023-04-03 20:50 UTC
Thank  you in advance for any ideas and suggestions.

Package: libpq[core,lz4,openssl,zlib]:x64-windows-v141 -> 15.2#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.16.27048.0
-    vcpkg-tool version: 2023-03-29-664f8bb619b752430368d0f30a8289b761f5caba
    vcpkg-scripts version: 19af97cba8 2023-04-02 (16 hours ago)

**To Reproduce**

`vcpkg install --recurse --clean-after-build boost boost-di cereal cudnn darknet[full] polyclipping g3log grpc gtest ms-gsl nlohmann-json cpr curl[brotli,c-ares,http2,non-http,ssl,tool] boost[mpi] vtk[qt] opencv[cuda,eigen,ffmpeg,ipp,opengl,qt,tbb] pcl[cuda,vtk,qt,opengl]`

**Failure logs**

```
-- Downloading https://ftp.postgresql.org/pub/source/v15.2/postgresql-15.2.tar.bz2 -> postgresql-15.2.tar.bz2...
-- Extracting source D:/BuildAgent/work/66025400e1320a68/vcpkg/downloads/postgresql-15.2.tar.bz2
-- Applying patch patches/windows/install.patch
-- Applying patch patches/windows/win_bison_flex.patch
-- Applying patch patches/windows/openssl-version.patch
-- Applying patch patches/windows/Solution.patch
-- Applying patch patches/windows/MSBuildProject_fix_gendef_perl.patch
-- Applying patch patches/windows/msgfmt.patch
-- Applying patch patches/windows/python_lib.patch
-- Applying patch patches/windows/fix-compile-flag-Zi.patch
-- Applying patch patches/windows/tcl_version.patch
-- Applying patch patches/windows/macro-def.patch
-- Applying patch patches/fix-configure.patch
-- Applying patch patches/windows/minimize_install.patch
-- Using source at D:/BuildAgent/work/66025400e1320a68/vcpkg/buildtrees/libpq/src/tgresql-15-8c0793a390.clean
-- Downloading https://strawberryperl.com/download/5.32.1.1/strawberry-perl-5.32.1.1-32bit.zip -> strawberry-perl-5.32.1.1-32bit.zip...
-- Downloading https://github.com/lexxmark/winflexbison/releases/download/v2.5.25/win_flex_bison-2.5.25.zip -> win_flex_bison-2.5.25.zip...
-- Getting CMake variables for x64-windows-v141
CMake Error at D:/BuildAgent/work/66025400e1320a68/myports-ports/libpq/portfile.cmake:90 (file):
  file STRINGS file
  "D:/BuildAgent/work/66025400e1320a68/vcpkg/installed/x64-windows-v141/lib/pkgconfig/openssl.pc"
  cannot be read.
Call Stack (most recent call first):
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by jimwang118** [comment] 2023-04-04 02:31
Duplicate of https://github.com/microsoft/vcpkg/issues/26416

**Comment by dg0yt** [comment] 2023-04-04 03:41
It is not a duplicate.

**Closed** 2023-04-05 23:42 UTC
Labels: category:port-bug
