### ISSUE TITLE
[New Port Request] argon2

### ISSUE THREAD

**Issue by JeremyGuinn** [microsoft/vcpkg#21547] opened 2021-11-19 16:35 UTC
Library name: argon2

Library description: Provides an API to both low-level and high-level functions for using Argon2.

Source repository URL: https://github.com/P-H-C/phc-winner-argon2

**Comment by JonLiu1993** [comment] 2021-11-22 02:00
Duplicate of #14754

**Closed by JonLiu1993** 2021-11-22 02:00 UTC
Labels: category:new-port, info:good-first-issue
