### ISSUE TITLE
[boost-vcpkg-helpers] Build error

### ISSUE THREAD

**Issue by 9705147437** [microsoft/vcpkg#29473] opened 2023-02-06 15:58 UTC
Package: boost-vcpkg-helpers[core]:x64-windows -> 1.81.0#2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31937.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 0ba60bfef 2023-02-03 (3 days ago)

**To Reproduce**

`vcpkg install osgearth:x64-windows`

**Failure logs**

```
-- Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt -> boost_LICENSE_1_0.txt...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Failed to download from mirror set
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt: WinHttpSendRequest failed with exit code 12002
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt: WinHttpSendRequest failed with exit code 12002
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt: WinHttpSendRequest failed with exit code 12002
error: https://raw.githubusercontent.com/boostorg/boost/boost-1.81.0/LICENSE_1_0.txt: WinHttpSendRequest failed with exit code 12002
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956): 
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 6 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 25529 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 2.94 min (175695478 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/boost-vcpkg-helpers/portfile.cmake:4 (vcpkg_download_distfile)
  scripts/ports.cmake:147 (include)



```

**Comment by jimwang118** [comment] 2023-02-07 08:11
Duplicate of https://github.com/microsoft/vcpkg/issues/29395.

**Closed by jimwang118** 2023-02-07 08:11 UTC
Labels: category:question
