### ISSUE TITLE
libjxl update to v0.10.2

### ISSUE THREAD

**Issue by JamieStM** [microsoft/vcpkg#37288] opened 2024-03-08 21:04 UTC
### Library name

libjxl

### New version number

0.10.2

### Other information that may be useful (release notes, etc...)

Current version is 0.8.2, releases 0.9.0-0.10.2 have significant API changes and bug fixes, including 2x-20x speed and memory improvements when compressing lossless images (per blog post here: https://cloudinary.com/blog/jpeg-xl-and-the-pareto-front).

**Comment by LilyWangLL** [comment] 2024-03-11 01:57
Closed as duplicate of #37066.

**Closed by LilyWangLL** 2024-03-11 01:57 UTC
Labels: category:port-update
