### ISSUE TITLE
I have same build problem as Issue 25419

### ISSUE THREAD

**Issue by analitic1983** [microsoft/vcpkg#27281] opened 2022-10-17 18:03 UTC
I have same build problem

https://github.com/microsoft/vcpkg/issues/25419

It`s have completed status, but have not published solution? How can i fix it?

**Comment by Kingtous** [comment] 2022-11-21 15:07
same issue here.

**Comment by slimsag** [comment] 2022-12-20 06:58
Duplicate of #27410

**Closed** 2023-02-14 09:47 UTC
Labels: category:community-triplet
