### ISSUE TITLE
vcpkg crashes when upgrading non existing port

### ISSUE THREAD

**Issue by autoantwort** [microsoft/vcpkg#31440] opened 2023-05-15 10:53 UTC
**Describe the bug**
If you try to upgrade a non existing port vcpkg crashes

**To Reproduce**
1. ./vcpkg upgrade test
```
➜  vcpkg git:(master) ./vcpkg upgrade test
error: The following packages are not installed:
    test:arm64-osx
error: The following packages do not have a valid CONTROL or vcpkg.json:
    test:arm64-osx
internal error: /Users/runner/work/1/s/src/vcpkg/commands.upgrade.cpp(180): vcpkg has crashed; no additional details are available.
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.
```

**Expected behavior**
Exit with an error message and non zero exit code.

**Comment by LilyWangLL** [comment] 2023-05-16 10:50
Closed as duplicate of https://github.com/microsoft/vcpkg/issues/21117.

**Closed by LilyWangLL** 2023-05-16 10:50 UTC
Labels: category:vcpkg-bug
