### ISSUE TITLE
[openssl] Build error on x64-windows

### ISSUE THREAD

**Issue by kkkkkcode** [microsoft/vcpkg#37185] opened 2024-03-06 13:37 UTC
My vcpkg failed to install openssl many times,here's the message from terminal:
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "E:/Microsoft/VS IDE/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: E:/Microsoft/vcpkg/buildtrees/openssl/x64-windows-dbg
    See logs for more information:
      E:\Microsoft\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log
      E:\Microsoft\vcpkg\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:69 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:78 (include)
  scripts/ports.cmake:170 (include)

error: building openssl:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openssl:x64-windows: 2.3 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error+on+x64-windows&body=Copy+issue+body+from+E%3A%2FMicrosoft%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by kkkkkcode** [comment] 2024-03-06 13:40
Here is the install-x64-windows-dbg-nmake-err.log:
cl: 鍛戒护琛?warning D9025 :姝ｅ湪閲嶅啓鈥?Zi鈥?鐢ㄢ€?Z7鈥?
NMAKE : fatal error U1077: “"E:\Microsoft\VS IDE\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"E:\\Microsoft\\vcpkg\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"E:\\Microsoft\\vcpkg\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"E:\\Microsoft\\vcpkg\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c"”: 返回代码“0x2”
Stop.
NMAKE : fatal error U1077: “"E:\Microsoft\VS IDE\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs”: 返回代码“0x2”
Stop.

**Comment by kkkkkcode** [comment] 2024-03-06 13:41
Here is the install-x64-windows-dbg-nmake-out.log:
	"E:\Microsoft\VS IDE\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 depend
	"E:\Microsoft\VS IDE\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\nmake.exe" /LU                 _build_libs
	"E:\Microsoft\VS IDE\VC\Tools\MSVC\14.38.33130\bin\Hostx64\x64\cl.exe"  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"crypto" -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"E:\\Microsoft\\vcpkg\\packages\\openssl_x64-windows\\debug\"" -D"ENGINESDIR=\"E:\\Microsoft\\vcpkg\\packages\\openssl_x64-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"E:\\Microsoft\\vcpkg\\packages\\openssl_x64-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DBSAES_ASM -DCMLL_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DKECCAK1600_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM -DX25519_ASM -c /Focrypto\libcrypto-shlib-cversion.obj "crypto\cversion.c"
cversion.c
crypto\cversion.c(60): warning C4129: “V”: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “T”: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “M”: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “H”: 不可识别的字符转义序列
crypto\cversion.c(60): warning C4129: “c”: 不可识别的字符转义序列
crypto\cversion.c(60): error C2143: 语法错误: 缺少“;”(在“常数”的前面)
crypto\cversion.c(60): error C2143: 语法错误: 缺少“;”(在“字符串”的前面)

**Comment by MonicaLiu0311** [comment] 2024-03-08 02:32
Duplicate of #37134.

**Closed by MonicaLiu0311** 2024-03-08 02:32 UTC
Labels: requires:repro
