### ISSUE TITLE
[python3] Build error on x64-linux

### ISSUE THREAD

**Issue by 244916896** [microsoft/vcpkg#37547] opened 2024-03-19 09:25 UTC
Copy issue body from /data/zhanghl/code/vcpkg-laster/installed/vcpkg/issue_body.md

<img width="954" alt="Snipaste_2024-03-19_17-24-06" src="https://github.com/microsoft/vcpkg/assets/7687328/06c48a6d-4ec8-4998-9db0-75b87cbb6c18">

**Comment by 244916896** [comment] 2024-03-19 09:28
<img width="958" alt="微信图片_20240319172804" src="https://github.com/microsoft/vcpkg/assets/7687328/29ce6459-21b0-4833-a30c-95f821289e6b">

**Comment by LilyWangLL** [comment] 2024-03-19 09:34
> undefined macro: AC_MSG_ERROR

Duplicate of https://github.com/microsoft/vcpkg/issues/36184, please refer to https://stackoverflow.com/questions/8811381/possibly-undefined-macro-ac-msg-error/49103418#49103418.

**Comment by LilyWangLL** [comment] 2024-04-02 07:38
We hope your question was answered to your satisfaction; if it wasn't, you can reopen with more info.

**Closed by LilyWangLL** 2024-04-02 07:38 UTC
Labels: category:question
