### ISSUE TITLE
[simdjson] unresolved external symbol on Visual Studio 2019 32/64 bit

### ISSUE THREAD

**Issue by ludekvodicka** [microsoft/vcpkg#16062] opened 2021-02-05 20:01 UTC
**Environment**
- OS: Windows
- Compiler: Visual Studio 2019, 32-bit / 64-bit (doesn't work on both platforms)

**To Reproduce**
vcpkg.exe install simdjson

Simple console app:

```
#include <iostream>
#include "simdjson.h"
int main(void)
{
	simdjson::dom::parser parser;
	simdjson::dom::element tweets = parser.load("twitter.json");
	std::cout << tweets["search_metadata"]["count"] << " results." << std::endl;
}
```

**Failure logs** 
```
1>simdjson.test.obj : error LNK2001: unresolved external symbol "class simdjson::internal::atomic_ptr<class simdjson::implementation const > simdjson::active_implementation" (?active_implementation@simdjson@@3V?$atomic_ptr@$$CBVimplementation@simdjson@@@internal@1@A)
1>simdjson.test.obj : error LNK2001: unresolved external symbol "struct simdjson::internal::error_code_info const * const simdjson::internal::error_codes" (?error_codes@internal@simdjson@@3QBUerror_code_info@12@B)
```

**Comment by ludekvodicka** [comment] 2021-02-05 21:19
It seems it's necessary to add `simdjson.cpp` file from the `singleheader` folder to the VS project. But this file isn't copied anywhere to installed folder and is available only in the buildtrees\simdjson\src\.

I thing `simdjson.cpp` should be included in the `simdjson.lib `

**Comment by sfhacker** [comment] 2021-02-05 22:39
Have you contacted us before?
It is good practice, after building any project, to run all the tests.

![image](https://user-images.githubusercontent.com/25817529/107096473-f580b700-685e-11eb-8716-317b89795397.png)

Just built the code snippet provided by you on Windows 10 x64. No issues at all.

![image](https://user-images.githubusercontent.com/25817529/107096509-0c270e00-685f-11eb-97b3-ab7520470a5c.png)

**Comment by ludekvodicka** [comment] 2021-02-06 07:05
@sfhacker sorry, why this negative attitude? I thought this is the place for reporting issue. I already reported several issues and also provided several fixes for issues, so I believe your rude answer isn't ok.

How can I run test projects when compiling port via vcpkg? As far as I know, there are CPKG recommendations that ports doesn't compile any tests. And if I check installed folder, there are no tests at all.

Also, can you please answer my original observation, if it is necessary to include `simdjson.cpp` in the project, instead of downvoting my post?

This is my settings of the project which causing these unresolved externals. As you can see, simdljson.lib is correctly attached to the project as .lib but doesn't work without `simdjson.cpp`

![devenv_2021-02-06_08-01-30](https://user-images.githubusercontent.com/3900551/107111579-881a5980-6851-11eb-9b11-ac5954c43c4d.png)

![devenv_2021-02-06_08-01-45](https://user-images.githubusercontent.com/3900551/107111583-910b2b00-6851-11eb-8190-d6ac43753e74.png)

![devenv_2021-02-06_08-01-59](https://user-images.githubusercontent.com/3900551/107111589-99636600-6851-11eb-986d-cb48bff38c61.png)

Complete project is here: 
[ConsoleApplication1.zip](https://github.com/microsoft/vcpkg/files/5936416/ConsoleApplication1.zip)


If you can provide me details how to compile and run tests via vcpkg system, I will be glad to help with testing.

**Comment by JonLiu1993** [comment] 2021-02-07 02:42
@ludekvodicka ,Don't pay attention to him. It is not the first time he has done this. He can't provide you with useful suggestions. We thank you for your continued support of vcpkg and thank you for your contribution! Really great!

**Comment by NancyLi1013** [comment] 2021-02-07 07:39
Hi @ludekvodicka 

Thanks for posting this issue.

It seems that simdjson is always built as a header-only library now. So `simdjson.cpp` is required to compiled in `simdjson.lib`.

I noticed that upstream has included in latest release on static build.

https://github.com/simdjson/simdjson/blob/v0.8.1/src/CMakeLists.txt#L53

So we need to update `simdjson `to new version 0.8.1.

**Comment by ludekvodicka** [comment] 2021-02-07 07:56
Hello @NancyLi1013 , thanks for your kind reply and for confirming my observation.

**Comment by NancyLi1013** [comment] 2021-02-08 02:24
After testing, I found the root cause is that we should define `SIMDJSON_USING_LIBRARY` in a console  application.

Please see the code here
https://github.com/simdjson/simdjson/blob/master/include/simdjson/common_defs.h#L156

`SIMDJSON_USING_LIBRARY` has been defined in CMake https://github.com/simdjson/simdjson/blob/master/src/CMakeLists.txt#L58

So there is no problem when building a CMake project.

I will update to new version and fix this problem.

**Comment by NancyLi1013** [comment] 2021-02-08 06:19
@ludekvodicka 

I submitted a PR #16015 to fix this issue. Could you please help confirm if this can work fine for you?

**Comment by ludekvodicka** [comment] 2021-02-08 20:52
Hello @NancyLi1013 , it's working perfectly. Thanks for the quick fix!

**Comment by NancyLi1013** [comment] 2021-02-09 02:24
Thanks for your feedback. It is good news.

Please keep this issue open until the PR has been merged.

**Closed** 2021-05-26 21:54 UTC
Labels: category:port-bug

**Comment by STaveras** [comment] 2022-12-19 07:34
This is still an issue even today in version 3.0.1

I'm getting: 
```
unresolved external symbol "struct simdjson::internal::error_code_info const * const simdjson::internal::error_codes"	
the default constructor of "simdjson::dom::stage1_worker" cannot be referenced -- it is a deleted function
the default constructor of "simdjson::fallback::ondemand::stage1_worker" cannot be referenced -- it is a deleted function
```
Same setup as above, linking to simdjson.lib

**Comment by lzq434718971** [comment] 2024-03-14 05:21
Is it normal that I encounter the similar problem on vs2022? What do I miss?

The environment and reproduce steps are the same except that I'm using vs2022.

My Simple Code:
```
#include "simdjson.h"

using namespace simdjson;

int main(void) {
    dom::parser parser;
    dom::element doc = parser.parse("[1,2,3]"_padded);
}
```
Failure Logs:
`error LNK2001: 无法解析的外部符号 "struct simdjson::internal::error_code_info const * const simdjson::internal::error_codes" (?error_codes@internal@simdjson@@3QBUerror_code_info@12@B)`
and "无法解析的外部符号" = unresolved external symbol

**Comment by MirionQs** [comment] 2024-12-31 05:24
It happended again on my computer with VS 2022 17.13.0 preview 2.1 and simdjson 3.10.1.

**Comment by dg0yt** [comment] 2024-12-31 05:52
If you have a problem in 2024, it may be pointless to comment on a different issue closed in 2021. Open a new, complete issue.

**Comment by qqq694637644** [comment] 2025-01-05 11:56
In version
[3.11.3](https://github.com/simdjson/simdjson/releases/tag/v3.11.3)
The issue still exists; the headonly compilation requires including the simdjson.cpp file to compile properly.

**Comment by GustavoEGPerez** [comment] 2025-02-14 15:55
"I had the same problem, and @NancyLi1013 helped to solve it as well. 
Using SIMDJSON_USING_LIBRARY as a macro solves it like a charm! 

Thanks.
