### ISSUE TITLE
Vcpkg parses manifest files of installed ports twice during install

### ISSUE THREAD

**Issue by Thomas1664** [microsoft/vcpkg#34095] opened 2023-09-28 13:02 UTC
**Describe the bug**

**Environment**
- OS: Linux

**To Reproduce**
1. ./vcpkg install zlib
2. strace -o strace.txt ./vcpkg install nlohmann-json
3. Search in the output file for `vcpkg/ports/zlib/vcpkg.json`
4. Observe that you get 2 hits

Sample strace output using latest version of the vcpkg binary:

```
lstat("/workspaces/vcpkg/ports/vcpkg-cmake/CONTROL", 0x7ffc8ca81ff0) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/workspaces/vcpkg/ports/zlib/vcpkg.json", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0666, st_size=228, ...}) = 0
read(3, "{\n  \"name\": \"zlib\",\n  \"version\":"..., 32768) = 228
read(3, "", 28672)                      = 0
close(3)                                = 0
lstat("/workspaces/vcpkg/ports/zlib/CONTROL", 0x7ffc8ca81f00) = -1 ENOENT (No such file or directory)
lstat("/workspaces/vcpkg/ports/zlib", {st_mode=S_IFDIR|0777, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/workspaces/vcpkg/ports/zlib/vcpkg.json", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0666, st_size=228, ...}) = 0
read(3, "{\n  \"name\": \"zlib\",\n  \"version\":"..., 32768) = 228
read(3, "", 28672)                      = 0
close(3)                                = 0
```

If you place a breakpoint at [`try_load_port()`](https://github.com/microsoft/vcpkg-tool/blob/785af0d180135ea93077c364445e879eb75dd1b4/src/vcpkg/paragraphs.cpp#L416), you can observe that this function is called twice per port.

Stacktrace for first call:
```
vcpkg::Paragraphs::try_load_port(const vcpkg::ReadOnlyFilesystem & fs, const vcpkg::Path & port_directory) (\workspaces\vcpkg-tool\src\vcpkg\paragraphs.cpp:418)
(anonymous namespace)::BuiltinFilesRegistry::get_scf(vcpkg::Path const&) const::{lambda()#1}::operator()() const(const class {...} * this) (\workspaces\vcpkg-tool\src\vcpkg\registries.cpp:494)
vcpkg::Cache<vcpkg::Path, vcpkg::ExpectedT<vcpkg::SourceControlFile, vcpkg::LocalizedString>, std::less<void> >::get_lazy<vcpkg::Path, (anonymous namespace)::BuiltinFilesRegistry::get_scf(vcpkg::Path const&) const::{lambda()#1}, 0>(vcpkg::Path const&, (anonymous namespace)::BuiltinFilesRegistry::get_scf(vcpkg::Path const&) const::{lambda()#1}&&) const(const vcpkg::Cache<vcpkg::Path, vcpkg::ExpectedT<vcpkg::SourceControlFile, vcpkg::LocalizedString>, std::less<void> > * this, const vcpkg::Path & k, class {...} && f) (\workspaces\vcpkg-tool\include\vcpkg\base\cache.h:46)
(anonymous namespace)::BuiltinFilesRegistry::get_scf(const (anonymous namespace)::BuiltinFilesRegistry * this, const vcpkg::Path & path) (\workspaces\vcpkg-tool\src\vcpkg\registries.cpp:493)
(anonymous namespace)::BuiltinFilesRegistry::get_baseline_version(const (anonymous namespace)::BuiltinFilesRegistry * this, vcpkg::StringView port_name) (\workspaces\vcpkg-tool\src\vcpkg\registries.cpp:743)
vcpkg::RegistrySet::baseline_for_port(const vcpkg::RegistrySet * this, vcpkg::StringView port_name) (\workspaces\vcpkg-tool\src\vcpkg\registries.cpp:1576)
vcpkg::(anonymous namespace)::BaselineProviderImpl::get_baseline_version(const vcpkg::(anonymous namespace)::BaselineProviderImpl * this, vcpkg::StringView port_name) (\workspaces\vcpkg-tool\src\vcpkg\portfileprovider.cpp:118)
vcpkg::PathsPortFileProvider::get_control_file(const vcpkg::PathsPortFileProvider * this, const std::string & spec) (\workspaces\vcpkg-tool\src\vcpkg\portfileprovider.cpp:82)
vcpkg::(anonymous namespace)::ClusterGraph::insert(vcpkg::(anonymous namespace)::ClusterGraph * this, const vcpkg::InstalledPackageView & ipv) (\workspaces\vcpkg-tool\src\vcpkg\dependencies.cpp:407)
vcpkg::create_feature_install_graph(const vcpkg::PortFileProvider & port_provider, const vcpkg::StatusParagraphs & status_db, vcpkg::Triplet host_triplet) (\workspaces\vcpkg-tool\src\vcpkg\dependencies.cpp:1145)
vcpkg::(anonymous namespace)::PackageGraph::PackageGraph(vcpkg::(anonymous namespace)::PackageGraph * this, const vcpkg::PortFileProvider & port_provider, const vcpkg::CMakeVars::CMakeVarProvider & var_provider, const vcpkg::StatusParagraphs & status_db, vcpkg::Triplet host_triplet, const vcpkg::Path & packages_dir) (\workspaces\vcpkg-tool\src\vcpkg\dependencies.cpp:1177)
vcpkg::create_feature_install_plan(const vcpkg::PortFileProvider & port_provider, const vcpkg::CMakeVars::CMakeVarProvider & var_provider, vcpkg::View<vcpkg::FullPackageSpec> specs, const vcpkg::StatusParagraphs & status_db, const vcpkg::CreateInstallPlanOptions & options) (\workspaces\vcpkg-tool\src\vcpkg\dependencies.cpp:762)
vcpkg::command_install_and_exit(const vcpkg::VcpkgCmdArguments & args, const vcpkg::VcpkgPaths & paths, vcpkg::Triplet default_triplet, vcpkg::Triplet host_triplet) (\workspaces\vcpkg-tool\src\vcpkg\commands.install.cpp:1257)
(anonymous namespace)::inner(const vcpkg::Filesystem & fs, const vcpkg::VcpkgCmdArguments & args, const vcpkg::BundleSettings & bundle) (\workspaces\vcpkg-tool\src\vcpkg.cpp:144)
main(const int argc, const char * const * const argv) (\workspaces\vcpkg-tool\src\vcpkg.cpp:400)
```

Stacktrace for second call:
```
vcpkg::Paragraphs::try_load_port(const vcpkg::ReadOnlyFilesystem & fs, const vcpkg::Path & port_directory) (\workspaces\vcpkg-tool\src\vcpkg\paragraphs.cpp:423)
vcpkg::(anonymous namespace)::VersionedPortfileProviderImpl::load_control_file(const vcpkg::(anonymous namespace)::VersionedPortfileProviderImpl * this, const vcpkg::VersionSpec & version_spec) (\workspaces\vcpkg-tool\src\vcpkg\portfileprovider.cpp:185)
vcpkg::(anonymous namespace)::VersionedPortfileProviderImpl::get_control_file(const vcpkg::(anonymous namespace)::VersionedPortfileProviderImpl * this, const vcpkg::VersionSpec & version_spec) (\workspaces\vcpkg-tool\src\vcpkg\portfileprovider.cpp:232)
vcpkg::PathsPortFileProvider::get_control_file(const vcpkg::PathsPortFileProvider * this, const std::string & spec) (\workspaces\vcpkg-tool\src\vcpkg\portfileprovider.cpp:85)
vcpkg::(anonymous namespace)::ClusterGraph::insert(vcpkg::(anonymous namespace)::ClusterGraph * this, const vcpkg::InstalledPackageView & ipv) (\workspaces\vcpkg-tool\src\vcpkg\dependencies.cpp:407)
vcpkg::create_feature_install_graph(const vcpkg::PortFileProvider & port_provider, const vcpkg::StatusParagraphs & status_db, vcpkg::Triplet host_triplet) (\workspaces\vcpkg-tool\src\vcpkg\dependencies.cpp:1145)
vcpkg::(anonymous namespace)::PackageGraph::PackageGraph(vcpkg::(anonymous namespace)::PackageGraph * this, const vcpkg::PortFileProvider & port_provider, const vcpkg::CMakeVars::CMakeVarProvider & var_provider, const vcpkg::StatusParagraphs & status_db, vcpkg::Triplet host_triplet, const vcpkg::Path & packages_dir) (\workspaces\vcpkg-tool\src\vcpkg\dependencies.cpp:1177)
vcpkg::create_feature_install_plan(const vcpkg::PortFileProvider & port_provider, const vcpkg::CMakeVars::CMakeVarProvider & var_provider, vcpkg::View<vcpkg::FullPackageSpec> specs, const vcpkg::StatusParagraphs & status_db, const vcpkg::CreateInstallPlanOptions & options) (\workspaces\vcpkg-tool\src\vcpkg\dependencies.cpp:762)
vcpkg::command_install_and_exit(const vcpkg::VcpkgCmdArguments & args, const vcpkg::VcpkgPaths & paths, vcpkg::Triplet default_triplet, vcpkg::Triplet host_triplet) (\workspaces\vcpkg-tool\src\vcpkg\commands.install.cpp:1257)
(anonymous namespace)::inner(const vcpkg::Filesystem & fs, const vcpkg::VcpkgCmdArguments & args, const vcpkg::BundleSettings & bundle) (\workspaces\vcpkg-tool\src\vcpkg.cpp:144)
main(const int argc, const char * const * const argv) (\workspaces\vcpkg-tool\src\vcpkg.cpp:400)
```

The results of `try_load_port` are independently cached in the Registry and in `versionedPortfileProviderImpl`.

I think this bug is just a symptom of a larger problem: The codebase is very complex and people don't know that certain functionality is already implemented elsewhere. This is especially true for everything related to getting information about a port.

**Comment by BillyONeal** [comment] 2023-10-02 19:19
I think I might have come close to addressing this in trying to make search better but I'm not positive. Assigning to me for now.

The root cause here is that the 'just use whatever is in this directory' and 'follow what versions are selected' are different paths that aren't entirely harmonized.

>The codebase is very complex and people don't know that certain functionality is already implemented elsewhere.

This is caused by different parts being implemented by different people and no one person being in the loop for end to end reviews over the product's lifetime. Unfortunately I don't see that changing much or soon.

**Comment by Thomas1664** [comment] 2024-04-08 07:32
No stale

**Closed** 2024-09-23 19:29 UTC
Labels: category:vcpkg-bug, requires:tool-release
