### ISSUE TITLE
Error: Building package boost-exception:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by okmechak** [microsoft/vcpkg#6330] opened 2019-05-06 20:00 UTC
Package: boost-exception:x64-windows
Vcpkg version: 2018.11.23-nohash
Win 10
Visual Studio 2019

```
notice: found boost-build.jam at C:/Users/ofcra/Source/vcpkg/installed/x64-windows/tools/boost-build/boost-build.jam
notice: loading Boost.Build from C:/Users/ofcra/Source/vcpkg/installed/x64-windows/tools/boost-build/src/kernel
notice: Site configuration files will be ignored due to the
notice: --ignore-site-config command-line option.
notice: Loading explicitly specified user configuration file:
    C:\Users\ofcra\Source\vcpkg\buildtrees\boost-exception\x64-windows-rel\user-config.jam
notice: Searching 'C:\Users\ofcra\Source\vcpkg\buildtrees\boost-exception\x64-windows-rel' for user-config configuration file 'user-config.jam'.
notice: Loading user-config configuration file 'user-config.jam' from 'C:/Users/ofcra/Source/vcpkg/buildtrees/boost-exception/x64-windows-rel'.

warning: Did not find command for MSVC toolset. If you have Visual Studio 2017 installed you will need to specify the full path to the command, set VS150COMNTOOLS for your installation, or build from the 'Visual Studio Command Prompt for VS 2017'.

notice: will use 'cl.exe' for msvc, condition <toolset>msvc
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>32', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>32', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>32', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>32', setup: 'x86'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>64', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>/<address-model>64', setup: 'amd64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>64', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>x86/<address-model>64', setup: 'amd64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>', setup: 'x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>64', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>ia64/<address-model>64', setup: 'x86_ia64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'x86_arm'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>32', setup: 'x86_arm'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>', setup: 'x86_arm64'
notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>64', setup: 'C:/Users/ofcra/Source/vcpkg/installed/x64-windows/share/boost-build/nothing.bat' notice: [msvc-cfg] condition: '<toolset>msvc/<architecture>arm/<address-model>64', setup: 'x86_arm64'
notice: [cmdline-cfg] toolset msvc-14.1 not previously configured; attempting to auto-configure now
error: msvc initialization: parameter 'version' inconsistent
error: no value was specified in earlier initialization
error: an explicit value is specified now
```

PS: I saw there is already many similar issues.. not sure if it is duplicate or not

Best,
Oleg

**Comment by vicroms** [comment] 2019-05-06 21:48
Duplicate of #6289

**Comment by s-martin** [comment] 2019-05-08 07:09
Should be resolved, when #6141 is merged.

**Comment by s-martin** [comment] 2019-05-08 07:13
As a temporary workaround you could locally update only boost-build to 1.70. This worked for me.
Please see the comment from maximilian578 in #5976

**Comment by zhaofeng-shu33** [comment] 2019-05-08 09:52
Visual Studio 2019 can install msvc toolset v141. I suggest you make a custom triplet(copied from x64-windows.cmake) called `x64-windows-v141.cmake`, and specify two additional entries.
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(VCPKG_PLATFORM_TOOLSET v141)
set(ENV{VS150COMNTOOLS} "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\Common7\\Tools\\")
```
Modify the env variable of VS150COMNTOOLS to your actual installation.
This is because boost 1.69 only supports msvc toolset <=141.

It works to build boost-atomic:x64-windows-v141.

**Comment by jepessen** [comment] 2019-05-15 20:24
This worked for me. I've created a new triplet with these data. I don't understand the meaning of `VS150COMNTOOLS` environment variable, it's the second time that I see it. The first was when I saw the build log of vcpkg.. It's something related to boost build? and why the `150` in the name?

**Comment by wangli28** [comment] 2019-05-17 06:49
Hi @okmechak, PR #6141 has been merged. I installed it successfully with VS2019 and VCPKG latest source. You can update vcpkg and rebuild.

> Starting package 44/72: boost-exception:x64-windows
Building package boost-exception[core]:x64-windows...
-- Downloading https://github.com/boostorg/exception/archive/boost-1.70.0.tar.gz...
-- Extracting source F:/Lily/issue6475/vcpkg/downloads/boostorg-exception-boost-1.70.0.tar.gz
-- Using source at F:/Lily/issue6475/vcpkg/buildtrees/boost-exception/src/ost-1.70.0-586c64cc78
-- Building x64-windows-rel
-- Building x64-windows-rel done
-- Building x64-windows-dbg
-- Building x64-windows-dbg done
-- Packaging x64-windows-rel
-- Packaging x64-windows-rel done
-- Packaging x64-windows-dbg
-- Packaging x64-windows-dbg done
-- Packaging headers
-- Packaging headers done
-- Using cached F:/Lily/issue6475/vcpkg/downloads/boost_LICENSE_1_0.txt
-- Installing: F:/Lily/issue6475/vcpkg/packages/boost-exception_x64-windows/share/boost-exception/copyright
-- Performing post-build validation
-- Performing post-build validation done
Building package boost-exception[core]:x64-windows... done
Installing package boost-exception[core]:x64-windows...
Installing package boost-exception[core]:x64-windows... done
Elapsed time for package boost-exception:x64-windows: 14.44 s

**Closed** 2019-05-17 08:07 UTC

**Comment by zhaofeng-shu33** [comment] 2019-05-17 09:18
@jepessen because boost jam (<=1.69) will search VS150COMNTOOLS environment variable.
