### ISSUE TITLE
[vcpkg] Build error with Ninja 1.10.0

### ISSUE THREAD

**Issue by ghost** [microsoft/vcpkg#10887] opened 2020-04-17 17:29 UTC
**Host Environment**
OS: [Microsoft Windows x64 Pro [Version 10.0.18363.778]]
Compiler:
Visual Studio 2017 Version: 15.9.22 VS Tools Version: 14.16.27023
Visual Studio 2019 Version: 16.5.4 VS Tools Version: 14.25.28610
WinSDK 10.0.18362.0
cmake version 3.17.1
ninja version 1.10.0
Vcpkg package management program version 2020.02.04-nohash-external

**To Reproduce**
`vcpkg install libiconv[*] liblzma[*] libxml2[*] tmx[*] zlib[*] --keep-going`

**Failure logs** 
-Cut and past the appropriate build messages from the console output.
```
Starting package 5/5: tmx:x64-windows
Building package tmx[core]:x64-windows...
-- Using cached D:/Git/vcpkg.downloads/baylej-tmx-tmx_1.0.0.tar.gz
-- Extracting source D:/Git/vcpkg.downloads/baylej-tmx-tmx_1.0.0.tar.gz
-- Using source at D:/Git/vs2019.test/buildtrees/tmx/src/tmx_1.0.0-d9b51128f6
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: D:/Git/vs2019.test/buildtrees/tmx/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Git\vs2019.test\buildtrees\tmx\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:297 (vcpkg_execute_required_process)
  ports/tmx/portfile.cmake:11 (vcpkg_configure_cmake)
  scripts/ports.cmake:90 (include)

Error: Building package tmx:x64-windows failed with: BUILD_FAILED
Elapsed time for package tmx:x64-windows: 4.441 s

-Please attach any additional failure logs mentioned in the console output.
```
[vs2019.test.v142.config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4494347/vs2019.test.v142.config-x64-windows-out.log)
[vs2017.test.v141.config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/4494348/vs2017.test.v141.config-x64-windows-out.log)

**Additional context**
1. The config-x64-windows-out.log for both VS2017 and VS2019 show the following error:
`CMake Error:`
  `Running`
   `'C:/Program Files (x86)/Microsoft Visual Studio/<vs-version>/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe' '-C' 'D:/Git/<vs-version>.test/buildtrees/tmx/x64-windows-rel' '-t' 'cleandead'`
  `failed with:`
   `ninja: error: build.ninja:225: multiple rules generate tmx.lib [-w dupbuild=err]`

2. If I comment out the `PREFER_NINJA` on line 13 of the `ports\tmx\portfile.cmake` letting the build use `msbuild` instead of `ninja` the port builds and installs successfully.

**Comment by NancyLi1013** [comment] 2020-04-21 06:06
Hi @timautry 
Thanks for posting this issue.
It might be something wrong with your test environment.
I cannot reproduce this issue on my local with Visual Studio 2019 and Visual Studio 2017.
Did you set Ninja path manually?

**Comment by NancyLi1013** [comment] 2020-04-21 06:53
It seems that `C:/Program Files (x86)/Microsoft Visual Studio/<vs-version>/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe` doesn't exist on your local machine or you don't set `Ninja` path.
Could you please check this?

**Comment by timautry** [comment] 2020-04-21 16:54
@NancyLi1013 cc: @LilyWangL  
- ninja 1.8.2 is installed at:
   - `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe`
   - `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe`
- ninja 1.10.0 is install at:
  - `<vcpkg-root>\downloads\tools\ninja-win`
  - [Ninja] Update to 1.10 #10796

- this issue is likely the upgrade to ninja v1.10.0 in `<vcpkg-root>/scripts/vcpkgTools.xml`
- there was a change made to ninja between v1.8.2 and v.1.9.0
  - when multiple rules are found for building the same binary, lib or file:
    - prior to ninja v1.9.0 it was a **warning, the build continues**
    - since ninja v1.9.0 it is an **error, the build stops**
 - there are some workarounds:
   - the one I used, to commend out #PREFER_NINJA in the portfile.cmake and causing the port build to use msbuild
   - or pass [-w dupbuild=warn] to the ninja build
   - or rework the CMakeLists.txt to eliminate having multiple definitions for the same binary, lib, etc...
- So far, I have identified the following ports with this issue:
   - darknet
   - portaudio
   - replxx
   - sundials
   - tmx

A few References:
- https://devzone.nordicsemi.com/f/nordic-q-a/46041/build-error-after-upgrading-to-ninja-release-1-9-0
- https://gitlab.kitware.com/cmake/cmake/issues/18900
- https://bugs.launchpad.net/kicad/+bug/1829082

**Comment by NancyLi1013** [comment] 2020-04-22 07:19
@timautry 
Thanks for your deep investigation about this.

I try to build this with ninja that is installed in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe`.
There is no any error.

For ninja 1.10.0, I noticed that it has been downloaded in `vcpkg_root_path\downloads\tools\ninja\ninja-1.10.0`.
But on my local, it seems that it will always point to the path that ninja 1.10.0 is installed.

So I 'm not sure the situation if building with ninja 1.10.0.

I wonder why the error posted the path ninja 1.8.2 even though you have used ninja 1.10.0.

**Comment by JackBoosY** [comment] 2020-04-22 09:08
I don't know why this warning / error occurred. But I think we can avoid this problem by passing `-w dupbuild=warn` to ninja.

**Comment by timautry** [comment] 2020-04-22 16:48
> I don't know why this warning / error occurred. But I think we can avoid this problem by passing `-w dupbuild=warn` to ninja.

I think this would be best also.

Thank you very much @NancyLi1013 @JackBoosY, you all do good work!

**Comment by timautry** [comment] 2020-07-14 00:01
I close, I no longer use product.

**Comment by NancyLi1013** [comment] 2020-11-26 08:47
This is not a vcpkg bug. Needs to fix the problem on ports sides.

Please see https://github.com/microsoft/vcpkg/pull/10964#issuecomment-656362040

Currently, all these ports have been fixed in current master branch. Please update vcpkg to the latest version to rebuild.

```
darknet
portaudio
replxx
sundials
tmx
```
I have tested these ports on x86-windows and there was no any error.

**Closed by NancyLi1013** 2020-11-26 08:47 UTC
Labels: category:port-bug
