### ISSUE TITLE
[colmap] Build error

### ISSUE THREAD

**Issue by YeZhuxi** [microsoft/vcpkg#30282] opened 2023-03-19 09:05 UTC
Package: colmap[core,cuda]:x64-windows -> 2023-03-12

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31937.0
- vcpkg-tool version: 2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
  vcpkg-scripts version: b51f391cd 2023-03-16 (2 days ago)

**To Reproduce**

`vcpkg install colmap[cuda]:x64-windows`

**Failure logs**

```
-- Using cached colmap-colmap-30da037ce19bdceb6d239c45342fadb221bdabb2.tar.gz.
-- Cleaning sources at C:/src/vcpkg/buildtrees/colmap/src/b221bdabb2-6df8038bd6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/src/vcpkg/downloads/colmap-colmap-30da037ce19bdceb6d239c45342fadb221bdabb2.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at C:/src/vcpkg/buildtrees/colmap/src/b221bdabb2-6df8038bd6.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/src/vcpkg/downloads/tools/cmake-3.25.1-windows/cmake-3.25.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/src/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\src\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:60 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)



```

<details><summary>C:\src\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log</summary>

```
[1/191] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DRELEASE -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -IC:\src\vcpkg\installed\x64-windows\include -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\installed\x64-windows\include\qt5 -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -IC:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W0 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folib\PoissonRecon\CMakeFiles\poisson_recon.dir\Factor.cpp.obj /Fdlib\PoissonRecon\CMakeFiles\poisson_recon.dir\poisson_recon.pdb /FS -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\PoissonRecon\Factor.cpp
[2/191] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -IC:\src\vcpkg\installed\x64-windows\include -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\installed\x64-windows\include\qt5 -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -IC:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folib\LSD\CMakeFiles\lsd.dir\lsd.c.obj /Fdlib\LSD\CMakeFiles\lsd.dir\lsd.pdb /FS -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\LSD\lsd.c
[3/191] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DRELEASE -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -IC:\src\vcpkg\installed\x64-windows\include -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\installed\x64-windows\include\qt5 -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -IC:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W0 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folib\PoissonRecon\CMakeFiles\poisson_recon.dir\CmdLineParser.cpp.obj /Fdlib\PoissonRecon\CMakeFiles\poisson_recon.dir\poisson_recon.pdb /FS -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\PoissonRecon\CmdLineParser.cpp
...
Skipped 49 lines
...

[50/191] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DVL_DISABLE_AVX -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -IC:\src\vcpkg\installed\x64-windows\include -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\installed\x64-windows\include\qt5 -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -IC:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folib\VLFeat\CMakeFiles\vlfeat.dir\svm.c.obj /Fdlib\VLFeat\CMakeFiles\vlfeat.dir\vlfeat.pdb /FS -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\VLFeat\svm.c
[51/191] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DVL_DISABLE_AVX -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -IC:\src\vcpkg\installed\x64-windows\include -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\installed\x64-windows\include\qt5 -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -IC:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /D__SSE2__ /showIncludes /Folib\VLFeat\CMakeFiles\vlfeat.dir\imopv_sse2.c.obj /Fdlib\VLFeat\CMakeFiles\vlfeat.dir\vlfeat.pdb /FS -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\VLFeat\imopv_sse2.c
[52/191] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DVL_DISABLE_AVX -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -IC:\src\vcpkg\installed\x64-windows\include -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\installed\x64-windows\include\qt5 -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -IC:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folib\VLFeat\CMakeFiles\vlfeat.dir\svmdataset.c.obj /Fdlib\VLFeat\CMakeFiles\vlfeat.dir\vlfeat.pdb /FS -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\VLFeat\svmdataset.c
[53/191] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DVL_DISABLE_AVX -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -IC:\src\vcpkg\installed\x64-windows\include -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\installed\x64-windows\include\qt5 -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -IC:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folib\VLFeat\CMakeFiles\vlfeat.dir\vlad.c.obj /Fdlib\VLFeat\CMakeFiles\vlfeat.dir\vlfeat.pdb /FS -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\VLFeat\vlad.c
[54/191] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DVL_DISABLE_AVX -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -IC:\src\vcpkg\installed\x64-windows\include -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\installed\x64-windows\include\qt5 -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -IC:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /D__SSE2__ /showIncludes /Folib\VLFeat\CMakeFiles\vlfeat.dir\mathop_sse2.c.obj /Fdlib\VLFeat\CMakeFiles\vlfeat.dir\vlfeat.pdb /FS -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\VLFeat\mathop_sse2.c
[55/191] C:\PROGRA~1\NVIDIA~2\CUDA\v11.8\bin\nvcc.exe -forward-unknown-to-host-compiler -DBOOST_ALL_DYN_LINK=1 -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DIMATH_DLL -DOPENEXR_DLL -DOPENGL_ENABLED -DOPENMP_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DWIN32_LEAN_AND_MEAN -D_MWAITXINTRIN_H_INCLUDED -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -isystem=C:\src\vcpkg\installed\x64-windows\include -isystem=C:\src\vcpkg\installed\x64-windows\include\eigen3 -isystem=C:\src\vcpkg\installed\x64-windows\include\qt5 -isystem=C:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -isystem=C:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -isystem=C:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -isystem=C:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -isystem=C:\src\vcpkg\installed\x64-windows\include\qt5\QtGui -isystem="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -isystem=C:\src\vcpkg\installed\x64-windows\include\webp -isystem=C:\src\vcpkg\installed\x64-windows\include\OpenEXR -isystem=C:\src\vcpkg\installed\x64-windows\include\Imath -isystem=C:\src\vcpkg\installed\x64-windows\include\GKlib -D_WINDOWS -Xcompiler="/W3 /GR /EHsc" -D_FORCE_INLINES -Wno-deprecated-gpu-targets --use_fast_math --default-stream per-thread -Xptxas=-suppress-stack-size-warning -Xcompiler="-MDd  -Zi -Ob0 -Od /RTC1" -arch=native /EHsc -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -std=c++14 -MD -MT src\CMakeFiles\colmap_cuda.dir\mvs\gpu_mat_ref_image.cu.obj -MF src\CMakeFiles\colmap_cuda.dir\mvs\gpu_mat_ref_image.cu.obj.d -x cu -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src\mvs\gpu_mat_ref_image.cu -o src\CMakeFiles\colmap_cuda.dir\mvs\gpu_mat_ref_image.cu.obj -Xcompiler=-Fdsrc\CMakeFiles\colmap_cuda.dir\colmap_cuda.pdb,-FS
FAILED: src/CMakeFiles/colmap_cuda.dir/mvs/gpu_mat_ref_image.cu.obj 
C:\PROGRA~1\NVIDIA~2\CUDA\v11.8\bin\nvcc.exe -forward-unknown-to-host-compiler -DBOOST_ALL_DYN_LINK=1 -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DIMATH_DLL -DOPENEXR_DLL -DOPENGL_ENABLED -DOPENMP_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DWIN32_LEAN_AND_MEAN -D_MWAITXINTRIN_H_INCLUDED -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -isystem=C:\src\vcpkg\installed\x64-windows\include -isystem=C:\src\vcpkg\installed\x64-windows\include\eigen3 -isystem=C:\src\vcpkg\installed\x64-windows\include\qt5 -isystem=C:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -isystem=C:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -isystem=C:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -isystem=C:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -isystem=C:\src\vcpkg\installed\x64-windows\include\qt5\QtGui -isystem="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -isystem=C:\src\vcpkg\installed\x64-windows\include\webp -isystem=C:\src\vcpkg\installed\x64-windows\include\OpenEXR -isystem=C:\src\vcpkg\installed\x64-windows\include\Imath -isystem=C:\src\vcpkg\installed\x64-windows\include\GKlib -D_WINDOWS -Xcompiler="/W3 /GR /EHsc" -D_FORCE_INLINES -Wno-deprecated-gpu-targets --use_fast_math --default-stream per-thread -Xptxas=-suppress-stack-size-warning -Xcompiler="-MDd  -Zi -Ob0 -Od /RTC1" -arch=native /EHsc -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -std=c++14 -MD -MT src\CMakeFiles\colmap_cuda.dir\mvs\gpu_mat_ref_image.cu.obj -MF src\CMakeFiles\colmap_cuda.dir\mvs\gpu_mat_ref_image.cu.obj.d -x cu -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src\mvs\gpu_mat_ref_image.cu -o src\CMakeFiles\colmap_cuda.dir\mvs\gpu_mat_ref_image.cu.obj -Xcompiler=-Fdsrc\CMakeFiles\colmap_cuda.dir\colmap_cuda.pdb,-FS
nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified

[56/191] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DCGAL_ENABLED -DCUDA_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DRELEASE -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -IC:\src\vcpkg\installed\x64-windows\include -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\installed\x64-windows\include\qt5 -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -IC:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W0 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /Folib\PoissonRecon\CMakeFiles\poisson_recon.dir\PoissonRecon.cpp.obj /Fdlib\PoissonRecon\CMakeFiles\poisson_recon.dir\poisson_recon.pdb /FS -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\PoissonRecon\PoissonRecon.cpp
[57/191] C:\PROGRA~1\NVIDIA~2\CUDA\v11.8\bin\nvcc.exe -forward-unknown-to-host-compiler -DCGAL_ENABLED -DCUDA_ENABLED -DCUDA_SIFTGPU_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DSIFTGPU_NO_DEVIL -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib -IC:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\src -IC:\src\vcpkg\installed\x64-windows\include -IC:\src\vcpkg\installed\x64-windows\include\eigen3 -IC:\src\vcpkg\installed\x64-windows\include\qt5 -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtCore -IC:\src\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtWidgets -IC:\src\vcpkg\installed\x64-windows\include\qt5\QtGui -isystem="C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -D_WINDOWS -Xcompiler="/W3 /GR /EHsc" -D_FORCE_INLINES -Wno-deprecated-gpu-targets -Xcompiler="-MDd  -Zi -Ob0 -Od /RTC1" -arch=native -std=c++14 -MD -MT lib\SiftGPU\CMakeFiles\sift_gpu.dir\ProgramCU.cu.obj -MF lib\SiftGPU\CMakeFiles\sift_gpu.dir\ProgramCU.cu.obj.d -x cu -c C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\SiftGPU\ProgramCU.cu -o lib\SiftGPU\CMakeFiles\sift_gpu.dir\ProgramCU.cu.obj -Xcompiler=-Fdlib\SiftGPU\CMakeFiles\sift_gpu.dir\sift_gpu.pdb,-FS
ProgramCU.cu
C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\SiftGPU\CuTexImage.h(64): warning C4267: 'return': conversion from 'size_t' to 'int', possible loss of data

C:\src\vcpkg\buildtrees\colmap\src\b221bdabb2-6df8038bd6.clean\lib\SiftGPU\ProgramCU.cu(1383): warning C4267: '=': conversion from 'size_t' to 'int', possible loss of data

ninja: build stopped: subcommand failed.
```

</details>

**Additional context**

[issue_body.md](https://github.com/microsoft/vcpkg/files/11010575/issue_body.md)

**Comment by debangsha-versatile** [comment] 2023-03-21 23:44
I am getting the same error

**Comment by amirrouhandeh** [comment] 2023-03-22 19:05
me too!

**Comment by FrankXie05** [comment] 2023-03-23 02:12
Duplicate of https://github.com/microsoft/vcpkg/issues/30272

**Closed** 2023-03-23 02:14 UTC
Labels: category:port-bug
