### ISSUE TITLE
vcpkg update failure

### ISSUE THREAD

**Issue by Captain-Freels** [microsoft/vcpkg#36717] opened 2024-02-12 19:43 UTC
### Operating system

Windows 11

### Compiler

ROS Noetic

### Steps to reproduce the behavior

```Shell
C:\opt\ros\noetic\x64\tools\vcpkg>bootstrap-vcpkg.bat
```

### Failure logs

C:\opt\ros\noetic\x64\tools\vcpkg>bootstrap-vcpkg.bat

Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  buildenvironment.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.fetch.cpp
  commands.format-manifest.cpp
  commands.hash.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.ifw.cpp
  export.prefab.cpp
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  platform-expression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkglib.vcxproj -> C:\opt\ros\noetic\x64\tools\vcpkg\toolsrc\msbuild.x86
  .release\vcpkglib.lib
  vcpkg.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 19945 functions were compiled because no usable IPDB/IOBJ from previo
  us compilation was found.
  Finished generating code
  vcpkg.vcxproj -> C:\opt\ros\noetic\x64\tools\vcpkg\toolsrc\msbuild.x86.re
  lease\vcpkg.exe
  vcpkgmetricsuploader.cpp
  Generating code
  Previous IPDB not found, fall back to full compilation.
  All 9332 functions were compiled because no usable IPDB/IOBJ from previou
  s compilation was found.
  Finished generating code
  vcpkgmetricsuploader.vcxproj -> C:\opt\ros\noetic\x64\tools\vcpkg\toolsrc
  \msbuild.x86.release\vcpkgmetricsuploader.exe

Building vcpkg.exe... done.

C:\opt\ros\noetic\x64\tools\vcpkg>vcpkg version
Vcpkg package management program version 2020.06.15-nohash

See LICENSE.txt for license information.

### Additional context

I tried 'vcpkg update' but I wanted to update the local profiles and it told me to use 'git pull', so I did. It then gave me the error: "fatal: not a git repository (or ant if the parent directories): .git". Which then led me to try bootstrap and here I am with no update. I have the 2024-02-07 version at C:\vcpkg but when I try to install ompl[app], it says:

"warning: The vcpkg C:\vcpkg\vcpkg.exe is using detected vcpkg root C:\vcpkg and ignoring mismatched 
  VCPKG_ROOT environment value c:\opt\ros\noetic\x64\tools\vcpkg. To suppress this message, unset the 
  environment variable or use the --vcpkg-root command line switch.
  Computing installation plan...
  ompl has no feature named app.note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this 
  failure."

Rerunning bootstrap here did not resolve the issue, and that is what lead me to the directory I am currently working in

**Comment by MonicaLiu0311** [comment] 2024-02-18 06:50
Please run `git pull https://github.com/microsoft/vcpkg.git master`.

**Comment by MonicaLiu0311** [comment] 2024-02-18 06:51
Duplicate of https://github.com/microsoft/vcpkg/issues/36688.

**Closed by MonicaLiu0311** 2024-02-18 06:51 UTC
Labels: category:question
