### ISSUE TITLE
[x264] build failure on previous vcpkg version

### ISSUE THREAD

**Issue by aspioupiou** [microsoft/vcpkg#12632] opened 2020-07-29 08:04 UTC
This is a duplicate of my message in the closed issue #7225 as I'm not sure maintainers got notified of this. 

Hi @NancyLi1013

I'd rather keep talking here instead of recreating a new issue, as my issue is directly linked to this one but not to #11765

As we're using vcpkg in a company environment, we do need to ensure we can build the dependencies.
Since updating to 2020.06 seems to be impossible in the meantime (x264 can't be built because of #11765), we tried to make a step back and update from a 2019.10 release to a 2020.01/04 instead of 06.

However, we've noticed x264 is not built there either, having a msys building issue :

```
-- Acquiring MSYS Packages...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/usr/Documents/Code/vcpkg/downloads/tools/msys2/msys64/usr/bin/bash.exe --noprofile --norc -c "pacman -Sy --noconfirm --needed diffutils"
    Working Directory: D:/brard/Documents/Code/vcpkg/downloads/tools/msys2
    Error code: Exit code 0xc0000142

    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_acquire_msys.cmake:106 (vcpkg_execute_required_process)
  scripts/cmake/vcpkg_configure_make.cmake:130 (vcpkg_acquire_msys)
  ports/x264/portfile.cmake:19 (vcpkg_configure_make)
  scripts/ports.cmake:94 (include)
```

This is very problematic, as we're not capable to build our project again since we absolutely need x264.
How such a regression happened? And how can we solve it to at least build the project without any errors? (BTW, we didn't noticed this issue before because of dependencies cache not beeing updated)

Thank you

**Comment by NancyLi1013** [comment] 2020-07-30 02:43
Hi @aspioupiou 

Thanks for posting this issue again. I tried to build this port based on the previous version and it failed due to `msys2` at the first time.
So I also tried to build the precious version for `x264 ` with the latest `msys2`. In this case, it can build successfully.

Considering the current status, you can only use the precious version for `x264 ` with the latest `msys2`.

Please update vcpkg to the latest version, and then update x264 to the commit https://github.com/microsoft/vcpkg/commit/7c6ff87f5737b57b7b2363ea8951a481e6397734 manually.

Hope this can help you.

**Comment by NancyLi1013** [comment] 2020-07-30 02:48
[portfile.txt](https://github.com/microsoft/vcpkg/files/4998478/portfile.txt)

You just need to update the content in portfile.cmake file. You can refer to this attachment.

**Comment by aspioupiou** [comment] 2020-07-30 07:02
Hi @NancyLi1013 

Thank you for your feedback,
After posting, I saw #12288 and understood it was a msys issue at first.

vcpkg is really a great tool and we love using it at the company, but the lack of stability is sometimes annoying and time consuming... 
Why not forking all these dependencies to avoid all these issues ?

Anyway, thanks again for your help

**Comment by NancyLi1013** [comment] 2020-08-04 09:37
@aspioupiou 
Sorry for the late response. 

Keeping all ports work fine, which is also what we expect. But now for the `msys `issue, it is caused by the update for `msys` components . 
More details, please see #12288

**Comment by NancyLi1013** [comment] 2020-08-11 09:13
Hi @aspioupiou 

In my opinion, this issue should be solved now. So I'm closing this issue for now.

For the issue that builds on Windows, we can track it here #11765.

**Closed by NancyLi1013** 2020-08-11 09:13 UTC
Labels: category:question
