### ISSUE TITLE
[vtk[all]] build failure

### ISSUE THREAD

**Issue by derekyu56** [microsoft/vcpkg#31135] opened 2023-04-26 16:19 UTC
### Operating system

Windows 10

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
./vcpkg install vtk[all]
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    vtk[all,atlmfc,core,gdal,geojson,mpi,python,qt,utf8,vtkm]:x64-windows -> 9.2.0-pv5.11.0#6
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\derekyu\AppData\Local\vcpkg\archives in 232 us. Use --debug to see more details.
Installing 1/1 vtk:x64-windows...
Building vtk[all,atlmfc,core,gdal,geojson,mpi,python,qt,utf8,vtkm]:x64-windows...
-- Using cached vtk-string-bfa3e4.diff.
-- Using cached Kitware-VTK-66143ef041b980a51e41ee470d053e67209150f8.tar.gz.
-- Cleaning sources at E:/dev/vcpkg/buildtrees/vtk/src/67209150f8-fc86012735.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/dev/vcpkg/downloads/Kitware-VTK-66143ef041b980a51e41ee470d053e67209150f8.tar.gz
-- Applying patch FindLZMA.patch
-- Applying patch FindLZ4.patch
-- Applying patch Findproj.patch
-- Applying patch pegtl.patch
-- Applying patch pythonwrapper.patch
-- Applying patch NoUndefDebug.patch
-- Applying patch fix-using-hdf5.patch
-- Applying patch FindExpat.patch
-- Applying patch cgns.patch
-- Applying patch vtkm.patch
-- Applying patch afxdll.patch
-- Applying patch vtkioss.patch
-- Applying patch jsoncpp.patch
-- Applying patch iotr.patch
-- Applying patch E:/dev/vcpkg/downloads/vtk-string-bfa3e4.diff
-- Applying patch 9690.diff
-- Using source at E:/dev/vcpkg/buildtrees/vtk/src/67209150f8-fc86012735.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: E:/dev/vcpkg/buildtrees/vtk/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\dev\vcpkg\buildtrees\vtk\config-x64-windows-dbg-CMakeCache.txt.log
      E:\dev\vcpkg\buildtrees\vtk\config-x64-windows-rel-CMakeCache.txt.log
      E:\dev\vcpkg\buildtrees\vtk\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:248 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:208 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building vtk:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vtk
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[vtk]+Build+error&body=Copy+issue+body+from+E%3A%2Fdev%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/11335120/config-x64-windows-out.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11335121/config-x64-windows-rel-CMakeCache.txt.log)
[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/11335122/config-x64-windows-dbg-CMakeCache.txt.log)

**Comment by FrankXie05** [comment] 2023-04-27 03:03
```
CMake Warning at E:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package):
  By not providing "Findospray.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ospray", but
  CMake did not find one.

  Could not find a package configuration file provided by "ospray" (requested
  version 2.1) with any of the following names:

    osprayConfig.cmake
    ospray-config.cmake

  Add the installation prefix of "ospray" to CMAKE_PREFIX_PATH or set
  "ospray_DIR" to a directory containing one of the above files.  If "ospray"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMake/vtkModule.cmake:4573 (find_package)
  Rendering/RayTracing/CMakeLists.txt:58 (vtk_module_find_package)


CMake Error at CMake/vtkModule.cmake:4579 (message):
  Could not find the ospray external dependency.
Call Stack (most recent call first):
  Rendering/RayTracing/CMakeLists.txt:58 (vtk_module_find_package)
```
Duplicate of https://github.com/microsoft/vcpkg/issues/25579.

**Closed by FrankXie05** 2023-04-27 03:03 UTC
Labels: category:port-bug
