### ISSUE TITLE
hash on 7zip downloadable has changed

### ISSUE THREAD

**Issue by jherico** [Microsoft/vcpkg#4671] opened 2018-11-07 20:41 UTC
https://github.com/Microsoft/vcpkg/blob/4f3e3fcdcb9e922533120aa92e8f8faf775e0d29/scripts/vcpkgTools.xml#L66

The hash for the file available at that [URL](https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0) has changed to a9dfaaafd15d98a2ac83682867ec5766720acf6e99d40d1a00d480692752603bf3f3742623f0ea85647a92374df405f331afd6021c5cf36af43ee8db198129c0  

My builds have started failing because of this.

**Comment by jherico** [comment] 2018-11-07 20:59
I've double checked the file...  if you grab it and rename it to a `zip` file, and open it, it contains files that have been modified in the past few days, although the nuget website insists it hasn't been updated in 7 months:  https://www.nuget.org/packages/7-Zip.CommandLine/18.1.0

**Comment by ras0219-msft** [comment] 2018-11-07 21:33
Duplicate of #4663.

**Closed by ras0219-msft** 2018-11-07 21:33 UTC
