### ISSUE TITLE
[openssl:x86-windows] Build error

### ISSUE THREAD

**Issue by 747728775** [microsoft/vcpkg#32721] opened 2023-07-24 06:53 UTC
Package: openssl:x86-windows -> 3.1.1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32535.0
-    vcpkg-tool version: 2023-06-15-8c254a5fb6c503615834fc66bd0717664a339a2e
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install openssl:x86-windows`

**Failure logs**

```
-- Using cached openssl-openssl-openssl-3.1.1.tar.gz.
-- Cleaning sources at E:/vcpkgnew/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/vcpkgnew/downloads/openssl-openssl-openssl-3.1.1.tar.gz
-- Applying patch disable-apps.patch
-- Applying patch disable-install-docs.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Using source at E:/vcpkgnew/buildtrees/openssl/src/nssl-3.1.1-53a8e40f57.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x86-windows
-- Getting CMake variables for x86-windows
-- Prerunning x86-windows-dbg
-- Building x86-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/VisualStudio/Community/VC/Tools/MSVC/14.36.32532/bin/Hostx64/x86/nmake.exe /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: E:/vcpkgnew/buildtrees/openssl/x86-windows-dbg
    See logs for more information:
      E:\vcpkgnew\buildtrees\openssl\install-x86-windows-dbg-nmake-out.log
      E:\vcpkgnew\buildtrees\openssl\install-x86-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:50 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:68 (include)
  scripts/ports.cmake:147 (include)



```
<details><summary>E:\vcpkgnew\buildtrees\openssl\install-x86-windows-dbg-nmake-out.log</summary>

```
	D:\VisualStudio\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x86\nmake.exe /LU                 depend
	D:\VisualStudio\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x86\nmake.exe /LU                 _build_libs
	"D:\VisualStudio\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x86\cl.exe" /EP -D__ASSEMBLER__  /Zi /Fdossl_static.pdb /Gs0 /GF /Gy /MDd -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP  -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -I"." -I"include" -I"providers\common\include" -I"providers\implementations\include" -D"L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSLDIR=\"E:\\vcpkgnew\\packages\\openssl_x86-windows\\debug\"" -D"ENGINESDIR=\"E:\\vcpkgnew\\packages\\openssl_x86-windows\\debug\\lib\\engines-3\"" -D"MODULESDIR=\"E:\\vcpkgnew\\packages\\openssl_x86-windows\\debug\\bin\"" -D"OPENSSL_BUILDING_OPENSSL" -D"OPENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D"_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"DEBUG" -D"_DEBUG"   -DAES_ASM -DCMLL_ASM -DDES_ASM -DECP_NISTZ256_ASM -DGHASH_ASM -DMD5_ASM -DOPENSSL_BN_ASM_GF2m -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_PART_WORDS -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_USE_APPLINK -DPADLOCK_ASM -DPOLY1305_ASM -DRMD160_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DVPAES_ASM -DWHIRLPOOL_ASM "crypto\aes\aes-586.S" > crypto\aes\libcrypto-shlib-aes-586.obj.asm
	"E:\vcpkgnew\downloads\tools\nasm\nasm-2.16.01\nasm.exe"  -f win32  -o crypto\aes\libcrypto-shlib-aes-586.obj crypto\aes\libcrypto-shlib-aes-586.obj.asm
```
</details>
<details><summary>E:\vcpkgnew\buildtrees\openssl\install-x86-windows-dbg-nmake-err.log</summary>

```
cl : Command line warning D9025 : overriding '/Zi' with '/Z7'
aes-586.S
crypto\aes\libcrypto-shlib-aes-586.obj.asm:1: error: parser: instruction expected
crypto\aes\libcrypto-shlib-aes-586.obj.asm:2: error: parser: instruction expected
crypto\aes\libcrypto-shlib-aes-586.obj.asm:5: error: label or instruction expected at start of line
crypto\aes\libcrypto-shlib-aes-586.obj.asm:21: warning: label alone on a line without a colon might be in error [-w+label-orphan]
NMAKE : fatal error U1077: '"E:\vcpkgnew\downloads\tools\nasm\nasm-2.16.01\nasm.exe"  -f win32  -o crypto\aes\libcrypto-shlib-aes-586.obj crypto\aes\libcrypto-shlib-aes-586.obj.asm' : return code '0x1'
Stop.
NMAKE : fatal error U1077: 'D:\VisualStudio\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x86\nmake.exe /LU                 _build_libs' : return code '0x2'
Stop.
```
</details>

**Additional context**

**Comment by jimwang118** [comment] 2023-07-24 07:57
Duplicate of https://github.com/microsoft/vcpkg/issues/32719

**Closed by jimwang118** 2023-07-24 07:57 UTC
