### ISSUE TITLE
vcpkg upgrade always installs default features

### ISSUE THREAD

**Issue by zrax** [microsoft/vcpkg#11479] opened 2020-05-20 22:26 UTC
**Describe the bug**
If a port was previously installed with only a subset of available features, upgrading it will always pull in the default features, which may not be desired.

**Environment**
- OS: Windows
- Compiler: MSVC 2019

**To Reproduce**
Example with libarchive:
1. Check out an older version of vcpkg
2. `./vcpkg install libarchive[core,bzip2,lzma]`
3. `git pull`
4. `./vcpkg upgrade`
    * or: `./vcpkg upgrade libarchive`
    * or even: `./vcpkg upgrade libarchive[core,bzip2,lzma]`

All three forms of step 4 cause vcpkg to pull in the full set of default features (`libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl,zstd]`).  The last version especially is pretty clearly not what the user intended.

**Expected behavior**
Only the features requested should be included in the updated package.

**Comment by JackBoosY** [comment] 2020-05-25 02:44
@strega-nil Could you please take a look?

Thanks.

**Comment by BillyONeal** [comment] 2020-09-03 19:08
Duplicate of https://github.com/microsoft/vcpkg/issues/7471

**Closed by BillyONeal** 2020-09-03 19:08 UTC
Labels: requires:discussion
