### ISSUE TITLE
[colmap] Build error on x64-windows vs2019

### ISSUE THREAD

**Issue by qwesafgagSGD1234** [microsoft/vcpkg#36531] opened 2024-02-02 10:27 UTC
Package: colmap[core,cuda,tests]:x64-windows@2023-10-01

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30153.0
-    vcpkg-tool version: 2023-12-12-1c9ec1978a6b0c2b39c9e9554a96e3e275f7556e
    vcpkg-scripts version: unknown

**To Reproduce**

`vcpkg install colmap[cuda,tests]:x64-windows`
*
[issue_body.md](https://github.com/microsoft/vcpkg/files/14138714/issue_body.md)

**Comment by LilyWangLL** [comment] 2024-02-04 02:54
> nvcc fatal   : A single input file is required for a non-link phase when an outputfile is specified

Closed as duplicate of https://github.com/microsoft/vcpkg/issues/30272.

**Closed by LilyWangLL** 2024-02-04 02:54 UTC
Labels: category:port-bug
