### ISSUE TITLE
liblzma build failure

### ISSUE THREAD

**Issue by hafedh-trimeche** [microsoft/vcpkg#38007] opened 2024-04-06 14:07 UTC
### Operating system

Windows 11

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
vcpkg install liblzma
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    liblzma:x64-windows@5.4.4
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exeRestored 0 package(s) from C:\Users\Hafedh TRIMECHE\AppData\Local\vcpkg\archives in 68.5 us. Use --debug to see more details.
Installing 1/1 liblzma:x64-windows@5.4.4...
Building liblzma:x64-windows@5.4.4...
-- Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz -> tukaani-project-xz-v5.4.4.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from D:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: D:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz
error: Failed to download from mirror set
error: https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz: failed: status code 404
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1031):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 2us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 592us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 615 ms (605673us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/liblzma/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)

error: building liblzma:x64-windows failed with: BUILD_FAILED
Elapsed time to handle liblzma:x64-windows: 652 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+liblzma
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[liblzma]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by LucasGauci** [comment] 2024-04-07 06:41
I have this same issue.

**Comment by LilyWangLL** [comment] 2024-04-07 07:15
Duplicate of https://github.com/microsoft/vcpkg/issues/37893.

**Closed by LilyWangLL** 2024-04-07 07:15 UTC
Labels: category:port-bug

**Comment by kevinchahine** [comment] 2024-04-08 02:22
Same problem on windows 11.
