### ISSUE TITLE
Why vcpkg in my computer can't install packages?

### ISSUE THREAD

**Issue by nebulaed** [microsoft/vcpkg#18861] opened 2021-07-08 03:25 UTC
When I try to install **matplotlib-cpp** using **vcpkg**, the console always returns `Computing installation plan...`, then nothing happens. After that, I checked the installation package with `.\vcpkg list`. It seems that this package has not been installed. 
I also tried to install other packages and encountered the same situation.

**Environment**:

 1. Windows 10, 64 bit build 19042
 2. Visual Studio 2019
 3. cmake 3.21.0-rc2
 4. Git

![The scene where the problem occurred.](https://user-images.githubusercontent.com/46734013/124857575-1f413400-dfdf-11eb-975f-82ad269df5ee.png)

**Comment by JonLiu1993** [comment] 2021-07-08 06:00
See [#18636  (comment)](https://github.com/microsoft/vcpkg/issues/18636#issuecomment-868555508)

**Comment by JonLiu1993** [comment] 2021-07-08 06:04
Duplicate of #18636

**Closed by JonLiu1993** 2021-07-08 06:04 UTC
Labels: requires:repro

**Comment by nebulaed** [comment] 2021-07-08 08:39
> Duplicate of #18636

Thank you. I reinstalled cmake 3.20.5, and then vcpkg worked.
