### ISSUE TITLE
[pcl] build failure: pcl has no feature named flann.

### ISSUE THREAD

**Issue by Bzz2745** [microsoft/vcpkg#31639] opened 2023-05-26 02:48 UTC
### Operating system

Windows 11

### Compiler

MSVC vc143

### Steps to reproduce the behavior

```Shell
`./vcpkg install pcl[apps,cuda,flann,openni2,pcap,qt,simulation,tools,visualization,vtk]:x64-windows --clean-after-build --recurse`
```

### Failure logs

pcl has no feature named flann.
note: updating vcpkg by rerunning bootstrap-vcpkg may resolve this failure.

**Comment by dg0yt** [comment] 2023-05-26 05:44
It is not a bug. pcl really has no feature named flann.

**Comment by jimwang118** [comment] 2023-05-26 06:06
There is no `flann` in the feature of `pcl`, it is in the dependency of `pcl`. So it will be installed automatically when you install `pcl`. You remove `flann `from the install command, then reinstall and it works.

**Comment by Bzz2745** [comment] 2023-05-26 10:43
> There is no `flann` in the feature of `pcl`, it is in the dependency of `pcl`. So it will be installed automatically when you install `pcl`. You remove `flann `from the install command, then reinstall and it works.

But originally FLANN is one of the dependencies of PCL, and the fast neighborhood search in PCL needs the support of FLANN, I don't know why there is suddenly no such dependency, but I just went to PCL's GitHub homepage today, and they did not explain this change.

**Comment by dg0yt** [comment] 2023-05-26 10:57
Again, `flann` is an unconditional *dependency* already. The dependency didn't disappear. It is not an on-demand *feature*. The abstract syntax of the install command is:
~~~
vcpkg install PORT[FEATURES] # not: PORT[DEPENDENCIES]
~~~

**Comment by jimwang118** [comment] 2023-06-02 07:16
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Closed by jimwang118** 2023-06-02 07:16 UTC
Labels: category:question
