### ISSUE TITLE
Optional Dependencies

### ISSUE THREAD

**Issue by JohannesBeck** [microsoft/vcpkg#249] opened 2016-11-03 06:47 UTC
I would like to specify optional dependencies, e.g. using OpenCV with cuda, if it is available, or boost with zlib. Is there such a mechanism available?

**Comment by ras0219-msft** [comment] 2016-11-03 21:42
We don't have such a mechanism currently. Instead, we tend to specify hard requirements on everything the project depends on in the default configuration. We want to build every piece that other libraries currently depend on.

In the future, we may need to have a mechanism like this, however it does cause some problems with transitive dependencies:

- SignalR depends on cpprestsdk's websockets support
- Cpprestsdk's websocket support is conditional on boost+openssl (optional dependencies)

Therefore, if we support optional dependencies for `cpprestsdk`, `signalr` isn't able to properly express its dependencies.

A simplifying invariant that might solve this is that "if library `B` is installed, all libraries with optional dependencies on `B` will be built with that dependency." Then, `signalr` could simply state that it depends on `cpprestsdk`, `boost`, and `openssl` and would then be guaranteed that `cpprestsdk` was built with full websockets support.

**Comment by ras0219-msft** [comment] 2016-11-03 21:43
PR #88 had some discussion on this topic as well.

**Comment by KindDragon** [comment] 2017-05-23 23:31
I think we should support `Recommends` and `Conflicts` in `CONTROL` file https://www.debian.org/doc/debian-policy/ch-relationships.html#s-binarydeps

**Comment by KindDragon** [comment] 2017-05-23 23:37
We just need `Conflicts`, `Provides` and `Replaces` https://github.com/klusark/libjpeg-turbo/blob/770687dfcd5b229d32bfc0de9509b5ed7fe5cfb8/debian/control#L16-L18

**Comment by ras0219-msft** [comment] 2017-05-24 00:01
I don't think `Conflicts`, `Provides` and `Replaces` is the right solution for this particular issue. They do help solve the issue of alternates (#164).

Consider the scenario where a library has 4+ independent optional settings (such as boost and libarchive). To support each optional combination via (ab)using `Provides` would imply creating 2^N independent ports that enumerates the entire configuration space.

We do have a proposal draft that we believe solves this issue, which I hope to publish for public review once #1111 closes. It is very similar to Cargo's "features" [1].

[1] http://doc.crates.io/manifest.html#the-features-section

**Comment by KindDragon** [comment] 2017-05-24 00:20
> I don't think Conflicts, Provides and Replaces is the right solution for this particular issue. They do help solve the issue of alternates (#164).

Why not? 
`Provides` allow you referencing in all project by name `libjpeg-dev`, so you can just install `libjpeg7-dev` or `libjpeg-turbo8-dev` package and everyone who depends on it can use it by name `libjpeg-dev`

So in BoringSSL we add `Provides: openssl` and `Conflicts: openssl` to disable installation when openssl already installed

**Comment by KindDragon** [comment] 2017-05-24 00:21
For optional dependencies we can use `Recommends`

**Comment by ras0219-msft** [comment] 2017-05-24 00:55
The troublesome part is that optional dependencies will require a rebuild. This is in contrast with the debian interpretation of `Recommends`, which afaik does not imply rebuilding the package.

Additionally, Recommends focuses on _dependencies_ and has no power to express things like building a subset of boost if it doesn't change the dependencies.

Therefore, I think it is sufficiently different to need a different mechanism.

**Comment by KindDragon** [comment] 2017-05-24 08:02
I think it should work without rebuild.
For example Cpprestsdk with optional boost.
I think `vcpkg install cpprestsdk` should ask a user if he wants to install boost. If not, never rebuild it automatically.
Maybe add a special command to rebuild the package with all dependent packages.

**Comment by ras0219-msft** [comment] 2017-06-01 00:41
I've opened a PR for a potential solution to this problem; please take a look and let us know any feedback!

**Comment by jasjuang** [comment] 2017-06-09 21:39
+1 for an option for OpenCV with CUDA, CUDA is the reason that I am still building OpenCV from source instead of using the one from vcpkg

**Comment by nagua** [comment] 2017-06-19 19:51
Did you look into way gentoo handles this with the portage system and USE-flags? I think this would be a very good way for vcpkg. There would be a central place for the vcpkg installation were it would be possible to add global use-flags. And a package can specify what to do when a particular use-flag is set. So one would set a use-flag "cuda" and every library that has cuda support could detect, that the user wants to build it against cuda.

**Comment by ras0219-msft** [comment] 2017-06-19 22:36
Yep, we did look at USE-flags. At the bottom of the draft in #1205, we have a few paragraphs describing and comparing the options. If you're an avid Gentoo user, we'd appreciate your feedback!

Some big problems with USE flags that came up in my research:
- Even with global flags, you often still have to tweak the flags on a per-package basis
- Essentially no ability for conflict resolution. Everything is extremely manual.

Instead, our approach targets a subset of the general problem that we _can_ solve with automatic dependency resolution. There are definitely some choices we can't represent with that solution though (such Qt XOR GTK), and I think _those_ will warrant a system much closer to USE flags.

The USE flags approach is actually already possible: we have that central place (our triplet files) and every library can detect any macros set inside that central place (triplet files are automatically included at the top of every portfile). Since the triplet file is "code", it can use conditionals to tweak flags on a per-port basis. The only lacking capability is to express different dependencies for automatic installation based on those flags -- for now you can detect their absence and fail the build.

**Comment by nagua** [comment] 2017-06-20 17:50
Yes, I switch regularly between my Gentoo and Windows installation.

I have a question to one of your problem above:
 - What do you mean by automatic conflict resolution? Most of the time I have no problems with conflicts in gentoo. So to which kind of conflicts do you refer to and what should cause them? Gentoo's emerge is actually very good at handling conflics and dependencies and so on.
 
I read the draft yesterday night and here is my review:

 - Actually the proposed `feature` and gentoo's `useflags` are quiet similar, but they also have interesting differences
 - In gentoo it is very much indifferent where you set your use flag:
   + so you can either specify it globally,
   + for a specific package, 
   + or temporarily for the invocation of the current install run.
   + So when I compare `useflags` to `features` in this point, `features` are "crippled" to temporary install invocations. It should be easy to add a global configuration file where you can specify what `features` you want and on what packages. To get a more stateful experience in vcpkg.
 - In Gentoo there is also no real term of "global" `useflag` every package uses what it feels is the right flag. There are also tools to display which packages have which `useflags` so I can also specify "local" `useflags` as "global" `useflags`. The tools look somewhat similar to your proposed `vcpkg search` output.
 - You said in the draft, that it is not possible to do something like: "DirectX xor OpenGL", so you could add a `Build-Blocks: angle[directx]` to the control file. So you can at least validate if the current configuration of the complete featurespace is correct and can be installed.

While at this: It would be really great if there would be something like the `make.conf` where you could specify your prefered toolchain(VS15/17) and build tripplet and such things. 

So currently I see no big differences in both approaches for practical applications. So I mean basically you can think that both could have the same power, weren't it for the constraints in the `CONTROLS` file.
I mean that if you think of it as a `feature` or `useflag` is not important, what is important is what you can do with it and that depends on the specific implementation. And that is constrained to the `CONTROLS` file or the new draft for it.

To make them equal you can introduce a new `feature` for every boolean condition you could express with `useflags` that is not very cool for the end-user but it would work. 
So in Gentoo it would be:
```
RDEPEND="directx? ( angle[directx] )
                     !directx? ( opengl? ( angle[opengl] )) )"
```

In vcpkg:
```
Feature: directx
Build-Depends: angle[direcx]
Build-Blocks: package[opengl]

Feature: opengl
Build-Depends: angle[opengl]
Build-Blocks: package[directx]
```

So I hope most of this post does make sense. I wrote it partly yesterday night and the rest this evening.
If there is something wrong or something does not make sense, feel free to ask me about it.

**Comment by ras0219-msft** [comment] 2017-06-20 21:35
> What do you mean by automatic conflict resolution?

Because Gentoo allows expressing "or" and "not", it becomes ambiguous or intractable to come up with a 'solution' for `install X`. In the example above with angle, what happens when you install `angle`? Does it depend on the current state? What if the chosen solution in the current state requires installing something that conflicts with the current state? And so forth -- it becomes a general Boolean satisfiability problem :(.

In contrast, by explicitly limiting feature packages to only _positive_ relationships, we are guaranteed that a single straightforward solution exists -- just recursively select features until everything is satisfied. 

It's also easier to independently reason about (though I admit this is just convention). We intend each feature to represent a specific disjoint set of APIs or behaviors, so you can express _behavior_ dependencies instead of dependency-dependency-dependencies (though they may sometimes be the same). For example, instead of having a `websocketspp` useflag for `cpprestsdk`, we have a `ws-client` feature which might not depend on websocketspp in the future.

It's my understanding that Gentoo tends to focus on the dependencies (build with openssl, don't build with python) instead of the APIs (I need to be able to instantiate `boost::asio::X`, so I need `boost[asio]`) since the problem domain is different: primarily delivering applications instead of development resources.

>or temporarily for the invocation of the current install run. ... To get a more stateful experience in vcpkg.

A core design philosophy of Vcpkg is to try to minimize transient state. This is to maximize reproducibility -- if `vcpkg update` says you're clean, you can simply tell someone else to clone Vcpkg at your current SHA and just run `vcpkg install <everything in vcpkg list>` and they'll get the exact same setup. This is incidentally a big part of why features are designed like they are; users get 90% of the right idea if they just think of them like any other package -- no additional concepts needed.

Need boost python? Just `install boost[python]`.
Need opencv's cuda APIs? Just `install opencv[cuda]`.
Need API Y from X? Just `install X[Y]`.

To make this work "seamlessly" however, we need to limit the problem space to something that's easily decidable.

>It would be really great if there would be something like the make.conf where you could specify your prefered toolchain(VS15/17) and build tripplet and such things.

We've actually slightly overloaded the term triplet to refer to our version of make.conf. Inside `triplets\` you can have as many independent `X.cmake` files as you want, which each have the exact make.conf capabilities you've mentioned (toolset, per-package settings, etc). By default we ship with a handful of reasonably-named files, but it's totally supported to create `triplets\strawberry.cmake` that applies whatever settings you'd like and then just do `vcpkg install boost:strawberry` [1]. Each triplet encapsulates an entire universe of package builds which are completely independent and consistent.

Overall, you're totally right that it comes down to what we explicitly want to support -- we certainly could just implement useflags! However, hopefully I've expressed above the benefits of reducing the problem space in terms of user experience.

I definitely agree that something like `Build-Blocks: angle[opengl]` seems very reasonable in the future if we decide that we really need to cover the entire SAT space.

[1] https://vcpkg.readthedocs.io/en/latest/users/triplets/

**Comment by kklouzal** [comment] 2017-11-01 19:49
Can we ask the user weather or not they want to install optional dependencies when download packages? For example, [uWebSockets](https://github.com/uNetworking/uWebSockets) optionally require Boost (which I don't want) but vcpkg installs it anyways..

**Comment by ras0219-msft** [comment] 2017-11-01 20:25
@kklouzal I see that they don't have boost on their main readme, so I've removed it as a dependency. Thanks for pointing that out!

**Comment by MikeGitb** [comment] 2019-03-02 13:41
Is there still something to discuss here/feedback desired or has the discussion run its course and the issue can be closed?

**Comment by PhoebeHui** [comment] 2019-07-29 03:20
See https://github.com/microsoft/vcpkg/pull/1205, currently vcpkg support to add feature for ports. I guess we can close it now.

**Closed by PhoebeHui** 2019-07-29 03:20 UTC
Labels: discussion needed, vcpkg feature
