### ISSUE TITLE
[New Port Request] libigl

### ISSUE THREAD

**Issue by sirvelo** [microsoft/vcpkg#8016] opened 2019-09-01 22:33 UTC
Library name: libigl

Library description: libigl is a simple C++ geometry processing library.

Source repository URL:  https://github.com/libigl/libigl/

Project homepage (if different from the source repository):

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

Windows shared libraries are required.

**Comment by LilyWangL** [comment] 2019-09-02 08:23
Thanks for posting this issue. Closed as duplicate of #2601. Please pay attention to the progress of issue #2601.

**Closed by LilyWangL** 2019-09-02 08:23 UTC
Labels: new port request - consider making a PR!
