### ISSUE TITLE
vcpkg autcomplete bash stdout in binary mode

### ISSUE THREAD

**Issue by linquize** [microsoft/vcpkg#10596] opened 2020-03-29 05:11 UTC
vcpkg autcomplete bash stdout should be in binary mode
Output  `\n` instead of `\r\n`

![image](https://user-images.githubusercontent.com/791115/77840804-e2707580-71bd-11ea-9631-3b958b32eebe.png)

Steps to reproduce:
Assume vcpkg is in `C:\vcpkg`
Open Msys2 bash
```bash
cd /C/vcpkg
. scripts/vcpkg_completion.bash
./vcpkg install libf<Press tab>
```

**Comment by JackBoosY** [comment] 2020-03-31 05:43
Does this change affect what is displayed when using powershell?

**Comment by linquize** [comment] 2020-03-31 06:32
No problem in powershell

**Comment by JackBoosY** [comment] 2020-07-30 09:15
Should be fixed.

**Comment by linquize** [comment] 2020-08-02 05:58
No, it is not fixed! trailing `^M` still present.

**Comment by linquize** [comment] 2020-08-02 05:59
No, it is not fixed! Trailing ^M still present.
Please re-open this issue.

**Comment by JonLiu1993** [comment] 2022-12-07 08:57
@linquiz, sorry for replying to you so late, I followed your steps to reproduce and got different results, can you see where it is different from yours?

- open gitbash
- . scripts/vcpkg_completion.bash
- ./vcpkg install libf<Press tab>

![image](https://user-images.githubusercontent.com/63675417/206132642-06f8edc5-dd5e-408d-9e9a-e477ec506541.png)

**Comment by linquize** [comment] 2022-12-09 04:45
This is because Git Bash from Git for Windows misses some files about bash completion.

**Comment by linquize** [comment] 2022-12-09 04:46
https://github.com/git-for-windows/git/issues/2562

**Comment by LilyWangLL** [comment] 2023-02-14 09:35
Since this is a issue about Git, so I am closing this issue for now.

**Closed by LilyWangLL** 2023-02-14 09:35 UTC
Labels: requires:repro
