### ISSUE TITLE
libtheora build fails without CMake x86 binaries installed, fails to check for prerequisites

### ISSUE THREAD

**Issue by 4creators** [Microsoft/vcpkg#612] opened 2017-01-30 21:35 UTC
While testing some packages I have encountered error with CMake compiler detection. CMake v3.7.2. x64 did not see c and cxx compilers on my machine (Win10 v1607 x64 with VS2015 U3 and VS2017 RC, CMake v3.7.2 x64 installed and available via PATH). Accidentally while installing sqlite3 package it installed CMake v3.7.2. x86 package what fixed libtheora build errors.

Seems to be bug either in perequisite checking if CMake x86 is a requirement (should detect and install missing prerequisite) or mishandles x64 CMake binaries.

**Comment by ras0219-msft** [comment] 2017-01-31 03:04
(Probably) duplicate of #611. I'll reopen this if we can determine it's package specific.

**Closed by ras0219-msft** 2017-01-31 03:04 UTC
