### ISSUE TITLE
[boost-config] error building x64-osx

### ISSUE THREAD

**Issue by charneykaye** [microsoft/vcpkg#29299] opened 2023-01-30 21:22 UTC
**Host Environment**

- OS: macOS Monterey (12.6.1)
- Compiler: revision cmake version 3.25.2

**To Reproduce**

`cmake --preset ninja-multiconfiguration-vcpkg`

**Failure logs**

- [console.log](https://github.com/microsoft/vcpkg/files/10540074/console.log)
- [vcpkg-manifest-install.log](https://github.com/microsoft/vcpkg/files/10540075/vcpkg-manifest-install.log)
 
**Additional context**
- [CMakeLists.txt](https://github.com/microsoft/vcpkg/files/10540079/CMakeLists.txt)
- [vcpkg.json.zip](https://github.com/microsoft/vcpkg/files/10540093/vcpkg.json.zip)
- [CMakePresets.json.zip](https://github.com/microsoft/vcpkg/files/10540092/CMakePresets.json.zip)

**Comment by BillyONeal** [comment] 2023-01-30 21:38
Duplicate of https://github.com/microsoft/vcpkg/issues/29288

**Closed by BillyONeal** 2023-01-30 21:38 UTC
Labels: category:port-bug
