### ISSUE TITLE
Cached archive for glfw3 references vcpkg install path, which breaks glfw in other installs of vcpkg

### ISSUE THREAD

**Issue by andreasxp** [microsoft/vcpkg#14393] opened 2020-11-04 17:11 UTC
**Describe the bug**
I installed glfw3 for the first time via vcpkg located in `D:/Files/Develop/test_vulkan/vcpkg`. After some time I deleted that instance of vcpkg and installed glfw3 again in a different directory. But files in the archive contain references to the original directory:
```bash
~/AppData/Local/vcpkg/archives/54/54e26ba0bc272572f0c2856af2e7809231988312
$ grep -nr test_vulkan .
Binary file ./debug/lib/glfw3.lib matches
./debug/lib/pkgconfig/glfw3.pc:1:prefix=D:/Files/Develop/test_vulkan/vcpkg/packages/glfw3_x64-windows-static/debug
./debug/lib/pkgconfig/glfw3.pc:3:includedir=D:/Files/Develop/test_vulkan/vcpkg/packages/glfw3_x64-windows-static/debug/include
./debug/lib/pkgconfig/glfw3.pc:4:libdir=D:/Files/Develop/test_vulkan/vcpkg/packages/glfw3_x64-windows-static/debug/lib
Binary file ./lib/glfw3.lib matches
./lib/pkgconfig/glfw3.pc:1:prefix=D:/Files/Develop/test_vulkan/vcpkg/packages/glfw3_x64-windows-static
./lib/pkgconfig/glfw3.pc:3:includedir=D:/Files/Develop/test_vulkan/vcpkg/packages/glfw3_x64-windows-static/include
./lib/pkgconfig/glfw3.pc:4:libdir=D:/Files/Develop/test_vulkan/vcpkg/packages/glfw3_x64-windows-static/lib
```
It seems this (wrong) reference to a deleted directory is what breaks my debugging:
```
// This is from an error message in vscode:
Unable to open 'win32_window.c': Unable to read file 'd:\Files\Develop\test_vulkan\vcpkg\buildtrees\glfw3\src\3.3.2-558ea1f140.clean\src\win32_window.c'
(Error: Unable to resolve non-existing file 'd:\Files\Develop\test_vulkan\vcpkg\buildtrees\glfw3\src\3.3.2-558ea1f140.clean\src\win32_window.c').
```
For the time being I can fix this by deleting the archive, but I thought I would report the bug anyway.

**Environment**
- OS: Windows
- Compiler: Visual C++ 16.7.7

**To Reproduce**
The triplet is `x64-windows-static`.
1. `./directory1/vcpkg install glfw3`
2. Delete `directory1`
3. `./directory2/vcpkg install glfw3`
4. Attempt debugging

**Expected behavior**
Port archives should probably be directory-agnostic.

**Comment by NancyLi1013** [comment] 2020-11-11 06:42
Hi @andreasxp 
Thanks for posting this issue.

Do you use the archive whose repo was deleted to debug?

Every time you install the port, it will create a new binary cache that is put in archive folder. But every archive should not be related with each other.

**Comment by andreasxp** [comment] 2020-11-11 14:04
Hi @NancyLi1013, thanks for taking a look at this.
> Do you use the archive whose repo was deleted to debug?

I'm not sure I understand the question. By "repo" do you mean a clone of vcpkg repo that was later deleted? Then yes, but I did not do this on purpose. Judging by the location of the cache folder `~/AppData/Local/vcpkg/archives` I assume there is only one archive per user and this archive is used by all vcpkg instances.

You said that every time I install a port, it will create a new binary cache. Is that true for *every* time I install a port, or just when I install a port I haven't had on the system before? I don't know much about vcpkg structure, but I assumed that if a particular port (for example glfw3:x64-windows-static) was once installed, it's binary is cached and not rebuilt from source again. Is my understanding correct?

Like I stated in my original message, I found references in archive to a vcpkg install folder that no longer exists: `D:/Files/Develop/test_vulkan/vcpkg`, a vcpkg folder cloned for a single project that was using glfw3. I deleted that project along with it's vcpkg instance and created a new project with a new vcpkg instance and installed glfw3 again. And when debugging this second project, the original `D:/Files/Develop/test_vulkan/vcpkg` path showed up when debugging because the debugger did not find a source file. If a new binary cache is created every time I install the port, I don't understand how the original path got there since at the time of second install in the first directory was long gone.

**Comment by NancyLi1013** [comment] 2020-11-12 08:43
@andreasxp 



> Hi @NancyLi1013, thanks for taking a look at this.
> 
> > Do you use the archive whose repo was deleted to debug?
> 
> I'm not sure I understand the question. By "repo" do you mean a clone of vcpkg repo that was later deleted? Then yes, but I did not do this on purpose. Judging by the location of the cache folder `~/AppData/Local/vcpkg/archives` I assume there is only one archive per user and this archive is used by all vcpkg instances.
> 

You're right, that's what I mean for "repo".

For archive, it seems that every vcpkg instance has one binary cache for one port. If you have installed the port, then you remove it via `vcpkg remove portName`, then you reinstall the port, in this case, the port will not build again, just using the cached binary that has stored in archive.

Please see the example as follows:
```
PS F:\new\vcpkg> .\vcpkg.exe install bzip2
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
Could not locate cached archive: C:\Users\username\AppData\Local\vcpkg\archives\84\84266fd697ac3385ee4e8dab994276e9191ffb81.zip
-- Fetching https://sourceware.org/git/bzip2.git...
-- Extracting source F:/new/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at F:/new/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at F:/new/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: F:/new/vcpkg/packages/bzip2_x86-windows/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig file: F:/new/vcpkg/packages/bzip2_x86-windows/debug/lib/pkgconfig/bzip2.pc
-- Installing: F:/new/vcpkg/packages/bzip2_x86-windows/share/bzip2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\username\AppData\Local\vcpkg\archives\84\84266fd697ac3385ee4e8dab994276e9191ffb81.zip
Building package bzip2[core]:x86-windows... done
Installing package bzip2[core]:x86-windows...
Installing package bzip2[core]:x86-windows... done
Elapsed time for package bzip2:x86-windows: 28.17 s

Total elapsed time: 35.39 s

The package bzip2 is compatible with built-in CMake targets:

    find_package(BZip2 REQUIRED)
    target_link_libraries(main PRIVATE BZip2::BZip2)

PS F:\new\vcpkg>
PS F:\new\vcpkg>
PS F:\new\vcpkg> .\vcpkg.exe remove bzip2
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
The following packages will be removed:
    bzip2:x86-windows
Removing package bzip2:x86-windows...
Removing package bzip2:x86-windows... done
PS F:\new\vcpkg>
PS F:\new\vcpkg>
PS F:\new\vcpkg> .\vcpkg.exe install bzip2
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
Using cached binary package: C:\Users\username\AppData\Local\vcpkg\archives\84\84266fd697ac3385ee4e8dab994276e9191ffb81.zip
Building package bzip2[core]:x86-windows... done
Installing package bzip2[core]:x86-windows...
Installing package bzip2[core]:x86-windows... done
Elapsed time for package bzip2:x86-windows: 377.2 ms

Total elapsed time: 6.599 s

The package bzip2 is compatible with built-in CMake targets:

    find_package(BZip2 REQUIRED)
    target_link_libraries(main PRIVATE BZip2::BZip2)
 
```

But if you build the same port in different vcpkg instance, it will create a new binary cache, which will also be stored in _C:\Users\username\AppData\Local\vcpkg\archives_. But this binary cache will be put in a new subdirectory listed in `archives`.

Please see this example:

```
PS F:\tool\vcpkg> .\vcpkg.exe install bzip2
Computing installation plan...
The following packages will be built and installed:
    bzip2[core]:x86-windows
Detecting compiler hash for triplet x86-windows...
Starting package 1/1: bzip2:x86-windows
Building package bzip2[core]:x86-windows...
Could not locate cached archive: C:\Users\username\AppData\Local\vcpkg\archives\d9\d9fda1ecd39ab5442cae49617376ab2f1abf43bc.zip
-- Using cached F:/tool/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Cleaning sources at F:/tool/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/tool/vcpkg/downloads/bzip2-75a94bea3918e612b879d6a11ca64b8689526147.tar.gz
-- Applying patch fix-import-export-macros.patch
-- Using source at F:/tool/vcpkg/buildtrees/bzip2/src/8689526147-1ef169fbaa.clean
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Using msys root at F:/tool/vcpkg/downloads/tools/msys2/c809757c94447846
-- Fixing pkgconfig file: F:/tool/vcpkg/packages/bzip2_x86-windows/lib/pkgconfig/bzip2.pc
-- Fixing pkgconfig file: F:/tool/vcpkg/packages/bzip2_x86-windows/debug/lib/pkgconfig/bzip2.pc
-- Installing: F:/tool/vcpkg/packages/bzip2_x86-windows/share/bzip2/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\username\AppData\Local\vcpkg\archives\d9\d9fda1ecd39ab5442cae49617376ab2f1abf43bc.zip
Building package bzip2[core]:x86-windows... done
Installing package bzip2[core]:x86-windows...
Installing package bzip2[core]:x86-windows... done
Elapsed time for package bzip2:x86-windows: 29.25 s

Total elapsed time: 38.76 s

The package bzip2 is compatible with built-in CMake targets:

    find_package(BZip2 REQUIRED)
    target_link_libraries(main PRIVATE BZip2::BZip2)
```

Summary:

- When installing a new port, vcpkg will check if the binary cache has existed in `archives`. If yes, it will not build the port again. If not, it will build the source and generate a binary cache.

- Every vcpkg instance has one binary cache for one port.

**Comment by andreasxp** [comment] 2020-11-12 22:02
@NancyLi1013 Unfortunately this has not been my experience. I reproduced this in completely new directories with an empty vcpkg archive:
* Directory 1:
```
PS C:\Users\andreasxp\Desktop\folder1> .\vcpkg\vcpkg install glfw3
Computing installation plan...
The following packages will be built and installed:
    glfw3[core]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: glfw3:x64-windows-static
Building package glfw3[core]:x64-windows-static...
Could not locate cached archive: C:\Users\andreasxp\AppData\Local\vcpkg\archives\ef\ef1ce2b12a208beee94073ceed0672fa89563c55.zip
-- Downloading https://github.com/glfw/glfw/archive/3.3.2.tar.gz...
-- Extracting source C:/Users/andreasxp/Desktop/folder1/vcpkg/downloads/glfw-glfw-3.3.2.tar.gz
-- Using source at C:/Users/andreasxp/Desktop/folder1/vcpkg/buildtrees/glfw3/src/3.3.2-558ea1f140.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
-- Building x64-windows-static-rel
-- Installing: C:/Users/andreasxp/Desktop/folder1/vcpkg/packages/glfw3_x64-windows-static/share/glfw3/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\andreasxp\AppData\Local\vcpkg\archives\ef\ef1ce2b12a208beee94073ceed0672fa89563c55.zip
Building package glfw3[core]:x64-windows-static... done
Installing package glfw3[core]:x64-windows-static...
Installing package glfw3[core]:x64-windows-static... done
Elapsed time for package glfw3:x64-windows-static: 17.17 s

Total elapsed time: 34.56 s

The package glfw3:x64-windows-static provides CMake targets:

    find_package(glfw3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glfw)

```
* Directory 2:
```
PS C:\Users\andreasxp\Desktop\folder2> .\vcpkg\vcpkg install glfw3
Computing installation plan...
The following packages will be built and installed:
    glfw3[core]:x64-windows-static
Detecting compiler hash for triplet x64-windows-static...
Starting package 1/1: glfw3:x64-windows-static
Building package glfw3[core]:x64-windows-static...
Using cached binary package: C:\Users\andreasxp\AppData\Local\vcpkg\archives\ef\ef1ce2b12a208beee94073ceed0672fa89563c55.zip
Building package glfw3[core]:x64-windows-static... done
Installing package glfw3[core]:x64-windows-static...
Installing package glfw3[core]:x64-windows-static... done
Elapsed time for package glfw3:x64-windows-static: 112.3 ms

Total elapsed time: 15.18 s

The package glfw3:x64-windows-static provides CMake targets:

    find_package(glfw3 CONFIG REQUIRED)
    target_link_libraries(main PRIVATE glfw)

```

As you can see, the second directory used the binary cache from the first directory, which is what caused my debugging problems in the first place.

**Comment by NancyLi1013** [comment] 2021-03-25 02:57
@andreasxp 

Sorry for the long delay. Seems your test results are right. I can get the same result with yours for binary cache with the latest vcpkg. Please see the doc to get more information about binary caching https://github.com/microsoft/vcpkg/blob/master/docs/users/binarycaching.md.

For the problem you encountered with `glfw3`, I think this is a port bug of `glfw3`. Since there is absolute path contained in glfw3.pc file, which is the root cause of this issue.

Now this issue has been fixed by adding `vcpkg_fixup_pkgconfig()` via https://github.com/microsoft/vcpkg/pull/16166.

So you can update to the latest vcpkg and rebuild `glfw3`.

I have checked the path has been relative now. I'm closing this issue.

**Closed by NancyLi1013** 2021-03-25 02:57 UTC
Labels: category:port-bug
