### ISSUE TITLE
qt5.8 problem: private headers (PRIVATE_INCLUDE_DIRS) not populated in cmake configuration files

### ISSUE THREAD

**Issue by bagong** [Microsoft/vcpkg#1021] opened 2017-05-03 22:11 UTC
Using the new qt5 (5.8) build in a Webkit build, I got the following errors:
````
  C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\qt\GraphicsContextQt.cpp(73): fatal error C1083: Cannot open include file: 'private/qpdf_p.h': No such file or directory [C:\Users\Rainer\Projects\sc\webkit\build\Source\WebCore\WebCore.vcxproj]
  C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\qt\ImageBufferDataQt.cpp(54): fatal error C1083: Cannot open include file: 'private/qopenglpaintengine_p.h': No such file or directory [C:\Users\Rainer\Projects\sc\webkit\build\Source\WebCore\WebCore.vcxproj]
  C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\qt\ImageQt.cpp(53): fatal error C1083: Cannot open include file: 'private/qhexstring_p.h': No such file or directory [C:\Users\Rainer\Projects\sc\webkit\build\Source\WebCore\WebCore.vcxproj]
  C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\qt\GraphicsContext3DQt.cpp(34): fatal error C1083: Cannot open include file: 'private/qopenglextensions_p.h': No such file or directory [C:\Users\Rainer\Projects\sc\webkit\build\Source\WebCore\WebCore.vcxproj]
  C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\qt\OpenGLShimsQt.h(28): fatal error C1083: Cannot open include file: 'private/qopenglextensions_p.h': No such file or directory (compiling source file C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\opengl\TemporaryOpenGLSetting.cpp) [C:\Users\Rainer\Projects\sc\webkit\build\Source\WebCore\WebCore.vcxproj]
  C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\qt\OpenGLShimsQt.h(28): fatal error C1083: Cannot open include file: 'private/qopenglextensions_p.h': No such file or directory (compiling source file C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\opengl\Extensions3DOpenGLCommon.cpp) [C:\Users\Rainer\Projects\sc\webkit\build\Source\WebCore\WebCore.vcxproj]
  C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\qt\OpenGLShimsQt.h(28): fatal error C1083: Cannot open include file: 'private/qopenglextensions_p.h': No such file or directory (compiling source file C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\opengl\Extensions3DOpenGL.cpp) [C:\Users\Rainer\Projects\sc\webkit\build\Source\WebCore\WebCore.vcxproj]
  C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\qt\OpenGLShimsQt.h(28): fatal error C1083: Cannot open include file: 'private/qopenglextensions_p.h': No such file or directory (compiling source file C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\opengl\GraphicsContext3DOpenGL.cpp) [C:\Users\Rainer\Projects\sc\webkit\build\Source\WebCore\WebCore.vcxproj]
  C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\qt\OpenGLShimsQt.h(28): fatal error C1083: Cannot open include file: 'private/qopenglextensions_p.h': No such file or directory (compiling source file C:\Users\Rainer\Projects\sc\webkit\Source\WebCore\platform\graphics\opengl\GraphicsContext3DOpenGLCommon.cpp) [C:\Users\Rainer\Projects\sc\webkit\build\Source\WebCore\WebCore.vcxproj]
````

The private Qt headers are not found.

Compare `installed/(triplet)/share/cmake/Qt5Gui/Qt5GuiConfig.cmake`, line 59, empty string:

`set(Qt5Gui_PRIVATE_INCLUDE_DIRS "")`

This seems to be a known problem with shadow builds. Compare:

https://bugreports.qt.io/browse/QTBUG-37417

https://bugreports.qt.io/browse/QTBUG-37297

https://www.bountysource.com/issues/11705181-dev-qt-qt-5-qt5-_private_include_dirs-are-empty-in-generated-qt5-config-cmake-files-in-shadow-builds

In the earlier link: "From personal experience and the Internet: This problem arises when doing a shadow build and then make install. Workaround is to do an in-source build." , or: to patch the installed files to provide paths...

Thanks for your considerations!

**Comment by tobiaskohlbau** [comment] 2017-05-04 07:27
I'v started reading into this. We could solve this by hardcoding inclusion of private headers, but I'm not sure if it is right in this context. I would suggest, as reported by many users over in the bountysource tracker, to switch over to an in source build. You could try to remove the disabled webkit support within qt5 port and report back any issues, maybe we could build a working build with webkit together. As soon as we have a working version built with webkit I would suggest to make it optional by commenting out the relevant lines and after support of optional features by vcpkg the user can decide what serves his needs.

Remove this [line](https://github.com/Microsoft/vcpkg/blob/master/ports/qt5/configure_qt.cmake#L15) for consecutive build speedup

**Comment by bagong** [comment] 2017-05-04 07:34
I like the idea of adding Webkit *as option*. I am ultimately interested in building this Webkit version (https://github.com/annulen/webkit), but I guess building the bundled one will make that easier anyways and provide helpful insights on the way. So I'll try to help soonish.

As to in source vs. patching/hardcoding, I have no informed opinion on what is better.

**Comment by bagong** [comment] 2017-05-05 08:56
@tobiaskohlbau , I am not leaving this unattended, currently trying to get Webkit build with vcpkg having @annulen 's help. I'll return here as soon as Webkit builds using vcpkg libraries (icu 4.9.1 is the problem). The webkit repo I was referring to is not a random one, it's likely the base for "webkit-ng" in Qt 5.9 or 5.10 and being developped in coordination both with core webkit and "official" Qt.

The provisional workaround to for the private headers issue with respect to webkit is just to add two entries pointing to the respective folders in just QtGui and QtCore in the respective cmake config files...

**Comment by tobiaskohlbau** [comment] 2017-05-05 12:04
I've mistaken the bugreport. Don't ask me why but I thought the trouble was produced by compiling webkit outside of qt but these problem resulted from building qt outside of the sourcecode.
I will prepare a patch to solve this. But as stated by the CONTRIBUTION Guide:

>When patches can't be avoided, do not modify the default behavior. The ideal lifecycle of a patch is to get merged upstream and no longer be needed. Try to keep this goal in mind when deciding how to patch something.

I've filled a [comment](https://bugreports.qt.io/browse/QTBUG-37417?focusedCommentId=356291&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-356291) within the bugreport. Let's see what the guys from Qt have to say about this.

**Comment by bagong** [comment] 2017-05-05 12:53
Yes, I likely mixed things a bit too much trying to demonstrate the relevance of the "bug". It's known Qt issue, but they likely don't care if somebody wants to do out of source/shadow builds. I personally hate in source builds, but I guess it's more a question of taste... ;) Looking forward to anything you may produce! And if you're still up to trying to get webkit built within this framework, I am getting close now to building webkit with annulen's help, and then it just remains a question of integrating it into this build (or a separate one if you prefer).

**Comment by bagong** [comment] 2017-05-05 14:37
A webkit teazer (webkit qt-testbrowser, qt5.8, x64-windows, all libs from this repo):

![webkit-qt5 8-github](https://cloud.githubusercontent.com/assets/1502057/25750175/2b607ef2-31b1-11e7-82d1-2c9c56e2008d.PNG)

**Comment by bagong** [comment] 2017-05-05 15:01
Thinking about in-source build: that would mean we need 2 to 6 different folders/sources for the various build-triplets, which seems not compliant with the design of vcpkg, which I like a lot, so I'd actually really prefer a patch that adds that paths post build...

**Comment by annulen** [comment] 2017-05-05 15:04
If your system is not starting each build triplet from freshly unpacked source archive, there is a problem already.

**Comment by bagong** [comment] 2017-05-05 15:34
Hmm, that would still allow for a single source directory (on my computer extracting the source alone takes about 30 mins though ;) ). But feels like you're recommending in source builds?

**Comment by bagong** [comment] 2017-05-21 12:23
My feeling is, as qt5.9 is around the corner and that's announced to become a long term release, efforts for a good vcpkg-package will focus on that version (hopefully with qtwebkit and qtwebengine options ;) )? So not much going to happen here? Maybe as a temporary fix a patch? The one attached adds all the private headers, but I am not sure if it applies in all contexts (extension changed to allow upload):

[0001-Add-private-header-paths-to-qt5-cmake-config-files.txt](https://github.com/Microsoft/vcpkg/files/1016936/0001-Add-private-header-paths-to-qt5-cmake-config-files.txt)

**Comment by bagong** [comment] 2017-05-25 11:05
I've recreated the patch to work with git and called it from the portfile. But I haven't tested it as it requires a loong build. But if somebody says this is a viable approach I'll try to make it working and do a PR:

https://github.com/bagong/vcpkg/commit/78255376a8a70d721acdde836e6841772973e113

**Comment by annulen** [comment] 2017-05-25 11:07
Patching installation artifacts is a really bad approach. In-source build of qt5 should be used instead.

**Comment by bagong** [comment] 2017-05-25 12:14
I understand your argument, but I think it is too puristic, not pragmatic. Is that switch to in-source build going to happen for 5.8? I don't think so. Should therefore builds depending on private headers fail (e.g. qtwebkit ;) )? Baad. Should the qt-webkit build write to the qt5 headers. Impossible. So this is a workaround until things get better in 5.9, and not only qtwebkit profits from it. Btw, Konstantin, the qtwebkit build doesn't generate the private header paths either. And that is the *default* build :D

**Comment by annulen** [comment] 2017-05-25 12:15
>Is that switch to in-source build going to happen for 5.8?

This change is not harder than applying patch you propose, and is a matter of package revision

**Comment by bagong** [comment] 2017-05-25 12:17
@tobiaskohlbau , do you have a take on this?

**Comment by ras0219-msft** [comment] 2017-06-01 00:44
Re: https://github.com/Microsoft/vcpkg/issues/1021#issuecomment-299114516

I've opened a PR (#1205) which would enable having an optional "webkit" component -- as well as expressing the rest of Qt as components. Please take a look and give us feedback!

**Comment by Cheney-W** [comment] 2019-02-28 07:29
@bagong , Thanks for reporting this issue. I can't reproduce it with the latest vcpkg, so I close it first.
Please open a new issue if this is still a problem for you.

**Closed by Cheney-W** 2019-02-28 07:29 UTC
