### ISSUE TITLE
[arrow] VS 16.2.x build failure?

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#7569] opened 2019-08-06 21:01 UTC
**Host Environment**
- OS: Windows
- Compiler: 16.2.1 Release VS (Community; whatever compiler number that is) 

**To Reproduce**
`./vcpkg install arrow:x64-windows`

**Failure logs** 
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.22.27905\include\list(1129): error C2280: 'std::pair<_Kty,_Ty> &std::pair<_Kty,_Ty>::operator =(volatile const std::pair<_Kty,_Ty> &)': attempting to reference a deleted function
        with
        [
            _Kty=int,
            _Ty=const parquet::schema::NodePtr
        ]

```
**Additional context**
Can somebody confirm this build error?
(Because I observed it while trying to fix regressions in PR 7524 but do not have time to investigate such build errors which seem unrelated to the PR)

**Comment by wangli28** [comment] 2019-08-07 02:05
Thanks for posting this issue. Closed as duplicate of #6497.

**Closed by wangli28** 2019-08-07 02:05 UTC
Labels: port bug
