### ISSUE TITLE
poco can't find pcre.h

### ISSUE THREAD

**Issue by Shadowrom2020** [Microsoft/vcpkg#632] opened 2017-02-04 20:25 UTC
Package: poco:x64-windows
Vcpkg version: 0.0.71-ce477bf21998c80afc551de72c6140178de3a114

poco is unable to find pcre.h, build fails.
[package-x64-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/752542/package-x64-windows-rel-out.txt)

**Comment by KindDragon** [comment] 2017-02-04 22:06
Duplicate of #475

**Comment by ras0219-msft** [comment] 2017-02-06 23:10
@Shadowrom2020 Thanks for the ping. I'll continue the investigation on the other issue.
@KindDragon Thanks for marking this as duplicate, it really helps!

**Closed by ras0219-msft** 2017-02-06 23:10 UTC
