### ISSUE TITLE
[skia] interface include path incorrect

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#28591] opened 2022-12-28 05:04 UTC
**Describe the bug**
```
    set_target_properties(unofficial::skia::skia PROPERTIES
        INTERFACE_INCLUDE_DIRECTORIES "${z_vcpkg_skia_root}/include/skia"
    )
```

It should be 
```c++
#include <skia/core/SkCanvas.h>
```
not
```c++
#include <core/SkCanvas.h>
```

**Comment by dg0yt** [comment] 2022-12-28 06:50
Do you have an official ustream reference for canonical include paths?

**Comment by xiaozhuai** [comment] 2022-12-28 07:15
> Do you have an official ustream reference for canonical include paths?

Try to find some demo code, but no results.
I think the skia prefix should be kept, otherwise it pollutes the user project's include path. User project may has a directory named `core`. It's very common isn't it ?

**Comment by dg0yt** [comment] 2022-12-28 08:32
I also searched without success when I updated skia. skia doesn't provide installation, so it is all up to the user. ATM we don't really know which files should be installed. (There is some property of public headers, but they come with non-public usage requirements.)

However, no public examples uses `skia/...`. The only occurence is vcpkg, and I even retained compatibility with this usage.

IMO there is no problem with the `core` directory where all header files are prefixed with `Sk`. (These files are probably meant to be public headers.) It might be more tricky with other directories (`modules`, `private`, `src`, `third_party`, `sksl`, `gpu`).

Everything is cleanly contained in `/include/skia`. It doesn't pollute the search path if you don't link to `unofficial::skia::skia`. If you really want to avoid the include path which comes with it, you can still setup your CMake project in a different way.

**Comment by xiaozhuai** [comment] 2022-12-28 08:47
> IMO there is no problem with the `core` directory where all header files are prefixed with `Sk`. (These files are probably meant to be public headers.) It might be more tricky with other directories (`modules`, `private`, `src`, `third_party`, `sksl`, `gpu`).

Then, why not just
```
#include <SkCanvas.h>
```

Think about if a user has a `core/Sxxxx.h`, when user type `core/S`, the ide popup many `core/Sk*`.
Keep the `skia` prefix is a good way, just need to write a few more characters to clear up the misunderstanding.

**Comment by dg0yt** [comment] 2022-12-28 09:20
> Then, why not just
> 
> ```
> #include <SkCanvas.h>
> ```

There are also other directories: `android`, ` codec`, `config`, ...
We would need to add them all to the include path.
For the ultimate answer, please ask upstream.

**Comment by Chlumsky** [comment] 2023-01-15 16:13
I also agree that this should be changed. This issue was not present prior to #28007 so it is at least a breaking change, and since other dependencies may bring the root include directory to the include path, many users probably don't even realize this change happened and their includes are wrong.

In our project, we also use a non-vcpkg Skia build for Emscripten version and we have always included it as `<skia/ ...` even before we knew vcpkg existed, so because of this, we now have this in our code, which I find terrible:

```c++
#ifdef __EMSCRIPTEN__
#include <skia/core/SkPath.h>
#include <skia/core/SkPathEffect.h>
#include <skia/core/SkColorSpace.h>
#include <skia/core/SkSurface.h>
#include <skia/core/SkCanvas.h>
#include <skia/utils/SkParsePath.h>
#include <skia/pathops/SkPathOps.h>
#include <skia/effects/SkDashPathEffect.h>
#else
#include <core/SkPath.h>
#include <core/SkPathEffect.h>
#include <core/SkColorSpace.h>
#include <core/SkSurface.h>
#include <core/SkCanvas.h>
#include <utils/SkParsePath.h>
#include <pathops/SkPathOps.h>
#include <effects/SkDashPathEffect.h>
#endif
```

I don't see any harm in providing both include paths so that users can choose whichever they like more...

**Comment by Chlumsky** [comment] 2023-01-15 16:20
> However, no public examples uses `skia/...`. The only occurence is vcpkg, and I even retained compatibility with this usage.

What do you mean you retained compatibility with this usage? It does not work anymore.

**Comment by dg0yt** [comment] 2023-01-15 17:12
> What do you mean you retained compatibility with this usage? It does not work anymore.

The files which were available with `#include <skia/...>` are still availabe in that style - provided that you use the same include dir. So you don't really need the `#ifdef / #else / #endif` but only two lines of everyday CMake.

This doesn't mean we could improve the situation with the vcpkg port. However, I still wish there was an official statement from upstream, or an reference of similar quality, before opening the next PR.

**Comment by Chlumsky** [comment] 2023-01-15 17:17
> The files which were available with `#include <skia/...>` are still availabe in that style

This is not the case. Here is a minimal test project that demonstrates this. Or perhaps you may explain what I did wrong.

[min-vcpkg-skia-test.zip](https://github.com/microsoft/vcpkg/files/10420752/min-vcpkg-skia-test.zip)

**Comment by dg0yt** [comment] 2023-01-15 17:38
I was refering to the *installed* files, and I did say you would need *two extra lines of CMake*:
~~~cmake
find_path(SKIA_INCLUDE_DIR "skia/core/SkPath.h")
target_include_directories(min-vcpkg-skia-test PRIVATE "${SKIA_INCLUDE_DIR}")
~~~
Note that the "skia" CMake config is neither official nor marked as unofficial. This issue reports a regression with regard to what was there before. We could add the old include path to `skia::skia`, but this config/target is deprecated for good reason.

**Comment by Chlumsky** [comment] 2023-01-15 20:12
Alright, thanks for that, at least I can get rid of the ifdef and even though I have no idea how it finds the right include directory, let's hope that it can't accidentally find a different installation of Skia or something.

This is a bit off-topic, but I would like to ask about the "unofficial" prefix. You're saying that the `skia::skia` target is deprecated for good reason, what reason is that? Can you explain what the goal is here? To be honest, I would really prefer having just

```cmake
find_package(skia REQUIRED)
target_link_libraries(my-project PRIVATE skia)
```

in my CMakeLists, mainly so that for example in my project, [msdfgen](https://github.com/Chlumsky/msdfgen), people aren't forced to use vcpkg to obtain Skia, but can provide another way for CMake to find it, and `unofficial::skia::skia` is vcpkg-specific. While the above works on some platforms with a warning, it does not work for example on WSL, returning this error:

```
CMake Error at /mnt/c/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake:623 (_add_library):
  _add_library cannot create ALIAS target "skia" because target
  "unofficial::skia::skia" is imported but not globally visible.
Call Stack (most recent call first):
  build/linux/vcpkg_installed/x64-linux-release/share/skia/skiaConfig.cmake:5 (add_library)
  /mnt/c/Dev/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package)
  CMakeLists.txt:3 (find_package)
```

Can this also be worked-around in CMake?

Currently, I am using

```cmake
set(MSDFGEN_SKIA_LIB skia)
if(NOT TARGET skia)
    if(MSDFGEN_USE_VCPKG)
        find_package(unofficial-skia REQUIRED)
        set(MSDFGEN_SKIA_LIB unofficial::skia::skia)
    else()
        find_package(skia REQUIRED)
    endif()
endif()
target_link_libraries(msdfgen-ext PRIVATE Threads::Threads ${MSDFGEN_SKIA_LIB})
```

Do you think that is the correct approach?

**Comment by BillyONeal** [comment] 2023-01-18 21:41
> You're saying that the `skia::skia` target is deprecated for good reason

We put "unofficial" in front of targets that vcpkg emits because we want to let the actual owners of things make their own targets that don't conflict with us.

**Closed** 2023-04-20 09:20 UTC
Labels: category:port-bug
