### ISSUE TITLE
[grpc] update to 1.46.2

### ISSUE THREAD

**Issue by 0x44449** [microsoft/vcpkg#24826] opened 2022-05-20 09:46 UTC
Library name: grpc

New version number: 1.46.2

Other information that may be useful (release notes, etc...)
grpc core updated v1.46.0
[https://github.com/grpc/grpc/releases/tag/v1.46.0](https://github.com/grpc/grpc/releases/tag/v1.46.0)

**Comment by JonLiu1993** [comment] 2022-05-20 09:55
Duplicate of #24557

**Closed by JonLiu1993** 2022-05-20 09:55 UTC
Labels: category:port-update
