### ISSUE TITLE
Error while linking unit-tests referencing boost unit_tests_framework

### ISSUE THREAD

**Issue by dimarusyy** [Microsoft/vcpkg#2442] opened 2017-12-25 12:34 UTC
Compiler : VC2017 v15.5.2
Branch : master
Boost : 1.66
Triplet : x86-windows-static, x64-windows-static

Error : 
> 3>boost_prg_exec_monitor-vc140-mt-gd-1_66.lib(cpp_main.obj) : error LNK2019: unresolved external symbol "int __cdecl cpp_main(int,char * * const)" (?cpp_main@@YAHHQAPAD@Z) referenced in function __catch$?prg_exec_monitor_main@boost@@YAHP6AHHQAPAD@ZH0@Z$1

Might be related to : [#2057](https://github.com/Microsoft/vcpkg/issues/2057)

**Comment by ras0219-msft** [comment] 2018-01-03 23:42
Duplicate of #2444. Thanks for reporting!

**Closed by ras0219-msft** 2018-01-03 23:42 UTC

**Comment by ras0219-msft** [comment] 2018-01-04 01:46
This should be fixed in master!
