### ISSUE TITLE
[libtorch] update to 2.1.1

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#35163] opened 2023-11-17 03:19 UTC
### Library name

libtorch

### New version number

2.1.1

### Other information that may be useful (release notes, etc...)

https://github.com/pytorch/pytorch
https://pytorch.org/get-started/locally/

**Comment by Neumann-A** [comment] 2023-11-20 08:43
An overlay for 2.1.0 can be found here https://github.com/Neumann-A/my-vcpkg-ports/tree/master/libtorch 
It is probably possible to simply update it to 2.1.1

**Comment by LilyWangLL** [comment] 2024-01-03 06:03
Closed as duplicate of #30224.

**Closed by LilyWangLL** 2024-01-03 06:03 UTC
Labels: category:port-update
