### ISSUE TITLE
[tensorflow] Build error

### ISSUE THREAD

**Issue by KirkPen** [microsoft/vcpkg#29797] opened 2023-02-22 18:25 UTC
Package: tensorflow[core]:x64-windows -> 2.10.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.35.32215.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: 703a8113f 2023-02-21 (23 hours ago)

**To Reproduce**

`vcpkg install tensorflow`

**Failure logs**

```
-- Using cached msys-unzip-6.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-libbz2-1.0.8-3-x86_64.pkg.tar.zst.
-- Using cached msys-patch-2.7.6-1-x86_64.pkg.tar.xz.
-- Using cached msys-gzip-1.11-1-x86_64.pkg.tar.zst.
-- Using cached msys-bash-5.1.008-1-x86_64.pkg.tar.zst.
-- Using cached msys-diffutils-3.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-coreutils-8.32-2-x86_64.pkg.tar.zst.
-- Using cached msys-grep-3.0-2-x86_64.pkg.tar.xz.
-- Using cached msys-sed-4.8-2-x86_64.pkg.tar.zst.
-- Using cached msys-libpcre-8.45-1-x86_64.pkg.tar.zst.
-- Using cached msys-gawk-5.1.0-2-x86_64.pkg.tar.zst.
-- Using cached msys-mpfr-4.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys-gmp-6.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys-libreadline-8.1.001-1-x86_64.pkg.tar.zst.
-- Using cached msys-ncurses-6.2-2-x86_64.pkg.tar.zst.
-- Using cached msys-pkg-config-0.29.2-4-x86_64.pkg.tar.zst.
-- Using cached msys-make-4.3-3-x86_64.pkg.tar.zst.
-- Using cached msys-libintl-0.21-1-x86_64.pkg.tar.zst.
-- Using cached msys-libiconv-1.16-2-x86_64.pkg.tar.zst.
-- Using cached msys-gcc-libs-11.2.0-3-x86_64.pkg.tar.zst.
-- Using cached msys-msys2-runtime-3.2.0-8-x86_64.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-python-numpy-1.20.3-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-openblas-0.3.19-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-gcc-libgfortran-11.2.0-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-python-3.8.9-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-bzip2-1.0.8-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-mpdecimal-2.5.1-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-ncurses-6.3-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-libsystre-1.0.1-4-any.pkg.tar.xz.
-- Using cached msys-mingw-w64-x86_64-libtre-git-r128.6fb7206-2-any.pkg.tar.xz.
-- Using cached msys-mingw-w64-x86_64-openssl-1.1.1.m-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-ca-certificates-20210119-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-p11-kit-0.24.1-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-libtasn1-4.18.0-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-sqlite3-3.37.2-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-readline-8.1.001-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-termcap-1.3.1-6-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-tk-8.6.11.1-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-tcl-8.6.11-5-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-xz-5.2.5-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-gettext-0.21-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-gcc-libs-11.2.0-8-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-mpc-1.2.1-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-mpfr-4.1.0-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-gmp-6.2.1-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-expat-2.4.4-1-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-libffi-3.3-4-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-libiconv-1.16-2-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-zlib-1.2.11-9-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-x86_64-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at D:/Dev/vcpkg/downloads/tools/msys2/70289b324bc026d6
-- Using cached tensorflow-tensorflow-v2.10.0.tar.gz.
-- Extracting source D:/Dev/vcpkg/downloads/tensorflow-tensorflow-v2.10.0.tar.gz
-- Applying patch D:/Dev/vcpkg/installed/x64-windows/share/tensorflow-common/fix-build-error.patch
-- Applying patch D:/Dev/vcpkg/installed/x64-windows/share/tensorflow-common/fix-windows-build.patch
-- Using source at D:/Dev/vcpkg/buildtrees/tensorflow/src/v2.10.0-257b67b673.clean
-- Configuring TensorFlow (dbg)
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/Dev/vcpkg/downloads/tools/msys2/70289b324bc026d6/mingw64/bin/python3.exe D:/Dev/vcpkg/buildtrees/tensorflow/x64-windows-dbg/configure.py --workspace D:/Dev/vcpkg/buildtrees/tensorflow/x64-windows-dbg
    Working Directory: D:/Dev/vcpkg/buildtrees/tensorflow/x64-windows-dbg
    Error code: 1
    See logs for more information:
      D:\Dev\vcpkg\buildtrees\tensorflow\config-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/tensorflow-common/tensorflow-common.cmake:187 (vcpkg_execute_required_process)
  ports/tensorflow/portfile.cmake:5 (include)
  scripts/ports.cmake:147 (include)



```
<details><summary>D:\Dev\vcpkg\buildtrees\tensorflow\config-x64-windows-dbg-out.log</summary>

```
Cannot find bazel. Please install bazel/bazelisk.
```
</details>

**Additional context**

**Comment by MonicaLiu0311** [comment] 2023-02-23 09:02
Duplicate of #27474.

**Closed by MonicaLiu0311** 2023-02-23 09:02 UTC
Labels: category:port-bug
