### ISSUE TITLE
[mpg123] Build error

### ISSUE THREAD

**Issue by Brambor** [microsoft/vcpkg#33638] opened 2023-09-07 14:55 UTC
```
Build started...
1>------ Skipped Build: Project: flatbuffers, Configuration: Release x64 ------
1>Project not selected to build for this solution configuration 
2>------ Build started: Project: Cataclysm-lib-vcpkg-static, Configuration: Release x64 ------
2>Generating "version.h"...
2>VERSION defined as "0.C-79156-g7e105d418e-dirty"
2>Installing vcpkg dependencies to D:\GitHub\Cataclysm-DDA\msvc-full-features\vcpkg_installed\x64-windows-static\
2>"C:\dev\vcpkg\vcpkg.exe" install "--host-triplet=x64-windows-static" --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "C:\dev\vcpkg\\" "--x-manifest-root=D:\GitHub\Cataclysm-DDA\msvc-full-features\\" "--x-install-root=D:\GitHub\Cataclysm-DDA\msvc-full-features\vcpkg_installed\x64-windows-static\\" --clean-after-build
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : warning: Embedding `vcpkg-configuration` in a manifest file is an EXPERIMENTAL feature.
2>Detecting compiler hash for triplet x64-windows-static...
2>The following packages will be built and installed:
2>  * brotli[core]:x64-windows-static -> 1.0.9#4
2>  * bzip2[core,tool]:x64-windows-static -> 1.0.8#3
2>  * freetype[brotli,bzip2,core,png,zlib]:x64-windows-static -> 2.12.1#3
2>  * libflac[core]:x64-windows-static -> 1.3.4#1
2>  * libmodplug[core]:x64-windows-static -> 0.8.9.0#10
2>  * libogg[core]:x64-windows-static -> 1.3.5#1
2>  * mpg123[core]:x64-windows-static -> 1.29.3
2>    sdl2-mixer[core,libflac,libmodplug,mpg123,nativemidi]:x64-windows-static -> 2.6.1#2
2>    sdl2-ttf[core]:x64-windows-static -> 2.20.0
2>Additional packages (*) will be modified to complete this operation.
2>Restored 0 package(s) from C:\Users\Tonda\AppData\Local\vcpkg\archives in 2.965 ms. Use --debug to see more details.
2>Installing 1/9 mpg123:x64-windows-static...
2>Building mpg123[core]:x64-windows-static...
2>-- Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=cfhcable;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=pilotfiber;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=gigenet;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=versaweb;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=ayera;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=netactuate;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=phoenixnap;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=astuteinternet;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=freefr;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=netcologne;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=deac-riga;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=excellmedia;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=iweb;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=jaist;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=jztkft;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=managedway;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=nchc;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=netix;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=ufpr;https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=tenet -> mpg123-1.29.3.tar.bz2...
2>[DEBUG] To include the environment variables in debug output, pass --debug-env
2>[DEBUG] Feature flag 'binarycaching' unset
2>[DEBUG] Feature flag 'compilertracking' unset
2>[DEBUG] Feature flag 'registries' unset
2>[DEBUG] Feature flag 'versions' unset
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=cfhcable
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=pilotfiber
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=gigenet
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=versaweb
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=ayera
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=netactuate
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=phoenixnap
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=astuteinternet
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=freefr
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=netcologne
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=deac-riga
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=excellmedia
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=iweb
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=jaist
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=jztkft
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=managedway
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=nchc
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=netix
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=ufpr
2>Downloading https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=tenet
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: Failed to download from mirror set
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=cfhcable
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=pilotfiber
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=gigenet
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=versaweb
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=ayera
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=netactuate
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=phoenixnap
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=astuteinternet
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=freefr
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=netcologne
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=deac-riga
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=excellmedia
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=iweb
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=jaist
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=jztkft
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=managedway
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=nchc
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=netix
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=ufpr
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: File does not have the expected hash:
2>url: https://sourceforge.net/projects/mpg123/files/mpg123/1.29.3/mpg123-1.29.3.tar.bz2/download?use_mirror=tenet
2>File: C:\dev\vcpkg\downloads\mpg123-1.29.3.tar.bz2.14112.part
2>Expected hash: 0d8db63f9bae1507887bc5241a56abccfeb767b7ba8362eb0fce9de2f63369e57fdd6f25a953f8ef5f9ead4f400237db51914816e278566fdf8e6f205ebca5d6
2>Actual hash: c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e
2>[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956):
2>[DEBUG] Time in subprocesses: 0 us
2>[DEBUG] Time in parsing JSON: 12 us
2>[DEBUG] Time in JSON reader: 0 us
2>[DEBUG] Time in filesystem: 9785 us
2>[DEBUG] Time in loading ports: 0 us
2>[DEBUG] Exiting after 2.296 s (2295678 us)
2>
2>CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
2>
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning :       Failed to download file with error: 1
2>      If you use a proxy, please check your proxy setting. Possible causes are:
2>
2>      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
2>         to `https://address:port`. This is not correct, because `https://` prefix
2>         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
2>         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
2>         HTTP_PROXY and HTTPS_PROXY instead.
2>
2>      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
2>         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
2>         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
2>         Change `http=address:port;https=address:port` to `address`, and fill the port number.
2>
2>      3. Your proxy's remote server is out of service.
2>
2>      In future vcpkg releases, if you are using Windows, you no longer need to set
2>      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
2>      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
2>      and (https://github.com/microsoft/vcpkg-tool/pull/77)
2>
2>      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues
2>
2>Call Stack (most recent call first):
2>  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
2>  scripts/cmake/vcpkg_from_sourceforge.cmake:83 (vcpkg_download_distfile)
2>  ports/mpg123/portfile.cmake:3 (vcpkg_from_sourceforge)
2>  scripts/ports.cmake:147 (include)
2>
2>
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: building mpg123:x64-windows-static failed with: BUILD_FAILED
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): warning : error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
2>Then check for known issues at:
2>    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+mpg123
2>You can submit a new issue at:
2>    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[mpg123]+Build+error
2>Include '[mpg123] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
2>    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
2>    vcpkg-scripts version: 0d239eb4d 2023-01-04 (8 months ago)
2>
2>
2>Please use the prefilled template from D:\GitHub\Cataclysm-DDA\msvc-full-features\vcpkg_installed\x64-windows-static\vcpkg\issue_body.md when reporting your issue.
2>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(161,5): error MSB3073: The command ""C:\dev\vcpkg\vcpkg.exe" install "--host-triplet=x64-windows-static" --x-wait-for-lock --triplet "x64-windows-static" --vcpkg-root "C:\dev\vcpkg\\" "--x-manifest-root=D:\GitHub\Cataclysm-DDA\msvc-full-features\\" "--x-install-root=D:\GitHub\Cataclysm-DDA\msvc-full-features\vcpkg_installed\x64-windows-static\\" --clean-after-build" exited with code 1.
2>Done building project "Cataclysm-lib-vcpkg-static.vcxproj" -- FAILED.
3>------ Skipped Build: Project: JsonFormatter-lib-vcpkg-static, Configuration: Release x64 ------
3>Project not selected to build for this solution configuration 
4>------ Build started: Project: Cataclysm-vcpkg-static, Configuration: Release x64 ------
5>------ Skipped Build: Project: Cataclysm-test-vcpkg-static, Configuration: Release x64 ------
5>Project not selected to build for this solution configuration 
6>------ Skipped Build: Project: JsonFormatter-vcpkg-static, Configuration: Release x64 ------
6>Project not selected to build for this solution configuration 
4>stdafx.cpp
4>D:\GitHub\Cataclysm-DDA\msvc-full-features\stdafx.h(81,16): fatal error C1083: Cannot open include file: 'SDL2/SDL_ttf.h': No such file or directory
4>messages.cpp
4>main.cpp
4>Done building project "Cataclysm-vcpkg-static.vcxproj" -- FAILED.
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 4 skipped ==========
```

**Comment by MonicaLiu0311** [comment] 2023-09-08 02:37
Duplicate of #33631.

Already fixed by sourceforge.net.

**Closed by MonicaLiu0311** 2023-09-08 02:37 UTC
Labels: category:question
