### ISSUE TITLE
[libtorch] update to <2.0.1>

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#31601] opened 2023-05-24 08:05 UTC
### Library name

libtorch

### New version number

2.0.1

### Other information that may be useful (release notes, etc...)

https://pytorch.org/get-started/locally/

**Comment by russelltg** [comment] 2023-05-31 19:19
Related to #30224

**Comment by LilyWangLL** [comment] 2023-06-01 09:11
Closed as duplicate of #30224.

**Closed by LilyWangLL** 2023-06-01 09:11 UTC
Labels: category:port-update

**Comment by WangHHY19931001** [comment] 2023-07-06 01:44
can u push a plat for this?
