### ISSUE TITLE
x64-windows debug build can't find zlib dll when using openvdb

### ISSUE THREAD

**Issue by tesfabpel** [microsoft/vcpkg#3601] opened 2018-05-28 15:20 UTC
I've installed openvdb:x64-windows (VS2017) and tried to run this code in Debug x64:

```
#include <openvdb/openvdb.h>

int main()
{
openvdb::initialize();
return 0;
}
```
When running, it says that it can't find `zlib1.dll`, `lz4.dll`, `snappy.dll`, and `zstd.dll`...

But if I try to run this code:
```
#include <zlib.h>

int main()
{
printf("%s", zlibVersion());
return 0;
}
```
it works...

These are the files present in `x64\Debug`:
```
blosc.dll
Half.dll
openvdb.dll
tbb_debug.dll
zlibd1.dll
```

vcpkg version 0.0.113-nohash
zlib 1.2.11-3
openvdb 5.0.0-1

**Comment by marsermd** [comment] 2018-09-03 09:40
Hi! 
I am having the exact same troubles. It seems that somewhere along the way debug and release libs got mixed up and hence the missing dll.

I'll keep you posted.

**Comment by JackBoosY** [comment] 2019-03-25 03:09
When I installed openvdb:x86-windows, there will be no problem using openvdb:x64-windows. So I guess this is a dependency bug.

**Comment by JackBoosY** [comment] 2019-04-22 08:14
Hi @tesfabpel, this issue should be fixed when openvdb is updated.
Can you repro it in latest version?
Thanks.

**Comment by NancyLi1013** [comment] 2019-12-19 09:54
Hi @tesfabpel  and @marsermd thanks for posting this issue.
`Openvdb `has been updated. I try to build it on my local and cannot reproduce this issue now.
Could you please try to update vcpkg and rebuild it?

**Comment by NancyLi1013** [comment] 2020-01-22 06:25
Please feel free to reopen this or open an issue if this is still problem for you.

**Closed by NancyLi1013** 2020-01-22 06:25 UTC
Labels: port bug
