### ISSUE TITLE
[<port name>] build failure

### ISSUE THREAD

**Issue by l8513454** [microsoft/vcpkg#42107] opened 2024-11-11 13:17 UTC
### Operating system

windows

### Compiler

msvc

### Steps to reproduce the behavior

```Shell
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
1> [CMake]     Command failed: F:/VS2022-Project/KICAD/vcpkg/downloads/tools/python/python-3.12.7-x64/python.exe F:/VS2022-Project/KICAD/vcpkg/buildtrees/wxpython/src/8854625dd8-861bd167bd.clean/public/get-pip.py --no-warn-script-location
1> [CMake]     Working Directory: F:/VS2022-Project/KICAD/vcpkg/buildtrees/wxpython
1> [CMake]     Error code: 1
1> [CMake]     See logs for more information:
1> [CMake]       F:\VS2022-Project\KICAD\vcpkg\buildtrees\wxpython\get-pip-x64-windows-err.log
1> [CMake] 
1> [CMake] Call Stack (most recent call first):
1> [CMake]   F:/VS2022-Project/KICAD/Kicad/build/x64-Debug/vcpkg_installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:48 (vcpkg_execute_required_process)
1> [CMake]   C:/Users/Administrator/AppData/Local/vcpkg/registries/git-trees/feabd68376664732bb0ae763c33daaf3a2427ac5/portfile.cmake:35 (x_vcpkg_get_python_packages)
1> [CMake]   scripts/ports.cmake:192 (include)
1> [CMake] error: 生成 wxpython:x64-windows 失败，结果为: BUILD_FAILED
```

### Failure logs

Traceback (most recent call last):
File "F:\VS2022-Project\KICAD\vcpkg\buildtrees\wxpython\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 33324, in
main()
File "F:\VS2022-Project\KICAD\vcpkg\buildtrees\wxpython\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 135, in main
bootstrap(tmpdir=tmpdir)
File "F:\VS2022-Project\KICAD\vcpkg\buildtrees\wxpython\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 111, in bootstrap
monkeypatch_for_cert(tmpdir)
File "F:\VS2022-Project\KICAD\vcpkg\buildtrees\wxpython\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 92, in monkeypatch_for_cert
from pip.internal.commands.install import InstallCommand
File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip_internal\commands_init.py", line 9, in
File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip_internal\cli\base_command.py", line 15, in
File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip_internal\cli\cmdoptions.py", line 23, in
File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip_internal\cli\parser.py", line 12, in
File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip_internal\configuration.py", line 26, in
File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip_internal\utils\logging.py", line 27, in
File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip_internal\utils\misc.py", line 39, in
File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip_internal\locations_init_.py", line 14, in
File "C:\Users\Administrator\AppData\Local\Temp\tmp1gm4sd6c\pip.zip\pip_internal\locations_distutils.py", line 9, in
ModuleNotFoundError: No module named 'distutils'

### Additional context

my python3.10:import distutils no wrong
my python3.12:import distutils ;No module named 'distutils'

**Comment by jimwang118** [comment] 2024-11-12 10:02
Duplicate of https://github.com/microsoft/vcpkg/issues/42021.

**Closed by jimwang118** 2024-11-12 10:02 UTC
Labels: category:port-bug
