### ISSUE TITLE
Fail to compile qt5:x64-windows with vcpkg

### ISSUE THREAD

**Issue by djryan7hotmailcom** [Microsoft/vcpkg#1228] opened 2017-06-06 18:16 UTC
[build-x64-windows-rel-err.txt](https://github.com/Microsoft/vcpkg/files/1056014/build-x64-windows-rel-err.txt)
[build-x64-windows-rel-out.txt](https://github.com/Microsoft/vcpkg/files/1056013/build-x64-windows-rel-out.txt)

PS C:\Users\djrya\Documents\GitHub\vcpkg> .\vcpkg install qt5:x64-windows
The following packages will be built and installed:
    qt5:x64-windows
Building package qt5:x64-windows...
-- CURRENT_INSTALLED_DIR=C:/Users/djrya/Documents/GitHub/vcpkg/installed/x64-windows
-- DOWNLOADS=C:/Users/djrya/Documents/GitHub/vcpkg/downloads
-- CURRENT_PACKAGES_DIR=C:/Users/djrya/Documents/GitHub/vcpkg/packages/qt5_x64-windows
-- CURRENT_BUILDTREES_DIR=C:/Users/djrya/Documents/GitHub/vcpkg/buildtrees/qt5
-- CURRENT_PORT_DIR=C:/Users/djrya/Documents/GitHub/vcpkg/ports/qt5/.
-- Using cached C:/Users/djrya/Documents/GitHub/vcpkg/downloads/qt-5.8.0.7z
-- Testing integrity of cached file...
-- Testing integrity of cached file... OK
-- Extracting done
-- Applying patch C:/Users/djrya/Documents/GitHub/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/djrya/Documents/GitHub/vcpkg/ports/qt5/fix-qalgorithms-vs2017.patch done
-- Applying patch C:/Users/djrya/Documents/GitHub/vcpkg/ports/qt5/fix-commandline-overrides.patch
-- Applying patch failed. This is expected if this patch was previously applied.
-- Applying patch C:/Users/djrya/Documents/GitHub/vcpkg/ports/qt5/fix-commandline-overrides.patch done
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package x64-windows-rel
CMake Error at C:/Users/djrya/Documents/GitHub/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:43 (message):
    Command failed: C:/Users/djrya/Documents/GitHub/vcpkg/downloads/tools/jom/jom-1.1.2/jom.exe;/J;8
    Working Directory: C:/Users/djrya/Documents/GitHub/vcpkg/buildtrees/qt5/x64-windows-rel
    See logs for more information:
      C:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\build-x64-windows-rel-out.log
      C:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\build-x64-windows-rel-err.log

Call Stack (most recent call first):
  C:/Users/djrya/Documents/GitHub/vcpkg/ports/qt5/install_qt.cmake:19 (vcpkg_execute_required_process)
  C:/Users/djrya/Documents/GitHub/vcpkg/ports/qt5/portfile.cmake:57 (install_qt)
  C:/Users/djrya/Documents/GitHub/vcpkg/scripts/ports.cmake:73 (include)

Error: Building package qt5:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5:x64-windows
  Vcpkg version: 0.0.81-e66d5f46c7ebf247ec350b19989adba3de7deaec

Additionally, attach any relevant sections from the log files above.
PS C:\Users\djrya\Documents\GitHub\vcpkg> .\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
PS C:\Users\djrya\Documents\GitHub\vcpkg> git pull
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 8 (delta 5), reused 8 (delta 5), pack-reused 0
Unpacking objects: 100% (8/8), done.
From https://github.com/Microsoft/vcpkg
 * [new branch]      dev/roschuma/docs -> origin/dev/roschuma/docs
Already up-to-date.

**Comment by ras0219-msft** [comment] 2017-06-06 18:19
Hi @djryan7hotmailcom, could you attach the log files to your post?

> buildtrees\qt5\build-x64-windows-rel-out.log
> buildtrees\qt5\build-x64-windows-rel-err.log

**Comment by ras0219-msft** [comment] 2017-06-06 18:26
From the logs:

>cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -O2 -MD -MP -W3 -w44456 -w44457 -w44458 -DUNICODE -DWIN32 -DWIN64 -DQT_NO_EXCEPTIONS -DQT_NO_DEBUG -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DNDEBUG -D_WINDLL -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\plugins\imageformats\webp -I. -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp\src -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp\src\dec -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp\src\enc -IC:/Users/djrya/Documents/GitHub/vcpkg/buildtrees/qt5/src/qt-5.8.0/qtimageformats/src/3rdparty/libwebp/src/extra -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp\src\dsp -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp\src\mux -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp\src\utils -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp\src\webp -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\include -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\include\QtGui -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\x64-windows-rel\qtbase\include -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\x64-windows-rel\qtbase\include\QtGui -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\include\QtCore -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\x64-windows-rel\qtbase\include\QtCore -I.moc\release -IC:\Users\djrya\Documents\GitHub\vcpkg\installed\x64-windows\include -IC:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtbase\mkspecs\win32-msvc2017 -Fo.obj\release\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp\src\dsp\alpha_processing_mips_dsp_r2.obj C:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp\src\dsp\alpha_processing_mips_dsp_r2.c

>C:\Users\djrya\Documents\GitHub\vcpkg\buildtrees\qt5\src\qt-5.8.0\qtimageformats\src\3rdparty\libwebp\src\dsp\alpha_processing_mips_dsp_r2.c : fatal error C1083: Cannot open compiler generated file: '': Invalid argument

It looks like you are probably hitting https://github.com/Microsoft/vcpkg/issues/426, which appears to be caused by max path limitations.

Could you move your vcpkg enlistment to a shorter name (less than 36 characters) and try again?

**Comment by djryan7hotmailcom** [comment] 2017-06-06 18:45
Thanks for the update, yes I’ll move my environment.

Dave

**Comment by djryan7hotmailcom** [comment] 2017-06-06 21:02
Robert,

Qt5 now compiles but my end goal was vtk however I get the following errors when I do

.\vcpkg install vtk:x64-windows

LINK : fatal error LNK1181: cannot open input file 'hdf5-shared.lib'
LINK failed. with 1181

**Comment by jasjuang** [comment] 2017-06-12 16:52
@djryan7hotmailcom See #739 to solve the hdf5 problem.

**Comment by NancyLi1013** [comment] 2019-02-21 09:57
Hi @djryan7hotmailcom, does this issue repro on your machine now?

**Comment by NancyLi1013** [comment] 2019-04-01 07:00
Hi @djryan7hotmailcom ,thanks for posting this issue. This issue should be fixed now. I can install it successfully on my machine. Please try it again. If there is any problem about this, you can reopen it or open a new issue.

**Closed by NancyLi1013** 2019-04-01 07:00 UTC
Labels: port bug
