### ISSUE TITLE
[spdlog] build+link failure

### ISSUE THREAD

**Issue by KRJackLee** [microsoft/vcpkg#28019] opened 2022-11-26 09:52 UTC
**Host Environment**

- OS: win10
- Compiler: msvc from vs 2019

**To Reproduce**

Steps to reproduce the behavior (I made `vcpkg` global and run on VS Developer Prompt):

`vcpkg install spdlog`
`cmake .`
`nmake`

**Failure logs**

- Loaded 'D:\...\C++\cpp\build\main.exe'. Symbols loaded.
Loaded 'C:\Windows\SysWOW64\ntdll.dll'. 
Loaded 'C:\Windows\SysWOW64\kernel32.dll'. 
Loaded 'C:\Windows\SysWOW64\KernelBase.dll'. 
Loaded 'C:\Windows\SysWOW64\apphelp.dll'. 
Loaded 'C:\Windows\SysWOW64\vcruntime140d.dll'. 
Loaded 'C:\Windows\SysWOW64\msvcp140d.dll'. 
2
Loaded 'C:\Windows\SysWOW64\ucrtbased.dll'. 
Unloaded 'C:\Windows\SysWOW64\ucrtbased.dll'.
The program '[8656] main.exe' has exited with code -1073741515 (0xc0000135).
- Build seems fine but run .exe nor debugging is bugged.

**Additional context**

`main.cpp`
```
#include <iostream>
#include "spdlog/spdlog.h"


using std::cout, std::endl;


int main() 
{
    spdlog::info("Welcome to spdlog!");
    spdlog::error("Some error message with arg: {}", 1);
    
    spdlog::warn("Easy padding in numbers like {:08d}", 12);
    spdlog::critical("Support for int: {0:d};  hex: {0:x};  oct: {0:o}; bin: {0:b}", 42);
    spdlog::info("Support for floats {:03.2f}", 1.23456);
    spdlog::info("Positional args are {1} {0}..", "too", "supported");
    spdlog::info("{:<30}", "left aligned");
    
    spdlog::set_level(spdlog::level::debug); // Set global log level to debug
    spdlog::debug("This message should be displayed..");    
    
    // change log pattern
    spdlog::set_pattern("[%H:%M:%S %z] [%n] [%^---%L---%$] [thread %t] %v");
    
    // Compile time log levels
    // define SPDLOG_ACTIVE_LEVEL to desired level
    SPDLOG_TRACE("Some trace message with param {}", 42);
    SPDLOG_DEBUG("Some debug message");
}
```

`CMakeLists.txt` (Such file works in linking other vcpkg-installed packages such as Matplot++)
```
cmake_minimum_required(VERSION 3.22)
project(main)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_PREFIX_PATH "C:/Program Files/vcpkg/installed/x86-windows/share")

include_directories("C:/Program Files/vcpkg/installed/x86-windows/include")
link_directories("C:/Program Files/vcpkg/installed/x86-windows/lib")

add_executable(${PROJECT_NAME} main.cpp)

find_package(spdlog CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE spdlog::spdlog)
```

**Comment by MonicaLiu0311** [comment] 2022-11-28 10:33
I can't reproduce it, can you please provide detailed logs?

**Comment by MonicaLiu0311** [comment] 2022-11-29 08:10
I used your file to build successfully, the steps are as follows:

Directory: `E:\tests_pdlog\`
----build\
----main.cpp
----CMakeLists.txt

1) PS E:\vcpkg> ./vcpkg install spdlog:x64-windows
```
    # this is heuristically generated, and may not be correct
    find_package(spdlog CONFIG REQUIRED)
    target_link_libraries(main PRIVATE spdlog::spdlog spdlog::spdlog_header_only)
```

2) E:\test_spdlog\build>cmake .. -G "Visual Studio 16 2019" "-DCMAKE_TOOLCHAIN_FILE=E:\vcpkg\scripts\buildsystems\vcpkg.cmake"
```
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19045.
-- The C compiler identification is MSVC 19.29.30147.0
-- The CXX compiler identification is MSVC 19.29.30147.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: E:/test_spdlog/build
```

3) E:\test_spdlog\build>cmake --build .
```
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  Checking Build System
  Building Custom Rule E:/test_spdlog/CMakeLists.txt
  main.cpp
  main.vcxproj -> E:\test_spdlog\build\Debug\main.exe
  Building Custom Rule E:/test_spdlog/CMakeLists.txt
```
[CMakeLists.txt](https://github.com/microsoft/vcpkg/files/10111011/CMakeLists.txt)
[main.txt](https://github.com/microsoft/vcpkg/files/10111013/main.txt)

**Comment by MonicaLiu0311** [comment] 2022-11-29 08:22
> nmake

`nmake` needs `MAKEFILE`, you are using `CMakelists.txt`.

> target_link_libraries(${PROJECT_NAME} PRIVATE spdlog::spdlog)

Please follow the usage suggested by vcpkg, which should be: `target_link_libraries(main PRIVATE spdlog::spdlog spdlog::spdlog_header_only)`

> set(CMAKE_PREFIX_PATH "C:/Program Files/vcpkg/installed/x86-windows/share")
include_directories("C:/Program Files/vcpkg/installed/x86-windows/include")
link_directories("C:/Program Files/vcpkg/installed/x86-windows/lib")

Just specify TOOLCHAIN_FILE, do not specify the header file path, vcpkg has already been set internally.
`"-DCMAKE_TOOLCHAIN_FILE=E:\vcpkg\scripts\buildsystems\vcpkg.cmake"`
(use `./vcpkg integrate install` to get TOOLCHAIN_FILE)

**Comment by dg0yt** [comment] 2022-11-29 09:26
> > nmake
> 
> `nmake` needs `MAKEFILE`, you are using `CMakelists.txt`.

Cmake has a generator for nmake makefiles. But we would recommend ninja or another generator instead.

**Comment by KRJackLee** [comment] 2022-11-29 15:03
> > nmake
> 
> `nmake` needs `MAKEFILE`, you are using `CMakelists.txt`.
> 
> > target_link_libraries(${PROJECT_NAME} PRIVATE spdlog::spdlog)
> 
> Please follow the usage suggested by vcpkg, which should be: `target_link_libraries(main PRIVATE spdlog::spdlog spdlog::spdlog_header_only)`
> 
> > set(CMAKE_PREFIX_PATH "C:/Program Files/vcpkg/installed/x86-windows/share")
> > include_directories("C:/Program Files/vcpkg/installed/x86-windows/include")
> > link_directories("C:/Program Files/vcpkg/installed/x86-windows/lib")
> 
> Just specify TOOLCHAIN_FILE, do not specify the header file path, vcpkg has already been set internally. `"-DCMAKE_TOOLCHAIN_FILE=E:\vcpkg\scripts\buildsystems\vcpkg.cmake"` (use `./vcpkg integrate install` to get TOOLCHAIN_FILE)

I've modified my CMakeLists.txt but the problem persists. I am missing a few details in steps to reproduce, so allow me to edit. In `cmake` I've made the args for `generator` a global varaible:

To Reproduce:
`vcpkg install spdlog`
`vcpkg integrate install`
`cmake -G "NMake Makefiles"`
`nmake`

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.22)
project(main)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_TOOLCHAIN_FILE "C:/Program Files/vcpkg/scripts/buildsystems/vcpkg.cmake")

add_executable(${PROJECT_NAME} main.cpp)

find_package(spdlog CONFIG REQUIRED)

if(NOT spdlog_FOUND)
    message(WARNING "spdlog not found!")
else()
    message(STATUS "Found spdlog on: " ${spdlog_DIR})
endif(NOT spdlog_FOUND)

target_link_libraries(${PROJECT_NAME} PRIVATE spdlog::spdlog spdlog::spdlog_header_only)
```

Log (from CMake Tool from vscode)
```
[main] Configuring folder: cpp 
[proc] Executing command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug "-Sd:/Study/Computer Programming/C++/cpp" "-Bd:/Study/Computer Programming/C++/cpp/build" -G "NMake Makefiles"
[cmake] Not searching for unused variables given on the command line.
[cmake] CMake Error at CMakeLists.txt:9 (find_package):
[cmake]   Could not find a package configuration file provided by "spdlog" with any
[cmake]   of the following names:
[cmake] 
[cmake]     spdlogConfig.cmake
[cmake]     spdlog-config.cmake
[cmake] 
[cmake]   Add the installation prefix of "spdlog" to CMAKE_PREFIX_PATH or set
[cmake]   "spdlog_DIR" to a directory containing one of the above files.  If "spdlog"
[cmake]   provides a separate development package or SDK, be sure it has been
[cmake]   installed.
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!
[cmake] See also "D:/Study/Computer Programming/C++/cpp/build/CMakeFiles/CMakeOutput.log".
[proc] The command: "C:\Program Files\CMake\bin\cmake.EXE" --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug "-Sd:/Study/Computer Programming/C++/cpp" "-Bd:/Study/Computer Programming/C++/cpp/build" -G "NMake Makefiles" exited with code: 1 and signal: null
```

What am I missing now?

**Comment by KRJackLee** [comment] 2022-11-29 23:43
> > > nmake
> > 
> > 
> > `nmake` needs `MAKEFILE`, you are using `CMakelists.txt`.
> 
> Cmake has a generator for nmake makefiles. But we would recommend ninja or another generator instead.

I am using `nmake` from my experience from Mingw with `make`, and VS installation of C++ support provide an `nmake.exe` as default. Will get in touch with `ninja` sometime. Thx for the advice.

**Comment by dg0yt** [comment] 2022-11-30 03:09
Note that nmake does not support parallel jobs by itself. This can be a huge disadvantage for some setups.
In any case, with cmake, the makefiles are genereated, and you don't have to know how to run the actual build. You can just run `cmake --build .`

**Comment by MonicaLiu0311** [comment] 2022-11-30 06:43
Here are two suggestions, check each and try: (I also built successfully with your new reproduction steps)

1) 
> To Reproduce:
vcpkg install spdlog
vcpkg integrate install
cmake -G "NMake Makefiles"
nmake

vcpkg installs x86-windows by default, if the project you build is x64, please also run `./vcpkg install spdlog:x64-windows`

2) 
> cmake -G "NMake Makefiles"
Please run:
cmake .. -G "NMake Makefiles" "-DCMAKE_TOOLCHAIN_FILE=E:\vcpkg\scripts\buildsystems\vcpkg.cmake"

**Comment by MonicaLiu0311** [comment] 2022-11-30 06:48
For details, refer to [quick-start-windows](https://github.com/microsoft/vcpkg#quick-start-windows) of vcpkg.

**Comment by MonicaLiu0311** [comment] 2022-11-30 09:56
> cmake_minimum_required(VERSION 3.22)
project(main)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_TOOLCHAIN_FILE "C:/Program Files/vcpkg/scripts/buildsystems/vcpkg.cmake")

I think I found the reason, because of scope, if you want to specify `TOOLCHAIN_FILE` in `CMakeList.txt`, then you must put `set(CMAKE_TOOLCHAIN_FILE)` in front of `project(main)`.
```
cmake_minimum_required(VERSION 3.22)
set(CMAKE_TOOLCHAIN_FILE "C:/Program Files/vcpkg/scripts/buildsystems/vcpkg.cmake")
project(main)
set(CMAKE_CXX_STANDARD 17)
```

**Comment by KRJackLee** [comment] 2022-11-30 13:59
> > cmake_minimum_required(VERSION 3.22)
> > project(main)
> > set(CMAKE_CXX_STANDARD 17)
> > set(CMAKE_TOOLCHAIN_FILE "C:/Program Files/vcpkg/scripts/buildsystems/vcpkg.cmake")
> 
> I think I found the reason, because of scope, if you want to specify `TOOLCHAIN_FILE` in `CMakeList.txt`, then you must put `set(CMAKE_TOOLCHAIN_FILE)` in front of `project(main)`.
> 
> ```
> cmake_minimum_required(VERSION 3.22)
> set(CMAKE_TOOLCHAIN_FILE "C:/Program Files/vcpkg/scripts/buildsystems/vcpkg.cmake")
> project(main)
> set(CMAKE_CXX_STANDARD 17)
> ```

This works! As CMake ran the successful build, I saw that `fmtd.dll` `spdlogd.dll` were installed. as it ran the Debug mode. It is the first time I link the .dll. Is it really necessary to install .dll to the program path? If so, why `fmt.lib` or `spdlog.lib` weren't installed?

**Comment by MonicaLiu0311** [comment] 2022-12-01 08:49
> I saw that `fmtd.dll` `spdlogd.dll` were installed.

Because you used `add_executable` to generate an `.exe`, and used the functions in `spdlog`.

> If so, why fmt.lib or spdlog.lib weren't installed?

The `.exe` needs to call the `.dll`, and the `.lib` is generally integrated into the exe.

**Comment by KRJackLee** [comment] 2022-12-02 12:47
> 

I assume that when I call `cmake .`, it is in Release mode as default, and fmt.dll and spdlog.dll weren't installed in project path. What makes that .dlls need to be downloaded under project path in Debug mode and not in Release mode?

**Comment by KRJackLee** [comment] 2022-12-02 12:53
> > > nmake
> > 
> > 
> > `nmake` needs `MAKEFILE`, you are using `CMakelists.txt`.
> 
> Cmake has a generator for nmake makefiles. But we would recommend ninja or another generator instead.

Can I write CMAKE_GENERATOR in `CMakeLists.txt`, so as to switch between `-G NMake Makefile` and `-G Ninja` without typing commands repeatedly? I tried `set(CMAKE_GENERATOR "Ninja")` at the top of file and CMake didn't build a `.ninja`,

**Comment by dg0yt** [comment] 2023-02-15 07:33
AFAICS this is a more a question about using CMake, not about using vcpkg.

**Comment by MonicaLiu0311** [comment] 2023-02-15 07:51
Since this issue is not related with vcpkg and have answered the user's link questions, so I am closing this issue for now.

**Closed by MonicaLiu0311** 2023-02-15 07:51 UTC
Labels: category:question
