### ISSUE TITLE
vcpkg.exe failed in Windows container says "Error getting canonicalization"

### ISSUE THREAD

**Issue by longli0** [microsoft/vcpkg#16614] opened 2021-03-09 06:27 UTC
**Describe the bug**
vcpkg.exe failed to build packages in Windows container says "Error getting canonicalization"

**Environment**
- OS: Windows 10 Version 20H2 (OS Build 19042.804)
- Compiler: VS BuildTools 16 +  'Microsoft.VisualStudio.Component.VC.Tools.x86.x64' + 'Microsoft.VisualStudio.Component.VC.v141.x86.x64', download link: https://aka.ms/vs/16/release/vs_buildtools.exe 
- Docker for Windows v3.1.0 (51484)
- Dockerfile base image: `mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2016`

**To Reproduce**
1. Update vcpkg to latest commit in master branch, hash `0dc27b9b672cb9d069cf58c48f3ae3f7395d108b`
2. `docker run -it -m 4GB -v C:\your_folder:C:/code mcr.microsoft.com/dotnet/framework/runtime:4.7.2-windowsservercore-ltsc2016`
2.  In Windows container 
```
bootstrap-vcpkg.bat
vcpkg integrate install --debug
vcpkg install zlib:x64-windows --debug
```
3. See failure logs
 

**Expected behavior**
Vcpkg build normally.

**Failure logs** 
```
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2021-02-24-d67989bce1043b98092ac45996a8230a059a2d7e/vcpkg.exe -> C:\code\vcpkg/vcpkg.exe
Done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\code\vcpkg
[DEBUG] Using installed-root: C:\code\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: C:\code\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\code\vcpkg\downloads
[DEBUG] Using packages-root: C:\code\vcpkg\packages
[DEBUG] Using scripts-root: C:\code\vcpkg\scripts
[DEBUG] Using ports-root: C:\code\vcpkg\ports
[DEBUG] Using versions-root: C:\code\vcpkg\versions
Error getting canonicalization of C:\code\vcpkg\triplets: The system cannot find the file specified.
[DEBUG] C:\A\1\70\s\src\vcpkg\vcpkgpaths.cpp(363)
[DEBUG] Exiting after 53758 us (16789 us)
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: C:\code\vcpkg
[DEBUG] Using installed-root: C:\code\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: C:\code\vcpkg\buildtrees
[DEBUG] Using downloads-root: C:\code\vcpkg\downloads
[DEBUG] Using packages-root: C:\code\vcpkg\packages
[DEBUG] Using scripts-root: C:\code\vcpkg\scripts
[DEBUG] Using ports-root: C:\code\vcpkg\ports
[DEBUG] Using versions-root: C:\code\vcpkg\versions
Error getting canonicalization of C:\code\vcpkg\triplets: The system cannot find the file specified.
[DEBUG] C:\A\1\70\s\src\vcpkg\vcpkgpaths.cpp(363)
[DEBUG] Exiting after 3721 us (1784 us)
Vcpkgs failed to build packages.
```

**Additional context**
This is probably related to this issue and the suggested workaround in the comment https://github.com/microsoft/vcpkg/issues/13744#issuecomment-709866872

> Looks like in my case issue is different from original reporter. On windows it was introduced by commit [0bb8780](https://github.com/microsoft/vcpkg/commit/0bb8780a60e67320a966421e2923595fa57cbf22).
> As a workaround I changed C:\appd\agent-dotnet-vcpkg\toolsrc\windows-bootstrap\vcpkg.vcxproj (set `VcpkgUseStdFilesystem=0` always and add `_SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING` definition). It helped.

I did the similar workaround and it works normally, but this doesn't look like a good solution, and we will have to use `std::filesystem` eventually.

**Comment by acgetchell** [comment] 2021-03-09 23:38
This also happens on macOS:

```
adam@hapkido ~/projects $ git clone https://github.com/Microsoft/vcpkg.git
Cloning into 'vcpkg'...
remote: Enumerating objects: 104562, done.
remote: Total 104562 (delta 0), reused 0 (delta 0), pack-reused 104562
Receiving objects: 100% (104562/104562), 31.83 MiB | 6.70 MiB/s, done.
Resolving deltas: 100% (65570/65570), done.
Updating files: 100% (7280/7280), done.
adam@hapkido ~/projects $ cd vcpkg
adam@hapkido ~/projects/vcpkg (master) $ ./bootstrap-vcpkg.sh 
Downloading cmake...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   637  100   637    0     0   1464      0 --:--:-- --:--:-- --:--:--  1461
100 60.7M  100 60.7M    0     0  16.8M      0  0:00:03  0:00:03 --:--:-- 26.1M
Downloading cmake... done.
Extracting cmake...
Extracting cmake... done.
Downloading ninja...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617  100   617    0     0   1523      0 --:--:-- --:--:-- --:--:--  1519
100  114k  100  114k    0     0   156k      0 --:--:-- --:--:-- --:--:--  156k
Downloading ninja... done.
Extracting ninja...
Extracting ninja... done.
Downloading vcpkg tool sources
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   173  100   173    0     0    433      0 --:--:-- --:--:-- --:--:--   433
100  479k    0  479k    0     0   267k      0 --:--:--  0:00:01 --:--:--  349k
Building vcpkg-tool...
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/bin/g++-10 - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting the C++ compiler in use
-- Detecting the C++ compiler in use - gcc
-- Detecting the C++ standard library
-- Detecting the C++ standard library - libstdc++
-- Detecting how to use the C++ filesystem library
-- Detecting how to use the C++ filesystem library - <filesystem>
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/adam/projects/vcpkg/buildtrees/_vcpkg/build
[0/2] Re-checking globbed directories...
[88/88] Linking CXX executable vcpkg
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
adam@hapkido ~/projects/vcpkg (master) $ ./vcpkg install catch2
Error getting canonicalization of /Users/adam/vcpkg: No such file or directory
```

**Comment by NancyLi1013** [comment] 2021-03-10 06:14
@strega-nil 
Do we have any plan to fix this problem?

**Comment by strega-nil** [comment] 2021-03-10 22:19
@longli0 could you run `dir C:\code\vcpkg` in your docker?

**Comment by longli0** [comment] 2021-03-11 02:32
> @longli0 could you run `dir C:\code\vcpkg` in your docker?

Sure, here is the output.
```
c:\code>dir C:\code\vcpkg
 Volume in drive C has no label.
 Volume Serial Number is C0EB-DF4A

 Directory of C:\code\vcpkg

03/10/2021  06:29 PM    <DIR>          .
03/10/2021  06:29 PM    <DIR>          ..
03/03/2021  05:44 PM               141 .gitattributes
03/03/2021  05:44 PM    <DIR>          .github
03/08/2021  09:56 PM             5,533 .gitignore
03/03/2021  05:44 PM                 0 .vcpkg-root
03/03/2021  05:44 PM               100 bootstrap-vcpkg.bat
03/03/2021  05:44 PM               109 bootstrap-vcpkg.sh
03/03/2021  05:44 PM           722,083 CHANGELOG.md
03/03/2021  05:44 PM             2,432 CONTRIBUTING.md
03/10/2021  06:26 PM    <DIR>          docs
03/10/2021  12:40 AM    <DIR>          installed
03/03/2021  05:44 PM             1,096 LICENSE.txt
03/03/2021  05:44 PM             2,334 NOTICE.txt
03/08/2021  09:56 PM    <DIR>          ports
03/03/2021  05:44 PM            12,056 README.md
03/08/2021  09:56 PM            15,477 README_es.md
03/03/2021  05:44 PM            12,457 README_fr.md
03/03/2021  05:44 PM            13,959 README_ko_KR.md
03/03/2021  05:44 PM            11,714 README_zh_CN.md
03/10/2021  06:26 PM    <DIR>          scripts
03/08/2021  09:56 PM               923 shell.nix
03/08/2021  09:56 PM    <DIR>          toolsrc
03/08/2021  09:56 PM    <DIR>          triplets
03/10/2021  06:26 PM    <DIR>          versions
              15 File(s)        800,414 bytes
              10 Dir(s)  78,709,825,536 bytes free
```

**Comment by BillyONeal** [comment] 2021-03-11 18:45
Hi there!

The `std::experimental::filesystem` implementation of `canonical` is incorrect, it doesn't resolve symlinks or other filesystem behavior. It does the equivalent of `std::filesystem::system_complete`:

https://github.com/microsoft/STL/blob/194efde4bdc7d3e73984e266b983aed334288f2a/stl/inc/experimental/filesystem#L1874-L1890

Compare with the `std::` one which opens the file and gets the final resolved name by using [`GetFinalPathNameByHandleW`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-getfinalpathnamebyhandlew):

https://github.com/microsoft/STL/blob/194efde4bdc7d3e73984e266b983aed334288f2a/stl/inc/filesystem#L3051-L3103

https://github.com/microsoft/STL/blob/194efde4bdc7d3e73984e266b983aed334288f2a/stl/src/filesystem.cpp#L173-L180

Perhaps some of the containers / docker stuff have a driver in that path which isn't correctly responding to such queries?

**Comment by BillyONeal** [comment] 2021-03-11 18:46
@strega-nil: It might make sense for vcpkg's purposes to try `canonical`, then fall back to `system_complete` if the file exists but `canonical` failed?

**Comment by strega-nil** [comment] 2021-03-11 18:48
@BillyONeal I'm okay with that.

**Comment by BillyONeal** [comment] 2021-03-11 18:50
@strega-nil We're trying to prevent a symlink in the path causing our resulting builds to be broken should the symlink change. And on case insensitive systems we're trying to get the actual case. If we don't fix this up `vcpkg_fixup_pkgconfig` can give wrong answers since it uses exact match :(

**Comment by strega-nil** [comment] 2021-03-11 18:52
hmm, I'm trying to think of when a build would break if a symlink changed...

**Comment by iskiselev** [comment] 2021-03-29 03:26
The issue was originally introduced by commit 0bb8780.
As a workaround before I changed C:\appd\agent-dotnet-vcpkg\toolsrc\windows-bootstrap\vcpkg.vcxproj (set VcpkgUseStdFilesystem=0 always and add _SILENCE_EXPERIMENTAL_FILESYSTEM_DEPRECATION_WARNING definition) - but now vcpkg is downloaded, not built.

**Comment by iskiselev** [comment] 2021-03-29 03:37
The issue is now harder to workaround compare to what  was at https://github.com/microsoft/vcpkg/issues/13744#issuecomment-709866872, as pre-build vcpkg is downloading now

**Comment by BillyONeal** [comment] 2021-03-29 23:30
@iskiselev Do you know folks to which the failure to handle `GetFinalPathNameByHandleW` could be reported? Ideally the bug would be fixed in Docker itself since this is an 'ordinary Windows API' breaking but we could try the 'fallback to `system_complete`' alternative...

**Comment by iskiselev** [comment] 2021-03-29 23:53
@BillyONeal , no unfortunately I don't know who is responsible for it. I even don't know if it is on docker side or on Windows site.

**Comment by BillyONeal** [comment] 2021-03-29 23:56
I'll ask around

**Comment by iskiselev** [comment] 2021-03-30 04:08
@BillyONeal, it would be great if vcpkg will implement fallback even if docker/windows will fix it. It is much longer wait until docker will be updated on build servers.

**Comment by BillyONeal** [comment] 2021-04-07 00:46
Some Windows Containers folks took a look at this and indicated that it's a known bug in the RS1 (server 2016) container images, fixed in the Server 2019 containers (windowsservercore-ltsc2019 or greater). As you indicated we might still want to work around it in vcpkg...

**Comment by iskiselev** [comment] 2021-05-13 20:33
@BillyONeal, any updates / estimates for this issue workaround? I 'm thinking if we need to do some in-house solution or can wait for proper fix from VCPKG.

**Comment by BillyONeal** [comment] 2021-06-05 21:33
@iskiselev Can you try applying the changes from https://github.com/microsoft/vcpkg-tool/pull/88 and let me know if that works for you?

**Comment by iskiselev** [comment] 2021-06-07 17:47
@BillyONeal, can you advice me what I should do in my clone of microsoft/vcpkg repo to test  microsoft/vcpkg-tool#88 ?

**Comment by BillyONeal** [comment] 2021-06-07 19:29
> @BillyONeal, can you advice me what I should do in my clone of microsoft/vcpkg repo to test [microsoft/vcpkg-tool#88](https://github.com/microsoft/vcpkg-tool/pull/88) ?

Something like:

```
git clone https://github.com/microsoft/vcpkg-tool
cd vcpkg-tool
git remote add BillyONeal https://github.com/BillyONeal/vcpkg-tool
git fetch BillyONeal
git switch -d BillyONeal/canonical-workaround
cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -B pick_a_build_dir_name_here -S .
ninja -C pick_a_build_dir_name_here
```

then get the resulting vcpkg.exe from that build dir and see if it works in your container etc.

(I would build it myself for you but I can't ship unsigned binaries and we aren't supposed to sign things that aren't landed)

**Comment by iskiselev** [comment] 2021-06-16 20:40
Thank you a lot, @BillyONeal. Sorry for a delay with testing it. I've confirmed that issue is fixed in vcpkg-tool master now (but download script in vcpkg repo still use older build, affected by the issue).

**Comment by BillyONeal** [comment] 2021-06-16 20:41
No problem, thanks for confirming. I'll keep you posted for when the repo is updated here. (I'm working on fixing one more binary caching issue before we turn the release crank)

**Comment by BillyONeal** [comment] 2021-06-16 22:40
( https://github.com/microsoft/vcpkg/pull/18233/ is probably going to be doing that update)

**Comment by iskiselev** [comment] 2021-06-24 05:23
Thank you, @BillyONeal  - issue solved in vcpkg master now.

**Comment by NancyLi1013** [comment] 2021-06-24 05:46
Now that this issue has been fixed in latest vcpkg, closing this issue. Thanks for your reply. @iskiselev

**Closed by NancyLi1013** 2021-06-24 05:46 UTC
Labels: category:vcpkg-bug

**Comment by darksectordds** [comment] 2021-06-30 17:56
I got same issue when i did installation steps to the instructions from here [https://github.com/microsoft/vcpkg/tree/master#quick-start-windows](url)

![image](https://user-images.githubusercontent.com/11490033/124008533-2f588280-d9e5-11eb-8f15-8d5916fe4568.png)

I have a file name **ezEngine-release-20.5.tar.gz** on level above, but not a folder.

**Comment by BillyONeal** [comment] 2021-06-30 18:19
That doesn't look like the 'same issue'. Please make sure VCPKG_ROOT isn't set to something funky

**Comment by darksectordds** [comment] 2021-07-01 04:56
@BillyONeal thx. You right. He actually created a new environment variable. I found out this by checking all the environment variables through the **set** command.

```
VCPKG_ROOT=D:\MyTest2\github\ezEngine-release-20.5\vcpkg
```
