### ISSUE TITLE
[tiff] build failure

### ISSUE THREAD

**Issue by eladm-ultrawis** [microsoft/vcpkg#30515] opened 2023-03-29 11:36 UTC
**Host Environment**

- OS: Windows 10
- Compiler: MSVC 17 (Visual Studio 2022)

**To Reproduce**

`./vcpkg install tiff`

**Failure logs**

```
Installing 1/1 tiff:x64-windows-static-md-v143...
Building tiff[core,jpeg,lzma,zip]:x64-windows-static-md-v143...
-- [OVERLAY] Loading triplet configuration from: C:\workspace\cranebit2\vcpkg_scripts\triplets\x64-windows-static-md-v143.cmake
-- Installing port from location: C:\libs\vcpkg\buildtrees\versioning_\versions\tiff\e1bb817eb3c58fcbe28f9d5217cb1b594493003f
-- Downloading https://gitlab.com/libtiff/libtiff/-/archive/v4.5.0/libtiff-v4.5.0.tar.gz -> libtiff-libtiff-v4.5.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://gitlab.com/libtiff/libtiff/-/archive/v4.5.0/libtiff-v4.5.0.tar.gz
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://gitlab.com/libtiff/libtiff/-/archive/v4.5.0/libtiff-v4.5.0.tar.gz
File: C:\libs\vcpkg\downloads\libtiff-libtiff-v4.5.0.tar.gz.24008.part
Expected hash: 5227cb7b496ac6829601d8d689233bd8f318c1d04e5ce3457cdd6eac9e4f8c80cd7211d90cd092c61ad38bc8a4949169a13eabd788c46c15bcee1f72519fa022
Actual hash: e45a0eb3229349db7d4707e8dd3557b1a744fd307820c40e70f598a2642e4122d98fcda660306ae8b3f9a49ea13dba55429d22b37dbc96e9038411310db56fc5
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956):
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 8 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 752 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 625.9 ms (617310 us)
```

**Additional context**

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by autoantwort** [comment] 2023-03-29 12:04
Duplicate of https://github.com/microsoft/vcpkg/issues/30481

**Closed** 2023-03-30 01:56 UTC
Labels: category:port-bug
