### ISSUE TITLE
Building sfml:x64-linux-dynamic  on Ubuntu 18.04 fails

### ISSUE THREAD

**Issue by giellamo** [microsoft/vcpkg#4773] opened 2018-11-20 11:25 UTC
I'm trying to build SFML with a dynamic toolchain but it fails.

 Package: sfml:x64-linux-dynamic
 Vcpkg version: 2018.10.20-unknownhash

[install-x64-linux-dynamic-dbg-out.log](https://github.com/Microsoft/vcpkg/files/2599461/install-x64-linux-dynamic-dbg-out.log)

My triplet file is:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Linux)
if(PORT MATCHES "bzip2")
    set(VCPKG_LIBRARY_LINKAGE static)
endif()
```
bzip2 is built static because cmake_test was failing when building dynamic...

**Comment by Nuckal777** [comment] 2019-05-31 22:51
I ran into this problem today. The port contains a patch file which adjusts linkage with freetype2. The applying of the patch fails due to incorrect file paths containing lowercase "sfml" instead of uppercase "SFML" in the src subdirectory of the buildtree. Applying the patch by hand leads to a successful compilation. Fixed patch file:
[use-system-freetype.patch.txt](https://github.com/microsoft/vcpkg/files/3243069/use-system-freetype.patch.txt)

**Comment by NancyLi1013** [comment] 2019-11-08 09:07
Hi @giellamo and @Nuckal777  thanks for posting this issue.
This port has been updated and please try to update vcpkg and build it again.
I cannot reproduce this issue on my local now. So this issue should be fixed.
Please free free to reopen this or open an new issue if this is still a problem for you.

Thanks a again.

**Closed by NancyLi1013** 2019-11-08 09:07 UTC
Labels: port bug
