### ISSUE TITLE
[wxwidgets] build failure: Windows VS 16.6.5: Internal compiler error

### ISSUE THREAD

**Issue by rkitover** [microsoft/vcpkg#12660] opened 2020-07-30 21:21 UTC
**Host Environment**
- OS: Windows Insider Preview Dev Channel (Build: 20180.1000)
- Compiler: Visual Studio 16.6.5

**To Reproduce**
`./vcpkg install wxwidgets:x64-windows-static`

**Failure logs** 

Console output:

```
Starting package 6/1: wxwidgets:x64-windows-static
Building package wxwidgets[core]:x64-windows-static...
Could not locate cached archive: C:\Users\rkitover\AppData\Local\vcpkg\archives\26\26f55be17126046d61da4d50582349ef31232355.zip
-- Using cached C:/Users/rkitover/src/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.3.tar.gz
-- Cleaning sources at C:/Users/rkitover/src/vcpkg/buildtrees/wxwidgets/src/v3.1.3-d3ae26deac.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/rkitover/src/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.3.tar.gz
-- Applying patch disable-platform-lib-dir.patch
-- Applying patch fix-macos-clipboard.patch
-- Using source at C:/Users/rkitover/src/vcpkg/buildtrees/wxwidgets/src/v3.1.3-d3ae26deac.clean
-- Configuring x64-windows-static
-- Building x64-windows-static-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:136 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v
    Working Directory: C:/Users/rkitover/src/vcpkg/buildtrees/wxwidgets/x64-windows-static-dbg
    See logs for more information:
      C:\Users\rkitover\src\vcpkg\buildtrees\wxwidgets\install-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:91 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:24 (vcpkg_build_cmake)
  ports/wxwidgets/portfile.cmake:38 (vcpkg_install_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package wxwidgets:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: wxwidgets:x64-windows-static
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
```

Build log error (full log attached):

```
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\cl.exe   /TP -DUNICODE -DWXBUILDING -DWX_PRECOMP -D_CRT_NON_CONFORMING_SWPRINTFS=1 -D_CRT_SECURE_NO_DEPRECATE=1 -D_LIB -D_SCL_SECURE_NO_WARNINGS=1 -D_UNICODE -D_WINSOCK_DEPRECATED_NO_WARNINGS=1 -D__WXMSW__ -DwxUSE_BASE=1 -DwxUSE_GUI=0 -IC:\Users\rkitover\src\vcpkg\buildtrees\wxwidgets\src\v3.1.3-d3ae26deac.clean\src\regex -IC:\Users\rkitover\src\vcpkg\installed\x64-windows-static\include -Ilib\vc_x64_\mswud -IC:\Users\rkitover\src\vcpkg\buildtrees\wxwidgets\src\v3.1.3-d3ae26deac.clean\include /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /MP /D_DEBUG /MTd /Z7 /Ob0 /Od /RTC1    /W4  /Yu"C:\Users\rkitover\src\vcpkg\buildtrees\wxwidgets\x64-windows-static-dbg\libs\base\cotire\base_CXX_prefix.hxx" /Fp"C:\Users\rkitover\src\vcpkg\buildtrees\wxwidgets\x64-windows-static-dbg\libs\base\cotire\base_CXX_prefix.pch" /FI"C:\Users\rkitover\src\vcpkg\buildtrees\wxwidgets\x64-windows-static-dbg\libs\base\cotire\base_CXX_prefix.hxx" /Zm170 /showIncludes /Folibs\base\CMakeFiles\base.dir\__\__\__\__\src\common\datstrm.cpp.obj /Fdlibs\base\CMakeFiles\base.dir\base.pdb /FS -c C:\Users\rkitover\src\vcpkg\buildtrees\wxwidgets\src\v3.1.3-d3ae26deac.clean\src\common\datstrm.cpp^M
cl : Command line warning D9025 : overriding '/W3' with '/W4'
C:\Users\rkitover\src\vcpkg\buildtrees\wxwidgets\src\v3.1.3-d3ae26deac.clean\src\common\datstrm.cpp: fatal error C1001: Internal compiler error.
(compiler file 'msc1.cpp', line 1533)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
INTERNAL COMPILER ERROR in 'C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1426~1.288\bin\Hostx64\x64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
```
[install-x64-windows-static-dbg-out.log](https://github.com/microsoft/vcpkg/files/5003837/install-x64-windows-static-dbg-out.log)

**Comment by rkitover** [comment] 2020-07-30 21:37
Link to Visual Studio problem report:

https://developercommunity.visualstudio.com/content/problem/1131900/internal-compiler-error-building-wxwidgets-from-vc.html

**Comment by rkitover** [comment] 2020-08-02 19:26
I uninstalled Visual Studio 16.6.5 and installed Build Tools 16.6.1 and the port compiled successfully.

**Comment by LilyWangL** [comment] 2020-08-04 05:51
Thanks for posting this issue. I can't reproduce this issue locally, I can install wxwidgets:x64-windows-static successfully with Visual Studio 16.6.5 on the latest VCPKG.

**Comment by rkitover** [comment] 2020-08-04 07:08
Could be something in my configuration, I don't know, but if that is the case I have no objections to closing this, especially as there's a separate Visual Studio report anyway.

**Comment by LilyWangL** [comment] 2020-08-04 08:59
Waiting for Visual Studio report has new progress, if it confirm this is not related with VCPKG, I will close this issue.

**Comment by LilyWangL** [comment] 2020-08-13 07:44
Now `wxwidgets:x64-windows-static` can build successfully on the latest VCPKG, so I an closing this issue for now.

**Closed by LilyWangL** 2020-08-13 07:44 UTC
Labels: requires:repro
