### ISSUE TITLE
[vcpkg-tool] pr 49 cause proxy no use

### ISSUE THREAD

**Issue by cathaysia** [microsoft/vcpkg#17752] opened 2021-05-09 03:01 UTC
**Describe the bug**

I had notice vcpkg.exe of may version has the ability to set proxy auto. But it no use acctually. And it will override the envs I set.

**To Reproduce**
1. install vcpkg.exe version may
2. use fiddler.exe set a proxy
3. run vcpkg
4. fiddler can't get any internet flow of vcpkg.exe

> Note:
>
> the flow in Chinese is called 流量， it means a internet swap between pc and other computers. But I don't know English is called flow or not.

**Expected behavior**

fiddler can catch flow of vcpkg.exe

**Failure logs** 

for vcpkg5.exe:
(no HTTP_PROXY set)
```
>vcpkg5.exe install laszip
Computing installation plan...
The following packages will be built and installed:
    laszip[core]:x64-windows -> 3.4.3
Detecting compiler hash for triplet x64-windows...
-- Setting HTTP_PROXY environment variables to http://127.0.0.1:8889
-- Setting HTTPS_PROXY environment variables to https://127.0.0.1:8889
Could not locate cached archive: C:\Users\Drago\AppData\Local\vcpkg\archives\58\589d2f070bea4b545f19a105f44b9c5b5dfeaf40.zip
Starting package 1/1: laszip:x64-windows
Building package laszip[core]:x64-windows...
-- Downloading https://github.com/LASzip/LASzip/archive/1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz -> LASzip-LASzip-1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz...
-- Downloading https://github.com/LASzip/LASzip/archive/1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz... Failed. Status: 4;"A requested feature, protocol or option was not found built-in in this libcurl due to a build-time decision."
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:184 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".

      If error with status 4 (Issue #15434),
      try setting "http://user:password@your-proxy-ip-address:port/".

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/laszip/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:142 (include)


Error: Building package laszip:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: laszip:x64-windows
  Vcpkg version: 2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9

Additionally, attach any relevant sections from the log files above.
```

for vcpkg4.exe:

```
>set HTTPS_PROXY=localhost:8889

>set HTTP_PROXY=localhost:8889

>vcpkg.exe install laszip
Computing installation plan...
The following packages will be built and installed:
    laszip[core]:x64-windows -> 3.4.3
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\Drago\AppData\Local\vcpkg\archives\58\589d2f070bea4b545f19a105f44b9c5b5dfeaf40.zip
Starting package 1/1: laszip:x64-windows
Building package laszip[core]:x64-windows...
-- Downloading https://github.com/LASzip/LASzip/archive/1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz -> LASzip-LASzip-1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz...
-- Extracting source D:/Documents/Tools/dev/vcpkg/downloads/LASzip-LASzip-1ab671e42ff1f086e29d5b7e300a5026e7b8d69b.tar.gz
-- Using source at D:/Documents/Tools/dev/vcpkg/buildtrees/laszip/src/26e7b8d69b-860c05dba9.clean
```

**Comment by PhoebeHui** [comment] 2021-05-10 02:15
@cathaysia, thanks for reporting this issue!

It may be same issue with https://github.com/microsoft/vcpkg/issues/17688, @cathaysia, could you confirm if PR https://github.com/microsoft/vcpkg/pull/17734 works for you?

**Comment by cnSchwarzer** [comment] 2021-05-10 05:15
Sorry for the bug I make, I fixed in PR: https://github.com/microsoft/vcpkg-tool/pull/77
The problem is caused by:
- I intentionally added prefix (https://) to HTTPS_PROXY by copying python's urllib implementation. This will let the vcpkg's underlying build process considering 127.0.0.1:8889 as a HTTPS proxy while it is just an HTTP proxy accepts https requests. This is fixed in above PR.
- I didn't detect whether the environment variables already contains HTTP(S)_PROXY, this is also fixed in above PR.

Any further issues please refer to this reply. Thanks and sorry for inconvenience.

**Comment by cathaysia** [comment] 2021-05-14 14:24
@PhoebeHui Hi, firend. I'am afraid I can't test this pr for I had removed MSVC :( If there are not a binary I can't let this work done.

But @cnSchwarzer should coverd a good work :)

The reason I remove MSVC just because it ask my source files had a BOM and it cause a lot problems. I find move to linux must be a better choice for me...

**Comment by PhoebeHui** [comment] 2021-05-15 03:03
@cathaysia, thanks for your response! and Thanks @cnSchwarzer for your great work!

**Closed** 2021-05-21 08:00 UTC
Labels: category:vcpkg-bug
