### ISSUE TITLE
Fail to static link freeglut

### ISSUE THREAD

**Issue by wby238** [Microsoft/vcpkg#3544] opened 2018-05-20 12:15 UTC
I use `cmake "-DCMAKE_TOOLCHAIN_FILE=***/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x86-windows-static -DCMAKE_BUILD_TYPE=Release -Wno-dev ..` to generate VS 2017 solution file, and use `cmake --build . --config Release` to build, and fail to link glut.
But I can dynamic link it with `cmake "-DCMAKE_TOOLCHAIN_FILE=***/vcpkg.cmake" -DVCPKG_TARGET_TRIPLET=x86-windows -DCMAKE_BUILD_TYPE=Release -Wno-dev ..`

This is cmake output log
```
-DCMAKE_BUILD_TYPE=Release -Wno-dev ..
-- Building for: Visual Studio 15 2017
-- The C compiler identification is MSVC 19.13.26131.1
-- The CXX compiler identification is MSVC 19.13.26131.1
****
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenGL: opengl32
-- Found GLUT: ***/vcpkg/installed/x86-windows-static/lib/freeglut.lib
-- Configuring done
-- Generating done
-- Build files have been written to: ***
```

build output
```
****
“C:\src\computer_graphics_homework3\build\ALL_BUILD.vcxproj”(默认目标) (1) ->
“C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj”
(默认目标) (3) ->
(Link 目标) ->
  main.obj : error LNK2019: 无法解析的外部符号 __imp__glutInitWindowSize@8，该符号在函数 _main中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
  main.obj : error LNK2019: 无法解析的外部符号 __imp__glutInitDisplayMode@4，该符号在函数 _main 中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
  main.obj : error LNK2019: 无法解析的外部符号 __imp__glutMainLoop@0，该符号在函数 _main 中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
  main.obj : error LNK2019: 无法解析的外部符号 __imp__glutPostRedisplay@0，该符号在函数 "void __cdecl keyboard(unsigned char,int,int)" (?keyboard@@YAXEHH@Z) 中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
  main.obj : error LNK2019: 无法解析的外部符号 __imp__glutSwapBuffers@0，该符号在函数 "void __cdecl display(void)" (?display@@YAXXZ) 中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
  main.obj : error LNK2019: 无法解析的外部符号 __imp__glutKeyboardFunc@4，该符号在函数 _main 中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
  main.obj : error LNK2019: 无法解析的外部符号 __imp__glutReshapeFunc@4，该符号在函数 _main 中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]  main.obj : error LNK2019: 无法解析的外部符号 __imp__glutDisplayFunc@4，该符号在函数 _main 中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
  main.obj : error LNK2019: 无法解析的外部符号 __imp__glutWireSphere@16，该符号在函数 "void __cdecl display(void)" (?display@@YAXXZ) 中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
  main.obj : error LNK2019: 无法解析的外部符号 __imp____glutInitWithExit@12，该符号在函数 _main 中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
  main.obj : error LNK2019: 无法解析的外部符号 __imp____glutCreateWindowWithExit@8，该符号在函数 _main 中被引用 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
  C:\src\computer_graphics_homework3\build\Release\computer_graphics_homework3.exe : fatal error LNK1120: 11 个无法解析的外部命令 [C:\src\computer_graphics_homework3\build\computer_graphics_homework3.vcxproj]
****
```

cmakelists.txt
```cmake
cmake_minimum_required(VERSION 3.0)
project(test)

find_package(OpenGL REQUIRED)
find_package(glm REQUIRED)
find_package(GLUT REQUIRED)

add_executable(${PROJECT_NAME} main.cpp)
target_link_libraries(${PROJECT_NAME} PRIVATE GLUT::GLUT)

set(CompilerFlags
        CMAKE_CXX_FLAGS
        CMAKE_CXX_FLAGS_DEBUG
        CMAKE_CXX_FLAGS_RELEASE
        CMAKE_C_FLAGS
        CMAKE_C_FLAGS_DEBUG
        CMAKE_C_FLAGS_RELEASE
        )
foreach(CompilerFlag ${CompilerFlags})
  string(REPLACE "/MD" "/MT" ${CompilerFlag} "${${CompilerFlag}}")
endforeach()
```

main.cpp
```cpp
#include <GL/glut.h>
void display();
void reshape(int width, int height);
void keyboard(unsigned char key, int x, int y);
static int revolution = 0, rotation = 0;
int main(int argc, char *argv[])
{
	glutInit(&argc, argv);
	glutInitDisplayMode(GLUT_RGB | GLUT_SINGLE);
	glutInitWindowSize(800, 800);
	glutCreateWindow("Computer Graphic Homework 3");
	glClearColor(0, 0, 0, 0);
	glShadeModel(GL_FLAT);
	glutKeyboardFunc(keyboard);
	glutReshapeFunc(reshape);
	glutDisplayFunc(display);
	glutMainLoop();
	return 0;
}
void display()
{
	glClear(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
	glColor3f(1.0f, 1.0f, 1.0f);
	glPushMatrix();
	glutWireSphere(1.0, 30, 24);
	glRotatef(static_cast<GLfloat>(revolution), 0.0f, 1.0f, 0.0f);
	glTranslatef(3.0f, 0.0f, 0.0f);
	glRotatef(static_cast<GLfloat>(rotation), 0.0f, 1.0f, 0.0f);
	glutWireSphere(0.25, 15, 12);
	glPopMatrix();
	glutSwapBuffers();
	glFlush();
}
void reshape(int width, int height)
{
	glViewport(0, 0, width, height);
	glMatrixMode(GL_PROJECTION);
	glLoadIdentity();
	gluPerspective(75.0, static_cast<GLfloat>(width) / static_cast<GLfloat>(height), 1.0, 15);
	glMatrixMode(GL_MODELVIEW);
	glLoadIdentity();
	gluLookAt(0.0, 0.0, 6.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0);
}
void keyboard(unsigned char key, int x, int y)
{
	switch (key)
	{
		case 'd':
			rotation = (rotation + 10) % 360;
			glutPostRedisplay();
			break;
		case 'D':
			rotation = (rotation - 10) % 360;
			glutPostRedisplay();
			break;
		case 'y':
			revolution = (revolution + 10) % 360;
			glutPostRedisplay();
			break;
		case 'Y':
			revolution = (revolution - 10) % 360;
			glutPostRedisplay();
			break;
		case 27: // ESC == 27
			exit(0);
		default:
			break;
	}
}
```

**Comment by JackBoosY** [comment] 2019-03-22 09:42
Hi @wby238 , thanks for reporting this issue!
freeglut depends on gult caused this issue. I will try to fix it.
Thx.

**Comment by JackBoosY** [comment] 2019-04-23 07:21
@wby238  It seems that someone has fixed this problem, and I can't reproduce it.
So I closed this issue, if you still have problems, please open a new issue.
Thank you.

**Closed by JackBoosY** 2019-04-23 07:21 UTC
Labels: port bug
