### ISSUE TITLE
"error C2593" while building "vcpkg.exe"

### ISSUE THREAD

**Issue by gvanem** [microsoft/vcpkg#24405] opened 2022-04-25 12:03 UTC
Since I see no Issue page for the **vcpkg-tool** repo, I write this here:

While compiling the `vcpkg.exe` program using MSVC-2019 (x86), I get these errors:
```
f:\gv\VC_2019\VC\Tools\MSVC\14.29.30133\include\xutility(5307): error C2593: 'operator ==' is ambiguous
(compiling source file vcpkg/base/files.cpp)
F:\gv\VC_project\VCPKG\vcpkg-tool\include\vcpkg/base/stringview.h(54): note: 
could be 'bool vcpkg::operator ==(vcpkg::StringView,vcpkg::StringView) noexcept' [found using argument-dependent lookup] (compiling source file vcpkg/base/files.cpp)
F:\gv\VC_project\VCPKG\vcpkg-tool\include\vcpkg/base/optional.h(401): note: or      
 'bool vcpkg::Optional<std::string>::operator==(const vcpkg::Optional<std::string> &,const vcpkg::Optional<std::string> &)'
[found using argument-dependent lookup] (compiling source file vcpkg/base/files.cpp)
f:\gv\VC_2019\VC\Tools\MSVC\14.29.30133\include\xutility(5307): note: while trying to match the argument list 
'(vcpkg::Path, const _Ty)'
        with
        [
            _Ty=vcpkg::Path
        ] (compiling source file vcpkg/base/files.cpp)
f:\gv\VC_2019\VC\Tools\MSVC\14.29.30133\include\xutility(5342): note: see reference to function template instantiation 
'_InIt std::_Find_unchecked1<_InIt,_Ty>(_InIt,const _InIt,const _Ty &,std::false_type)' being compiled ...
....
```

Some issue in `vcpkg/base/files.cpp`?

But doing the same using `clang-cl`, there is no problem what-so-ever!

**Comment by Cheney-W** [comment] 2022-04-26 03:04
Thanks for reporting this issue to us.
Unfortunately, I can't reproduce this issue in my side, my repro step as below:
1. git clone https://github.com/microsoft/vcpkg-tool
2. Open the vcpkg-tool folder as a cmake folder in VS.
3. Use following config to generate the sln file.
{
      "name": "x86-Debug",
      "generator": "Visual Studio 16 2019",
      "configurationType": "Debug",
      "buildRoot": "${projectDir}\\out\\build\\${name}",
      "installRoot": "${projectDir}\\out\\install\\${name}",
      "cmakeCommandArgs": "",
      "inheritEnvironments": [ "msvc_x86" ],
 }
4. Open the vcpkg.sln file with VS2019 16.11.13.
5. Build vcpkg successfully with debug x86.

I used the latest commit of vcpkg-tool: https://github.com/microsoft/vcpkg-tool/commit/66a6ae191a6ccc10e38f84a798cf2a1a6bbe991e, and my VS is VS2019 16.11.13.
What's the version of your vcpkg-tool and VS? 
Could you please provide your repro steps to me?

BTW, If you clone the https://github.com/Microsoft/vcpkg and run the bootstrap-vcpkg.bat script, you will get the latest vcpkg.exe directly without having to build it manually.

**Comment by gvanem** [comment] 2022-04-26 05:39
I figured it out; it seems `cl -std:c++latest` is needed. With `cl -std:c++17`, I get the above error `C2593`.
To make things worse a `clang-cl -std:c++latest` does not work. Gotta love the mess with these C++ standards.

> the bootstrap-vcpkg.bat script, you will get the latest vcpkg.exe directly without having to build it manually.

I tried it. Does only work if I edit to simply say: `powershell.exe %~dp0scripts\bootstrap.ps1 %*`

**Comment by Cheney-W** [comment] 2022-04-26 07:22
1. I can't reproduce the error C2593 with /std:c++17, in the vcpkg.sln project generated with cmake, /std:c++17 option is used by default. On the contrary, I encountered other compilation error with /std:c++latest.

2. In the bootstrap.ps1 file, vcpkg.exe will be download with the line 52:
`& "$scriptsDir/tls12-download.exe" github.com "/microsoft/vcpkg-tool/releases/download/$versionDate/vcpkg.exe" "$vcpkgRootDir\vcpkg.exe"`
In general, we do not recommend that users build vcpkg.exe themselves. We deliberately separate vcpkg-tool from vcpkg to provide users with stable and available vcpkg.exe, this can avoid all kinds of problems that users encounter when building vcpkg.exe with the their self's environment.

**Comment by Thomas1664** [comment] 2022-08-03 17:15
@Cheney-W The compiler errors with C++ latest were fixed in were fixed in https://github.com/microsoft/vcpkg-tool/pull/643

**Comment by Cheney-W** [comment] 2022-08-05 07:42
Thanks for posting this issue. Please reopen this issue if this is still a problem for you.

**Closed by Cheney-W** 2022-08-05 07:42 UTC
Labels: requires:repro
