### ISSUE TITLE
libpng does not build for arm-uwp

### ISSUE THREAD

**Issue by stammen** [Microsoft/vcpkg#510] opened 2017-01-10 15:27 UTC
libpng does not build for arm-uwp. It is incorrectly being built as arm desktop and the build fails. x86-uwp and x64-uwp seem to be building but need to be checked if they are correct uwp dlls.

**Comment by codicodi** [comment] 2017-01-10 16:05
> need to be checked if they are correct uwp dlls

I think post-build checks take care of that automatically.

Besides, libpng:arm-uwp builds fine for me - looks like the problem is more subtle.

**Comment by stammen** [comment] 2017-01-10 16:16
The arm-uwp build fails with the support projects genfiles, gensym, and genvers. The following error is produced:

1>C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\ucrt\corecrt.h(226): fatal error C1189: #error:  Compiling Desktop applications for the ARM platform is not supported.

These projects probably need to be x86/

**Comment by ras0219-msft** [comment] 2017-01-19 01:37
I'm getting the same behavior as @codicodi; the arm build of libpng works on my machine. Are you using the latest version of Vcpkg (0.0.67) and libpng (1.6.24-1)?

**Comment by zabulus** [comment] 2017-06-01 05:01
I can confirm that on:
```Vcpkg version: 0.0.81-18f9d17a6b2ff14deba779461bc9aea9c3c4cc98```
and ``` libpng-1.6.28 ``` this builds fione

**Comment by ras0219-msft** [comment] 2017-06-02 00:25
Thanks for independently confirming this. I'm going to close this issue for now; I'd be happy to reopen it if we get another repro.

**Closed by ras0219-msft** 2017-06-02 00:25 UTC
Labels: needs-repro

**Comment by stammen** [comment] 2017-06-02 01:11
@ras0219-msft  I can also confirm libpng:arm-uwp builds in the current version of vcpkg
