### ISSUE TITLE
[libtorch] build failure

### ISSUE THREAD

**Issue by IgorWojas** [microsoft/vcpkg#37924] opened 2024-04-02 18:15 UTC
### Operating system

windows 10

### Compiler

msvc 2022

### Steps to reproduce the behavior

```Shell
./vcpkg install libtorch
```

### Failure logs

Computing installation plan...
The following packages will be built and installed:
    libtorch:x64-windows -> 1.12.1#3
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\HP\AppData\Local\vcpkg\archives in 1.16 ms. Use --debug to see more details.
Installing 1/1 libtorch:x64-windows...
Building libtorch:x64-windows...
-- Using cached pytorch-pytorch-v1.12.1.tar.gz.
-- Cleaning sources at C:/Users/HP/vcpkg/buildtrees/libtorch/src/v1.12.1-e1cb316ec6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/HP/vcpkg/downloads/pytorch-pytorch-v1.12.1.tar.gz
-- Applying patch pytorch-pr-85958.patch
-- Applying patch fix-cmake.patch
-- Applying patch fix-fbgemm-include.patch
-- Applying patch fix-c10-glog.patch
-- Applying patch use-flatbuffers2.patch
-- Applying patch fix-windows.patch
-- Applying patch fix_werror.patch
-- Using source at C:/Users/HP/vcpkg/buildtrees/libtorch/src/v1.12.1-e1cb316ec6.clean
-- Using flatc: C:/Users/HP/vcpkg/installed/x64-windows/tools/flatbuffers/flatc.exe
-- Using protoc: C:/Users/HP/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Users/HP/vcpkg/downloads/tools/python/python-3.11.5-x64/Scripts/pip.exe install virtualenv --no-warn-script-location
    Working Directory: C:/Users/HP/vcpkg/buildtrees/libtorch
    Error code: 1
    See logs for more information:
      C:\Users\HP\vcpkg\buildtrees\libtorch\pip-install-virtualenv-x64-windows-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:62 (vcpkg_execute_required_process)
  ports/libtorch/portfile.cmake:35 (x_vcpkg_get_python_packages)
  scripts/ports.cmake:168 (include)

error: building libtorch:x64-windows failed with: BUILD_FAILED
Elapsed time to handle libtorch:x64-windows: 19 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libtorch
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[libtorch]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2FHP%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

err log: 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Scripts\pip.exe\__main__.py", line 4, in <module>
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\cli\autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\cli\main_parser.py", line 9, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\build_env.py", line 19, in <module>
    from pip._internal.cli.spinners import open_spinner
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\cli\spinners.py", line 9, in <module>
    from pip._internal.utils.logging import get_indentation
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\utils\logging.py", line 29, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\utils\misc.py", line 44, in <module>
    from pip._internal.locations import get_major_minor_version
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\locations\__init__.py", line 14, in <module>
    from . import _sysconfig
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\locations\_sysconfig.py", line 11, in <module>
    from .base import change_root, get_major_minor_version, is_osx_framework
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\locations\base.py", line 9, in <module>
    from pip._internal.utils import appdirs
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_internal\utils\appdirs.py", line 13, in <module>
    from pip._vendor import platformdirs as _appdirs
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 46, in <module>
    PlatformDirs = _set_platform_dir_class()  #: Currently active platform
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_vendor\platformdirs\__init__.py", line 26, in _set_platform_dir_class
    from pip._vendor.platformdirs.windows import Windows as Result
  File "C:\Users\HP\vcpkg\downloads\tools\python\python-3.11.5-x64\Lib\site-packages\pip\_vendor\platformdirs\windows.py", line 4, in <module>
    import ctypes
  File "ctypes\__init__.py", line 8, in <module>
ImportError: DLL load failed while importing _ctypes: Nie można odnaleźć określonego modułu.

**Comment by IgorWojas** [comment] 2024-04-02 20:13
i have deleted all python related stuff i could find and now i cab get through venv but:

PS C:\Users\HP\vcpkg> ./vcpkg install libtorch
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
The following packages will be built and installed:
    libtorch[core,xnnpack]:x64-windows -> 1.12.1#3
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\HP\AppData\Local\vcpkg\archives in 778 us. Use --debug to see more details.
Installing 1/1 libtorch:x64-windows...
Building libtorch[core,xnnpack]:x64-windows...
-- Using cached pytorch-pytorch-v1.12.1.tar.gz.
-- Cleaning sources at C:/Users/HP/vcpkg/buildtrees/libtorch/src/v1.12.1-e1cb316ec6.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Users/HP/vcpkg/downloads/pytorch-pytorch-v1.12.1.tar.gz
-- Applying patch pytorch-pr-85958.patch
-- Applying patch fix-cmake.patch
-- Applying patch fix-fbgemm-include.patch
-- Applying patch fix-c10-glog.patch
-- Applying patch use-flatbuffers2.patch
-- Applying patch fix-windows.patch
-- Applying patch fix_werror.patch
-- Using source at C:/Users/HP/vcpkg/buildtrees/libtorch/src/v1.12.1-e1cb316ec6.clean
-- Using flatc: C:/Users/HP/vcpkg/installed/x64-windows/tools/flatbuffers/flatc.exe
-- Using protoc: C:/Users/HP/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe
-- Setting up python virtual environmnent...
-- Installing python packages: typing-extensions;pyyaml;numpy
-- Setting up python virtual environmnent...finished.
-- Using Python3: C:/Users/HP/vcpkg/buildtrees/libtorch/x64-windows-venv/Scripts/python.exe
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target torch_cpu -- -v -j9
    Working Directory: C:/Users/HP/vcpkg/buildtrees/libtorch/x64-windows-dbg
    See logs for more information:
      C:\Users\HP\vcpkg\buildtrees\libtorch\build-torch_cpu-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  ports/libtorch/portfile.cmake:158 (vcpkg_cmake_build)
  scripts/ports.cmake:168 (include)


error: building libtorch:x64-windows failed with: BUILD_FAILED

[build-torch_cpu-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/14843209/build-torch_cpu-x64-windows-dbg-out.log)


and err log in attachment

**Comment by JonLiu1993** [comment] 2024-04-03 07:27
Duplicate of PR #35202
````
C:\Users\HP\vcpkg\buildtrees\libtorch\src\v1.12.1-e1cb316ec6.clean\aten\src\ATen/cpu/vec/vec_base.h(134): fatal error C1001: Wewnętrzny błąd kompilatora.
(plik kompilatora „D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\toinil.c”, wiersz 910)
 Aby obejść ten problem, spróbuj uprościć lub zmienić program w pobliżu miejsc wymienionych na liście powyżej.
Jeśli to możliwe, podaj kroki umożliwiające odtworzenie na stronie https://developercommunity.visualstudio.com 
Wybierz polecenie Pomoc techniczna w menu Pomoc 
 Visual C++ lub otwórz plik pomocy technicznej, aby uzyskać więcej informacji
````

**Closed by JonLiu1993** 2024-04-03 07:27 UTC
Labels: category:port-bug
