### ISSUE TITLE
[openmvg] include error

### ISSUE THREAD

**Issue by FishHe** [microsoft/vcpkg#12905] opened 2020-08-14 07:17 UTC
I use Vcpkg global integration. Other libs works fine.
When I include openMVG/robust_estimation/robust_estimator_ACRansac.hpp, the file "third_party/histogram/histogram.hpp" can't be found.

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1083	无法打开包括文件: “third_party/histogram/histogram.hpp”: No such file or directory	MVRGlobalSFM	D:\vcpkg\installed\x64-windows-static-md\include\openMVG\robust_estimation\robust_estimator_ACRansac.hpp	50

**Comment by LilyWangL** [comment] 2020-08-14 08:44
Waiting for PR #12895 merged, it fix `lapack-reference` build failed.

**Comment by LilyWangL** [comment] 2020-08-18 10:10
The related source issue: https://github.com/openMVG/openMVG/issues/1782

**Comment by JackBoosY** [comment] 2022-02-05 08:05
So, according to the upstream reply, we should fix this path in vcpkg side.

**Comment by LilyWangLL** [comment] 2023-04-20 09:03
Sorry for the late reply. 

If the "Vcpkg global integration" you mentioned refers to the "vcpkg integrate install" command, then this issue is by design. After executing this command, vcpkg only adds the `installed\{triplet}\include` path to the `INCLUDE DIRECTORIES` environment variable, while the folder path named after the port in the "include" directory will not be added. This is the reason why `third_party/histogram/histogram.hpp` cannot be found.

To fix this issue, there are two solutions:

1. Manually add the `${CMAKE_INSTALL_PREFIX}/include/openMVG` path to the `INCLUDE DIRECTORIES` of VS project.
2. Use CMake to build the VS project. vcpkg provides below usage of `openmvg`:
```
find_package(OpenMVG CONFIG REQUIRED)
target_link_libraries(main PRIVATE OpenMVG::openMVG_sfm OpenMVG::openMVG_exif OpenMVG::openMVG_fast OpenMVG::openMVG_kvld)
```
Link targets `OpenMVG::openMVG_sfm` or `OpenMVG::openMVG_kvld` will add `installed\{triplet}\include` and `installed\{triplet}\include\openMVG` to the `INCLUDE DIRECTORIES` environment variable together.

**Closed** 2023-04-20 09:03 UTC
Labels: category:question
