### ISSUE TITLE
Running vcpkg from within `cmd.exe` such that `vcvarsall.bat` runs, installs the embedded-into-VS copy's doskey macro

### ISSUE THREAD

**Issue by DougRogers** [microsoft/vcpkg#32641] opened 2023-07-19 19:23 UTC
```
C:\vcpkg>vcpkg list
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
```

This is after a new install and clearing caches

```
Normal calls
C:\>git clone https://github.com/Microsoft/vcpkg.git
C:\>.\vcpkg\bootstrap-vcpkg.bat

```
install packages

```
C:\vcpkg>vcpkg integrate install
C:\vcpkg>
C:\vcpkg>vcpkg list
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.

```

**Comment by DougRogers** [comment] 2023-07-19 19:25
After starting a new CLI, list works

**Comment by DougRogers** [comment] 2023-07-19 19:58
later, I get the following error

```
C:\vcpkg>vcpkg search openimageio --featurepackages
error: this vcpkg instance requires a manifest with a specified baseline in order to interact with ports. Please add 'builtin-baseline' to the manifest or add a 'vcpkg-configuration.json' that redefines the default registry.

```

**Comment by DougRogers** [comment] 2023-07-19 19:59
And another new prompt solves that issue,

**Comment by LilyWangLL** [comment] 2023-07-20 08:54
This issue cannot reproduce on the latest vcpkg, the similar issue: https://github.com/microsoft/vcpkg/issues/32026.
My repro logs:

```
Microsoft Windows [Version 10.0.22621.1992]
(c) Microsoft Corporation. All rights reserved.

C:\>git clone https://github.com/Microsoft/vcpkg.git
Cloning into 'vcpkg'...
remote: Enumerating objects: 199719, done.
remote: Counting objects: 100% (14950/14950), done.
remote: Compressing objects: 100% (402/402), done.
remote: Total 199719 (delta 14662), reused 14631 (delta 14548), pack-reused 184769
Receiving objects: 100% (199719/199719), 64.29 MiB | 25.33 MiB/s, done.
Resolving deltas: 100% (130595/130595), done.
Updating files: 100% (10349/10349), done.

C:\>.\vcpkg\bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-06-22/vcpkg.exe -> C:\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

C:\>cd vcpkg

C:\vcpkg>vcpkg.exe integrate install
Applied user-wide integration for this vcpkg root.
CMake projects should use: "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

All MSBuild C++ projects can now #include any installed libraries. Linking will be handled automatically. Installing new libraries will make them instantly available.

C:\vcpkg>vcpkg.exe install zlib:x64-windows
Computing installation plan...
A suitable version of cmake was not found (required v3.25.1) Downloading portable cmake 3.25.1...
Downloading cmake...
......
The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)

C:\vcpkg>vcpkg.exe list
vcpkg-cmake:x64-windows                           2023-05-04
zlib:x64-windows                                  1.2.13              A compression library
```

**Comment by JiK** [comment] 2023-07-23 21:29
I'm having the same problem with a fresh install. After every `vcpkg install` command, I have to restart cmd.exe. I don't think I used admin mode at any point.

**Comment by dg0yt** [comment] 2023-07-24 06:48
> ~~~
> C:\vcpkg>vcpkg.exe install zlib:x64-windows

`vcpkg.exe` will be searched via the environment variable `PATH`. This may or may not be the same as running `.\vcpkg.exe`, the executable in the current working directory...

**Comment by DougRogers** [comment] 2023-08-06 21:57
I am still having problems.  How can this be resolved?

```
C:\vcpkg>vcpkg install opencv[tbb]:x64-windows --recurse
Computing installation plan...
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
```

**Comment by zoenie123** [comment] 2023-08-12 08:58
Solution1: starting a new command prompt each time before a new command
Solution2: use .\vcpkg instead of vcpkg
Both of them seemed to work for me.

**Comment by NeoxyCN** [comment] 2023-08-13 05:56
I added vcpkg to PATH and then I must use a new cmd for a new command.
Before I clone the lastest vcpkg repo, it worked correctly.

**Comment by ras0219-msft** [comment] 2023-08-24 01:44
This most likely caused by your prompt getting confused between a copy of vcpkg coming from Visual Studio (which does not support classic mode) and a separate copy of vcpkg you've installed yourself. To confirm this, run `where.exe vcpkg`:

```
>where.exe vcpkg
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\vcpkg\vcpkg.exe
C:\src\vcpkg\vcpkg.exe
```
and check the value of `VCPKG_ROOT`:
```
>echo %VCPKG_ROOT%
C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\vcpkg
```

You can fix this in a few ways:
1. Use [Manifest Mode](https://learn.microsoft.com/vcpkg/users/manifests) instead of Classic Mode.
2. Set `VCPKG_ROOT` to the vcpkg instance you want to use. This will be cleared when you close your command prompt.
3. Unset `VCPKG_ROOT` and invoke vcpkg with a specific path instead of `vcpkg`.
4. Uninstall the vcpkg optional package from your Visual Studio instance.

**Comment by DougRogers** [comment] 2023-08-24 01:48
VCPKG_ROOT was not set.
```
C:\Windows\System32>echo %VCPKG_ROOT%
%VCPKG_ROOT%
```

**Comment by DougRogers** [comment] 2023-08-24 03:12
I set the root and still get
```
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.
```

I'm not sure why this is complicated.  I'm just trying to use it at the command line.  I don't need or want manifest mode, I just want the packages to install.

**Comment by BillyONeal** [comment] 2023-08-24 16:59
What does `where vcpkg` say?

**Comment by DougRogers** [comment] 2023-08-24 17:03
I don't understand.  I'm not talking about VS integration, just the command line not working.

**Comment by ras0219-msft** [comment] 2023-08-24 18:08
In a command prompt with the incorrect behavior, can you please run BOTH:
```
echo %VCPKG_ROOT%
```
and
```
where.exe vcpkg
```
and reply with the results?

**Comment by DougRogers** [comment] 2023-08-24 19:41
```
C:\vcpkg>echo %VCPKG_ROOT%
C:\vcpkg

C:\vcpkg>where.exe vcpkg
C:\vcpkg\vcpkg
C:\vcpkg\vcpkg.exe

```

**Comment by DougRogers** [comment] 2023-09-03 22:59
More errors

```
C:\vcpkg>vcpkg search gstreamer
error: this vcpkg instance requires a manifest with a specified baseline in order to interact with ports. Please add 'builtin-baseline' to the manifest or add a 'vcpkg-configuration.json' that redefines the default registry.
```

**Comment by BillyONeal** [comment] 2023-09-07 00:16
Is there a `C:\vcpkg\vcpkg-bundle.json`?

**Comment by z3dxz** [comment] 2023-09-07 00:36
It worked if I used powershell with ./ instead of cmd

**Comment by BillyONeal** [comment] 2023-09-07 06:50
> It worked if I used powershell with ./ instead of cmd

If this is powershell the equivalent of the `where` command above we need is `Get-Command`. As in, `Get-Command vcpkg`.

It is highly likely that there is a bug here but I'm still grasping at straws as to what the trigger is.

**Comment by DougRogers** [comment] 2023-09-07 15:50
> Is there a `C:\vcpkg\vcpkg-bundle.json`?

No,  there are no json files in this directory,

**Comment by theoractice** [comment] 2023-10-05 06:03
Hey everyone,
I'm having the same problem, but I am also using `cmder` for terminal, and the `clink` package that comes with it has just give me some clue.
When the problem occurs, `vcpkg` is rendered in `cyan`, just like `clink` itself. This means `vcpkg` here is an alias. So I checked:
```
D:\Coding\vcpkg (master -> origin)
⠕ doskey /macros
pwd=cd
;=Add aliases below here
gl=git log --oneline --all --graph --decorate  $*
e.=explorer .
clink="C:\cmder\vendor\clink\clink_x64.exe" $*
history="C:\cmder\vendor\clink\clink_x64.exe" history $*
ls=ls --show-control-chars -F --color $*
clear=cls
unalias=alias /d $1
vi=vim $*
cmderr=cd /d "%CMDER_ROOT%"
vcpkg="C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\vcpkg\vcpkg-cmd.cmd" $*
```

And after I removed vcpkg from the doskey macros(aliases) list, everything is back to normal again. Just type
```
D:\Coding\vcpkg (master -> origin)
⠕ doskey vcpkg=
```

@BillyONeal @ras0219-msft Hope this helps you to locate the root cause of the problem.

**Comment by dg0yt** [comment] 2023-10-05 06:11
As noted in https://github.com/microsoft/vcpkg/issues/32641#issuecomment-1647313037, for most installations, `vcpkg` or `vcpkg.exe` is not the same as `.\vcpkg.exe`, the fresh bootstrapped local vcpkg tool.

**Comment by BillyONeal** [comment] 2023-10-05 17:33
> So why is `vcpkg` becoming an alias? @BillyONeal @ras0219-msft Hope this helps you to locate the root cause of the problem.

The 'developer command prompt' installs an alias necessary for `vcpkg use` and `vcpkg activate` to work, since these want to touch environment variables in the enclosing terminal.

**Comment by DougRogers** [comment] 2023-11-03 16:22
I am still having this issue.  How can this be resolved?

**Comment by BillyONeal** [comment] 2023-11-03 22:58
> I am still having this issue. How can this be resolved?

We still don't understand what the issue is or how to reproduce it in order to fix it.

**Comment by theoractice** [comment] 2023-11-05 04:19
> > I am still having this issue. How can this be resolved?
> 
> We still don't understand what the issue is or how to reproduce it in order to fix it.

I think I have already explained that in my previous comment. To reproduce this issue you need:
1. Install Visual Studio 2022 preview.
2. Start a `cmd` console, git clone vcpkg repo and bootstrap.
3. Install anything, e.g. `vcpkg install mimalloc`.
4. Run any vcpkg command, e.g. `vcpkg list`. You will find it's not working now. However `.\vcpkg list` still works.
5. Run `doskey vcpkg=`, then `vcpkg list` works again.

**Comment by BillyONeal** [comment] 2023-11-29 03:38
> 2\. Start a `cmd` console, git clone vcpkg repo and bootstrap.

I'm assuming you mean 'developer command prompt' rather than 'cmd'?

**Comment by theoractice** [comment] 2023-11-29 06:43
> > 2. Start a `cmd` console, git clone vcpkg repo and bootstrap.
> 
> I'm assuming you mean 'developer command prompt' rather than 'cmd'? Because plain cmd doesn't come with any doskeys.

NO. If this is a `developer command prompt` then I probably won't consider it a bug.
Below is a gif reproducing the bug:
![aaa](https://github.com/microsoft/vcpkg/assets/14279372/6ca19209-e1bf-4404-858e-10b0f0ac52cf)
and the whole console output:
```

d:\Repro>doskey /macros

d:\Repro>git clone https://github.com/microsoft/vcpkg
Cloning into 'vcpkg'...
remote: Enumerating objects: 214617, done.
remote: Counting objects: 100% (18055/18055), done.
remote: Compressing objects: 100% (589/589), done.
remote: Total 214617 (delta 17733), reused 17476 (delta 17466), pack-reused 196562
Receiving objects: 100% (214617/214617), 63.27 MiB | 10.21 MiB/s, done.

Resolving deltas: 100% (141552/141552), done.
Updating files: 100% (10924/10924), done.

d:\Repro>cd vcpkg

d:\Repro\vcpkg>bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-11-16/vcpkg.exe -> D:\Repro\vcpkg\vcpkg.exe (using proxy: http://127.0.0.1:9051)... done.
Validating signature... done.

vcpkg package management program version 2023-11-16-4c1df40a3c5c5e18de299a99e9accb03c2a82e1e

See LICENSE.txt for license information.
Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

d:\Repro\vcpkg>vcpkg install zlib
warning: In the September 2023 release, the default triplet for vcpkg libraries changed from x86-windows to the detected host triplet (x64-windows). For the old behavior, add --triplet x86-windows . To suppress this message, add --triplet x64-windows .
Computing installation plan...
A suitable version of cmake was not found (required v3.27.1) Downloading portable cmake 3.27.1...
Downloading cmake...
https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-windows-i386.zip->D:\Repro\vcpkg\downloads\cmake-3.27.1-windows-i386.zip
Downloading https://github.com/Kitware/CMake/releases/download/v3.27.1/cmake-3.27.1-windows-i386.zip
Extracting cmake...
The following packages will be built and installed:
  * vcpkg-cmake:x64-windows -> 2023-05-04
    zlib:x64-windows -> 1.3
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
-- Using %HTTP(S)_PROXY% in environment variables.
A suitable version of powershell-core was not found (required v7.2.11) Downloading portable powershell-core 7.2.11...
Downloading powershell-core...
https://github.com/PowerShell/PowerShell/releases/download/v7.2.11/PowerShell-7.2.11-win-x86.zip->D:\Repro\vcpkg\downloads\PowerShell-7.2.11-win-x86.zip
Downloading https://github.com/PowerShell/PowerShell/releases/download/v7.2.11/PowerShell-7.2.11-win-x86.zip
Extracting powershell-core...
A suitable version of 7zip was not found (required v23.1.0) Downloading portable 7zip 23.1.0...
Downloading 7zip...
https://www.7-zip.org/a/7z2301-extra.7z->D:\Repro\vcpkg\downloads\7z2301-extra.7z
Downloading https://www.7-zip.org/a/7z2301-extra.7z
Extracting 7zip...
Restored 2 package(s) from C:\Users\tpasy\AppData\Local\vcpkg\archives in 38.2 ms. Use --debug to see more details.
Installing 1/2 vcpkg-cmake:x64-windows...
Elapsed time to handle vcpkg-cmake:x64-windows: 4.23 ms
Installing 2/2 zlib:x64-windows...
Elapsed time to handle zlib:x64-windows: 6.73 ms
Total install time: 11.5 ms
The package zlib is compatible with built-in CMake targets:

    find_package(ZLIB REQUIRED)
    target_link_libraries(main PRIVATE ZLIB::ZLIB)


d:\Repro\vcpkg>vcpkg list
error: Could not locate a manifest (vcpkg.json) above the current working directory.
This vcpkg distribution does not have a classic mode instance.

d:\Repro\vcpkg>doskey /macros
vcpkg="C:\Program Files\Microsoft Visual Studio\2022\Community\VC\vcpkg\vcpkg-cmd.cmd" $*

d:\Repro\vcpkg>
```

**Comment by BillyONeal** [comment] 2023-11-30 20:12
I see, OK, I think I know what's happening now.

* `vcpkg install` wants to get a compiler to use. In order to figure that out, it runs `vcvarsall.bat`
* `vcvarsall.bat` has embedded within it the 'comes with Visual Studio' copy of vcpkg, which installs a `doskey` macro in order to enable artifacts scenarios like `vcpkg use`
* Unexpectedly, the doskey macro is being 'inherited'? by the parent process, so it leaks into the caller of `vcpkg install`

Workarounds are either:

* `doskey vcpkg=` to remove the macro after doing this
* going around the doskey macro by saying `vcpkg.exe` rather than `vcpkg`

I never noticed this because all my shells start with pwsh and Windows Terminal and apparently something in that combo causes this inheritance to not happen.

I ... don't have great ideas on fixing this. Maybe doing the `vcvarsall.bat` call with `CREATE_NEW_CONSOLE` might fix it but really this is kind of an overall design issue with how artifacts interacts with consoles :(

**Comment by BillyONeal** [comment] 2023-12-01 02:05
OK I think I have a workaround in https://github.com/microsoft/vcpkg-tool/pull/1295

**Comment by BillyONeal** [comment] 2024-01-13 01:31
OK, should be fixed by https://github.com/microsoft/vcpkg/pull/36141 . Thanks again!

**Comment by theoractice** [comment] 2024-05-10 13:05
@BillyONeal
Hi, I just discovered that the same problem occured again after installing `blaze` library
```
vcpkg install blaze:x64-windows-static
```
on a newly cloned vcpkg repo.


Maybe we need another fix?

**Comment by BillyONeal** [comment] 2024-05-14 21:57
Unfortunately I'm out of ideas on workarounds this time.

**Comment by BillyONeal** [comment] 2024-06-26 22:06
We are considering renaming the shell function to something else to avoid this confusion

**Comment by BillyONeal** [comment] 2024-08-01 19:14
Looks like 17.12 is going to be the release with this changed as this would have to go through endless paperwork to get into 17.11

**Comment by BillyONeal** [comment] 2024-12-10 21:35
As far as I know now that 17.12 is out this issue is now fixed.

**Closed by BillyONeal** 2024-12-10 21:35 UTC
Labels: category:question, requires:tool-release
