### ISSUE TITLE
[re2] Build error on arm64-osx

### ISSUE THREAD

**Issue by 1-30205** [microsoft/vcpkg#38152] opened 2024-04-12 13:26 UTC
Computing installation plan...
The following packages will be built and installed:
    grpc[codegen,core]:arm64-osx@1.51.1#3
  * re2:arm64-osx@2024-04-01#1
  * upb[codegen,core]:arm64-osx@2022-06-21#1
  * zlib:arm64-osx@1.3.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-osx...
Compiler found: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
Restored 0 package(s) from /Users/wubo/.cache/vcpkg/archives in 14.2 us. Use --debug to see more details.
Installing 1/4 re2:arm64-osx@2024-04-01#1...
Building re2:arm64-osx@2024-04-01#1...
-- Downloading https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1 -> 9ebe4a22cad8a025b68a9594bdff3c047a111333.patch...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from /Users/wubo/.vcpkg/vcpkg/vcpkg-bundle.json
[DEBUG] Failed to open: /Users/wubo/.vcpkg/vcpkg/vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
[DEBUG] 1000: execute_process(curl --fail -L https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1 --create-dirs --output /Users/wubo/.vcpkg/vcpkg/downloads/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.47658.part)
[DEBUG] 1000: cmd_execute_and_stream_data() returned 0 after   906484 us
[DEBUG] Trying to hash /Users/wubo/.vcpkg/vcpkg/downloads/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.47658.part
[DEBUG] /Users/wubo/.vcpkg/vcpkg/downloads/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.47658.part has hash 83c1a4cc4ddd6e1443f5201f7f00cf6a0729d0a0fb8fc5068c3d80766238d72f019f1fddaeffebcc2d4322a07daf2203214121cdda039b10a5f39214b9fa8647
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/google/re2/commit/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch?full_index=1
File: /Users/wubo/.vcpkg/vcpkg/downloads/9ebe4a22cad8a025b68a9594bdff3c047a111333.patch.47658.part
Expected hash: 167a0153bf24e77db2b8555a7d6391acf740dc4720a71e6ce19a3533c7e0a49923d9584ff32544a454837a25eedace00cb2ef9ddbf4250deb5f2c5aeda04ac26
Actual hash: 83c1a4cc4ddd6e1443f5201f7f00cf6a0729d0a0fb8fc5068c3d80766238d72f019f1fddaeffebcc2d4322a07daf2203214121cdda039b10a5f39214b9fa8647
[DEBUG] /Users/runner/work/1/s/src/vcpkg/base/downloads.cpp(1031): 
[DEBUG] Time in subprocesses: 906484us
[DEBUG] Time in parsing JSON: 0us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 273us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 908 ms (906894us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  ports/re2/portfile.cmake:1 (vcpkg_download_distfile)
  scripts/ports.cmake:175 (include)

**Comment by dg0yt** [comment] 2024-04-13 03:29
Fixed by https://github.com/microsoft/vcpkg/pull/38148.

**Comment by WangWeiLin-MV** [comment] 2024-04-15 01:46
Duplicate of #38146

**Closed by WangWeiLin-MV** 2024-04-15 01:46 UTC
Labels: category:port-bug
