### ISSUE TITLE
[qtwebengine] Build error on x64-windows

### ISSUE THREAD

**Issue by shiyebo** [microsoft/vcpkg#35975] opened 2024-01-02 02:37 UTC
Copy issue body from D:/vcpkg/installed/vcpkg/issue_body.md
[issue_body.md](https://github.com/microsoft/vcpkg/files/13806770/issue_body.md)

i tried for several days and my work cannot be continued...

**Comment by shiyebo** [comment] 2024-01-02 08:15
I tried these steps:
1.search error info online;
2.rebuild my vcpkg at least 5 times;
3.rebuild my vs2019 package with amd64 options.

but time is limit and i have done nothing in progress now.
maybe i should give up using qtwebegine in my vcpkg qt environment  ORZ

**Comment by Cheney-W** [comment] 2024-01-02 10:17
Duplicate of https://github.com/microsoft/vcpkg/issues/35843

**Closed by Cheney-W** 2024-01-02 10:17 UTC
