### ISSUE TITLE
Install results in "Computing installation plan..." and then nothing

### ISSUE THREAD

**Issue by Wouterdek** [microsoft/vcpkg#18818] opened 2021-07-05 13:57 UTC
**Describe the bug**
Same as #9943. Trying to install any package results in "Computing installation plan..." and then vcpkg just exits.

**Environment**
Brand new, fresh install of Windows 10:
- OS: Windows 10 Build 19043.928
- Compiler: MSVC v142 (Installed along with VS 2019 "Desktop development with C++")

**To Reproduce**
1. ./vcpkg install xxxx
2. See  "Computing installation plan..."
3. vcpkg exits without installing anything

**Expected behavior**
Vcpkg should continue to install the package

**Failure logs** 
I'm not sure where to find logs.

**Additional context**
I've tried rebooting, deleting and reinstalling vcpkg, running bootstrap and integrate again.

**Comment by CCRcmcpe** [comment] 2021-07-05 14:41
Same, is it a server fault?

**Comment by autoantwort** [comment] 2021-07-05 15:17
Duplicate of #18636

**Comment by JonLiu1993** [comment] 2021-07-06 01:57
@Wouterdek ,Thanks for posting this  issue,
This issue duplicate of #18636,please refer to the solution of issue #18636

**Closed by JonLiu1993** 2021-07-06 01:57 UTC

**Comment by Wouterdek** [comment] 2021-07-06 08:26
That fixed my issue, thanks!

**Comment by manojimentus** [comment] 2021-07-06 12:33
https://github.com/microsoft/vcpkg/issues/18636#issuecomment-868555508
just go for this comment
