### ISSUE TITLE
libpg build failed windows10 x64

### ISSUE THREAD

**Issue by rfoz-git** [microsoft/vcpkg#12576] opened 2020-07-26 05:32 UTC
Build process
Building package libpq[core,openssl,zlib]:x64-windows...
-- Using cached D:/vcpkg-2020.06/downloads/postgresql-12.2.tar.bz2
-- Using source at D:/vcpkg-2020.06/buildtrees/libpq/src/tgresql-12-3dcd887135
-- Copying libpq source files to D:/vcpkg-2020.06/buildtrees/libpq/x64-windows-rel...
-- Copying libpq source files... done
-- Applying patch patches/windows/Solution_RELEASE.patch
-- Applying patch patches/windows/python3_build_RELEASE.patch
-- Patches applied!
-- Building libpq x64-windows-RELEASE...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: D:/vcpkg-2020.06/downloads/tools/perl/perl/bin/perl.exe build.pl RELEASE libpq
    Working Directory: D:/vcpkg-2020.06/buildtrees/libpq/x64-windows-rel/src/tools/msvc
    Error code: 53
    See logs for more information:
      D:\vcpkg-2020.06\buildtrees\libpq\build-libpq-x64-windows-RELEASE-out.log
      D:\vcpkg-2020.06\buildtrees\libpq\build-libpq-x64-windows-RELEASE-err.log

Call Stack (most recent call first):
  ports/libpq/portfile.cmake:214 (vcpkg_execute_required_process)

Error log 
Unable to determine OpenSSL version: The openssl.exe command wasn't found. at D:\vcpkg-2020.06\buildtrees\libpq\x64-windows-rel\src\tools\msvc/Mkvcbuild.pm line 147.

I am pretty sure i have compiled openssl,and i remove and rubuild it,but fialed too.anyone has sloved this problem?
Please tell me,thanks

  scripts/ports.cmake:76 (include)

**Comment by StarGate-One** [comment] 2020-07-26 17:53
Maybe duplicate of #12443

**Comment by rfoz-git** [comment] 2020-07-27 01:22
> Maybe duplicate of #12443
> **Unable to determine OpenSSL version: The openssl.exe command wasn't found**

Thanks

**Comment by JackBoosY** [comment] 2020-07-27 03:15
Duplicate with #12443, please track that issue.

**Closed by JackBoosY** 2020-07-27 03:15 UTC
