### ISSUE TITLE
[fontconfig] build failure using versioning

### ISSUE THREAD

**Issue by csorvagep** [microsoft/vcpkg#17155] opened 2021-04-08 14:17 UTC
**Host Environment**
- OS: Windows 10 20H2
- Compiler: MSVC 16.9.3

**To Reproduce**
 1. vcpkg versioning enabled by env var
 2. CMake project generated with CMakeTools
 3. Use the following manifest file 
 4. Configure

``` json
{
    "name": "vctest",
    "version": "1.0",
    "dependencies": [
        "fontconfig"
    ],
    "builtin-baseline": "4278a5f9eafbdadfaa65d7aafd914964841cba42"
}
```

**Failure logs** 
```
Starting package 16/16: fontconfig:x64-windows
Building package fontconfig[core]:x64-windows...
-- Installing port from location: D:\local\vcpkg\buildtrees\versioning\versions\fontconfig\2b49a3ee02b25efc3101d849a0df38280a1ca299
-- Using cached D:/local/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Extracting source D:/local/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch macos_arm_fccache.patch
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:57 (message):
  Applying patch failed: error: corrupt patch at line 10

Call Stack (most recent call first):
  scripts/cmake/vcpkg_extract_source_archive_ex.cmake:144 (z_vcpkg_apply_patches)
  scripts/cmake/vcpkg_from_gitlab.cmake:139 (vcpkg_extract_source_archive_ex)
  buildtrees/versioning/versions/fontconfig/2b49a3ee02b25efc3101d849a0df38280a1ca299/portfile.cmake:7 (vcpkg_from_gitlab)
  scripts/ports.cmake:142 (include)
```

**Additional context**
Without the "builtin-baseline" there is no error. The baseline included above, uses the current commit of vcpkg I'm at.

**Comment by vicroms** [comment] 2021-04-09 17:44
@csorvagep I tried to reproduce the issue locally without success. 

```
The following packages will be rebuilt:
    fontconfig[core]:x64-windows -> 2.13.1#4 -- D:\vcpkg\buildtrees\versioning\versions\fontconfig\2b49a3ee02b25efc3101d849a0df38280a1ca299
Could not locate cached archive: C:\Users\_\AppData\Local\vcpkg\archives\80\8085be4bbb264085a506b1d4108942e78962b0f1.zip
Starting package 2/2: fontconfig:x64-windows
Building package fontconfig[core]:x64-windows...
-- Installing port from location: D:\vcpkg\buildtrees\versioning\versions\fontconfig\2b49a3ee02b25efc3101d849a0df38280a1ca299
-- Using cached D:/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Cleaning sources at D:/vcpkg/buildtrees/fontconfig/src/75c13b2421-03766d577b.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/fontconfig-fontconfig-844d8709a1f3ecab45015b24b72dd775c13b2421.tar.gz
-- Applying patch remove_tests.patch
-- Applying patch build.patch
-- Applying patch build2.patch
-- Applying patch disable-install-data.patch
-- Applying patch macos_arm_fccache.patch
-- Applying patch fix_def_dll_name.patch
-- Using source at D:/vcpkg/buildtrees/fontconfig/src/75c13b2421-03766d577b.clean
-- Configuring x64-windows
-- Using msys root at D:/vcpkg/downloads/tools/msys2/1b7574df3402ae90
-- Using msys root at D:/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Generating configure for x64-windows
-- Finished generating configure for x64-windows
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Using msys root at D:/vcpkg/downloads/tools/msys2/969c0913b9df89e1
-- Building x64-windows-dbg
-- Installing x64-windows-dbg
-- Building x64-windows-rel
-- Installing x64-windows-rel
CMake Warning at scripts/cmake/vcpkg_copy_pdbs.cmake:69 (message):
  Could not find a matching pdb file
  for: 
      D:/vcpkg/packages/fontconfig_x64-windows/bin/fontconfig-1.dll
      D:/vcpkg/packages/fontconfig_x64-windows/debug/bin/fontconfig-1.dll
Call Stack (most recent call first):
  buildtrees/versioning/versions/fontconfig/2b49a3ee02b25efc3101d849a0df38280a1ca299/portfile.cmake:48 (vcpkg_copy_pdbs)
  scripts/ports.cmake:142 (include)
-- Using msys root at D:/vcpkg/downloads/tools/msys2/50864d9fae363d6e
-- Fixing pkgconfig file: D:/vcpkg/packages/fontconfig_x64-windows/lib/pkgconfig/fontconfig.pc
-- Fixing pkgconfig file: D:/vcpkg/packages/fontconfig_x64-windows/debug/lib/pkgconfig/fontconfig.pc
-- Installing: D:/vcpkg/packages/fontconfig_x64-windows/share/fontconfig/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\_\AppData\Local\vcpkg\archives\80\8085be4bbb264085a506b1d4108942e78962b0f1.zip
Building package fontconfig[core]:x64-windows... done
Installing package fontconfig[core]:x64-windows...
Installing package fontconfig[core]:x64-windows... done
```

I'm using the current latest commit and just pointing the `builtin-baseline` to `4278a5f9eafbdadfaa65d7aafd914964841cba42`.  But that shouldn't matter since at the end we get the same portfiles for `fontconfig`.

Can you inspect the contents of the corrupted patch?

**Comment by csorvagep** [comment] 2021-04-09 19:55
I found the patch files in [vcpkg install loc]/ports/fontconfig directory. The log refers to line 10 in the patch which is an empty line. I don't see an problem with it, but here I included the part of the patch and three lines before and after that:

```
+++ b/src/fcatomic.h
@@ -70,24 +70,16 @@ typedef LONG fc_atomic_int_t;
 #elif !defined(FC_NO_MT) && defined(__APPLE__)

 #include <libkern/OSAtomic.h>
-#ifdef __MAC_OS_X_MIN_REQUIRED
 #include <AvailabilityMacros.h>
```
The log tells me to call update and then create an issue, which I did. But I forgot to include the vcpkg version:

`Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e`

**Comment by csorvagep** [comment] 2021-04-09 19:58
Since that I found the portfiles and patch in the [vcpkg install loc]/buildtrees/versioning/fontconfig/2b49a3ee02b25efc3101d849a0df38280a1ca299 The content of the two macos_arm_fccache.patch files are the same.

**Comment by PhoebeHui** [comment] 2021-04-12 09:32
```
CMake Error at scripts/cmake/z_vcpkg_apply_patches.cmake:57 (message):
  Applying patch failed: error: corrupt patch at line 10
```
About the applying failed issue, we have similar issues https://github.com/microsoft/vcpkg/issues/16955 and https://github.com/microsoft/vcpkg/issues/16955.

It may due to the end of line are different in the patch files. Possible solved by https://github.com/microsoft/vcpkg/issues/16615#issuecomment-793892069

@csorvagep, could you try above solution?

**Comment by csorvagep** [comment] 2021-04-12 16:10
@PhoebeHui thanks, that solved for me. But I don't like the idea to set that as a global git config. Is it possible to set that only for vcpkg somehow?

**Comment by strega-nil** [comment] 2021-04-13 00:40
I think the solution here is to pass `-c core.autocrlf=false` to git. We should be doing this everywhere we use the `git` tool from vcpkg.

**Comment by strega-nil** [comment] 2021-04-15 16:22
This is fixed in upstream vcpkg-tool, we need to do a release (once #17269 is fixed)

**Comment by JackBoosY** [comment] 2021-04-16 01:54
Fixed.

**Comment by PhoebeHui** [comment] 2021-05-14 07:42
The new version of vcpkg-tool has released, so please get latest source and try again.

**Closed by PhoebeHui** 2021-05-14 07:42 UTC
Labels: category:vcpkg-bug
