### ISSUE TITLE
[regression] Triplet not recognised anymore

### ISSUE THREAD

**Issue by Brewir** [microsoft/vcpkg#41268] opened 2024-09-30 14:59 UTC
**Describe the bug**
At tag  `2024.09.23`, using `./vcpkg install --triplet x86_64-unknown-linux-gnu --overlay-triplets=${THIRD_PARTY}/vcpkg/overlay-triplets` fails with error :
`error: expected the end of input parsing a package spec; this usually means the indicated character is not allowed to be in a package spec. Port, triplet, and feature names are all lowercase alphanumeric+hypens.`

This triplet comes from a third party library that would be a pain to change the name. Also, this is a regression because it works fine at tag `2024.08.23`

**Environment**
- OS: WSL Debian 12
- Compiler: gcc (Debian 12.2.0-14) 12.2.0 + clang-16.0.6

**To Reproduce**
1. `./vcpkg install --triplet x86_64-unknown-linux-gnu --overlay-triplets=${THIRD_PARTY}/vcpkg/overlay-triplets`
2. `error: expected the end of input parsing a package spec; this usually means the indicated character is not allowed to be in a package spec. Port, triplet, and feature names are all lowercase alphanumeric+hypens.`
Repro code when

**Expected behavior**
The configuration of vcpkg triplet works

**Additional context**
I'm using vcpkg to build a library for a program using specific compiler. It furnishes the triplet with this name

**Comment by Thomas1664** [comment] 2024-09-30 15:12
> triplets fails with error :
> error: expected the end of input parsing a package spec; this usually means the indicated character is not allowed to be in a package spec. Port, triplet, and feature names are all lowercase alphanumeric+hypens.

As the error message says: your triplet name is invalid because it contains an underscore

**Comment by Brewir** [comment] 2024-09-30 15:18
> As the error message says: your triplet name is invalid because it contains an underscore

It is a regression, it was working fine before. Why was it changed to make it not work anymore?

I can't change the name of the triplet as it comes from a third party  source.

**Comment by Thomas1664** [comment] 2024-09-30 17:35
> It is a regression, it was working fine before. Why was it changed to make it not work anymore?

No, this is actually the intended behavior: https://github.com/microsoft/vcpkg-tool/pull/1474, [docs](https://learn.microsoft.com/vcpkg/concepts/triplets#custom-triplets)

> I can't change the name of the triplet as it comes from a third party source.

Technically, you could rename the triplet like so as part of your CI: `mv x86_64-unknown-linux-gnu.cmake x86-64-unknown-linux-gnu.cmake && vcpkg install ...`

**Comment by victorlazaro** [comment] 2024-10-03 17:19
This is also a regression for those using manifest mode. We're having to change our triplets from `x86_64`, a pretty standard ABI accepted by CMake, to something else.

**Comment by Brewir** [comment] 2024-10-08 08:18
As it seems I'm not the only one, I reopen this issue in the hope the "no underscores" rule will be changed

**Comment by Brewir** [comment] 2024-11-11 10:00
The point is that the design needs to change to authorize it again as there is no good reasons to forbid _ character in triplet names

**Comment by BillyONeal** [comment] 2024-11-13 00:35
If we are claiming we are parsing a package spec while parsing `--triplet`, I believe that is a bug. I don't believe forbidding `_` is a bug, that has been the documented behavior for all identifiers in the product for a very long time. I believe the 'regression' you're seeing is that we fixed it not being checked in a few places. (In particular, parsing the triplet name out of `port-name:triplet-name[features]` always depended on triplet-name only having identifier characters in it)

I'll ask around to see if other maintainers think we should change this but I'm at most neutral on the subject.

**Comment by BillyONeal** [comment] 2024-11-13 00:39
This change was https://github.com/microsoft/vcpkg-tool/pull/1474 "Disallow invalid triplet names to `--triplet`" , which fixed https://github.com/microsoft/vcpkg/issues/10120

**Comment by BillyONeal** [comment] 2024-11-13 00:46
> If we are claiming we are parsing a package spec while parsing `--triplet`, I believe that is a bug.

No repro on this part, at least with 2024-11-12:

```console
PS D:\vcpkg> .\vcpkg.exe --triplet with_underscores install zlib
error: Invalid triplet name. Triplet names are all lowercase alphanumeric+hyphens.
  on expression: with_underscores
                     ^
Built-in Triplets:
```

**Comment by Brewir** [comment] 2024-11-15 20:15
Well... that's exactly the point... everything was working fine with triplets having `_`, but when then the "fix" it was not working anymore for just an obscure line in the spec.
I really think that `_` should be allowed again as it is pretty standard, and even more as it allows to build the triplet name directly using the `arch` command from linux.

**Comment by woshizhangbowen** [comment] 2024-11-24 03:06
hello，Unfortunately,I have a same question in my two computers.In Windows10,VS2022 and newest VCPKG .If I use 
**vcpkg install zlib:x64-windows**     
it will show me an error : error: 
Invalid triplet name. Triplet names are all lowercase alphanumeric+hyphens.
  on expression: x64_windows
Built-in Triplets:
  arm-neon-android
  arm64-android
  arm64-osx
  arm64-uwp
  arm64-windows

But if I write like this:
**vcpkg install zlib --triplet=x64-windows**
It works.   But this error  already happened tow month ago.And still not solve yet. 2024.11.24

**Comment by BillyONeal** [comment] 2024-11-25 20:58
> Well... that's exactly the point... everything was working fine with triplets having `_`, but when then the "fix" it was not working anymore for just an obscure line in the spec.

It isn't 'just an obscure line in the spec', it's also enforced by everything else that touches triplet infrastructure. The only place it was not checked before was `--triplet`, and there some differences only worked on Windows.

@ras0219-msft @vicroms @JavierMatosD and I discussed this last week and agree that this behavior is not a bug.

> hello，Unfortunately,I have a same question in my two computers.In Windows10,VS2022 and newest VCPKG .If I use **vcpkg install zlib:x64-windows** it will show me an error : error: Invalid triplet name. Triplet names are all lowercase alphanumeric+hyphens. on expression: x64_windows Built-in Triplets: arm-neon-android arm64-android arm64-osx arm64-uwp arm64-windows
> 
> But if I write like this: **vcpkg install zlib --triplet=x64-windows** It works. But this error already happened tow month ago.And still not solve yet. 2024.11.24

This seems like an unrelated issue. My guess is that somewhere the environment variable [`VCPKG_DEFAULT_TRIPLET`](https://learn.microsoft.com/vcpkg/users/config-environment#vcpkg_default_triplet) is set to `x64_windows` in your environment.

**Comment by woshizhangbowen** [comment] 2024-11-26 16:24
> > Well... that's exactly the point... everything was working fine with triplets having `_`, but when then the "fix" it was not working anymore for just an obscure line in the spec.好吧...这就是重点一切都很好地工作与三胞胎有`_`，但当然后“修复”，它不再工作，只是一个模糊的行在规范。
> 
> It isn't 'just an obscure line in the spec', it's also enforced by everything else that touches triplet infrastructure. The only place it was not checked before was `--triplet`, and there some differences only worked on Windows.它不仅仅是“规范中的一条模糊的线”，它还被涉及三重基础设施的所有其他东西所强制执行。唯一没有检查过的地方是`--triplet`，并且只有在Windows上才有一些区别。
> 
> [@ras0219-msft](https://github.com/ras0219-msft) [@vicroms](https://github.com/vicroms) [@JavierMatosD](https://github.com/JavierMatosD) and I discussed this last week and agree that this behavior is not a bug.我上周讨论过这个问题，并同意这种行为不是一个bug。
> 
> > hello，Unfortunately,I have a same question in my two computers.In Windows10,VS2022 and newest VCPKG .If I use **vcpkg install zlib:x64-windows** it will show me an error : error: Invalid triplet name. Triplet names are all lowercase alphanumeric+hyphens. on expression: x64_windows Built-in Triplets: arm-neon-android arm64-android arm64-osx arm64-uwp arm64-windows你好，不幸的是，我有一个相同的问题在我的两台电脑.在Windows10，VS 2022和最新的VCPKG .如果我使用**vcpkg安装zlib：x64-windows**它会显示一个错误：错误：无效的三元组名称.三个名字都是字母数字+连字符。x64_windows内置三胞胎：arm-neon-android arm 64-android arm 64-osx arm 64-uwp arm 64-windows
> > But if I write like this: **vcpkg install zlib --triplet=x64-windows** It works. But this error already happened tow month ago.And still not solve yet. 2024.11.24但是如果我这样写：**vcpkg install zlib --triplet=x64-windows**它可以工作。但是这个错误在两个月前就已经发生了，到现在还没有解决。2024.11.24
> 
> This seems like an unrelated issue. My guess is that somewhere the environment variable [`VCPKG_DEFAULT_TRIPLET`](https://learn.microsoft.com/vcpkg/users/config-environment#vcpkg_default_triplet) is set to `x64_windows` in your environment.这似乎是一个无关的问题。我猜测在您的环境中，环境变量[`VCPKG_DEFAULT_TRIPLET`](https://learn.microsoft.com/vcpkg/users/config-environment#vcpkg_default_triplet)在某个地方被设置为`x64_windows`。

dude，Thank you very much.You are the god.Oh,I think you are the Iron man.太感谢啦！！！！

**Comment by MonicaLiu0311** [comment] 2024-12-02 02:33
Closing this issue as it has been resolved.

**Closed by MonicaLiu0311** 2024-12-02 02:33 UTC
Labels: category:question

**Comment by invy** [comment] 2025-02-24 12:37
@BillyONeal @MonicaLiu0311 What is the point of prohibiting '_' again?
You are diverging from actually very long tradition of naming triplets:
https://www.gnu.org/software/autoconf/manual/autoconf-2.71/html_node/Specifying-Target-Triplets.html

```
./configure --build=x86_64-pc-linux-gnu --host=x86_64-w64-mingw64
```
And so on and so on...
More, in Linux you have **everywhere** underscores!
```
$ ls /usr/include/ | grep x86
x86_64-linux-gnu
x86_64-linux-musl
```
I don't see any reason behind prohibiting '_'.
Please reopen and fix.

**Comment by woshizhangbowen** [comment] 2025-02-24 15:40
no&nbsp; &nbsp;Because I use it in my computer system environment path with the wrong x86_64-linux- .So every time it will wrong


&nbsp;


骑士部落
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Igor ***@***.***&gt;; 
发送时间: 2025年2月24日(星期一) 晚上8:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/vcpkg] [regression] Triplet not recognised anymore (Issue #41268)












   
@BillyONeal @MonicaLiu0311 What is the point of prohibiting '_' again?
 You are diverging from actually very long tradition of naming triplets:
 https://www.gnu.org/software/autoconf/manual/autoconf-2.71/html_node/Specifying-Target-Triplets.html
 ./configure --build=x86_64-pc-linux-gnu --host=x86_64-w64-mingw64  
And so on and so on...
 More, in Linux you have everywhere underscores!
 $ ls /usr/include/ | grep x86 x86_64-linux-gnu x86_64-linux-musl  
I don't see any reason behind prohibiting '_'.
 Please reopen and fix.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  invy left a comment &nbsp;&nbsp;留下了评论(microsoft/vcpkg#41268)&nbsp;&nbsp;（microsoft/vcpkg#41268）
 
@BillyONeal @MonicaLiu0311 What is the point of prohibiting '_' again?
为什么又禁止“_”？
 You are diverging from actually very long tradition of naming triplets:
你偏离了命名三胞胎的悠久传统：
 https://www.gnu.org/software/autoconf/manual/autoconf-2.71/html_node/Specifying-Target-Triplets.html
 ./configure --build=x86_64-pc-linux-gnu --host=x86_64-w64-mingw64  
And so on and so on...
等等等等...
 More, in Linux you have everywhere underscores!
此外，在Linux中，到处都有下划线！
 $ ls /usr/include/ | grep x86 x86_64-linux-gnu x86_64-linux-musl  
I don't see any reason behind prohibiting '_'.
我看不出有什么理由禁止“_”。
 Please reopen and fix.&nbsp;&nbsp;请重新打开并修复。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
直接回复此电子邮件，在GitHub上查看或取消订阅。
You are receiving this because you commented.
你收到这个是因为你评论了。  Message ID: ***@***.***&gt;
