### ISSUE TITLE
[sanity check] fails due to "different serialized paragraph", but paragraphs are actually identical

### ISSUE THREAD

**Issue by danielebosetti** [microsoft/vcpkg#15523] opened 2021-01-08 11:40 UTC
**Describe the bug**
I tried packaging a library using "vcpkg create try-ppeureka https://github.com/shadowxiali/ppeureka/archive/0.0.2.tar.gz", and then edited the portfile.
Then I ran "vcpkg install try-ppeureka", which failed with this log:

`[sanity check] The serialized binary paragraph was different from the original binary paragraph.
Please open an issue at https://github.com/microsoft/vcpkg, with the following output:

=== Original BinaryParagraph ===
spec: "try-ppeureka:x64-windows"
version: "0.0.1"
port_version: 0
description: [""]
maintainers: [""]
feature: ""
default_features: [""]
dependencies: [""]
abi: "17bc7ba496309db9483e17375eaf0128ec64c027"
type: Port

=== Serialized BinaryParagraph ===
spec: "try-ppeureka:x64-windows"
version: "0.0.1"
port_version: 0
description: [""]
maintainers: [""]
feature: ""
default_features: [""]
dependencies: [""]
abi: "17bc7ba496309db9483e17375eaf0128ec64c027"
type: Port`

**Environment**
- OS: Windows
- Compiler: VS community 2019

**To Reproduce**
1. ./vcpkg create try-ppeureka https://github.com/shadowxiali/ppeureka/archive/0.0.2.tar.gz
2. tweak portfile
3. ./vcpkg install try-ppeureka

**Expected behavior**
A clean installation

**Failure logs** 
=== Original BinaryParagraph ===
spec: "try-ppeureka:x64-windows"
version: "0.0.1"
port_version: 0
description: [""]
maintainers: [""]
feature: ""
default_features: [""]
dependencies: [""]
abi: "17bc7ba496309db9483e17375eaf0128ec64c027"
type: Port

=== Serialized BinaryParagraph ===
spec: "try-ppeureka:x64-windows"
version: "0.0.1"
port_version: 0
description: [""]
maintainers: [""]
feature: ""
default_features: [""]
dependencies: [""]
abi: "17bc7ba496309db9483e17375eaf0128ec64c027"
type: Port`

**Additional context**

**Comment by danielebosetti** [comment] 2021-01-08 11:41
Note, not sure why vcpkg complains about a "different serialized paragraph"? These seems to be identical

**Comment by danielebosetti** [comment] 2021-01-08 11:42
My vcpkg.json is
`{
  "name": "try-ppeureka",
  "version-string": "0.0.1",
  "homepage": "",
  "description": "",
  "dependencies": [],

  "default-features": [],
  "features": [
  ]
}`

**Comment by danielebosetti** [comment] 2021-01-08 11:57
(update) the installation succeeds after I edited the vcpkg.json file to be:

{
  "name": "ppeureka",
  "version-string": "0.0.1",
  "homepage": "asd",
  "description": "asd",
  "dependencies": [],

  "default-features": [],
  "features": [
    {
      "name": "test",
      "description": "asd",
      "dependencies": []
    }
  ]
}

**Comment by JackBoosY** [comment] 2021-01-11 06:20
Hi @danielebosetti, thanks for report this issue.
This may be caused by empty fields in some vcpkg.json.
Reproduce with:
vcpkg.json:
```json
{
  "name": "try-ppeureka",
  "version-string": "0.0.1",
  "homepage": "",
  "description": "",
  "dependencies": ["json11"]
}
```

portfile.cmake:
```cmake
if (VCPKG_TARGET_IS_WINDOWS)
    vcpkg_check_linkage(ONLY_STATIC_LIBRARY)
endif()

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO shadowxiali/ppeureka
    REF 9b934816a02192b02f26f183b39cb9a75cc597f5 # v0.0.2
    SHA512 9a75ea6156d12a4c1787213efdfc33e4e4e11e4fa89cf807ed40ec6ec1c50ff258f0124489c668d94bb66142a0b77b4f2e5fba51d97f186316b1171f0ffba418 
    HEAD_REF master
)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "static" BUILD_STATIC)

vcpkg_configure_cmake(
    SOURCE_PATH ${SOURCE_PATH}
    PREFER_NINJA
    OPTIONS
        -DBUILD_STATIC_LIB=${BUILD_STATIC}
)

vcpkg_install_cmake()

vcpkg_fixup_cmake_targets(CONFIG_PATH cmake)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")

# Handle copyright
file(INSTALL "${SOURCE_PATH}/README.md" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```

Error log:
```
[sanity check] The serialized binary paragraph was different from the original binary paragraph.
Please open an issue at https://github.com/microsoft/vcpkg, with the following output:

=== Original BinaryParagraph ===
spec: "try-ppeureka:x86-windows"
version: "0.0.1"
port_version: 0
description: [""]
maintainers: [""]
feature: ""
default_features: [""]
dependencies: ["json11"]
abi: "0b20123b6f6eacf2e826ca72b2bb30bcdca7a72f"
type: Port

=== Serialized BinaryParagraph ===
spec: "try-ppeureka:x86-windows"
version: "0.0.1"
port_version: 0
description: [""]
maintainers: [""]
feature: ""
default_features: [""]
dependencies: ["json11"]
abi: "0b20123b6f6eacf2e826ca72b2bb30bcdca7a72f"
type: Port
```

Fixed json:
```json
{
  "name": "try-ppeureka",
  "version-string": "0.0.2",
  "homepage": "https://github.com/shadowxiali/ppeureka",
  "description": "A C++ client library for Spring Cloud Eureka.",
  "dependencies": ["json11"]
}
```

**Comment by NancyLi1013** [comment] 2021-08-10 07:04
Hi @danielebosetti 

This issue should be fixed now. I cannot reproduce this with the vcpkg.json file 
 from @JackBoosY here https://github.com/microsoft/vcpkg/issues/15523#issuecomment-757648777.

 Please try to update to the latest vcpkg `2021-08-03-1a6d67b8150e94b7f473c6ab1c0cfdd794316a64` via `git pull` , 
 then rerun .`\bootstrap-vcpkg.bat` and rebuild this.

**Closed by NancyLi1013** 2021-08-10 07:04 UTC
Labels: category:vcpkg-bug
