### ISSUE TITLE
[mongo-cxx-driver] update to 3.6.0

### ISSUE THREAD

**Issue by Gigas002** [microsoft/vcpkg#12942] opened 2020-08-16 16:38 UTC
Library name: mongo-cxx-driver

New version number: 3.6.0

Other information that may be useful (release notes, etc...):
https://github.com/mongodb/mongo-cxx-driver/

**Comment by TaeZStkyoht** [comment] 2021-02-22 10:56
Could you prioritize this?

**Comment by JonLiu1993** [comment] 2021-07-01 05:49
Duplicate of #18730

**Closed by JonLiu1993** 2021-07-01 05:49 UTC
Labels: category:port-update
