### ISSUE TITLE
[openimageio] Build error

### ISSUE THREAD

**Issue by Isoide** [microsoft/vcpkg#33104] opened 2023-08-10 16:20 UTC
error from vcpkg command:
{
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/mzarzycki/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j13
    Working Directory: C:/Users/mzarzycki/vcpkg/buildtrees/openimageio/x64-windows-dbg
    See logs for more information:
      C:\Users\mzarzycki\vcpkg\buildtrees\openimageio\install-x64-windows-dbg-out.log
      C:\Users\mzarzycki\vcpkg\buildtrees\openimageio\install-x64-windows-dbg-out-1.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openimageio/portfile.cmake:72 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)

error: building openimageio:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openimageio:x64-windows: 1.5 min
}

comment:
Win11, vcpkg was installed fresh

file:
[issue_body.md](https://github.com/microsoft/vcpkg/files/12314914/issue_body.md)

**Comment by Isoide** [comment] 2023-08-10 16:22
Here are the logs.
[install-x64-windows-dbg-out-1.log](https://github.com/microsoft/vcpkg/files/12314940/install-x64-windows-dbg-out-1.log)
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/12314941/install-x64-windows-dbg-out.log)

**Comment by Adela0814** [comment] 2023-08-11 05:50
Duplicate of https://github.com/microsoft/vcpkg/issues/32776.

**Closed by Adela0814** 2023-08-11 05:50 UTC

**Comment by Isoide** [comment] 2023-08-16 13:53
Well, I have found a fix for my problem.
I am not that good in terms of programming, but for some reason vcpkg does not find python installed on windows. Your fixes did not work for me.
What I ended up doing was installing python3:x64-windows via vcpkg and it went through without any more problems.
