### ISSUE TITLE
[gstreamer] Build error

### ISSUE THREAD

**Issue by wuzhizhe7273** [microsoft/vcpkg#33758] opened 2023-09-14 04:06 UTC
Package: gstreamer[core,plugins-base]:x64-windows -> 1.20.5#11

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.37.32822.0
-    vcpkg-tool version: 2023-08-09-9990a4c9026811a312cb2af78bf77f3d9d288416
    vcpkg-scripts version: 2c401863d 2023-09-13 (2 hours ago)

**To Reproduce**

`vcpkg install qt:x64-windows`
**Failure logs**

```
-- Using cached gstreamer-gstreamer-1.20.5.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/gstreamer/src/1.20.5-a6a8a0db6f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/gstreamer-gstreamer-1.20.5.tar.gz
-- Applying patch fix-clang-cl.patch
-- Applying patch fix-clang-cl-gstreamer.patch
-- Applying patch fix-clang-cl-base.patch
-- Applying patch fix-clang-cl-good.patch
-- Applying patch fix-clang-cl-bad.patch
-- Applying patch fix-clang-cl-ugly.patch
-- Applying patch gstreamer-disable-no-unused.patch
-- Applying patch srtp_fix.patch
-- Applying patch fix-bz2-windows-debug-dependency.patch
-- Applying patch plugin-base-disable-no-unused.patch
-- Using source at C:/dev/vcpkg/buildtrees/gstreamer/src/1.20.5-a6a8a0db6f.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/dev/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/dev/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe C:/dev/vcpkg/installed/x64-windows/tools/meson/meson.py -Dgpl=disabled -Dlibav=disabled -Dnls=disabled -Dges=disabled -Dbase=enabled -Dgst-plugins-base:gl-graphene=disabled -Dgst-plugins-base:alsa=disabled -Dgst-plugins-base:ogg=disabled -Dgst-plugins-base:opus=disabled -Dgst-plugins-base:pango=disabled -Dgst-plugins-base:vorbis=disabled -Dgst-plugins-base:x11=disabled -Dgst-plugins-base:xshm=disabled -Dgood=disabled -Dgst-plugins-good:bz2=disabled -Dgst-plugins-good:cairo=disabled -Dgst-plugins-good:flac=disabled -Dgst-plugins-good:gdk-pixbuf=disabled -Dgst-plugins-good:jpeg=disabled -Dgst-plugins-good:mpg123=disabled -Dgst-plugins-good:png=disabled -Dgst-plugins-good:speex=disabled -Dgst-plugins-good:taglib=disabled -Dgst-plugins-good:vpx=disabled -Dugly=disabled -Dgst-plugins-ugly:x264=disabled -Dbad=disabled -Dgst-plugins-bad:aes=disabled -Dgst-plugins-bad:assrender=disabled -Dgst-plugins-bad:bz2=disabled -Dgst-plugins-bad:chromaprint=disabled -Dgst-plugins-bad:closedcaption=disabled -Dgst-plugins-bad:colormanagement=disabled -Dgst-plugins-bad:dash=disabled -Dgst-plugins-bad:dc1394=disabled -Dgst-plugins-bad:dtls=disabled -Dgst-plugins-bad:faad=disabled -Dgst-plugins-bad:fdkaac=disabled -Dgst-plugins-bad:fluidsynth=disabled -Dgst-plugins-bad:libde265=disabled -Dgst-plugins-bad:microdns=disabled -Dgst-plugins-bad:modplug=disabled -Dgst-plugins-bad:openal=disabled -Dgst-plugins-bad:openh264=disabled -Dgst-plugins-bad:openjpeg=disabled -Dgst-plugins-bad:openmpt=disabled -Dgst-plugins-bad:opus=disabled -Dgst-plugins-bad:smoothstreaming=disabled -Dgst-plugins-bad:sndfile=disabled -Dgst-plugins-bad:soundtouch=disabled -Dgst-plugins-bad:srt=disabled -Dgst-plugins-bad:srtp=disabled -Dgst-plugins-bad:webp=disabled -Dgst-plugins-bad:webrtc=disabled -Dgst-plugins-bad:wildmidi=disabled -Dgst-plugins-bad:x11=disabled -Dgst-plugins-bad:x265=disabled -Dgst-plugins-bad:asio=disabled -Dpython=disabled -Dlibnice=disabled -Ddevtools=disabled -Drtsp_server=disabled -Domx=disabled -Dvaapi=disabled -Dsharp=disabled -Drs=disabled -Dgst-examples=disabled -Dtls=disabled -Dqt5=disabled -Dtests=disabled -Dexamples=disabled -Dintrospection=disabled -Dorc=disabled -Ddoc=disabled -Dgtk_doc=disabled -Dgstreamer:check=disabled -Dgstreamer:libunwind=disabled -Dgstreamer:libdw=disabled -Dgstreamer:dbghelp=disabled -Dgstreamer:bash-completion=disabled -Dgstreamer:coretracers=disabled -Dgstreamer:benchmarks=disabled -Dgstreamer:gst_debug=true -Dgst-plugins-base:gl_winsys=win32 -Dgst-plugins-base:gl_platform=wgl -Dgst-plugins-base:cdparanoia=disabled -Dgst-plugins-base:libvisual=disabled -Dgst-plugins-base:theora=disabled -Dgst-plugins-base:tremor=disabled -Dgst-plugins-base:xvideo=disabled -Dgst-plugins-good:aalib=disabled -Dgst-plugins-good:directsound=auto -Dgst-plugins-good:dv=disabled -Dgst-plugins-good:dv1394=disabled -Dgst-plugins-good:gtk3=disabled -Dgst-plugins-good:jack=disabled -Dgst-plugins-good:lame=disabled -Dgst-plugins-good:libcaca=disabled -Dgst-plugins-good:oss=disabled -Dgst-plugins-good:oss4=disabled -Dgst-plugins-good:osxaudio=auto -Dgst-plugins-good:osxvideo=auto -Dgst-plugins-good:pulse=auto -Dgst-plugins-good:qt5=disabled -Dgst-plugins-good:shout2=disabled -Dgst-plugins-good:soup=disabled -Dgst-plugins-good:twolame=disabled -Dgst-plugins-good:waveform=auto -Dgst-plugins-good:wavpack=disabled -Dgst-plugins-ugly:a52dec=disabled -Dgst-plugins-ugly:amrnb=disabled -Dgst-plugins-ugly:amrwbdec=disabled -Dgst-plugins-ugly:cdio=disabled -Dgst-plugins-ugly:dvdread=disabled -Dgst-plugins-ugly:mpeg2dec=disabled -Dgst-plugins-ugly:sidplay=disabled -Dgst-plugins-bad:aom=disabled -Dgst-plugins-bad:avtp=disabled -Dgst-plugins-bad:androidmedia=auto -Dgst-plugins-bad:applemedia=auto -Dgst-plugins-bad:asio-sdk-path= -Dgst-plugins-bad:bluez=disabled -Dgst-plugins-bad:bs2b=disabled -Dgst-plugins-bad:curl=disabled -Dgst-plugins-bad:curl-ssh2=disabled -Dgst-plugins-bad:d3dvideosink=auto -Dgst-plugins-bad:d3d11=auto -Dgst-plugins-bad:decklink=disabled -Dgst-plugins-bad:directfb=disabled -Dgst-plugins-bad:directsound=auto -Dgst-plugins-bad:dts=disabled -Dgst-plugins-bad:dvb=auto -Dgst-plugins-bad:faac=disabled -Dgst-plugins-bad:fbdev=auto -Dgst-plugins-bad:flite=disabled -Dgst-plugins-bad:gl=auto -Dgst-plugins-bad:gme=disabled -Dgst-plugins-bad:gs=disabled -Dgst-plugins-bad:gsm=disabled -Dgst-plugins-bad:ipcpipeline=auto -Dgst-plugins-bad:iqa=disabled -Dgst-plugins-bad:kate=disabled -Dgst-plugins-bad:kms=disabled -Dgst-plugins-bad:ladspa=disabled -Dgst-plugins-bad:ldac=disabled -Dgst-plugins-bad:lv2=disabled -Dgst-plugins-bad:mediafoundation=auto -Dgst-plugins-bad:mpeg2enc=disabled -Dgst-plugins-bad:mplex=disabled -Dgst-plugins-bad:msdk=disabled -Dgst-plugins-bad:musepack=disabled -Dgst-plugins-bad:neon=disabled -Dgst-plugins-bad:nvcodec=enabled -Dgst-plugins-bad:onnx=disabled -Dgst-plugins-bad:openaptx=disabled -Dgst-plugins-bad:opencv=disabled -Dgst-plugins-bad:openexr=disabled -Dgst-plugins-bad:openni2=disabled -Dgst-plugins-bad:opensles=disabled -Dgst-plugins-bad:qroverlay=disabled -Dgst-plugins-bad:resindvd=disabled -Dgst-plugins-bad:rsvg=disabled -Dgst-plugins-bad:rtmp=disabled -Dgst-plugins-bad:sbc=disabled -Dgst-plugins-bad:sctp=auto -Dgst-plugins-bad:shm=disabled -Dgst-plugins-bad:spandsp=disabled -Dgst-plugins-bad:svthevcenc=disabled -Dgst-plugins-bad:teletext=disabled -Dgst-plugins-bad:tinyalsa=disabled -Dgst-plugins-bad:transcode=disabled -Dgst-plugins-bad:ttml=disabled -Dgst-plugins-bad:uvch264=disabled -Dgst-plugins-bad:va=disabled -Dgst-plugins-bad:voaacenc=disabled -Dgst-plugins-bad:voamrwbenc=disabled -Dgst-plugins-bad:vulkan=auto -Dgst-plugins-bad:wasapi=auto -Dgst-plugins-bad:wasapi2=auto -Dgst-plugins-bad:wayland=auto -Dgst-plugins-bad:winks=disabled -Dgst-plugins-bad:winscreencap=auto -Dgst-plugins-bad:zbar=disabled -Dgst-plugins-bad:zxing=disabled -Dgst-plugins-bad:wpe=disabled -Dgst-plugins-bad:magicleap=disabled -Dgst-plugins-bad:v4l2codecs=disabled -Dgst-plugins-bad:isac=disabled --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib --native C:/dev/vcpkg/buildtrees/gstreamer/meson-x64-windows-dbg.log -Ddebug=true --prefix C:/dev/vcpkg/packages/gstreamer_x64-windows/debug --includedir ../include -Dcmake_prefix_path=['C:/dev/vcpkg/installed/x64-windows/debug','C:/dev/vcpkg/installed/x64-windows','C:/dev/vcpkg/installed/x64-windows/share'] C:/dev/vcpkg/buildtrees/gstreamer/src/1.20.5-a6a8a0db6f.clean
    Working Directory: C:/dev/vcpkg/buildtrees/gstreamer/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\gstreamer\config-x64-windows-dbg-meson-log.txt.log
      C:\dev\vcpkg\buildtrees\gstreamer\config-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:431 (vcpkg_execute_required_process)
  ports/gstreamer/portfile.cmake:146 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)



```
<details><summary>C:\dev\vcpkg\buildtrees\gstreamer\config-x64-windows-dbg-meson-log.txt.log</summary>

```
Build started at 2023-09-14T12:03:05.409806
Main binary: C:\dev\vcpkg\downloads\tools\python\python-3.11.5-x64\python.exe
Build Options: -Dgpl=disabled -Dlibav=disabled -Dnls=disabled -Dges=disabled -Dbase=enabled -Dgst-plugins-base:gl-graphene=disabled -Dgst-plugins-base:alsa=disabled -Dgst-plugins-base:ogg=disabled -Dgst-plugins-base:opus=disabled -Dgst-plugins-base:pango=disabled -Dgst-plugins-base:vorbis=disabled -Dgst-plugins-base:x11=disabled -Dgst-plugins-base:xshm=disabled -Dgood=disabled -Dgst-plugins-good:bz2=disabled -Dgst-plugins-good:cairo=disabled -Dgst-plugins-good:flac=disabled -Dgst-plugins-good:gdk-pixbuf=disabled -Dgst-plugins-good:jpeg=disabled -Dgst-plugins-good:mpg123=disabled -Dgst-plugins-good:png=disabled -Dgst-plugins-good:speex=disabled -Dgst-plugins-good:taglib=disabled -Dgst-plugins-good:vpx=disabled -Dugly=disabled -Dgst-plugins-ugly:x264=disabled -Dbad=disabled -Dgst-plugins-bad:aes=disabled -Dgst-plugins-bad:assrender=disabled -Dgst-plugins-bad:bz2=disabled -Dgst-plugins-bad:chromaprint=disabled -Dgst-plugins-bad:closedcaption=disabled -Dgst-plugins-bad:colormanagement=disabled -Dgst-plugins-bad:dash=disabled -Dgst-plugins-bad:dc1394=disabled -Dgst-plugins-bad:dtls=disabled -Dgst-plugins-bad:faad=disabled -Dgst-plugins-bad:fdkaac=disabled -Dgst-plugins-bad:fluidsynth=disabled -Dgst-plugins-bad:libde265=disabled -Dgst-plugins-bad:microdns=disabled -Dgst-plugins-bad:modplug=disabled -Dgst-plugins-bad:openal=disabled -Dgst-plugins-bad:openh264=disabled -Dgst-plugins-bad:openjpeg=disabled -Dgst-plugins-bad:openmpt=disabled -Dgst-plugins-bad:opus=disabled -Dgst-plugins-bad:smoothstreaming=disabled -Dgst-plugins-bad:sndfile=disabled -Dgst-plugins-bad:soundtouch=disabled -Dgst-plugins-bad:srt=disabled -Dgst-plugins-bad:srtp=disabled -Dgst-plugins-bad:webp=disabled -Dgst-plugins-bad:webrtc=disabled -Dgst-plugins-bad:wildmidi=disabled -Dgst-plugins-bad:x11=disabled -Dgst-plugins-bad:x265=disabled -Dgst-plugins-bad:asio=disabled -Dpython=disabled -Dlibnice=disabled -Ddevtools=disabled -Drtsp_server=disabled -Domx=disabled -Dvaapi=disabled -Dsharp=disabled -Drs=disabled -Dgst-examples=disabled -Dtls=disabled -Dqt5=disabled -Dtests=disabled -Dexamples=disabled -Dintrospection=disabled -Dorc=disabled -Ddoc=disabled -Dgtk_doc=disabled -Dgstreamer:check=disabled -Dgstreamer:libunwind=disabled -Dgstreamer:libdw=disabled -Dgstreamer:dbghelp=disabled -Dgstreamer:bash-completion=disabled -Dgstreamer:coretracers=disabled -Dgstreamer:benchmarks=disabled -Dgstreamer:gst_debug=true -Dgst-plugins-base:gl_winsys=win32 -Dgst-plugins-base:gl_platform=wgl -Dgst-plugins-base:cdparanoia=disabled -Dgst-plugins-base:libvisual=disabled -Dgst-plugins-base:theora=disabled -Dgst-plugins-base:tremor=disabled -Dgst-plugins-base:xvideo=disabled -Dgst-plugins-good:aalib=disabled -Dgst-plugins-good:directsound=auto -Dgst-plugins-good:dv=disabled -Dgst-plugins-good:dv1394=disabled -Dgst-plugins-good:gtk3=disabled -Dgst-plugins-good:jack=disabled -Dgst-plugins-good:lame=disabled -Dgst-plugins-good:libcaca=disabled -Dgst-plugins-good:oss=disabled -Dgst-plugins-good:oss4=disabled -Dgst-plugins-good:osxaudio=auto -Dgst-plugins-good:osxvideo=auto -Dgst-plugins-good:pulse=auto -Dgst-plugins-good:qt5=disabled -Dgst-plugins-good:shout2=disabled -Dgst-plugins-good:soup=disabled -Dgst-plugins-good:twolame=disabled -Dgst-plugins-good:waveform=auto -Dgst-plugins-good:wavpack=disabled -Dgst-plugins-ugly:a52dec=disabled -Dgst-plugins-ugly:amrnb=disabled -Dgst-plugins-ugly:amrwbdec=disabled -Dgst-plugins-ugly:cdio=disabled -Dgst-plugins-ugly:dvdread=disabled -Dgst-plugins-ugly:mpeg2dec=disabled -Dgst-plugins-ugly:sidplay=disabled -Dgst-plugins-bad:aom=disabled -Dgst-plugins-bad:avtp=disabled -Dgst-plugins-bad:androidmedia=auto -Dgst-plugins-bad:applemedia=auto -Dgst-plugins-bad:asio-sdk-path= -Dgst-plugins-bad:bluez=disabled -Dgst-plugins-bad:bs2b=disabled -Dgst-plugins-bad:curl=disabled -Dgst-plugins-bad:curl-ssh2=disabled -Dgst-plugins-bad:d3dvideosink=auto -Dgst-plugins-bad:d3d11=auto -Dgst-plugins-bad:decklink=disabled -Dgst-plugins-bad:directfb=disabled -Dgst-plugins-bad:directsound=auto -Dgst-plugins-bad:dts=disabled -Dgst-plugins-bad:dvb=auto -Dgst-plugins-bad:faac=disabled -Dgst-plugins-bad:fbdev=auto -Dgst-plugins-bad:flite=disabled -Dgst-plugins-bad:gl=auto -Dgst-plugins-bad:gme=disabled -Dgst-plugins-bad:gs=disabled -Dgst-plugins-bad:gsm=disabled -Dgst-plugins-bad:ipcpipeline=auto -Dgst-plugins-bad:iqa=disabled -Dgst-plugins-bad:kate=disabled -Dgst-plugins-bad:kms=disabled -Dgst-plugins-bad:ladspa=disabled -Dgst-plugins-bad:ldac=disabled -Dgst-plugins-bad:lv2=disabled -Dgst-plugins-bad:mediafoundation=auto -Dgst-plugins-bad:mpeg2enc=disabled -Dgst-plugins-bad:mplex=disabled -Dgst-plugins-bad:msdk=disabled -Dgst-plugins-bad:musepack=disabled -Dgst-plugins-bad:neon=disabled -Dgst-plugins-bad:nvcodec=enabled -Dgst-plugins-bad:onnx=disabled -Dgst-plugins-bad:openaptx=disabled -Dgst-plugins-bad:opencv=disabled -Dgst-plugins-bad:openexr=disabled -Dgst-plugins-bad:openni2=disabled -Dgst-plugins-bad:opensles=disabled -Dgst-plugins-bad:qroverlay=disabled -Dgst-plugins-bad:resindvd=disabled -Dgst-plugins-bad:rsvg=disabled -Dgst-plugins-bad:rtmp=disabled -Dgst-plugins-bad:sbc=disabled -Dgst-plugins-bad:sctp=auto -Dgst-plugins-bad:shm=disabled -Dgst-plugins-bad:spandsp=disabled -Dgst-plugins-bad:svthevcenc=disabled -Dgst-plugins-bad:teletext=disabled -Dgst-plugins-bad:tinyalsa=disabled -Dgst-plugins-bad:transcode=disabled -Dgst-plugins-bad:ttml=disabled -Dgst-plugins-bad:uvch264=disabled -Dgst-plugins-bad:va=disabled -Dgst-plugins-bad:voaacenc=disabled -Dgst-plugins-bad:voamrwbenc=disabled -Dgst-plugins-bad:vulkan=auto -Dgst-plugins-bad:wasapi=auto -Dgst-plugins-bad:wasapi2=auto -Dgst-plugins-bad:wayland=auto -Dgst-plugins-bad:winks=disabled -Dgst-plugins-bad:winscreencap=auto -Dgst-plugins-bad:zbar=disabled -Dgst-plugins-bad:zxing=disabled -Dgst-plugins-bad:wpe=disabled -Dgst-plugins-bad:magicleap=disabled -Dgst-plugins-bad:v4l2codecs=disabled -Dgst-plugins-bad:isac=disabled -Ddebug=true '-Dcmake_prefix_path=['"'"'C:/dev/vcpkg/installed/x64-windows/debug'"'"','"'"'C:/dev/vcpkg/installed/x64-windows'"'"','"'"'C:/dev/vcpkg/installed/x64-windows/share'"'"']' -Dprefix=C:/dev/vcpkg/packages/gstreamer_x64-windows/debug -Dincludedir=../include -Dlibdir=lib -Dbackend=ninja -Dbuildtype=plain -Dwrap_mode=nodownload '--native-file C:/dev/vcpkg/buildtrees/gstreamer/meson-x64-windows-dbg.log'
Python system: Windows
The Meson build system
Version: 0.62.1
Source dir: C:\dev\vcpkg\buildtrees\gstreamer\src\1.20.5-a6a8a0db6f.clean
Build dir: C:\dev\vcpkg\buildtrees\gstreamer\x64-windows-dbg
Build type: native build
Project name: gstreamer-full
Project version: 1.20.5
Sanity testing C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe
Is cross compiler: False.
Sanity check compiler command line: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe sanitycheckc.c /Fesanitycheckc.exe /MDd -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 -IC:/dev/vcpkg/installed/x64-windows/include /nologo /showIncludes /utf-8 /link -machine:x64 -debug -INCREMENTAL /LIBPATH:C:/dev/vcpkg/installed/x64-windows/debug/lib
Sanity check compile stdout:
sanitycheckc.c

-----
Sanity check compile stderr:

-----
Running test binary command: C:\dev\vcpkg\buildtrees\gstreamer\x64-windows-dbg\meson-private\sanitycheckc.exe
C compiler for the host machine: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe (msvc 19.37.32822 "鐢ㄤ簬 x64 鐨� Microsoft (R) C/C++ 浼樺寲缂栬瘧鍣� 19.37.32822 鐗�")
C linker for the host machine: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/link.exe link 14.37.32822.0
Sanity testing C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe
Is cross compiler: False.
Sanity check compiler command line: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe sanitycheckc.c /Fesanitycheckc.exe /MDd /nologo /showIncludes /utf-8 /link
Sanity check compile stdout:
sanitycheckc.c

-----
Sanity check compile stderr:

-----
Running test binary command: C:\dev\vcpkg\buildtrees\gstreamer\x64-windows-dbg\meson-private\sanitycheckc.exe
C compiler for the build machine: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe (msvc 19.37.32822 "鐢ㄤ簬 x64 鐨� Microsoft (R) C/C++ 浼樺寲缂栬瘧鍣� 19.37.32822 鐗�")
C linker for the build machine: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/link.exe link 14.37.32822.0
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
Unusable script 'C:/dev/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe'
Program python found: YES (C:/dev/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe)
Running command: C:/dev/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe -c 
import os
assert('GST_ENV' not in os.environ)

--- stdout ---

--- stderr ---


Running command: C:/dev/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe -c import shutil; shutil.copy("scripts/git-hooks/multi-pre-commit.hook", ".git/hooks/pre-commit")
--- stdout ---

--- stderr ---
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "shutil.py", line 419, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "shutil.py", line 258, in copyfile
    with open(dst, 'wb') as fdst:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '.git/hooks/pre-commit'


Program uname found: NO
Running compile:
Working directory:  C:\dev\vcpkg\buildtrees\gstreamer\x64-windows-dbg\meson-private\tmp35yvwyjf
Command line:  C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe -IC:/dev/vcpkg/installed/x64-windows/include C:\dev\vcpkg\buildtrees\gstreamer\x64-windows-dbg\meson-private\tmp35yvwyjf\testfile.c /FoC:\dev\vcpkg\buildtrees\gstreamer\x64-windows-dbg\meson-private\tmp35yvwyjf\output.obj /nologo /showIncludes /utf-8 /c -nologo -DWIN32 -D_WINDOWS -W3 -utf-8 -MP -D_DEBUG -MDd -Z7 -Ob0 -Od -RTC1 /nologo /showIncludes /utf-8 /c /Od /Oi- /utf-8 

Code:
 extern int i;
int i;

Compiler stdout:
 testfile.c

Compiler stderr:
 
Compiler for C supports arguments /utf-8: YES 

Executing subproject win-flex-bison-binaries 

Project name: win-flex-bison-binary
Project version: 2.5.18
'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
Unusable script 'C:\\dev\\vcpkg\\downloads\\tools\\python\\python-3.11.5-x64\\python.exe'
Message: Downloading and extracting win-flex-bison binaries...
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Running command: C:\dev\vcpkg\downloads\tools\python\python-3.11.5-x64\python.exe C:\dev\vcpkg\buildtrees\gstreamer\src\1.20.5-a6a8a0db6f.clean\subprojects\win-flex-bison-binaries\download-binary.py 2.5.18 095cf65cb3f12ee5888022f93109acbe6264e5f18f6ffce0bda77feb31b65bd8
--- stdout ---

--- stderr ---
Traceback (most recent call last):
  File "C:\dev\vcpkg\buildtrees\gstreamer\src\1.20.5-a6a8a0db6f.clean\subprojects\win-flex-bison-binaries\download-binary.py", line 5, in <module>
    import ssl
  File "ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ImportError: DLL load failed while importing _ssl: 找不到指定的模块。


Message: 

..\src\1.20.5-a6a8a0db6f.clean\subprojects\win-flex-bison-binaries\meson.build:12:2: ERROR: Problem encountered: Traceback (most recent call last):
  File "C:\dev\vcpkg\buildtrees\gstreamer\src\1.20.5-a6a8a0db6f.clean\subprojects\win-flex-bison-binaries\download-binary.py", line 5, in <module>
    import ssl
  File "ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ImportError: DLL load failed while importing _ssl: 找不到指定的模块。

```
</details>
<details><summary>C:\dev\vcpkg\buildtrees\gstreamer\config-x64-windows-dbg-out.log</summary>

```
WARNING: Recommend using either -Dbuildtype or -Doptimization + -Ddebug. Using both is redundant since they override each other. See: https://mesonbuild.com/Builtin-options.html#build-type-options
The Meson build system
Version: 0.62.1
Source dir: C:\dev\vcpkg\buildtrees\gstreamer\src\1.20.5-a6a8a0db6f.clean
Build dir: C:\dev\vcpkg\buildtrees\gstreamer\x64-windows-dbg
Build type: native build
Project name: gstreamer-full
Project version: 1.20.5
C compiler for the host machine: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe (msvc 19.37.32822 "??? x64 ?? Microsoft (R) C/C++ ???????? 19.37.32822 ??")
C linker for the host machine: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/link.exe link 14.37.32822.0
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program python found: YES (C:/dev/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe)
Program uname found: NO
Compiler for C supports arguments /utf-8: YES 

Executing subproject win-flex-bison-binaries 

win-flex-bison-binaries| Project name: win-flex-bison-binary
win-flex-bison-binaries| Project version: 2.5.18
win-flex-bison-binaries| Message: Downloading and extracting win-flex-bison binaries...
win-flex-bison-binaries| WARNING: You should add the boolean check kwarg to the run_command call.
win-flex-bison-binaries| It currently defaults to false,
win-flex-bison-binaries| but it will default to true in future releases of meson.
win-flex-bison-binaries| See also: https://github.com/mesonbuild/meson/issues/9300
win-flex-bison-binaries| Message:

..\src\1.20.5-a6a8a0db6f.clean\subprojects\win-flex-bison-binaries\meson.build:12:2: ERROR: Problem encountered: Traceback (most recent call last):
  File "C:\dev\vcpkg\buildtrees\gstreamer\src\1.20.5-a6a8a0db6f.clean\subprojects\win-flex-bison-binaries\download-binary.py", line 5, in <module>
    import ssl
  File "ssl.py", line 100, in <module>
    import _ssl             # if we can't import it, let the error propagate
    ^^^^^^^^^^^
ImportError: DLL load failed while importing _ssl: �Ҳ���ָ����ģ�顣


A full log can be found at C:\dev\vcpkg\buildtrees\gstreamer\x64-windows-dbg\meson-logs\meson-log.txt
```
</details>

**Comment by MonicaLiu0311** [comment] 2023-09-14 09:35
Duplicate of #33434.

**Closed by MonicaLiu0311** 2023-09-14 09:35 UTC
Labels: requires:repro
