### ISSUE TITLE
[qt5-webengine] Build error

### ISSUE THREAD

**Issue by kshuyusheng** [microsoft/vcpkg#27550] opened 2022-10-30 04:32 UTC
```
jom 1.1.3 - empower your cores

Project MESSAGE: E:\vcpkg\buildtrees\qt5-webengine\src\5.15.6-cd4fc1058e.clean\src\3rdparty\gn\build\gen.py --no-last-commit-position --out-path E:/vcpkg/buildtrees/qt5-webengine/x64-windows-dbg/src/3rdparty/gn/out/Release --cc "E:\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\bin\Hostx64\x64\cl.exe" --cxx "E:\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\bin\Hostx64\x64\cl.exe" --ld "E:\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.33.31629\bin\Hostx64\x64\link.exe" --use-lto
Project MESSAGE: Running: E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\3rdparty\gn\out\Release\gn.exe gen E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\debug --script-executable=E:\vcpkg\downloads\tools\python\python-2.7.18-x64\python.exe --args="use_qt=true init_stack_vars=false is_component_build=false is_shared=true enable_debugallocation=false enable_media_remoting=false enable_message_center=false enable_nacl=false enable_remoting=false enable_reporting=false enable_resource_allowlist_generation=false enable_swiftshader=false enable_swiftshader_vulkan=false angle_enable_swiftshader=false enable_web_speech=false enable_widevine=true forbid_non_component_debug_builds=false has_native_accessibility=false safe_browsing_mode=0 skia_use_dawn=false toolkit_views=false treat_warnings_as_errors=false use_allocator_shim=false use_allocator=\"none\" use_custom_libcxx=false chrome_pgo_phase=0 enable_hangout_services_extension=true optimize_webui=false enable_js_type_check=false v8_use_external_startup_data=false strip_absolute_paths_from_debug_symbols=false jumbo_build_excluded=[\"browser\"] enable_precompiled_headers=false is_official_build=false is_unsafe_developer_build=false from_here_uses_location_builtins=false is_debug=true use_debug_fission=false enable_iterator_debugging=true v8_optimized_debug=false blink_symbol_level=0 remove_v8base_debug_symbols=true use_sysroot=false enable_session_service=false ninja_use_custom_environment_files=false win_linker_timing=true com_init_check_hook_disabled=true heterogeneous_executables=true enable_vr=false is_clang=false use_lld=false use_incremental_linking=false visual_studio_version=2019 visual_studio_path=\"E:/Microsoft Visual Studio/2022/Enterprise\" windows_sdk_path=\"C:/Program Files ^(x86^)/Windows Kits/10\" target_cpu=\"x64\" enable_basic_printing=true enable_print_preview=true enable_pdf=true enable_plugins=true enable_spellcheck=true enable_webrtc=true proprietary_codecs=false enable_extensions=true use_kerberos=true use_browser_spellchecker=false qtwebengine_target=\"E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\debug:QtWebEngineCore\"" --root=E:\vcpkg\buildtrees\qt5-webengine\src\5.15.6-cd4fc1058e.clean\src\3rdparty\chromium 
Project MESSAGE: Running: E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\3rdparty\gn\out\Release\gn.exe gen E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\release --script-executable=E:\vcpkg\downloads\tools\python\python-2.7.18-x64\python.exe --args="use_qt=true init_stack_vars=false is_component_build=false is_shared=true enable_debugallocation=false enable_media_remoting=false enable_message_center=false enable_nacl=false enable_remoting=false enable_reporting=false enable_resource_allowlist_generation=false enable_swiftshader=false enable_swiftshader_vulkan=false angle_enable_swiftshader=false enable_web_speech=false enable_widevine=true forbid_non_component_debug_builds=false has_native_accessibility=false safe_browsing_mode=0 skia_use_dawn=false toolkit_views=false treat_warnings_as_errors=false use_allocator_shim=false use_allocator=\"none\" use_custom_libcxx=false chrome_pgo_phase=0 enable_hangout_services_extension=true optimize_webui=false enable_js_type_check=false v8_use_external_startup_data=false strip_absolute_paths_from_debug_symbols=false jumbo_build_excluded=[\"browser\"] enable_precompiled_headers=false is_official_build=true is_debug=false symbol_level=0 blink_symbol_level=0 remove_v8base_debug_symbols=true use_sysroot=false enable_session_service=false ninja_use_custom_environment_files=false win_linker_timing=true com_init_check_hook_disabled=true heterogeneous_executables=true enable_vr=false is_clang=false use_lld=false use_incremental_linking=false visual_studio_version=2019 visual_studio_path=\"E:/Microsoft Visual Studio/2022/Enterprise\" windows_sdk_path=\"C:/Program Files ^(x86^)/Windows Kits/10\" target_cpu=\"x64\" enable_basic_printing=true enable_print_preview=true enable_pdf=true enable_plugins=true enable_spellcheck=true enable_webrtc=true proprietary_codecs=false enable_extensions=true use_kerberos=true use_browser_spellchecker=false qtwebengine_target=\"E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\release:QtWebEngineCore\"" --root=E:\vcpkg\buildtrees\qt5-webengine\src\5.15.6-cd4fc1058e.clean\src\3rdparty\chromium 
jom: E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile.gn_run.Debug [run_ninja] Error 1
jom: E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile.gn_run [debug] Error 2
jom: E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile [sub-gn_run-pro-make_first] Error 2
jom: E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\Makefile [sub-core-make_first] Error 2
jom: E:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\Makefile [sub-src-make_first] Error 2
```

**Comment by JonLiu1993** [comment] 2023-04-12 08:58
Duplicate of #27932

**Closed by JonLiu1993** 2023-04-12 08:58 UTC
Labels: category:port-bug
