### ISSUE TITLE
Vtk port error

### ISSUE THREAD

**Issue by Fleischner** [Microsoft/vcpkg#1129] opened 2017-05-21 16:46 UTC
Build Error Package: vtk:x64-windows
  Vcpkg version: 0.0.81-c99983613acb3878eb6f7d9269aaf62eeacd6fe8

Build crashes with error: LINK : fatal error LNK1181: "hdf5-shared.lib“ not found, because the generated port hdf5 library filename is hdf5.lib
I'm a little bit surprised as the port files are already a couple of weeks old. I'm using a fresh installation both of vcpkg an vs2017

Somehow the name 'hdf5-shared.lib' ends up in the CMakeCache.txt. Sorry I gave up to find where in the thousands of thousands of thousands lines of cryptic cmake variable definitions, undefinitions and combinations this happens.

There might be more problems. While searching the for the error I recognized that the set port file options:
-DVTK_USE_SYSTEM_EXPAT=ON
        -DVTK_USE_SYSTEM_FREETYPE=ON
        # -DVTK_USE_SYSTEM_GL2PS=ON
        -DVTK_USE_SYSTEM_GLEW=ON
        -DVTK_USE_SYSTEM_HDF5=ON
        -DVTK_USE_SYSTEM_JSONCPP=ON
        # -DVTK_USE_SYSTEM_LIBPROJ4=ON
        # -DVTK_USE_SYSTEM_LIBRARIES=ON
        -DVTK_USE_SYSTEM_LIBXML2=ON
        # -DVTK_USE_SYSTEM_NETCDF=ON
        # -DVTK_USE_SYSTEM_OGGTHEORA=ON
        -DVTK_USE_SYSTEM_PNG=ON
        -DVTK_USE_SYSTEM_TIFF=ON
        -DVTK_USE_SYSTEM_ZLIB=ON 
Do not match with the CMakeCache.txt result
VTK_USE_SYSTEM_EXPAT:BOOL=ON
VTK_USE_SYSTEM_FREETYPE:BOOL=ON
VTK_USE_SYSTEM_GL2PS:BOOL=OFF
VTK_USE_SYSTEM_GLEW:BOOL=OFF
VTK_USE_SYSTEM_HDF5:BOOL=ON
VTK_USE_SYSTEM_JPEG:BOOL=OFF
VTK_USE_SYSTEM_JSONCPP:BOOL=ON
VTK_USE_SYSTEM_LIBPROJ4:BOOL=OFF
VTK_USE_SYSTEM_LIBRARIES:BOOL=OFF
VTK_USE_SYSTEM_LIBXML2:BOOL=ON
VTK_USE_SYSTEM_NETCDF:BOOL=OFF
VTK_USE_SYSTEM_OGGTHEORA:BOOL=OFF
VTK_USE_SYSTEM_PNG:BOOL=ON
VTK_USE_SYSTEM_TIFF:BOOL=ON
VTK_USE_SYSTEM_ZLIB:BOOL=ON
The ninja build script contains a lot of references to the vtk/thirdparty folder for lib glew and jpeg.

----

-With my version 0.0.81 pdbs are not copied.
-The patch applied message is printed into the error log file instead of the normal log file.
-And it would be nice to get an cleanup command that cleans all build artifacs from the sourcetree.

**Comment by albertziegenhagel** [comment] 2017-05-22 15:40
I think this is a duplicate of #739

Can you try the workaround described in the comments of that issue?

**Comment by Fleischner** [comment] 2017-05-25 20:55
Thanks the helps. (However in the meantime we already removed the dependency to hdf5 in our port, as we don't need it)

A little flaw that could get fixed in the future: vtkjpeg-7.1.dll and vtkglew-7.1.dll get build form the internal dependencies instead from vcpkg ports.

**Comment by KindDragon** [comment] 2017-07-05 07:53
Can be closed

**Closed** 2019-02-27 06:23 UTC
