### ISSUE TITLE
How do I ...

### ISSUE THREAD

**Issue by chuichuiY** [microsoft/vcpkg#26440] opened 2022-08-20 13:25 UTC
error: building giflib:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+giflib
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[giflib]+Build+error
Include '[giflib] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-07-21-a0e87e227afb536c62188c11ad029954f28fdb22
    vcpkg-scripts version: d293ac220 2022-08-12 (8 days ago)

You can also use the prefilled template from F:\dev\installed\vcpkg\issue_body.md.

**Comment by FrankXie05** [comment] 2022-08-22 03:03
@chuichuiY Is this issue duplicate of https://github.com/microsoft/vcpkg/issues/26439, if not please reply me and I will reopen it

**Closed by FrankXie05** 2022-08-22 03:03 UTC
