### ISSUE TITLE
[fmt] Build error

### ISSUE THREAD

**Issue by GLgele** [microsoft/vcpkg#25584] opened 2022-07-05 12:15 UTC
**Host Environment**
- OS: Windows
- Compiler: revision

**To Reproduce**
` ./vcpkg install spdlog`

**Failure logs**
```
`CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/Users/Administrator/Documents/GitHub/vcpkg/buildtrees/fmt/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Users\Administrator\Documents\GitHub\vcpkg\buildtrees\fmt\config-x86-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:238 (vcpkg_execute_required_process)
  ports/fmt/portfile.cmake:12 (vcpkg_cmake_configure)
  scripts/ports.cmake:146 (include)


error: building fmt:x86-windows failed with: BUILD_FAILED `
```
**Additional context**
Full Text:
```
` Computing installation plan...
The following packages will be built and installed:
  * fmt[core]:x86-windows -> 8.1.1#1
    spdlog[core]:x86-windows -> 1.10.0#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet "x86-windows"...
Restored 0 packages from C:\Users\Administrator\AppData\Local\vcpkg\archives in 222.3 us. Use --debug to see more details.
Installing 1/2 fmt:x86-windows...
Building fmt[core]:x86-windows...
-- Using cached fmtlib-fmt-8.1.1.tar.gz.
-- Cleaning sources at D:/Users/Administrator/Documents/GitHub/vcpkg/buildtrees/fmt/src/8.1.1-11f8359597.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Users/Administrator/Documents/GitHub/vcpkg/downloads/fmtlib-fmt-8.1.1.tar.gz
-- Applying patch fix-write-batch.patch
-- Applying patch fix-invalid-command.patch
-- Using source at D:/Users/Administrator/Documents/GitHub/vcpkg/buildtrees/fmt/src/8.1.1-11f8359597.clean
-- Found external ninja('1.10.2').
-- Configuring x86-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:83 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/Users/Administrator/Documents/GitHub/vcpkg/buildtrees/fmt/x86-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\Users\Administrator\Documents\GitHub\vcpkg\buildtrees\fmt\config-x86-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:238 (vcpkg_execute_required_process)
  ports/fmt/portfile.cmake:12 (vcpkg_cmake_configure)
  scripts/ports.cmake:146 (include)


error: building fmt:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+fmt
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[fmt]+Build+error
Include '[fmt] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: 4826ede84 2022-07-01 (3 days ago)
```
You can also use the prefilled template from D:\Users\Administrator\Documents\GitHub\vcpkg\installed\vcpkg\issue_body.md `

**Comment by GLgele** [comment] 2022-07-06 04:53
Fixed...
but i don't know how it worked....

**Comment by Cheney-W** [comment] 2022-07-06 06:37
Good to know that the issue is gone, I can't reproduce the same on my side.
I'll close this issue, and if it reappears with you, please reopen this issue and send the failure log to us.

**Closed** 2022-07-06 06:38 UTC
Labels: requires:repro
