### ISSUE TITLE
[cpp-httplib] CMAKE configure failure at httplibConfig.cmake

### ISSUE THREAD

**Issue by CPT-KK** [microsoft/vcpkg#38077] opened 2024-04-09 15:34 UTC
### Operating system

Windows x64

### Compiler

MSVC

### Steps to reproduce the behavior

```Shell
1. `vcpkg install cpp-httplib`
2. `vcpkg add port cpp-httplib` at work dir
3. Add `find_package(httplib REQUIRED)` to CMakeLists.txt
4. Run CMAKE configure
5. CMAKE returned error 
> `CMake Error at build/vcpkg_installed/x64-windows-static/share/httplib/httplibConfig.cmake:12 (message)`
```

### Failure logs

[cmake] -- Running vcpkg install
[cmake] Loading dependency information for 152 packages...
[cmake] Detecting compiler hash for triplet x64-windows-static...
[cmake] Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe
[cmake] Detecting compiler hash for triplet x64-windows...
[cmake] Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe
[cmake] All requested packages are currently installed.
[cmake] Total install time: 500 ns
[cmake] cpp-httplib provides CMake targets:
[cmake] 
[cmake]     find_package(httplib CONFIG REQUIRED)
[cmake]     target_link_libraries(main PRIVATE httplib::httplib)
[cmake] 
[cmake] -- Running vcpkg install - done
[cmake] -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
[cmake] CMake Error at build/vcpkg_installed/x64-windows-static/share/httplib/httplibConfig.cmake:12 (message):
[cmake]   File or directory <some_path>/build/vcpkg_installed/include referenced by variable
[cmake]   HTTPLIB_INCLUDE_DIR does not exist !
[cmake] Call Stack (most recent call first):
[cmake]   build/vcpkg_installed/x64-windows-static/share/httplib/httplibConfig.cmake:64 (set_and_check)
[cmake]   C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake:859 (_find_package)
[cmake]   CMakeLists.txt:13 (find_package)
[cmake] 
[cmake] 
[cmake] -- Configuring incomplete, errors occurred!

### Additional context

I believe the reason is as follows.
- In line 12 of the `httplibConfig.cmake`, a marco named `set_and_check` is defined.
- In line 64 of the `httplibConfig.cmake`, the marco is called, but the triplet information is missing in the second input `"${PACKAGE_${CMAKE_FIND_PACKAGE_NAME}_COUNTER_1}/include"`, which is a path to the header file.
- The problem seems to be solved by changing "${PACKAGE_${CMAKE_FIND_PACKAGE_NAME}_COUNTER_1}/include"` to `set_and_check(HTTPLIB_INCLUDE_DIR "${PACKAGE_${CMAKE_FIND_PACKAGE_NAME}_COUNTER_1}/${VCPKG_TARGET_TRIPLET}/include")`.
- The same goes for line 67.

**Comment by dg0yt** [comment] 2024-04-09 17:42
https://github.com/microsoft/vcpkg/issues/37968
Get of CMake 3.29.1, and reinstall all ports that were built with that version.

**Comment by WangWeiLin-MV** [comment] 2024-04-10 01:23
Duplicate of #37968

**Closed by WangWeiLin-MV** 2024-04-10 01:23 UTC
Labels: category:port-bug

**Comment by CPT-KK** [comment] 2024-04-10 01:27
Much appreciated
