### ISSUE TITLE
ceres[suitesparse,cxsparse] does not enable SUITESPARSE

### ISSUE THREAD

**Issue by patrikhuber** [microsoft/vcpkg#3417] opened 2018-05-03 21:55 UTC
I installed the following:
`.\vcpkg install ceres[suitesparse,cxsparse]:x64-windows --recurse`

But despite that, `sparse_linear_algebra_library_type` of a `Solver` is set to `NO_SPARSE (3)`, and if I try to use SuiteSparse, I get:

`solver.cc:531] Terminating: Can't use SPARSE_SCHUR with SUITESPARSE because SuiteSparse was not enabled when Ceres was built.`

cxsparse doesn't appear to be working either.

**Comment by patrikhuber** [comment] 2018-05-04 06:11
Tried with `[eigensparse]` now. Same results.
What's weird is that CMake outputs that Ceres has been installed with the sparse components:
> Found Ceres version: 1.14.0 installed in: C:/Users/Patrik/vcpkg/installed/x64-windows with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, C++11, OpenMP, Multithreading]

I'm not sure it has anything to do with it but what's also a bit weird is that in Debug mode, even if I do `ceres::Solver::Options opts = ceres::Solver::Options();` to explicitly call the constructor, if I set a breakpoint inside the constructor in `vcpkg\installed\x64-windows\include\ceres\solver.h`, the breakpoint doesn't get hit.
Also there are quite a number of compiler warnings like this one:
> Warning	C4251	'ceres::Solver::Options::linear_solver_ordering': class 'std::shared_ptr<ceres::ParameterBlockOrdering>' needs to have dll-interface to be used by clients of struct 'ceres::Solver::Options'	myapp	vcpkg\installed\x64-windows\include\ceres\solver.h	503

**Comment by warlock8hz** [comment] 2019-01-25 08:07
Same problem, you fixed it now?

**Comment by warlock8hz** [comment] 2019-01-25 08:08
> Tried with `[eigensparse]` now. Same results.
> What's weird is that CMake outputs that Ceres has been installed with the sparse components:
> 
> > Found Ceres version: 1.14.0 installed in: C:/Users/Patrik/vcpkg/installed/x64-windows with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, C++11, OpenMP, Multithreading]
> 
> I'm not sure it has anything to do with it but what's also a bit weird is that in Debug mode, even if I do `ceres::Solver::Options opts = ceres::Solver::Options();` to explicitly call the constructor, if I set a breakpoint inside the constructor in `vcpkg\installed\x64-windows\include\ceres\solver.h`, the breakpoint doesn't get hit.
> Also there are quite a number of compiler warnings like this one:
> 
> > Warning	C4251	'ceres::Solver::Options::linear_solver_ordering': class 'std::shared_ptrceres::ParameterBlockOrdering' needs to have dll-interface to be used by clients of struct 'ceres::Solver::Options'	myapp	vcpkg\installed\x64-windows\include\ceres\solver.h	503

Same problem, you fixed it?

**Comment by VVingerfly** [comment] 2019-03-01 05:54
> I installed the following:
> `.\vcpkg install ceres[suitesparse,cxsparse]:x64-windows --recurse`
> 
> But despite that, `sparse_linear_algebra_library_type` of a `Solver` is set to `NO_SPARSE (3)`, and if I try to use SuiteSparse, I get:
> 
> `solver.cc:531] Terminating: Can't use SPARSE_SCHUR with SUITESPARSE because SuiteSparse was not enabled when Ceres was built.`
> 
> cxsparse doesn't appear to be working either.


Hi, I have the same problem as yours, have you fixed it? Thanks.

**Comment by warlock8hz** [comment] 2019-03-01 07:42
> > I installed the following:
> > `.\vcpkg install ceres[suitesparse,cxsparse]:x64-windows --recurse`
> > But despite that, `sparse_linear_algebra_library_type` of a `Solver` is set to `NO_SPARSE (3)`, and if I try to use SuiteSparse, I get:
> > `solver.cc:531] Terminating: Can't use SPARSE_SCHUR with SUITESPARSE because SuiteSparse was not enabled when Ceres was built.`
> > cxsparse doesn't appear to be working either.
> 
> Hi, I have the same problem as yours, have you fixed it? Thanks.

If you are using vs, clear all the previous builds and rebuild again. That's how I fix the problem.

**Comment by warlock8hz** [comment] 2019-03-01 07:43
> > I installed the following:
> > `.\vcpkg install ceres[suitesparse,cxsparse]:x64-windows --recurse`
> > But despite that, `sparse_linear_algebra_library_type` of a `Solver` is set to `NO_SPARSE (3)`, and if I try to use SuiteSparse, I get:
> > `solver.cc:531] Terminating: Can't use SPARSE_SCHUR with SUITESPARSE because SuiteSparse was not enabled when Ceres was built.`
> > cxsparse doesn't appear to be working either.
> 
> Hi, I have the same problem as yours, have you fixed it? Thanks.

You should make sure cxsparse and other dependencies have already been installed using vcpkg first.

**Comment by VVingerfly** [comment] 2019-03-02 08:39
> > > I installed the following:
> > > `.\vcpkg install ceres[suitesparse,cxsparse]:x64-windows --recurse`
> > > But despite that, `sparse_linear_algebra_library_type` of a `Solver` is set to `NO_SPARSE (3)`, and if I try to use SuiteSparse, I get:
> > > `solver.cc:531] Terminating: Can't use SPARSE_SCHUR with SUITESPARSE because SuiteSparse was not enabled when Ceres was built.`
> > > cxsparse doesn't appear to be working either.
> > 
> > 
> > Hi, I have the same problem as yours, have you fixed it? Thanks.
> 
> If you are using vs, clear all the previous builds and rebuild again. That's how I fix the problem.


Hi, thanks for you reply.
I used the command `.\vcpkg install ceres[suitesparse,cxsparse]:x64-windows --recurse` to reinstall ceres with suitesparse and cxsparse support, and option `--recurse`  enables uninstalling previous installed ceres first.
And then the command `.\vcpkg list` shows
```
ceres:x64-windows                                  1.14.0-1         non-linear optimization package
ceres[cxsparse]:x64-windows                                         CXSparse support for Ceres
ceres[lapack]:x64-windows                                           Use Lapack in Ceres
ceres[suitesparse]:x64-windows                                      SuiteSparse support for Ceres
```
But in VS, I still can't use `options.linear_solver_type = ceres::SPARSE_NORMAL_CHOLESKY;`

Is there any thing wrong here?
What do u mean by saying `clear all the previous builds and rebuild again`？Does it mean use `.\vcpkg uninstall ceres` first, then  use `.\vcpkg install ceres[suitesparse,cxsparse]:x64-windows`?

Thanks!

**Comment by warlock8hz** [comment] 2019-03-02 09:45
> > > > I installed the following:
> > > > `.\vcpkg install ceres[suitesparse,cxsparse]:x64-windows --recurse`
> > > > But despite that, `sparse_linear_algebra_library_type` of a `Solver` is set to `NO_SPARSE (3)`, and if I try to use SuiteSparse, I get:
> > > > `solver.cc:531] Terminating: Can't use SPARSE_SCHUR with SUITESPARSE because SuiteSparse was not enabled when Ceres was built.`
> > > > cxsparse doesn't appear to be working either.
> > > 
> > > 
> > > Hi, I have the same problem as yours, have you fixed it? Thanks.
> > 
> > 
> > If you are using vs, clear all the previous builds and rebuild again. That's how I fix the problem.
> 
> Hi, thanks for you reply.
> I used the command `.\vcpkg install ceres[suitesparse,cxsparse]:x64-windows --recurse` to reinstall ceres with suitesparse and cxsparse support, and option `--recurse` enables uninstalling previous installed ceres first.
> And then the command `.\vcpkg list` shows
> 
> ```
> ceres:x64-windows                                  1.14.0-1         non-linear optimization package
> ceres[cxsparse]:x64-windows                                         CXSparse support for Ceres
> ceres[lapack]:x64-windows                                           Use Lapack in Ceres
> ceres[suitesparse]:x64-windows                                      SuiteSparse support for Ceres
> ```
> But in VS, I still can't use `options.linear_solver_type = ceres::SPARSE_NORMAL_CHOLESKY;`
> 
> Is there any thing wrong here?
> What do u mean by saying `clear all the previous builds and rebuild again`？Does it mean use `.\vcpkg uninstall ceres` first, then use `.\vcpkg install ceres[suitesparse,cxsparse]:x64-windows`?
> 
> Thanks!

That sounds exactly the same as my situation. 

Try clean all previous builds in YOUR project/solution and rebuild the solution to fix it. 

The problem is due to the previous builds does not actually link to the updated library.

**Comment by patrikhuber** [comment] 2019-03-02 10:15
> The problem is due to the previous builds does not actually link to the updated library.

You mean your own project's builds, that link to Ceres? No that wasn't the problem in my case.

What you perhaps mean is deleting the `vcpkg/buildtrees` folder? I think I tried this but don't remember 100%, in any case I am not convinced that this helps fix the problem.

**Comment by warlock8hz** [comment] 2019-03-02 10:50
> > The problem is due to the previous builds does not actually link to the updated library.
> 
> You mean your own project's builds, that link to Ceres? No that wasn't the problem in my case.
> 
> What you perhaps mean is deleting the `vcpkg/buildtrees` folder? I think I tried this but don't remember 100%, in any case I am not convinced that this helps fix the problem.

I did try uninstalling and reinstalling the ceres and its dependency in vcpkg. But no use. 

After trying everything and asking help from some experienced guy, the only answer in my case is clean and rebuild my project.

**Comment by VVingerfly** [comment] 2019-03-03 02:49
> the only answer in my case is clean and rebuild my project.

Hi, do you mean clean and rebuild your VS project? @warlock8hz

**Comment by warlock8hz** [comment] 2019-03-03 05:15
> > the only answer in my case is clean and rebuild my project.
> 
> Hi, do you mean clean and rebuild your VS project? @warlock8hz

Don't say it, try it

**Comment by danieltuzes** [comment] 2019-05-14 13:31
@warlock8hz I have only installed `.\vcpkg install suitesparse:x64-windows`, but VS says `Cannot open include file: 'umfpack.h': No such file or directory`. If I include `C:\local\vcpkg\packages\suitesparse_x64-windows\include\suitesparse` in the VC++ Directories under Include Directories, my project compiles. If I remove it, I cannot compile, even I clean my solution followed by a VS restart.

So is this a bug, is there something I still do wrong?

**Comment by NancyLi1013** [comment] 2019-07-18 05:53
Hi @patrikhuber, thanks for posting this issue. This port has been updated. This issue should be fixed now. I cannot reproduce it on my local. Please let us know whether it still exists on your machine now. If yes, please provide project case.
@danieltuzes, could you update suitesparse and try it again? I can use it successfully.

**Comment by NancyLi1013** [comment] 2019-08-02 08:27
Please feel free to reopen this issue if this is still a problem for you.

**Closed by NancyLi1013** 2019-08-02 08:27 UTC
Labels: port bug
