### ISSUE TITLE
Error happened when detecting compiler hash for triplet x64-windows

### ISSUE THREAD

**Issue by ENDLESSZ** [microsoft/vcpkg#36260] opened 2024-01-19 14:42 UTC
Hello guys, I was dealing with vcpkg install on win11 OS. It's seeming to be fatal error happening. 

Here is all call back in cmd:

C:\Users\25124> vcpkg install netcdf-c gdal[core,tools,default-features] pcre2 fftw3[core,threads] clapack openblas --triplet x64-windows
Computing installation plan...
The following packages are already installed:
    clapack:x64-windows@3.2.1#22
    fftw3[core,threads]:x64-windows@3.3.10#8
    openblas:x64-windows@0.3.25
The following packages will be built and installed:
    gdal[core,curl,default-features,expat,geos,gif,hdf5,iconv,jpeg,lerc,libkml,libspatialite,libxml2,lzma,netcdf,openjpeg,openssl,pcre2,png,postgresql,qhull,recommended-features,sqlite3,tools,webp,zstd]:x64-windows@3.8.3
  * libpq[core,lz4,openssl,zlib]:x64-windows@16.0#1
  * libspatialite[core,freexl]:x64-windows@5.1.0#1
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows@1.3.2
  * libxml2[core,http,iconv,lzma,zlib]:x64-windows@2.11.6#1
    netcdf-c[core,dap,hdf5,nczarr,netcdf-4]:x64-windows@4.8.1#4
  * openjpeg:x64-windows@2.5.0#1
  * openssl:x64-windows@3.2.0#2
    pcre2[core,jit,platform-default-features]:x64-windows@10.42#1
  * pkgconf:x64-windows@2.1.0
  * qhull:x64-windows@8.0.2#4
  * vcpkg-pkgconfig-get-modules:x64-windows@2023-09-06
  * vcpkg-tool-meson:x64-windows@0.63#2
  * zstd:x64-windows@1.5.5#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Restored 0 package(s) from C:\Users\25124\AppData\Local\vcpkg\archives in 251 us. Use --debug to see more details.
clapack:x64-windows is already installed
fftw3:x64-windows is already installed
openblas:x64-windows is already installed
Installing 1/14 openssl:x64-windows@3.2.0#2...
Building openssl:x64-windows@3.2.0#2...
-- Using cached openssl-openssl-openssl-3.2.0.tar.gz.
-- Cleaning sources at F:/GMT/vcpkg/vcpkg-master/vcpkg-master/buildtrees/openssl/src/nssl-3.2.0-5a1db6e780.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/GMT/vcpkg/vcpkg-master/vcpkg-master/downloads/openssl-openssl-openssl-3.2.0.tar.gz
-- Applying patch asm-comments.patch
-- Applying patch declspec-align.patch
-- Applying patch qt-msvc.patch
-- Applying patch script-prefix.patch
-- Applying patch windows/install-layout.patch
-- Applying patch windows/install-pdbs.patch
-- Applying patch unix/android-cc.patch
-- Applying patch unix/move-openssldir.patch
-- Applying patch unix/no-empty-dirs.patch
-- Applying patch unix/no-static-libs-for-shared.patch
-- Applying patch unix/disable-quicserver.patch
-- Using source at F:/GMT/vcpkg/vcpkg-master/vcpkg-master/buildtrees/openssl/src/nssl-3.2.0-5a1db6e780.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Prerunning x64-windows-dbg
-- Building x64-windows-dbg
-- Restarting build without parallelism
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "F:/Visual Studio/123/VC/Tools/MSVC/14.38.33130/bin/Hostx64/x64/nmake.exe" /NOLOGO /G /U /F makefile install_dev install_modules INSTALL_PDBS=ON
    Working Directory: F:/GMT/vcpkg/vcpkg-master/vcpkg-master/buildtrees/openssl/x64-windows-dbg
    See logs for more information:
      F:\GMT\vcpkg\vcpkg-master\vcpkg-master\buildtrees\openssl\install-x64-windows-dbg-nmake-out.log
      F:\GMT\vcpkg\vcpkg-master\vcpkg-master\buildtrees\openssl\install-x64-windows-dbg-nmake-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_nmake.cmake:156 (vcpkg_execute_build_process)
  ports/openssl/windows/portfile.cmake:69 (vcpkg_build_nmake)
  ports/openssl/portfile.cmake:78 (include)
  scripts/ports.cmake:170 (include)

error: building openssl:x64-windows failed with: BUILD_FAILED
Elapsed time to handle openssl:x64-windows: 42 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[openssl]+Build+error+on+x64-windows&body=Copy+issue+body+from+F%3A%2FGMT%2Fvcpkg%2Fvcpkg-master%2Fvcpkg-master%2Finstalled%2Fvcpkg%2Fissue_body.md

Here are dialogs establish by the app:

[install-x64-windows-dbg-jom-err.log](https://github.com/microsoft/vcpkg/files/13990551/install-x64-windows-dbg-jom-err.log)
[install-x64-windows-dbg-jom-out.log](https://github.com/microsoft/vcpkg/files/13990555/install-x64-windows-dbg-jom-out.log)
[install-x64-windows-dbg-nmake-err.log](https://github.com/microsoft/vcpkg/files/13990556/install-x64-windows-dbg-nmake-err.log)
[install-x64-windows-dbg-nmake-out.log](https://github.com/microsoft/vcpkg/files/13990557/install-x64-windows-dbg-nmake-out.log)

**Comment by MonicaLiu0311** [comment] 2024-01-22 05:52
Duplicate of https://github.com/microsoft/vcpkg/issues/36175

**Closed by MonicaLiu0311** 2024-01-22 05:52 UTC
Labels: category:question
