### ISSUE TITLE
[harfbuzz] Build error

### ISSUE THREAD

**Issue by LarsLive** [microsoft/vcpkg#34037] opened 2023-09-26 18:15 UTC
Copy issue body from C:/vcpkg/installed/vcpkg/issue_body.md

-- Package x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe install -v
    Working Directory: C:/vcpkg/buildtrees/harfbuzz/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\harfbuzz\package-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:70 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)

error: building harfbuzz:x64-windows failed with: BUILD_FAILED
Elapsed time to handle harfbuzz:x64-windows: 2.9 min

Here the compile error out of log file:
        with
        [
            Type=void
        ]
C:\vcpkg\buildtrees\harfbuzz\src\8.2.1-63f9ae7085.clean\src\hb-subset.cc : fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj
ninja: build stopped: subcommand failed.

**Comment by FrankXie05** [comment] 2023-09-27 07:56
Could you please use the latest vcpkg and try again?

**Comment by LarsLive** [comment] 2023-09-27 10:53
I tried again with latest vcpkg:

git pull
.\vcpkg.exe update
.\vcpkg.exe install qt5 --triplet x86-windows


But unfortunately I get the same error again:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_install_meson.cmake:33 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:70 (vcpkg_install_meson)
  scripts/ports.cmake:147 (include)


error: building harfbuzz:x64-windows failed with: BUILD_FAILED
Elapsed time to handle harfbuzz:x64-windows: 3 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+harfbuzz
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[harfbuzz]+Build+error&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
[https://github.githubassets.com/images/modules/open_graph/github-logo.png]<https://github.com/microsoft/vcpkg/issues/new?title=[harfbuzz]+Build+error&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md>
Build software better, together<https://github.com/microsoft/vcpkg/issues/new?title=[harfbuzz]+Build+error&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md>
GitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 330 million projects.
github.com





________________________________
Von: Frank ***@***.***>
Gesendet: Mittwoch, 27. September 2023 07:56
An: microsoft/vcpkg ***@***.***>
Cc: LarsLive ***@***.***>; Author ***@***.***>
Betreff: Re: [microsoft/vcpkg] [harfbuzz] Build error (Issue #34037)


Could you please use the latest vcpkg and try again?

**Comment by SchaichAlonso** [comment] 2023-09-29 10:48
Can you try deleting the checkout  and cloning/bootstrapping it again?

In order to update, rather then recloning, you should delete everything in `downloads/tools` and then re-run `bootstrap-vcpkg.bat` to prevent the ports refering to vcpkg functionallity that wasn't yet available or was buggy and had to be workarounded at the time you invoked `bootstrap-vcpkg.bat` the last time. 

Also, adding `--debug` to `vcpkg install` will have it emit some diagnostics indicating what third-party tools are being used to compile each port.

**Comment by dg0yt** [comment] 2023-09-29 11:30
There is no need to delete everything, or to debug vcpgk. The compiler flags should be in the packages log, and there is a configuration log. However, the logs are not shared here, and the error doesn't seem to appear elsewhere. We can't guess the trigger in this way.

> `C:\vcpkg\buildtrees\harfbuzz\src\8.2.1-63f9ae7085.clean\src\hb-subset.cc ...`

8.2.1-63f9ae7085.clean looks like the current source configuration.

> Duplicate issue #26202 
> And has been fixed by PR #26229

And the fix was removed in #28243.

Upstream issues: https://github.com/search?q=repo%3Aharfbuzz%2Fharfbuzz+bigobj&type=issues

**Comment by dg0yt** [comment] 2023-09-29 11:31
... we don't even know the features ...

**Comment by sfc9982** [comment] 2023-10-04 09:37
For me, use MSVC rather than 2017 solve the problem:
```
set(VCPKG_PLATFORM_TOOLSET "v142")
set(VCPKG_DEP_INFO_OVERRIDE_VARS "v142")
```

Or you can choose the version by settings above, just put them into triplets.

**Comment by oliVRqin** [comment] 2023-10-06 06:33
@FrankXie05, I was able to reproduce this issue and have the exact same error as @LarsLive

**Comment by FrankXie05** [comment] 2023-10-07 08:36
@oliVRqin 
I don't know why the patch was deleted, it was not merged. cc @Neumann-A 

You can temporarily use this patch to solve the problem.
https://github.com/microsoft/vcpkg/pull/26229/files#:~:text=)-,%2Bextra_hb_cpp_args%20%3D%20%5B%5D,%2B,-hb_subset_headers%20%3D%20files(

**Comment by oliVRqin** [comment] 2023-10-08 06:37
@FrankXie05 seems like the file where that change was made doesn't exist anymore/may have been removed since the patch. I tried the fix you proposed and it doesn't seem to work :(

**Comment by FrankXie05** [comment] 2023-10-08 06:44
@oliVRqin Can't find the patch or the patch doesn't work?

**Comment by oliVRqin** [comment] 2023-10-08 07:00
@FrankXie05 I ended up using GPT for the fix, for future people I added "-Dc_args=['/bigobj']" and  "-Dcpp_args=['/bigobj']"  under the default setup within the vcpkg_configure_meson function in the portfile.cmake file in /ports/harfbuzz/portfile.cmake.

so it should look like something like this: 

`OPTIONS_DEBUG
        ${OPTIONS_DEBUG}
        "-Dc_args=['/bigobj']"
        "-Dcpp_args=['/bigobj']"
    OPTIONS_RELEASE
        ${OPTIONS_RELEASE}
        "-Dc_args=['/bigobj']"
        "-Dcpp_args=['/bigobj']"`

**Closed** 2023-10-09 22:37 UTC
Labels: requires:repro
