### ISSUE TITLE
Error: Building package fribidi:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by Basheer33** [microsoft/vcpkg#7213] opened 2019-07-09 17:59 UTC
This Happens while trying to install libass when it reaches the fribidi installing part
Package: fribidi:x64-windows
Vcpkg version :2019.06.26-nohash

CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: fribidi-58c6cb390a9a18c98b2cbaac555d8ea9352a9e4f/README
CMake Error: Problem extracting tar: C:/Users/bashe/vcpkg/downloads/fribidi-fribidi-58c6cb390a9a18c98b2cbaac555d8ea9352a9e4f.tar.gz

[extract-err.log](https://github.com/microsoft/vcpkg/files/3374239/extract-err.log)

**Comment by meitiever** [comment] 2019-07-17 06:25
This error occurs in protobuf(version google-protobuf-v3.8.0.tar.gz currently) as well.
Log:
CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: protobuf-3.8.0/examples/third_party/zlib.BUILD
CMake Error: Problem extracting tar: D:/Github/vcpkg/downloads/google-protobuf-v3.8.0.tar.gz

Could i specify vcpkg_from_github download google-protobuf-v3.8.0.zip instead of google-protobuf-v3.8.0.tar.gz?
zip file could be extracted correctly.

**Comment by reid-p** [comment] 2019-08-01 09:32
I've hit the similar problem with:

CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: SDL-release-2.0.9/android-project-ant/AndroidManifest.xml
CMake Error: Problem extracting tar: C:/vcpkg/downloads/SDL-Mirror-SDL-release-2.0.9.tar.gz

CMake Error: Problem with archive_write_header(): Can't create ''
CMake Error: Current file: libexpat-R_2_2_6/README.md
CMake Error: Problem extracting tar: C:/vcpkg/downloads/libexpat-libexpat-R_2_2_6.tar.gz

The files failing are symlinks in the archive.

**Comment by reid-p** [comment] 2019-08-01 13:18
Found a work around, turn off windows setting "Beta: Use Unicode UTF-8"
run intl.cpl then Administrative Tab -> Change System Locale -> Unselect
"Beta: User Unicode UTF-8 for worldwide language support"

see: https://superuser.com/questions/1425331/tar-on-windows-fails-to-extract-symlink-out-of-archive

**Comment by wangli28** [comment] 2019-08-19 09:53
Hi @Basheer33, thanks for posting this issue! I can't reproduce this issue locally, does the issue persist? can you try vcpkg latest revision?

**Comment by reid-p** [comment] 2019-08-19 12:49
@wangli28, Have you tried enabling Win10 system option  "Beta: User Unicode UTF-8 for worldwide language support" I referenced above. 
The problem persists for me.

**Comment by wangli28** [comment] 2019-08-20 04:11
@reid-p Thanks for your suggestion! I reproduced it locally. Duplicated to issue #5951. So I am closing this issue for now. Please pay attention to the progress of issue #5951.

**Closed by wangli28** 2019-08-20 04:11 UTC
Labels: needs-repro
