### ISSUE TITLE
Add Ceres Solver 

### ISSUE THREAD

**Issue by bigdimboom** [Microsoft/vcpkg#1070] opened 2017-05-10 21:13 UTC
Ceres can solve bounds constrained robustified non-linear least squares problems.
http://ceres-solver.org/features.html

**Comment by KindDragon** [comment] 2017-06-09 14:39
Duplicate of #318

**Comment by KindDragon** [comment] 2017-06-30 08:31
@ras0219-msft Pls close issue

**Closed** 2017-06-30 16:34 UTC
Labels: new port request - consider making a PR!
