### ISSUE TITLE
[colmap] Build error on x64-windows ,failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by monkeycc** [microsoft/vcpkg#35312] opened 2023-11-25 00:38 UTC
`.\vcpkg install colmap[cuda,tests]:x64-windows`

```python
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows -> 2023-10-01
Detecting compiler hash for triplet x64-windows...
-- Automatically setting %HTTP(S)_PROXY% environment variables to "127.0.0.1:10809".
Restored 0 package(s) from C:\Users\monke\AppData\Local\vcpkg\archives in 85.4 us. Use --debug to see more details.
Installing 1/1 colmap:x64-windows...
Building colmap[core,cuda,tests]:x64-windows...
-- Using cached colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz.
-- Cleaning sources at E:/2023_Code_WEB/vcpkg/buildtrees/colmap/src/f69e5aa28f-361efbb7b2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/2023_Code_WEB/vcpkg/downloads/colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz
-- Using source at E:/2023_Code_WEB/vcpkg/buildtrees/colmap/src/f69e5aa28f-361efbb7b2.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: "D:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j21
    Working Directory: E:/2023_Code_WEB/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      E:\2023_Code_WEB\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:58 (vcpkg_cmake_install)
  scripts/ports.cmake:170 (include)


error: building colmap:x64-windows failed with: BUILD_FAILED
Elapsed time to handle colmap:x64-windows: 1.7 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[colmap]+Build+error+on+x64-windows&body=Copy+issue+body+from+E%3A%2F2023_Code_WEB%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

```

```python

E:\2023_Code_WEB\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src\colmap/optim/loransac.h(86): note: 查看对正在编译的函数 模板 实例化“colmap::RANSAC<Estimator,SupportMeasurer,Sampler>::RANSAC(const colmap::RANSACOptions &)”的引用
        with
        [
            Estimator=colmap::SimilarityTransformEstimator<3,true>,
            SupportMeasurer=colmap::InlierSupportMeasurer,
            Sampler=colmap::RandomSampler
        ]
E:\2023_Code_WEB\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src\colmap/optim/loransac.h(86): note: 在编译 类 模板 成员函数“colmap::LORANSAC<colmap::SimilarityTransformEstimator<3,true>,colmap::SimilarityTransformEstimator<3,true>,colmap::InlierSupportMeasurer,colmap::RandomSampler>::LORANSAC(const colmap::RANSACOptions &)”时
E:\2023_Code_WEB\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src\colmap\optim\loransac_test.cc(83): note: 查看对正在编译的函数 模板 实例化“colmap::LORANSAC<colmap::SimilarityTransformEstimator<3,true>,colmap::SimilarityTransformEstimator<3,true>,colmap::InlierSupportMeasurer,colmap::RandomSampler>::LORANSAC(const colmap::RANSACOptions &)”的引用
E:\2023_Code_WEB\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src\colmap\optim\loransac_test.cc(46): note: 查看对正在编译的 类 模板 实例化“colmap::LORANSAC<colmap::SimilarityTransformEstimator<3,true>,colmap::SimilarityTransformEstimator<3,true>,colmap::InlierSupportMeasurer,colmap::RandomSampler>”的引用
[205/369] "C:\PROGRA~2\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe"   /TP -DBOOST_ALL_DYN_LINK=1 -DCGAL_USE_GMPXX=1 -DCOLMAP_CGAL_ENABLED -DCOLMAP_CUDA_ENABLED -DCOLMAP_GPU_ENABLED -DCOLMAP_GUI_ENABLED -DCOLMAP_OPENGL_ENABLED -DCOLMAP_OPENMP_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DIMATH_DLL -DNOMINMAX -DOPENEXR_DLL -DQT_CORE_LIB -DQT_GUI_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DWIN32_LEAN_AND_MEAN -D_MWAITXINTRIN_H_INCLUDED -IE:\2023_Code_WEB\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\include -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\include\eigen3 -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\include\webp -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\include\OpenEXR -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\include\Imath -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\include\qt5 -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\include\qt5\QtCore -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\include\qt5\QtWidgets -external:IE:\2023_Code_WEB\vcpkg\installed\x64-windows\include\qt5\QtGui -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP /bigobj /W3 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++14 /Zc:__cplusplus /EHsc -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /bigobj /showIncludes /Fosrc\colmap\mvs\CMakeFiles\colmap_mvs.dir\meshing.cc.obj /Fdsrc\colmap\mvs\CMakeFiles\colmap_mvs.dir\colmap_mvs.pdb /FS -c E:\2023_Code_WEB\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src\colmap\mvs\meshing.cc
ninja: build stopped: subcommand failed.
```

```python
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_INSTALL_BINDIR
    FETCHCONTENT_FULLY_DISCONNECTED
    _VCPKG_ROOT_DIR

```

```
vcpkg version
vcpkg package management program version 2023-11-16-4c1df40a3c5c5e18de299a99e9accb03c2a82e1e

cmake --version
cmake version 3.28.0-rc5

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

python -V
Python 3.8.18

```

[colmap_log.zip](https://github.com/microsoft/vcpkg/files/13462857/colmap_log.zip)

**Comment by LilyWangLL** [comment] 2023-11-27 07:22
Duplicate of https://github.com/microsoft/vcpkg/issues/30272

**Closed by LilyWangLL** 2023-11-27 07:22 UTC
Labels: category:port-bug

**Comment by GhostRenia** [comment] 2023-12-08 02:12
Hi, I have the same error here. And I don't know how to solve it!
