### ISSUE TITLE
Problems installing openal-soft

### ISSUE THREAD

**Issue by bjornwah** [Microsoft/vcpkg#2985] opened 2018-03-07 23:09 UTC
Hi!

I'm having issues installing sfml with one dependency, openal-soft, failing.

From powershell:

> PS C:\dev\vcpkg> .\vcpkg.exe install sfml
> The following packages will be built and installed:
>   * openal-soft[core]:x86-windows
>     sfml[core]:x86-windows
>   * stb[core]:x86-windows
> Additional packages (*) will be modified to complete this operation.
> Starting package 1/3: openal-soft:x86-windows
> Building package openal-soft[core]:x86-windows...
> -- CURRENT_INSTALLED_DIR=C:/dev/vcpkg/installed/x86-windows
> -- DOWNLOADS=C:/dev/vcpkg/downloads
> -- CURRENT_PACKAGES_DIR=C:/dev/vcpkg/packages/openal-soft_x86-windows
> -- CURRENT_BUILDTREES_DIR=C:/dev/vcpkg/buildtrees/openal-soft
> -- CURRENT_PORT_DIR=C:/dev/vcpkg/ports/openal-soft/.
> -- Using cached C:/dev/vcpkg/downloads/kcat-openal-soft-openal-soft-1.18.2.tar.gz
> -- Testing integrity of cached file...
> -- Testing integrity of cached file... OK
> -- Extracting done
> -- Applying patch C:/dev/vcpkg/ports/openal-soft/dont-export-symbols-in-static-build.patch
> -- Applying patch failed. This is expected if this patch was previously applied.
> -- Applying patch C:/dev/vcpkg/ports/openal-soft/dont-export-symbols-in-static-build.patch done
> -- Configuring x86-windows
> CMake Error at C:/dev/vcpkg/scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
>     Command failed: ninja;-v
>     Working Directory: C:/dev/vcpkg/buildtrees/openal-soft/x86-windows-rel/vcpkg-parallel-configure
>     See logs for more information:
>       C:\dev\vcpkg\buildtrees\openal-soft\config-x86-windows-out.log
> 
> Call Stack (most recent call first):
>   C:/dev/vcpkg/scripts/cmake/vcpkg_configure_cmake.cmake:250 (vcpkg_execute_required_process)
>   C:/dev/vcpkg/ports/openal-soft/portfile.cmake:23 (vcpkg_configure_cmake)
>   C:/dev/vcpkg/scripts/ports.cmake:72 (include)
> 
> 
> Error: Building package openal-soft:x86-windows failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: openal-soft:x86-windows
>   Vcpkg version: 0.0.105-2018-03-07-58e8c96de050907cbf76d567f247c01c68bb9855
> 
> Additionally, attach any relevant sections from the log files above.

From the log file:
> ...
> -- Could NOT find ALSA (missing: ALSA_LIBRARY ALSA_INCLUDE_DIR) 
> -- Could NOT find OSS (missing: OSS_INCLUDE_DIR) 
> -- Could NOT find AudioIO (missing: AUDIOIO_INCLUDE_DIR) 
> -- Could NOT find SoundIO (missing: SOUNDIO_LIBRARY SOUNDIO_INCLUDE_DIR) 
> -- Could NOT find QSA (missing: QSA_LIBRARY QSA_INCLUDE_DIR) 
> CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules/CheckIncludeFiles.cmake:63 (message):
>   Unknown arguments:
> 
>     -D_WIN32_WINNT=0x0502
> 
> Call Stack (most recent call first):
>   CMakeLists.txt:968 (CHECK_INCLUDE_FILES)
> ...

The reference log file is attached.

I did run vcpkg update but no help. I tried installing openal-soft stand-alone but that also didn't work.

Any help would be much appreciated :-)

//Björn W

[config-x86-windows-out.log](https://github.com/Microsoft/vcpkg/files/1791219/config-x86-windows-out.log)

**Comment by ras0219-msft** [comment] 2018-03-08 00:01
Thanks for posting this issue!

>CMake Error at C:/Program Files/CMake/share/cmake-3.11/Modules

This immediately makes me suspect that there is an issue in the latest CMake 3.11-rc2. The quickest way to test if this is the problem would be to temporarily rename the `C:\Program Files\CMake` folder to something else and re-run `vcpkg install sfml`, allowing Vcpkg to download our known-good version of CMake. I'll also try out the latest CMake as well to see if we can reproduce the issue ourselves :)

**Comment by bjornwah** [comment] 2018-03-08 12:20
I will test this tonight.

**Comment by bjornwah** [comment] 2018-03-10 01:08
Should I close the issue? Is vcpkg intended to work with 3.11?

**Comment by ras0219-msft** [comment] 2018-03-10 01:46
We certainly need to interact better than this!

For now, the best option available is to "block" certain versions of CMake that we know are bad (like this rc) and insist on pulling down our applocal copy. I'd like to use this issue to track that :)

**Comment by JayFoxRox** [comment] 2018-04-18 14:11
I think this should be closed because of https://github.com/appveyor/ci/issues/2231#issuecomment-379368245

**Comment by sanojsubran** [comment] 2018-09-25 14:54
Could anyone please mention the version of cmake to be used?

**Comment by izogfif** [comment] 2018-10-14 11:56
@sanojsubran 
> Could anyone please mention the version of cmake to be used?

3.10.2. Check https://github.com/Microsoft/vcpkg, it says:
> Optional: CMake 3.10.2

**Comment by LarryIII** [comment] 2019-02-20 02:38
This issue should be fixed in https://github.com/Microsoft/vcpkg/commit/3baf583934f3077070e9ed4e7684f743ecced577, so closed this issue!

**Closed by LarryIII** 2019-02-20 02:38 UTC
