### ISSUE TITLE
[Colmap] build failure

### ISSUE THREAD

**Issue by EvanZarrella** [microsoft/vcpkg#27992] opened 2022-11-24 09:30 UTC
Package: colmap[core]:x64-windows -> 2022-03-14#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.34.31933.0
-    vcpkg-tool version: 2022-11-10-5fdee72bc1fceca198fb1ab7589837206a8b81ba
    vcpkg-scripts version: c2c25d916 2022-11-23 (6 hours ago)

**To Reproduce**

`vcpkg install colmap:x64-windows`

**Failure logs**

```
-- Using cached colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz.
-- Cleaning sources at D:/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkg/downloads/colmap-colmap-29a1e3642a3b00734a52b21e597ea4d576485fe6.tar.gz
-- Applying patch fix-dependencies.patch
-- Using source at D:/vcpkg/buildtrees/colmap/src/d576485fe6-7dd36362d1.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
-- Building x64-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:131 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.24.0-windows/cmake-3.24.0-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j17
    Working Directory: D:/vcpkg/buildtrees/colmap/x64-windows-rel
    See logs for more information:
      D:\vcpkg\buildtrees\colmap\install-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:59 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)



```
<details><summary>D:\vcpkg\buildtrees\colmap\install-x64-windows-rel-out.log</summary>

```
[1/190] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DCGAL_ENABLED -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DRELEASE -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -ID:\vcpkg\installed\x64-windows\include -ID:\vcpkg\installed\x64-windows\include\eigen3 -ID:\vcpkg\installed\x64-windows\include\qt5 -ID:\vcpkg\installed\x64-windows\include\qt5\QtCore -ID:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -ID:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -ID:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -ID:\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W0 /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /Folib\PoissonRecon\CMakeFiles\poisson_recon.dir\CmdLineParser.cpp.obj /Fdlib\PoissonRecon\CMakeFiles\poisson_recon.dir\poisson_recon.pdb /FS -c D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\PoissonRecon\CmdLineParser.cpp
[2/190] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DCGAL_ENABLED -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -DRELEASE -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -ID:\vcpkg\installed\x64-windows\include -ID:\vcpkg\installed\x64-windows\include\eigen3 -ID:\vcpkg\installed\x64-windows\include\qt5 -ID:\vcpkg\installed\x64-windows\include\qt5\QtCore -ID:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -ID:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -ID:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -ID:\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W0 /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /Folib\PoissonRecon\CMakeFiles\poisson_recon.dir\Factor.cpp.obj /Fdlib\PoissonRecon\CMakeFiles\poisson_recon.dir\poisson_recon.pdb /FS -c D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\PoissonRecon\Factor.cpp
[3/190] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   -DCGAL_ENABLED -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DOPENGL_ENABLED -DOPENMP_ENABLED -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -ID:\vcpkg\installed\x64-windows\include -ID:\vcpkg\installed\x64-windows\include\eigen3 -ID:\vcpkg\installed\x64-windows\include\qt5 -ID:\vcpkg\installed\x64-windows\include\qt5\QtCore -ID:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -ID:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -ID:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -ID:\vcpkg\installed\x64-windows\include\qt5\QtGui /nologo /DWIN32 /D_WINDOWS  /utf-8 /MP  /MP -openmp /W0 /MD /O2 /Oi /Gy /DNDEBUG /Z7 /showIncludes /Folib\LSD\CMakeFiles\lsd.dir\lsd.c.obj /Fdlib\LSD\CMakeFiles\lsd.dir\lsd.pdb /FS -c D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib\LSD\lsd.c
...
Skipped 1598 lines
...

C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\xmemory(680): warning C4267: 'initializing': conversion from 'size_t' to '_Objty', possible loss of data
        with
        [
            _Objty=int
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\xmemory(1663): note: see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,const unsigned __int64&>(_Alloc &,_Objty *const ,const unsigned __int64 &)' being compiled
        with
        [
            _Alloc=std::allocator<int32_t>,
            _Ty=int,
            _Objty=int
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\xmemory(1663): note: see reference to function template instantiation 'void std::_Default_allocator_traits<_Alloc>::construct<_Ty,const unsigned __int64&>(_Alloc &,_Objty *const ,const unsigned __int64 &)' being compiled
        with
        [
            _Alloc=std::allocator<int32_t>,
            _Ty=int,
            _Objty=int
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\xmemory(1749): note: see reference to function template instantiation 'void std::_Uninitialized_backout_al<_Alloc>::_Emplace_back<const unsigned __int64&>(const unsigned __int64 &)' being compiled
        with
        [
            _Alloc=std::allocator<int32_t>
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\xmemory(1749): note: see reference to function template instantiation 'void std::_Uninitialized_backout_al<_Alloc>::_Emplace_back<const unsigned __int64&>(const unsigned __int64 &)' being compiled
        with
        [
            _Alloc=std::allocator<int32_t>
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(1203): note: see reference to function template instantiation 'int *std::_Uninitialized_copy_n<const unsigned __int64*,std::allocator<int32_t>>(_InIt,size_t,int *,_Alloc &)' being compiled
        with
        [
            _InIt=const unsigned __int64 *,
            _Alloc=std::allocator<int32_t>
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(1306): note: see reference to function template instantiation 'void std::vector<int32_t,std::allocator<int32_t>>::_Insert_counted_range<const unsigned __int64*>(std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,_Iter,const unsigned __int64)' being compiled
        with
        [
            _Ty=int32_t,
            _Iter=const unsigned __int64 *
        ]
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.34.31933\include\vector(1306): note: see reference to function template instantiation 'void std::vector<int32_t,std::allocator<int32_t>>::_Insert_counted_range<const unsigned __int64*>(std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,_Iter,const unsigned __int64)' being compiled
        with
        [
            _Ty=int32_t,
            _Iter=const unsigned __int64 *
        ]
D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\pose.cc(261): note: see reference to function template instantiation 'std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>> std::vector<_Ty,std::allocator<_Ty>>::insert<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>,0>(std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,_Iter,_Iter)' being compiled
        with
        [
            _Ty=int32_t,
            _Iter=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<size_t>>>
        ]
D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\pose.cc(259): note: see reference to function template instantiation 'std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>> std::vector<_Ty,std::allocator<_Ty>>::insert<std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<unsigned __int64>>>,0>(std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,_Iter,_Iter)' being compiled
        with
        [
            _Ty=int32_t,
            _Iter=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<size_t>>>
        ]
[117/190] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DBOOST_ALL_DYN_LINK=1 -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DIMATH_DLL -DOPENEXR_DLL -DOPENGL_ENABLED -DOPENMP_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -external:ID:\vcpkg\installed\x64-windows\include -external:ID:\vcpkg\installed\x64-windows\include\eigen3 -external:ID:\vcpkg\installed\x64-windows\include\qt5 -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtCore -external:ID:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtGui -external:ID:\vcpkg\installed\x64-windows\include\OpenEXR -external:ID:\vcpkg\installed\x64-windows\include\Imath -external:ID:\vcpkg\installed\x64-windows\include\GKlib -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W3 /MD /O2 /Oi /Gy /DNDEBUG /Z7  /EHsc /Zc:__cplusplus -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /bigobj /showIncludes /Fosrc\CMakeFiles\colmap.dir\estimators\fundamental_matrix.cc.obj /Fdsrc\CMakeFiles\colmap.dir\colmap.pdb /FS -c D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\fundamental_matrix.cc
[118/190] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DBOOST_ALL_DYN_LINK=1 -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DIMATH_DLL -DOPENEXR_DLL -DOPENGL_ENABLED -DOPENMP_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -external:ID:\vcpkg\installed\x64-windows\include -external:ID:\vcpkg\installed\x64-windows\include\eigen3 -external:ID:\vcpkg\installed\x64-windows\include\qt5 -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtCore -external:ID:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtGui -external:ID:\vcpkg\installed\x64-windows\include\OpenEXR -external:ID:\vcpkg\installed\x64-windows\include\Imath -external:ID:\vcpkg\installed\x64-windows\include\GKlib -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W3 /MD /O2 /Oi /Gy /DNDEBUG /Z7  /EHsc /Zc:__cplusplus -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /bigobj /showIncludes /Fosrc\CMakeFiles\colmap.dir\estimators\essential_matrix.cc.obj /Fdsrc\CMakeFiles\colmap.dir\colmap.pdb /FS -c D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\essential_matrix.cc
[119/190] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DBOOST_ALL_DYN_LINK=1 -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DIMATH_DLL -DOPENEXR_DLL -DOPENGL_ENABLED -DOPENMP_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -external:ID:\vcpkg\installed\x64-windows\include -external:ID:\vcpkg\installed\x64-windows\include\eigen3 -external:ID:\vcpkg\installed\x64-windows\include\qt5 -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtCore -external:ID:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtGui -external:ID:\vcpkg\installed\x64-windows\include\OpenEXR -external:ID:\vcpkg\installed\x64-windows\include\Imath -external:ID:\vcpkg\installed\x64-windows\include\GKlib -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W3 /MD /O2 /Oi /Gy /DNDEBUG /Z7  /EHsc /Zc:__cplusplus -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /bigobj /showIncludes /Fosrc\CMakeFiles\colmap.dir\estimators\absolute_pose.cc.obj /Fdsrc\CMakeFiles\colmap.dir\colmap.pdb /FS -c D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\absolute_pose.cc
D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\absolute_pose.cc(263): warning C4244: 'argument': conversion from 'unsigned __int64' to 'const double', possible loss of data
D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\absolute_pose.cc(557): warning C4244: 'argument': conversion from 'unsigned __int64' to 'const double', possible loss of data
D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\absolute_pose.cc(558): warning C4244: 'argument': conversion from 'unsigned __int64' to 'const double', possible loss of data
[120/190] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DBOOST_ALL_DYN_LINK=1 -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DIMATH_DLL -DOPENEXR_DLL -DOPENGL_ENABLED -DOPENMP_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -external:ID:\vcpkg\installed\x64-windows\include -external:ID:\vcpkg\installed\x64-windows\include\eigen3 -external:ID:\vcpkg\installed\x64-windows\include\qt5 -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtCore -external:ID:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtGui -external:ID:\vcpkg\installed\x64-windows\include\OpenEXR -external:ID:\vcpkg\installed\x64-windows\include\Imath -external:ID:\vcpkg\installed\x64-windows\include\GKlib -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W3 /MD /O2 /Oi /Gy /DNDEBUG /Z7  /EHsc /Zc:__cplusplus -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /bigobj /showIncludes /Fosrc\CMakeFiles\colmap.dir\estimators\generalized_relative_pose.cc.obj /Fdsrc\CMakeFiles\colmap.dir\colmap.pdb /FS -c D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\generalized_relative_pose.cc
[121/190] C:\PROGRA~1\MICROS~3\2022\COMMUN~1\VC\Tools\MSVC\1434~1.319\bin\Hostx64\x64\cl.exe   /TP -DBOOST_ALL_DYN_LINK=1 -DCGAL_ENABLED -DCGAL_USE_GMPXX=1 -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGL_GLEXT_PROTOTYPES -DGUI_ENABLED -DIMATH_DLL -DOPENEXR_DLL -DOPENGL_ENABLED -DOPENMP_ENABLED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\lib -ID:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src -external:ID:\vcpkg\installed\x64-windows\include -external:ID:\vcpkg\installed\x64-windows\include\eigen3 -external:ID:\vcpkg\installed\x64-windows\include\qt5 -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtCore -external:ID:\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtWidgets -external:ID:\vcpkg\installed\x64-windows\include\qt5\QtGui -external:ID:\vcpkg\installed\x64-windows\include\OpenEXR -external:ID:\vcpkg\installed\x64-windows\include\Imath -external:ID:\vcpkg\installed\x64-windows\include\GKlib -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP -openmp /W3 /MD /O2 /Oi /Gy /DNDEBUG /Z7  /EHsc /Zc:__cplusplus -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS /fp:strict /fp:except- /bigobj /showIncludes /Fosrc\CMakeFiles\colmap.dir\estimators\generalized_absolute_pose_coeffs.cc.obj /Fdsrc\CMakeFiles\colmap.dir\colmap.pdb /FS -c D:\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\estimators\generalized_absolute_pose_coeffs.cc
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

I had no problems building it 2 weeks ago on a Win10/VS2019 machine. 
This bug occurs with Win11/VS2022.

Bug also happens with `vcpkg install colmap[core, cuda, test]:x64-windows`

**Comment by MonicaLiu0311** [comment] 2022-11-25 05:55
I can't get error message from your log, but colmap has a [Visual Studio bug](https://developercommunity.visualstudio.com/t/fatal-error-C1001:-Internal-compiler-err/10076899) now. Could you check your local log is same with issue https://github.com/microsoft/vcpkg/issues/25303?

**Comment by EvanZarrella** [comment] 2022-11-25 19:03
I don't exactly have the same messages but it's similar enough that I believe it to be the same. I attached the log file for you to have a look.
[install-x64-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/10094723/install-x64-windows-rel-out.log)

**Comment by MonicaLiu0311** [comment] 2023-01-09 08:54
Found the following error in your `install-x64-windows-rel-out.log` file:
```
C:\Users\evanz\vcpkg\buildtrees\colmap\src\d576485fe6-7dd36362d1.clean\src\feature\utils.cc(81) : fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\Utc\src\p2\main.c', line 224)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
  cl!RaiseException()+0x6c
  cl!RaiseException()+0x6c
  cl!InvokeCompilerPassW()+0x889db
  cl!InvokeCompilerPassW()+0xa7843

```

Closing this issue as duplicate of https://github.com/microsoft/vcpkg/issues/25303.

**Closed by MonicaLiu0311** 2023-01-09 08:54 UTC
Labels: requires:repro
