### ISSUE TITLE
[proj] build failure

### ISSUE THREAD

**Issue by ChrisSchulte** [microsoft/vcpkg#25497] opened 2022-06-30 07:26 UTC
**Host Environment**
- OS: Windows 10 20H2 19042.1706
- Compiler: Visual Studio 2019 (Build engine 16.11.2.50704)

**To Reproduce**
`./vcpkg install proj:x64-windows`

**Failure logs**
```
Computing installation plan...
The following packages will be built and installed:
    proj[core,net,tiff]:x64-windows -> 9.0.1
Detecting compiler hash for triplet "x64-windows"...
-- Using HTTP(S)_PROXY in environment variables.
Restored 0 packages from D:\cschulte\AppData\Local\vcpkg\archives in 241 us. Use --debug to see more details.
Installing 1/1 proj:x64-windows...
Building proj[core,net,tiff]:x64-windows...
-- Using cached OSGeo-PROJ-9.0.1.tar.gz.
-- Cleaning sources at D:/cschulte/DevEnv64/vcpkg/buildtrees/proj/src/9.0.1-b314c5518d.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/cschulte/DevEnv64/vcpkg/downloads/OSGeo-PROJ-9.0.1.tar.gz
-- Applying patch fix-win-output-name.patch
-- Applying patch fix-proj4-targets-cmake.patch
-- Applying patch tools-cmake.patch
-- Using source at D:/cschulte/DevEnv64/vcpkg/buildtrees/proj/src/9.0.1-b314c5518d.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: D:/cschulte/DevEnv64/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: D:/cschulte/DevEnv64/vcpkg/buildtrees/proj/x64-windows-dbg
    See logs for more information:
      D:\cschulte\DevEnv64\vcpkg\buildtrees\proj\install-x64-windows-dbg-out.log
      D:\cschulte\DevEnv64\vcpkg\buildtrees\proj\install-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/proj/portfile.cmake:41 (vcpkg_cmake_install)
  scripts/ports.cmake:146 (include)


error: building proj:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+proj
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[proj]+Build+error
Include '[proj] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: 019027ada 2022-06-21 (8 days ago)

You can also use the prefilled template from D:\cschulte\DevEnv64\vcpkg\installed\vcpkg\issue_body.md.
```
**Additional context**
This issue does not appear with the previous version of proj. Indeed from version 9.0.0 to 9.0.1 man install path has been modified from share/man/man1 to $CMAKE_INSTALL_MANDIR/man1 (https://github.com/OSGeo/PROJ/commit/1461c9b30d93941e858cf68c01117b83f095c3d6). I clearly have the needed privileges on the vcpkg folder as every other install works correctly. As he tries to create path /man1 I don't know where he is trying to create this folder.
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/9017349/install-x64-windows-dbg-out.log)
[install-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/9017350/install-x64-windows-dbg-err.log)

**Comment by Adela0814** [comment] 2022-06-30 10:28
I'm not able to repro this issue, could you please check your permission(are you an admin user). `/man1` will be installed in the same directory as your `vcpkg`.

**Comment by ChrisSchulte** [comment] 2022-06-30 11:35
Hi @Adela0814 , I am not administrator of this PC but I can confirm you that the man files will not be installed in the vcpkg directory as I have complete rights on this folder. I join the original CmakeLists.txt files for version 9.0.0 and 9.0.1 and also the generated cmake_install.cmake files.
As you can see in the generated files for version 9.0.0 the install directory is "${CMAKE_INSTALL_PREFIX}/share/man/man1" but for 9.0.1 it is only "/man1" which points nowhere...
[CMakeLists-proj-9.0.1-src-man-dir.txt](https://github.com/microsoft/vcpkg/files/9019351/CMakeLists-proj-9.0.1-src-man-dir.txt)
[cmake_install-proj-9.0.0-x64-windows-dbg-man-dir.cmake.txt](https://github.com/microsoft/vcpkg/files/9019353/cmake_install-proj-9.0.0-x64-windows-dbg-man-dir.cmake.txt)
[cmake_install-proj-9.0.1-x64-windows-dbg-man-dir.cmake.txt](https://github.com/microsoft/vcpkg/files/9019355/cmake_install-proj-9.0.1-x64-windows-dbg-man-dir.cmake.txt)
[CMakeLists-proj-9.0.0-src-man-dir.txt](https://github.com/microsoft/vcpkg/files/9019356/CMakeLists-proj-9.0.0-src-man-dir.txt)

**Comment by dg0yt** [comment] 2022-06-30 11:37
> I'm not able to repro this issue, could you please check your permission(are you an admin user). 

You shouldn't be an administrator. It just hides problems, doesn't solve them.

> `/man1` will be installed in the same directory as your `vcpkg`.

No, it is an absolute path. It seems to lack a proper prefix. Upstream uses `${CMAKE_INSTALL_MANDIR}` which should come from package `GNUInstallDirs`. 

The CI build doesn't have any man files for proj:x64-windows, but I don't see how they could be skipped. proj:x64-linux has them. Maybe there is really an issue with `GNUInstallDirs` on Windows?

**Comment by dg0yt** [comment] 2022-06-30 11:58
Hm, it looks like `GNUInstallDirs` is used correctly in `master` but inconsistently in `9.0.1`. And vcpkg CI runs with administrator privilege and hides problems which don't exist on x64-linux.

**Comment by ChrisSchulte** [comment] 2022-06-30 12:48
I can confirm @dg0yt, I've just cloned and compiled with the same options as the port file master and tag 9.0.1 of proj. Tag 9.0.1 doesn't install (error on administrative privileges for /man), master compiles and install flawlessly, with man files in folder CMAKE_INSTALL_PREFIX/share/man/man1.

**Comment by Thomas1664** [comment] 2022-06-30 16:03
I will remove the man files

**Comment by Thomas1664** [comment] 2022-06-30 17:53
@ChrisSchulte Does proj try to install any other files outside of your vcpkg directory?

**Comment by JackBoosY** [comment] 2022-07-01 02:27
According to the [cmake doc](https://cmake.org/cmake/help/latest/command/install.html?highlight=cmake_install_mandir) and the [cmake code](https://github.com/Kitware/CMake/blob/7fc013a9229087cbafeb9ff4c96d1d1acb71c5d6/Source/cmInstallCommand.cxx#L2315-L2319), `CMAKE_INSTALL_MANDIR` should be `${CMAKE_INSTALL_PREFIX}/man`.
No idea why this happened.
Can you please add debug option `--debug` to the install command, try again then provide the output?

Thanks.

**Comment by dg0yt** [comment] 2022-07-01 03:51
> According to the [cmake doc](https://cmake.org/cmake/help/latest/command/install.html?highlight=cmake_install_mandir) and the [cmake code](https://github.com/Kitware/CMake/blob/7fc013a9229087cbafeb9ff4c96d1d1acb71c5d6/Source/cmInstallCommand.cxx#L2315-L2319), `CMAKE_INSTALL_MANDIR` should be `${CMAKE_INSTALL_PREFIX}/man`. 
> No idea why this happened.

It was already answered above: In PROJ 9.0.1, the man page installation uses  `CMAKE_INSTALL_MANDIR` on all platforms, but doesn't include `GNUInstallDirs` for Windows. The variable is unset.

**Comment by dg0yt** [comment] 2022-07-01 03:59
https://github.com/OSGeo/PROJ/blob/9.0.1/cmake/ProjInstallPath.cmake#L26-L45

**Comment by JackBoosY** [comment] 2022-07-01 06:07
> > According to the [cmake doc](https://cmake.org/cmake/help/latest/command/install.html?highlight=cmake_install_mandir) and the [cmake code](https://github.com/Kitware/CMake/blob/7fc013a9229087cbafeb9ff4c96d1d1acb71c5d6/Source/cmInstallCommand.cxx#L2315-L2319), `CMAKE_INSTALL_MANDIR` should be `${CMAKE_INSTALL_PREFIX}/man`.
> > No idea why this happened.
> 
> It was already answered above: In PROJ 9.0.1, the man page installation uses `CMAKE_INSTALL_MANDIR` on all platforms, but doesn't include `GNUInstallDirs` for Windows. The variable is unset.

The diffenence between [9.0.1](https://github.com/OSGeo/PROJ/blob/9.0.1/cmake/ProjInstallPath.cmake#L26-L45) and [9.0.0](https://github.com/OSGeo/PROJ/blob/9.0.0/cmake/ProjInstallPath.cmake#L26-L45) is added condition `OR MINGW`, which will never be true on x64-windows.

**Comment by dg0yt** [comment] 2022-07-01 07:09
> The diffenence between [9.0.1](https://github.com/OSGeo/PROJ/blob/9.0.1/cmake/ProjInstallPath.cmake#L26-L45) and [9.0.0](https://github.com/OSGeo/PROJ/blob/9.0.0/cmake/ProjInstallPath.cmake#L26-L45) is added condition `OR MINGW`, which will never be true on x64-windows.

This indicates that it might have already been broken in 9.0.0 - subject to changes in `doc/CMakeLists.txt`.

**Comment by JackBoosY** [comment] 2022-07-01 07:26
> This indicates that it might have already been broken in 9.0.0 - subject to changes in `doc/CMakeLists.txt`.

The point is `x64-windows` will not enable condition `UNIX OR MINGW`, so cmake should use `CMAKE_INSTALL_PREFIX`.

**Comment by dg0yt** [comment] 2022-07-01 07:32
> The point is `x64-windows` will not enable condition `UNIX OR MINGW`.

That's obvious but this point is pointless.

> So cmake should use `CMAKE_INSTALL_PREFIX`. 

It does, with `GNUInstallDirs`...

The point is that we don't have to patch upstream's temporary bug if vcpkg prefers to not install documentation at all.

**Comment by JackBoosY** [comment] 2022-07-01 07:34
> The point is that we don't have to patch upstream's temporary bug if vcpkg prefers to not install documentation at all.

We really should first find out what the root cause is: is it upstream, or the cmake configuration in the local machine.

**Comment by dg0yt** [comment] 2022-07-01 07:37
> > The point is that we don't have to patch upstream's temporary bug if vcpkg prefers to not install documentation at all.
> 
> We really should first find out what the root cause is: is it upstream, or the cmake configuration in the local machine.

We know that already. It is upstream. `GNUInstallDirs` isn't used for Windows, but `CMAKE_INSTALL_MANDIR` is used for all platforms.

**Comment by JackBoosY** [comment] 2022-07-01 09:48
> We know that already. It is upstream. `GNUInstallDirs` isn't used for Windows, but `CMAKE_INSTALL_MANDIR` is used for all platforms.

The question is we can't reproduce this locally. That proves this issue must be related to some unknown items.
If `CMAKE_INSTALL_MANDIR is used for all platforms`, this must can be reproduced in our local machine.

**Comment by dg0yt** [comment] 2022-07-01 10:25
> > We know that already. It is upstream. `GNUInstallDirs` isn't used for Windows, but `CMAKE_INSTALL_MANDIR` is used for all platforms.
> 
> The question is we can't reproduce this locally. That proves this issue must be related to some unknown items. If `CMAKE_INSTALL_MANDIR is used for all platforms`, this must can be reproduced in our local machine.

There are two possible local behaviours, both invalid:
- Build failure due to lack or write privilege. More likely to happen with vcpg build on C: (system drive). **[Original post in this issue](https://github.com/microsoft/vcpkg/issues/25497#issue-1289714164).**
- Build success, but `man1` directory created in the root of the vcpkg drive. **[Suspected for CI/windows](https://github.com/microsoft/vcpkg/issues/25497#issuecomment-1171110681), [observed by @Osyotr](https://github.com/microsoft/vcpkg/issues/25497#issuecomment-1171295957).**

Please check that you don't see the second case.
The valid behaviour would be:
- Build success, with `man1` directory created in the proper `share` location. **[Observed for CI/linux](https://github.com/microsoft/vcpkg/issues/25497#issuecomment-1171110681).**

**Comment by dg0yt** [comment] 2022-07-02 17:18
FTR upstream confirmed the regression in 9.0.1. and reverted the offending commit: https://github.com/OSGeo/PROJ/pull/3245 
For vcpkg, it is still okay to just patch out the docs.

**Comment by ChrisSchulte** [comment] 2022-07-04 06:42
> @ChrisSchulte Does proj try to install any other files outside of your vcpkg directory?

No other file installed outside of the vcpkg directory, sorry I was not available this weekend.

**Closed** 2022-07-05 22:00 UTC
Labels: category:port-bug
