### ISSUE TITLE
vcpkg upgrade fails with an error

### ISSUE THREAD

**Issue by GeorgePimpleton** [microsoft/vcpkg#32000] opened 2023-06-14 18:29 UTC
The last two times I have done a vcpkg upgrade to installed packages that have updates the upgrade has failed.  I receive an error:

internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(889): Value was null

My update/upgrade command is:  vcpkg upgrade --no-dry-run >>install.txt

I ensure vcpkg is up to date by issuing a bootstrap-vcpkg command before doing the update/upgrade.  My vcpkg is 8 June.

When the upgrade command fails I have to issue an install command for the packages/libraries as the upgrade command removed them earlier before the upgrade errors out.

The following packages will be rebuilt:
  * boost:x64-windows -> 1.82.0#2
  * boost:x64-windows-static -> 1.82.0#2
  * boost:x86-windows -> 1.82.0#2
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows -> 1.82.0#2
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x64-windows-static -> 1.82.0#2
  * boost-iostreams[bzip2,core,lzma,zlib,zstd]:x86-windows -> 1.82.0#2
  * boost-parameter-python:x64-windows -> 1.82.0#2
  * boost-parameter-python:x64-windows-static -> 1.82.0#2
  * boost-parameter-python:x86-windows -> 1.82.0#2
  * boost-python[core,python3]:x64-windows -> 1.82.0#2
  * boost-python[core,python3]:x64-windows-static -> 1.82.0#2
  * boost-python[core,python3]:x86-windows -> 1.82.0#2
  * liblzma:x64-windows -> 5.4.3
  * liblzma:x64-windows-static -> 5.4.3
  * liblzma:x86-windows -> 5.4.3
  * python3:x64-windows -> 3.10.7#6
  * python3:x64-windows-static -> 3.10.7#6
  * python3:x86-windows -> 3.10.7#6
  * sqlite3[core,json1]:x64-windows -> 3.42.0
  * sqlite3[core,json1]:x86-windows -> 3.42.0
  * sqlite3[core,json1]:x64-windows-static -> 3.42.0
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.5.0#3
  * tiff[core,jpeg,lzma,zip]:x64-windows-static -> 4.5.0#3
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.5.0#3
  * wxwidgets[core,debug-support,sound]:x64-windows -> 3.2.2.1#2
  * wxwidgets[core,debug-support,sound]:x64-windows-static -> 3.2.2.1#2
  * wxwidgets[core,debug-support,sound]:x86-windows -> 3.2.2.1#2
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x64-windows-static...
Detecting compiler hash for triplet x86-windows...
Removing 1/54 boost:x64-windows
Elapsed time to handle boost:x64-windows: 96.1 ms
Removing 2/54 boost:x64-windows-static
Elapsed time to handle boost:x64-windows-static: 61.8 ms
Removing 3/54 boost:x86-windows
Elapsed time to handle boost:x86-windows: 100 ms
Removing 4/54 boost-iostreams:x64-windows
Elapsed time to handle boost-iostreams:x64-windows: 553 ms
Removing 5/54 boost-iostreams:x64-windows-static
Elapsed time to handle boost-iostreams:x64-windows-static: 400 ms
Removing 6/54 boost-iostreams:x86-windows
Elapsed time to handle boost-iostreams:x86-windows: 493 ms
Removing 7/54 boost-parameter-python:x64-windows
Elapsed time to handle boost-parameter-python:x64-windows: 185 ms
Removing 8/54 boost-parameter-python:x64-windows-static
Elapsed time to handle boost-parameter-python:x64-windows-static: 120 ms
Removing 9/54 boost-parameter-python:x86-windows
Elapsed time to handle boost-parameter-python:x86-windows: 104 ms
Removing 10/54 boost-python:x64-windows
Elapsed time to handle boost-python:x64-windows: 394 ms
Removing 11/54 boost-python:x64-windows-static
Elapsed time to handle boost-python:x64-windows-static: 1.9 s
Removing 12/54 boost-python:x86-windows
Elapsed time to handle boost-python:x86-windows: 303 ms
Removing 13/54 python3:x64-windows-static
Elapsed time to handle python3:x64-windows-static: 3.1 s
Removing 14/54 python3:x86-windows
Elapsed time to handle python3:x86-windows: 5.3 s
Removing 15/54 python3:x64-windows
Elapsed time to handle python3:x64-windows: 3.8 s
Removing 16/54 wxwidgets:x64-windows
Elapsed time to handle wxwidgets:x64-windows: 3.7 s
Removing 17/54 tiff:x64-windows
Elapsed time to handle tiff:x64-windows: 93.8 ms
Removing 18/54 liblzma:x64-windows
Elapsed time to handle liblzma:x64-windows: 114 ms
Removing 19/54 wxwidgets:x64-windows-static
Elapsed time to handle wxwidgets:x64-windows-static: 2.5 s
Removing 20/54 tiff:x64-windows-static
Elapsed time to handle tiff:x64-windows-static: 185 ms
Removing 21/54 liblzma:x64-windows-static
Elapsed time to handle liblzma:x64-windows-static: 133 ms
Removing 22/54 wxwidgets:x86-windows
Elapsed time to handle wxwidgets:x86-windows: 3.9 s
Removing 23/54 tiff:x86-windows
Elapsed time to handle tiff:x86-windows: 272 ms
Removing 24/54 liblzma:x86-windows
Elapsed time to handle liblzma:x86-windows: 112 ms
Removing 25/54 sqlite3:x64-windows
Elapsed time to handle sqlite3:x64-windows: 297 ms
Removing 26/54 sqlite3:x64-windows-static
Elapsed time to handle sqlite3:x64-windows-static: 104 ms
Removing 27/54 sqlite3:x86-windows
Elapsed time to handle sqlite3:x86-windows: 64.7 ms
Installing 28/54 liblzma:x64-windows...
Building liblzma:x64-windows...
-- Downloading https://github.com/tukaani-project/xz/archive/v5.4.3.tar.gz -> tukaani-project-xz-v5.4.3.tar.gz...
-- Extracting source D:/Programming/vcpkg/downloads/tukaani-project-xz-v5.4.3.tar.gz
-- Applying patch fix_config_include.patch
-- Applying patch win_output_name.patch
-- Applying patch add_support_ios.patch
-- Applying patch build-tools.patch
-- Using source at D:/Programming/vcpkg/buildtrees/liblzma/src/v5.4.3-3da4e465c1.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Fixing pkgconfig file: D:/Programming/vcpkg/packages/liblzma_x64-windows/lib/pkgconfig/liblzma.pc
-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at D:/Programming/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Fixing pkgconfig file: D:/Programming/vcpkg/packages/liblzma_x64-windows/debug/lib/pkgconfig/liblzma.pc
-- Installing: D:/Programming/vcpkg/packages/liblzma_x64-windows/share/liblzma/copyright
-- Performing post-build validation
internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(889): Value was null
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.

**Comment by autoantwort** [comment] 2023-06-14 23:16
Duplicate of #31908

**Comment by LilyWangLL** [comment] 2023-06-15 01:57
Closed as duplicate of #31908.

**Closed by LilyWangLL** 2023-06-15 01:57 UTC
