### ISSUE TITLE
[pdal] update to 2.3.0

### ISSUE THREAD

**Issue by xavier2k6** [microsoft/vcpkg#19862] opened 2021-09-01 16:28 UTC
Library name: pdal

New version number: 2.3.0

Other information that may be useful (release notes, etc...)
https://github.com/PDAL/PDAL/releases/latest

**Comment by JonLiu1993** [comment] 2021-09-02 02:30
Duplicate of #13946 ,pdal will update to 2.3.0 in #13946

**Closed by JonLiu1993** 2021-09-02 02:30 UTC
Labels: category:port-update
