### ISSUE TITLE
[pcl] Build error

### ISSUE THREAD

**Issue by SC-94** [microsoft/vcpkg#22472] opened 2022-01-11 09:38 UTC
**Host Environment**
- OS: Windows 11
- Compiler: Standard windows Visual C++  compiler
[install-x86-windows-rel-out.log](https://github.com/microsoft/vcpkg/files/7845287/install-x86-windows-rel-out.log)

**To Reproduce**
`./vcpkg install pcl`

**Failure logs** 
-- Building x86-windows-dbg
-- Building x86-windows-rel
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:155 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.21.1-windows/cmake-3.21.1-windows-i386/bin/cmake.exe --build . --config Release --target install -- -v -j9
    Working Directory: D:/vcpkg/buildtrees/pcl/x86-windows-rel
    See logs for more information:
      D:\vcpkg\buildtrees\pcl\install-x86-windows-rel-out.log

**Additional context**
Tried re-installing Cmake, Visual Studio, Vcpkg

**Comment by dg0yt** [comment] 2022-01-11 11:42
"Internal compiler error"

**Comment by dg0yt** [comment] 2022-01-11 11:44
Maybe duplicate of: #19561

**Comment by LilyWangLL** [comment] 2022-01-11 12:18
Yes, this issue is duplicate with #19561, I am closing this issue for now. Please pay attention of issue #19561.

**Closed by LilyWangLL** 2022-01-11 12:18 UTC
Labels: category:port-bug, depends:upstream-changes
