### ISSUE TITLE
[libuuid] Build error

### ISSUE THREAD

**Issue by Arlen-LT** [microsoft/vcpkg#33633] opened 2023-09-07 08:24 UTC
~~I found that the url is wrong like `libuuid//files`, but it should be `libuuid/files`~~ **The url is right**

```
Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_sourceforge.cmake:83 (vcpkg_download_distfile)
  ports/libuuid/portfile.cmake:3 (vcpkg_from_sourceforge)
  scripts/ports.cmake:147 (include)


error: building libuuid:x64-linux failed with: BUILD_FAILED
Elapsed time to handle libuuid:x64-linux: 20 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+libuuid
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?title=[libuuid]+Build+error&body=Copy+issue+body+from+%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
```
```
Building libuuid:x64-linux...
-- Downloading https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=cfhcable;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=pilotfiber;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=gigenet;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=versaweb;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=ayera;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=netactuate;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=phoenixnap;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=astuteinternet;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=freefr;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=netcologne;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=deac-riga;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=excellmedia;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=iweb;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=jaist;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=jztkft;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=managedway;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=nchc;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=netix;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=ufpr;https://sourceforge.net/projects/libuuid//files/libuuid-1.0.3.tar.gz/download?use_mirror=tenet -> libuuid-1.0.3.tar.gz...
```

**Comment by derrohrbach** [comment] 2023-09-07 08:36
Seems related to #33631

**Comment by derrohrbach** [comment] 2023-09-07 08:43
You are right @Arlen-LT. Even though the page seems to work with one slash, the download is still broken. I guess we'll have to wait.

**Comment by MonicaLiu0311** [comment] 2023-09-07 10:38
Duplicate of #33631.

**Closed by MonicaLiu0311** 2023-09-07 10:38 UTC
Labels: category:question
