### ISSUE TITLE
[vcpkg upgrade] Build failures when remove ports or features

### ISSUE THREAD

**Issue by diablodale** [microsoft/vcpkg#11482] opened 2020-05-21 02:12 UTC
`vcpkg upgrade` to move boost from 1.72.0 to 1.73.0 fails. Results in manual removal of all Boost triplets and manual install of all triplets. `upgrade` fails in its reason to exist 😆

### Setup

* Windows 2004 Version 10.0.19041.264
* Visual Studio 2019 Community 16.6.0

### Repro

1. Have previously installed Boost 1.72.0 with all its components/features
2. `git pull`
3. `vcpkg update` and notice there is a new Boost 1.73.0
4. `vcpkg upgrade`

### Result

Failure.

```
Error: while loading boost-disjoint-sets:x64-windows-static-md-v142-sdk10b17134: Port definition not found.
Please run "vcpkg remove boost-disjoint-sets:x64-windows-static-md-v142-sdk10b17134" and re-attempt.
```

### Continued Repro

5. `vcpkg remove boost-disjoint-sets:x64-windows-static-md-v142-sdk10b17134`

### Result 2

Failure. The vcpkg state is such that a manual removal of the entire boost package (see 1st line with *) must occur. I have four triplets. Therefore, I will need to manually remove all four and then manually install all four. Such tedium is the job of `upgrade`, but it fails as seen above.

```
The following packages will be removed:
  * boost:x64-windows-static-md-v142-sdk10b17134
    boost-disjoint-sets:x64-windows-static-md-v142-sdk10b17134
Additional packages (*) need to be removed to complete this operation.
If you are sure you want to remove them, run the command with the --recurse option
```

### Expected

No errors or failures. `vcpkg upgrade` should nicely upgrade all parts of Boost on all installed triplets. If any features no longer exist, then it should warn and/or easily remove them. At no time should a manual remove and manual install of all triplets be needed.

**Comment by timautry** [comment] 2020-05-21 02:17
Yes, boost decided to drop the boost-disjoint-sets library, but it also happened to me on harfbuzz that was just upgraded as the ucdn feature was removed and I have to do a manual `vcpkg remove harfbuzz --recurse` to delete it all all ports depending on it and then had to do a manual vcpkg install harfbuzz and all the other ports previously removed. 
A very tedious time consuming process that should be able to handled automajically in the upgrade process.

**Comment by PhoebeHui** [comment] 2020-05-21 03:02
Confirmed, this issue reproed. It should be a vcpkg bug when use 'vcpkg upgrade'.

This issue reproed with below 2 cases:
1. Removed the port
2. Removed the feature of the port

**Comment by aPSopt** [comment] 2020-05-22 13:21
Confirmed. The bug reproduced very simply. 
I just make vcpkg update and then vcpkg upgrade --no-dry-run - and receive error described in initial post.

**Comment by aPSopt** [comment] 2020-05-25 08:29
This bug exists more than week. Is there are some solution appears?

**Comment by realsarm** [comment] 2021-01-24 16:27
Any solution to this?

**Comment by sfinktah** [comment] 2021-02-08 16:48
Here's a helpful BASH script (it's pure bash, should run in your vsdev/git bash prompt).  Just place it in the same directory as vcpkg, and run.  It will delete all installed boost packages from all triplets.   It doesn't attempt to reinstall them, because that's a pretty simple task and best left to the user's discretion.

    chmod 755 rebash.sh
    ./rebash.sh

(assuming you save it as `rebash.sh`)

```bash
#!/usr/bin/env bash
while read -ra LINE; do
    package=${LINE[0]}
    echo "$package"
    if [[ $package == boost* ]]; then
        echo "./vcpkg remove $package --recurse"
        ./vcpkg remove $package --recurse
    fi
done <<< $( ./vcpkg update )
```

**Comment by BillyONeal** [comment] 2023-09-07 22:21
Fixed by https://github.com/microsoft/vcpkg-tool/pull/873

**Closed by BillyONeal** 2023-09-07 22:21 UTC
Labels: category:vcpkg-bug
