### ISSUE TITLE
[New Port Request] <serial>

### ISSUE THREAD

**Issue by ThinkalVB** [microsoft/vcpkg#19438] opened 2021-08-07 18:30 UTC
Library name: serial

Library description: This is a cross-platform library for interfacing with rs-232 serial like ports written in C++.

Source repository URL: https://github.com/wjwwood/serial

Project homepage (if different from the source repository): http://wjwwood.github.io/serial/

It doesn't have any dependencies. Support C Make and Make build systems. It's pretty popular with 105 watchers , 1.3k stars and 649 forks. I guess it would be easy to integrate and a valid addition to vcpkg.

**Comment by ThinkalVB** [comment] 2021-08-12 10:25
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO wjwwood/serial
    REF 1.2.1
    SHA512 41df7b5cd7237f3990f2debe8d3eb17cbe428666f9b298072abccd2bbaed4a1e82b074a416af132c94c0e2abff881513e7b4ab4feab82a6b7ae01cd01be5fa3e
    HEAD_REF master
)
{
  "name": "serial",
  "version-semver": "1.2.1",
  "description": "A cross-platform library for interfacing with rs-232 serial like ports written in C++",
  "homepage": "https://github.com/wjwwood/serial"
}

**Comment by ThinkalVB** [comment] 2021-08-12 10:27
{
  "name": "serial",
  "version-semver": "1.2.1",
  "description": "A cross-platform library for interfacing with rs-232 serial like ports written in C++",
  "homepage": "https://github.com/wjwwood/serial"
}

$REPO
wjwwood/serial
$REF
1.2.1
$SHA512 41df7b5cd7237f3990f2debe8d3eb17cbe428666f9b298072abccd2bbaed4a1e82b074a416af132c94c0e2abff881513e7b4ab4feab82a6b7ae01cd01be5fa3e
$HEAD_REF
master

**Comment by PhoebeHui** [comment] 2021-09-10 09:06
@ThinkalVB, could you please submit a PR for the library?

**Comment by ThinkalVB** [comment] 2021-09-12 19:07
@PhoebeHui  It's a little complex than that. I have tried to use the above-mentioned script, but unfortunately, it didn't work as expected, or else I would have done a PR already.

**Comment by ericfont** [comment] 2021-11-11 04:34
duplicate of #19293

**Comment by PhoebeHui** [comment] 2021-12-02 08:29
Closing in favor of https://github.com/microsoft/vcpkg/issues/19293.

**Closed by PhoebeHui** 2021-12-02 08:29 UTC
Labels: category:new-port, info:good-first-issue
