### ISSUE TITLE
[gtest] find_package(GTest) locates release version when CMAKE_BUILD_TYPE=Debug

### ISSUE THREAD

**Issue by justusranvier** [microsoft/vcpkg#14355] opened 2020-11-02 15:21 UTC
**Describe the bug**
Attempting to build unit tests that link against gtest will fail when building in debug mode on Windows.

**Environment**
windows-2019 github action

**To Reproduce**
1. ./vcpkg --triplet x64-windows-static gtest
2. build an application with -DCMAKE_BUILD_TYPE=Debug. Use find_package(GTest CONFIG REQUIRED) in CMakeLists.txt
3. compile applicant

Application fails to link

**Expected behavior**
Cmake should find a debug version of gtest.lib linked to the debug version of the standard library (/MTd)

**Failure logs** 
```
  -- Found Threads: TRUE  
  -- Found GTest: D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/lib/gtest.lib  
  -- Found unofficial-sodium: D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/debug/lib/libsodium.lib  
  -- Found Protobuf: optimized;D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/lib/libprotobuf.lib;debug;D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/debug/lib/libprotobufd.lib (found version "3.13.0") 
  -- Found ZLIB: optimized;D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/lib/zlib.lib;debug;D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/debug/lib/zlibd.lib (found version "1.2.11") 
  -- Found Boost: D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/include (found suitable version "1.73.0", minimum required is "1.73.0") found components: system filesystem missing components: stacktrace_basic
  -- Found Boost: D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/include (found version "1.73.0") found components: thread chrono date_time atomic 
  -- Found Boost: D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/include (found version "1.73.0") found components: iostreams regex 
  -- Found lmdb: D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/lib/lmdb.lib  
  -- Found OpenSSL: D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/debug/lib/libcrypto.lib (found suitable version "1.1.1h", minimum required is "1.0.1")  
  -- Found unofficial-secp256k1: D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/debug/lib/secp256k1.lib  
```
...

```
  FAILED: tests/unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.exe 
  cmd.exe /C "cd . && C:\hostedtoolcache\windows\cmake\3.18.4\x64\cmake-3.18.4-win32-x86\bin\cmake.exe -E vs_link_exe --intdir=tests\blockchain\headeroracle\CMakeFiles\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.rsp  /out:tests\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.exe /implib:tests\blockchain\headeroracle\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.lib /pdb:tests\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.pdb /version:0.0 /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:msvcrt.lib /NODEFAULTLIB:msvcrtd.lib /debug /INCREMENTAL /subsystem:console  && cmd.exe /C "cd /D D:\a\opentxs\opentxs\build\tests\blockchain\headeroracle && powershell -noprofile -executionpolicy Bypass -file D:/a/opentxs/opentxs/deps/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/a/opentxs/opentxs/build/tests/unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.exe -installedDir D:/a/opentxs/opentxs/deps/vcpkg/installed/x64-windows-static/debug/bin -OutVariable out""
  LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2019\ENTERP~1\VC\Tools\MSVC\1427~1.291\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.rsp /out:tests\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.exe /implib:tests\blockchain\headeroracle\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.lib /pdb:tests\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.pdb /version:0.0 /NODEFAULTLIB:libcmt.lib /NODEFAULTLIB:msvcrt.lib /NODEFAULTLIB:msvcrtd.lib /debug /INCREMENTAL /subsystem:console /MANIFEST /MANIFESTFILE:tests\blockchain\headeroracle\CMakeFiles\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.dir/intermediate.manifest tests\blockchain\headeroracle\CMakeFiles\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.dir/manifest.res" failed (exit code 1319) with the following output:
  gtest.lib(gtest-all.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.cpp.obj
  gtest.lib(gtest-all.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in main.cpp.obj
  gtest.lib(gtest-all.cc.obj) : error LNK2038: mismatch detected for '_ITERATOR_DEBUG_LEVEL': value '0' doesn't match value '2' in main.cpp.obj
  gtest.lib(gtest-all.cc.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MT_StaticRelease' doesn't match value 'MTd_StaticDebug' in main.cpp.obj
     Creating library tests\blockchain\headeroracle\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.lib and object tests\blockchain\headeroracle\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.exp
  tests\unittests-opentxs-blockchain-headeroracle-add_checkpoint_already_in_best_chain.exe : fatal error LNK1319: 2 mismatches detected
```

**Comment by Neumann-A** [comment] 2020-11-02 16:38
considering that I use gtest myself i don't believe you are using `find_package(GTest CONFIG REQUIRED)` or are wrongly linking against gtests
Please show 
a) the true context of the `find_package` call
b) the true context of the `target_link_libraries` call

**Comment by justusranvier** [comment] 2020-11-02 20:35
Adding CONFIG to find_package fixes the vcpkg case. It breaks a few non-vcpkg build scenarios but those are issues for other bug trackers.

**Comment by JonLiu1993** [comment] 2020-11-03 08:24
Hi @justusranvier,I cannot reproduce this on my machine( Windows10 )，Vcpkg version: 2020.06.15-nohash
Here are the steps I reproduced：
 ./vcpkg install gtest:x64-windows-static
 CMakeLists.txt:
````
cmake_minimum_required(VERSION 3.0)

project(test)

add_executable(test CMakeProject16.cpp)

find_package(GTest CONFIG REQUIRED)
target_link_libraries(test PRIVATE GTest::gmock GTest::gtest GTest::gmock_main GTest::gtest_main)
````
CMakeSettings.json:
````
{
  "configurations": [
    {
      "name": "x64-Debug",
      "generator": "Visual Studio 15 2017 Win64",
      "configurationType": "Debug",
      "inheritEnvironments": [
        "msvc_x64_x64"
      ],
      "buildRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\build\\${name}",
      "installRoot": "${env.USERPROFILE}\\CMakeBuilds\\${workspaceHash}\\install\\${name}",
      "cmakeCommandArgs": "-DCMAKE_TOOLCHAIN_FILE=F:/test3/vcpkg/scripts/buildsystems/vcpkg.cmake",
      "buildCommandArgs": "",
      "ctestCommandArgs": "",
      "variables": [
        {
          "name": "VCPKG_TARGET_TRIPLET",
          "value": "x64-windows-static"
        }
      ]
    }
  ]
}

````

**Comment by JonLiu1993** [comment] 2020-11-03 08:24
````
 FinalizeBuildStatus:
    Deleting file "test.dir\Debug\test.tlog\unsuccessfulbuild".
    Touching "test.dir\Debug\test.tlog\test.lastbuildstate".
  Done Building Project "C:\Users\vzhli17\CMakeBuilds\f07d6b14-67bc-a335-9640-39316e44727b\build\x64-Debug\CMakeProject16\test.vcxproj" (default targets).
  
  Build succeeded.
      0 Warning(s)
      0 Error(s)
  
  Time Elapsed 00:00:04.09

Build succeeded.
````

**Comment by JonLiu1993** [comment] 2020-11-03 08:26
Can you send me the CMakeLists that you use gtest?

**Comment by Neumann-A** [comment] 2020-11-03 08:28
@justusranvier: You can set https://cmake.org/cmake/help/latest/variable/CMAKE_FIND_PACKAGE_PREFER_CONFIG.html if you don't want to manually add CONFIG. 

@JonLiu1993 he only used `find_package(GTest REQUIRED)` not `find_package(GTest CONFIG REQUIRED)` which is why it failed. Maybe a `vcpkg_cmake_wrapper` should be installed to always search for the `-Config.cmake`

**Comment by JonLiu1993** [comment] 2020-11-03 08:48
@Neumann-A ,Okay, I will try to add vcpkg_cmake_wrapper

**Comment by JackBoosY** [comment] 2020-11-06 09:08
@Neumann-A I think we don't needed. `vcpkg_cmake_wrapper` in vcpkg is used to deal with mismatched cmake modules(`Find*.cmake`) and exported configurations(`*-config.cmake`).
In this case, the author just need to add keyword `CONFIG` in his `find_package`.

**Comment by Neumann-A** [comment] 2020-11-06 09:15
>  is used to deal with mismatched cmake modules(Find*.cmake) and exported configurations(*-config.cmake).

That is exactly the case here. The internal cmake FindGTest has other rules than the config.

**Comment by JackBoosY** [comment] 2020-11-06 09:21
@Neumann-A I prefer to use config mode because it's stronger, the module provided by cmake may be out of date, but it will not.

If we need to not use the `CONFIG` keyword and call them (to completely avoid to call the module provided by cmake) in the scene containing the exported configuration file, I think we should not implement it through `vcpkg_cmake_wrapper`.
This should be provided by vcpkg itself.

**Comment by JackBoosY** [comment] 2021-06-10 06:15
Also, `FindGTest.cmake` provides some special functions. If we add a wrapper, the user's right to use these functions is cancelled.

Closed this issue by solved.

**Closed by JackBoosY** 2021-06-10 06:15 UTC
Labels: category:question
