### ISSUE TITLE
CMake not finding vcpkg installed libraries

### ISSUE THREAD

**Issue by MariusKM** [microsoft/vcpkg#10470] opened 2020-03-19 16:27 UTC
**Describe the bug**
While trying to build a PCL .cpp project, CMake does not find any installed libraries, even when using the toolchain file.

**Environment**
- OS: Windows
- Compiler: CMake, VS2019

**To Reproduce**
1. ./vcpkg install install pcl:x64-windows-static
2. ./vcpkg install integrate
3. create .cpp file and CMakeLists.txt in a new Folder
3.  build using cmake ( either normally or with  -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake command)

My CMakeLists.txt:
cmake_minimum_required(VERSION 2.8)
project("D:/Projekte/WattX/Tech in Contruction/PCLViewer VS/PCDWrite")
find_package(PCL REQUIRED)
include_directories(${PCL_INCLUDE_DIRS})
link_directories(${PCL_LIBRARY_DIRS})
add_definitions(${PCL_DEFINITIONS})
add_executable(pcd_write_test pcd_write.cpp)
target_link_libraries(pcd_write_test ${PCL_LIBRARIES})

**Expected behavior**
CMake should finish building successfully

**Failure logs** 
CMake Error at C:/vcpkg/scripts/buildsystems/vcpkg.cmake:288 (_find_package):
  By not providing "FindPCL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "PCL", but
  CMake did not find one.

  Could not find a package configuration file provided by "PCL" with any of
  the following names:

    PCLConfig.cmake
    pcl-config.cmake

  Add the installation prefix of "PCL" to CMAKE_PREFIX_PATH or set "PCL_DIR"
  to a directory containing one of the above files.  If "PCL" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!

**Additional context**
I was following this tutorial from the official PCL documentation
http://pointclouds.org/documentation/tutorials/using_pcl_pcl_config.php

**Comment by LilyWangL** [comment] 2020-03-20 09:23
Closed as duplicate of #6190.

**Closed by LilyWangL** 2020-03-20 09:23 UTC
