### ISSUE TITLE
[qt5-webengine] build failure

### ISSUE THREAD

**Issue by al-sabr** [microsoft/vcpkg#15712] opened 2021-01-17 14:56 UTC
**Host Environment**
- OS: Windows
- Compiler: Vcpkg package management program version 2020.11.12--unknownhash

See LICENSE.txt for license information.

**To Reproduce**
`vcpkg.exe install qt5-webengine:x64-windows`

**Failure logs** 
-- Extracting source G:/vcpkg/downloads/qtwebengine-everywhere-src-5.15.0.tar.xz
-- Applying patch common.pri.patch
-- Applying patch gl.patch
-- Using source at G:/vcpkg/buildtrees/qt5-webengine/src/5.15.0-d5f1643016.clean
-- Using msys root at G:/vcpkg/downloads/tools/msys2/c809757c94447846
-- Configuring x64-windows-rel
-- Configuring x64-windows-rel done
-- Configuring x64-windows-dbg
-- Configuring x64-windows-dbg done
-- Package build-x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:145 (message):
    Command failed: G:/vcpkg/downloads/tools/jom/jom-1.1.3/jom.exe -j 9
    Working Directory: G:/vcpkg/buildtrees/qt5-webengine/x64-windows-dbg
    See logs for more information:
      G:\vcpkg\buildtrees\qt5-webengine\package-build-x64-windows-dbg-out.log
      G:\vcpkg\buildtrees\qt5-webengine\package-build-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_qmake.cmake:43 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_build_qmake.cmake:94 (run_jom)
  installed/x64-windows/share/qt5/qt_build_submodule.cmake:12 (vcpkg_build_qmake)
  installed/x64-windows/share/qt5/qt_submodule_installation.cmake:8 (qt_build_submodule)
  ports/qt5-webengine/portfile.cmake:46 (qt_submodule_installation)
  scripts/ports.cmake:136 (include)

Error: Building package qt5-webengine:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: qt5-webengine:x64-windows
  Vcpkg version: 2020.11.12--unknownhash

Additionally, attach any relevant sections from the log files above.

```
jom 1.1.3 - empower your cores

Project MESSAGE: G:\vcpkg\buildtrees\qt5-webengine\src\5.15.0-d5f1643016.clean\src\3rdparty\gn\build\gen.py --no-last-commit-position --out-path G:/vcpkg/buildtrees/qt5-webengine/x64-windows-dbg/src/3rdparty/gn/out/Release --cc "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe" --cxx "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe" --ld "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\link.exe" --use-lto
Project MESSAGE: Running: G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\3rdparty\gn\out\Release\gn.exe gen G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\debug --script-executable=G:\vcpkg\downloads\tools\python\python-2.7.16-x64\python.exe --args="use_qt=true closure_compile=false is_component_build=false is_shared=true enable_debugallocation=false enable_media_remoting=false enable_message_center=false enable_nacl=false enable_remoting=false enable_reporting=false enable_resource_whitelist_generation=false enable_swiftshader=false angle_enable_swiftshader=false enable_web_auth=false enable_web_speech=false enable_widevine=true has_native_accessibility=false optimize_webui=false safe_browsing_mode=0 strip_absolute_paths_from_debug_symbols=false toolkit_views=false treat_warnings_as_errors=false use_allocator_shim=false use_allocator=\"none\" use_custom_libcxx=false v8_use_external_startup_data=false forbid_non_component_debug_builds=false jumbo_build_excluded=[\"browser\"] enable_basic_printing=true enable_print_preview=true enable_pdf=true enable_plugins=true enable_spellcheck=true enable_webrtc=true proprietary_codecs=false enable_extensions=true enable_precompiled_headers=false is_official_build=false is_unsafe_developer_build=false is_debug=true use_debug_fission=false enable_iterator_debugging=true v8_optimized_debug=false blink_symbol_level=0 remove_v8base_debug_symbols=true use_kerberos=true use_sysroot=false enable_session_service=false ninja_use_custom_environment_files=false is_multi_dll_chrome=false win_linker_timing=true com_init_check_hook_disabled=true heterogeneous_executables=true is_clang=false use_lld=false is_win_fastlink=false use_incremental_linking=false visual_studio_version=2019 visual_studio_path=\"C:/Program Files ^(x86^)/Microsoft Visual Studio/2019/Community\" windows_sdk_path=\"C:/Program Files ^(x86^)/Windows Kits/10\" target_cpu=\"x64\" use_browser_spellchecker=false qtwebengine_target=\"G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\debug:QtWebEngineCore\"" --root=G:\vcpkg\buildtrees\qt5-webengine\src\5.15.0-d5f1643016.clean\src\3rdparty\chromium 
Project MESSAGE: Running: G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\3rdparty\gn\out\Release\gn.exe gen G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\release --script-executable=G:\vcpkg\downloads\tools\python\python-2.7.16-x64\python.exe --args="use_qt=true closure_compile=false is_component_build=false is_shared=true enable_debugallocation=false enable_media_remoting=false enable_message_center=false enable_nacl=false enable_remoting=false enable_reporting=false enable_resource_whitelist_generation=false enable_swiftshader=false angle_enable_swiftshader=false enable_web_auth=false enable_web_speech=false enable_widevine=true has_native_accessibility=false optimize_webui=false safe_browsing_mode=0 strip_absolute_paths_from_debug_symbols=false toolkit_views=false treat_warnings_as_errors=false use_allocator_shim=false use_allocator=\"none\" use_custom_libcxx=false v8_use_external_startup_data=false forbid_non_component_debug_builds=false jumbo_build_excluded=[\"browser\"] enable_basic_printing=true enable_print_preview=true enable_pdf=true enable_plugins=true enable_spellcheck=true enable_webrtc=true proprietary_codecs=false enable_extensions=true enable_precompiled_headers=false is_official_build=true is_debug=false symbol_level=0 blink_symbol_level=0 remove_v8base_debug_symbols=true use_kerberos=true use_sysroot=false enable_session_service=false ninja_use_custom_environment_files=false is_multi_dll_chrome=false win_linker_timing=true com_init_check_hook_disabled=true heterogeneous_executables=true is_clang=false use_lld=false is_win_fastlink=false use_incremental_linking=false visual_studio_version=2019 visual_studio_path=\"C:/Program Files ^(x86^)/Microsoft Visual Studio/2019/Community\" windows_sdk_path=\"C:/Program Files ^(x86^)/Windows Kits/10\" target_cpu=\"x64\" use_browser_spellchecker=false qtwebengine_target=\"G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\release:QtWebEngineCore\"" --root=G:\vcpkg\buildtrees\qt5-webengine\src\5.15.0-d5f1643016.clean\src\3rdparty\chromium 
jom: G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile.gn_run.Debug [run_ninja] Error 1
jom: G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile.gn_run [debug] Error 2
jom: G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\core\Makefile [sub-gn_run-pro-make_first] Error 2
jom: G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\src\Makefile [sub-core-make_first] Error 2
jom: G:\vcpkg\buildtrees\qt5-webengine\x64-windows-dbg\Makefile [sub-src-make_first] Error 2
```

```
/Foobj/third_party/angle/angle_common/matrix_utils.obj /Fd"obj/third_party/angle/angle_common_cc.pdb"
[851/28243] ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64/cl.exe" /nologo /showIncludes -DUSE_AURA=1 -DTOOLKIT_QT -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DANGLE_IS_64_BIT_CPU -DANGLE_ENABLE_DEBUG_ANNOTATIONS -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src/common/third_party/base -Igen/angle -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /wd4117 /D__DATE__= /D__TIME__= /D__TIMESTAMP__= /W4 /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /Od /Ob0 /GF /Zi /MDd /we4244 /we4456 /we4458 /we4715 /we4800 /we4838 /TP /wd4577 /GR- /c ../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src/common/string_utils.cpp /Foobj/third_party/angle/angle_common/string_utils.obj /Fd"obj/third_party/angle/angle_common_cc.pdb"
[852/28243] ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64/cl.exe" /nologo /showIncludes -DUSE_AURA=1 -DTOOLKIT_QT -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DANGLE_IS_64_BIT_CPU -DANGLE_ENABLE_DEBUG_ANNOTATIONS -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src/common/third_party/base -Igen/angle -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /wd4117 /D__DATE__= /D__TIME__= /D__TIMESTAMP__= /W4 /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /Od /Ob0 /GF /Zi /MDd /we4244 /we4456 /we4458 /we4715 /we4800 /we4838 /TP /wd4577 /GR- /c ../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src/common/utilities.cpp /Foobj/third_party/angle/angle_common/utilities.obj /Fd"obj/third_party/angle/angle_common_cc.pdb"
[853/28243] ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64/cl.exe" /nologo /showIncludes -DUSE_AURA=1 -DTOOLKIT_QT -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DANGLE_IS_64_BIT_CPU -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src/common/third_party/base -Igen/angle -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /wd4117 /D__DATE__= /D__TIME__= /D__TIMESTAMP__= /W4 /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /Od /Ob0 /GF /Zi /MDd /we4244 /we4456 /we4458 /we4715 /we4800 /we4838 /TP /wd4577 /GR- /c ../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src/image_util/loadimage.cpp /Foobj/third_party/angle/angle_image_util/loadimage.obj /Fd"obj/third_party/angle/angle_image_util_cc.pdb"
[854/28243] ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64/cl.exe" /nologo /showIncludes -DUSE_AURA=1 -DTOOLKIT_QT -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DANGLE_IS_64_BIT_CPU -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src/common/third_party/base -Igen/angle -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /wd4117 /D__DATE__= /D__TIME__= /D__TIMESTAMP__= /W4 /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /Od /Ob0 /GF /Zi /MDd /we4244 /we4456 /we4458 /we4715 /we4800 /we4838 /TP /wd4577 /GR- /c ../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src/image_util/loadimage_etc.cpp /Foobj/third_party/angle/angle_image_util/loadimage_etc.obj /Fd"obj/third_party/angle/angle_image_util_cc.pdb"
[855/28243] ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64/cl.exe" /nologo /showIncludes -DUSE_AURA=1 -DTOOLKIT_QT -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DANGLE_IS_64_BIT_CPU -DANGLE_ENABLE_D3D9 -DANGLE_ENABLE_D3D11 -DANGLE_ENABLE_OPENGL -DANGLE_ENABLE_OPENGL_NULL -DANGLE_ENABLE_NULL -DANGLE_ENABLE_VULKAN -DANGLE_USE_CUSTOM_VULKAN_CMD_BUFFERS=1 -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src/common/third_party/base -Igen/angle -I../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/include /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /wd4117 /D__DATE__= /D__TIME__= /D__TIMESTAMP__= /W4 /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /Od /Ob0 /GF /Zi /MDd /we4244 /we4456 /we4458 /we4715 /we4800 /we4838 /TP /wd4577 /GR- /c ../../../../src/5.15.0-d5f1643016.clean/src/3rdparty/chromium/third_party/angle/src/gpu_info_util/SystemInfo_win.cpp /Foobj/third_party/angle/angle_gpu_info_util/SystemInfo_win.obj /Fd"obj/third_party/angle/angle_gpu_info_util_cc.pdb"
ninja: build stopped: subcommand failed.

```

[package-build-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/5829095/package-build-x64-windows-dbg-err.log)
[package-build-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/5829096/package-build-x64-windows-dbg-out.log)

**Comment by Neumann-A** [comment] 2021-01-17 21:15
>ninja: build stopped: subcommand failed.

is not the error. Please attach the logs or find the real error.

**Comment by JackBoosY** [comment] 2021-01-18 00:58
Please provide FULL log
_G:\vcpkg\buildtrees\qt5-webengine\package-build-x64-windows-dbg-out.log_
_G:\vcpkg\buildtrees\qt5-webengine\package-build-x64-windows-dbg-err.log_.

Thanks.

**Comment by al-sabr** [comment] 2021-01-18 09:54
Uploaded in first comment.

**Comment by al-sabr** [comment] 2021-01-18 09:54
Uploaded in first comment.

**Comment by JackBoosY** [comment] 2021-01-18 09:58
```
[2970/28337] ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64/cl.exe" /nologo /showIncludes -DUSE_AURA=1 -DTOOLKIT_QT -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DANGLE_IS_64_BIT_CPU -DANGLE_ENABLE_DEBUG_ANNOTATIONS -I../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/include -I../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/src -I../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/src/common/third_party/base -Igen/angle -I../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/include /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /wd4117 /D__DATE__= /D__TIME__= /D__TIMESTAMP__= /W4 /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /Od /Ob0 /GF /Zi /MDd /we4244 /we4456 /we4458 /we4715 /we4800 /we4838 /TP /wd4577 /GR- /c ../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/src/common/mathutil.cpp /Foobj/third_party/angle/angle_common/mathutil.obj /Fd"obj/third_party/angle/angle_common_cc.pdb"
FAILED: obj/third_party/angle/angle_common/mathutil.obj 
ninja -t msvc -e environment.x64 -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64/cl.exe" /nologo /showIncludes -DUSE_AURA=1 -DTOOLKIT_QT -D_HAS_EXCEPTIONS=0 -D__STD_C -D_CRT_RAND_S -D_CRT_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_DEPRECATE -D_ATL_NO_OPENGL -D_WINDOWS -DCERT_CHAIN_PARA_HAS_EXTRA_FIELDS -DPSAPI_VERSION=2 -DWIN32 -D_SECURE_ATL -D_USING_V110_SDK71_ -DWINAPI_FAMILY=WINAPI_FAMILY_DESKTOP_APP -DWIN32_LEAN_AND_MEAN -DNOMINMAX -D_UNICODE -DUNICODE -DNTDDI_VERSION=NTDDI_WIN10_RS2 -D_WIN32_WINNT=0x0A00 -DWINVER=0x0A00 -D_DEBUG -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DANGLE_IS_64_BIT_CPU -DANGLE_ENABLE_DEBUG_ANNOTATIONS -I../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/include -I../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/src -I../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/src/common/third_party/base -Igen/angle -I../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/include /Gy /FS /bigobj /utf-8 /Zc:sizedDealloc- /wd4117 /D__DATE__= /D__TIME__= /D__TIMESTAMP__= /W4 /wd4091 /wd4127 /wd4251 /wd4275 /wd4312 /wd4324 /wd4351 /wd4355 /wd4503 /wd4589 /wd4611 /wd4100 /wd4121 /wd4244 /wd4505 /wd4510 /wd4512 /wd4610 /wd4838 /wd4995 /wd4996 /wd4456 /wd4457 /wd4458 /wd4459 /wd4200 /wd4201 /wd4204 /wd4221 /wd4245 /wd4267 /wd4305 /wd4389 /wd4702 /wd4701 /wd4703 /wd4661 /wd4706 /wd4715 /Od /Ob0 /GF /Zi /MDd /we4244 /we4456 /we4458 /we4715 /we4800 /we4838 /TP /wd4577 /GR- /c ../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/src/common/mathutil.cpp /Foobj/third_party/angle/angle_common/mathutil.obj /Fd"obj/third_party/angle/angle_common_cc.pdb"
../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/src/common/mathutil.cpp(75): error C4244: '=': conversion from 'double' to 'float', possible loss of data
../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/src/common/mathutil.cpp(77): error C4244: '=': conversion from 'double' to 'float', possible loss of data
../../../../src/5.15.1-8798b27a4c.clean/src/3rdparty/chromium/third_party/angle/src/common/mathutil.cpp(79): error C4244: '=': conversion from 'double' to 'float', possible loss of data
```

**Comment by Neumann-A** [comment] 2021-01-18 10:08
ah that is a duplicate of the other qt5-webengine issue which is fixed in the update to 5.15.2

**Comment by al-sabr** [comment] 2021-01-18 10:21
> Add `/wd4244` can solve this issue.

Where do I put that?

**Comment by JackBoosY** [comment] 2021-01-18 10:26
@al-sabr We should waiting for #14678 merge.

**Comment by al-sabr** [comment] 2021-01-18 10:28
I have qt5:x64-windows                        5.15.1 installed with vcpkg on windows

**Comment by al-sabr** [comment] 2021-01-18 16:05
I am now testing compilation with 094e496. I will let you know if it is working well.

**Comment by al-sabr** [comment] 2021-01-18 17:53
I can confirm that the compilation goes through without generating any error until yet.  
So the patches seem the fix the compilation errors.

**Comment by al-sabr** [comment] 2021-01-18 22:10
Can someone tell me how much time it does take this module to compile?

**Comment by Neumann-A** [comment] 2021-01-18 22:15
(>4h per configuration) so at least 8 hours unless you defined VCPKG_BUILD_TYPE to release only. But it highly depends on your build PC.

**Comment by al-sabr** [comment] 2021-01-19 12:09
Here are the final results

\`\`\`

Building package qt5-webengine\[core\]:x64-windows... done

Installing package qt5-webengine\[core\]:x64-windows...

Installing package qt5-webengine\[core\]:x64-windows... done

Elapsed time for package qt5-webengine:x64-windows: 20.14 h

Total elapsed time: 20.14 h

The package qt5-webengine:x64-windows provides CMake targets:

   find\_package(Qt5Designer CONFIG REQUIRED)

   target\_link\_libraries(main PRIVATE Qt5::QWebEngineViewPlugin)

   find\_package(Qt5Gui CONFIG REQUIRED)

   target\_link\_libraries(main PRIVATE Qt5::QPdfPlugin)

   find\_package(Qt5Pdf CONFIG REQUIRED)

   target\_link\_libraries(main PRIVATE Qt::Pdf Qt5::Pdf Qt::PdfPrivate Qt5::PdfPrivate)

   find\_package(Qt5PdfWidgets CONFIG REQUIRED)

   target\_link\_libraries(main PRIVATE Qt::PdfWidgets Qt5::PdfWidgets Qt::PdfWidgetsPrivate Qt5::PdfWidgetsPrivate)

   find\_package(Qt5WebEngine CONFIG REQUIRED)

   target\_link\_libraries(main PRIVATE Qt::WebEngine Qt5::WebEngine Qt::WebEnginePrivate Qt5::WebEnginePrivate)

   find\_package(Qt5WebEngineCore CONFIG REQUIRED)

   target\_link\_libraries(main PRIVATE Qt::WebEngineCore Qt5::WebEngineCore Qt::WebEngineCorePrivate Qt5::WebEngineCorePrivate)

   find\_package(Qt5WebEngineWidgets CONFIG REQUIRED)

   target\_link\_libraries(main PRIVATE Qt::WebEngineWidgets Qt5::WebEngineWidgets Qt::WebEngineWidgetsPrivate Qt5::WebEngineWidgetsPrivate)

\`\`\`

**Comment by al-sabr** [comment] 2021-01-19 12:10
The patches are working and approved by me!

**Comment by Neumann-A** [comment] 2021-01-19 12:17
You probably only need to do 
```
 find_package(Qt5WebEngine CONFIG REQUIRED)
 target_link_libraries(main PRIVATE Qt::WebEngine )
```
in cmake

**Comment by al-sabr** [comment] 2021-01-19 12:47
It works 100% all my code is compiling.

**Comment by JackBoosY** [comment] 2021-01-20 02:58
Please wait for #14678 merge.

**Closed** 2021-01-20 20:55 UTC
Labels: category:port-bug

**Comment by 3UR** [comment] 2024-06-18 23:41
this seems to be an issue again :(
```
jom: X:\v\b\qt5-webengine\x86-windows-dbg\src\core\Makefile.gn_run.Debug [run_ninja] Error 1
jom: X:\v\b\qt5-webengine\x86-windows-dbg\src\core\Makefile.gn_run [debug] Error 2
jom: X:\v\b\qt5-webengine\x86-windows-dbg\src\core\Makefile [sub-gn_run-pro-make_first] Error 2
jom: X:\v\b\qt5-webengine\x86-windows-dbg\src\Makefile [sub-core-make_first] Error 2
jom: X:\v\b\qt5-webengine\x86-windows-dbg\Makefile [sub-src-make_first] Error 2

**Comment by 3UR** [comment] 2024-06-18 23:42
actually

```enable_extensions=true use_kerberos=true enable_ipc_logging=false use_browser_spellchecker=false qtwebengine_target=\"X:\v\bld\qt5-webengine\x86-windows-dbg\src\core\release:QtWebEngineCore\"" --root=X:\v\bld\qt5-webengine\src\5.15.13-a0ec028bd2.clean\src\3rdparty\chromium
ninja: fatal: CreateProcess: Operation did not complete successfully because the file contains a virus or potentially unwanted software.
