### ISSUE TITLE
Building icu fails on Windows 10

### ISSUE THREAD

**Issue by Kakiking** [microsoft/vcpkg#20365] opened 2021-09-26 17:58 UTC
Output of `vcpkg install qt5`:
```
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/vcpkg/downloads/tools/msys2/8a1f6fda6ae3aa5c/usr/bin/bash.exe" --noprofile --norc --debug -c "V=1 CPP='cl.exe -E' CC='cl.exe' CC_FOR_BUILD='cl.exe' CXX='cl.exe' RC='rc.exe' WINDRES='rc.exe' AR='lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS=':' ./../src/c-69_1-src-86e71a956d.clean/source/configure --build=x86_64-pc-mingw32 --disable-samples --disable-tests --disable-layoutex ac_cv_prog_ac_ct_STRIP=: gl_cv_double_slash_root=yes ac_cv_func_memmove=yes --disable-silent-rules --verbose --enable-shared --disable-static --enable-debug --disable-release --prefix=/C/Program\\ Files/vcpkg/installed/x64-windows/debug --bindir='${prefix}'/../tools/icu/debug/bin --sbindir='${prefix}'/../tools/icu/debug/sbin --libdir='${prefix}'/lib --includedir='${prefix}'/../include --datarootdir='${prefix}'/share/icu"
    Working Directory: C:/Program Files/vcpkg/buildtrees/icu/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\Program Files\vcpkg\buildtrees\icu\config-x64-windows-dbg-out.log
      C:\Program Files\vcpkg\buildtrees\icu\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:820 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:48 (vcpkg_configure_make)
  scripts/ports.cmake:140 (include)


Error: Building package icu:x64-windows failed with: BUILD_FAILED
```
```
  Package: icu:x64-windows
  Vcpkg version: 2021-09-10-2059ef11aa6067e6f59b0d939c5d17e3c5c47d3e
```
Log files:
[config-x64-windows-dbg-err.log](https://github.com/microsoft/vcpkg/files/7231932/config-x64-windows-dbg-err.log)
[config-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/7231933/config-x64-windows-dbg-out.log)

**Comment by autoantwort** [comment] 2021-09-26 18:10
duplicate of #18992

**Comment by JackBoosY** [comment] 2021-09-27 06:05
Duplicated to #18922.
This is because the nmake couldn't resolve the path with space.

**Closed by JackBoosY** 2021-09-27 06:05 UTC
