### ISSUE TITLE
icu:x64-linux build failure

### ISSUE THREAD

**Issue by cd606** [microsoft/vcpkg#24229] opened 2022-04-18 21:51 UTC
**Host Environment**
- OS: CentOS 7
- Compiler: gcc 11.2.1

**To Reproduce**
`./vcpkg install icu:x64-linux`

**Failure logs**
Computing installation plan...
The following packages will be built and installed:
    icu[core]:x64-linux -> 70.1
Detecting compiler hash for triplet x64-linux...
Restored 0 packages from .../.cache/vcpkg/archives in 24.55 us. Use --debug to see more details.
Starting package 1/1: icu:x64-linux
Building package icu[core]:x64-linux...
-- Using cached icu4c-70_1-src.tgz.
-- Cleaning sources at .../vcpkg/buildtrees/icu/src/c-70_1-src-a6ee276eef.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source .../vcpkg/downloads/icu4c-70_1-src.tgz
-- Applying patch disable-escapestr-tool.patch
-- Applying patch remove-MD-from-configure.patch
-- Applying patch fix_parallel_build_on_windows.patch
-- Applying patch fix-extra.patch
-- Applying patch mingw-dll-install.patch
-- Applying patch disable-static-prefix.patch
-- Applying patch fix-win-build.patch
-- Using source at .../vcpkg/buildtrees/icu/src/c-70_1-src-a6ee276eef.clean
-- Getting CMake variables for x64-linux-dbg
-- Getting CMake variables for x64-linux-rel
-- Generating configure for x64-linux
-- Finished generating configure for x64-linux
-- Configuring x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:128 (message):
Command failed: /usr/bin/bash -c "V=1 ./../src/c-70_1-src-a6ee276eef.clean/source/configure  \"--disable-samples\" \"--disable-tests\" \"--disable-layoutex\" \"--disable-silent-rules\" \"--verbose\" \"--disable-shared\" \"--enable-static\" \"--enable-debug\" \"--disable-release\" \"--prefix=.../vcpkg/installed/x64-linux/debug\" \"--bindir=\\${prefix}/../tools/icu/debug/bin\" \"--sbindir=\\${prefix}/../tools/icu/debug/sbin\" \"--libdir=\\${prefix}/lib\" \"--includedir=\\${prefix}/../include\" \"--datarootdir=\\${prefix}/share/icu\""
    Working Directory: .../vcpkg/buildtrees/icu/x64-linux-dbg
    Error code: 2
    See logs for more information:
      .../vcpkg/buildtrees/icu/config-x64-linux-dbg-out.log
      .../vcpkg/buildtrees/icu/config-x64-linux-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:815 (vcpkg_execute_required_process)
  ports/icu/portfile.cmake:52 (vcpkg_configure_make)
  scripts/ports.cmake:145 (include)

error: building icu:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `./vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+icu
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[icu]+Build+error
including:
  package: icu[core]:x64-linux -> 70.1
    vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
    vcpkg-scripts version: da6351432 2022-04-18 (7 minutes ago)

The relevant output from the log file  .../vcpkg/buildtrees/icu/config-x64-linux-dbg-err.log is:

./../src/c-70_1-src-a6ee276eef.clean/source/configure: line 8000: syntax error near unexpected token `newline'
./../src/c-70_1-src-a6ee276eef.clean/source/configure: line 8000: `AX_CHECK_COMPILE_FLAG('

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by autoantwort** [comment] 2022-04-18 22:46
Duplicate of #24140

**Comment by LilyWangLL** [comment] 2022-04-19 06:32
Thanks for posting this issue. Could you try the solution from: https://github.com/microsoft/vcpkg/issues/24140#issuecomment-1099166080

**Comment by cd606** [comment] 2022-04-19 16:44
That worked, thanks.

**Closed** 2022-04-20 01:50 UTC
Labels: category:question
