### ISSUE TITLE
[colmap] colmap[cuda,tests]:x64-windows build error

### ISSUE THREAD

**Issue by mxlik-ali** [microsoft/vcpkg#37515] opened 2024-03-17 04:25 UTC
C:\vcpkg>.\vcpkg install colmap[cuda,tests]:x64-windows
Computing installation plan...
The following packages will be built and installed:
    colmap[core,cuda,tests]:x64-windows@2023-10-01
Detecting compiler hash for triplet x64-windows...
A suitable version of 7zip was not found (required v23.1.0) Downloading portable 7zip 23.1.0...
Extracting 7zip...
Restored 0 package(s) from C:\Users\Mohommad Ali\AppData\Local\vcpkg\archives in 1.37 ms. Use --debug to see more details.
Installing 1/1 colmap[core,cuda,tests]:x64-windows@2023-10-01...
Building colmap[core,cuda,tests]:x64-windows@2023-10-01...
-- Using cached colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/colmap/src/f69e5aa28f-361efbb7b2.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/colmap-colmap-9c704e89ff0a80e797725e112011f9f69e5aa28f.tar.gz
-- Using source at C:/vcpkg/buildtrees/colmap/src/f69e5aa28f-361efbb7b2.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows-dbg
-- Configuring x64-windows-rel
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: C:/vcpkg/buildtrees/colmap/x64-windows-dbg
    See logs for more information:
      C:\vcpkg\buildtrees\colmap\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/colmap/portfile.cmake:58 (vcpkg_cmake_install)
  scripts/ports.cmake:175 (include)

error: building colmap:x64-windows failed with: BUILD_FAILED
Elapsed time to handle colmap:x64-windows: 6.4 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+colmap
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[colmap]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by Cheney-W** [comment] 2024-03-18 09:57
Duplicate of https://github.com/microsoft/vcpkg/issues/30272

**Closed by Cheney-W** 2024-03-18 09:57 UTC
Labels: category:port-bug
