### ISSUE TITLE
[lz4] Build error

### ISSUE THREAD

**Issue by andreamartini** [microsoft/vcpkg#35762] opened 2023-12-18 17:03 UTC
Package: lz4:x86-windows -> 1.9.4#1

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30151.0
-    vcpkg-tool version: 2023-07-19-814b7ec837b59f1c8778f72351c1dd7605983cd2
    vcpkg-scripts version: 0e47c1985 2023-12-15 (3 days ago)

**To Reproduce**

`vcpkg install librdkafka`

**Failure logs**

```
-- Using cached lz4-lz4-v1.9.4.tar.gz.
-- Cleaning sources at C:/Tools/Workspaces/DiagnosticSW/Third-Party/vcpkg/vcpkg/buildtrees/lz4/src/v1.9.4-9f4a1a30bd.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Tools/Workspaces/DiagnosticSW/Third-Party/vcpkg/vcpkg/downloads/lz4-lz4-v1.9.4.tar.gz
-- Using source at C:/Tools/Workspaces/DiagnosticSW/Third-Party/vcpkg/vcpkg/buildtrees/lz4/src/v1.9.4-9f4a1a30bd.clean
CMake Error at ports/lz4/portfile.cmake:11 (vcpkg_cmake_configure):
  Unknown CMake command "vcpkg_cmake_configure".
Call Stack (most recent call first):
  scripts/ports.cmake:170 (include)



```

**Comment by StarGate-One** [comment] 2023-12-18 17:47
>vcpkg-tool version: 2023-07-19-814b7ec837b59f1c8778f72351c1dd7605983cd2

Old vcpkg repo - update vcpkg:
`cd <vcpkg-root>`
`git pull`
`.\vcpkg-bootstrap.bat`
`vcpkg upgrade --no-dry-run`
`vcpkg install librdkafka`

**Comment by jimwang118** [comment] 2023-12-19 06:25
Sorry, I haven't reproduced this issue.
![image](https://github.com/microsoft/vcpkg/assets/122244446/2f24d08c-462f-44a1-b2b1-ececa4bf8683)

**Comment by dg0yt** [comment] 2023-12-19 07:01
@jimwang118 This error is always caused by an outdated installation of `vcpkg-cmake`, and never reproduced by a fresh installation.

**Comment by jimwang118** [comment] 2023-12-19 07:31
> vcpkg_cmake_configure

alright, thank you very much. 
@andreamartini  You can try to update `vcpkg` and then reinstall.

**Comment by andreamartini** [comment] 2023-12-19 13:16
Thank you guys. 
Unfortunally i continue get the same error after vcpkg update and reinstall.
I solved with vcpkg install in another folder (i mean:  
- git clone https://github.com/microsoft/vcpkg
-  .\vcpkg\bootstrap-vcpkg.bat
)
After that, everything gone well.

**Comment by jimwang118** [comment] 2023-12-20 02:38
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Closed by jimwang118** 2023-12-20 02:38 UTC
Labels: requires:repro
