### ISSUE TITLE
[angle] build failure

### ISSUE THREAD

**Issue by karlfroldan** [microsoft/vcpkg#25286] opened 2022-06-17 05:45 UTC
**Host Environment**
- OS: Windows 11, x64
- Compiler: MSVC 2019 (VS 2022 default)

**To Reproduce**
As with Angle website, 
1. Install python 3.10
2. Extract `depot_tools`.
3. Install with `vcpkg install angle --triplet x64-windows`

**Failure logs**
There are no failure logs. On, `ls` on powershell, almost all `*-err.log` are empty, including `install-x64-windows-dbg-err.log`.

Last few lines of `install-x64-windows-dbg-out.log`
```
[412/419] "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe"   /TP -DANGLE_CAPTURE_ENABLED=0 -DANGLE_EXPORT="" -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DEGL_EGLEXT_PROTOTYPES -DEGL_EGL_PROTOTYPES=1 -DGL_API="" -DGL_APICALL="" -DGL_GLES_PROTOTYPES=1 -DGL_GLEXT_PROTOTYPES -DGL_SILENCE_DEPRECATION -DLIBANGLE_IMPLEMENTATION -DLIBGLESV2_IMPLEMENTATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -DlibGLESv2_EXPORTS -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -ID:\dev\vcpkg\buildtrees\angle\x64-windows-dbg\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\libGLESv2.dir\src\libGLESv2\entry_points_gles_3_2_autogen.cpp.obj /FdCMakeFiles\libGLESv2.dir\ /FS -c D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\libGLESv2\entry_points_gles_3_2_autogen.cpp
[413/419] "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe"   /TP -DANGLE_CAPTURE_ENABLED=0 -DANGLE_EXPORT="" -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DEGL_EGLEXT_PROTOTYPES -DEGL_EGL_PROTOTYPES=1 -DGL_API="" -DGL_APICALL="" -DGL_GLES_PROTOTYPES=1 -DGL_GLEXT_PROTOTYPES -DGL_SILENCE_DEPRECATION -DLIBANGLE_IMPLEMENTATION -DLIBGLESV2_IMPLEMENTATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -DlibGLESv2_EXPORTS -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -ID:\dev\vcpkg\buildtrees\angle\x64-windows-dbg\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\libGLESv2.dir\src\libGLESv2\entry_points_gles_3_1_autogen.cpp.obj /FdCMakeFiles\libGLESv2.dir\ /FS -c D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\libGLESv2\entry_points_gles_3_1_autogen.cpp
[414/419] "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe"   /TP -DANGLE_CAPTURE_ENABLED=0 -DANGLE_EXPORT="" -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DEGL_EGLEXT_PROTOTYPES -DEGL_EGL_PROTOTYPES=1 -DGL_API="" -DGL_APICALL="" -DGL_GLES_PROTOTYPES=1 -DGL_GLEXT_PROTOTYPES -DGL_SILENCE_DEPRECATION -DLIBANGLE_IMPLEMENTATION -DLIBGLESV2_IMPLEMENTATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -DlibGLESv2_EXPORTS -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -ID:\dev\vcpkg\buildtrees\angle\x64-windows-dbg\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\libGLESv2.dir\src\libGLESv2\entry_points_gles_ext_autogen.cpp.obj /FdCMakeFiles\libGLESv2.dir\ /FS -c D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\libGLESv2\entry_points_gles_ext_autogen.cpp
[415/419] "D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe"   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -ID:\dev\vcpkg\buildtrees\angle\x64-windows-dbg\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\SymbolTable_autogen.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\SymbolTable_autogen.cpp
FAILED: CMakeFiles/angle_translator.dir/src/compiler/translator/SymbolTable_autogen.cpp.obj
"D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe"   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -ID:\dev\vcpkg\buildtrees\angle\x64-windows-dbg\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\SymbolTable_autogen.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\SymbolTable_autogen.cpp
D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(137): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(150): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/StaticType.h(156): fatal error C1001: Internal compiler error.
(compiler file 'msc1.cpp', line 1693)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com
Please choose the Technical Support command on the Visual C++
 Help menu, or open the Technical Support help file for more information
D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/StaticType.h(108): note: while evaluating constexpr function 'sh::StaticType::Helpers::BuildStaticArrayMangledName'
D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/StaticType.h(156): note: see reference to variable template 'const sh::StaticType::Helpers::StaticArrayMangledName kMangledNameArrayInstance<3,0,1,2,1,&sh::BuiltInVariable::kArraySize4,1>' being compiled
D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/StaticType.h(189): note: see reference to variable template 'const sh::TType arrayInstance<3,0,1,2,1,&sh::BuiltInVariable::kArraySize4,1>' being compiled
D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\SymbolTable_autogen.cpp(4211): note: see reference to function template instantiation 'const sh::TType *sh::StaticType::GetArray<sh::EbtInt,sh::EbpUndefined,sh::EvqGlobal,2,1,& sh::BuiltInVariable::kArraySize4,1>(void)' being compiled
INTERNAL COMPILER ERROR in 'D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe'
    Please choose the Technical Support command on the Visual C++
    Help menu, or open the Technical Support help file for more information
ninja: build stopped: subcommand failed.
```

stdout during installation:
```
-- Using cached google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz.
-- Cleaning sources at D:/dev/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/dev/vcpkg/downloads/google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz
-- Applying patch 001-fix-uwp.patch
-- Applying patch 002-fix-builder-error.patch
-- Applying patch 003-fix-mingw.patch
-- Using source at D:/dev/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean
-- Using cached D:/dev/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Extracting source D:/dev/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Applying patch third-party-zlib-far-undef.patch
-- Using source at D:/dev/vcpkg/buildtrees/angle/src/8ee76d4a8e-895bfc7289.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: "D:/Program Files/CMake/bin/cmake.exe" --build . --config Debug --target install -- -v -j13
    Working Directory: D:/dev/vcpkg/buildtrees/angle/x64-windows-dbg
    See logs for more information:
      D:\dev\vcpkg\buildtrees\angle\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:78 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:18 (vcpkg_build_cmake)
  ports/angle/portfile.cmake:64 (vcpkg_install_cmake)
  scripts/ports.cmake:146 (include)
```

Full log attached here:
[https://gist.github.com/karlfroldan/e69f23744e460e9751210e315e253a07](https://gist.github.com/karlfroldan/e69f23744e460e9751210e315e253a07)

**Comment by JonLiu1993** [comment] 2022-06-17 05:57
This issue was fixed by Visual Studio 2022 dev branch but have not published yet.
````
FAILED: CMakeFiles/angle_translator.dir/src/compiler/translator/SymbolTable_autogen.cpp.obj 
"D:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe"   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -ID:\dev\vcpkg\buildtrees\angle\x64-windows-dbg\include -ID:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\SymbolTable_autogen.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\SymbolTable_autogen.cpp
D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(137): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(150): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
D:\dev\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/StaticType.h(156): fatal error C1001: Internal compiler error.
````

**Comment by JonLiu1993** [comment] 2022-06-17 05:58
Duplicate of #24704

**Closed by JonLiu1993** 2022-06-17 05:58 UTC
Labels: category:question
