### ISSUE TITLE
[boost-vcpkg-helpers] Build error on x64-windows-static

### ISSUE THREAD

**Issue by qwfgw** [microsoft/vcpkg#35669] opened 2023-12-14 03:00 UTC
[issue_body.md](https://github.com/microsoft/vcpkg/files/13667805/issue_body.md)

**Comment by Adela0814** [comment] 2023-12-14 06:36
Please see https://github.com/microsoft/vcpkg/issues/30604 for how to report an issue.

**Comment by Adela0814** [comment] 2023-12-14 10:23
Duplicate of  https://github.com/microsoft/vcpkg/issues/35681.

**Closed by Adela0814** 2023-12-14 10:23 UTC
Labels: category:question
