### ISSUE TITLE
error: building gmp:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by milen-prg** [microsoft/vcpkg#41813] opened 2024-10-27 18:41 UTC
error: building gmp:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle gmp:x64-windows: 6 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+gmp
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[gmp]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by dg0yt** [comment] 2024-10-27 19:17
Probably duplicates #41804.

**Comment by LilyWangLL** [comment] 2024-10-28 06:18
Duplicate of https://github.com/microsoft/vcpkg/issues/41804.

**Closed by LilyWangLL** 2024-10-28 06:18 UTC
Labels: category:port-bug
