### ISSUE TITLE
[tesseract] update to <5.0.1>

### ISSUE THREAD

**Issue by bakashigure** [microsoft/vcpkg#23210] opened 2022-02-21 19:30 UTC
Library name: `tesseract`

New version number: `5.0.1`

Other information that may be useful (release notes, etc...)
https://github.com/tesseract-ocr/tesseract/releases/tag/5.0.1

**Comment by wrosecrans** [comment] 2022-02-21 21:10
FYI, there is a draft PR for updating Tesseract already started, PR #23101 if you want to take a look at it.

**Comment by JonLiu1993** [comment] 2022-02-22 01:12
Duplicate of #16019

**Closed by JonLiu1993** 2022-02-22 01:12 UTC
Labels: category:port-update
