### ISSUE TITLE
[boost-container] Build error

### ISSUE THREAD

**Issue by Na1usnuk** [microsoft/vcpkg#33239] opened 2023-08-17 13:01 UTC
I did all the instructions from https://crowcpp.org/master/getting_started/setup/windows/, and when i run my Visual Studio project get 1 warning and 1 error:
Warning: error: building boost-container:x64-windows failed with: BUILD_FAILED Crow111 C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets 183
Error: MSB3073 The command ""C:\dev\vcpkg\vcpkg.exe" install --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\dev\vcpkg\" "--x-manifest-root=C:\Users\Nazar\Documents\Visual Studio 2022\Projects\Crow111\Crow111\" "--x-install-root=C:\Users\Nazar\Documents\Visual Studio 2022\Projects\Crow111\Crow111\vcpkg_installed\x64-windows\" --feature-flags="versions"" exited with code 1. Crow111 C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets 183

I already tried git pull and vcpkg update (all up to date)

There is build output:
Build started...
1>------ Build started: Project: Crow111, Configuration: Debug x64 ------
1>Installing vcpkg dependencies to C:\Users\Nazar\Documents\Visual Studio 2022\Projects\Crow111\Crow111\vcpkg_installed\x64-windows
1>"C:\dev\vcpkg\vcpkg.exe" install --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\dev\vcpkg\" "--x-manifest-root=C:\Users\Nazar\Documents\Visual Studio 2022\Projects\Crow111\Crow111\" "--x-install-root=C:\Users\Nazar\Documents\Visual Studio 2022\Projects\Crow111\Crow111\vcpkg_installed\x64-windows\" --feature-flags="versions"
1>Detecting compiler hash for triplet x64-windows...
1>The following packages will be built and installed:
1> boost-algorithm:x64-windows -> 1.70.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-algorithm\cbb4255f2568bd50392989d2da11c11b0ffde059
1> * boost-align:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-align\9f77d89d4c76cf998be2d4f15aa922e04f233f1c
1> boost-array:x64-windows -> 1.70.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-array\d27628d9a0832fb99c3adb78cc1807b5e4ecd7ac
1> boost-asio:x64-windows -> 1.70.0-2 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-asio\8f730c9bf4fcc233ec5a43c5584c9694cc2f3916
1> * boost-atomic:x64-windows -> 1.75.0#1 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-atomic\b0eb6bd0f609a494f58910e9f5c640144d5f8890
1> * boost-bind:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-bind\110fc6710128cce06256143e5c2df83bf3060a42
1> * boost-chrono:x64-windows -> 1.75.0#1 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-chrono\23fe79b0d84dee32f51951fa275a5949e1188930
1> * boost-container:x64-windows -> 1.75.0#1 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-container\5d351bf7c795d3dd8437d2beed167bd3cd66e10b
1> * boost-context:x64-windows -> 1.75.0#4 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-context\73ede4d1c06f12b1162f39e0b03935cc429c763a
1> * boost-coroutine:x64-windows -> 1.75.0#1 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-coroutine\cb03de5030c0a5c3b49eff0acb5b363156c458ba
1> boost-date-time:x64-windows -> 1.70.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-date-time\68b4aa76f870d0c3bfa8c7ebe16456cc06508046
1> * boost-exception:x64-windows -> 1.75.0#1 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-exception\913ecf461f245ac3467948fdddf49ce4b6f1b6ff
1> * boost-function:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-function\7698d7fd2822972ca04cfe1c9778c9f04fb56c3e
1> * boost-lambda:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-lambda\c3c314ac0cc6971f58c7dd9fc1708caaa059b7ae
1> boost-lexical-cast:x64-windows -> 1.70.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-lexical-cast\0d81c9256f1dcf4190d10319281d66ebd712679b
1> * boost-math:x64-windows -> 1.75.0#1 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-math\c64c9882971998a3d0330928f7e8c48a3e584658
1> * boost-mp11:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-mp11\d70457824e1e3084281f6841211641a548a2ea56
1> * boost-numeric-conversion:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-numeric-conversion\9de299c79ee96b9090a3a27cbbaee41b62455003
1> * boost-pool:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-pool\90d72e8d8b2f27deb72fc883542f130142878a86
1> * boost-range:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-range\57c3a7dae1c551c1839a35a2d518c2ea0dd43795
1> * boost-ratio:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-ratio\bfdcac03e6dd3a24818ca99a96f464a2404f2f0b
1> * boost-rational:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-rational\27fc174ae8a94007819eecfa02e8830e85017ebd
1> * boost-regex:x64-windows -> 1.75.0#2 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-regex\9b5c6faa967ec00a8f3ed0aa1bb1f82564e3e064
1> * boost-system:x64-windows -> 1.75.0#1 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-system\0a1188e2c052f77ac0b2152eb3ad78e19ed29e0c
1> * boost-thread:x64-windows -> 1.75.0#1 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-thread\281c8b8c17e414c9b0fd0b0bc6a569fba02d4fff
1> * boost-tokenizer:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-tokenizer\ce248c1ba37037937a656c72bfaafb0d523559e4
1> * boost-type-index:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-type-index\1ed3f10185cfa0140d6b5dd5e7be18b7b3b447c6
1> * boost-unordered:x64-windows -> 1.75.0 -- C:\dev\vcpkg\buildtrees\versioning_\versions\boost-unordered\28c6f9fc668fed0a0f193cda0a99619e8beeb398
1> openssl:x64-windows -> 1.1.1k -- C:\dev\vcpkg\buildtrees\versioning_\versions\openssl\dc279487c79f2b009333d7888799f3f9f83d8765
1> zlib:x64-windows -> 1.2.11#10 -- C:\dev\vcpkg\buildtrees\versioning_\versions\zlib\53a4615c8bb9b98a3864b834a6bbe51cc6c849ef
1>Additional packages (*) will be modified to complete this operation.
1>Restored 0 package(s) from C:\Users\Nazar\AppData\Local\vcpkg\archives in 1.12 ms. Use --debug to see more details.
1>Installing 1/30 boost-container:x64-windows...
1>Building boost-container:x64-windows...
1>-- Installing port from location: C:\dev\vcpkg\buildtrees\versioning_\versions\boost-container\5d351bf7c795d3dd8437d2beed167bd3cd66e10b
1>-- Using cached boostorg-container-boost-1.75.0.tar.gz.
1>-- Cleaning sources at C:/dev/vcpkg/buildtrees/boost-container/src/ost-1.75.0-707de84ce8.clean. Use --editable to skip cleaning for the packages you specify.
1>-- Extracting source C:/dev/vcpkg/downloads/boostorg-container-boost-1.75.0.tar.gz
1>-- Using source at C:/dev/vcpkg/buildtrees/boost-container/src/ost-1.75.0-707de84ce8.clean
1>CMake Error at C:/Users/Nazar/Documents/Visual Studio 2022/Projects/Crow111/Crow111/vcpkg_installed/x64-windows/x64-windows/share/boost-build/boost-modular-build.cmake:316 (message):
1> Unsupported value for VCPKG_PLATFORM_TOOLSET: 'v143'
1>Call Stack (most recent call first):
1> buildtrees/versioning_/versions/boost-container/5d351bf7c795d3dd8437d2beed167bd3cd66e10b/portfile.cmake:15 (boost_modular_build)
1> scripts/ports.cmake:147 (include)
1>
1>
1>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : error: building boost-container:x64-windows failed with: BUILD_FAILED
1>Elapsed time to handle boost-container:x64-windows: 313 ms
1>Please ensure you're using the latest port files with git pull and vcpkg update.
1>Then check for known issues at:
1> https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+boost-container
1>You can submit a new issue at:
1> [https://github.com/microsoft/vcpkg/issues/new?title=[boost-container]+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2FNazar%2FDocuments%2FVisual%20Studio%202022%2FProjects%2FCrow111%2FCrow111%2Fvcpkg_installed%2Fx64-windows%2Fvcpkg%2Fissue_body.md](https://github.com/microsoft/vcpkg/issues/new?title=%5Bboost-container%5D+Build+error&body=Copy+issue+body+from+C%3A%2FUsers%2FNazar%2FDocuments%2FVisual%20Studio%202022%2FProjects%2FCrow111%2FCrow111%2Fvcpkg_installed%2Fx64-windows%2Fvcpkg%2Fissue_body.md)
1>
1>C:\dev\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): error MSB3073: The command ""C:\dev\vcpkg\vcpkg.exe" install --x-wait-for-lock --triplet "x64-windows" --vcpkg-root "C:\dev\vcpkg\" "--x-manifest-root=C:\Users\Nazar\Documents\Visual Studio 2022\Projects\Crow111\Crow111\" "--x-install-root=C:\Users\Nazar\Documents\Visual Studio 2022\Projects\Crow111\Crow111\vcpkg_installed\x64-windows\" --feature-flags="versions"" exited with code 1.
1>Done building project "Crow111.vcxproj" -- FAILED.
1>
1>Project Performance Summary:
1> 4974 ms C:\Users\Nazar\Documents\Visual Studio 2022\Projects\Crow111\Crow111\Crow111.vcxproj 1 calls
1>
1>Target Performance Summary:
1> 0 ms PreBuildEvent 1 calls
1> 0 ms BuildGenerateSourcesTraverse 1 calls
1> 0 ms SelectClCompile 1 calls
1> 0 ms VcpkgCheckManifestRoot 1 calls
1> 0 ms _SelectedFiles 1 calls
1> 0 ms ComputeCustomBuildOutput 1 calls
1> 0 ms CopyFileToFolders 1 calls
1> 0 ms _Xsd 1 calls
1> 0 ms ComputeMIDLGeneratedCompileInputs 1 calls
1> 0 ms AfterMidl 1 calls
1> 0 ms _Midl 1 calls
1> 0 ms AfterBuildGenerateSources 1 calls
1> 0 ms AfterBuildGenerateSourcesEvent 1 calls
1> 0 ms _BuildGenerateSourcesAction 1 calls
1> 0 ms BuildGenerateSources 1 calls
1> 0 ms BuildCompileTraverse 1 calls
1> 0 ms ComputeCLInputPDBName 1 calls
1> 0 ms FindReferenceAssembliesForReferences 1 calls
1> 0 ms GetReferencedVCProjectsInfo 1 calls
1> 0 ms ComputeReferenceCLInput 1 calls
1> 0 ms ResolveReferences 1 calls
1> 0 ms AfterResolveReferences 1 calls
1> 0 ms BeforeBuildGenerateSources 1 calls
1> 0 ms ExpandSDKReferences 1 calls
1> 0 ms BeforeResolveReferences 1 calls
1> 0 ms _AddOutputPathToGlobalPropertiesToRemove 1 calls
1> 0 ms ResolveProjectReferences 1 calls
1> 0 ms GetFrameworkPaths 1 calls
1> 0 ms GetReferenceAssemblyPaths 1 calls
1> 0 ms SetBuildDefaultEnvironmentVariables 1 calls
1> 0 ms PrepareProjectReferences 1 calls
1> 0 ms VcpkgTripletSelection 1 calls
1> 0 ms _CheckWindowsSDKInstalled 1 calls
1> 0 ms SetCABuildNativeEnvironmentVariables 1 calls
1> 0 ms ResolveSDKReferences 1 calls
1> 0 ms GetResolvedWinMD 1 calls
1> 1 ms ResolveAssemblyReferences 1 calls
1> 1 ms BeforeClCompile 1 calls
1> 1 ms SelectCustomBuild 1 calls
1> 2 ms _PrepareForReferenceResolution 1 calls
1> 2 ms AddExternalIncludDirectoriesToPaths 1 calls
1> 2 ms MakeDirsForMidl 1 calls
1> 2 ms ComputeStdModulesCompileInputs 1 calls
1> 4 ms MakeDirsForCl 1 calls
1> 4 ms WarnCompileDuplicatedFilename 1 calls
1> 5 ms _SplitProjectReferencesByFileExistence 1 calls
1> 5 ms SetTelemetryEnvironmentVariables 1 calls
1> 5 ms FixupCLCompileOptions 1 calls
1> 9 ms AssignProjectConfiguration 1 calls
1> 9 ms CustomBuild 1 calls
1> 13 ms InitializeBuildStatus 1 calls
1> 14 ms _PrepareForBuild 1 calls
1> 28 ms PrepareForBuild 1 calls
1> 34 ms _GetProjectReferenceTargetFrameworkProperties 1 calls
1> 63 ms _CheckForInvalidConfigurationAndPlatform 1 calls
1> 4731 ms VcpkgInstallManifestDependencies 1 calls
1>
1>Task Performance Summary:
1> 1 ms CheckVCToolsetVersion 1 calls
1> 1 ms SetRidAgnosticValueForProjects 1 calls
1> 2 ms WriteLinesToFile 1 calls
1> 2 ms Touch 1 calls
1> 4 ms SetEnv 11 calls
1> 6 ms MSBuild 1 calls
1> 6 ms MakeDir 6 calls
1> 7 ms ReadLinesFromFile 1 calls
1> 9 ms AssignProjectConfiguration 1 calls
1> 9 ms GetOutOfDateItems 3 calls
1> 21 ms Message 6 calls
1> 4725 ms Exec 1 calls
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 15:28 and took 05,901 seconds ==========

Please help!

**Comment by LilyWangLL** [comment] 2023-08-18 01:36
Closed as duplicate of #33238.

**Closed by LilyWangLL** 2023-08-18 01:36 UTC
