### ISSUE TITLE
vcpkg bootstrap failed on FreeBSD 13

### ISSUE THREAD

**Issue by AFOEK** [microsoft/vcpkg#31070] opened 2023-04-23 14:28 UTC
**Describe the bug**
Failed to bootstrap on FreeBSD, when building CXX object files.

**Environment**
- OS: FreeBSD 13.1
- Compiler: clang 13

**To Reproduce**
1. ./bootstrap-vcpkg.sh

**Expected behavior**
Building of vcpkg complete and successful

**Failure logs**
```
FAILED: CMakeFiles/vcpkg-test.dir/src/vcpkg-test/argument.cpp.o
...
...
...
error: POSIX thread support was enabled in PCH file but is currently disabled
```

**Additional context**
I'm running on bare metal FreeBSD

**Comment by autoantwort** [comment] 2023-04-23 15:56
Duplicate of https://github.com/microsoft/vcpkg/issues/30863. It is fixed on main but not released yet.

**Comment by MonicaLiu0311** [comment] 2023-04-24 05:43
Fixed by https://github.com/microsoft/vcpkg-tool/pull/1025.

**Closed by MonicaLiu0311** 2023-04-24 05:43 UTC
Labels: category:question
