### ISSUE TITLE
vcpkg crashes while building opencv with x86-windows-static-md

### ISSUE THREAD

**Issue by carmangary** [microsoft/vcpkg#30533] opened 2023-03-30 02:02 UTC
**Describe the bug**
Building a project with opencv causes vcpkg to crash with latest version.  This was working fine in the past but today I did a git pull on the vcpkg repo and now it fails.

**Environment**
- OS: Windows
- Compiler: Visual Studio 17.5.3

**To Reproduce**
1. With latest vcpkg I have project with this manifestL
{
  "$schema": "https://raw.githubusercontent.com/microsoft/vcpkg/master/scripts/vcpkg.schema.json",
  "name": "spaghetti-laser-show",
  "builtin-baseline": "6ba505cf2c1752d8ea5abb21427e23ff89dc486f",
  "version": "0.0.1",
  "dependencies": [
    {
      "name": "opencv"
    },
    {
      "name": "libusb"
    }
  ],
  "overrides": [
    {
      "name": "libusb",
      "version": "1.0.23"
    }
  ]
}
2. See error
>The following packages will be built and installed:
8>  * libpng[core]:x86-windows-static-md -> 1.6.37#16 -- H:\vcpkg\buildtrees\versioning_\versions\libpng\b082585ac20aefc27150af5386b6a8a15473e93a
8>    opencv[core,default-features]:x86-windows-static-md -> 4.5.4#1 -- H:\vcpkg\buildtrees\versioning_\versions\opencv\c120b015f37bc79900712d64e8ca612d71be22cc
8>  * opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x86-windows-static-md -> 4.5.4#2 -- H:\vcpkg\buildtrees\versioning_\versions\opencv4\537abba5a070d173cf42510f86ff4ffe057dd77f
8>  * protobuf[core]:x64-windows -> 3.18.0#1 -- H:\vcpkg\buildtrees\versioning_\versions\protobuf\5f6aa04d94e184b89c1887946fb4684bc51c4611
8>  * protobuf[core]:x86-windows-static-md -> 3.18.0#1 -- H:\vcpkg\buildtrees\versioning_\versions\protobuf\5f6aa04d94e184b89c1887946fb4684bc51c4611
8>  * quirc[core]:x86-windows-static-md -> 1.1#2 -- H:\vcpkg\buildtrees\versioning_\versions\quirc\15bad29ef4d2466b236311ce7af075dbb9507ed9
8>Additional packages (*) will be modified to complete this operation.
8>Restored 0 package(s) from C:\Users\Gary\AppData\Local\vcpkg\archives in  274 us. Use --debug to see more details.
8>Installing 1/6 quirc:x86-windows-static-md...
8>Building quirc[core]:x86-windows-static-md...
8>H:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : warning: -- Using community triplet x86-windows-static-md. This triplet configuration is not guaranteed to succeed.
8>-- [COMMUNITY] Loading triplet configuration from: H:\vcpkg\triplets\community\x86-windows-static-md.cmake
8>-- Installing port from location: H:\vcpkg\buildtrees\versioning_\versions\quirc\15bad29ef4d2466b236311ce7af075dbb9507ed9
8>-- Using cached dlbeer-quirc-7e7ab596e4d0988faf1c12ae89c354b114181c40.tar.gz.
8>-- Cleaning sources at H:/vcpkg/buildtrees/quirc/src/b114181c40-f1e71e0d5b.clean. Use --editable to skip cleaning for the packages you specify.
8>-- Extracting source H:/vcpkg/downloads/dlbeer-quirc-7e7ab596e4d0988faf1c12ae89c354b114181c40.tar.gz
8>-- Using source at H:/vcpkg/buildtrees/quirc/src/b114181c40-f1e71e0d5b.clean
8>-- Found external ninja('1.11.0').
8>-- Configuring x86-windows-static-md
8>-- Building x86-windows-static-md-dbg
8>-- Building x86-windows-static-md-rel
8>-- Installing: H:/vcpkg/packages/quirc_x86-windows-static-md/share/quirc/copyright/LICENSE
8>-- Performing post-build validation
8>H:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : warning: `copyright` being a directory is deprecated.
8>H:\vcpkg\scripts\buildsystems\msbuild\vcpkg.targets(183,5): warning : warning: The software license must be available at ${CURRENT_PACKAGES_DIR}/share/quirc/copyright
8>Elapsed time to handle quirc:x86-windows-static-md: 3.1538863 s
8>vcpkg has crashed. Please create an issue at https://github.com/microsoft/vcpkg containing a brief summary of what you were trying to do and the following information.
8>
8>Version=2023-03-14-105f7f7e8a5ea10dfac9874ff9d1a6bacba5f454
8>EXCEPTION=argument not found

**Expected behavior**
No error

**Failure logs**
None

**Additional context**
None

I am not sure how to go about debugging this issue.  Please let me know if there is additional information needed and how to obtain it.

**Comment by MonicaLiu0311** [comment] 2023-03-30 10:04
Glad I reproduced the problem and found the cause.

The `builtin-baseline` you are using is `6ba505cf2c1752d8ea5abb21427e23ff89dc486f`, which was committed on `2022-01-28`:
```
PS E:\vcpkg02> git show 6ba505cf2c1752d8ea5abb21427e23ff89dc486f
commit 6ba505cf2c1752d8ea5abb21427e23ff89dc486f
Author: autoantwort <41973254+autoantwort@users.noreply.github.com>
Date:   Fri Jan 28 20:30:49 2022 +0100
```

At this point, the processing of `copyright` in `prots/quirc/portfile.cmake` is as follows:
`file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/quirc/copyright)`

It will create a `share/quirc/copyright/` folder, which is non-compliant, so a post-check error will be reported:
```
-- Performing post-build validation
warning: `copyright` being a directory is deprecated.
warning: The software license must be available at ${CURRENT_PACKAGES_DIR}/share/quirc/copyright
Elapsed time to handle quirc:x86-windows-static-md: 12.8941562 s
vcpkg has crashed. Please create an issue at https://github.com/microsoft/vcpkg containing a brief summary of what you were trying to do and the following information.
```

Later, we uniformly made modifications in https://github.com/microsoft/vcpkg/pull/25409: 
```
- file(INSTALL ${SOURCE_PATH}/LICENSE DESTINATION ${CURRENT_PACKAGES_DIR}/share/quirc/copyright)
+ file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
```


There are currently two **solutions**:
1. Use the modified ID, for example: 763f6664c1858240fdfb563c55f9c9fdc5e19ac7. 

2. Use `override` to overwrite other version constraints:
```
"overrides": [
    {
        "name": "quirc",
        "version": "1.1#3"
    }
]
```

**Comment by carmangary** [comment] 2023-03-30 23:42
Thank you.  I didn't use either of your solutions but your reply did make me notice my builtin-baseline uuid.  I don't quite understand how that value works but I updated it to the current value of vcpkg and now my application compiles without error.  Thank you for your reply and the explanation.

**Comment by MonicaLiu0311** [comment] 2023-03-31 06:34
> I don't quite understand how that value works

For a port that does not specify a version with `override` and `version>=`, it will search for the highest version specified by the current `builtin-baseline` by default.

For example: https://github.com/microsoft/vcpkg/commit/763f6664c1858240fdfb563c55f9c9fdc5e19ac7
```
PS E:\vcpkg01> git show 763f666
commit 763f6664c1858240fdfb563c55f9c9fdc5e19ac7
Author: Thomas1664 <46387399+Thomas1664@users.noreply.github.com>
Date: Fri Jun 24 21:50:23 2022 +0200
```
Your dependency `opencv` will find the latest version before `Date: Fri Jun 24 21:50:23 2022 +0200`:
```
PS E:\vcpkg04> git blame versions/o-/opencv.json
2f6537fa2b port_versions/o-/opencv.json (Victor Romero     2021-01-14 16:08:36 -0800   1) {
2f6537fa2b port_versions/o-/opencv.json (Victor Romero     2021-01-14 16:08:36 -0800   2)   "versions": [
2a95acc161 versions/o-/opencv.json      (Russell Greene    2023-02-24 14:02:54 -0600   3)     {
2a95acc161 versions/o-/opencv.json      (Russell Greene    2023-02-24 14:02:54 -0600   4)       "git-tree": "7c13270745cf85fc4146cd4f21ee4f71eb2ca7e1",
2a95acc161 versions/o-/opencv.json      (Russell Greene    2023-02-24 14:02:54 -0600   5)       "version": "4.7.0",
2a95acc161 versions/o-/opencv.json      (Russell Greene    2023-02-24 14:02:54 -0600   6)       "port-version": 1
2a95acc161 versions/o-/opencv.json      (Russell Greene    2023-02-24 14:02:54 -0600   7)     },
49299e0c05 versions/o-/opencv.json      (Matthew Oliver    2023-01-18 06:35:29 +1100   8)     {
49299e0c05 versions/o-/opencv.json      (Matthew Oliver    2023-01-18 06:35:29 +1100   9)       "git-tree": "562bbf3bc1027e73456d71a10020ba984eec0eb1",
49299e0c05 versions/o-/opencv.json      (Matthew Oliver    2023-01-18 06:35:29 +1100  10)       "version": "4.7.0",
49299e0c05 versions/o-/opencv.json      (Matthew Oliver    2023-01-18 06:35:29 +1100  11)       "port-version": 0
49299e0c05 versions/o-/opencv.json      (Matthew Oliver    2023-01-18 06:35:29 +1100  12)     },
acb370dd6d versions/o-/opencv.json      (Stefano Sinigardi 2022-08-05 02:21:59 +0200  13)     {
acb370dd6d versions/o-/opencv.json      (Stefano Sinigardi 2022-08-05 02:21:59 +0200  14)       "git-tree": "135db832c720c800e2ac222994aa216df7575d17",
acb370dd6d versions/o-/opencv.json      (Stefano Sinigardi 2022-08-05 02:21:59 +0200  15)       "version": "4.6.0",
acb370dd6d versions/o-/opencv.json      (Stefano Sinigardi 2022-08-05 02:21:59 +0200  16)       "port-version": 0
acb370dd6d versions/o-/opencv.json      (Stefano Sinigardi 2022-08-05 02:21:59 +0200  17)     },
bde216bf73 versions/o-/opencv.json      (LilyWangLL        2022-06-10 11:11:05 +0800  18)     {
bde216bf73 versions/o-/opencv.json      (LilyWangLL        2022-06-10 11:11:05 +0800  19)       "git-tree": "1ed18903421ae513e731348b2e5afb13c8c38d24",
bde216bf73 versions/o-/opencv.json      (LilyWangLL        2022-06-10 11:11:05 +0800  20)       "version": "4.5.5",
bde216bf73 versions/o-/opencv.json      (LilyWangLL        2022-06-10 11:11:05 +0800  21)       "port-version": 1
bde216bf73 versions/o-/opencv.json      (LilyWangLL        2022-06-10 11:11:05 +0800  22)     },
401578455f versions/o-/opencv.json      (Stefano Sinigardi 2022-02-23 20:57:13 +0100  23)     {
401578455f versions/o-/opencv.json      (Stefano Sinigardi 2022-02-23 20:57:13 +0100  24)       "git-tree": "afe6b1b5c7be14be0656724754f95e537416c763",
401578455f versions/o-/opencv.json      (Stefano Sinigardi 2022-02-23 20:57:13 +0100  25)       "version": "4.5.5",
401578455f versions/o-/opencv.json      (Stefano Sinigardi 2022-02-23 20:57:13 +0100  26)       "port-version": 0
401578455f versions/o-/opencv.json      (Stefano Sinigardi 2022-02-23 20:57:13 +0100  27)     },
```
It can be seen that the latest one before the `Date` specified by the `baseline` is `4.5.5#1` updated at `2022-06-10 11:11:05 +0800`:
```
bde216bf73 versions/o-/opencv.json      (LilyWangLL        2022-06-10 11:11:05 +0800  18)     {
bde216bf73 versions/o-/opencv.json      (LilyWangLL        2022-06-10 11:11:05 +0800  19)       "git-tree": "1ed18903421ae513e731348b2e5afb13c8c38d24",
bde216bf73 versions/o-/opencv.json      (LilyWangLL        2022-06-10 11:11:05 +0800  20)       "version": "4.5.5",
bde216bf73 versions/o-/opencv.json      (LilyWangLL        2022-06-10 11:11:05 +0800  21)       "port-version": 1
bde216bf73 versions/o-/opencv.json      (LilyWangLL        2022-06-10 11:11:05 +0800  22)     },
```
So when you use https://github.com/microsoft/vcpkg/commit/763f6664c1858240fdfb563c55f9c9fdc5e19ac7 the dependency `opencv` will download version `4.5.5#1`.

Usually, it is enough to set the `baseline` to the latest, and the latest version in vcpkg will be downloaded.

**Closed** 2023-03-31 06:35 UTC
Labels: category:question

**Comment by carmangary** [comment] 2023-03-31 10:42
@MonicaLiu0311 Thank you explaining that.  What I actually want to do is just pin the version of libusb at 1.0.23 while everything else uses the latest available version.  In order to set override for libusb it required me to set a baseline version.  Is there a way I can just pin libusb without limiting everything else to some version?  I tried to figure this out from the documentation but I wasn't able to.

**Comment by MonicaLiu0311** [comment] 2023-04-03 02:51
> Is there a way I can just pin libusb without limiting everything else to some version?

You only need to use `overrides` to specify the version of libusb, and keep the `baseline` up to date, just like you did above:
```
"overrides": [
    {
        "name": "libusb",
        "version": "1.0.23"
    }
]
```
