### ISSUE TITLE
tcmalloc

### ISSUE THREAD

**Issue by xenginez** [microsoft/vcpkg#4353] opened 2018-09-26 13:35 UTC
There is no tcmalloc library in the list

**Comment by Voskrese** [comment] 2019-03-02 13:12
double https://github.com/Microsoft/vcpkg/issues/3536

**Comment by NancyLi1013** [comment] 2019-05-07 08:12
Hi @xenginez, thanks for posting this issue. It is duplicate of #3536, we close it now. Please pay attention to the progress in #3536.

**Closed by NancyLi1013** 2019-05-07 08:12 UTC
Labels: new port request - consider making a PR!
