### ISSUE TITLE
Unable to build any package due to invalid path to vcpkg (missing platform in triplet name)

### ISSUE THREAD

**Issue by pistecid** [microsoft/vcpkg#12086] opened 2020-06-24 14:09 UTC
**Describe the bug**
Unable to build a project which uses any vcpkg library due to incorrect path to vcpkg headers/libs

**Environment**
- OS: Windows
- Visual Studio 2015

**To Reproduce**
1. Clone vcpkg, build it
2. Install any package
3. Make integrate install
4. Run visual studio, create empty project, try to use the package (e.g. include some header)

**Expected behavior**
No errors during compilation

**Additional context**
It looks like the problem is in $(VCPKG_ROOT)\scripts\buildsystems\msbuild\vcpkg.targets.
The default $(VcpkgUserTriplet) is initialized as $(PlatformTarget)-$(VcpkgOSTarget). In solution $(PlatformTarget) seems to be empty when usertriplet is calculated. The workaround is to specify $(VcpkgPlatformTarget) variable ( the same way it is defined in vcpkg.props) and use it instead of $(PlatformTarget)

**Comment by aggieNick02** [comment] 2020-06-24 15:43
This is one of the other "odd behaviors" I saw in issue https://github.com/microsoft/vcpkg/issues/12062 . It is somehow caused by commit https://github.com/microsoft/vcpkg/commit/14514508d8d30bdbd645b2bec89696aec25497f1 .

What is even more odd/interesting is that this doesn't always happen in VS2015. I think it may be dependent upon VS2015 bugfix version, as I see it in VS2015 version 14.0.25425.01 Update 3, but not in VS2015 version 14.0.25431.01 Update 3. The former defaults the triplet to `$(PlatformTarget)-$(VcpkgOSTarget)`, while the latter defaults to `$(VcpkgPlatformTarget)-$(VcpkgOSTarget)`.

I don't know how to bugfix upgrade a VS2015 install (running the latest VS2015 Update 3 installer just told me the update was already installed). As a workaround, you could try figuring out how to install the bugfix update (perhaps just remove then reinstall VS2015 Update 3 with the latest installer), or you can clone vcpkg and then checkout before the problematic commit with
```
git checkout 14514508d8d30bdbd645b2bec89696aec25497f1~1
```
from the root directory before building it.

**Comment by JackBoosY** [comment] 2020-06-28 06:21
@BillyONeal Could you take a look?

Thanks.

**Comment by JackBoosY** [comment] 2020-07-09 02:17
Close this issue via #12257 merged.

**Closed by JackBoosY** 2020-07-09 02:17 UTC
