### ISSUE TITLE
vcpkg.exe build failure with Visual Studio 2015 update 3

### ISSUE THREAD

**Issue by tigerbobo** [microsoft/vcpkg#11712] opened 2020-06-02 03:29 UTC
**Host Environment**
- OS: windows 7 64bit
- Compiler: Visual Studio 2015 update 3

**To Reproduce**
bootstrap-vcpkg.bat

**Failure logs** 
Building vcpkg.exe ...

  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.prefab.cpp
..\src\vcpkg\export.prefab.cpp : warning C4819: The file contains a character that cannot be represented in the current code page (936). Save the file in Unicode format to prevent data loss [D:\downl
oad\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj]
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  logicexpression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
..\src\vcpkg\metrics.cpp(44): error C2127: 'write_byte': illegal initialization of 'constexpr' entity with a non-constant expression [D:\download\vcpkg-master\toolsrc\vcpkglib\vcpkglib.vcxproj]
  ..\src\vcpkg\metrics.cpp(44): note: failure was caused by evaluating a lambda expression
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
D:\download\vcpkg-master\scripts\bootstrap.ps1 : Building vcpkg.exe failed. Please ensure you have installed Visual Studio with the Desktop C++ workload and the Windows SDK for Desktop C++.
At line:1 char:4
+ & {& 'D:\download\vcpkg-master\scripts\bootstrap.ps1' }
+    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,bootstrap.ps1

**Additional context**
Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by tigerbobo** [comment] 2020-06-02 03:31
![image](https://user-images.githubusercontent.com/47912046/83476977-a363e680-a4c4-11ea-9582-60fa0d4ba501.png)

**Comment by Voskrese** [comment] 2020-06-02 08:30
> Please ensure you have installed Visual Studio with the Desktop C++ workload  **and the Windows SDK for Desktop C++.**

**Comment by LilyWangL** [comment] 2020-06-04 09:58
Thanks for posting this issue. I can't reproduce this issue on Visual Studio 2015 and Visual Studio 2017.

**Comment by LilyWangL** [comment] 2020-06-08 03:19
Closed as duplicate of #11773.

**Closed by LilyWangL** 2020-06-08 03:19 UTC
Labels: category:vcpkg-bug
