### ISSUE TITLE
gfortran build failure (dependency of lapack

### ISSUE THREAD

**Issue by rkcarroll** [microsoft/vcpkg#12892] opened 2020-08-13 14:29 UTC
After new pull today (08/13/2020), gfortran, a dependency of lapack, fails to build.

E:\Libs\vcpkg>vcpkg install ceres[eigensparse,lapack,tools]
Computing installation plan...
The following packages will be built and installed:
    ceres[core,eigensparse,lapack,tools]:x64-windows
  * lapack[core]:x64-windows
  * lapack-reference[blas-select,core,noblas]:x64-windows
  * vcpkg-gfortran[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/4: vcpkg-gfortran:x64-windows
Building package vcpkg-gfortran[core]:x64-windows...
Could not locate cached archive: C:\Users\Kevin.Carroll\AppData\Local\vcpkg\archives\b3\b3aedb32ae55a0c39d901fa6b0296b15faa7c0a5.zip
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Acquiring MSYS Packages...
-- Acquiring MSYS Packages... OK
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/bin/libgfortran-5.dll
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/bin/libquadmath-0.dll
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/bin/libwinpthread-1.dll
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/bin/libgcc_s_seh-1.dll
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/debug/bin/libgfortran-5.dll
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/debug/bin/libquadmath-0.dll
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/debug/bin/libwinpthread-1.dll
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/debug/bin/libgcc_s_seh-1.dll
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/share/vcpkg-gfortran/license/winpthreads
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/share/vcpkg-gfortran/license/winpthreads/COPYING
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/share/vcpkg-gfortran/license/winpthreads/mingw-w64-libraries
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/share/vcpkg-gfortran/license/winpthreads/mingw-w64-libraries/winpthreads
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/share/vcpkg-gfortran/license/winpthreads/mingw-w64-libraries/winpthreads/COPYING
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/share/vcpkg-gfortran/license/gcc-libs
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/share/vcpkg-gfortran/license/gcc-libs/COPYING.LIB
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/share/vcpkg-gfortran/license/gcc-libs/COPYING.RUNTIME
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/share/vcpkg-gfortran/license/gcc-libs/COPYING3
-- Installing: E:/Libs/vcpkg/packages/vcpkg-gfortran_x64-windows/share/vcpkg-gfortran/license/gcc-libs/README
CMake Error at ports/vcpkg-gfortran/portfile.cmake:50 (file):
  file INSTALL cannot find
  "E:/Libs/vcpkg/downloads/tools/msys2/msys64/mingw64/share/licenses/crt/COPYING.MinGW-w64-runtime.txt":
  No such file or directory.
Call Stack (most recent call first):
  scripts/ports.cmake:79 (include)

Error: Building package vcpkg-gfortran:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vcpkg-gfortran:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by Neumann-A** [comment] 2020-08-13 20:15
duplicate of #12888

**Comment by Neumann-A** [comment] 2020-08-13 20:18
Please remove your cached MSYS install and retry. Normally it is located in `downloads/tools/msys2`

**Comment by rkcarroll** [comment] 2020-08-16 12:43
I removed my cached MSYS and retried the install.  MSYS was pulled down, but the error persists.

Here is the output and the vcpkg\buildtrees\lapack-reference\config-x64-windows-out.log:
==================================
E:\Libs\vcpkg>vcpkg install lapack
Computing installation plan...
The following packages will be built and installed:
    lapack[core]:x64-windows
  * lapack-reference[blas-select,core,noblas]:x64-windows
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Starting package 1/2: lapack-reference:x64-windows
Building package lapack-reference[blas-select,core,noblas]:x64-windows...
Could not locate cached archive: C:\Users\Kevin.Carroll\AppData\Local\vcpkg\archives\3e\3efd478cfc4b6e71d4d5bab59e76004378608593.zip
-- Using cached E:/Libs/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Cleaning sources at E:/Libs/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source E:/Libs/vcpkg/downloads/Reference-LAPACK-lapack-v3.8.0.tar.gz
-- Using source at E:/Libs/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean
-- The Fortran compiler identification is unknown
-- No Fortran compiler found on the PATH. Using MinGW gfortran!
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: ninja -v
    Working Directory: E:/Libs/vcpkg/buildtrees/lapack-reference/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\Libs\vcpkg\buildtrees\lapack-reference\config-x64-windows-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:300 (vcpkg_execute_required_process)
  ports/lapack-reference/portfile.cmake:56 (vcpkg_configure_cmake)
  scripts/ports.cmake:79 (include)


Error: Building package lapack-reference:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: lapack-reference:x64-windows
  Vcpkg version: 2020.06.15-nohash

Additionally, attach any relevant sections from the log files above.
=================================
[1/2] cmd /c "cd ../../x64-windows-dbg && "E:/Libs/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "E:/Libs/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean" "-DUSE_OPTIMIZED_BLAS=ON" "-DCBLAS=OFF" "-DCMAKE_GNUtoMS=ON" "-DCMAKE_Fortran_COMPILER=E:/Libs/vcpkg/downloads/tools/msys2-20200812/msys64/mingw64/bin/gfortran.exe" "-DCMAKE_C_COMPILER=E:/Libs/vcpkg/downloads/tools/msys2-20200812/msys64/mingw64/bin/gcc.exe" "-DCMAKE_Fortran_FLAGS_INIT:STRING= -mabi=ms -m64 " "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/Libs/vcpkg/scripts/toolchains/mingw.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/Libs/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=E:/Libs/vcpkg" "-D_VCPKG_INSTALLED_DIR=E:/Libs/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=E:/Libs/vcpkg/packages/lapack-reference_x64-windows/debug""
FAILED: ../../x64-windows-dbg/CMakeCache.txt 
cmd /c "cd ../../x64-windows-dbg && "E:/Libs/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "E:/Libs/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean" "-DUSE_OPTIMIZED_BLAS=ON" "-DCBLAS=OFF" "-DCMAKE_GNUtoMS=ON" "-DCMAKE_Fortran_COMPILER=E:/Libs/vcpkg/downloads/tools/msys2-20200812/msys64/mingw64/bin/gfortran.exe" "-DCMAKE_C_COMPILER=E:/Libs/vcpkg/downloads/tools/msys2-20200812/msys64/mingw64/bin/gcc.exe" "-DCMAKE_Fortran_FLAGS_INIT:STRING= -mabi=ms -m64 " "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/Libs/vcpkg/scripts/toolchains/mingw.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/Libs/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=E:/Libs/vcpkg" "-D_VCPKG_INSTALLED_DIR=E:/Libs/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Debug" "-DCMAKE_INSTALL_PREFIX=E:/Libs/vcpkg/packages/lapack-reference_x64-windows/debug""
CMake Error at CMakeLists.txt:3 (project):
  The Ninja generator does not support Fortran using Ninja version

    1.8.2

  due to lack of required features.  Ninja 1.10 or higher is required.


-- Configuring incomplete, errors occurred!
See also "E:/Libs/vcpkg/buildtrees/lapack-reference/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
[2/2] cmd /c "cd .. && "E:/Libs/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "E:/Libs/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean" "-DUSE_OPTIMIZED_BLAS=ON" "-DCBLAS=OFF" "-DCMAKE_GNUtoMS=ON" "-DCMAKE_Fortran_COMPILER=E:/Libs/vcpkg/downloads/tools/msys2-20200812/msys64/mingw64/bin/gfortran.exe" "-DCMAKE_C_COMPILER=E:/Libs/vcpkg/downloads/tools/msys2-20200812/msys64/mingw64/bin/gcc.exe" "-DCMAKE_Fortran_FLAGS_INIT:STRING= -mabi=ms -m64 " "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/Libs/vcpkg/scripts/toolchains/mingw.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/Libs/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=E:/Libs/vcpkg" "-D_VCPKG_INSTALLED_DIR=E:/Libs/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=E:/Libs/vcpkg/packages/lapack-reference_x64-windows""
FAILED: ../CMakeCache.txt 
cmd /c "cd .. && "E:/Libs/vcpkg/downloads/tools/cmake-3.17.2-windows/cmake-3.17.2-win32-x86/bin/cmake.exe" "E:/Libs/vcpkg/buildtrees/lapack-reference/src/v3.8.0-954f10683f.clean" "-DUSE_OPTIMIZED_BLAS=ON" "-DCBLAS=OFF" "-DCMAKE_GNUtoMS=ON" "-DCMAKE_Fortran_COMPILER=E:/Libs/vcpkg/downloads/tools/msys2-20200812/msys64/mingw64/bin/gfortran.exe" "-DCMAKE_C_COMPILER=E:/Libs/vcpkg/downloads/tools/msys2-20200812/msys64/mingw64/bin/gcc.exe" "-DCMAKE_Fortran_FLAGS_INIT:STRING= -mabi=ms -m64 " "-DCMAKE_MAKE_PROGRAM=C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=E:/Libs/vcpkg/scripts/toolchains/mingw.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v142" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=E:/Libs/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=E:/Libs/vcpkg" "-D_VCPKG_INSTALLED_DIR=E:/Libs/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=E:/Libs/vcpkg/packages/lapack-reference_x64-windows""
CMake Error at CMakeLists.txt:3 (project):
  The Ninja generator does not support Fortran using Ninja version

    1.8.2

  due to lack of required features.  Ninja 1.10 or higher is required.


-- Configuring incomplete, errors occurred!
See also "E:/Libs/vcpkg/buildtrees/lapack-reference/x64-windows-rel/CMakeFiles/CMakeOutput.log".
ninja: build stopped: subcommand failed.

**Comment by Neumann-A** [comment] 2020-08-16 13:08
Now the error is a duplicate of #12888
If you want a temporary workaround doing: `vcpkg fetch ninja` should be good enough until #12895 is merged

**Comment by LilyWangL** [comment] 2020-08-17 08:03
@rkcarroll Thanks for posting this issue. Now PR #12895 has been merged, does this issue still occur?

**Comment by rkcarroll** [comment] 2020-08-17 15:16
I did a new pull this morning (08/17/2020) and got a clean install.  Thanks!!!

**Comment by LilyWangL** [comment] 2020-08-18 07:05
Thanks for posting this issue. This issue has been fixed. So I am closing this issue for now.

**Closed by LilyWangL** 2020-08-18 07:05 UTC
Labels: requires:repro
