### ISSUE TITLE
[Github] Unable to use "reference in new issue" from source

### ISSUE THREAD

**Issue by Neumann-A** [microsoft/vcpkg#9048] opened 2019-11-19 21:07 UTC
Clicking a line in the source and trying to reference it in a new issue redirects to the issue selection screen which loses the line information for the selected code.

**Comment by JackBoosY** [comment] 2019-11-20 02:34
Try to force a refresh of that page?

**Comment by PhoebeHui** [comment] 2019-11-20 02:40
@Neumann-A , it's not a vcpkg issue, I think should be Github issue, I tried others repository like https://github.com/microsoft/vscode, it has same issue, I suspect that if it applied issue template, it will lost the line information.

**Comment by Neumann-A** [comment] 2019-11-20 09:08
I played a bit around and the problem is that the link is:
`https://github.com/microsoft/vcpkg/issues/new/choose?<permalink>`

and it should be 
`https://github.com/microsoft/vcpkg/issues/new?<permalink>`

Maybe Github offers some way to circumvent the `/choose` part or to keep the `?<permalink>` info in selection?

**Comment by grdowns** [comment] 2019-11-25 23:48
Seems like this is either "by design" or a design bug on GitHub's part. I can see there being a decision to be made about where to insert the link to the file+line in the issue template. E.g. should it go to the bottom? Top? How do we communicate this to the user?

While not related to vcpkg, this is an interesting find. I'd suggest getting in touch with someone on the GitHub team if you'd like their take on it. Imo, the "Reference in new issue" action should be disabled if there are issue templates on the repo (if that's the best option).

Thanks @Neumann-A! I'll close this since it's non-vcpkg specific.

**Closed by grdowns** 2019-11-25 23:48 UTC
