### ISSUE TITLE
MariaDB libs broken

### ISSUE THREAD

**Issue by harsh-telepathy** [Microsoft/vcpkg#4381] opened 2018-10-01 04:51 UTC
[harsh@phoenix vcpkg]$ ./vcpkg install libmariadb
The following packages will be built and installed:
    libmariadb[core]:x64-linux
Starting package 1/1: libmariadb:x64-linux
Building package libmariadb[core]:x64-linux...
-- Using cached /home/harsh/vcpkg/downloads/MariaDB-mariadb-connector-c-v3.0.2.tar.gz
-- Using source at /home/harsh/vcpkg/buildtrees/libmariadb/src/v3.0.2-283e8b69ee
-- Configuring x64-linux-dbg
-- Configuring x64-linux-rel
-- Building x64-linux-dbg
-- Building x64-linux-rel
CMake Error at ports/libmariadb/portfile.cmake:31 (file):
  file RENAME failed to rename

    /home/harsh/vcpkg/packages/libmariadb_x64-linux/lib/mariadb/mariadbclient.lib

  to

    /home/harsh/vcpkg/packages/libmariadb_x64-linux/lib/mariadbclient.lib

  because: No such file or directory

Call Stack (most recent call first):
  scripts/ports.cmake:71 (include)

Error: Building package libmariadb:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: libmariadb:x64-linux
  Vcpkg version: 0.0.113-unknownhash

**Comment by harsh-telepathy** [comment] 2018-10-01 04:52
Running inside a docker image hived off from **centos/devtoolset-7-toolchain-centos7:latest**

**Comment by Voskrese** [comment] 2018-10-01 09:36
*.lib = windows

`ls /home/harsh/vcpkg/packages/libmariadb_x64-linux/lib`

**Comment by dereksbg** [comment] 2018-11-22 17:57
Duplicate of https://github.com/Microsoft/vcpkg/issues/3624

**Comment by PhoebeHui** [comment] 2019-02-28 06:49
Thank you for posting this issue! it's a same issue with  https://github.com/Microsoft/vcpkg/issues/3624, so close it.

**Closed by PhoebeHui** 2019-02-28 06:49 UTC
Labels: port bug
