### ISSUE TITLE
[microsoft-ui-uiautomation] Build error on x64-windows

### ISSUE THREAD

**Issue by srktirumala** [microsoft/vcpkg#37904] opened 2024-04-01 13:52 UTC
Package: microsoft-ui-uiautomation:x64-windows@2022-04-26

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33522.0
-    vcpkg-tool version: 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b
    vcpkg-scripts version: 0bdcc2473 2024-04-01 (8 hours ago)

**To Reproduce**

`vcpkg install microsoft-ui-uiautomation`
**Failure logs**

```
-- Using cached Microsoft-Microsoft-UI-UIAutomation-d8c87fae212678915d9b73505e188c3b63db0d79.tar.gz.
-- Cleaning sources at D:/vcpkgUIA/buildtrees/microsoft-ui-uiautomation/src/3b63db0d79-a1bfd272c1.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/vcpkgUIA/downloads/Microsoft-Microsoft-UI-UIAutomation-d8c87fae212678915d9b73505e188c3b63db0d79.tar.gz
-- Using source at D:/vcpkgUIA/buildtrees/microsoft-ui-uiautomation/src/3b63db0d79-a1bfd272c1.clean
-- Building microsoft-ui-uiautomation for Windows
-- SOURCE_PATH: D:/vcpkgUIA/buildtrees/microsoft-ui-uiautomation/src/3b63db0d79-a1bfd272c1.clean
-- VCPKG_CMAKE_SYSTEM_NAME: 
-- VCPKG_TARGET_TRIPLET: 
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Building UiaOperationAbstraction/UiaOperationAbstraction.vcxproj for Release
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: msbuild D:/vcpkgUIA/buildtrees/microsoft-ui-uiautomation/x64-windows-rel/UiaOperationAbstraction/UiaOperationAbstraction.vcxproj /p:Configuration=Release /r:True /p:RestorePackagesConfig=True /t:Rebuild /p:ForceImportAfterCppProps=D:/vcpkgUIA/buildtrees/microsoft-ui-uiautomation/x64-windows/vcpkg_msbuild.props /p:ForceImportAfterCppTargets=D:/vcpkgUIA/buildtrees/microsoft-ui-uiautomation/x64-windows/vcpkg_msbuild.targets /t:Rebuild /p:UseMultiToolTask=true /p:MultiProcMaxCount=13 /p:EnforceProcessCountAcrossBuilds=true /m:13 -maxCpuCount:13 /p:Platform=x64 /p:PlatformTarget=x64 /p:PlatformToolset=v143 /p:WindowsTargetPlatformVersion=10.0.22621.0 /p:VcpkgApplocalDeps=false /p:VcpkgManifestInstall=false /p:VcpkgManifestEnabled=false /p:VcpkgEnabled=false /p:VcpkgTriplet=x64-windows /p:VcpkgInstalledDir=D:/vcpkgUIA/installed
    Working Directory: D:/vcpkgUIA/buildtrees/microsoft-ui-uiautomation/x64-windows-rel
    Error code: 1
    See logs for more information:
      D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\build-x64-windows-rel-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-msbuild/vcpkg_msbuild_install.cmake:108 (vcpkg_execute_required_process)
  ports/microsoft-ui-uiautomation/portfile.cmake:14 (vcpkg_msbuild_install)
  scripts/ports.cmake:175 (include)



```
<details><summary>D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\build-x64-windows-rel-out.log</summary>

```
MSBuild version 17.9.5+33de0b227 for .NET Framework
Build started 4/1/2024 7:16:16 PM.

     1>Project "D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\UiaOperationAbstraction.vcxproj" on node 1 (Restore target(s)).
     1>_GetAllRestoreProjectPathItems:
         Determining projects to restore...
       Restore:
         X.509 certificate chain validation will use the default trust store selected by .NET for code signing.
         X.509 certificate chain validation will use the default trust store selected by .NET for timestamping.
         Restoring NuGet package Microsoft.Windows.CppWinRT.2.0.200703.9.
         Restoring NuGet package Microsoft.Windows.ImplementationLibrary.1.0.191107.2.
         Adding package 'Microsoft.Windows.ImplementationLibrary.1.0.191107.2' to folder 'D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\packages'
         Adding package 'Microsoft.Windows.CppWinRT.2.0.200703.9' to folder 'D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\packages'
         Added package 'Microsoft.Windows.CppWinRT.2.0.200703.9' to folder 'D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\packages'
         Added package 'Microsoft.Windows.ImplementationLibrary.1.0.191107.2' to folder 'D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\packages'
         
         NuGet Config files used:
             C:\Users\shtiruma\AppData\Roaming\NuGet\NuGet.Config
             C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.FallbackLocation.config
             C:\Program Files (x86)\NuGet\Config\Microsoft.VisualStudio.Offline.config
         
         Feeds used:
             C:\Users\shtiruma\.nuget\packages\
             https://api.nuget.org/v3/index.json
             C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
         
         Installed:
             2 package(s) to packages.config projects
     1>Done Building Project "D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\UiaOperationAbstraction.vcxproj" (Restore target(s)).
   1:7>Project "D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\UiaOperationAbstraction.vcxproj" on node 1 (Rebuild target(s)).
     1>CoreClean:
         Creating directory "UiaOpera.A5682ADB\x64\Release\".
     1>D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\UiaOperationAbstraction.vcxproj(205,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Windows.ImplementationLibrary.1.0.191107.2\build\native\Microsoft.Windows.ImplementationLibrary.targets.
     1>Done Building Project "D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\UiaOperationAbstraction.vcxproj" (Rebuild target(s)) -- FAILED.

Build FAILED.

       "D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\UiaOperationAbstraction.vcxproj" (Rebuild target) (1:7) ->
       (EnsureNuGetPackageBuildImports target) -> 
         D:\vcpkgUIA\buildtrees\microsoft-ui-uiautomation\x64-windows-rel\UiaOperationAbstraction\UiaOperationAbstraction.vcxproj(205,5): error : This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Windows.ImplementationLibrary.1.0.191107.2\build\native\Microsoft.Windows.ImplementationLibrary.targets.

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.58
```
</details>

**Comment by srktirumala** [comment] 2024-04-01 13:54
# portfile.cmake
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO Microsoft/Microsoft-UI-UIAutomation
    REF d8c87fae212678915d9b73505e188c3b63db0d79
    SHA512 4266d5f236ee7f4e2daf02177544876f025b6ec04e9ce0ad63afd0c4674ef1411865a9188d6a8a3a13b64bab1da70bebba25f03b3fc1bf39272f0c04bcbbe28f
    HEAD_REF main
)

message(STATUS "Building microsoft-ui-uiautomation for Windows")
message(STATUS "SOURCE_PATH: ${SOURCE_PATH}")
message(STATUS "VCPKG_CMAKE_SYSTEM_NAME: ${VCPKG_CMAKE_SYSTEM_NAME}")
message(STATUS "VCPKG_TARGET_TRIPLET: ${VCPKG_TARGET_TRIPLET}")
vcpkg_msbuild_install(
    SOURCE_PATH "${SOURCE_PATH}/src/UIAutomation/"
    PROJECT_SUBPATH "UiaOperationAbstraction/UiaOperationAbstraction.vcxproj"
    OPTIONS
        "/r:True"
        "/p:RestorePackagesConfig=True"
        # "/p:configuration=Release"
        "/t:Rebuild"
        # "/p:SolutionDir=${SOURCE_PATH}/src/UIAutomation/"
)

set(VCPKG_POLICY_EMPTY_INCLUDE_FOLDER enabled)

vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSE")

**Comment by srktirumala** [comment] 2024-04-01 13:54
{
  "name": "microsoft-ui-uiautomation",
  "version-date": "2022-04-26",
  "description": "Microsoft UI Automation library",
  "homepage": "https://github.com/microsoft/Microsoft-UI-UIAutomation",
  "license": "MIT",
  "supports": "windows",
  "dependencies": [
    {
      "name": "vcpkg-msbuild",
      "host": true,
      "platform": "windows"
    }
  ]
}

**Comment by MonicaLiu0311** [comment] 2024-04-02 02:27
Duplicate of #37569.

I found that you have already submitted a PR #37389 to add this new port. If you have any questions, you can leave a message under the PR to ask the assigned members.

**Closed by MonicaLiu0311** 2024-04-02 02:27 UTC
Labels: category:question
