### ISSUE TITLE
[grpc] update upb to 20220621 for port of grpc v1.48.0

### ISSUE THREAD

**Issue by aohotnik** [microsoft/vcpkg#26128] opened 2022-08-02 13:52 UTC
GRPC v1.48.0 is using newer version of UPB as specified below, while vcpkg port of GRPC v1.48.0 is using outdated UPB version (20220404). It appears to cause runtime issues with malloc alignment when GRPC port is built for x86/windows. There were changes to alignment in newer version of UPB so I suspect something doesn't work out between new GRPC and old UPB and causes failures.

Library name: UPB

New version number:  20220621 (commit e4635f223e7d36dfbea3b722a4ca4807a7e882e2)

Other information that may be useful (release notes, etc...)

I tried bumping baselines and refs to the above versions but GRPC v1.48.0 port build starts to fail on UPB library dependency. Need a kind soul to look into it.

**Comment by JonLiu1993** [comment] 2022-09-15 09:27
Duplicate of #26808

**Closed by JonLiu1993** 2022-09-15 09:27 UTC
Labels: category:port-update
