### ISSUE TITLE
[slikenet] link failure

### ISSUE THREAD

**Issue by Reveares** [microsoft/vcpkg#13168] opened 2020-08-26 13:19 UTC
**Describe the bug**
Link slikenet to a program results in a failure.

**Environment**
- OS: Windows 10
- Compiler: Visual Studio 2019

**To Reproduce**
1. ./vcpkg install slikenet
2. `#include "slikenet/peer.h"`
3. build

**Expected behavior**
Successfully linkage.

**Failure logs** 
```
error LNK2019: unresolved external symbol "public: __thiscall SLNet::BPSTracker::TimeAndValue2::~TimeAndValue2(void)" (??1TimeAndValue2@BPSTracker@SLNet@@QAE@XZ) referenced in function "public: void * __thiscall SLNet::BPSTracker::TimeAndValue2::`vector deleting destructor'(unsigned int)" (??_ETimeAndValue2@BPSTracker@SLNet@@QAEPAXI@Z)
```

**Comment by LilyWangL** [comment] 2020-08-27 08:39
Thanks for posting this issue. After investigation, I found when defining function symbols, `slikenet` was not export these function symbols.
For example:
```
struct BPSTracker
{
	BPSTracker();
	~BPSTracker();
	void Reset(const char *file, unsigned int line);
	inline void Push1(CCTimeType time, uint64_t value1) {dataQueue.Push(TimeAndValue2(time,value1),_FILE_AND_LINE_); total1+=value1; lastSec1+=value1;}
//	void Push2(SLNet::TimeUS time, uint64_t value1, uint64_t value2);
	inline uint64_t GetBPS1(CCTimeType time) {(void) time; return lastSec1;}
	inline uint64_t GetBPS1Threadsafe(CCTimeType time) {(void) time; return lastSec1;}
//	uint64_t GetBPS2(RakNetTimeUS time);
//	void GetBPS1And2(RakNetTimeUS time, uint64_t &out1, uint64_t &out2);
	uint64_t GetTotal1(void) const;
//	uint64_t GetTotal2(void) const;

	struct TimeAndValue2
	{
		TimeAndValue2();
		~TimeAndValue2();
		TimeAndValue2(CCTimeType t, uint64_t v1);
	//	TimeAndValue2(SLNet::TimeUS t, uint64_t v1, uint64_t v2);
	//	uint64_t value1, value2;
		uint64_t value1;
		CCTimeType time;
	};
```
So these function don't support external calls, this is not a bug of VCPKG. You can ask how to use `slikenet` on the official page of `slikenet`.
https://github.com/SLikeSoft/SLikeNet
https://www.slikesoft.com/

**Comment by Reveares** [comment] 2020-08-27 20:50
Thanks for looking into this and sorry that I haven't looked deeper in this before posting the issue. I was sure the dll build and linked correctly, but this was probably with an older version.
I also tested the triplets `x64-windows-static-md`, `x64-windows-static`, `x86-windows-static-md` and `x86-windows-static`  which works fine.
Maybe it would be advisable to deactivate the triplets `x64-windows` and `x86-windows` for now because it is unclear when an official update could happen and I don't know if I could provide a fix.

**Comment by LilyWangL** [comment] 2020-08-28 03:04
Thanks for your reply. Since 'slikenet' is a `only_static_library`, actually when installing 'slikenet:x64-windows' or 'slikenet:x86-windows' the user will get a static library.

**Comment by Brouilles** [comment] 2020-09-26 11:07
Hi, 
I have the same problem @Reveares, how I can fix it?
```
1>Server.obj : error LNK2019: unresolved external symbol "public: struct SLNet::SystemAddress __cdecl SLNet::RakNetSocket2::GetBoundAddress(void)const " (?GetBoundAddress@RakNetSocket2@SLNet@@QEBA?AUSystemAddress@2@XZ) referenced in function main
1>Server.obj : error LNK2019: unresolved external symbol Gets referenced in function main
1>Server.obj : error LNK2001: unresolved external symbol "struct SLNet::SystemAddress const SLNet::UNASSIGNED_SYSTEM_ADDRESS" (?UNASSIGNED_SYSTEM_ADDRESS@SLNet@@3USystemAddress@1@B)
1>Server.obj : error LNK2001: unresolved external symbol "struct SLNet::RakNetGUID const SLNet::UNASSIGNED_RAKNET_GUID" (?UNASSIGNED_RAKNET_GUID@SLNet@@3URakNetGUID@1@B)
```
Thanks.

**Comment by Reveares** [comment] 2022-01-27 17:54
There is already an issue, but still unresolved SLikeSoft/SLikeNet#66.

**Comment by LilyWangLL** [comment] 2022-07-29 08:02
Close this issue until upstream fixes this.

**Closed by LilyWangLL** 2022-07-29 08:02 UTC
Labels: category:port-bug, depends:upstream-changes
