### ISSUE TITLE
[harfbuzz:x64-windows>] build failure

### ISSUE THREAD

**Issue by zhangkmsjtu** [microsoft/vcpkg#29320] opened 2023-01-31 11:45 UTC
Package: harfbuzz[core]:x64-windows -> 6.0.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.32.31329.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: b4f29c544 2023-01-30 (10 hours ago)

**To Reproduce**

`vcpkg install qt5:x64-windows`

**Failure logs**

```
-- Using cached harfbuzz-harfbuzz-6.0.0.tar.gz.
-- Cleaning sources at D:/Evision/src/vcpkg/buildtrees/harfbuzz/src/6.0.0-21fda9578f.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source D:/Evision/src/vcpkg/downloads/harfbuzz-harfbuzz-6.0.0.tar.gz
-- Using source at D:/Evision/src/vcpkg/buildtrees/harfbuzz/src/6.0.0-21fda9578f.clean
-- Found external ninja('1.10.2').
-- Getting CMake variables for x64-windows
-- Configuring x64-windows-dbg
-- Using cached msys-mingw-w64-i686-pkg-config-0.29.2-3-any.pkg.tar.zst.
-- Using cached msys-mingw-w64-i686-libwinpthread-git-9.0.0.6373.5be8fcd83-1-any.pkg.tar.zst.
-- Using msys root at D:/Evision/src/vcpkg/downloads/tools/msys2/9a1ec3f33446b195
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/Evision/src/vcpkg/downloads/tools/python/python-3.10.7-x64/python.exe D:/Evision/src/vcpkg/installed/x64-windows/tools/meson/meson.py -Dicu=disabled -Dgraphite=disabled -Dcoretext=disabled -Dglib=disabled -Dgobject=disabled -Dfreetype=enabled -Dcairo=disabled -Ddocs=disabled -Dtests=disabled -Dbenchmark=disabled -Dintrospection=disabled --buildtype plain --backend ninja --wrap-mode nodownload --libdir lib --native D:/Evision/src/vcpkg/buildtrees/harfbuzz/meson-x64-windows-dbg.log -Ddebug=true --prefix D:/Evision/src/vcpkg/packages/harfbuzz_x64-windows/debug --includedir ../include -Dcmake_prefix_path=['D:/Evision/src/vcpkg/installed/x64-windows/debug','D:/Evision/src/vcpkg/installed/x64-windows','D:/Evision/src/vcpkg/installed/x64-windows/share'] D:/Evision/src/vcpkg/buildtrees/harfbuzz/src/6.0.0-21fda9578f.clean
    Working Directory: D:/Evision/src/vcpkg/buildtrees/harfbuzz/x64-windows-dbg
    Error code: Exit code 0xc000007b

  

    See logs for more information:

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_meson.cmake:433 (vcpkg_execute_required_process)
  ports/harfbuzz/portfile.cmake:54 (vcpkg_configure_meson)
  scripts/ports.cmake:147 (include)



```

**Additional context**

**Comment by LilyWangLL** [comment] 2023-02-01 10:04
Duplicate of #26235.

> Thanks for posting this issue. Since `python 3.9` and above do not support Windows7, and `harfbuzz` use meson build, so `harfbuzz` build failed on Windows 7. You can try this solution from: [#23582 (comment)](https://github.com/microsoft/vcpkg/issues/23582#issuecomment-1069764361).

**Closed** 2023-02-01 23:25 UTC
Labels: category:question
