### ISSUE TITLE
[New Port Request] <webrtc>

### ISSUE THREAD

**Issue by chris-shenzhen-china** [microsoft/vcpkg#22646] opened 2022-01-20 07:09 UTC
Library name: webrtc

Library description: Build Custom Video Experiences

Source repository URL:   https://webrtc.googlesource.com/src/

Project homepage (if different from the source repository):  https://webrtc.org/?hl=en

Anything else that is useful to know when adding (such as optional features the library may have that should be included):

**Comment by Nemirtingas** [comment] 2022-01-21 08:52
Duplicate with #6205 and #12134 ?

**Comment by JackBoosY** [comment] 2022-03-24 07:05
Duplicate of #6205.

**Closed by JackBoosY** 2022-03-24 07:05 UTC
Labels: category:new-port, info:good-first-issue, info:new-port-unresolved
