### ISSUE TITLE
[ryml] build failure on x64-windows

### ISSUE THREAD

**Issue by nextstate** [microsoft/vcpkg#38167] opened 2024-04-13 00:59 UTC
### Operating system

Windows 11

### Compiler

Visual C++ 2022

### Steps to reproduce the behavior

```Shell
`
```

### Failure logs

Installing 19/20 c4core:x64-windows@0.1.11...
Elapsed time to handle c4core:x64-windows: 17.7 ms
c4core:x64-windows package ABI: b4a69090769a0d6f4f8cbe7fb718eec76c2f58fe3cda1f54cad0b29a0a00ff2d
Installing 20/20 ryml[core,def-callbacks]:x64-windows@0.5.0...
Building ryml[core,def-callbacks]:x64-windows@0.5.0...
D:\a\1\s\custom-triplets\x64-windows.cmake: info: loaded overlay triplet from here
-- Note: ryml only supports static library linkage. Building static library.
-- Downloading https://github.com/biojppm/rapidyaml/archive/v0.5.0.tar.gz -> biojppm-rapidyaml-v0.5.0.tar.gz...
-- Extracting source D:/a/1/s/thirdparty/vcpkg/downloads/biojppm-rapidyaml-v0.5.0.tar.gz
-- Applying patch cmake-fix.patch
-- Using source at D:/a/1/s/thirdparty/vcpkg/buildtrees/ryml/src/v0.5.0-406ae178a5.clean
-- Downloading https://github.com/biojppm/cmake/archive/fe41e86552046c3df9ba73a40bf3d755df028c1e.zip -> cmake-fe41e86552046c3df9ba73a40bf3d755df028c1e.zip...
-- Extracting source D:/a/1/s/thirdparty/vcpkg/downloads/cmake-fe41e86552046c3df9ba73a40bf3d755df028c1e.zip
-- Using source at D:/a/1/s/thirdparty/vcpkg/buildtrees/ryml/src/deps/55df028c1e-bc82d887ab.clean
-- Found external ninja('1.11.0').
-- Configuring x64-windows
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/a/1/s/thirdparty/vcpkg/buildtrees/ryml/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\a\1\s\thirdparty\vcpkg\buildtrees\ryml\config-x64-windows-rel-CMakeCache.txt.log
      D:\a\1\s\thirdparty\vcpkg\buildtrees\ryml\config-x64-windows-out.log

Call Stack (most recent call first):
  D:/a/1/s/build/out/x64-Release-CI/vcpkg_installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:252 (vcpkg_execute_required_process)
  ports/ryml/portfile.cmake:38 (vcpkg_cmake_configure)
  scripts/ports.cmake:175 (include)

error: building ryml:x64-windows failed with: BUILD_FAILED
Elapsed time to handle ryml:x64-windows: 7.8 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+ryml
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[ryml]+Build+error+on+x64-windows&body=Copy+issue+body+from+D%3A%2Fa%2F1%2Fs%2Fbuild%2Fout%2Fx64-Release-CI%2Fvcpkg_installed%2Fvcpkg%2Fissue_body.md
You can also submit an issue by running (GitHub CLI must be installed):
  gh issue create -R microsoft/vcpkg --title "[ryml] Build failure on x64-windows" --body-file D:/a/1/s/build/out/x64-Release-CI/vcpkg_installed/vcpkg/issue_body.md
-- Running vcpkg install - failed
CMake Error at thirdparty/vcpkg/scripts/buildsystems/vcpkg.cmake:899 (message):
  vcpkg install failed.  See logs for more information:
  D:\a\1\s\build\out\x64-Release-CI\vcpkg-manifest-install.log
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:146 (include)
  CMakeLists.txt:14 (project)

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
##[error]PowerShell exited with code '1'.
Finishing: Configure
[config-x64-windows-out.log](https://github.com/microsoft/vcpkg/files/14964783/config-x64-windows-out.log)
[config-x64-windows-rel-CMakeCache.txt.log](https://github.com/microsoft/vcpkg/files/14964784/config-x64-windows-rel-CMakeCache.txt.log)
[stdout-x64-windows.log](https://github.com/microsoft/vcpkg/files/14964785/stdout-x64-windows.log)

**Comment by nextstate** [comment] 2024-04-13 03:18
This looks like the CMake 3.29.1 issue as described in #37968

**Comment by dg0yt** [comment] 2024-04-13 09:07
Don't use CMake 3.29.1: https://github.com/microsoft/vcpkg/issues/37968
Replace CMake, and reinstall all packages that were built with this version.

**Comment by JonLiu1993** [comment] 2024-04-15 06:37
Duplicate of https://github.com/microsoft/vcpkg/issues/37968

**Closed by JonLiu1993** 2024-04-15 06:37 UTC
Labels: category:port-bug
