### ISSUE TITLE
Cannot download package

### ISSUE THREAD

**Issue by yajokboy** [microsoft/vcpkg#18919] opened 2021-07-12 16:20 UTC
I try to download any package via install command but it can not
 
Example display (I try to using Power shell and command prompt that same answer)
PS C:\> vcpkg install grpc:x64-windows
Computing installation plan...
PS C:\>

**Comment by autoantwort** [comment] 2021-07-12 18:05
Duplicate of #18636: Don't use cmake 21, use cmake 20.x

**Comment by NancyLi1013** [comment] 2021-07-13 00:37
Hi @yajokboy
 
Thanks for posting this issue.
Could you please help confirm if you encountered the same problem as #18636? If yes, please try to use cmake 3.20.x to rebuild.

https://github.com/microsoft/vcpkg/issues/18636#issuecomment-868555508

**Comment by yajokboy** [comment] 2021-07-13 01:32
> Hi @yajokboy
> 
> Thanks for posting this issue.
> Could you please help confirm if you encountered the same problem as #18636? If yes, please try to use cmake 3.20.x to rebuild.
> 
> [#18636 (comment)](https://github.com/microsoft/vcpkg/issues/18636#issuecomment-868555508)

Hi @NancyLi1013 I try to down version to 3.20.5 that worked , thank you

**Closed** 2021-07-13 01:33 UTC
Labels: category:question
