### ISSUE TITLE
[halide:x64-linux] Cmake find_package fails - Libs installed to the wrong folder

### ISSUE THREAD

**Issue by gebdadendo** [microsoft/vcpkg#19797] opened 2021-08-30 08:16 UTC
**Host Environment**
- OS: Ubuntu 20.04
- Compiler: GCC 9.3
- cmake 3.21.1

**To Reproduce**
1. $  ./vcpkg install Halide:x64-linux

2. use cmake code in a project:
```

set(CMAKE_TOOLCHAIN_FILE "$ENV{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake")
project(Halide_lab VERSION 0.1.0)
find_package(Halide REQUIRED)

```

> After I installed Halide that way, in my project, cmake find_package still failed:
> The autoscheduler libraries were expected to be in the vcpkg/installed/x64-linux/**tools/halide** folder, which they weren't.
> So I had to copy them by hand from the vcpkg/installed/x64-linux/**lib** folder to the expected place. But that's a different issue I guess.

@gebdadendo -- Please @ me in that issue as it's my responsibility to fix

_Originally posted by @alexreinking in https://github.com/microsoft/vcpkg/issues/19635#issuecomment-907317473_

**Comment by alexreinking** [comment] 2021-08-30 09:16
The problem is with `vcpkg_cmake_config_fixup()` being very greedy on Linux whereas on Windows it only rewrites `bin/*.exe`. I posted the following on Slack the other day... need a response:

> Where does vcpkg want me to put loadable modules on Linux? On Windows, putting them in bin was fine, since they had a .dll extension. But vcpkg_cmake_config_fixup() apparently breaks my package on Linux since it rewrites bin/ to tools/<port>, whereas on Windows it rewrites bin/*.exe to tools/<port>/*.exe.

**Comment by alexreinking** [comment] 2021-08-30 17:28
I wonder if the right solution is to make `vcpkg_cmake_config_fixup()` smarter about selecting executable targets on Linux. This could be done by shelling out to `file`, making sure regex matches only `add_executable()`, etc. etc.

**Comment by alexreinking** [comment] 2021-10-04 20:49
It's been a bit over a month... can I get some advice re: how to resolve this issue? I'm happy to put in the work on either the Halide port or on reworking `vcpkg_cmake_config_fixup` as I suggested above.

@ras0219-msft @ras0219 @NancyLi1013 @JackBoosY

**Comment by dg0yt** [comment] 2021-10-04 21:14
IIUC the problem is not generally rewriting `bin` to `tools/port/bin` on Linux, but having `bin` in the original exported config when libraries (or plugins?) indeed belong to `lib`.

**Comment by alexreinking** [comment] 2021-10-04 21:33
Vcpkg's policies require (or at least used to require) that loadable modules be placed in `bin`, not `lib`.

https://github.com/microsoft/vcpkg/pull/13860/commits/3bfdc2ff63a5257c4754f6922f114f3aba8f8345

**Comment by dg0yt** [comment] 2021-10-04 21:43
> Vcpkg's policies require (or at least used to require) that loadable modules be placed in `bin`, not `lib`. See the commit message in [3bfdc2f](https://github.com/microsoft/vcpkg/commit/3bfdc2ff63a5257c4754f6922f114f3aba8f8345)

The comment refers to DLLs which are in `bin` on Windows. This is not quite the same as shared objects or loadable modules on Linux. For reference, `qt5-base` installs plugins to `plugins` on Linux.

**Comment by alexreinking** [comment] 2021-10-04 22:22
@dg0yt - so is the resolution to use two different folders based on the platform, or would placing them somewhere like `lib/halide` all the time be okay?

**Comment by dg0yt** [comment] 2021-10-05 06:18
>  so is the resolution to use two different folders based on the platform, or would placing them somewhere like `lib/halide` all the time be okay?

@alexreinking I can't say for sure for vcpkg.  But you already pinged the vcpkg maintainers 9 hours ago so you let us wait for a response.

**Comment by JackBoosY** [comment] 2021-10-09 09:16
```bash
root@usr:/home/usr/work/vcpkg# find packages/halide_x64-linux/tools/halide/
featurization_to_sample    get_host_target            retrain_cost_model         weightsdir_to_weightsfile
root@usr:/home/usr/work/vcpkg# find packages/halide_x64-linux/share/ | xargs grep "featurization_to_sample"
grep: packages/halide_x64-linux/share/: Is a directory
grep: packages/halide_x64-linux/share/HalideHelpers: Is a directory
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:# Import target "Halide::featurization_to_sample" for configuration "Release"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:set_property(TARGET Halide::featurization_to_sample APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:set_target_properties(Halide::featurization_to_sample PROPERTIES
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/tools/halide/featurization_to_sample"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:list(APPEND _IMPORT_CHECK_TARGETS Halide::featurization_to_sample )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:list(APPEND _IMPORT_CHECK_FILES_FOR_Halide::featurization_to_sample "${_IMPORT_PREFIX}/tools/halide/featurization_to_sample" )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:# Import target "Halide::featurization_to_sample" for configuration "Debug"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:set_property(TARGET Halide::featurization_to_sample APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:set_target_properties(Halide::featurization_to_sample PROPERTIES
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/tools/halide/featurization_to_sample"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:list(APPEND _IMPORT_CHECK_TARGETS Halide::featurization_to_sample )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:list(APPEND _IMPORT_CHECK_FILES_FOR_Halide::featurization_to_sample "${_IMPORT_PREFIX}/tools/halide/featurization_to_sample" )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:foreach(_expectedTarget Halide::Tools Halide::ImageIO Halide::RunGenMain Halide::Runtime Halide::retrain_cost_model Halide::featurization_to_sample Halide::get_host_target Halide::weightsdir_to_weightsfile)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:# Create imported target Halide::featurization_to_sample
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:add_executable(Halide::featurization_to_sample IMPORTED)
grep: packages/halide_x64-linux/share/halide: Is a directory
grep: packages/halide_x64-linux/share/halide/tools: Is a directory
packages/halide_x64-linux/share/halide/tools/autotune_loop.sh:    ${AUTOSCHED_BIN}/featurization_to_sample ${D}/${FNAME}.featurization $R $P $S ${D}/${FNAME}.sample || echo "featurization_to_sample failed for ${D} (probably because benchmarking failed)"
root@usr:/home/usr/work/vcpkg# find packages/halide_x64-linux/share/ | xargs grep "get_host_target"
grep: packages/halide_x64-linux/share/: Is a directory
grep: packages/halide_x64-linux/share/HalideHelpers: Is a directory
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:# Import target "Halide::get_host_target" for configuration "Release"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:set_property(TARGET Halide::get_host_target APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:set_target_properties(Halide::get_host_target PROPERTIES
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/tools/halide/get_host_target"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:list(APPEND _IMPORT_CHECK_TARGETS Halide::get_host_target )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:list(APPEND _IMPORT_CHECK_FILES_FOR_Halide::get_host_target "${_IMPORT_PREFIX}/tools/halide/get_host_target" )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:# Import target "Halide::get_host_target" for configuration "Debug"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:set_property(TARGET Halide::get_host_target APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:set_target_properties(Halide::get_host_target PROPERTIES
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/tools/halide/get_host_target"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:list(APPEND _IMPORT_CHECK_TARGETS Halide::get_host_target )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:list(APPEND _IMPORT_CHECK_FILES_FOR_Halide::get_host_target "${_IMPORT_PREFIX}/tools/halide/get_host_target" )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:foreach(_expectedTarget Halide::Tools Halide::ImageIO Halide::RunGenMain Halide::Runtime Halide::retrain_cost_model Halide::featurization_to_sample Halide::get_host_target Halide::weightsdir_to_weightsfile)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:# Create imported target Halide::get_host_target
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:add_executable(Halide::get_host_target IMPORTED)
grep: packages/halide_x64-linux/share/halide: Is a directory
grep: packages/halide_x64-linux/share/halide/tools: Is a directory
packages/halide_x64-linux/share/halide/tools/autotune_loop.sh:HL_TARGET=`${AUTOSCHED_BIN}/get_host_target avx512 avx512_knl avx512_skylake avx512_cannonlake`
root@usr:/home/usr/work/vcpkg# find packages/halide_x64-linux/share/ | xargs grep "retrain_cost_model"
grep: packages/halide_x64-linux/share/: Is a directory
grep: packages/halide_x64-linux/share/HalideHelpers: Is a directory
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:# Import target "Halide::retrain_cost_model" for configuration "Release"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:set_property(TARGET Halide::retrain_cost_model APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:set_target_properties(Halide::retrain_cost_model PROPERTIES
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/tools/halide/retrain_cost_model"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:list(APPEND _IMPORT_CHECK_TARGETS Halide::retrain_cost_model )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:list(APPEND _IMPORT_CHECK_FILES_FOR_Halide::retrain_cost_model "${_IMPORT_PREFIX}/tools/halide/retrain_cost_model" )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:# Import target "Halide::retrain_cost_model" for configuration "Debug"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:set_property(TARGET Halide::retrain_cost_model APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:set_target_properties(Halide::retrain_cost_model PROPERTIES
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/tools/halide/retrain_cost_model"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:list(APPEND _IMPORT_CHECK_TARGETS Halide::retrain_cost_model )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:list(APPEND _IMPORT_CHECK_FILES_FOR_Halide::retrain_cost_model "${_IMPORT_PREFIX}/tools/halide/retrain_cost_model" )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:foreach(_expectedTarget Halide::Tools Halide::ImageIO Halide::RunGenMain Halide::Runtime Halide::retrain_cost_model Halide::featurization_to_sample Halide::get_host_target Halide::weightsdir_to_weightsfile)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:# Create imported target Halide::retrain_cost_model
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:add_executable(Halide::retrain_cost_model IMPORTED)
grep: packages/halide_x64-linux/share/halide: Is a directory
grep: packages/halide_x64-linux/share/halide/tools: Is a directory
packages/halide_x64-linux/share/halide/tools/autotune_loop.sh:            ${AUTOSCHED_BIN}/retrain_cost_model \
root@usr:/home/usr/work/vcpkg# find packages/halide_x64-linux/share/ | xargs grep "weightsdir_to_weightsfile"
grep: packages/halide_x64-linux/share/: Is a directory
grep: packages/halide_x64-linux/share/HalideHelpers: Is a directory
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:# Import target "Halide::weightsdir_to_weightsfile" for configuration "Release"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:set_property(TARGET Halide::weightsdir_to_weightsfile APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:set_target_properties(Halide::weightsdir_to_weightsfile PROPERTIES
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/tools/halide/weightsdir_to_weightsfile"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:list(APPEND _IMPORT_CHECK_TARGETS Halide::weightsdir_to_weightsfile )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-release.cmake:list(APPEND _IMPORT_CHECK_FILES_FOR_Halide::weightsdir_to_weightsfile "${_IMPORT_PREFIX}/tools/halide/weightsdir_to_weightsfile" )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:# Import target "Halide::weightsdir_to_weightsfile" for configuration "Debug"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:set_property(TARGET Halide::weightsdir_to_weightsfile APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:set_target_properties(Halide::weightsdir_to_weightsfile PROPERTIES
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:  IMPORTED_LOCATION_DEBUG "${_IMPORT_PREFIX}/tools/halide/weightsdir_to_weightsfile"
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:list(APPEND _IMPORT_CHECK_TARGETS Halide::weightsdir_to_weightsfile )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces-debug.cmake:list(APPEND _IMPORT_CHECK_FILES_FOR_Halide::weightsdir_to_weightsfile "${_IMPORT_PREFIX}/tools/halide/weightsdir_to_weightsfile" )
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:foreach(_expectedTarget Halide::Tools Halide::ImageIO Halide::RunGenMain Halide::Runtime Halide::retrain_cost_model Halide::featurization_to_sample Halide::get_host_target Halide::weightsdir_to_weightsfile)
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:# Create imported target Halide::weightsdir_to_weightsfile
packages/halide_x64-linux/share/HalideHelpers/Halide-Interfaces.cmake:add_executable(Halide::weightsdir_to_weightsfile IMPORTED)
grep: packages/halide_x64-linux/share/halide: Is a directory
grep: packages/halide_x64-linux/share/halide/tools: Is a directory
root@usr:/home/usr/work/vcpkg#
```
Is there anything I missed?
All tools are in _tools/halide_ folder and the cmake configurations are correct.

**Comment by JackBoosY** [comment] 2021-10-09 09:54
In windows:
- dynamic libraries -> _bin_.
- static libraries -> _lib_.
- tools -> _tools/${PORT}_

In non-Windows:
- dynamic libraries -> _lib_.
- static libraries -> _lib_.
- tools -> _tools/${PORT}_.

The module file should be placed in share/ (called by the library) or placed in tools/PORT (called by the tool).
Of course, we may need to modify the code or configuration.

**Comment by alexreinking** [comment] 2021-11-03 21:48
@JackBoosY - it looks like the Halide port is going to be updated in #20749... it would be nice to get this fixed at the same time. What is the agreed-upon resolution? Re-add `set(VCPKG_POLICY_EMPTY_PACKAGE enabled)` and set `-DHalide_INSTALL_PLUGINDIR=plugins/${PORT}`?

**Comment by jacobkahn** [comment] 2021-12-27 17:40
@JackBoosY any updates here? This is also causing https://github.com/microsoft/vcpkg/issues/22228 which makes automating things downstream with the package impossible.

**Comment by JackBoosY** [comment] 2021-12-30 16:30
I'm not sure about that.
I think we cannot effectively solve this problem before we solve `rpath`.
Any other suggestions here?

**Comment by JackBoosY** [comment] 2022-09-01 16:35
This issue should be fixed by https://github.com/microsoft/vcpkg/pull/23035. Please ping me to reopen this issue if it still bother you.

**Closed by JackBoosY** 2022-09-01 16:35 UTC
Labels: category:port-bug, requires:discussion
