### ISSUE TITLE
vcpkg install fails to download archive

### ISSUE THREAD

**Issue by JoeABrown58** [microsoft/vcpkg#11312] opened 2020-05-11 21:07 UTC
When I tried vcplg install project_lib it complained about the underscore. Are there rules about project naming somewhere?

I renamed the folder. In **vcpkg\ports\project\portfile.cmake** I included lines like
```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO My-Company/project_lib
    REF f7434249407aebca09eb6ff94bc57dedaea6111a
    SHA512 1
    HEAD_REF master
)

```
I ran **.\vcpkg install project** and got the error
```
-- Downloading https://github.com/My-Company/project_lib/archive/f7434249407aebca09eb6ff94bc57dedaea6111a.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

      Failed to download file.
      If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY environment
      variables to "https://user:password@your-proxy-ip-address:port/".
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

```
I am not aware of any proxy. Do I have to make an archive for any commit that I use? If so, is there a shortcut for the latest commit?

**Comment by NancyLi1013** [comment] 2020-05-12 10:19
Hi @JoeABrown58 
Thanks for posting this issue.
It seems that `https://github.com/My-Company/project_lib/archive/f7434249407aebca09eb6ff94bc57dedaea6111a.tar.gz` doesn't exist.
I also try to go through the URL, but I cannot have access to it.

So could you please check if the URL is normal?

**Comment by JoeABrown58** [comment] 2020-05-12 14:51
It a real REF but not a real REPO. The question was whether I have to manually create an archive or whether github will just return one with a recognized REF.

**Comment by NancyLi1013** [comment] 2020-05-13 06:06
There must be an archive in REF.
Whether the `REPO `is real or not, we must keep that the URL can be accessible.
Please refer to the function [vcpkg_from_git()](https://github.com/Microsoft/vcpkg/blob/master/scripts/cmake/vcpkg_from_github.cmake).

**Comment by JoeABrown58** [comment] 2020-05-13 12:38
How do I do that? Do I have to create an archive file in an _archive_ directory in my project and then commit that?

**Comment by NancyLi1013** [comment] 2020-05-18 10:03
Hi @JoeABrown58 
Could you please provide your URL on GitHub?

**Comment by JoeABrown58** [comment] 2020-05-19 14:31
REPO Paradigm-Electronics/pscom_lib

**Comment by NancyLi1013** [comment] 2020-05-20 01:49
Sorry, I still cannot access this. Could you provide the full URL like this` https://github.com/My-Company/project_lib/archive/f7434249407aebca09eb6ff94bc57dedaea6111a.tar.gz`?

**Comment by JoeABrown58** [comment] 2020-05-20 12:15
There is no archive. There documentation is not clear about whether I have to create one and commit it.

**Comment by NancyLi1013** [comment] 2020-05-21 10:16
Since most projects are from GitHub directly that has included archive files.
https://github.com/microsoft/vcpkg/blob/master/docs/maintainers/vcpkg_from_github.md

Your case is a bit special, sorry, I could not help you.

It might be better to try in both ways if not complex for you.

**Comment by JoeABrown58** [comment] 2020-05-22 13:23
I tried this:

```
vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO Paradigm-Electronics/pscom_lib
    REF d286407e04e5b238d6b4b75be5c12b2958062725
    SHA512 1
    HEAD_REF master
)

```
PS C:\Users\josephbrown\source\vcpkg\vcpkg> .\vcpkg install pscom

It produced this:

```
Computing installation plan...
The following packages will be built and installed:
    pscom[core]:x64-windows-static
Starting package 1/1: pscom:x64-windows-static
Building package pscom[core]:x64-windows-static...
-- Downloading https://github.com/Paradigm-Electronics/pscom_lib/archive/d286407e04e5b238d6b4b75be5c12b2958062725.tar.gz...
-- Downloading https://github.com/Paradigm-Electronics/pscom_lib/archive/d286407e04e5b238d6b4b75be5c12b2958062725.tar.gz... Failed. Status: 22;"HTTP response code said error"
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:175 (message):

```
      Failed to download file.

Question 1: Is there anything wrong with the configuration?
Question 2: Do I have to generate a tar.gz file?

**Comment by NancyLi1013** [comment] 2020-05-29 06:31
Sorry for the late reply.
This link `https://github.com/Paradigm-Electronics/pscom_lib` still cannot be accessed now.
I think the problem is here. It seems that it is not related with tar.gz file currently.
Your `REPO `seems to be not correct.

**Comment by JoeABrown58** [comment] 2020-05-29 12:27
When I entered the link in my browser the repository appears. There is a 'lock' symbol to the left of the name and 'Private' to the right. Do I have to include a user name and password in my script?

**Comment by NancyLi1013** [comment] 2020-06-01 08:15
Could you please help provide the screenshot for the branch on the GitHub if possible?
Since this function `vcpkg_from_github()` is only supported the public one. 

Please make sure the link that can be accessible by others.

**Comment by JoeABrown58** [comment] 2020-06-01 12:07
Hi Nancy:


I have attached a snapshot of the web page.


--Joe

________________________________

**Comment by NancyLi1013** [comment] 2020-06-02 05:47
It seems there is no any attachment here.
Sorry, I didn't see it. Could you please check it again?

**Comment by JoeABrown58** [comment] 2020-06-02 12:58
Here is a shot of the page.


--Joe


________________________________

**Comment by JoeABrown58** [comment] 2020-06-02 13:10
In case the email reply did not work..

![Screenshot from 2020-06-02 08-57-16](https://user-images.githubusercontent.com/52177764/83523842-bec4f680-a4b0-11ea-9a3e-997a18561cf3.png)

**Comment by NancyLi1013** [comment] 2020-06-03 07:48
@JoeABrown58 

Thanks for your above info.
There seems to be nothing exception on your URL except for the private one.

I'm sorry for this. But the function`vcpkg_from_github()` only supports for public website for now.

So you cannot use it.

**Comment by NancyLi1013** [comment] 2020-07-07 08:29
I'm closing this issue for now since it seems there is no any support that can help you.

**Closed by NancyLi1013** 2020-07-07 08:29 UTC
Labels: category:question
