### ISSUE TITLE
[opencv] update to 4.8.0

### ISSUE THREAD

**Issue by naari3** [microsoft/vcpkg#33047] opened 2023-08-08 19:47 UTC
### Library name

OpenCV

### New version number

4.8.0

### Other information that may be useful (release notes, etc...)

Released on 2022-12-29. [Release notes](https://github.com/opencv/opencv/wiki/ChangeLog#version480)

**Comment by LilyWangLL** [comment] 2023-08-09 01:56
Closed as duplicate of #32463.

**Closed by LilyWangLL** 2023-08-09 01:56 UTC
Labels: category:port-update
