### ISSUE TITLE
How do I add vcpkg to Visual Studio 2019

### ISSUE THREAD

**Issue by Ou7law007** [microsoft/vcpkg#14729] opened 2020-11-23 17:20 UTC
Hey,
I changed "use vcpkg" to no and the whole vcpkg option is gone from my project! It's still showing in other projects and also in newly created projects, but once its disabled, it's gone.
Deleting and reinstalling vcpkg (+ all the libraries that were installed) did not help. The only way is to make a new project and copy over all the source files to the new project (.cpp .h...) 
Is that a bug? Isn't there a way to re-enable it after it was disabled? And also even though it's "disabled", the options in side of it are all active that is the project still links normally to where libraries are installed and removing the vcpkg folder would cause errors.
![image](https://user-images.githubusercontent.com/64309267/99992927-45e78d00-2db7-11eb-9a84-a665b363563c.png)

![image](https://user-images.githubusercontent.com/64309267/99993439-f81f5480-2db7-11eb-9f8f-b7d291c6da5b.png)

Thanks for taking the time

**Comment by PhoebeHui** [comment] 2020-11-24 02:17
@Ou7law007, this is a VS bug, and already fixed in VS 16.8.2, could you upgrade vs and try again?

**Comment by Ou7law007** [comment] 2020-11-24 10:41
I am using latest version.

![image](https://user-images.githubusercontent.com/64309267/100083514-e090ac00-2e49-11eb-8753-2adfc7007ce0.png)

**Comment by ZhilkinSerg** [comment] 2020-11-25 07:03
I can confirm the issue is there on latest VS 2019 (16.8.2). I believe it has the same root cause as #14735 - #13755 and reverting to e126e3e fixes the issue.

**Comment by PhoebeHui** [comment] 2020-11-26 06:21
@ZhilkinSerg, thanks for the comments!

I forget to pull the latest source from master, and doesn't repro on 16.8.2 in another machine, it's my fault, sorry for the mistakes.

I will take a look .

**Comment by PhoebeHui** [comment] 2020-11-26 08:30
@Ou7law007, I have summited PR #14797 to fix this issue, could you help to test if it works for you?

**Comment by ZhilkinSerg** [comment] 2020-11-26 12:40
> 
> 
> I re-cloned the repository of vcpkg and installed it normally and tested again. For me, the vcpkg option still disappeared after setting it to 'No'. Did you add a re-enable option that I'm missing?

You need to apply changes from #14797 to your local copy first.

**Comment by Ou7law007** [comment] 2020-11-26 13:31
You're right, it works for me now. I'm sorry this was literally my second post github, guess I don't know how things work yet.

**Closed** 2020-11-26 13:35 UTC
Labels: category:vcpkg-bug
