### ISSUE TITLE
MSMPI doesn't support static lib/MD

### ISSUE THREAD

**Issue by bjornpiltz** [microsoft/vcpkg#2059] opened 2017-10-26 10:29 UTC
It fails with:
```
-- Performing post-build validation
Expected Release,Dynamic crt linkage, but the following libs had invalid crt linkage:

    D:/Dev/playground/vcpkg/packages/msmpi_rmak/lib/msmpifec.lib: Release,Static
    D:/Dev/playground/vcpkg/packages/msmpi_rmak/lib/msmpifmc.lib: Release,Static
```

**Comment by ras0219-msft** [comment] 2017-10-28 08:41
Thanks for reporting this issue!

I'm not able to reproduce the problem; can you post the contents of the `rmak` triplet and ensure you're using the latest version of `vcpkg` and `msmpi`?

**Comment by bjornpiltz** [comment] 2017-11-02 09:27
Yes, this is still an issue at tip. You can reproduce it with the following triplet:
```cmake
set(VCPKG_TARGET_ARCHITECTURE x64)

# Always use the dynamic CRT.
set(VCPKG_CRT_LINKAGE dynamic)

# Prefer to link statically.
set(VCPKG_LIBRARY_LINKAGE static)
```

**Comment by cenit** [comment] 2018-02-24 16:41
@ras0219-msft I have the same problem, exactly the same triplet and msmpi does not install.
Looks like the prebuilt distributed libraries are not enough to cover all our combinations (but it would be awesome to have a static lib with dynamic linking to CRT)

**Comment by NancyLi1013** [comment] 2019-06-20 02:13
Hi @bjornpiltz, @cenit, the PR has been merged to the master. This issue should be fixed now.

**Closed by NancyLi1013** 2019-06-20 02:13 UTC
Labels: port bug
