### ISSUE TITLE
bug occurs when install jasper:

### ISSUE THREAD

**Issue by dongfangZh** [microsoft/vcpkg#41312] opened 2024-10-03 10:31 UTC
**Environment**
- OS: windows10  22H2
- Compiler: Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe

**Describe the bug**
.\vcpkg install jasper:x64-windows
Computing installation plan...
warning: vcpkg appears to be in a Visual Studio prompt targeting x86 but installing for x64-windows. Consider using --triplet x86-windows or --triplet x86-uwp.
The following packages will be built and installed:
    jasper[core,default-features,opengl]:x64-windows@4.2.1
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
Restored 0 package(s) from C:\Users\Viking\AppData\Local\vcpkg\archives in 1.87 ms. Use --debug to see more details.
Installing 1/1 jasper[core,default-features,opengl]:x64-windows@4.2.1...
Building jasper[core,default-features,opengl]:x64-windows@4.2.1...
-- Downloading https://github.com/jasper-software/jasper/archive/version-4.2.1.tar.gz -> jasper-software-jasper-version-4-2da4b72e.2.1.tar.gz...
-- Extracting source D:/vcpkg/downloads/jasper-software-jasper-version-4-2da4b72e.2.1.tar.gz
-- Applying patch no_stdc_check.patch
-- Applying patch fix-library-name.patch
-- Using source at D:/vcpkg/buildtrees/jasper/src/sion-4.2.1-8404b64315.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: D:/vcpkg/downloads/tools/cmake-3.30.1-windows/cmake-3.30.1-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j9
    Working Directory: D:/vcpkg/buildtrees/jasper/x64-windows-dbg
    See logs for more information:
      D:\vcpkg\buildtrees\jasper\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/jasper/portfile.cmake:38 (vcpkg_cmake_install)
  scripts/ports.cmake:192 (include)

**Failure logs**
Change Dir: 'D:/vcpkg/buildtrees/jasper/x64-windows-dbg'

Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v -v -j9 install
[1/55] C:\PROGRA~2\MICROS~3\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe   -DJAS_BUILDING_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -Dlibjasper_EXPORTS -ID:\vcpkg\buildtrees\jasper\x64-windows-dbg\src\libjasper\include -ID:\vcpkg\buildtrees\jasper\src\sion-4.2.1-8404b64315.clean\src\libjasper\include -external:ID:\vcpkg\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /utf-8 /MP /D_CRT_DECLARE_NONSTDC_NAMES /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c11 -MDd /wd4244 /wd4090 /wd4018 /wd4996 /wd4267 /showIncludes /Fosrc\libjasper\CMakeFiles\libjasper.dir\base\jas_iccdata.c.obj /Fdsrc\libjasper\CMakeFiles\libjasper.dir\ /FS -c D:\vcpkg\buildtrees\jasper\src\sion-4.2.1-8404b64315.clean\src\libjasper\base\jas_iccdata.c
[2/55] C:\PROGRA~2\MICROS~3\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe   -DJAS_BUILDING_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -Dlibjasper_EXPORTS -ID:\vcpkg\buildtrees\jasper\x64-windows-dbg\src\libjasper\include -ID:\vcpkg\buildtrees\jasper\src\sion-4.2.1-8404b64315.clean\src\libjasper\include -external:ID:\vcpkg\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /utf-8 /MP /D_CRT_DECLARE_NONSTDC_NAMES /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c11 -MDd /wd4244 /wd4090 /wd4018 /wd4996 /wd4267 /showIncludes /Fosrc\libjasper\CMakeFiles\libjasper.dir\base\jas_malloc.c.obj /Fdsrc\libjasper\CMakeFiles\libjasper.dir\ /FS -c D:\vcpkg\buildtrees\jasper\src\sion-4.2.1-8404b64315.clean\src\libjasper\base\jas_malloc.c
FAILED: src/libjasper/CMakeFiles/libjasper.dir/base/jas_malloc.c.obj 
C:\PROGRA~2\MICROS~3\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe   -DJAS_BUILDING_DLL -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -Dlibjasper_EXPORTS -ID:\vcpkg\buildtrees\jasper\x64-windows-dbg\src\libjasper\include -ID:\vcpkg\buildtrees\jasper\src\sion-4.2.1-8404b64315.clean\src\libjasper\include -external:ID:\vcpkg\installed\x64-windows\include -external:W0 /nologo /DWIN32 /D_WINDOWS /utf-8 /MP /D_CRT_DECLARE_NONSTDC_NAMES /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c11 -MDd /wd4244 /wd4090 /wd4018 /wd4996 /wd4267 /showIncludes /Fosrc\libjasper\CMakeFiles\libjasper.dir\base\jas_malloc.c.obj /Fdsrc\libjasper\CMakeFiles\libjasper.dir\ /FS -c D:\vcpkg\buildtrees\jasper\src\sion-4.2.1-8404b64315.clean\src\libjasper\base\jas_malloc.c
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\corecrt_search.h(182): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\stdlib.h(78): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\stdlib.h(1286): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\math.h(43): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\math.h(960): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\process.h(229): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\ctype.h(223): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\corecrt_memory.h(76): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\corecrt_wstring.h(566): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\ucrt\string.h(522): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um\winbase.h(8946): warning C5105: macro expansion producing 'defined' has undefined behavior
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um\oaidl.h(473): warning C5103: pasting '/' and '/' does not result in a valid preprocessing token
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\shared\wtypes.h(745): note: in expansion of macro '_VARIANT_BOOL'
C:\Program Files (x86)\Windows Kits\10\include\10.0.14393.0\um\oaidl.h(473): error C2059: syntax error: '/'

**Additional context**

**Comment by FrankXie05** [comment] 2024-10-08 08:45
Duplicate of https://github.com/microsoft/vcpkg/issues/41348

**Closed by FrankXie05** 2024-10-08 08:45 UTC
Labels: category:port-bug
