### ISSUE TITLE
[tensorflow] Build error on x64-windows-static

### ISSUE THREAD

**Issue by jmussemann** [microsoft/vcpkg#36224] opened 2024-01-17 22:02 UTC
Copy issue body from D:/code/git/Sandboxes/tenser-flow-sandbox/build-RWD/vcpkg_installed/vcpkg/issue_body.md

**Comment by jmussemann** [comment] 2024-01-17 22:03
Package: tensorflow:x64-windows-static -> 2.10.0

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.29.30139.0
- vcpkg-tool version: 2023-11-16-4c1df40a3c5c5e18de299a99e9accb03c2a82e1e
  vcpkg-scripts version: 38d1652f1 2024-01-17 (2 hours ago)

**To Reproduce**

`vcpkg install `
**Failure logs**

```
-- Using cached msys2-bash-5.2.021-1-x86_64.pkg.tar.zst.
-- Using cached msys2-unzip-6.0-2-x86_64.pkg.tar.xz.
-- Using cached msys2-patch-2.7.6-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-python-numpy-1.26.2-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-python-numpy-1.26.2-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-python-numpy-1.26.2-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-python-numpy-1.26.2-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-python-numpy-1.26.2-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-python-numpy-1.26.2-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-python-numpy-1.26.2-1-any.pkg.tar.zst...
-- Using cached msys2-file-5.45-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.9-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-openblas-0.3.25-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-openblas-0.3.25-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-openblas-0.3.25-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-openblas-0.3.25-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-openblas-0.3.25-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-openblas-0.3.25-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-openblas-0.3.25-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-python-3.11.6-2-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-python-3.11.6-2-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-python-3.11.6-2-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-python-3.11.6-2-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-python-3.11.6-2-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-python-3.11.6-2-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-python-3.11.6-2-any.pkg.tar.zst...
-- Using cached msys2-liblzma-5.4.5-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.5-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.007-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-libgfortran-13.2.0-2-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-libgfortran-13.2.0-2-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-libgfortran-13.2.0-2-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-libgfortran-13.2.0-2-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-libgfortran-13.2.0-2-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-libgfortran-13.2.0-2-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-gcc-libgfortran-13.2.0-2-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-libs-13.2.0-2-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gcc-libs-13.2.0-2-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-libs-13.2.0-2-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-libs-13.2.0-2-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-libs-13.2.0-2-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-gcc-libs-13.2.0-2-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-gcc-libs-13.2.0-2-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-libwinpthread-git-11.0.0.r404.g3a137bd87-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-libwinpthread-git-11.0.0.r404.g3a137bd87-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-libwinpthread-git-11.0.0.r404.g3a137bd87-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-libwinpthread-git-11.0.0.r404.g3a137bd87-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-libwinpthread-git-11.0.0.r404.g3a137bd87-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-libwinpthread-git-11.0.0.r404.g3a137bd87-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-libwinpthread-git-11.0.0.r404.g3a137bd87-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-bzip2-1.0.8-3-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-bzip2-1.0.8-3-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-bzip2-1.0.8-3-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-bzip2-1.0.8-3-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-bzip2-1.0.8-3-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-bzip2-1.0.8-3-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-bzip2-1.0.8-3-any.pkg.tar.zst...
-- Using cached msys2-mingw-w64-x86_64-expat-2.5.0-1-any.pkg.tar.zst.
-- Using cached msys2-mingw-w64-x86_64-libffi-3.4.4-1-any.pkg.tar.zst.
-- Using cached msys2-mingw-w64-x86_64-mpdecimal-2.5.1-1-any.pkg.tar.zst.
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-ncurses-6.4.20230708-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-ncurses-6.4.20230708-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-ncurses-6.4.20230708-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-ncurses-6.4.20230708-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-ncurses-6.4.20230708-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-ncurses-6.4.20230708-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-ncurses-6.4.20230708-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-openssl-3.2.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-openssl-3.2.0-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-openssl-3.2.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-openssl-3.2.0-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-openssl-3.2.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-openssl-3.2.0-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-openssl-3.2.0-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-sqlite3-3.44.0-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-sqlite3-3.44.0-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-sqlite3-3.44.0-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-sqlite3-3.44.0-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-sqlite3-3.44.0-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-sqlite3-3.44.0-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-sqlite3-3.44.0-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-tcl-8.6.12-2-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-tcl-8.6.12-2-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-tcl-8.6.12-2-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-tcl-8.6.12-2-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-tcl-8.6.12-2-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-tcl-8.6.12-2-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-tcl-8.6.12-2-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-tk-8.6.12-2-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-tk-8.6.12-2-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-tk-8.6.12-2-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-tk-8.6.12-2-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-tk-8.6.12-2-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-tk-8.6.12-2-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-tk-8.6.12-2-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-xz-5.4.5-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-xz-5.4.5-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-xz-5.4.5-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-xz-5.4.5-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-xz-5.4.5-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-xz-5.4.5-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-xz-5.4.5-1-any.pkg.tar.zst...
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-zlib-1.3-1-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-zlib-1.3-1-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-zlib-1.3-1-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-zlib-1.3-1-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-zlib-1.3-1-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-zlib-1.3-1-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-zlib-1.3-1-any.pkg.tar.zst...
-- Using cached msys2-ncurses-6.4-2-x86_64.pkg.tar.zst.
-- Using cached msys2-mingw-w64-x86_64-libsystre-1.0.1-4-any.pkg.tar.xz.
-- Using cached msys2-mingw-w64-x86_64-readline-8.2.001-6-any.pkg.tar.zst.
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-gettext-0.22.4-3-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-gettext-0.22.4-3-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-gettext-0.22.4-3-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-gettext-0.22.4-3-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-gettext-0.22.4-3-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-gettext-0.22.4-3-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-gettext-0.22.4-3-any.pkg.tar.zst...
-- Using cached msys2-mingw-w64-x86_64-libtre-git-r128.6fb7206-2-any.pkg.tar.xz.
-- Downloading https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-termcap-1.3.1-7-any.pkg.tar.zst;https://repo.msys2.org/mingw/mingw64/mingw-w64-x86_64-termcap-1.3.1-7-any.pkg.tar.zst;https://mirror.yandex.ru/mirrors/msys2/mingw/mingw64/mingw-w64-x86_64-termcap-1.3.1-7-any.pkg.tar.zst;https://mirrors.tuna.tsinghua.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-termcap-1.3.1-7-any.pkg.tar.zst;https://mirrors.ustc.edu.cn/msys2/mingw/mingw64/mingw-w64-x86_64-termcap-1.3.1-7-any.pkg.tar.zst;https://mirror.selfnet.de/msys2/mingw/mingw64/mingw-w64-x86_64-termcap-1.3.1-7-any.pkg.tar.zst -> msys2-mingw-w64-x86_64-termcap-1.3.1-7-any.pkg.tar.zst...
-- Using cached msys2-mingw-w64-x86_64-libiconv-1.17-3-any.pkg.tar.zst.
-- Using msys root at D:/dev/vcpkg/downloads/tools/msys2/c19a26c7173f8e13
-- Using cached tensorflow-tensorflow-v2.10.0.tar.gz.
-- Extracting source D:/dev/vcpkg/downloads/tensorflow-tensorflow-v2.10.0.tar.gz
-- Applying patch D:/code/git/Sandboxes/tenser-flow-sandbox/build-RWD/vcpkg_installed/x64-windows-static/share/tensorflow-common/fix-build-error.patch
-- Applying patch D:/code/git/Sandboxes/tenser-flow-sandbox/build-RWD/vcpkg_installed/x64-windows-static/share/tensorflow-common/change-macros-for-static-lib.patch
-- Applying patch D:/code/git/Sandboxes/tenser-flow-sandbox/build-RWD/vcpkg_installed/x64-windows-static/share/tensorflow-common/fix-windows-build.patch
-- Using source at D:/code/git/Sandboxes/tenser-flow-sandbox/vcpkg/buildtrees/tensorflow/src/v2.10.0-4baaf97d01.clean
-- Configuring TensorFlow (dbg)
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: D:/dev/vcpkg/downloads/tools/msys2/c19a26c7173f8e13/mingw64/bin/python3.exe D:/code/git/Sandboxes/tenser-flow-sandbox/vcpkg/buildtrees/tensorflow/x64-windows-static-dbg/configure.py --workspace D:/code/git/Sandboxes/tenser-flow-sandbox/vcpkg/buildtrees/tensorflow/x64-windows-static-dbg
    Working Directory: D:/code/git/Sandboxes/tenser-flow-sandbox/vcpkg/buildtrees/tensorflow/x64-windows-static-dbg
    Error code: 1
    See logs for more information:
      D:\code\git\Sandboxes\tenser-flow-sandbox\vcpkg\buildtrees\tensorflow\config-x64-windows-static-dbg-out.log

Call Stack (most recent call first):
  D:/code/git/Sandboxes/tenser-flow-sandbox/build-RWD/vcpkg_installed/x64-windows-static/share/tensorflow-common/tensorflow-common.cmake:187 (vcpkg_execute_required_process)
  buildtrees/versioning_/versions/tensorflow/87372cfe6baffa73e3dd20d50fda320ff2f1f023/portfile.cmake:5 (include)
  scripts/ports.cmake:170 (include)



```

<details><summary>D:\code\git\Sandboxes\tenser-flow-sandbox\vcpkg\buildtrees\tensorflow\config-x64-windows-static-dbg-out.log</summary>

```
Cannot find bazel. Please install bazel/bazelisk.
```

</details>

**Additional context**

<details><summary>vcpkg.json</summary>

```
{
  "name": "vcpkg-libaries",
  "version": "1.0.0",
  "$builtin-baseline_comment": "TAG: 2024.01.12",
  "builtin-baseline": "53bef8994c541b6561884a8395ea35715ece75db",
  "dependencies": [
    "boost-system",
    "boost-date-time",
    "boost-filesystem",
    "tensorflow"
  ]
}

```

</details>

**Comment by JonLiu1993** [comment] 2024-01-18 03:02
Duplicate of https://github.com/microsoft/vcpkg/issues/27474.

**Closed by JonLiu1993** 2024-01-18 03:02 UTC
Labels: category:port-bug
