### ISSUE TITLE
[sdl2] alias targets break multiple `find_package` calls on CMake < 3.18

### ISSUE THREAD

**Issue by alexreinking** [microsoft/vcpkg#19686] opened 2021-08-21 17:03 UTC
When calling `find_package(SDL2)` from multiple subdirectories on CMake versions below 3.18, the following snippet runs:

https://github.com/microsoft/vcpkg/blob/025e564979cc01d0fbc5c920aa8a36635efb01bb/ports/sdl2/0004-sdl2-alias-on-static-build.patch#L1-L17

The existence of this alias triggers a failure in `SDL2Targets.cmake` when it attempts to create `SDL2::SDL2-static`. This should be fixed by amending this patch to check early on in `SDL2Config.cmake` if the version is less than 3.18 and `SDL2::SDL2` already exists. When this is the case, a `FATAL_ERROR` should result that explains the issue and encourages users to upgrade CMake.

**Comment by NancyLi1013** [comment] 2021-08-23 08:56
Hi @alexreinking 

Thanks for posting this issue.

@RT222 
Could you please help confirm if the patch is needed here? Seems the changes in this patch cannot be merged to upstream.

**Comment by RT222** [comment] 2021-09-18 23:51
Sorry about the late answer, I must have missed the notification. On dynamic linkage the sdl2 cmake file create the SDL2::SDL2 target, but on static linkage it create the SDL2::SDL2-static target instead. The problem is that libraries depending on the sdl2 (sdl2-ttf, sdl2-image, sdl2-net...) will only look for the former target, even on static linkage, and so will fail to build in this case. That's what this patch fixes.

**Comment by cjwijtmans** [comment] 2021-10-05 17:02
so if I want to build SDL statically I have to use `SDL2::SDL2-static`? Which breaks on other platforms non `vcpkg` or is this upstream behaviour? If i want to build statically on `vcpkg` I use the -static triplet.

**Comment by dg0yt** [comment] 2021-10-05 18:10
> if I want to build SDL statically I have to use `SDL2::SDL2-static`?

@cjwijtmans The discussion is about using SDL2, not building. Some packages offer to build static and dynamic at the same time. That's why they offer different targets. In vcpkg, this property isn't used, and often packages are patched to offer a single target for uniform usage.

**Comment by cjwijtmans** [comment] 2021-10-05 18:14
> @cjwijtmans The discussion is about using SDL2,


You can't be serious. If I don't build my project with SDL2 how can I "use" it? Do not ever reply to me again.

**Comment by dg0yt** [comment] 2021-10-05 19:12
> > @cjwijtmans The discussion is about using SDL2,
> 
> You can't be serious. If I don't build my project with SDL2 how can I "use" it? Do not ever reply to me again.

Slow, please. Building *your* project *with* SDL2 is *using* SDL2, in contrast to *building* SDL2 itself.

FTR this issue is about `find_package` breaking on multiple calls. It is not clear to me if you are actually suffering from this issue, or if your question is about another topic.

**Comment by dg0yt** [comment] 2021-10-06 06:53
Please test the change from #20542.

**Closed** 2021-10-06 18:12 UTC
Labels: category:port-bug
