### ISSUE TITLE
[upb] Build error

### ISSUE THREAD

**Issue by davidyancich** [microsoft/vcpkg#32424] opened 2023-07-06 13:56 UTC
Copy issue body from C:/source/vcpkg/installed/vcpkg/issue_body.md
[issue_body.md](https://github.com/microsoft/vcpkg/files/11968920/issue_body.md)

**Comment by davidyancich** [comment] 2023-07-06 13:57
I have tried solutions from previous bug reports, but nothing is working.

**Comment by JonLiu1993** [comment] 2023-07-07 08:48
@davidyancich, Thanks for posting this issue, This issue is duplicate of https://github.com/microsoft/vcpkg/issues/31620, Please track this issue in another issue.

**Closed by JonLiu1993** 2023-07-07 08:48 UTC
Labels: category:question
