### ISSUE TITLE
[sundials] invalid command: x-download

### ISSUE THREAD

**Issue by SKNo** [microsoft/vcpkg#18353] opened 2021-06-09 12:42 UTC
Hi 
I was trying to install sundials and got following error message.  Before submitting a bug report just wanted to know if this is related to my setup or something else  (I tried on two computers same error)

**Environment**
```
- OS: [ Windows]
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30037 for x64

```
**Error Message**
```
E:\Lib\vcpkg>vcpkg install sundials --triplet x64-windows
Computing installation plan...
The following packages will be built and installed:
    sundials[core]:x64-windows -> 5.7.0#1
Detecting compiler hash for triplet x64-windows...
Could not locate cached archive: C:\Users\ch6535\AppData\Local\vcpkg\archives\df\df61b63fc4d86a443bbedaa77be748372df4bfe
c.zip
Starting package 1/1: sundials:x64-windows
Building package sundials[core]:x64-windows...
-- Downloading https://github.com/LLNL/sundials/archive/73c280cd55ca2b42019c8a9aa54af10e41e27b9d.tar.gz -> LLNL-sundials
-73c280cd55ca2b42019c8a9aa54af10e41e27b9d.tar.gz...
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' = off
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using vcpkg-root: E:\Lib\vcpkg
[DEBUG] Using installed-root: E:\Lib\vcpkg\installed
[DEBUG] BuiltinRegistry initialized with: ""
[DEBUG] Using buildtrees-root: E:\Lib\vcpkg\buildtrees
[DEBUG] Using downloads-root: E:\Lib\vcpkg\downloads
[DEBUG] Using packages-root: E:\Lib\vcpkg\packages
[DEBUG] Using scripts-root: E:\Lib\vcpkg\scripts
[DEBUG] Using ports-root: E:\Lib\vcpkg\ports
[DEBUG] Using versions-root: E:\Lib\vcpkg\versions
invalid command: x-download
Commands:
  vcpkg search [pat]              Search for packages available to be built
  vcpkg install <pkg>...          Install a package
  vcpkg remove <pkg>...           Uninstall a package
  vcpkg remove --outdated         Uninstall all out-of-date packages
  vcpkg list                      List installed packages
  vcpkg update                    Display list of packages for updating
  vcpkg upgrade                   Rebuild all outdated packages
  vcpkg x-history <pkg>           (Experimental) Shows the history of CONTROL versions of a package
  vcpkg hash <file> [alg]         Hash a file by specific algorithm, default SHA512
  vcpkg help topics               Display the list of help topics
  vcpkg help <topic>              Display help for a specific topic

  vcpkg integrate install         Make installed packages available user-wide. Requires admin
                                  privileges on first use
  vcpkg integrate remove          Remove user-wide integration
  vcpkg integrate project         Generate a referencing nuget package for individual VS project use
  vcpkg integrate powershell      Enable PowerShell tab-completion

  vcpkg export <pkg>... [opt]...  Exports a package
  vcpkg edit <pkg>                Open up a port for editing (uses %EDITOR%, default 'code')
  vcpkg create <pkg> <url> [archivename]
                                  Create a new package
  vcpkg owns <pat>                Search for files in installed packages
  vcpkg depend-info <pkg>...      Display a list of dependencies for packages
  vcpkg env                       Creates a clean shell environment for development or compiling
  vcpkg version                   Display version information
  vcpkg contact                   Display contact information to send feedback

Options:
  --triplet=<t>                   Specify the target architecture triplet. See 'vcpkg help triplet'
                                  (default: %VCPKG_DEFAULT_TRIPLET%)
  --host-triplet=<t>              Specify the host architecture triplet. See 'vcpkg help triplet'
                                  (default: %VCPKG_DEFAULT_HOST_TRIPLET%)
  --overlay-ports=<path>          Specify directories to be used when searching for ports
                                  (also: %VCPKG_OVERLAY_PORTS%)
  --overlay-triplets=<path>       Specify directories containing triplets files
                                  (also: %VCPKG_OVERLAY_TRIPLETS%)
  --binarysource=<path>           Add sources for binary caching. See 'vcpkg help binarycaching'
  --downloads-root=<path>         Specify the downloads root directory
                                  (default: %VCPKG_DOWNLOADS%)
  --vcpkg-root=<path>             Specify the vcpkg root directory
                                  (default: %VCPKG_ROOT%)
  --x-buildtrees-root=<path>      (Experimental) Specify the buildtrees root directory
  --x-install-root=<path>         (Experimental) Specify the install root directory
  --x-packages-root=<path>        (Experimental) Specify the packages root directory
  --x-scripts-root=<path>         (Experimental) Specify the scripts root directory
  --x-builtin-ports-root=<path>   (Experimental) Specify the packages root directory
  --x-builtin-registry-versions-dir=<path>
                                  (Experimental) Specify the versions root directory
  --x-json                        (Experimental) Request JSON output

  @response_file                  Specify a response file to provide additional parameters

For more help (including examples) see the accompanying README.md and docs folder.
[DEBUG] C:\A\1\70\s\src\vcpkg.cpp(46)
[DEBUG] Exiting after 53776 us (53553 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:226 (message):

      Failed to download file.
      If you use a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.

      3. You proxy's remote server is out of service.

      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)

      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_from_github.cmake:147 (vcpkg_download_distfile)
  ports/sundials/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:139 (include)


Error: Building package sundials:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: sundials:x64-windows
  Vcpkg version: 2021-01-13-d67989bce1043b98092ac45996a8230a059a2d7e

Additionally, attach any relevant sections from the log files above.`
```

**Comment by autoantwort** [comment] 2021-06-09 13:35
Please update your vcpkg version with `git pull` and `./bootstrap-vcpkg.bat` and try again

**Comment by SKNo** [comment] 2021-06-09 13:46
Hi 
@autoantwort  Ah no coffee this morning --- worked like a charm .. thank you 
@autoantwort  another question : in the situations like this , should i close the issu myself or someone else (I mean project  custodians) ?

**Comment by autoantwort** [comment] 2021-06-09 13:51
I think you can close the issue yourself because the problem is solved/the question is answered.

**Closed** 2021-06-09 13:54 UTC
