### ISSUE TITLE
[ceres ] update to 2.2.0

### ISSUE THREAD

**Issue by wystephen** [microsoft/vcpkg#38310] opened 2024-04-22 04:21 UTC
### Library name

ceres 

### New version number

2.2.0

### Other information that may be useful (release notes, etc...)

I can see some issues with this library, but the latest version of ceres-solver in vcpkg.io is still 2.1.0.

**Comment by JonLiu1993** [comment] 2024-04-24 06:13
Duplicate of #34483, fixing by PR #35021.

**Closed by JonLiu1993** 2024-04-24 06:13 UTC
Labels: category:port-update
