### ISSUE TITLE
[zlib] Build error

### ISSUE THREAD

**Issue by Ares3173** [microsoft/vcpkg#29308] opened 2023-01-31 01:38 UTC
Package: zlib[core]:x86-windows -> 1.2.13

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.32.31332.0
-    vcpkg-tool version: 2023-01-24-8a88d63f241d391772fbde69af9cab96c3c64c75
    vcpkg-scripts version: b4f29c544 2023-01-30 (17 minutes ago)

**To Reproduce**

`vcpkg install cpr`

**Failure logs**

```
-- Downloading https://github.com/madler/zlib/archive/v1.2.13.tar.gz -> madler-zlib-v1.2.13.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
Downloading https://github.com/madler/zlib/archive/v1.2.13.tar.gz
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/madler/zlib/archive/v1.2.13.tar.gz
File: C:\dev\vcpkg\downloads\madler-zlib-v1.2.13.tar.gz.39924.part
Expected hash: 44b834fbfb50cca229209b8dbe1f96b258f19a49f5df23b80970b716371d856a4adf525edb4c6e0e645b180ea949cb90f5365a1d896160f297f56794dd888659
Actual hash: b3ee66e1670fcdaa063e42cdbc906b5ff320ef50cc7e0c2036e8cd92f94b7837be9b126d5b9bc9634f6576a971563d60ba6d87dacc0f33f24f0e75d85de8fc36
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(956): 
[DEBUG] Time in subprocesses: 0 us
[DEBUG] Time in parsing JSON: 3 us
[DEBUG] Time in JSON reader: 0 us
[DEBUG] Time in filesystem: 460 us
[DEBUG] Time in loading ports: 0 us
[DEBUG] Exiting after 1.305 s (1289483 us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you use a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. You are using Fiddler. Currently a bug (https://github.com/microsoft/vcpkg/issues/17752)
         will set HTTPS_PROXY to `https://fiddler_address:port` which lead to problem 1 above.
         Workaround is open Windows 10 Settings App, and search for Proxy Configuration page,
         Change `http=address:port;https=address:port` to `address`, and fill the port number.
      
      3. Your proxy's remote server is out of service.
      
      In future vcpkg releases, if you are using Windows, you no longer need to set
      HTTP(S)_PROXY environment variables. Vcpkg will simply apply Windows IE Proxy
      Settings set by your proxy software. See (https://github.com/microsoft/vcpkg-tool/pull/49)
      and (https://github.com/microsoft/vcpkg-tool/pull/77)
      
      Otherwise, please submit an issue at https://github.com/Microsoft/vcpkg/issues

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:273 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/zlib/portfile.cmake:2 (vcpkg_from_github)
  scripts/ports.cmake:147 (include)



```

**Additional context**
I have already tried a fresh reinstall of vcpkg by deleting the folder and doing git clone https://github.com/Microsoft/vcpkg.git

**Comment by BillyONeal** [comment] 2023-01-31 03:59
Duplicate of https://github.com/microsoft/vcpkg/issues/29288

**Closed by BillyONeal** 2023-01-31 03:59 UTC
Labels: category:port-bug
