### ISSUE TITLE
GL3W Build_failed

### ISSUE THREAD

**Issue by Elekhyr** [Microsoft/vcpkg#3438] opened 2018-05-06 10:32 UTC
Hi, i'm trying to install gl3w 
  Package: gl3w:x64-windows
  Vcpkg version: 0.0.110-2018-04-30-5288e9e7029aa6b9b491bc2197b87a09778825b4

but i've got the following error : 
File does not have expected hash:
          File path: [{path_to_vcpkg}/vcpkg/downloads/temp/glcorearb-2018-02-27.h ]
      Expected hash: [ 02c3672606e6360f2e1e8335fe581bc2d2b3d518b0f24b0c327006a70de07261dace4b53b13e93029a8eb2af43bcba904c4392f2c35ac512c7f278534ef8eb5d ]
        Actual hash: [ dfb4c54e7a8b0f2fd5d1e2f41e9d49057765b52e17989c115ec92d673a9d84732f9b990babdd3aab624eb4f613b88c2b02aced46ec99c5341836133bcf22fdab ]

  The file may have been corrupted in transit.  This can be caused by
  proxies.  If you use a proxy, please set the HTTPS_PROXY and HTTP_PROXY
  environment variables to
  "https://user:password@your-proxy-ip-address:port/".

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:162 (test_hash)
  ports/gl3w/portfile.cmake:13 (vcpkg_download_distfile)
  scripts/ports.cmake:72 (include)

**Comment by YukinoHayakawa** [comment] 2018-05-29 06:33
I can confirm this and the hash of source has changed.

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:87 (message):

  File does not have expected hash:
          File path: [ .../vcpkg/downloads/temp/glcorearb-2018-02-27.h ]
      Expected hash: [ 02c3672606e6360f2e1e8335fe581bc2d2b3d518b0f24b0c327006a70de07261dace4b53b13e93029a8eb2af43bcba904c4392f2c35ac512c7f278534ef8eb5d ]
        Actual hash: [ 2d8ff9263cdb317b08af9dc7759c61d162dcc560eb83c0de5aa26af9898244dbc475c799f81bd237615f8369bf923932534c30a69b8cc977eb9e3a4ce6a4b714 ]

**Comment by AlexZ005** [comment] 2018-06-05 16:57
Just as a temporal solution is to replace expected hash to actual hash inside ./ports/gl3w/portfile.cmake file.

**Comment by marinedalek** [comment] 2018-06-14 01:04
While using the new hash above does allow attempted installation, the compilation will still fail due to a missing header required by the new file. This is fixed in the gl3w repository but that hasn't yet filtered down to vcpkg. (see [here](https://github.com/skaslev/gl3w/commit/99ed321100d37032cb6bfa7dd8dea85f10c86132) for the relevant gl3w commit)

**Comment by NancyLi1013** [comment] 2019-03-04 07:32
Thanks for posting this issue.
Please open a new issue if this is still a problem for you.

**Closed by NancyLi1013** 2019-03-04 07:32 UTC
Labels: needs-repro
