### ISSUE TITLE
vtk static build failed

### ISSUE THREAD

**Issue by vecbib** [microsoft/vcpkg#7007] opened 2019-06-24 05:51 UTC
Build fails when I am trying to install static library. 

I was trying to install pcl by the following command : 
`vcpkg install pcl:x64-windows-static`

```
Additional packages (*) will be modified to complete this operation.
Starting package 1/62: vtk:x64-windows-static
Building package vtk[core]:x64-windows-static...
-- Using cached E:/vcpkg/downloads/Kitware-VTK-v8.2.0.tar.gz
-- Using source at E:/vcpkg/buildtrees/vtk/src/v8.2.0-b37306c27c
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: E:/vcpkg/buildtrees/vtk/x64-windows-static-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      E:\vcpkg\buildtrees\vtk\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:274 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:107 (vcpkg_configure_cmake)
  scripts/ports.cmake:71 (include)


Error: Building package vtk:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: vtk:x64-windows-static
  Vcpkg version: 2019.06.21-nohash

Additionally, attach any relevant sections from the log files above.
```

[config-x64-windows-static-out.log](https://github.com/microsoft/vcpkg/files/3319388/config-x64-windows-static-out.log)

[CMakeError.log](https://github.com/microsoft/vcpkg/files/3319389/CMakeError.log)
[CMakeOutput.log](https://github.com/microsoft/vcpkg/files/3319390/CMakeOutput.log)

**Comment by wangli28** [comment] 2019-07-02 02:52
Thanks for posting this issue. Same error with #6889 #7111. Closed as duplicate of #7111.

**Closed by wangli28** 2019-07-02 02:52 UTC
Labels: needs-repro
