### ISSUE TITLE
[hdf5] build failure

### ISSUE THREAD

**Issue by yxnchen** [microsoft/vcpkg#21696] opened 2021-11-27 16:14 UTC
**Host Environment**
- OS: Windows 11
- Compiler: Visual C++ Build Tools 2015 update 3 (without IDE)

**To Reproduce**
`./vcpkg install gdal:x64-windows boost-geometry:x64-windows boost-graph:x64-windows boost-serialization:x64-windows`

**Failure logs** 
-Cut and paste the appropriate build messages from the console output.

> Starting package 1/18: hdf5:x64-windows
Building package hdf5[core,szip,zlib]:x64-windows...
-- Using cached HDFGroup-hdf5-hdf5-1_12_1.tar.gz.
-- Cleaning sources at C:/dev/vcpkg/buildtrees/hdf5/src/df5-1_12_1-859faf3d27.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/dev/vcpkg/downloads/HDFGroup-hdf5-hdf5-1_12_1.tar.gz
-- Applying patch hdf5_config.patch
-- Applying patch szip.patch
-- Applying patch pkgconfig-requires.patch
-- Applying patch pkgconfig-link-order.patch
-- Using source at C:/dev/vcpkg/buildtrees/hdf5/src/df5-1_12_1-859faf3d27.clean
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/CMake/bin/cmake.exe" C:/dev/vcpkg/buildtrees/hdf5/src/df5-1_12_1-859faf3d27.clean -DHDF5_ENABLE_PARALLEL=OFF -DHDF5_BUILD_TOOLS=OFF -DHDF5_BUILD_CPP_LIB=OFF -DHDF5_ENABLE_SZIP_SUPPORT=ON -DHDF5_ENABLE_SZIP_ENCODING=ON -DHDF5_ENABLE_Z_LIB_SUPPORT=ON -DHDF5_BUILD_FORTRAN=OFF -DHDF5_ENABLE_THREADSAFE=OFF -DHDF5_BUILD_UTILS=OFF -DBUILD_STATIC_LIBS=OFF -DONLY_SHARED_LIBS=ON -DBUILD_TESTING=OFF -DHDF5_BUILD_EXAMPLES=OFF -DHDF5_INSTALL_DATA_DIR=share/hdf5/data -DHDF5_INSTALL_CMAKE_DIR=share -DHDF_PACKAGE_NAMESPACE:STRING=hdf5:: -DHDF5_MSVC_NAMING_CONVENTION=OFF -DSZIP_USE_EXTERNAL=ON -DALLOW_UNSUPPORTED=OFF -DCMAKE_MAKE_PROGRAM=C:/dev/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe -DBUILD_SHARED_LIBS=ON -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/toolchains/windows.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=v140 -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_LINKER_FLAGS_RELEASE= -DVCPKG_LINKER_FLAGS_DEBUG= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -D_VCPKG_ROOT_DIR=C:/dev/vcpkg -D_VCPKG_INSTALLED_DIR=C:/dev/vcpkg/installed -DVCPKG_MANIFEST_INSTALL=OFF -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=C:/dev/vcpkg/packages/hdf5_x64-windows/debug
    Working Directory: C:/dev/vcpkg/buildtrees/hdf5/x64-windows-dbg
    Error code: 1
    See logs for more information:
      C:\dev\vcpkg\buildtrees\hdf5\config-x64-windows-dbg-out.log
      C:\dev\vcpkg\buildtrees\hdf5\config-x64-windows-dbg-err.log
Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:423 (vcpkg_execute_required_process)
  ports/hdf5/portfile.cmake:62 (vcpkg_cmake_configure)
  scripts/ports.cmake:142 (include)
Error: Building package hdf5:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `git pull` and `.\vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+hdf5
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[hdf5]+Build+error
including:
  package: hdf5[core,szip,zlib]:x64-windows -> 1.12.1#1
    vcpkg-tool version: 2021-11-24-48b94a6946b8a70abd21529218927fd478d02b6c
    vcpkg-scripts version: b3cfaaf1b 2021-11-26 (29 hours ago)
Additionally, attach any relevant sections from the log files above.

-Please attach any additional failure logs mentioned in the console output.
`config-x64-windows-dbg-err.log`:
> CMake Error at config/cmake/ConfigureChecks.cmake:334 (file):
  file failed to open for reading (No such file or directory):
    C:/dev/vcpkg/buildtrees/hdf5/x64-windows-dbg/pac_Cconftest.out
Call Stack (most recent call first):
  CMakeLists.txt:464 (include)

`config-x64-windows-dbg-out.log`:
> -- The C compiler identification is MSVC 19.0.24210.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/amd64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for include file sys/file.h
-- Looking for include file sys/file.h - not found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - not found
-- Looking for include file sys/resource.h
-- Looking for include file sys/resource.h - not found
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - not found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include files sys/stat.h, sys/time.h
-- Looking for include files sys/stat.h, sys/time.h - not found
-- Looking for include files sys/stat.h, sys/types.h
-- Looking for include files sys/stat.h, sys/types.h - found
-- Looking for 3 include files sys/stat.h, ..., features.h
-- Looking for 3 include files sys/stat.h, ..., features.h - not found
-- Looking for 3 include files sys/stat.h, ..., dirent.h
-- Looking for 3 include files sys/stat.h, ..., dirent.h - not found
-- Looking for 3 include files sys/stat.h, ..., setjmp.h
-- Looking for 3 include files sys/stat.h, ..., setjmp.h - found
-- Looking for 4 include files sys/stat.h, ..., stddef.h
-- Looking for 4 include files sys/stat.h, ..., stddef.h - found
-- Looking for 5 include files sys/stat.h, ..., stdint.h
-- Looking for 5 include files sys/stat.h, ..., stdint.h - found
-- Looking for 6 include files sys/stat.h, ..., unistd.h
-- Looking for 6 include files sys/stat.h, ..., unistd.h - not found
-- Looking for 6 include files sys/stat.h, ..., io.h
-- Looking for 6 include files sys/stat.h, ..., io.h - found
-- Looking for 7 include files sys/stat.h, ..., winsock2.h
-- Looking for 7 include files sys/stat.h, ..., winsock2.h - found
-- Looking for 8 include files sys/stat.h, ..., globus/common.h
-- Looking for 8 include files sys/stat.h, ..., globus/common.h - not found
-- Looking for 8 include files sys/stat.h, ..., pdb.h
-- Looking for 8 include files sys/stat.h, ..., pdb.h - not found
-- Looking for 8 include files sys/stat.h, ..., pthread.h
-- Looking for 8 include files sys/stat.h, ..., pthread.h - not found
-- Looking for 8 include files sys/stat.h, ..., srbclient.h
-- Looking for 8 include files sys/stat.h, ..., srbclient.h - not found
-- Looking for 8 include files sys/stat.h, ..., string.h
-- Looking for 8 include files sys/stat.h, ..., string.h - found
-- Looking for 9 include files sys/stat.h, ..., strings.h
-- Looking for 9 include files sys/stat.h, ..., strings.h - not found
-- Looking for 9 include files sys/stat.h, ..., stdlib.h
-- Looking for 9 include files sys/stat.h, ..., stdlib.h - found
-- Looking for 10 include files sys/stat.h, ..., memory.h
-- Looking for 10 include files sys/stat.h, ..., memory.h - found
-- Looking for 11 include files sys/stat.h, ..., dlfcn.h
-- Looking for 11 include files sys/stat.h, ..., dlfcn.h - not found
-- Looking for 11 include files sys/stat.h, ..., inttypes.h
-- Looking for 11 include files sys/stat.h, ..., inttypes.h - found
-- Looking for 12 include files sys/stat.h, ..., netinet/in.h
-- Looking for 12 include files sys/stat.h, ..., netinet/in.h - not found
-- Looking for 12 include files sys/stat.h, ..., netdb.h
-- Looking for 12 include files sys/stat.h, ..., netdb.h - not found
-- Looking for 12 include files sys/stat.h, ..., arpa/inet.h
-- Looking for 12 include files sys/stat.h, ..., arpa/inet.h - not found
-- Looking for 12 include files sys/stat.h, ..., stdbool.h
-- Looking for 12 include files sys/stat.h, ..., stdbool.h - found
-- Looking for include file quadmath.h
-- Looking for include file quadmath.h - not found
-- Looking for gethostname in ucb;
-- Looking for gethostname in ucb; - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of char
-- Check size of char - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of unsigned
-- Check size of unsigned - done
-- Check size of long
-- Check size of long - done
-- Check size of long long
-- Check size of long long - done
-- Check size of __int64
-- Check size of __int64 - done
-- Check size of float
-- Check size of float - done
-- Check size of double
-- Check size of double - done
-- Check size of long double
-- Check size of long double - done
-- Check size of int8_t
-- Check size of int8_t - done
-- Check size of uint8_t
-- Check size of uint8_t - done
-- Check size of int_least8_t
-- Check size of int_least8_t - done
-- Check size of uint_least8_t
-- Check size of uint_least8_t - done
-- Check size of int_fast8_t
-- Check size of int_fast8_t - done
-- Check size of uint_fast8_t
-- Check size of uint_fast8_t - done
-- Check size of int16_t
-- Check size of int16_t - done
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Check size of int_least16_t
-- Check size of int_least16_t - done
-- Check size of uint_least16_t
-- Check size of uint_least16_t - done
-- Check size of int_fast16_t
-- Check size of int_fast16_t - done
-- Check size of uint_fast16_t
-- Check size of uint_fast16_t - done
-- Check size of int32_t
-- Check size of int32_t - done
-- Check size of uint32_t
-- Check size of uint32_t - done
-- Check size of int_least32_t
-- Check size of int_least32_t - done
-- Check size of uint_least32_t
-- Check size of uint_least32_t - done
-- Check size of int_fast32_t
-- Check size of int_fast32_t - done
-- Check size of uint_fast32_t
-- Check size of uint_fast32_t - done
-- Check size of int64_t
-- Check size of int64_t - done
-- Check size of uint64_t
-- Check size of uint64_t - done
-- Check size of int_least64_t
-- Check size of int_least64_t - done
-- Check size of uint_least64_t
-- Check size of uint_least64_t - done
-- Check size of int_fast64_t
-- Check size of int_fast64_t - done
-- Check size of uint_fast64_t
-- Check size of uint_fast64_t - done
-- Check size of size_t
-- Check size of size_t - done
-- Check size of ssize_t
-- Check size of ssize_t - failed
-- Check size of off_t
-- Check size of off_t - done
-- Check size of off64_t
-- Check size of off64_t - failed
-- Check size of time_t
-- Check size of time_t - done
-- Check size of _Bool
-- Check size of _Bool - done
-- Looking for alarm
-- Looking for alarm - not found
-- Looking for fcntl
-- Looking for fcntl - not found
-- Looking for flock
-- Looking for flock - not found
-- Looking for fork
-- Looking for fork - not found
-- Looking for frexpf
-- Looking for frexpf - not found
-- Looking for frexpl
-- Looking for frexpl - not found
-- Looking for getrusage
-- Looking for getrusage - not found
-- Looking for llround
-- Looking for llround - found
-- Looking for llroundf
-- Looking for llroundf - found
-- Looking for lround
-- Looking for lround - found
-- Looking for lroundf
-- Looking for lroundf - found
-- Looking for lstat
-- Looking for lstat - not found
-- Looking for pread
-- Looking for pread - not found
-- Looking for pwrite
-- Looking for pwrite - not found
-- Looking for rand_r
-- Looking for rand_r - not found
-- Looking for random
-- Looking for random - not found
-- Looking for round
-- Looking for round - found
-- Looking for roundf
-- Looking for roundf - found
-- Looking for setsysinfo
-- Looking for setsysinfo - not found
-- Looking for signal
-- Looking for signal - found
-- Looking for setjmp
-- Looking for setjmp - found
-- Looking for siglongjmp
-- Looking for siglongjmp - not found
-- Looking for sigsetjmp
-- Looking for sigsetjmp - not found
-- Looking for sigprocmask
-- Looking for sigprocmask - not found
-- Looking for snprintf
-- Looking for snprintf - not found
-- Looking for srandom
-- Looking for srandom - not found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for strtoull
-- Looking for strtoull - found
-- Looking for symlink
-- Looking for symlink - not found
-- Looking for tmpfile
-- Looking for tmpfile - found
-- Looking for asprintf
-- Looking for asprintf - not found
-- Looking for vasprintf
-- Looking for vasprintf - not found
-- Looking for waitpid
-- Looking for waitpid - not found
-- Looking for vsnprintf
-- Looking for vsnprintf - not found
-- Looking for sigsetjmp
-- Looking for sigsetjmp - not found
-- Looking for difftime
-- Looking for difftime - found
-- Check size of __float128
-- Check size of __float128 - failed
-- Check size of _Quad
-- Check size of _Quad - failed
-- Testing maximum decimal precision for C - 
-- maximum decimal precision for C var - 0
-- Could NOT find Perl (missing: PERL_EXECUTABLE) 
-- ....All Warnings are enabled
-- Could NOT find ZLIB (missing: ZLIB_DIR)
-- Found ZLIB: optimized;C:/dev/vcpkg/installed/x64-windows/lib/zlib.lib;debug;C:/dev/vcpkg/installed/x64-windows/debug/lib/zlibd.lib (found version "1.2.11") 
-- Configuring incomplete, errors occurred!
See also "C:/dev/vcpkg/buildtrees/hdf5/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "C:/dev/vcpkg/buildtrees/hdf5/x64-windows-dbg/CMakeFiles/CMakeError.log".

Then in `C:/dev/vcpkg/buildtrees/hdf5/x64-windows-dbg/CMakeFiles/CMakeError.log`:
> Determining if files ;sys/file.h exist failed with the following output:
Change Dir: C:/dev/vcpkg/buildtrees/hdf5/x64-windows-dbg/CMakeFiles/CMakeTmp

> Run Build Command(s):C:/dev/vcpkg/downloads/tools/ninja/1.10.2-windows/ninja.exe cmTC_1c73e && [1/2] Building C object CMakeFiles\cmTC_1c73e.dir\H5_HAVE_SYS_FILE_H.c.obj

> AILED: CMakeFiles/cmTC_1c73e.dir/H5_HAVE_SYS_FILE_H.c.obj 

> C:\PROGRA\~2\MICROS~1.0\VC\bin\amd64\cl.exe  /nologo   /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /MP  /DWIN32_LEAN_AND_MEAN=1 /DNOGDI=1 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1 /showIncludes /FoCMakeFiles\cmTC_1c73e.dir\H5_HAVE_SYS_FILE_H.c.obj /FdCMakeFiles\cmTC_1c73e.dir\ /FS -c C:\dev\vcpkg\buildtrees\hdf5\x64-windows-dbg\CMakeFiles\CheckIncludeFiles\H5_HAVE_SYS_FILE_H.c

> C:\dev\vcpkg\buildtrees\hdf5\x64-windows-dbg\CMakeFiles\CheckIncludeFiles\H5_HAVE_SYS_FILE_H.c(2): fatal error C1083: Cannot open include file: 'sys/file.h': No such file or directory
ninja: build stopped: subcommand failed.

**Additional context**
None.

**Comment by yxnchen** [comment] 2021-11-30 01:51
I used the [versioning](https://vcpkg.io/en/docs/examples/versioning.getting-started.html) method to revert to a previous commit and reinstalled the packages. And the build passed.

The log shows that the installed version of hdf5 is 1.12.0. It looks like that the problem is related to the latest version of the hdf5 package.

**Comment by LilyWangLL** [comment] 2021-12-06 09:01
Hi @yxnchen, sorry I am late. It looks like hdf5 build failed with this error:
```
CMake Error at config/cmake/ConfigureChecks.cmake:334 (file):
file failed to open for reading (No such file or directory):
C:/dev/vcpkg/buildtrees/hdf5/x64-windows-dbg/pac_Cconftest.out
```
And it also appears in config-x64-windows-dbg-out.log: `-- Testing maximum decimal precision for C -`
I can install hdf5 succeed locally, and I found this file exists in directory: _VCPKG_root\buildtrees\hdf5\x64-windows-dbg_. And there is only one line in **pac_Cconftest.out**: `15;0;`

**Comment by dg0yt** [comment] 2021-12-07 07:48
Don't look at CMakeError.log (unless you are familiar with it. Focus on vcpkg output:
~~~
See logs for more information:
C:\dev\vcpkg\buildtrees\hdf5\config-x64-windows-dbg-out.log
C:\dev\vcpkg\buildtrees\hdf5\config-x64-windows-dbg-err.log
~~~
Please make attachments, don't use copy-and-paste.

**Comment by yxnchen** [comment] 2021-12-08 03:17
> Hi @yxnchen, sorry I am late. It looks like hdf5 build failed with this error:
> 
> ```
> CMake Error at config/cmake/ConfigureChecks.cmake:334 (file):
> file failed to open for reading (No such file or directory):
> C:/dev/vcpkg/buildtrees/hdf5/x64-windows-dbg/pac_Cconftest.out
> ```
> 
> And it also appears in config-x64-windows-dbg-out.log: `-- Testing maximum decimal precision for C -`, there should be a value here like this: `-- Testing maximum decimal precision for C - 15;0;` I can install hdf5 succeed locally, and I found this file exists in directory: _VCPKG_root\buildtrees\hdf5\x64-windows-dbg_. And there is only one line in **pac_Cconftest.out**: `15;0;` By the way, I install complete Visual Studio 2015 update3.

In my case, there is no such file `pac_Cconftest.out` in directory `C:/dev/vcpkg/buildtrees/hdf5/x64-windows-dbg/`. By the way, the build succeeded after I installed an older version.

**Comment by yxnchen** [comment] 2021-12-08 03:35
Hi, @dg0yt , I update vcpkg and reinstall the latest version of hdf5 again today. The build was passed and I can not reproduce the error log anymore.

**Comment by LilyWangLL** [comment] 2021-12-09 06:43
Since this issue can't be reproduced, I am closing this issue for now. If you have any question, please open a new issue.

**Closed by LilyWangLL** 2021-12-09 06:43 UTC
Labels: requires:repro
