### ISSUE TITLE
Add Skia

### ISSUE THREAD

**Issue by zhenqinshang** [Microsoft/vcpkg#835] opened 2017-03-22 14:01 UTC

**Comment by ras0219-msft** [comment] 2017-03-22 22:34
Hi @zhenqinshang, we do already have cairo available. I'll edit the title to reflect that this is a request for Skia.

Website: https://skia.org/

**Comment by ras0219-msft** [comment] 2017-03-23 19:10
Duplicate of #357

**Closed by ras0219-msft** 2017-03-23 19:11 UTC
Labels: new port request
