### ISSUE TITLE
[qt5] Qt5 build fails with an obscure error message if the vcpkg directory absolute path is 36 characters long or more

### ISSUE THREAD

**Issue by traversaro** [Microsoft/vcpkg#426] opened 2016-12-18 18:49 UTC
Some weeks ago, I experienced several failure when trying to install the `qt5` port, always with this error message:
~~~
copy /y C:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\x86-windows\qtimageformats\lib\cmake\Qt5Gui\Qt5Gui_QWbmpPlugin.cmake C:\Users\Traversaro\Documents\Code\vcpkg2\packages\qt5_x86-windows\lib\cmake\Qt5Gui
        1 file(s) copied.
        cd webp\ && ( if not exist Makefile C:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\x86-windows\qtbase\bin\qmake C:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\plugins\imageformats\webp\webp.pro -o Makefile ) && C:\Users\Traversaro\Documents\Code\vcpkg2\downloads\tools\jom\jom.exe -f Makefile install
        C:\Users\Traversaro\Documents\Code\vcpkg2\downloads\tools\jom\jom.exe -f Makefile.Debug install
        cl -c -nologo -Zc:wchar_t -FS -Zc:strictStrings -Zi -MDd -W3 -w44456 -w44457 -w44458 /Fd..\..\..\..\plugins\imageformats\qwebpd.pdb -DUNICODE -DWIN32 -DQT_NO_EXCEPTIONS -DQT_PLUGIN -DQT_GUI_LIB -DQT_CORE_LIB -DQT_OPENGL_ES_2 -DQT_OPENGL_ES_2_ANGLE -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\plugins\imageformats\webp -I. -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp\src -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp\src\dec -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp\src\enc -IC:/Users/Traversaro/Documents/Code/vcpkg2/buildtrees/qt5/src/qt-5.7.0/qtimageformats/src/3rdparty/libwebp/src/extra -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp\src\dsp -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp\src\mux -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp\src\utils -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp\src\webp -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtbase\include -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtbase\include\QtGui -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtbase\include\QtANGLE -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\x86-windows\qtbase\include -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\x86-windows\qtbase\include\QtGui -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtbase\include\QtCore -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\x86-windows\qtbase\include\QtCore -I.moc\debug -IC:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtbase\mkspecs\win32-msvc2015 -Fo.obj\debug\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp\src\dsp\alpha_processing_mips_dsp_r2.obj C:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp\src\dsp\alpha_processing_mips_dsp_r2.c
alpha_processing_mips_dsp_r2.c
C:\Users\Traversaro\Documents\Code\vcpkg2\buildtrees\qt5\src\qt-5.7.0\qtimageformats\src\3rdparty\libwebp\src\dsp\alpha_processing_mips_dsp_r2.c : fatal error C1083: Cannot open compiler generated file: '': Invalid argument
~~~

In particular it turns out that `C1083` can be caused by the [1] "path/filename length limitation of Visual Studio". My  vcpkg directory absolute path is 42 characters long. Moving the vcpkg directory to `C:\vcpkg` indeed solved the problem. Perhaps this is obvious to experienced Windows developers. but it would be nice to provide a clean error message in this case. 

A possible solution is for `vcpkg` to explicitly support a maximum length of the absolute directory path in which it is installed (checked using Continuous Integration, see [2]) and print a warning if it is installed in a directory whose absolute path is greater then the supported one.

[1] : http://stackoverflow.com/questions/34074925/vs-2015-cannot-open-compiler-generated-file-invalid-argument
[2] : https://github.com/Microsoft/vcpkg/issues/72

**Comment by ForNeVeR** [comment] 2017-01-08 08:48
For the record, my path to vcpkg was 36 chars, and that's already too big, so this error appears.

**And thank you very much for filing this issue!** I'd never know what the problem is without this issue.

**Comment by traversaro** [comment] 2017-01-08 08:53
@ForNeVeR thanks for the info, I updated the title.

**Comment by ras0219-msft** [comment] 2017-06-06 18:39
While not a direct fix, I've added a check in the portfile to help mitigate this.

As a workaround for those in the future: the `subst` command seems to work well for me to quickly get a short path.

**Comment by wangli28** [comment] 2019-02-27 09:57
Hi everyone, this issue should be fixed. Please open a new issue if this is still a problem for you.
Thanks.

**Closed by wangli28** 2019-02-27 09:57 UTC
Labels: vcpkg feature

**Comment by traversaro** [comment] 2019-02-27 10:01
Hi @wangli28, which `vcpkg` commit fixed the issue?

**Comment by traversaro** [comment] 2020-09-18 11:26
> 
> 
> Hi everyone, this issue should be fixed. Please open a new issue if this is still a problem for you.
> Thanks.

Hi @LilyWangL , which `vcpkg` change or commit fixed the issue? Thanks!
