### ISSUE TITLE
[angle] Build error

### ISSUE THREAD

**Issue by krNeko9t** [microsoft/vcpkg#25725] opened 2022-07-12 06:50 UTC
Package: angle[core]:x64-windows -> chromium_4472#3
**Host Environment**
- Host: x64-windows
- Compiler: MSVC 19.16.27048.0
-    vcpkg-tool version: 2022-06-17-9268e366206712e38102b28dbd1617697a99ff2e
    vcpkg-scripts version: d769781d1 2022-07-11 (7 hours ago)

**To Reproduce**
`vcpkg install angle`

**Failure logs**
```
-- Using cached google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz.
-- Cleaning sources at C:/Projects/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Projects/vcpkg/downloads/google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz
-- Applying patch 001-fix-uwp.patch
-- Applying patch 002-fix-builder-error.patch
-- Applying patch 003-fix-mingw.patch
-- Using source at C:/Projects/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean
-- Using cached C:/Projects/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Extracting source C:/Projects/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Applying patch third-party-zlib-far-undef.patch
-- Using source at C:/Projects/vcpkg/buildtrees/angle/src/8ee76d4a8e-895bfc7289.clean
-- Configuring x64-windows
-- Building x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: C:/Projects/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j17
    Working Directory: C:/Projects/vcpkg/buildtrees/angle/x64-windows-dbg
    See logs for more information:
      C:\Projects\vcpkg\buildtrees\angle\install-x64-windows-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:78 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:18 (vcpkg_build_cmake)
  ports/angle/portfile.cmake:64 (vcpkg_install_cmake)
  scripts/ports.cmake:146 (include)



```
<details><summary>C:\Projects\vcpkg\buildtrees\angle\install-x64-windows-dbg-out.log</summary>

```
[1/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\blocklayoutHLSL.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\blocklayoutHLSL.cpp
[2/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\tree_ops\d3d\ExpandIntegerPowExpressions.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\tree_ops\d3d\ExpandIntegerPowExpressions.cpp
[3/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\tree_ops\d3d\RemoveSwitchFallThrough.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\tree_ops\d3d\RemoveSwitchFallThrough.cpp
...
Skipped 549 lines
...

C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(137): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(150): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
[399/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\tree_ops\gl\RewriteRepeatedAssignToSwizzled.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\tree_ops\gl\RewriteRepeatedAssignToSwizzled.cpp
[400/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\AtomicCounterFunctionHLSL.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\AtomicCounterFunctionHLSL.cpp
[401/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\tree_ops\gl\VectorizeVectorScalarArithmetic.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\tree_ops\gl\VectorizeVectorScalarArithmetic.cpp
[402/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\tree_ops\gl\RegenerateStructNames.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\tree_ops\gl\RegenerateStructNames.cpp
C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(137): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(150): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
[403/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\tree_ops\gl\UseInterfaceBlockFields.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\tree_ops\gl\UseInterfaceBlockFields.cpp
C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(137): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(150): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
[404/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\ImageFunctionHLSL.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\ImageFunctionHLSL.cpp
[405/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\ASTMetadataHLSL.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\ASTMetadataHLSL.cpp
C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(137): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(150): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
[406/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\BuiltInFunctionEmulatorHLSL.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\BuiltInFunctionEmulatorHLSL.cpp
[407/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_ENABLE_ESSL -DANGLE_ENABLE_GLSL -DANGLE_ENABLE_HLSL -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DGL_SILENCE_DEPRECATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\angle_translator.dir\src\compiler\translator\OutputHLSL.cpp.obj /FdCMakeFiles\angle_translator.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler\translator\OutputHLSL.cpp
C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(137): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/SymbolTable.h(150): warning C4267: 'initializing': conversion from 'size_t' to 'uint8_t', possible loss of data
[408/419] C:\PROGRA~2\MICROS~2\2017\PROFES~1\VC\Tools\MSVC\1416~1.270\bin\Hostx64\x64\cl.exe   /TP -DANGLE_CAPTURE_ENABLED=0 -DANGLE_EXPORT="" -DANGLE_IS_64_BIT_CPU -DANGLE_IS_WIN -DANGLE_STANDALONE_BUILD -DANGLE_UTIL_EXPORT="" -DEGLAPI="" -DEGL_EGLEXT_PROTOTYPES -DEGL_EGL_PROTOTYPES=1 -DGL_API="" -DGL_APICALL="" -DGL_GLES_PROTOTYPES=1 -DGL_GLEXT_PROTOTYPES -DGL_SILENCE_DEPRECATION -DLIBANGLE_IMPLEMENTATION -DLIBGLESV2_IMPLEMENTATION -DNOMINMAX -D_CRT_SECURE_NO_DEPRECATE -D_HAS_EXCEPTIONS=0 -D_SCL_SECURE_NO_WARNINGS -DlibGLESv2_EXPORTS -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src -IC:\Projects\vcpkg\buildtrees\angle\x64-windows-dbg\include -IC:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\common\third_party\base /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  /d2guard4 /Wv:18 /guard:cf /permissive /bigobj -DANGLE_ENABLE_DEBUG_ANNOTATIONS /showIncludes /FoCMakeFiles\libGLESv2.dir\src\libGLESv2\entry_points_gles_ext_autogen.cpp.obj /FdCMakeFiles\libGLESv2.dir\ /FS -c C:\Projects\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\libGLESv2\entry_points_gles_ext_autogen.cpp
ninja: build stopped: subcommand failed.
```
</details>

**Additional context**

**Comment by Adela0814** [comment] 2022-07-13 02:17
Duplicate of https://github.com/microsoft/vcpkg/issues/24704 (internal compiler error).

**Closed by Adela0814** 2022-07-13 02:17 UTC

**Comment by krNeko9t** [comment] 2022-07-13 07:27
[issue_body.md](https://github.com/microsoft/vcpkg/files/9099898/issue_body.md)
I download English language pack and use VS 2022 17.2.6, but still have problem.
