### ISSUE TITLE
vcpkg upgrade --no-dry-run no-longer functioning properly - Value was null

### ISSUE THREAD

**Issue by timautry** [microsoft/vcpkg#9916] opened 2020-02-05 01:57 UTC
**Describe the bug**
When I try to do a _.\vcpkg upgrade --no-dry-run_ it deletes all the packages and the required downstream package dependencies but vcpkg fails to continue and reinstall the upgraded packages and any other related packages with the upgraded packages features.

**Environment**
- OS: [Windows 10 x64 Version 1909 OS Build 18363.628]
- OS: [Linux openSUSE x64 Version 15.1]
- Compiler: Windows vs2017 v15.9.19 and vs2019 v16.4.4
- Compiler: Linux gcc (SUSE Linus) v7.5.0

**To Reproduce**
1. On windows - .\vcpkg upgrade --no-dry-run
    On Linux ./vcpkg upgrade --no-dry-run
2. Errors

  _On Windows:_

- VS2017:
SYSTEM@ANDROMEDA 02/04/2020 20:44:36 D:\Git\vs2017.prod
->vcpkg upgrade
The following packages will be rebuilt:
  * mpi[core]:x64-windows
  * msmpi[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
If you are sure you want to rebuild the above packages, run this command with the --no-dry-run option.

SYSTEM@ANDROMEDA 02/04/2020 20:46:24 D:\Git\vs2017.prod
->vcpkg upgrade --no-dry-run
The following packages will be rebuilt:
  * mpi[core]:x64-windows
  * msmpi[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: mpi:x64-windows
Removing package mpi:x64-windows...
Removing package mpi:x64-windows... done
Purging package mpi:x64-windows...
Purging package mpi:x64-windows... done
Elapsed time for package mpi:x64-windows: 3.849 ms
Starting package 2/4: msmpi:x64-windows
Removing package msmpi:x64-windows...
Removing package msmpi:x64-windows... done
Purging package msmpi:x64-windows...
Purging package msmpi:x64-windows... done
Elapsed time for package msmpi:x64-windows: 6.446 ms
Starting package 3/4: msmpi:x64-windows
Building package msmpi[core]:x64-windows...
**Value was null**

- VS2019:
SYSTEM@ANDROMEDA 02/04/2020 20:44:58 D:\Git\vs2019.prod
->vcpkg upgrade
The following packages will be rebuilt:
  * mpi[core]:x64-windows
  * msmpi[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
If you are sure you want to rebuild the above packages, run this command with the --no-dry-run option.

SYSTEM@ANDROMEDA 02/04/2020 20:47:31 D:\Git\vs2019.prod
->vcpkg upgrade --no-dry-run
The following packages will be rebuilt:
  * mpi[core]:x64-windows
  * msmpi[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: mpi:x64-windows
Removing package mpi:x64-windows...
Removing package mpi:x64-windows... done
Purging package mpi:x64-windows...
Purging package mpi:x64-windows... done
Elapsed time for package mpi:x64-windows: 3.389 ms
Starting package 2/4: msmpi:x64-windows
Removing package msmpi:x64-windows...
Removing package msmpi:x64-windows... done
Purging package msmpi:x64-windows...
Purging package msmpi:x64-windows... done
Elapsed time for package msmpi:x64-windows: 7.008 ms
Starting package 3/4: msmpi:x64-windows
Building package msmpi[core]:x64-windows...
**Value was null**

  _On Linux:_
tim.autry@galactica:[~/git/vcpkg]
>$ vcpkg upgrade --no-dry-run
The following packages will be rebuilt:
  * libarchive[bzip2,core,libxml2,lz4,lzma,lzo,openssl]:x64-linux
    liblzma[core]:x64-linux
  * libxml2[core]:x64-linux
Additional packages (*) will be modified to complete this operation.
Starting package 1/6: libarchive:x64-linux
Removing package libarchive:x64-linux...
Removing package libarchive:x64-linux... done
Purging package libarchive:x64-linux...
Purging package libarchive:x64-linux... done
Elapsed time for package libarchive:x64-linux: 5.89 ms
Starting package 2/6: libxml2:x64-linux
Removing package libxml2:x64-linux...
Removing package libxml2:x64-linux... done
Purging package libxml2:x64-linux...
Purging package libxml2:x64-linux... done
Elapsed time for package libxml2:x64-linux: 5.923 ms
Starting package 3/6: liblzma:x64-linux
Removing package liblzma:x64-linux...
Removing package liblzma:x64-linux... done
Purging package liblzma:x64-linux...
Purging package liblzma:x64-linux... done
Elapsed time for package liblzma:x64-linux: 2.973 ms
Starting package 4/6: liblzma:x64-linux
Building package liblzma[core]:x64-linux...
**CMake Error: Error processing file: home/tim.autry/git/vcpkg/scripts/get_triplet_environment.cmake**

**Expected behavior**
vcpkg should delete packages to be upgraded along with downstream dependencies and then reinstall them.

**Failure logs** 
- There are no failure logs, only above output to console screen.

**Additional context**
Happens on Windows and Linux, I've tried Windows vcpkg built as x86 and x64, and Linux as x64. 
It started a few days ago, I thought my vcpkg installs were corrupt, so I deleted and cloned them again from scratch. Then I thought maybe my fork on github was corrupt, so I delete my fork and recreated. I then delete my local vcpkg repositories and cloned them directly from microsoft/vcpkg. So then I tried another machine and the same thing happens - on windows I get **Value was null** and on linux I get a **CMake Error: Error processing file: /home/tim.autry/git/vcpkg/scripts/get_triplet_environment.cmake**.

I can recreate by manually increasing the version number in a package's _Control_ file,

Also on windows it started putting the "asterisk" in front of all packages, where before only the downstream packages had the "asterisk" and all the upgraded packages did not.

**_I'm at a loss at what could be the issue - I deleted and cloned vcpkg at least a half dozen times this past few days I think I'm about to lose it???_**

**Comment by timautry** [comment] 2020-02-05 02:31
Additional info: On Linux, after I removed the old vcpkg env from my .bashrc profile I now get the same message as windows on the ./vcpkg upgrade --no-dry-run **Value was null**.

**Comment by PhoebeHui** [comment] 2020-02-05 13:35
Confirmed, this issue reproed. @timautry, thanks for reporting this issue, 
@ras0219-msft, this issue seems vcpkg bug that invoved in recently changes, could you help have a look?

**Comment by timautry** [comment] 2020-02-05 15:08
Thank you @PhoebeHui @ras0219 !!!

**Comment by degski** [comment] 2020-02-05 16:03
Just submitting I have the same error.

**Comment by rkitover** [comment] 2020-02-05 16:59
I am getting this as well.

**Comment by OlafvdSpek** [comment] 2020-02-06 10:55
Me too, on two different Windows systems.

**Comment by rkitover** [comment] 2020-02-06 15:01
Just wanted to point out that as a temporary workaround, you can read the list of new packages from `upgrade` **without** `--no-dry-run`, and then pass the packages to first `remove` and then `install`. This works fine for me.

**Comment by acgetchell** [comment] 2020-02-11 19:29
Also seeing same bug. As it uninstalls `CGAL`, my workaround is to simply reinstall it.

**Comment by Christsnatcher** [comment] 2020-02-12 23:11
I'm also having the same issue on Windows 8.1 x64 with the latest Visual Studio 2019 build installed. Yesterday I set up an entirely "fresh" vcpkg installation hoping this would resolve the issue, but unfortunately without success. Please fix this - critical - bug as soon as possible, thank you very much!

**Comment by OlafvdSpek** [comment] 2020-02-13 10:44
> Also seeing same bug. Is there a way to script this?

Put your dependencies in a `vcpkg-install.txt` file and you can simply reinstall everything from scratch whenever needed.

**Comment by rkcarroll** [comment] 2020-02-14 16:03
I am also having this issue.  As of 2/14/2020, did a new pull, update, upgrade --no-dry-run.  It removes boost (and others), although they still show up in "list".  Fixing is a tedious process.

Latest error message:
Starting package 107/212: boost-modular-build-helper:x64-windows
Building package boost-modular-build-helper[core]:x64-windows...
CMake Error: Error processing file: E:/Libs/vcpkg/scripts/get_triplet_environment.cmake

My system does not have the mentioned cmake script.

**Comment by rkcarroll** [comment] 2020-02-14 16:06
Sorry, disregard previous comment.  Looks like running the bootstrap script fixed the issue (for now).

**Comment by cenit** [comment] 2020-02-18 10:48
Still having the "Value was null" problem (even with a fresh rebuilt vcpkg).
Isn't this considered high priority for a fix? Not being able to upgrade (and also outputting the error after having removed all the libraries,  so in an undesired state) is a major inconvenience...

**Comment by yezilaoda** [comment] 2020-02-20 06:09
me too . win10

**Comment by acgetchell** [comment] 2020-02-20 16:52
Had to remove AppVeyor caching because then packages are upgraded, and this fails. Also confirmed on Ubuntu 18.04 that I just rebuilt my project on.

**Comment by cenit** [comment] 2020-02-20 17:00
@acgetchell exactly. This problem has huge problems for automated ci for downstream projects. I don't want to delete cache

**Comment by rkitover** [comment] 2020-02-23 18:51
I was trying to diagnose this issue and I made a tool to help me repeatedly reproduce the error:

https://github.com/rkitover/vcpkg-binpkg-prototype/

this is still a work in progress, and I need to check a few things for accuracy, but I may start using this.

But anyway, with this you can make a package of the outdated package, and when the failed upgrade operation deletes it, you can reinstall it to allow repeating the error.

I will try to do some more diagnosis of this, I've read most of the core vcpkg C++ sources already.

**Comment by aPSopt** [comment] 2020-02-24 09:59
me too :(
win10, msvs - last version

**Comment by ras0219-msft** [comment] 2020-02-24 22:39
Thanks everyone for identifying this regression so quickly and providing awesome repro steps!

It should be fixed on master via PR #10202.

**Closed by ras0219-msft** 2020-02-24 22:39 UTC
Labels: vcpkg bug

**Comment by timautry** [comment] 2020-02-25 19:17
@ras0219-msft @PhoebeHui 
Thank you for fixing this!! I appreciate the hard work, and I don't know if this is a problem or not?
- In the past before this last vcpkg code upgrade, vcpkg would show the ports needing to be upgraded without any symbol preceding them
-  Only the ports needing to be rebuilt due to the upgrades would be shown with an asterisk preceding it 
- In the example below, llvm and xlnt are to be upgraded
- llvm is going to be upgraded, but halide depends on llvm so it too must be recompiled and it would show it with an asterisk proceeding it

->vcpkg upgrade
The following packages will be rebuilt:
  * halide[core,opencl,opengl,utils]:x64-windows
    llvm[core,example,test,tools,utils]:x64-windows
    xlnt[core]:x64-windows

Additional packages (*) will be modified to complete this operation.
If you are sure you want to rebuild the above packages, run this command with the --no-dry-run option.
