### ISSUE TITLE
It is hoped that libgda of windows (x64, x86) version can be added

### ISSUE THREAD

**Issue by moshilgc** [microsoft/vcpkg#20239] opened 2021-09-18 06:13 UTC
Library name:
    libgda

Library description:
   GNU Data Access (GDA) is an attempt to provide uniform access to different kinds of data sources (databases, information 
 servers, mail spools, etc). It is a complete architecture that provides all you need to access  your data.

Source repository URL:
   https://download.gnome.org/sources/libgda/6.0/
Project homepage (if different from the source repository):
  https://github.com/GNOME/libgda

**Comment by JonLiu1993** [comment] 2021-09-18 06:20
Duplicate of #20238

**Closed by JonLiu1993** 2021-09-18 06:20 UTC
