### ISSUE TITLE
[vtk] Build error

### ISSUE THREAD

**Issue by helloworld0xf** [microsoft/vcpkg#28891] opened 2023-01-12 06:04 UTC
**Host Environment**
- OS: win10
- Compiler: vs2019

**To Reproduce**
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: "C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: D:/vcpkg/buildtrees/vtk/x64-windows-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      D:\vcpkg\buildtrees\vtk\config-x64-windows-dbg-CMakeCache.txt.log
      D:\vcpkg\buildtrees\vtk\config-x64-windows-rel-CMakeCache.txt.log
      D:\vcpkg\buildtrees\vtk\config-x64-windows-out.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake:247 (vcpkg_execute_required_process)
  ports/vtk/portfile.cmake:153 (vcpkg_cmake_configure)
  scripts/ports.cmake:147 (include)

error: building vtk:x64-windows failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+vtk
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[vtk]+Build+error
Include '[vtk] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-12-14-7ae0d8527fb488fde10a89c2813802dc9b03b6f9
    vcpkg-scripts version: d40bedd6f 2023-01-11 (5 hours ago)

`.\vcpkg.exe install vtk[all]:x64-windows`

**Failure logs**
-- Found SQLite3: D:/vcpkg/installed/x64-windows/include (found version "3.40.0") 
-- VTK module debug building: VTK::IOSQL is being built
-- VTK module debug building: VTK::TestingIOSQL is being built
-- VTK module debug building: VTK::TestingGenericBridge is being built
-- VTK module debug building: VTK::FiltersAMR is being built
-- VTK module debug building: VTK::RenderingVolumeAMR is being built
-- VTK module debug building: VTK::RenderingRayTracing is being built
CMake Warning at D:/vcpkg/scripts/buildsystems/vcpkg.cmake:843 (_find_package):
  By not providing "Findospray.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "ospray", but
  CMake did not find one.

  Could not find a package configuration file provided by "ospray" (requested
  version 2.1) with any of the following names:

    osprayConfig.cmake
    ospray-config.cmake

  Add the installation prefix of "ospray" to CMAKE_PREFIX_PATH or set
  "ospray_DIR" to a directory containing one of the above files.  If "ospray"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMake/vtkModule.cmake:4222 (find_package)
  Rendering/RayTracing/CMakeLists.txt:58 (vtk_module_find_package)

CMake Error at CMake/vtkModule.cmake:4228 (message):
  Could not find the ospray external dependency.
Call Stack (most recent call first):
  Rendering/RayTracing/CMakeLists.txt:58 (vtk_module_find_package)

-- Configuring incomplete, errors occurred!
See also "D:/vcpkg/buildtrees/vtk/x64-windows-dbg/CMakeFiles/CMakeOutput.log".
See also "D:/vcpkg/buildtrees/vtk/x64-windows-dbg/CMakeFiles/CMakeError.log".
ninja: build stopped: subcommand failed.

**Comment by Cheney-W** [comment] 2023-01-12 10:40
Duplicate of https://github.com/microsoft/vcpkg/issues/25579.

**Closed by Cheney-W** 2023-01-12 10:40 UTC
Labels: category:port-bug
