### ISSUE TITLE
[New Port Request] argon2

### ISSUE THREAD

**Issue by hmoffatt** [microsoft/vcpkg#17920] opened 2021-05-14 00:22 UTC
Library name: argon2

Library description: password hashing function library

Source repository URL: https://github.com/P-H-C/phc-winner-argon2

**Comment by JonLiu1993** [comment] 2021-05-14 01:23
Duplicate of #14754

**Closed by JonLiu1993** 2021-05-14 01:23 UTC

**Comment by hmoffatt** [comment] 2021-05-14 02:28
Sorry about that, not sure why my search failed me.
