### ISSUE TITLE
wxwidgets build failure

### ISSUE THREAD

**Issue by amciffer** [microsoft/vcpkg#10689] opened 2020-04-04 00:13 UTC
**Host Environment**
Windows 10
Visual Studio 19

**To Reproduce**
`./vcpkg install wxwidgets

**Failure logs** 
-- Performing post-build validation
Include files should not be duplicated into the /debug/include directory. If this cannot be disabled in the project cmake, use
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
There should be no empty directories in C:\Users\Andrew\vcpkg\packages\wxwidgets_x86-windows
The following empty directories were found:

    C:/Users/Andrew/vcpkg/packages/wxwidgets_x86-windows/debug/include

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")

Found 2 error(s). Please correct the portfile:
    C:\Users\Andrew\vcpkg\ports\wxwidgets\portfile.cmake
-- Performing post-build validation done
Error: Building package wxwidgets:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: wxwidgets:x86-windows
  Vcpkg version: 2020.02.04-nohash

**Comment by NancyLi1013** [comment] 2020-04-07 07:16
Hi @amciffer 
Could you please help confirm if you modified any files for `wxwidgets `?
I cannot reproduce this issue on my local machine with Visual Studio 2019 and Visual Studio 2017.

**Comment by amciffer** [comment] 2020-04-08 01:08
No, I didn’t modify anything.  I pulled it down, and did the build.

**Comment by NancyLi1013** [comment] 2020-04-08 08:42
Could you please help confirm if the directory is empty?_C:/Users/Andrew/vcpkg/packages/wxwidgets_x86-windows/debug/include_
Do you only build release type?

**Comment by amciffer** [comment] 2020-04-08 16:16
It’s empty.

I did “install wxwidgets”.  Does that create debug and release?

I will try running it again.

**Comment by amciffer** [comment] 2020-04-08 17:09
I ran it again and received the same error.  Here is the full output from the process.  What is interesting is that I did see output in the debug folder after the debug portion was completed.  The process must then delete them.

C:\Users\Andrew\vcpkg> .\vcpkg install wxwidgets
Computing installation plan...
The following packages will be built and installed:
    wxwidgets[core]:x86-windows
Starting package 1/1: wxwidgets:x86-windows
Building package wxwidgets[core]:x86-windows...
-- Using cached C:/Users/Andrew/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.3.tar.gz
-- Using source at C:/Users/Andrew/vcpkg/buildtrees/wxwidgets/src/v3.1.3-91ca46db88
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
Include files should not be duplicated into the /debug/include directory. If this cannot be disabled in the project cmake, use
    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
There should be no empty directories in C:\Users\Andrew\vcpkg\packages\wxwidgets_x86-windows
The following empty directories were found:

    C:/Users/Andrew/vcpkg/packages/wxwidgets_x86-windows/debug/include

If a directory should be populated but is not, this might indicate an error in the portfile.
If the directories are not needed and their creation cannot be disabled, use something like this in the portfile to remove them:

    file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/a/dir" "${CURRENT_PACKAGES_DIR}/some/other/dir")


Found 2 error(s). Please correct the portfile:
    C:\Users\Andrew\vcpkg\ports\wxwidgets\portfile.cmake
-- Performing post-build validation done
Error: Building package wxwidgets:x86-windows failed with: POST_BUILD_CHECKS_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: wxwidgets:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

**Comment by NancyLi1013** [comment] 2020-04-09 07:10
I'm not sure what happened on your machine.
This is the build process on my local:
```
PS F:\new\vcpkg> .\vcpkg.exe install wxwidgets
Your feedback is important to improve Vcpkg! Please take 3 minutes to complete our survey by running: vcpkg contact --survey
Computing installation plan...
The following packages will be built and installed:
    wxwidgets[core]:x86-windows
Starting package 1/1: wxwidgets:x86-windows
Building package wxwidgets[core]:x86-windows...
-- Using cached F:/new/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.3.tar.gz
-- Using source at F:/new/vcpkg/buildtrees/wxwidgets/src/v3.1.3-91ca46db88
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package wxwidgets[core]:x86-windows... done
Installing package wxwidgets[core]:x86-windows...
Installing package wxwidgets[core]:x86-windows... done
Elapsed time for package wxwidgets:x86-windows: 6.399 min

Total elapsed time: 6.402 min
```
Could you please remove _C:/Users/Andrew/vcpkg/buildtrees/wxwidgets_ and update vcpkg, then build this port again?

**Comment by amciffer** [comment] 2020-04-09 20:17
I followed your advice and now it builds without error.  I see the include files in the debug directory.

Thanks for your help.  I haven’t programmed in quite a while and wanted to get back into C++.

C:\Users\Andrew\vcpkg>.\vcpkg install wxwidgets
Computing installation plan...
The following packages will be built and installed:
    wxwidgets[core]:x86-windows
Starting package 1/1: wxwidgets:x86-windows
Building package wxwidgets[core]:x86-windows...
-- Using cached C:/Users/Andrew/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.3.tar.gz
-- Extracting source C:/Users/Andrew/vcpkg/downloads/wxWidgets-wxWidgets-v3.1.3.tar.gz
-- Applying patch disable-platform-lib-dir.patch
-- Using source at C:/Users/Andrew/vcpkg/buildtrees/wxwidgets/src/v3.1.3-91ca46db88
-- Configuring x86-windows
-- Building x86-windows-dbg
-- Building x86-windows-rel
-- Performing post-build validation
-- Performing post-build validation done
Building package wxwidgets[core]:x86-windows... done
Installing package wxwidgets[core]:x86-windows...
Installing package wxwidgets[core]:x86-windows... done
Elapsed time for package wxwidgets:x86-windows: 12.19 min

Total elapsed time: 12.19 min

**Comment by NancyLi1013** [comment] 2020-04-10 01:58
Thanks for your update.
Since it has been fixed, I am closing this issue for now.

**Closed by NancyLi1013** 2020-04-10 01:58 UTC
Labels: needs-repro
