### ISSUE TITLE
problem while installing grpc via vcpkg on Apple M1

### ISSUE THREAD

**Issue by limarev** [microsoft/vcpkg#17468] opened 2021-04-23 12:55 UTC
**Host Environment**
- OS: [macOS Big Sur 11.2.3 Apple M1]
- Compiler: Clang 12.0.0

**To Reproduce**
`./vcpkg install --recurse --clean-after-build --triplet=arm64-osx grpc`

**Failure logs** 
Konstantin, [16 Apr 2021, 02:54:36]:
limarev@MacBook-Air-Konstantin vcpkg % vcpkg install --recurse --clean-after-build --triplet=arm64-osx grpc         
Computing installation plan...
The following packages will be built and installed:
  * abseil[core]:arm64-osx -> 2021-03-24
  * abseil[core]:x64-osx -> 2021-03-24
  * c-ares[core]:arm64-osx -> 1.17.1#1
  * c-ares[core]:x64-osx -> 1.17.1#1
  * grpc[core]:x64-osx -> 1.33.1#3
    grpc[core]:arm64-osx -> 1.33.1#3
  * openssl[core]:x64-osx -> 1.1.1j
  * re2[core]:x64-osx -> 2020-10-01
  * re2[core]:arm64-osx -> 2020-10-01
  * upb[core]:x64-osx -> 2020-08-19
  * upb[core]:arm64-osx -> 2020-08-19
  * zlib[core]:x64-osx -> 1.2.11#9
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet arm64-osx...
Detecting compiler hash for triplet x64-osx...
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/d6/d6c93035aef8e62fef02c4bbde35558b706941ff.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/60/603608257b181dc69f249b264d45cb0b73b539b2.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/d0/d06d272f9ed750e1d3b0464dd0c20ea3c281e726.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/8a/8ae238a4b90bcab967113076e0248b15b68d3c7d.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/d3/d3c28088f285f50c085d41d5cf1d698d1c24557f.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/2c/2c76b65178ed853286b3017e2aefd0e026ad61e2.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/5c/5cd0b0492192627c29b685cd7efce443827ea431.zip
Using cached binary package: /Users/limarev/.cache/vcpkg/archives/33/334111b1eeac9da2793d3ec2de73e204cc2131d7.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/10/10aa3cc9cb583d74568437417d8ae392e67229cd.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/d2/d29939b458cb7fcee415e0104b98779ca21a49b9.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/55/558f54dc40a65dc3d758c18805639569f4061c63.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/70/701b5c63c6c71e99c7f8f49893a55ff9a52d90dd.zip
Starting package 1/12: abseil:arm64-osx
Building package abseil[core]:arm64-osx...
-- Using community triplet arm64-osx. This triplet configuration is not guaranteed to succeed.
-- [COMMUNITY] Loading triplet configuration from: /Users/limarev/local/vcpkg/vcpkg/triplets/community/arm64-osx.cmake
-- Downloading https://github.com/abseil/abseil-cpp/archive/997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz -> abseil-abseil-cpp-997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz...
-- Extracting source /Users/limarev/local/vcpkg/vcpkg/downloads/abseil-abseil-cpp-997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz
-- Applying patch fix-cxx-standard.patch
-- Using source at /Users/limarev/local/vcpkg/vcpkg/buildtrees/abseil/src/ca9688e9f6-e4cda1d679.clean
-- Found external ninja('1.10.2').
-- Configuring arm64-osx-dbg
-- Configuring arm64-osx-rel
-- Building arm64-osx-dbg
-- Building arm64-osx-rel
-- Installing: /Users/limarev/local/vcpkg/vcpkg/packages/abseil_arm64-osx/share/abseil/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: /Users/limarev/.cache/vcpkg/archives/d6/d6c93035aef8e62fef02c4bbde35558b706941ff.zip
Building package abseil[core]:arm64-osx... done
Installing package abseil[core]:arm64-osx...
Installing package abseil[core]:arm64-osx... done
Elapsed time for package abseil:arm64-osx: 14.35 s
Starting package 2/12: abseil:x64-osx
Building package abseil[core]:x64-osx...
-- Downloading https://github.com/abseil/abseil-cpp/archive/997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz -> abseil-abseil-cpp-997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz...
-- Extracting source /Users/limarev/local/vcpkg/vcpkg/downloads/abseil-abseil-cpp-997aaf3a28308eba1b9156aa35ab7bca9688e9f6.tar.gz
-- Applying patch fix-cxx-standard.patch

-- Using source at /Users/limarev/local/vcpkg/vcpkg/buildtrees/abseil/src/ca9688e9f6-e4cda1d679.clean
-- Found external ninja('1.10.2').
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /usr/local/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /Users/limarev/local/vcpkg/vcpkg/buildtrees/abseil/x64-osx-dbg
    See logs for more information:
      /Users/limarev/local/vcpkg/vcpkg/buildtrees/abseil/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/abseil/portfile.cmake:32 (vcpkg_install_cmake)
  scripts/ports.cmake:142 (include)

Error: Building package abseil:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: abseil:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

<img width="1440" alt="Screenshot 2021-04-16 at 02 57 45" src="https://user-images.githubusercontent.com/56980675/115872668-bcfa7d80-a44a-11eb-9f7f-feb64a1e7044.png">

abseil/abseil-cpp#945
grpc/grpc#26000

**Additional context**

I compile gcc-10 and compile cmake with gcc-10. Then reinstalled vcpkg and tried to install grpc again. 
limarev@MacBook-Air-Konstantin ~ % vcpkg install --recurse --clean-after-build --triplet=arm64-osx grpc
Computing installation plan...
The following packages will be built and installed:
  * grpc[core]:x64-osx -> 1.33.1#3
    grpc[core]:arm64-osx -> 1.33.1#3
  * openssl[core]:x64-osx -> 1.1.1j#1
  * openssl[core]:arm64-osx -> 1.1.1j#1
  * protobuf[core]:x64-osx -> 3.15.8
  * protobuf[core]:arm64-osx -> 3.15.8
  * re2[core]:x64-osx -> 2020-10-01
  * re2[core]:arm64-osx -> 2020-10-01
  * upb[core]:x64-osx -> 2020-08-19
  * upb[core]:arm64-osx -> 2020-08-19
  * zlib[core]:x64-osx -> 1.2.11#10
  * zlib[core]:arm64-osx -> 1.2.11#10
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-osx...
Detecting compiler hash for triplet arm64-osx...
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/9f/9f67fb75e3dddc25a5afd16311d655fea4b0b4da.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/81/813cec966d1aa440017b3765d537fff2c34596de.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/ec/ec627c3701a39a53350bbb6437bfe1d2bdc867bb.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/54/547af56128e48f15651bb79ee9c2034d4a97955e.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/ef/ef0ab1ebacf9c021473ebc79b0df75bc9181885e.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/38/38c1f4c1e71d9b9314570e735bfe80d3740652a7.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/93/93f7bac58dc244295ce3177ba6f3348339c0daee.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/a2/a2f39657d1d326c041fa2f11d24189c9073605d1.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/c2/c2b1e2caf7e1c59a69d77c3fe16dd5172f4d96e2.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/01/01990819cd5171a0590d6a7cd3292e2398535f6f.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/8e/8efa855854846284b3ed362f19b0a57c8f92dcbb.zip
Could not locate cached archive: /Users/limarev/.cache/vcpkg/archives/c7/c7b29e50553a325c187f993141a60987bbd9381c.zip
Starting package 1/12: openssl:x64-osx
Building package openssl[core]:x64-osx...
-- Using cached /Users/limarev/local/vcpkg/downloads/openssl-1.1.1j.tar.gz
-- Extracting source /Users/limarev/local/vcpkg/downloads/openssl-1.1.1j.tar.gz
-- Using source at /Users/limarev/local/vcpkg/buildtrees/openssl/src/1.1.1j-ff1006361a.clean
-- Found external ninja('1.10.2').
-- Configuring x64-osx-dbg
-- Configuring x64-osx-rel
-- Building x64-osx-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:146 (message):
    Command failed: /opt/homebrew/Cellar/cmake/3.20.1/bin/cmake --build . --config Debug --target install -- -v -j9
    Working Directory: /Users/limarev/local/vcpkg/buildtrees/openssl/x64-osx-dbg
    See logs for more information:
      /Users/limarev/local/vcpkg/buildtrees/openssl/install-x64-osx-dbg-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_build_cmake.cmake:105 (vcpkg_execute_build_process)
  scripts/cmake/vcpkg_install_cmake.cmake:45 (vcpkg_build_cmake)
  ports/openssl/unix/portfile.cmake:33 (vcpkg_install_cmake)
  ports/openssl/portfile.cmake:21 (include)
  scripts/ports.cmake:142 (include)

Error: Building package openssl:x64-osx failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `./vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: openssl:x64-osx
  Vcpkg version: 2021-01-13-unknownhash

Additionally, attach any relevant sections from the log files above.

[install-x64-osx-dbg-out.log](https://github.com/microsoft/vcpkg/files/6365400/install-x64-osx-dbg-out.log)

**Comment by autoantwort** [comment] 2021-04-23 13:03
duplicate of #17436

**Closed** 2021-04-23 14:42 UTC
