### ISSUE TITLE
Bug Install vcpkg

### ISSUE THREAD

**Issue by kamahall** [microsoft/vcpkg#17889] opened 2021-05-12 18:26 UTC
**Describe the bug**
````
`-- Build files have been written to: /root/vcpkg/buildtrees/_vcpkg/build
[0/2] Re-checking globbed directories...
[4/91] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o
FAILED: CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o
/usr/bin/g++-6 -DVCPKG_BASE_VERSION=2021-05-05 -DVCPKG_USE_STD_FILESYSTEM=0 -DVCPKG_VERSION=unknownhash -I/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include -O3 -DNDEBUG -std=c++1z -MD -MT CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -MF CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o.d -o CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -c /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp: In function ‘void load_config(vcpkg::Files::Filesystem&)’:
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:123:55: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’
         auto locked_metrics = Metrics::g_metrics.lock();
                                                       ^
In file included from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4:0,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17:
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: note: ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’ is implicitly deleted because the default definition would be ill-formed:
     struct LockGuardPtr
            ^~~~~~~~~~~~
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: error: use of deleted function ‘std::lock_guard<_Mutex>::lock_guard(const std::lock_guard<_Mutex>&) [with _Mutex = std::mutex]’
In file included from /usr/include/c++/6/mutex:44:0,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:5,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17:
/usr/include/c++/6/bits/std_mutex.h:170:7: note: declared here
       lock_guard(const lock_guard&) = delete;
       ^~~~~~~~~~
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp: In lambda function:
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:186:48: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’
         auto metrics = Metrics::g_metrics.lock();
                                                ^
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp: In function ‘int main(int, const char* const*)’:
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:207:55: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’
         auto locked_metrics = Metrics::g_metrics.lock();
                                                       ^
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:235:48: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’
         auto metrics = Metrics::g_metrics.lock();
                                                ^
In file included from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4:0,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17:
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h: In instantiation of ‘vcpkg::Util::LockGuardPtr<T> vcpkg::Util::LockGuarded<T>::lock() [with T = vcpkg::Metrics::Metrics]’:
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:51:29:   required from here
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:14:42: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’
         LockGuardPtr<T> lock() { return *this; }
                                          ^~~~
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:29:9: note:   after user-defined conversion: vcpkg::Util::LockGuardPtr<T>::LockGuardPtr(vcpkg::Util::LockGuarded<T>&) [with T = vcpkg::Metrics::Metrics]
         LockGuardPtr(LockGuarded<T>& sync) : m_lock(sync.m_mutex), m_ptr(sync.m_t) { }
         ^~~~~~~~~~~~
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h: In instantiation of ‘vcpkg::Util::LockGuardPtr<T> vcpkg::Util::LockGuarded<T>::lock() [with T = std::__cxx11::basic_string<char>]’:
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:137:36:   required from here
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:14:42: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<std::__cxx11::basic_string<char> >::LockGuardPtr(vcpkg::Util::LockGuardPtr<std::__cxx11::basic_string<char> >&&)’
         LockGuardPtr<T> lock() { return *this; }
                                          ^~~~
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: note: ‘vcpkg::Util::LockGuardPtr<std::__cxx11::basic_string<char> >::LockGuardPtr(vcpkg::Util::LockGuardPtr<std::__cxx11::basic_string<char> >&&)’ is implicitly deleted because the default definition would be ill-formed:
     struct LockGuardPtr
            ^~~~~~~~~~~~
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: error: use of deleted function ‘std::lock_guard<_Mutex>::lock_guard(const std::lock_guard<_Mutex>&) [with _Mutex = std::mutex]’
In file included from /usr/include/c++/6/mutex:44:0,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:5,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17:
/usr/include/c++/6/bits/std_mutex.h:170:7: note: declared here
       lock_guard(const lock_guard&) = delete;
       ^~~~~~~~~~
In file included from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4:0,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17:
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:29:9: note:   after user-defined conversion: vcpkg::Util::LockGuardPtr<T>::LockGuardPtr(vcpkg::Util::LockGuarded<T>&) [with T = std::__cxx11::basic_string<char>]
         LockGuardPtr(LockGuarded<T>& sync) : m_lock(sync.m_mutex), m_ptr(sync.m_t) { }
         ^~~~~~~~~~~~
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h: In instantiation of ‘vcpkg::Util::LockGuardPtr<T> vcpkg::Util::LockGuarded<T>::lock() [with T = vcpkg::Chrono::ElapsedTimer]’:
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:167:30:   required from here
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:14:42: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Chrono::ElapsedTimer>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Chrono::ElapsedTimer>&&)’
         LockGuardPtr<T> lock() { return *this; }
                                          ^~~~
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: note: ‘vcpkg::Util::LockGuardPtr<vcpkg::Chrono::ElapsedTimer>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Chrono::ElapsedTimer>&&)’ is implicitly deleted because the default definition would be ill-formed:
     struct LockGuardPtr
            ^~~~~~~~~~~~
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: error: use of deleted function ‘std::lock_guard<_Mutex>::lock_guard(const std::lock_guard<_Mutex>&) [with _Mutex = std::mutex]’
In file included from /usr/include/c++/6/mutex:44:0,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:5,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17:
/usr/include/c++/6/bits/std_mutex.h:170:7: note: declared here
       lock_guard(const lock_guard&) = delete;
       ^~~~~~~~~~
In file included from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4:0,
                 from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17:
/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:29:9: note:   after user-defined conversion: vcpkg::Util::LockGuardPtr<T>::LockGuardPtr(vcpkg::Util::LockGuarded<T>&) [with T = vcpkg::Chrono::ElapsedTimer]
         LockGuardPtr(LockGuarded<T>& sync) : m_lock(sync.m_mutex), m_ptr(sync.m_t) { }
         ^~~~~~~~~~~~
[9/91] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o
ninja: build stopped: subcommand failed.`
````
**Environment**
- OS: [e.g. Windows/Linux etc...]
- Compiler: revision

**To Reproduce**
1. ./vcpkg install xxxx
2. See error
Repro code when

**Expected behavior**

**Failure logs** 
-(please attached failure logs)

**Additional context**

Someone help me with this error please

**Comment by autoantwort** [comment] 2021-05-12 18:37
> Environment:
    OS: [e.g. Windows/Linux etc...]
    Compiler: revision
?

An please format your error message properly with
\```
The error
\```
Thanks :)

**Comment by kamahall** [comment] 2021-05-12 18:54
```-- Build files have been written to: /root/vcpkg/buildtrees/_vcpkg/build [0/2] Re-checking globbed directories... [4/91] Building CXX object CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o FAILED: CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o /usr/bin/g++-6 -DVCPKG_BASE_VERSION=2021-05-05 -DVCPKG_USE_STD_FILESYSTEM=0 -DVCPKG_VERSION=unknownhash -I/root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include -O3 -DNDEBUG -std=c++1z -MD -MT CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -MF CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o.d -o CMakeFiles/vcpkg.dir/src/vcpkg.cpp.o -c /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp: In function ‘void load_config(vcpkg::Files::Filesystem&)’: /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:123:55: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’ auto locked_metrics = Metrics::g_metrics.lock(); ^ In file included from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4:0, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17: /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: note: ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’ is implicitly deleted because the default definition would be ill-formed: struct LockGuardPtr ^~~~~~~~~~~~ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: error: use of deleted function ‘std::lock_guard<_Mutex>::lock_guard(const std::lock_guard<_Mutex>&) [with _Mutex = std::mutex]’ In file included from /usr/include/c++/6/mutex:44:0, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:5, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17: /usr/include/c++/6/bits/std_mutex.h:170:7: note: declared here lock_guard(const lock_guard&) = delete; ^~~~~~~~~~ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp: In lambda function: /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:186:48: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’ auto metrics = Metrics::g_metrics.lock(); ^ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp: In function ‘int main(int, const char* const*)’: /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:207:55: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’ auto locked_metrics = Metrics::g_metrics.lock(); ^ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:235:48: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’ auto metrics = Metrics::g_metrics.lock(); ^ In file included from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4:0, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17: /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h: In instantiation of ‘vcpkg::Util::LockGuardPtr<T> vcpkg::Util::LockGuarded<T>::lock() [with T = vcpkg::Metrics::Metrics]’: /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:51:29: required from here /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:14:42: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Metrics::Metrics>&&)’ LockGuardPtr<T> lock() { return *this; } ^~~~ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:29:9: note: after user-defined conversion: vcpkg::Util::LockGuardPtr<T>::LockGuardPtr(vcpkg::Util::LockGuarded<T>&) [with T = vcpkg::Metrics::Metrics] LockGuardPtr(LockGuarded<T>& sync) : m_lock(sync.m_mutex), m_ptr(sync.m_t) { } ^~~~~~~~~~~~ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h: In instantiation of ‘vcpkg::Util::LockGuardPtr<T> vcpkg::Util::LockGuarded<T>::lock() [with T = std::__cxx11::basic_string<char>]’: /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:137:36: required from here /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:14:42: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<std::__cxx11::basic_string<char> >::LockGuardPtr(vcpkg::Util::LockGuardPtr<std::__cxx11::basic_string<char> >&&)’ LockGuardPtr<T> lock() { return *this; } ^~~~ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: note: ‘vcpkg::Util::LockGuardPtr<std::__cxx11::basic_string<char> >::LockGuardPtr(vcpkg::Util::LockGuardPtr<std::__cxx11::basic_string<char> >&&)’ is implicitly deleted because the default definition would be ill-formed: struct LockGuardPtr ^~~~~~~~~~~~ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: error: use of deleted function ‘std::lock_guard<_Mutex>::lock_guard(const std::lock_guard<_Mutex>&) [with _Mutex = std::mutex]’ In file included from /usr/include/c++/6/mutex:44:0, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:5, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17: /usr/include/c++/6/bits/std_mutex.h:170:7: note: declared here lock_guard(const lock_guard&) = delete; ^~~~~~~~~~ In file included from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4:0, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17: /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:29:9: note: after user-defined conversion: vcpkg::Util::LockGuardPtr<T>::LockGuardPtr(vcpkg::Util::LockGuarded<T>&) [with T = std::__cxx11::basic_string<char>] LockGuardPtr(LockGuarded<T>& sync) : m_lock(sync.m_mutex), m_ptr(sync.m_t) { } ^~~~~~~~~~~~ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h: In instantiation of ‘vcpkg::Util::LockGuardPtr<T> vcpkg::Util::LockGuarded<T>::lock() [with T = vcpkg::Chrono::ElapsedTimer]’: /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:167:30: required from here /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:14:42: error: use of deleted function ‘vcpkg::Util::LockGuardPtr<vcpkg::Chrono::ElapsedTimer>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Chrono::ElapsedTimer>&&)’ LockGuardPtr<T> lock() { return *this; } ^~~~ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: note: ‘vcpkg::Util::LockGuardPtr<vcpkg::Chrono::ElapsedTimer>::LockGuardPtr(vcpkg::Util::LockGuardPtr<vcpkg::Chrono::ElapsedTimer>&&)’ is implicitly deleted because the default definition would be ill-formed: struct LockGuardPtr ^~~~~~~~~~~~ /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:22:12: error: use of deleted function ‘std::lock_guard<_Mutex>::lock_guard(const std::lock_guard<_Mutex>&) [with _Mutex = std::mutex]’ In file included from /usr/include/c++/6/mutex:44:0, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:5, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17: /usr/include/c++/6/bits/std_mutex.h:170:7: note: declared here lock_guard(const lock_guard&) = delete; ^~~~~~~~~~ In file included from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/metrics.h:4:0, from /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/src/vcpkg.cpp:17: /root/vcpkg/buildtrees/_vcpkg/src/vcpkg-tool-2021-05-05-9f849c4c43e50d1b16186ae76681c27b0c1be9d9/include/vcpkg/base/lockguarded.h:29:9: note: after user-defined conversion: vcpkg::Util::LockGuardPtr<T>::LockGuardPtr(vcpkg::Util::LockGuarded<T>&) [with T = vcpkg::Chrono::ElapsedTimer] LockGuardPtr(LockGuarded<T>& sync) : m_lock(sync.m_mutex), m_ptr(sync.m_t) { } ^~~~~~~~~~~~ [9/91] Building CXX object CMakeFiles/vcpkglib.dir/src/vcpkg/base/files.cpp.o ninja: build stopped: subcommand failed.```

**Comment by JonLiu1993** [comment] 2021-05-13 02:49
@kamahall ,Please provide your Windows version, Visual Studio version ,and wuich port you installed? 

Thanks

**Comment by JackBoosY** [comment] 2021-05-13 02:55
Which system do you use? Apple or Linux? And please provide the system version.

Thanks.

**Comment by autoantwort** [comment] 2021-05-13 08:30
duplicate of #17897

**Closed** 2021-05-13 08:34 UTC
Labels: requires:more-information, requires:repro
