### ISSUE TITLE
PDCurses install fails on Linux

### ISSUE THREAD

**Issue by simple-hash** [microsoft/vcpkg#9812] opened 2020-01-24 15:05 UTC
```
[root@localhost vcpkg]# ./vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
[root@localhost vcpkg]# ./vcpkg install pdcurses
The following packages will be built and installed:
    pdcurses[core]:x64-linux
Starting package 1/1: pdcurses:x64-linux
Building package pdcurses[core]:x64-linux...
-- Using cached /opt/vcpkg/downloads/wmcbrine-PDCurses-2467ab2b6c07163d0171b80ad6c252c29da28173.tar.gz
-- Using source at /opt/vcpkg/buildtrees/pdcurses/src/c29da28173-04343f6e37
-- Build x64-linux-rel
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
    Command failed: NMAKE-NOTFOUND /A -f /opt/vcpkg/buildtrees/pdcurses/src/c29da28173-04343f6e37/wincon/Makefile.vc WIDE=Y UTF8=Y
    Working Directory: /opt/vcpkg/buildtrees/pdcurses/src/c29da28173-04343f6e37/wincon
    Error code: No such file or directory
    See logs for more information:

Call Stack (most recent call first):
  ports/pdcurses/portfile.cmake:23 (vcpkg_execute_required_process)
  scripts/ports.cmake:94 (include)


Error: Building package pdcurses:x64-linux failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: pdcurses:x64-linux
  Vcpkg version: 2019.09.12-unknownhash

Additionally, attach any relevant sections from the log files above.
```

**Comment by GitMensch** [comment] 2021-09-22 06:24
As noted in #14620 (which _may_ be seen as duplicate of this issue) the problem is that also for osx and linux the port tries to use the wincon port - while it should use either the sdl2 or x11 ports.

**Comment by PhoebeHui** [comment] 2021-09-26 02:46
Closing in favor of https://github.com/microsoft/vcpkg/issues/14620.

**Closed by PhoebeHui** 2021-09-26 02:46 UTC
Labels: category:port-feature
