### ISSUE TITLE
Fortran support

### ISSUE THREAD

**Issue by albertziegenhagel** [microsoft/vcpkg#485] opened 2017-01-03 14:23 UTC
There are some port requests on the tracker that require a Fortran compiler to compile the respective libraries (#23, #233). I want to create this issue to start a discussion on how Fortran support could be brought to vcpkg.

Since Visual Studio does not come with a Fortran compiler, on Windows one usually uses one of the following

- Intel Fortran (ifort)
- gfortran through MinGW/MSYS

Intel Fortran is proprietary and thus may not be available for everyone but it has a nice Visual Studio integration which makes it pretty straight forward to consume libraries compiled with ifort from within Visual Studio.

gfortran on the other hand is free but does not have an integration into Visual Studio. In general one uses MinGW/MSYS to compile fortran libraries for windows when using gfortran. This comes with some implications:

- one can not use the Visual Studio generator in CMake but instead has to use some makefile system that is supported by MSYS (GNU Makefiles in general). As far as I know there is a special branch of ninja with fortran support maintained by kitware (https://github.com/Kitware/ninja) but I have no experience in using it and do not know how far the implementation is.
- The compiled libraries will be linked against the gcc and gfortran runtime libraries provided by MinGW.
- When compiling projects that include both Fortran and C or C++ code gcc/g++ is used to compile the C/C++ code instead of Visual C++.

So the first question would be which version should implemented in vcpkg:

1. Intel Fortran (in my opinion more easy to implement)
2. gfortran (may be preferred since it is free)
3. both (choice is always the best solution. Triplets could be used to determine which toolset to use)

I do not have a lot of experience in using gfortran on windows but I do have a port for netlib blas+lapack (http://www.netlib.org/lapack/) which works with some minor additional modifications to vcpkg itself when using Intel Fortran.

**Comment by traversaro** [comment] 2017-01-03 16:10
As discussed in https://github.com/Microsoft/vcpkg/issues/233, at least initially I am for using Intel Fortran. However, I fear that requiring all the `vcpkg` users that want to install Fortran-dependent ports to buy the Intel Fortran compiler is a too much limiting. A possible workaround is to upload the binaries produced using Intel Fortran to a website and then let the port download them in binary form, as it is already done for ports such as `tbb`. 

Perhaps Microsoft could provide some support for hosting such binaries produced by the community? @ras0219-msft @alexkaratarakis

**Comment by traversaro** [comment] 2017-01-03 16:27
More in the long term, it would be interesting to see how the `flang` project  for integrating a Fortan compiled in  LLVM evolves. It was announced one year ago by PGI/Nvidia and it still not open source, but it is in progress. [1] 
Considering LLVM compatibility with Visual Studio ABI, perhaps _in a few years_ it could be a viable solution for `vcpkg`. : ) 

[1] : https://developer.arm.com/-/media/developer/developers/hpc/files/ARM-HPC-UG-SC16-PGI.pdf

**Comment by traversaro** [comment] 2017-01-03 20:43
On the use of `gfortran`: checking [Lapack documentation on how to build it on Windows](http://icl.cs.utk.edu/lapack-for-windows/lapack/index.html) I discovered of the [`GNUtoMS`](https://cmake.org/cmake/help/v3.7/prop_tgt/GNUtoMS.html) CMake property, described in [this article](http://www.netlib.org/lapack/lawnspdf/lawn270.pdf) regarding the improvement to Fortran support in CMake.

**Comment by ras0219-msft** [comment] 2017-01-19 01:17
Requiring Intel Fortran for a complete out-of-the-box experience is definitely not desirable considering its licensing. However, it does look like it's a very popular (the most popular?) solution on Windows, so we should support it. This is exactly what triplets should do -- specify the toolchain and build parameters to be used for all built libraries.

We can totally handle tools that don't have VS IDE integration; we could easily download Ninja or use MSYS internally as long as we can produce crt-compatible libraries out the other side.

As for hosting prebuilt binaries -- assuming it is fine with the intel fortran license (I'm not too familiar on this point), we could very easily host them inside the NuGet gallery, treating the NuGet package as a simple zip archive of the prebuilt binaries. We even already have the capability to download the NuGet.exe tool (for the MSBuild per-project integration).

As has been mentioned many times elsewhere, building from source would be preferable for users who can (i.e. that have intel fortran), but it's better to have binaries than nothing at all -- as long as the fortran library doesn't have dependencies. We don't want the fact that library X required a binary drop to obstruct the maintainer of dependency Y from updating.

**Comment by albertziegenhagel** [comment] 2017-01-19 05:45
The only thing I had to change to make it work with the Intel Compiler was to remove the extra arguments that are passed to "cmake --build" in vcpkg_install_cmake and vcpkg_build_cmake. This is because when the Visual Studio project files include Fortran code, "cmake --build" will invoke devenv.exe instead of msbuild.exe which will not understand the extra arguments.
Maybe an additional parameter that is passed to vcpkg_install_cmake and vcpkg_build_cmake to disable all extra arguments can be introduced (just like the one that has recently been introduced to disable the /m switch only).

The Intel compiler always got detected correctly by cmake automatically. I don't know whether this is the case under all circumstances (e.g. if you have multiple versions installed) but one could always set "CMAKE_Fortran_COMPILER" in the triplet. The problem would here would be to auto-detect and choose the correct paths to ifort.exe.

**Comment by traversaro** [comment] 2017-02-04 11:00
> As for hosting prebuilt binaries -- assuming it is fine with the intel fortran license (I'm not too familiar on this point), we could very easily host them inside the NuGet gallery, treating the NuGet package as a simple zip archive of the prebuilt binaries. We even already have the capability to download the NuGet.exe tool (for the MSBuild per-project integration).

Interesting read on this: 
https://software.intel.com/en-us/forums/intel-visual-fortran-compiler-for-windows/topic/626497

**Comment by traversaro** [comment] 2017-02-04 11:32
I think that this approach https://github.com/Microsoft/vcpkg/issues/23#issuecomment-277437432 to packaging a fortran library such as LAPACK is relevant also here.

**Comment by traversaro** [comment] 2017-05-19 07:10
The preliminary version of the flang compiler (based on PGI frontend) was open sourced in https://github.com/flang-compiler/flang . I don't think it is ready for use in vcpkg (I doubt there are binary availables) but it is interesting to look at it.

**Comment by albertziegenhagel** [comment] 2017-05-19 07:34
Very interesting! As far as I can see there is no official announcement available yet?!

I will go on and compile everything and try how far I can get with it. If it is just the missing binaries we may will be able to host the binaries ourselves somewhere.

**Comment by traversaro** [comment] 2017-05-19 10:09
> As far as I can see there is no official announcement available yet?! 
Apparently no: http://www.phoronix.com/scan.php?page=news_item&px=LLVM-NVIDIA-Fortran-Flang .

**Comment by jakirkham** [comment] 2017-05-25 16:39
Would be curious to hear about your experiences with Flang. We (at [conda-forge]( http://conda-forge.github.io/ )) have been eyeing progress on it for some time (though it was only recently open sourced). In particular, we were looking at it for building things like OpenBLAS and SciPy, but inevitably including Fortran support for other things.

**Comment by traversaro** [comment] 2017-07-18 07:42
Relevant flang issue on Windows support: https://github.com/flang-compiler/flang/issues/143 .

**Comment by traversaro** [comment] 2017-09-23 14:34
Good news regarding support for `ucrtbase.dll` support in `mingw-w64`, if I understood correctly, at least partial support for `ucrtbase.dll` has been merged in the master branch : 
* https://sourceforge.net/p/mingw-w64/mailman/mingw-w64-public/thread/1505134111-13637-2-git-send-email-martin%40martin.st/#msg36033731
* https://sourceforge.net/p/mingw-w64/mingw-w64/ci/bc6a87488995675ae80c312e3585cb1ace739b43/log/?path=

I don't know if this directly affects the libraries build with gfortran, and when this will be available in a released version of `mingw-w64` .

**Comment by albertziegenhagel** [comment] 2017-09-25 07:55
This sound like great news!

The PR at #1098 already includes MinGW+w64 support, but it requires the not yet released version of CMake 3.10 to support GnuToMS for the Ninja generator and of course has the known problems of linking against msvcrt.

I am really looking forward to a release version of MinGW that includes the final ucrt suppprt.

**Comment by xoviat** [comment] 2017-10-17 18:12
Ironically, using vcpkg to build flang would be the most time-efficient method to get a fortran compiler with MSVC ABI compatibility. **But**,  MSVC does not have OpenMP 4.0, which flang requires. So essentially, the steps would be:

1. Add clang support to vcpkg (clang has ABI compatibility with MSVC and supports OpenMP 4.0).
2. Fill in the required libraries (specifically, clang-flang, which is a modified clang)
3. Add `openmp-llvm` to the ports.
4. Use vcpkg to install the libraries and then build flang with MSVC.

Now whether this will actually happen is a different story MSFT might not want to add clang support to this project because then people may obviously not use their compiler. But based on their responses, there is little chance of MSVC adding OpenMP 4 support.

In other words, this is technically solvable, but when business interests / people come into the picture it might not be (and I have nothing against MSFT; I think it's a good company and I think this is an excellent project that was long overdue).

**Comment by albertziegenhagel** [comment] 2017-10-18 12:24
@xoviat have you tried to build flang for windows with the described method manually? And then use that flang binary to build any fortran code on windows? As far as I understood, flang does not yet support windows at all (not only being build by MSVC, but in general. Correct me if I am wrong!).

**Comment by xoviat** [comment] 2017-10-18 14:30
Flang supports windows but someone just needs to build it, which is not trivial for the same reason that vcpkg exists.

**Comment by jakirkham** [comment] 2017-10-18 14:36
If that's true, why aren't there any updates in issue ( https://github.com/flang-compiler/flang/issues/143 )? Where has this work been occurring?

**Comment by xoviat** [comment] 2017-10-18 14:39
No one has built it yet but it's "just" CMake.

**Comment by xoviat** [comment] 2017-10-18 15:36
Actually, after reconsidering the problem, it's possible to override the generator with a `PreLoad.cmake`. If my theory is correct, then we don't actually need MSFT to modify the tool sources to build `openmp-llvm`. I think we have a viable path forward.

So to summarize, we need ports for:
-`openmp-llvm`
- `clang-flang`

If someone else wants to port one of these, then I may port the other.

**Comment by muemart** [comment] 2017-10-18 16:51
i don't think even ports are necessary. We could just precompile flang and treat it like one of the external tools, and then use it like that. Though I'm not sure if flang is actually buildable on Windows, even with msys2 and friends.

**Comment by xoviat** [comment] 2017-10-18 16:57
> Though I'm not sure if flang is actually buildable on Windows, even with msys2 and friends.

Let me be clear: flang is buildable on windows, but it has a complex dependency chain, which is the exact problem that vcpkg was designed to solve. The *only* problem is  that one dependency is `openmp-llvm`, which MSVC can't build. However, it appears that the default generator can be overridden, making it buildable with once the above libraries are ported.

>  We could just precompile flang

Yes, but precompiling is **the** problem. The libraries aren't there yet. But they could be with vcpkg.

**Comment by jakirkham** [comment] 2017-10-18 18:37
LLVM's `openmp` is definitely buildable on Windows. We build it in conda-forge currently.

ref: https://github.com/conda-forge/openmp-feedstock

**Comment by xoviat** [comment] 2017-10-18 18:38
With MSVC?

**Comment by xoviat** [comment] 2017-10-18 18:40
Update: looks like you are using clang as well. So essentially what I've already said. 

@jakirkham Can conda install the headers and libs? If so, then the problem could be solved!

**Comment by xoviat** [comment] 2017-10-18 18:41
Assuming yes, we just need a port for `clang-flang`. That is completely doable.

**Comment by xoviat** [comment] 2017-10-18 19:05
PR: #2010.

**Comment by xoviat** [comment] 2017-10-20 15:31
@albertziegenhagel Thanks so much for doing that. I was given incorrect information apparently. What I'm going to do then is work on the POSIX API issue and then we can try again when the C code is compatible.

**Comment by isuruf** [comment] 2017-10-20 16:41
@xoviat, yes conda-forge package has the headers and libraries.

**Comment by jakirkham** [comment] 2017-10-20 20:10
> Update: looks like you are using clang as well. So essentially what I've already said.

I think it is just using [vanilla MSVC]( https://ci.appveyor.com/project/conda-forge/openmp-feedstock/build/1.0.1/job/937f6ke4kbntes36#L462 ). We only require [`llvmdev`]( https://github.com/conda-forge/openmp-feedstock/blob/19490e0d2f043e318e6140e9b831c0eb9010b114/recipe/meta.yaml#L25 ) (static build of LLVM) be present, but we don't actually install `clang` for the `build`. We do require `clang` at run time though.

**Comment by xoviat** [comment] 2017-10-20 20:12
Interesting. My research on that topic was apparently not correct.

**Comment by xoviat** [comment] 2017-10-21 00:10
Actually, I have another wild idea that may be more practical than any of the current options. It is a bit complex if done manually but can be made to work seamlessly with a bit of vcpkg coordination.

Windows now has the "Windows Subsystem for Linux," which is essentially a way to run ubuntu applications inside windows. In addition, flang can target LLVM IR. So essentially what we need to do is install flang within the "Subsystem for Linux" and then we can have an executable file that simply does the following:

1. Takes the input file and copies it to a temporary location within the subsystem for Linux
2. Runs flang inside the subsystem for Linux and generates LLVM IR
3. Copies the LLVM IR back to the windows space and compiles it with LLVM

Sounds a bit tricky and somewhat complicated. But how difficult can it be to write a script that simply copies a few files and runs a few commands? And then maybe optimize that script by rewriting it in a lower-level language (like C++, which I know the vcpkg folks love).

@ras0219-msft What do you think of that idea? Sounds completely doable to me.

**Comment by ras0219-msft** [comment] 2017-10-21 03:27
If you could make that work, that would be really cool! I'd be happy to merge support in that form :)

**Comment by xoviat** [comment] 2017-10-29 18:28
Update: we've built flang on win32. I expect there to be bugs but we need real-world testing to find them. I'm going to look at the existing fortran PR and look to update it.

Flang on win32 requires:
- a development version of CMake (changes may not even be in `master`, but they will soon)
- the following cmake configuration flags:

> cmake -G "NMake Makefiles" -DCMAKE_Fortran_COMPILER=flang -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_BUILD_TYPE=Release

**Comment by xoviat** [comment] 2017-10-29 18:32
Also, thanks so much to @isuruf  and @albertziegenhagel who made this possible.

**Comment by isuruf** [comment] 2017-10-29 18:36
@xoviat, with https://github.com/isuruf/flang/commit/970f43bb7387a4f29b1b7a87cace277b64da55ec, I don't think we need development version. Latest is fine.

**Comment by xoviat** [comment] 2017-10-29 18:42
Okay.

**Comment by jakirkham** [comment] 2017-10-29 18:56
Nice work! Is there a PR with the conda recipe somewhere?

**Comment by isuruf** [comment] 2017-10-29 20:50
I'm working on the conda recipe here, https://github.com/isuruf/staged-recipes/tree/flang2
This needs a custom `clangdev` package as well.

**Comment by ras0219-msft** [comment] 2017-10-30 02:04
Will conda have a prebuilt binary package we can download? There's really no reason to build the Fortran compiler itself from source for us; only the Fortran libraries themselves.

**Comment by isuruf** [comment] 2017-10-30 02:06
you can do,
```
conda config --add channels conda-forge
conda config --add channels isuruf/label/flang
conda install flangdev
```
to download the compiler and the runtime libraries

**Comment by xoviat** [comment] 2017-10-31 18:43
@ras0219-msft Do you have any questions about how to download the compiler or need help creating a redistributable? What are the next steps and what do you need from us?

**Comment by albertziegenhagel** [comment] 2017-10-31 18:54
Is there a way to download the executables from your conda package as an archive file (without having to install conda)? If that would be possible I could very easily integrate flang as Fortran compiler in my PR #1098. Else I could upload my own builds of flang somewhere.

To make this work, we would need to finish the cmake integration at [1].

[1] https://gitlab.kitware.com/cmake/cmake/merge_requests/1430

**Comment by xoviat** [comment] 2017-10-31 19:00
> Is there a way to download the executables from your conda package as an archive file (without having to install conda)?

The conda installer is just "resolve, download and spread." Of course, it's a .tar.bz2 format, but you can resolve dependencies using paper and pencil and then download the archives directly from the website. The spread part is just unpacking to different directories.

**Comment by xoviat** [comment] 2017-10-31 19:02
Here's the resolver solution for flang:

```
   clangdev:  4.0.0-flang_git_2b0d6a5_0 isuruf/label/flang [vc14]
    flangdev:  4.0.0.git.fd7f1c0-vc14_0  isuruf/label/flang [vc14]
    libiconv:  1.14-vc14_4               conda-forge        [vc14]
    libxml2:   2.9.5-vc14_0              conda-forge        [vc14]
    llvmdev:   4.0.0-default_0           conda-forge        [vc14]
    openmp:    4.0.0-vc14_0              conda-forge        [vc14]
    zlib:      1.2.11-vc14_0             conda-forge        [vc14]
```

**Comment by albertziegenhagel** [comment] 2017-10-31 19:14
Perfect, thank you!

`.tar.bz2`  should not be a problem. I will integrate this tomorrow and then try to build all the fortran ports I have with it.

**Comment by albertziegenhagel** [comment] 2017-11-06 10:13
I've implemented initial support for Flang in #1098 based on the binaries provided in the conda packages of @isuruf.

Currently one needs to make sure a CMake version that includes the patches from [1] is in the PATH before calling vcpkg.

I was able to build reference LAPACK (including BLAS) with that configuration. I did not check whether the resulting binaries do actually work correctly. I will try my other Fortran ports soon.

[1] https://gitlab.kitware.com/cmake/cmake/merge_requests/1430

**Comment by isuruf** [comment] 2017-11-09 22:43
@albertziegenhagel, we published the packages in conda-forge and cleaned up dependencies a bit. The solver resolution is now
```
clangdev:       5.0.0-flang_1 conda-forge [flang vc14]
flang:          5.0.0-vc14_1  conda-forge [vc14      ]
libflang:       5.0.0-vc14_1  conda-forge [vc14      ]
openmp:         5.0.0-vc14_0  conda-forge [vc14      ]
```

**Comment by albertziegenhagel** [comment] 2017-11-13 09:07
Sorry for the delay, but I've now updated the PR to download the new version from conda-forge.

Btw: I could build LAPACK and ScaLAPACK with flang, but when I try to compile MUMPS it fails with a message about a missing header, although on the first look it seems that the correct include path is set. If you want to try it yourself:

- checkout the branch `fortran-ports` from https://github.com/albertziegenhagel/vcpkg/tree/fortran-ports
- Add `set(VCPKG_FORTRAN_COMPILER Flang)` to the triplet file
- Make sure a current CMake build is your PATH
- Try `vcpkg install mumps`

**Comment by atkawa7** [comment] 2018-01-30 18:29
@albertziegenhagel   Thank you for your work on integrating fortran on vcpkg. Just wondering if you were able to make fortran work. @ras0219-msft Regarding the choice of the fotran compiler. Shouldn't we leave that decision to the user.  I prefer using intel  fortran compiler. So if we choose flang it feels as if vcpkg had locked us in.

**Comment by albertziegenhagel** [comment] 2018-01-31 10:11
@atkawa7 I am using fortran libraries build via vcpkg locally all the time through #1098. There you have the option to select the fortran compiler in the triplet file with currently `Intel`, `PGI`, `GNU (MinGW gfortran)` and `Flang` as options (with the last two being experimental). I would prefer to keep those options available. `Flang` can be used as a default, since it is free and promises to have the best compatibility with the rest of the "msvc environment".

**Comment by claudiofantacci** [comment] 2018-09-24 11:50
Hi everyone, how is this PR evolving?
Is there any chance to see https://github.com/Microsoft/vcpkg/pull/1098 going through 😄?

**Comment by traversaro** [comment] 2019-01-11 09:33
I obviously can't speak for vcpkg mantainers, but I guess one of the reasons https://github.com/Microsoft/vcpkg/pull/1098 cannot be merged is that it three out of the four supported compilers cannot be maintained in a "clean" way (please correct me if I am getting something wrong): 
* `Intel` : It is not possible to maintain/debug problems, unless you have the (relatively expensive) license for it.
* `Flang` : The Windows version shipped through conda is a fork of upstream flang, that itself requires a fork of upstream llvm and clang. I saw that now work has started on `f18`, a modern fortran compielr that will aim for upstream llvm integration, but I guess it will take years to be completed  and integrated upstream. 
* `PGI` : The main problem there is the 1 year time-bomb condition discussed in https://github.com/Microsoft/vcpkg/pull/1098#issuecomment-302056376 and the related EULA. 

Do not get me wrong, I am a huge fan of the work of @albertziegenhagel , I just suspect these are the reasons why it can't be integrated upstream, and I thought it could be useful to have recap of them at this moment. 

The only remaining option is `GNU (MinGW gfortran)`, that back in time had the major drawback on not being able to link to the [`ucrt` runtime library](https://docs.microsoft.com/en-us/cpp/c-runtime-library/c-run-time-library-reference?view=vs-2017) used since VS2015, and it required instead an older crt, see https://github.com/Microsoft/vcpkg/issues/485#issuecomment-331804641 . I recently checked on the Mingw-w64 website, and apparently in the last year they had several releases that improved support for linking with ucrt (thanks to the amazing work  of @mstorsjo), see for example https://mingw-w64.org/doku.php and https://sourceforge.net/p/mingw-w64/mailman/message/36416777/ . If someone is interested in streamlining Fortran support in upstream vcpkg, perhaps it could make sense to try to update @albertziegenhagel's fork to use the latest Mingw-w64 to see if the ucrt support is advanced enough to produce usable fortran libraries, or if there are other tricky issues.

**Comment by fcooper8472** [comment] 2019-01-11 12:49
@traversaro thanks for summarising.  It looks as though there is at least **some** problem with each of the four options of `Intel`, `Flang`, `PGI`, and `GNU`.

Surely, though, **some** fortran support is better than **no** fortran support?  I have successfully used @albertziegenhagel's fork in the past, and it would be great to integrate that functionality properly into vcpkg.

Why, for instance, does the issue you raise with `Flang` prevent it being a perfectly adequate solution for vcpkg?

**Comment by traversaro** [comment] 2019-03-16 13:45
Some interesting recent discussion related to this issue:
* https://github.com/isuruf/flang/issues/129#issuecomment-465851596 : Recent discussion in the Python community on a Fortran UCRT-compatible, involving the same people behind the conda's Flang port (cc @rgommers that may be interested in this discussion) 
* http://lists.llvm.org/pipermail/llvm-dev/2019-February/130497.html : RFC for comment for moving the development of the new experimental [f18](https://github.com/flang-compiler/f18) Fortran LLVM front-end to LLVM upstream. The front-end is not a currently able to generate code (see http://lists.llvm.org/pipermail/llvm-dev/2019-March/130694.html for an update on a current progress) but in the long-term it could be a good solution.
* In the f18 llvm-dev thread, they posted a link to http://fort-compiler.org/, another Fortran front end for LLVM that I had never heard of.

**Comment by traversaro** [comment] 2019-04-10 22:54
> http://lists.llvm.org/pipermail/llvm-dev/2019-February/130497.html : RFC for comment for moving the development of the new experimental f18 Fortran LLVM front-end to LLVM upstream. The front-end is not a currently able to generate code (see http://lists.llvm.org/pipermail/llvm-dev/2019-March/130694.html for an update on a current progress) but in the long-term it could be a good solution.

http://lists.llvm.org/pipermail/llvm-dev/2019-April/131703.html
The f18  Fortran LLVM front-end will be integrated in LLVM upstream.

**Comment by gmanlan** [comment] 2019-04-23 02:46
@ghost: is the flang win32 version actually 32 bit or you mean x64? conda-forge has dropped support for Windows 32 bit so only 64 bit packages can be found. Have you produced a 32 bit version of flang? If so, it is published through a conda channel or available as a standalone tar?

I have tried the channel isuruf/label/flang but no luck.

**Comment by isuruf** [comment] 2019-04-26 03:21
@gmanlan, it's x64. flang doesn't support 32 bit version.

**Comment by BillyONeal** [comment] 2020-09-03 21:26
I note that there are ports using fortran at this time so the original issue filing appears to be resolved, but as you note above there are still some 'holes' in that support. You might want to consider opening issues for the specific CRT problems above to make it easier for folks familiar with this problem space to find. I'll leave this open for now though.

**Comment by Neumann-A** [comment] 2021-01-07 13:03
Since Intel OneAPI is freely available now and includes the intel fortran compiler ifort we should try to switch from gfortran to ifort if it is possible to install Intel OneAPI on the CI machines.  This should in theory cleanly resolve the CRT problems.

**Comment by traversaro** [comment] 2021-07-16 08:02
For what regards CRT problems, I recently noticed that msys2 now provides ucrt-based builds on top of the already existing `MINGW64` builds: https://packages.msys2.org/package/mingw-w64-ucrt-x86_64-gcc-fortran?repo=ucrt64 . If people are still interested in this, a possible strategy may be to switch the `vcpkg-gfortran` port (added in https://github.com/microsoft/vcpkg/pull/12805) to use the ucrt gfortran version.

**Closed** 2021-07-22 07:52 UTC
Labels: category:vcpkg-feature
