### ISSUE TITLE
[glib] Upgrade glib and use meson build system.

### ISSUE THREAD

**Issue by vlj** [microsoft/vcpkg#11476] opened 2020-05-20 19:08 UTC
glib  port is 3 years old and use a custom CMakeSystem.
glib now uses meson as a build system. Since vcpkg now supports this build system it would be better to use it to ease maintainability.

**Comment by geraldcombs** [comment] 2020-11-29 18:59
Duplicate of #10389?

**Comment by JackBoosY** [comment] 2020-11-30 03:05
Will fixed in #13100, and duplicated to #10389.

**Closed by JackBoosY** 2020-11-30 03:05 UTC
Labels: category:port-feature
