### ISSUE TITLE
Build library fails if toolset path has Unicode chars

### ISSUE THREAD

**Issue by Swinki3** [microsoft/vcpkg#3017] opened 2018-03-12 22:29 UTC
Sample output:

```
E:\Src\Vcpkg>vcpkg install sdl2
The following packages will be built and installed:
    sdl2[core]:x86-windows
Starting package 1/1: sdl2:x86-windows
Building package sdl2[core]:x86-windows...
Could not locate a complete toolset.
The following paths were examined:
    E:\Pliki programĂŻÂżÂ˝w (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat
```

Correct path is E:\Pliki programów (x86)\Microsoft Visual Studio 14.0

**Comment by Chronial** [comment] 2021-09-26 21:42
This is probably a case of #5995

**Comment by WangWeiLin-MV** [comment] 2024-05-29 09:03
Duplicate of #5995

**Closed by WangWeiLin-MV** 2024-05-29 09:03 UTC
Labels: category:vcpkg-bug
