### ISSUE TITLE
[libtorch] Build error on x64-windows

### ISSUE THREAD

**Issue by WangHHY19931001** [microsoft/vcpkg#37057] opened 2024-03-01 03:16 UTC
Copy issue body from C:/vcpkg/installed/vcpkg/issue_Package: libtorch[core,cuda,dist,fftw3,leveldb,llvm,opencv,vulkan,xnnpack,zstd]:x64-windows@2.1.2

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.39.33521.0
-    vcpkg-tool version: 2024-02-07-8a83681f921b10d86ae626fd833c253f4f8c355b
    vcpkg-scripts version: 2ac6ba173 2024-02-28 (6 hours ago)

**To Reproduce**

`vcpkg install libtorch[llvm,vulkan,zstd,leveldb,fftw3,dist,cuda,opencv]:x64-windows openssl:x64-windows openssl:x64-windows-static cppcodec:x64-windows cppcodec:x64-windows-static`
**Failure logs**

```
-- Downloading https://github.com/pytorch/pytorch/archive/v2.1.2.tar.gz -> pytorch-pytorch-v2.1.2.tar.gz...
-- Extracting source C:/vcpkg/downloads/pytorch-pytorch-v2.1.2.tar.gz
-- Applying patch cmake-fixes.patch
-- Applying patch more-fixes.patch
-- Applying patch fix-build.patch
-- Applying patch clang-cl.patch
-- Applying patch cuda-adjustments.patch
-- Applying patch fix-api-export.patch
-- Applying patch fix-onnx-case.patch
-- Applying patch fxdiv.patch
-- Applying patch protoc.patch
-- Applying patch fix-sleef.patch
-- Applying patch fix-glog.patch
-- Applying patch fix-msvc-ICE.patch
-- Using source at C:/vcpkg/buildtrees/libtorch/src/v2.1.2-092a41c81b.clean
-- Downloading https://github.com/pytorch/kineto/archive/49e854d805d916b2031e337763928d2f8d2e1fbf.tar.gz -> pytorch-kineto-49e854d805d916b2031e337763928d2f8d2e1fbf.tar.gz...
-- Extracting source C:/vcpkg/downloads/pytorch-kineto-49e854d805d916b2031e337763928d2f8d2e1fbf.tar.gz
-- Applying patch kineto.patch
-- Using source at C:/vcpkg/buildtrees/libtorch/src/2f8d2e1fbf-de7a6d4b27.clean
-- Downloading https://github.com/NVIDIA/cudnn-frontend/archive/12f35fa2be5994c1106367cac2fba21457b064f4.tar.gz -> NVIDIA-cudnn-frontend-12f35fa2be5994c1106367cac2fba21457b064f4.tar.gz...
-- Extracting source C:/vcpkg/downloads/NVIDIA-cudnn-frontend-12f35fa2be5994c1106367cac2fba21457b064f4.tar.gz
-- Using source at C:/vcpkg/buildtrees/libtorch/src/1457b064f4-11f2c20faf.clean
-- Downloading https://github.com/NVIDIA/cutlass/archive/6f47420213f757831fae65c686aa471749fa8d60.tar.gz -> NVIDIA-cutlass-6f47420213f757831fae65c686aa471749fa8d60.tar.gz...
-- Extracting source C:/vcpkg/downloads/NVIDIA-cutlass-6f47420213f757831fae65c686aa471749fa8d60.tar.gz
-- Using source at C:/vcpkg/buildtrees/libtorch/src/1749fa8d60-777f8079ff.clean
-- Using flatc: C:/vcpkg/installed/x64-windows/tools/flatbuffers/flatc.exe
-- Using protoc: C:/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe
-- Downloading https://github.com/pypa/get-pip/archive/38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz -> pypa-get-pip-38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz...
-- Extracting source C:/vcpkg/downloads/pypa-get-pip-38e54e5de07c66e875c11a1ebbdb938854625dd8.tar.gz
-- Using source at C:/vcpkg/buildtrees/libtorch/src/8854625dd8-861bd167bd.clean
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/vcpkg/downloads/tools/python/python-3.11.5-x64/python.exe C:/vcpkg/buildtrees/libtorch/src/8854625dd8-861bd167bd.clean/public/get-pip.py --no-warn-script-location
    Working Directory: C:/vcpkg/buildtrees/libtorch
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\libtorch\get-pip-x64-windows-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-get-python-packages/x_vcpkg_get_python_packages.cmake:48 (vcpkg_execute_required_process)
  ports/libtorch/portfile.cmake:75 (x_vcpkg_get_python_packages)
  scripts/ports.cmake:172 (include)



```
<details><summary>C:\vcpkg\buildtrees\libtorch\get-pip-x64-windows-err.log</summary>

```
Traceback (most recent call last):
  File "C:\vcpkg\buildtrees\libtorch\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 33324, in <module>
    main()
  File "C:\vcpkg\buildtrees\libtorch\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 135, in main
    bootstrap(tmpdir=tmpdir)
  File "C:\vcpkg\buildtrees\libtorch\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 111, in bootstrap
    monkeypatch_for_cert(tmpdir)
  File "C:\vcpkg\buildtrees\libtorch\src\8854625dd8-861bd167bd.clean\public\get-pip.py", line 92, in monkeypatch_for_cert
    from pip._internal.commands.install import InstallCommand
  File "C:\Users\dingli\AppData\Local\Temp\tmpfbqq40si\pip.zip\pip\_internal\commands\__init__.py", line 9, in <module>
  File "C:\Users\dingli\AppData\Local\Temp\tmpfbqq40si\pip.zip\pip\_internal\cli\base_command.py", line 15, in <module>
  File "C:\Users\dingli\AppData\Local\Temp\tmpfbqq40si\pip.zip\pip\_internal\cli\cmdoptions.py", line 23, in <module>
  File "C:\Users\dingli\AppData\Local\Temp\tmpfbqq40si\pip.zip\pip\_internal\cli\parser.py", line 12, in <module>
  File "C:\Users\dingli\AppData\Local\Temp\tmpfbqq40si\pip.zip\pip\_internal\configuration.py", line 24, in <module>
  File "C:\Users\dingli\AppData\Local\Temp\tmpfbqq40si\pip.zip\pip\_internal\utils\appdirs.py", line 13, in <module>
  File "C:\Users\dingli\AppData\Local\Temp\tmpfbqq40si\pip.zip\pip\_vendor\platformdirs\__init__.py", line 33, in <module>
  File "C:\Users\dingli\AppData\Local\Temp\tmpfbqq40si\pip.zip\pip\_vendor\platformdirs\__init__.py", line 29, in _set_platform_dir_class
  File "importlib\__init__.py", line 126, in import_module
  File "C:\Users\dingli\AppData\Local\Temp\tmpfbqq40si\pip.zip\pip\_vendor\platformdirs\windows.py", line 3, in <module>
  File "ctypes\__init__.py", line 8, in <module>
ImportError: DLL load failed while importing _ctypes: 找不到指定的模块。
```
</details>

body.md

**Comment by WangHHY19931001** [comment] 2024-03-01 03:18
emm... may be python env configure error

**Comment by JonLiu1993** [comment] 2024-03-01 06:58
duplicate of https://github.com/microsoft/vcpkg/issues/34746

**Closed by JonLiu1993** 2024-03-01 06:58 UTC
Labels: category:port-bug
