### ISSUE TITLE
[imgui] update to 1.83

### ISSUE THREAD

**Issue by IvaOsi** [microsoft/vcpkg#18648] opened 2021-06-25 12:41 UTC
Library name: imgui

New version number: 1.83

Other information that may be useful (release notes, etc...)

Hello! i try to using new version of imgui but see this:

![image](https://user-images.githubusercontent.com/17671542/123426130-af3cb200-d5cb-11eb-92fa-7c91a4cd04ee.png)

i use last version vcpkg:

![image](https://user-images.githubusercontent.com/17671542/123426181-bf549180-d5cb-11eb-92b4-f852df14c1e7.png)

will be cool see new version of imgui 1.83

**Comment by autoantwort** [comment] 2021-06-25 15:17
Duplicate of #18576 it is already at 1.83 -.-

**Comment by IvaOsi** [comment] 2021-06-25 16:34
Sorry but how to use git pull + vcpkg search 
can u explain me

**Comment by IvaOsi** [comment] 2021-06-25 16:38
So i update lib using git pull command

![image](https://user-images.githubusercontent.com/17671542/123457685-d5267e80-d5ec-11eb-88c4-2fb722c021b0.png)

after that i see this:

![image](https://user-images.githubusercontent.com/17671542/123457734-e53e5e00-d5ec-11eb-8651-44ae9ca54ceb.png)

**Comment by autoantwort** [comment] 2021-06-25 16:39
only `git pull`

**Comment by IvaOsi** [comment] 2021-06-25 17:42
it dosnt work

**Comment by autoantwort** [comment] 2021-06-25 23:15
What is the error of `git pull`?

**Comment by NancyLi1013** [comment] 2021-06-28 07:16
Hi @IvaOsi 

Thanks for posting this issue.

Please help provide the error info after you use `git pull`? Generally, there is no need to delete old ingui, you just need to run `git pull `to update to the latest vcpkg.

@autoantwort 

Thanks again for your help to figure this out.

**Comment by IvaOsi** [comment] 2021-06-30 18:37
I only get this phrase and nothing else:

fatal: refusing to merge unrelated histories

**Comment by autoantwort** [comment] 2021-06-30 19:10
Then do `git clone https://github.com/microsoft/vcpkg` to get a new clean non broken copy of vcpkg

**Comment by IvaOsi** [comment] 2021-06-30 19:55
> Then do `git clone https://github.com/microsoft/vcpkg` to get a new clean non broken copy of vcpkg

sry for noob question but i need did it in vcpkg dir or create new dir?

**Comment by autoantwort** [comment] 2021-06-30 20:11
I would remove the existing vcpkg dir and then do it in the parent folder

**Comment by NancyLi1013** [comment] 2021-08-03 10:15
> I only get this phrase and nothing else:
> ` fatal: refusing to merge unrelated histories`

Please refer to [this](https://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories-on-rebase).

Is this still a problem for you now? @IvaOsi

**Comment by IvaOsi** [comment] 2021-08-03 11:19
> > I only get this phrase and nothing else:
> > ` fatal: refusing to merge unrelated histories`
> 
> Please refer to [this](https://stackoverflow.com/questions/37937984/git-refusing-to-merge-unrelated-histories-on-rebase).
> 
> Is this still a problem for you now? @IvaOsi

No, just update vcpkg

**Comment by NancyLi1013** [comment] 2021-08-04 01:39
Thanks for your feedback. Closing this issue for now.

**Closed by NancyLi1013** 2021-08-04 01:39 UTC
Labels: category:question
