### ISSUE TITLE
[hyperscan:x64-linux] build failure

### ISSUE THREAD

**Issue by kreuzerkrieg** [microsoft/vcpkg#10181] opened 2020-02-23 08:46 UTC
> ./vcpkg install hyperscan
> Computing installation plan...
> The following packages will be built and installed:
>     hyperscan[core]:x64-linux
> Starting package 1/1: hyperscan:x64-linux
> Building package hyperscan[core]:x64-linux...
> -- Using cached /home/user/Development/vcpkg/downloads/intel-hyperscan-v5.1.0.tar.gz
> -- Using source at /home/user/Development/vcpkg/buildtrees/hyperscan/src/v5.1.0-e80f138a71
> -- Configuring x64-linux-dbg
> CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:72 (message):
>     Command failed: /home/user/Development/vcpkg/downloads/tools/cmake-3.14.0-linux/cmake-3.14.0-Linux-x86_64/bin/cmake /home/user/Development/vcpkg/buildtrees/hyperscan/src/v5.1.0-e80f138a71 -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja -DCMAKE_SYSTEM_NAME=Linux -DBUILD_SHARED_LIBS=OFF -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=/home/user/Development/vcpkg/scripts/toolchains/linux.cmake -DVCPKG_TARGET_TRIPLET=x64-linux -DVCPKG_SET_CHARSET_FLAG=ON -DVCPKG_PLATFORM_TOOLSET=external -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON -DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON -DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE -DCMAKE_VERBOSE_MAKEFILE=ON -DVCPKG_APPLOCAL_DEPS=OFF -DCMAKE_TOOLCHAIN_FILE=/home/user/Development/vcpkg/scripts/buildsystems/vcpkg.cmake -DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON -DVCPKG_CXX_FLAGS= -DVCPKG_CXX_FLAGS_RELEASE= -DVCPKG_CXX_FLAGS_DEBUG= -DVCPKG_C_FLAGS= -DVCPKG_C_FLAGS_RELEASE= -DVCPKG_C_FLAGS_DEBUG= -DVCPKG_CRT_LINKAGE=dynamic -DVCPKG_LINKER_FLAGS= -DVCPKG_TARGET_ARCHITECTURE=x64 -DCMAKE_INSTALL_LIBDIR:STRING=lib -DCMAKE_INSTALL_BINDIR:STRING=bin -G Ninja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/home/user/Development/vcpkg/packages/hyperscan_x64-linux/debug
>     Working Directory: /home/user/Development/vcpkg/buildtrees/hyperscan/x64-linux-dbg
>     Error code: 1
>     See logs for more information:
>       /home/user/Development/vcpkg/buildtrees/hyperscan/config-x64-linux-dbg-out.log
>       /home/user/Development/vcpkg/buildtrees/hyperscan/config-x64-linux-dbg-err.log
> 
> Call Stack (most recent call first):
>   scripts/cmake/vcpkg_configure_cmake.cmake:304 (vcpkg_execute_required_process)
>   ports/hyperscan/portfile.cmake:17 (vcpkg_configure_cmake)
>   scripts/ports.cmake:90 (include)
> 
> 
> Error: Building package hyperscan:x64-linux failed with: BUILD_FAILED
> Please ensure you're using the latest portfiles with `.\vcpkg update`, then
> submit an issue at https://github.com/Microsoft/vcpkg/issues including:
>   Package: hyperscan:x64-linux
>   Vcpkg version: 2020.02.04-unknownhash
> 
> Additionally, attach any relevant sections from the log files above.

The build fails with inability to detect avx2/sse
/home/user/Development/vcpkg/buildtrees/hyperscan/config-x64-linux-dbg-out.log contains following

> -- The C compiler identification is GNU 9.2.1
> -- The CXX compiler identification is GNU 9.2.1
> -- Check for working C compiler: /usr/lib/ccache/cc
> -- Check for working C compiler: /usr/lib/ccache/cc -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/lib/ccache/c++
> -- Check for working CXX compiler: /usr/lib/ccache/c++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- Performing Test ARCH_64_BIT
> -- Performing Test ARCH_64_BIT - Success
> -- Performing Test ARCH_32_BIT
> -- Performing Test ARCH_32_BIT - Failed
> -- Build type DEBUG
> -- Boost version: 1.72.0
> -- Found PythonInterp: /usr/bin/python (found version "2.7.17") 
> -- Build date: 2020-02-23
> -- gcc version 9.2.1
> -- g++ version 9.2.1
> -- Looking for include file unistd.h
> -- Looking for include file unistd.h - found
> -- Looking for include file intrin.h
> -- Looking for include file intrin.h - not found
> -- Looking for C++ include intrin.h
> -- Looking for C++ include intrin.h - not found
> -- Looking for include file x86intrin.h
> -- Looking for include file x86intrin.h - found
> -- Looking for C++ include x86intrin.h
> -- Looking for C++ include x86intrin.h - found
> -- Looking for posix_memalign
> -- Looking for posix_memalign - found
> -- Looking for _aligned_malloc
> -- Looking for _aligned_malloc - not found
> -- Performing Test HAS_C_HIDDEN
> -- Performing Test HAS_C_HIDDEN - Success
> -- Performing Test HAS_CXX_HIDDEN
> -- Performing Test HAS_CXX_HIDDEN - Success
> -- Looking for _LIBCPP_VERSION
> -- Looking for _LIBCPP_VERSION - not found
> -- generator is Ninja
> -- Performing Test HAS_C_ATTR_IFUNC
> -- Performing Test HAS_C_ATTR_IFUNC - Success
> **-- Performing Test HAVE_SSSE3
> -- Performing Test HAVE_SSSE3 - Failed
> -- Performing Test HAVE_AVX2
> -- Performing Test HAVE_AVX2 - Failed
> -- Performing Test HAVE_AVX512
> -- Performing Test HAVE_AVX512 - Failed**
> -- Building without AVX2 support
> -- Building without AVX512 support
> -- Configuring incomplete, errors occurred!
> 

config-x64-linux-dbg-err.log contains

> CMake Error at CMakeLists.txt:204 (message):
>   Something went wrong determining gcc tune: -mtune=option: not valid
> 
> 
> CMake Error at cmake/arch.cmake:79 (message):
>   A minimum of SSSE3 compiler support is required
> Call Stack (most recent call first):
>   CMakeLists.txt:334 (include)

I've tried to build the original library `master` branch and it works as expected

**Comment by LilyWangL** [comment] 2020-02-27 08:34
Hi @kreuzerkrieg, thanks for posting this issue. I can't reproduce this issue locally. I installed hyperscan successfully on Linux 18.04.2 with the latest VCPKG. My gcc version is 7.4.0. Did you do some changes before building hyperscan?

**Comment by kreuzerkrieg** [comment] 2020-02-27 09:37
it is dev machine, things definitely were done to it, like installing stuff which may affect the behavior. Worth to mention there is gcc/7/8/9 install and clang from ubuntu stock version to clang 11 devel

**Comment by kreuzerkrieg** [comment] 2020-02-27 11:02
The same behavior is confirmed on "clean" machine
dpkg install log available [here](https://1drv.ms/u/s!AvKB-sqTwjdHhp9bXyP3kaaN9fjdUA?e=pjZuLA)
Date of interest from 24 Feb and later
I bet on gcc 9.2

**Comment by LilyWangL** [comment] 2020-03-05 02:05
Thanks for posting this issue. This issue has been fixed, so I am closing this issue for now.

**Closed by LilyWangL** 2020-03-05 02:05 UTC
Labels: needs-repro
