### ISSUE TITLE
[cfitsio] read data file failed

### ISSUE THREAD

**Issue by songlm2005** [microsoft/vcpkg#24560] opened 2022-05-05 15:09 UTC
Please create a discussion in https://github.com/microsoft/vcpkg/discussions/new instead.

**Comment by songlm2005** [comment] 2022-05-05 15:18
When I read the fits file with fitsio, 
df2 = FITS(“F:/Julia-work/HEB200227305_HE-Evt.fits”)
the output information:ERROR: LoadError: BitArray (‘X’) columns not yet supported
Stacktrace:
[1] error(::String) at .\error.jl:33
[2] fits_get_col_info at C:\Users\hp.juliapro\JuliaPro_v1.4.0-1\packages\FITSIO\BavHZ\src\table.jl:44 [inlined]
[3] show(::Base.TTY, ::TableHDU) at C:\Users\hp.juliapro\JuliaPro_v1.4.0-1\packages\FITSIO\BavHZ\src\table.jl:197
[4] print(::Base.TTY, ::TableHDU) at .\strings\io.jl:35
[5] print(::Base.TTY, ::TableHDU, ::Char) at .\strings\io.jl:46
[6] println(::Base.TTY, ::TableHDU) at .\strings\io.jl:73
[7] println(::TableHDU) at .\coreio.jl:4
[8] top-level scope at F:\Julia-work\readfits.jl:33
in expression starting at F:\Julia-work\readfits.jl:33

I check the fits file with fv,
![](https://discourse.juliacn.com/uploads/default/original/2X/9/9dbe2db9e8ea41293cf8427b9d4e916ebacc2e51.png)
I guess the error maybe caused by ACD column. So I deleted this column, then read the new fits file again. the output is OK. 
My question is: how get the content of ACD column?

**Comment by FrankXie05** [comment] 2022-05-06 02:44
@songlm2005 This is not an issue with vcpkg, for `Julia` they are improving their features and you should submit an issue with them instead of vcpkg. I'm going to close it because we can't provide any help, sorry. :)
https://github.com/JuliaAstro/FITSIO.jl/issues

**Comment by JackBoosY** [comment] 2022-05-07 06:20
I'm not familiar with cfitsio, can you please double confirm your data file runs successfully with the official build?

**Comment by songlm2005** [comment] 2022-05-07 07:01
Thanks for your attention.
The fits file is the observation data of Chinese astronomy satellite Insight-HXMT. I could get the correct contents of the file use the C++ routine call CFITSIO lib directly.So I think the format of the file is in accord with FITSIO standard.

**Comment by JackBoosY** [comment] 2022-05-07 07:03
Can you please provide a sample project to reproduce this issue?

Thanks.

**Comment by songlm2005** [comment] 2022-05-07 07:21
for julia, the version is 1.4.1, FITSIO is v0.16.12 .

**Comment by JackBoosY** [comment] 2022-05-07 08:00
@songlm2005 Please provide the complete sample project, including source code and data files, so that we can reproduce this issue.

**Comment by FrankXie05** [comment] 2022-06-24 01:57
We don't have enough information to solve this issue, unfortunately; if you have any more information to help us solve this, please reopen!

**Closed by FrankXie05** 2022-06-24 01:57 UTC
Labels: requires:more-information
