### ISSUE TITLE
[liblzma] Build error on x64-windows

### ISSUE THREAD

**Issue by RevengeSpeed** [microsoft/vcpkg#37937] opened 2024-04-03 04:23 UTC
este es el error que se me presenta alguien me podria ayudar? 
C:\Users\Victor>.\vcpkg\vcpkg install libxml2:x64-windows
Computing installation plan...
The following packages will be built and installed:
  * liblzma:x64-windows@5.4.4
    libxml2[core,iconv,lzma,zlib]:x64-windows@2.11.7
  * zlib:x64-windows@1.3.1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.39.33519/bin/Hostx64/x64/cl.exeRestored 0 package(s) from C:\Users\Victor\AppData\Local\vcpkg\archives in 382 us. Use --debug to see more details.
Installing 1/3 liblzma:x64-windows@5.4.4...
Building liblzma:x64-windows@5.4.4...
-- Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz -> tukaani-project-xz-v5.4.4.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\Users\Victor\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\Users\Victor\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Metrics enabled.
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
Downloading https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz
[DEBUG] Trying to hash C:\Users\Victor\vcpkg\downloads\tukaani-project-xz-v5.4.4.tar.gz.8836.part
[DEBUG] C:\Users\Victor\vcpkg\downloads\tukaani-project-xz-v5.4.4.tar.gz.8836.part has hash b169eb5dcd74e14477bc98c5c898f5404f937b582afaa86f3cd18c70b6cce034cf76b61b138b6f352995bca59bb35699cebf867cc5cc355e4f0f097fd4661b70
error: Failed to download from mirror set
error: File does not have the expected hash:
url: https://github.com/tukaani-project/xz/archive/v5.4.4.tar.gz
File: C:\Users\Victor\vcpkg\downloads\tukaani-project-xz-v5.4.4.tar.gz.8836.part
Expected hash: c28461123562564e030f3f733f078bc4c840e87598d9f4b718d4bca639120d8133f969c45d7bdc62f33f081d789ec0f14a1791fb7da18515682bfe3c0c7362e0
Actual hash: b169eb5dcd74e14477bc98c5c898f5404f937b582afaa86f3cd18c70b6cce034cf76b61b138b6f352995bca59bb35699cebf867cc5cc355e4f0f097fd4661b70
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1031):
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 4us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 1861us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 840 ms (818555us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):

      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:

      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.

      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.

      3. Your proxy's remote server is out of service.

      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/liblzma/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:175 (include)

error: building liblzma:x64-windows failed with: BUILD_FAILED
Elapsed time to handle liblzma:x64-windows: 957 ms
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+liblzma
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[liblzma]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2FUsers%2FVictor%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

**Comment by MonicaLiu0311** [comment] 2024-04-03 06:01
Duplicate of https://github.com/microsoft/vcpkg/issues/37893

**Closed by MonicaLiu0311** 2024-04-03 06:01 UTC
Labels: depends:upstream-changes
