### ISSUE TITLE
Colmap build fail VS2022 colmap[core,cuda]:x64-windows@2023-10-01

### ISSUE THREAD

**Issue by mbernier-arcturus** [microsoft/vcpkg#38773] opened 2024-05-16 20:59 UTC
I cannot build Colmap using VS2022 with `.\bootstrap-vcpkg.bat` and `.\vcpkg install colmap[cuda]:x64-windows`

I get the following error:

```
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: C:/Users/berm2/git/vcpkg/downloads/tools/cmake-3.29.2-windows/cmake-3.29.2-windows-i386/bin/cmake.exe --build . --config Debug --target install -- -v -j25
```
And the log:

```
[53/210] C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1439~1.335\bin\Hostx64\x64\cl.exe   /TP -DBOOST_ATOMIC_DYN_LINK -DBOOST_ATOMIC_NO_LIB -DBOOST_CHRONO_DYN_LINK -DBOOST_CHRONO_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_CONTAINER_NO_LIB -DBOOST_DATE_TIME_DYN_LINK -DBOOST_DATE_TIME_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK=1 -DBOOST_FILESYSTEM_NO_LIB -DBOOST_GRAPH_DYN_LINK -DBOOST_GRAPH_NO_LIB -DBOOST_RANDOM_DYN_LINK -DBOOST_RANDOM_NO_LIB -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_SERIALIZATION_NO_LIB -DBOOST_THREAD_DYN_LINK -DBOOST_THREAD_NO_LIB -DBOOST_THREAD_USE_DLL -DCOLMAP_CGAL_ENABLED -DCOLMAP_CUDA_ENABLED -DCOLMAP_GPU_ENABLED -DCOLMAP_GUI_ENABLED -DCOLMAP_OPENGL_ENABLED -DCOLMAP_OPENMP_ENABLED -DEIGEN_INITIALIZE_MATRICES_BY_NAN -DGFLAGS_IS_A_DLL=1 -DGLOG_NO_ABBREVIATED_SEVERITIES -DGLOG_USE_GFLAGS -DGLOG_USE_GLOG_EXPORT -DGL_GLEXT_PROTOTYPES -DIMATH_DLL -DNOMINMAX -DOPENEXR_DLL -DQT_CORE_LIB -DQT_GUI_LIB -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DWIN32_LEAN_AND_MEAN -D_MWAITXINTRIN_H_INCLUDED -IC:\Users\berm2\git\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include\eigen3 -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include\qt5 -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include\qt5\QtCore -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\tools\qt5\mkspecs\win32-msvc -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include\qt5\QtOpenGL -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include\qt5\QtWidgets -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include\qt5\QtGui -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include\openjpeg-2.5 -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include\webp -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include\OpenEXR -external:IC:\Users\berm2\git\vcpkg\installed\x64-windows\include\Imath -external:W0 /nologo /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /EHsc /MP /bigobj /W3 /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1  -std:c++14 /Zc:__cplusplus /EHsc /showIncludes /Fosrc\colmap\estimators\CMakeFiles\colmap_estimators.dir\absolute_pose.cc.obj /Fdsrc\colmap\estimators\CMakeFiles\colmap_estimators.dir\colmap_estimators.pdb /FS -c C:\Users\berm2\git\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src\colmap\estimators\absolute_pose.cc
C:\Users\berm2\git\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src\colmap\estimators\absolute_pose.cc(256): warning C4244: 'argument': conversion from 'unsigned __int64' to 'const double', possible loss of data
C:\Users\berm2\git\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src\colmap\estimators\absolute_pose.cc(548): warning C4244: 'argument': conversion from 'unsigned __int64' to 'const double', possible loss of data
C:\Users\berm2\git\vcpkg\buildtrees\colmap\src\f69e5aa28f-361efbb7b2.clean\src\colmap\estimators\absolute_pose.cc(549): warning C4244: 'argument': conversion from 'unsigned __int64' to 'const double', possible loss of data
ninja: build stopped: subcommand failed.
```

**Comment by MonicaLiu0311** [comment] 2024-05-17 02:03
Duplicate of #38774.

**Closed by MonicaLiu0311** 2024-05-17 02:03 UTC
Labels: category:question
