### ISSUE TITLE
[<v8:x64-windows>] build failure

### ISSUE THREAD

**Issue by folklore212** [microsoft/vcpkg#38380] opened 2024-04-24 06:15 UTC
### Operating system

Windows 10 Profession 10.0.19045

### Compiler

MSVC 

### Steps to reproduce the behavior

```Shell
'./vspkg install v8:x64-windows'
```

### Failure logs

-- Found external ninja('1.11.0').
-- Using cached msys2-pkgconf-2.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.026-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.45-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.10-1-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-2.1.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.10-4-x86_64.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.22.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.3.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-13.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.6-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.5-1-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.3.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.010-1-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-4-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-2-x86_64.pkg.tar.zst.
-- Using msys root at C:/vcpkg/downloads/tools/msys2/65b7e009c675ae7a
-- Using cached C:/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Cleaning sources at C:/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/v8-7d3d62c91f69a702e5aa54c6b4dbbaa883683717.tar.gz
-- Applying patch C:/vcpkg/ports/v8/v8.patch
-- Using source at C:/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean
-- Fetching submodules
-- Generating v8 build files. Please wait...
-- Generating build (x64-windows-dbg)...
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/vcpkg/installed/x64-windows/tools/gn/gn.exe gen C:/vcpkg/buildtrees/v8/x64-windows-dbg "--args=is_component_build=true target_cpu=\"x64\" v8_monolithic=false v8_use_external_startup_data=true use_sysroot=false is_clang=false use_custom_libcxx=false v8_enable_verify_heap=false icu_use_data_file=false is_debug=true enable_iterator_debugging=true pkg_config_libdir=\"/c/vcpkg/installed/x64-windows/debug/lib/pkgconfig\""
    Working Directory: C:/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\v8\generate-x64-windows-dbg-out.log
      C:\vcpkg\buildtrees\v8\generate-x64-windows-dbg-err.log

Call Stack (most recent call first):
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:10 (vcpkg_execute_required_process)
  installed/x64-windows/share/vcpkg-gn/vcpkg_gn_configure.cmake:34 (z_vcpkg_gn_configure_generate)
  ports/v8/portfile.cmake:150 (vcpkg_gn_configure)
  scripts/ports.cmake:175 (include)

error: building v8:x64-windows failed with: BUILD_FAILED
Elapsed time to handle v8:x64-windows: 1.5 min
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+v8
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[v8]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md

### Additional context

ERROR at //build/config/win/visual_studio_version.gni:27:7: Script returned non-zero exit code.
      exec_script("../../vs_toolchain.py", [ "get_toolchain_dir" ], "scope")
      ^----------
Current dir: C:/vcpkg/buildtrees/v8/x64-windows-dbg/
Command: C:/vcpkg/downloads/tools/python/python-3.11.8-x64/python.exe C:/vcpkg/buildtrees/v8/src/a883683717-d6c82ef7bb.clean/build/vs_toolchain.py get_toolchain_dir
Returned 1.
See //build/toolchain/win/BUILD.gn:8:1: whence it was imported.
import("//build/config/win/visual_studio_version.gni")
^----------------------------------------------------
See //BUILD.gn:1195:1: which caused the file to be included.
action("postmortem-metadata") {
^------------------------------

**Comment by MonicaLiu0311** [comment] 2024-04-24 07:17
Duplicate of #36716.

**Closed** 2024-04-24 07:18 UTC
Labels: category:port-bug
